# 05 — Market State Features

## Notebook purpose

This notebook constructs the V0.1 causal market-state feature interface from the verified outputs of Notebooks 00, 02, 03, and 04.

Its primary task is:

> Produce one auditable pre-batch market-state observation for every authoritative Notebook 04 scoring batch, using only information available strictly before that batch, while preserving exact-time simultaneity, event membership, partition authority, delayed-mark availability, and upstream artifact identity.

The resulting batch-level features, event-level feature projection, delayed-mark activation ledger, and physically separate future-label tables become the authorized inputs for Notebook 06 point-process baseline estimation.

This notebook must not infer upstream paths, schemas, hash conventions, row counts, or authority rules from naming conventions. Every required input must be resolved and interpreted through the actual producing manifests, handoffs, contracts, sidecars, registries, and persisted table schemas.

---

## Current V0.1 stage

**Project:** The Clown Project  
**Pipeline:** V0.1 causal market-data reconstruction and event-stream pipeline  
**Notebook:** `05_MARKET_STATE_FEATURES.ipynb`  
**Previous notebook:** `04_EVENT_STREAM_CONSTRUCTION.ipynb`  
**Next notebook:** `06_POINT_PROCESS_BASELINES.ipynb`

**Source run prefix:** `BTCUSDT_spot_20260710T063746Z_c8b5bf12`  
**V0.1 run ID:** `v0_1_20260714T090616Z_e82325081a81`  
**Operating mode:** `ENGINEERING_REPRODUCTION_MODE`  
**Canonical timezone:** UTC  
**Primary ordering authority:** `collector_sequence`  
**Primary alignment authority:** `LOCAL_STRICT`  
**Primary event representation:** `SAME_MS_SAME_SIDE_BURSTS`  
**Primary event time:** `event_time_ns`  
**Primary event partition:** `event_partition`  
**Timestamp interface:** `SIMULTANEOUS_EVENT_BATCH_REQUIRED`  
**Initial status:** `NOT EVALUATED`

---

## Frozen Notebook 04 authority

Notebook 04 is authoritative for:

- the selected primary-event definition;
- primary-event identities;
- exact-time scoring-batch identities;
- event-to-batch membership;
- trade-to-event membership;
- event partitions;
- observation windows;
- simultaneous-event semantics;
- aggregate-mark availability times;
- persisted event and batch table identities.

The authoritative interface contains:

- `13,887` primary events;
- `13,564` scoring batches;
- `67,683` conserved trade prints;
- `249` simultaneous primary-event batches;
- `41` mixed-side primary-event batches;
- `1,575` primary events with aggregate marks unavailable at initiation.

These counts must be independently verified from the persisted Notebook 04 artifacts before feature construction begins.

No Notebook 05 operation may:

- jitter an event timestamp;
- remove an event;
- regroup events independently;
- reinterpret collector sequence as physical elapsed time;
- allow one event in a tied scoring batch to affect another member;
- backdate an aggregate burst mark;
- replace Notebook 04 event partitions with inherited Notebook 03 partitions.

---

## Canonical observational unit

The primary feature-construction unit is one Notebook 04 scoring batch.

Every event sharing the same authoritative batch must be evaluated using one common pre-batch state based on history strictly before the shared batch cutoff.

All pre-batch features must therefore be constructed once at batch level and only then propagated to member events through the verified Notebook 04 event-to-batch membership table.

Every propagated pre-batch feature, missingness field, coverage field, and observability flag must be identical for all events in the same batch.

Current-batch multiplicity, side composition, quantity, notional, and other outcomes are not pre-batch information.

---

## Information-time classes

Notebook 05 must keep four timing classes physically and semantically distinct.

### Pre-batch state: `t-`

Information that was causally observable before the scoring batch.

Permitted sources include:

- the latest eligible visible-book state;
- earlier primary events and batches;
- earlier visible-book updates;
- previously activated aggregate marks;
- earlier midpoint, weighted-midpoint, spread, depth, and order-flow changes.

The current scoring batch is excluded.

### Post-batch context: `t+`

Information known only after the current batch has occurred.

Examples include:

- current-batch event multiplicity;
- current-batch buy and sell composition;
- current-batch constituent-print count;
- current-batch aggregate quantity and notional.

These fields must be stored separately and may not enter the current batch’s feature vector.

### Delayed aggregate marks

Aggregate quantity, notional, VWAP, print count, and similar burst marks may enter history only after their persisted `aggregate_mark_available_time_ns`.

A mark with availability time equal to a scoring-batch time remains unavailable to that batch.

### Future labels

All outcomes measured after the scoring batch must be written to separate label artifacts.

No future label, future target timestamp, future realization state, or future-derived statistic may appear in an authoritative feature table.

---

## Required upstream authority

Notebook 05 must verify and consume the actual persisted outputs of:

### Notebook 00

- run identity and source authority;
- source registry and run configuration;
- chronological split contract;
- market-data and timestamp contracts;
- missing-data and rejection rules;
- downstream partition-access rules.

Notebook 00 artifacts must be resolved through the actual Notebook 00 output manifest.

No conventional configuration path may be assumed.

### Notebook 02

- reconstructed visible-book state table;
- top-ten visible-book representation;
- required reconstruction diagnostics and quality gates;
- Notebook 02 manifest and handoff.

Notebook 02 is authoritative for visible market-by-price state and book-update history.

### Notebook 03

- LOCAL_STRICT matched trade-book table;
- alignment diagnostics and lag fields;
- Notebook 03 manifest and handoff.

Notebook 03 is authoritative for causal trade-to-book alignment.

Its inherited partition fields remain diagnostic only.

### Notebook 04

- primary event table;
- exact-time batch table;
- scoring-batch table;
- event-to-batch membership;
- trade membership;
- observation-window contract;
- event-array index and required array identities;
- event-definition contract;
- persistence contract;
- output manifest;
- final acceptance report;
- Notebook 04-to-Notebook 05 handoff.

Notebook 04’s handoff is the primary path authority for Notebook 05 event-stream inputs.

Its manifest and sidecars are the authority for schemas, row counts, raw-file hashes, semantic table hashes, and read-back identities.

---

## Artifact-verification principle

Notebook 05 must interpret every upstream artifact according to its actual persisted structure.

It must distinguish between:

- enveloped JSON documents;
- flat JSON documents;
- exact raw-file SHA-256 hashes;
- canonical JSON payload SHA-256 hashes;
- canonical table or array payload hashes;
- artifact-specific self-hash fields;
- hashes that reference another artifact.

No universal JSON envelope, self-hash name, or artifact parser may be assumed.

A hash ending in `_sha256` is not automatically the self-hash of the document containing it.

An artifact may be used only after its:

- path authority;
- document structure;
- producing notebook;
- run identity;
- acceptance status;
- raw-file identity;
- semantic payload identity;
- schema;
- row count;
- read-back integrity

have been verified under the correct artifact-specific convention.

---

## Common visible-book rule

Each scoring batch must receive one common visible-book state that was available before every member event.

Eligibility must respect both:

- local receipt time;
- collector sequence.

The selected state must precede the batch’s minimum initiating trade collector sequence.

A same-local-timestamp book state may be eligible only when its collector sequence is strictly earlier than the minimum initiating sequence of the batch.

The selected state must be the latest eligible accepted Notebook 02 state.

A valid earlier-partition book state may initialize a later-partition batch and must be explicitly flagged as cross-partition causal history.

A later-partition state is forbidden.

Failure to find an eligible state must preserve the batch row with an explicit missing reason. The batch may not be removed.

---

## Feature scope

Notebook 05 is authorized to construct causal features covering:

- static visible-book state;
- spread and price state;
- top-one through top-ten visible depth;
- queue and depth imbalance;
- book concentration and shape;
- adjacent-level price gaps;
- weighted midpoint or microprice;
- prior BUY and SELL event flow;
- prior simultaneous-batch activity;
- activated quantity, notional, and print-flow state;
- visible-book update flow;
- level-one order-flow imbalance;
- optional audited multi-level order-flow imbalance;
- midpoint and weighted-midpoint movement;
- realized variation and volatility;
- observability, lag, staleness, coverage, and warm-up controls.

Feature definitions, rolling windows, units, valid ranges, missingness rules, and partition behavior must be frozen before predictive results are examined.

---

## Partition and warm-up rules

Notebook 00’s chronological split contract remains authoritative.

Earlier-partition history may initialize a later partition when it is genuinely causal.

Information may never flow backward from a later partition.

Insufficient history must remain missing with an explicit reason and coverage record.

It must never be encoded as a genuine zero.

VALIDATION and ENGINEERING_HOLDOUT may not determine:

- feature definitions;
- feature inclusion;
- rolling-window sizes;
- normalization rules;
- clipping rules;
- missing-value treatment;
- label horizons.

Future labels must not cross an authoritative partition boundary.

Rows too close to a partition end must be right-censored with an explicit missing-label reason.

---

## Required outputs

Notebook 05 must persist and verify:

- feature-construction contract;
- feature-definition manifest;
- rolling-window contract;
- common pre-batch book mapping;
- authoritative batch-level pre-batch feature table;
- authoritative event-level feature projection;
- delayed aggregate-mark activation ledger;
- post-batch diagnostic context table;
- physically separate batch future-label table;
- optional event-level future-label projection;
- history-coverage and warm-up records;
- upstream-authority audit;
- conservation and membership audits;
- causal-book-selection audit;
- strict-history and delayed-mark leakage audits;
- partition-boundary audit;
- finite-value, range, and missingness audits;
- algebraic-redundancy audit;
- future-label separation audit;
- V0.0 reconciliation outputs;
- Notebook 05 output manifest;
- Notebook 05 final acceptance report;
- controlled Notebook 05-to-Notebook 06 handoff.

Exact paths and filenames must be generated through the verified V0.1 output authority and recorded in the completed Notebook 05 manifest.

Every authoritative persisted table must be read back and verified for:

- schema;
- column order;
- row order;
- row count;
- raw-file checksum;
- canonical table identity.

---

## Acceptance gate

Notebook 05 may pass only if:

- all required upstream authority is verified;
- all `13,564` scoring batches are preserved exactly once;
- all `13,887` primary events are preserved exactly once;
- all `67,683` trades remain conserved through membership;
- every event maps to exactly one scoring batch;
- one valid common pre-batch state or explicit missing-state record exists per batch;
- all pre-batch event projections are invariant within batch;
- no current-batch event enters its own history;
- no same-time event affects another tied event;
- no post-cutoff book state is selected;
- no delayed mark is backdated;
- no later-partition information enters an earlier partition;
- insufficient history is never represented as zero;
- no future label appears in a feature artifact;
- no V0.0 artifact substitutes for a V0.1 reconstruction;
- every authoritative output passes persistence and read-back verification.

Any violation of authority, conservation, causal timing, partition isolation, delayed-mark timing, feature-label separation, or persistence integrity is a blocking failure.

---

## Scope limitation

This notebook does not authorize or perform:

- Poisson estimation;
- Hawkes estimation;
- Hawkes residual diagnostics;
- Hawkes superiority claims;
- state-dependent Hawkes estimation;
- quote construction;
- queue-position inference;
- fill simulation;
- latency-sensitive execution simulation;
- inventory management;
- fee modeling;
- cash or P&L calculation;
- Sharpe-ratio or drawdown evaluation;
- market-making strategy evaluation;
- paper trading;
- live deployment.

A successful terminal status authorizes only:

1. the verified causal market-state feature interface;
2. the separate future-label interface;
3. the controlled start of Notebook 06.

In [1]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 02 — Imports, fixed notebook identity, frozen upstream
#           authority, bootstrap control paths, and run record
# ============================================================

from __future__ import annotations

import hashlib
import json
import math
import os
import platform
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from types import MappingProxyType
from typing import Any, Final, Iterable, Mapping, Sequence

import numpy as np
import pandas as pd
from IPython.display import display


# ------------------------------------------------------------
# Display and pandas behavior
# ------------------------------------------------------------

pd.set_option("display.max_columns", 260)
pd.set_option("display.max_rows", 120)
pd.set_option("display.width", 240)
pd.set_option("display.max_colwidth", 200)

try:
    pd.options.mode.copy_on_write = True
except Exception:
    pass


# ------------------------------------------------------------
# Fixed notebook identity
# ------------------------------------------------------------

PROJECT_NAME: Final[str] = "The Clown Project"
PIPELINE_VERSION: Final[str] = "V0.1"

NOTEBOOK_NUMBER: Final[str] = "05"
NOTEBOOK_NAME: Final[str] = "05_MARKET_STATE_FEATURES"
NOTEBOOK_FILENAME: Final[str] = f"{NOTEBOOK_NAME}.ipynb"
NOTEBOOK_SCHEMA_VERSION: Final[str] = "v0.1.0"

PREVIOUS_NOTEBOOK_NAME: Final[str] = (
    "04_EVENT_STREAM_CONSTRUCTION"
)
NEXT_NOTEBOOK_NAME: Final[str] = (
    "06_POINT_PROCESS_BASELINES"
)

NOTEBOOK_PURPOSE: Final[str] = (
    "Construct verified causal pre-batch market-state features "
    "and physically separate future labels"
)

INITIAL_STATUS: Final[str] = "NOT EVALUATED"
OPERATING_MODE: Final[str] = "ENGINEERING_REPRODUCTION_MODE"


# ------------------------------------------------------------
# Frozen run identity
# ------------------------------------------------------------

SOURCE_RUN_PREFIX: Final[str] = (
    "BTCUSDT_spot_20260710T063746Z_c8b5bf12"
)

V01_RUN_ID: Final[str] = (
    "v0_1_20260714T090616Z_e82325081a81"
)

COMBINED_PREFIX: Final[str] = (
    f"{SOURCE_RUN_PREFIX}__{V01_RUN_ID}"
)

SYMBOL: Final[str] = "BTCUSDT"
CANONICAL_TIMEZONE: Final[str] = "UTC"
PRIMARY_ORDERING_AUTHORITY: Final[str] = "collector_sequence"
PRIMARY_ALIGNMENT_POLICY: Final[str] = "LOCAL_STRICT"
INTERVAL_CONVENTION: Final[str] = "[start, end)"


# ------------------------------------------------------------
# Frozen run hashes
# ------------------------------------------------------------

EXPECTED_SOURCE_SET_SHA256: Final[str] = (
    "132c83531eec615d279408b5c06f402973114ba3058dfadd2fe58e2e67184c4b"
)

EXPECTED_RUN_CONFIG_SHA256: Final[str] = (
    "14aea0efb3c7b6a193b8c4575a440babe8265d2935c6a770bee995f688d59617"
)

EXPECTED_RUN_IDENTITY_SHA256: Final[str] = (
    "5eb89cf073c036d70e3767df4b35ace7c31822e52e9b9df19204c42e37fe4198"
)


# ------------------------------------------------------------
# Frozen upstream control-artifact hashes
#
# The hash type is intentionally encoded in each variable name.
# No later cell may treat these as one universal hash class.
# ------------------------------------------------------------

EXPECTED_NOTEBOOK_00_MANIFEST_FILE_SHA256: Final[str] = (
    "e12966301d92e61656715f2a6d397786820de836d8156dd70092250619cbb00e"
)

EXPECTED_NOTEBOOK_02_MANIFEST_FILE_SHA256: Final[str] = (
    "0150ed8386326d30017ed892d82a8980f9c8a3d9ba13fb0e7bc2d01d055a2f8e"
)

EXPECTED_NOTEBOOK_02_TO_03_HANDOFF_PAYLOAD_SHA256: Final[str] = (
    "b13e9c47c46e13cb698aff5497b3cbd12f0e0030368fa755f260a7ee3ed8fe76"
)

EXPECTED_NOTEBOOK_03_MANIFEST_FILE_SHA256: Final[str] = (
    "4daa7fa17c2f953e3b931b607e1b5b066f4e29e7dea7397d86b3c9e3b77406ca"
)

EXPECTED_NOTEBOOK_03_TO_04_HANDOFF_FILE_SHA256: Final[str] = (
    "6f4d48e4fbb56d9ac80b415b3c0fe6c4625526b555938b846ee2876626b6152e"
)

EXPECTED_NOTEBOOK_04_MANIFEST_PAYLOAD_SHA256: Final[str] = (
    "c8454d2059f1b5e50675aa156e1eabd7762642cbf624065b496bea1edb56ff53"
)

EXPECTED_NOTEBOOK_04_TO_05_HANDOFF_PAYLOAD_SHA256: Final[str] = (
    "f0544516d59fbabc24d1c8ff42063c96e7c6c4b72fcd5cedbd8ef0a2dfc38a28"
)

EXPECTED_NOTEBOOK_04_FINAL_ACCEPTANCE_PAYLOAD_SHA256: Final[str] = (
    "d056dab3330dff3be55ccc4d5a7aa3acf6ba7569712bd3588f3b088d2a1ef8cd"
)


# ------------------------------------------------------------
# Frozen upstream counts
# ------------------------------------------------------------

EXPECTED_RECONSTRUCTED_BOOK_STATES: Final[int] = 35_985
EXPECTED_TOP10_WIDE_ROWS: Final[int] = 35_985
EXPECTED_TOP10_LONG_ROWS: Final[int] = 719_700

EXPECTED_MATCHED_TRADE_ROWS: Final[int] = 67_683
EXPECTED_PRIMARY_EVENT_ROWS: Final[int] = 13_887
EXPECTED_PRIMARY_BATCH_ROWS: Final[int] = 13_564
EXPECTED_TRADE_MEMBERSHIP_ROWS: Final[int] = 67_683

EXPECTED_SIMULTANEOUS_BATCH_COUNT: Final[int] = 249
EXPECTED_MIXED_SIDE_BATCH_COUNT: Final[int] = 41
EXPECTED_DELAYED_AGGREGATE_EVENT_COUNT: Final[int] = 1_575


# ------------------------------------------------------------
# Frozen Notebook 04 semantic authority
# ------------------------------------------------------------

PRIMARY_EVENT_REPRESENTATION: Final[str] = (
    "SAME_MS_SAME_SIDE_BURSTS"
)

PRIMARY_EVENT_TIME_FIELD: Final[str] = "event_time_ns"
PRIMARY_EVENT_PARTITION_FIELD: Final[str] = "event_partition"

PRIMARY_TIMESTAMP_INTERFACE: Final[str] = (
    "SIMULTANEOUS_EVENT_BATCH_REQUIRED"
)

PRIMARY_EVENT_ID_FIELD: Final[str] = "primary_event_id"
PRIMARY_BATCH_ID_FIELD: Final[str] = "primary_event_batch_id"

NO_TIMESTAMP_JITTER_ALLOWED: Final[bool] = True
NO_EVENT_REMOVAL_ALLOWED: Final[bool] = True
ZERO_LAG_WITHIN_BATCH_EXCITATION_ALLOWED: Final[bool] = False
V00_ACCEPTANCE_AUTHORITY_ALLOWED: Final[bool] = False

VALID_AGGRESSOR_SIDES: Final[tuple[str, str]] = (
    "BUY",
    "SELL",
)

SIDE_CODE: Final[Mapping[str, int]] = MappingProxyType(
    {
        "BUY": 1,
        "SELL": -1,
    }
)

PARTITION_ORDER: Final[tuple[str, ...]] = (
    "DEVELOPMENT",
    "CALIBRATION",
    "VALIDATION",
    "ENGINEERING_HOLDOUT",
)

PARTITION_ORDER_MAP: Final[Mapping[str, int]] = MappingProxyType(
    {
        partition: order
        for order, partition in enumerate(
            PARTITION_ORDER,
            start=1,
        )
    }
)


# ------------------------------------------------------------
# Project roots
#
# These roots are explicitly registered in the current project
# authority map. Data-artifact paths are not declared here and
# must later be resolved from verified manifests and handoffs.
# ------------------------------------------------------------

PROJECT_ROOT: Final[Path] = Path(r"D:\Clown Project")
V00_ROOT: Final[Path] = PROJECT_ROOT / "V0.0"
V01_ROOT: Final[Path] = PROJECT_ROOT / "V0.1"

V01_DATA_ROOT: Final[Path] = V01_ROOT / "data"
V01_ARTIFACT_ROOT: Final[Path] = V01_ROOT / "artifacts"
V01_CONFIG_ROOT: Final[Path] = V01_ROOT / "config"

V01_MANIFEST_DIR: Final[Path] = (
    V01_ARTIFACT_ROOT / "manifests"
)

V01_HANDOFF_DIR: Final[Path] = (
    V01_ARTIFACT_ROOT / "handoff"
)

V01_AUDIT_TABLE_DIR: Final[Path] = (
    V01_ARTIFACT_ROOT
    / "audit_tables"
    / NOTEBOOK_NAME
)

V01_RECONCILIATION_DIR: Final[Path] = (
    V01_ARTIFACT_ROOT
    / "reconciliation"
    / NOTEBOOK_NAME
)

V01_DIAGNOSTICS_DIR: Final[Path] = (
    V01_ARTIFACT_ROOT
    / "diagnostics"
    / NOTEBOOK_NAME
)

V01_HANDOFF_OUTPUT_DIR: Final[Path] = V01_HANDOFF_DIR

V01_FEATURE_OUTPUT_DIR: Final[Path] = (
    V01_DATA_ROOT
    / "processed"
    / "market_state_features"
)

V01_LABEL_OUTPUT_DIR: Final[Path] = (
    V01_DATA_ROOT
    / "processed"
    / "market_state_labels"
)


# ------------------------------------------------------------
# Bootstrap control-artifact paths
#
# These are the exact current authority-map locations of the
# upstream control documents. They must still be independently
# verified before any path contained inside them is trusted.
# ------------------------------------------------------------

NOTEBOOK_00_OUTPUT_MANIFEST_PATH: Final[Path] = (
    V01_MANIFEST_DIR
    / (
        f"{COMBINED_PREFIX}"
        "__00_V01_RUN_CONTRACT"
        "__notebook_00_output_manifest.json"
    )
)

NOTEBOOK_02_OUTPUT_MANIFEST_PATH: Final[Path] = (
    V01_MANIFEST_DIR
    / (
        f"{COMBINED_PREFIX}"
        "__02_VISIBLE_BOOK_RECONSTRUCTION"
        "__notebook_02_output_manifest.json"
    )
)

NOTEBOOK_02_TO_03_HANDOFF_PATH: Final[Path] = (
    V01_HANDOFF_DIR
    / (
        f"{COMBINED_PREFIX}"
        "__02_VISIBLE_BOOK_RECONSTRUCTION"
        "__notebook_02_to_notebook_03_handoff.json"
    )
)

NOTEBOOK_03_OUTPUT_MANIFEST_PATH: Final[Path] = (
    V01_MANIFEST_DIR
    / (
        f"{COMBINED_PREFIX}"
        "__03_CAUSAL_TRADE_BOOK_ALIGNMENT"
        "__notebook_03_output_manifest.json"
    )
)

NOTEBOOK_03_TO_04_HANDOFF_PATH: Final[Path] = (
    V01_HANDOFF_DIR
    / (
        f"{COMBINED_PREFIX}"
        "__03_CAUSAL_TRADE_BOOK_ALIGNMENT"
        "__notebook_03_to_notebook_04_handoff.json"
    )
)

NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT_PATH: Final[Path] = (
    V01_MANIFEST_DIR
    / (
        f"{COMBINED_PREFIX}"
        "__04_EVENT_STREAM_CONSTRUCTION"
        "__notebook_04_final_acceptance_report.json"
    )
)

NOTEBOOK_04_OUTPUT_MANIFEST_PATH: Final[Path] = (
    V01_MANIFEST_DIR
    / (
        f"{COMBINED_PREFIX}"
        "__04_EVENT_STREAM_CONSTRUCTION"
        "__notebook_04_output_manifest.json"
    )
)

NOTEBOOK_04_TO_05_HANDOFF_PATH: Final[Path] = (
    V01_HANDOFF_DIR
    / (
        f"{COMBINED_PREFIX}"
        "__04_EVENT_STREAM_CONSTRUCTION"
        "__notebook_04_to_notebook_05_handoff.json"
    )
)


# ------------------------------------------------------------
# General integrity constants
# ------------------------------------------------------------

SHA256_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"^[0-9a-f]{64}$"
)

HASH_CHUNK_SIZE: Final[int] = 8 * 1024 * 1024

NOTEBOOK_STARTED_AT_UTC: Final[str] = (
    datetime.now(timezone.utc).isoformat()
)


# ------------------------------------------------------------
# Runtime record
# ------------------------------------------------------------

runtime_record = {
    "project_name": PROJECT_NAME,
    "pipeline_version": PIPELINE_VERSION,
    "notebook_number": NOTEBOOK_NUMBER,
    "notebook_name": NOTEBOOK_NAME,
    "notebook_filename": NOTEBOOK_FILENAME,
    "notebook_schema_version": NOTEBOOK_SCHEMA_VERSION,
    "notebook_purpose": NOTEBOOK_PURPOSE,
    "previous_notebook": PREVIOUS_NOTEBOOK_NAME,
    "next_notebook": NEXT_NOTEBOOK_NAME,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "v0_1_run_id": V01_RUN_ID,
    "combined_prefix": COMBINED_PREFIX,
    "symbol": SYMBOL,
    "operating_mode": OPERATING_MODE,
    "canonical_timezone": CANONICAL_TIMEZONE,
    "primary_ordering_authority": PRIMARY_ORDERING_AUTHORITY,
    "primary_alignment_policy": PRIMARY_ALIGNMENT_POLICY,
    "primary_event_representation": PRIMARY_EVENT_REPRESENTATION,
    "primary_event_time_field": PRIMARY_EVENT_TIME_FIELD,
    "primary_event_partition_field": PRIMARY_EVENT_PARTITION_FIELD,
    "primary_timestamp_interface": PRIMARY_TIMESTAMP_INTERFACE,
    "initial_status": INITIAL_STATUS,
    "started_at_utc": NOTEBOOK_STARTED_AT_UTC,
    "python_version": sys.version,
    "python_executable": sys.executable,
    "platform": platform.platform(),
    "pandas_version": pd.__version__,
    "numpy_version": np.__version__,
    "working_directory": str(Path.cwd()),
}

runtime_record

{'project_name': 'The Clown Project',
 'pipeline_version': 'V0.1',
 'notebook_number': '05',
 'notebook_name': '05_MARKET_STATE_FEATURES',
 'notebook_filename': '05_MARKET_STATE_FEATURES.ipynb',
 'notebook_schema_version': 'v0.1.0',
 'notebook_purpose': 'Construct verified causal pre-batch market-state features and physically separate future labels',
 'previous_notebook': '04_EVENT_STREAM_CONSTRUCTION',
 'next_notebook': '06_POINT_PROCESS_BASELINES',
 'source_run_prefix': 'BTCUSDT_spot_20260710T063746Z_c8b5bf12',
 'v0_1_run_id': 'v0_1_20260714T090616Z_e82325081a81',
 'combined_prefix': 'BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81',
 'symbol': 'BTCUSDT',
 'operating_mode': 'ENGINEERING_REPRODUCTION_MODE',
 'canonical_timezone': 'UTC',
 'primary_ordering_authority': 'collector_sequence',
 'primary_alignment_policy': 'LOCAL_STRICT',
 'primary_event_representation': 'SAME_MS_SAME_SIDE_BURSTS',
 'primary_event_time_field': 'event_time_ns',
 'primary_event_partition_field': 'event_partition',
 'primary_timestamp_interface': 'SIMULTANEOUS_EVENT_BATCH_REQUIRED',
 'initial_status': 'NOT EVALUATED',
 'started_at_utc': '2026-07-19T09:33:45.800308+00:00',
 'python_version': '3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]',
 'python_executable': 'd:\\Sylva\\sylva\\.venv\\Scripts\\python.exe',
 'platform': 'Windows-10-10.0.26200-SP0',
 'pandas_version': '2.3.3',
 'numpy_version': '2.4.6',
 'working_directory': 'd:\\Clown Project\\V0.1\\Notebooks'}

In [2]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 03 — Output-directory initialization, upstream control
#           artifact discovery, and artifact-specific hash audit
# ============================================================


# ------------------------------------------------------------
# Correctly separate Notebook 04's persisted side code from
# Notebook 05's later signed-flow encoding.
# ------------------------------------------------------------

NOTEBOOK_04_SIDE_CODE: Final[Mapping[str, int]] = MappingProxyType(
    {
        "BUY": 0,
        "SELL": 1,
    }
)

SIGNED_EVENT_SIDE_CODE: Final[Mapping[str, int]] = MappingProxyType(
    {
        "BUY": 1,
        "SELL": -1,
    }
)

# Preserve SIDE_CODE as the actual upstream Notebook 04 mapping.
SIDE_CODE = NOTEBOOK_04_SIDE_CODE


# ------------------------------------------------------------
# Initialize Notebook 05-owned output directories
#
# No path under V0.0 is created or modified.
# ------------------------------------------------------------

NOTEBOOK_05_OUTPUT_DIRECTORIES: Final[tuple[Path, ...]] = (
    V01_FEATURE_OUTPUT_DIR,
    V01_LABEL_OUTPUT_DIR,
    V01_MANIFEST_DIR,
    V01_HANDOFF_OUTPUT_DIR,
    V01_AUDIT_TABLE_DIR,
    V01_DIAGNOSTICS_DIR,
    V01_RECONCILIATION_DIR,
)

for directory in NOTEBOOK_05_OUTPUT_DIRECTORIES:
    directory.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# General validation helpers
# ------------------------------------------------------------

def utc_now_iso() -> str:
    """Return the current UTC time as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


def require(condition: bool, message: str) -> None:
    """Raise immediately when a blocking invariant is false."""
    if not bool(condition):
        raise AssertionError(message)


def require_sha256(value: str, field_name: str) -> str:
    """Validate and normalize a lowercase SHA-256 literal."""
    require(
        isinstance(value, str),
        f"{field_name} must be a string.",
    )

    normalized = value.strip().lower()

    require(
        SHA256_PATTERN.fullmatch(normalized) is not None,
        f"{field_name} is not a valid SHA-256 value: {value!r}",
    )

    return normalized


def require_file(path: Path, label: str | None = None) -> Path:
    """Require an existing regular file."""
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(
            f"{label or 'Required file'} does not exist: {path}"
        )

    if not path.is_file():
        raise FileNotFoundError(
            f"{label or 'Required path'} is not a regular file: {path}"
        )

    return path


def require_directory(
    path: Path,
    label: str | None = None,
) -> Path:
    """Require an existing directory."""
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(
            f"{label or 'Required directory'} does not exist: {path}"
        )

    if not path.is_dir():
        raise NotADirectoryError(
            f"{label or 'Required path'} is not a directory: {path}"
        )

    return path


def normalized_resolved_path(path: Path) -> Path:
    """Return a normalized absolute path without requiring existence."""
    return Path(path).resolve(strict=False)


def path_is_within(path: Path, root: Path) -> bool:
    """Return whether path resolves inside root."""
    candidate = normalized_resolved_path(path)
    authority_root = normalized_resolved_path(root)

    try:
        candidate.relative_to(authority_root)
        return True
    except ValueError:
        return False


def sha256_file(
    path: Path,
    chunk_size: int = HASH_CHUNK_SIZE,
) -> str:
    """Compute the raw-byte SHA-256 of a file."""
    path = require_file(path)

    digest = hashlib.sha256()

    with path.open("rb") as handle:
        for chunk in iter(
            lambda: handle.read(chunk_size),
            b"",
        ):
            digest.update(chunk)

    return digest.hexdigest()


def json_default(value: Any) -> Any:
    """Convert supported non-native scalar values for JSON hashing."""
    if isinstance(value, Path):
        return str(value)

    if isinstance(value, np.integer):
        return int(value)

    if isinstance(value, np.floating):
        numeric = float(value)

        if not math.isfinite(numeric):
            raise ValueError(
                "Non-finite floating-point value cannot enter "
                "canonical JSON."
            )

        return numeric

    if isinstance(value, np.bool_):
        return bool(value)

    if isinstance(value, pd.Timestamp):
        return value.isoformat()

    if isinstance(value, datetime):
        return value.isoformat()

    raise TypeError(
        f"Object of type {type(value).__name__} "
        "is not canonically JSON serializable."
    )


def canonical_json_bytes(payload: Any) -> bytes:
    """Serialize JSON deterministically under the upstream convention."""
    return json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
        default=json_default,
    ).encode("utf-8")


def canonical_json_sha256(payload: Any) -> str:
    """Compute SHA-256 of deterministic canonical JSON bytes."""
    return hashlib.sha256(
        canonical_json_bytes(payload)
    ).hexdigest()


def read_json_object(path: Path) -> dict[str, Any]:
    """Read a JSON file and require an object at the top level."""
    path = require_file(path)

    with path.open("r", encoding="utf-8") as handle:
        document = json.load(handle)

    if not isinstance(document, dict):
        raise TypeError(
            f"JSON top level must be an object: {path}"
        )

    return document


# ------------------------------------------------------------
# Artifact-document classifications
# ------------------------------------------------------------

JSON_SHAPE_ENVELOPED: Final[str] = "ENVELOPED_JSON"
JSON_SHAPE_FLAT: Final[str] = "FLAT_JSON"

HASH_MODE_RAW_FILE: Final[str] = "RAW_FILE_SHA256"
HASH_MODE_ENVELOPED_PAYLOAD: Final[str] = (
    "ENVELOPED_PAYLOAD_SHA256"
)
HASH_MODE_FLAT_SELF: Final[str] = (
    "FLAT_ARTIFACT_SELF_HASH"
)


def classify_json_shape(
    document: Mapping[str, Any],
) -> str:
    """Classify an upstream JSON artifact by actual top-level shape."""
    has_metadata = "artifact_metadata" in document
    has_payload = "payload" in document

    if has_metadata or has_payload:
        require(
            has_metadata and has_payload,
            "Partially enveloped JSON artifact: both "
            "'artifact_metadata' and 'payload' are required.",
        )

        require(
            isinstance(document["artifact_metadata"], dict),
            "'artifact_metadata' must be an object.",
        )

        require(
            isinstance(document["payload"], dict),
            "'payload' must be an object.",
        )

        return JSON_SHAPE_ENVELOPED

    return JSON_SHAPE_FLAT


def verify_enveloped_payload_hash(
    document: Mapping[str, Any],
    *,
    artifact_label: str,
) -> tuple[str, str]:
    """
    Verify artifact_metadata.payload_sha256 against the canonical
    hash of the inner payload.
    """
    require(
        classify_json_shape(document) == JSON_SHAPE_ENVELOPED,
        f"{artifact_label} is not an enveloped JSON artifact.",
    )

    metadata = document["artifact_metadata"]
    payload = document["payload"]

    expected_payload_hash = require_sha256(
        str(metadata.get("payload_sha256")),
        f"{artifact_label}.artifact_metadata.payload_sha256",
    )

    observed_payload_hash = canonical_json_sha256(payload)

    require(
        observed_payload_hash == expected_payload_hash,
        (
            f"{artifact_label} inner payload hash mismatch:\n"
            f"registered: {expected_payload_hash}\n"
            f"observed:   {observed_payload_hash}"
        ),
    )

    return expected_payload_hash, observed_payload_hash


def verify_flat_self_hash(
    document: Mapping[str, Any],
    *,
    artifact_label: str,
    self_hash_field: str,
) -> tuple[str, str]:
    """
    Verify one explicitly named flat-document self-hash.

    Only the declared self-hash field is removed. Other SHA-256
    fields remain in the payload because they may reference other
    artifacts and are semantically part of the document.
    """
    require(
        classify_json_shape(document) == JSON_SHAPE_FLAT,
        f"{artifact_label} is not a flat JSON artifact.",
    )

    require(
        self_hash_field in document,
        (
            f"{artifact_label} lacks its declared self-hash field: "
            f"{self_hash_field}"
        ),
    )

    expected_self_hash = require_sha256(
        str(document[self_hash_field]),
        f"{artifact_label}.{self_hash_field}",
    )

    hash_payload = {
        key: value
        for key, value in document.items()
        if key != self_hash_field
    }

    observed_self_hash = canonical_json_sha256(
        hash_payload
    )

    require(
        observed_self_hash == expected_self_hash,
        (
            f"{artifact_label} self-hash mismatch:\n"
            f"field:      {self_hash_field}\n"
            f"registered: {expected_self_hash}\n"
            f"observed:   {observed_self_hash}"
        ),
    )

    return expected_self_hash, observed_self_hash


# ------------------------------------------------------------
# Fail-closed artifact discovery
#
# Exact current authority-map paths are preferred. Semantic
# fallback searches are constrained to declared V0.1 roots and
# must return exactly one candidate.
# ------------------------------------------------------------

def deduplicate_paths(
    paths: Iterable[Path],
) -> list[Path]:
    """Deduplicate existing files by normalized path identity."""
    unique: dict[str, Path] = {}

    for path in paths:
        candidate = Path(path)

        if not candidate.is_file():
            continue

        resolved = candidate.resolve()
        unique[str(resolved).casefold()] = resolved

    return sorted(
        unique.values(),
        key=lambda value: str(value).casefold(),
    )


def search_json_files(
    roots: Iterable[Path],
) -> list[Path]:
    """Enumerate JSON files only under declared search roots."""
    discovered: list[Path] = []

    for root in roots:
        root = Path(root)

        if not root.exists():
            continue

        require_directory(root)

        for candidate in root.rglob("*.json"):
            if candidate.is_file():
                discovered.append(candidate.resolve())

    return deduplicate_paths(discovered)


def normalized_search_text(path: Path) -> str:
    """Return a case-normalized searchable path string."""
    return str(path).replace("\\", "/").casefold()


def resolve_control_artifact(
    *,
    label: str,
    exact_paths: Iterable[Path],
    search_roots: Iterable[Path],
    required_tokens: Iterable[str],
    forbidden_tokens: Iterable[str] = (
        "05_market_state_features",
    ),
) -> tuple[Path, str]:
    """
    Resolve one required upstream control artifact.

    Selection is blocked when zero or multiple candidates remain.
    """
    exact_matches = deduplicate_paths(exact_paths)

    if len(exact_matches) == 1:
        selected = exact_matches[0]

        require(
            path_is_within(selected, V01_ROOT),
            f"{label} is outside the registered V0.1 root: {selected}",
        )

        require(
            not path_is_within(selected, V00_ROOT),
            f"{label} improperly resolves inside V0.0: {selected}",
        )

        return selected, "EXACT_AUTHORITY_MAP_PATH"

    if len(exact_matches) > 1:
        raise RuntimeError(
            f"{label}: multiple exact-path candidates exist:\n"
            + "\n".join(
                f"  - {path}"
                for path in exact_matches
            )
        )

    required = tuple(
        str(token).casefold()
        for token in required_tokens
    )

    forbidden = tuple(
        str(token).casefold()
        for token in forbidden_tokens
    )

    candidates: list[Path] = []

    for candidate in search_json_files(search_roots):
        searchable = normalized_search_text(candidate)

        if not all(
            token in searchable
            for token in required
        ):
            continue

        if any(
            token in searchable
            for token in forbidden
        ):
            continue

        if not path_is_within(candidate, V01_ROOT):
            continue

        if path_is_within(candidate, V00_ROOT):
            continue

        candidates.append(candidate)

    candidates = deduplicate_paths(candidates)

    if not candidates:
        raise FileNotFoundError(
            f"{label}: no matching upstream artifact was found.\n"
            f"Required tokens: {required}\n"
            "Search roots:\n"
            + "\n".join(
                f"  - {Path(root)}"
                for root in search_roots
            )
        )

    if len(candidates) > 1:
        raise RuntimeError(
            f"{label}: semantic discovery is ambiguous.\n"
            f"Required tokens: {required}\n"
            "Candidates:\n"
            + "\n".join(
                f"  - {path}"
                for path in candidates
            )
        )

    return candidates[0], "UNAMBIGUOUS_SEMANTIC_DISCOVERY"


# ------------------------------------------------------------
# Artifact-specific bootstrap specifications
# ------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class ControlArtifactSpec:
    key: str
    label: str
    exact_path: Path
    search_roots: tuple[Path, ...]
    required_tokens: tuple[str, ...]
    expected_json_shape: str
    expected_hash_mode: str
    expected_sha256: str
    self_hash_field: str | None = None


CONTROL_ARTIFACT_SPECS: Final[
    tuple[ControlArtifactSpec, ...]
] = (
    ControlArtifactSpec(
        key="notebook_00_output_manifest",
        label="Notebook 00 output manifest",
        exact_path=NOTEBOOK_00_OUTPUT_MANIFEST_PATH,
        search_roots=(
            V01_MANIFEST_DIR,
            V01_ARTIFACT_ROOT,
        ),
        required_tokens=(
            "00_v01_run_contract",
            "notebook_00_output_manifest",
        ),
        expected_json_shape=JSON_SHAPE_ENVELOPED,
        expected_hash_mode=HASH_MODE_RAW_FILE,
        expected_sha256=(
            EXPECTED_NOTEBOOK_00_MANIFEST_FILE_SHA256
        ),
    ),
    ControlArtifactSpec(
        key="notebook_02_output_manifest",
        label="Notebook 02 output manifest",
        exact_path=NOTEBOOK_02_OUTPUT_MANIFEST_PATH,
        search_roots=(
            V01_MANIFEST_DIR,
            V01_ARTIFACT_ROOT,
        ),
        required_tokens=(
            "02_visible_book_reconstruction",
            "notebook_02_output_manifest",
        ),
        expected_json_shape=JSON_SHAPE_ENVELOPED,
        expected_hash_mode=HASH_MODE_RAW_FILE,
        expected_sha256=(
            EXPECTED_NOTEBOOK_02_MANIFEST_FILE_SHA256
        ),
    ),
    ControlArtifactSpec(
        key="notebook_02_to_03_handoff",
        label="Notebook 02 to Notebook 03 handoff",
        exact_path=NOTEBOOK_02_TO_03_HANDOFF_PATH,
        search_roots=(
            V01_HANDOFF_DIR,
            V01_ARTIFACT_ROOT,
        ),
        required_tokens=(
            "02_visible_book_reconstruction",
            "notebook_02_to_notebook_03_handoff",
        ),
        expected_json_shape=JSON_SHAPE_ENVELOPED,
        expected_hash_mode=HASH_MODE_ENVELOPED_PAYLOAD,
        expected_sha256=(
            EXPECTED_NOTEBOOK_02_TO_03_HANDOFF_PAYLOAD_SHA256
        ),
    ),
    ControlArtifactSpec(
        key="notebook_03_output_manifest",
        label="Notebook 03 output manifest",
        exact_path=NOTEBOOK_03_OUTPUT_MANIFEST_PATH,
        search_roots=(
            V01_MANIFEST_DIR,
            V01_ARTIFACT_ROOT,
        ),
        required_tokens=(
            "03_causal_trade_book_alignment",
            "notebook_03_output_manifest",
        ),
        expected_json_shape=JSON_SHAPE_FLAT,
        expected_hash_mode=HASH_MODE_RAW_FILE,
        expected_sha256=(
            EXPECTED_NOTEBOOK_03_MANIFEST_FILE_SHA256
        ),
    ),
    ControlArtifactSpec(
        key="notebook_03_to_04_handoff",
        label="Notebook 03 to Notebook 04 handoff",
        exact_path=NOTEBOOK_03_TO_04_HANDOFF_PATH,
        search_roots=(
            V01_HANDOFF_DIR,
            V01_ARTIFACT_ROOT,
        ),
        required_tokens=(
            "03_causal_trade_book_alignment",
            "notebook_03_to_notebook_04_handoff",
        ),
        expected_json_shape=JSON_SHAPE_FLAT,
        expected_hash_mode=HASH_MODE_RAW_FILE,
        expected_sha256=(
            EXPECTED_NOTEBOOK_03_TO_04_HANDOFF_FILE_SHA256
        ),
    ),
    ControlArtifactSpec(
        key="notebook_04_output_manifest",
        label="Notebook 04 output manifest",
        exact_path=NOTEBOOK_04_OUTPUT_MANIFEST_PATH,
        search_roots=(
            V01_MANIFEST_DIR,
            V01_ARTIFACT_ROOT,
        ),
        required_tokens=(
            "04_event_stream_construction",
            "notebook_04_output_manifest",
        ),
        expected_json_shape=JSON_SHAPE_FLAT,
        expected_hash_mode=HASH_MODE_FLAT_SELF,
        expected_sha256=(
            EXPECTED_NOTEBOOK_04_MANIFEST_PAYLOAD_SHA256
        ),
        self_hash_field="manifest_payload_sha256",
    ),
    ControlArtifactSpec(
        key="notebook_04_to_05_handoff",
        label="Notebook 04 to Notebook 05 handoff",
        exact_path=NOTEBOOK_04_TO_05_HANDOFF_PATH,
        search_roots=(
            V01_HANDOFF_DIR,
            V01_ARTIFACT_ROOT,
        ),
        required_tokens=(
            "04_event_stream_construction",
            "notebook_04_to_notebook_05_handoff",
        ),
        expected_json_shape=JSON_SHAPE_FLAT,
        expected_hash_mode=HASH_MODE_FLAT_SELF,
        expected_sha256=(
            EXPECTED_NOTEBOOK_04_TO_05_HANDOFF_PAYLOAD_SHA256
        ),
        self_hash_field="handoff_payload_sha256",
    ),
    ControlArtifactSpec(
        key="notebook_04_final_acceptance_report",
        label="Notebook 04 final acceptance report",
        exact_path=NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT_PATH,
        search_roots=(
            V01_MANIFEST_DIR,
            V01_ARTIFACT_ROOT,
        ),
        required_tokens=(
            "04_event_stream_construction",
            "notebook_04_final_acceptance_report",
        ),
        expected_json_shape=JSON_SHAPE_FLAT,
        expected_hash_mode=HASH_MODE_FLAT_SELF,
        expected_sha256=(
            EXPECTED_NOTEBOOK_04_FINAL_ACCEPTANCE_PAYLOAD_SHA256
        ),
        self_hash_field=(
            "final_acceptance_report_payload_sha256"
        ),
    ),
)


# ------------------------------------------------------------
# Resolve and verify every control artifact under its own
# persisted convention
# ------------------------------------------------------------

resolved_control_artifacts: dict[str, Path] = {}
control_artifact_documents: dict[
    str,
    dict[str, Any],
] = {}

control_artifact_rows: list[dict[str, Any]] = []

for spec in CONTROL_ARTIFACT_SPECS:
    resolved_path, discovery_method = (
        resolve_control_artifact(
            label=spec.label,
            exact_paths=(spec.exact_path,),
            search_roots=spec.search_roots,
            required_tokens=spec.required_tokens,
        )
    )

    require_file(resolved_path, spec.label)

    require(
        path_is_within(resolved_path, V01_ROOT),
        f"{spec.label} is outside V0.1: {resolved_path}",
    )

    require(
        not path_is_within(resolved_path, V00_ROOT),
        f"{spec.label} resolves inside V0.0: {resolved_path}",
    )

    document = read_json_object(resolved_path)
    observed_shape = classify_json_shape(document)

    require(
        observed_shape == spec.expected_json_shape,
        (
            f"{spec.label} JSON-shape mismatch:\n"
            f"expected: {spec.expected_json_shape}\n"
            f"observed: {observed_shape}"
        ),
    )

    expected_hash = require_sha256(
        spec.expected_sha256,
        f"{spec.label}.expected_sha256",
    )

    raw_file_hash = sha256_file(resolved_path)
    canonical_document_hash = canonical_json_sha256(
        document
    )

    verified_inner_or_self_hash: str | None = None

    if observed_shape == JSON_SHAPE_ENVELOPED:
        (
            _registered_payload_hash,
            verified_inner_or_self_hash,
        ) = verify_enveloped_payload_hash(
            document,
            artifact_label=spec.label,
        )

    elif spec.self_hash_field is not None:
        (
            _registered_self_hash,
            verified_inner_or_self_hash,
        ) = verify_flat_self_hash(
            document,
            artifact_label=spec.label,
            self_hash_field=spec.self_hash_field,
        )

    if spec.expected_hash_mode == HASH_MODE_RAW_FILE:
        observed_expected_hash_class = raw_file_hash

    elif (
        spec.expected_hash_mode
        == HASH_MODE_ENVELOPED_PAYLOAD
    ):
        require(
            observed_shape == JSON_SHAPE_ENVELOPED,
            (
                f"{spec.label} was configured for an enveloped "
                "payload hash but is not enveloped."
            ),
        )

        require(
            verified_inner_or_self_hash is not None,
            f"{spec.label} lacks a verified inner payload hash.",
        )

        observed_expected_hash_class = (
            verified_inner_or_self_hash
        )

    elif spec.expected_hash_mode == HASH_MODE_FLAT_SELF:
        require(
            spec.self_hash_field is not None,
            (
                f"{spec.label} was configured for a flat self-hash "
                "without a declared self-hash field."
            ),
        )

        require(
            verified_inner_or_self_hash is not None,
            f"{spec.label} lacks a verified flat self-hash.",
        )

        observed_expected_hash_class = (
            verified_inner_or_self_hash
        )

    else:
        raise ValueError(
            f"Unsupported hash mode for {spec.label}: "
            f"{spec.expected_hash_mode}"
        )

    require(
        observed_expected_hash_class == expected_hash,
        (
            f"{spec.label} frozen authority hash mismatch:\n"
            f"hash mode: {spec.expected_hash_mode}\n"
            f"expected:  {expected_hash}\n"
            f"observed:  {observed_expected_hash_class}"
        ),
    )

    resolved_control_artifacts[spec.key] = (
        resolved_path.resolve()
    )

    control_artifact_documents[spec.key] = document

    control_artifact_rows.append(
        {
            "artifact_key": spec.key,
            "artifact_label": spec.label,
            "resolved_path": str(resolved_path.resolve()),
            "discovery_method": discovery_method,
            "json_shape": observed_shape,
            "expected_hash_mode": spec.expected_hash_mode,
            "self_hash_field": spec.self_hash_field,
            "size_bytes": int(
                resolved_path.stat().st_size
            ),
            "raw_file_sha256": raw_file_hash,
            "canonical_document_sha256": (
                canonical_document_hash
            ),
            "verified_inner_or_self_sha256": (
                verified_inner_or_self_hash
            ),
            "expected_authority_sha256": expected_hash,
            "authority_hash_matches": (
                observed_expected_hash_class
                == expected_hash
            ),
            "inside_v0_1": path_is_within(
                resolved_path,
                V01_ROOT,
            ),
            "inside_v0_0": path_is_within(
                resolved_path,
                V00_ROOT,
            ),
            "status": "PASS",
        }
    )


# ------------------------------------------------------------
# Immutable bootstrap registries
# ------------------------------------------------------------

UPSTREAM_CONTROL_PATHS: Final[Mapping[str, Path]] = (
    MappingProxyType(
        dict(resolved_control_artifacts)
    )
)

UPSTREAM_CONTROL_DOCUMENTS: Final[
    Mapping[str, dict[str, Any]]
] = MappingProxyType(
    dict(control_artifact_documents)
)

UPSTREAM_CONTROL_ARTIFACT_AUDIT = pd.DataFrame.from_records(
    control_artifact_rows
).sort_values(
    "artifact_key",
    kind="stable",
).reset_index(drop=True)


# ------------------------------------------------------------
# Root and output-directory audit
# ------------------------------------------------------------

root_audit_rows: list[dict[str, Any]] = [
    {
        "logical_name": "project_root",
        "path": str(PROJECT_ROOT.resolve()),
        "exists": PROJECT_ROOT.exists(),
        "is_directory": PROJECT_ROOT.is_dir(),
        "authority": "PROJECT_ROOT",
    },
    {
        "logical_name": "v0_0_root",
        "path": str(V00_ROOT.resolve()),
        "exists": V00_ROOT.exists(),
        "is_directory": V00_ROOT.is_dir(),
        "authority": "IMMUTABLE_SOURCE_AND_RECONCILIATION_ONLY",
    },
    {
        "logical_name": "v0_1_root",
        "path": str(V01_ROOT.resolve()),
        "exists": V01_ROOT.exists(),
        "is_directory": V01_ROOT.is_dir(),
        "authority": "ACTIVE_OUTPUT_AUTHORITY",
    },
]

for directory in NOTEBOOK_05_OUTPUT_DIRECTORIES:
    root_audit_rows.append(
        {
            "logical_name": directory.name,
            "path": str(directory.resolve()),
            "exists": directory.exists(),
            "is_directory": directory.is_dir(),
            "authority": "NOTEBOOK_05_OUTPUT",
        }
    )

NOTEBOOK_05_ROOT_AND_DIRECTORY_AUDIT = (
    pd.DataFrame.from_records(root_audit_rows)
)

require(
    bool(
        NOTEBOOK_05_ROOT_AND_DIRECTORY_AUDIT[
            "exists"
        ].all()
    ),
    "One or more required project/output paths do not exist.",
)

require(
    bool(
        NOTEBOOK_05_ROOT_AND_DIRECTORY_AUDIT[
            "is_directory"
        ].all()
    ),
    "One or more required project/output paths are not directories.",
)

require(
    bool(
        UPSTREAM_CONTROL_ARTIFACT_AUDIT[
            "authority_hash_matches"
        ].all()
    ),
    "One or more upstream control artifacts failed authority hashing.",
)

require(
    not bool(
        UPSTREAM_CONTROL_ARTIFACT_AUDIT[
            "inside_v0_0"
        ].any()
    ),
    "A V0.1 upstream control artifact resolved inside V0.0.",
)


# ------------------------------------------------------------
# Bootstrap result
# ------------------------------------------------------------

UPSTREAM_CONTROL_ARTIFACTS_VERIFIED: Final[bool] = True

display(
    UPSTREAM_CONTROL_ARTIFACT_AUDIT[
        [
            "artifact_key",
            "discovery_method",
            "json_shape",
            "expected_hash_mode",
            "authority_hash_matches",
            "size_bytes",
            "resolved_path",
        ]
    ]
)

{
    "status": "PASS",
    "upstream_control_artifacts_verified": (
        UPSTREAM_CONTROL_ARTIFACTS_VERIFIED
    ),
    "control_artifact_count": int(
        len(UPSTREAM_CONTROL_ARTIFACT_AUDIT)
    ),
    "exact_path_resolutions": int(
        UPSTREAM_CONTROL_ARTIFACT_AUDIT[
            "discovery_method"
        ]
        .eq("EXACT_AUTHORITY_MAP_PATH")
        .sum()
    ),
    "semantic_fallback_resolutions": int(
        UPSTREAM_CONTROL_ARTIFACT_AUDIT[
            "discovery_method"
        ]
        .eq("UNAMBIGUOUS_SEMANTIC_DISCOVERY")
        .sum()
    ),
    "enveloped_json_artifacts": int(
        UPSTREAM_CONTROL_ARTIFACT_AUDIT[
            "json_shape"
        ]
        .eq(JSON_SHAPE_ENVELOPED)
        .sum()
    ),
    "flat_json_artifacts": int(
        UPSTREAM_CONTROL_ARTIFACT_AUDIT[
            "json_shape"
        ]
        .eq(JSON_SHAPE_FLAT)
        .sum()
    ),
    "raw_file_hash_authorities": int(
        UPSTREAM_CONTROL_ARTIFACT_AUDIT[
            "expected_hash_mode"
        ]
        .eq(HASH_MODE_RAW_FILE)
        .sum()
    ),
    "enveloped_payload_hash_authorities": int(
        UPSTREAM_CONTROL_ARTIFACT_AUDIT[
            "expected_hash_mode"
        ]
        .eq(HASH_MODE_ENVELOPED_PAYLOAD)
        .sum()
    ),
    "flat_self_hash_authorities": int(
        UPSTREAM_CONTROL_ARTIFACT_AUDIT[
            "expected_hash_mode"
        ]
        .eq(HASH_MODE_FLAT_SELF)
        .sum()
    ),
    "notebook_05_output_directories": int(
        len(NOTEBOOK_05_OUTPUT_DIRECTORIES)
    ),
    "notebook_04_side_code": dict(
        NOTEBOOK_04_SIDE_CODE
    ),
    "notebook_05_signed_side_code": dict(
        SIGNED_EVENT_SIDE_CODE
    ),
    "verified_at_utc": utc_now_iso(),
}

,artifact_key,discovery_method,json_shape,expected_hash_mode,authority_hash_matches,size_bytes,resolved_path
0,notebook_00_output_manifest,EXACT_AUTHORITY_MAP_PATH,ENVELOPED_JSON,RAW_FILE_SHA256,True,15290,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__00_V01_RUN_CONTRACT__notebook_00_output_manifest.json
1,notebook_02_output_manifest,EXACT_AUTHORITY_MAP_PATH,ENVELOPED_JSON,RAW_FILE_SHA256,True,15362,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__02_VISIBLE_BOOK_RECONSTRUCTION__notebook_02_output_manifest.json
2,notebook_02_to_03_handoff,EXACT_AUTHORITY_MAP_PATH,ENVELOPED_JSON,ENVELOPED_PAYLOAD_SHA256,True,4413,D:\Clown Project\V0.1\artifacts\handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__02_VISIBLE_BOOK_RECONSTRUCTION__notebook_02_to_notebook_03_handoff.json
3,notebook_03_output_manifest,EXACT_AUTHORITY_MAP_PATH,FLAT_JSON,RAW_FILE_SHA256,True,19576,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__03_CAUSAL_TRADE_BOOK_ALIGNMENT__notebook_03_output_manifest.json
4,notebook_03_to_04_handoff,EXACT_AUTHORITY_MAP_PATH,FLAT_JSON,RAW_FILE_SHA256,True,28856,D:\Clown Project\V0.1\artifacts\handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__03_CAUSAL_TRADE_BOOK_ALIGNMENT__notebook_03_to_notebook_04_handoff.json
5,notebook_04_final_acceptance_report,EXACT_AUTHORITY_MAP_PATH,FLAT_JSON,FLAT_ARTIFACT_SELF_HASH,True,2082,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__notebook_04_final_acceptance_report.json
6,notebook_04_output_manifest,EXACT_AUTHORITY_MAP_PATH,FLAT_JSON,FLAT_ARTIFACT_SELF_HASH,True,24653,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__notebook_04_output_manifest.json
7,notebook_04_to_05_handoff,EXACT_AUTHORITY_MAP_PATH,FLAT_JSON,FLAT_ARTIFACT_SELF_HASH,True,5649,D:\Clown Project\V0.1\artifacts\handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__notebook_04_to_notebook_05_handoff.json

{'status': 'PASS',
 'upstream_control_artifacts_verified': True,
 'control_artifact_count': 8,
 'exact_path_resolutions': 8,
 'semantic_fallback_resolutions': 0,
 'enveloped_json_artifacts': 3,
 'flat_json_artifacts': 5,
 'raw_file_hash_authorities': 4,
 'enveloped_payload_hash_authorities': 1,
 'flat_self_hash_authorities': 3,
 'notebook_05_output_directories': 7,
 'notebook_04_side_code': {'BUY': 0, 'SELL': 1},
 'notebook_05_signed_side_code': {'BUY': 1, 'SELL': -1},
 'verified_at_utc': '2026-07-19T09:33:45.983229+00:00'}

In [3]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 04 — Notebook 00 artifact registry, run identity,
#           market-data authority, and split-contract audit
# ============================================================


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "UPSTREAM_CONTROL_ARTIFACTS_VERIFIED",
        False,
    )
    is True,
    (
        "Upstream control artifacts have not been verified. "
        "Run Cell 03 first."
    ),
)

require(
    "UPSTREAM_CONTROL_DOCUMENTS" in globals(),
    "UPSTREAM_CONTROL_DOCUMENTS is missing.",
)

require(
    "UPSTREAM_CONTROL_PATHS" in globals(),
    "UPSTREAM_CONTROL_PATHS is missing.",
)


# ------------------------------------------------------------
# Frozen Notebook 00 split-contract payload identity
#
# This is the canonical payload SHA-256 registered and verified
# by the upstream producing notebooks. It is not a raw-file hash.
# ------------------------------------------------------------

EXPECTED_CHRONOLOGICAL_SPLIT_CONTRACT_PAYLOAD_SHA256: Final[
    str
] = (
    "3b7e8d46f43d8a4dd7b7a1f3d9a61c2c92d3f3643042a8b01968ddc7e0fb4624"
)


# ------------------------------------------------------------
# Structural helpers
# ------------------------------------------------------------

def require_mapping(
    value: Any,
    value_name: str,
) -> dict[str, Any]:
    """Require a JSON-like mapping."""
    require(
        isinstance(value, dict),
        (
            f"{value_name} must be a mapping; "
            f"observed={type(value).__name__}."
        ),
    )

    return value


def require_list(
    value: Any,
    value_name: str,
) -> list[Any]:
    """Require a JSON-like list."""
    require(
        isinstance(value, list),
        (
            f"{value_name} must be a list; "
            f"observed={type(value).__name__}."
        ),
    )

    return value


def require_columns(
    frame: pd.DataFrame,
    required_columns: Iterable[str],
    frame_name: str,
) -> None:
    """Require an exact minimum set of DataFrame columns."""
    required_set = set(required_columns)
    missing_columns = sorted(
        required_set - set(frame.columns)
    )

    require(
        not missing_columns,
        (
            f"{frame_name} is missing required columns: "
            f"{missing_columns}"
        ),
    )


def require_unique_columns(
    frame: pd.DataFrame,
    frame_name: str,
) -> None:
    """Require unique DataFrame column names."""
    duplicate_columns = (
        frame.columns[
            frame.columns.duplicated(keep=False)
        ]
        .astype(str)
        .tolist()
    )

    require(
        not duplicate_columns,
        (
            f"{frame_name} contains duplicate columns: "
            f"{duplicate_columns}"
        ),
    )


def normalized_path_key(
    path: Path | str,
) -> str:
    """Return a normalized case-insensitive path identity."""
    return str(
        Path(path).resolve(strict=False)
    ).replace("\\", "/").casefold()


def paths_match(
    left: Path | str,
    right: Path | str,
) -> bool:
    """Compare two paths by normalized resolved identity."""
    return (
        normalized_path_key(left)
        == normalized_path_key(right)
    )


def require_nonfailure_status(
    value: Any,
    value_name: str,
) -> str:
    """Require a nonempty status that is not an explicit failure."""
    require(
        isinstance(value, str),
        f"{value_name} must be a string.",
    )

    normalized = value.strip().upper()

    require(
        normalized not in {
            "FAIL",
            "FAILED",
            "BLOCKING_FAILURE",
            "CRITICAL_FAILURE",
            "REJECTED",
        },
        (
            f"{value_name} reports an upstream failure: "
            f"{value!r}"
        ),
    )

    require(
        bool(normalized),
        f"{value_name} cannot be empty.",
    )

    return value


def unwrap_notebook_00_artifact(
    document: Mapping[str, Any],
    *,
    artifact_name: str,
    expected_artifact_type: str,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """
    Verify and unwrap one Notebook 00 enveloped JSON artifact.

    This function is intentionally specific to Notebook 00
    artifacts and does not define a universal project envelope.
    """
    envelope = require_mapping(
        dict(document),
        artifact_name,
    )

    metadata = require_mapping(
        envelope.get("artifact_metadata"),
        f"{artifact_name}.artifact_metadata",
    )

    payload = require_mapping(
        envelope.get("payload"),
        f"{artifact_name}.payload",
    )

    required_metadata_fields = {
        "artifact_type",
        "artifact_schema_version",
        "pipeline_version",
        "source_run_prefix",
        "source_set_hash",
        "v0_1_run_id",
        "producing_notebook",
        "acceptance_status",
        "payload_sha256",
    }

    missing_metadata_fields = sorted(
        required_metadata_fields - set(metadata)
    )

    require(
        not missing_metadata_fields,
        (
            f"{artifact_name} metadata is missing fields: "
            f"{missing_metadata_fields}"
        ),
    )

    require(
        metadata["artifact_type"]
        == expected_artifact_type,
        (
            f"{artifact_name} artifact-type mismatch:\n"
            f"expected={expected_artifact_type!r}\n"
            f"observed={metadata['artifact_type']!r}"
        ),
    )

    require(
        metadata["pipeline_version"]
        == PIPELINE_VERSION,
        (
            f"{artifact_name} pipeline-version mismatch: "
            f"{metadata['pipeline_version']!r}"
        ),
    )

    require(
        metadata["source_run_prefix"]
        == SOURCE_RUN_PREFIX,
        (
            f"{artifact_name} source-run mismatch: "
            f"{metadata['source_run_prefix']!r}"
        ),
    )

    require(
        metadata["source_set_hash"]
        == EXPECTED_SOURCE_SET_SHA256,
        (
            f"{artifact_name} source-set hash mismatch: "
            f"{metadata['source_set_hash']!r}"
        ),
    )

    require(
        metadata["v0_1_run_id"]
        == V01_RUN_ID,
        (
            f"{artifact_name} V0.1 run-ID mismatch: "
            f"{metadata['v0_1_run_id']!r}"
        ),
    )

    require(
        metadata["producing_notebook"]
        == "00_V01_RUN_CONTRACT.ipynb",
        (
            f"{artifact_name} producing-notebook mismatch: "
            f"{metadata['producing_notebook']!r}"
        ),
    )

    require_nonfailure_status(
        metadata["acceptance_status"],
        f"{artifact_name}.acceptance_status",
    )

    registered_payload_hash = require_sha256(
        str(metadata["payload_sha256"]),
        f"{artifact_name}.artifact_metadata.payload_sha256",
    )

    observed_payload_hash = canonical_json_sha256(
        payload
    )

    require(
        registered_payload_hash
        == observed_payload_hash,
        (
            f"{artifact_name} payload SHA-256 mismatch:\n"
            f"registered={registered_payload_hash}\n"
            f"observed={observed_payload_hash}"
        ),
    )

    return metadata, payload


def resolve_notebook_00_manifested_path(
    registry: pd.DataFrame,
    artifact_type: str,
) -> tuple[Path, pd.Series]:
    """
    Resolve one Notebook 00 artifact strictly from its manifest.

    The manifest's resolved_path is the primary authority.
    relative_path is checked only as a consistency field.
    """
    matches = registry.loc[
        registry["artifact_type"].eq(
            artifact_type
        )
    ]

    require(
        len(matches) == 1,
        (
            f"Expected exactly one Notebook 00 "
            f"{artifact_type} record; observed={len(matches)}."
        ),
    )

    record = matches.iloc[0]

    require(
        pd.notna(record["resolved_path"]),
        f"{artifact_type} lacks resolved_path.",
    )

    resolved_path = Path(
        str(record["resolved_path"])
    ).resolve(strict=True)

    require(
        path_is_within(
            resolved_path,
            V01_ROOT,
        ),
        (
            f"{artifact_type} resolves outside V0.1: "
            f"{resolved_path}"
        ),
    )

    require(
        not path_is_within(
            resolved_path,
            V00_ROOT,
        ),
        (
            f"{artifact_type} improperly resolves inside V0.0: "
            f"{resolved_path}"
        ),
    )

    if (
        "relative_path" in record.index
        and pd.notna(record["relative_path"])
    ):
        relative_resolved_path = (
            V01_ROOT
            / str(record["relative_path"])
        ).resolve(strict=False)

        require(
            paths_match(
                resolved_path,
                relative_resolved_path,
            ),
            (
                f"{artifact_type} resolved_path and "
                f"relative_path disagree:\n"
                f"resolved_path={resolved_path}\n"
                f"relative_path={record['relative_path']}"
            ),
        )

    require_file(
        resolved_path,
        artifact_type,
    )

    require(
        int(record["size_bytes"])
        == int(resolved_path.stat().st_size),
        (
            f"{artifact_type} size mismatch:\n"
            f"registered={record['size_bytes']}\n"
            f"observed={resolved_path.stat().st_size}"
        ),
    )

    registered_file_hash = require_sha256(
        str(record["sha256"]),
        f"{artifact_type}.manifest.sha256",
    )

    observed_file_hash = sha256_file(
        resolved_path
    )

    require(
        registered_file_hash == observed_file_hash,
        (
            f"{artifact_type} raw-file SHA-256 mismatch:\n"
            f"registered={registered_file_hash}\n"
            f"observed={observed_file_hash}"
        ),
    )

    return resolved_path, record


# ------------------------------------------------------------
# Unwrap and verify the Notebook 00 output manifest
# ------------------------------------------------------------

NOTEBOOK_00_OUTPUT_MANIFEST_DOCUMENT = (
    UPSTREAM_CONTROL_DOCUMENTS[
        "notebook_00_output_manifest"
    ]
)

(
    NOTEBOOK_00_OUTPUT_MANIFEST_METADATA,
    NOTEBOOK_00_OUTPUT_MANIFEST_BODY,
) = unwrap_notebook_00_artifact(
    NOTEBOOK_00_OUTPUT_MANIFEST_DOCUMENT,
    artifact_name=(
        "Notebook 00 output manifest"
    ),
    expected_artifact_type=(
        "NOTEBOOK_00_OUTPUT_MANIFEST"
    ),
)

require(
    NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
        "manifest_type"
    )
    == "NOTEBOOK_00_OUTPUT_MANIFEST",
    "Notebook 00 manifest body has the wrong manifest_type.",
)

require(
    NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
        "source_run_prefix"
    )
    == SOURCE_RUN_PREFIX,
    "Notebook 00 manifest body has the wrong source run.",
)

require(
    NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
        "source_set_hash"
    )
    == EXPECTED_SOURCE_SET_SHA256,
    "Notebook 00 manifest body has the wrong source-set hash.",
)

require(
    NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
        "v0_1_run_id"
    )
    == V01_RUN_ID,
    "Notebook 00 manifest body has the wrong V0.1 run ID.",
)

require(
    NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
        "v0_1_run_config_hash"
    )
    == EXPECTED_RUN_CONFIG_SHA256,
    "Notebook 00 manifest body has the wrong run-config hash.",
)

require(
    NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
        "v0_1_run_identity_hash"
    )
    == EXPECTED_RUN_IDENTITY_SHA256,
    "Notebook 00 manifest body has the wrong run-identity hash.",
)

require(
    NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
        "operating_mode"
    )
    == OPERATING_MODE,
    "Notebook 00 manifest body has the wrong operating mode.",
)

require(
    NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
        "producing_notebook"
    )
    == "00_V01_RUN_CONTRACT.ipynb",
    "Notebook 00 manifest body has the wrong producer.",
)

manifest_acceptance_status = (
    require_nonfailure_status(
        NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
            "acceptance_status"
        ),
        "Notebook 00 manifest-body acceptance_status",
    )
)

notebook_00_manifest_artifact_records = (
    require_list(
        NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
            "artifacts"
        ),
        "Notebook 00 manifest artifacts",
    )
)

require(
    int(
        NOTEBOOK_00_OUTPUT_MANIFEST_BODY.get(
            "artifact_count",
            -1,
        )
    )
    == len(
        notebook_00_manifest_artifact_records
    ),
    (
        "Notebook 00 manifest artifact_count does not match "
        "its artifact-record list."
    ),
)

NOTEBOOK_00_ARTIFACT_REGISTRY = (
    pd.DataFrame.from_records(
        notebook_00_manifest_artifact_records
    )
)

require_unique_columns(
    NOTEBOOK_00_ARTIFACT_REGISTRY,
    "NOTEBOOK_00_ARTIFACT_REGISTRY",
)

require_columns(
    NOTEBOOK_00_ARTIFACT_REGISTRY,
    [
        "artifact_type",
        "format",
        "acceptance_status",
        "resolved_path",
        "relative_path",
        "size_bytes",
        "sha256",
    ],
    "NOTEBOOK_00_ARTIFACT_REGISTRY",
)

require(
    NOTEBOOK_00_ARTIFACT_REGISTRY[
        "artifact_type"
    ].notna().all(),
    "Notebook 00 registry contains a null artifact_type.",
)

require(
    not NOTEBOOK_00_ARTIFACT_REGISTRY[
        "artifact_type"
    ].duplicated().any(),
    (
        "Notebook 00 registry contains duplicate "
        "artifact_type values."
    ),
)

require(
    NOTEBOOK_00_ARTIFACT_REGISTRY[
        "acceptance_status"
    ].astype(str).eq(
        str(manifest_acceptance_status)
    ).all(),
    (
        "Notebook 00 artifact-record acceptance statuses do not "
        "match the manifest body."
    ),
)


# ------------------------------------------------------------
# Required Notebook 00 artifacts for Notebook 05
# ------------------------------------------------------------

REQUIRED_NOTEBOOK_00_ARTIFACT_TYPES: Final[
    tuple[str, ...]
] = (
    "V0_0_SOURCE_REGISTRY",
    "V0_1_RUN_CONFIG",
    "CHRONOLOGICAL_SPLIT_CONTRACT",
    "MARKET_DATA_CONTRACT",
    "MISSING_DATA_REJECTION_CONTRACT",
    "DECISION_AND_TOLERANCE_CONTRACT",
    "V0_1_RUN_IDENTITY",
)

observed_notebook_00_artifact_types = set(
    NOTEBOOK_00_ARTIFACT_REGISTRY[
        "artifact_type"
    ].astype(str)
)

missing_required_notebook_00_artifacts = sorted(
    set(REQUIRED_NOTEBOOK_00_ARTIFACT_TYPES)
    - observed_notebook_00_artifact_types
)

require(
    not missing_required_notebook_00_artifacts,
    (
        "Notebook 00 manifest lacks required artifacts: "
        f"{missing_required_notebook_00_artifacts}"
    ),
)


# ------------------------------------------------------------
# Resolve, rehash, load, and unwrap required Notebook 00
# artifacts using the manifest as path authority
# ------------------------------------------------------------

notebook_00_required_paths: dict[str, Path] = {}
notebook_00_required_documents: dict[
    str,
    dict[str, Any],
] = {}
notebook_00_required_metadata: dict[
    str,
    dict[str, Any],
] = {}
notebook_00_required_payloads: dict[
    str,
    dict[str, Any],
] = {}

notebook_00_required_audit_rows: list[
    dict[str, Any]
] = []

for artifact_type in REQUIRED_NOTEBOOK_00_ARTIFACT_TYPES:
    artifact_path, artifact_record = (
        resolve_notebook_00_manifested_path(
            NOTEBOOK_00_ARTIFACT_REGISTRY,
            artifact_type,
        )
    )

    require(
        str(
            artifact_record["format"]
        ).upper()
        == "JSON",
        (
            f"{artifact_type} must be registered as JSON; "
            f"observed={artifact_record['format']!r}."
        ),
    )

    artifact_document = read_json_object(
        artifact_path
    )

    artifact_metadata, artifact_payload = (
        unwrap_notebook_00_artifact(
            artifact_document,
            artifact_name=artifact_type,
            expected_artifact_type=artifact_type,
        )
    )

    require(
        str(
            artifact_metadata[
                "acceptance_status"
            ]
        )
        == str(
            artifact_record[
                "acceptance_status"
            ]
        ),
        (
            f"{artifact_type} envelope and manifest-record "
            "acceptance statuses disagree."
        ),
    )

    notebook_00_required_paths[
        artifact_type
    ] = artifact_path

    notebook_00_required_documents[
        artifact_type
    ] = artifact_document

    notebook_00_required_metadata[
        artifact_type
    ] = artifact_metadata

    notebook_00_required_payloads[
        artifact_type
    ] = artifact_payload

    notebook_00_required_audit_rows.append(
        {
            "artifact_type": artifact_type,
            "resolved_path": str(
                artifact_path
            ),
            "relative_path": str(
                artifact_record[
                    "relative_path"
                ]
            ),
            "format": str(
                artifact_record[
                    "format"
                ]
            ),
            "acceptance_status": str(
                artifact_record[
                    "acceptance_status"
                ]
            ),
            "size_bytes": int(
                artifact_path.stat().st_size
            ),
            "raw_file_sha256": sha256_file(
                artifact_path
            ),
            "payload_sha256": str(
                artifact_metadata[
                    "payload_sha256"
                ]
            ),
            "producing_notebook": str(
                artifact_metadata[
                    "producing_notebook"
                ]
            ),
            "source_set_hash": str(
                artifact_metadata[
                    "source_set_hash"
                ]
            ),
            "status": "PASS",
        }
    )


NOTEBOOK_00_REQUIRED_PATHS: Final[
    Mapping[str, Path]
] = MappingProxyType(
    dict(notebook_00_required_paths)
)

NOTEBOOK_00_REQUIRED_DOCUMENTS: Final[
    Mapping[str, dict[str, Any]]
] = MappingProxyType(
    dict(notebook_00_required_documents)
)

NOTEBOOK_00_REQUIRED_METADATA: Final[
    Mapping[str, dict[str, Any]]
] = MappingProxyType(
    dict(notebook_00_required_metadata)
)

NOTEBOOK_00_REQUIRED_PAYLOADS: Final[
    Mapping[str, dict[str, Any]]
] = MappingProxyType(
    dict(notebook_00_required_payloads)
)

NOTEBOOK_00_REQUIRED_ARTIFACT_AUDIT = (
    pd.DataFrame.from_records(
        notebook_00_required_audit_rows
    )
    .sort_values(
        "artifact_type",
        kind="stable",
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Register actual Notebook 00 payloads
# ------------------------------------------------------------

V0_0_SOURCE_REGISTRY = (
    NOTEBOOK_00_REQUIRED_PAYLOADS[
        "V0_0_SOURCE_REGISTRY"
    ]
)

V0_1_RUN_CONFIG = (
    NOTEBOOK_00_REQUIRED_PAYLOADS[
        "V0_1_RUN_CONFIG"
    ]
)

CHRONOLOGICAL_SPLIT_CONTRACT = (
    NOTEBOOK_00_REQUIRED_PAYLOADS[
        "CHRONOLOGICAL_SPLIT_CONTRACT"
    ]
)

MARKET_DATA_CONTRACT = (
    NOTEBOOK_00_REQUIRED_PAYLOADS[
        "MARKET_DATA_CONTRACT"
    ]
)

MISSING_DATA_REJECTION_CONTRACT = (
    NOTEBOOK_00_REQUIRED_PAYLOADS[
        "MISSING_DATA_REJECTION_CONTRACT"
    ]
)

DECISION_AND_TOLERANCE_CONTRACT = (
    NOTEBOOK_00_REQUIRED_PAYLOADS[
        "DECISION_AND_TOLERANCE_CONTRACT"
    ]
)

V0_1_RUN_IDENTITY = (
    NOTEBOOK_00_REQUIRED_PAYLOADS[
        "V0_1_RUN_IDENTITY"
    ]
)


# ------------------------------------------------------------
# Verify V0.1 run-config payload identity and required sections
# ------------------------------------------------------------

observed_run_config_payload_sha256 = (
    canonical_json_sha256(
        V0_1_RUN_CONFIG
    )
)

require(
    observed_run_config_payload_sha256
    == EXPECTED_RUN_CONFIG_SHA256,
    (
        "V0.1 run-config canonical payload hash mismatch:\n"
        f"expected={EXPECTED_RUN_CONFIG_SHA256}\n"
        f"observed={observed_run_config_payload_sha256}"
    ),
)

require(
    V0_1_RUN_CONFIG.get(
        "config_type"
    )
    == "V0_1_RUN_CONFIGURATION",
    "Run config has the wrong config_type.",
)

require(
    V0_1_RUN_CONFIG.get(
        "pipeline_version"
    )
    == PIPELINE_VERSION,
    "Run config has the wrong pipeline version.",
)

require(
    V0_1_RUN_CONFIG.get(
        "producing_notebook"
    )
    == "00_V01_RUN_CONTRACT.ipynb",
    "Run config has the wrong producing notebook.",
)

required_run_config_sections = {
    "source_identity",
    "operating_authority",
    "market",
    "chronological_partitions",
    "reproducibility",
    "output_contract",
    "pipeline_sequence",
    "component_hashes",
}

missing_run_config_sections = sorted(
    required_run_config_sections
    - set(V0_1_RUN_CONFIG)
)

require(
    not missing_run_config_sections,
    (
        "Run config is missing required sections: "
        f"{missing_run_config_sections}"
    ),
)

run_config_source_identity = require_mapping(
    V0_1_RUN_CONFIG[
        "source_identity"
    ],
    "V0_1_RUN_CONFIG.source_identity",
)

run_config_operating_authority = require_mapping(
    V0_1_RUN_CONFIG[
        "operating_authority"
    ],
    "V0_1_RUN_CONFIG.operating_authority",
)

run_config_market = require_mapping(
    V0_1_RUN_CONFIG[
        "market"
    ],
    "V0_1_RUN_CONFIG.market",
)

run_config_output_contract = require_mapping(
    V0_1_RUN_CONFIG[
        "output_contract"
    ],
    "V0_1_RUN_CONFIG.output_contract",
)

require(
    run_config_source_identity.get(
        "source_run_prefix"
    )
    == SOURCE_RUN_PREFIX,
    "Run config source-run prefix mismatch.",
)

require(
    run_config_source_identity.get(
        "source_set_hash"
    )
    == EXPECTED_SOURCE_SET_SHA256,
    "Run config source-set hash mismatch.",
)

require(
    run_config_operating_authority.get(
        "operating_mode"
    )
    == OPERATING_MODE,
    "Run config operating-mode mismatch.",
)

require(
    run_config_market.get(
        "symbol"
    )
    == SYMBOL,
    "Run config symbol mismatch.",
)

require(
    run_config_market.get(
        "canonical_timezone"
    )
    == CANONICAL_TIMEZONE,
    "Run config timezone mismatch.",
)

require(
    run_config_market.get(
        "primary_causal_order"
    )
    == PRIMARY_ORDERING_AUTHORITY,
    "Run config primary causal-order mismatch.",
)

require(
    paths_match(
        run_config_output_contract.get(
            "authoritative_root"
        ),
        V01_ROOT,
    ),
    (
        "Run config authoritative output root does not match "
        "the registered V0.1 root."
    ),
)

require(
    run_config_output_contract.get(
        "overwrite_v0_0_allowed"
    )
    is False,
    "Run config improperly permits V0.0 overwrite.",
)

require(
    run_config_output_contract.get(
        "atomic_write_required"
    )
    is True,
    "Run config does not require atomic writes.",
)


# ------------------------------------------------------------
# Verify V0.1 run-identity payload
#
# The registered run-identity hash excludes the payload's own
# v0_1_run_identity_hash field, as frozen by Notebook 00.
# ------------------------------------------------------------

require(
    V0_1_RUN_IDENTITY.get(
        "identity_type"
    )
    == "V0_1_RUN_INSTANCE",
    "Run identity has the wrong identity_type.",
)

require(
    V0_1_RUN_IDENTITY.get(
        "pipeline_version"
    )
    == PIPELINE_VERSION,
    "Run identity has the wrong pipeline version.",
)

require(
    V0_1_RUN_IDENTITY.get(
        "v0_1_run_id"
    )
    == V01_RUN_ID,
    "Run identity contains the wrong V0.1 run ID.",
)

require(
    V0_1_RUN_IDENTITY.get(
        "producing_notebook"
    )
    == "00_V01_RUN_CONTRACT.ipynb",
    "Run identity has the wrong producing notebook.",
)

run_identity_without_self_hash = dict(
    V0_1_RUN_IDENTITY
)

registered_run_identity_hash = (
    require_sha256(
        str(
            run_identity_without_self_hash.pop(
                "v0_1_run_identity_hash",
                None,
            )
        ),
        "V0_1_RUN_IDENTITY.v0_1_run_identity_hash",
    )
)

observed_run_identity_hash = (
    canonical_json_sha256(
        run_identity_without_self_hash
    )
)

require(
    registered_run_identity_hash
    == EXPECTED_RUN_IDENTITY_SHA256,
    (
        "Run identity registered self-hash does not match the "
        "frozen V0.1 run identity."
    ),
)

require(
    observed_run_identity_hash
    == EXPECTED_RUN_IDENTITY_SHA256,
    (
        "Run identity canonical recomputation mismatch:\n"
        f"expected={EXPECTED_RUN_IDENTITY_SHA256}\n"
        f"observed={observed_run_identity_hash}"
    ),
)

run_identity_source = require_mapping(
    V0_1_RUN_IDENTITY.get(
        "source_identity"
    ),
    "V0_1_RUN_IDENTITY.source_identity",
)

run_identity_configuration = require_mapping(
    V0_1_RUN_IDENTITY.get(
        "configuration_identity"
    ),
    "V0_1_RUN_IDENTITY.configuration_identity",
)

run_identity_authority = require_mapping(
    V0_1_RUN_IDENTITY.get(
        "execution_authority"
    ),
    "V0_1_RUN_IDENTITY.execution_authority",
)

require(
    run_identity_source.get(
        "source_run_prefix"
    )
    == SOURCE_RUN_PREFIX,
    "Run identity source-run prefix mismatch.",
)

require(
    run_identity_source.get(
        "source_set_hash"
    )
    == EXPECTED_SOURCE_SET_SHA256,
    "Run identity source-set hash mismatch.",
)

require(
    run_identity_configuration.get(
        "v0_1_run_config_hash"
    )
    == EXPECTED_RUN_CONFIG_SHA256,
    "Run identity run-config hash mismatch.",
)

require(
    run_identity_authority.get(
        "operating_mode"
    )
    == OPERATING_MODE,
    "Run identity operating-mode mismatch.",
)

require(
    run_identity_authority.get(
        "claim_bearing_holdout_available"
    )
    is False,
    (
        "The current one-session engineering run must not "
        "claim an independent holdout."
    ),
)

require(
    run_identity_authority.get(
        "partitions_are_independent"
    )
    is False,
    (
        "The current engineering partitions must not be "
        "represented as independent samples."
    ),
)


# ------------------------------------------------------------
# Verify V0.0 source registry structure without substituting it
# for V0.1 processed authority
# ------------------------------------------------------------

primary_source_records = require_list(
    V0_0_SOURCE_REGISTRY.get(
        "authoritative_primary_sources"
    ),
    (
        "V0_0_SOURCE_REGISTRY."
        "authoritative_primary_sources"
    ),
)

AUTHORITATIVE_RAW_SOURCE_MANIFEST = (
    pd.DataFrame.from_records(
        primary_source_records
    )
)

require_unique_columns(
    AUTHORITATIVE_RAW_SOURCE_MANIFEST,
    "AUTHORITATIVE_RAW_SOURCE_MANIFEST",
)

require_columns(
    AUTHORITATIVE_RAW_SOURCE_MANIFEST,
    [
        "source_role",
        "resolved_path",
        "size_bytes",
        "sha256",
    ],
    "AUTHORITATIVE_RAW_SOURCE_MANIFEST",
)

require(
    AUTHORITATIVE_RAW_SOURCE_MANIFEST[
        "source_role"
    ].is_unique,
    (
        "V0.0 source registry contains duplicate "
        "source_role values."
    ),
)

require(
    all(
        path_is_within(
            Path(path),
            V00_ROOT,
        )
        for path in (
            AUTHORITATIVE_RAW_SOURCE_MANIFEST[
                "resolved_path"
            ]
            .astype(str)
        )
    ),
    (
        "At least one authoritative raw source is outside "
        "the immutable V0.0 root."
    ),
)

require(
    all(
        not path_is_within(
            Path(path),
            V01_ROOT,
        )
        for path in (
            AUTHORITATIVE_RAW_SOURCE_MANIFEST[
                "resolved_path"
            ]
            .astype(str)
        )
    ),
    (
        "At least one authoritative raw source improperly "
        "resolves inside V0.1."
    ),
)


# ------------------------------------------------------------
# Verify canonical market-data contract
# ------------------------------------------------------------

require(
    MARKET_DATA_CONTRACT.get(
        "pipeline_version"
    )
    == PIPELINE_VERSION,
    "Market-data contract pipeline-version mismatch.",
)

require(
    MARKET_DATA_CONTRACT.get(
        "source_run_prefix"
    )
    == SOURCE_RUN_PREFIX,
    "Market-data contract source-run mismatch.",
)

require(
    MARKET_DATA_CONTRACT.get(
        "source_set_hash"
    )
    == EXPECTED_SOURCE_SET_SHA256,
    "Market-data contract source-set hash mismatch.",
)

require(
    MARKET_DATA_CONTRACT.get(
        "operating_mode"
    )
    == OPERATING_MODE,
    "Market-data contract operating-mode mismatch.",
)

market_contract_market = require_mapping(
    MARKET_DATA_CONTRACT.get(
        "market"
    ),
    "MARKET_DATA_CONTRACT.market",
)

market_contract_book = require_mapping(
    MARKET_DATA_CONTRACT.get(
        "book_representation"
    ),
    "MARKET_DATA_CONTRACT.book_representation",
)

market_contract_time = require_mapping(
    MARKET_DATA_CONTRACT.get(
        "time_contract"
    ),
    "MARKET_DATA_CONTRACT.time_contract",
)

market_contract_ordering = require_mapping(
    MARKET_DATA_CONTRACT.get(
        "ordering_contract"
    ),
    "MARKET_DATA_CONTRACT.ordering_contract",
)

market_contract_causality = require_mapping(
    MARKET_DATA_CONTRACT.get(
        "causality_contract"
    ),
    "MARKET_DATA_CONTRACT.causality_contract",
)

market_contract_authority = require_mapping(
    MARKET_DATA_CONTRACT.get(
        "authority_contract"
    ),
    "MARKET_DATA_CONTRACT.authority_contract",
)

require(
    market_contract_market.get(
        "venue"
    )
    == "BINANCE",
    "Market-data contract venue mismatch.",
)

require(
    market_contract_market.get(
        "venue_segment"
    )
    == "SPOT",
    "Market-data contract venue-segment mismatch.",
)

require(
    market_contract_market.get(
        "symbol"
    )
    == SYMBOL,
    "Market-data contract symbol mismatch.",
)

require(
    market_contract_book.get(
        "type"
    )
    == "VISIBLE_MARKET_BY_PRICE",
    "Market-data contract book representation mismatch.",
)

require(
    market_contract_book.get(
        "queue_position_observable"
    )
    is False,
    (
        "The market-data contract must not claim observable "
        "queue position."
    ),
)

require(
    market_contract_time.get(
        "canonical_timezone"
    )
    == CANONICAL_TIMEZONE,
    "Market-data contract timezone mismatch.",
)

require(
    market_contract_time.get(
        "collector_receipt_unit"
    )
    == "nanoseconds",
    "Collector receipt-time unit mismatch.",
)

require(
    market_contract_time.get(
        "timestamp_jitter_allowed"
    )
    is False,
    "Market-data contract improperly permits timestamp jitter.",
)

require(
    market_contract_ordering.get(
        "primary_causal_order"
    )
    == PRIMARY_ORDERING_AUTHORITY,
    "Market-data contract ordering-authority mismatch.",
)

require(
    market_contract_ordering.get(
        "equal_timestamps_preserved"
    )
    is True,
    (
        "Market-data contract must preserve equal "
        "timestamps."
    ),
)

require(
    market_contract_ordering.get(
        "cross_stream_ties_resolved_by"
    )
    == PRIMARY_ORDERING_AUTHORITY,
    "Cross-stream tie authority mismatch.",
)

require(
    market_contract_ordering.get(
        "forward_reordering_allowed"
    )
    is False,
    "Market-data contract permits forward reordering.",
)

require(
    market_contract_causality.get(
        "forward_join_allowed"
    )
    is False,
    "Market-data contract permits forward joins.",
)

require(
    market_contract_causality.get(
        "future_label_in_feature_table_allowed"
    )
    is False,
    (
        "Market-data contract permits future labels in "
        "feature tables."
    ),
)

require(
    market_contract_causality.get(
        "split_intervals"
    )
    == INTERVAL_CONVENTION,
    "Market-data contract split-interval rule mismatch.",
)

require(
    market_contract_authority.get(
        "v0_0_processed_authority"
    )
    == "REFERENCE_ONLY",
    (
        "V0.0 processed artifacts must remain "
        "reference-only."
    ),
)

require(
    market_contract_authority.get(
        "silent_reference_substitution_allowed"
    )
    is False,
    (
        "Market-data contract improperly permits silent "
        "V0.0 substitution."
    ),
)


# ------------------------------------------------------------
# Verify missing-data and rejection authority
# ------------------------------------------------------------

require(
    MISSING_DATA_REJECTION_CONTRACT.get(
        "pipeline_version"
    )
    == PIPELINE_VERSION,
    "Missing-data contract pipeline-version mismatch.",
)

require(
    MISSING_DATA_REJECTION_CONTRACT.get(
        "source_run_prefix"
    )
    == SOURCE_RUN_PREFIX,
    "Missing-data contract source-run mismatch.",
)

require(
    MISSING_DATA_REJECTION_CONTRACT.get(
        "source_set_hash"
    )
    == EXPECTED_SOURCE_SET_SHA256,
    "Missing-data contract source-set hash mismatch.",
)

missing_data_contract_text = json.dumps(
    MISSING_DATA_REJECTION_CONTRACT,
    sort_keys=True,
    ensure_ascii=False,
).upper()

require(
    "TIMESTAMP_JITTER_ALLOWED" not in missing_data_contract_text
    or '"TIMESTAMP_JITTER_ALLOWED": FALSE'
    in missing_data_contract_text,
    (
        "Missing-data contract contains an unresolved "
        "timestamp-jitter rule."
    ),
)


# ------------------------------------------------------------
# Verify chronological split-contract payload and schema
# ------------------------------------------------------------

split_contract_metadata = (
    NOTEBOOK_00_REQUIRED_METADATA[
        "CHRONOLOGICAL_SPLIT_CONTRACT"
    ]
)

registered_split_payload_sha256 = (
    require_sha256(
        str(
            split_contract_metadata[
                "payload_sha256"
            ]
        ),
        (
            "CHRONOLOGICAL_SPLIT_CONTRACT."
            "artifact_metadata.payload_sha256"
        ),
    )
)

observed_split_payload_sha256 = (
    canonical_json_sha256(
        CHRONOLOGICAL_SPLIT_CONTRACT
    )
)

require(
    registered_split_payload_sha256
    == EXPECTED_CHRONOLOGICAL_SPLIT_CONTRACT_PAYLOAD_SHA256,
    (
        "Split-contract registered payload SHA-256 does not "
        "match the frozen Notebook 00 identity."
    ),
)

require(
    observed_split_payload_sha256
    == EXPECTED_CHRONOLOGICAL_SPLIT_CONTRACT_PAYLOAD_SHA256,
    (
        "Split-contract canonical payload SHA-256 mismatch:\n"
        f"expected="
        f"{EXPECTED_CHRONOLOGICAL_SPLIT_CONTRACT_PAYLOAD_SHA256}\n"
        f"observed={observed_split_payload_sha256}"
    ),
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "pipeline_version"
    )
    == PIPELINE_VERSION,
    "Split contract pipeline-version mismatch.",
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "source_run_prefix"
    )
    == SOURCE_RUN_PREFIX,
    "Split contract source-run mismatch.",
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "source_set_hash"
    )
    == EXPECTED_SOURCE_SET_SHA256,
    "Split contract source-set hash mismatch.",
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "operating_mode"
    )
    == OPERATING_MODE,
    "Split contract operating-mode mismatch.",
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "primary_boundary_authority"
    )
    == PRIMARY_ORDERING_AUTHORITY,
    "Split contract boundary-authority mismatch.",
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "interval_convention"
    )
    == INTERVAL_CONVENTION,
    "Split contract interval-convention mismatch.",
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "canonical_timezone"
    )
    == CANONICAL_TIMEZONE,
    "Split contract timezone mismatch.",
)

require(
    tuple(
        CHRONOLOGICAL_SPLIT_CONTRACT.get(
            "partition_order",
            [],
        )
    )
    == PARTITION_ORDER,
    "Split contract partition order mismatch.",
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "partitions_are_independent"
    )
    is False,
    (
        "Engineering-reproduction partitions must not be "
        "represented as independent."
    ),
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "claim_bearing_holdout_available"
    )
    is False,
    (
        "The current source run must not claim a "
        "claim-bearing holdout."
    ),
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "final_partition_model_selection_access"
    )
    is False,
    (
        "The final partition must remain unavailable for "
        "model selection."
    ),
)

require(
    CHRONOLOGICAL_SPLIT_CONTRACT.get(
        "producing_notebook"
    )
    == "00_V01_RUN_CONTRACT.ipynb",
    "Split contract producing-notebook mismatch.",
)


# ------------------------------------------------------------
# Boundary-table validation
# ------------------------------------------------------------

SPLIT_BOUNDARY_TABLE = pd.DataFrame.from_records(
    require_list(
        CHRONOLOGICAL_SPLIT_CONTRACT.get(
            "boundary_table"
        ),
        "CHRONOLOGICAL_SPLIT_CONTRACT.boundary_table",
    )
)

require_unique_columns(
    SPLIT_BOUNDARY_TABLE,
    "SPLIT_BOUNDARY_TABLE",
)

require_columns(
    SPLIT_BOUNDARY_TABLE,
    [
        "partition_order",
        "partition",
        "collector_sequence_start",
        "collector_sequence_end_exclusive",
        "collector_sequence_last_included",
        "receipt_time_start_ns",
        "receipt_time_end_ns_exclusive",
        "row_count",
        "trade_row_count",
        "depth_row_count",
        "independent_partition",
        "claim_authority",
        "interval_convention",
    ],
    "SPLIT_BOUNDARY_TABLE",
)

SPLIT_BOUNDARY_TABLE = (
    SPLIT_BOUNDARY_TABLE
    .sort_values(
        "partition_order",
        kind="stable",
    )
    .reset_index(drop=True)
)

require(
    tuple(
        SPLIT_BOUNDARY_TABLE[
            "partition"
        ].astype(str)
    )
    == PARTITION_ORDER,
    "Boundary-table partition order mismatch.",
)

require(
    SPLIT_BOUNDARY_TABLE[
        "partition_order"
    ].astype(int).tolist()
    == [1, 2, 3, 4],
    "Boundary-table partition numbers are invalid.",
)

require(
    SPLIT_BOUNDARY_TABLE[
        "interval_convention"
    ].astype(str).eq(
        INTERVAL_CONVENTION
    ).all(),
    "Boundary table contains a non-half-open interval.",
)

require(
    ~SPLIT_BOUNDARY_TABLE[
        "independent_partition"
    ].astype(bool).any(),
    (
        "No engineering-reproduction partition may be marked "
        "independent."
    ),
)

require(
    ~SPLIT_BOUNDARY_TABLE[
        "claim_authority"
    ].astype(bool).any(),
    (
        "No partition in this one-session engineering run may "
        "carry claim authority."
    ),
)

require(
    (
        SPLIT_BOUNDARY_TABLE[
            "trade_row_count"
        ].astype(int)
        + SPLIT_BOUNDARY_TABLE[
            "depth_row_count"
        ].astype(int)
    ).equals(
        SPLIT_BOUNDARY_TABLE[
            "row_count"
        ].astype(int)
    ),
    (
        "Boundary-table trade and depth counts do not sum to "
        "combined partition row counts."
    ),
)

require(
    int(
        SPLIT_BOUNDARY_TABLE[
            "trade_row_count"
        ].sum()
    )
    == EXPECTED_MATCHED_TRADE_ROWS,
    (
        "Notebook 00 partition trade counts do not sum to "
        f"{EXPECTED_MATCHED_TRADE_ROWS:,}."
    ),
)

for row_index in range(
    len(SPLIT_BOUNDARY_TABLE)
):
    row = SPLIT_BOUNDARY_TABLE.iloc[
        row_index
    ]

    require(
        int(
            row[
                "collector_sequence_last_included"
            ]
        )
        == (
            int(
                row[
                    "collector_sequence_end_exclusive"
                ]
            )
            - 1
        ),
        (
            f"{row['partition']} has an invalid last-included "
            "collector sequence."
        ),
    )

    require(
        int(
            row[
                "collector_sequence_start"
            ]
        )
        < int(
            row[
                "collector_sequence_end_exclusive"
            ]
        ),
        (
            f"{row['partition']} has an empty or reversed "
            "collector-sequence interval."
        ),
    )

    require(
        int(
            row[
                "receipt_time_start_ns"
            ]
        )
        < int(
            row[
                "receipt_time_end_ns_exclusive"
            ]
        ),
        (
            f"{row['partition']} has an empty or reversed "
            "receipt-time interval."
        ),
    )

for current_index in range(
    len(SPLIT_BOUNDARY_TABLE) - 1
):
    current_row = SPLIT_BOUNDARY_TABLE.iloc[
        current_index
    ]

    next_row = SPLIT_BOUNDARY_TABLE.iloc[
        current_index + 1
    ]

    require(
        int(
            current_row[
                "collector_sequence_end_exclusive"
            ]
        )
        == int(
            next_row[
                "collector_sequence_start"
            ]
        ),
        (
            "Collector-sequence partition intervals are not "
            f"contiguous: {current_row['partition']} -> "
            f"{next_row['partition']}."
        ),
    )

    require(
        int(
            current_row[
                "receipt_time_end_ns_exclusive"
            ]
        )
        == int(
            next_row[
                "receipt_time_start_ns"
            ]
        ),
        (
            "Receipt-time partition intervals are not "
            f"contiguous: {current_row['partition']} -> "
            f"{next_row['partition']}."
        ),
    )


# ------------------------------------------------------------
# Access-matrix validation
# ------------------------------------------------------------

SPLIT_ACCESS_MATRIX = pd.DataFrame.from_records(
    require_list(
        CHRONOLOGICAL_SPLIT_CONTRACT.get(
            "access_matrix"
        ),
        "CHRONOLOGICAL_SPLIT_CONTRACT.access_matrix",
    )
)

require_unique_columns(
    SPLIT_ACCESS_MATRIX,
    "SPLIT_ACCESS_MATRIX",
)

require_columns(
    SPLIT_ACCESS_MATRIX,
    [
        "partition",
        "model_selection_access",
        "parameter_estimation_access",
        "final_evaluation_access",
        "claim_authority",
    ],
    "SPLIT_ACCESS_MATRIX",
)

require(
    set(
        SPLIT_ACCESS_MATRIX[
            "partition"
        ].astype(str)
    )
    == set(PARTITION_ORDER),
    "Split access matrix does not cover all partitions.",
)

engineering_holdout_access = (
    SPLIT_ACCESS_MATRIX.loc[
        SPLIT_ACCESS_MATRIX[
            "partition"
        ].eq("ENGINEERING_HOLDOUT")
    ]
)

require(
    len(engineering_holdout_access) == 1,
    (
        "Split access matrix must contain exactly one "
        "ENGINEERING_HOLDOUT row."
    ),
)

require(
    not bool(
        engineering_holdout_access.iloc[0][
            "model_selection_access"
        ]
    ),
    (
        "ENGINEERING_HOLDOUT must remain unavailable for "
        "model selection."
    ),
)

require(
    not bool(
        engineering_holdout_access.iloc[0][
            "claim_authority"
        ]
    ),
    (
        "ENGINEERING_HOLDOUT must not carry claim authority "
        "in engineering-reproduction mode."
    ),
)


# ------------------------------------------------------------
# Market-state feature history rule
# ------------------------------------------------------------

SPLIT_HISTORY_RULES = pd.DataFrame.from_records(
    require_list(
        CHRONOLOGICAL_SPLIT_CONTRACT.get(
            "history_rules"
        ),
        "CHRONOLOGICAL_SPLIT_CONTRACT.history_rules",
    )
)

require_unique_columns(
    SPLIT_HISTORY_RULES,
    "SPLIT_HISTORY_RULES",
)

require_columns(
    SPLIT_HISTORY_RULES,
    [
        "stage",
        "history_carry_allowed",
        "history_usage",
        "scored_pre_boundary_events",
    ],
    "SPLIT_HISTORY_RULES",
)

market_state_history_rows = (
    SPLIT_HISTORY_RULES.loc[
        SPLIT_HISTORY_RULES[
            "stage"
        ].eq("MARKET_STATE_FEATURES")
    ]
)

require(
    len(market_state_history_rows) == 1,
    (
        "Split history rules must contain exactly one "
        "MARKET_STATE_FEATURES row."
    ),
)

MARKET_STATE_HISTORY_RULE = (
    market_state_history_rows.iloc[0].to_dict()
)

require(
    bool(
        MARKET_STATE_HISTORY_RULE[
            "history_carry_allowed"
        ]
    ),
    (
        "Market-state features must permit causal history "
        "carry across partition boundaries."
    ),
)

require(
    not bool(
        MARKET_STATE_HISTORY_RULE[
            "scored_pre_boundary_events"
        ]
    ),
    (
        "Pre-boundary observations may initialize state but "
        "may not be scored in the later partition."
    ),
)


# ------------------------------------------------------------
# Cross-contract hash reconciliation
# ------------------------------------------------------------

RUN_CONFIG_COMPONENT_HASHES = require_mapping(
    V0_1_RUN_CONFIG.get(
        "component_hashes"
    ),
    "V0_1_RUN_CONFIG.component_hashes",
)

DECISION_CONTRACT_EXPLORATION_RULES = (
    require_mapping(
        DECISION_AND_TOLERANCE_CONTRACT.get(
            "exploration_rules"
        ),
        (
            "DECISION_AND_TOLERANCE_CONTRACT."
            "exploration_rules"
        ),
    )
)

require(
    DECISION_CONTRACT_EXPLORATION_RULES.get(
        "may_use_future_labels"
    )
    is False,
    (
        "Decision contract improperly permits future labels "
        "during feature selection."
    ),
)

require(
    DECISION_CONTRACT_EXPLORATION_RULES.get(
        "may_access_final_partition_for_selection"
    )
    is False,
    (
        "Decision contract improperly permits final-partition "
        "selection access."
    ),
)

require(
    DECISION_CONTRACT_EXPLORATION_RULES.get(
        "may_modify_raw_inputs"
    )
    is False,
    "Decision contract permits modification of raw inputs.",
)

require(
    run_identity_configuration.get(
        "chronological_split_contract_hash"
    )
    == EXPECTED_CHRONOLOGICAL_SPLIT_CONTRACT_PAYLOAD_SHA256,
    (
        "Run identity and split-contract payload hash "
        "disagree."
    ),
)

require(
    DECISION_AND_TOLERANCE_CONTRACT.get(
        "chronological_split_contract_hash"
    )
    == EXPECTED_CHRONOLOGICAL_SPLIT_CONTRACT_PAYLOAD_SHA256,
    (
        "Decision contract and split-contract payload hash "
        "disagree."
    ),
)


# ------------------------------------------------------------
# Notebook 00 authority gate table
# ------------------------------------------------------------

NOTEBOOK_00_AUTHORITY_GATES = pd.DataFrame(
    [
        {
            "gate": "notebook_00_manifest_envelope_verified",
            "severity": "BLOCKING",
            "passed": True,
            "evidence": str(
                UPSTREAM_CONTROL_PATHS[
                    "notebook_00_output_manifest"
                ]
            ),
        },
        {
            "gate": "required_notebook_00_artifacts_verified",
            "severity": "BLOCKING",
            "passed": (
                len(
                    NOTEBOOK_00_REQUIRED_ARTIFACT_AUDIT
                )
                == len(
                    REQUIRED_NOTEBOOK_00_ARTIFACT_TYPES
                )
            ),
            "evidence": (
                f"verified="
                f"{len(NOTEBOOK_00_REQUIRED_ARTIFACT_AUDIT)}/"
                f"{len(REQUIRED_NOTEBOOK_00_ARTIFACT_TYPES)}"
            ),
        },
        {
            "gate": "run_config_payload_identity_verified",
            "severity": "BLOCKING",
            "passed": (
                observed_run_config_payload_sha256
                == EXPECTED_RUN_CONFIG_SHA256
            ),
            "evidence": (
                observed_run_config_payload_sha256
            ),
        },
        {
            "gate": "run_identity_verified",
            "severity": "BLOCKING",
            "passed": (
                observed_run_identity_hash
                == EXPECTED_RUN_IDENTITY_SHA256
            ),
            "evidence": observed_run_identity_hash,
        },
        {
            "gate": "split_contract_payload_verified",
            "severity": "BLOCKING",
            "passed": (
                observed_split_payload_sha256
                == EXPECTED_CHRONOLOGICAL_SPLIT_CONTRACT_PAYLOAD_SHA256
            ),
            "evidence": observed_split_payload_sha256,
        },
        {
            "gate": "split_intervals_contiguous",
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                f"partitions={len(SPLIT_BOUNDARY_TABLE)}"
            ),
        },
        {
            "gate": "matched_trade_count_reconciles",
            "severity": "BLOCKING",
            "passed": (
                int(
                    SPLIT_BOUNDARY_TABLE[
                        "trade_row_count"
                    ].sum()
                )
                == EXPECTED_MATCHED_TRADE_ROWS
            ),
            "evidence": (
                f"trade_rows="
                f"{int(SPLIT_BOUNDARY_TABLE['trade_row_count'].sum())}"
            ),
        },
        {
            "gate": "market_state_history_carry_authorized",
            "severity": "BLOCKING",
            "passed": bool(
                MARKET_STATE_HISTORY_RULE[
                    "history_carry_allowed"
                ]
            ),
            "evidence": str(
                MARKET_STATE_HISTORY_RULE[
                    "history_usage"
                ]
            ),
        },
        {
            "gate": "pre_boundary_rows_not_scored",
            "severity": "BLOCKING",
            "passed": not bool(
                MARKET_STATE_HISTORY_RULE[
                    "scored_pre_boundary_events"
                ]
            ),
            "evidence": (
                "scored_pre_boundary_events=False"
            ),
        },
        {
            "gate": "engineering_holdout_not_claim_bearing",
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                "claim_bearing_holdout_available=False"
            ),
        },
        {
            "gate": "partitions_not_independent",
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                "partitions_are_independent=False"
            ),
        },
    ]
)

NOTEBOOK_00_AUTHORITY_GATES[
    "status"
] = np.select(
    [
        NOTEBOOK_00_AUTHORITY_GATES[
            "passed"
        ],
        NOTEBOOK_00_AUTHORITY_GATES[
            "severity"
        ].eq("BLOCKING"),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

notebook_00_blocking_failures = (
    NOTEBOOK_00_AUTHORITY_GATES.loc[
        NOTEBOOK_00_AUTHORITY_GATES[
            "severity"
        ].eq("BLOCKING")
        & ~NOTEBOOK_00_AUTHORITY_GATES[
            "passed"
        ]
    ]
)

require(
    notebook_00_blocking_failures.empty,
    (
        "Notebook 00 authority verification has one or more "
        "blocking failures."
    ),
)


# ------------------------------------------------------------
# Immutable authority objects for downstream cells
# ------------------------------------------------------------

NOTEBOOK_00_AUTHORITY_VERIFIED: Final[
    bool
] = True

AUTHORITATIVE_PARTITION_ORDER: Final[
    tuple[str, ...]
] = tuple(
    SPLIT_BOUNDARY_TABLE[
        "partition"
    ].astype(str)
)

AUTHORITATIVE_PARTITION_BOUNDARIES: Final[
    tuple[Mapping[str, Any], ...]
] = tuple(
    MappingProxyType(
        dict(record)
    )
    for record in (
        SPLIT_BOUNDARY_TABLE.to_dict(
            orient="records"
        )
    )
)


# ------------------------------------------------------------
# Display compact authority summaries
# ------------------------------------------------------------

display(
    NOTEBOOK_00_REQUIRED_ARTIFACT_AUDIT[
        [
            "artifact_type",
            "acceptance_status",
            "size_bytes",
            "payload_sha256",
            "resolved_path",
        ]
    ]
)

display(
    SPLIT_BOUNDARY_TABLE[
        [
            "partition_order",
            "partition",
            "collector_sequence_start",
            "collector_sequence_end_exclusive",
            "receipt_time_start_ns",
            "receipt_time_end_ns_exclusive",
            "trade_row_count",
            "depth_row_count",
            "claim_authority",
        ]
    ]
)

display(
    SPLIT_HISTORY_RULES[
        [
            "stage",
            "history_carry_allowed",
            "scored_pre_boundary_events",
            "history_usage",
        ]
    ]
)

display(
    NOTEBOOK_00_AUTHORITY_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "notebook_00_authority_verified": (
        NOTEBOOK_00_AUTHORITY_VERIFIED
    ),
    "manifest_artifact_count": int(
        len(NOTEBOOK_00_ARTIFACT_REGISTRY)
    ),
    "required_artifact_count": int(
        len(
            NOTEBOOK_00_REQUIRED_ARTIFACT_AUDIT
        )
    ),
    "source_registry_primary_file_count": int(
        len(
            AUTHORITATIVE_RAW_SOURCE_MANIFEST
        )
    ),
    "source_set_sha256": (
        EXPECTED_SOURCE_SET_SHA256
    ),
    "run_config_sha256": (
        observed_run_config_payload_sha256
    ),
    "run_identity_sha256": (
        observed_run_identity_hash
    ),
    "split_contract_payload_sha256": (
        observed_split_payload_sha256
    ),
    "partition_order": list(
        AUTHORITATIVE_PARTITION_ORDER
    ),
    "partition_count": int(
        len(SPLIT_BOUNDARY_TABLE)
    ),
    "partition_trade_rows": int(
        SPLIT_BOUNDARY_TABLE[
            "trade_row_count"
        ].sum()
    ),
    "market_state_history_carry_allowed": bool(
        MARKET_STATE_HISTORY_RULE[
            "history_carry_allowed"
        ]
    ),
    "pre_boundary_events_scored": bool(
        MARKET_STATE_HISTORY_RULE[
            "scored_pre_boundary_events"
        ]
    ),
    "claim_bearing_holdout_available": bool(
        CHRONOLOGICAL_SPLIT_CONTRACT[
            "claim_bearing_holdout_available"
        ]
    ),
    "partitions_are_independent": bool(
        CHRONOLOGICAL_SPLIT_CONTRACT[
            "partitions_are_independent"
        ]
    ),
    "verified_at_utc": utc_now_iso(),
}

,artifact_type,acceptance_status,size_bytes,payload_sha256,resolved_path
0,CHRONOLOGICAL_SPLIT_CONTRACT,CONDITIONAL PASS,7330,3b7e8d46f43d8a4dd7b7a1f3d9a61c2c92d3f3643042a8b01968ddc7e0fb4624,D:\Clown Project\V0.1\config\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__00_V01_RUN_CONTRACT__split_contract.json
1,DECISION_AND_TOLERANCE_CONTRACT,CONDITIONAL PASS,13413,31e054874e4072f0d90a0f7dfd14e1531f54f22e3c5beec824534b53a75c43b2,D:\Clown Project\V0.1\config\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__00_V01_RUN_CONTRACT__decision_and_tolerance_contract.json
2,MARKET_DATA_CONTRACT,CONDITIONAL PASS,3556,aadc573f7d891385115db3029a51b242f5c1213313b9b8b904ee6cdd34da9f15,D:\Clown Project\V0.1\config\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__00_V01_RUN_CONTRACT__market_data_contract.json
3,MISSING_DATA_REJECTION_CONTRACT,CONDITIONAL PASS,24687,27dafdd4a69308d7ff4d64fb0bdde5150c123c92cc425a80027e9a3d0f6eca49,D:\Clown Project\V0.1\config\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__00_V01_RUN_CONTRACT__missing_data_rejection_contract.json
4,V0_0_SOURCE_REGISTRY,CONDITIONAL PASS,21284,06d50b25d11a4b4a60d5882afaf60079bb5c357b7afbb9d0e401d963719267dd,D:\Clown Project\V0.1\config\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__00_V01_RUN_CONTRACT__v0_0_source_registry.json
5,V0_1_RUN_CONFIG,CONDITIONAL PASS,12529,14aea0efb3c7b6a193b8c4575a440babe8265d2935c6a770bee995f688d59617,D:\Clown Project\V0.1\config\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__00_V01_RUN_CONTRACT__run_config.json
6,V0_1_RUN_IDENTITY,CONDITIONAL PASS,3320,aa302fc391c4cb332e30549912ff7d03a2c6bea388998b2072c84a686d0e0405,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__00_V01_RUN_CONTRACT__run_identity.json

   partition_order            partition  collector_sequence_start  collector_sequence_end_exclusive  receipt_time_start_ns  receipt_time_end_ns_exclusive  trade_row_count  depth_row_count  claim_authority
0                1          DEVELOPMENT                         1                             51840    1783665467531985400            1783667269391572100            33820            18019            False
1                2          CALIBRATION                     51840                             72576    1783667269391572100            1783667989690751200            13532             7204            False
2                3           VALIDATION                     72576                             88127    1783667989690751200            1783668525057534700            10198             5353            False
3                4  ENGINEERING_HOLDOUT                     88127                            103678    1783668525057534700            1783669066749750801            10133             5418            False

                   stage  history_carry_allowed  scored_pre_boundary_events                                                                                                            history_usage
0    BOOK_RECONSTRUCTION                   True                       False                                               Carry the last valid reconstructed book state across partition boundaries.
1   TRADE_BOOK_ALIGNMENT                   True                       False                                   Use only book states causally available before each trade in collector-sequence order.
2  MARKET_STATE_FEATURES                   True                       False                       Pre-boundary observations may initialize rolling state, but cannot be scored inside the partition.
3       HAWKES_INTENSITY                   True                       False  Earlier events may initialize excitation history; partition likelihood and diagnostics begin at the partition boundary.
4        MODEL_SELECTION                  False                       False                                          The final reserved partition cannot influence model choice or parameter tuning.

                                       gate  severity   status                                                                                                                                                                     evidence
0    notebook_00_manifest_envelope_verified  BLOCKING     PASS  D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__00_V01_RUN_CONTRACT__notebook_00_output_manifest.json
1   required_notebook_00_artifacts_verified  BLOCKING     PASS                                                                                                                                                                 verified=7/7
2      run_config_payload_identity_verified  BLOCKING     PASS                                                                                                             14aea0efb3c7b6a193b8c4575a440babe8265d2935c6a770bee995f688d59617
3                     run_identity_verified  BLOCKING     PASS                                                                                                             5eb89cf073c036d70e3767df4b35ace7c31822e52e9b9df19204c42e37fe4198
4           split_contract_payload_verified  BLOCKING     PASS                                                                                                             3b7e8d46f43d8a4dd7b7a1f3d9a61c2c92d3f3643042a8b01968ddc7e0fb4624
5                split_intervals_contiguous  BLOCKING     PASS                                                                                                                                                                 partitions=4
6            matched_trade_count_reconciles  BLOCKING     PASS                                                                                                                                                             trade_rows=67683
7     market_state_history_carry_authorized  BLOCKING     PASS                                                                           Pre-boundary observations may initialize rolling state, but cannot be scored inside the partition.
8              pre_boundary_rows_not_scored  BLOCKING     PASS                                                                                                                                             scored_pre_boundary_events=False
9     engineering_holdout_not_claim_bearing   WARNING  WARNING                                                                                                                                        claim_bearing_holdout_available=False
10               partitions_not_independent   WARNING  WARNING                                                                                                                                             partitions_are_independent=False

{'status': 'PASS',
 'notebook_00_authority_verified': True,
 'manifest_artifact_count': 21,
 'required_artifact_count': 7,
 'source_registry_primary_file_count': 5,
 'source_set_sha256': '132c83531eec615d279408b5c06f402973114ba3058dfadd2fe58e2e67184c4b',
 'run_config_sha256': '14aea0efb3c7b6a193b8c4575a440babe8265d2935c6a770bee995f688d59617',
 'run_identity_sha256': '5eb89cf073c036d70e3767df4b35ace7c31822e52e9b9df19204c42e37fe4198',
 'split_contract_payload_sha256': '3b7e8d46f43d8a4dd7b7a1f3d9a61c2c92d3f3643042a8b01968ddc7e0fb4624',
 'partition_order': ['DEVELOPMENT',
  'CALIBRATION',
  'VALIDATION',
  'ENGINEERING_HOLDOUT'],
 'partition_count': 4,
 'partition_trade_rows': 67683,
 'market_state_history_carry_allowed': True,
 'pre_boundary_events_scored': False,
 'claim_bearing_holdout_available': False,
 'partitions_are_independent': False,
 'verified_at_utc': '2026-07-19T09:33:46.198446+00:00'}

In [4]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 05 — Notebook 02 visible-book authority, manifested
#           path resolution, table loading, and structural audit
# ============================================================


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "NOTEBOOK_00_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 00 authority has not been verified.",
)

require(
    globals().get(
        "UPSTREAM_CONTROL_ARTIFACTS_VERIFIED",
        False,
    )
    is True,
    "Upstream control artifacts have not been verified.",
)


# ------------------------------------------------------------
# Frozen Notebook 02 authority
# ------------------------------------------------------------

NOTEBOOK_02_PRODUCER: Final[str] = (
    "02_VISIBLE_BOOK_RECONSTRUCTION.ipynb"
)

NOTEBOOK_02_EXPECTED_FINAL_STATUS: Final[str] = (
    "PASS_WITH_REFERENCE_WARNINGS"
)

NOTEBOOK_02_EXPECTED_NEXT_NOTEBOOK: Final[str] = (
    "03_CAUSAL_TRADE_BOOK_ALIGNMENT.ipynb"
)

NOTEBOOK_02_EXPECTED_TOP_N_LEVELS: Final[int] = 10

REQUIRED_NOTEBOOK_02_DOWNSTREAM_ARTIFACTS: Final[
    tuple[str, ...]
] = (
    "RECONSTRUCTED_BOOK_STATES",
    "TOP_10_VISIBLE_BOOK_WIDE",
    "VISIBLE_TOP_10_BOOK_LONG",
    "UPDATE_CONTINUITY_REPORT",
    "RECONSTRUCTION_SESSION_LEDGER",
    "BOOK_QUALITY_GATES",
)


# ------------------------------------------------------------
# Notebook 02-specific envelope interpretation
#
# Notebook 02 metadata names differ from Notebook 00.
# ------------------------------------------------------------

def unwrap_notebook_02_artifact(
    document: Mapping[str, Any],
    *,
    artifact_label: str,
    expected_artifact_type: str,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Validate and unwrap one Notebook 02 JSON artifact."""
    require(
        classify_json_shape(document)
        == JSON_SHAPE_ENVELOPED,
        f"{artifact_label} must be enveloped JSON.",
    )

    metadata = require_mapping(
        document.get("artifact_metadata"),
        f"{artifact_label}.artifact_metadata",
    )

    payload = require_mapping(
        document.get("payload"),
        f"{artifact_label}.payload",
    )

    required_metadata_fields = {
        "artifact_type",
        "source_run_prefix",
        "source_set_sha256",
        "v0_1_run_id",
        "run_config_sha256",
        "run_identity_sha256",
        "producing_notebook",
        "producing_notebook_name",
        "notebook_schema_version",
        "created_at_utc",
        "payload_sha256",
        "acceptance_status",
    }

    missing_metadata_fields = sorted(
        required_metadata_fields - set(metadata)
    )

    require(
        not missing_metadata_fields,
        (
            f"{artifact_label} metadata is missing fields: "
            f"{missing_metadata_fields}"
        ),
    )

    require(
        metadata["artifact_type"]
        == expected_artifact_type,
        (
            f"{artifact_label} artifact-type mismatch:\n"
            f"expected={expected_artifact_type!r}\n"
            f"observed={metadata['artifact_type']!r}"
        ),
    )

    require(
        metadata["source_run_prefix"]
        == SOURCE_RUN_PREFIX,
        f"{artifact_label} source-run mismatch.",
    )

    require(
        metadata["source_set_sha256"]
        == EXPECTED_SOURCE_SET_SHA256,
        f"{artifact_label} source-set hash mismatch.",
    )

    require(
        metadata["v0_1_run_id"]
        == V01_RUN_ID,
        f"{artifact_label} V0.1 run-ID mismatch.",
    )

    require(
        metadata["run_config_sha256"]
        == EXPECTED_RUN_CONFIG_SHA256,
        f"{artifact_label} run-config hash mismatch.",
    )

    require(
        metadata["run_identity_sha256"]
        == EXPECTED_RUN_IDENTITY_SHA256,
        f"{artifact_label} run-identity hash mismatch.",
    )

    require(
        metadata["producing_notebook"]
        == NOTEBOOK_02_PRODUCER,
        (
            f"{artifact_label} producing-notebook mismatch: "
            f"{metadata['producing_notebook']!r}"
        ),
    )

    require(
        metadata["acceptance_status"]
        == NOTEBOOK_02_EXPECTED_FINAL_STATUS,
        (
            f"{artifact_label} acceptance-status mismatch:\n"
            f"expected={NOTEBOOK_02_EXPECTED_FINAL_STATUS!r}\n"
            f"observed={metadata['acceptance_status']!r}"
        ),
    )

    registered_payload_hash = require_sha256(
        str(metadata["payload_sha256"]),
        f"{artifact_label}.payload_sha256",
    )

    observed_payload_hash = canonical_json_sha256(
        payload
    )

    require(
        observed_payload_hash
        == registered_payload_hash,
        (
            f"{artifact_label} canonical payload mismatch:\n"
            f"registered={registered_payload_hash}\n"
            f"observed={observed_payload_hash}"
        ),
    )

    return metadata, payload


# ------------------------------------------------------------
# Parse and verify Notebook 02 manifest and handoff
# ------------------------------------------------------------

NOTEBOOK_02_OUTPUT_MANIFEST_DOCUMENT = (
    UPSTREAM_CONTROL_DOCUMENTS[
        "notebook_02_output_manifest"
    ]
)

NOTEBOOK_02_HANDOFF_DOCUMENT = (
    UPSTREAM_CONTROL_DOCUMENTS[
        "notebook_02_to_03_handoff"
    ]
)

(
    NOTEBOOK_02_OUTPUT_MANIFEST_METADATA,
    NOTEBOOK_02_OUTPUT_MANIFEST_PAYLOAD,
) = unwrap_notebook_02_artifact(
    NOTEBOOK_02_OUTPUT_MANIFEST_DOCUMENT,
    artifact_label="Notebook 02 output manifest",
    expected_artifact_type=(
        "NOTEBOOK_02_OUTPUT_MANIFEST"
    ),
)

(
    NOTEBOOK_02_HANDOFF_METADATA,
    NOTEBOOK_02_HANDOFF_PAYLOAD,
) = unwrap_notebook_02_artifact(
    NOTEBOOK_02_HANDOFF_DOCUMENT,
    artifact_label="Notebook 02 to Notebook 03 handoff",
    expected_artifact_type=(
        "NOTEBOOK_02_TO_NOTEBOOK_03_HANDOFF"
    ),
)


# ------------------------------------------------------------
# Manifest and handoff identity reconciliation
# ------------------------------------------------------------

expected_notebook_02_manifest_fields = {
    "manifest_type": "NOTEBOOK_02_OUTPUT_MANIFEST",
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": EXPECTED_SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "v0_1_run_config_hash": EXPECTED_RUN_CONFIG_SHA256,
    "v0_1_run_identity_hash": EXPECTED_RUN_IDENTITY_SHA256,
    "producing_notebook": NOTEBOOK_02_PRODUCER,
    "operating_mode": OPERATING_MODE,
    "final_status": NOTEBOOK_02_EXPECTED_FINAL_STATUS,
    "notebook_03_authorized": True,
}

for field_name, expected_value in (
    expected_notebook_02_manifest_fields.items()
):
    observed_value = (
        NOTEBOOK_02_OUTPUT_MANIFEST_PAYLOAD.get(
            field_name
        )
    )

    require(
        observed_value == expected_value,
        (
            f"Notebook 02 manifest field {field_name!r} "
            f"mismatch:\n"
            f"expected={expected_value!r}\n"
            f"observed={observed_value!r}"
        ),
    )


expected_notebook_02_handoff_fields = {
    "handoff_type": "NOTEBOOK_02_TO_NOTEBOOK_03_HANDOFF",
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": EXPECTED_SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "v0_1_run_config_hash": EXPECTED_RUN_CONFIG_SHA256,
    "v0_1_run_identity_hash": EXPECTED_RUN_IDENTITY_SHA256,
    "producing_notebook": NOTEBOOK_02_PRODUCER,
    "next_notebook": NOTEBOOK_02_EXPECTED_NEXT_NOTEBOOK,
    "notebook_02_final_status": (
        NOTEBOOK_02_EXPECTED_FINAL_STATUS
    ),
    "notebook_03_authorized": True,
    "operating_mode": OPERATING_MODE,
    "canonical_timezone": CANONICAL_TIMEZONE,
    "ordering_authority": PRIMARY_ORDERING_AUTHORITY,
    "top_n_levels": NOTEBOOK_02_EXPECTED_TOP_N_LEVELS,
    "accepted_book_states": (
        EXPECTED_RECONSTRUCTED_BOOK_STATES
    ),
    "top_10_wide_rows": EXPECTED_TOP10_WIDE_ROWS,
    "top_10_long_rows": EXPECTED_TOP10_LONG_ROWS,
    "v0_0_reference_used_as_authority": False,
}

for field_name, expected_value in (
    expected_notebook_02_handoff_fields.items()
):
    observed_value = NOTEBOOK_02_HANDOFF_PAYLOAD.get(
        field_name
    )

    require(
        observed_value == expected_value,
        (
            f"Notebook 02 handoff field {field_name!r} "
            f"mismatch:\n"
            f"expected={expected_value!r}\n"
            f"observed={observed_value!r}"
        ),
    )

require(
    NOTEBOOK_02_HANDOFF_METADATA[
        "payload_sha256"
    ]
    == EXPECTED_NOTEBOOK_02_TO_03_HANDOFF_PAYLOAD_SHA256,
    (
        "Notebook 02 handoff payload identity differs from "
        "the frozen authority-map value."
    ),
)


# ------------------------------------------------------------
# Construct the actual Notebook 02 artifact registry
# ------------------------------------------------------------

notebook_02_artifact_records = require_list(
    NOTEBOOK_02_OUTPUT_MANIFEST_PAYLOAD.get(
        "artifacts"
    ),
    "NOTEBOOK_02_OUTPUT_MANIFEST_PAYLOAD.artifacts",
)

NOTEBOOK_02_ARTIFACT_REGISTRY = (
    pd.DataFrame.from_records(
        notebook_02_artifact_records
    )
)

require_unique_columns(
    NOTEBOOK_02_ARTIFACT_REGISTRY,
    "NOTEBOOK_02_ARTIFACT_REGISTRY",
)

require_columns(
    NOTEBOOK_02_ARTIFACT_REGISTRY,
    [
        "artifact_type",
        "format",
        "relative_path",
        "size_bytes",
        "sha256",
        "row_count",
        "column_count",
        "acceptance_status",
    ],
    "NOTEBOOK_02_ARTIFACT_REGISTRY",
)

require(
    NOTEBOOK_02_ARTIFACT_REGISTRY[
        "artifact_type"
    ].notna().all(),
    "Notebook 02 registry contains a null artifact type.",
)

require(
    not NOTEBOOK_02_ARTIFACT_REGISTRY[
        "artifact_type"
    ].duplicated().any(),
    "Notebook 02 registry contains duplicate artifact types.",
)

manifest_artifact_count = (
    NOTEBOOK_02_OUTPUT_MANIFEST_PAYLOAD.get(
        "artifact_count"
    )
)

if manifest_artifact_count is not None:
    require(
        int(manifest_artifact_count)
        == len(NOTEBOOK_02_ARTIFACT_REGISTRY),
        (
            "Notebook 02 manifest artifact_count does not "
            "match the artifact list."
        ),
    )


# ------------------------------------------------------------
# Handoff downstream-input registry
# ------------------------------------------------------------

NOTEBOOK_02_REQUIRED_DOWNSTREAM_INPUTS = (
    require_mapping(
        NOTEBOOK_02_HANDOFF_PAYLOAD.get(
            "required_downstream_inputs"
        ),
        (
            "NOTEBOOK_02_HANDOFF_PAYLOAD."
            "required_downstream_inputs"
        ),
    )
)

require(
    set(
        REQUIRED_NOTEBOOK_02_DOWNSTREAM_ARTIFACTS
    )
    == set(
        NOTEBOOK_02_REQUIRED_DOWNSTREAM_INPUTS
    ),
    (
        "Notebook 02 handoff downstream-input set mismatch:\n"
        f"expected="
        f"{sorted(REQUIRED_NOTEBOOK_02_DOWNSTREAM_ARTIFACTS)}\n"
        f"observed="
        f"{sorted(NOTEBOOK_02_REQUIRED_DOWNSTREAM_INPUTS)}"
    ),
)


# ------------------------------------------------------------
# Resolve one Notebook 02 table using both:
# - the output manifest;
# - the handoff required_downstream_inputs mapping.
# ------------------------------------------------------------

def resolve_notebook_02_table(
    artifact_type: str,
) -> tuple[Path, pd.Series]:
    """Resolve and verify one required Notebook 02 CSV."""
    manifest_matches = (
        NOTEBOOK_02_ARTIFACT_REGISTRY.loc[
            NOTEBOOK_02_ARTIFACT_REGISTRY[
                "artifact_type"
            ].eq(artifact_type)
        ]
    )

    require(
        len(manifest_matches) == 1,
        (
            f"Expected one Notebook 02 {artifact_type} "
            f"manifest record; observed={len(manifest_matches)}."
        ),
    )

    record = manifest_matches.iloc[0]

    require(
        str(record["format"]).lower() == "csv",
        (
            f"{artifact_type} must be a manifested CSV; "
            f"observed={record['format']!r}."
        ),
    )

    manifest_relative_path = str(
        record["relative_path"]
    )

    handoff_relative_path = str(
        NOTEBOOK_02_REQUIRED_DOWNSTREAM_INPUTS[
            artifact_type
        ]
    )

    require(
        Path(manifest_relative_path)
        == Path(handoff_relative_path),
        (
            f"{artifact_type} path differs between manifest "
            f"and handoff:\n"
            f"manifest={manifest_relative_path}\n"
            f"handoff={handoff_relative_path}"
        ),
    )

    artifact_path = (
        V01_ROOT / manifest_relative_path
    ).resolve(strict=True)

    require(
        path_is_within(
            artifact_path,
            V01_ROOT,
        ),
        (
            f"{artifact_type} resolves outside V0.1: "
            f"{artifact_path}"
        ),
    )

    require(
        not path_is_within(
            artifact_path,
            V00_ROOT,
        ),
        (
            f"{artifact_type} improperly resolves inside V0.0: "
            f"{artifact_path}"
        ),
    )

    require_file(
        artifact_path,
        artifact_type,
    )

    registered_size = int(
        record["size_bytes"]
    )

    observed_size = int(
        artifact_path.stat().st_size
    )

    require(
        registered_size == observed_size,
        (
            f"{artifact_type} file-size mismatch:\n"
            f"registered={registered_size}\n"
            f"observed={observed_size}"
        ),
    )

    registered_file_hash = require_sha256(
        str(record["sha256"]),
        f"{artifact_type}.sha256",
    )

    observed_file_hash = sha256_file(
        artifact_path
    )

    require(
        observed_file_hash
        == registered_file_hash,
        (
            f"{artifact_type} raw-file SHA-256 mismatch:\n"
            f"registered={registered_file_hash}\n"
            f"observed={observed_file_hash}"
        ),
    )

    require(
        str(record["acceptance_status"])
        == NOTEBOOK_02_EXPECTED_FINAL_STATUS,
        (
            f"{artifact_type} acceptance-status mismatch: "
            f"{record['acceptance_status']!r}"
        ),
    )

    return artifact_path, record


# ------------------------------------------------------------
# Load all required Notebook 02 downstream tables
# ------------------------------------------------------------

notebook_02_data_paths: dict[str, Path] = {}
notebook_02_tables: dict[str, pd.DataFrame] = {}
notebook_02_table_audit_rows: list[
    dict[str, Any]
] = []

for artifact_type in (
    REQUIRED_NOTEBOOK_02_DOWNSTREAM_ARTIFACTS
):
    table_path, manifest_record = (
        resolve_notebook_02_table(
            artifact_type
        )
    )

    table = pd.read_csv(
        table_path,
        low_memory=False,
    )

    require_unique_columns(
        table,
        artifact_type,
    )

    registered_row_count = int(
        manifest_record["row_count"]
    )

    registered_column_count = int(
        manifest_record["column_count"]
    )

    require(
        len(table) == registered_row_count,
        (
            f"{artifact_type} row-count mismatch:\n"
            f"registered={registered_row_count:,}\n"
            f"observed={len(table):,}"
        ),
    )

    require(
        table.shape[1]
        == registered_column_count,
        (
            f"{artifact_type} column-count mismatch:\n"
            f"registered={registered_column_count}\n"
            f"observed={table.shape[1]}"
        ),
    )

    notebook_02_data_paths[
        artifact_type
    ] = table_path

    notebook_02_tables[
        artifact_type
    ] = table

    notebook_02_table_audit_rows.append(
        {
            "artifact_type": artifact_type,
            "resolved_path": str(
                table_path
            ),
            "format": "csv",
            "row_count": int(
                len(table)
            ),
            "column_count": int(
                table.shape[1]
            ),
            "size_bytes": int(
                table_path.stat().st_size
            ),
            "raw_file_sha256": sha256_file(
                table_path
            ),
            "acceptance_status": str(
                manifest_record[
                    "acceptance_status"
                ]
            ),
            "status": "PASS",
        }
    )


NOTEBOOK_02_DATA_PATHS: Final[
    Mapping[str, Path]
] = MappingProxyType(
    dict(notebook_02_data_paths)
)

NOTEBOOK_02_TABLES: Final[
    Mapping[str, pd.DataFrame]
] = MappingProxyType(
    dict(notebook_02_tables)
)

NOTEBOOK_02_TABLE_LOAD_AUDIT = (
    pd.DataFrame.from_records(
        notebook_02_table_audit_rows
    )
    .sort_values(
        "artifact_type",
        kind="stable",
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Register authoritative tables
# ------------------------------------------------------------

RECONSTRUCTED_BOOK_STATES = (
    NOTEBOOK_02_TABLES[
        "RECONSTRUCTED_BOOK_STATES"
    ]
)

TOP_10_VISIBLE_BOOK_WIDE = (
    NOTEBOOK_02_TABLES[
        "TOP_10_VISIBLE_BOOK_WIDE"
    ]
)

VISIBLE_TOP_10_BOOK_LONG = (
    NOTEBOOK_02_TABLES[
        "VISIBLE_TOP_10_BOOK_LONG"
    ]
)

UPDATE_CONTINUITY_REPORT = (
    NOTEBOOK_02_TABLES[
        "UPDATE_CONTINUITY_REPORT"
    ]
)

RECONSTRUCTION_SESSION_LEDGER = (
    NOTEBOOK_02_TABLES[
        "RECONSTRUCTION_SESSION_LEDGER"
    ]
)

BOOK_QUALITY_GATES = (
    NOTEBOOK_02_TABLES[
        "BOOK_QUALITY_GATES"
    ]
)


# ------------------------------------------------------------
# Required actual Notebook 02 schema
# ------------------------------------------------------------

BOOK_LEVEL_COLUMNS: Final[tuple[str, ...]] = tuple(
    column_name
    for level_number in range(
        1,
        NOTEBOOK_02_EXPECTED_TOP_N_LEVELS + 1,
    )
    for column_name in (
        f"bid_price_{level_number}",
        f"bid_quantity_{level_number}",
        f"ask_price_{level_number}",
        f"ask_quantity_{level_number}",
    )
)

RECONSTRUCTED_BOOK_REQUIRED_COLUMNS: Final[
    tuple[str, ...]
] = (
    "reconstruction_session_id",
    "book_state_id",
    "source_position",
    "source_line_number",
    "connection_session_id",
    "collector_sequence",
    "local_receipt_time_ns",
    "local_receipt_time_utc",
    "exchange_event_time_ms",
    "exchange_event_time_utc",
    "first_update_id",
    "final_update_id",
    "continuity_status",
    "partition",
    "state_accepted",
    "best_bid",
    "best_ask",
    "best_bid_quantity",
    "best_ask_quantity",
    "spread",
    "spread_ticks",
    "spread_basis_points",
    "midpoint",
    "microprice",
    "microprice_minus_midpoint",
    "top_level_imbalance",
    "multi_level_imbalance",
    "visible_bid_depth_top_10",
    "visible_ask_depth_top_10",
    "visible_total_depth_top_10",
    "bid_depth_concentration_l1_top_10",
    "ask_depth_concentration_l1_top_10",
    "combined_l1_depth_concentration_top_10",
    "best_bid_change",
    "best_ask_change",
    "midpoint_change",
    "top_of_book_moved",
    "top_10_changed",
    "movement_code",
    "locked_state",
    "crossed_state",
    "incomplete_state",
    "top_10_state_sha256",
    "local_interval_ns",
    "interval_multiple_of_nominal",
    "stale_interval",
    *BOOK_LEVEL_COLUMNS,
)

require_columns(
    RECONSTRUCTED_BOOK_STATES,
    RECONSTRUCTED_BOOK_REQUIRED_COLUMNS,
    "RECONSTRUCTED_BOOK_STATES",
)

require_columns(
    TOP_10_VISIBLE_BOOK_WIDE,
    (
        "reconstruction_session_id",
        "book_state_id",
        "partition",
        "collector_sequence",
        "local_receipt_time_ns",
        "local_receipt_time_utc",
        "exchange_event_time_ms",
        "exchange_event_time_utc",
        "first_update_id",
        "final_update_id",
        "top_10_state_sha256",
        *BOOK_LEVEL_COLUMNS,
    ),
    "TOP_10_VISIBLE_BOOK_WIDE",
)

require_columns(
    VISIBLE_TOP_10_BOOK_LONG,
    (
        "reconstruction_session_id",
        "book_state_id",
        "partition",
        "collector_sequence",
        "local_receipt_time_ns",
        "local_receipt_time_utc",
        "exchange_event_time_ms",
        "exchange_event_time_utc",
        "first_update_id",
        "final_update_id",
        "continuity_status",
        "top_10_state_sha256",
        "side",
        "side_order",
        "level",
        "price",
        "quantity",
    ),
    "VISIBLE_TOP_10_BOOK_LONG",
)

require_columns(
    UPDATE_CONTINUITY_REPORT,
    (
        "reconstruction_session_id",
        "book_state_id",
        "collector_sequence",
        "local_receipt_time_ns",
        "first_update_id",
        "final_update_id",
        "expected_first_update_id",
        "continuity_status",
        "collector_order_valid",
        "local_time_order_valid",
        "state_accepted",
        "resynchronization_required",
        "partition",
    ),
    "UPDATE_CONTINUITY_REPORT",
)

require_columns(
    BOOK_QUALITY_GATES,
    (
        "gate",
        "observed",
        "expected",
        "passed",
        "critical",
    ),
    "BOOK_QUALITY_GATES",
)


# ------------------------------------------------------------
# Boolean coercion helper for persisted CSV values
# ------------------------------------------------------------

def strict_boolean_series(
    series: pd.Series,
    *,
    field_name: str,
) -> pd.Series:
    """Convert an actual persisted Boolean column fail-closed."""
    if pd.api.types.is_bool_dtype(series):
        return series.astype(bool)

    normalized = (
        series.astype("string")
        .str.strip()
        .str.lower()
    )

    mapping = {
        "true": True,
        "false": False,
        "1": True,
        "0": False,
    }

    invalid_values = sorted(
        set(
            normalized.dropna().unique()
        )
        - set(mapping)
    )

    require(
        not invalid_values,
        (
            f"{field_name} contains invalid Boolean values: "
            f"{invalid_values}"
        ),
    )

    converted = normalized.map(mapping)

    require(
        converted.notna().all(),
        f"{field_name} contains missing Boolean values.",
    )

    return converted.astype(bool)


# ------------------------------------------------------------
# Core row-count and identity invariants
# ------------------------------------------------------------

require(
    len(RECONSTRUCTED_BOOK_STATES)
    == EXPECTED_RECONSTRUCTED_BOOK_STATES,
    (
        "Reconstructed-book state count mismatch: "
        f"{len(RECONSTRUCTED_BOOK_STATES):,}"
    ),
)

require(
    len(TOP_10_VISIBLE_BOOK_WIDE)
    == EXPECTED_TOP10_WIDE_ROWS,
    (
        "Top-10 wide row count mismatch: "
        f"{len(TOP_10_VISIBLE_BOOK_WIDE):,}"
    ),
)

require(
    len(VISIBLE_TOP_10_BOOK_LONG)
    == EXPECTED_TOP10_LONG_ROWS,
    (
        "Top-10 long row count mismatch: "
        f"{len(VISIBLE_TOP_10_BOOK_LONG):,}"
    ),
)

book_state_ids = pd.to_numeric(
    RECONSTRUCTED_BOOK_STATES[
        "book_state_id"
    ],
    errors="raise",
).astype("int64")

book_sequences = pd.to_numeric(
    RECONSTRUCTED_BOOK_STATES[
        "collector_sequence"
    ],
    errors="raise",
).astype("int64")

book_local_times = pd.to_numeric(
    RECONSTRUCTED_BOOK_STATES[
        "local_receipt_time_ns"
    ],
    errors="raise",
).astype("int64")

require(
    book_state_ids.is_unique,
    "Reconstructed book_state_id is not unique.",
)

require(
    book_state_ids.is_monotonic_increasing,
    "Reconstructed book_state_id is not increasing.",
)

require(
    book_sequences.is_unique,
    "Book collector_sequence is not unique.",
)

require(
    book_sequences.is_monotonic_increasing,
    "Book collector_sequence is not increasing.",
)

require(
    book_local_times.is_monotonic_increasing,
    "Book local receipt time reverses.",
)

require(
    set(
        RECONSTRUCTED_BOOK_STATES[
            "partition"
        ].astype(str).unique()
    )
    == set(PARTITION_ORDER),
    "Reconstructed-book partitions do not match Notebook 00.",
)

observed_book_partition_order = (
    RECONSTRUCTED_BOOK_STATES[
        "partition"
    ]
    .astype(str)
    .map(PARTITION_ORDER_MAP)
)

require(
    observed_book_partition_order.notna().all(),
    "A reconstructed book state has an unknown partition.",
)

require(
    observed_book_partition_order.is_monotonic_increasing,
    "Reconstructed-book partition order reverses.",
)


# ------------------------------------------------------------
# State acceptance and structural quality
# ------------------------------------------------------------

state_accepted = strict_boolean_series(
    RECONSTRUCTED_BOOK_STATES[
        "state_accepted"
    ],
    field_name="RECONSTRUCTED_BOOK_STATES.state_accepted",
)

locked_state = strict_boolean_series(
    RECONSTRUCTED_BOOK_STATES[
        "locked_state"
    ],
    field_name="RECONSTRUCTED_BOOK_STATES.locked_state",
)

crossed_state = strict_boolean_series(
    RECONSTRUCTED_BOOK_STATES[
        "crossed_state"
    ],
    field_name="RECONSTRUCTED_BOOK_STATES.crossed_state",
)

incomplete_state = strict_boolean_series(
    RECONSTRUCTED_BOOK_STATES[
        "incomplete_state"
    ],
    field_name="RECONSTRUCTED_BOOK_STATES.incomplete_state",
)

require(
    state_accepted.all(),
    "At least one reconstructed book state is not accepted.",
)

require(
    not locked_state.any(),
    "At least one reconstructed state is locked.",
)

require(
    not crossed_state.any(),
    "At least one reconstructed state is crossed.",
)

require(
    not incomplete_state.any(),
    "At least one reconstructed state is incomplete.",
)


# ------------------------------------------------------------
# Numeric visible-book invariants
# ------------------------------------------------------------

def finite_numeric_series(
    frame: pd.DataFrame,
    column_name: str,
) -> pd.Series:
    """Return one required finite numeric series."""
    values = pd.to_numeric(
        frame[column_name],
        errors="raise",
    ).astype("float64")

    require(
        np.isfinite(values.to_numpy()).all(),
        f"{column_name} contains non-finite values.",
    )

    return values


best_bid = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "best_bid",
)

best_ask = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "best_ask",
)

best_bid_quantity = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "best_bid_quantity",
)

best_ask_quantity = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "best_ask_quantity",
)

spread = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "spread",
)

midpoint = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "midpoint",
)

microprice = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "microprice",
)

top_level_imbalance = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "top_level_imbalance",
)

multi_level_imbalance = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "multi_level_imbalance",
)

require(
    (best_bid > 0).all()
    and (best_ask > 0).all(),
    "Best prices must be positive.",
)

require(
    (best_bid_quantity > 0).all()
    and (best_ask_quantity > 0).all(),
    "Level-one quantities must be positive.",
)

require(
    (best_bid < best_ask).all(),
    "At least one book state is locked or crossed.",
)

require(
    np.allclose(
        spread.to_numpy(),
        (
            best_ask - best_bid
        ).to_numpy(),
        rtol=0.0,
        atol=1e-10,
    ),
    "Persisted spread does not equal best ask minus best bid.",
)

require(
    np.allclose(
        midpoint.to_numpy(),
        (
            (best_bid + best_ask) / 2.0
        ).to_numpy(),
        rtol=0.0,
        atol=1e-10,
    ),
    "Persisted midpoint is inconsistent with best prices.",
)

require(
    (
        (microprice >= best_bid)
        & (microprice <= best_ask)
    ).all(),
    "At least one microprice lies outside the spread.",
)

require(
    top_level_imbalance.between(
        -1.0,
        1.0,
        inclusive="both",
    ).all(),
    "Top-level imbalance lies outside [-1, 1].",
)

require(
    multi_level_imbalance.between(
        -1.0,
        1.0,
        inclusive="both",
    ).all(),
    "Multi-level imbalance lies outside [-1, 1].",
)


# ------------------------------------------------------------
# Top-ten price and quantity invariants
# ------------------------------------------------------------

for level_number in range(
    1,
    NOTEBOOK_02_EXPECTED_TOP_N_LEVELS + 1,
):
    for side_name in ("bid", "ask"):
        price_column = (
            f"{side_name}_price_{level_number}"
        )

        quantity_column = (
            f"{side_name}_quantity_{level_number}"
        )

        level_price = finite_numeric_series(
            RECONSTRUCTED_BOOK_STATES,
            price_column,
        )

        level_quantity = finite_numeric_series(
            RECONSTRUCTED_BOOK_STATES,
            quantity_column,
        )

        require(
            (level_price > 0).all(),
            f"{price_column} contains non-positive values.",
        )

        require(
            (level_quantity > 0).all(),
            f"{quantity_column} contains non-positive values.",
        )


for level_number in range(
    1,
    NOTEBOOK_02_EXPECTED_TOP_N_LEVELS,
):
    next_level_number = level_number + 1

    current_bid = finite_numeric_series(
        RECONSTRUCTED_BOOK_STATES,
        f"bid_price_{level_number}",
    )

    next_bid = finite_numeric_series(
        RECONSTRUCTED_BOOK_STATES,
        f"bid_price_{next_level_number}",
    )

    current_ask = finite_numeric_series(
        RECONSTRUCTED_BOOK_STATES,
        f"ask_price_{level_number}",
    )

    next_ask = finite_numeric_series(
        RECONSTRUCTED_BOOK_STATES,
        f"ask_price_{next_level_number}",
    )

    require(
        (current_bid > next_bid).all(),
        (
            f"Bid levels {level_number} and "
            f"{next_level_number} are not strictly ordered."
        ),
    )

    require(
        (current_ask < next_ask).all(),
        (
            f"Ask levels {level_number} and "
            f"{next_level_number} are not strictly ordered."
        ),
    )


# ------------------------------------------------------------
# Recompute top-ten visible depth
# ------------------------------------------------------------

recomputed_bid_depth_top_10 = sum(
    finite_numeric_series(
        RECONSTRUCTED_BOOK_STATES,
        f"bid_quantity_{level_number}",
    )
    for level_number in range(
        1,
        NOTEBOOK_02_EXPECTED_TOP_N_LEVELS + 1,
    )
)

recomputed_ask_depth_top_10 = sum(
    finite_numeric_series(
        RECONSTRUCTED_BOOK_STATES,
        f"ask_quantity_{level_number}",
    )
    for level_number in range(
        1,
        NOTEBOOK_02_EXPECTED_TOP_N_LEVELS + 1,
    )
)

persisted_bid_depth_top_10 = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "visible_bid_depth_top_10",
)

persisted_ask_depth_top_10 = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "visible_ask_depth_top_10",
)

persisted_total_depth_top_10 = finite_numeric_series(
    RECONSTRUCTED_BOOK_STATES,
    "visible_total_depth_top_10",
)

require(
    np.allclose(
        persisted_bid_depth_top_10,
        recomputed_bid_depth_top_10,
        rtol=1e-12,
        atol=1e-12,
    ),
    "Persisted top-10 bid depth does not reconcile.",
)

require(
    np.allclose(
        persisted_ask_depth_top_10,
        recomputed_ask_depth_top_10,
        rtol=1e-12,
        atol=1e-12,
    ),
    "Persisted top-10 ask depth does not reconcile.",
)

require(
    np.allclose(
        persisted_total_depth_top_10,
        (
            recomputed_bid_depth_top_10
            + recomputed_ask_depth_top_10
        ),
        rtol=1e-12,
        atol=1e-12,
    ),
    "Persisted total top-10 depth does not reconcile.",
)


# ------------------------------------------------------------
# Full-state versus top-ten-wide identity
# ------------------------------------------------------------

for identity_column in (
    "reconstruction_session_id",
    "book_state_id",
    "partition",
    "collector_sequence",
    "local_receipt_time_ns",
    "first_update_id",
    "final_update_id",
    "top_10_state_sha256",
):
    left_values = (
        RECONSTRUCTED_BOOK_STATES[
            identity_column
        ]
        .astype("string")
        .fillna("<NA>")
        .to_numpy()
    )

    right_values = (
        TOP_10_VISIBLE_BOOK_WIDE[
            identity_column
        ]
        .astype("string")
        .fillna("<NA>")
        .to_numpy()
    )

    require(
        np.array_equal(
            left_values,
            right_values,
        ),
        (
            f"Full-state and top-ten-wide identity mismatch "
            f"for {identity_column}."
        ),
    )


for level_column in BOOK_LEVEL_COLUMNS:
    full_values = pd.to_numeric(
        RECONSTRUCTED_BOOK_STATES[
            level_column
        ],
        errors="raise",
    ).astype("float64")

    wide_values = pd.to_numeric(
        TOP_10_VISIBLE_BOOK_WIDE[
            level_column
        ],
        errors="raise",
    ).astype("float64")

    require(
        np.allclose(
            full_values,
            wide_values,
            rtol=0.0,
            atol=0.0,
        ),
        (
            f"Full-state and top-ten-wide values differ for "
            f"{level_column}."
        ),
    )


# ------------------------------------------------------------
# Long top-ten table invariants
# ------------------------------------------------------------

long_side = (
    VISIBLE_TOP_10_BOOK_LONG[
        "side"
    ].astype(str)
)

long_side_order = pd.to_numeric(
    VISIBLE_TOP_10_BOOK_LONG[
        "side_order"
    ],
    errors="raise",
).astype("int64")

long_level = pd.to_numeric(
    VISIBLE_TOP_10_BOOK_LONG[
        "level"
    ],
    errors="raise",
).astype("int64")

long_price = pd.to_numeric(
    VISIBLE_TOP_10_BOOK_LONG[
        "price"
    ],
    errors="raise",
).astype("float64")

long_quantity = pd.to_numeric(
    VISIBLE_TOP_10_BOOK_LONG[
        "quantity"
    ],
    errors="raise",
).astype("float64")

require(
    set(long_side.unique())
    == {"bid", "ask"},
    "Top-ten long table contains invalid sides.",
)

require(
    set(long_side_order.unique())
    == {0, 1},
    "Top-ten long table contains invalid side_order values.",
)

require(
    set(long_level.unique())
    == set(range(1, 11)),
    "Top-ten long table does not contain levels 1 through 10.",
)

require(
    np.isfinite(long_price).all()
    and (long_price > 0).all(),
    "Top-ten long table contains invalid prices.",
)

require(
    np.isfinite(long_quantity).all()
    and (long_quantity > 0).all(),
    "Top-ten long table contains invalid quantities.",
)

long_group_counts = (
    VISIBLE_TOP_10_BOOK_LONG
    .groupby(
        [
            "book_state_id",
            "side",
        ],
        sort=False,
        observed=False,
    )
    .size()
)

require(
    long_group_counts.eq(10).all(),
    (
        "At least one book-state/side pair does not contain "
        "exactly ten long-form levels."
    ),
)

long_state_counts = (
    VISIBLE_TOP_10_BOOK_LONG
    .groupby(
        "book_state_id",
        sort=False,
        observed=False,
    )
    .size()
)

require(
    long_state_counts.eq(20).all(),
    (
        "At least one book state does not contain exactly "
        "twenty long-form rows."
    ),
)

require(
    set(
        pd.to_numeric(
            VISIBLE_TOP_10_BOOK_LONG[
                "book_state_id"
            ],
            errors="raise",
        ).astype("int64").unique()
    )
    == set(book_state_ids),
    (
        "Top-ten long table book-state membership does not "
        "match the reconstructed-state table."
    ),
)


# ------------------------------------------------------------
# Update-continuity identity and acceptance
# ------------------------------------------------------------

require(
    len(UPDATE_CONTINUITY_REPORT)
    == EXPECTED_RECONSTRUCTED_BOOK_STATES,
    "Update-continuity row count does not match book states.",
)

for identity_column in (
    "book_state_id",
    "collector_sequence",
    "local_receipt_time_ns",
    "partition",
):
    state_values = (
        RECONSTRUCTED_BOOK_STATES[
            identity_column
        ]
        .astype("string")
        .fillna("<NA>")
        .to_numpy()
    )

    continuity_values = (
        UPDATE_CONTINUITY_REPORT[
            identity_column
        ]
        .astype("string")
        .fillna("<NA>")
        .to_numpy()
    )

    require(
        np.array_equal(
            state_values,
            continuity_values,
        ),
        (
            f"Update-continuity identity mismatch for "
            f"{identity_column}."
        ),
    )

continuity_state_accepted = strict_boolean_series(
    UPDATE_CONTINUITY_REPORT[
        "state_accepted"
    ],
    field_name=(
        "UPDATE_CONTINUITY_REPORT.state_accepted"
    ),
)

continuity_collector_valid = strict_boolean_series(
    UPDATE_CONTINUITY_REPORT[
        "collector_order_valid"
    ],
    field_name=(
        "UPDATE_CONTINUITY_REPORT."
        "collector_order_valid"
    ),
)

continuity_local_time_valid = strict_boolean_series(
    UPDATE_CONTINUITY_REPORT[
        "local_time_order_valid"
    ],
    field_name=(
        "UPDATE_CONTINUITY_REPORT."
        "local_time_order_valid"
    ),
)

continuity_resynchronization = strict_boolean_series(
    UPDATE_CONTINUITY_REPORT[
        "resynchronization_required"
    ],
    field_name=(
        "UPDATE_CONTINUITY_REPORT."
        "resynchronization_required"
    ),
)

require(
    continuity_state_accepted.all(),
    "An update-continuity row is not accepted.",
)

require(
    continuity_collector_valid.all(),
    "An update-continuity row violates collector ordering.",
)

require(
    continuity_local_time_valid.all(),
    "An update-continuity row violates local-time ordering.",
)

require(
    not continuity_resynchronization.any(),
    "A reconstructed state required resynchronization.",
)


# ------------------------------------------------------------
# Reconstruction-session identity
# ------------------------------------------------------------

require(
    len(RECONSTRUCTION_SESSION_LEDGER) == 1,
    (
        "Expected exactly one reconstruction-session ledger "
        f"row; observed={len(RECONSTRUCTION_SESSION_LEDGER)}."
    ),
)

require_columns(
    RECONSTRUCTION_SESSION_LEDGER,
    (
        "reconstruction_session_id",
        "accepted_state_count",
        "rejected_update_count",
        "resynchronization_count",
        "session_status",
    ),
    "RECONSTRUCTION_SESSION_LEDGER",
)

unique_reconstruction_session_ids = set(
    RECONSTRUCTED_BOOK_STATES[
        "reconstruction_session_id"
    ].astype(str).unique()
)

require(
    len(unique_reconstruction_session_ids) == 1,
    "Book states contain multiple reconstruction sessions.",
)

ledger_session_id = str(
    RECONSTRUCTION_SESSION_LEDGER.iloc[0][
        "reconstruction_session_id"
    ]
)

require(
    unique_reconstruction_session_ids
    == {ledger_session_id},
    (
        "Reconstruction-session ledger does not match the "
        "book-state table."
    ),
)

require(
    ledger_session_id
    == str(
        NOTEBOOK_02_HANDOFF_PAYLOAD[
            "reconstruction_session_id"
        ]
    ),
    (
        "Reconstruction-session identity differs between the "
        "handoff and persisted tables."
    ),
)

require(
    int(
        RECONSTRUCTION_SESSION_LEDGER.iloc[0][
            "accepted_state_count"
        ]
    )
    == EXPECTED_RECONSTRUCTED_BOOK_STATES,
    "Session ledger accepted-state count mismatch.",
)

require(
    int(
        RECONSTRUCTION_SESSION_LEDGER.iloc[0][
            "rejected_update_count"
        ]
    )
    == 0,
    "Session ledger records rejected depth updates.",
)

require(
    int(
        RECONSTRUCTION_SESSION_LEDGER.iloc[0][
            "resynchronization_count"
        ]
    )
    == 0,
    "Session ledger records resynchronizations.",
)

require(
    str(
        RECONSTRUCTION_SESSION_LEDGER.iloc[0][
            "session_status"
        ]
    )
    == "CLOSED_CONTINUOUS",
    "Reconstruction session did not close continuously.",
)


# ------------------------------------------------------------
# Persisted book-quality gate authority
# ------------------------------------------------------------

quality_gate_passed = strict_boolean_series(
    BOOK_QUALITY_GATES[
        "passed"
    ],
    field_name="BOOK_QUALITY_GATES.passed",
)

quality_gate_critical = strict_boolean_series(
    BOOK_QUALITY_GATES[
        "critical"
    ],
    field_name="BOOK_QUALITY_GATES.critical",
)

failed_critical_book_gates = (
    BOOK_QUALITY_GATES.loc[
        quality_gate_critical
        & ~quality_gate_passed
    ]
)

require(
    failed_critical_book_gates.empty,
    (
        "Persisted Notebook 02 critical book-quality gates "
        "contain failures:\n"
        + failed_critical_book_gates.to_string(
            index=False
        )
    ),
)


# ------------------------------------------------------------
# Partition-count reconciliation against the Notebook 02
# handoff and Notebook 00 authority
# ------------------------------------------------------------

observed_book_partition_counts = (
    RECONSTRUCTED_BOOK_STATES[
        "partition"
    ]
    .astype(str)
    .value_counts(sort=False)
    .reindex(PARTITION_ORDER)
    .fillna(0)
    .astype("int64")
)

handoff_book_partition_counts = pd.Series(
    NOTEBOOK_02_HANDOFF_PAYLOAD[
        "partition_counts"
    ],
    dtype="int64",
).reindex(PARTITION_ORDER)

require(
    observed_book_partition_counts.equals(
        handoff_book_partition_counts
    ),
    (
        "Reconstructed-book partition counts differ from the "
        "Notebook 02 handoff."
    ),
)

notebook_00_depth_partition_counts = (
    SPLIT_BOUNDARY_TABLE.set_index(
        "partition"
    )["depth_row_count"]
    .astype("int64")
    .reindex(PARTITION_ORDER)
)

# Notebook 02 excludes nine pre-snapshot depth messages.
partition_depth_count_difference = (
    notebook_00_depth_partition_counts
    - observed_book_partition_counts
)

require(
    (partition_depth_count_difference >= 0).all(),
    (
        "Notebook 02 contains more reconstructed states than "
        "Notebook 00 depth messages in a partition."
    ),
)

require(
    int(
        partition_depth_count_difference.sum()
    )
    == (
        int(
            SPLIT_BOUNDARY_TABLE[
                "depth_row_count"
            ].sum()
        )
        - EXPECTED_RECONSTRUCTED_BOOK_STATES
    ),
    (
        "Notebook 02 pre-snapshot exclusion count does not "
        "reconcile to Notebook 00."
    ),
)


# ------------------------------------------------------------
# Notebook 02 gate table
# ------------------------------------------------------------

NOTEBOOK_02_AUTHORITY_GATES = pd.DataFrame(
    [
        {
            "gate": "manifest_payload_verified",
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                NOTEBOOK_02_OUTPUT_MANIFEST_METADATA[
                    "payload_sha256"
                ]
            ),
        },
        {
            "gate": "handoff_payload_verified",
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                NOTEBOOK_02_HANDOFF_METADATA[
                    "payload_sha256"
                ]
            ),
        },
        {
            "gate": "required_downstream_paths_reconcile",
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                f"artifacts="
                f"{len(REQUIRED_NOTEBOOK_02_DOWNSTREAM_ARTIFACTS)}"
            ),
        },
        {
            "gate": "reconstructed_state_count",
            "severity": "BLOCKING",
            "passed": (
                len(RECONSTRUCTED_BOOK_STATES)
                == EXPECTED_RECONSTRUCTED_BOOK_STATES
            ),
            "evidence": (
                f"states={len(RECONSTRUCTED_BOOK_STATES)}"
            ),
        },
        {
            "gate": "top_10_wide_identity",
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                f"rows={len(TOP_10_VISIBLE_BOOK_WIDE)}"
            ),
        },
        {
            "gate": "top_10_long_membership",
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                f"rows={len(VISIBLE_TOP_10_BOOK_LONG)}"
            ),
        },
        {
            "gate": "book_collector_order",
            "severity": "BLOCKING",
            "passed": (
                book_sequences.is_unique
                and book_sequences.is_monotonic_increasing
            ),
            "evidence": (
                f"first={int(book_sequences.iloc[0])}, "
                f"last={int(book_sequences.iloc[-1])}"
            ),
        },
        {
            "gate": "book_local_time_order",
            "severity": "BLOCKING",
            "passed": (
                book_local_times.is_monotonic_increasing
            ),
            "evidence": (
                f"first={int(book_local_times.iloc[0])}, "
                f"last={int(book_local_times.iloc[-1])}"
            ),
        },
        {
            "gate": "book_structural_quality",
            "severity": "BLOCKING",
            "passed": (
                not locked_state.any()
                and not crossed_state.any()
                and not incomplete_state.any()
            ),
            "evidence": (
                f"locked={int(locked_state.sum())}, "
                f"crossed={int(crossed_state.sum())}, "
                f"incomplete={int(incomplete_state.sum())}"
            ),
        },
        {
            "gate": "persisted_critical_quality_gates",
            "severity": "BLOCKING",
            "passed": (
                failed_critical_book_gates.empty
            ),
            "evidence": (
                f"failed_critical="
                f"{len(failed_critical_book_gates)}"
            ),
        },
        {
            "gate": "v0_0_reference_not_authority",
            "severity": "BLOCKING",
            "passed": (
                NOTEBOOK_02_HANDOFF_PAYLOAD[
                    "v0_0_reference_used_as_authority"
                ]
                is False
            ),
            "evidence": (
                "v0_0_reference_used_as_authority=False"
            ),
        },
        {
            "gate": "reference_reconciliation_warnings",
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                f"status="
                f"{NOTEBOOK_02_HANDOFF_PAYLOAD.get('reference_reconciliation_status')}, "
                f"warning_count="
                f"{NOTEBOOK_02_HANDOFF_PAYLOAD.get('reference_warning_count')}"
            ),
        },
    ]
)

NOTEBOOK_02_AUTHORITY_GATES[
    "status"
] = np.select(
    [
        NOTEBOOK_02_AUTHORITY_GATES[
            "passed"
        ],
        NOTEBOOK_02_AUTHORITY_GATES[
            "severity"
        ].eq("BLOCKING"),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

notebook_02_blocking_failures = (
    NOTEBOOK_02_AUTHORITY_GATES.loc[
        NOTEBOOK_02_AUTHORITY_GATES[
            "severity"
        ].eq("BLOCKING")
        & ~NOTEBOOK_02_AUTHORITY_GATES[
            "passed"
        ]
    ]
)

require(
    notebook_02_blocking_failures.empty,
    (
        "Notebook 02 authority verification contains blocking "
        "failures."
    ),
)


# ------------------------------------------------------------
# Downstream immutable authority state
# ------------------------------------------------------------

NOTEBOOK_02_AUTHORITY_VERIFIED: Final[
    bool
] = True

AUTHORITATIVE_RECONSTRUCTION_SESSION_ID: Final[
    str
] = ledger_session_id

AUTHORITATIVE_BOOK_PARTITION_COUNTS: Final[
    Mapping[str, int]
] = MappingProxyType(
    {
        partition: int(
            observed_book_partition_counts[
                partition
            ]
        )
        for partition in PARTITION_ORDER
    }
)


# ------------------------------------------------------------
# Display compact Notebook 02 authority summaries
# ------------------------------------------------------------

display(
    NOTEBOOK_02_TABLE_LOAD_AUDIT[
        [
            "artifact_type",
            "row_count",
            "column_count",
            "size_bytes",
            "acceptance_status",
            "resolved_path",
        ]
    ]
)

display(
    pd.DataFrame(
        {
            "partition": PARTITION_ORDER,
            "notebook_00_depth_messages": (
                notebook_00_depth_partition_counts.values
            ),
            "notebook_02_book_states": (
                observed_book_partition_counts.values
            ),
            "pre_snapshot_or_unreconstructed_difference": (
                partition_depth_count_difference.values
            ),
        }
    )
)

display(
    NOTEBOOK_02_AUTHORITY_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "notebook_02_authority_verified": (
        NOTEBOOK_02_AUTHORITY_VERIFIED
    ),
    "reconstruction_session_id": (
        AUTHORITATIVE_RECONSTRUCTION_SESSION_ID
    ),
    "reconstructed_book_states": int(
        len(RECONSTRUCTED_BOOK_STATES)
    ),
    "top_10_wide_rows": int(
        len(TOP_10_VISIBLE_BOOK_WIDE)
    ),
    "top_10_long_rows": int(
        len(VISIBLE_TOP_10_BOOK_LONG)
    ),
    "book_state_columns": int(
        RECONSTRUCTED_BOOK_STATES.shape[1]
    ),
    "first_book_state_id": int(
        book_state_ids.iloc[0]
    ),
    "last_book_state_id": int(
        book_state_ids.iloc[-1]
    ),
    "first_book_collector_sequence": int(
        book_sequences.iloc[0]
    ),
    "last_book_collector_sequence": int(
        book_sequences.iloc[-1]
    ),
    "partition_counts": dict(
        AUTHORITATIVE_BOOK_PARTITION_COUNTS
    ),
    "locked_states": int(
        locked_state.sum()
    ),
    "crossed_states": int(
        crossed_state.sum()
    ),
    "incomplete_states": int(
        incomplete_state.sum()
    ),
    "stale_interval_count": int(
        strict_boolean_series(
            RECONSTRUCTED_BOOK_STATES[
                "stale_interval"
            ],
            field_name=(
                "RECONSTRUCTED_BOOK_STATES."
                "stale_interval"
            ),
        ).sum()
    ),
    "critical_book_quality_failures": int(
        len(failed_critical_book_gates)
    ),
    "v0_0_reference_used_as_authority": False,
    "verified_at_utc": utc_now_iso(),
}

,artifact_type,row_count,column_count,size_bytes,acceptance_status,resolved_path
0,BOOK_QUALITY_GATES,22,5,1003,PASS_WITH_REFERENCE_WARNINGS,D:\Clown Project\V0.1\artifacts\audit_tables\02_VISIBLE_BOOK_RECONSTRUCTION\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__02_VISIBLE_BOOK_RECONSTRUCTION__book_quality...
1,RECONSTRUCTED_BOOK_STATES,35985,108,50443026,PASS_WITH_REFERENCE_WARNINGS,D:\Clown Project\V0.1\data\processed\book\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__02_VISIBLE_BOOK_RECONSTRUCTION__reconstructed_book_states.csv
2,RECONSTRUCTION_SESSION_LEDGER,1,15,515,PASS_WITH_REFERENCE_WARNINGS,D:\Clown Project\V0.1\artifacts\audit_tables\02_VISIBLE_BOOK_RECONSTRUCTION\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__02_VISIBLE_BOOK_RECONSTRUCTION__reconstructi...
3,TOP_10_VISIBLE_BOOK_WIDE,35985,55,29832139,PASS_WITH_REFERENCE_WARNINGS,D:\Clown Project\V0.1\data\processed\book\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__02_VISIBLE_BOOK_RECONSTRUCTION__top_10_visible_book_wide.csv
4,UPDATE_CONTINUITY_REPORT,35985,18,7772482,PASS_WITH_REFERENCE_WARNINGS,D:\Clown Project\V0.1\artifacts\audit_tables\02_VISIBLE_BOOK_RECONSTRUCTION\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__02_VISIBLE_BOOK_RECONSTRUCTION__update_conti...
5,VISIBLE_TOP_10_BOOK_LONG,719700,17,230620822,PASS_WITH_REFERENCE_WARNINGS,D:\Clown Project\V0.1\data\processed\book\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__02_VISIBLE_BOOK_RECONSTRUCTION__top_10_visible_book_long.csv

             partition  notebook_00_depth_messages  notebook_02_book_states  pre_snapshot_or_unreconstructed_difference
0          DEVELOPMENT                       18019                    18010                                           9
1          CALIBRATION                        7204                     7204                                           0
2           VALIDATION                        5353                     5353                                           0
3  ENGINEERING_HOLDOUT                        5418                     5418                                           0

                                   gate  severity   status                                                          evidence
0             manifest_payload_verified  BLOCKING     PASS  3fa290a1d0cc23cfbf69b4fbe77adcaf47c1f99e3a7cf0cf777b49531108a50b
1              handoff_payload_verified  BLOCKING     PASS  b13e9c47c46e13cb698aff5497b3cbd12f0e0030368fa755f260a7ee3ed8fe76
2   required_downstream_paths_reconcile  BLOCKING     PASS                                                       artifacts=6
3             reconstructed_state_count  BLOCKING     PASS                                                      states=35985
4                  top_10_wide_identity  BLOCKING     PASS                                                        rows=35985
5                top_10_long_membership  BLOCKING     PASS                                                       rows=719700
6                  book_collector_order  BLOCKING     PASS                                             first=10, last=103677
7                 book_local_time_order  BLOCKING     PASS               first=1783665468432309400, last=1783669066749750800
8               book_structural_quality  BLOCKING     PASS                                 locked=0, crossed=0, incomplete=0
9      persisted_critical_quality_gates  BLOCKING     PASS                                                 failed_critical=0
10         v0_0_reference_not_authority  BLOCKING     PASS                            v0_0_reference_used_as_authority=False
11    reference_reconciliation_warnings   WARNING  WARNING               status=REFERENCE_WARNING_ACCEPTED, warning_count=52

{'status': 'PASS',
 'notebook_02_authority_verified': True,
 'reconstruction_session_id': 'v0_1_20260714T090616Z_e82325081a81__book_session_0001',
 'reconstructed_book_states': 35985,
 'top_10_wide_rows': 35985,
 'top_10_long_rows': 719700,
 'book_state_columns': 108,
 'first_book_state_id': 0,
 'last_book_state_id': 35984,
 'first_book_collector_sequence': 10,
 'last_book_collector_sequence': 103677,
 'partition_counts': {'DEVELOPMENT': 18010,
  'CALIBRATION': 7204,
  'VALIDATION': 5353,
  'ENGINEERING_HOLDOUT': 5418},
 'locked_states': 0,
 'crossed_states': 0,
 'incomplete_states': 0,
 'stale_interval_count': 0,
 'critical_book_quality_failures': 0,
 'v0_0_reference_used_as_authority': False,
 'verified_at_utc': '2026-07-19T09:33:49.882404+00:00'}

In [5]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 06 — Notebook 03 LOCAL_STRICT authority, matched-table
#           verification, causal audit, and book reconciliation
# ============================================================


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "NOTEBOOK_00_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 00 authority has not been verified.",
)

require(
    globals().get(
        "NOTEBOOK_02_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 02 authority has not been verified.",
)

require(
    globals().get(
        "UPSTREAM_CONTROL_ARTIFACTS_VERIFIED",
        False,
    )
    is True,
    "Upstream control artifacts have not been verified.",
)

require(
    "RECONSTRUCTED_BOOK_STATES" in globals(),
    "Notebook 02 reconstructed-book states are unavailable.",
)


# ------------------------------------------------------------
# Frozen Notebook 03 authority
# ------------------------------------------------------------

NOTEBOOK_03_NAME: Final[str] = (
    "03_CAUSAL_TRADE_BOOK_ALIGNMENT"
)

NOTEBOOK_03_FILENAME: Final[str] = (
    "03_CAUSAL_TRADE_BOOK_ALIGNMENT.ipynb"
)

NOTEBOOK_03_EXPECTED_TERMINAL_STATUS: Final[str] = (
    "PASS_WITH_ALIGNMENT_WARNINGS"
)

NOTEBOOK_03_EXPECTED_NEXT_NOTEBOOK: Final[str] = (
    "04_EVENT_STREAM_CONSTRUCTION"
)

EXPECTED_NOTEBOOK_03_MATCHED_ALIGNMENT_FILE_SHA256: Final[
    str
] = (
    "a18f66ca6a97a66b8f42a4d61b2aa34d26bcee5ae5a8d2054e576c88beede7a3"
)

EXPECTED_NOTEBOOK_03_MATCHED_COLUMNS: Final[int] = 148


# ------------------------------------------------------------
# Load the already verified flat control documents
# ------------------------------------------------------------

NOTEBOOK_03_OUTPUT_MANIFEST = require_mapping(
    UPSTREAM_CONTROL_DOCUMENTS[
        "notebook_03_output_manifest"
    ],
    "Notebook 03 output manifest",
)

NOTEBOOK_03_TO_04_HANDOFF = require_mapping(
    UPSTREAM_CONTROL_DOCUMENTS[
        "notebook_03_to_04_handoff"
    ],
    "Notebook 03 to Notebook 04 handoff",
)

require(
    classify_json_shape(
        NOTEBOOK_03_OUTPUT_MANIFEST
    )
    == JSON_SHAPE_FLAT,
    "Notebook 03 output manifest must be flat JSON.",
)

require(
    classify_json_shape(
        NOTEBOOK_03_TO_04_HANDOFF
    )
    == JSON_SHAPE_FLAT,
    "Notebook 03 handoff must be flat JSON.",
)

# Notebook 03 did not persist embedded self-hash fields.
require(
    not any(
        field_name in NOTEBOOK_03_OUTPUT_MANIFEST
        for field_name in (
            "manifest_payload_sha256",
            "payload_sha256",
            "artifact_metadata",
        )
    ),
    (
        "Notebook 03 manifest unexpectedly exposes an "
        "embedded self-hash or envelope."
    ),
)

require(
    not any(
        field_name in NOTEBOOK_03_TO_04_HANDOFF
        for field_name in (
            "handoff_payload_sha256",
            "payload_sha256",
            "artifact_metadata",
        )
    ),
    (
        "Notebook 03 handoff unexpectedly exposes an "
        "embedded self-hash or envelope."
    ),
)


# ------------------------------------------------------------
# Reverify Notebook 03 raw control-file identities
# ------------------------------------------------------------

notebook_03_manifest_path = (
    UPSTREAM_CONTROL_PATHS[
        "notebook_03_output_manifest"
    ]
)

notebook_03_handoff_path = (
    UPSTREAM_CONTROL_PATHS[
        "notebook_03_to_04_handoff"
    ]
)

require(
    sha256_file(
        notebook_03_manifest_path
    )
    == EXPECTED_NOTEBOOK_03_MANIFEST_FILE_SHA256,
    "Notebook 03 manifest raw-file SHA-256 changed.",
)

require(
    sha256_file(
        notebook_03_handoff_path
    )
    == EXPECTED_NOTEBOOK_03_TO_04_HANDOFF_FILE_SHA256,
    "Notebook 03 handoff raw-file SHA-256 changed.",
)


# ------------------------------------------------------------
# Manifest identity and acceptance
# ------------------------------------------------------------

expected_notebook_03_manifest_fields = {
    "project_name": PROJECT_NAME,
    "pipeline_version": PIPELINE_VERSION,
    "notebook_name": NOTEBOOK_03_NAME,
    "notebook_filename": NOTEBOOK_03_FILENAME,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "v0_1_run_id": V01_RUN_ID,
    "combined_prefix": COMBINED_PREFIX,
    "operating_mode": OPERATING_MODE,
    "primary_ordering_authority": (
        PRIMARY_ORDERING_AUTHORITY
    ),
    "primary_alignment_policy": (
        PRIMARY_ALIGNMENT_POLICY
    ),
    "canonical_timezone": CANONICAL_TIMEZONE,
    "terminal_status": (
        NOTEBOOK_03_EXPECTED_TERMINAL_STATUS
    ),
    "notebook_04_authorized": True,
}

for field_name, expected_value in (
    expected_notebook_03_manifest_fields.items()
):
    observed_value = (
        NOTEBOOK_03_OUTPUT_MANIFEST.get(
            field_name
        )
    )

    require(
        observed_value == expected_value,
        (
            f"Notebook 03 manifest field {field_name!r} "
            f"mismatch:\n"
            f"expected={expected_value!r}\n"
            f"observed={observed_value!r}"
        ),
    )


# ------------------------------------------------------------
# Handoff identity and acceptance
# ------------------------------------------------------------

expected_notebook_03_handoff_fields = {
    "project_name": PROJECT_NAME,
    "pipeline_version": PIPELINE_VERSION,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "v0_1_run_id": V01_RUN_ID,
    "combined_prefix": COMBINED_PREFIX,
    "producing_notebook": NOTEBOOK_03_NAME,
    "next_notebook": (
        NOTEBOOK_03_EXPECTED_NEXT_NOTEBOOK
    ),
    "terminal_status": (
        NOTEBOOK_03_EXPECTED_TERMINAL_STATUS
    ),
    "notebook_04_authorized": True,
    "primary_alignment_policy": (
        PRIMARY_ALIGNMENT_POLICY
    ),
    "primary_ordering_authority": (
        PRIMARY_ORDERING_AUTHORITY
    ),
    "canonical_timezone": CANONICAL_TIMEZONE,
}

for field_name, expected_value in (
    expected_notebook_03_handoff_fields.items()
):
    observed_value = (
        NOTEBOOK_03_TO_04_HANDOFF.get(
            field_name
        )
    )

    require(
        observed_value == expected_value,
        (
            f"Notebook 03 handoff field {field_name!r} "
            f"mismatch:\n"
            f"expected={expected_value!r}\n"
            f"observed={observed_value!r}"
        ),
    )


# ------------------------------------------------------------
# Verify handoff counts
# ------------------------------------------------------------

NOTEBOOK_03_HANDOFF_COUNTS = require_mapping(
    NOTEBOOK_03_TO_04_HANDOFF.get(
        "counts"
    ),
    "Notebook 03 handoff counts",
)

expected_notebook_03_counts = {
    "raw_trade_count": EXPECTED_MATCHED_TRADE_ROWS,
    "book_state_count": (
        EXPECTED_RECONSTRUCTED_BOOK_STATES
    ),
    "local_strict_all_alignment_rows": (
        EXPECTED_MATCHED_TRADE_ROWS
    ),
    "local_strict_matched_rows": (
        EXPECTED_MATCHED_TRADE_ROWS
    ),
    "local_strict_unmatched_rows": 0,
}

notebook_03_count_audit_rows: list[
    dict[str, Any]
] = []

for count_name, expected_value in (
    expected_notebook_03_counts.items()
):
    observed_value = (
        NOTEBOOK_03_HANDOFF_COUNTS.get(
            count_name
        )
    )

    passed = (
        observed_value is not None
        and int(observed_value)
        == int(expected_value)
    )

    notebook_03_count_audit_rows.append(
        {
            "count_name": count_name,
            "expected_value": int(
                expected_value
            ),
            "observed_value": (
                None
                if observed_value is None
                else int(observed_value)
            ),
            "passed": passed,
        }
    )

NOTEBOOK_03_COUNT_AUDIT = (
    pd.DataFrame.from_records(
        notebook_03_count_audit_rows
    )
)

require(
    NOTEBOOK_03_COUNT_AUDIT[
        "passed"
    ].all(),
    "Notebook 03 handoff counts do not reconcile.",
)

require(
    int(
        NOTEBOOK_03_HANDOFF_COUNTS.get(
            "buy_trade_count",
            -1,
        )
    )
    + int(
        NOTEBOOK_03_HANDOFF_COUNTS.get(
            "sell_trade_count",
            -1,
        )
    )
    == EXPECTED_MATCHED_TRADE_ROWS,
    (
        "Notebook 03 BUY and SELL counts do not conserve "
        "the matched trade population."
    ),
)


# ------------------------------------------------------------
# Verify event-stream authority declarations
# ------------------------------------------------------------

NOTEBOOK_03_EVENT_STREAM_AUTHORITY = require_mapping(
    NOTEBOOK_03_TO_04_HANDOFF.get(
        "event_stream_authority"
    ),
    "Notebook 03 event_stream_authority",
)

required_event_stream_authority = {
    "primary_event_time_field_for_notebook_04": (
        "trade_local_receipt_time_ns"
    ),
    "secondary_exchange_trade_time_field": (
        "trade_exchange_trade_time_ms"
    ),
    "primary_ordering_field": (
        "trade_collector_sequence"
    ),
    "trade_identity_field": "trade_id",
    "aggressor_side_field": (
        "trade_aggressor_side"
    ),
    "price_field": "trade_price",
    "quantity_field": "trade_quantity",
    "notional_field": "trade_notional",
    "matched_book_sequence_field": (
        "book_collector_sequence"
    ),
    "matched_book_local_time_field": (
        "book_local_receipt_time_ns"
    ),
    "alignment_policy": PRIMARY_ALIGNMENT_POLICY,
}

notebook_03_event_authority_rows: list[
    dict[str, Any]
] = []

for field_name, expected_value in (
    required_event_stream_authority.items()
):
    observed_value = (
        NOTEBOOK_03_EVENT_STREAM_AUTHORITY.get(
            field_name
        )
    )

    notebook_03_event_authority_rows.append(
        {
            "field": field_name,
            "expected_value": expected_value,
            "observed_value": observed_value,
            "passed": (
                observed_value
                == expected_value
            ),
        }
    )

NOTEBOOK_03_EVENT_AUTHORITY_AUDIT = (
    pd.DataFrame.from_records(
        notebook_03_event_authority_rows
    )
)

require(
    NOTEBOOK_03_EVENT_AUTHORITY_AUDIT[
        "passed"
    ].all(),
    (
        "Notebook 03 event-stream authority declarations "
        "do not reconcile."
    ),
)


# ------------------------------------------------------------
# EXCHANGE_STRICT must remain sensitivity-only
# ------------------------------------------------------------

NOTEBOOK_03_SENSITIVITY_ONLY_INPUTS = (
    require_mapping(
        NOTEBOOK_03_TO_04_HANDOFF.get(
            "sensitivity_only_inputs"
        ),
        "Notebook 03 sensitivity_only_inputs",
    )
)

require(
    "exchange_strict_alignment_sensitivity"
    in NOTEBOOK_03_SENSITIVITY_ONLY_INPUTS,
    (
        "Notebook 03 handoff does not preserve "
        "EXCHANGE_STRICT as sensitivity-only."
    ),
)

require(
    NOTEBOOK_03_TO_04_HANDOFF[
        "primary_alignment_policy"
    ]
    != "EXCHANGE_STRICT",
    "EXCHANGE_STRICT cannot be primary authority.",
)


# ------------------------------------------------------------
# Resolve authoritative matched-table metadata from the handoff
# ------------------------------------------------------------

NOTEBOOK_03_AUTHORITATIVE_INPUTS = require_mapping(
    NOTEBOOK_03_TO_04_HANDOFF.get(
        "authoritative_inputs_for_notebook_04"
    ),
    (
        "Notebook 03 "
        "authoritative_inputs_for_notebook_04"
    ),
)

require(
    "local_strict_matched_trade_book"
    in NOTEBOOK_03_AUTHORITATIVE_INPUTS,
    (
        "Notebook 03 handoff lacks the LOCAL_STRICT "
        "matched trade-book artifact."
    ),
)

matched_table_handoff_record = require_mapping(
    NOTEBOOK_03_AUTHORITATIVE_INPUTS[
        "local_strict_matched_trade_book"
    ],
    (
        "Notebook 03 local_strict_matched_trade_book "
        "handoff record"
    ),
)

required_matched_metadata_fields = {
    "path",
    "row_count",
    "size_bytes",
    "sha256",
}

missing_matched_metadata_fields = sorted(
    required_matched_metadata_fields
    - set(matched_table_handoff_record)
)

require(
    not missing_matched_metadata_fields,
    (
        "Notebook 03 matched-table handoff record is "
        f"missing fields: {missing_matched_metadata_fields}"
    ),
)


# ------------------------------------------------------------
# Reconcile the handoff record with the flat manifest record
# ------------------------------------------------------------

notebook_03_manifest_output_records = require_list(
    NOTEBOOK_03_OUTPUT_MANIFEST.get(
        "output_artifacts"
    ),
    "Notebook 03 manifest output_artifacts",
)

NOTEBOOK_03_OUTPUT_ARTIFACT_REGISTRY = (
    pd.DataFrame.from_records(
        notebook_03_manifest_output_records
    )
)

require_unique_columns(
    NOTEBOOK_03_OUTPUT_ARTIFACT_REGISTRY,
    "NOTEBOOK_03_OUTPUT_ARTIFACT_REGISTRY",
)

require_columns(
    NOTEBOOK_03_OUTPUT_ARTIFACT_REGISTRY,
    (
        "group",
        "artifact_name",
        "path",
        "row_count",
        "size_bytes",
        "sha256",
    ),
    "NOTEBOOK_03_OUTPUT_ARTIFACT_REGISTRY",
)

require(
    NOTEBOOK_03_OUTPUT_ARTIFACT_REGISTRY[
        "path"
    ].is_unique,
    "Notebook 03 manifest contains duplicate output paths.",
)

matched_manifest_rows = (
    NOTEBOOK_03_OUTPUT_ARTIFACT_REGISTRY.loc[
        NOTEBOOK_03_OUTPUT_ARTIFACT_REGISTRY[
            "artifact_name"
        ].eq("local_strict_matched_trade_book")
    ]
)

require(
    len(matched_manifest_rows) == 1,
    (
        "Notebook 03 manifest must contain exactly one "
        "local_strict_matched_trade_book record."
    ),
)

matched_table_manifest_record = (
    matched_manifest_rows.iloc[0]
)

for metadata_field in (
    "path",
    "row_count",
    "size_bytes",
    "sha256",
):
    handoff_value = (
        matched_table_handoff_record[
            metadata_field
        ]
    )

    manifest_value = (
        matched_table_manifest_record[
            metadata_field
        ]
    )

    if metadata_field in {
        "row_count",
        "size_bytes",
    }:
        matches = (
            int(handoff_value)
            == int(manifest_value)
        )
    elif metadata_field == "path":
        matches = paths_match(
            handoff_value,
            manifest_value,
        )
    else:
        matches = (
            str(handoff_value).lower()
            == str(manifest_value).lower()
        )

    require(
        matches,
        (
            "Notebook 03 handoff and manifest disagree for "
            f"matched-table field {metadata_field!r}:\n"
            f"handoff={handoff_value!r}\n"
            f"manifest={manifest_value!r}"
        ),
    )


# ------------------------------------------------------------
# Resolve and verify the matched table
# ------------------------------------------------------------

NOTEBOOK_03_MATCHED_ALIGNMENT_PATH = Path(
    str(
        matched_table_handoff_record[
            "path"
        ]
    )
).resolve(strict=True)

require_file(
    NOTEBOOK_03_MATCHED_ALIGNMENT_PATH,
    "Notebook 03 LOCAL_STRICT matched table",
)

require(
    path_is_within(
        NOTEBOOK_03_MATCHED_ALIGNMENT_PATH,
        V01_ROOT,
    ),
    (
        "Notebook 03 matched table resolves outside V0.1: "
        f"{NOTEBOOK_03_MATCHED_ALIGNMENT_PATH}"
    ),
)

require(
    not path_is_within(
        NOTEBOOK_03_MATCHED_ALIGNMENT_PATH,
        V00_ROOT,
    ),
    (
        "Notebook 03 matched table improperly resolves "
        "inside V0.0."
    ),
)

registered_matched_row_count = int(
    matched_table_handoff_record[
        "row_count"
    ]
)

registered_matched_size = int(
    matched_table_handoff_record[
        "size_bytes"
    ]
)

registered_matched_sha256 = require_sha256(
    str(
        matched_table_handoff_record[
            "sha256"
        ]
    ),
    (
        "Notebook 03 matched-table registered "
        "raw-file SHA-256"
    ),
)

require(
    registered_matched_row_count
    == EXPECTED_MATCHED_TRADE_ROWS,
    (
        "Notebook 03 matched-table registered row count "
        "is incorrect."
    ),
)

require(
    registered_matched_size
    == int(
        NOTEBOOK_03_MATCHED_ALIGNMENT_PATH
        .stat()
        .st_size
    ),
    "Notebook 03 matched-table file size changed.",
)

observed_matched_sha256 = sha256_file(
    NOTEBOOK_03_MATCHED_ALIGNMENT_PATH
)

require(
    observed_matched_sha256
    == registered_matched_sha256,
    (
        "Notebook 03 matched-table raw-file hash differs "
        "from its handoff and manifest."
    ),
)

require(
    observed_matched_sha256
    == EXPECTED_NOTEBOOK_03_MATCHED_ALIGNMENT_FILE_SHA256,
    (
        "Notebook 03 matched-table raw-file hash differs "
        "from the frozen authority-map value."
    ),
)


# ------------------------------------------------------------
# Load the authoritative LOCAL_STRICT matched table
# ------------------------------------------------------------

LOCAL_STRICT_MATCHED_TRADE_BOOK = pd.read_csv(
    NOTEBOOK_03_MATCHED_ALIGNMENT_PATH,
    low_memory=False,
)

require_unique_columns(
    LOCAL_STRICT_MATCHED_TRADE_BOOK,
    "LOCAL_STRICT_MATCHED_TRADE_BOOK",
)

require(
    len(LOCAL_STRICT_MATCHED_TRADE_BOOK)
    == EXPECTED_MATCHED_TRADE_ROWS,
    (
        "Notebook 03 matched-table row-count mismatch:\n"
        f"expected={EXPECTED_MATCHED_TRADE_ROWS:,}\n"
        f"observed="
        f"{len(LOCAL_STRICT_MATCHED_TRADE_BOOK):,}"
    ),
)

require(
    LOCAL_STRICT_MATCHED_TRADE_BOOK.shape[1]
    == EXPECTED_NOTEBOOK_03_MATCHED_COLUMNS,
    (
        "Notebook 03 matched-table column-count mismatch:\n"
        f"expected={EXPECTED_NOTEBOOK_03_MATCHED_COLUMNS}\n"
        f"observed="
        f"{LOCAL_STRICT_MATCHED_TRADE_BOOK.shape[1]}"
    ),
)


# ------------------------------------------------------------
# Required actual Notebook 03 schema
#
# Only fields confirmed by Notebook 03 and consumed by
# Notebook 04 are blocking requirements here.
# ------------------------------------------------------------

NOTEBOOK_03_MATCHED_REQUIRED_COLUMNS: Final[
    tuple[str, ...]
] = (
    "source_run_prefix",
    "v0_1_run_id",
    "alignment_policy",
    "trade_id",
    "trade_collector_sequence",
    "trade_local_receipt_time_ns",
    "trade_exchange_trade_time_ms",
    "trade_price",
    "trade_quantity",
    "trade_notional",
    "trade_aggressor_side",
    "trade_partition",
    "is_local_strict_match",
    "book_state_id",
    "book_collector_sequence",
    "book_local_receipt_time_ns",
    "book_partition",
    "matched_book_partition",
    "sequence_lag",
    "local_observation_lag_ns",
    "local_observation_lag_ms",
    "local_strict_sequence_condition",
    "local_strict_time_condition",
)

require_columns(
    LOCAL_STRICT_MATCHED_TRADE_BOOK,
    NOTEBOOK_03_MATCHED_REQUIRED_COLUMNS,
    "LOCAL_STRICT_MATCHED_TRADE_BOOK",
)


# ------------------------------------------------------------
# Strict parsing helpers
# ------------------------------------------------------------

def parse_required_int64(
    series: pd.Series,
    field_name: str,
) -> pd.Series:
    """Parse a required integral field without truncation."""
    numeric = pd.to_numeric(
        series,
        errors="raise",
    )

    require(
        numeric.notna().all(),
        f"{field_name} contains missing values.",
    )

    if pd.api.types.is_integer_dtype(
        numeric.dtype
    ):
        return numeric.astype("int64")

    numeric_float = numeric.astype("float64")

    require(
        np.isfinite(
            numeric_float.to_numpy()
        ).all(),
        f"{field_name} contains non-finite values.",
    )

    require(
        numeric_float.eq(
            np.floor(numeric_float)
        ).all(),
        f"{field_name} contains non-integral values.",
    )

    return numeric_float.astype("int64")


def parse_required_float64(
    series: pd.Series,
    field_name: str,
) -> pd.Series:
    """Parse a required finite floating-point field."""
    numeric = pd.to_numeric(
        series,
        errors="raise",
    ).astype("float64")

    require(
        numeric.notna().all(),
        f"{field_name} contains missing values.",
    )

    require(
        np.isfinite(
            numeric.to_numpy()
        ).all(),
        f"{field_name} contains non-finite values.",
    )

    return numeric


def parse_optional_float64(
    series: pd.Series,
    field_name: str,
) -> tuple[pd.Series, int]:
    """
    Parse an optional float field.

    Blank and missing values are permitted. Nonblank values
    that cannot be parsed are blocking schema failures.
    """
    text = series.astype("string")
    stripped = text.str.strip()

    has_value = (
        stripped.notna()
        & stripped.ne("")
        & ~stripped.str.lower().isin(
            {
                "nan",
                "none",
                "<na>",
                "null",
            }
        )
    )

    numeric = pd.to_numeric(
        series,
        errors="coerce",
    ).astype("float64")

    invalid_nonblank = (
        has_value
        & numeric.isna()
    )

    require(
        not invalid_nonblank.any(),
        (
            f"{field_name} contains nonblank values that "
            "cannot be parsed as floats."
        ),
    )

    finite_nonmissing = numeric.dropna()

    require(
        np.isfinite(
            finite_nonmissing.to_numpy()
        ).all(),
        f"{field_name} contains non-finite values.",
    )

    return numeric, int(
        has_value.sum()
    )


# ------------------------------------------------------------
# Parse core identity and timing fields
# ------------------------------------------------------------

trade_id = (
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "trade_id"
    ]
    .astype("string")
    .str.strip()
)

trade_sequence = parse_required_int64(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "trade_collector_sequence"
    ],
    "trade_collector_sequence",
)

trade_local_time_ns = parse_required_int64(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "trade_local_receipt_time_ns"
    ],
    "trade_local_receipt_time_ns",
)

book_state_id_attached = parse_required_int64(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "book_state_id"
    ],
    "book_state_id",
)

book_sequence_attached = parse_required_int64(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "book_collector_sequence"
    ],
    "book_collector_sequence",
)

book_local_time_ns_attached = (
    parse_required_int64(
        LOCAL_STRICT_MATCHED_TRADE_BOOK[
            "book_local_receipt_time_ns"
        ],
        "book_local_receipt_time_ns",
    )
)

sequence_lag = parse_required_int64(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "sequence_lag"
    ],
    "sequence_lag",
)

local_lag_ns = parse_required_int64(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "local_observation_lag_ns"
    ],
    "local_observation_lag_ns",
)

local_lag_ms = parse_required_float64(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "local_observation_lag_ms"
    ],
    "local_observation_lag_ms",
)

trade_price = parse_required_float64(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "trade_price"
    ],
    "trade_price",
)

trade_quantity = parse_required_float64(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "trade_quantity"
    ],
    "trade_quantity",
)

trade_notional = parse_required_float64(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "trade_notional"
    ],
    "trade_notional",
)

is_local_strict_match = strict_boolean_series(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "is_local_strict_match"
    ],
    field_name="is_local_strict_match",
)

local_strict_sequence_condition = (
    strict_boolean_series(
        LOCAL_STRICT_MATCHED_TRADE_BOOK[
            "local_strict_sequence_condition"
        ],
        field_name=(
            "local_strict_sequence_condition"
        ),
    )
)

local_strict_time_condition = (
    strict_boolean_series(
        LOCAL_STRICT_MATCHED_TRADE_BOOK[
            "local_strict_time_condition"
        ],
        field_name=(
            "local_strict_time_condition"
        ),
    )
)


# ------------------------------------------------------------
# Identity, conservation, and causal alignment gates
# ------------------------------------------------------------

require(
    trade_id.notna().all()
    and trade_id.ne("").all(),
    "Notebook 03 contains a missing trade ID.",
)

require(
    trade_id.is_unique,
    "Notebook 03 contains duplicate trade IDs.",
)

require(
    trade_sequence.is_unique,
    (
        "Notebook 03 contains duplicate trade collector "
        "sequences."
    ),
)

require(
    trade_sequence.is_monotonic_increasing,
    (
        "Notebook 03 trade collector sequence is not "
        "strictly ordered."
    ),
)

require(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "source_run_prefix"
    ].astype(str).eq(
        SOURCE_RUN_PREFIX
    ).all(),
    "Notebook 03 matched rows contain a wrong source run.",
)

require(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "v0_1_run_id"
    ].astype(str).eq(
        V01_RUN_ID
    ).all(),
    "Notebook 03 matched rows contain a wrong V0.1 run ID.",
)

require(
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "alignment_policy"
    ].astype(str).eq(
        PRIMARY_ALIGNMENT_POLICY
    ).all(),
    (
        "Notebook 03 matched rows contain a non-LOCAL_STRICT "
        "alignment policy."
    ),
)

require(
    is_local_strict_match.all(),
    (
        "The authoritative matched table contains a row that "
        "is not marked as matched."
    ),
)

require(
    local_strict_sequence_condition.all(),
    (
        "At least one matched row fails the LOCAL_STRICT "
        "sequence condition."
    ),
)

require(
    local_strict_time_condition.all(),
    (
        "At least one matched row fails the LOCAL_STRICT "
        "local-time condition."
    ),
)

require(
    (
        book_sequence_attached
        < trade_sequence
    ).all(),
    (
        "Notebook 03 contains a post-trade or same-sequence "
        "book state."
    ),
)

require(
    (
        book_local_time_ns_attached
        <= trade_local_time_ns
    ).all(),
    (
        "Notebook 03 contains a book state observed after "
        "its matched trade."
    ),
)

require(
    (
        sequence_lag
        == (
            trade_sequence
            - book_sequence_attached
        )
    ).all(),
    "Notebook 03 sequence_lag arithmetic is inconsistent.",
)

require(
    (
        local_lag_ns
        == (
            trade_local_time_ns
            - book_local_time_ns_attached
        )
    ).all(),
    (
        "Notebook 03 local_observation_lag_ns arithmetic "
        "is inconsistent."
    ),
)

require(
    (
        local_lag_ns >= 0
    ).all(),
    "Notebook 03 contains a negative local observation lag.",
)

require(
    np.allclose(
        local_lag_ms.to_numpy(),
        (
            local_lag_ns.astype("float64")
            / 1_000_000.0
        ).to_numpy(),
        rtol=0.0,
        atol=1e-12,
    ),
    (
        "Notebook 03 local_observation_lag_ms does not "
        "reconcile to nanoseconds."
    ),
)

require(
    set(
        LOCAL_STRICT_MATCHED_TRADE_BOOK[
            "trade_aggressor_side"
        ].astype(str).unique()
    )
    == set(VALID_AGGRESSOR_SIDES),
    (
        "Notebook 03 aggressor-side domain differs from "
        "{BUY, SELL}."
    ),
)

require(
    (trade_price > 0).all(),
    "Notebook 03 contains a non-positive trade price.",
)

require(
    (trade_quantity > 0).all(),
    "Notebook 03 contains a non-positive trade quantity.",
)

require(
    (trade_notional > 0).all(),
    "Notebook 03 contains a non-positive trade notional.",
)

require(
    np.allclose(
        trade_notional.to_numpy(),
        (
            trade_price
            * trade_quantity
        ).to_numpy(),
        rtol=1e-11,
        atol=1e-10,
    ),
    "Notebook 03 trade notional does not equal price × quantity.",
)


# ------------------------------------------------------------
# Reconcile attached Notebook 03 book identity against
# authoritative Notebook 02 reconstruction
#
# Notebook 03 repeats book fields once per matched trade.
# One book state may therefore appear in many matched rows.
# ------------------------------------------------------------

NOTEBOOK_03_ATTACHED_BOOK_CORE_FIELDS: Final[
    tuple[str, ...]
] = (
    "book_state_id",
    "book_collector_sequence",
    "book_local_receipt_time_ns",
)

optional_attached_book_fields = tuple(
    column_name
    for column_name in (
        "book_best_bid",
        "book_best_ask",
        "book_best_bid_size",
        "book_best_ask_size",
        "book_spread",
        "book_midpoint",
        "book_microprice",
        "book_l1_imbalance",
        "book_top10_imbalance",
        "book_partition",
        "matched_book_partition",
    )
    if column_name
    in LOCAL_STRICT_MATCHED_TRADE_BOOK.columns
)

attached_consistency_fields = (
    NOTEBOOK_03_ATTACHED_BOOK_CORE_FIELDS
    + optional_attached_book_fields
)

notebook_03_attached_conflict_rows: list[
    dict[str, Any]
] = []

book_state_grouped = (
    LOCAL_STRICT_MATCHED_TRADE_BOOK
    .groupby(
        "book_state_id",
        sort=False,
        observed=False,
        dropna=False,
    )
)

for field_name in attached_consistency_fields:
    distinct_per_state = (
        book_state_grouped[
            field_name
        ]
        .nunique(
            dropna=False
        )
    )

    conflict_count = int(
        distinct_per_state.gt(1).sum()
    )

    notebook_03_attached_conflict_rows.append(
        {
            "field": field_name,
            "book_state_conflict_count": (
                conflict_count
            ),
            "passed": (
                conflict_count == 0
            ),
        }
    )

NOTEBOOK_03_ATTACHED_FIELD_CONSISTENCY_AUDIT = (
    pd.DataFrame.from_records(
        notebook_03_attached_conflict_rows
    )
)

require(
    NOTEBOOK_03_ATTACHED_FIELD_CONSISTENCY_AUDIT[
        "passed"
    ].all(),
    (
        "Notebook 03 repeats inconsistent attached values "
        "for the same book_state_id."
    ),
)

NOTEBOOK_03_UNIQUE_ATTACHED_BOOK_STATES = (
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        list(attached_consistency_fields)
    ]
    .drop_duplicates(
        subset=["book_state_id"],
        keep="first",
    )
    .copy()
)

NOTEBOOK_03_UNIQUE_ATTACHED_BOOK_STATES[
    "book_state_id"
] = pd.to_numeric(
    NOTEBOOK_03_UNIQUE_ATTACHED_BOOK_STATES[
        "book_state_id"
    ],
    errors="raise",
).astype("int64")

NOTEBOOK_02_BOOK_RECONCILIATION_SOURCE = (
    RECONSTRUCTED_BOOK_STATES.copy()
)

NOTEBOOK_02_BOOK_RECONCILIATION_SOURCE[
    "book_state_id"
] = pd.to_numeric(
    NOTEBOOK_02_BOOK_RECONCILIATION_SOURCE[
        "book_state_id"
    ],
    errors="raise",
).astype("int64")

NOTEBOOK_03_BOOK_RECONCILIATION = (
    NOTEBOOK_03_UNIQUE_ATTACHED_BOOK_STATES.merge(
        NOTEBOOK_02_BOOK_RECONCILIATION_SOURCE,
        how="left",
        on="book_state_id",
        suffixes=(
            "__n03",
            "__n02",
        ),
        indicator=True,
        validate="one_to_one",
    )
)

require(
    NOTEBOOK_03_BOOK_RECONCILIATION[
        "_merge"
    ].eq("both").all(),
    (
        "Notebook 03 references at least one book_state_id "
        "that is absent from Notebook 02."
    ),
)


# ------------------------------------------------------------
# Exact integer book-field reconciliation
# ------------------------------------------------------------

integer_book_field_pairs = (
    (
        "book_collector_sequence",
        "collector_sequence",
    ),
    (
        "book_local_receipt_time_ns",
        "local_receipt_time_ns",
    ),
)

book_field_reconciliation_rows: list[
    dict[str, Any]
] = []

for notebook_03_field, notebook_02_field in (
    integer_book_field_pairs
):
    left = pd.to_numeric(
        NOTEBOOK_03_BOOK_RECONCILIATION[
            notebook_03_field
        ],
        errors="raise",
    ).astype("int64")

    right = pd.to_numeric(
        NOTEBOOK_03_BOOK_RECONCILIATION[
            notebook_02_field
        ],
        errors="raise",
    ).astype("int64")

    mismatch_count = int(
        left.ne(right).sum()
    )

    book_field_reconciliation_rows.append(
        {
            "notebook_03_field": (
                notebook_03_field
            ),
            "notebook_02_field": (
                notebook_02_field
            ),
            "authority_class": (
                "AUTHORITATIVE_IDENTITY"
            ),
            "compared_rows": int(
                len(left)
            ),
            "nonnull_notebook_03_rows": int(
                left.notna().sum()
            ),
            "mismatch_count": mismatch_count,
            "maximum_absolute_error": 0.0,
            "status": (
                "PASS"
                if mismatch_count == 0
                else "FAIL"
            ),
        }
    )

require(
    all(
        row["mismatch_count"] == 0
        for row in book_field_reconciliation_rows
    ),
    (
        "Notebook 03 attached book identity differs from "
        "Notebook 02 reconstruction."
    ),
)


# ------------------------------------------------------------
# Confirmed attached numeric fields
#
# These are reconciled only when the fields actually exist.
# They are not used as Notebook 05 visible-book authority;
# Notebook 02 remains the authority for market-state features.
# ------------------------------------------------------------

numeric_book_field_pairs = (
    (
        "book_best_bid",
        "best_bid",
    ),
    (
        "book_best_ask",
        "best_ask",
    ),
    (
        "book_best_bid_size",
        "best_bid_quantity",
    ),
    (
        "book_best_ask_size",
        "best_ask_quantity",
    ),
    (
        "book_spread",
        "spread",
    ),
    (
        "book_midpoint",
        "midpoint",
    ),
    (
        "book_microprice",
        "microprice",
    ),
    (
        "book_l1_imbalance",
        "top_level_imbalance",
    ),
)

for notebook_03_field, notebook_02_field in (
    numeric_book_field_pairs
):
    if (
        notebook_03_field
        not in NOTEBOOK_03_BOOK_RECONCILIATION.columns
    ):
        book_field_reconciliation_rows.append(
            {
                "notebook_03_field": (
                    notebook_03_field
                ),
                "notebook_02_field": (
                    notebook_02_field
                ),
                "authority_class": (
                    "DIAGNOSTIC_ATTACHED_FIELD"
                ),
                "compared_rows": 0,
                "nonnull_notebook_03_rows": 0,
                "mismatch_count": 0,
                "maximum_absolute_error": np.nan,
                "status": "NOT_PRESENT",
            }
        )
        continue

    left, left_nonblank_count = (
        parse_optional_float64(
            NOTEBOOK_03_BOOK_RECONCILIATION[
                notebook_03_field
            ],
            notebook_03_field,
        )
    )

    right = pd.to_numeric(
        NOTEBOOK_03_BOOK_RECONCILIATION[
            notebook_02_field
        ],
        errors="raise",
    ).astype("float64")

    comparison_mask = (
        left.notna()
        & right.notna()
    )

    if comparison_mask.any():
        close_mask = np.isclose(
            left.loc[
                comparison_mask
            ].to_numpy(),
            right.loc[
                comparison_mask
            ].to_numpy(),
            rtol=1e-11,
            atol=1e-10,
            equal_nan=False,
        )

        mismatch_count = int(
            (~close_mask).sum()
        )

        maximum_absolute_error = float(
            np.max(
                np.abs(
                    left.loc[
                        comparison_mask
                    ].to_numpy()
                    - right.loc[
                        comparison_mask
                    ].to_numpy()
                )
            )
        )
    else:
        mismatch_count = 0
        maximum_absolute_error = np.nan

    missing_attached_count = int(
        left.isna().sum()
    )

    status = (
        "PASS"
        if mismatch_count == 0
        and missing_attached_count == 0
        else (
            "WARNING_MISSING"
            if mismatch_count == 0
            else "FAIL"
        )
    )

    book_field_reconciliation_rows.append(
        {
            "notebook_03_field": (
                notebook_03_field
            ),
            "notebook_02_field": (
                notebook_02_field
            ),
            "authority_class": (
                "DIAGNOSTIC_ATTACHED_FIELD"
            ),
            "compared_rows": int(
                comparison_mask.sum()
            ),
            "nonnull_notebook_03_rows": int(
                left_nonblank_count
            ),
            "mismatch_count": (
                mismatch_count
            ),
            "maximum_absolute_error": (
                maximum_absolute_error
            ),
            "status": status,
        }
    )

    require(
        mismatch_count == 0,
        (
            f"Notebook 03 attached field "
            f"{notebook_03_field} differs from the "
            f"corresponding Notebook 02 field "
            f"{notebook_02_field}."
        ),
    )


# ------------------------------------------------------------
# Notebook 03 book_top10_imbalance treatment
#
# Notebook 03 attempted to resolve aliases such as
# top10_imbalance and top_10_imbalance. Notebook 02's actual
# authoritative field is multi_level_imbalance.
#
# The Notebook 03 alias set did not bind that field, so the
# persisted book_top10_imbalance may be entirely missing.
#
# This is an inherited optional-field warning, not a causal
# alignment failure. Notebook 05 must use Notebook 02's
# multi_level_imbalance directly and must not use the Notebook
# 03 attached book_top10_imbalance as feature authority.
# ------------------------------------------------------------

NOTEBOOK_03_TOP10_IMBALANCE_POLICY: Final[str] = (
    "NON_AUTHORITATIVE_OPTIONAL_ATTACHMENT"
)

notebook_03_top10_nonblank_count = 0
notebook_03_top10_mismatch_count = 0
notebook_03_top10_maximum_error = np.nan

if (
    "book_top10_imbalance"
    in NOTEBOOK_03_BOOK_RECONCILIATION.columns
):
    notebook_03_top10_values, (
        notebook_03_top10_nonblank_count
    ) = parse_optional_float64(
        NOTEBOOK_03_BOOK_RECONCILIATION[
            "book_top10_imbalance"
        ],
        "book_top10_imbalance",
    )

    notebook_02_multilevel_values = (
        pd.to_numeric(
            NOTEBOOK_03_BOOK_RECONCILIATION[
                "multi_level_imbalance"
            ],
            errors="raise",
        )
        .astype("float64")
    )

    top10_comparison_mask = (
        notebook_03_top10_values.notna()
        & notebook_02_multilevel_values.notna()
    )

    if top10_comparison_mask.any():
        top10_close = np.isclose(
            notebook_03_top10_values.loc[
                top10_comparison_mask
            ].to_numpy(),
            notebook_02_multilevel_values.loc[
                top10_comparison_mask
            ].to_numpy(),
            rtol=1e-11,
            atol=1e-10,
            equal_nan=False,
        )

        notebook_03_top10_mismatch_count = int(
            (~top10_close).sum()
        )

        notebook_03_top10_maximum_error = float(
            np.max(
                np.abs(
                    notebook_03_top10_values.loc[
                        top10_comparison_mask
                    ].to_numpy()
                    - notebook_02_multilevel_values.loc[
                        top10_comparison_mask
                    ].to_numpy()
                )
            )
        )

        require(
            notebook_03_top10_mismatch_count == 0,
            (
                "Nonmissing Notebook 03 "
                "book_top10_imbalance values differ from "
                "Notebook 02 multi_level_imbalance."
            ),
        )

    if notebook_03_top10_nonblank_count == 0:
        notebook_03_top10_status = (
            "WARNING_UPSTREAM_ALIAS_UNRESOLVED"
        )
    else:
        notebook_03_top10_status = "PASS_NONMISSING_SUBSET"
else:
    notebook_03_top10_status = (
        "WARNING_FIELD_NOT_PRESENT"
    )

book_field_reconciliation_rows.append(
    {
        "notebook_03_field": (
            "book_top10_imbalance"
        ),
        "notebook_02_field": (
            "multi_level_imbalance"
        ),
        "authority_class": (
            NOTEBOOK_03_TOP10_IMBALANCE_POLICY
        ),
        "compared_rows": int(
            notebook_03_top10_nonblank_count
        ),
        "nonnull_notebook_03_rows": int(
            notebook_03_top10_nonblank_count
        ),
        "mismatch_count": int(
            notebook_03_top10_mismatch_count
        ),
        "maximum_absolute_error": (
            notebook_03_top10_maximum_error
        ),
        "status": notebook_03_top10_status,
    }
)


# ------------------------------------------------------------
# Partition fields are diagnostic only
#
# Notebook 04 independently reconstructed authoritative
# event partitions from the Notebook 00 split contract.
# Notebook 03 trade_partition is therefore never accepted as
# Notebook 05 partition authority.
# ------------------------------------------------------------

notebook_03_partition_values = (
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "trade_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

notebook_03_book_partition_values = (
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "book_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

notebook_03_matched_book_partition_values = (
    LOCAL_STRICT_MATCHED_TRADE_BOOK[
        "matched_book_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

require(
    notebook_03_partition_values.notna().all(),
    "Notebook 03 trade_partition contains missing values.",
)

require(
    notebook_03_book_partition_values.notna().all(),
    "Notebook 03 book_partition contains missing values.",
)

require(
    notebook_03_matched_book_partition_values.notna().all(),
    (
        "Notebook 03 matched_book_partition contains "
        "missing values."
    ),
)

require(
    set(
        notebook_03_partition_values.unique()
    ).issubset(
        set(PARTITION_ORDER)
    ),
    "Notebook 03 trade_partition has an unknown value.",
)

require(
    set(
        notebook_03_book_partition_values.unique()
    ).issubset(
        set(PARTITION_ORDER)
    ),
    "Notebook 03 book_partition has an unknown value.",
)

require(
    set(
        notebook_03_matched_book_partition_values.unique()
    ).issubset(
        set(PARTITION_ORDER)
    ),
    (
        "Notebook 03 matched_book_partition has an "
        "unknown value."
    ),
)

notebook_03_partition_crossing_count = int(
    notebook_03_partition_values.ne(
        notebook_03_matched_book_partition_values
    ).sum()
)


# ------------------------------------------------------------
# Final reconciliation frame
# ------------------------------------------------------------

NOTEBOOK_03_BOOK_FIELD_RECONCILIATION = (
    pd.DataFrame.from_records(
        book_field_reconciliation_rows
    )
)

blocking_book_field_failures = (
    NOTEBOOK_03_BOOK_FIELD_RECONCILIATION.loc[
        NOTEBOOK_03_BOOK_FIELD_RECONCILIATION[
            "status"
        ].eq("FAIL")
    ]
)

require(
    blocking_book_field_failures.empty,
    (
        "Notebook 03 contains blocking attached-book field "
        "reconciliation failures."
    ),
)


# ------------------------------------------------------------
# Carry inherited warnings without treating them as filters
# ------------------------------------------------------------

NOTEBOOK_03_WARNINGS_TO_CARRY_FORWARD = (
    pd.DataFrame.from_records(
        require_list(
            NOTEBOOK_03_TO_04_HANDOFF.get(
                "warnings_to_carry_forward",
                [],
            ),
            "Notebook 03 warnings_to_carry_forward",
        )
    )
)

# Warning rows may never be interpreted as row-rejection rules.
notebook_03_warning_count = int(
    len(
        NOTEBOOK_03_WARNINGS_TO_CARRY_FORWARD
    )
)


# ------------------------------------------------------------
# Notebook 03 authority gates
# ------------------------------------------------------------

NOTEBOOK_03_AUTHORITY_GATES = pd.DataFrame(
    [
        {
            "gate": (
                "notebook_03_manifest_raw_hash"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                EXPECTED_NOTEBOOK_03_MANIFEST_FILE_SHA256
            ),
        },
        {
            "gate": (
                "notebook_03_handoff_raw_hash"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                EXPECTED_NOTEBOOK_03_TO_04_HANDOFF_FILE_SHA256
            ),
        },
        {
            "gate": (
                "notebook_03_terminal_status"
            ),
            "severity": "BLOCKING",
            "passed": (
                NOTEBOOK_03_TO_04_HANDOFF[
                    "terminal_status"
                ]
                == NOTEBOOK_03_EXPECTED_TERMINAL_STATUS
            ),
            "evidence": str(
                NOTEBOOK_03_TO_04_HANDOFF[
                    "terminal_status"
                ]
            ),
        },
        {
            "gate": (
                "notebook_04_authorized"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                NOTEBOOK_03_TO_04_HANDOFF[
                    "notebook_04_authorized"
                ]
            ),
            "evidence": (
                "notebook_04_authorized=True"
            ),
        },
        {
            "gate": (
                "matched_table_manifest_handoff_reconcile"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": str(
                NOTEBOOK_03_MATCHED_ALIGNMENT_PATH
            ),
        },
        {
            "gate": (
                "matched_table_raw_hash"
            ),
            "severity": "BLOCKING",
            "passed": (
                observed_matched_sha256
                == EXPECTED_NOTEBOOK_03_MATCHED_ALIGNMENT_FILE_SHA256
            ),
            "evidence": (
                observed_matched_sha256
            ),
        },
        {
            "gate": (
                "matched_table_row_count"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    LOCAL_STRICT_MATCHED_TRADE_BOOK
                )
                == EXPECTED_MATCHED_TRADE_ROWS
            ),
            "evidence": (
                f"rows="
                f"{len(LOCAL_STRICT_MATCHED_TRADE_BOOK)}"
            ),
        },
        {
            "gate": (
                "matched_table_column_count"
            ),
            "severity": "BLOCKING",
            "passed": (
                LOCAL_STRICT_MATCHED_TRADE_BOOK.shape[1]
                == EXPECTED_NOTEBOOK_03_MATCHED_COLUMNS
            ),
            "evidence": (
                f"columns="
                f"{LOCAL_STRICT_MATCHED_TRADE_BOOK.shape[1]}"
            ),
        },
        {
            "gate": (
                "trade_identity_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                trade_id.is_unique
                and trade_sequence.is_unique
            ),
            "evidence": (
                f"trade_ids={trade_id.nunique()}, "
                f"trade_sequences={trade_sequence.nunique()}"
            ),
        },
        {
            "gate": (
                "local_strict_sequence_causality"
            ),
            "severity": "BLOCKING",
            "passed": (
                (
                    book_sequence_attached
                    < trade_sequence
                ).all()
            ),
            "evidence": (
                "book_collector_sequence < "
                "trade_collector_sequence"
            ),
        },
        {
            "gate": (
                "local_strict_time_causality"
            ),
            "severity": "BLOCKING",
            "passed": (
                (
                    book_local_time_ns_attached
                    <= trade_local_time_ns
                ).all()
            ),
            "evidence": (
                "book_local_receipt_time_ns <= "
                "trade_local_receipt_time_ns"
            ),
        },
        {
            "gate": (
                "lag_arithmetic_reconciles"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                "sequence and local-time lag formulas pass"
            ),
        },
        {
            "gate": (
                "attached_book_identity_reconciles"
            ),
            "severity": "BLOCKING",
            "passed": (
                blocking_book_field_failures.empty
            ),
            "evidence": (
                f"unique_attached_book_states="
                f"{len(NOTEBOOK_03_UNIQUE_ATTACHED_BOOK_STATES)}"
            ),
        },
        {
            "gate": (
                "book_top10_imbalance_attachment"
            ),
            "severity": "WARNING",
            "passed": (
                notebook_03_top10_status
                == "PASS_NONMISSING_SUBSET"
            ),
            "evidence": (
                f"status={notebook_03_top10_status}; "
                f"nonnull={notebook_03_top10_nonblank_count}; "
                "Notebook 02 multi_level_imbalance remains "
                "the feature authority"
            ),
        },
        {
            "gate": (
                "notebook_03_partition_fields_diagnostic_only"
            ),
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                "Notebook 04 event_partition and Notebook 00 "
                "split contract remain authoritative; "
                f"inherited_crossing_rows="
                f"{notebook_03_partition_crossing_count}"
            ),
        },
        {
            "gate": (
                "inherited_alignment_warnings_carried"
            ),
            "severity": "WARNING",
            "passed": (
                notebook_03_warning_count == 0
            ),
            "evidence": (
                f"warning_count="
                f"{notebook_03_warning_count}"
            ),
        },
    ]
)

NOTEBOOK_03_AUTHORITY_GATES[
    "status"
] = np.select(
    [
        NOTEBOOK_03_AUTHORITY_GATES[
            "passed"
        ],
        NOTEBOOK_03_AUTHORITY_GATES[
            "severity"
        ].eq("BLOCKING"),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

notebook_03_blocking_failures = (
    NOTEBOOK_03_AUTHORITY_GATES.loc[
        NOTEBOOK_03_AUTHORITY_GATES[
            "severity"
        ].eq("BLOCKING")
        & ~NOTEBOOK_03_AUTHORITY_GATES[
            "passed"
        ]
    ]
)

require(
    notebook_03_blocking_failures.empty,
    (
        "Notebook 03 authority verification contains "
        "blocking failures."
    ),
)


# ------------------------------------------------------------
# Downstream authority state
# ------------------------------------------------------------

NOTEBOOK_03_AUTHORITY_VERIFIED: Final[
    bool
] = True

NOTEBOOK_03_PARTITION_FIELDS_AUTHORITY: Final[
    str
] = "DIAGNOSTIC_ONLY"

NOTEBOOK_03_ATTACHED_BOOK_FIELDS_AUTHORITY: Final[
    str
] = "RECONCILIATION_ONLY"

NOTEBOOK_05_VISIBLE_BOOK_FEATURE_AUTHORITY: Final[
    str
] = "NOTEBOOK_02_RECONSTRUCTED_BOOK_STATES"


# ------------------------------------------------------------
# Compact displays
# ------------------------------------------------------------

display(
    NOTEBOOK_03_COUNT_AUDIT
)

display(
    NOTEBOOK_03_EVENT_AUTHORITY_AUDIT
)

display(
    NOTEBOOK_03_BOOK_FIELD_RECONCILIATION[
        [
            "notebook_03_field",
            "notebook_02_field",
            "authority_class",
            "compared_rows",
            "nonnull_notebook_03_rows",
            "mismatch_count",
            "maximum_absolute_error",
            "status",
        ]
    ]
)

display(
    NOTEBOOK_03_AUTHORITY_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "notebook_03_authority_verified": (
        NOTEBOOK_03_AUTHORITY_VERIFIED
    ),
    "terminal_status": (
        NOTEBOOK_03_TO_04_HANDOFF[
            "terminal_status"
        ]
    ),
    "matched_table_path": str(
        NOTEBOOK_03_MATCHED_ALIGNMENT_PATH
    ),
    "matched_table_sha256": (
        observed_matched_sha256
    ),
    "matched_rows": int(
        len(
            LOCAL_STRICT_MATCHED_TRADE_BOOK
        )
    ),
    "matched_columns": int(
        LOCAL_STRICT_MATCHED_TRADE_BOOK.shape[1]
    ),
    "unique_trade_ids": int(
        trade_id.nunique()
    ),
    "unique_trade_sequences": int(
        trade_sequence.nunique()
    ),
    "unique_attached_book_states": int(
        len(
            NOTEBOOK_03_UNIQUE_ATTACHED_BOOK_STATES
        )
    ),
    "minimum_sequence_lag": int(
        sequence_lag.min()
    ),
    "minimum_local_lag_ns": int(
        local_lag_ns.min()
    ),
    "maximum_local_lag_ns": int(
        local_lag_ns.max()
    ),
    "book_top10_imbalance_status": (
        notebook_03_top10_status
    ),
    "book_top10_imbalance_nonnull_states": int(
        notebook_03_top10_nonblank_count
    ),
    "visible_book_feature_authority": (
        NOTEBOOK_05_VISIBLE_BOOK_FEATURE_AUTHORITY
    ),
    "notebook_03_partition_authority": (
        NOTEBOOK_03_PARTITION_FIELDS_AUTHORITY
    ),
    "inherited_warning_count": int(
        notebook_03_warning_count
    ),
    "verified_at_utc": utc_now_iso(),
}

                        count_name  expected_value  observed_value  passed
0                  raw_trade_count           67683           67683    True
1                 book_state_count           35985           35985    True
2  local_strict_all_alignment_rows           67683           67683    True
3        local_strict_matched_rows           67683           67683    True
4      local_strict_unmatched_rows               0               0    True

                                       field                expected_value                observed_value  passed
0   primary_event_time_field_for_notebook_04   trade_local_receipt_time_ns   trade_local_receipt_time_ns    True
1        secondary_exchange_trade_time_field  trade_exchange_trade_time_ms  trade_exchange_trade_time_ms    True
2                     primary_ordering_field      trade_collector_sequence      trade_collector_sequence    True
3                       trade_identity_field                      trade_id                      trade_id    True
4                       aggressor_side_field          trade_aggressor_side          trade_aggressor_side    True
5                                price_field                   trade_price                   trade_price    True
6                             quantity_field                trade_quantity                trade_quantity    True
7                             notional_field                trade_notional                trade_notional    True
8                matched_book_sequence_field       book_collector_sequence       book_collector_sequence    True
9              matched_book_local_time_field    book_local_receipt_time_ns    book_local_receipt_time_ns    True
10                          alignment_policy                  LOCAL_STRICT                  LOCAL_STRICT    True

             notebook_03_field      notebook_02_field                        authority_class  compared_rows  nonnull_notebook_03_rows  mismatch_count  maximum_absolute_error                             status
0      book_collector_sequence     collector_sequence                 AUTHORITATIVE_IDENTITY          10170                     10170               0            0.000000e+00                               PASS
1   book_local_receipt_time_ns  local_receipt_time_ns                 AUTHORITATIVE_IDENTITY          10170                     10170               0            0.000000e+00                               PASS
2                book_best_bid               best_bid              DIAGNOSTIC_ATTACHED_FIELD          10170                     10170               0            0.000000e+00                               PASS
3                book_best_ask               best_ask              DIAGNOSTIC_ATTACHED_FIELD          10170                     10170               0            0.000000e+00                               PASS
4           book_best_bid_size      best_bid_quantity              DIAGNOSTIC_ATTACHED_FIELD          10170                     10170               0            0.000000e+00                               PASS
5           book_best_ask_size      best_ask_quantity              DIAGNOSTIC_ATTACHED_FIELD          10170                     10170               0            0.000000e+00                               PASS
6                  book_spread                 spread              DIAGNOSTIC_ATTACHED_FIELD          10170                     10170               0            0.000000e+00                               PASS
7                book_midpoint               midpoint              DIAGNOSTIC_ATTACHED_FIELD          10170                     10170               0            0.000000e+00                               PASS
8              book_microprice             microprice              DIAGNOSTIC_ATTACHED_FIELD          10170                     10170               0            7.275958e-12                               PASS
9            book_l1_imbalance    top_level_imbalance              DIAGNOSTIC_ATTACHED_FIELD          10170                     10170               0            4.440892e-16                               PASS
10        book_top10_imbalance  multi_level_imbalance  NON_AUTHORITATIVE_OPTIONAL_ATTACHMENT              0                         0               0                     NaN  WARNING_UPSTREAM_ALIAS_UNRESOLVED

,gate,severity,status,evidence
0,notebook_03_manifest_raw_hash,BLOCKING,PASS,4daa7fa17c2f953e3b931b607e1b5b066f4e29e7dea7397d86b3c9e3b77406ca
1,notebook_03_handoff_raw_hash,BLOCKING,PASS,6f4d48e4fbb56d9ac80b415b3c0fe6c4625526b555938b846ee2876626b6152e
2,notebook_03_terminal_status,BLOCKING,PASS,PASS_WITH_ALIGNMENT_WARNINGS
3,notebook_04_authorized,BLOCKING,PASS,notebook_04_authorized=True
4,matched_table_manifest_handoff_reconcile,BLOCKING,PASS,D:\Clown Project\V0.1\data\processed\trade_book_alignment\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__03_CAUSAL_TRADE_BOOK_ALIGNMENT__local_strict_matched_trade_boo...
5,matched_table_raw_hash,BLOCKING,PASS,a18f66ca6a97a66b8f42a4d61b2aa34d26bcee5ae5a8d2054e576c88beede7a3
6,matched_table_row_count,BLOCKING,PASS,rows=67683
7,matched_table_column_count,BLOCKING,PASS,columns=148
8,trade_identity_conserved,BLOCKING,PASS,"trade_ids=67683, trade_sequences=67683"
9,local_strict_sequence_causality,BLOCKING,PASS,book_collector_sequence < trade_collector_sequence
10,local_strict_time_causality,BLOCKING,PASS,book_local_receipt_time_ns <= trade_local_receipt_time_ns
11,lag_arithmetic_reconciles,BLOCKING,PASS,sequence and local-time lag formulas pass
12,attached_book_identity_reconciles,BLOCKING,PASS,unique_attached_book_states=10170
13,book_top10_imbalance_attachment,WARNING,WARNING,status=WARNING_UPSTREAM_ALIAS_UNRESOLVED; nonnull=0; Notebook 02 multi_level_imbalance remains the feature authority
14,notebook_03_partition_fields_diagnostic_only,WARNING,WARNING,Notebook 04 event_partition and Notebook 00 split contract remain authoritative; inherited_crossing_rows=0
15,inherited_alignment_warnings_carried,WARNING,WARNING,warning_count=6

{'status': 'PASS',
 'notebook_03_authority_verified': True,
 'terminal_status': 'PASS_WITH_ALIGNMENT_WARNINGS',
 'matched_table_path': 'D:\\Clown Project\\V0.1\\data\\processed\\trade_book_alignment\\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__03_CAUSAL_TRADE_BOOK_ALIGNMENT__local_strict_matched_trade_book.csv',
 'matched_table_sha256': 'a18f66ca6a97a66b8f42a4d61b2aa34d26bcee5ae5a8d2054e576c88beede7a3',
 'matched_rows': 67683,
 'matched_columns': 148,
 'unique_trade_ids': 67683,
 'unique_trade_sequences': 67683,
 'unique_attached_book_states': 10170,
 'minimum_sequence_lag': 1,
 'minimum_local_lag_ns': 0,
 'maximum_local_lag_ns': 113319100,
 'book_top10_imbalance_status': 'WARNING_UPSTREAM_ALIAS_UNRESOLVED',
 'book_top10_imbalance_nonnull_states': 0,
 'visible_book_feature_authority': 'NOTEBOOK_02_RECONSTRUCTED_BOOK_STATES',
 'notebook_03_partition_authority': 'DIAGNOSTIC_ONLY',
 'inherited_warning_count': 6,
 'verified_at_utc': '2026-07-19T09:33:51.527645+00:00'}

In [6]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 07 — Notebook 04 event-stream authority, artifact-
#           specific persistence verification, required-table
#           loading, and batch-interface conservation audit
# ============================================================


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "NOTEBOOK_00_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 00 authority has not been verified.",
)

require(
    globals().get(
        "NOTEBOOK_02_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 02 authority has not been verified.",
)

require(
    globals().get(
        "NOTEBOOK_03_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 03 authority has not been verified.",
)

require(
    globals().get(
        "UPSTREAM_CONTROL_ARTIFACTS_VERIFIED",
        False,
    )
    is True,
    "Upstream control artifacts have not been verified.",
)


# ------------------------------------------------------------
# Frozen Notebook 04 authority
# ------------------------------------------------------------

NOTEBOOK_04_NAME: Final[str] = (
    "04_EVENT_STREAM_CONSTRUCTION"
)

NOTEBOOK_04_EXPECTED_STATUS: Final[str] = (
    "PASS_WITH_EVENT_STREAM_WARNINGS"
)

NOTEBOOK_04_EXPECTED_NEXT_NOTEBOOK: Final[str] = (
    "05_MARKET_STATE_FEATURES"
)

NOTEBOOK_04_EXPECTED_EVENT_REPRESENTATION: Final[
    str
] = "SAME_MS_SAME_SIDE_BURSTS"

NOTEBOOK_04_EXPECTED_TIMESTAMP_INTERFACE: Final[
    str
] = "SIMULTANEOUS_EVENT_BATCH_REQUIRED"

NOTEBOOK_04_REQUIRED_TABLE_LABELS: Final[
    tuple[str, ...]
] = (
    "observation_window_contract",
    "primary_estimation_events",
    "primary_exact_time_batches",
    "primary_trade_membership",
    "primary_event_to_batch_membership",
    "primary_event_array_index",
    "primary_scoring_batches",
)

NOTEBOOK_04_REQUIRED_ARRAY_LABELS: Final[
    tuple[str, ...]
] = (
    "partition_event_arrays",
    "partition_batch_arrays",
)


# ------------------------------------------------------------
# Notebook 04 canonical persistence helpers
#
# These reproduce Notebook 04's actual semantic-hash
# conventions. They are intentionally not universal project
# artifact parsers.
# ------------------------------------------------------------

def _n05_n04_jsonable_scalar(
    value: Any,
) -> Any:
    """Reproduce Notebook 04 scalar canonicalization."""
    if value is None:
        return None

    if value is pd.NA:
        return None

    if value is pd.NaT:
        return None

    if isinstance(value, np.bool_):
        return bool(value)

    if isinstance(value, bool):
        return value

    if isinstance(value, np.integer):
        return int(value)

    if isinstance(value, int):
        return value

    if isinstance(value, np.floating):
        numeric = float(value)

        if math.isnan(numeric):
            return None

        if math.isinf(numeric):
            return str(numeric)

        return numeric

    if isinstance(value, float):
        if math.isnan(value):
            return None

        if math.isinf(value):
            return str(value)

        return value

    if isinstance(value, pd.Timestamp):
        if pd.isna(value):
            return None

        return value.isoformat()

    if isinstance(value, datetime):
        return value.isoformat()

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, bytes):
        return value.hex()

    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass

    if isinstance(value, str):
        return value

    return str(value)


def _n05_n04_canonical_json_bytes(
    payload: Any,
) -> bytes:
    """Reproduce Notebook 04 canonical JSON bytes."""
    return json.dumps(
        payload,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def _n05_n04_canonical_json_sha256(
    payload: Any,
) -> str:
    """Reproduce Notebook 04 canonical JSON hashing."""
    return hashlib.sha256(
        _n05_n04_canonical_json_bytes(
            payload
        )
    ).hexdigest()


def _n05_n04_prepare_frame(
    frame: pd.DataFrame,
) -> pd.DataFrame:
    """Reproduce Notebook 04's table preparation."""
    prepared = frame.copy()

    prepared.columns = [
        str(column)
        for column in prepared.columns
    ]

    for column in prepared.columns:
        series = prepared[column]

        if isinstance(
            series.dtype,
            pd.CategoricalDtype,
        ):
            prepared[column] = (
                series.astype("string")
            )
            continue

        if pd.api.types.is_object_dtype(
            series.dtype
        ):
            prepared[column] = series.map(
                lambda value: (
                    None
                    if _n05_n04_jsonable_scalar(
                        value
                    )
                    is None
                    else _n05_n04_jsonable_scalar(
                        value
                    )
                )
            )

            inferred_dtype = (
                pd.api.types.infer_dtype(
                    prepared[column].dropna(),
                    skipna=True,
                )
            )

            if inferred_dtype in {
                "string",
                "unicode",
                "mixed",
                "mixed-integer",
                "mixed-integer-float",
                "bytes",
                "empty",
            }:
                prepared[column] = (
                    prepared[column]
                    .astype("string")
                )

    return prepared.reset_index(
        drop=True
    )


def _n05_n04_table_payload_sha256(
    frame: pd.DataFrame,
) -> str:
    """
    Reproduce Notebook 04's row-order-sensitive and
    column-order-sensitive table payload hash.
    """
    prepared = _n05_n04_prepare_frame(
        frame
    )

    digest = hashlib.sha256()

    columns = [
        str(column)
        for column in prepared.columns
    ]

    digest.update(
        _n05_n04_canonical_json_bytes(
            {
                "columns": columns,
                "row_count": int(
                    len(prepared)
                ),
            }
        )
    )

    for row in prepared.itertuples(
        index=False,
        name=None,
    ):
        canonical_row = [
            _n05_n04_jsonable_scalar(
                value
            )
            for value in row
        ]

        digest.update(b"\n")

        digest.update(
            json.dumps(
                canonical_row,
                ensure_ascii=False,
                separators=(",", ":"),
            ).encode("utf-8")
        )

    return digest.hexdigest()


def _n05_n04_array_payload_sha256(
    arrays: Mapping[str, np.ndarray],
) -> str:
    """Reproduce Notebook 04's canonical NPZ-array hash."""
    digest = hashlib.sha256()

    normalized_schema: dict[
        str,
        dict[str, Any],
    ] = {}

    for key in sorted(arrays):
        array = np.ascontiguousarray(
            arrays[key]
        )

        normalized_schema[key] = {
            "dtype": str(array.dtype),
            "shape": [
                int(dimension)
                for dimension in array.shape
            ],
        }

    digest.update(
        _n05_n04_canonical_json_bytes(
            {
                "array_schema": (
                    normalized_schema
                ),
                "array_count": int(
                    len(arrays)
                ),
            }
        )
    )

    for key in sorted(arrays):
        array = np.ascontiguousarray(
            arrays[key]
        )

        digest.update(b"\n")
        digest.update(
            key.encode("utf-8")
        )
        digest.update(b"\n")
        digest.update(
            array.tobytes(order="C")
        )

    return digest.hexdigest()


def _n05_verify_flat_document_hash(
    document: Mapping[str, Any],
    *,
    hash_field: str,
    label: str,
) -> str:
    """
    Verify one explicitly declared Notebook 04 flat-document
    self-hash. Reference hashes remain inside the payload.
    """
    require(
        hash_field in document,
        (
            f"{label} is missing its self-hash field "
            f"{hash_field!r}."
        ),
    )

    expected_hash = require_sha256(
        str(document[hash_field]),
        f"{label}.{hash_field}",
    )

    payload_without_self_hash = {
        key: value
        for key, value in document.items()
        if key != hash_field
    }

    observed_hash = (
        _n05_n04_canonical_json_sha256(
            payload_without_self_hash
        )
    )

    require(
        observed_hash == expected_hash,
        (
            f"{label} self-hash mismatch:\n"
            f"expected={expected_hash}\n"
            f"observed={observed_hash}"
        ),
    )

    return observed_hash


# ------------------------------------------------------------
# Load verified Notebook 04 control documents
# ------------------------------------------------------------

NOTEBOOK_04_OUTPUT_MANIFEST = (
    require_mapping(
        UPSTREAM_CONTROL_DOCUMENTS[
            "notebook_04_output_manifest"
        ],
        "Notebook 04 output manifest",
    )
)

NOTEBOOK_04_TO_05_HANDOFF = (
    require_mapping(
        UPSTREAM_CONTROL_DOCUMENTS[
            "notebook_04_to_05_handoff"
        ],
        "Notebook 04 to Notebook 05 handoff",
    )
)

NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT = (
    require_mapping(
        UPSTREAM_CONTROL_DOCUMENTS[
            "notebook_04_final_acceptance_report"
        ],
        "Notebook 04 final acceptance report",
    )
)

require(
    classify_json_shape(
        NOTEBOOK_04_OUTPUT_MANIFEST
    )
    == JSON_SHAPE_FLAT,
    "Notebook 04 output manifest must be flat JSON.",
)

require(
    classify_json_shape(
        NOTEBOOK_04_TO_05_HANDOFF
    )
    == JSON_SHAPE_FLAT,
    "Notebook 04 handoff must be flat JSON.",
)

require(
    classify_json_shape(
        NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT
    )
    == JSON_SHAPE_FLAT,
    (
        "Notebook 04 final acceptance report must be "
        "flat JSON."
    ),
)


# ------------------------------------------------------------
# Verify artifact-specific self-hashes again
# ------------------------------------------------------------

observed_n04_manifest_payload_sha256 = (
    _n05_verify_flat_document_hash(
        NOTEBOOK_04_OUTPUT_MANIFEST,
        hash_field=(
            "manifest_payload_sha256"
        ),
        label="Notebook 04 output manifest",
    )
)

observed_n04_handoff_payload_sha256 = (
    _n05_verify_flat_document_hash(
        NOTEBOOK_04_TO_05_HANDOFF,
        hash_field=(
            "handoff_payload_sha256"
        ),
        label=(
            "Notebook 04 to Notebook 05 handoff"
        ),
    )
)

observed_n04_final_report_payload_sha256 = (
    _n05_verify_flat_document_hash(
        NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT,
        hash_field=(
            "final_acceptance_report_payload_sha256"
        ),
        label=(
            "Notebook 04 final acceptance report"
        ),
    )
)

require(
    observed_n04_manifest_payload_sha256
    == EXPECTED_NOTEBOOK_04_MANIFEST_PAYLOAD_SHA256,
    (
        "Notebook 04 output-manifest identity differs "
        "from the frozen authority map."
    ),
)

require(
    observed_n04_handoff_payload_sha256
    == EXPECTED_NOTEBOOK_04_TO_05_HANDOFF_PAYLOAD_SHA256,
    (
        "Notebook 04 handoff identity differs from the "
        "frozen authority map."
    ),
)

require(
    observed_n04_final_report_payload_sha256
    == EXPECTED_NOTEBOOK_04_FINAL_ACCEPTANCE_PAYLOAD_SHA256,
    (
        "Notebook 04 final-report identity differs from "
        "the frozen authority map."
    ),
)


# ------------------------------------------------------------
# Manifest identity and acceptance
# ------------------------------------------------------------

expected_n04_manifest_fields = {
    "artifact_type": (
        "NOTEBOOK_04_OUTPUT_MANIFEST"
    ),
    "artifact_schema_version": "1.0",
    "acceptance_status": (
        NOTEBOOK_04_EXPECTED_STATUS
    ),
    "project_name": PROJECT_NAME,
    "pipeline_version": PIPELINE_VERSION,
    "notebook_name": NOTEBOOK_04_NAME,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "v0_1_run_id": V01_RUN_ID,
    "combined_prefix": COMBINED_PREFIX,
    "operating_mode": OPERATING_MODE,
    "previous_notebook": (
        "03_CAUSAL_TRADE_BOOK_ALIGNMENT"
    ),
    "next_notebook": (
        NOTEBOOK_04_EXPECTED_NEXT_NOTEBOOK
    ),
    "primary_event_representation": (
        NOTEBOOK_04_EXPECTED_EVENT_REPRESENTATION
    ),
    "timestamp_interface": (
        NOTEBOOK_04_EXPECTED_TIMESTAMP_INTERFACE
    ),
    "primary_alignment_policy": (
        PRIMARY_ALIGNMENT_POLICY
    ),
    "primary_ordering_authority": (
        PRIMARY_ORDERING_AUTHORITY
    ),
    (
        "protected_partitions_opened_only_"
        "after_selection_freeze"
    ): True,
    "blocking_gate_failures": 0,
}

for field_name, expected_value in (
    expected_n04_manifest_fields.items()
):
    observed_value = (
        NOTEBOOK_04_OUTPUT_MANIFEST.get(
            field_name
        )
    )

    require(
        observed_value == expected_value,
        (
            f"Notebook 04 manifest field {field_name!r} "
            f"mismatch:\n"
            f"expected={expected_value!r}\n"
            f"observed={observed_value!r}"
        ),
    )


# ------------------------------------------------------------
# Handoff identity, authority, and scoring semantics
# ------------------------------------------------------------

expected_n04_handoff_fields = {
    "artifact_type": (
        "NOTEBOOK_04_TO_NOTEBOOK_05_HANDOFF"
    ),
    "artifact_schema_version": "1.0",
    "acceptance_status": (
        NOTEBOOK_04_EXPECTED_STATUS
    ),
    "project_name": PROJECT_NAME,
    "pipeline_version": PIPELINE_VERSION,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "v0_1_run_id": V01_RUN_ID,
    "combined_prefix": COMBINED_PREFIX,
    "producing_notebook": NOTEBOOK_04_NAME,
    "next_notebook": (
        NOTEBOOK_04_EXPECTED_NEXT_NOTEBOOK
    ),
    "event_stream_authorized": True,
    "feature_construction_authorized": True,
    "hawkes_estimation_authorized": False,
    "market_making_authorized": False,
    "primary_event_representation": (
        NOTEBOOK_04_EXPECTED_EVENT_REPRESENTATION
    ),
    "timestamp_interface": (
        NOTEBOOK_04_EXPECTED_TIMESTAMP_INTERFACE
    ),
    (
        "requires_simultaneous_event_"
        "batch_interface"
    ): True,
    "side_code": {
        "BUY": 0,
        "SELL": 1,
    },
    "primary_event_rows": (
        EXPECTED_PRIMARY_EVENT_ROWS
    ),
    "primary_batch_rows": (
        EXPECTED_PRIMARY_BATCH_ROWS
    ),
    "trade_print_rows_conserved": (
        EXPECTED_TRADE_MEMBERSHIP_ROWS
    ),
    "expected_trade_rows": (
        EXPECTED_TRADE_MEMBERSHIP_ROWS
    ),
    "event_partition_field": (
        PRIMARY_EVENT_PARTITION_FIELD
    ),
    "strict_no_jitter_contract": True,
    "strict_no_event_removal_contract": True,
}

for field_name, expected_value in (
    expected_n04_handoff_fields.items()
):
    observed_value = (
        NOTEBOOK_04_TO_05_HANDOFF.get(
            field_name
        )
    )

    require(
        observed_value == expected_value,
        (
            f"Notebook 04 handoff field {field_name!r} "
            f"mismatch:\n"
            f"expected={expected_value!r}\n"
            f"observed={observed_value!r}"
        ),
    )

NOTEBOOK_04_SCORING_SEMANTICS = (
    require_mapping(
        NOTEBOOK_04_TO_05_HANDOFF.get(
            "scoring_batch_semantics"
        ),
        "Notebook 04 scoring_batch_semantics",
    )
)

expected_scoring_semantics = {
    "history_used_for_batch_scoring": (
        "STRICTLY_BEFORE_BATCH_TIME"
    ),
    (
        "zero_lag_within_batch_"
        "excitation_allowed"
    ): False,
    (
        "apply_batch_excitation_after_"
        "all_members_scored"
    ): True,
    (
        "collector_sequence_inside_tie_"
        "is_trace_order_only"
    ): True,
}

for field_name, expected_value in (
    expected_scoring_semantics.items()
):
    observed_value = (
        NOTEBOOK_04_SCORING_SEMANTICS.get(
            field_name
        )
    )

    require(
        observed_value == expected_value,
        (
            f"Notebook 04 scoring semantic "
            f"{field_name!r} mismatch:\n"
            f"expected={expected_value!r}\n"
            f"observed={observed_value!r}"
        ),
    )


# ------------------------------------------------------------
# Final acceptance-report identity and authority
# ------------------------------------------------------------

expected_n04_final_report_fields = {
    "artifact_type": (
        "NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT"
    ),
    "artifact_schema_version": "1.0",
    "acceptance_status": (
        NOTEBOOK_04_EXPECTED_STATUS
    ),
    "project_name": PROJECT_NAME,
    "pipeline_version": PIPELINE_VERSION,
    "notebook_name": NOTEBOOK_04_NAME,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "v0_1_run_id": V01_RUN_ID,
    "combined_prefix": COMBINED_PREFIX,
    "primary_event_representation": (
        NOTEBOOK_04_EXPECTED_EVENT_REPRESENTATION
    ),
    "timestamp_interface": (
        NOTEBOOK_04_EXPECTED_TIMESTAMP_INTERFACE
    ),
    (
        "requires_simultaneous_event_"
        "batch_interface"
    ): True,
    "primary_event_rows": (
        EXPECTED_PRIMARY_EVENT_ROWS
    ),
    "primary_batch_rows": (
        EXPECTED_PRIMARY_BATCH_ROWS
    ),
    "trade_print_rows_conserved": (
        EXPECTED_TRADE_MEMBERSHIP_ROWS
    ),
    "expected_trade_rows": (
        EXPECTED_TRADE_MEMBERSHIP_ROWS
    ),
    "blocking_gate_failures": 0,
    "authorized_next_notebook": (
        NOTEBOOK_04_EXPECTED_NEXT_NOTEBOOK
    ),
    "notebook_05_authorized": True,
    "hawkes_estimation_authorized": False,
    "market_making_authorized": False,
}

for field_name, expected_value in (
    expected_n04_final_report_fields.items()
):
    observed_value = (
        NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT.get(
            field_name
        )
    )

    require(
        observed_value == expected_value,
        (
            f"Notebook 04 final-report field "
            f"{field_name!r} mismatch:\n"
            f"expected={expected_value!r}\n"
            f"observed={observed_value!r}"
        ),
    )


# ------------------------------------------------------------
# Cross-document path and hash reconciliation
# ------------------------------------------------------------

n04_manifest_path = (
    UPSTREAM_CONTROL_PATHS[
        "notebook_04_output_manifest"
    ].resolve()
)

n04_handoff_path = (
    UPSTREAM_CONTROL_PATHS[
        "notebook_04_to_05_handoff"
    ].resolve()
)

require(
    paths_match(
        NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT[
            "output_manifest_path"
        ],
        n04_manifest_path,
    ),
    (
        "Notebook 04 final report points to a different "
        "output manifest."
    ),
)

require(
    paths_match(
        NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT[
            "handoff_path"
        ],
        n04_handoff_path,
    ),
    (
        "Notebook 04 final report points to a different "
        "Notebook 04-to-05 handoff."
    ),
)

require(
    NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT[
        "output_manifest_payload_sha256"
    ]
    == observed_n04_manifest_payload_sha256,
    (
        "Notebook 04 final report references the wrong "
        "manifest payload hash."
    ),
)

require(
    NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT[
        "handoff_payload_sha256"
    ]
    == observed_n04_handoff_payload_sha256,
    (
        "Notebook 04 final report references the wrong "
        "handoff payload hash."
    ),
)

n04_handoff_manifest_reference = (
    require_mapping(
        NOTEBOOK_04_TO_05_HANDOFF.get(
            "notebook_04_output_manifest"
        ),
        (
            "Notebook 04 handoff "
            "notebook_04_output_manifest"
        ),
    )
)

require(
    paths_match(
        n04_handoff_manifest_reference[
            "path"
        ],
        n04_manifest_path,
    ),
    (
        "Notebook 04 handoff references a different "
        "output manifest path."
    ),
)

require(
    n04_handoff_manifest_reference[
        "manifest_payload_sha256"
    ]
    == observed_n04_manifest_payload_sha256,
    (
        "Notebook 04 handoff references a different "
        "manifest payload hash."
    ),
)


# ------------------------------------------------------------
# Verify event-stream persistence contract
# ------------------------------------------------------------

n04_persistence_contract_path = Path(
    str(
        NOTEBOOK_04_OUTPUT_MANIFEST[
            "event_stream_persistence_contract_path"
        ]
    )
).resolve(strict=True)

require_file(
    n04_persistence_contract_path,
    "Notebook 04 event-stream persistence contract",
)

require(
    path_is_within(
        n04_persistence_contract_path,
        V01_ROOT,
    ),
    (
        "Notebook 04 persistence contract resolves "
        "outside V0.1."
    ),
)

require(
    not path_is_within(
        n04_persistence_contract_path,
        V00_ROOT,
    ),
    (
        "Notebook 04 persistence contract resolves "
        "inside V0.0."
    ),
)

NOTEBOOK_04_PERSISTENCE_CONTRACT = (
    read_json_object(
        n04_persistence_contract_path
    )
)

observed_n04_persistence_contract_sha256 = (
    _n05_verify_flat_document_hash(
        NOTEBOOK_04_PERSISTENCE_CONTRACT,
        hash_field=(
            "contract_payload_sha256"
        ),
        label=(
            "Notebook 04 event-stream persistence contract"
        ),
    )
)

require(
    observed_n04_persistence_contract_sha256
    == NOTEBOOK_04_OUTPUT_MANIFEST[
        "event_stream_persistence_contract_payload_sha256"
    ],
    (
        "Notebook 04 persistence contract hash differs "
        "from the output manifest."
    ),
)

require(
    observed_n04_persistence_contract_sha256
    == (
        "4c486bab5ea30cc9dbe94bc995033fd530dca8ef8f1880680f06db63e1b88230"
    ),
    (
        "Notebook 04 persistence contract differs from "
        "the frozen project authority."
    ),
)

expected_persistence_fields = {
    "artifact_type": (
        "NOTEBOOK_04_EVENT_STREAM_PERSISTENCE_CONTRACT"
    ),
    "artifact_schema_version": "1.0",
    "acceptance_status": "PASS",
    "project_name": PROJECT_NAME,
    "pipeline_version": PIPELINE_VERSION,
    "notebook_name": NOTEBOOK_04_NAME,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "v0_1_run_id": V01_RUN_ID,
    "combined_prefix": COMBINED_PREFIX,
    "primary_event_representation": (
        NOTEBOOK_04_EXPECTED_EVENT_REPRESENTATION
    ),
    "timestamp_interface": (
        NOTEBOOK_04_EXPECTED_TIMESTAMP_INTERFACE
    ),
    (
        "requires_simultaneous_event_"
        "batch_interface"
    ): True,
    "side_code": {
        "BUY": 0,
        "SELL": 1,
    },
    "event_partition_field": (
        PRIMARY_EVENT_PARTITION_FIELD
    ),
    "primary_event_rows": (
        EXPECTED_PRIMARY_EVENT_ROWS
    ),
    "primary_batch_rows": (
        EXPECTED_PRIMARY_BATCH_ROWS
    ),
    "trade_rows_conserved": (
        EXPECTED_TRADE_MEMBERSHIP_ROWS
    ),
    "expected_trade_rows": (
        EXPECTED_TRADE_MEMBERSHIP_ROWS
    ),
    "simultaneous_batch_count": (
        EXPECTED_SIMULTANEOUS_BATCH_COUNT
    ),
    "mixed_side_batch_count": (
        EXPECTED_MIXED_SIDE_BATCH_COUNT
    ),
    "aggregate_mark_after_event_count": (
        EXPECTED_DELAYED_AGGREGATE_EVENT_COUNT
    ),
}

for field_name, expected_value in (
    expected_persistence_fields.items()
):
    observed_value = (
        NOTEBOOK_04_PERSISTENCE_CONTRACT.get(
            field_name
        )
    )

    require(
        observed_value == expected_value,
        (
            f"Notebook 04 persistence-contract field "
            f"{field_name!r} mismatch:\n"
            f"expected={expected_value!r}\n"
            f"observed={observed_value!r}"
        ),
    )


# ------------------------------------------------------------
# Build actual Notebook 04 table and array registries
# ------------------------------------------------------------

n04_table_records = require_list(
    NOTEBOOK_04_OUTPUT_MANIFEST.get(
        "table_artifacts"
    ),
    "Notebook 04 output manifest table_artifacts",
)

n04_array_records = require_list(
    NOTEBOOK_04_OUTPUT_MANIFEST.get(
        "array_artifacts"
    ),
    "Notebook 04 output manifest array_artifacts",
)

NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY = (
    pd.DataFrame.from_records(
        n04_table_records
    )
)

NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY = (
    pd.DataFrame.from_records(
        n04_array_records
    )
)

require_unique_columns(
    NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY,
    "NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY",
)

require_unique_columns(
    NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY,
    "NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY",
)

require_columns(
    NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY,
    (
        "label",
        "artifact_type",
        "format",
        "path",
        "contract_path",
        "row_count",
        "column_count",
        "table_payload_sha256",
        "file_sha256",
        "contract_payload_sha256",
        "readback_verified",
    ),
    "NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY",
)

require_columns(
    NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY,
    (
        "label",
        "artifact_type",
        "format",
        "path",
        "schema_path",
        "contract_path",
        "array_count",
        "array_payload_sha256",
        "file_sha256",
        "schema_payload_sha256",
        "contract_payload_sha256",
        "readback_verified",
    ),
    "NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY",
)

require(
    NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY[
        "label"
    ].is_unique,
    "Notebook 04 table labels are not unique.",
)

require(
    NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY[
        "label"
    ].is_unique,
    "Notebook 04 array labels are not unique.",
)

require(
    len(
        NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY
    )
    == int(
        NOTEBOOK_04_OUTPUT_MANIFEST[
            "table_artifact_count"
        ]
    ),
    (
        "Notebook 04 table-artifact count does not "
        "match its manifest."
    ),
)

require(
    len(
        NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY
    )
    == int(
        NOTEBOOK_04_OUTPUT_MANIFEST[
            "array_artifact_count"
        ]
    ),
    (
        "Notebook 04 array-artifact count does not "
        "match its manifest."
    ),
)

require(
    set(
        NOTEBOOK_04_REQUIRED_TABLE_LABELS
    ).issubset(
        set(
            NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY[
                "label"
            ].astype(str)
        )
    ),
    (
        "Notebook 04 manifest lacks one or more "
        "required Notebook 05 table inputs."
    ),
)

require(
    set(
        NOTEBOOK_04_REQUIRED_ARRAY_LABELS
    ).issubset(
        set(
            NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY[
                "label"
            ].astype(str)
        )
    ),
    (
        "Notebook 04 manifest lacks one or more "
        "required partition-array inputs."
    ),
)


# ------------------------------------------------------------
# Verify all required handoff table references against the
# manifest before loading any table
# ------------------------------------------------------------

for label in (
    NOTEBOOK_04_REQUIRED_TABLE_LABELS
):
    handoff_record = require_mapping(
        NOTEBOOK_04_TO_05_HANDOFF.get(
            label
        ),
        f"Notebook 04 handoff {label}",
    )

    manifest_matches = (
        NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY.loc[
            NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY[
                "label"
            ].eq(label)
        ]
    )

    require(
        len(manifest_matches) == 1,
        (
            f"Notebook 04 manifest must contain exactly "
            f"one record for {label!r}."
        ),
    )

    manifest_record = (
        manifest_matches.iloc[0]
    )

    require(
        paths_match(
            handoff_record["path"],
            manifest_record["path"],
        ),
        (
            f"Notebook 04 handoff and manifest paths "
            f"differ for {label!r}."
        ),
    )

    require(
        handoff_record[
            "table_payload_sha256"
        ]
        == manifest_record[
            "table_payload_sha256"
        ],
        (
            f"Notebook 04 handoff and manifest table "
            f"payload hashes differ for {label!r}."
        ),
    )


for label in (
    NOTEBOOK_04_REQUIRED_ARRAY_LABELS
):
    handoff_record = require_mapping(
        NOTEBOOK_04_TO_05_HANDOFF.get(
            label
        ),
        f"Notebook 04 handoff {label}",
    )

    manifest_matches = (
        NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY.loc[
            NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY[
                "label"
            ].eq(label)
        ]
    )

    require(
        len(manifest_matches) == 1,
        (
            f"Notebook 04 manifest must contain exactly "
            f"one array record for {label!r}."
        ),
    )

    manifest_record = (
        manifest_matches.iloc[0]
    )

    require(
        paths_match(
            handoff_record["path"],
            manifest_record["path"],
        ),
        (
            f"Notebook 04 handoff and manifest array "
            f"paths differ for {label!r}."
        ),
    )

    require(
        paths_match(
            handoff_record["schema_path"],
            manifest_record["schema_path"],
        ),
        (
            f"Notebook 04 handoff and manifest schema "
            f"paths differ for {label!r}."
        ),
    )

    require(
        handoff_record[
            "array_payload_sha256"
        ]
        == manifest_record[
            "array_payload_sha256"
        ],
        (
            f"Notebook 04 handoff and manifest array "
            f"payload hashes differ for {label!r}."
        ),
    )


# ------------------------------------------------------------
# Table verification and loading
# ------------------------------------------------------------

def _n05_verify_and_load_n04_table(
    record: Mapping[str, Any],
) -> tuple[pd.DataFrame, dict[str, Any]]:
    """Verify one Notebook 04 Parquet table and sidecar."""
    label = str(record["label"])

    require(
        str(record["format"]).lower()
        == "parquet",
        f"{label} is not registered as Parquet.",
    )

    require(
        bool(record["readback_verified"]),
        (
            f"{label} is not marked read-back verified "
            "by Notebook 04."
        ),
    )

    table_path = Path(
        str(record["path"])
    ).resolve(strict=True)

    contract_path = Path(
        str(record["contract_path"])
    ).resolve(strict=True)

    require_file(
        table_path,
        f"{label} Parquet table",
    )

    require_file(
        contract_path,
        f"{label} sidecar contract",
    )

    for candidate_path in (
        table_path,
        contract_path,
    ):
        require(
            path_is_within(
                candidate_path,
                V01_ROOT,
            ),
            (
                f"{label} artifact resolves outside "
                f"V0.1: {candidate_path}"
            ),
        )

        require(
            not path_is_within(
                candidate_path,
                V00_ROOT,
            ),
            (
                f"{label} artifact resolves inside "
                f"V0.0: {candidate_path}"
            ),
        )

    contract = read_json_object(
        contract_path
    )

    observed_contract_hash = (
        _n05_verify_flat_document_hash(
            contract,
            hash_field=(
                "contract_payload_sha256"
            ),
            label=f"{label} table sidecar",
        )
    )

    expected_contract_fields = {
        "artifact_type": (
            record["artifact_type"]
        ),
        "artifact_schema_version": "1.0",
        "acceptance_status": "PASS",
        "project_name": PROJECT_NAME,
        "pipeline_version": PIPELINE_VERSION,
        "notebook_name": NOTEBOOK_04_NAME,
        "source_run_prefix": (
            SOURCE_RUN_PREFIX
        ),
        "v0_1_run_id": V01_RUN_ID,
        "combined_prefix": COMBINED_PREFIX,
        "label": label,
        "format": "parquet",
        "path": str(table_path),
        "contract_path": str(
            contract_path
        ),
        "row_count": int(
            record["row_count"]
        ),
        "column_count": int(
            record["column_count"]
        ),
        "table_payload_sha256": (
            record[
                "table_payload_sha256"
            ]
        ),
        "file_sha256": (
            record["file_sha256"]
        ),
    }

    for field_name, expected_value in (
        expected_contract_fields.items()
    ):
        observed_value = contract.get(
            field_name
        )

        if field_name in {
            "path",
            "contract_path",
        }:
            matches = paths_match(
                observed_value,
                expected_value,
            )
        else:
            matches = (
                observed_value
                == expected_value
            )

        require(
            matches,
            (
                f"{label} sidecar field "
                f"{field_name!r} mismatch:\n"
                f"expected={expected_value!r}\n"
                f"observed={observed_value!r}"
            ),
        )

    require(
        observed_contract_hash
        == record[
            "contract_payload_sha256"
        ],
        (
            f"{label} sidecar hash differs from "
            "the manifest record."
        ),
    )

    observed_file_hash = sha256_file(
        table_path
    )

    require(
        observed_file_hash
        == record["file_sha256"],
        (
            f"{label} raw Parquet SHA-256 "
            "mismatch."
        ),
    )

    table = pd.read_parquet(
        table_path
    )

    require_unique_columns(
        table,
        label,
    )

    prepared_table = (
        _n05_n04_prepare_frame(
            table
        )
    )

    observed_table_hash = (
        _n05_n04_table_payload_sha256(
            prepared_table
        )
    )

    require(
        observed_table_hash
        == record[
            "table_payload_sha256"
        ],
        (
            f"{label} canonical table payload "
            f"SHA-256 mismatch:\n"
            f"expected="
            f"{record['table_payload_sha256']}\n"
            f"observed={observed_table_hash}"
        ),
    )

    require(
        observed_table_hash
        == contract[
            "readback_table_payload_sha256"
        ],
        (
            f"{label} semantic hash differs from "
            "the sidecar read-back identity."
        ),
    )

    require(
        len(prepared_table)
        == int(record["row_count"]),
        (
            f"{label} row-count mismatch:\n"
            f"expected={record['row_count']}\n"
            f"observed={len(prepared_table)}"
        ),
    )

    require(
        prepared_table.shape[1]
        == int(record["column_count"]),
        (
            f"{label} column-count mismatch:\n"
            f"expected={record['column_count']}\n"
            f"observed={prepared_table.shape[1]}"
        ),
    )

    require(
        list(prepared_table.columns)
        == list(contract["columns"]),
        (
            f"{label} column order differs from "
            "the sidecar schema."
        ),
    )

    audit_record = {
        "label": label,
        "artifact_type": str(
            record["artifact_type"]
        ),
        "row_count": int(
            len(prepared_table)
        ),
        "column_count": int(
            prepared_table.shape[1]
        ),
        "file_sha256": (
            observed_file_hash
        ),
        "table_payload_sha256": (
            observed_table_hash
        ),
        "contract_payload_sha256": (
            observed_contract_hash
        ),
        "resolved_path": str(
            table_path
        ),
        "status": "PASS",
    }

    return prepared_table, audit_record


notebook_04_required_tables: dict[
    str,
    pd.DataFrame,
] = {}

notebook_04_required_table_audit_rows: list[
    dict[str, Any]
] = []

for label in (
    NOTEBOOK_04_REQUIRED_TABLE_LABELS
):
    record = (
        NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY.loc[
            NOTEBOOK_04_TABLE_ARTIFACT_REGISTRY[
                "label"
            ].eq(label)
        ]
        .iloc[0]
        .to_dict()
    )

    loaded_table, audit_record = (
        _n05_verify_and_load_n04_table(
            record
        )
    )

    notebook_04_required_tables[
        label
    ] = loaded_table

    notebook_04_required_table_audit_rows.append(
        audit_record
    )


NOTEBOOK_04_REQUIRED_TABLES: Final[
    Mapping[str, pd.DataFrame]
] = MappingProxyType(
    dict(
        notebook_04_required_tables
    )
)

NOTEBOOK_04_REQUIRED_TABLE_AUDIT = (
    pd.DataFrame.from_records(
        notebook_04_required_table_audit_rows
    )
    .sort_values(
        "label",
        kind="stable",
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Verify required partition arrays without making them the
# source of market-state feature calculations
# ------------------------------------------------------------

def _n05_verify_n04_array_artifact(
    record: Mapping[str, Any],
) -> dict[str, Any]:
    """Verify one Notebook 04 NPZ artifact and contracts."""
    label = str(record["label"])

    require(
        str(record["format"]).lower()
        == "npz",
        f"{label} is not registered as NPZ.",
    )

    require(
        bool(record["readback_verified"]),
        (
            f"{label} is not marked read-back "
            "verified by Notebook 04."
        ),
    )

    npz_path = Path(
        str(record["path"])
    ).resolve(strict=True)

    schema_path = Path(
        str(record["schema_path"])
    ).resolve(strict=True)

    contract_path = Path(
        str(record["contract_path"])
    ).resolve(strict=True)

    for path_value, path_label in (
        (npz_path, f"{label} NPZ"),
        (schema_path, f"{label} schema"),
        (contract_path, f"{label} sidecar"),
    ):
        require_file(
            path_value,
            path_label,
        )

        require(
            path_is_within(
                path_value,
                V01_ROOT,
            ),
            (
                f"{path_label} resolves outside "
                f"V0.1: {path_value}"
            ),
        )

        require(
            not path_is_within(
                path_value,
                V00_ROOT,
            ),
            (
                f"{path_label} resolves inside "
                f"V0.0: {path_value}"
            ),
        )

    schema_document = read_json_object(
        schema_path
    )

    observed_schema_hash = (
        _n05_verify_flat_document_hash(
            schema_document,
            hash_field=(
                "schema_payload_sha256"
            ),
            label=f"{label} array schema",
        )
    )

    require(
        observed_schema_hash
        == record[
            "schema_payload_sha256"
        ],
        (
            f"{label} schema hash differs from "
            "the manifest record."
        ),
    )

    contract_document = read_json_object(
        contract_path
    )

    observed_contract_hash = (
        _n05_verify_flat_document_hash(
            contract_document,
            hash_field=(
                "contract_payload_sha256"
            ),
            label=f"{label} array contract",
        )
    )

    require(
        observed_contract_hash
        == record[
            "contract_payload_sha256"
        ],
        (
            f"{label} contract hash differs from "
            "the manifest record."
        ),
    )

    require(
        contract_document[
            "array_payload_sha256"
        ]
        == record[
            "array_payload_sha256"
        ],
        (
            f"{label} contract and manifest array "
            "payload hashes differ."
        ),
    )

    require(
        contract_document[
            "schema_payload_sha256"
        ]
        == record[
            "schema_payload_sha256"
        ],
        (
            f"{label} contract and schema hashes "
            "differ."
        ),
    )

    observed_file_hash = sha256_file(
        npz_path
    )

    require(
        observed_file_hash
        == record["file_sha256"],
        (
            f"{label} raw NPZ SHA-256 mismatch."
        ),
    )

    with np.load(
        npz_path,
        allow_pickle=False,
    ) as loaded:
        arrays = {
            key: np.ascontiguousarray(
                loaded[key]
            )
            for key in loaded.files
        }

    require(
        all(
            array.dtype != object
            for array in arrays.values()
        ),
        f"{label} contains an object-dtype array.",
    )

    observed_array_hash = (
        _n05_n04_array_payload_sha256(
            arrays
        )
    )

    require(
        observed_array_hash
        == record[
            "array_payload_sha256"
        ],
        (
            f"{label} canonical array payload "
            f"SHA-256 mismatch:\n"
            f"expected="
            f"{record['array_payload_sha256']}\n"
            f"observed={observed_array_hash}"
        ),
    )

    require(
        len(arrays)
        == int(record["array_count"]),
        (
            f"{label} array-count mismatch:\n"
            f"expected={record['array_count']}\n"
            f"observed={len(arrays)}"
        ),
    )

    return {
        "label": label,
        "artifact_type": str(
            record["artifact_type"]
        ),
        "array_count": int(
            len(arrays)
        ),
        "file_sha256": (
            observed_file_hash
        ),
        "array_payload_sha256": (
            observed_array_hash
        ),
        "schema_payload_sha256": (
            observed_schema_hash
        ),
        "contract_payload_sha256": (
            observed_contract_hash
        ),
        "resolved_path": str(
            npz_path
        ),
        "status": "PASS",
    }


notebook_04_array_audit_rows: list[
    dict[str, Any]
] = []

for label in (
    NOTEBOOK_04_REQUIRED_ARRAY_LABELS
):
    record = (
        NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY.loc[
            NOTEBOOK_04_ARRAY_ARTIFACT_REGISTRY[
                "label"
            ].eq(label)
        ]
        .iloc[0]
        .to_dict()
    )

    notebook_04_array_audit_rows.append(
        _n05_verify_n04_array_artifact(
            record
        )
    )

NOTEBOOK_04_REQUIRED_ARRAY_AUDIT = (
    pd.DataFrame.from_records(
        notebook_04_array_audit_rows
    )
    .sort_values(
        "label",
        kind="stable",
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Register authoritative Notebook 04 tables
# ------------------------------------------------------------

OBSERVATION_WINDOW_CONTRACT = (
    NOTEBOOK_04_REQUIRED_TABLES[
        "observation_window_contract"
    ]
)

PRIMARY_ESTIMATION_EVENTS = (
    NOTEBOOK_04_REQUIRED_TABLES[
        "primary_estimation_events"
    ]
)

PRIMARY_EXACT_TIME_BATCHES = (
    NOTEBOOK_04_REQUIRED_TABLES[
        "primary_exact_time_batches"
    ]
)

PRIMARY_TRADE_MEMBERSHIP = (
    NOTEBOOK_04_REQUIRED_TABLES[
        "primary_trade_membership"
    ]
)

PRIMARY_EVENT_TO_BATCH_MEMBERSHIP = (
    NOTEBOOK_04_REQUIRED_TABLES[
        "primary_event_to_batch_membership"
    ]
)

PRIMARY_EVENT_ARRAY_INDEX = (
    NOTEBOOK_04_REQUIRED_TABLES[
        "primary_event_array_index"
    ]
)

PRIMARY_SCORING_BATCHES = (
    NOTEBOOK_04_REQUIRED_TABLES[
        "primary_scoring_batches"
    ]
)


# ------------------------------------------------------------
# Required persisted schemas
# ------------------------------------------------------------

require_columns(
    OBSERVATION_WINDOW_CONTRACT,
    (
        "partition_order",
        "event_partition",
        "contract_sequence_start",
        "contract_sequence_end_exclusive",
        "contract_start_ns",
        "contract_end_exclusive_ns",
        "contract_duration_ns",
        "event_clock_origin_ns",
        "first_event_time_ns",
        "last_event_time_ns",
        "left_censoring_duration_ns",
        "observation_window_duration_ns",
        "primary_event_count",
        "primary_batch_count",
        "simultaneous_batch_count",
        "mixed_side_batch_count",
        "contract_interval_convention",
        "event_clock_origin_rule",
        "left_censoring_preserved",
    ),
    "OBSERVATION_WINDOW_CONTRACT",
)

require_columns(
    PRIMARY_ESTIMATION_EVENTS,
    (
        "primary_event_id",
        "primary_event_number",
        "primary_event_batch_id",
        "primary_event_batch_number",
        "partition_event_index",
        "event_partition_order",
        "event_partition",
        "event_time_ns",
        "event_side",
        "event_side_code",
        "event_print_count",
        "event_quantity",
        "event_notional",
        "initiation_trade_id",
        "initiation_trade_collector_sequence",
        "initiation_book_state_id",
        "initiation_book_collector_sequence",
        "initiation_book_local_receipt_time_ns",
        "matched_book_partition",
        "aggregate_mark_available_time_ns",
        "aggregate_mark_available_at_initiation_flag",
        "aggregate_mark_lag_after_event_ns",
        "primary_event_representation",
        "timestamp_interface",
        (
            "requires_simultaneous_event_"
            "batch_interface"
        ),
        "event_clock_origin_ns",
        "relative_event_time_ns",
        "relative_event_time_seconds",
        "contract_start_ns",
        "contract_end_exclusive_ns",
        "observation_window_duration_ns",
        "event_time_inside_contract_window_flag",
        (
            "relative_event_time_inside_"
            "window_flag"
        ),
    ),
    "PRIMARY_ESTIMATION_EVENTS",
)

require_columns(
    PRIMARY_EXACT_TIME_BATCHES,
    (
        "primary_event_batch_id",
        "primary_event_batch_number",
        "partition_batch_index",
        "event_partition_order",
        "event_partition",
        "event_time_ns",
        "batch_event_count",
        "buy_event_count",
        "sell_event_count",
        "unique_side_count",
        "batch_print_count",
        "batch_quantity",
        "batch_notional",
        "first_primary_event_id",
        "last_primary_event_id",
        "mixed_side_batch_flag",
        "simultaneous_batch_required_flag",
        "event_clock_origin_ns",
        "relative_batch_time_ns",
        "relative_batch_time_seconds",
        "contract_start_ns",
        "contract_end_exclusive_ns",
        "observation_window_duration_ns",
        (
            "batch_time_inside_contract_"
            "window_flag"
        ),
        (
            "relative_batch_time_inside_"
            "window_flag"
        ),
    ),
    "PRIMARY_EXACT_TIME_BATCHES",
)

require_columns(
    PRIMARY_SCORING_BATCHES,
    (
        "primary_event_batch_id",
        "primary_event_batch_number",
        "partition_batch_index",
        "event_partition_order",
        "event_partition",
        "event_time_ns",
        "relative_batch_time_ns",
        "relative_batch_time_seconds",
        "batch_event_count",
        "buy_event_count",
        "sell_event_count",
        "unique_side_count",
        "batch_print_count",
        "batch_quantity",
        "batch_notional",
        "mixed_side_batch_flag",
        "simultaneous_batch_required_flag",
        "event_clock_origin_ns",
        "observation_window_duration_ns",
        (
            "score_with_history_strictly_"
            "before_batch_time"
        ),
        (
            "zero_lag_within_batch_"
            "excitation_allowed"
        ),
        (
            "apply_batch_excitation_after_"
            "all_members_scored"
        ),
        (
            "collector_sequence_is_"
            "trace_order_only"
        ),
        "timestamp_jitter_allowed",
        "event_removal_allowed",
    ),
    "PRIMARY_SCORING_BATCHES",
)

require_columns(
    PRIMARY_EVENT_TO_BATCH_MEMBERSHIP,
    (
        "primary_event_id",
        "primary_event_number",
        "partition_event_index",
        "primary_event_batch_id",
        "primary_event_batch_number",
        "event_partition_order",
        "event_partition",
        "event_time_ns",
        "event_side",
        "event_side_code",
    ),
    "PRIMARY_EVENT_TO_BATCH_MEMBERSHIP",
)

require_columns(
    PRIMARY_TRADE_MEMBERSHIP,
    (
        "trade_id",
        "trade_collector_sequence",
        "trade_local_receipt_time_ns",
        "trade_exchange_trade_time_ms",
        "trade_aggressor_side",
        "event_partition",
        "event_partition_order",
        "primary_event_id",
        "primary_event_number",
    ),
    "PRIMARY_TRADE_MEMBERSHIP",
)

require_columns(
    PRIMARY_EVENT_ARRAY_INDEX,
    (
        "primary_event_id",
        "primary_event_number",
        "partition_event_index",
        "primary_event_batch_id",
        "primary_event_batch_number",
        "event_partition_order",
        "event_partition",
        "event_time_ns",
    ),
    "PRIMARY_EVENT_ARRAY_INDEX",
)


# ------------------------------------------------------------
# Row counts and unique identities
# ------------------------------------------------------------

require(
    len(PRIMARY_ESTIMATION_EVENTS)
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Primary event row count mismatch:\n"
        f"expected={EXPECTED_PRIMARY_EVENT_ROWS:,}\n"
        f"observed="
        f"{len(PRIMARY_ESTIMATION_EVENTS):,}"
    ),
)

require(
    len(PRIMARY_EXACT_TIME_BATCHES)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Primary exact-time batch row count mismatch:\n"
        f"expected={EXPECTED_PRIMARY_BATCH_ROWS:,}\n"
        f"observed="
        f"{len(PRIMARY_EXACT_TIME_BATCHES):,}"
    ),
)

require(
    len(PRIMARY_SCORING_BATCHES)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Primary scoring-batch row count mismatch:\n"
        f"expected={EXPECTED_PRIMARY_BATCH_ROWS:,}\n"
        f"observed="
        f"{len(PRIMARY_SCORING_BATCHES):,}"
    ),
)

require(
    len(PRIMARY_TRADE_MEMBERSHIP)
    == EXPECTED_TRADE_MEMBERSHIP_ROWS,
    (
        "Primary trade-membership row count mismatch:\n"
        f"expected={EXPECTED_TRADE_MEMBERSHIP_ROWS:,}\n"
        f"observed="
        f"{len(PRIMARY_TRADE_MEMBERSHIP):,}"
    ),
)

require(
    len(
        PRIMARY_EVENT_TO_BATCH_MEMBERSHIP
    )
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Event-to-batch membership row count mismatch."
    ),
)

require(
    len(PRIMARY_EVENT_ARRAY_INDEX)
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Primary event-array index row count mismatch."
    ),
)

require(
    len(OBSERVATION_WINDOW_CONTRACT)
    == len(PARTITION_ORDER),
    (
        "Observation-window contract does not cover "
        "all partitions."
    ),
)

require(
    PRIMARY_ESTIMATION_EVENTS[
        "primary_event_id"
    ].is_unique,
    "Primary event IDs are not unique.",
)

require(
    PRIMARY_ESTIMATION_EVENTS[
        "primary_event_number"
    ].is_unique,
    "Primary event numbers are not unique.",
)

require(
    PRIMARY_EXACT_TIME_BATCHES[
        "primary_event_batch_id"
    ].is_unique,
    "Primary batch IDs are not unique.",
)

require(
    PRIMARY_EXACT_TIME_BATCHES[
        "primary_event_batch_number"
    ].is_unique,
    "Primary batch numbers are not unique.",
)

require(
    PRIMARY_TRADE_MEMBERSHIP[
        "trade_id"
    ].is_unique,
    (
        "A trade appears more than once in primary "
        "trade membership."
    ),
)

require(
    PRIMARY_EVENT_TO_BATCH_MEMBERSHIP[
        "primary_event_id"
    ].is_unique,
    (
        "A primary event appears more than once in "
        "event-to-batch membership."
    ),
)

require(
    PRIMARY_EVENT_ARRAY_INDEX[
        "primary_event_id"
    ].is_unique,
    (
        "A primary event appears more than once in "
        "the event-array index."
    ),
)


# ------------------------------------------------------------
# Strict numeric and Boolean parsing
# ------------------------------------------------------------

primary_event_time_ns = parse_required_int64(
    PRIMARY_ESTIMATION_EVENTS[
        "event_time_ns"
    ],
    "PRIMARY_ESTIMATION_EVENTS.event_time_ns",
)

primary_event_number = parse_required_int64(
    PRIMARY_ESTIMATION_EVENTS[
        "primary_event_number"
    ],
    (
        "PRIMARY_ESTIMATION_EVENTS."
        "primary_event_number"
    ),
)

primary_event_batch_number = parse_required_int64(
    PRIMARY_ESTIMATION_EVENTS[
        "primary_event_batch_number"
    ],
    (
        "PRIMARY_ESTIMATION_EVENTS."
        "primary_event_batch_number"
    ),
)

primary_event_print_count = parse_required_int64(
    PRIMARY_ESTIMATION_EVENTS[
        "event_print_count"
    ],
    (
        "PRIMARY_ESTIMATION_EVENTS."
        "event_print_count"
    ),
)

primary_event_quantity = parse_required_float64(
    PRIMARY_ESTIMATION_EVENTS[
        "event_quantity"
    ],
    (
        "PRIMARY_ESTIMATION_EVENTS."
        "event_quantity"
    ),
)

primary_event_notional = parse_required_float64(
    PRIMARY_ESTIMATION_EVENTS[
        "event_notional"
    ],
    (
        "PRIMARY_ESTIMATION_EVENTS."
        "event_notional"
    ),
)

aggregate_mark_available_time_ns = (
    parse_required_int64(
        PRIMARY_ESTIMATION_EVENTS[
            "aggregate_mark_available_time_ns"
        ],
        (
            "PRIMARY_ESTIMATION_EVENTS."
            "aggregate_mark_available_time_ns"
        ),
    )
)

aggregate_mark_lag_ns = (
    parse_required_int64(
        PRIMARY_ESTIMATION_EVENTS[
            "aggregate_mark_lag_after_event_ns"
        ],
        (
            "PRIMARY_ESTIMATION_EVENTS."
            "aggregate_mark_lag_after_event_ns"
        ),
    )
)

aggregate_available_at_initiation = (
    strict_boolean_series(
        PRIMARY_ESTIMATION_EVENTS[
            "aggregate_mark_available_at_initiation_flag"
        ],
        field_name=(
            "PRIMARY_ESTIMATION_EVENTS."
            "aggregate_mark_available_at_initiation_flag"
        ),
    )
)

primary_requires_batch_interface = (
    strict_boolean_series(
        PRIMARY_ESTIMATION_EVENTS[
            (
                "requires_simultaneous_event_"
                "batch_interface"
            )
        ],
        field_name=(
            "PRIMARY_ESTIMATION_EVENTS."
            "requires_simultaneous_event_batch_interface"
        ),
    )
)

exact_batch_event_count = parse_required_int64(
    PRIMARY_EXACT_TIME_BATCHES[
        "batch_event_count"
    ],
    (
        "PRIMARY_EXACT_TIME_BATCHES."
        "batch_event_count"
    ),
)

exact_batch_print_count = parse_required_int64(
    PRIMARY_EXACT_TIME_BATCHES[
        "batch_print_count"
    ],
    (
        "PRIMARY_EXACT_TIME_BATCHES."
        "batch_print_count"
    ),
)

exact_batch_quantity = parse_required_float64(
    PRIMARY_EXACT_TIME_BATCHES[
        "batch_quantity"
    ],
    (
        "PRIMARY_EXACT_TIME_BATCHES."
        "batch_quantity"
    ),
)

exact_batch_notional = parse_required_float64(
    PRIMARY_EXACT_TIME_BATCHES[
        "batch_notional"
    ],
    (
        "PRIMARY_EXACT_TIME_BATCHES."
        "batch_notional"
    ),
)

simultaneous_batch_flag = (
    strict_boolean_series(
        PRIMARY_EXACT_TIME_BATCHES[
            "simultaneous_batch_required_flag"
        ],
        field_name=(
            "PRIMARY_EXACT_TIME_BATCHES."
            "simultaneous_batch_required_flag"
        ),
    )
)

mixed_side_batch_flag = (
    strict_boolean_series(
        PRIMARY_EXACT_TIME_BATCHES[
            "mixed_side_batch_flag"
        ],
        field_name=(
            "PRIMARY_EXACT_TIME_BATCHES."
            "mixed_side_batch_flag"
        ),
    )
)


# ------------------------------------------------------------
# Primary event semantic authority
# ------------------------------------------------------------

require(
    PRIMARY_ESTIMATION_EVENTS[
        "primary_event_representation"
    ].astype(str).eq(
        NOTEBOOK_04_EXPECTED_EVENT_REPRESENTATION
    ).all(),
    (
        "Primary event rows contain an unexpected event "
        "representation."
    ),
)

require(
    PRIMARY_ESTIMATION_EVENTS[
        "timestamp_interface"
    ].astype(str).eq(
        NOTEBOOK_04_EXPECTED_TIMESTAMP_INTERFACE
    ).all(),
    (
        "Primary event rows contain an unexpected timestamp "
        "interface."
    ),
)

require(
    primary_requires_batch_interface.all(),
    (
        "At least one primary event does not preserve the "
        "required simultaneous-batch interface."
    ),
)

require(
    set(
        PRIMARY_ESTIMATION_EVENTS[
            "event_side"
        ].astype(str).unique()
    )
    == set(VALID_AGGRESSOR_SIDES),
    (
        "Primary-event side domain differs from "
        "{BUY, SELL}."
    ),
)

observed_event_side_code = (
    PRIMARY_ESTIMATION_EVENTS[
        "event_side"
    ]
    .astype(str)
    .map(NOTEBOOK_04_SIDE_CODE)
)

stored_event_side_code = pd.to_numeric(
    PRIMARY_ESTIMATION_EVENTS[
        "event_side_code"
    ],
    errors="raise",
).astype("int64")

require(
    observed_event_side_code.notna().all(),
    "At least one event side cannot be encoded.",
)

require(
    stored_event_side_code.equals(
        observed_event_side_code.astype(
            "int64"
        )
    ),
    (
        "Primary-event side codes do not match the frozen "
        "Notebook 04 mapping."
    ),
)

require(
    primary_event_number.tolist()
    == list(
        range(
            1,
            EXPECTED_PRIMARY_EVENT_ROWS + 1,
        )
    ),
    "Primary event numbers are not consecutive.",
)

require(
    primary_event_print_count.ge(1).all(),
    "At least one primary event has no trade prints.",
)

require(
    primary_event_quantity.gt(0).all(),
    "At least one primary event has non-positive quantity.",
)

require(
    primary_event_notional.gt(0).all(),
    "At least one primary event has non-positive notional.",
)

require(
    int(
        primary_event_print_count.sum()
    )
    == EXPECTED_TRADE_MEMBERSHIP_ROWS,
    (
        "Primary-event print counts do not conserve all "
        "matched trades."
    ),
)


# ------------------------------------------------------------
# Delayed aggregate-mark timing authority
# ------------------------------------------------------------

require(
    aggregate_mark_lag_ns.equals(
        aggregate_mark_available_time_ns
        - primary_event_time_ns
    ),
    (
        "Aggregate-mark lag does not equal availability time "
        "minus event time."
    ),
)

require(
    aggregate_mark_lag_ns.ge(0).all(),
    (
        "At least one aggregate mark is backdated before its "
        "event initiation."
    ),
)

expected_available_at_initiation = (
    aggregate_mark_available_time_ns.eq(
        primary_event_time_ns
    )
    & primary_event_print_count.eq(1)
)

require(
    aggregate_available_at_initiation.equals(
        expected_available_at_initiation
    ),
    (
        "Aggregate-mark initiation-availability flags do not "
        "match the persisted Notebook 04 definition."
    ),
)

observed_delayed_aggregate_count = int(
    aggregate_mark_lag_ns.gt(0).sum()
)

require(
    observed_delayed_aggregate_count
    == EXPECTED_DELAYED_AGGREGATE_EVENT_COUNT,
    (
        "Delayed aggregate-mark count mismatch:\n"
        f"expected="
        f"{EXPECTED_DELAYED_AGGREGATE_EVENT_COUNT:,}\n"
        f"observed="
        f"{observed_delayed_aggregate_count:,}"
    ),
)


# ------------------------------------------------------------
# Exact-time batch identity and scoring-spine identity
# ------------------------------------------------------------

batch_identity_columns = [
    "primary_event_batch_id",
    "primary_event_batch_number",
    "partition_batch_index",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
    "relative_batch_time_ns",
    "relative_batch_time_seconds",
    "batch_event_count",
    "buy_event_count",
    "sell_event_count",
    "unique_side_count",
    "batch_print_count",
    "batch_quantity",
    "batch_notional",
    "mixed_side_batch_flag",
    "simultaneous_batch_required_flag",
    "event_clock_origin_ns",
    "observation_window_duration_ns",
]

exact_batch_identity = (
    PRIMARY_EXACT_TIME_BATCHES[
        batch_identity_columns
    ]
    .reset_index(drop=True)
)

scoring_batch_identity = (
    PRIMARY_SCORING_BATCHES[
        batch_identity_columns
    ]
    .reset_index(drop=True)
)

require(
    _n05_n04_table_payload_sha256(
        exact_batch_identity
    )
    == _n05_n04_table_payload_sha256(
        scoring_batch_identity
    ),
    (
        "Primary scoring-batch spine differs from the "
        "authoritative exact-time batch table."
    ),
)

require(
    PRIMARY_SCORING_BATCHES[
        "primary_event_batch_number"
    ].astype("int64").tolist()
    == list(
        range(
            1,
            EXPECTED_PRIMARY_BATCH_ROWS + 1,
        )
    ),
    "Primary batch numbers are not consecutive.",
)

require(
    not PRIMARY_EXACT_TIME_BATCHES[
        [
            "event_partition",
            "event_time_ns",
        ]
    ].duplicated().any(),
    (
        "More than one authoritative batch exists for the "
        "same partition and event time."
    ),
)

require(
    int(
        exact_batch_event_count.sum()
    )
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Exact-time batch event counts do not conserve "
        "primary events."
    ),
)

require(
    int(
        exact_batch_print_count.sum()
    )
    == EXPECTED_TRADE_MEMBERSHIP_ROWS,
    (
        "Exact-time batch print counts do not conserve "
        "trade prints."
    ),
)

require(
    simultaneous_batch_flag.equals(
        exact_batch_event_count.gt(1)
    ),
    (
        "Simultaneous-batch flags do not equal "
        "batch_event_count > 1."
    ),
)

require(
    int(
        simultaneous_batch_flag.sum()
    )
    == EXPECTED_SIMULTANEOUS_BATCH_COUNT,
    (
        "Simultaneous-batch count mismatch."
    ),
)

require(
    int(
        mixed_side_batch_flag.sum()
    )
    == EXPECTED_MIXED_SIDE_BATCH_COUNT,
    (
        "Mixed-side batch count mismatch."
    ),
)

require(
    (
        pd.to_numeric(
            PRIMARY_EXACT_TIME_BATCHES[
                "buy_event_count"
            ],
            errors="raise",
        )
        + pd.to_numeric(
            PRIMARY_EXACT_TIME_BATCHES[
                "sell_event_count"
            ],
            errors="raise",
        )
    ).astype("int64").equals(
        exact_batch_event_count
    ),
    (
        "BUY and SELL event counts do not sum to batch "
        "event counts."
    ),
)


# ------------------------------------------------------------
# Frozen batch-scoring semantics in every scoring row
# ------------------------------------------------------------

require(
    strict_boolean_series(
        PRIMARY_SCORING_BATCHES[
            (
                "score_with_history_strictly_"
                "before_batch_time"
            )
        ],
        field_name=(
            "PRIMARY_SCORING_BATCHES."
            "score_with_history_strictly_before_batch_time"
        ),
    ).all(),
    (
        "At least one scoring batch does not require "
        "strictly prior history."
    ),
)

require(
    not strict_boolean_series(
        PRIMARY_SCORING_BATCHES[
            (
                "zero_lag_within_batch_"
                "excitation_allowed"
            )
        ],
        field_name=(
            "PRIMARY_SCORING_BATCHES."
            "zero_lag_within_batch_excitation_allowed"
        ),
    ).any(),
    (
        "At least one scoring batch permits zero-lag "
        "within-batch excitation."
    ),
)

require(
    strict_boolean_series(
        PRIMARY_SCORING_BATCHES[
            (
                "apply_batch_excitation_after_"
                "all_members_scored"
            )
        ],
        field_name=(
            "PRIMARY_SCORING_BATCHES."
            "apply_batch_excitation_after_all_members_scored"
        ),
    ).all(),
    (
        "At least one scoring batch does not defer batch "
        "excitation until all members are scored."
    ),
)

require(
    strict_boolean_series(
        PRIMARY_SCORING_BATCHES[
            (
                "collector_sequence_is_"
                "trace_order_only"
            )
        ],
        field_name=(
            "PRIMARY_SCORING_BATCHES."
            "collector_sequence_is_trace_order_only"
        ),
    ).all(),
    (
        "At least one scoring batch treats collector "
        "sequence as physical elapsed time."
    ),
)

require(
    not strict_boolean_series(
        PRIMARY_SCORING_BATCHES[
            "timestamp_jitter_allowed"
        ],
        field_name=(
            "PRIMARY_SCORING_BATCHES."
            "timestamp_jitter_allowed"
        ),
    ).any(),
    (
        "At least one scoring batch permits timestamp "
        "jitter."
    ),
)

require(
    not strict_boolean_series(
        PRIMARY_SCORING_BATCHES[
            "event_removal_allowed"
        ],
        field_name=(
            "PRIMARY_SCORING_BATCHES."
            "event_removal_allowed"
        ),
    ).any(),
    (
        "At least one scoring batch permits event removal."
    ),
)


# ------------------------------------------------------------
# Event-to-batch membership conservation and reconciliation
# ------------------------------------------------------------

event_membership_ids = set(
    PRIMARY_EVENT_TO_BATCH_MEMBERSHIP[
        "primary_event_id"
    ].astype(str)
)

primary_event_ids = set(
    PRIMARY_ESTIMATION_EVENTS[
        "primary_event_id"
    ].astype(str)
)

require(
    event_membership_ids
    == primary_event_ids,
    (
        "Event-to-batch membership does not cover the exact "
        "primary-event identity set."
    ),
)

require(
    set(
        PRIMARY_EVENT_TO_BATCH_MEMBERSHIP[
            "primary_event_batch_id"
        ].astype(str)
    ).issubset(
        set(
            PRIMARY_EXACT_TIME_BATCHES[
                "primary_event_batch_id"
            ].astype(str)
        )
    ),
    (
        "Event-to-batch membership references an unknown "
        "batch ID."
    ),
)

event_membership_reconciliation = (
    PRIMARY_EVENT_TO_BATCH_MEMBERSHIP[
        [
            "primary_event_id",
            "primary_event_number",
            "partition_event_index",
            "primary_event_batch_id",
            "primary_event_batch_number",
            "event_partition_order",
            "event_partition",
            "event_time_ns",
            "event_side",
            "event_side_code",
        ]
    ]
    .merge(
        PRIMARY_ESTIMATION_EVENTS[
            [
                "primary_event_id",
                "primary_event_number",
                "partition_event_index",
                "primary_event_batch_id",
                "primary_event_batch_number",
                "event_partition_order",
                "event_partition",
                "event_time_ns",
                "event_side",
                "event_side_code",
            ]
        ],
        on="primary_event_id",
        how="outer",
        suffixes=(
            "__membership",
            "__event",
        ),
        indicator=True,
        validate="one_to_one",
    )
)

require(
    event_membership_reconciliation[
        "_merge"
    ].eq("both").all(),
    (
        "Event-to-batch membership and primary-event table "
        "do not have identical event membership."
    ),
)

for field_name in (
    "primary_event_number",
    "partition_event_index",
    "primary_event_batch_id",
    "primary_event_batch_number",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
    "event_side",
    "event_side_code",
):
    left = (
        event_membership_reconciliation[
            f"{field_name}__membership"
        ]
        .astype("string")
        .fillna("<NA>")
    )

    right = (
        event_membership_reconciliation[
            f"{field_name}__event"
        ]
        .astype("string")
        .fillna("<NA>")
    )

    require(
        left.equals(right),
        (
            "Event-to-batch membership differs from the "
            f"primary-event table for {field_name!r}."
        ),
    )


# ------------------------------------------------------------
# Recompute exact-time batch aggregates from the event table
# ------------------------------------------------------------

recomputed_batch_aggregates = (
    PRIMARY_ESTIMATION_EVENTS.groupby(
        [
            "primary_event_batch_id",
            "primary_event_batch_number",
            "event_partition_order",
            "event_partition",
            "event_time_ns",
        ],
        observed=True,
        sort=False,
        dropna=False,
    )
    .agg(
        recomputed_batch_event_count=(
            "primary_event_id",
            "size",
        ),
        recomputed_buy_event_count=(
            "event_side",
            lambda values: int(
                values.astype(str)
                .eq("BUY")
                .sum()
            ),
        ),
        recomputed_sell_event_count=(
            "event_side",
            lambda values: int(
                values.astype(str)
                .eq("SELL")
                .sum()
            ),
        ),
        recomputed_unique_side_count=(
            "event_side",
            "nunique",
        ),
        recomputed_batch_print_count=(
            "event_print_count",
            "sum",
        ),
        recomputed_batch_quantity=(
            "event_quantity",
            "sum",
        ),
        recomputed_batch_notional=(
            "event_notional",
            "sum",
        ),
    )
    .reset_index()
)

batch_reconciliation = (
    PRIMARY_EXACT_TIME_BATCHES.merge(
        recomputed_batch_aggregates,
        on=[
            "primary_event_batch_id",
            "primary_event_batch_number",
            "event_partition_order",
            "event_partition",
            "event_time_ns",
        ],
        how="outer",
        indicator=True,
        validate="one_to_one",
    )
)

require(
    batch_reconciliation[
        "_merge"
    ].eq("both").all(),
    (
        "Recomputed primary batches do not match the "
        "persisted exact-time batch identity set."
    ),
)

for stored_field, recomputed_field in (
    (
        "batch_event_count",
        "recomputed_batch_event_count",
    ),
    (
        "buy_event_count",
        "recomputed_buy_event_count",
    ),
    (
        "sell_event_count",
        "recomputed_sell_event_count",
    ),
    (
        "unique_side_count",
        "recomputed_unique_side_count",
    ),
    (
        "batch_print_count",
        "recomputed_batch_print_count",
    ),
):
    stored_values = pd.to_numeric(
        batch_reconciliation[
            stored_field
        ],
        errors="raise",
    ).astype("int64")

    recomputed_values = pd.to_numeric(
        batch_reconciliation[
            recomputed_field
        ],
        errors="raise",
    ).astype("int64")

    require(
        stored_values.equals(
            recomputed_values
        ),
        (
            f"Persisted batch field {stored_field!r} "
            "does not reconcile to primary events."
        ),
    )

for stored_field, recomputed_field in (
    (
        "batch_quantity",
        "recomputed_batch_quantity",
    ),
    (
        "batch_notional",
        "recomputed_batch_notional",
    ),
):
    stored_values = pd.to_numeric(
        batch_reconciliation[
            stored_field
        ],
        errors="raise",
    ).astype("float64")

    recomputed_values = pd.to_numeric(
        batch_reconciliation[
            recomputed_field
        ],
        errors="raise",
    ).astype("float64")

    require(
        np.allclose(
            stored_values.to_numpy(),
            recomputed_values.to_numpy(),
            rtol=1e-12,
            atol=1e-10,
        ),
        (
            f"Persisted batch field {stored_field!r} "
            "does not reconcile to primary events."
        ),
    )


# ------------------------------------------------------------
# Trade-to-event membership conservation
# ------------------------------------------------------------

require(
    set(
        PRIMARY_TRADE_MEMBERSHIP[
            "primary_event_id"
        ].astype(str)
    ).issubset(
        primary_event_ids
    ),
    (
        "Primary trade membership references an unknown "
        "primary event."
    ),
)

require(
    set(
        PRIMARY_TRADE_MEMBERSHIP[
            "trade_id"
        ].astype(str)
    )
    == set(
        LOCAL_STRICT_MATCHED_TRADE_BOOK[
            "trade_id"
        ].astype(str)
    ),
    (
        "Primary trade membership does not conserve the "
        "Notebook 03 trade identity set."
    ),
)

trade_membership_event_counts = (
    PRIMARY_TRADE_MEMBERSHIP.groupby(
        "primary_event_id",
        observed=True,
        sort=False,
        dropna=False,
    )
    .size()
    .rename(
        "membership_print_count"
    )
)

event_print_count_by_id = (
    PRIMARY_ESTIMATION_EVENTS.set_index(
        "primary_event_id"
    )[
        "event_print_count"
    ]
    .astype("int64")
)

trade_membership_count_reconciliation = (
    event_print_count_by_id.to_frame()
    .join(
        trade_membership_event_counts,
        how="outer",
    )
)

require(
    trade_membership_count_reconciliation[
        [
            "event_print_count",
            "membership_print_count",
        ]
    ].notna().all().all(),
    (
        "At least one primary event is missing from either "
        "the event table or trade-membership ledger."
    ),
)

require(
    trade_membership_count_reconciliation[
        "event_print_count"
    ].astype("int64").equals(
        trade_membership_count_reconciliation[
            "membership_print_count"
        ].astype("int64")
    ),
    (
        "Primary event print counts differ from the number "
        "of constituent trade-membership rows."
    ),
)


# ------------------------------------------------------------
# Event-array index identity
# ------------------------------------------------------------

event_array_identity_columns = [
    "primary_event_id",
    "primary_event_number",
    "partition_event_index",
    "primary_event_batch_id",
    "primary_event_batch_number",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
]

event_array_reconciliation = (
    PRIMARY_EVENT_ARRAY_INDEX[
        event_array_identity_columns
    ]
    .merge(
        PRIMARY_ESTIMATION_EVENTS[
            event_array_identity_columns
        ],
        on="primary_event_id",
        how="outer",
        suffixes=(
            "__array",
            "__event",
        ),
        indicator=True,
        validate="one_to_one",
    )
)

require(
    event_array_reconciliation[
        "_merge"
    ].eq("both").all(),
    (
        "Primary event-array index does not conserve the "
        "primary-event identity set."
    ),
)

for field_name in (
    "primary_event_number",
    "partition_event_index",
    "primary_event_batch_id",
    "primary_event_batch_number",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
):
    left = (
        event_array_reconciliation[
            f"{field_name}__array"
        ]
        .astype("string")
        .fillna("<NA>")
    )

    right = (
        event_array_reconciliation[
            f"{field_name}__event"
        ]
        .astype("string")
        .fillna("<NA>")
    )

    require(
        left.equals(right),
        (
            f"Primary event-array index differs from the "
            f"event table for {field_name!r}."
        ),
    )


# ------------------------------------------------------------
# Observation-window and partition reconciliation
# ------------------------------------------------------------

require(
    tuple(
        OBSERVATION_WINDOW_CONTRACT.sort_values(
            "partition_order",
            kind="stable",
        )[
            "event_partition"
        ].astype(str)
    )
    == PARTITION_ORDER,
    (
        "Observation-window partition order differs from "
        "Notebook 00."
    ),
)

require(
    OBSERVATION_WINDOW_CONTRACT[
        "event_partition"
    ].is_unique,
    (
        "Observation-window contract contains duplicate "
        "partitions."
    ),
)

require(
    OBSERVATION_WINDOW_CONTRACT[
        "contract_interval_convention"
    ].astype(str).eq(
        INTERVAL_CONVENTION
    ).all(),
    (
        "Observation-window contract contains a non-half-open "
        "interval convention."
    ),
)

require(
    strict_boolean_series(
        OBSERVATION_WINDOW_CONTRACT[
            "left_censoring_preserved"
        ],
        field_name=(
            "OBSERVATION_WINDOW_CONTRACT."
            "left_censoring_preserved"
        ),
    ).all(),
    (
        "Observation-window contract does not preserve "
        "left censoring."
    ),
)

observed_primary_event_partition_counts = (
    PRIMARY_ESTIMATION_EVENTS[
        "event_partition"
    ]
    .astype(str)
    .value_counts(sort=False)
    .reindex(PARTITION_ORDER)
    .fillna(0)
    .astype("int64")
)

contract_primary_event_partition_counts = (
    OBSERVATION_WINDOW_CONTRACT.set_index(
        "event_partition"
    )[
        "primary_event_count"
    ]
    .astype("int64")
    .reindex(PARTITION_ORDER)
)

require(
    observed_primary_event_partition_counts.equals(
        contract_primary_event_partition_counts
    ),
    (
        "Primary event partition counts differ from the "
        "observation-window contract."
    ),
)

observed_primary_batch_partition_counts = (
    PRIMARY_EXACT_TIME_BATCHES[
        "event_partition"
    ]
    .astype(str)
    .value_counts(sort=False)
    .reindex(PARTITION_ORDER)
    .fillna(0)
    .astype("int64")
)

contract_primary_batch_partition_counts = (
    OBSERVATION_WINDOW_CONTRACT.set_index(
        "event_partition"
    )[
        "primary_batch_count"
    ]
    .astype("int64")
    .reindex(PARTITION_ORDER)
)

require(
    observed_primary_batch_partition_counts.equals(
        contract_primary_batch_partition_counts
    ),
    (
        "Primary batch partition counts differ from the "
        "observation-window contract."
    ),
)

require(
    strict_boolean_series(
        PRIMARY_ESTIMATION_EVENTS[
            "event_time_inside_contract_window_flag"
        ],
        field_name=(
            "PRIMARY_ESTIMATION_EVENTS."
            "event_time_inside_contract_window_flag"
        ),
    ).all(),
    (
        "At least one primary event lies outside its frozen "
        "contract window."
    ),
)

require(
    strict_boolean_series(
        PRIMARY_ESTIMATION_EVENTS[
            (
                "relative_event_time_inside_"
                "window_flag"
            )
        ],
        field_name=(
            "PRIMARY_ESTIMATION_EVENTS."
            "relative_event_time_inside_window_flag"
        ),
    ).all(),
    (
        "At least one primary event lies outside its "
        "relative observation window."
    ),
)

require(
    strict_boolean_series(
        PRIMARY_EXACT_TIME_BATCHES[
            (
                "batch_time_inside_contract_"
                "window_flag"
            )
        ],
        field_name=(
            "PRIMARY_EXACT_TIME_BATCHES."
            "batch_time_inside_contract_window_flag"
        ),
    ).all(),
    (
        "At least one primary batch lies outside its frozen "
        "contract window."
    ),
)

require(
    strict_boolean_series(
        PRIMARY_EXACT_TIME_BATCHES[
            (
                "relative_batch_time_inside_"
                "window_flag"
            )
        ],
        field_name=(
            "PRIMARY_EXACT_TIME_BATCHES."
            "relative_batch_time_inside_window_flag"
        ),
    ).all(),
    (
        "At least one primary batch lies outside its "
        "relative observation window."
    ),
)


# ------------------------------------------------------------
# Notebook 04 warning reconciliation
# ------------------------------------------------------------

n04_manifest_warnings = require_mapping(
    NOTEBOOK_04_OUTPUT_MANIFEST.get(
        "warning_findings"
    ),
    "Notebook 04 manifest warning_findings",
)

n04_final_warnings = require_mapping(
    NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT.get(
        "warning_findings"
    ),
    (
        "Notebook 04 final acceptance warning_findings"
    ),
)

for warning_field, expected_value in (
    (
        "simultaneous_batch_count",
        EXPECTED_SIMULTANEOUS_BATCH_COUNT,
    ),
    (
        "mixed_side_batch_count",
        EXPECTED_MIXED_SIDE_BATCH_COUNT,
    ),
    (
        "aggregate_mark_after_event_count",
        EXPECTED_DELAYED_AGGREGATE_EVENT_COUNT,
    ),
):
    require(
        int(
            n04_manifest_warnings[
                warning_field
            ]
        )
        == expected_value,
        (
            f"Notebook 04 manifest warning "
            f"{warning_field!r} mismatch."
        ),
    )

    require(
        int(
            n04_final_warnings[
                warning_field
            ]
        )
        == expected_value,
        (
            f"Notebook 04 final-report warning "
            f"{warning_field!r} mismatch."
        ),
    )


# ------------------------------------------------------------
# Notebook 04 authority gates
# ------------------------------------------------------------

NOTEBOOK_04_AUTHORITY_GATES = pd.DataFrame(
    [
        {
            "gate": (
                "output_manifest_payload_verified"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                observed_n04_manifest_payload_sha256
            ),
        },
        {
            "gate": (
                "handoff_payload_verified"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                observed_n04_handoff_payload_sha256
            ),
        },
        {
            "gate": (
                "final_acceptance_payload_verified"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                observed_n04_final_report_payload_sha256
            ),
        },
        {
            "gate": (
                "persistence_contract_verified"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                observed_n04_persistence_contract_sha256
            ),
        },
        {
            "gate": (
                "required_table_artifacts_verified"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    NOTEBOOK_04_REQUIRED_TABLE_AUDIT
                )
                == len(
                    NOTEBOOK_04_REQUIRED_TABLE_LABELS
                )
            ),
            "evidence": (
                f"tables="
                f"{len(NOTEBOOK_04_REQUIRED_TABLE_AUDIT)}"
            ),
        },
        {
            "gate": (
                "required_array_artifacts_verified"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    NOTEBOOK_04_REQUIRED_ARRAY_AUDIT
                )
                == len(
                    NOTEBOOK_04_REQUIRED_ARRAY_LABELS
                )
            ),
            "evidence": (
                f"arrays="
                f"{len(NOTEBOOK_04_REQUIRED_ARRAY_AUDIT)}"
            ),
        },
        {
            "gate": (
                "primary_event_conservation"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(PRIMARY_ESTIMATION_EVENTS)
                == EXPECTED_PRIMARY_EVENT_ROWS
            ),
            "evidence": (
                f"events="
                f"{len(PRIMARY_ESTIMATION_EVENTS)}"
            ),
        },
        {
            "gate": (
                "primary_batch_conservation"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(PRIMARY_SCORING_BATCHES)
                == EXPECTED_PRIMARY_BATCH_ROWS
            ),
            "evidence": (
                f"batches="
                f"{len(PRIMARY_SCORING_BATCHES)}"
            ),
        },
        {
            "gate": (
                "trade_print_conservation"
            ),
            "severity": "BLOCKING",
            "passed": (
                int(
                    primary_event_print_count.sum()
                )
                == EXPECTED_TRADE_MEMBERSHIP_ROWS
            ),
            "evidence": (
                f"trade_prints="
                f"{int(primary_event_print_count.sum())}"
            ),
        },
        {
            "gate": (
                "event_to_batch_membership_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                event_membership_ids
                == primary_event_ids
            ),
            "evidence": (
                f"membership_rows="
                f"{len(PRIMARY_EVENT_TO_BATCH_MEMBERSHIP)}"
            ),
        },
        {
            "gate": (
                "trade_to_event_membership_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(PRIMARY_TRADE_MEMBERSHIP)
                == EXPECTED_TRADE_MEMBERSHIP_ROWS
            ),
            "evidence": (
                f"membership_rows="
                f"{len(PRIMARY_TRADE_MEMBERSHIP)}"
            ),
        },
        {
            "gate": (
                "scoring_batch_identity_verified"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                "primary_scoring_batches equals the "
                "exact-time batch spine"
            ),
        },
        {
            "gate": (
                "strict_batch_history_semantics"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                "history strictly before batch time; "
                "zero-lag excitation forbidden"
            ),
        },
        {
            "gate": (
                "no_timestamp_jitter"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                "timestamp_jitter_allowed=False"
            ),
        },
        {
            "gate": (
                "no_event_removal"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                "event_removal_allowed=False"
            ),
        },
        {
            "gate": (
                "delayed_mark_no_backdating"
            ),
            "severity": "BLOCKING",
            "passed": (
                aggregate_mark_lag_ns.ge(0).all()
            ),
            "evidence": (
                f"delayed_events="
                f"{observed_delayed_aggregate_count}"
            ),
        },
        {
            "gate": (
                "simultaneous_batches_present"
            ),
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                f"count="
                f"{int(simultaneous_batch_flag.sum())}"
            ),
        },
        {
            "gate": (
                "mixed_side_batches_present"
            ),
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                f"count="
                f"{int(mixed_side_batch_flag.sum())}"
            ),
        },
        {
            "gate": (
                "delayed_aggregate_marks_present"
            ),
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                f"count="
                f"{observed_delayed_aggregate_count}"
            ),
        },
    ]
)

NOTEBOOK_04_AUTHORITY_GATES[
    "status"
] = np.select(
    [
        NOTEBOOK_04_AUTHORITY_GATES[
            "passed"
        ],
        NOTEBOOK_04_AUTHORITY_GATES[
            "severity"
        ].eq("BLOCKING"),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

notebook_04_blocking_failures = (
    NOTEBOOK_04_AUTHORITY_GATES.loc[
        NOTEBOOK_04_AUTHORITY_GATES[
            "severity"
        ].eq("BLOCKING")
        & ~NOTEBOOK_04_AUTHORITY_GATES[
            "passed"
        ]
    ]
)

require(
    notebook_04_blocking_failures.empty,
    (
        "Notebook 04 authority verification contains "
        "blocking failures."
    ),
)


# ------------------------------------------------------------
# Downstream frozen authority
# ------------------------------------------------------------

NOTEBOOK_04_AUTHORITY_VERIFIED: Final[
    bool
] = True

AUTHORITATIVE_PRIMARY_EVENT_COUNT: Final[
    int
] = int(
    len(PRIMARY_ESTIMATION_EVENTS)
)

AUTHORITATIVE_PRIMARY_BATCH_COUNT: Final[
    int
] = int(
    len(PRIMARY_SCORING_BATCHES)
)

AUTHORITATIVE_PRIMARY_TRADE_COUNT: Final[
    int
] = int(
    len(PRIMARY_TRADE_MEMBERSHIP)
)

AUTHORITATIVE_EVENT_PARTITION_COUNTS: Final[
    Mapping[str, int]
] = MappingProxyType(
    {
        partition: int(
            observed_primary_event_partition_counts[
                partition
            ]
        )
        for partition in PARTITION_ORDER
    }
)

AUTHORITATIVE_BATCH_PARTITION_COUNTS: Final[
    Mapping[str, int]
] = MappingProxyType(
    {
        partition: int(
            observed_primary_batch_partition_counts[
                partition
            ]
        )
        for partition in PARTITION_ORDER
    }
)

NOTEBOOK_04_EVENT_PARTITION_FIELD: Final[
    str
] = str(
    NOTEBOOK_04_TO_05_HANDOFF[
        "event_partition_field"
    ]
)

NOTEBOOK_04_MATCHED_BOOK_PARTITION_FIELD: Final[
    str
] = str(
    NOTEBOOK_04_TO_05_HANDOFF[
        "matched_book_partition_field"
    ]
)

NOTEBOOK_04_CROSS_PARTITION_HISTORY_FIELD: Final[
    str
] = str(
    NOTEBOOK_04_TO_05_HANDOFF[
        "cross_partition_history_field"
    ]
)


# ------------------------------------------------------------
# Compact displays
# ------------------------------------------------------------

display(
    NOTEBOOK_04_REQUIRED_TABLE_AUDIT[
        [
            "label",
            "row_count",
            "column_count",
            "table_payload_sha256",
            "resolved_path",
        ]
    ]
)

display(
    NOTEBOOK_04_REQUIRED_ARRAY_AUDIT[
        [
            "label",
            "array_count",
            "array_payload_sha256",
            "resolved_path",
        ]
    ]
)

display(
    pd.DataFrame(
        {
            "partition": PARTITION_ORDER,
            "primary_event_count": (
                observed_primary_event_partition_counts
                .values
            ),
            "primary_batch_count": (
                observed_primary_batch_partition_counts
                .values
            ),
            "contract_event_count": (
                contract_primary_event_partition_counts
                .values
            ),
            "contract_batch_count": (
                contract_primary_batch_partition_counts
                .values
            ),
        }
    )
)

display(
    NOTEBOOK_04_AUTHORITY_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "notebook_04_authority_verified": (
        NOTEBOOK_04_AUTHORITY_VERIFIED
    ),
    "terminal_status": (
        NOTEBOOK_04_FINAL_ACCEPTANCE_REPORT[
            "acceptance_status"
        ]
    ),
    "primary_event_representation": (
        NOTEBOOK_04_EXPECTED_EVENT_REPRESENTATION
    ),
    "timestamp_interface": (
        NOTEBOOK_04_EXPECTED_TIMESTAMP_INTERFACE
    ),
    "primary_event_rows": (
        AUTHORITATIVE_PRIMARY_EVENT_COUNT
    ),
    "primary_batch_rows": (
        AUTHORITATIVE_PRIMARY_BATCH_COUNT
    ),
    "trade_membership_rows": (
        AUTHORITATIVE_PRIMARY_TRADE_COUNT
    ),
    "simultaneous_batch_count": int(
        simultaneous_batch_flag.sum()
    ),
    "mixed_side_batch_count": int(
        mixed_side_batch_flag.sum()
    ),
    "delayed_aggregate_event_count": int(
        observed_delayed_aggregate_count
    ),
    "event_partition_counts": dict(
        AUTHORITATIVE_EVENT_PARTITION_COUNTS
    ),
    "batch_partition_counts": dict(
        AUTHORITATIVE_BATCH_PARTITION_COUNTS
    ),
    "event_partition_field": (
        NOTEBOOK_04_EVENT_PARTITION_FIELD
    ),
    "matched_book_partition_field": (
        NOTEBOOK_04_MATCHED_BOOK_PARTITION_FIELD
    ),
    "cross_partition_history_field": (
        NOTEBOOK_04_CROSS_PARTITION_HISTORY_FIELD
    ),
    "feature_construction_authorized": True,
    "hawkes_estimation_authorized": False,
    "market_making_authorized": False,
    "verified_at_utc": utc_now_iso(),
}

,label,row_count,column_count,table_payload_sha256,resolved_path
0,observation_window_contract,4,19,05b4c4649f39b4a830039d796b7274768ebe653265631f5d7edd9aeb39b0327c,D:\Clown Project\V0.1\config\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__observation_window_contract.parquet
1,primary_estimation_events,13887,88,ba5dd792854699e46f0ab73642cdce38c4b628c53b0b965cb740ab7a621acc55,D:\Clown Project\V0.1\data\processed\events\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__primary_estimation_events.parquet
2,primary_event_array_index,13887,18,00035dd27081c82e7be2438066fb07978d169ee94a868b60b61cb6ecc70124aa,D:\Clown Project\V0.1\data\processed\events\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__primary_event_array_index.parquet
3,primary_event_to_batch_membership,13887,10,70e5cadf74fa77b58647a8b894617b829f4dc413fe2689061d6fb42870a4d052,D:\Clown Project\V0.1\data\processed\events\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__primary_event_to_batch_membership.parquet
4,primary_exact_time_batches,13564,27,2051fc3f9a97476edcc230732c7bd1a1c11ff27c4ccf3d9eed71976d4fa54026,D:\Clown Project\V0.1\data\processed\events\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__primary_exact_time_batches.parquet
5,primary_scoring_batches,13564,25,4db21ef48848bb5cf5e79bf43dd18ea71fcc8d534b2e9666780cedf1b0d848d7,D:\Clown Project\V0.1\data\processed\events\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__primary_scoring_batches.parquet
6,primary_trade_membership,67683,11,bb69305556ea58a782a079da9a24645e01c6bd133f7d0d7016d7a56d37c2aef6,D:\Clown Project\V0.1\data\processed\events\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__primary_trade_membership.parquet

,label,array_count,array_payload_sha256,resolved_path
0,partition_batch_arrays,44,56da4e6d4a2bf4f0be8e20a372d935c15b6c9ae45c51e285b8bcab2024ab7844,D:\Clown Project\V0.1\data\processed\point_process\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__partition_batch_arrays.npz
1,partition_event_arrays,52,ee6049585ea1975c83aba3aa8c3bd1037fd3845c88486815dd0034ae2ca2469e,D:\Clown Project\V0.1\data\processed\point_process\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__partition_event_arrays.npz

             partition  primary_event_count  primary_batch_count  contract_event_count  contract_batch_count
0          DEVELOPMENT                 7004                 6859                  7004                  6859
1          CALIBRATION                 2493                 2400                  2493                  2400
2           VALIDATION                 2048                 1999                  2048                  1999
3  ENGINEERING_HOLDOUT                 2342                 2306                  2342                  2306

                                   gate  severity   status                                                           evidence
0      output_manifest_payload_verified  BLOCKING     PASS   c8454d2059f1b5e50675aa156e1eabd7762642cbf624065b496bea1edb56ff53
1              handoff_payload_verified  BLOCKING     PASS   f0544516d59fbabc24d1c8ff42063c96e7c6c4b72fcd5cedbd8ef0a2dfc38a28
2     final_acceptance_payload_verified  BLOCKING     PASS   d056dab3330dff3be55ccc4d5a7aa3acf6ba7569712bd3588f3b088d2a1ef8cd
3         persistence_contract_verified  BLOCKING     PASS   4c486bab5ea30cc9dbe94bc995033fd530dca8ef8f1880680f06db63e1b88230
4     required_table_artifacts_verified  BLOCKING     PASS                                                           tables=7
5     required_array_artifacts_verified  BLOCKING     PASS                                                           arrays=2
6            primary_event_conservation  BLOCKING     PASS                                                       events=13887
7            primary_batch_conservation  BLOCKING     PASS                                                      batches=13564
8              trade_print_conservation  BLOCKING     PASS                                                 trade_prints=67683
9   event_to_batch_membership_conserved  BLOCKING     PASS                                              membership_rows=13887
10  trade_to_event_membership_conserved  BLOCKING     PASS                                              membership_rows=67683
11      scoring_batch_identity_verified  BLOCKING     PASS          primary_scoring_batches equals the exact-time batch spine
12       strict_batch_history_semantics  BLOCKING     PASS  history strictly before batch time; zero-lag excitation forbidden
13                  no_timestamp_jitter  BLOCKING     PASS                                     timestamp_jitter_allowed=False
14                     no_event_removal  BLOCKING     PASS                                        event_removal_allowed=False
15           delayed_mark_no_backdating  BLOCKING     PASS                                                delayed_events=1575
16         simultaneous_batches_present   WARNING  WARNING                                                          count=249
17           mixed_side_batches_present   WARNING  WARNING                                                           count=41
18      delayed_aggregate_marks_present   WARNING  WARNING                                                         count=1575

{'status': 'PASS',
 'notebook_04_authority_verified': True,
 'terminal_status': 'PASS_WITH_EVENT_STREAM_WARNINGS',
 'primary_event_representation': 'SAME_MS_SAME_SIDE_BURSTS',
 'timestamp_interface': 'SIMULTANEOUS_EVENT_BATCH_REQUIRED',
 'primary_event_rows': 13887,
 'primary_batch_rows': 13564,
 'trade_membership_rows': 67683,
 'simultaneous_batch_count': 249,
 'mixed_side_batch_count': 41,
 'delayed_aggregate_event_count': 1575,
 'event_partition_counts': {'DEVELOPMENT': 7004,
  'CALIBRATION': 2493,
  'VALIDATION': 2048,
  'ENGINEERING_HOLDOUT': 2342},
 'batch_partition_counts': {'DEVELOPMENT': 6859,
  'CALIBRATION': 2400,
  'VALIDATION': 1999,
  'ENGINEERING_HOLDOUT': 2306},
 'event_partition_field': 'event_partition',
 'matched_book_partition_field': 'matched_book_partition',
 'cross_partition_history_field': 'cross_partition_history_flag',
 'feature_construction_authorized': True,
 'hawkes_estimation_authorized': False,
 'market_making_authorized': False,
 'verified_at_utc': '2026-07-19T09:33:58.333779+00:00'}

In [7]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 08 — Canonical scoring-batch spine, common pre-batch
#           visible-book selection, and event propagation audit
# ============================================================


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "NOTEBOOK_00_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 00 authority has not been verified.",
)

require(
    globals().get(
        "NOTEBOOK_02_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 02 authority has not been verified.",
)

require(
    globals().get(
        "NOTEBOOK_03_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 03 authority has not been verified.",
)

require(
    globals().get(
        "NOTEBOOK_04_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 04 authority has not been verified.",
)


# ------------------------------------------------------------
# Frozen Notebook 05 observational-unit contract
# ------------------------------------------------------------

CANONICAL_OBSERVATIONAL_UNIT: Final[str] = (
    "PRIMARY_SCORING_BATCH"
)

COMMON_PRE_BATCH_BOOK_SELECTION_RULE: Final[str] = (
    "LOCAL_STRICT_COMMON_BATCH_CUTOFF"
)

COMMON_PRE_BATCH_BOOK_TIME_RULE: Final[str] = (
    "book_local_receipt_time_ns <= event_time_ns"
)

COMMON_PRE_BATCH_BOOK_SEQUENCE_RULE: Final[str] = (
    "book_collector_sequence < "
    "batch_min_initiating_trade_collector_sequence"
)

COMMON_PRE_BATCH_BOOK_LATEST_RULE: Final[str] = (
    "latest book state satisfying both the local-time and "
    "collector-sequence constraints"
)

COMMON_PRE_BATCH_EQUAL_TIME_RULE: Final[str] = (
    "equal local receipt timestamps are eligible only when "
    "the book collector sequence precedes every initiating "
    "event sequence in the scoring batch"
)

COLLECTOR_SEQUENCE_TIE_INTERPRETATION: Final[str] = (
    "TRACE_ORDER_ONLY_NOT_PHYSICAL_ELAPSED_TIME"
)


# ------------------------------------------------------------
# Required authoritative schemas
# ------------------------------------------------------------

require_columns(
    PRIMARY_SCORING_BATCHES,
    (
        "primary_event_batch_id",
        "primary_event_batch_number",
        "partition_batch_index",
        "event_partition_order",
        "event_partition",
        "event_time_ns",
        "batch_event_count",
        "buy_event_count",
        "sell_event_count",
        "unique_side_count",
        "batch_print_count",
        "batch_quantity",
        "batch_notional",
        "mixed_side_batch_flag",
        "simultaneous_batch_required_flag",
        (
            "score_with_history_strictly_"
            "before_batch_time"
        ),
        (
            "zero_lag_within_batch_"
            "excitation_allowed"
        ),
        (
            "apply_batch_excitation_after_"
            "all_members_scored"
        ),
        (
            "collector_sequence_is_"
            "trace_order_only"
        ),
        "timestamp_jitter_allowed",
        "event_removal_allowed",
    ),
    "PRIMARY_SCORING_BATCHES",
)

require_columns(
    PRIMARY_ESTIMATION_EVENTS,
    (
        "primary_event_id",
        "primary_event_number",
        "primary_event_batch_id",
        "primary_event_batch_number",
        "partition_event_index",
        "event_partition_order",
        "event_partition",
        "event_time_ns",
        "event_side",
        "event_side_code",
        "initiation_trade_id",
        "initiation_trade_collector_sequence",
        "initiation_book_state_id",
        "initiation_book_collector_sequence",
        "initiation_book_local_receipt_time_ns",
        "matched_book_partition",
        "matched_book_partition_order",
        "aggregate_mark_available_time_ns",
    ),
    "PRIMARY_ESTIMATION_EVENTS",
)

require_columns(
    PRIMARY_EVENT_TO_BATCH_MEMBERSHIP,
    (
        "primary_event_id",
        "primary_event_number",
        "primary_event_batch_id",
        "primary_event_batch_number",
        "event_partition_order",
        "event_partition",
        "event_time_ns",
    ),
    "PRIMARY_EVENT_TO_BATCH_MEMBERSHIP",
)

require_columns(
    RECONSTRUCTED_BOOK_STATES,
    (
        "book_state_id",
        "collector_sequence",
        "local_receipt_time_ns",
        "partition",
        "best_bid",
        "best_ask",
        "best_bid_quantity",
        "best_ask_quantity",
        "spread",
        "spread_ticks",
        "midpoint",
        "microprice",
        "microprice_minus_midpoint",
        "top_level_imbalance",
        "multi_level_imbalance",
        "visible_bid_depth_top_10",
        "visible_ask_depth_top_10",
        "visible_total_depth_top_10",
        "state_accepted",
        "locked_state",
        "crossed_state",
        "incomplete_state",
    ),
    "RECONSTRUCTED_BOOK_STATES",
)


# ------------------------------------------------------------
# Prepare the canonical scoring-batch spine
# ------------------------------------------------------------

CANONICAL_BATCH_SPINE = (
    PRIMARY_SCORING_BATCHES.copy()
    .sort_values(
        [
            "event_partition_order",
            "partition_batch_index",
            "primary_event_batch_number",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

require_unique_columns(
    CANONICAL_BATCH_SPINE,
    "CANONICAL_BATCH_SPINE",
)

require(
    len(CANONICAL_BATCH_SPINE)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Canonical batch-spine row count mismatch:\n"
        f"expected={EXPECTED_PRIMARY_BATCH_ROWS:,}\n"
        f"observed={len(CANONICAL_BATCH_SPINE):,}"
    ),
)

require(
    CANONICAL_BATCH_SPINE[
        "primary_event_batch_id"
    ].is_unique,
    "Canonical batch IDs are not unique.",
)

require(
    CANONICAL_BATCH_SPINE[
        "primary_event_batch_number"
    ].is_unique,
    "Canonical batch numbers are not unique.",
)

CANONICAL_BATCH_SPINE[
    "primary_event_batch_number"
] = parse_required_int64(
    CANONICAL_BATCH_SPINE[
        "primary_event_batch_number"
    ],
    (
        "CANONICAL_BATCH_SPINE."
        "primary_event_batch_number"
    ),
)

CANONICAL_BATCH_SPINE[
    "event_partition_order"
] = parse_required_int64(
    CANONICAL_BATCH_SPINE[
        "event_partition_order"
    ],
    (
        "CANONICAL_BATCH_SPINE."
        "event_partition_order"
    ),
)

CANONICAL_BATCH_SPINE[
    "event_time_ns"
] = parse_required_int64(
    CANONICAL_BATCH_SPINE[
        "event_time_ns"
    ],
    "CANONICAL_BATCH_SPINE.event_time_ns",
)

CANONICAL_BATCH_SPINE[
    "batch_event_count"
] = parse_required_int64(
    CANONICAL_BATCH_SPINE[
        "batch_event_count"
    ],
    "CANONICAL_BATCH_SPINE.batch_event_count",
)

CANONICAL_BATCH_SPINE[
    "event_partition"
] = (
    CANONICAL_BATCH_SPINE[
        "event_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

require(
    tuple(
        CANONICAL_BATCH_SPINE.sort_values(
            "primary_event_batch_number",
            kind="stable",
        )[
            "primary_event_batch_number"
        ].tolist()
    )
    == tuple(
        range(
            1,
            EXPECTED_PRIMARY_BATCH_ROWS + 1,
        )
    ),
    "Canonical batch numbers are not consecutive.",
)

require(
    set(
        CANONICAL_BATCH_SPINE[
            "event_partition"
        ].dropna().unique()
    )
    == set(PARTITION_ORDER),
    "Canonical batch spine does not cover all partitions.",
)


# ------------------------------------------------------------
# Preserve Notebook 04 batch-scoring semantics
# ------------------------------------------------------------

require(
    strict_boolean_series(
        CANONICAL_BATCH_SPINE[
            (
                "score_with_history_strictly_"
                "before_batch_time"
            )
        ],
        field_name=(
            "CANONICAL_BATCH_SPINE."
            "score_with_history_strictly_before_batch_time"
        ),
    ).all(),
    (
        "A canonical batch does not require strictly prior "
        "event history."
    ),
)

require(
    not strict_boolean_series(
        CANONICAL_BATCH_SPINE[
            (
                "zero_lag_within_batch_"
                "excitation_allowed"
            )
        ],
        field_name=(
            "CANONICAL_BATCH_SPINE."
            "zero_lag_within_batch_excitation_allowed"
        ),
    ).any(),
    (
        "A canonical batch permits zero-lag within-batch "
        "excitation."
    ),
)

require(
    strict_boolean_series(
        CANONICAL_BATCH_SPINE[
            (
                "apply_batch_excitation_after_"
                "all_members_scored"
            )
        ],
        field_name=(
            "CANONICAL_BATCH_SPINE."
            "apply_batch_excitation_after_all_members_scored"
        ),
    ).all(),
    (
        "A canonical batch does not defer excitation until "
        "all batch members have been scored."
    ),
)

require(
    strict_boolean_series(
        CANONICAL_BATCH_SPINE[
            (
                "collector_sequence_is_"
                "trace_order_only"
            )
        ],
        field_name=(
            "CANONICAL_BATCH_SPINE."
            "collector_sequence_is_trace_order_only"
        ),
    ).all(),
    (
        "A canonical batch does not preserve collector "
        "sequence as trace order only."
    ),
)

require(
    not strict_boolean_series(
        CANONICAL_BATCH_SPINE[
            "timestamp_jitter_allowed"
        ],
        field_name=(
            "CANONICAL_BATCH_SPINE."
            "timestamp_jitter_allowed"
        ),
    ).any(),
    "A canonical batch permits timestamp jitter.",
)

require(
    not strict_boolean_series(
        CANONICAL_BATCH_SPINE[
            "event_removal_allowed"
        ],
        field_name=(
            "CANONICAL_BATCH_SPINE."
            "event_removal_allowed"
        ),
    ).any(),
    "A canonical batch permits event removal.",
)


# ------------------------------------------------------------
# Derive one common information cutoff per scoring batch
#
# The minimum initiating trade sequence is required because
# every event in the same exact-time batch must receive the
# same pre-batch visible-book state.
# ------------------------------------------------------------

event_cutoff_source = (
    PRIMARY_ESTIMATION_EVENTS[
        [
            "primary_event_id",
            "primary_event_number",
            "primary_event_batch_id",
            "primary_event_batch_number",
            "event_partition_order",
            "event_partition",
            "event_time_ns",
            "initiation_trade_id",
            "initiation_trade_collector_sequence",
            "initiation_book_state_id",
            "initiation_book_collector_sequence",
            "initiation_book_local_receipt_time_ns",
            "matched_book_partition",
            "matched_book_partition_order",
        ]
    ]
    .copy()
    .sort_values(
        [
            "primary_event_batch_number",
            "initiation_trade_collector_sequence",
            "primary_event_number",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

event_cutoff_source[
    "primary_event_number"
] = parse_required_int64(
    event_cutoff_source[
        "primary_event_number"
    ],
    "event_cutoff_source.primary_event_number",
)

event_cutoff_source[
    "primary_event_batch_number"
] = parse_required_int64(
    event_cutoff_source[
        "primary_event_batch_number"
    ],
    (
        "event_cutoff_source."
        "primary_event_batch_number"
    ),
)

event_cutoff_source[
    "event_partition_order"
] = parse_required_int64(
    event_cutoff_source[
        "event_partition_order"
    ],
    "event_cutoff_source.event_partition_order",
)

event_cutoff_source[
    "event_time_ns"
] = parse_required_int64(
    event_cutoff_source[
        "event_time_ns"
    ],
    "event_cutoff_source.event_time_ns",
)

event_cutoff_source[
    "initiation_trade_collector_sequence"
] = parse_required_int64(
    event_cutoff_source[
        "initiation_trade_collector_sequence"
    ],
    (
        "event_cutoff_source."
        "initiation_trade_collector_sequence"
    ),
)

event_cutoff_source[
    "initiation_book_state_id"
] = parse_required_int64(
    event_cutoff_source[
        "initiation_book_state_id"
    ],
    "event_cutoff_source.initiation_book_state_id",
)

event_cutoff_source[
    "initiation_book_collector_sequence"
] = parse_required_int64(
    event_cutoff_source[
        "initiation_book_collector_sequence"
    ],
    (
        "event_cutoff_source."
        "initiation_book_collector_sequence"
    ),
)

event_cutoff_source[
    "initiation_book_local_receipt_time_ns"
] = parse_required_int64(
    event_cutoff_source[
        "initiation_book_local_receipt_time_ns"
    ],
    (
        "event_cutoff_source."
        "initiation_book_local_receipt_time_ns"
    ),
)

event_cutoff_source[
    "matched_book_partition_order"
] = parse_required_int64(
    event_cutoff_source[
        "matched_book_partition_order"
    ],
    (
        "event_cutoff_source."
        "matched_book_partition_order"
    ),
)

event_cutoff_source[
    "event_partition"
] = (
    event_cutoff_source[
        "event_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

event_cutoff_source[
    "matched_book_partition"
] = (
    event_cutoff_source[
        "matched_book_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

BATCH_INFORMATION_CUTOFFS = (
    event_cutoff_source.groupby(
        [
            "primary_event_batch_id",
            "primary_event_batch_number",
            "event_partition_order",
            "event_partition",
            "event_time_ns",
        ],
        observed=True,
        sort=False,
        dropna=False,
    )
    .agg(
        recomputed_batch_event_count=(
            "primary_event_id",
            "size",
        ),
        first_primary_event_id=(
            "primary_event_id",
            "first",
        ),
        last_primary_event_id=(
            "primary_event_id",
            "last",
        ),
        batch_min_initiating_trade_collector_sequence=(
            "initiation_trade_collector_sequence",
            "min",
        ),
        batch_max_initiating_trade_collector_sequence=(
            "initiation_trade_collector_sequence",
            "max",
        ),
        batch_min_initiation_book_state_id=(
            "initiation_book_state_id",
            "min",
        ),
        batch_max_initiation_book_state_id=(
            "initiation_book_state_id",
            "max",
        ),
        batch_inherited_initiation_book_state_count=(
            "initiation_book_state_id",
            "nunique",
        ),
        batch_min_inherited_book_collector_sequence=(
            "initiation_book_collector_sequence",
            "min",
        ),
        batch_max_inherited_book_collector_sequence=(
            "initiation_book_collector_sequence",
            "max",
        ),
        batch_min_inherited_book_local_receipt_time_ns=(
            "initiation_book_local_receipt_time_ns",
            "min",
        ),
        batch_max_inherited_book_local_receipt_time_ns=(
            "initiation_book_local_receipt_time_ns",
            "max",
        ),
        batch_min_matched_book_partition_order=(
            "matched_book_partition_order",
            "min",
        ),
        batch_max_matched_book_partition_order=(
            "matched_book_partition_order",
            "max",
        ),
    )
    .reset_index()
)

require(
    len(BATCH_INFORMATION_CUTOFFS)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Batch-information cutoff count mismatch:\n"
        f"expected={EXPECTED_PRIMARY_BATCH_ROWS:,}\n"
        f"observed={len(BATCH_INFORMATION_CUTOFFS):,}"
    ),
)

require(
    BATCH_INFORMATION_CUTOFFS[
        "primary_event_batch_id"
    ].is_unique,
    "Batch-information cutoffs contain duplicate batch IDs.",
)

CANONICAL_BATCH_SPINE = (
    CANONICAL_BATCH_SPINE.merge(
        BATCH_INFORMATION_CUTOFFS,
        how="left",
        on=[
            "primary_event_batch_id",
            "primary_event_batch_number",
            "event_partition_order",
            "event_partition",
            "event_time_ns",
        ],
        validate="one_to_one",
    )
)

require(
    CANONICAL_BATCH_SPINE[
        "recomputed_batch_event_count"
    ].notna().all(),
    (
        "At least one canonical batch lacks a reconstructed "
        "event cutoff."
    ),
)

require(
    CANONICAL_BATCH_SPINE[
        "batch_event_count"
    ].astype("int64").equals(
        CANONICAL_BATCH_SPINE[
            "recomputed_batch_event_count"
        ].astype("int64")
    ),
    (
        "Recomputed event counts differ from Notebook 04 "
        "batch_event_count."
    ),
)

require(
    CANONICAL_BATCH_SPINE[
        (
            "batch_min_initiating_"
            "trade_collector_sequence"
        )
    ].le(
        CANONICAL_BATCH_SPINE[
            (
                "batch_max_initiating_"
                "trade_collector_sequence"
            )
        ]
    ).all(),
    "A batch has reversed initiating-sequence bounds.",
)

require(
    CANONICAL_BATCH_SPINE[
        (
            "batch_inherited_initiation_"
            "book_state_count"
        )
    ].ge(1).all(),
    (
        "At least one batch contains no inherited initiation "
        "book state."
    ),
)


# ------------------------------------------------------------
# Prepare Notebook 02 book states exactly as required by the
# Notebook 03 LOCAL_STRICT matching rule
# ------------------------------------------------------------

BOOK_SELECTION_AUTHORITY = (
    RECONSTRUCTED_BOOK_STATES.copy()
    .sort_values(
        [
            "collector_sequence",
            "book_state_id",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

BOOK_SELECTION_AUTHORITY[
    "book_state_id"
] = parse_required_int64(
    BOOK_SELECTION_AUTHORITY[
        "book_state_id"
    ],
    "BOOK_SELECTION_AUTHORITY.book_state_id",
)

BOOK_SELECTION_AUTHORITY[
    "collector_sequence"
] = parse_required_int64(
    BOOK_SELECTION_AUTHORITY[
        "collector_sequence"
    ],
    (
        "BOOK_SELECTION_AUTHORITY."
        "collector_sequence"
    ),
)

BOOK_SELECTION_AUTHORITY[
    "local_receipt_time_ns"
] = parse_required_int64(
    BOOK_SELECTION_AUTHORITY[
        "local_receipt_time_ns"
    ],
    (
        "BOOK_SELECTION_AUTHORITY."
        "local_receipt_time_ns"
    ),
)

BOOK_SELECTION_AUTHORITY[
    "partition"
] = (
    BOOK_SELECTION_AUTHORITY[
        "partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

require(
    len(BOOK_SELECTION_AUTHORITY)
    == EXPECTED_RECONSTRUCTED_BOOK_STATES,
    "Book-selection authority row count changed.",
)

require(
    BOOK_SELECTION_AUTHORITY[
        "book_state_id"
    ].is_unique,
    "Book-selection authority has duplicate book-state IDs.",
)

require(
    BOOK_SELECTION_AUTHORITY[
        "collector_sequence"
    ].is_unique,
    (
        "Book-selection authority has duplicate collector "
        "sequences."
    ),
)

require(
    BOOK_SELECTION_AUTHORITY[
        "collector_sequence"
    ].is_monotonic_increasing,
    (
        "Book-selection authority collector sequence is not "
        "strictly increasing."
    ),
)

require(
    BOOK_SELECTION_AUTHORITY[
        "local_receipt_time_ns"
    ].is_monotonic_increasing,
    (
        "Book-selection authority local receipt time is not "
        "non-decreasing."
    ),
)

require(
    set(
        BOOK_SELECTION_AUTHORITY[
            "partition"
        ].dropna().unique()
    )
    == set(PARTITION_ORDER),
    (
        "Book-selection authority partition domain differs "
        "from Notebook 00."
    ),
)


# ------------------------------------------------------------
# LOCAL_STRICT common pre-batch visible-book selection
#
# This reproduces Notebook 03's actual two-bound method:
#
# sequence upper bound:
#   first book sequence >= minimum initiating sequence
#
# local-time upper bound:
#   first book local time > shared batch time
#
# latest common eligible state:
#   min(sequence upper, time upper) - 1
# ------------------------------------------------------------

book_sequence_array = (
    BOOK_SELECTION_AUTHORITY[
        "collector_sequence"
    ]
    .astype("int64")
    .to_numpy()
)

book_local_time_array = (
    BOOK_SELECTION_AUTHORITY[
        "local_receipt_time_ns"
    ]
    .astype("int64")
    .to_numpy()
)

batch_min_initiating_sequence_array = (
    CANONICAL_BATCH_SPINE[
        (
            "batch_min_initiating_"
            "trade_collector_sequence"
        )
    ]
    .astype("int64")
    .to_numpy()
)

batch_time_array = (
    CANONICAL_BATCH_SPINE[
        "event_time_ns"
    ]
    .astype("int64")
    .to_numpy()
)

batch_sequence_upper_positions = np.searchsorted(
    book_sequence_array,
    batch_min_initiating_sequence_array,
    side="left",
)

batch_time_upper_positions = np.searchsorted(
    book_local_time_array,
    batch_time_array,
    side="right",
)

common_book_candidate_positions = (
    np.minimum(
        batch_sequence_upper_positions,
        batch_time_upper_positions,
    )
    - 1
)

common_book_candidate_exists = (
    common_book_candidate_positions >= 0
)

require(
    common_book_candidate_exists.all(),
    (
        "At least one scoring batch has no causally eligible "
        "common pre-batch book state."
    ),
)

selected_common_book_rows = (
    BOOK_SELECTION_AUTHORITY.iloc[
        common_book_candidate_positions
    ]
    .reset_index(drop=True)
    .copy()
)

selected_common_book_rows.insert(
    0,
    "book_authority_row_position",
    common_book_candidate_positions.astype(
        "int64"
    ),
)

selected_common_book_rows = (
    selected_common_book_rows.add_prefix(
        "common_book_"
    )
)

require(
    len(selected_common_book_rows)
    == len(CANONICAL_BATCH_SPINE),
    (
        "Selected common-book row count differs from the "
        "canonical batch count."
    ),
)

CANONICAL_BATCH_SPINE = pd.concat(
    [
        CANONICAL_BATCH_SPINE.reset_index(
            drop=True
        ),
        selected_common_book_rows.reset_index(
            drop=True
        ),
    ],
    axis=1,
)

require_unique_columns(
    CANONICAL_BATCH_SPINE,
    "CANONICAL_BATCH_SPINE",
)


# ------------------------------------------------------------
# Attach selection bounds and causal diagnostics
# ------------------------------------------------------------

CANONICAL_BATCH_SPINE[
    "common_book_sequence_upper_position"
] = batch_sequence_upper_positions.astype(
    "int64"
)

CANONICAL_BATCH_SPINE[
    "common_book_time_upper_position"
] = batch_time_upper_positions.astype(
    "int64"
)

CANONICAL_BATCH_SPINE[
    "common_book_candidate_position"
] = common_book_candidate_positions.astype(
    "int64"
)

CANONICAL_BATCH_SPINE[
    "common_book_candidate_exists_flag"
] = common_book_candidate_exists.astype(
    bool
)

CANONICAL_BATCH_SPINE[
    "common_book_selection_rule"
] = COMMON_PRE_BATCH_BOOK_SELECTION_RULE

CANONICAL_BATCH_SPINE[
    "common_book_time_rule"
] = COMMON_PRE_BATCH_BOOK_TIME_RULE

CANONICAL_BATCH_SPINE[
    "common_book_sequence_rule"
] = COMMON_PRE_BATCH_BOOK_SEQUENCE_RULE

CANONICAL_BATCH_SPINE[
    "common_book_latest_rule"
] = COMMON_PRE_BATCH_BOOK_LATEST_RULE

CANONICAL_BATCH_SPINE[
    "common_book_equal_time_rule"
] = COMMON_PRE_BATCH_EQUAL_TIME_RULE

CANONICAL_BATCH_SPINE[
    "collector_sequence_tie_interpretation"
] = COLLECTOR_SEQUENCE_TIE_INTERPRETATION

CANONICAL_BATCH_SPINE[
    "common_book_age_ns"
] = (
    CANONICAL_BATCH_SPINE[
        "event_time_ns"
    ].astype("int64")
    - CANONICAL_BATCH_SPINE[
        "common_book_local_receipt_time_ns"
    ].astype("int64")
)

CANONICAL_BATCH_SPINE[
    "common_book_age_ms"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_age_ns"
    ].astype("float64")
    / 1_000_000.0
)

CANONICAL_BATCH_SPINE[
    (
        "common_book_sequence_distance_to_"
        "batch_min_initiation"
    )
] = (
    CANONICAL_BATCH_SPINE[
        (
            "batch_min_initiating_"
            "trade_collector_sequence"
        )
    ].astype("int64")
    - CANONICAL_BATCH_SPINE[
        "common_book_collector_sequence"
    ].astype("int64")
)

CANONICAL_BATCH_SPINE[
    "common_book_same_local_timestamp_flag"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_age_ns"
    ].eq(0)
)

CANONICAL_BATCH_SPINE[
    "common_book_strictly_earlier_local_time_flag"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_age_ns"
    ].gt(0)
)

CANONICAL_BATCH_SPINE[
    "common_book_sequence_condition_flag"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_collector_sequence"
    ].astype("int64")
    < CANONICAL_BATCH_SPINE[
        (
            "batch_min_initiating_"
            "trade_collector_sequence"
        )
    ].astype("int64")
)

CANONICAL_BATCH_SPINE[
    "common_book_local_time_condition_flag"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_local_receipt_time_ns"
    ].astype("int64")
    <= CANONICAL_BATCH_SPINE[
        "event_time_ns"
    ].astype("int64")
)

CANONICAL_BATCH_SPINE[
    "common_book_selection_basis"
] = np.where(
    CANONICAL_BATCH_SPINE[
        "common_book_same_local_timestamp_flag"
    ],
    "EQUAL_LOCAL_TIME_PRIOR_COLLECTOR_SEQUENCE",
    "STRICTLY_EARLIER_LOCAL_RECEIPT_TIME",
)


# ------------------------------------------------------------
# Latest-eligible-state audit
# ------------------------------------------------------------

common_book_next_positions = (
    common_book_candidate_positions + 1
)

common_book_has_next_state = (
    (common_book_next_positions >= 0)
    & (
        common_book_next_positions
        < len(book_sequence_array)
    )
)

next_book_sequence_array = np.full(
    len(CANONICAL_BATCH_SPINE),
    np.iinfo(np.int64).max,
    dtype=np.int64,
)

next_book_local_time_array = np.full(
    len(CANONICAL_BATCH_SPINE),
    np.iinfo(np.int64).max,
    dtype=np.int64,
)

next_book_state_id_array = np.full(
    len(CANONICAL_BATCH_SPINE),
    -1,
    dtype=np.int64,
)

next_book_sequence_array[
    common_book_has_next_state
] = book_sequence_array[
    common_book_next_positions[
        common_book_has_next_state
    ]
]

next_book_local_time_array[
    common_book_has_next_state
] = book_local_time_array[
    common_book_next_positions[
        common_book_has_next_state
    ]
]

book_state_id_array = (
    BOOK_SELECTION_AUTHORITY[
        "book_state_id"
    ]
    .astype("int64")
    .to_numpy()
)

next_book_state_id_array[
    common_book_has_next_state
] = book_state_id_array[
    common_book_next_positions[
        common_book_has_next_state
    ]
]

common_book_next_would_be_eligible = (
    common_book_has_next_state
    & (
        next_book_sequence_array
        < batch_min_initiating_sequence_array
    )
    & (
        next_book_local_time_array
        <= batch_time_array
    )
)

CANONICAL_BATCH_SPINE[
    "common_book_next_position"
] = common_book_next_positions.astype(
    "int64"
)

CANONICAL_BATCH_SPINE[
    "common_book_has_next_state_flag"
] = common_book_has_next_state.astype(
    bool
)

CANONICAL_BATCH_SPINE[
    "common_book_next_state_id"
] = next_book_state_id_array

CANONICAL_BATCH_SPINE[
    "common_book_next_sequence"
] = next_book_sequence_array

CANONICAL_BATCH_SPINE[
    "common_book_next_local_receipt_time_ns"
] = next_book_local_time_array

CANONICAL_BATCH_SPINE[
    "common_book_next_would_be_eligible_flag"
] = common_book_next_would_be_eligible.astype(
    bool
)

require(
    CANONICAL_BATCH_SPINE[
        "common_book_candidate_exists_flag"
    ].all(),
    "A canonical batch lacks a common pre-batch book state.",
)

require(
    CANONICAL_BATCH_SPINE[
        "common_book_sequence_condition_flag"
    ].all(),
    (
        "At least one common book state does not precede the "
        "minimum initiating collector sequence."
    ),
)

require(
    CANONICAL_BATCH_SPINE[
        "common_book_local_time_condition_flag"
    ].all(),
    (
        "At least one common book state was observed after "
        "the shared batch time."
    ),
)

require(
    CANONICAL_BATCH_SPINE[
        "common_book_age_ns"
    ].ge(0).all(),
    "At least one common book state has negative age.",
)

require(
    CANONICAL_BATCH_SPINE[
        (
            "common_book_sequence_distance_to_"
            "batch_min_initiation"
        )
    ].gt(0).all(),
    (
        "At least one common book state has a non-positive "
        "sequence distance from the batch cutoff."
    ),
)

require(
    not CANONICAL_BATCH_SPINE[
        "common_book_next_would_be_eligible_flag"
    ].any(),
    (
        "At least one selected common book state is not the "
        "latest causally eligible state."
    ),
)


# ------------------------------------------------------------
# Partition identity and causal history carry
# ------------------------------------------------------------

CANONICAL_BATCH_SPINE[
    "common_book_partition"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

CANONICAL_BATCH_SPINE[
    "common_book_partition_order"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_partition"
    ]
    .map(PARTITION_ORDER_MAP)
)

require(
    CANONICAL_BATCH_SPINE[
        "common_book_partition_order"
    ].notna().all(),
    (
        "At least one selected common book state has an "
        "unknown partition."
    ),
)

CANONICAL_BATCH_SPINE[
    "common_book_partition_order"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_partition_order"
    ].astype("int64")
)

CANONICAL_BATCH_SPINE[
    "common_book_same_partition_flag"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_partition_order"
    ].eq(
        CANONICAL_BATCH_SPINE[
            "event_partition_order"
        ].astype("int64")
    )
)

CANONICAL_BATCH_SPINE[
    "cross_partition_history_flag"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_partition_order"
    ].lt(
        CANONICAL_BATCH_SPINE[
            "event_partition_order"
        ].astype("int64")
    )
)

CANONICAL_BATCH_SPINE[
    "future_partition_book_flag"
] = (
    CANONICAL_BATCH_SPINE[
        "common_book_partition_order"
    ].gt(
        CANONICAL_BATCH_SPINE[
            "event_partition_order"
        ].astype("int64")
    )
)

require(
    not CANONICAL_BATCH_SPINE[
        "future_partition_book_flag"
    ].any(),
    (
        "At least one scoring batch uses a visible-book state "
        "from a later partition."
    ),
)


# ------------------------------------------------------------
# Reconcile the common book against the earliest initiating
# event in each batch
#
# This must match because the common cutoff uses the minimum
# initiating trade sequence and the same LOCAL_STRICT rule as
# Notebook 03.
# ------------------------------------------------------------

EARLIEST_INITIATING_EVENT_PER_BATCH = (
    event_cutoff_source.sort_values(
        [
            "primary_event_batch_number",
            "initiation_trade_collector_sequence",
            "primary_event_number",
        ],
        kind="stable",
    )
    .drop_duplicates(
        subset=[
            "primary_event_batch_id"
        ],
        keep="first",
    )
    [
        [
            "primary_event_batch_id",
            "primary_event_id",
            "primary_event_number",
            "initiation_trade_id",
            "initiation_trade_collector_sequence",
            "initiation_book_state_id",
            "initiation_book_collector_sequence",
            "initiation_book_local_receipt_time_ns",
        ]
    ]
    .rename(
        columns={
            "primary_event_id": (
                "earliest_initiating_primary_event_id"
            ),
            "primary_event_number": (
                "earliest_initiating_primary_event_number"
            ),
            "initiation_trade_id": (
                "earliest_initiating_trade_id"
            ),
            (
                "initiation_trade_"
                "collector_sequence"
            ): (
                "earliest_initiating_trade_"
                "collector_sequence"
            ),
            "initiation_book_state_id": (
                "earliest_initiation_book_state_id"
            ),
            (
                "initiation_book_"
                "collector_sequence"
            ): (
                "earliest_initiation_book_"
                "collector_sequence"
            ),
            (
                "initiation_book_"
                "local_receipt_time_ns"
            ): (
                "earliest_initiation_book_"
                "local_receipt_time_ns"
            ),
        }
    )
    .reset_index(drop=True)
)

COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION = (
    CANONICAL_BATCH_SPINE[
        [
            "primary_event_batch_id",
            "common_book_book_state_id",
            "common_book_collector_sequence",
            "common_book_local_receipt_time_ns",
        ]
    ]
    .merge(
        EARLIEST_INITIATING_EVENT_PER_BATCH,
        how="left",
        on="primary_event_batch_id",
        validate="one_to_one",
    )
)

require(
    COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
        "earliest_initiating_primary_event_id"
    ].notna().all(),
    (
        "At least one batch lacks its earliest initiating "
        "event reconciliation row."
    ),
)

COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
    "common_book_matches_earliest_initiation_state_flag"
] = (
    COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
        "common_book_book_state_id"
    ].astype("int64")
    .eq(
        COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
            "earliest_initiation_book_state_id"
        ].astype("int64")
    )
)

COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
    "common_book_matches_earliest_initiation_sequence_flag"
] = (
    COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
        "common_book_collector_sequence"
    ].astype("int64")
    .eq(
        COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
            (
                "earliest_initiation_book_"
                "collector_sequence"
            )
        ].astype("int64")
    )
)

COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
    "common_book_matches_earliest_initiation_time_flag"
] = (
    COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
        "common_book_local_receipt_time_ns"
    ].astype("int64")
    .eq(
        COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
            (
                "earliest_initiation_book_"
                "local_receipt_time_ns"
            )
        ].astype("int64")
    )
)

require(
    COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
        (
            "common_book_matches_earliest_"
            "initiation_state_flag"
        )
    ].all(),
    (
        "Common pre-batch book selection differs from the "
        "earliest event's inherited initiation book state."
    ),
)

require(
    COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
        (
            "common_book_matches_earliest_"
            "initiation_sequence_flag"
        )
    ].all(),
    (
        "Common pre-batch book sequence differs from the "
        "earliest event's inherited initiation book sequence."
    ),
)

require(
    COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
        (
            "common_book_matches_earliest_"
            "initiation_time_flag"
        )
    ].all(),
    (
        "Common pre-batch book time differs from the earliest "
        "event's inherited initiation book time."
    ),
)


# ------------------------------------------------------------
# Canonical batch-level common visible-book table
# ------------------------------------------------------------

COMMON_PRE_BATCH_BOOK_STATES = (
    CANONICAL_BATCH_SPINE.copy()
)

require(
    len(COMMON_PRE_BATCH_BOOK_STATES)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Common pre-batch book-state table does not contain "
        "one row per scoring batch."
    ),
)

require(
    COMMON_PRE_BATCH_BOOK_STATES[
        "primary_event_batch_id"
    ].is_unique,
    (
        "Common pre-batch book-state table contains duplicate "
        "batch IDs."
    ),
)

require(
    COMMON_PRE_BATCH_BOOK_STATES[
        "common_book_book_state_id"
    ].notna().all(),
    (
        "At least one common pre-batch row lacks a book-state "
        "identity."
    ),
)


# ------------------------------------------------------------
# Propagate the common batch state to every primary event
# ------------------------------------------------------------

common_book_event_propagation_columns = [
    "primary_event_batch_id",
    "primary_event_batch_number",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
    "batch_event_count",
    (
        "batch_min_initiating_"
        "trade_collector_sequence"
    ),
    (
        "batch_max_initiating_"
        "trade_collector_sequence"
    ),
    (
        "batch_inherited_initiation_"
        "book_state_count"
    ),
    "common_book_book_state_id",
    "common_book_collector_sequence",
    "common_book_local_receipt_time_ns",
    "common_book_partition",
    "common_book_partition_order",
    "common_book_age_ns",
    "common_book_age_ms",
    (
        "common_book_sequence_distance_to_"
        "batch_min_initiation"
    ),
    "common_book_same_local_timestamp_flag",
    "common_book_strictly_earlier_local_time_flag",
    "common_book_same_partition_flag",
    "cross_partition_history_flag",
    "common_book_selection_basis",
    "common_book_best_bid",
    "common_book_best_ask",
    "common_book_best_bid_quantity",
    "common_book_best_ask_quantity",
    "common_book_spread",
    "common_book_spread_ticks",
    "common_book_midpoint",
    "common_book_microprice",
    "common_book_microprice_minus_midpoint",
    "common_book_top_level_imbalance",
    "common_book_multi_level_imbalance",
    "common_book_visible_bid_depth_top_10",
    "common_book_visible_ask_depth_top_10",
    "common_book_visible_total_depth_top_10",
]

require_columns(
    COMMON_PRE_BATCH_BOOK_STATES,
    common_book_event_propagation_columns,
    "COMMON_PRE_BATCH_BOOK_STATES",
)

PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP = (
    event_cutoff_source.merge(
        COMMON_PRE_BATCH_BOOK_STATES[
            common_book_event_propagation_columns
        ],
        how="left",
        on=[
            "primary_event_batch_id",
            "primary_event_batch_number",
            "event_partition_order",
            "event_partition",
            "event_time_ns",
        ],
        validate="many_to_one",
    )
)

require(
    len(
        PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP
    )
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Event common-book membership row count mismatch:\n"
        f"expected={EXPECTED_PRIMARY_EVENT_ROWS:,}\n"
        f"observed="
        f"{len(PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP):,}"
    ),
)

require(
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "primary_event_id"
    ].is_unique,
    (
        "Event common-book membership contains duplicate "
        "primary-event IDs."
    ),
)

require(
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "common_book_book_state_id"
    ].notna().all(),
    (
        "At least one primary event lacks a propagated common "
        "pre-batch book state."
    ),
)

require(
    set(
        PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
            "primary_event_id"
        ].astype(str)
    )
    == set(
        PRIMARY_ESTIMATION_EVENTS[
            "primary_event_id"
        ].astype(str)
    ),
    (
        "Event common-book membership changed the primary "
        "event identity set."
    ),
)


# ------------------------------------------------------------
# Compare the common batch state with each event's inherited
# initiation book
#
# Later members of an exact-time batch may inherit a later book
# state from Notebook 03. That later state is not allowed to
# change another member's t-minus features.
# ------------------------------------------------------------

PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
    "common_book_matches_event_initiation_state_flag"
] = (
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "common_book_book_state_id"
    ].astype("int64")
    .eq(
        PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
            "initiation_book_state_id"
        ].astype("int64")
    )
)

PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
    "event_inherited_initiation_book_is_later_flag"
] = (
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "initiation_book_collector_sequence"
    ].astype("int64")
    .gt(
        PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
            "common_book_collector_sequence"
        ].astype("int64")
    )
)

PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
    "event_inherited_initiation_book_is_earlier_flag"
] = (
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "initiation_book_collector_sequence"
    ].astype("int64")
    .lt(
        PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
            "common_book_collector_sequence"
        ].astype("int64")
    )
)

PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
    (
        "event_inherited_book_sequence_distance_"
        "from_common"
    )
] = (
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "initiation_book_collector_sequence"
    ].astype("int64")
    - PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "common_book_collector_sequence"
    ].astype("int64")
)

PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
    (
        "event_inherited_book_time_distance_"
        "from_common_ns"
    )
] = (
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "initiation_book_local_receipt_time_ns"
    ].astype("int64")
    - PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "common_book_local_receipt_time_ns"
    ].astype("int64")
)

require(
    not PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "event_inherited_initiation_book_is_earlier_flag"
    ].any(),
    (
        "At least one event inherited an initiation book "
        "earlier than the selected common batch book."
    ),
)

require(
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        (
            "event_inherited_book_sequence_"
            "distance_from_common"
        )
    ].ge(0).all(),
    (
        "At least one event has a negative inherited-book "
        "sequence distance from the common batch book."
    ),
)

require(
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        (
            "event_inherited_book_time_"
            "distance_from_common_ns"
        )
    ].ge(0).all(),
    (
        "At least one event has a negative inherited-book "
        "time distance from the common batch book."
    ),
)

mismatched_common_book_flag = (
    ~PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "common_book_matches_event_initiation_state_flag"
    ].astype(bool)
)

later_inherited_book_flag = (
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "event_inherited_initiation_book_is_later_flag"
    ].astype(bool)
)

require(
    mismatched_common_book_flag.equals(
        later_inherited_book_flag
    ),
    (
        "An event's inherited initiation book differs from "
        "the common batch book without being strictly later."
    ),
)


# ------------------------------------------------------------
# Explicit scalar counts
#
# Boolean Series are reduced with .sum() before conversion to
# Python integers.
# ------------------------------------------------------------

batches_with_multiple_inherited_book_states = int(
    COMMON_PRE_BATCH_BOOK_STATES[
        (
            "batch_inherited_initiation_"
            "book_state_count"
        )
    ].gt(1).sum()
)

events_not_matching_common_book_count = int(
    mismatched_common_book_flag.sum()
)

events_with_later_inherited_book_count = int(
    later_inherited_book_flag.sum()
)

events_with_earlier_inherited_book_count = int(
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        "event_inherited_initiation_book_is_earlier_flag"
    ].astype(bool).sum()
)

require(
    events_not_matching_common_book_count
    == events_with_later_inherited_book_count,
    (
        "Common-book mismatch count does not equal the count "
        "of later inherited initiation-book states."
    ),
)

require(
    events_with_earlier_inherited_book_count == 0,
    (
        "At least one event inherited an earlier book state "
        "than the common batch state."
    ),
)


# ------------------------------------------------------------
# Event-to-batch assignment reconciliation
# ------------------------------------------------------------

common_membership_assignment = (
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        [
            "primary_event_id",
            "primary_event_number",
            "primary_event_batch_id",
            "primary_event_batch_number",
            "event_partition_order",
            "event_partition",
            "event_time_ns",
        ]
    ]
    .merge(
        PRIMARY_EVENT_TO_BATCH_MEMBERSHIP[
            [
                "primary_event_id",
                "primary_event_number",
                "primary_event_batch_id",
                "primary_event_batch_number",
                "event_partition_order",
                "event_partition",
                "event_time_ns",
            ]
        ],
        how="outer",
        on="primary_event_id",
        suffixes=(
            "__common",
            "__upstream",
        ),
        indicator=True,
        validate="one_to_one",
    )
)

require(
    common_membership_assignment[
        "_merge"
    ].eq("both").all(),
    (
        "Common-book event membership and Notebook 04 "
        "event-to-batch membership have different events."
    ),
)

for assignment_field in (
    "primary_event_number",
    "primary_event_batch_id",
    "primary_event_batch_number",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
):
    common_values = (
        common_membership_assignment[
            f"{assignment_field}__common"
        ]
        .astype("string")
        .fillna("<NA>")
    )

    upstream_values = (
        common_membership_assignment[
            f"{assignment_field}__upstream"
        ]
        .astype("string")
        .fillna("<NA>")
    )

    require(
        common_values.equals(
            upstream_values
        ),
        (
            "Common-book event membership changed Notebook "
            f"04 assignment field {assignment_field!r}."
        ),
    )


# ------------------------------------------------------------
# Same-batch feature-invariance audit
# ------------------------------------------------------------

COMMON_BOOK_INVARIANCE_FIELDS: Final[
    tuple[str, ...]
] = (
    "common_book_book_state_id",
    "common_book_collector_sequence",
    "common_book_local_receipt_time_ns",
    "common_book_partition",
    "common_book_partition_order",
    "common_book_age_ns",
    (
        "common_book_sequence_distance_to_"
        "batch_min_initiation"
    ),
    "common_book_best_bid",
    "common_book_best_ask",
    "common_book_best_bid_quantity",
    "common_book_best_ask_quantity",
    "common_book_spread",
    "common_book_spread_ticks",
    "common_book_midpoint",
    "common_book_microprice",
    "common_book_microprice_minus_midpoint",
    "common_book_top_level_imbalance",
    "common_book_multi_level_imbalance",
    "common_book_visible_bid_depth_top_10",
    "common_book_visible_ask_depth_top_10",
    "common_book_visible_total_depth_top_10",
    "common_book_selection_basis",
    "cross_partition_history_flag",
)

batch_invariance_nunique = (
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP.groupby(
        "primary_event_batch_id",
        observed=True,
        sort=False,
        dropna=False,
    )[
        list(
            COMMON_BOOK_INVARIANCE_FIELDS
        )
    ]
    .nunique(
        dropna=False
    )
)

batch_invariance_failure_mask = (
    batch_invariance_nunique.gt(1)
)

same_batch_feature_invariance_failure_count = int(
    batch_invariance_failure_mask.any(
        axis=1
    ).sum()
)

SAME_BATCH_FEATURE_INVARIANCE_AUDIT = (
    batch_invariance_nunique.reset_index()
)

SAME_BATCH_FEATURE_INVARIANCE_AUDIT[
    "maximum_distinct_common_value_count"
] = (
    batch_invariance_nunique.max(
        axis=1
    ).to_numpy()
)

SAME_BATCH_FEATURE_INVARIANCE_AUDIT[
    "same_batch_common_book_invariant_flag"
] = (
    SAME_BATCH_FEATURE_INVARIANCE_AUDIT[
        "maximum_distinct_common_value_count"
    ].le(1)
)

require(
    same_batch_feature_invariance_failure_count == 0,
    (
        "One or more exact-time batches received different "
        "common pre-batch visible-book values."
    ),
)


# ------------------------------------------------------------
# Reconcile propagated event counts to batch counts
# ------------------------------------------------------------

propagated_event_counts = (
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP.groupby(
        "primary_event_batch_id",
        observed=True,
        sort=False,
        dropna=False,
    )
    .size()
    .rename(
        "propagated_event_count"
    )
)

batch_event_count_reconciliation = (
    COMMON_PRE_BATCH_BOOK_STATES[
        [
            "primary_event_batch_id",
            "batch_event_count",
        ]
    ]
    .set_index(
        "primary_event_batch_id"
    )
    .join(
        propagated_event_counts,
        how="outer",
    )
)

require(
    batch_event_count_reconciliation[
        [
            "batch_event_count",
            "propagated_event_count",
        ]
    ].notna().all().all(),
    (
        "At least one batch is missing from the propagated "
        "event-count reconciliation."
    ),
)

require(
    batch_event_count_reconciliation[
        "batch_event_count"
    ].astype("int64").equals(
        batch_event_count_reconciliation[
            "propagated_event_count"
        ].astype("int64")
    ),
    (
        "Propagated common-book event counts differ from "
        "Notebook 04 batch event counts."
    ),
)


# ------------------------------------------------------------
# Compact partition-level selection summary
# ------------------------------------------------------------

COMMON_PRE_BATCH_BOOK_SELECTION_SUMMARY = (
    COMMON_PRE_BATCH_BOOK_STATES.groupby(
        [
            "event_partition_order",
            "event_partition",
        ],
        observed=True,
        sort=True,
        dropna=False,
    )
    .agg(
        batch_count=(
            "primary_event_batch_id",
            "size",
        ),
        unique_common_book_state_count=(
            "common_book_book_state_id",
            "nunique",
        ),
        zero_local_lag_batch_count=(
            "common_book_same_local_timestamp_flag",
            "sum",
        ),
        cross_partition_history_batch_count=(
            "cross_partition_history_flag",
            "sum",
        ),
        multiple_inherited_book_state_batch_count=(
            (
                "batch_inherited_initiation_"
                "book_state_count"
            ),
            lambda values: int(
                values.gt(1).sum()
            ),
        ),
        common_book_age_ns_min=(
            "common_book_age_ns",
            "min",
        ),
        common_book_age_ns_median=(
            "common_book_age_ns",
            "median",
        ),
        common_book_age_ns_max=(
            "common_book_age_ns",
            "max",
        ),
        sequence_distance_min=(
            (
                "common_book_sequence_distance_to_"
                "batch_min_initiation"
            ),
            "min",
        ),
        sequence_distance_median=(
            (
                "common_book_sequence_distance_to_"
                "batch_min_initiation"
            ),
            "median",
        ),
        sequence_distance_max=(
            (
                "common_book_sequence_distance_to_"
                "batch_min_initiation"
            ),
            "max",
        ),
    )
    .reset_index()
)

event_reconciliation_summary = (
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP.groupby(
        [
            "event_partition_order",
            "event_partition",
        ],
        observed=True,
        sort=True,
        dropna=False,
    )
    .agg(
        event_count=(
            "primary_event_id",
            "size",
        ),
        event_common_book_match_count=(
            (
                "common_book_matches_event_"
                "initiation_state_flag"
            ),
            "sum",
        ),
        later_inherited_book_event_count=(
            (
                "event_inherited_initiation_"
                "book_is_later_flag"
            ),
            "sum",
        ),
    )
    .reset_index()
)

COMMON_PRE_BATCH_BOOK_SELECTION_SUMMARY = (
    COMMON_PRE_BATCH_BOOK_SELECTION_SUMMARY.merge(
        event_reconciliation_summary,
        how="left",
        on=[
            "event_partition_order",
            "event_partition",
        ],
        validate="one_to_one",
    )
)


# ------------------------------------------------------------
# Gate table
# ------------------------------------------------------------

zero_local_lag_batch_count = int(
    COMMON_PRE_BATCH_BOOK_STATES[
        "common_book_same_local_timestamp_flag"
    ].astype(bool).sum()
)

cross_partition_history_batch_count = int(
    COMMON_PRE_BATCH_BOOK_STATES[
        "cross_partition_history_flag"
    ].astype(bool).sum()
)

future_partition_book_count = int(
    COMMON_PRE_BATCH_BOOK_STATES[
        "future_partition_book_flag"
    ].astype(bool).sum()
)

latest_eligible_failure_count = int(
    COMMON_PRE_BATCH_BOOK_STATES[
        "common_book_next_would_be_eligible_flag"
    ].astype(bool).sum()
)

COMMON_PRE_BATCH_BOOK_GATES = pd.DataFrame(
    [
        {
            "gate": (
                "canonical_batch_spine_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    COMMON_PRE_BATCH_BOOK_STATES
                )
                == EXPECTED_PRIMARY_BATCH_ROWS
            ),
            "evidence": (
                f"batches="
                f"{len(COMMON_PRE_BATCH_BOOK_STATES)}"
            ),
        },
        {
            "gate": (
                "common_book_candidate_exists"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                COMMON_PRE_BATCH_BOOK_STATES[
                    "common_book_candidate_exists_flag"
                ].all()
            ),
            "evidence": (
                f"missing="
                f"{int((~COMMON_PRE_BATCH_BOOK_STATES['common_book_candidate_exists_flag'].astype(bool)).sum())}"
            ),
        },
        {
            "gate": (
                "common_book_sequence_cutoff"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                COMMON_PRE_BATCH_BOOK_STATES[
                    "common_book_sequence_condition_flag"
                ].all()
            ),
            "evidence": (
                "common book sequence < minimum "
                "initiating sequence"
            ),
        },
        {
            "gate": (
                "common_book_local_time_cutoff"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                COMMON_PRE_BATCH_BOOK_STATES[
                    "common_book_local_time_condition_flag"
                ].all()
            ),
            "evidence": (
                "common book local time <= batch time"
            ),
        },
        {
            "gate": (
                "latest_eligible_common_book"
            ),
            "severity": "BLOCKING",
            "passed": (
                latest_eligible_failure_count == 0
            ),
            "evidence": (
                f"later_eligible_states="
                f"{latest_eligible_failure_count}"
            ),
        },
        {
            "gate": (
                "common_book_matches_earliest_event"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
                    (
                        "common_book_matches_earliest_"
                        "initiation_state_flag"
                    )
                ].all()
            ),
            "evidence": (
                f"batches="
                f"{len(COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION)}"
            ),
        },
        {
            "gate": (
                "event_membership_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP
                )
                == EXPECTED_PRIMARY_EVENT_ROWS
            ),
            "evidence": (
                f"events="
                f"{len(PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP)}"
            ),
        },
        {
            "gate": (
                "event_to_batch_assignment_preserved"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                common_membership_assignment[
                    "_merge"
                ].eq("both").all()
            ),
            "evidence": (
                f"assignments="
                f"{len(common_membership_assignment)}"
            ),
        },
        {
            "gate": (
                "same_batch_feature_invariance"
            ),
            "severity": "BLOCKING",
            "passed": (
                same_batch_feature_invariance_failure_count
                == 0
            ),
            "evidence": (
                f"failed_batches="
                f"{same_batch_feature_invariance_failure_count}"
            ),
        },
        {
            "gate": (
                "no_future_partition_book"
            ),
            "severity": "BLOCKING",
            "passed": (
                future_partition_book_count == 0
            ),
            "evidence": (
                f"future_partition_books="
                f"{future_partition_book_count}"
            ),
        },
        {
            "gate": (
                "no_event_inherited_earlier_book"
            ),
            "severity": "BLOCKING",
            "passed": (
                events_with_earlier_inherited_book_count
                == 0
            ),
            "evidence": (
                f"earlier_inherited_events="
                f"{events_with_earlier_inherited_book_count}"
            ),
        },
        {
            "gate": (
                "zero_local_lag_common_books"
            ),
            "severity": "WARNING",
            "passed": (
                zero_local_lag_batch_count == 0
            ),
            "evidence": (
                f"count="
                f"{zero_local_lag_batch_count}; "
                "eligible only by prior collector sequence"
            ),
        },
        {
            "gate": (
                "cross_partition_history_carried"
            ),
            "severity": "WARNING",
            "passed": (
                cross_partition_history_batch_count == 0
            ),
            "evidence": (
                f"count="
                f"{cross_partition_history_batch_count}"
            ),
        },
        {
            "gate": (
                "multiple_inherited_books_inside_batch"
            ),
            "severity": "WARNING",
            "passed": (
                batches_with_multiple_inherited_book_states
                == 0
            ),
            "evidence": (
                f"batches="
                f"{batches_with_multiple_inherited_book_states}"
            ),
        },
        {
            "gate": (
                "later_event_specific_inherited_books"
            ),
            "severity": "WARNING",
            "passed": (
                events_with_later_inherited_book_count
                == 0
            ),
            "evidence": (
                f"events="
                f"{events_with_later_inherited_book_count}; "
                "later inherited states are excluded from "
                "common t-minus features"
            ),
        },
    ]
)

COMMON_PRE_BATCH_BOOK_GATES[
    "status"
] = np.select(
    [
        COMMON_PRE_BATCH_BOOK_GATES[
            "passed"
        ],
        COMMON_PRE_BATCH_BOOK_GATES[
            "severity"
        ].eq("BLOCKING"),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

common_book_blocking_failures = (
    COMMON_PRE_BATCH_BOOK_GATES.loc[
        COMMON_PRE_BATCH_BOOK_GATES[
            "severity"
        ].eq("BLOCKING")
        & ~COMMON_PRE_BATCH_BOOK_GATES[
            "passed"
        ]
    ]
)

require(
    common_book_blocking_failures.empty,
    (
        "Common pre-batch visible-book construction contains "
        "blocking failures."
    ),
)


# ------------------------------------------------------------
# Frozen downstream interface
# ------------------------------------------------------------

CANONICAL_BATCH_SPINE_VERIFIED: Final[
    bool
] = True

COMMON_PRE_BATCH_BOOK_INTERFACE_VERIFIED: Final[
    bool
] = True

COMMON_PRE_BATCH_BOOK_ROW_COUNT: Final[
    int
] = int(
    len(
        COMMON_PRE_BATCH_BOOK_STATES
    )
)

PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP_ROW_COUNT: Final[
    int
] = int(
    len(
        PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP
    )
)


# ------------------------------------------------------------
# Compact displays
# ------------------------------------------------------------

display(
    COMMON_PRE_BATCH_BOOK_SELECTION_SUMMARY
)

display(
    COMMON_BOOK_EARLIEST_EVENT_RECONCILIATION[
        [
            "primary_event_batch_id",
            "common_book_book_state_id",
            "earliest_initiation_book_state_id",
            (
                "common_book_matches_earliest_"
                "initiation_state_flag"
            ),
        ]
    ].head(20)
)

display(
    PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP[
        [
            "primary_event_id",
            "primary_event_batch_id",
            "event_partition",
            "event_time_ns",
            "initiation_book_state_id",
            "common_book_book_state_id",
            (
                "common_book_matches_event_"
                "initiation_state_flag"
            ),
            (
                "event_inherited_initiation_"
                "book_is_later_flag"
            ),
            "common_book_age_ns",
            "cross_partition_history_flag",
        ]
    ].head(20)
)

display(
    COMMON_PRE_BATCH_BOOK_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "canonical_observational_unit": (
        CANONICAL_OBSERVATIONAL_UNIT
    ),
    "canonical_batch_spine_verified": (
        CANONICAL_BATCH_SPINE_VERIFIED
    ),
    "common_pre_batch_book_interface_verified": (
        COMMON_PRE_BATCH_BOOK_INTERFACE_VERIFIED
    ),
    "common_book_selection_rule": (
        COMMON_PRE_BATCH_BOOK_SELECTION_RULE
    ),
    "batch_rows": int(
        len(
            COMMON_PRE_BATCH_BOOK_STATES
        )
    ),
    "event_membership_rows": int(
        len(
            PRIMARY_EVENT_COMMON_BOOK_MEMBERSHIP
        )
    ),
    "unique_common_book_states": int(
        COMMON_PRE_BATCH_BOOK_STATES[
            "common_book_book_state_id"
        ].nunique()
    ),
    "zero_local_lag_batches": int(
        zero_local_lag_batch_count
    ),
    "cross_partition_history_batches": int(
        cross_partition_history_batch_count
    ),
    "batches_with_multiple_inherited_book_states": int(
        batches_with_multiple_inherited_book_states
    ),
    "events_not_matching_common_book": int(
        events_not_matching_common_book_count
    ),
    "events_with_later_inherited_book": int(
        events_with_later_inherited_book_count
    ),
    "events_with_earlier_inherited_book": int(
        events_with_earlier_inherited_book_count
    ),
    "same_batch_invariance_failures": int(
        same_batch_feature_invariance_failure_count
    ),
    "latest_eligible_selection_failures": int(
        latest_eligible_failure_count
    ),
    "future_partition_book_count": int(
        future_partition_book_count
    ),
    "timestamp_jitter_applied": False,
    "events_removed": 0,
    "future_labels_attached": False,
    "verified_at_utc": utc_now_iso(),
}

,event_partition_order,event_partition,batch_count,unique_common_book_state_count,zero_local_lag_batch_count,cross_partition_history_batch_count,multiple_inherited_book_state_batch_count,common_book_age_ns_min,common_book_age_ns_median,common_book_age_ns_max,sequence_distance_min,sequence_distance_median,sequence_distance_max,event_count,event_common_book_match_count,later_inherited_book_event_count
0,1,DEVELOPMENT,6859,5161,40,0,3,0,50963900.0,108565100,1,1.0,455,7004,7001,3
1,2,CALIBRATION,2400,1805,24,0,0,0,51182100.0,108050600,1,1.0,258,2493,2493,0
2,3,VALIDATION,1999,1501,22,1,1,0,50679800.0,107980600,1,1.0,309,2048,2047,1
3,4,ENGINEERING_HOLDOUT,2306,1702,21,0,1,0,50639600.0,101629200,1,1.0,280,2342,2341,1

,primary_event_batch_id,common_book_book_state_id,earliest_initiation_book_state_id,common_book_matches_earliest_initiation_state_flag
0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000001,3,3,True
1,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000002,6,6,True
2,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000003,10,10,True
3,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000004,12,12,True
4,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000005,18,18,True
5,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000006,18,18,True
6,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000007,21,21,True
7,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,32,32,True
8,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000009,33,33,True
9,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000010,34,34,True
10,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000011,37,37,True
11,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000012,38,38,True
12,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000013,41,41,True
13,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000014,45,45,True
14,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000015,46,46,True
15,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000016,47,47,True
16,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000017,48,48,True
17,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000018,49,49,True
18,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000019,54,54,True
19,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000020,62,62,True

,primary_event_id,primary_event_batch_id,event_partition,event_time_ns,initiation_book_state_id,common_book_book_state_id,common_book_matches_event_initiation_state_flag,event_inherited_initiation_book_is_later_flag,common_book_age_ns,cross_partition_history_flag
0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000001,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000001,DEVELOPMENT,1783665468766951600,3,3,True,False,33290800,False
1,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000002,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000002,DEVELOPMENT,1783665469052166500,6,6,True,False,20223700,False
2,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000003,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000003,DEVELOPMENT,1783665469437964400,10,10,True,False,5144200,False
3,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000004,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000004,DEVELOPMENT,1783665469692104200,12,12,True,False,59733300,False
4,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000005,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000005,DEVELOPMENT,1783665470242312100,18,18,True,False,10415300,False
5,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000006,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000006,DEVELOPMENT,1783665470304239100,18,18,True,False,72342300,False
6,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000007,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000007,DEVELOPMENT,1783665470597198800,21,21,True,False,65189700,False
7,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000008,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,DEVELOPMENT,1783665471662326600,32,32,True,False,29998400,False
8,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000009,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000009,DEVELOPMENT,1783665471742062100,33,33,True,False,9220900,False
9,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000010,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000010,DEVELOPMENT,1783665471862162900,34,34,True,False,29836100,False
10,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000011,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000011,DEVELOPMENT,1783665472192276400,37,37,True,False,59903200,False
11,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000012,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000012,DEVELOPMENT,1783665472241436900,38,38,True,False,9206600,False
12,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000013,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000013,DEVELOPMENT,1783665472587325700,41,41,True,False,55158100,False
13,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000014,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000014,DEVELOPMENT,1783665473022153600,45,45,True,False,90250000,False
14,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000015,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000015,DEVELOPMENT,1783665473076372900,46,46,True,False,44095800,False
15,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000016,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000016,DEVELOPMENT,1783665473232045400,47,47,True,False,99863200,False
16,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000017,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000017,DEVELOPMENT,1783665473281888100,48,48,True,False,49842700,False
17,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000018,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000018,DEVELOPMENT,1783665473362182500,49,49,True,False,30294000,False
18,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000019,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000019,DEVELOPMENT,1783665473855268900,54,54,True,False,22941100,False
19,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000020,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000020,DEVELOPMENT,1783665474632049800,62,62,True,False,0,False

                                     gate  severity   status                                                                    evidence
0         canonical_batch_spine_conserved  BLOCKING     PASS                                                               batches=13564
1            common_book_candidate_exists  BLOCKING     PASS                                                                   missing=0
2             common_book_sequence_cutoff  BLOCKING     PASS                          common book sequence < minimum initiating sequence
3           common_book_local_time_cutoff  BLOCKING     PASS                                        common book local time <= batch time
4             latest_eligible_common_book  BLOCKING     PASS                                                     later_eligible_states=0
5      common_book_matches_earliest_event  BLOCKING     PASS                                                               batches=13564
6              event_membership_conserved  BLOCKING     PASS                                                                events=13887
7     event_to_batch_assignment_preserved  BLOCKING     PASS                                                           assignments=13887
8           same_batch_feature_invariance  BLOCKING     PASS                                                            failed_batches=0
9                no_future_partition_book  BLOCKING     PASS                                                    future_partition_books=0
10        no_event_inherited_earlier_book  BLOCKING     PASS                                                  earlier_inherited_events=0
11            zero_local_lag_common_books   WARNING  WARNING                        count=107; eligible only by prior collector sequence
12        cross_partition_history_carried   WARNING  WARNING                                                                     count=1
13  multiple_inherited_books_inside_batch   WARNING  WARNING                                                                   batches=5
14   later_event_specific_inherited_books   WARNING  WARNING  events=5; later inherited states are excluded from common t-minus features

{'status': 'PASS',
 'canonical_observational_unit': 'PRIMARY_SCORING_BATCH',
 'canonical_batch_spine_verified': True,
 'common_pre_batch_book_interface_verified': True,
 'common_book_selection_rule': 'LOCAL_STRICT_COMMON_BATCH_CUTOFF',
 'batch_rows': 13564,
 'event_membership_rows': 13887,
 'unique_common_book_states': 10169,
 'zero_local_lag_batches': 107,
 'cross_partition_history_batches': 1,
 'batches_with_multiple_inherited_book_states': 5,
 'events_not_matching_common_book': 5,
 'events_with_later_inherited_book': 5,
 'events_with_earlier_inherited_book': 0,
 'same_batch_invariance_failures': 0,
 'latest_eligible_selection_failures': 0,
 'future_partition_book_count': 0,
 'timestamp_jitter_applied': False,
 'events_removed': 0,
 'future_labels_attached': False,
 'verified_at_utc': '2026-07-19T09:33:58.822434+00:00'}

In [8]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 09 — Information-time classes and causal static
#           visible-book feature interface
# ============================================================


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "CANONICAL_BATCH_SPINE_VERIFIED",
        False,
    )
    is True,
    "Canonical scoring-batch spine has not been verified.",
)

require(
    globals().get(
        "COMMON_PRE_BATCH_BOOK_INTERFACE_VERIFIED",
        False,
    )
    is True,
    "Common pre-batch visible-book interface is unavailable.",
)

require(
    len(COMMON_PRE_BATCH_BOOK_STATES)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Common pre-batch visible-book row count changed "
        "before static feature construction."
    ),
)


# ------------------------------------------------------------
# Frozen information-time classes
# ------------------------------------------------------------

TIMING_CLASS_T_MINUS: Final[str] = "T_MINUS"

TIMING_CLASS_T_PLUS: Final[str] = "T_PLUS"

TIMING_CLASS_DELAYED_ACTIVATION: Final[str] = (
    "DELAYED_ACTIVATION"
)

TIMING_CLASS_FUTURE_LABEL: Final[str] = (
    "FUTURE_LABEL"
)

NOTEBOOK_05_INFORMATION_TIME_CONTRACT = pd.DataFrame(
    [
        {
            "timing_class": TIMING_CLASS_T_MINUS,
            "physical_table_role": (
                "CAUSAL_MARKET_STATE_FEATURE"
            ),
            "availability_rule": (
                "Information must be causally available at "
                "or before the shared scoring-batch cutoff, "
                "subject to the frozen collector-sequence rule."
            ),
            "current_batch_information_allowed": False,
            "same_batch_member_information_allowed": False,
            "future_information_allowed": False,
            "physical_separation_required": False,
            "authorized_in_feature_table": True,
        },
        {
            "timing_class": TIMING_CLASS_T_PLUS,
            "physical_table_role": (
                "POST_BATCH_DIAGNOSTIC"
            ),
            "availability_rule": (
                "Information created by the current scoring "
                "batch becomes available only after all batch "
                "members have been scored."
            ),
            "current_batch_information_allowed": True,
            "same_batch_member_information_allowed": True,
            "future_information_allowed": False,
            "physical_separation_required": True,
            "authorized_in_feature_table": False,
        },
        {
            "timing_class": (
                TIMING_CLASS_DELAYED_ACTIVATION
            ),
            "physical_table_role": (
                "DELAYED_MARK_ACTIVATION"
            ),
            "availability_rule": (
                "A mark may enter historical state only for "
                "a later batch whose event_time_ns is strictly "
                "after the mark availability timestamp."
            ),
            "current_batch_information_allowed": False,
            "same_batch_member_information_allowed": False,
            "future_information_allowed": False,
            "physical_separation_required": True,
            "authorized_in_feature_table": False,
        },
        {
            "timing_class": TIMING_CLASS_FUTURE_LABEL,
            "physical_table_role": (
                "SEPARATE_FUTURE_LABEL"
            ),
            "availability_rule": (
                "The value is realized strictly after the "
                "scoring-batch time and may never be stored "
                "inside a market-state feature artifact."
            ),
            "current_batch_information_allowed": False,
            "same_batch_member_information_allowed": False,
            "future_information_allowed": True,
            "physical_separation_required": True,
            "authorized_in_feature_table": False,
        },
    ]
)

require(
    NOTEBOOK_05_INFORMATION_TIME_CONTRACT[
        "timing_class"
    ].is_unique,
    "Information-time classes are not unique.",
)

require(
    set(
        NOTEBOOK_05_INFORMATION_TIME_CONTRACT[
            "timing_class"
        ]
    )
    == {
        TIMING_CLASS_T_MINUS,
        TIMING_CLASS_T_PLUS,
        TIMING_CLASS_DELAYED_ACTIVATION,
        TIMING_CLASS_FUTURE_LABEL,
    },
    "Information-time contract is incomplete.",
)


# ------------------------------------------------------------
# Required common-book source fields
# ------------------------------------------------------------

STATIC_BOOK_IDENTITY_FIELDS: Final[
    tuple[str, ...]
] = (
    "primary_event_batch_id",
    "primary_event_batch_number",
    "partition_batch_index",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
)

STATIC_BOOK_SELECTION_FIELDS: Final[
    tuple[str, ...]
] = (
    "common_book_book_state_id",
    "common_book_collector_sequence",
    "common_book_local_receipt_time_ns",
    "common_book_partition",
    "common_book_partition_order",
    "common_book_age_ns",
    "common_book_age_ms",
    (
        "common_book_sequence_distance_to_"
        "batch_min_initiation"
    ),
    "common_book_same_local_timestamp_flag",
    "common_book_same_partition_flag",
    "cross_partition_history_flag",
    "common_book_selection_basis",
)

STATIC_BOOK_CORE_FIELDS: Final[
    tuple[str, ...]
] = (
    "common_book_best_bid",
    "common_book_best_ask",
    "common_book_best_bid_quantity",
    "common_book_best_ask_quantity",
    "common_book_spread",
    "common_book_spread_ticks",
    "common_book_spread_basis_points",
    "common_book_midpoint",
    "common_book_microprice",
    "common_book_microprice_minus_midpoint",
    "common_book_top_level_imbalance",
    "common_book_multi_level_imbalance",
    "common_book_visible_bid_depth_top_10",
    "common_book_visible_ask_depth_top_10",
    "common_book_visible_total_depth_top_10",
    (
        "common_book_bid_depth_"
        "concentration_l1_top_10"
    ),
    (
        "common_book_ask_depth_"
        "concentration_l1_top_10"
    ),
    (
        "common_book_combined_l1_"
        "depth_concentration_top_10"
    ),
)

STATIC_BOOK_LEVEL_FIELDS: Final[
    tuple[str, ...]
] = tuple(
    column_name
    for level_number in range(1, 11)
    for column_name in (
        f"common_book_bid_price_{level_number}",
        f"common_book_bid_quantity_{level_number}",
        f"common_book_ask_price_{level_number}",
        f"common_book_ask_quantity_{level_number}",
    )
)

require_columns(
    COMMON_PRE_BATCH_BOOK_STATES,
    (
        *STATIC_BOOK_IDENTITY_FIELDS,
        *STATIC_BOOK_SELECTION_FIELDS,
        *STATIC_BOOK_CORE_FIELDS,
        *STATIC_BOOK_LEVEL_FIELDS,
    ),
    "COMMON_PRE_BATCH_BOOK_STATES",
)


# ------------------------------------------------------------
# Create the static visible-book feature spine
#
# Current-batch event counts, sides, quantities, notionals,
# and aggregate marks are deliberately excluded.
# ------------------------------------------------------------

BATCH_STATIC_VISIBLE_BOOK_FEATURES = (
    COMMON_PRE_BATCH_BOOK_STATES[
        [
            *STATIC_BOOK_IDENTITY_FIELDS,
            *STATIC_BOOK_SELECTION_FIELDS,
        ]
    ]
    .copy()
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)
)

require_unique_columns(
    BATCH_STATIC_VISIBLE_BOOK_FEATURES,
    "BATCH_STATIC_VISIBLE_BOOK_FEATURES",
)

require(
    len(BATCH_STATIC_VISIBLE_BOOK_FEATURES)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Static visible-book feature spine does not contain "
        "one row per scoring batch."
    ),
)

require(
    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        "primary_event_batch_id"
    ].is_unique,
    "Static visible-book feature batch IDs are not unique.",
)


# ------------------------------------------------------------
# Strict source parsing
# ------------------------------------------------------------

def static_book_numeric(
    column_name: str,
) -> pd.Series:
    """Parse one required finite common-book numeric field."""
    return parse_required_float64(
        COMMON_PRE_BATCH_BOOK_STATES[
            column_name
        ],
        column_name,
    )


best_bid = static_book_numeric(
    "common_book_best_bid"
)

best_ask = static_book_numeric(
    "common_book_best_ask"
)

best_bid_quantity = static_book_numeric(
    "common_book_best_bid_quantity"
)

best_ask_quantity = static_book_numeric(
    "common_book_best_ask_quantity"
)

stored_spread = static_book_numeric(
    "common_book_spread"
)

stored_spread_ticks = static_book_numeric(
    "common_book_spread_ticks"
)

stored_spread_bps = static_book_numeric(
    "common_book_spread_basis_points"
)

stored_midpoint = static_book_numeric(
    "common_book_midpoint"
)

stored_microprice = static_book_numeric(
    "common_book_microprice"
)

stored_microprice_displacement = static_book_numeric(
    "common_book_microprice_minus_midpoint"
)

stored_l1_imbalance = static_book_numeric(
    "common_book_top_level_imbalance"
)

stored_top10_imbalance = static_book_numeric(
    "common_book_multi_level_imbalance"
)

stored_bid_depth_top10 = static_book_numeric(
    "common_book_visible_bid_depth_top_10"
)

stored_ask_depth_top10 = static_book_numeric(
    "common_book_visible_ask_depth_top_10"
)

stored_total_depth_top10 = static_book_numeric(
    "common_book_visible_total_depth_top_10"
)

stored_bid_l1_concentration = static_book_numeric(
    (
        "common_book_bid_depth_"
        "concentration_l1_top_10"
    )
)

stored_ask_l1_concentration = static_book_numeric(
    (
        "common_book_ask_depth_"
        "concentration_l1_top_10"
    )
)

stored_combined_l1_concentration = (
    static_book_numeric(
        (
            "common_book_combined_l1_"
            "depth_concentration_top_10"
        )
    )
)


# ------------------------------------------------------------
# Core visible-book arithmetic
# ------------------------------------------------------------

recomputed_spread = (
    best_ask - best_bid
)

recomputed_midpoint = (
    best_bid + best_ask
) / 2.0

l1_total_quantity = (
    best_bid_quantity + best_ask_quantity
)

recomputed_l1_imbalance = (
    best_bid_quantity - best_ask_quantity
) / l1_total_quantity

recomputed_microprice = (
    (
        best_ask * best_bid_quantity
    )
    + (
        best_bid * best_ask_quantity
    )
) / l1_total_quantity

recomputed_microprice_displacement = (
    recomputed_microprice
    - recomputed_midpoint
)

algebraic_microprice_displacement = (
    0.5
    * recomputed_spread
    * recomputed_l1_imbalance
)

recomputed_spread_bps = (
    recomputed_spread
    / recomputed_midpoint
    * 10_000.0
)

implied_tick_size = (
    recomputed_spread
    / stored_spread_ticks
)

require(
    (best_bid > 0).all()
    and (best_ask > 0).all(),
    "Static visible-book best prices must be positive.",
)

require(
    (best_bid < best_ask).all(),
    "A static visible-book row is locked or crossed.",
)

require(
    (best_bid_quantity > 0).all()
    and (best_ask_quantity > 0).all(),
    "Static visible-book level-one quantities must be positive.",
)

require(
    (stored_spread_ticks > 0).all(),
    "Static visible-book spread_ticks must be positive.",
)

require(
    (implied_tick_size > 0).all(),
    "Derived implied tick size must be positive.",
)

authoritative_implied_tick_size = float(
    implied_tick_size.median()
)

require(
    np.allclose(
        implied_tick_size.to_numpy(),
        authoritative_implied_tick_size,
        rtol=0.0,
        atol=1e-10,
    ),
    (
        "The implied tick size is not stable across the "
        "common visible-book states."
    ),
)


# ------------------------------------------------------------
# Load level-price and level-quantity matrices
# ------------------------------------------------------------

bid_price_matrix = np.column_stack(
    [
        static_book_numeric(
            f"common_book_bid_price_{level}"
        ).to_numpy()
        for level in range(1, 11)
    ]
)

ask_price_matrix = np.column_stack(
    [
        static_book_numeric(
            f"common_book_ask_price_{level}"
        ).to_numpy()
        for level in range(1, 11)
    ]
)

bid_quantity_matrix = np.column_stack(
    [
        static_book_numeric(
            f"common_book_bid_quantity_{level}"
        ).to_numpy()
        for level in range(1, 11)
    ]
)

ask_quantity_matrix = np.column_stack(
    [
        static_book_numeric(
            f"common_book_ask_quantity_{level}"
        ).to_numpy()
        for level in range(1, 11)
    ]
)

require(
    np.isfinite(
        bid_price_matrix
    ).all()
    and np.isfinite(
        ask_price_matrix
    ).all()
    and np.isfinite(
        bid_quantity_matrix
    ).all()
    and np.isfinite(
        ask_quantity_matrix
    ).all(),
    "A top-ten visible-book matrix contains non-finite values.",
)

require(
    (bid_price_matrix > 0).all()
    and (ask_price_matrix > 0).all(),
    "A top-ten visible-book price is non-positive.",
)

require(
    (bid_quantity_matrix > 0).all()
    and (ask_quantity_matrix > 0).all(),
    "A top-ten visible-book quantity is non-positive.",
)

require(
    (
        np.diff(
            bid_price_matrix,
            axis=1,
        )
        < 0
    ).all(),
    "Bid levels are not strictly descending.",
)

require(
    (
        np.diff(
            ask_price_matrix,
            axis=1,
        )
        > 0
    ).all(),
    "Ask levels are not strictly ascending.",
)


# ------------------------------------------------------------
# Depth families: top 1, 3, 5, and 10
# ------------------------------------------------------------

DEPTH_LEVEL_GRID: Final[
    tuple[int, ...]
] = (
    1,
    3,
    5,
    10,
)

depth_family_audit_rows: list[
    dict[str, Any]
] = []

for depth_level in DEPTH_LEVEL_GRID:
    bid_depth = pd.Series(
        bid_quantity_matrix[
            :,
            :depth_level,
        ].sum(axis=1),
        index=BATCH_STATIC_VISIBLE_BOOK_FEATURES.index,
        dtype="float64",
    )

    ask_depth = pd.Series(
        ask_quantity_matrix[
            :,
            :depth_level,
        ].sum(axis=1),
        index=BATCH_STATIC_VISIBLE_BOOK_FEATURES.index,
        dtype="float64",
    )

    total_depth = (
        bid_depth + ask_depth
    )

    depth_imbalance = (
        bid_depth - ask_depth
    ) / total_depth

    bid_depth_share = (
        bid_depth / total_depth
    )

    ask_depth_share = (
        ask_depth / total_depth
    )

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        f"tminus_book_bid_depth_top_{depth_level}"
    ] = bid_depth

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        f"tminus_book_ask_depth_top_{depth_level}"
    ] = ask_depth

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        f"tminus_book_total_depth_top_{depth_level}"
    ] = total_depth

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        f"tminus_book_depth_imbalance_top_{depth_level}"
    ] = depth_imbalance

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        f"tminus_book_bid_depth_share_top_{depth_level}"
    ] = bid_depth_share

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        f"tminus_book_ask_depth_share_top_{depth_level}"
    ] = ask_depth_share

    require(
        (bid_depth > 0).all()
        and (ask_depth > 0).all(),
        (
            f"Top-{depth_level} side depth contains a "
            "non-positive value."
        ),
    )

    require(
        depth_imbalance.between(
            -1.0,
            1.0,
            inclusive="both",
        ).all(),
        (
            f"Top-{depth_level} depth imbalance lies "
            "outside [-1, 1]."
        ),
    )

    require(
        bid_depth_share.between(
            0.0,
            1.0,
            inclusive="both",
        ).all()
        and ask_depth_share.between(
            0.0,
            1.0,
            inclusive="both",
        ).all(),
        (
            f"Top-{depth_level} relative depth share lies "
            "outside [0, 1]."
        ),
    )

    require(
        np.allclose(
            (
                bid_depth_share
                + ask_depth_share
            ).to_numpy(),
            1.0,
            rtol=0.0,
            atol=1e-12,
        ),
        (
            f"Top-{depth_level} bid and ask depth shares "
            "do not sum to one."
        ),
    )

    depth_family_audit_rows.append(
        {
            "depth_level": depth_level,
            "minimum_bid_depth": float(
                bid_depth.min()
            ),
            "minimum_ask_depth": float(
                ask_depth.min()
            ),
            "minimum_imbalance": float(
                depth_imbalance.min()
            ),
            "maximum_imbalance": float(
                depth_imbalance.max()
            ),
            "status": "PASS",
        }
    )

STATIC_DEPTH_FAMILY_AUDIT = (
    pd.DataFrame.from_records(
        depth_family_audit_rows
    )
)


# ------------------------------------------------------------
# Core level-one and price-state features
# ------------------------------------------------------------

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_best_bid"
] = best_bid

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_best_ask"
] = best_ask

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_best_bid_quantity"
] = best_bid_quantity

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_best_ask_quantity"
] = best_ask_quantity

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_spread"
] = recomputed_spread

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_spread_ticks"
] = stored_spread_ticks

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_spread_basis_points"
] = recomputed_spread_bps

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_midpoint"
] = recomputed_midpoint

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_weighted_midpoint"
] = recomputed_microprice

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_weighted_midpoint_displacement"
] = recomputed_microprice_displacement

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    (
        "tminus_book_weighted_midpoint_"
        "displacement_basis_points"
    )
] = (
    recomputed_microprice_displacement
    / recomputed_midpoint
    * 10_000.0
)

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_level_one_imbalance"
] = recomputed_l1_imbalance

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_implied_tick_size"
] = implied_tick_size

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_wide_spread_flag"
] = (
    stored_spread_ticks > 1.0
)


# ------------------------------------------------------------
# Depth concentration and book-shape features
# ------------------------------------------------------------

bid_depth_top10_array = (
    bid_quantity_matrix.sum(
        axis=1
    )
)

ask_depth_top10_array = (
    ask_quantity_matrix.sum(
        axis=1
    )
)

total_depth_top10_array = (
    bid_depth_top10_array
    + ask_depth_top10_array
)

bid_depth_share_matrix = (
    bid_quantity_matrix
    / bid_depth_top10_array[:, None]
)

ask_depth_share_matrix = (
    ask_quantity_matrix
    / ask_depth_top10_array[:, None]
)

bid_depth_hhi_top10 = (
    bid_depth_share_matrix ** 2
).sum(axis=1)

ask_depth_hhi_top10 = (
    ask_depth_share_matrix ** 2
).sum(axis=1)

combined_quantity_matrix = np.concatenate(
    [
        bid_quantity_matrix,
        ask_quantity_matrix,
    ],
    axis=1,
)

combined_depth_share_matrix = (
    combined_quantity_matrix
    / total_depth_top10_array[:, None]
)

combined_depth_hhi_top10 = (
    combined_depth_share_matrix ** 2
).sum(axis=1)

bid_distance_from_best_ticks = (
    (
        bid_price_matrix[:, [0]]
        - bid_price_matrix
    )
    / implied_tick_size.to_numpy()[:, None]
)

ask_distance_from_best_ticks = (
    (
        ask_price_matrix
        - ask_price_matrix[:, [0]]
    )
    / implied_tick_size.to_numpy()[:, None]
)

bid_depth_weighted_distance_ticks = (
    (
        bid_quantity_matrix
        * bid_distance_from_best_ticks
    ).sum(axis=1)
    / bid_depth_top10_array
)

ask_depth_weighted_distance_ticks = (
    (
        ask_quantity_matrix
        * ask_distance_from_best_ticks
    ).sum(axis=1)
    / ask_depth_top10_array
)

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_bid_depth_hhi_top_10"
] = bid_depth_hhi_top10

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_ask_depth_hhi_top_10"
] = ask_depth_hhi_top10

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    "tminus_book_combined_depth_hhi_top_10"
] = combined_depth_hhi_top10

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    (
        "tminus_book_bid_depth_weighted_"
        "distance_ticks_top_10"
    )
] = bid_depth_weighted_distance_ticks

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    (
        "tminus_book_ask_depth_weighted_"
        "distance_ticks_top_10"
    )
] = ask_depth_weighted_distance_ticks

BATCH_STATIC_VISIBLE_BOOK_FEATURES[
    (
        "tminus_book_depth_weighted_"
        "distance_asymmetry_top_10"
    )
] = (
    bid_depth_weighted_distance_ticks
    - ask_depth_weighted_distance_ticks
)

require(
    (
        bid_depth_hhi_top10 >= 0.1 - 1e-12
    ).all()
    and (
        bid_depth_hhi_top10 <= 1.0 + 1e-12
    ).all(),
    "Bid-side top-10 depth HHI lies outside its valid range.",
)

require(
    (
        ask_depth_hhi_top10 >= 0.1 - 1e-12
    ).all()
    and (
        ask_depth_hhi_top10 <= 1.0 + 1e-12
    ).all(),
    "Ask-side top-10 depth HHI lies outside its valid range.",
)

require(
    (
        combined_depth_hhi_top10
        >= 0.05 - 1e-12
    ).all()
    and (
        combined_depth_hhi_top10
        <= 1.0 + 1e-12
    ).all(),
    (
        "Combined top-10 depth HHI lies outside its "
        "valid range."
    ),
)

require(
    (
        bid_depth_weighted_distance_ticks >= 0
    ).all()
    and (
        ask_depth_weighted_distance_ticks >= 0
    ).all(),
    "A depth-weighted book-shape distance is negative.",
)


# ------------------------------------------------------------
# Adjacent-level price gaps
# ------------------------------------------------------------

bid_adjacent_gap_price = (
    bid_price_matrix[:, :-1]
    - bid_price_matrix[:, 1:]
)

ask_adjacent_gap_price = (
    ask_price_matrix[:, 1:]
    - ask_price_matrix[:, :-1]
)

bid_adjacent_gap_ticks = (
    bid_adjacent_gap_price
    / implied_tick_size.to_numpy()[:, None]
)

ask_adjacent_gap_ticks = (
    ask_adjacent_gap_price
    / implied_tick_size.to_numpy()[:, None]
)

require(
    (bid_adjacent_gap_price > 0).all()
    and (ask_adjacent_gap_price > 0).all(),
    "An adjacent-level visible-book price gap is non-positive.",
)

for gap_number in range(1, 10):
    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        (
            f"tminus_book_bid_gap_"
            f"level_{gap_number}_to_{gap_number + 1}_ticks"
        )
    ] = bid_adjacent_gap_ticks[
        :,
        gap_number - 1,
    ]

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        (
            f"tminus_book_ask_gap_"
            f"level_{gap_number}_to_{gap_number + 1}_ticks"
        )
    ] = ask_adjacent_gap_ticks[
        :,
        gap_number - 1,
    ]

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        (
            f"tminus_book_bid_gap_"
            f"level_{gap_number}_to_{gap_number + 1}_"
            "basis_points"
        )
    ] = (
        bid_adjacent_gap_price[
            :,
            gap_number - 1,
        ]
        / recomputed_midpoint.to_numpy()
        * 10_000.0
    )

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        (
            f"tminus_book_ask_gap_"
            f"level_{gap_number}_to_{gap_number + 1}_"
            "basis_points"
        )
    ] = (
        ask_adjacent_gap_price[
            :,
            gap_number - 1,
        ]
        / recomputed_midpoint.to_numpy()
        * 10_000.0
    )


for depth_level in (
    3,
    5,
    10,
):
    adjacent_gap_count = (
        depth_level - 1
    )

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        (
            f"tminus_book_mean_bid_adjacent_"
            f"gap_ticks_top_{depth_level}"
        )
    ] = bid_adjacent_gap_ticks[
        :,
        :adjacent_gap_count,
    ].mean(axis=1)

    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        (
            f"tminus_book_mean_ask_adjacent_"
            f"gap_ticks_top_{depth_level}"
        )
    ] = ask_adjacent_gap_ticks[
        :,
        :adjacent_gap_count,
    ].mean(axis=1)


# ------------------------------------------------------------
# Reconciliation with Notebook 02 persisted calculations
# ------------------------------------------------------------

static_reconciliation_rows: list[
    dict[str, Any]
] = []


def reconcile_static_numeric(
    *,
    field_name: str,
    persisted: pd.Series,
    recomputed: pd.Series | np.ndarray,
    rtol: float = 1e-11,
    atol: float = 1e-10,
) -> None:
    """Audit one persisted versus recomputed book field."""
    left = np.asarray(
        persisted,
        dtype="float64",
    )

    right = np.asarray(
        recomputed,
        dtype="float64",
    )

    require(
        left.shape == right.shape,
        (
            f"{field_name} reconciliation shape mismatch: "
            f"{left.shape} versus {right.shape}."
        ),
    )

    close = np.isclose(
        left,
        right,
        rtol=rtol,
        atol=atol,
        equal_nan=False,
    )

    mismatch_count = int(
        (~close).sum()
    )

    maximum_absolute_error = float(
        np.max(
            np.abs(
                left - right
            )
        )
    )

    static_reconciliation_rows.append(
        {
            "field": field_name,
            "row_count": int(
                len(left)
            ),
            "mismatch_count": (
                mismatch_count
            ),
            "maximum_absolute_error": (
                maximum_absolute_error
            ),
            "status": (
                "PASS"
                if mismatch_count == 0
                else "FAIL"
            ),
        }
    )

    require(
        mismatch_count == 0,
        (
            f"Static visible-book field {field_name!r} "
            "does not reconcile with Notebook 02."
        ),
    )


reconcile_static_numeric(
    field_name="spread",
    persisted=stored_spread,
    recomputed=recomputed_spread,
)

reconcile_static_numeric(
    field_name="spread_basis_points",
    persisted=stored_spread_bps,
    recomputed=recomputed_spread_bps,
)

reconcile_static_numeric(
    field_name="midpoint",
    persisted=stored_midpoint,
    recomputed=recomputed_midpoint,
)

reconcile_static_numeric(
    field_name="microprice",
    persisted=stored_microprice,
    recomputed=recomputed_microprice,
)

reconcile_static_numeric(
    field_name="microprice_minus_midpoint",
    persisted=stored_microprice_displacement,
    recomputed=recomputed_microprice_displacement,
)

reconcile_static_numeric(
    field_name="top_level_imbalance",
    persisted=stored_l1_imbalance,
    recomputed=recomputed_l1_imbalance,
)

reconcile_static_numeric(
    field_name="visible_bid_depth_top_10",
    persisted=stored_bid_depth_top10,
    recomputed=bid_depth_top10_array,
)

reconcile_static_numeric(
    field_name="visible_ask_depth_top_10",
    persisted=stored_ask_depth_top10,
    recomputed=ask_depth_top10_array,
)

reconcile_static_numeric(
    field_name="visible_total_depth_top_10",
    persisted=stored_total_depth_top10,
    recomputed=total_depth_top10_array,
)

recomputed_top10_imbalance = (
    bid_depth_top10_array
    - ask_depth_top10_array
) / total_depth_top10_array

reconcile_static_numeric(
    field_name="multi_level_imbalance",
    persisted=stored_top10_imbalance,
    recomputed=recomputed_top10_imbalance,
)

reconcile_static_numeric(
    field_name="bid_l1_depth_concentration_top_10",
    persisted=stored_bid_l1_concentration,
    recomputed=(
        bid_quantity_matrix[:, 0]
        / bid_depth_top10_array
    ),
)

reconcile_static_numeric(
    field_name="ask_l1_depth_concentration_top_10",
    persisted=stored_ask_l1_concentration,
    recomputed=(
        ask_quantity_matrix[:, 0]
        / ask_depth_top10_array
    ),
)

reconcile_static_numeric(
    field_name="combined_l1_depth_concentration_top_10",
    persisted=stored_combined_l1_concentration,
    recomputed=(
        (
            bid_quantity_matrix[:, 0]
            + ask_quantity_matrix[:, 0]
        )
        / total_depth_top10_array
    ),
)

STATIC_BOOK_RECONCILIATION_AUDIT = (
    pd.DataFrame.from_records(
        static_reconciliation_rows
    )
)


# ------------------------------------------------------------
# Algebraic redundancy audit
#
# weighted midpoint displacement
#   = 0.5 × spread × level-one imbalance
#
# Therefore spread, midpoint, imbalance, weighted midpoint,
# and weighted-midpoint displacement are not jointly
# independent state variables.
# ------------------------------------------------------------

microprice_identity_close = np.isclose(
    recomputed_microprice_displacement.to_numpy(),
    algebraic_microprice_displacement.to_numpy(),
    rtol=1e-11,
    atol=1e-10,
    equal_nan=False,
)

microprice_identity_failure_count = int(
    (~microprice_identity_close).sum()
)

require(
    microprice_identity_failure_count == 0,
    (
        "Weighted-midpoint displacement does not satisfy "
        "0.5 × spread × level-one imbalance."
    ),
)

STATIC_BOOK_ALGEBRAIC_REDUNDANCY_AUDIT = pd.DataFrame(
    [
        {
            "redundancy_group": (
                "LEVEL_ONE_WEIGHTED_MIDPOINT_IDENTITY"
            ),
            "primary_components": (
                "spread; midpoint; level_one_imbalance"
            ),
            "derived_component": (
                "weighted_midpoint"
            ),
            "derived_displacement": (
                "weighted_midpoint - midpoint"
            ),
            "identity": (
                "weighted_midpoint_displacement = "
                "0.5 * spread * level_one_imbalance"
            ),
            "row_count": int(
                len(
                    BATCH_STATIC_VISIBLE_BOOK_FEATURES
                )
            ),
            "failure_count": (
                microprice_identity_failure_count
            ),
            "status": "PASS",
        }
    ]
)


# ------------------------------------------------------------
# Feature authority registry
# ------------------------------------------------------------

STATIC_BOOK_IDENTIFIER_COLUMNS: Final[
    tuple[str, ...]
] = (
    *STATIC_BOOK_IDENTITY_FIELDS,
    *STATIC_BOOK_SELECTION_FIELDS,
)

static_feature_registry_rows: list[
    dict[str, Any]
] = []

for feature_name in (
    column_name
    for column_name in (
        BATCH_STATIC_VISIBLE_BOOK_FEATURES.columns
    )
    if column_name
    not in STATIC_BOOK_IDENTIFIER_COLUMNS
):
    if feature_name in {
        "tminus_book_weighted_midpoint",
        (
            "tminus_book_weighted_midpoint_"
            "displacement"
        ),
        (
            "tminus_book_weighted_midpoint_"
            "displacement_basis_points"
        ),
    }:
        authority_class = (
            "AUTHORITATIVE_ALGEBRAICALLY_REDUNDANT"
        )

        redundancy_group = (
            "LEVEL_ONE_WEIGHTED_MIDPOINT_IDENTITY"
        )

    elif feature_name.endswith(
        "_flag"
    ):
        authority_class = (
            "DIAGNOSTIC_CONTROL"
        )

        redundancy_group = None

    elif (
        "hhi" in feature_name
        or "distance" in feature_name
        or "gap_" in feature_name
    ):
        authority_class = (
            "DETERMINISTIC_DERIVED"
        )

        redundancy_group = None

    else:
        authority_class = (
            "AUTHORITATIVE_VISIBLE_BOOK"
        )

        redundancy_group = None

    static_feature_registry_rows.append(
        {
            "feature_name": feature_name,
            "source_notebook": (
                "02_VISIBLE_BOOK_RECONSTRUCTION"
            ),
            "source_artifact": (
                "RECONSTRUCTED_BOOK_STATES"
            ),
            "observational_unit": (
                CANONICAL_OBSERVATIONAL_UNIT
            ),
            "timing_class": (
                TIMING_CLASS_T_MINUS
            ),
            "source_clock": (
                "local_receipt_time_ns"
            ),
            "scoring_clock": (
                "event_time_ns"
            ),
            "causal_cutoff": (
                COMMON_PRE_BATCH_BOOK_SELECTION_RULE
            ),
            "current_batch_included": False,
            "same_batch_member_included": False,
            "authority_class": (
                authority_class
            ),
            "algebraic_redundancy_group": (
                redundancy_group
            ),
        }
    )

STATIC_VISIBLE_BOOK_FEATURE_REGISTRY = (
    pd.DataFrame.from_records(
        static_feature_registry_rows
    )
)

require(
    STATIC_VISIBLE_BOOK_FEATURE_REGISTRY[
        "feature_name"
    ].is_unique,
    "Static visible-book feature registry has duplicate names.",
)

require(
    STATIC_VISIBLE_BOOK_FEATURE_REGISTRY[
        "timing_class"
    ].eq(
        TIMING_CLASS_T_MINUS
    ).all(),
    "A static visible-book feature has the wrong timing class.",
)

require(
    not STATIC_VISIBLE_BOOK_FEATURE_REGISTRY[
        "current_batch_included"
    ].any(),
    (
        "A static visible-book feature incorrectly includes "
        "current-batch information."
    ),
)

require(
    not STATIC_VISIBLE_BOOK_FEATURE_REGISTRY[
        "same_batch_member_included"
    ].any(),
    (
        "A static visible-book feature incorrectly includes "
        "same-batch member information."
    ),
)


# ------------------------------------------------------------
# Leakage and forbidden-field audit
# ------------------------------------------------------------

FORBIDDEN_STATIC_FEATURE_COLUMNS: Final[
    tuple[str, ...]
] = (
    "batch_event_count",
    "buy_event_count",
    "sell_event_count",
    "unique_side_count",
    "batch_print_count",
    "batch_quantity",
    "batch_notional",
    "event_side",
    "event_side_code",
    "event_print_count",
    "event_quantity",
    "event_notional",
    "aggregate_mark_available_time_ns",
    "aggregate_mark_lag_after_event_ns",
)

forbidden_present_columns = sorted(
    set(
        FORBIDDEN_STATIC_FEATURE_COLUMNS
    )
    & set(
        BATCH_STATIC_VISIBLE_BOOK_FEATURES.columns
    )
)

future_like_columns = sorted(
    column_name
    for column_name in (
        BATCH_STATIC_VISIBLE_BOOK_FEATURES.columns
    )
    if (
        column_name.startswith(
            "future_"
        )
        or column_name.startswith(
            "label_"
        )
        or column_name.startswith(
            "target_"
        )
    )
)

require(
    not forbidden_present_columns,
    (
        "Static visible-book table contains current-batch or "
        f"post-batch fields: {forbidden_present_columns}"
    ),
)

require(
    not future_like_columns,
    (
        "Static visible-book table contains future-label-like "
        f"columns: {future_like_columns}"
    ),
)


# ------------------------------------------------------------
# Finite-value and range audit
# ------------------------------------------------------------

static_feature_columns = (
    STATIC_VISIBLE_BOOK_FEATURE_REGISTRY[
        "feature_name"
    ].tolist()
)

numeric_static_feature_columns = [
    column_name
    for column_name in static_feature_columns
    if not pd.api.types.is_bool_dtype(
        BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            column_name
        ]
    )
]

static_numeric_matrix = (
    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        numeric_static_feature_columns
    ]
    .apply(
        pd.to_numeric,
        errors="raise",
    )
    .to_numpy(
        dtype="float64"
    )
)

static_nonfinite_count = int(
    (
        ~np.isfinite(
            static_numeric_matrix
        )
    ).sum()
)

static_missing_feature_count = int(
    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        static_feature_columns
    ].isna().sum().sum()
)

require(
    static_nonfinite_count == 0,
    (
        "Static visible-book feature table contains "
        f"{static_nonfinite_count} non-finite numeric values."
    ),
)

require(
    static_missing_feature_count == 0,
    (
        "Static visible-book feature table contains "
        f"{static_missing_feature_count} missing feature values."
    ),
)

require(
    (
        BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_bid_depth_top_1"
        ]
        <= BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_bid_depth_top_3"
        ]
    ).all()
    and (
        BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_bid_depth_top_3"
        ]
        <= BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_bid_depth_top_5"
        ]
    ).all()
    and (
        BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_bid_depth_top_5"
        ]
        <= BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_bid_depth_top_10"
        ]
    ).all(),
    "Bid-side cumulative depth is not monotonic by level.",
)

require(
    (
        BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_ask_depth_top_1"
        ]
        <= BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_ask_depth_top_3"
        ]
    ).all()
    and (
        BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_ask_depth_top_3"
        ]
        <= BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_ask_depth_top_5"
        ]
    ).all()
    and (
        BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_ask_depth_top_5"
        ]
        <= BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_ask_depth_top_10"
        ]
    ).all(),
    "Ask-side cumulative depth is not monotonic by level.",
)

require(
    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        "tminus_book_weighted_midpoint"
    ].between(
        BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_best_bid"
        ],
        BATCH_STATIC_VISIBLE_BOOK_FEATURES[
            "tminus_book_best_ask"
        ],
        inclusive="both",
    ).all(),
    (
        "A weighted midpoint lies outside the visible "
        "best bid and ask."
    ),
)


# ------------------------------------------------------------
# Same-batch invariance after static feature construction
# ------------------------------------------------------------

STATIC_EVENT_FEATURE_MEMBERSHIP = (
    PRIMARY_EVENT_TO_BATCH_MEMBERSHIP[
        [
            "primary_event_id",
            "primary_event_batch_id",
        ]
    ]
    .merge(
        BATCH_STATIC_VISIBLE_BOOK_FEATURES,
        how="left",
        on="primary_event_batch_id",
        validate="many_to_one",
    )
)

require(
    len(STATIC_EVENT_FEATURE_MEMBERSHIP)
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Static event-feature propagation changed the "
        "primary event count."
    ),
)

static_event_invariance = (
    STATIC_EVENT_FEATURE_MEMBERSHIP.groupby(
        "primary_event_batch_id",
        observed=True,
        sort=False,
        dropna=False,
    )[
        static_feature_columns
    ]
    .nunique(
        dropna=False
    )
)

static_same_batch_invariance_failure_count = int(
    static_event_invariance.gt(1).any(
        axis=1
    ).sum()
)

require(
    static_same_batch_invariance_failure_count == 0,
    (
        "At least one simultaneous batch received different "
        "static visible-book feature values."
    ),
)


# ------------------------------------------------------------
# Gate table
# ------------------------------------------------------------

wide_spread_batch_count = int(
    BATCH_STATIC_VISIBLE_BOOK_FEATURES[
        "tminus_book_wide_spread_flag"
    ].astype(bool).sum()
)

STATIC_VISIBLE_BOOK_FEATURE_GATES = pd.DataFrame(
    [
        {
            "gate": (
                "static_batch_rows_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    BATCH_STATIC_VISIBLE_BOOK_FEATURES
                )
                == EXPECTED_PRIMARY_BATCH_ROWS
            ),
            "evidence": (
                f"rows="
                f"{len(BATCH_STATIC_VISIBLE_BOOK_FEATURES)}"
            ),
        },
        {
            "gate": (
                "static_batch_identity_unique"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                BATCH_STATIC_VISIBLE_BOOK_FEATURES[
                    "primary_event_batch_id"
                ].is_unique
            ),
            "evidence": (
                f"unique_batches="
                f"{BATCH_STATIC_VISIBLE_BOOK_FEATURES['primary_event_batch_id'].nunique()}"
            ),
        },
        {
            "gate": (
                "notebook_02_field_reconciliation"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                STATIC_BOOK_RECONCILIATION_AUDIT[
                    "mismatch_count"
                ].eq(0).all()
            ),
            "evidence": (
                f"fields="
                f"{len(STATIC_BOOK_RECONCILIATION_AUDIT)}"
            ),
        },
        {
            "gate": (
                "weighted_midpoint_algebraic_identity"
            ),
            "severity": "BLOCKING",
            "passed": (
                microprice_identity_failure_count
                == 0
            ),
            "evidence": (
                f"failures="
                f"{microprice_identity_failure_count}"
            ),
        },
        {
            "gate": (
                "static_feature_finite_values"
            ),
            "severity": "BLOCKING",
            "passed": (
                static_nonfinite_count == 0
            ),
            "evidence": (
                f"nonfinite="
                f"{static_nonfinite_count}"
            ),
        },
        {
            "gate": (
                "static_feature_missingness"
            ),
            "severity": "BLOCKING",
            "passed": (
                static_missing_feature_count == 0
            ),
            "evidence": (
                f"missing="
                f"{static_missing_feature_count}"
            ),
        },
        {
            "gate": (
                "static_feature_same_batch_invariance"
            ),
            "severity": "BLOCKING",
            "passed": (
                static_same_batch_invariance_failure_count
                == 0
            ),
            "evidence": (
                f"failed_batches="
                f"{static_same_batch_invariance_failure_count}"
            ),
        },
        {
            "gate": (
                "no_current_batch_fields"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    forbidden_present_columns
                )
                == 0
            ),
            "evidence": (
                f"forbidden_columns="
                f"{len(forbidden_present_columns)}"
            ),
        },
        {
            "gate": (
                "no_future_label_fields"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    future_like_columns
                )
                == 0
            ),
            "evidence": (
                f"future_like_columns="
                f"{len(future_like_columns)}"
            ),
        },
        {
            "gate": (
                "stable_implied_tick_size"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                f"tick_size="
                f"{authoritative_implied_tick_size:.12g}"
            ),
        },
        {
            "gate": (
                "wide_spread_states_present"
            ),
            "severity": "WARNING",
            "passed": (
                wide_spread_batch_count == 0
            ),
            "evidence": (
                f"count="
                f"{wide_spread_batch_count}"
            ),
        },
        {
            "gate": (
                "algebraically_redundant_features_retained"
            ),
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                "weighted midpoint and displacement are "
                "retained for transparency but registered "
                "as algebraically redundant"
            ),
        },
    ]
)

STATIC_VISIBLE_BOOK_FEATURE_GATES[
    "status"
] = np.select(
    [
        STATIC_VISIBLE_BOOK_FEATURE_GATES[
            "passed"
        ],
        STATIC_VISIBLE_BOOK_FEATURE_GATES[
            "severity"
        ].eq("BLOCKING"),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

static_book_blocking_failures = (
    STATIC_VISIBLE_BOOK_FEATURE_GATES.loc[
        STATIC_VISIBLE_BOOK_FEATURE_GATES[
            "severity"
        ].eq("BLOCKING")
        & ~STATIC_VISIBLE_BOOK_FEATURE_GATES[
            "passed"
        ]
    ]
)

require(
    static_book_blocking_failures.empty,
    (
        "Static visible-book feature construction contains "
        "blocking failures."
    ),
)


# ------------------------------------------------------------
# Frozen downstream state
# ------------------------------------------------------------

STATIC_VISIBLE_BOOK_FEATURES_VERIFIED: Final[
    bool
] = True

STATIC_VISIBLE_BOOK_FEATURE_ROW_COUNT: Final[
    int
] = int(
    len(
        BATCH_STATIC_VISIBLE_BOOK_FEATURES
    )
)

STATIC_VISIBLE_BOOK_FEATURE_COUNT: Final[
    int
] = int(
    len(
        STATIC_VISIBLE_BOOK_FEATURE_REGISTRY
    )
)

AUTHORITATIVE_TICK_SIZE: Final[
    float
] = authoritative_implied_tick_size


# ------------------------------------------------------------
# Compact displays
# ------------------------------------------------------------

display(
    NOTEBOOK_05_INFORMATION_TIME_CONTRACT
)

display(
    STATIC_DEPTH_FAMILY_AUDIT
)

display(
    STATIC_BOOK_RECONCILIATION_AUDIT
)

display(
    STATIC_BOOK_ALGEBRAIC_REDUNDANCY_AUDIT
)

display(
    STATIC_VISIBLE_BOOK_FEATURE_REGISTRY[
        [
            "feature_name",
            "timing_class",
            "authority_class",
            "algebraic_redundancy_group",
        ]
    ]
)

display(
    STATIC_VISIBLE_BOOK_FEATURE_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "static_visible_book_features_verified": (
        STATIC_VISIBLE_BOOK_FEATURES_VERIFIED
    ),
    "observational_unit": (
        CANONICAL_OBSERVATIONAL_UNIT
    ),
    "timing_class": (
        TIMING_CLASS_T_MINUS
    ),
    "batch_rows": (
        STATIC_VISIBLE_BOOK_FEATURE_ROW_COUNT
    ),
    "static_feature_count": (
        STATIC_VISIBLE_BOOK_FEATURE_COUNT
    ),
    "authoritative_tick_size": (
        AUTHORITATIVE_TICK_SIZE
    ),
    "wide_spread_batch_count": int(
        wide_spread_batch_count
    ),
    "algebraic_redundancy_groups": int(
        STATIC_VISIBLE_BOOK_FEATURE_REGISTRY[
            "algebraic_redundancy_group"
        ].dropna().nunique()
    ),
    "same_batch_invariance_failures": int(
        static_same_batch_invariance_failure_count
    ),
    "nonfinite_feature_values": int(
        static_nonfinite_count
    ),
    "missing_feature_values": int(
        static_missing_feature_count
    ),
    "current_batch_fields_attached": False,
    "future_labels_attached": False,
    "verified_at_utc": utc_now_iso(),
}

,timing_class,physical_table_role,availability_rule,current_batch_information_allowed,same_batch_member_information_allowed,future_information_allowed,physical_separation_required,authorized_in_feature_table
0,T_MINUS,CAUSAL_MARKET_STATE_FEATURE,"Information must be causally available at or before the shared scoring-batch cutoff, subject to the frozen collector-sequence rule.",False,False,False,False,True
1,T_PLUS,POST_BATCH_DIAGNOSTIC,Information created by the current scoring batch becomes available only after all batch members have been scored.,True,True,False,True,False
2,DELAYED_ACTIVATION,DELAYED_MARK_ACTIVATION,A mark may enter historical state only for a later batch whose event_time_ns is strictly after the mark availability timestamp.,False,False,False,True,False
3,FUTURE_LABEL,SEPARATE_FUTURE_LABEL,The value is realized strictly after the scoring-batch time and may never be stored inside a market-state feature artifact.,False,False,True,True,False

   depth_level  minimum_bid_depth  minimum_ask_depth  minimum_imbalance  maximum_imbalance status
0            1            0.00009            0.00008          -0.999879           0.999760   PASS
1            3            0.00146            0.00034          -0.999744           0.999679   PASS
2            5            0.00172            0.00078          -0.999717           0.999708   PASS
3           10            0.00452            0.00294          -0.999406           0.999514   PASS

                                     field  row_count  mismatch_count  maximum_absolute_error status
0                                   spread      13564               0            5.238690e-12   PASS
1                      spread_basis_points      13564               0            8.209657e-13   PASS
2                                 midpoint      13564               0            7.275958e-12   PASS
3                               microprice      13564               0            2.182787e-11   PASS
4                microprice_minus_midpoint      13564               0            2.284109e-11   PASS
5                      top_level_imbalance      13564               0            4.440892e-16   PASS
6                 visible_bid_depth_top_10      13564               0            3.552714e-15   PASS
7                 visible_ask_depth_top_10      13564               0            3.552714e-15   PASS
8               visible_total_depth_top_10      13564               0            3.552714e-15   PASS
9                    multi_level_imbalance      13564               0            4.440892e-16   PASS
10       bid_l1_depth_concentration_top_10      13564               0            5.551115e-16   PASS
11       ask_l1_depth_concentration_top_10      13564               0            5.551115e-16   PASS
12  combined_l1_depth_concentration_top_10      13564               0            5.551115e-16   PASS

                       redundancy_group                     primary_components  derived_component          derived_displacement                                                             identity  row_count  failure_count status
0  LEVEL_ONE_WEIGHTED_MIDPOINT_IDENTITY  spread; midpoint; level_one_imbalance  weighted_midpoint  weighted_midpoint - midpoint  weighted_midpoint_displacement = 0.5 * spread * level_one_imbalance      13564              0   PASS

                                               feature_name timing_class                        authority_class            algebraic_redundancy_group
0                               tminus_book_bid_depth_top_1      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
1                               tminus_book_ask_depth_top_1      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
2                             tminus_book_total_depth_top_1      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
3                         tminus_book_depth_imbalance_top_1      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
4                         tminus_book_bid_depth_share_top_1      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
5                         tminus_book_ask_depth_share_top_1      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
6                               tminus_book_bid_depth_top_3      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
7                               tminus_book_ask_depth_top_3      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
8                             tminus_book_total_depth_top_3      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
9                         tminus_book_depth_imbalance_top_3      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
10                        tminus_book_bid_depth_share_top_3      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
11                        tminus_book_ask_depth_share_top_3      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
12                              tminus_book_bid_depth_top_5      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
13                              tminus_book_ask_depth_top_5      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
14                            tminus_book_total_depth_top_5      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
15                        tminus_book_depth_imbalance_top_5      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
16                        tminus_book_bid_depth_share_top_5      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
17                        tminus_book_ask_depth_share_top_5      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
18                             tminus_book_bid_depth_top_10      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
19                             tminus_book_ask_depth_top_10      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
20                           tminus_book_total_depth_top_10      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
21                       tminus_book_depth_imbalance_top_10      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
22                       tminus_book_bid_depth_share_top_10      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
23                       tminus_book_ask_depth_share_top_10      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
24                                     tminus_book_best_bid      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
25                                     tminus_book_best_ask      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
26                            tminus_book_best_bid_quantity      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
27                            tminus_book_best_ask_quantity      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
28                                       tminus_book_spread      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
29                                 tminus_book_spread_ticks      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
30                          tminus_book_spread_basis_points      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
31                                     tminus_book_midpoint      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
32                            tminus_book_weighted_midpoint      T_MINUS  AUTHORITATIVE_ALGEBRAICALLY_REDUNDANT  LEVEL_ONE_WEIGHTED_MIDPOINT_IDENTITY
33               tminus_book_weighted_midpoint_displacement      T_MINUS  AUTHORITATIVE_ALGEBRAICALLY_REDUNDANT  LEVEL_ONE_WEIGHTED_MIDPOINT_IDENTITY
34  tminus_book_weighted_midpoint_displacement_basis_points      T_MINUS  AUTHORITATIVE_ALGEBRAICALLY_REDUNDANT  LEVEL_ONE_WEIGHTED_MIDPOINT_IDENTITY
35                          tminus_book_level_one_imbalance      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
36                            tminus_book_implied_tick_size      T_MINUS             AUTHORITATIVE_VISIBLE_BOOK                                  None
37                             tminus_book_wide_spread_flag      T_MINUS                     DIAGNOSTIC_CONTROL                                  None
38                         tminus_book_bid_depth_hhi_top_10      T_MINUS                  DETERMINISTIC_DERIVED                                  None
39                         tminus_book_ask_depth_hhi_top_10      T_MINUS                  DETERMINISTIC_DERIVED                                  None
40                    tminus_book_combined_depth_hhi_top_10      T_MINUS                  DETERMINISTIC_DERIVED                                  None
41     tminus_book_bid_depth_weighted_distance_ticks_top_10      T_MINUS                  DETERMINISTIC_DERIVED                                  None
42     tminus_book_ask_depth_weighted_distance_ticks_top_10      T_MINUS                  DETERMINISTIC_DERIVED                                  None
43     tminus_book_depth_weighted_distance_asymmetry_top_10      T_MINUS                  DETERMINISTIC_DERIVED                                  None
44                   tminus_book_bid_gap_level_1_to_2_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
45                   tminus_book_ask_gap_level_1_to_2_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
46            tminus_book_bid_gap_level_1_to_2_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
47            tminus_book_ask_gap_level_1_to_2_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
48                   tminus_book_bid_gap_level_2_to_3_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
49                   tminus_book_ask_gap_level_2_to_3_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
50            tminus_book_bid_gap_level_2_to_3_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
51            tminus_book_ask_gap_level_2_to_3_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
52                   tminus_book_bid_gap_level_3_to_4_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
53                   tminus_book_ask_gap_level_3_to_4_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
54            tminus_book_bid_gap_level_3_to_4_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
55            tminus_book_ask_gap_level_3_to_4_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
56                   tminus_book_bid_gap_level_4_to_5_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
57                   tminus_book_ask_gap_level_4_to_5_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
58            tminus_book_bid_gap_level_4_to_5_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
59            tminus_book_ask_gap_level_4_to_5_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
60                   tminus_book_bid_gap_level_5_to_6_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
61                   tminus_book_ask_gap_level_5_to_6_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
62            tminus_book_bid_gap_level_5_to_6_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
63            tminus_book_ask_gap_level_5_to_6_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
64                   tminus_book_bid_gap_level_6_to_7_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
65                   tminus_book_ask_gap_level_6_to_7_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
66            tminus_book_bid_gap_level_6_to_7_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
67            tminus_book_ask_gap_level_6_to_7_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
68                   tminus_book_bid_gap_level_7_to_8_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
69                   tminus_book_ask_gap_level_7_to_8_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
70            tminus_book_bid_gap_level_7_to_8_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
71            tminus_book_ask_gap_level_7_to_8_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
72                   tminus_book_bid_gap_level_8_to_9_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
73                   tminus_book_ask_gap_level_8_to_9_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
74            tminus_book_bid_gap_level_8_to_9_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
75            tminus_book_ask_gap_level_8_to_9_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
76                  tminus_book_bid_gap_level_9_to_10_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
77                  tminus_book_ask_gap_level_9_to_10_ticks      T_MINUS                  DETERMINISTIC_DERIVED                                  None
78           tminus_book_bid_gap_level_9_to_10_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
79           tminus_book_ask_gap_level_9_to_10_basis_points      T_MINUS                  DETERMINISTIC_DERIVED                                  None
80            tminus_book_mean_bid_adjacent_gap_ticks_top_3      T_MINUS                  DETERMINISTIC_DERIVED                                  None
81            tminus_book_mean_ask_adjacent_gap_ticks_top_3      T_MINUS                  DETERMINISTIC_DERIVED                                  None
82            tminus_book_mean_bid_adjacent_gap_ticks_top_5      T_MINUS                  DETERMINISTIC_DERIVED                                  None
83            tminus_book_mean_ask_adjacent_gap_ticks_top_5      T_MINUS                  DETERMINISTIC_DERIVED                                  None
84           tminus_book_mean_bid_adjacent_gap_ticks_top_10      T_MINUS                  DETERMINISTIC_DERIVED                                  None
85           tminus_book_mean_ask_adjacent_gap_ticks_top_10      T_MINUS                  DETERMINISTIC_DERIVED                                  None

                                         gate  severity   status                                                                                                    evidence
0                 static_batch_rows_conserved  BLOCKING     PASS                                                                                                  rows=13564
1                static_batch_identity_unique  BLOCKING     PASS                                                                                        unique_batches=13564
2            notebook_02_field_reconciliation  BLOCKING     PASS                                                                                                   fields=13
3        weighted_midpoint_algebraic_identity  BLOCKING     PASS                                                                                                  failures=0
4                static_feature_finite_values  BLOCKING     PASS                                                                                                 nonfinite=0
5                  static_feature_missingness  BLOCKING     PASS                                                                                                   missing=0
6        static_feature_same_batch_invariance  BLOCKING     PASS                                                                                            failed_batches=0
7                     no_current_batch_fields  BLOCKING     PASS                                                                                         forbidden_columns=0
8                      no_future_label_fields  BLOCKING     PASS                                                                                       future_like_columns=0
9                    stable_implied_tick_size  BLOCKING     PASS                                                                                    tick_size=0.010000000002
10                 wide_spread_states_present   WARNING  WARNING                                                                                                     count=5
11  algebraically_redundant_features_retained   WARNING  WARNING  weighted midpoint and displacement are retained for transparency but registered as algebraically redundant

{'status': 'PASS',
 'static_visible_book_features_verified': True,
 'observational_unit': 'PRIMARY_SCORING_BATCH',
 'timing_class': 'T_MINUS',
 'batch_rows': 13564,
 'static_feature_count': 86,
 'authoritative_tick_size': 0.010000000002037268,
 'wide_spread_batch_count': 5,
 'algebraic_redundancy_groups': 1,
 'same_batch_invariance_failures': 0,
 'nonfinite_feature_values': 0,
 'missing_feature_values': 0,
 'current_batch_fields_attached': False,
 'future_labels_attached': False,
 'verified_at_utc': '2026-07-19T09:33:59.118148+00:00'}

In [9]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 10 — Frozen rolling-window grid and delayed aggregate-
#           mark activation ledger
# ============================================================


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "STATIC_VISIBLE_BOOK_FEATURES_VERIFIED",
        False,
    )
    is True,
    "Static visible-book features have not been verified.",
)

require(
    globals().get(
        "NOTEBOOK_04_AUTHORITY_VERIFIED",
        False,
    )
    is True,
    "Notebook 04 authority has not been verified.",
)

require(
    len(PRIMARY_ESTIMATION_EVENTS)
    == EXPECTED_PRIMARY_EVENT_ROWS,
    "Primary event count changed before activation construction.",
)

require(
    len(PRIMARY_SCORING_BATCHES)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    "Primary batch count changed before activation construction.",
)


# ------------------------------------------------------------
# Frozen rolling-window grids
#
# These windows are fixed before any future-label or predictive
# result is inspected.
# ------------------------------------------------------------

CLOCK_TIME_WINDOW_SPECS: Final[
    tuple[Mapping[str, Any], ...]
] = (
    MappingProxyType(
        {
            "window_name": "W250MS",
            "window_ns": 250_000_000,
            "window_seconds": 0.25,
            "justification": (
                "Short microstructure window above the "
                "dominant observed causal alignment-lag scale."
            ),
        }
    ),
    MappingProxyType(
        {
            "window_name": "W1S",
            "window_ns": 1_000_000_000,
            "window_seconds": 1.0,
            "justification": (
                "Near-term event, book-update, and price-state "
                "activity baseline."
            ),
        }
    ),
    MappingProxyType(
        {
            "window_name": "W5S",
            "window_ns": 5_000_000_000,
            "window_seconds": 5.0,
            "justification": (
                "Short clustering, order-flow, and realized-"
                "variation context."
            ),
        }
    ),
    MappingProxyType(
        {
            "window_name": "W30S",
            "window_ns": 30_000_000_000,
            "window_seconds": 30.0,
            "justification": (
                "Slower local market-state reference while "
                "remaining well inside the observed session."
            ),
        }
    ),
)

PRIOR_BATCH_COUNT_WINDOW_SPECS: Final[
    tuple[Mapping[str, Any], ...]
] = (
    MappingProxyType(
        {
            "window_name": "B10",
            "prior_batch_count": 10,
            "justification": (
                "Compact recent-batch state independent of "
                "short-term clock-time sparsity."
            ),
        }
    ),
    MappingProxyType(
        {
            "window_name": "B50",
            "prior_batch_count": 50,
            "justification": (
                "Longer prior-batch context for side balance, "
                "multiplicity, and run diagnostics."
            ),
        }
    ),
)


clock_window_rows: list[dict[str, Any]] = []

for specification in CLOCK_TIME_WINDOW_SPECS:
    clock_window_rows.append(
        {
            "window_name": specification[
                "window_name"
            ],
            "window_type": "CLOCK_TIME",
            "window_ns": int(
                specification[
                    "window_ns"
                ]
            ),
            "window_seconds": float(
                specification[
                    "window_seconds"
                ]
            ),
            "prior_batch_count": pd.NA,
            "timing_class": TIMING_CLASS_T_MINUS,
            "source_clock": "SOURCE_SPECIFIC_CAUSAL_CLOCK",
            "interval_convention": "[t-window, t)",
            "left_boundary_included": True,
            "right_boundary_included": False,
            "current_batch_included": False,
            "same_time_event_batch_included": False,
            "partition_boundary_rule": (
                "Earlier-partition causal history may carry "
                "forward; later-partition history is forbidden."
            ),
            "minimum_coverage_rule": (
                "Full requested duration is required for an "
                "authoritative rate, variance, or volatility "
                "value; partial coverage remains diagnostic."
            ),
            "minimum_observation_rule": (
                "Feature-specific; counts may be zero with "
                "full coverage, while changes require at least "
                "two source observations."
            ),
            "delayed_mark_rule": (
                "aggregate_mark_available_time_ns < "
                "current_batch_event_time_ns"
            ),
            "output_unit": "FEATURE_SPECIFIC",
            "valid_domain": "FEATURE_SPECIFIC",
            "selection_basis": "FROZEN_BEFORE_MODEL_RESULTS",
            "feature_selection_using_validation_allowed": False,
            "feature_selection_using_holdout_allowed": False,
            "justification": specification[
                "justification"
            ],
        }
    )


prior_batch_window_rows: list[dict[str, Any]] = []

for specification in (
    PRIOR_BATCH_COUNT_WINDOW_SPECS
):
    prior_batch_window_rows.append(
        {
            "window_name": specification[
                "window_name"
            ],
            "window_type": "PRIOR_BATCH_COUNT",
            "window_ns": pd.NA,
            "window_seconds": np.nan,
            "prior_batch_count": int(
                specification[
                    "prior_batch_count"
                ]
            ),
            "timing_class": TIMING_CLASS_T_MINUS,
            "source_clock": "PRIMARY_SCORING_BATCH_ORDER",
            "interval_convention": (
                "previous N completed scoring batches"
            ),
            "left_boundary_included": True,
            "right_boundary_included": False,
            "current_batch_included": False,
            "same_time_event_batch_included": False,
            "partition_boundary_rule": (
                "Earlier-partition causal batches may carry "
                "forward; no backward information flow."
            ),
            "minimum_coverage_rule": (
                "Exactly N prior completed batches are required "
                "for an authoritative prior-batch-window value."
            ),
            "minimum_observation_rule": (
                "Exactly the requested number of prior scoring "
                "batches."
            ),
            "delayed_mark_rule": (
                "Delayed aggregate marks are not defined by "
                "batch-count windows unless separately stated "
                "in the feature registry."
            ),
            "output_unit": "FEATURE_SPECIFIC",
            "valid_domain": "FEATURE_SPECIFIC",
            "selection_basis": "FROZEN_BEFORE_MODEL_RESULTS",
            "feature_selection_using_validation_allowed": False,
            "feature_selection_using_holdout_allowed": False,
            "justification": specification[
                "justification"
            ],
        }
    )


ROLLING_WINDOW_CONTRACT = pd.concat(
    [
        pd.DataFrame.from_records(
            clock_window_rows
        ),
        pd.DataFrame.from_records(
            prior_batch_window_rows
        ),
    ],
    ignore_index=True,
)

require_unique_columns(
    ROLLING_WINDOW_CONTRACT,
    "ROLLING_WINDOW_CONTRACT",
)

require(
    ROLLING_WINDOW_CONTRACT[
        "window_name"
    ].is_unique,
    "Rolling-window names are not unique.",
)

require(
    tuple(
        ROLLING_WINDOW_CONTRACT.loc[
            ROLLING_WINDOW_CONTRACT[
                "window_type"
            ].eq("CLOCK_TIME"),
            "window_name",
        ]
    )
    == (
        "W250MS",
        "W1S",
        "W5S",
        "W30S",
    ),
    "Clock-time window grid changed.",
)

require(
    tuple(
        ROLLING_WINDOW_CONTRACT.loc[
            ROLLING_WINDOW_CONTRACT[
                "window_type"
            ].eq("PRIOR_BATCH_COUNT"),
            "window_name",
        ]
    )
    == (
        "B10",
        "B50",
    ),
    "Prior-batch-count window grid changed.",
)

require(
    not ROLLING_WINDOW_CONTRACT[
        "current_batch_included"
    ].any(),
    "A rolling window includes the current batch.",
)

require(
    not ROLLING_WINDOW_CONTRACT[
        "same_time_event_batch_included"
    ].any(),
    "A rolling window includes same-time event history.",
)

require(
    not ROLLING_WINDOW_CONTRACT[
        "feature_selection_using_validation_allowed"
    ].any(),
    "A rolling definition permits validation-based selection.",
)

require(
    not ROLLING_WINDOW_CONTRACT[
        "feature_selection_using_holdout_allowed"
    ].any(),
    "A rolling definition permits holdout-based selection.",
)


CLOCK_TIME_WINDOWS_NS: Final[
    Mapping[str, int]
] = MappingProxyType(
    {
        str(row["window_name"]): int(
            row["window_ns"]
        )
        for row in clock_window_rows
    }
)

PRIOR_BATCH_COUNT_WINDOWS: Final[
    Mapping[str, int]
] = MappingProxyType(
    {
        str(row["window_name"]): int(
            row["prior_batch_count"]
        )
        for row in prior_batch_window_rows
    }
)


# ------------------------------------------------------------
# Prepare authoritative event-level mark source
# ------------------------------------------------------------

DELAYED_MARK_EVENT_SOURCE_COLUMNS: Final[
    tuple[str, ...]
] = (
    "primary_event_id",
    "primary_event_number",
    "primary_event_batch_id",
    "primary_event_batch_number",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
    "event_side",
    "event_side_code",
    "event_print_count",
    "event_quantity",
    "event_notional",
    "aggregate_mark_available_time_ns",
    "aggregate_mark_available_at_initiation_flag",
    "aggregate_mark_lag_after_event_ns",
)

require_columns(
    PRIMARY_ESTIMATION_EVENTS,
    DELAYED_MARK_EVENT_SOURCE_COLUMNS,
    "PRIMARY_ESTIMATION_EVENTS",
)

DELAYED_MARK_EVENT_SOURCE = (
    PRIMARY_ESTIMATION_EVENTS[
        list(
            DELAYED_MARK_EVENT_SOURCE_COLUMNS
        )
    ]
    .copy()
    .sort_values(
        "primary_event_number",
        kind="stable",
    )
    .reset_index(drop=True)
)

DELAYED_MARK_EVENT_SOURCE[
    "primary_event_number"
] = parse_required_int64(
    DELAYED_MARK_EVENT_SOURCE[
        "primary_event_number"
    ],
    (
        "DELAYED_MARK_EVENT_SOURCE."
        "primary_event_number"
    ),
)

DELAYED_MARK_EVENT_SOURCE[
    "primary_event_batch_number"
] = parse_required_int64(
    DELAYED_MARK_EVENT_SOURCE[
        "primary_event_batch_number"
    ],
    (
        "DELAYED_MARK_EVENT_SOURCE."
        "primary_event_batch_number"
    ),
)

DELAYED_MARK_EVENT_SOURCE[
    "event_partition_order"
] = parse_required_int64(
    DELAYED_MARK_EVENT_SOURCE[
        "event_partition_order"
    ],
    (
        "DELAYED_MARK_EVENT_SOURCE."
        "event_partition_order"
    ),
)

DELAYED_MARK_EVENT_SOURCE[
    "event_time_ns"
] = parse_required_int64(
    DELAYED_MARK_EVENT_SOURCE[
        "event_time_ns"
    ],
    "DELAYED_MARK_EVENT_SOURCE.event_time_ns",
)

DELAYED_MARK_EVENT_SOURCE[
    "event_print_count"
] = parse_required_int64(
    DELAYED_MARK_EVENT_SOURCE[
        "event_print_count"
    ],
    (
        "DELAYED_MARK_EVENT_SOURCE."
        "event_print_count"
    ),
)

DELAYED_MARK_EVENT_SOURCE[
    "event_quantity"
] = parse_required_float64(
    DELAYED_MARK_EVENT_SOURCE[
        "event_quantity"
    ],
    "DELAYED_MARK_EVENT_SOURCE.event_quantity",
)

DELAYED_MARK_EVENT_SOURCE[
    "event_notional"
] = parse_required_float64(
    DELAYED_MARK_EVENT_SOURCE[
        "event_notional"
    ],
    "DELAYED_MARK_EVENT_SOURCE.event_notional",
)

DELAYED_MARK_EVENT_SOURCE[
    "aggregate_mark_available_time_ns"
] = parse_required_int64(
    DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_available_time_ns"
    ],
    (
        "DELAYED_MARK_EVENT_SOURCE."
        "aggregate_mark_available_time_ns"
    ),
)

DELAYED_MARK_EVENT_SOURCE[
    "aggregate_mark_lag_after_event_ns"
] = parse_required_int64(
    DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_lag_after_event_ns"
    ],
    (
        "DELAYED_MARK_EVENT_SOURCE."
        "aggregate_mark_lag_after_event_ns"
    ),
)

DELAYED_MARK_EVENT_SOURCE[
    "aggregate_mark_available_at_initiation_flag"
] = (
    strict_boolean_series(
        DELAYED_MARK_EVENT_SOURCE[
            "aggregate_mark_available_at_initiation_flag"
        ],
        field_name=(
            "DELAYED_MARK_EVENT_SOURCE."
            "aggregate_mark_available_at_initiation_flag"
        ),
    )
)

DELAYED_MARK_EVENT_SOURCE[
    "event_partition"
] = (
    DELAYED_MARK_EVENT_SOURCE[
        "event_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

DELAYED_MARK_EVENT_SOURCE[
    "event_side"
] = (
    DELAYED_MARK_EVENT_SOURCE[
        "event_side"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

DELAYED_MARK_EVENT_SOURCE[
    "derived_event_vwap"
] = (
    DELAYED_MARK_EVENT_SOURCE[
        "event_notional"
    ]
    / DELAYED_MARK_EVENT_SOURCE[
        "event_quantity"
    ]
)

require(
    len(DELAYED_MARK_EVENT_SOURCE)
    == EXPECTED_PRIMARY_EVENT_ROWS,
    "Delayed-mark event source changed the event count.",
)

require(
    DELAYED_MARK_EVENT_SOURCE[
        "primary_event_id"
    ].is_unique,
    "Delayed-mark event source contains duplicate event IDs.",
)

require(
    DELAYED_MARK_EVENT_SOURCE[
        "event_print_count"
    ].ge(1).all(),
    "An event mark source has no constituent trade prints.",
)

require(
    DELAYED_MARK_EVENT_SOURCE[
        "event_quantity"
    ].gt(0).all(),
    "An event mark source has non-positive quantity.",
)

require(
    DELAYED_MARK_EVENT_SOURCE[
        "event_notional"
    ].gt(0).all(),
    "An event mark source has non-positive notional.",
)

require(
    np.isfinite(
        DELAYED_MARK_EVENT_SOURCE[
            "derived_event_vwap"
        ].to_numpy(
            dtype="float64"
        )
    ).all(),
    "Derived event VWAP contains a non-finite value.",
)

require(
    DELAYED_MARK_EVENT_SOURCE[
        "derived_event_vwap"
    ].gt(0).all(),
    "Derived event VWAP contains a non-positive value.",
)

require(
    DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_available_time_ns"
    ].ge(
        DELAYED_MARK_EVENT_SOURCE[
            "event_time_ns"
        ]
    ).all(),
    "At least one aggregate mark is backdated.",
)

require(
    DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_lag_after_event_ns"
    ].equals(
        DELAYED_MARK_EVENT_SOURCE[
            "aggregate_mark_available_time_ns"
        ]
        - DELAYED_MARK_EVENT_SOURCE[
            "event_time_ns"
        ]
    ),
    "Aggregate-mark lag arithmetic changed.",
)


# ------------------------------------------------------------
# Map each mark availability timestamp to the frozen Notebook
# 00 chronological split contract
# ------------------------------------------------------------

split_boundaries_by_order = (
    SPLIT_BOUNDARY_TABLE.sort_values(
        "partition_order",
        kind="stable",
    )
    .reset_index(drop=True)
)

split_start_ns_array = (
    split_boundaries_by_order[
        "receipt_time_start_ns"
    ]
    .astype("int64")
    .to_numpy()
)

split_end_ns_array = (
    split_boundaries_by_order[
        "receipt_time_end_ns_exclusive"
    ]
    .astype("int64")
    .to_numpy()
)

split_partition_array = (
    split_boundaries_by_order[
        "partition"
    ]
    .astype(str)
    .to_numpy()
)

split_partition_order_array = (
    split_boundaries_by_order[
        "partition_order"
    ]
    .astype("int64")
    .to_numpy()
)

availability_time_array = (
    DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_available_time_ns"
    ]
    .astype("int64")
    .to_numpy()
)

availability_partition_positions = (
    np.searchsorted(
        split_end_ns_array,
        availability_time_array,
        side="right",
    )
)

availability_inside_split_contract = (
    availability_partition_positions
    < len(split_partition_array)
)

valid_availability_positions = np.flatnonzero(
    availability_inside_split_contract
)

if len(valid_availability_positions) > 0:
    valid_partition_positions = (
        availability_partition_positions[
            valid_availability_positions
        ]
    )

    availability_inside_split_contract[
        valid_availability_positions
    ] &= (
        availability_time_array[
            valid_availability_positions
        ]
        >= split_start_ns_array[
            valid_partition_positions
        ]
    )

require(
    availability_inside_split_contract.all(),
    (
        "At least one aggregate-mark availability timestamp "
        "falls outside the Notebook 00 split contract."
    ),
)

availability_partition_values = (
    split_partition_array[
        availability_partition_positions
    ]
)

availability_partition_order_values = (
    split_partition_order_array[
        availability_partition_positions
    ]
)

DELAYED_MARK_EVENT_SOURCE[
    "aggregate_mark_availability_partition"
] = pd.Series(
    availability_partition_values,
    dtype="string",
)

DELAYED_MARK_EVENT_SOURCE[
    "aggregate_mark_availability_partition_order"
] = pd.Series(
    availability_partition_order_values,
    dtype="int64",
)

DELAYED_MARK_EVENT_SOURCE[
    "availability_inside_split_contract_flag"
] = (
    availability_inside_split_contract
)

DELAYED_MARK_EVENT_SOURCE[
    "availability_crosses_source_partition_flag"
] = (
    DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_availability_partition_order"
    ].gt(
        DELAYED_MARK_EVENT_SOURCE[
            "event_partition_order"
        ]
    )
)

DELAYED_MARK_EVENT_SOURCE[
    "availability_precedes_source_partition_flag"
] = (
    DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_availability_partition_order"
    ].lt(
        DELAYED_MARK_EVENT_SOURCE[
            "event_partition_order"
        ]
    )
)

require(
    not DELAYED_MARK_EVENT_SOURCE[
        "availability_precedes_source_partition_flag"
    ].any(),
    (
        "An aggregate mark becomes available in a partition "
        "earlier than its source event."
    ),
)


# ------------------------------------------------------------
# Resolve the earliest eligible future scoring batch
#
# Eligibility is strict:
#
#   earliest_future_batch_time
#       > aggregate_mark_available_time_ns
#
# Equality is never sufficient.
# ------------------------------------------------------------

ACTIVATION_BATCH_SPINE = (
    PRIMARY_SCORING_BATCHES[
        [
            "primary_event_batch_id",
            "primary_event_batch_number",
            "event_partition_order",
            "event_partition",
            "event_time_ns",
        ]
    ]
    .copy()
    .sort_values(
        [
            "event_time_ns",
            "primary_event_batch_number",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

ACTIVATION_BATCH_SPINE[
    "primary_event_batch_number"
] = parse_required_int64(
    ACTIVATION_BATCH_SPINE[
        "primary_event_batch_number"
    ],
    (
        "ACTIVATION_BATCH_SPINE."
        "primary_event_batch_number"
    ),
)

ACTIVATION_BATCH_SPINE[
    "event_partition_order"
] = parse_required_int64(
    ACTIVATION_BATCH_SPINE[
        "event_partition_order"
    ],
    (
        "ACTIVATION_BATCH_SPINE."
        "event_partition_order"
    ),
)

ACTIVATION_BATCH_SPINE[
    "event_time_ns"
] = parse_required_int64(
    ACTIVATION_BATCH_SPINE[
        "event_time_ns"
    ],
    "ACTIVATION_BATCH_SPINE.event_time_ns",
)

ACTIVATION_BATCH_SPINE[
    "event_partition"
] = (
    ACTIVATION_BATCH_SPINE[
        "event_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

require(
    ACTIVATION_BATCH_SPINE[
        "event_time_ns"
    ].is_monotonic_increasing,
    "Activation batch times are not non-decreasing.",
)

activation_batch_time_array = (
    ACTIVATION_BATCH_SPINE[
        "event_time_ns"
    ]
    .astype("int64")
    .to_numpy()
)

earliest_eligible_batch_positions = (
    np.searchsorted(
        activation_batch_time_array,
        availability_time_array,
        side="right",
    )
)

has_observed_future_batch = (
    earliest_eligible_batch_positions
    < len(ACTIVATION_BATCH_SPINE)
)

earliest_batch_id = pd.Series(
    pd.NA,
    index=DELAYED_MARK_EVENT_SOURCE.index,
    dtype="string",
)

earliest_batch_number = pd.Series(
    pd.NA,
    index=DELAYED_MARK_EVENT_SOURCE.index,
    dtype="Int64",
)

earliest_batch_partition = pd.Series(
    pd.NA,
    index=DELAYED_MARK_EVENT_SOURCE.index,
    dtype="string",
)

earliest_batch_partition_order = pd.Series(
    pd.NA,
    index=DELAYED_MARK_EVENT_SOURCE.index,
    dtype="Int64",
)

earliest_batch_time_ns = pd.Series(
    pd.NA,
    index=DELAYED_MARK_EVENT_SOURCE.index,
    dtype="Int64",
)

future_event_indices = np.flatnonzero(
    has_observed_future_batch
)

if len(future_event_indices) > 0:
    future_batch_positions = (
        earliest_eligible_batch_positions[
            future_event_indices
        ]
    )

    earliest_batch_id.iloc[
        future_event_indices
    ] = (
        ACTIVATION_BATCH_SPINE.iloc[
            future_batch_positions
        ][
            "primary_event_batch_id"
        ]
        .astype("string")
        .to_numpy()
    )

    earliest_batch_number.iloc[
        future_event_indices
    ] = (
        ACTIVATION_BATCH_SPINE.iloc[
            future_batch_positions
        ][
            "primary_event_batch_number"
        ]
        .astype("int64")
        .to_numpy()
    )

    earliest_batch_partition.iloc[
        future_event_indices
    ] = (
        ACTIVATION_BATCH_SPINE.iloc[
            future_batch_positions
        ][
            "event_partition"
        ]
        .astype("string")
        .to_numpy()
    )

    earliest_batch_partition_order.iloc[
        future_event_indices
    ] = (
        ACTIVATION_BATCH_SPINE.iloc[
            future_batch_positions
        ][
            "event_partition_order"
        ]
        .astype("int64")
        .to_numpy()
    )

    earliest_batch_time_ns.iloc[
        future_event_indices
    ] = (
        ACTIVATION_BATCH_SPINE.iloc[
            future_batch_positions
        ][
            "event_time_ns"
        ]
        .astype("int64")
        .to_numpy()
    )


DELAYED_MARK_EVENT_SOURCE[
    "earliest_eligible_future_batch_position"
] = pd.Series(
    earliest_eligible_batch_positions,
    dtype="int64",
)

DELAYED_MARK_EVENT_SOURCE[
    "has_observed_eligible_future_batch_flag"
] = (
    has_observed_future_batch
)

DELAYED_MARK_EVENT_SOURCE[
    "earliest_eligible_future_batch_id"
] = earliest_batch_id

DELAYED_MARK_EVENT_SOURCE[
    "earliest_eligible_future_batch_number"
] = earliest_batch_number

DELAYED_MARK_EVENT_SOURCE[
    "earliest_eligible_future_batch_partition"
] = earliest_batch_partition

DELAYED_MARK_EVENT_SOURCE[
    "earliest_eligible_future_batch_partition_order"
] = earliest_batch_partition_order

DELAYED_MARK_EVENT_SOURCE[
    "earliest_eligible_future_batch_time_ns"
] = earliest_batch_time_ns

DELAYED_MARK_EVENT_SOURCE[
    "activation_delay_to_earliest_batch_ns"
] = (
    earliest_batch_time_ns
    - DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_available_time_ns"
    ].astype("Int64")
)

DELAYED_MARK_EVENT_SOURCE[
    "activation_crosses_source_partition_flag"
] = (
    earliest_batch_partition_order
    > DELAYED_MARK_EVENT_SOURCE[
        "event_partition_order"
    ].astype("Int64")
)

DELAYED_MARK_EVENT_SOURCE[
    "activation_crosses_availability_partition_flag"
] = (
    earliest_batch_partition_order
    > DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_availability_partition_order"
    ].astype("Int64")
)

DELAYED_MARK_EVENT_SOURCE[
    "current_source_batch_is_eligible_flag"
] = (
    earliest_batch_id
    == DELAYED_MARK_EVENT_SOURCE[
        "primary_event_batch_id"
    ].astype("string")
)

DELAYED_MARK_EVENT_SOURCE[
    "equal_availability_time_activation_flag"
] = (
    earliest_batch_time_ns
    == DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_available_time_ns"
    ].astype("Int64")
)

DELAYED_MARK_EVENT_SOURCE[
    "activation_status"
] = np.where(
    has_observed_future_batch,
    "ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID",
    "NO_LATER_SCORING_BATCH_OBSERVED",
)


# ------------------------------------------------------------
# Verify strict activation timing
# ------------------------------------------------------------

observed_future_event_mask = (
    DELAYED_MARK_EVENT_SOURCE[
        "has_observed_eligible_future_batch_flag"
    ].astype(bool)
)

require(
    not DELAYED_MARK_EVENT_SOURCE[
        "current_source_batch_is_eligible_flag"
    ].fillna(False).astype(bool).any(),
    (
        "A delayed aggregate mark is incorrectly eligible "
        "for its own source batch."
    ),
)

require(
    not DELAYED_MARK_EVENT_SOURCE[
        "equal_availability_time_activation_flag"
    ].fillna(False).astype(bool).any(),
    (
        "A mark is incorrectly activated at a batch with an "
        "equal timestamp."
    ),
)

require(
    (
        DELAYED_MARK_EVENT_SOURCE.loc[
            observed_future_event_mask,
            "earliest_eligible_future_batch_time_ns",
        ].astype("int64")
        > DELAYED_MARK_EVENT_SOURCE.loc[
            observed_future_event_mask,
            "aggregate_mark_available_time_ns",
        ].astype("int64")
    ).all(),
    (
        "An observed earliest eligible batch is not strictly "
        "later than mark availability."
    ),
)

require(
    (
        DELAYED_MARK_EVENT_SOURCE.loc[
            observed_future_event_mask,
            "earliest_eligible_future_batch_number",
        ].astype("int64")
        > DELAYED_MARK_EVENT_SOURCE.loc[
            observed_future_event_mask,
            "primary_event_batch_number",
        ].astype("int64")
    ).all(),
    (
        "An aggregate mark activates in its source batch or "
        "an earlier batch."
    ),
)

require(
    (
        DELAYED_MARK_EVENT_SOURCE.loc[
            observed_future_event_mask,
            "activation_delay_to_earliest_batch_ns",
        ].astype("int64")
        > 0
    ).all(),
    (
        "An aggregate mark has a non-positive delay to its "
        "earliest eligible scoring batch."
    ),
)


# ------------------------------------------------------------
# Verify searchsorted minimality:
#
# the immediately previous batch, when it exists, must have
# event_time_ns <= availability_time_ns.
# ------------------------------------------------------------

previous_batch_positions = (
    earliest_eligible_batch_positions - 1
)

has_previous_batch = (
    previous_batch_positions >= 0
)

previous_batch_time_ns = pd.Series(
    pd.NA,
    index=DELAYED_MARK_EVENT_SOURCE.index,
    dtype="Int64",
)

previous_event_indices = np.flatnonzero(
    has_previous_batch
)

if len(previous_event_indices) > 0:
    previous_positions = (
        previous_batch_positions[
            previous_event_indices
        ]
    )

    previous_batch_time_ns.iloc[
        previous_event_indices
    ] = activation_batch_time_array[
        previous_positions
    ]

DELAYED_MARK_EVENT_SOURCE[
    "previous_batch_time_before_activation_ns"
] = previous_batch_time_ns

require(
    (
        previous_batch_time_ns.loc[
            has_previous_batch
        ].astype("int64")
        <= DELAYED_MARK_EVENT_SOURCE.loc[
            has_previous_batch,
            "aggregate_mark_available_time_ns",
        ].astype("int64")
    ).all(),
    (
        "Earliest eligible activation-batch search skipped an "
        "earlier strictly eligible scoring batch."
    ),
)


# ------------------------------------------------------------
# Expand to one row per event and aggregate-mark type
# ------------------------------------------------------------

DELAYED_AGGREGATE_MARK_SPECS: Final[
    tuple[Mapping[str, Any], ...]
] = (
    MappingProxyType(
        {
            "mark_type": "AGGREGATE_QUANTITY",
            "source_field": "event_quantity",
            "mark_unit": "BTC",
            "integer_valued": False,
            "derived": False,
            "source_fields": "event_quantity",
        }
    ),
    MappingProxyType(
        {
            "mark_type": "AGGREGATE_NOTIONAL",
            "source_field": "event_notional",
            "mark_unit": "USDT",
            "integer_valued": False,
            "derived": False,
            "source_fields": "event_notional",
        }
    ),
    MappingProxyType(
        {
            "mark_type": "AGGREGATE_PRINT_COUNT",
            "source_field": "event_print_count",
            "mark_unit": "TRADE_PRINTS",
            "integer_valued": True,
            "derived": False,
            "source_fields": "event_print_count",
        }
    ),
    MappingProxyType(
        {
            "mark_type": "AGGREGATE_VWAP",
            "source_field": "derived_event_vwap",
            "mark_unit": "USDT_PER_BTC",
            "integer_valued": False,
            "derived": True,
            "source_fields": (
                "event_notional / event_quantity"
            ),
        }
    ),
)


activation_ledger_frames: list[
    pd.DataFrame
] = []

for mark_specification in (
    DELAYED_AGGREGATE_MARK_SPECS
):
    mark_frame = (
        DELAYED_MARK_EVENT_SOURCE.copy()
    )

    mark_frame[
        "mark_type"
    ] = mark_specification[
        "mark_type"
    ]

    mark_frame[
        "mark_source_field"
    ] = mark_specification[
        "source_field"
    ]

    mark_frame[
        "mark_source_fields"
    ] = mark_specification[
        "source_fields"
    ]

    mark_frame[
        "mark_unit"
    ] = mark_specification[
        "mark_unit"
    ]

    mark_frame[
        "mark_integer_valued_flag"
    ] = bool(
        mark_specification[
            "integer_valued"
        ]
    )

    mark_frame[
        "mark_derived_flag"
    ] = bool(
        mark_specification[
            "derived"
        ]
    )

    mark_frame[
        "mark_value"
    ] = pd.to_numeric(
        mark_frame[
            mark_specification[
                "source_field"
            ]
        ],
        errors="raise",
    ).astype("float64")

    mark_frame[
        "mark_value_int64"
    ] = pd.Series(
        pd.NA,
        index=mark_frame.index,
        dtype="Int64",
    )

    if bool(
        mark_specification[
            "integer_valued"
        ]
    ):
        integer_mark_values = (
            mark_frame[
                "mark_value"
            ]
        )

        require(
            integer_mark_values.eq(
                np.floor(
                    integer_mark_values
                )
            ).all(),
            (
                f"{mark_specification['mark_type']} contains "
                "a non-integral value."
            ),
        )

        mark_frame[
            "mark_value_int64"
        ] = (
            integer_mark_values.astype(
                "int64"
            )
        )

    mark_frame[
        "activation_ledger_id"
    ] = (
        mark_frame[
            "primary_event_id"
        ].astype("string")
        + "__MARK__"
        + str(
            mark_specification[
                "mark_type"
            ]
        )
    )

    mark_frame[
        "timing_class"
    ] = TIMING_CLASS_DELAYED_ACTIVATION

    mark_frame[
        "current_batch_eligible_flag"
    ] = False

    mark_frame[
        "equal_timestamp_eligible_flag"
    ] = False

    mark_frame[
        "activation_rule"
    ] = (
        "earliest scoring batch satisfying "
        "event_time_ns > aggregate_mark_available_time_ns"
    )

    activation_ledger_frames.append(
        mark_frame
    )


DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER = (
    pd.concat(
        activation_ledger_frames,
        ignore_index=True,
    )
    .sort_values(
        [
            "primary_event_number",
            "mark_type",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

require_unique_columns(
    DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER,
    "DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER",
)

EXPECTED_ACTIVATION_LEDGER_ROWS: Final[int] = (
    EXPECTED_PRIMARY_EVENT_ROWS
    * len(
        DELAYED_AGGREGATE_MARK_SPECS
    )
)

require(
    len(
        DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER
    )
    == EXPECTED_ACTIVATION_LEDGER_ROWS,
    (
        "Delayed aggregate-mark activation ledger row-count "
        "mismatch:\n"
        f"expected={EXPECTED_ACTIVATION_LEDGER_ROWS:,}\n"
        f"observed="
        f"{len(DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER):,}"
    ),
)

require(
    DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER[
        "activation_ledger_id"
    ].is_unique,
    "Activation-ledger identities are not unique.",
)

require(
    DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER[
        "mark_value"
    ].gt(0).all(),
    "An aggregate-mark value is non-positive.",
)

require(
    np.isfinite(
        DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER[
            "mark_value"
        ].to_numpy(
            dtype="float64"
        )
    ).all(),
    "An aggregate-mark value is non-finite.",
)

require(
    DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER[
        "timing_class"
    ].eq(
        TIMING_CLASS_DELAYED_ACTIVATION
    ).all(),
    "An activation-ledger row has the wrong timing class.",
)

require(
    not DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER[
        "current_batch_eligible_flag"
    ].any(),
    "An activation-ledger mark is eligible in its source batch.",
)

require(
    not DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER[
        "equal_timestamp_eligible_flag"
    ].any(),
    "An activation-ledger mark permits equal-time activation.",
)


# ------------------------------------------------------------
# One event must have exactly one row for every frozen mark type
# ------------------------------------------------------------

event_mark_type_counts = (
    DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER.groupby(
        "primary_event_id",
        observed=True,
        sort=False,
        dropna=False,
    )[
        "mark_type"
    ]
    .nunique()
)

require(
    event_mark_type_counts.eq(
        len(
            DELAYED_AGGREGATE_MARK_SPECS
        )
    ).all(),
    (
        "At least one primary event lacks a required aggregate "
        "mark type or contains a duplicate mark type."
    ),
)

observed_mark_type_set = set(
    DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER[
        "mark_type"
    ].astype(str).unique()
)

expected_mark_type_set = {
    str(
        specification[
            "mark_type"
        ]
    )
    for specification in (
        DELAYED_AGGREGATE_MARK_SPECS
    )
}

require(
    observed_mark_type_set
    == expected_mark_type_set,
    "Activation-ledger mark-type domain changed.",
)


# ------------------------------------------------------------
# Event-level activation summary
# ------------------------------------------------------------

DELAYED_MARK_EVENT_ACTIVATION_SUMMARY = (
    DELAYED_MARK_EVENT_SOURCE.copy()
)

require(
    len(
        DELAYED_MARK_EVENT_ACTIVATION_SUMMARY
    )
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Delayed-mark event activation summary changed the "
        "event count."
    ),
)

require(
    DELAYED_MARK_EVENT_ACTIVATION_SUMMARY[
        "primary_event_id"
    ].is_unique,
    (
        "Delayed-mark event activation summary contains "
        "duplicate event IDs."
    ),
)


# ------------------------------------------------------------
# Activation audits
# ------------------------------------------------------------

delayed_event_count = int(
    DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_lag_after_event_ns"
    ].gt(0).sum()
)

immediate_event_count = int(
    DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_lag_after_event_ns"
    ].eq(0).sum()
)

events_without_later_batch_count = int(
    (
        ~DELAYED_MARK_EVENT_SOURCE[
            "has_observed_eligible_future_batch_flag"
        ].astype(bool)
    ).sum()
)

availability_cross_partition_event_count = int(
    DELAYED_MARK_EVENT_SOURCE[
        "availability_crosses_source_partition_flag"
    ].astype(bool).sum()
)

activation_cross_partition_event_count = int(
    DELAYED_MARK_EVENT_SOURCE[
        "activation_crosses_source_partition_flag"
    ].fillna(False).astype(bool).sum()
)

activation_cross_availability_partition_event_count = int(
    DELAYED_MARK_EVENT_SOURCE[
        "activation_crosses_availability_partition_flag"
    ].fillna(False).astype(bool).sum()
)

equal_time_activation_violation_count = int(
    DELAYED_MARK_EVENT_SOURCE[
        "equal_availability_time_activation_flag"
    ].fillna(False).astype(bool).sum()
)

current_batch_activation_violation_count = int(
    DELAYED_MARK_EVENT_SOURCE[
        "current_source_batch_is_eligible_flag"
    ].fillna(False).astype(bool).sum()
)

backdated_event_count = int(
    DELAYED_MARK_EVENT_SOURCE[
        "aggregate_mark_available_time_ns"
    ].lt(
        DELAYED_MARK_EVENT_SOURCE[
            "event_time_ns"
        ]
    ).sum()
)

require(
    delayed_event_count
    == EXPECTED_DELAYED_AGGREGATE_EVENT_COUNT,
    (
        "Delayed aggregate-mark event count differs from "
        "Notebook 04 authority."
    ),
)

require(
    immediate_event_count
    + delayed_event_count
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Immediate and delayed aggregate-mark events do not "
        "conserve the primary event population."
    ),
)

require(
    backdated_event_count == 0,
    "The activation ledger contains a backdated event mark.",
)

require(
    equal_time_activation_violation_count == 0,
    "The activation ledger permits equal-time activation.",
)

require(
    current_batch_activation_violation_count == 0,
    "The activation ledger permits current-batch activation.",
)


MARK_TYPE_ACTIVATION_AUDIT = (
    DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER.groupby(
        [
            "mark_type",
            "mark_unit",
            "mark_integer_valued_flag",
            "mark_derived_flag",
        ],
        observed=True,
        sort=True,
        dropna=False,
    )
    .agg(
        ledger_row_count=(
            "activation_ledger_id",
            "size",
        ),
        unique_event_count=(
            "primary_event_id",
            "nunique",
        ),
        minimum_mark_value=(
            "mark_value",
            "min",
        ),
        maximum_mark_value=(
            "mark_value",
            "max",
        ),
        delayed_event_count=(
            "aggregate_mark_lag_after_event_ns",
            lambda values: int(
                values.gt(0).sum()
            ),
        ),
        no_later_batch_count=(
            "has_observed_eligible_future_batch_flag",
            lambda values: int(
                (~values.astype(bool)).sum()
            ),
        ),
    )
    .reset_index()
)

require(
    MARK_TYPE_ACTIVATION_AUDIT[
        "ledger_row_count"
    ].eq(
        EXPECTED_PRIMARY_EVENT_ROWS
    ).all(),
    (
        "A mark type does not contain exactly one row per "
        "primary event."
    ),
)

require(
    MARK_TYPE_ACTIVATION_AUDIT[
        "unique_event_count"
    ].eq(
        EXPECTED_PRIMARY_EVENT_ROWS
    ).all(),
    (
        "A mark type does not cover every primary-event ID."
    ),
)


# ------------------------------------------------------------
# Partition-level activation summary
# ------------------------------------------------------------

ACTIVATION_PARTITION_SUMMARY = (
    DELAYED_MARK_EVENT_SOURCE.groupby(
        [
            "event_partition_order",
            "event_partition",
        ],
        observed=True,
        sort=True,
        dropna=False,
    )
    .agg(
        source_event_count=(
            "primary_event_id",
            "size",
        ),
        immediate_at_initiation_count=(
            "aggregate_mark_lag_after_event_ns",
            lambda values: int(
                values.eq(0).sum()
            ),
        ),
        delayed_after_initiation_count=(
            "aggregate_mark_lag_after_event_ns",
            lambda values: int(
                values.gt(0).sum()
            ),
        ),
        availability_cross_partition_count=(
            "availability_crosses_source_partition_flag",
            "sum",
        ),
        activation_cross_partition_count=(
            "activation_crosses_source_partition_flag",
            lambda values: int(
                values.fillna(False)
                .astype(bool)
                .sum()
            ),
        ),
        no_later_batch_count=(
            "has_observed_eligible_future_batch_flag",
            lambda values: int(
                (~values.astype(bool)).sum()
            ),
        ),
        minimum_mark_lag_ns=(
            "aggregate_mark_lag_after_event_ns",
            "min",
        ),
        median_mark_lag_ns=(
            "aggregate_mark_lag_after_event_ns",
            "median",
        ),
        maximum_mark_lag_ns=(
            "aggregate_mark_lag_after_event_ns",
            "max",
        ),
    )
    .reset_index()
)


# ------------------------------------------------------------
# Leakage-facing ledger field audit
# ------------------------------------------------------------

required_activation_ledger_fields = {
    "activation_ledger_id",
    "primary_event_id",
    "primary_event_batch_id",
    "event_partition",
    "event_time_ns",
    "aggregate_mark_available_time_ns",
    "mark_type",
    "mark_value",
    "mark_unit",
    "earliest_eligible_future_batch_id",
    "earliest_eligible_future_batch_time_ns",
    "activation_status",
    "timing_class",
    "activation_rule",
}

missing_activation_ledger_fields = sorted(
    required_activation_ledger_fields
    - set(
        DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER.columns
    )
)

require(
    not missing_activation_ledger_fields,
    (
        "Activation ledger is missing required fields: "
        f"{missing_activation_ledger_fields}"
    ),
)

future_label_like_activation_columns = sorted(
    column_name
    for column_name in (
        DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER.columns
    )
    if (
        column_name.startswith(
            "future_label_"
        )
        or column_name.startswith(
            "target_outcome_"
        )
    )
)

require(
    not future_label_like_activation_columns,
    (
        "Activation ledger contains future-label fields: "
        f"{future_label_like_activation_columns}"
    ),
)


# ------------------------------------------------------------
# Gate table
# ------------------------------------------------------------

ROLLING_AND_ACTIVATION_GATES = pd.DataFrame(
    [
        {
            "gate": "rolling_clock_window_grid_frozen",
            "severity": "BLOCKING",
            "passed": (
                len(
                    CLOCK_TIME_WINDOWS_NS
                )
                == 4
            ),
            "evidence": str(
                dict(
                    CLOCK_TIME_WINDOWS_NS
                )
            ),
        },
        {
            "gate": "prior_batch_window_grid_frozen",
            "severity": "BLOCKING",
            "passed": (
                len(
                    PRIOR_BATCH_COUNT_WINDOWS
                )
                == 2
            ),
            "evidence": str(
                dict(
                    PRIOR_BATCH_COUNT_WINDOWS
                )
            ),
        },
        {
            "gate": "current_batch_excluded_from_windows",
            "severity": "BLOCKING",
            "passed": (
                not ROLLING_WINDOW_CONTRACT[
                    "current_batch_included"
                ].any()
            ),
            "evidence": (
                "all rolling intervals exclude the "
                "current scoring batch"
            ),
        },
        {
            "gate": "activation_ledger_row_conservation",
            "severity": "BLOCKING",
            "passed": (
                len(
                    DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER
                )
                == EXPECTED_ACTIVATION_LEDGER_ROWS
            ),
            "evidence": (
                f"rows="
                f"{len(DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER)}"
            ),
        },
        {
            "gate": "activation_ledger_identity_unique",
            "severity": "BLOCKING",
            "passed": bool(
                DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER[
                    "activation_ledger_id"
                ].is_unique
            ),
            "evidence": (
                f"unique_ids="
                f"{DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER['activation_ledger_id'].nunique()}"
            ),
        },
        {
            "gate": "all_mark_types_per_event",
            "severity": "BLOCKING",
            "passed": bool(
                event_mark_type_counts.eq(
                    len(
                        DELAYED_AGGREGATE_MARK_SPECS
                    )
                ).all()
            ),
            "evidence": (
                f"mark_types="
                f"{len(DELAYED_AGGREGATE_MARK_SPECS)}"
            ),
        },
        {
            "gate": "no_mark_backdating",
            "severity": "BLOCKING",
            "passed": (
                backdated_event_count == 0
            ),
            "evidence": (
                f"backdated_events="
                f"{backdated_event_count}"
            ),
        },
        {
            "gate": "strictly_later_activation",
            "severity": "BLOCKING",
            "passed": (
                equal_time_activation_violation_count
                == 0
                and current_batch_activation_violation_count
                == 0
            ),
            "evidence": (
                f"equal_time_violations="
                f"{equal_time_activation_violation_count}; "
                f"current_batch_violations="
                f"{current_batch_activation_violation_count}"
            ),
        },
        {
            "gate": "activation_batch_minimality",
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                "immediately previous batch time is never "
                "strictly after mark availability"
            ),
        },
        {
            "gate": "availability_inside_split_contract",
            "severity": "BLOCKING",
            "passed": bool(
                availability_inside_split_contract.all()
            ),
            "evidence": (
                f"outside_count="
                f"{int((~availability_inside_split_contract).sum())}"
            ),
        },
        {
            "gate": "delayed_event_count_reconciles",
            "severity": "BLOCKING",
            "passed": (
                delayed_event_count
                == EXPECTED_DELAYED_AGGREGATE_EVENT_COUNT
            ),
            "evidence": (
                f"delayed_events="
                f"{delayed_event_count}"
            ),
        },
        {
            "gate": "future_labels_absent",
            "severity": "BLOCKING",
            "passed": (
                len(
                    future_label_like_activation_columns
                )
                == 0
            ),
            "evidence": (
                f"future_label_columns="
                f"{len(future_label_like_activation_columns)}"
            ),
        },
        {
            "gate": "events_without_later_scoring_batch",
            "severity": "WARNING",
            "passed": (
                events_without_later_batch_count
                == 0
            ),
            "evidence": (
                f"count="
                f"{events_without_later_batch_count}; "
                "marks remain right-censored in the "
                "observed scoring grid"
            ),
        },
        {
            "gate": "availability_crosses_partition",
            "severity": "WARNING",
            "passed": (
                availability_cross_partition_event_count
                == 0
            ),
            "evidence": (
                f"count="
                f"{availability_cross_partition_event_count}"
            ),
        },
        {
            "gate": "activation_crosses_source_partition",
            "severity": "WARNING",
            "passed": (
                activation_cross_partition_event_count
                == 0
            ),
            "evidence": (
                f"count="
                f"{activation_cross_partition_event_count}"
            ),
        },
        {
            "gate": (
                "activation_crosses_availability_partition"
            ),
            "severity": "WARNING",
            "passed": (
                activation_cross_availability_partition_event_count
                == 0
            ),
            "evidence": (
                f"count="
                f"{activation_cross_availability_partition_event_count}"
            ),
        },
    ]
)

ROLLING_AND_ACTIVATION_GATES[
    "status"
] = np.select(
    [
        ROLLING_AND_ACTIVATION_GATES[
            "passed"
        ],
        ROLLING_AND_ACTIVATION_GATES[
            "severity"
        ].eq("BLOCKING"),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

rolling_activation_blocking_failures = (
    ROLLING_AND_ACTIVATION_GATES.loc[
        ROLLING_AND_ACTIVATION_GATES[
            "severity"
        ].eq("BLOCKING")
        & ~ROLLING_AND_ACTIVATION_GATES[
            "passed"
        ]
    ]
)

require(
    rolling_activation_blocking_failures.empty,
    (
        "Rolling-window or delayed-mark activation "
        "construction contains blocking failures."
    ),
)


# ------------------------------------------------------------
# Frozen downstream state
# ------------------------------------------------------------

ROLLING_WINDOW_CONTRACT_VERIFIED: Final[
    bool
] = True

DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER_VERIFIED: Final[
    bool
] = True

DELAYED_AGGREGATE_MARK_TYPE_COUNT: Final[
    int
] = int(
    len(
        DELAYED_AGGREGATE_MARK_SPECS
    )
)

DELAYED_AGGREGATE_MARK_LEDGER_ROW_COUNT: Final[
    int
] = int(
    len(
        DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER
    )
)


# ------------------------------------------------------------
# Compact displays
# ------------------------------------------------------------

display(
    ROLLING_WINDOW_CONTRACT[
        [
            "window_name",
            "window_type",
            "window_ns",
            "window_seconds",
            "prior_batch_count",
            "timing_class",
            "interval_convention",
            "current_batch_included",
            "partition_boundary_rule",
        ]
    ]
)

display(
    MARK_TYPE_ACTIVATION_AUDIT
)

display(
    ACTIVATION_PARTITION_SUMMARY
)

display(
    DELAYED_MARK_EVENT_ACTIVATION_SUMMARY[
        [
            "primary_event_id",
            "primary_event_batch_id",
            "event_partition",
            "event_time_ns",
            "aggregate_mark_available_time_ns",
            "aggregate_mark_lag_after_event_ns",
            "earliest_eligible_future_batch_id",
            "earliest_eligible_future_batch_time_ns",
            "activation_delay_to_earliest_batch_ns",
            "activation_status",
        ]
    ].head(20)
)

display(
    ROLLING_AND_ACTIVATION_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "rolling_window_contract_verified": (
        ROLLING_WINDOW_CONTRACT_VERIFIED
    ),
    "delayed_aggregate_mark_activation_ledger_verified": (
        DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER_VERIFIED
    ),
    "clock_time_windows_ns": dict(
        CLOCK_TIME_WINDOWS_NS
    ),
    "prior_batch_count_windows": dict(
        PRIOR_BATCH_COUNT_WINDOWS
    ),
    "activation_mark_type_count": (
        DELAYED_AGGREGATE_MARK_TYPE_COUNT
    ),
    "activation_ledger_rows": (
        DELAYED_AGGREGATE_MARK_LEDGER_ROW_COUNT
    ),
    "source_event_rows": int(
        len(
            DELAYED_MARK_EVENT_SOURCE
        )
    ),
    "immediate_at_initiation_events": int(
        immediate_event_count
    ),
    "delayed_after_initiation_events": int(
        delayed_event_count
    ),
    "events_without_later_scoring_batch": int(
        events_without_later_batch_count
    ),
    "availability_cross_partition_events": int(
        availability_cross_partition_event_count
    ),
    "activation_cross_source_partition_events": int(
        activation_cross_partition_event_count
    ),
    "equal_time_activation_violations": int(
        equal_time_activation_violation_count
    ),
    "current_batch_activation_violations": int(
        current_batch_activation_violation_count
    ),
    "future_labels_attached": False,
    "verified_at_utc": utc_now_iso(),
}

,window_name,window_type,window_ns,window_seconds,prior_batch_count,timing_class,interval_convention,current_batch_included,partition_boundary_rule
0,W250MS,CLOCK_TIME,250000000,0.25,<NA>,T_MINUS,"[t-window, t)",False,Earlier-partition causal history may carry forward; later-partition history is forbidden.
1,W1S,CLOCK_TIME,1000000000,1.00,<NA>,T_MINUS,"[t-window, t)",False,Earlier-partition causal history may carry forward; later-partition history is forbidden.
2,W5S,CLOCK_TIME,5000000000,5.00,<NA>,T_MINUS,"[t-window, t)",False,Earlier-partition causal history may carry forward; later-partition history is forbidden.
3,W30S,CLOCK_TIME,30000000000,30.00,<NA>,T_MINUS,"[t-window, t)",False,Earlier-partition causal history may carry forward; later-partition history is forbidden.
4,B10,PRIOR_BATCH_COUNT,<NA>,NaN,10,T_MINUS,previous N completed scoring batches,False,Earlier-partition causal batches may carry forward; no backward information flow.
5,B50,PRIOR_BATCH_COUNT,<NA>,NaN,50,T_MINUS,previous N completed scoring batches,False,Earlier-partition causal batches may carry forward; no backward information flow.

               mark_type     mark_unit  mark_integer_valued_flag  mark_derived_flag  ledger_row_count  unique_event_count  minimum_mark_value  maximum_mark_value  delayed_event_count  no_later_batch_count
0     AGGREGATE_NOTIONAL          USDT                     False              False             13887               13887            4.467633       639392.180637                 1575                     1
1  AGGREGATE_PRINT_COUNT  TRADE_PRINTS                      True              False             13887               13887            1.000000          239.000000                 1575                     1
2     AGGREGATE_QUANTITY           BTC                     False              False             13887               13887            0.000070           10.000000                 1575                     1
3         AGGREGATE_VWAP  USDT_PER_BTC                     False               True             13887               13887        63802.153520        64011.900000                 1575                     1

,event_partition_order,event_partition,source_event_count,immediate_at_initiation_count,delayed_after_initiation_count,availability_cross_partition_count,activation_cross_partition_count,no_later_batch_count,minimum_mark_lag_ns,median_mark_lag_ns,maximum_mark_lag_ns
0,1,DEVELOPMENT,7004,6255,749,0,True,0,0,0.0,18302900
1,2,CALIBRATION,2493,2192,301,0,True,0,0,0.0,10378400
2,3,VALIDATION,2048,1800,248,0,True,0,0,0.0,12489300
3,4,ENGINEERING_HOLDOUT,2342,2065,277,0,False,1,0,0.0,12496200

,primary_event_id,primary_event_batch_id,event_partition,event_time_ns,aggregate_mark_available_time_ns,aggregate_mark_lag_after_event_ns,earliest_eligible_future_batch_id,earliest_eligible_future_batch_time_ns,activation_delay_to_earliest_batch_ns,activation_status
0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000001,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000001,DEVELOPMENT,1783665468766951600,1783665468766951600,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000002,1783665469052166500,285214900,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
1,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000002,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000002,DEVELOPMENT,1783665469052166500,1783665469052166500,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000003,1783665469437964400,385797900,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
2,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000003,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000003,DEVELOPMENT,1783665469437964400,1783665469437964400,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000004,1783665469692104200,254139800,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
3,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000004,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000004,DEVELOPMENT,1783665469692104200,1783665469692104200,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000005,1783665470242312100,550207900,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
4,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000005,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000005,DEVELOPMENT,1783665470242312100,1783665470242312100,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000006,1783665470304239100,61927000,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
5,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000006,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000006,DEVELOPMENT,1783665470304239100,1783665470304239100,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000007,1783665470597198800,292959700,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
6,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000007,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000007,DEVELOPMENT,1783665470597198800,1783665470597198800,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,1783665471662326600,1065127800,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
7,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000008,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,DEVELOPMENT,1783665471662326600,1783665471662326600,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000009,1783665471742062100,79735500,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
8,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000009,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000009,DEVELOPMENT,1783665471742062100,1783665471742062100,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000010,1783665471862162900,120100800,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
9,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000010,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000010,DEVELOPMENT,1783665471862162900,1783665471862162900,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000011,1783665472192276400,330113500,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
10,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000011,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000011,DEVELOPMENT,1783665472192276400,1783665472192276400,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000012,1783665472241436900,49160500,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
11,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000012,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000012,DEVELOPMENT,1783665472241436900,1783665472241436900,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000013,1783665472587325700,345888800,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
12,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000013,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000013,DEVELOPMENT,1783665472587325700,1783665472587325700,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000014,1783665473022153600,434827900,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
13,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000014,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000014,DEVELOPMENT,1783665473022153600,1783665473022153600,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000015,1783665473076372900,54219300,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
14,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000015,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000015,DEVELOPMENT,1783665473076372900,1783665473076372900,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000016,1783665473232045400,155672500,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
15,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000016,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000016,DEVELOPMENT,1783665473232045400,1783665473232045400,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000017,1783665473281888100,49842700,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
16,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000017,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000017,DEVELOPMENT,1783665473281888100,1783665473281888100,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000018,1783665473362182500,80294400,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
17,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000018,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000018,DEVELOPMENT,1783665473362182500,1783665473362182500,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000019,1783665473855268900,493086400,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
18,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000019,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000019,DEVELOPMENT,1783665473855268900,1783665473855268900,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000020,1783665474632049800,776780900,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID
19,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__BURST_ALL__00000020,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000020,DEVELOPMENT,1783665474632049800,1783665474632049800,0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000021,1783665475023106900,391057100,ELIGIBLE_WITHIN_OBSERVED_SCORING_GRID

                                         gate  severity   status                                                                          evidence
0            rolling_clock_window_grid_frozen  BLOCKING     PASS  {'W250MS': 250000000, 'W1S': 1000000000, 'W5S': 5000000000, 'W30S': 30000000000}
1              prior_batch_window_grid_frozen  BLOCKING     PASS                                                            {'B10': 10, 'B50': 50}
2         current_batch_excluded_from_windows  BLOCKING     PASS                           all rolling intervals exclude the current scoring batch
3          activation_ledger_row_conservation  BLOCKING     PASS                                                                        rows=55548
4           activation_ledger_identity_unique  BLOCKING     PASS                                                                  unique_ids=55548
5                    all_mark_types_per_event  BLOCKING     PASS                                                                      mark_types=4
6                          no_mark_backdating  BLOCKING     PASS                                                                backdated_events=0
7                   strictly_later_activation  BLOCKING     PASS                               equal_time_violations=0; current_batch_violations=0
8                 activation_batch_minimality  BLOCKING     PASS         immediately previous batch time is never strictly after mark availability
9          availability_inside_split_contract  BLOCKING     PASS                                                                   outside_count=0
10             delayed_event_count_reconciles  BLOCKING     PASS                                                               delayed_events=1575
11                       future_labels_absent  BLOCKING     PASS                                                            future_label_columns=0
12         events_without_later_scoring_batch   WARNING  WARNING                 count=1; marks remain right-censored in the observed scoring grid
13             availability_crosses_partition   WARNING     PASS                                                                           count=0
14        activation_crosses_source_partition   WARNING  WARNING                                                                           count=3
15  activation_crosses_availability_partition   WARNING  WARNING                                                                           count=3

{'status': 'PASS',
 'rolling_window_contract_verified': True,
 'delayed_aggregate_mark_activation_ledger_verified': True,
 'clock_time_windows_ns': {'W250MS': 250000000,
  'W1S': 1000000000,
  'W5S': 5000000000,
  'W30S': 30000000000},
 'prior_batch_count_windows': {'B10': 10, 'B50': 50},
 'activation_mark_type_count': 4,
 'activation_ledger_rows': 55548,
 'source_event_rows': 13887,
 'immediate_at_initiation_events': 12312,
 'delayed_after_initiation_events': 1575,
 'events_without_later_scoring_batch': 1,
 'availability_cross_partition_events': 0,
 'activation_cross_source_partition_events': 3,
 'equal_time_activation_violations': 0,
 'current_batch_activation_violations': 0,
 'future_labels_attached': False,
 'verified_at_utc': '2026-07-19T09:33:59.478075+00:00'}

In [10]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 11 — Causal prior event-flow, prior batch-flow, and
#           availability-gated aggregate-mark features
# ============================================================


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "ROLLING_WINDOW_CONTRACT_VERIFIED",
        False,
    )
    is True,
    "Rolling-window contract has not been verified.",
)

require(
    globals().get(
        "DELAYED_AGGREGATE_MARK_ACTIVATION_LEDGER_VERIFIED",
        False,
    )
    is True,
    "Delayed aggregate-mark activation ledger is unavailable.",
)

require(
    globals().get(
        "STATIC_VISIBLE_BOOK_FEATURES_VERIFIED",
        False,
    )
    is True,
    "Static visible-book feature interface is unavailable.",
)

require(
    len(PRIMARY_ESTIMATION_EVENTS)
    == EXPECTED_PRIMARY_EVENT_ROWS,
    "Primary event count changed before event-flow construction.",
)

require(
    len(PRIMARY_SCORING_BATCHES)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    "Primary batch count changed before event-flow construction.",
)


# ------------------------------------------------------------
# Physically separate current-batch post-event context
#
# These values are known only after the current exact-time
# scoring batch has occurred. They are never joined into the
# current batch's t-minus feature vector.
# ------------------------------------------------------------

POST_BATCH_CONTEXT_SOURCE_COLUMNS: Final[
    tuple[str, ...]
] = (
    "primary_event_batch_id",
    "primary_event_batch_number",
    "partition_batch_index",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
    "batch_event_count",
    "buy_event_count",
    "sell_event_count",
    "unique_side_count",
    "batch_print_count",
    "batch_quantity",
    "batch_notional",
    "mixed_side_batch_flag",
    "simultaneous_batch_required_flag",
)

require_columns(
    PRIMARY_EXACT_TIME_BATCHES,
    POST_BATCH_CONTEXT_SOURCE_COLUMNS,
    "PRIMARY_EXACT_TIME_BATCHES",
)

BATCH_POST_EVENT_CONTEXT = (
    PRIMARY_EXACT_TIME_BATCHES[
        list(
            POST_BATCH_CONTEXT_SOURCE_COLUMNS
        )
    ]
    .copy()
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)
)

BATCH_POST_EVENT_CONTEXT = (
    BATCH_POST_EVENT_CONTEXT.rename(
        columns={
            "batch_event_count": (
                "tplus_current_batch_event_count"
            ),
            "buy_event_count": (
                "tplus_current_batch_buy_event_count"
            ),
            "sell_event_count": (
                "tplus_current_batch_sell_event_count"
            ),
            "unique_side_count": (
                "tplus_current_batch_unique_side_count"
            ),
            "batch_print_count": (
                "tplus_current_batch_print_count"
            ),
            "batch_quantity": (
                "tplus_current_batch_quantity"
            ),
            "batch_notional": (
                "tplus_current_batch_notional"
            ),
            "mixed_side_batch_flag": (
                "tplus_current_batch_mixed_side_flag"
            ),
            "simultaneous_batch_required_flag": (
                "tplus_current_batch_simultaneous_flag"
            ),
        }
    )
)

BATCH_POST_EVENT_CONTEXT[
    "timing_class"
] = TIMING_CLASS_T_PLUS

BATCH_POST_EVENT_CONTEXT[
    "authorized_in_tminus_feature_table"
] = False

BATCH_POST_EVENT_CONTEXT[
    "available_only_after_all_batch_members_scored"
] = True

require(
    len(BATCH_POST_EVENT_CONTEXT)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Post-batch context does not contain one row per "
        "authoritative scoring batch."
    ),
)

require(
    BATCH_POST_EVENT_CONTEXT[
        "primary_event_batch_id"
    ].is_unique,
    "Post-batch context contains duplicate batch IDs.",
)

require(
    BATCH_POST_EVENT_CONTEXT[
        "timing_class"
    ].eq(
        TIMING_CLASS_T_PLUS
    ).all(),
    "A post-batch context row has the wrong timing class.",
)

require(
    not BATCH_POST_EVENT_CONTEXT[
        "authorized_in_tminus_feature_table"
    ].any(),
    "Post-batch context is incorrectly authorized as t-minus.",
)


# ------------------------------------------------------------
# Canonical event-flow feature spine
# ------------------------------------------------------------

EVENT_FLOW_IDENTITY_COLUMNS: Final[
    tuple[str, ...]
] = (
    "primary_event_batch_id",
    "primary_event_batch_number",
    "partition_batch_index",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
)

BATCH_CAUSAL_EVENT_FLOW_FEATURES = (
    PRIMARY_SCORING_BATCHES[
        list(
            EVENT_FLOW_IDENTITY_COLUMNS
        )
    ]
    .copy()
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)
)

require_unique_columns(
    BATCH_CAUSAL_EVENT_FLOW_FEATURES,
    "BATCH_CAUSAL_EVENT_FLOW_FEATURES",
)

require(
    len(BATCH_CAUSAL_EVENT_FLOW_FEATURES)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Causal event-flow feature spine does not contain "
        "one row per scoring batch."
    ),
)

require(
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        "primary_event_batch_id"
    ].is_unique,
    "Causal event-flow feature batch IDs are not unique.",
)

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "primary_event_batch_number"
] = parse_required_int64(
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        "primary_event_batch_number"
    ],
    (
        "BATCH_CAUSAL_EVENT_FLOW_FEATURES."
        "primary_event_batch_number"
    ),
)

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "event_partition_order"
] = parse_required_int64(
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        "event_partition_order"
    ],
    (
        "BATCH_CAUSAL_EVENT_FLOW_FEATURES."
        "event_partition_order"
    ),
)

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "event_time_ns"
] = parse_required_int64(
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        "event_time_ns"
    ],
    (
        "BATCH_CAUSAL_EVENT_FLOW_FEATURES."
        "event_time_ns"
    ),
)

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "event_partition"
] = (
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        "event_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

require(
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        "event_time_ns"
    ].is_monotonic_increasing,
    "Scoring-batch event times are not non-decreasing.",
)


# ------------------------------------------------------------
# Prefix-sum helpers
# ------------------------------------------------------------

def causal_prefix_sum(
    values: np.ndarray | pd.Series,
    *,
    dtype: np.dtype | str = "float64",
) -> np.ndarray:
    """Construct a leading-zero prefix sum."""
    array = np.asarray(
        values,
        dtype=dtype,
    )

    return np.concatenate(
        [
            np.zeros(
                1,
                dtype=array.dtype,
            ),
            np.cumsum(
                array,
                dtype=array.dtype,
            ),
        ]
    )


def causal_slice_sum(
    prefix: np.ndarray,
    left_positions: np.ndarray,
    right_positions: np.ndarray,
) -> np.ndarray:
    """Return prefix[right] - prefix[left]."""
    return (
        prefix[
            right_positions
        ]
        - prefix[
            left_positions
        ]
    )


def safe_fraction(
    numerator: np.ndarray,
    denominator: np.ndarray,
) -> np.ndarray:
    """Return numerator / denominator with NaN at zero."""
    numerator_array = np.asarray(
        numerator,
        dtype="float64",
    )

    denominator_array = np.asarray(
        denominator,
        dtype="float64",
    )

    output = np.full(
        numerator_array.shape,
        np.nan,
        dtype="float64",
    )

    valid = (
        denominator_array > 0
    )

    output[
        valid
    ] = (
        numerator_array[
            valid
        ]
        / denominator_array[
            valid
        ]
    )

    return output


# ------------------------------------------------------------
# Canonical event source
#
# Event counts and event sides are available at initiation.
# Quantity, notional, print count, and VWAP are usable only
# after aggregate_mark_available_time_ns.
# ------------------------------------------------------------

EVENT_FLOW_SOURCE = (
    DELAYED_MARK_EVENT_ACTIVATION_SUMMARY[
        [
            "primary_event_id",
            "primary_event_number",
            "primary_event_batch_id",
            "primary_event_batch_number",
            "event_partition_order",
            "event_partition",
            "event_time_ns",
            "event_side",
            "event_side_code",
            "event_print_count",
            "event_quantity",
            "event_notional",
            "derived_event_vwap",
            "aggregate_mark_available_time_ns",
            "aggregate_mark_lag_after_event_ns",
            "earliest_eligible_future_batch_number",
        ]
    ]
    .copy()
    .sort_values(
        [
            "event_time_ns",
            "primary_event_number",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

require(
    len(EVENT_FLOW_SOURCE)
    == EXPECTED_PRIMARY_EVENT_ROWS,
    "Event-flow source changed the primary event population.",
)

require(
    EVENT_FLOW_SOURCE[
        "primary_event_id"
    ].is_unique,
    "Event-flow source contains duplicate event IDs.",
)

EVENT_FLOW_SOURCE[
    "primary_event_number"
] = parse_required_int64(
    EVENT_FLOW_SOURCE[
        "primary_event_number"
    ],
    "EVENT_FLOW_SOURCE.primary_event_number",
)

EVENT_FLOW_SOURCE[
    "primary_event_batch_number"
] = parse_required_int64(
    EVENT_FLOW_SOURCE[
        "primary_event_batch_number"
    ],
    (
        "EVENT_FLOW_SOURCE."
        "primary_event_batch_number"
    ),
)

EVENT_FLOW_SOURCE[
    "event_partition_order"
] = parse_required_int64(
    EVENT_FLOW_SOURCE[
        "event_partition_order"
    ],
    "EVENT_FLOW_SOURCE.event_partition_order",
)

EVENT_FLOW_SOURCE[
    "event_time_ns"
] = parse_required_int64(
    EVENT_FLOW_SOURCE[
        "event_time_ns"
    ],
    "EVENT_FLOW_SOURCE.event_time_ns",
)

EVENT_FLOW_SOURCE[
    "event_print_count"
] = parse_required_int64(
    EVENT_FLOW_SOURCE[
        "event_print_count"
    ],
    "EVENT_FLOW_SOURCE.event_print_count",
)

EVENT_FLOW_SOURCE[
    "event_quantity"
] = parse_required_float64(
    EVENT_FLOW_SOURCE[
        "event_quantity"
    ],
    "EVENT_FLOW_SOURCE.event_quantity",
)

EVENT_FLOW_SOURCE[
    "event_notional"
] = parse_required_float64(
    EVENT_FLOW_SOURCE[
        "event_notional"
    ],
    "EVENT_FLOW_SOURCE.event_notional",
)

EVENT_FLOW_SOURCE[
    "aggregate_mark_available_time_ns"
] = parse_required_int64(
    EVENT_FLOW_SOURCE[
        "aggregate_mark_available_time_ns"
    ],
    (
        "EVENT_FLOW_SOURCE."
        "aggregate_mark_available_time_ns"
    ),
)

EVENT_FLOW_SOURCE[
    "aggregate_mark_lag_after_event_ns"
] = parse_required_int64(
    EVENT_FLOW_SOURCE[
        "aggregate_mark_lag_after_event_ns"
    ],
    (
        "EVENT_FLOW_SOURCE."
        "aggregate_mark_lag_after_event_ns"
    ),
)

EVENT_FLOW_SOURCE[
    "event_side"
] = (
    EVENT_FLOW_SOURCE[
        "event_side"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

require(
    EVENT_FLOW_SOURCE[
        "event_time_ns"
    ].is_monotonic_increasing,
    "Event-flow source event times are not non-decreasing.",
)

require(
    set(
        EVENT_FLOW_SOURCE[
            "event_side"
        ].dropna().unique()
    )
    == set(VALID_AGGRESSOR_SIDES),
    "Event-flow source side domain differs from {BUY, SELL}.",
)


# ------------------------------------------------------------
# Canonical event arrays and prefixes
# ------------------------------------------------------------

event_flow_time_array = (
    EVENT_FLOW_SOURCE[
        "event_time_ns"
    ]
    .astype("int64")
    .to_numpy()
)

event_flow_availability_array = (
    EVENT_FLOW_SOURCE[
        "aggregate_mark_available_time_ns"
    ]
    .astype("int64")
    .to_numpy()
)

event_flow_lag_array = (
    EVENT_FLOW_SOURCE[
        "aggregate_mark_lag_after_event_ns"
    ]
    .astype("int64")
    .to_numpy()
)

event_flow_buy_indicator = (
    EVENT_FLOW_SOURCE[
        "event_side"
    ]
    .eq("BUY")
    .astype("int64")
    .to_numpy()
)

event_flow_sell_indicator = (
    EVENT_FLOW_SOURCE[
        "event_side"
    ]
    .eq("SELL")
    .astype("int64")
    .to_numpy()
)

event_flow_signed_indicator = (
    event_flow_buy_indicator
    - event_flow_sell_indicator
)

event_flow_print_count_array = (
    EVENT_FLOW_SOURCE[
        "event_print_count"
    ]
    .astype("int64")
    .to_numpy()
)

event_flow_quantity_array = (
    EVENT_FLOW_SOURCE[
        "event_quantity"
    ]
    .astype("float64")
    .to_numpy()
)

event_flow_notional_array = (
    EVENT_FLOW_SOURCE[
        "event_notional"
    ]
    .astype("float64")
    .to_numpy()
)

event_flow_batch_number_array = (
    EVENT_FLOW_SOURCE[
        "primary_event_batch_number"
    ]
    .astype("int64")
    .to_numpy()
)

event_count_prefix = causal_prefix_sum(
    np.ones(
        len(EVENT_FLOW_SOURCE),
        dtype="int64",
    ),
    dtype="int64",
)

event_buy_prefix = causal_prefix_sum(
    event_flow_buy_indicator,
    dtype="int64",
)

event_sell_prefix = causal_prefix_sum(
    event_flow_sell_indicator,
    dtype="int64",
)

event_signed_prefix = causal_prefix_sum(
    event_flow_signed_indicator,
    dtype="int64",
)


# ------------------------------------------------------------
# Completed-batch history source
#
# Current-batch quantities and marks remain physically stored
# in BATCH_POST_EVENT_CONTEXT. Only completed earlier batches
# may contribute to t-minus batch-history features.
# ------------------------------------------------------------

COMPLETED_BATCH_HISTORY_SOURCE = (
    BATCH_POST_EVENT_CONTEXT.copy()
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)
)

completed_batch_time_array = (
    parse_required_int64(
        COMPLETED_BATCH_HISTORY_SOURCE[
            "event_time_ns"
        ],
        (
            "COMPLETED_BATCH_HISTORY_SOURCE."
            "event_time_ns"
        ),
    ).to_numpy()
)

completed_batch_number_array = (
    parse_required_int64(
        COMPLETED_BATCH_HISTORY_SOURCE[
            "primary_event_batch_number"
        ],
        (
            "COMPLETED_BATCH_HISTORY_SOURCE."
            "primary_event_batch_number"
        ),
    ).to_numpy()
)

completed_batch_partition_order_array = (
    parse_required_int64(
        COMPLETED_BATCH_HISTORY_SOURCE[
            "event_partition_order"
        ],
        (
            "COMPLETED_BATCH_HISTORY_SOURCE."
            "event_partition_order"
        ),
    ).to_numpy()
)

completed_batch_event_count_array = (
    parse_required_int64(
        COMPLETED_BATCH_HISTORY_SOURCE[
            "tplus_current_batch_event_count"
        ],
        (
            "COMPLETED_BATCH_HISTORY_SOURCE."
            "tplus_current_batch_event_count"
        ),
    ).to_numpy()
)

completed_batch_buy_event_count_array = (
    parse_required_int64(
        COMPLETED_BATCH_HISTORY_SOURCE[
            "tplus_current_batch_buy_event_count"
        ],
        (
            "COMPLETED_BATCH_HISTORY_SOURCE."
            "tplus_current_batch_buy_event_count"
        ),
    ).to_numpy()
)

completed_batch_sell_event_count_array = (
    parse_required_int64(
        COMPLETED_BATCH_HISTORY_SOURCE[
            "tplus_current_batch_sell_event_count"
        ],
        (
            "COMPLETED_BATCH_HISTORY_SOURCE."
            "tplus_current_batch_sell_event_count"
        ),
    ).to_numpy()
)

completed_batch_simultaneous_array = (
    strict_boolean_series(
        COMPLETED_BATCH_HISTORY_SOURCE[
            "tplus_current_batch_simultaneous_flag"
        ],
        field_name=(
            "COMPLETED_BATCH_HISTORY_SOURCE."
            "tplus_current_batch_simultaneous_flag"
        ),
    )
    .astype("int64")
    .to_numpy()
)

completed_batch_mixed_array = (
    strict_boolean_series(
        COMPLETED_BATCH_HISTORY_SOURCE[
            "tplus_current_batch_mixed_side_flag"
        ],
        field_name=(
            "COMPLETED_BATCH_HISTORY_SOURCE."
            "tplus_current_batch_mixed_side_flag"
        ),
    )
    .astype("int64")
    .to_numpy()
)

require(
    np.array_equal(
        completed_batch_number_array,
        BATCH_CAUSAL_EVENT_FLOW_FEATURES[
            "primary_event_batch_number"
        ].astype("int64").to_numpy(),
    ),
    (
        "Completed-batch history source is not aligned with "
        "the scoring-batch feature spine."
    ),
)

require(
    np.array_equal(
        completed_batch_time_array,
        BATCH_CAUSAL_EVENT_FLOW_FEATURES[
            "event_time_ns"
        ].astype("int64").to_numpy(),
    ),
    (
        "Completed-batch times are not aligned with the "
        "scoring-batch feature spine."
    ),
)

completed_batch_count_prefix = causal_prefix_sum(
    np.ones(
        len(COMPLETED_BATCH_HISTORY_SOURCE),
        dtype="int64",
    ),
    dtype="int64",
)

completed_batch_event_prefix = causal_prefix_sum(
    completed_batch_event_count_array,
    dtype="int64",
)

completed_batch_buy_event_prefix = causal_prefix_sum(
    completed_batch_buy_event_count_array,
    dtype="int64",
)

completed_batch_sell_event_prefix = causal_prefix_sum(
    completed_batch_sell_event_count_array,
    dtype="int64",
)

completed_batch_simultaneous_prefix = causal_prefix_sum(
    completed_batch_simultaneous_array,
    dtype="int64",
)

completed_batch_mixed_prefix = causal_prefix_sum(
    completed_batch_mixed_array,
    dtype="int64",
)


# ------------------------------------------------------------
# Global observable start and current batch arrays
# ------------------------------------------------------------

GLOBAL_EVENT_OBSERVATION_START_NS: Final[int] = int(
    pd.to_numeric(
        OBSERVATION_WINDOW_CONTRACT[
            "contract_start_ns"
        ],
        errors="raise",
    ).min()
)

GLOBAL_EVENT_OBSERVATION_END_EXCLUSIVE_NS: Final[int] = int(
    pd.to_numeric(
        OBSERVATION_WINDOW_CONTRACT[
            "contract_end_exclusive_ns"
        ],
        errors="raise",
    ).max()
)

current_batch_time_array = (
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        "event_time_ns"
    ]
    .astype("int64")
    .to_numpy()
)

current_batch_number_array = (
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        "primary_event_batch_number"
    ]
    .astype("int64")
    .to_numpy()
)

current_batch_partition_order_array = (
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        "event_partition_order"
    ]
    .astype("int64")
    .to_numpy()
)

current_batch_partition_start_array = (
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        "event_partition"
    ]
    .map(
        SPLIT_BOUNDARY_TABLE.set_index(
            "partition"
        )[
            "receipt_time_start_ns"
        ].astype("int64")
    )
)

require(
    current_batch_partition_start_array.notna().all(),
    (
        "At least one scoring batch cannot be mapped to its "
        "Notebook 00 partition start."
    ),
)

current_batch_partition_start_ns_array = (
    current_batch_partition_start_array
    .astype("int64")
    .to_numpy()
)

require(
    (
        current_batch_time_array
        >= GLOBAL_EVENT_OBSERVATION_START_NS
    ).all(),
    "A scoring batch precedes the observable run start.",
)

require(
    (
        current_batch_time_array
        < GLOBAL_EVENT_OBSERVATION_END_EXCLUSIVE_NS
    ).all(),
    "A scoring batch lies outside the observable run end.",
)


# ------------------------------------------------------------
# Clock-time rolling event-flow features
# ------------------------------------------------------------

clock_window_feature_audit_rows: list[
    dict[str, Any]
] = []

clock_window_position_registry: dict[
    str,
    dict[str, np.ndarray],
] = {}

clock_window_count_registry: dict[
    str,
    dict[str, np.ndarray],
] = {}

activation_timing_violation_count = 0
activation_batch_number_violation_count = 0
same_time_event_inclusion_violation_count = 0

for window_name, window_ns in (
    CLOCK_TIME_WINDOWS_NS.items()
):
    window_slug = (
        window_name.lower()
    )

    window_seconds = (
        float(window_ns)
        / 1_000_000_000.0
    )

    window_start_ns = (
        current_batch_time_array
        - int(window_ns)
    )

    event_left_positions = np.searchsorted(
        event_flow_time_array,
        window_start_ns,
        side="left",
    )

    event_right_positions = np.searchsorted(
        event_flow_time_array,
        current_batch_time_array,
        side="left",
    )

    batch_left_positions = np.searchsorted(
        completed_batch_time_array,
        window_start_ns,
        side="left",
    )

    batch_right_positions = np.searchsorted(
        completed_batch_time_array,
        current_batch_time_array,
        side="left",
    )

    event_count = causal_slice_sum(
        event_count_prefix,
        event_left_positions,
        event_right_positions,
    ).astype("int64")

    buy_event_count = causal_slice_sum(
        event_buy_prefix,
        event_left_positions,
        event_right_positions,
    ).astype("int64")

    sell_event_count = causal_slice_sum(
        event_sell_prefix,
        event_left_positions,
        event_right_positions,
    ).astype("int64")

    signed_event_count = causal_slice_sum(
        event_signed_prefix,
        event_left_positions,
        event_right_positions,
    ).astype("int64")

    prior_batch_count = causal_slice_sum(
        completed_batch_count_prefix,
        batch_left_positions,
        batch_right_positions,
    ).astype("int64")

    prior_batch_event_count = causal_slice_sum(
        completed_batch_event_prefix,
        batch_left_positions,
        batch_right_positions,
    ).astype("int64")

    prior_batch_buy_event_count = causal_slice_sum(
        completed_batch_buy_event_prefix,
        batch_left_positions,
        batch_right_positions,
    ).astype("int64")

    prior_batch_sell_event_count = causal_slice_sum(
        completed_batch_sell_event_prefix,
        batch_left_positions,
        batch_right_positions,
    ).astype("int64")

    simultaneous_batch_count = causal_slice_sum(
        completed_batch_simultaneous_prefix,
        batch_left_positions,
        batch_right_positions,
    ).astype("int64")

    mixed_side_batch_count = causal_slice_sum(
        completed_batch_mixed_prefix,
        batch_left_positions,
        batch_right_positions,
    ).astype("int64")

    full_coverage_flag = (
        window_start_ns
        >= GLOBAL_EVENT_OBSERVATION_START_NS
    )

    observed_duration_ns = np.minimum(
        int(window_ns),
        np.maximum(
            0,
            (
                current_batch_time_array
                - GLOBAL_EVENT_OBSERVATION_START_NS
            ),
        ),
    ).astype("int64")

    coverage_fraction = (
        observed_duration_ns.astype("float64")
        / float(window_ns)
    )

    cross_partition_history_flag = (
        window_start_ns
        < current_batch_partition_start_ns_array
    )

    activated_event_count = np.zeros(
        len(
            BATCH_CAUSAL_EVENT_FLOW_FEATURES
        ),
        dtype="int64",
    )

    activated_immediate_event_count = np.zeros_like(
        activated_event_count
    )

    activated_delayed_event_count = np.zeros_like(
        activated_event_count
    )

    activated_buy_event_count = np.zeros_like(
        activated_event_count
    )

    activated_sell_event_count = np.zeros_like(
        activated_event_count
    )

    activated_print_count = np.zeros_like(
        activated_event_count
    )

    activated_buy_print_count = np.zeros_like(
        activated_event_count
    )

    activated_sell_print_count = np.zeros_like(
        activated_event_count
    )

    activated_quantity = np.zeros(
        len(
            BATCH_CAUSAL_EVENT_FLOW_FEATURES
        ),
        dtype="float64",
    )

    activated_buy_quantity = np.zeros_like(
        activated_quantity
    )

    activated_sell_quantity = np.zeros_like(
        activated_quantity
    )

    activated_notional = np.zeros_like(
        activated_quantity
    )

    activated_buy_notional = np.zeros_like(
        activated_quantity
    )

    activated_sell_notional = np.zeros_like(
        activated_quantity
    )

    for batch_position in range(
        len(
            BATCH_CAUSAL_EVENT_FLOW_FEATURES
        )
    ):
        left_position = int(
            event_left_positions[
                batch_position
            ]
        )

        right_position = int(
            event_right_positions[
                batch_position
            ]
        )

        if right_position <= left_position:
            continue

        source_slice = slice(
            left_position,
            right_position,
        )

        current_time_ns = int(
            current_batch_time_array[
                batch_position
            ]
        )

        current_batch_number = int(
            current_batch_number_array[
                batch_position
            ]
        )

        source_event_times = (
            event_flow_time_array[
                source_slice
            ]
        )

        source_availability_times = (
            event_flow_availability_array[
                source_slice
            ]
        )

        available_mask = (
            source_availability_times
            < current_time_ns
        )

        if np.any(
            source_event_times
            >= current_time_ns
        ):
            same_time_event_inclusion_violation_count += int(
                np.sum(
                    source_event_times
                    >= current_time_ns
                )
            )

        if np.any(
            source_availability_times[
                available_mask
            ]
            >= current_time_ns
        ):
            activation_timing_violation_count += int(
                np.sum(
                    source_availability_times[
                        available_mask
                    ]
                    >= current_time_ns
                )
            )

        eligible_batch_numbers = (
            EVENT_FLOW_SOURCE.iloc[
                left_position:right_position
            ][
                "earliest_eligible_future_batch_number"
            ]
        )

        eligible_batch_number_values = pd.to_numeric(
            eligible_batch_numbers,
            errors="coerce",
        ).to_numpy(
            dtype="float64"
        )

        available_with_registered_batch = (
            available_mask
            & np.isfinite(
                eligible_batch_number_values
            )
        )

        if np.any(
            eligible_batch_number_values[
                available_with_registered_batch
            ]
            > current_batch_number
        ):
            activation_batch_number_violation_count += int(
                np.sum(
                    eligible_batch_number_values[
                        available_with_registered_batch
                    ]
                    > current_batch_number
                )
            )

        buy_mask = (
            available_mask
            & (
                event_flow_buy_indicator[
                    source_slice
                ]
                == 1
            )
        )

        sell_mask = (
            available_mask
            & (
                event_flow_sell_indicator[
                    source_slice
                ]
                == 1
            )
        )

        immediate_mask = (
            available_mask
            & (
                event_flow_lag_array[
                    source_slice
                ]
                == 0
            )
        )

        delayed_mask = (
            available_mask
            & (
                event_flow_lag_array[
                    source_slice
                ]
                > 0
            )
        )

        activated_event_count[
            batch_position
        ] = int(
            available_mask.sum()
        )

        activated_immediate_event_count[
            batch_position
        ] = int(
            immediate_mask.sum()
        )

        activated_delayed_event_count[
            batch_position
        ] = int(
            delayed_mask.sum()
        )

        activated_buy_event_count[
            batch_position
        ] = int(
            buy_mask.sum()
        )

        activated_sell_event_count[
            batch_position
        ] = int(
            sell_mask.sum()
        )

        activated_print_count[
            batch_position
        ] = int(
            event_flow_print_count_array[
                source_slice
            ][
                available_mask
            ].sum()
        )

        activated_buy_print_count[
            batch_position
        ] = int(
            event_flow_print_count_array[
                source_slice
            ][
                buy_mask
            ].sum()
        )

        activated_sell_print_count[
            batch_position
        ] = int(
            event_flow_print_count_array[
                source_slice
            ][
                sell_mask
            ].sum()
        )

        activated_quantity[
            batch_position
        ] = float(
            event_flow_quantity_array[
                source_slice
            ][
                available_mask
            ].sum()
        )

        activated_buy_quantity[
            batch_position
        ] = float(
            event_flow_quantity_array[
                source_slice
            ][
                buy_mask
            ].sum()
        )

        activated_sell_quantity[
            batch_position
        ] = float(
            event_flow_quantity_array[
                source_slice
            ][
                sell_mask
            ].sum()
        )

        activated_notional[
            batch_position
        ] = float(
            event_flow_notional_array[
                source_slice
            ][
                available_mask
            ].sum()
        )

        activated_buy_notional[
            batch_position
        ] = float(
            event_flow_notional_array[
                source_slice
            ][
                buy_mask
            ].sum()
        )

        activated_sell_notional[
            batch_position
        ] = float(
            event_flow_notional_array[
                source_slice
            ][
                sell_mask
            ].sum()
        )

    unavailable_mark_event_count = (
        event_count
        - activated_event_count
    )

    activated_signed_event_count = (
        activated_buy_event_count
        - activated_sell_event_count
    )

    activated_signed_print_count = (
        activated_buy_print_count
        - activated_sell_print_count
    )

    activated_signed_quantity = (
        activated_buy_quantity
        - activated_sell_quantity
    )

    activated_signed_notional = (
        activated_buy_notional
        - activated_sell_notional
    )

    activated_vwap = safe_fraction(
        activated_notional,
        activated_quantity,
    )

    buy_event_fraction = safe_fraction(
        buy_event_count,
        event_count,
    )

    sell_event_fraction = safe_fraction(
        sell_event_count,
        event_count,
    )

    signed_event_fraction = safe_fraction(
        signed_event_count,
        event_count,
    )

    activated_mark_fraction = safe_fraction(
        activated_event_count,
        event_count,
    )

    simultaneous_batch_fraction = safe_fraction(
        simultaneous_batch_count,
        prior_batch_count,
    )

    mixed_side_batch_fraction = safe_fraction(
        mixed_side_batch_count,
        prior_batch_count,
    )

    mean_events_per_batch = safe_fraction(
        prior_batch_event_count,
        prior_batch_count,
    )

    event_rate_per_second = np.where(
        full_coverage_flag,
        (
            event_count.astype("float64")
            / window_seconds
        ),
        np.nan,
    )

    buy_event_rate_per_second = np.where(
        full_coverage_flag,
        (
            buy_event_count.astype("float64")
            / window_seconds
        ),
        np.nan,
    )

    sell_event_rate_per_second = np.where(
        full_coverage_flag,
        (
            sell_event_count.astype("float64")
            / window_seconds
        ),
        np.nan,
    )

    prior_batch_rate_per_second = np.where(
        full_coverage_flag,
        (
            prior_batch_count.astype("float64")
            / window_seconds
        ),
        np.nan,
    )

    activated_print_rate_per_second = np.where(
        full_coverage_flag,
        (
            activated_print_count.astype(
                "float64"
            )
            / window_seconds
        ),
        np.nan,
    )

    activated_quantity_rate_per_second = np.where(
        full_coverage_flag,
        (
            activated_quantity
            / window_seconds
        ),
        np.nan,
    )

    activated_notional_rate_per_second = np.where(
        full_coverage_flag,
        (
            activated_notional
            / window_seconds
        ),
        np.nan,
    )

    feature_prefix = (
        f"tminus_event_{window_slug}"
    )

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_full_coverage_flag"
    ] = full_coverage_flag

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_coverage_fraction"
    ] = coverage_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_observed_duration_seconds"
    ] = (
        observed_duration_ns.astype("float64")
        / 1_000_000_000.0
    )

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_cross_partition_history_flag"
    ] = cross_partition_history_flag

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_event_count"
    ] = event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_buy_event_count"
    ] = buy_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_sell_event_count"
    ] = sell_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_signed_event_count"
    ] = signed_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_buy_event_fraction"
    ] = buy_event_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_sell_event_fraction"
    ] = sell_event_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_signed_event_fraction"
    ] = signed_event_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_event_rate_per_second"
    ] = event_rate_per_second

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_buy_event_rate_per_second"
    ] = buy_event_rate_per_second

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_sell_event_rate_per_second"
    ] = sell_event_rate_per_second

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_prior_batch_count"
    ] = prior_batch_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_prior_batch_event_count"
    ] = prior_batch_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_prior_batch_buy_event_count"
    ] = prior_batch_buy_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_prior_batch_sell_event_count"
    ] = prior_batch_sell_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_prior_batch_rate_per_second"
    ] = prior_batch_rate_per_second

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_simultaneous_batch_count"
    ] = simultaneous_batch_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_simultaneous_batch_fraction"
    ] = simultaneous_batch_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_mixed_side_batch_count"
    ] = mixed_side_batch_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_mixed_side_batch_fraction"
    ] = mixed_side_batch_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_mean_events_per_batch"
    ] = mean_events_per_batch

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_mark_event_count"
    ] = activated_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_immediate_event_count"
    ] = activated_immediate_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_delayed_event_count"
    ] = activated_delayed_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_unavailable_mark_event_count"
    ] = unavailable_mark_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_mark_fraction"
    ] = activated_mark_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_buy_event_count"
    ] = activated_buy_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_sell_event_count"
    ] = activated_sell_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_signed_event_count"
    ] = activated_signed_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_print_count"
    ] = activated_print_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_buy_print_count"
    ] = activated_buy_print_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_sell_print_count"
    ] = activated_sell_print_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_signed_print_count"
    ] = activated_signed_print_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_print_rate_per_second"
    ] = activated_print_rate_per_second

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_quantity"
    ] = activated_quantity

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_buy_quantity"
    ] = activated_buy_quantity

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_sell_quantity"
    ] = activated_sell_quantity

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_signed_quantity"
    ] = activated_signed_quantity

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_quantity_rate_per_second"
    ] = activated_quantity_rate_per_second

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_notional"
    ] = activated_notional

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_buy_notional"
    ] = activated_buy_notional

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_sell_notional"
    ] = activated_sell_notional

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_signed_notional"
    ] = activated_signed_notional

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_notional_rate_per_second"
    ] = activated_notional_rate_per_second

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_activated_vwap"
    ] = activated_vwap

    require(
        np.array_equal(
            buy_event_count
            + sell_event_count,
            event_count,
        ),
        (
            f"{window_name} BUY and SELL event counts do not "
            "sum to total event count."
        ),
    )

    require(
        np.array_equal(
            prior_batch_buy_event_count
            + prior_batch_sell_event_count,
            prior_batch_event_count,
        ),
        (
            f"{window_name} prior-batch BUY and SELL event "
            "counts do not sum to total prior-batch events."
        ),
    )

    require(
        (
            activated_event_count
            <= event_count
        ).all(),
        (
            f"{window_name} activated mark-event count exceeds "
            "the prior event count."
        ),
    )

    require(
        np.array_equal(
            activated_buy_event_count
            + activated_sell_event_count,
            activated_event_count,
        ),
        (
            f"{window_name} activated BUY and SELL event "
            "counts do not sum to activated event count."
        ),
    )

    require(
        (
            activated_print_count
            >= activated_event_count
        ).all(),
        (
            f"{window_name} activated print count is smaller "
            "than activated event count."
        ),
    )

    require(
        np.allclose(
            activated_buy_quantity
            + activated_sell_quantity,
            activated_quantity,
            rtol=1e-12,
            atol=1e-12,
        ),
        (
            f"{window_name} activated side quantities do not "
            "sum to total quantity."
        ),
    )

    require(
        np.allclose(
            activated_buy_notional
            + activated_sell_notional,
            activated_notional,
            rtol=1e-12,
            atol=1e-8,
        ),
        (
            f"{window_name} activated side notionals do not "
            "sum to total notional."
        ),
    )

    require(
        (
            unavailable_mark_event_count
            >= 0
        ).all(),
        (
            f"{window_name} contains a negative unavailable "
            "mark-event count."
        ),
    )

    require(
        (
            coverage_fraction >= 0.0
        ).all()
        and (
            coverage_fraction <= 1.0
        ).all(),
        (
            f"{window_name} coverage fraction lies outside "
            "[0, 1]."
        ),
    )

    rate_columns = [
        f"{feature_prefix}_event_rate_per_second",
        f"{feature_prefix}_buy_event_rate_per_second",
        f"{feature_prefix}_sell_event_rate_per_second",
        f"{feature_prefix}_prior_batch_rate_per_second",
        f"{feature_prefix}_activated_print_rate_per_second",
        f"{feature_prefix}_activated_quantity_rate_per_second",
        f"{feature_prefix}_activated_notional_rate_per_second",
    ]

    require(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES.loc[
            full_coverage_flag,
            rate_columns,
        ].notna().all().all(),
        (
            f"{window_name} contains missing authoritative "
            "rate values despite full history coverage."
        ),
    )

    require(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES.loc[
            ~full_coverage_flag,
            rate_columns,
        ].isna().all().all(),
        (
            f"{window_name} contains authoritative rate values "
            "despite incomplete history coverage."
        ),
    )

    clock_window_position_registry[
        window_name
    ] = {
        "event_left": event_left_positions,
        "event_right": event_right_positions,
        "batch_left": batch_left_positions,
        "batch_right": batch_right_positions,
    }

    clock_window_count_registry[
        window_name
    ] = {
        "event_count": event_count,
        "prior_batch_count": prior_batch_count,
        "activated_event_count": activated_event_count,
        "activated_quantity": activated_quantity,
        "activated_notional": activated_notional,
    }

    clock_window_feature_audit_rows.append(
        {
            "window_name": window_name,
            "window_ns": int(
                window_ns
            ),
            "full_coverage_batch_count": int(
                full_coverage_flag.sum()
            ),
            "partial_coverage_batch_count": int(
                (
                    ~full_coverage_flag
                ).sum()
            ),
            "cross_partition_history_batch_count": int(
                cross_partition_history_flag.sum()
            ),
            "total_prior_event_memberships": int(
                event_count.sum()
            ),
            "total_prior_batch_memberships": int(
                prior_batch_count.sum()
            ),
            "total_activated_mark_event_memberships": int(
                activated_event_count.sum()
            ),
            "total_unavailable_mark_event_memberships": int(
                unavailable_mark_event_count.sum()
            ),
            "maximum_event_count": int(
                event_count.max()
            ),
            "maximum_prior_batch_count": int(
                prior_batch_count.max()
            ),
            "status": "PASS",
        }
    )


CLOCK_WINDOW_EVENT_FLOW_AUDIT = (
    pd.DataFrame.from_records(
        clock_window_feature_audit_rows
    )
)


# ------------------------------------------------------------
# Monotonicity across nested clock-time windows
# ------------------------------------------------------------

ordered_clock_window_names = [
    "W250MS",
    "W1S",
    "W5S",
    "W30S",
]

clock_window_monotonicity_rows: list[
    dict[str, Any]
] = []

for metric_name in (
    "event_count",
    "prior_batch_count",
    "activated_event_count",
    "activated_quantity",
    "activated_notional",
):
    previous_values: np.ndarray | None = None
    previous_window_name: str | None = None

    for window_name in (
        ordered_clock_window_names
    ):
        current_values = (
            clock_window_count_registry[
                window_name
            ][
                metric_name
            ]
        )

        if previous_values is not None:
            if metric_name in {
                "activated_quantity",
                "activated_notional",
            }:
                failure_count = int(
                    (
                        current_values
                        + 1e-12
                        < previous_values
                    ).sum()
                )
            else:
                failure_count = int(
                    (
                        current_values
                        < previous_values
                    ).sum()
                )

            clock_window_monotonicity_rows.append(
                {
                    "metric": metric_name,
                    "smaller_window": (
                        previous_window_name
                    ),
                    "larger_window": window_name,
                    "failure_count": (
                        failure_count
                    ),
                    "status": (
                        "PASS"
                        if failure_count == 0
                        else "FAIL"
                    ),
                }
            )

            require(
                failure_count == 0,
                (
                    f"{metric_name} decreases when expanding "
                    f"from {previous_window_name} to "
                    f"{window_name}."
                ),
            )

        previous_values = current_values
        previous_window_name = window_name


CLOCK_WINDOW_MONOTONICITY_AUDIT = (
    pd.DataFrame.from_records(
        clock_window_monotonicity_rows
    )
)


# ------------------------------------------------------------
# Prior completed-batch count windows
#
# These features use only batches [i-N, i). Current batch i is
# never included.
# ------------------------------------------------------------

prior_batch_window_audit_rows: list[
    dict[str, Any]
] = []

batch_position_array = np.arange(
    len(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES
    ),
    dtype="int64",
)

for window_name, prior_batch_count_required in (
    PRIOR_BATCH_COUNT_WINDOWS.items()
):
    window_slug = window_name.lower()

    left_positions = np.maximum(
        0,
        (
            batch_position_array
            - int(
                prior_batch_count_required
            )
        ),
    )

    right_positions = (
        batch_position_array
    )

    observed_prior_batch_count = (
        right_positions
        - left_positions
    ).astype("int64")

    full_coverage_flag = (
        observed_prior_batch_count
        == int(
            prior_batch_count_required
        )
    )

    prior_event_count = causal_slice_sum(
        completed_batch_event_prefix,
        left_positions,
        right_positions,
    ).astype("int64")

    prior_buy_event_count = causal_slice_sum(
        completed_batch_buy_event_prefix,
        left_positions,
        right_positions,
    ).astype("int64")

    prior_sell_event_count = causal_slice_sum(
        completed_batch_sell_event_prefix,
        left_positions,
        right_positions,
    ).astype("int64")

    prior_signed_event_count = (
        prior_buy_event_count
        - prior_sell_event_count
    )

    prior_simultaneous_batch_count = (
        causal_slice_sum(
            completed_batch_simultaneous_prefix,
            left_positions,
            right_positions,
        ).astype("int64")
    )

    prior_mixed_side_batch_count = (
        causal_slice_sum(
            completed_batch_mixed_prefix,
            left_positions,
            right_positions,
        ).astype("int64")
    )

    prior_buy_event_fraction = safe_fraction(
        prior_buy_event_count,
        prior_event_count,
    )

    prior_sell_event_fraction = safe_fraction(
        prior_sell_event_count,
        prior_event_count,
    )

    prior_signed_event_fraction = safe_fraction(
        prior_signed_event_count,
        prior_event_count,
    )

    prior_simultaneous_batch_fraction = (
        safe_fraction(
            prior_simultaneous_batch_count,
            observed_prior_batch_count,
        )
    )

    prior_mixed_side_batch_fraction = (
        safe_fraction(
            prior_mixed_side_batch_count,
            observed_prior_batch_count,
        )
    )

    mean_events_per_batch = safe_fraction(
        prior_event_count,
        observed_prior_batch_count,
    )

    first_prior_partition_order = np.full(
        len(
            BATCH_CAUSAL_EVENT_FLOW_FEATURES
        ),
        -1,
        dtype="int64",
    )

    has_prior_batches = (
        observed_prior_batch_count > 0
    )

    first_prior_partition_order[
        has_prior_batches
    ] = (
        completed_batch_partition_order_array[
            left_positions[
                has_prior_batches
            ]
        ]
    )

    cross_partition_history_flag = (
        has_prior_batches
        & (
            first_prior_partition_order
            < current_batch_partition_order_array
        )
    )

    feature_prefix = (
        f"tminus_prior_batch_{window_slug}"
    )

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_full_coverage_flag"
    ] = full_coverage_flag

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_observed_batch_count"
    ] = observed_prior_batch_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_cross_partition_history_flag"
    ] = cross_partition_history_flag

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_event_count"
    ] = prior_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_buy_event_count"
    ] = prior_buy_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_sell_event_count"
    ] = prior_sell_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_signed_event_count"
    ] = prior_signed_event_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_buy_event_fraction"
    ] = prior_buy_event_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_sell_event_fraction"
    ] = prior_sell_event_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_signed_event_fraction"
    ] = prior_signed_event_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_simultaneous_batch_count"
    ] = prior_simultaneous_batch_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_simultaneous_batch_fraction"
    ] = prior_simultaneous_batch_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_mixed_side_batch_count"
    ] = prior_mixed_side_batch_count

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_mixed_side_batch_fraction"
    ] = prior_mixed_side_batch_fraction

    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        f"{feature_prefix}_mean_events_per_batch"
    ] = mean_events_per_batch

    require(
        np.array_equal(
            prior_buy_event_count
            + prior_sell_event_count,
            prior_event_count,
        ),
        (
            f"{window_name} prior BUY and SELL event counts "
            "do not sum to total prior event count."
        ),
    )

    require(
        np.array_equal(
            observed_prior_batch_count,
            np.minimum(
                batch_position_array,
                int(
                    prior_batch_count_required
                ),
            ),
        ),
        (
            f"{window_name} observed prior-batch coverage does "
            "not match the frozen batch-count window."
        ),
    )

    require(
        (
            prior_simultaneous_batch_count
            <= observed_prior_batch_count
        ).all(),
        (
            f"{window_name} simultaneous-batch count exceeds "
            "the observed prior-batch count."
        ),
    )

    require(
        (
            prior_mixed_side_batch_count
            <= observed_prior_batch_count
        ).all(),
        (
            f"{window_name} mixed-side-batch count exceeds "
            "the observed prior-batch count."
        ),
    )

    prior_batch_window_audit_rows.append(
        {
            "window_name": window_name,
            "requested_prior_batch_count": int(
                prior_batch_count_required
            ),
            "full_coverage_batch_count": int(
                full_coverage_flag.sum()
            ),
            "partial_coverage_batch_count": int(
                (
                    ~full_coverage_flag
                ).sum()
            ),
            "cross_partition_history_batch_count": int(
                cross_partition_history_flag.sum()
            ),
            "maximum_prior_event_count": int(
                prior_event_count.max()
            ),
            "maximum_simultaneous_batch_count": int(
                prior_simultaneous_batch_count.max()
            ),
            "maximum_mixed_side_batch_count": int(
                prior_mixed_side_batch_count.max()
            ),
            "status": "PASS",
        }
    )


PRIOR_BATCH_WINDOW_FEATURE_AUDIT = (
    pd.DataFrame.from_records(
        prior_batch_window_audit_rows
    )
)


# ------------------------------------------------------------
# Strict prior-event recency features
# ------------------------------------------------------------

def previous_time_before_batch(
    source_times: np.ndarray,
    batch_times: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Return previous source time strictly before each batch and
    a Boolean availability flag.
    """
    positions = (
        np.searchsorted(
            source_times,
            batch_times,
            side="left",
        )
        - 1
    )

    available = (
        positions >= 0
    )

    previous_times = np.full(
        len(batch_times),
        -1,
        dtype="int64",
    )

    previous_times[
        available
    ] = source_times[
        positions[
            available
        ]
    ]

    return previous_times, available


buy_event_time_array = (
    event_flow_time_array[
        event_flow_buy_indicator
        == 1
    ]
)

sell_event_time_array = (
    event_flow_time_array[
        event_flow_sell_indicator
        == 1
    ]
)

last_event_time_ns, has_prior_event = (
    previous_time_before_batch(
        event_flow_time_array,
        current_batch_time_array,
    )
)

last_buy_event_time_ns, has_prior_buy_event = (
    previous_time_before_batch(
        buy_event_time_array,
        current_batch_time_array,
    )
)

last_sell_event_time_ns, has_prior_sell_event = (
    previous_time_before_batch(
        sell_event_time_array,
        current_batch_time_array,
    )
)

last_completed_batch_time_ns = np.full(
    len(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES
    ),
    -1,
    dtype="int64",
)

has_prior_completed_batch = (
    batch_position_array > 0
)

last_completed_batch_time_ns[
    has_prior_completed_batch
] = completed_batch_time_array[
    batch_position_array[
        has_prior_completed_batch
    ]
    - 1
]


def elapsed_ms_or_nan(
    current_times: np.ndarray,
    previous_times: np.ndarray,
    available: np.ndarray,
) -> np.ndarray:
    """Return elapsed milliseconds or NaN if unavailable."""
    output = np.full(
        len(current_times),
        np.nan,
        dtype="float64",
    )

    output[
        available
    ] = (
        current_times[
            available
        ]
        - previous_times[
            available
        ]
    ) / 1_000_000.0

    return output


time_since_last_event_ms = elapsed_ms_or_nan(
    current_batch_time_array,
    last_event_time_ns,
    has_prior_event,
)

time_since_last_buy_event_ms = (
    elapsed_ms_or_nan(
        current_batch_time_array,
        last_buy_event_time_ns,
        has_prior_buy_event,
    )
)

time_since_last_sell_event_ms = (
    elapsed_ms_or_nan(
        current_batch_time_array,
        last_sell_event_time_ns,
        has_prior_sell_event,
    )
)

time_since_previous_batch_ms = (
    elapsed_ms_or_nan(
        current_batch_time_array,
        last_completed_batch_time_ns,
        has_prior_completed_batch,
    )
)

require(
    (
        time_since_last_event_ms[
            has_prior_event
        ]
        > 0
    ).all(),
    (
        "A prior event recency value is not strictly "
        "positive."
    ),
)

require(
    (
        time_since_last_buy_event_ms[
            has_prior_buy_event
        ]
        > 0
    ).all(),
    (
        "A prior BUY-event recency value is not strictly "
        "positive."
    ),
)

require(
    (
        time_since_last_sell_event_ms[
            has_prior_sell_event
        ]
        > 0
    ).all(),
    (
        "A prior SELL-event recency value is not strictly "
        "positive."
    ),
)

require(
    (
        time_since_previous_batch_ms[
            has_prior_completed_batch
        ]
        > 0
    ).all(),
    (
        "A previous-batch recency value is not strictly "
        "positive."
    ),
)

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "tminus_has_prior_event_flag"
] = has_prior_event

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "tminus_time_since_last_event_ms"
] = time_since_last_event_ms

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "tminus_has_prior_buy_event_flag"
] = has_prior_buy_event

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "tminus_time_since_last_buy_event_ms"
] = time_since_last_buy_event_ms

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "tminus_has_prior_sell_event_flag"
] = has_prior_sell_event

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "tminus_time_since_last_sell_event_ms"
] = time_since_last_sell_event_ms

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "tminus_has_prior_completed_batch_flag"
] = has_prior_completed_batch

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "tminus_time_since_previous_batch_ms"
] = time_since_previous_batch_ms


# ------------------------------------------------------------
# Prior pure-side batch run
#
# Code:
#   +1 = previous completed batch was BUY-only
#   -1 = previous completed batch was SELL-only
#    0 = no prior batch or previous batch was mixed-side
# ------------------------------------------------------------

completed_batch_side_code = np.zeros(
    len(
        COMPLETED_BATCH_HISTORY_SOURCE
    ),
    dtype="int64",
)

buy_only_mask = (
    (
        completed_batch_buy_event_count_array
        > 0
    )
    & (
        completed_batch_sell_event_count_array
        == 0
    )
)

sell_only_mask = (
    (
        completed_batch_sell_event_count_array
        > 0
    )
    & (
        completed_batch_buy_event_count_array
        == 0
    )
)

completed_batch_side_code[
    buy_only_mask
] = 1

completed_batch_side_code[
    sell_only_mask
] = -1

completed_batch_run_ending_here = np.zeros(
    len(
        COMPLETED_BATCH_HISTORY_SOURCE
    ),
    dtype="int64",
)

for batch_position in range(
    len(
        COMPLETED_BATCH_HISTORY_SOURCE
    )
):
    current_side_code = int(
        completed_batch_side_code[
            batch_position
        ]
    )

    if current_side_code == 0:
        completed_batch_run_ending_here[
            batch_position
        ] = 0

    elif (
        batch_position > 0
        and completed_batch_side_code[
            batch_position - 1
        ]
        == current_side_code
    ):
        completed_batch_run_ending_here[
            batch_position
        ] = (
            completed_batch_run_ending_here[
                batch_position - 1
            ]
            + 1
        )

    else:
        completed_batch_run_ending_here[
            batch_position
        ] = 1


prior_completed_batch_side_code = np.zeros(
    len(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES
    ),
    dtype="int64",
)

prior_pure_side_run_length = np.zeros_like(
    prior_completed_batch_side_code
)

prior_completed_batch_side_code[
    has_prior_completed_batch
] = completed_batch_side_code[
    batch_position_array[
        has_prior_completed_batch
    ]
    - 1
]

prior_pure_side_run_length[
    has_prior_completed_batch
] = completed_batch_run_ending_here[
    batch_position_array[
        has_prior_completed_batch
    ]
    - 1
]

require(
    set(
        np.unique(
            prior_completed_batch_side_code
        )
    ).issubset(
        {
            -1,
            0,
            1,
        }
    ),
    "Prior completed-batch side code has an invalid value.",
)

require(
    (
        prior_pure_side_run_length
        >= 0
    ).all(),
    "Prior pure-side run length is negative.",
)

require(
    (
        prior_pure_side_run_length[
            prior_completed_batch_side_code
            == 0
        ]
        == 0
    ).all(),
    (
        "A mixed or unavailable prior batch has a non-zero "
        "pure-side run length."
    ),
)

require(
    (
        prior_pure_side_run_length[
            prior_completed_batch_side_code
            != 0
        ]
        >= 1
    ).all(),
    (
        "A pure-side prior batch has a zero run length."
    ),
)

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "tminus_prior_completed_batch_side_code"
] = prior_completed_batch_side_code

BATCH_CAUSAL_EVENT_FLOW_FEATURES[
    "tminus_prior_pure_side_run_length"
] = prior_pure_side_run_length


# ------------------------------------------------------------
# Strict cutoff audits
# ------------------------------------------------------------

event_right_positions_global = np.searchsorted(
    event_flow_time_array,
    current_batch_time_array,
    side="left",
)

has_prior_event_global = (
    event_right_positions_global > 0
)

last_included_event_time_global = np.full(
    len(
        current_batch_time_array
    ),
    -1,
    dtype="int64",
)

last_included_event_time_global[
    has_prior_event_global
] = event_flow_time_array[
    event_right_positions_global[
        has_prior_event_global
    ]
    - 1
]

strict_event_cutoff_failure_count = int(
    (
        last_included_event_time_global[
            has_prior_event_global
        ]
        >= current_batch_time_array[
            has_prior_event_global
        ]
    ).sum()
)

batch_right_positions_global = np.searchsorted(
    completed_batch_time_array,
    current_batch_time_array,
    side="left",
)

has_prior_batch_global = (
    batch_right_positions_global > 0
)

last_included_batch_time_global = np.full(
    len(
        current_batch_time_array
    ),
    -1,
    dtype="int64",
)

last_included_batch_time_global[
    has_prior_batch_global
] = completed_batch_time_array[
    batch_right_positions_global[
        has_prior_batch_global
    ]
    - 1
]

strict_batch_cutoff_failure_count = int(
    (
        last_included_batch_time_global[
            has_prior_batch_global
        ]
        >= current_batch_time_array[
            has_prior_batch_global
        ]
    ).sum()
)

require(
    strict_event_cutoff_failure_count == 0,
    (
        "At least one event-flow feature window includes an "
        "event at or after the current batch time."
    ),
)

require(
    strict_batch_cutoff_failure_count == 0,
    (
        "At least one event-flow feature window includes the "
        "current or a later scoring batch."
    ),
)

require(
    same_time_event_inclusion_violation_count == 0,
    (
        "A clock-time feature window included a same-time "
        "primary event."
    ),
)

require(
    activation_timing_violation_count == 0,
    (
        "A clock-time feature window included a mark before "
        "its strict availability cutoff."
    ),
)

require(
    activation_batch_number_violation_count == 0,
    (
        "A clock-time feature window included a mark before "
        "its earliest eligible future scoring batch."
    ),
)


# ------------------------------------------------------------
# Feature registry
# ------------------------------------------------------------

EVENT_FLOW_FEATURE_COLUMNS = [
    column_name
    for column_name in (
        BATCH_CAUSAL_EVENT_FLOW_FEATURES.columns
    )
    if column_name
    not in EVENT_FLOW_IDENTITY_COLUMNS
]

event_flow_feature_registry_rows: list[
    dict[str, Any]
] = []

for feature_name in (
    EVENT_FLOW_FEATURE_COLUMNS
):
    if feature_name.startswith(
        "tminus_event_w250ms_"
    ):
        window_name = "W250MS"
        window_type = "CLOCK_TIME"

    elif feature_name.startswith(
        "tminus_event_w1s_"
    ):
        window_name = "W1S"
        window_type = "CLOCK_TIME"

    elif feature_name.startswith(
        "tminus_event_w5s_"
    ):
        window_name = "W5S"
        window_type = "CLOCK_TIME"

    elif feature_name.startswith(
        "tminus_event_w30s_"
    ):
        window_name = "W30S"
        window_type = "CLOCK_TIME"

    elif feature_name.startswith(
        "tminus_prior_batch_b10_"
    ):
        window_name = "B10"
        window_type = "PRIOR_BATCH_COUNT"

    elif feature_name.startswith(
        "tminus_prior_batch_b50_"
    ):
        window_name = "B50"
        window_type = "PRIOR_BATCH_COUNT"

    else:
        window_name = None
        window_type = "RECENCY_OR_RUN_STATE"

    if "activated_" in feature_name:
        source_artifact = (
            "PRIMARY_ESTIMATION_EVENTS_AND_"
            "DELAYED_MARK_ACTIVATION_LEDGER"
        )

        availability_rule = (
            "event_time_ns in [t-window, t) and "
            "aggregate_mark_available_time_ns < t"
        )

        authority_class = (
            "AVAILABILITY_GATED_EVENT_MARK"
        )

    elif (
        "prior_batch_" in feature_name
        or "simultaneous_batch" in feature_name
        or "mixed_side_batch" in feature_name
        or "previous_batch" in feature_name
        or "completed_batch" in feature_name
        or "pure_side_run" in feature_name
    ):
        source_artifact = (
            "PRIMARY_EXACT_TIME_BATCHES"
        )

        availability_rule = (
            "completed batch time strictly before current "
            "scoring-batch event_time_ns"
        )

        authority_class = (
            "CAUSAL_COMPLETED_BATCH_HISTORY"
        )

    else:
        source_artifact = (
            "PRIMARY_ESTIMATION_EVENTS"
        )

        availability_rule = (
            "primary event time strictly before current "
            "scoring-batch event_time_ns"
        )

        authority_class = (
            "CAUSAL_PRIOR_EVENT_HISTORY"
        )

    if feature_name.endswith(
        "_flag"
    ) or "coverage_" in feature_name:
        authority_class = (
            "DIAGNOSTIC_COVERAGE_CONTROL"
        )

    if (
        "fraction" in feature_name
        or "vwap" in feature_name
        or "time_since" in feature_name
    ):
        missingness_rule = (
            "NaN is required when the denominator or prior "
            "source observation is unavailable."
        )

    elif (
        "rate_per_second" in feature_name
    ):
        missingness_rule = (
            "NaN is required until the full requested clock "
            "window is observable."
        )

    else:
        missingness_rule = (
            "Counts and additive values may be genuine zero; "
            "missing values are not permitted."
        )

    event_flow_feature_registry_rows.append(
        {
            "feature_name": feature_name,
            "source_notebook": (
                "04_EVENT_STREAM_CONSTRUCTION"
            ),
            "source_artifact": source_artifact,
            "observational_unit": (
                CANONICAL_OBSERVATIONAL_UNIT
            ),
            "timing_class": (
                TIMING_CLASS_T_MINUS
            ),
            "window_name": window_name,
            "window_type": window_type,
            "interval_convention": (
                "[t-window, t)"
                if window_type == "CLOCK_TIME"
                else (
                    "previous N completed batches"
                    if window_type
                    == "PRIOR_BATCH_COUNT"
                    else "strictly prior source state"
                )
            ),
            "availability_rule": (
                availability_rule
            ),
            "current_batch_included": False,
            "same_batch_member_included": False,
            "future_information_included": False,
            "authority_class": (
                authority_class
            ),
            "missingness_rule": (
                missingness_rule
            ),
        }
    )


CAUSAL_EVENT_FLOW_FEATURE_REGISTRY = (
    pd.DataFrame.from_records(
        event_flow_feature_registry_rows
    )
)

require(
    CAUSAL_EVENT_FLOW_FEATURE_REGISTRY[
        "feature_name"
    ].is_unique,
    (
        "Causal event-flow feature registry contains "
        "duplicate feature names."
    ),
)

require(
    CAUSAL_EVENT_FLOW_FEATURE_REGISTRY[
        "timing_class"
    ].eq(
        TIMING_CLASS_T_MINUS
    ).all(),
    "A causal event-flow feature has the wrong timing class.",
)

require(
    not CAUSAL_EVENT_FLOW_FEATURE_REGISTRY[
        "current_batch_included"
    ].any(),
    "A causal event-flow feature includes the current batch.",
)

require(
    not CAUSAL_EVENT_FLOW_FEATURE_REGISTRY[
        "same_batch_member_included"
    ].any(),
    (
        "A causal event-flow feature includes a same-batch "
        "member."
    ),
)

require(
    not CAUSAL_EVENT_FLOW_FEATURE_REGISTRY[
        "future_information_included"
    ].any(),
    "A causal event-flow feature includes future information.",
)


# ------------------------------------------------------------
# Missingness and finite-value audit
# ------------------------------------------------------------

event_flow_feature_frame = (
    BATCH_CAUSAL_EVENT_FLOW_FEATURES[
        EVENT_FLOW_FEATURE_COLUMNS
    ]
)

EVENT_FLOW_FEATURE_MISSINGNESS_AUDIT = (
    pd.DataFrame(
        {
            "feature_name": (
                EVENT_FLOW_FEATURE_COLUMNS
            ),
            "missing_count": [
                int(
                    event_flow_feature_frame[
                        column_name
                    ].isna().sum()
                )
                for column_name in (
                    EVENT_FLOW_FEATURE_COLUMNS
                )
            ],
            "nonmissing_count": [
                int(
                    event_flow_feature_frame[
                        column_name
                    ].notna().sum()
                )
                for column_name in (
                    EVENT_FLOW_FEATURE_COLUMNS
                )
            ],
        }
    )
)

numeric_event_flow_columns = [
    column_name
    for column_name in (
        EVENT_FLOW_FEATURE_COLUMNS
    )
    if (
        pd.api.types.is_numeric_dtype(
            event_flow_feature_frame[
                column_name
            ]
        )
        or pd.api.types.is_bool_dtype(
            event_flow_feature_frame[
                column_name
            ]
        )
    )
]

numeric_event_flow_values = (
    event_flow_feature_frame[
        numeric_event_flow_columns
    ]
    .apply(
        pd.to_numeric,
        errors="raise",
    )
    .to_numpy(
        dtype="float64"
    )
)

event_flow_infinite_value_count = int(
    np.isinf(
        numeric_event_flow_values
    ).sum()
)

require(
    event_flow_infinite_value_count == 0,
    (
        "Causal event-flow features contain "
        f"{event_flow_infinite_value_count} infinite values."
    ),
)

event_flow_count_columns = [
    column_name
    for column_name in (
        EVENT_FLOW_FEATURE_COLUMNS
    )
    if (
        column_name.endswith(
            "_count"
        )
        or column_name.endswith(
            "_run_length"
        )
    )
]

for column_name in (
    event_flow_count_columns
):
    values = pd.to_numeric(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES[
            column_name
        ],
        errors="raise",
    )

    require(
        values.notna().all(),
        (
            f"Count-like event-flow feature "
            f"{column_name!r} contains missing values."
        ),
    )

    require(
        values.ge(0).all()
        or column_name.endswith(
            "_signed_event_count"
        )
        or column_name.endswith(
            "_signed_print_count"
        ),
        (
            f"Unsigned count-like feature "
            f"{column_name!r} contains a negative value."
        ),
    )


# ------------------------------------------------------------
# Same-batch feature invariance
# ------------------------------------------------------------

EVENT_FLOW_EVENT_PROJECTION_AUDIT = (
    PRIMARY_EVENT_TO_BATCH_MEMBERSHIP[
        [
            "primary_event_id",
            "primary_event_batch_id",
        ]
    ]
    .merge(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES,
        how="left",
        on="primary_event_batch_id",
        validate="many_to_one",
    )
)

require(
    len(
        EVENT_FLOW_EVENT_PROJECTION_AUDIT
    )
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Event-flow projection changed the primary event "
        "population."
    ),
)

event_flow_batch_invariance = (
    EVENT_FLOW_EVENT_PROJECTION_AUDIT.groupby(
        "primary_event_batch_id",
        observed=True,
        sort=False,
        dropna=False,
    )[
        EVENT_FLOW_FEATURE_COLUMNS
    ]
    .nunique(
        dropna=False
    )
)

event_flow_same_batch_invariance_failure_count = int(
    event_flow_batch_invariance.gt(1).any(
        axis=1
    ).sum()
)

require(
    event_flow_same_batch_invariance_failure_count == 0,
    (
        "At least one simultaneous batch received different "
        "causal event-flow feature values."
    ),
)


# ------------------------------------------------------------
# Leakage-facing forbidden-field audit
# ------------------------------------------------------------

FORBIDDEN_EVENT_FLOW_COLUMNS: Final[
    tuple[str, ...]
] = (
    "batch_event_count",
    "buy_event_count",
    "sell_event_count",
    "unique_side_count",
    "batch_print_count",
    "batch_quantity",
    "batch_notional",
    "event_side",
    "event_side_code",
    "event_quantity",
    "event_notional",
    "event_print_count",
    "aggregate_mark_available_time_ns",
)

forbidden_event_flow_columns_present = sorted(
    set(
        FORBIDDEN_EVENT_FLOW_COLUMNS
    )
    & set(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES.columns
    )
)

future_like_event_flow_columns = sorted(
    column_name
    for column_name in (
        BATCH_CAUSAL_EVENT_FLOW_FEATURES.columns
    )
    if (
        column_name.startswith(
            "future_"
        )
        or column_name.startswith(
            "label_"
        )
        or column_name.startswith(
            "target_"
        )
    )
)

tplus_columns_in_tminus_table = sorted(
    column_name
    for column_name in (
        BATCH_CAUSAL_EVENT_FLOW_FEATURES.columns
    )
    if column_name.startswith(
        "tplus_"
    )
)

require(
    not forbidden_event_flow_columns_present,
    (
        "Causal event-flow feature table contains raw "
        "current-batch fields: "
        f"{forbidden_event_flow_columns_present}"
    ),
)

require(
    not future_like_event_flow_columns,
    (
        "Causal event-flow feature table contains future-like "
        f"fields: {future_like_event_flow_columns}"
    ),
)

require(
    not tplus_columns_in_tminus_table,
    (
        "Causal event-flow feature table contains t-plus "
        f"fields: {tplus_columns_in_tminus_table}"
    ),
)


# ------------------------------------------------------------
# Gate table
# ------------------------------------------------------------

EVENT_FLOW_FEATURE_GATES = pd.DataFrame(
    [
        {
            "gate": (
                "post_batch_context_physically_separate"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    tplus_columns_in_tminus_table
                )
                == 0
            ),
            "evidence": (
                f"post_batch_rows="
                f"{len(BATCH_POST_EVENT_CONTEXT)}"
            ),
        },
        {
            "gate": (
                "event_flow_batch_rows_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    BATCH_CAUSAL_EVENT_FLOW_FEATURES
                )
                == EXPECTED_PRIMARY_BATCH_ROWS
            ),
            "evidence": (
                f"rows="
                f"{len(BATCH_CAUSAL_EVENT_FLOW_FEATURES)}"
            ),
        },
        {
            "gate": (
                "strict_prior_event_cutoff"
            ),
            "severity": "BLOCKING",
            "passed": (
                strict_event_cutoff_failure_count
                == 0
                and same_time_event_inclusion_violation_count
                == 0
            ),
            "evidence": (
                f"cutoff_failures="
                f"{strict_event_cutoff_failure_count}; "
                f"same_time_inclusions="
                f"{same_time_event_inclusion_violation_count}"
            ),
        },
        {
            "gate": (
                "strict_prior_batch_cutoff"
            ),
            "severity": "BLOCKING",
            "passed": (
                strict_batch_cutoff_failure_count
                == 0
            ),
            "evidence": (
                f"cutoff_failures="
                f"{strict_batch_cutoff_failure_count}"
            ),
        },
        {
            "gate": (
                "aggregate_mark_availability_cutoff"
            ),
            "severity": "BLOCKING",
            "passed": (
                activation_timing_violation_count
                == 0
                and activation_batch_number_violation_count
                == 0
            ),
            "evidence": (
                f"timing_violations="
                f"{activation_timing_violation_count}; "
                f"eligible_batch_violations="
                f"{activation_batch_number_violation_count}"
            ),
        },
        {
            "gate": (
                "clock_window_nested_monotonicity"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                CLOCK_WINDOW_MONOTONICITY_AUDIT[
                    "failure_count"
                ].eq(0).all()
            ),
            "evidence": (
                f"comparisons="
                f"{len(CLOCK_WINDOW_MONOTONICITY_AUDIT)}"
            ),
        },
        {
            "gate": (
                "prior_batch_count_windows_verified"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                PRIOR_BATCH_WINDOW_FEATURE_AUDIT[
                    "status"
                ].eq("PASS").all()
            ),
            "evidence": (
                f"windows="
                f"{len(PRIOR_BATCH_WINDOW_FEATURE_AUDIT)}"
            ),
        },
        {
            "gate": (
                "event_flow_same_batch_invariance"
            ),
            "severity": "BLOCKING",
            "passed": (
                event_flow_same_batch_invariance_failure_count
                == 0
            ),
            "evidence": (
                f"failed_batches="
                f"{event_flow_same_batch_invariance_failure_count}"
            ),
        },
        {
            "gate": (
                "event_flow_no_infinite_values"
            ),
            "severity": "BLOCKING",
            "passed": (
                event_flow_infinite_value_count
                == 0
            ),
            "evidence": (
                f"infinite_values="
                f"{event_flow_infinite_value_count}"
            ),
        },
        {
            "gate": (
                "no_current_batch_raw_fields"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    forbidden_event_flow_columns_present
                )
                == 0
            ),
            "evidence": (
                f"forbidden_fields="
                f"{len(forbidden_event_flow_columns_present)}"
            ),
        },
        {
            "gate": (
                "no_future_label_fields"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    future_like_event_flow_columns
                )
                == 0
            ),
            "evidence": (
                f"future_like_fields="
                f"{len(future_like_event_flow_columns)}"
            ),
        },
        {
            "gate": (
                "partial_clock_window_coverage_present"
            ),
            "severity": "WARNING",
            "passed": bool(
                CLOCK_WINDOW_EVENT_FLOW_AUDIT[
                    "partial_coverage_batch_count"
                ].eq(0).all()
            ),
            "evidence": (
                f"partial_memberships="
                f"{int(CLOCK_WINDOW_EVENT_FLOW_AUDIT['partial_coverage_batch_count'].sum())}"
            ),
        },
        {
            "gate": (
                "cross_partition_clock_history_present"
            ),
            "severity": "WARNING",
            "passed": bool(
                CLOCK_WINDOW_EVENT_FLOW_AUDIT[
                    "cross_partition_history_batch_count"
                ].eq(0).all()
            ),
            "evidence": (
                f"count="
                f"{int(CLOCK_WINDOW_EVENT_FLOW_AUDIT['cross_partition_history_batch_count'].sum())}"
            ),
        },
        {
            "gate": (
                "cross_partition_batch_count_history_present"
            ),
            "severity": "WARNING",
            "passed": bool(
                PRIOR_BATCH_WINDOW_FEATURE_AUDIT[
                    "cross_partition_history_batch_count"
                ].eq(0).all()
            ),
            "evidence": (
                f"count="
                f"{int(PRIOR_BATCH_WINDOW_FEATURE_AUDIT['cross_partition_history_batch_count'].sum())}"
            ),
        },
        {
            "gate": (
                "unavailable_marks_excluded"
            ),
            "severity": "WARNING",
            "passed": bool(
                CLOCK_WINDOW_EVENT_FLOW_AUDIT[
                    "total_unavailable_mark_event_memberships"
                ].eq(0).all()
            ),
            "evidence": (
                f"excluded_memberships="
                f"{int(CLOCK_WINDOW_EVENT_FLOW_AUDIT['total_unavailable_mark_event_memberships'].sum())}"
            ),
        },
    ]
)

EVENT_FLOW_FEATURE_GATES[
    "status"
] = np.select(
    [
        EVENT_FLOW_FEATURE_GATES[
            "passed"
        ],
        EVENT_FLOW_FEATURE_GATES[
            "severity"
        ].eq("BLOCKING"),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

event_flow_blocking_failures = (
    EVENT_FLOW_FEATURE_GATES.loc[
        EVENT_FLOW_FEATURE_GATES[
            "severity"
        ].eq("BLOCKING")
        & ~EVENT_FLOW_FEATURE_GATES[
            "passed"
        ]
    ]
)

require(
    event_flow_blocking_failures.empty,
    (
        "Causal event-flow feature construction contains "
        "blocking failures."
    ),
)


# ------------------------------------------------------------
# Frozen downstream state
# ------------------------------------------------------------

CAUSAL_EVENT_FLOW_FEATURES_VERIFIED: Final[
    bool
] = True

POST_BATCH_CONTEXT_VERIFIED: Final[
    bool
] = True

CAUSAL_EVENT_FLOW_FEATURE_ROW_COUNT: Final[
    int
] = int(
    len(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES
    )
)

CAUSAL_EVENT_FLOW_FEATURE_COUNT: Final[
    int
] = int(
    len(
        CAUSAL_EVENT_FLOW_FEATURE_REGISTRY
    )
)


# ------------------------------------------------------------
# Compact displays
# ------------------------------------------------------------

display(
    BATCH_POST_EVENT_CONTEXT.head(10)
)

display(
    CLOCK_WINDOW_EVENT_FLOW_AUDIT
)

display(
    CLOCK_WINDOW_MONOTONICITY_AUDIT
)

display(
    PRIOR_BATCH_WINDOW_FEATURE_AUDIT
)

display(
    EVENT_FLOW_FEATURE_MISSINGNESS_AUDIT.loc[
        EVENT_FLOW_FEATURE_MISSINGNESS_AUDIT[
            "missing_count"
        ].gt(0)
    ]
)

display(
    EVENT_FLOW_FEATURE_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "post_batch_context_verified": (
        POST_BATCH_CONTEXT_VERIFIED
    ),
    "causal_event_flow_features_verified": (
        CAUSAL_EVENT_FLOW_FEATURES_VERIFIED
    ),
    "observational_unit": (
        CANONICAL_OBSERVATIONAL_UNIT
    ),
    "timing_class": (
        TIMING_CLASS_T_MINUS
    ),
    "batch_rows": (
        CAUSAL_EVENT_FLOW_FEATURE_ROW_COUNT
    ),
    "event_flow_feature_count": (
        CAUSAL_EVENT_FLOW_FEATURE_COUNT
    ),
    "clock_window_count": int(
        len(
            CLOCK_TIME_WINDOWS_NS
        )
    ),
    "prior_batch_window_count": int(
        len(
            PRIOR_BATCH_COUNT_WINDOWS
        )
    ),
    "post_batch_context_rows": int(
        len(
            BATCH_POST_EVENT_CONTEXT
        )
    ),
    "strict_event_cutoff_failures": int(
        strict_event_cutoff_failure_count
    ),
    "strict_batch_cutoff_failures": int(
        strict_batch_cutoff_failure_count
    ),
    "same_time_event_inclusions": int(
        same_time_event_inclusion_violation_count
    ),
    "mark_availability_timing_violations": int(
        activation_timing_violation_count
    ),
    "mark_activation_batch_violations": int(
        activation_batch_number_violation_count
    ),
    "same_batch_invariance_failures": int(
        event_flow_same_batch_invariance_failure_count
    ),
    "infinite_feature_values": int(
        event_flow_infinite_value_count
    ),
    "current_batch_raw_fields_attached": False,
    "tplus_fields_attached": False,
    "future_labels_attached": False,
    "verified_at_utc": utc_now_iso(),
}

C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1536: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1544: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1551: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1555: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1559: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1563: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1567: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1571: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1575: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1579: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1583: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1587: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1591: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1595: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1599: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1603: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1607: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1611: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1615: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1619: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1623: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1627: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1631: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1635: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1639: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1643: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1647: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1651: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1655: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1659: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1663: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1667: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1671: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1675: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1679: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1683: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1687: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1691: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1695: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1699: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1703: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1707: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1711: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1715: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1719: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1723: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1727: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1536: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1544: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[
C:\Users\Bryan\AppData\Local\Temp\ipykernel_23784\1047796601.py:1551: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BATCH_CAUSAL_EVENT_FLOW_FEATURES[

,primary_event_batch_id,primary_event_batch_number,partition_batch_index,event_partition_order,event_partition,event_time_ns,tplus_current_batch_event_count,tplus_current_batch_buy_event_count,tplus_current_batch_sell_event_count,tplus_current_batch_unique_side_count,tplus_current_batch_print_count,tplus_current_batch_quantity,tplus_current_batch_notional,tplus_current_batch_mixed_side_flag,tplus_current_batch_simultaneous_flag,timing_class,authorized_in_tminus_feature_table,available_only_after_all_batch_members_scored
0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000001,1,1,1,DEVELOPMENT,1783665468766951600,1,1,0,1,1,0.00046,29.400610,False,False,T_PLUS,False,True
1,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000002,2,2,1,DEVELOPMENT,1783665469052166500,1,1,0,1,1,0.00060,38.348622,False,False,T_PLUS,False,True
2,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000003,3,3,1,DEVELOPMENT,1783665469437964400,1,1,0,1,1,0.00020,12.782874,False,False,T_PLUS,False,True
3,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000004,4,4,1,DEVELOPMENT,1783665469692104200,1,1,0,1,1,0.00039,24.926604,False,False,T_PLUS,False,True
4,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000005,5,5,1,DEVELOPMENT,1783665470242312100,1,0,1,1,1,0.00046,29.400606,False,False,T_PLUS,False,True
5,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000006,6,6,1,DEVELOPMENT,1783665470304239100,1,0,1,1,1,0.00018,11.504585,False,False,T_PLUS,False,True
6,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000007,7,7,1,DEVELOPMENT,1783665470597198800,1,0,1,1,1,0.03495,2233.806882,False,False,T_PLUS,False,True
7,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,8,8,1,DEVELOPMENT,1783665471662326600,1,0,1,1,1,0.00056,35.792042,False,False,T_PLUS,False,True
8,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000009,9,9,1,DEVELOPMENT,1783665471742062100,1,0,1,1,1,0.00020,12.782872,False,False,T_PLUS,False,True
9,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000010,10,10,1,DEVELOPMENT,1783665471862162900,1,1,0,1,1,0.00046,29.400610,False,False,T_PLUS,False,True

,window_name,window_ns,full_coverage_batch_count,partial_coverage_batch_count,cross_partition_history_batch_count,total_prior_event_memberships,total_prior_batch_memberships,total_activated_mark_event_memberships,total_unavailable_mark_event_memberships,maximum_event_count,maximum_prior_batch_count,status
0,W250MS,250000000,13564,0,3,23137,21564,22725,412,31,26,PASS
1,W1S,1000000000,13564,0,7,65870,63065,65458,412,52,47,PASS
2,W5S,5000000000,13552,12,58,289294,280414,288882,412,88,78,PASS
3,W30S,30000000000,13437,127,457,1618879,1580150,1618467,412,218,207,PASS

                   metric smaller_window larger_window  failure_count status
0             event_count         W250MS           W1S              0   PASS
1             event_count            W1S           W5S              0   PASS
2             event_count            W5S          W30S              0   PASS
3       prior_batch_count         W250MS           W1S              0   PASS
4       prior_batch_count            W1S           W5S              0   PASS
5       prior_batch_count            W5S          W30S              0   PASS
6   activated_event_count         W250MS           W1S              0   PASS
7   activated_event_count            W1S           W5S              0   PASS
8   activated_event_count            W5S          W30S              0   PASS
9      activated_quantity         W250MS           W1S              0   PASS
10     activated_quantity            W1S           W5S              0   PASS
11     activated_quantity            W5S          W30S              0   PASS
12     activated_notional         W250MS           W1S              0   PASS
13     activated_notional            W1S           W5S              0   PASS
14     activated_notional            W5S          W30S              0   PASS

  window_name  requested_prior_batch_count  full_coverage_batch_count  partial_coverage_batch_count  cross_partition_history_batch_count  maximum_prior_event_count  maximum_simultaneous_batch_count  maximum_mixed_side_batch_count status
0         B10                           10                      13554                            10                                   30                         20                                 5                               2   PASS
1         B50                           50                      13514                            50                                  150                         70                                12                               3   PASS

                                             feature_name  missing_count  nonmissing_count
8                  tminus_event_w250ms_buy_event_fraction           5102              8462
9                 tminus_event_w250ms_sell_event_fraction           5102              8462
10              tminus_event_w250ms_signed_event_fraction           5102              8462
20        tminus_event_w250ms_simultaneous_batch_fraction           5102              8462
22          tminus_event_w250ms_mixed_side_batch_fraction           5102              8462
23              tminus_event_w250ms_mean_events_per_batch           5102              8462
28            tminus_event_w250ms_activated_mark_fraction           5102              8462
47                     tminus_event_w250ms_activated_vwap           5141              8423
56                    tminus_event_w1s_buy_event_fraction            496             13068
57                   tminus_event_w1s_sell_event_fraction            496             13068
58                 tminus_event_w1s_signed_event_fraction            496             13068
68           tminus_event_w1s_simultaneous_batch_fraction            496             13068
70             tminus_event_w1s_mixed_side_batch_fraction            496             13068
71                 tminus_event_w1s_mean_events_per_batch            496             13068
76               tminus_event_w1s_activated_mark_fraction            496             13068
95                        tminus_event_w1s_activated_vwap            498             13066
104                   tminus_event_w5s_buy_event_fraction              1             13563
105                  tminus_event_w5s_sell_event_fraction              1             13563
106                tminus_event_w5s_signed_event_fraction              1             13563
107                tminus_event_w5s_event_rate_per_second             12             13552
108            tminus_event_w5s_buy_event_rate_per_second             12             13552
109           tminus_event_w5s_sell_event_rate_per_second             12             13552
114          tminus_event_w5s_prior_batch_rate_per_second             12             13552
116          tminus_event_w5s_simultaneous_batch_fraction              1             13563
118            tminus_event_w5s_mixed_side_batch_fraction              1             13563
119                tminus_event_w5s_mean_events_per_batch              1             13563
124              tminus_event_w5s_activated_mark_fraction              1             13563
132      tminus_event_w5s_activated_print_rate_per_second             12             13552
137   tminus_event_w5s_activated_quantity_rate_per_second             12             13552
142   tminus_event_w5s_activated_notional_rate_per_second             12             13552
143                       tminus_event_w5s_activated_vwap              1             13563
152                  tminus_event_w30s_buy_event_fraction              1             13563
153                 tminus_event_w30s_sell_event_fraction              1             13563
154               tminus_event_w30s_signed_event_fraction              1             13563
155               tminus_event_w30s_event_rate_per_second            127             13437
156           tminus_event_w30s_buy_event_rate_per_second            127             13437
157          tminus_event_w30s_sell_event_rate_per_second            127             13437
162         tminus_event_w30s_prior_batch_rate_per_second            127             13437
164         tminus_event_w30s_simultaneous_batch_fraction              1             13563
166           tminus_event_w30s_mixed_side_batch_fraction              1             13563
167               tminus_event_w30s_mean_events_per_batch              1             13563
172             tminus_event_w30s_activated_mark_fraction              1             13563
180     tminus_event_w30s_activated_print_rate_per_second            127             13437
185  tminus_event_w30s_activated_quantity_rate_per_second            127             13437
190  tminus_event_w30s_activated_notional_rate_per_second            127             13437
191                      tminus_event_w30s_activated_vwap              1             13563
199             tminus_prior_batch_b10_buy_event_fraction              1             13563
200            tminus_prior_batch_b10_sell_event_fraction              1             13563
201          tminus_prior_batch_b10_signed_event_fraction              1             13563
203    tminus_prior_batch_b10_simultaneous_batch_fraction              1             13563
205      tminus_prior_batch_b10_mixed_side_batch_fraction              1             13563
206          tminus_prior_batch_b10_mean_events_per_batch              1             13563
214             tminus_prior_batch_b50_buy_event_fraction              1             13563
215            tminus_prior_batch_b50_sell_event_fraction              1             13563
216          tminus_prior_batch_b50_signed_event_fraction              1             13563
218    tminus_prior_batch_b50_simultaneous_batch_fraction              1             13563
220      tminus_prior_batch_b50_mixed_side_batch_fraction              1             13563
221          tminus_prior_batch_b50_mean_events_per_batch              1             13563
223                       tminus_time_since_last_event_ms              1             13563
225                   tminus_time_since_last_buy_event_ms              1             13563
227                  tminus_time_since_last_sell_event_ms              5             13559
229                   tminus_time_since_previous_batch_ms              1             13563

                                           gate  severity   status                                          evidence
0        post_batch_context_physically_separate  BLOCKING     PASS                             post_batch_rows=13564
1               event_flow_batch_rows_conserved  BLOCKING     PASS                                        rows=13564
2                     strict_prior_event_cutoff  BLOCKING     PASS         cutoff_failures=0; same_time_inclusions=0
3                     strict_prior_batch_cutoff  BLOCKING     PASS                                 cutoff_failures=0
4            aggregate_mark_availability_cutoff  BLOCKING     PASS  timing_violations=0; eligible_batch_violations=0
5              clock_window_nested_monotonicity  BLOCKING     PASS                                    comparisons=15
6            prior_batch_count_windows_verified  BLOCKING     PASS                                         windows=2
7              event_flow_same_batch_invariance  BLOCKING     PASS                                  failed_batches=0
8                 event_flow_no_infinite_values  BLOCKING     PASS                                 infinite_values=0
9                   no_current_batch_raw_fields  BLOCKING     PASS                                forbidden_fields=0
10                       no_future_label_fields  BLOCKING     PASS                              future_like_fields=0
11        partial_clock_window_coverage_present   WARNING  WARNING                           partial_memberships=139
12        cross_partition_clock_history_present   WARNING  WARNING                                         count=525
13  cross_partition_batch_count_history_present   WARNING  WARNING                                         count=180
14                   unavailable_marks_excluded   WARNING  WARNING                         excluded_memberships=1648

{'status': 'PASS',
 'post_batch_context_verified': True,
 'causal_event_flow_features_verified': True,
 'observational_unit': 'PRIMARY_SCORING_BATCH',
 'timing_class': 'T_MINUS',
 'batch_rows': 13564,
 'event_flow_feature_count': 232,
 'clock_window_count': 4,
 'prior_batch_window_count': 2,
 'post_batch_context_rows': 13564,
 'strict_event_cutoff_failures': 0,
 'strict_batch_cutoff_failures': 0,
 'same_time_event_inclusions': 0,
 'mark_availability_timing_violations': 0,
 'mark_activation_batch_violations': 0,
 'same_batch_invariance_failures': 0,
 'infinite_feature_values': 0,
 'current_batch_raw_fields_attached': False,
 'tplus_fields_attached': False,
 'future_labels_attached': False,
 'verified_at_utc': '2026-07-19T09:34:08.382150+00:00'}

In [11]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 12 — Causal visible-book update flow, level-one OFI,
#           price variation, volatility, and book recency
# ============================================================


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "CAUSAL_EVENT_FLOW_FEATURES_VERIFIED",
        False,
    )
    is True,
    "Causal event-flow features have not been verified.",
)

require(
    globals().get(
        "STATIC_VISIBLE_BOOK_FEATURES_VERIFIED",
        False,
    )
    is True,
    "Static visible-book features have not been verified.",
)

require(
    globals().get(
        "COMMON_PRE_BATCH_BOOK_INTERFACE_VERIFIED",
        False,
    )
    is True,
    "Common pre-batch book interface has not been verified.",
)

require(
    globals().get(
        "ROLLING_WINDOW_CONTRACT_VERIFIED",
        False,
    )
    is True,
    "Rolling-window contract has not been verified.",
)

require(
    len(RECONSTRUCTED_BOOK_STATES)
    == EXPECTED_RECONSTRUCTED_BOOK_STATES,
    (
        "Reconstructed-book row count changed before "
        "book-flow feature construction."
    ),
)

require(
    len(COMMON_PRE_BATCH_BOOK_STATES)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Common pre-batch book-state row count changed before "
        "book-flow feature construction."
    ),
)


# ------------------------------------------------------------
# Defragment previously constructed wide feature frames
#
# Wide columns were constructed incrementally in prior cells.
# A deep copy consolidates the internal pandas blocks before
# subsequent joins and persistence.
# ------------------------------------------------------------

BATCH_CAUSAL_EVENT_FLOW_FEATURES = (
    BATCH_CAUSAL_EVENT_FLOW_FEATURES.copy(
        deep=True
    )
)

BATCH_STATIC_VISIBLE_BOOK_FEATURES = (
    BATCH_STATIC_VISIBLE_BOOK_FEATURES.copy(
        deep=True
    )
)

EVENT_FLOW_FRAME_DEFRAGMENTED: Final[
    bool
] = True

STATIC_BOOK_FRAME_DEFRAGMENTED: Final[
    bool
] = True


# ------------------------------------------------------------
# Frozen visible-book history rule
#
# Book history differs from event history at the upper bound:
#
#   local_receipt_time_ns < batch time
#
# or:
#
#   local_receipt_time_ns == batch time
#   and collector_sequence <
#       minimum initiating trade sequence in the batch
#
# Therefore same-time book states are permitted only when they
# are already causally available in collector trace order.
# ------------------------------------------------------------

BOOK_HISTORY_INTERVAL_CONVENTION: Final[str] = (
    "[t-window, t] WITH LOCAL_STRICT_SEQUENCE_CUTOFF"
)

BOOK_HISTORY_UPPER_BOUND_RULE: Final[str] = (
    "book_local_receipt_time_ns < event_time_ns OR "
    "(book_local_receipt_time_ns == event_time_ns AND "
    "book_collector_sequence < "
    "batch_min_initiating_trade_collector_sequence)"
)

BOOK_HISTORY_LOWER_BOUND_RULE: Final[str] = (
    "book_local_receipt_time_ns >= event_time_ns - window_ns"
)

BOOK_FLOW_OFI_DEFINITION: Final[str] = (
    "Cont-style level-one order-flow imbalance from "
    "consecutive reconstructed visible-book states"
)


# ------------------------------------------------------------
# Required Notebook 02 source schema
# ------------------------------------------------------------

BOOK_FLOW_REQUIRED_COLUMNS: Final[
    tuple[str, ...]
] = (
    "book_state_id",
    "collector_sequence",
    "local_receipt_time_ns",
    "partition",
    "bid_message_level_count",
    "ask_message_level_count",
    "message_level_count",
    "message_delete_count",
    "inserted_level_count",
    "replaced_level_count",
    "unchanged_replacement_count",
    "deleted_level_count",
    "absent_delete_noop_count",
    "actual_changed_level_count",
    "best_bid",
    "best_ask",
    "best_bid_quantity",
    "best_ask_quantity",
    "spread",
    "spread_basis_points",
    "midpoint",
    "microprice",
    "top_level_imbalance",
    "multi_level_imbalance",
    "visible_bid_depth_top_10",
    "visible_ask_depth_top_10",
    "visible_total_depth_top_10",
    "best_bid_change",
    "best_ask_change",
    "midpoint_change",
    "top_of_book_moved",
    "top_10_changed",
    "movement_code",
    "top_10_state_sha256",
    "state_accepted",
    "locked_state",
    "crossed_state",
    "incomplete_state",
    "stale_interval",
)

require_columns(
    RECONSTRUCTED_BOOK_STATES,
    BOOK_FLOW_REQUIRED_COLUMNS,
    "RECONSTRUCTED_BOOK_STATES",
)


# ------------------------------------------------------------
# Prepare authoritative ordered visible-book source
# ------------------------------------------------------------

BOOK_FLOW_SOURCE = (
    RECONSTRUCTED_BOOK_STATES.copy()
    .sort_values(
        [
            "collector_sequence",
            "book_state_id",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

require_unique_columns(
    BOOK_FLOW_SOURCE,
    "BOOK_FLOW_SOURCE",
)

BOOK_FLOW_SOURCE[
    "book_state_id"
] = parse_required_int64(
    BOOK_FLOW_SOURCE[
        "book_state_id"
    ],
    "BOOK_FLOW_SOURCE.book_state_id",
)

BOOK_FLOW_SOURCE[
    "collector_sequence"
] = parse_required_int64(
    BOOK_FLOW_SOURCE[
        "collector_sequence"
    ],
    "BOOK_FLOW_SOURCE.collector_sequence",
)

BOOK_FLOW_SOURCE[
    "local_receipt_time_ns"
] = parse_required_int64(
    BOOK_FLOW_SOURCE[
        "local_receipt_time_ns"
    ],
    "BOOK_FLOW_SOURCE.local_receipt_time_ns",
)

BOOK_FLOW_SOURCE[
    "partition"
] = (
    BOOK_FLOW_SOURCE[
        "partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

BOOK_FLOW_SOURCE[
    "book_partition_order"
] = (
    BOOK_FLOW_SOURCE[
        "partition"
    ]
    .map(PARTITION_ORDER_MAP)
)

require(
    BOOK_FLOW_SOURCE[
        "book_partition_order"
    ].notna().all(),
    (
        "At least one reconstructed book state has an "
        "unknown partition."
    ),
)

BOOK_FLOW_SOURCE[
    "book_partition_order"
] = (
    BOOK_FLOW_SOURCE[
        "book_partition_order"
    ].astype("int64")
)

require(
    len(BOOK_FLOW_SOURCE)
    == EXPECTED_RECONSTRUCTED_BOOK_STATES,
    "Book-flow source changed the reconstructed-state count.",
)

require(
    BOOK_FLOW_SOURCE[
        "book_state_id"
    ].is_unique,
    "Book-flow source contains duplicate book-state IDs.",
)

require(
    BOOK_FLOW_SOURCE[
        "collector_sequence"
    ].is_unique,
    (
        "Book-flow source contains duplicate collector "
        "sequences."
    ),
)

require(
    BOOK_FLOW_SOURCE[
        "collector_sequence"
    ].is_monotonic_increasing,
    (
        "Book-flow source collector sequences are not "
        "strictly increasing."
    ),
)

require(
    BOOK_FLOW_SOURCE[
        "local_receipt_time_ns"
    ].is_monotonic_increasing,
    (
        "Book-flow source local receipt times are not "
        "non-decreasing."
    ),
)


# ------------------------------------------------------------
# Structural quality flags
# ------------------------------------------------------------

book_state_accepted = strict_boolean_series(
    BOOK_FLOW_SOURCE[
        "state_accepted"
    ],
    field_name=(
        "BOOK_FLOW_SOURCE.state_accepted"
    ),
)

book_locked_state = strict_boolean_series(
    BOOK_FLOW_SOURCE[
        "locked_state"
    ],
    field_name=(
        "BOOK_FLOW_SOURCE.locked_state"
    ),
)

book_crossed_state = strict_boolean_series(
    BOOK_FLOW_SOURCE[
        "crossed_state"
    ],
    field_name=(
        "BOOK_FLOW_SOURCE.crossed_state"
    ),
)

book_incomplete_state = strict_boolean_series(
    BOOK_FLOW_SOURCE[
        "incomplete_state"
    ],
    field_name=(
        "BOOK_FLOW_SOURCE.incomplete_state"
    ),
)

book_stale_interval = strict_boolean_series(
    BOOK_FLOW_SOURCE[
        "stale_interval"
    ],
    field_name=(
        "BOOK_FLOW_SOURCE.stale_interval"
    ),
)

require(
    book_state_accepted.all(),
    "Book-flow source contains a rejected book state.",
)

require(
    not book_locked_state.any(),
    "Book-flow source contains a locked state.",
)

require(
    not book_crossed_state.any(),
    "Book-flow source contains a crossed state.",
)

require(
    not book_incomplete_state.any(),
    "Book-flow source contains an incomplete state.",
)


# ------------------------------------------------------------
# Strict numeric parsing
# ------------------------------------------------------------

book_best_bid = parse_required_float64(
    BOOK_FLOW_SOURCE[
        "best_bid"
    ],
    "BOOK_FLOW_SOURCE.best_bid",
)

book_best_ask = parse_required_float64(
    BOOK_FLOW_SOURCE[
        "best_ask"
    ],
    "BOOK_FLOW_SOURCE.best_ask",
)

book_best_bid_quantity = (
    parse_required_float64(
        BOOK_FLOW_SOURCE[
            "best_bid_quantity"
        ],
        "BOOK_FLOW_SOURCE.best_bid_quantity",
    )
)

book_best_ask_quantity = (
    parse_required_float64(
        BOOK_FLOW_SOURCE[
            "best_ask_quantity"
        ],
        "BOOK_FLOW_SOURCE.best_ask_quantity",
    )
)

book_spread = parse_required_float64(
    BOOK_FLOW_SOURCE[
        "spread"
    ],
    "BOOK_FLOW_SOURCE.spread",
)

book_spread_bps = parse_required_float64(
    BOOK_FLOW_SOURCE[
        "spread_basis_points"
    ],
    "BOOK_FLOW_SOURCE.spread_basis_points",
)

book_midpoint = parse_required_float64(
    BOOK_FLOW_SOURCE[
        "midpoint"
    ],
    "BOOK_FLOW_SOURCE.midpoint",
)

book_microprice = parse_required_float64(
    BOOK_FLOW_SOURCE[
        "microprice"
    ],
    "BOOK_FLOW_SOURCE.microprice",
)

book_l1_imbalance = parse_required_float64(
    BOOK_FLOW_SOURCE[
        "top_level_imbalance"
    ],
    "BOOK_FLOW_SOURCE.top_level_imbalance",
)

book_top10_imbalance = parse_required_float64(
    BOOK_FLOW_SOURCE[
        "multi_level_imbalance"
    ],
    "BOOK_FLOW_SOURCE.multi_level_imbalance",
)

book_bid_depth_top10 = parse_required_float64(
    BOOK_FLOW_SOURCE[
        "visible_bid_depth_top_10"
    ],
    (
        "BOOK_FLOW_SOURCE."
        "visible_bid_depth_top_10"
    ),
)

book_ask_depth_top10 = parse_required_float64(
    BOOK_FLOW_SOURCE[
        "visible_ask_depth_top_10"
    ],
    (
        "BOOK_FLOW_SOURCE."
        "visible_ask_depth_top_10"
    ),
)

book_total_depth_top10 = (
    parse_required_float64(
        BOOK_FLOW_SOURCE[
            "visible_total_depth_top_10"
        ],
        (
            "BOOK_FLOW_SOURCE."
            "visible_total_depth_top_10"
        ),
    )
)


BOOK_ACTION_COUNT_COLUMNS: Final[
    tuple[str, ...]
] = (
    "bid_message_level_count",
    "ask_message_level_count",
    "message_level_count",
    "message_delete_count",
    "inserted_level_count",
    "replaced_level_count",
    "unchanged_replacement_count",
    "deleted_level_count",
    "absent_delete_noop_count",
    "actual_changed_level_count",
)

book_action_arrays: dict[
    str,
    np.ndarray,
] = {}

for column_name in (
    BOOK_ACTION_COUNT_COLUMNS
):
    parsed_values = parse_required_int64(
        BOOK_FLOW_SOURCE[
            column_name
        ],
        f"BOOK_FLOW_SOURCE.{column_name}",
    )

    require(
        parsed_values.ge(0).all(),
        (
            f"Book action field {column_name!r} contains "
            "a negative value."
        ),
    )

    book_action_arrays[
        column_name
    ] = parsed_values.to_numpy(
        dtype="int64"
    )


# ------------------------------------------------------------
# Recompute consecutive visible-book transitions
# ------------------------------------------------------------

book_row_count = len(
    BOOK_FLOW_SOURCE
)

book_position_array = np.arange(
    book_row_count,
    dtype="int64",
)

book_best_bid_array = (
    book_best_bid.to_numpy(
        dtype="float64"
    )
)

book_best_ask_array = (
    book_best_ask.to_numpy(
        dtype="float64"
    )
)

book_best_bid_quantity_array = (
    book_best_bid_quantity.to_numpy(
        dtype="float64"
    )
)

book_best_ask_quantity_array = (
    book_best_ask_quantity.to_numpy(
        dtype="float64"
    )
)

book_spread_array = (
    book_spread.to_numpy(
        dtype="float64"
    )
)

book_spread_bps_array = (
    book_spread_bps.to_numpy(
        dtype="float64"
    )
)

book_midpoint_array = (
    book_midpoint.to_numpy(
        dtype="float64"
    )
)

book_microprice_array = (
    book_microprice.to_numpy(
        dtype="float64"
    )
)

book_l1_imbalance_array = (
    book_l1_imbalance.to_numpy(
        dtype="float64"
    )
)

book_top10_imbalance_array = (
    book_top10_imbalance.to_numpy(
        dtype="float64"
    )
)

book_bid_depth_top10_array = (
    book_bid_depth_top10.to_numpy(
        dtype="float64"
    )
)

book_ask_depth_top10_array = (
    book_ask_depth_top10.to_numpy(
        dtype="float64"
    )
)

book_total_depth_top10_array = (
    book_total_depth_top10.to_numpy(
        dtype="float64"
    )
)

book_time_array = (
    BOOK_FLOW_SOURCE[
        "local_receipt_time_ns"
    ]
    .astype("int64")
    .to_numpy()
)

book_sequence_array = (
    BOOK_FLOW_SOURCE[
        "collector_sequence"
    ]
    .astype("int64")
    .to_numpy()
)

book_state_id_array = (
    BOOK_FLOW_SOURCE[
        "book_state_id"
    ]
    .astype("int64")
    .to_numpy()
)

book_partition_order_array = (
    BOOK_FLOW_SOURCE[
        "book_partition_order"
    ]
    .astype("int64")
    .to_numpy()
)


book_transition_valid = np.zeros(
    book_row_count,
    dtype=bool,
)

book_transition_valid[
    1:
] = True


recomputed_best_bid_change = np.zeros(
    book_row_count,
    dtype="float64",
)

recomputed_best_ask_change = np.zeros(
    book_row_count,
    dtype="float64",
)

recomputed_midpoint_change = np.zeros(
    book_row_count,
    dtype="float64",
)

recomputed_spread_change = np.zeros(
    book_row_count,
    dtype="float64",
)

recomputed_bid_depth_top10_change = np.zeros(
    book_row_count,
    dtype="float64",
)

recomputed_ask_depth_top10_change = np.zeros(
    book_row_count,
    dtype="float64",
)

recomputed_total_depth_top10_change = np.zeros(
    book_row_count,
    dtype="float64",
)

recomputed_log_midpoint_return = np.zeros(
    book_row_count,
    dtype="float64",
)

recomputed_best_bid_change[
    1:
] = np.diff(
    book_best_bid_array
)

recomputed_best_ask_change[
    1:
] = np.diff(
    book_best_ask_array
)

recomputed_midpoint_change[
    1:
] = np.diff(
    book_midpoint_array
)

recomputed_spread_change[
    1:
] = np.diff(
    book_spread_array
)

recomputed_bid_depth_top10_change[
    1:
] = np.diff(
    book_bid_depth_top10_array
)

recomputed_ask_depth_top10_change[
    1:
] = np.diff(
    book_ask_depth_top10_array
)

recomputed_total_depth_top10_change[
    1:
] = np.diff(
    book_total_depth_top10_array
)

recomputed_log_midpoint_return[
    1:
] = np.log(
    book_midpoint_array[
        1:
    ]
    / book_midpoint_array[
        :-1
    ]
)


# ------------------------------------------------------------
# Recompute movement classifications
# ------------------------------------------------------------

recomputed_top_of_book_moved = np.zeros(
    book_row_count,
    dtype=bool,
)

recomputed_top_of_book_moved[
    0
] = True

recomputed_top_of_book_moved[
    1:
] = (
    (
        book_best_bid_array[
            1:
        ]
        != book_best_bid_array[
            :-1
        ]
    )
    | (
        book_best_ask_array[
            1:
        ]
        != book_best_ask_array[
            :-1
        ]
    )
)

book_top10_hash_array = (
    BOOK_FLOW_SOURCE[
        "top_10_state_sha256"
    ]
    .astype("string")
    .to_numpy()
)

recomputed_top10_changed = np.zeros(
    book_row_count,
    dtype=bool,
)

recomputed_top10_changed[
    0
] = True

recomputed_top10_changed[
    1:
] = (
    book_top10_hash_array[
        1:
    ]
    != book_top10_hash_array[
        :-1
    ]
)


recomputed_midpoint_direction = np.sign(
    recomputed_midpoint_change
).astype("int64")

recomputed_spread_direction = np.sign(
    recomputed_spread_change
).astype("int64")


recomputed_movement_code = np.full(
    book_row_count,
    "NO_VISIBLE_TOP_10_CHANGE",
    dtype=object,
)

recomputed_movement_code[
    0
] = "INITIAL_APPLIED_STATE"

midpoint_up_mask = (
    book_transition_valid
    & (
        recomputed_midpoint_direction
        > 0
    )
)

midpoint_down_mask = (
    book_transition_valid
    & (
        recomputed_midpoint_direction
        < 0
    )
)

flat_midpoint_quote_change_mask = (
    book_transition_valid
    & (
        recomputed_midpoint_direction
        == 0
    )
    & recomputed_top_of_book_moved
)

depth_only_change_mask = (
    book_transition_valid
    & (
        recomputed_midpoint_direction
        == 0
    )
    & ~recomputed_top_of_book_moved
    & recomputed_top10_changed
)

recomputed_movement_code[
    midpoint_up_mask
] = "MIDPOINT_UP"

recomputed_movement_code[
    midpoint_down_mask
] = "MIDPOINT_DOWN"

recomputed_movement_code[
    flat_midpoint_quote_change_mask
] = "QUOTE_CHANGE_FLAT_MIDPOINT"

recomputed_movement_code[
    depth_only_change_mask
] = "DEPTH_CHANGE_ONLY"


# ------------------------------------------------------------
# Level-one order-flow imbalance
#
# e_n =
#   1{bid_n >= bid_n-1} qbid_n
# - 1{bid_n <= bid_n-1} qbid_n-1
# - 1{ask_n <= ask_n-1} qask_n
# + 1{ask_n >= ask_n-1} qask_n-1
#
# The first reconstructed state has no persisted predecessor,
# so its OFI contribution is zero and its validity flag is false.
# ------------------------------------------------------------

book_l1_ofi = np.zeros(
    book_row_count,
    dtype="float64",
)

previous_bid_price = (
    book_best_bid_array[
        :-1
    ]
)

current_bid_price = (
    book_best_bid_array[
        1:
    ]
)

previous_ask_price = (
    book_best_ask_array[
        :-1
    ]
)

current_ask_price = (
    book_best_ask_array[
        1:
    ]
)

previous_bid_quantity = (
    book_best_bid_quantity_array[
        :-1
    ]
)

current_bid_quantity = (
    book_best_bid_quantity_array[
        1:
    ]
)

previous_ask_quantity = (
    book_best_ask_quantity_array[
        :-1
    ]
)

current_ask_quantity = (
    book_best_ask_quantity_array[
        1:
    ]
)

book_l1_ofi[
    1:
] = (
    np.where(
        current_bid_price
        >= previous_bid_price,
        current_bid_quantity,
        0.0,
    )
    - np.where(
        current_bid_price
        <= previous_bid_price,
        previous_bid_quantity,
        0.0,
    )
    - np.where(
        current_ask_price
        <= previous_ask_price,
        current_ask_quantity,
        0.0,
    )
    + np.where(
        current_ask_price
        >= previous_ask_price,
        previous_ask_quantity,
        0.0,
    )
)

require(
    np.isfinite(
        book_l1_ofi
    ).all(),
    "Recomputed level-one OFI contains a non-finite value.",
)


# ------------------------------------------------------------
# Reconcile Notebook 02 persisted transition fields
# ------------------------------------------------------------

stored_best_bid_change, _ = (
    parse_optional_float64(
        BOOK_FLOW_SOURCE[
            "best_bid_change"
        ],
        "BOOK_FLOW_SOURCE.best_bid_change",
    )
)

stored_best_ask_change, _ = (
    parse_optional_float64(
        BOOK_FLOW_SOURCE[
            "best_ask_change"
        ],
        "BOOK_FLOW_SOURCE.best_ask_change",
    )
)

stored_midpoint_change, _ = (
    parse_optional_float64(
        BOOK_FLOW_SOURCE[
            "midpoint_change"
        ],
        "BOOK_FLOW_SOURCE.midpoint_change",
    )
)

stored_top_of_book_moved = (
    strict_boolean_series(
        BOOK_FLOW_SOURCE[
            "top_of_book_moved"
        ],
        field_name=(
            "BOOK_FLOW_SOURCE.top_of_book_moved"
        ),
    )
)

stored_top10_changed = (
    strict_boolean_series(
        BOOK_FLOW_SOURCE[
            "top_10_changed"
        ],
        field_name=(
            "BOOK_FLOW_SOURCE.top_10_changed"
        ),
    )
)

stored_movement_code = (
    BOOK_FLOW_SOURCE[
        "movement_code"
    ]
    .astype("string")
    .str.strip()
)

require(
    pd.isna(
        stored_best_bid_change.iloc[
            0
        ]
    ),
    (
        "Notebook 02 first best_bid_change should be "
        "left-censored."
    ),
)

require(
    pd.isna(
        stored_best_ask_change.iloc[
            0
        ]
    ),
    (
        "Notebook 02 first best_ask_change should be "
        "left-censored."
    ),
)

require(
    pd.isna(
        stored_midpoint_change.iloc[
            0
        ]
    ),
    (
        "Notebook 02 first midpoint_change should be "
        "left-censored."
    ),
)


transition_reconciliation_rows: list[
    dict[str, Any]
] = []


def reconcile_book_transition_numeric(
    *,
    field_name: str,
    stored: pd.Series,
    recomputed: np.ndarray,
    rtol: float = 1e-11,
    atol: float = 1e-10,
) -> None:
    """Reconcile one persisted transition field."""
    comparison_mask = (
        book_transition_valid
        & stored.notna().to_numpy()
    )

    stored_values = (
        stored.to_numpy(
            dtype="float64",
            na_value=np.nan,
        )
    )

    close_mask = np.isclose(
        stored_values[
            comparison_mask
        ],
        recomputed[
            comparison_mask
        ],
        rtol=rtol,
        atol=atol,
        equal_nan=False,
    )

    mismatch_count = int(
        (
            ~close_mask
        ).sum()
    )

    if comparison_mask.any():
        maximum_absolute_error = float(
            np.max(
                np.abs(
                    stored_values[
                        comparison_mask
                    ]
                    - recomputed[
                        comparison_mask
                    ]
                )
            )
        )
    else:
        maximum_absolute_error = np.nan

    transition_reconciliation_rows.append(
        {
            "field": field_name,
            "compared_rows": int(
                comparison_mask.sum()
            ),
            "mismatch_count": (
                mismatch_count
            ),
            "maximum_absolute_error": (
                maximum_absolute_error
            ),
            "status": (
                "PASS"
                if mismatch_count == 0
                else "FAIL"
            ),
        }
    )

    require(
        mismatch_count == 0,
        (
            f"Notebook 02 transition field {field_name!r} "
            "does not reconcile."
        ),
    )


reconcile_book_transition_numeric(
    field_name="best_bid_change",
    stored=stored_best_bid_change,
    recomputed=recomputed_best_bid_change,
)

reconcile_book_transition_numeric(
    field_name="best_ask_change",
    stored=stored_best_ask_change,
    recomputed=recomputed_best_ask_change,
)

reconcile_book_transition_numeric(
    field_name="midpoint_change",
    stored=stored_midpoint_change,
    recomputed=recomputed_midpoint_change,
)


top_of_book_movement_mismatch_count = int(
    (
        stored_top_of_book_moved.to_numpy()
        != recomputed_top_of_book_moved
    ).sum()
)

top10_movement_mismatch_count = int(
    (
        stored_top10_changed.to_numpy()
        != recomputed_top10_changed
    ).sum()
)

movement_code_mismatch_count = int(
    (
        stored_movement_code.to_numpy(
            dtype=object
        )
        != recomputed_movement_code
    ).sum()
)

transition_reconciliation_rows.extend(
    [
        {
            "field": "top_of_book_moved",
            "compared_rows": int(
                book_row_count
            ),
            "mismatch_count": (
                top_of_book_movement_mismatch_count
            ),
            "maximum_absolute_error": np.nan,
            "status": (
                "PASS"
                if top_of_book_movement_mismatch_count
                == 0
                else "FAIL"
            ),
        },
        {
            "field": "top_10_changed",
            "compared_rows": int(
                book_row_count
            ),
            "mismatch_count": (
                top10_movement_mismatch_count
            ),
            "maximum_absolute_error": np.nan,
            "status": (
                "PASS"
                if top10_movement_mismatch_count
                == 0
                else "FAIL"
            ),
        },
        {
            "field": "movement_code",
            "compared_rows": int(
                book_row_count
            ),
            "mismatch_count": (
                movement_code_mismatch_count
            ),
            "maximum_absolute_error": np.nan,
            "status": (
                "PASS"
                if movement_code_mismatch_count
                == 0
                else "FAIL"
            ),
        },
    ]
)

require(
    top_of_book_movement_mismatch_count
    == 0,
    "Notebook 02 top_of_book_moved does not reconcile.",
)

require(
    top10_movement_mismatch_count
    == 0,
    "Notebook 02 top_10_changed does not reconcile.",
)

require(
    movement_code_mismatch_count
    == 0,
    "Notebook 02 movement_code does not reconcile.",
)


BOOK_TRANSITION_RECONCILIATION_AUDIT = (
    pd.DataFrame.from_records(
        transition_reconciliation_rows
    )
)


# ------------------------------------------------------------
# Feature-contribution arrays
#
# The initial reconstructed state is a valid applied update,
# but it has no persisted predecessor. It contributes update
# actions, but not movement, return, depth-change, or OFI.
# ------------------------------------------------------------

book_observable_top_of_book_move = (
    recomputed_top_of_book_moved.copy()
)

book_observable_top_of_book_move[
    0
] = False

book_observable_top10_change = (
    recomputed_top10_changed.copy()
)

book_observable_top10_change[
    0
] = False

book_midpoint_up = (
    recomputed_midpoint_direction
    > 0
)

book_midpoint_down = (
    recomputed_midpoint_direction
    < 0
)

book_midpoint_flat = (
    book_transition_valid
    & (
        recomputed_midpoint_direction
        == 0
    )
)

book_spread_widened = (
    recomputed_spread_direction
    > 0
)

book_spread_narrowed = (
    recomputed_spread_direction
    < 0
)

book_spread_unchanged = (
    book_transition_valid
    & (
        recomputed_spread_direction
        == 0
    )
)

book_depth_change_only = (
    depth_only_change_mask
)

book_no_visible_top10_change = (
    book_transition_valid
    & ~recomputed_top10_changed
)

book_l1_total_quantity_array = (
    book_best_bid_quantity_array
    + book_best_ask_quantity_array
)


# ------------------------------------------------------------
# Prefix arrays for additive rolling features
# ------------------------------------------------------------

book_prefixes: dict[
    str,
    np.ndarray,
] = {
    "state_count": causal_prefix_sum(
        np.ones(
            book_row_count,
            dtype="int64",
        ),
        dtype="int64",
    ),
    "transition_valid": causal_prefix_sum(
        book_transition_valid.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "top_of_book_move": causal_prefix_sum(
        book_observable_top_of_book_move.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "top10_change": causal_prefix_sum(
        book_observable_top10_change.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "midpoint_up": causal_prefix_sum(
        book_midpoint_up.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "midpoint_down": causal_prefix_sum(
        book_midpoint_down.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "midpoint_flat": causal_prefix_sum(
        book_midpoint_flat.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "spread_widened": causal_prefix_sum(
        book_spread_widened.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "spread_narrowed": causal_prefix_sum(
        book_spread_narrowed.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "spread_unchanged": causal_prefix_sum(
        book_spread_unchanged.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "depth_change_only": causal_prefix_sum(
        book_depth_change_only.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "no_visible_top10_change": causal_prefix_sum(
        book_no_visible_top10_change.astype(
            "int64"
        ),
        dtype="int64",
    ),
    "stale_interval": causal_prefix_sum(
        book_stale_interval.astype(
            "int64"
        ).to_numpy(),
        dtype="int64",
    ),
    "midpoint_change": causal_prefix_sum(
        recomputed_midpoint_change,
        dtype="float64",
    ),
    "absolute_midpoint_change": causal_prefix_sum(
        np.abs(
            recomputed_midpoint_change
        ),
        dtype="float64",
    ),
    "log_midpoint_return": causal_prefix_sum(
        recomputed_log_midpoint_return,
        dtype="float64",
    ),
    "absolute_log_midpoint_return": causal_prefix_sum(
        np.abs(
            recomputed_log_midpoint_return
        ),
        dtype="float64",
    ),
    "squared_log_midpoint_return": causal_prefix_sum(
        np.square(
            recomputed_log_midpoint_return
        ),
        dtype="float64",
    ),
    "spread_change": causal_prefix_sum(
        recomputed_spread_change,
        dtype="float64",
    ),
    "bid_depth_top10_change": causal_prefix_sum(
        recomputed_bid_depth_top10_change,
        dtype="float64",
    ),
    "ask_depth_top10_change": causal_prefix_sum(
        recomputed_ask_depth_top10_change,
        dtype="float64",
    ),
    "total_depth_top10_change": causal_prefix_sum(
        recomputed_total_depth_top10_change,
        dtype="float64",
    ),
    "l1_ofi": causal_prefix_sum(
        book_l1_ofi,
        dtype="float64",
    ),
    "absolute_l1_ofi": causal_prefix_sum(
        np.abs(
            book_l1_ofi
        ),
        dtype="float64",
    ),
    "midpoint": causal_prefix_sum(
        book_midpoint_array,
        dtype="float64",
    ),
    "spread_bps": causal_prefix_sum(
        book_spread_bps_array,
        dtype="float64",
    ),
    "l1_imbalance": causal_prefix_sum(
        book_l1_imbalance_array,
        dtype="float64",
    ),
    "top10_imbalance": causal_prefix_sum(
        book_top10_imbalance_array,
        dtype="float64",
    ),
    "l1_total_quantity": causal_prefix_sum(
        book_l1_total_quantity_array,
        dtype="float64",
    ),
    "total_depth_top10": causal_prefix_sum(
        book_total_depth_top10_array,
        dtype="float64",
    ),
}

for action_column_name, action_values in (
    book_action_arrays.items()
):
    book_prefixes[
        action_column_name
    ] = causal_prefix_sum(
        action_values,
        dtype="int64",
    )


# ------------------------------------------------------------
# Canonical batch-level feature spine and cutoff arrays
# ------------------------------------------------------------

BOOK_FLOW_IDENTITY_COLUMNS: Final[
    tuple[str, ...]
] = (
    "primary_event_batch_id",
    "primary_event_batch_number",
    "partition_batch_index",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
)

BATCH_CAUSAL_BOOK_FLOW_FEATURES = (
    COMMON_PRE_BATCH_BOOK_STATES[
        [
            *BOOK_FLOW_IDENTITY_COLUMNS,
            "batch_min_initiating_trade_collector_sequence",
            "common_book_candidate_position",
            "common_book_book_state_id",
            "common_book_collector_sequence",
            "common_book_local_receipt_time_ns",
            "common_book_partition",
            "common_book_partition_order",
            "common_book_age_ns",
            "common_book_same_local_timestamp_flag",
            "cross_partition_history_flag",
        ]
    ]
    .copy()
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)
)

require_unique_columns(
    BATCH_CAUSAL_BOOK_FLOW_FEATURES,
    "BATCH_CAUSAL_BOOK_FLOW_FEATURES",
)

require(
    len(BATCH_CAUSAL_BOOK_FLOW_FEATURES)
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Causal book-flow feature spine does not contain "
        "one row per scoring batch."
    ),
)

require(
    BATCH_CAUSAL_BOOK_FLOW_FEATURES[
        "primary_event_batch_id"
    ].is_unique,
    "Causal book-flow batch IDs are not unique.",
)


current_book_batch_time_array = (
    parse_required_int64(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES[
            "event_time_ns"
        ],
        (
            "BATCH_CAUSAL_BOOK_FLOW_FEATURES."
            "event_time_ns"
        ),
    ).to_numpy()
)

current_book_batch_sequence_cutoff_array = (
    parse_required_int64(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES[
            (
                "batch_min_initiating_trade_"
                "collector_sequence"
            )
        ],
        (
            "BATCH_CAUSAL_BOOK_FLOW_FEATURES."
            "batch_min_initiating_trade_"
            "collector_sequence"
        ),
    ).to_numpy()
)

common_book_candidate_position_array = (
    parse_required_int64(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES[
            "common_book_candidate_position"
        ],
        (
            "BATCH_CAUSAL_BOOK_FLOW_FEATURES."
            "common_book_candidate_position"
        ),
    ).to_numpy()
)

current_book_batch_partition_order_array = (
    parse_required_int64(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES[
            "event_partition_order"
        ],
        (
            "BATCH_CAUSAL_BOOK_FLOW_FEATURES."
            "event_partition_order"
        ),
    ).to_numpy()
)

current_book_partition_start_ns_array = (
    BATCH_CAUSAL_BOOK_FLOW_FEATURES[
        "event_partition"
    ]
    .map(
        SPLIT_BOUNDARY_TABLE.set_index(
            "partition"
        )[
            "receipt_time_start_ns"
        ].astype("int64")
    )
)

require(
    current_book_partition_start_ns_array.notna().all(),
    (
        "At least one book-flow batch cannot be mapped to "
        "its partition start."
    ),
)

current_book_partition_start_ns_array = (
    current_book_partition_start_ns_array
    .astype("int64")
    .to_numpy()
)


book_window_right_position_array = (
    common_book_candidate_position_array
    + 1
)

require(
    (
        book_window_right_position_array
        > 0
    ).all(),
    (
        "At least one scoring batch has no eligible common "
        "book state."
    ),
)

require(
    (
        book_window_right_position_array
        <= book_row_count
    ).all(),
    "A common-book cutoff exceeds the book source length.",
)

require(
    np.array_equal(
        book_state_id_array[
            common_book_candidate_position_array
        ],
        BATCH_CAUSAL_BOOK_FLOW_FEATURES[
            "common_book_book_state_id"
        ].astype("int64").to_numpy(),
    ),
    (
        "Common-book candidate positions do not resolve to "
        "the persisted common book-state identities."
    ),
)

require(
    (
        book_sequence_array[
            common_book_candidate_position_array
        ]
        < current_book_batch_sequence_cutoff_array
    ).all(),
    (
        "A common book state violates the batch collector-"
        "sequence cutoff."
    ),
)

require(
    (
        book_time_array[
            common_book_candidate_position_array
        ]
        <= current_book_batch_time_array
    ).all(),
    (
        "A common book state occurs after its scoring-batch "
        "time."
    ),
)


GLOBAL_BOOK_OBSERVATION_START_NS: Final[int] = int(
    book_time_array[
        0
    ]
)

GLOBAL_BOOK_OBSERVATION_END_NS: Final[int] = int(
    book_time_array[
        -1
    ]
)


# ------------------------------------------------------------
# Construct clock-time book-flow feature blocks without
# repeated DataFrame insertion
# ------------------------------------------------------------

book_flow_feature_payload: dict[
    str,
    Any,
] = {}

book_window_feature_audit_rows: list[
    dict[str, Any]
] = []

book_window_count_registry: dict[
    str,
    dict[str, np.ndarray],
] = {}

book_same_time_cutoff_violation_count = 0
book_sequence_cutoff_violation_count = 0
book_future_partition_violation_count = 0


for window_name, window_ns in (
    CLOCK_TIME_WINDOWS_NS.items()
):
    window_slug = (
        window_name.lower()
    )

    feature_prefix = (
        f"tminus_book_flow_{window_slug}"
    )

    window_seconds = (
        float(window_ns)
        / 1_000_000_000.0
    )

    window_start_ns = (
        current_book_batch_time_array
        - int(
            window_ns
        )
    )

    left_positions = np.searchsorted(
        book_time_array,
        window_start_ns,
        side="left",
    )

    right_positions = (
        book_window_right_position_array
    )

    require(
        (
            left_positions
            <= right_positions
        ).all(),
        (
            f"{window_name} has a book-window left position "
            "after its causal right cutoff."
        ),
    )

    state_count = causal_slice_sum(
        book_prefixes[
            "state_count"
        ],
        left_positions,
        right_positions,
    ).astype("int64")

    require(
        (
            state_count > 0
        ).all(),
        (
            f"{window_name} contains a scoring batch with no "
            "causally eligible book state."
        ),
    )

    transition_count = causal_slice_sum(
        book_prefixes[
            "transition_valid"
        ],
        left_positions,
        right_positions,
    ).astype("int64")

    top_of_book_move_count = (
        causal_slice_sum(
            book_prefixes[
                "top_of_book_move"
            ],
            left_positions,
            right_positions,
        ).astype("int64")
    )

    top10_change_count = (
        causal_slice_sum(
            book_prefixes[
                "top10_change"
            ],
            left_positions,
            right_positions,
        ).astype("int64")
    )

    midpoint_up_count = causal_slice_sum(
        book_prefixes[
            "midpoint_up"
        ],
        left_positions,
        right_positions,
    ).astype("int64")

    midpoint_down_count = causal_slice_sum(
        book_prefixes[
            "midpoint_down"
        ],
        left_positions,
        right_positions,
    ).astype("int64")

    midpoint_flat_count = causal_slice_sum(
        book_prefixes[
            "midpoint_flat"
        ],
        left_positions,
        right_positions,
    ).astype("int64")

    spread_widen_count = causal_slice_sum(
        book_prefixes[
            "spread_widened"
        ],
        left_positions,
        right_positions,
    ).astype("int64")

    spread_narrow_count = causal_slice_sum(
        book_prefixes[
            "spread_narrowed"
        ],
        left_positions,
        right_positions,
    ).astype("int64")

    spread_unchanged_count = (
        causal_slice_sum(
            book_prefixes[
                "spread_unchanged"
            ],
            left_positions,
            right_positions,
        ).astype("int64")
    )

    depth_change_only_count = (
        causal_slice_sum(
            book_prefixes[
                "depth_change_only"
            ],
            left_positions,
            right_positions,
        ).astype("int64")
    )

    no_visible_top10_change_count = (
        causal_slice_sum(
            book_prefixes[
                "no_visible_top10_change"
            ],
            left_positions,
            right_positions,
        ).astype("int64")
    )

    stale_interval_count = causal_slice_sum(
        book_prefixes[
            "stale_interval"
        ],
        left_positions,
        right_positions,
    ).astype("int64")

    signed_midpoint_change = causal_slice_sum(
        book_prefixes[
            "midpoint_change"
        ],
        left_positions,
        right_positions,
    )

    absolute_midpoint_variation = (
        causal_slice_sum(
            book_prefixes[
                "absolute_midpoint_change"
            ],
            left_positions,
            right_positions,
        )
    )

    signed_log_midpoint_return = (
        causal_slice_sum(
            book_prefixes[
                "log_midpoint_return"
            ],
            left_positions,
            right_positions,
        )
    )

    absolute_log_midpoint_variation = (
        causal_slice_sum(
            book_prefixes[
                "absolute_log_midpoint_return"
            ],
            left_positions,
            right_positions,
        )
    )

    squared_log_midpoint_variation = (
        causal_slice_sum(
            book_prefixes[
                "squared_log_midpoint_return"
            ],
            left_positions,
            right_positions,
        )
    )

    signed_spread_change = causal_slice_sum(
        book_prefixes[
            "spread_change"
        ],
        left_positions,
        right_positions,
    )

    signed_bid_depth_top10_change = (
        causal_slice_sum(
            book_prefixes[
                "bid_depth_top10_change"
            ],
            left_positions,
            right_positions,
        )
    )

    signed_ask_depth_top10_change = (
        causal_slice_sum(
            book_prefixes[
                "ask_depth_top10_change"
            ],
            left_positions,
            right_positions,
        )
    )

    signed_total_depth_top10_change = (
        causal_slice_sum(
            book_prefixes[
                "total_depth_top10_change"
            ],
            left_positions,
            right_positions,
        )
    )

    l1_ofi = causal_slice_sum(
        book_prefixes[
            "l1_ofi"
        ],
        left_positions,
        right_positions,
    )

    absolute_l1_ofi = causal_slice_sum(
        book_prefixes[
            "absolute_l1_ofi"
        ],
        left_positions,
        right_positions,
    )

    mean_midpoint = safe_fraction(
        causal_slice_sum(
            book_prefixes[
                "midpoint"
            ],
            left_positions,
            right_positions,
        ),
        state_count,
    )

    mean_spread_bps = safe_fraction(
        causal_slice_sum(
            book_prefixes[
                "spread_bps"
            ],
            left_positions,
            right_positions,
        ),
        state_count,
    )

    mean_l1_imbalance = safe_fraction(
        causal_slice_sum(
            book_prefixes[
                "l1_imbalance"
            ],
            left_positions,
            right_positions,
        ),
        state_count,
    )

    mean_top10_imbalance = safe_fraction(
        causal_slice_sum(
            book_prefixes[
                "top10_imbalance"
            ],
            left_positions,
            right_positions,
        ),
        state_count,
    )

    mean_l1_total_quantity = safe_fraction(
        causal_slice_sum(
            book_prefixes[
                "l1_total_quantity"
            ],
            left_positions,
            right_positions,
        ),
        state_count,
    )

    mean_total_depth_top10 = safe_fraction(
        causal_slice_sum(
            book_prefixes[
                "total_depth_top10"
            ],
            left_positions,
            right_positions,
        ),
        state_count,
    )

    action_sums: dict[
        str,
        np.ndarray,
    ] = {}

    for action_column_name in (
        BOOK_ACTION_COUNT_COLUMNS
    ):
        action_sums[
            action_column_name
        ] = causal_slice_sum(
            book_prefixes[
                action_column_name
            ],
            left_positions,
            right_positions,
        ).astype("int64")


    midpoint_minimum = np.empty(
        len(
            BATCH_CAUSAL_BOOK_FLOW_FEATURES
        ),
        dtype="float64",
    )

    midpoint_maximum = np.empty_like(
        midpoint_minimum
    )

    first_book_partition_order = np.empty(
        len(
            BATCH_CAUSAL_BOOK_FLOW_FEATURES
        ),
        dtype="int64",
    )

    first_book_state_id = np.empty_like(
        first_book_partition_order
    )

    last_book_state_id = np.empty_like(
        first_book_partition_order
    )

    for batch_position, (
        left_position,
        right_position,
    ) in enumerate(
        zip(
            left_positions,
            right_positions,
            strict=True,
        )
    ):
        left_position_int = int(
            left_position
        )

        right_position_int = int(
            right_position
        )

        midpoint_slice = (
            book_midpoint_array[
                left_position_int:
                right_position_int
            ]
        )

        midpoint_minimum[
            batch_position
        ] = float(
            midpoint_slice.min()
        )

        midpoint_maximum[
            batch_position
        ] = float(
            midpoint_slice.max()
        )

        first_book_partition_order[
            batch_position
        ] = int(
            book_partition_order_array[
                left_position_int
            ]
        )

        first_book_state_id[
            batch_position
        ] = int(
            book_state_id_array[
                left_position_int
            ]
        )

        last_book_state_id[
            batch_position
        ] = int(
            book_state_id_array[
                right_position_int - 1
            ]
        )


    midpoint_range = (
        midpoint_maximum
        - midpoint_minimum
    )

    midpoint_range_bps = (
        midpoint_range
        / book_midpoint_array[
            common_book_candidate_position_array
        ]
        * 10_000.0
    )

    full_coverage_flag = (
        window_start_ns
        >= GLOBAL_BOOK_OBSERVATION_START_NS
    )

    observed_duration_ns = np.minimum(
        int(
            window_ns
        ),
        np.maximum(
            0,
            (
                current_book_batch_time_array
                - GLOBAL_BOOK_OBSERVATION_START_NS
            ),
        ),
    ).astype("int64")

    coverage_fraction = (
        observed_duration_ns.astype(
            "float64"
        )
        / float(
            window_ns
        )
    )

    cross_partition_history_flag = (
        first_book_partition_order
        < current_book_batch_partition_order_array
    )

    future_partition_history_flag = (
        first_book_partition_order
        > current_book_batch_partition_order_array
    )

    same_time_start_positions = np.searchsorted(
        book_time_array,
        current_book_batch_time_array,
        side="left",
    )

    same_time_prior_sequence_state_count = np.maximum(
        0,
        (
            right_positions
            - np.maximum(
                left_positions,
                same_time_start_positions,
            )
        ),
    ).astype("int64")

    for batch_position in np.flatnonzero(
        same_time_prior_sequence_state_count
        > 0
    ):
        left_same_time_position = int(
            max(
                left_positions[
                    batch_position
                ],
                same_time_start_positions[
                    batch_position
                ],
            )
        )

        right_same_time_position = int(
            right_positions[
                batch_position
            ]
        )

        same_time_sequences = (
            book_sequence_array[
                left_same_time_position:
                right_same_time_position
            ]
        )

        if np.any(
            same_time_sequences
            >= current_book_batch_sequence_cutoff_array[
                batch_position
            ]
        ):
            book_same_time_cutoff_violation_count += int(
                np.sum(
                    same_time_sequences
                    >= current_book_batch_sequence_cutoff_array[
                        batch_position
                    ]
                )
            )

    for batch_position, right_position in enumerate(
        right_positions
    ):
        included_sequences = (
            book_sequence_array[
                : int(
                    right_position
                )
            ]
        )

        if (
            included_sequences.size > 0
            and included_sequences[
                -1
            ]
            >= current_book_batch_sequence_cutoff_array[
                batch_position
            ]
        ):
            book_sequence_cutoff_violation_count += 1

    book_future_partition_violation_count += int(
        future_partition_history_flag.sum()
    )


    authoritative_rate_mask = (
        full_coverage_flag
    )

    authoritative_variation_mask = (
        full_coverage_flag
        & (
            transition_count > 0
        )
    )

    update_rate_per_second = np.where(
        authoritative_rate_mask,
        (
            state_count.astype(
                "float64"
            )
            / window_seconds
        ),
        np.nan,
    )

    message_level_rate_per_second = np.where(
        authoritative_rate_mask,
        (
            action_sums[
                "message_level_count"
            ].astype(
                "float64"
            )
            / window_seconds
        ),
        np.nan,
    )

    actual_changed_level_rate_per_second = np.where(
        authoritative_rate_mask,
        (
            action_sums[
                "actual_changed_level_count"
            ].astype(
                "float64"
            )
            / window_seconds
        ),
        np.nan,
    )

    top_of_book_move_rate_per_second = np.where(
        authoritative_rate_mask,
        (
            top_of_book_move_count.astype(
                "float64"
            )
            / window_seconds
        ),
        np.nan,
    )

    top10_change_rate_per_second = np.where(
        authoritative_rate_mask,
        (
            top10_change_count.astype(
                "float64"
            )
            / window_seconds
        ),
        np.nan,
    )

    l1_ofi_rate_per_second = np.where(
        authoritative_rate_mask,
        (
            l1_ofi
            / window_seconds
        ),
        np.nan,
    )

    realized_variance = np.where(
        authoritative_variation_mask,
        squared_log_midpoint_variation,
        np.nan,
    )

    realized_volatility_bps = np.where(
        authoritative_variation_mask,
        (
            np.sqrt(
                squared_log_midpoint_variation
            )
            * 10_000.0
        ),
        np.nan,
    )

    l1_ofi_normalized_by_mean_l1_depth = (
        safe_fraction(
            l1_ofi,
            mean_l1_total_quantity,
        )
    )

    top_of_book_move_fraction = (
        safe_fraction(
            top_of_book_move_count,
            transition_count,
        )
    )

    top10_change_fraction = safe_fraction(
        top10_change_count,
        transition_count,
    )

    stale_interval_fraction = safe_fraction(
        stale_interval_count,
        state_count,
    )

    actual_changed_levels_per_update = (
        safe_fraction(
            action_sums[
                "actual_changed_level_count"
            ],
            state_count,
        )
    )


    book_flow_feature_payload[
        f"{feature_prefix}_full_coverage_flag"
    ] = full_coverage_flag

    book_flow_feature_payload[
        f"{feature_prefix}_coverage_fraction"
    ] = coverage_fraction

    book_flow_feature_payload[
        f"{feature_prefix}_observed_duration_seconds"
    ] = (
        observed_duration_ns.astype(
            "float64"
        )
        / 1_000_000_000.0
    )

    book_flow_feature_payload[
        f"{feature_prefix}_cross_partition_history_flag"
    ] = cross_partition_history_flag

    book_flow_feature_payload[
        f"{feature_prefix}_state_count"
    ] = state_count

    book_flow_feature_payload[
        f"{feature_prefix}_valid_transition_count"
    ] = transition_count

    book_flow_feature_payload[
        (
            f"{feature_prefix}_same_time_prior_"
            "sequence_state_count"
        )
    ] = same_time_prior_sequence_state_count

    book_flow_feature_payload[
        f"{feature_prefix}_update_rate_per_second"
    ] = update_rate_per_second

    book_flow_feature_payload[
        f"{feature_prefix}_bid_message_level_count"
    ] = action_sums[
        "bid_message_level_count"
    ]

    book_flow_feature_payload[
        f"{feature_prefix}_ask_message_level_count"
    ] = action_sums[
        "ask_message_level_count"
    ]

    book_flow_feature_payload[
        f"{feature_prefix}_message_level_count"
    ] = action_sums[
        "message_level_count"
    ]

    book_flow_feature_payload[
        f"{feature_prefix}_message_level_rate_per_second"
    ] = message_level_rate_per_second

    book_flow_feature_payload[
        f"{feature_prefix}_message_delete_count"
    ] = action_sums[
        "message_delete_count"
    ]

    book_flow_feature_payload[
        f"{feature_prefix}_inserted_level_count"
    ] = action_sums[
        "inserted_level_count"
    ]

    book_flow_feature_payload[
        f"{feature_prefix}_replaced_level_count"
    ] = action_sums[
        "replaced_level_count"
    ]

    book_flow_feature_payload[
        f"{feature_prefix}_unchanged_replacement_count"
    ] = action_sums[
        "unchanged_replacement_count"
    ]

    book_flow_feature_payload[
        f"{feature_prefix}_deleted_level_count"
    ] = action_sums[
        "deleted_level_count"
    ]

    book_flow_feature_payload[
        f"{feature_prefix}_absent_delete_noop_count"
    ] = action_sums[
        "absent_delete_noop_count"
    ]

    book_flow_feature_payload[
        f"{feature_prefix}_actual_changed_level_count"
    ] = action_sums[
        "actual_changed_level_count"
    ]

    book_flow_feature_payload[
        (
            f"{feature_prefix}_actual_changed_level_"
            "rate_per_second"
        )
    ] = actual_changed_level_rate_per_second

    book_flow_feature_payload[
        (
            f"{feature_prefix}_actual_changed_levels_"
            "per_update"
        )
    ] = actual_changed_levels_per_update

    book_flow_feature_payload[
        f"{feature_prefix}_top_of_book_move_count"
    ] = top_of_book_move_count

    book_flow_feature_payload[
        (
            f"{feature_prefix}_top_of_book_move_"
            "fraction"
        )
    ] = top_of_book_move_fraction

    book_flow_feature_payload[
        (
            f"{feature_prefix}_top_of_book_move_"
            "rate_per_second"
        )
    ] = top_of_book_move_rate_per_second

    book_flow_feature_payload[
        f"{feature_prefix}_top10_change_count"
    ] = top10_change_count

    book_flow_feature_payload[
        f"{feature_prefix}_top10_change_fraction"
    ] = top10_change_fraction

    book_flow_feature_payload[
        f"{feature_prefix}_top10_change_rate_per_second"
    ] = top10_change_rate_per_second

    book_flow_feature_payload[
        f"{feature_prefix}_depth_change_only_count"
    ] = depth_change_only_count

    book_flow_feature_payload[
        (
            f"{feature_prefix}_no_visible_top10_"
            "change_count"
        )
    ] = no_visible_top10_change_count

    book_flow_feature_payload[
        f"{feature_prefix}_midpoint_up_count"
    ] = midpoint_up_count

    book_flow_feature_payload[
        f"{feature_prefix}_midpoint_down_count"
    ] = midpoint_down_count

    book_flow_feature_payload[
        f"{feature_prefix}_midpoint_flat_count"
    ] = midpoint_flat_count

    book_flow_feature_payload[
        f"{feature_prefix}_spread_widen_count"
    ] = spread_widen_count

    book_flow_feature_payload[
        f"{feature_prefix}_spread_narrow_count"
    ] = spread_narrow_count

    book_flow_feature_payload[
        f"{feature_prefix}_spread_unchanged_count"
    ] = spread_unchanged_count

    book_flow_feature_payload[
        f"{feature_prefix}_stale_interval_count"
    ] = stale_interval_count

    book_flow_feature_payload[
        f"{feature_prefix}_stale_interval_fraction"
    ] = stale_interval_fraction

    book_flow_feature_payload[
        f"{feature_prefix}_signed_midpoint_change"
    ] = signed_midpoint_change

    book_flow_feature_payload[
        f"{feature_prefix}_absolute_midpoint_variation"
    ] = absolute_midpoint_variation

    book_flow_feature_payload[
        (
            f"{feature_prefix}_signed_log_midpoint_"
            "return_basis_points"
        )
    ] = (
        signed_log_midpoint_return
        * 10_000.0
    )

    book_flow_feature_payload[
        (
            f"{feature_prefix}_absolute_log_midpoint_"
            "variation_basis_points"
        )
    ] = (
        absolute_log_midpoint_variation
        * 10_000.0
    )

    book_flow_feature_payload[
        f"{feature_prefix}_realized_variance"
    ] = realized_variance

    book_flow_feature_payload[
        f"{feature_prefix}_realized_volatility_basis_points"
    ] = realized_volatility_bps

    book_flow_feature_payload[
        f"{feature_prefix}_midpoint_range"
    ] = midpoint_range

    book_flow_feature_payload[
        f"{feature_prefix}_midpoint_range_basis_points"
    ] = midpoint_range_bps

    book_flow_feature_payload[
        f"{feature_prefix}_mean_midpoint"
    ] = mean_midpoint

    book_flow_feature_payload[
        f"{feature_prefix}_mean_spread_basis_points"
    ] = mean_spread_bps

    book_flow_feature_payload[
        f"{feature_prefix}_signed_spread_change"
    ] = signed_spread_change

    book_flow_feature_payload[
        f"{feature_prefix}_mean_level_one_imbalance"
    ] = mean_l1_imbalance

    book_flow_feature_payload[
        f"{feature_prefix}_mean_top10_imbalance"
    ] = mean_top10_imbalance

    book_flow_feature_payload[
        f"{feature_prefix}_mean_level_one_total_quantity"
    ] = mean_l1_total_quantity

    book_flow_feature_payload[
        f"{feature_prefix}_mean_total_depth_top10"
    ] = mean_total_depth_top10

    book_flow_feature_payload[
        f"{feature_prefix}_signed_bid_depth_top10_change"
    ] = signed_bid_depth_top10_change

    book_flow_feature_payload[
        f"{feature_prefix}_signed_ask_depth_top10_change"
    ] = signed_ask_depth_top10_change

    book_flow_feature_payload[
        f"{feature_prefix}_signed_total_depth_top10_change"
    ] = signed_total_depth_top10_change

    book_flow_feature_payload[
        f"{feature_prefix}_level_one_ofi"
    ] = l1_ofi

    book_flow_feature_payload[
        f"{feature_prefix}_absolute_level_one_ofi"
    ] = absolute_l1_ofi

    book_flow_feature_payload[
        f"{feature_prefix}_level_one_ofi_rate_per_second"
    ] = l1_ofi_rate_per_second

    book_flow_feature_payload[
        (
            f"{feature_prefix}_level_one_ofi_"
            "normalized_by_mean_depth"
        )
    ] = l1_ofi_normalized_by_mean_l1_depth


    require(
        (
            transition_count
            <= state_count
        ).all(),
        (
            f"{window_name} transition count exceeds "
            "book-state count."
        ),
    )

    require(
        (
            top_of_book_move_count
            <= transition_count
        ).all(),
        (
            f"{window_name} top-of-book move count exceeds "
            "valid transition count."
        ),
    )

    require(
        (
            top10_change_count
            <= transition_count
        ).all(),
        (
            f"{window_name} top-10 change count exceeds "
            "valid transition count."
        ),
    )

    require(
        np.array_equal(
            midpoint_up_count
            + midpoint_down_count
            + midpoint_flat_count,
            transition_count,
        ),
        (
            f"{window_name} midpoint direction counts do not "
            "conserve valid book transitions."
        ),
    )

    require(
        np.array_equal(
            spread_widen_count
            + spread_narrow_count
            + spread_unchanged_count,
            transition_count,
        ),
        (
            f"{window_name} spread direction counts do not "
            "conserve valid book transitions."
        ),
    )

    require(
        (
            stale_interval_count
            <= state_count
        ).all(),
        (
            f"{window_name} stale interval count exceeds "
            "book-state count."
        ),
    )

    require(
        (
            coverage_fraction
            >= 0.0
        ).all()
        and (
            coverage_fraction
            <= 1.0
        ).all(),
        (
            f"{window_name} book coverage fraction lies "
            "outside [0, 1]."
        ),
    )

    require(
        not future_partition_history_flag.any(),
        (
            f"{window_name} includes a book state from a "
            "future partition."
        ),
    )

    rate_feature_names = [
        f"{feature_prefix}_update_rate_per_second",
        f"{feature_prefix}_message_level_rate_per_second",
        (
            f"{feature_prefix}_actual_changed_level_"
            "rate_per_second"
        ),
        (
            f"{feature_prefix}_top_of_book_move_"
            "rate_per_second"
        ),
        f"{feature_prefix}_top10_change_rate_per_second",
        f"{feature_prefix}_level_one_ofi_rate_per_second",
    ]

    variation_feature_names = [
        f"{feature_prefix}_realized_variance",
        (
            f"{feature_prefix}_realized_volatility_"
            "basis_points"
        ),
    ]

    rate_frame = pd.DataFrame(
        {
            feature_name: (
                book_flow_feature_payload[
                    feature_name
                ]
            )
            for feature_name in (
                rate_feature_names
            )
        }
    )

    variation_frame = pd.DataFrame(
        {
            feature_name: (
                book_flow_feature_payload[
                    feature_name
                ]
            )
            for feature_name in (
                variation_feature_names
            )
        }
    )

    require(
        rate_frame.loc[
            authoritative_rate_mask,
            :,
        ].notna().all().all(),
        (
            f"{window_name} has missing rate values despite "
            "full book-history coverage."
        ),
    )

    require(
        rate_frame.loc[
            ~authoritative_rate_mask,
            :,
        ].isna().all().all(),
        (
            f"{window_name} exposes rate values before full "
            "book-history coverage."
        ),
    )

    require(
        variation_frame.loc[
            authoritative_variation_mask,
            :,
        ].notna().all().all(),
        (
            f"{window_name} has missing variance or "
            "volatility despite sufficient full coverage."
        ),
    )

    require(
        variation_frame.loc[
            ~authoritative_variation_mask,
            :,
        ].isna().all().all(),
        (
            f"{window_name} exposes variance or volatility "
            "without full history and a valid transition."
        ),
    )


    book_window_count_registry[
        window_name
    ] = {
        "state_count": state_count,
        "transition_count": transition_count,
        "message_level_count": action_sums[
            "message_level_count"
        ],
        "actual_changed_level_count": action_sums[
            "actual_changed_level_count"
        ],
        "top_of_book_move_count": (
            top_of_book_move_count
        ),
        "top10_change_count": (
            top10_change_count
        ),
        "absolute_midpoint_variation": (
            absolute_midpoint_variation
        ),
        "absolute_l1_ofi": absolute_l1_ofi,
    }

    book_window_feature_audit_rows.append(
        {
            "window_name": window_name,
            "window_ns": int(
                window_ns
            ),
            "full_coverage_batch_count": int(
                full_coverage_flag.sum()
            ),
            "partial_coverage_batch_count": int(
                (
                    ~full_coverage_flag
                ).sum()
            ),
            "cross_partition_history_batch_count": int(
                cross_partition_history_flag.sum()
            ),
            "same_time_prior_sequence_state_memberships": int(
                same_time_prior_sequence_state_count.sum()
            ),
            "total_book_state_memberships": int(
                state_count.sum()
            ),
            "total_valid_transition_memberships": int(
                transition_count.sum()
            ),
            "maximum_book_state_count": int(
                state_count.max()
            ),
            "maximum_message_level_count": int(
                action_sums[
                    "message_level_count"
                ].max()
            ),
            "maximum_actual_changed_level_count": int(
                action_sums[
                    "actual_changed_level_count"
                ].max()
            ),
            "status": "PASS",
        }
    )


BOOK_WINDOW_FEATURE_AUDIT = (
    pd.DataFrame.from_records(
        book_window_feature_audit_rows
    )
)


# ------------------------------------------------------------
# Nested-window monotonicity audit
# ------------------------------------------------------------

BOOK_WINDOW_MONOTONICITY_AUDIT_ROWS: list[
    dict[str, Any]
] = []

ordered_book_window_names = [
    "W250MS",
    "W1S",
    "W5S",
    "W30S",
]

for metric_name in (
    "state_count",
    "transition_count",
    "message_level_count",
    "actual_changed_level_count",
    "top_of_book_move_count",
    "top10_change_count",
    "absolute_midpoint_variation",
    "absolute_l1_ofi",
):
    previous_values: np.ndarray | None = None
    previous_window_name: str | None = None

    for window_name in (
        ordered_book_window_names
    ):
        current_values = (
            book_window_count_registry[
                window_name
            ][
                metric_name
            ]
        )

        if previous_values is not None:
            if metric_name in {
                "absolute_midpoint_variation",
                "absolute_l1_ofi",
            }:
                failure_count = int(
                    (
                        current_values
                        + 1e-12
                        < previous_values
                    ).sum()
                )
            else:
                failure_count = int(
                    (
                        current_values
                        < previous_values
                    ).sum()
                )

            BOOK_WINDOW_MONOTONICITY_AUDIT_ROWS.append(
                {
                    "metric": metric_name,
                    "smaller_window": (
                        previous_window_name
                    ),
                    "larger_window": (
                        window_name
                    ),
                    "failure_count": (
                        failure_count
                    ),
                    "status": (
                        "PASS"
                        if failure_count == 0
                        else "FAIL"
                    ),
                }
            )

            require(
                failure_count == 0,
                (
                    f"{metric_name} decreases when expanding "
                    f"from {previous_window_name} to "
                    f"{window_name}."
                ),
            )

        previous_values = (
            current_values
        )

        previous_window_name = (
            window_name
        )


BOOK_WINDOW_MONOTONICITY_AUDIT = (
    pd.DataFrame.from_records(
        BOOK_WINDOW_MONOTONICITY_AUDIT_ROWS
    )
)


# ------------------------------------------------------------
# Book recency and latest-transition state
# ------------------------------------------------------------

def cumulative_last_true_position(
    condition: np.ndarray,
) -> np.ndarray:
    """Return the latest true position at each source row."""
    require(
        condition.ndim == 1,
        "Condition must be one-dimensional.",
    )

    positions = np.where(
        condition,
        np.arange(
            len(
                condition
            ),
            dtype="int64",
        ),
        -1,
    )

    return np.maximum.accumulate(
        positions
    )


last_midpoint_change_position_by_book = (
    cumulative_last_true_position(
        book_transition_valid
        & (
            recomputed_midpoint_direction
            != 0
        )
    )
)

last_top_of_book_move_position_by_book = (
    cumulative_last_true_position(
        book_transition_valid
        & book_observable_top_of_book_move
    )
)

last_top10_change_position_by_book = (
    cumulative_last_true_position(
        book_transition_valid
        & book_observable_top10_change
    )
)

last_spread_change_position_by_book = (
    cumulative_last_true_position(
        book_transition_valid
        & (
            recomputed_spread_direction
            != 0
        )
    )
)


selected_last_midpoint_change_position = (
    last_midpoint_change_position_by_book[
        common_book_candidate_position_array
    ]
)

selected_last_top_of_book_move_position = (
    last_top_of_book_move_position_by_book[
        common_book_candidate_position_array
    ]
)

selected_last_top10_change_position = (
    last_top10_change_position_by_book[
        common_book_candidate_position_array
    ]
)

selected_last_spread_change_position = (
    last_spread_change_position_by_book[
        common_book_candidate_position_array
    ]
)


def elapsed_from_optional_book_position_ms(
    selected_positions: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Return elapsed milliseconds and availability flags."""
    available = (
        selected_positions >= 0
    )

    elapsed_ms = np.full(
        len(
            selected_positions
        ),
        np.nan,
        dtype="float64",
    )

    elapsed_ms[
        available
    ] = (
        current_book_batch_time_array[
            available
        ]
        - book_time_array[
            selected_positions[
                available
            ]
        ]
    ) / 1_000_000.0

    return elapsed_ms, available


time_since_last_midpoint_change_ms, (
    has_prior_midpoint_change
) = elapsed_from_optional_book_position_ms(
    selected_last_midpoint_change_position
)

time_since_last_top_of_book_move_ms, (
    has_prior_top_of_book_move
) = elapsed_from_optional_book_position_ms(
    selected_last_top_of_book_move_position
)

time_since_last_top10_change_ms, (
    has_prior_top10_change
) = elapsed_from_optional_book_position_ms(
    selected_last_top10_change_position
)

time_since_last_spread_change_ms, (
    has_prior_spread_change
) = elapsed_from_optional_book_position_ms(
    selected_last_spread_change_position
)


last_nonzero_midpoint_direction = np.zeros(
    len(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES
    ),
    dtype="int64",
)

last_nonzero_midpoint_direction[
    has_prior_midpoint_change
] = recomputed_midpoint_direction[
    selected_last_midpoint_change_position[
        has_prior_midpoint_change
    ]
]

last_nonzero_spread_direction = np.zeros(
    len(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES
    ),
    dtype="int64",
)

last_nonzero_spread_direction[
    has_prior_spread_change
] = recomputed_spread_direction[
    selected_last_spread_change_position[
        has_prior_spread_change
    ]
]


updates_since_last_midpoint_change = np.full(
    len(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES
    ),
    np.nan,
    dtype="float64",
)

updates_since_last_midpoint_change[
    has_prior_midpoint_change
] = (
    common_book_candidate_position_array[
        has_prior_midpoint_change
    ]
    - selected_last_midpoint_change_position[
        has_prior_midpoint_change
    ]
).astype("float64")


latest_transition_available = (
    common_book_candidate_position_array
    > 0
)

latest_update_l1_ofi = np.full(
    len(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES
    ),
    np.nan,
    dtype="float64",
)

latest_update_midpoint_return_bps = np.full(
    len(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES
    ),
    np.nan,
    dtype="float64",
)

latest_update_midpoint_direction = np.zeros(
    len(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES
    ),
    dtype="int64",
)

latest_update_spread_direction = np.zeros(
    len(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES
    ),
    dtype="int64",
)

latest_update_l1_ofi[
    latest_transition_available
] = book_l1_ofi[
    common_book_candidate_position_array[
        latest_transition_available
    ]
]

latest_update_midpoint_return_bps[
    latest_transition_available
] = (
    recomputed_log_midpoint_return[
        common_book_candidate_position_array[
            latest_transition_available
        ]
    ]
    * 10_000.0
)

latest_update_midpoint_direction[
    latest_transition_available
] = (
    recomputed_midpoint_direction[
        common_book_candidate_position_array[
            latest_transition_available
        ]
    ]
)

latest_update_spread_direction[
    latest_transition_available
] = (
    recomputed_spread_direction[
        common_book_candidate_position_array[
            latest_transition_available
        ]
    ]
)


book_recency_feature_payload = {
    "tminus_book_has_valid_latest_transition_flag": (
        latest_transition_available
    ),
    "tminus_book_time_since_latest_update_ms": (
        BATCH_CAUSAL_BOOK_FLOW_FEATURES[
            "common_book_age_ns"
        ].astype("float64").to_numpy()
        / 1_000_000.0
    ),
    "tminus_book_latest_update_level_one_ofi": (
        latest_update_l1_ofi
    ),
    (
        "tminus_book_latest_update_midpoint_"
        "return_basis_points"
    ): latest_update_midpoint_return_bps,
    "tminus_book_latest_update_midpoint_direction": (
        latest_update_midpoint_direction
    ),
    "tminus_book_latest_update_spread_direction": (
        latest_update_spread_direction
    ),
    "tminus_book_has_prior_midpoint_change_flag": (
        has_prior_midpoint_change
    ),
    "tminus_book_time_since_last_midpoint_change_ms": (
        time_since_last_midpoint_change_ms
    ),
    "tminus_book_last_nonzero_midpoint_direction": (
        last_nonzero_midpoint_direction
    ),
    "tminus_book_updates_since_last_midpoint_change": (
        updates_since_last_midpoint_change
    ),
    "tminus_book_has_prior_top_of_book_move_flag": (
        has_prior_top_of_book_move
    ),
    "tminus_book_time_since_last_top_of_book_move_ms": (
        time_since_last_top_of_book_move_ms
    ),
    "tminus_book_has_prior_top10_change_flag": (
        has_prior_top10_change
    ),
    "tminus_book_time_since_last_top10_change_ms": (
        time_since_last_top10_change_ms
    ),
    "tminus_book_has_prior_spread_change_flag": (
        has_prior_spread_change
    ),
    "tminus_book_time_since_last_spread_change_ms": (
        time_since_last_spread_change_ms
    ),
    "tminus_book_last_nonzero_spread_direction": (
        last_nonzero_spread_direction
    ),
}

book_flow_feature_payload.update(
    book_recency_feature_payload
)


# ------------------------------------------------------------
# Materialize the feature block in one concatenation
# ------------------------------------------------------------

BOOK_FLOW_FEATURE_BLOCK = pd.DataFrame(
    book_flow_feature_payload,
    index=(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES.index
    ),
)

require_unique_columns(
    BOOK_FLOW_FEATURE_BLOCK,
    "BOOK_FLOW_FEATURE_BLOCK",
)

overlapping_book_feature_columns = sorted(
    set(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES.columns
    )
    & set(
        BOOK_FLOW_FEATURE_BLOCK.columns
    )
)

require(
    not overlapping_book_feature_columns,
    (
        "Book-flow feature block overlaps identity or cutoff "
        f"columns: {overlapping_book_feature_columns}"
    ),
)

BATCH_CAUSAL_BOOK_FLOW_FEATURES = pd.concat(
    [
        BATCH_CAUSAL_BOOK_FLOW_FEATURES,
        BOOK_FLOW_FEATURE_BLOCK,
    ],
    axis=1,
)

BATCH_CAUSAL_BOOK_FLOW_FEATURES = (
    BATCH_CAUSAL_BOOK_FLOW_FEATURES.copy(
        deep=True
    )
)

require_unique_columns(
    BATCH_CAUSAL_BOOK_FLOW_FEATURES,
    "BATCH_CAUSAL_BOOK_FLOW_FEATURES",
)


# ------------------------------------------------------------
# Feature registry
# ------------------------------------------------------------

BOOK_FLOW_NONFEATURE_COLUMNS: Final[
    tuple[str, ...]
] = (
    *BOOK_FLOW_IDENTITY_COLUMNS,
    "batch_min_initiating_trade_collector_sequence",
    "common_book_candidate_position",
    "common_book_book_state_id",
    "common_book_collector_sequence",
    "common_book_local_receipt_time_ns",
    "common_book_partition",
    "common_book_partition_order",
    "common_book_age_ns",
    "common_book_same_local_timestamp_flag",
    "cross_partition_history_flag",
)

BOOK_FLOW_FEATURE_COLUMNS = [
    column_name
    for column_name in (
        BATCH_CAUSAL_BOOK_FLOW_FEATURES.columns
    )
    if column_name
    not in BOOK_FLOW_NONFEATURE_COLUMNS
]

book_flow_registry_rows: list[
    dict[str, Any]
] = []

for feature_name in (
    BOOK_FLOW_FEATURE_COLUMNS
):
    if feature_name.startswith(
        "tminus_book_flow_w250ms_"
    ):
        window_name = "W250MS"

    elif feature_name.startswith(
        "tminus_book_flow_w1s_"
    ):
        window_name = "W1S"

    elif feature_name.startswith(
        "tminus_book_flow_w5s_"
    ):
        window_name = "W5S"

    elif feature_name.startswith(
        "tminus_book_flow_w30s_"
    ):
        window_name = "W30S"

    else:
        window_name = None

    if (
        "level_one_ofi" in feature_name
    ):
        authority_class = (
            "DETERMINISTIC_LEVEL_ONE_OFI"
        )

        source_fields = (
            "best_bid; best_ask; best_bid_quantity; "
            "best_ask_quantity"
        )

    elif (
        "realized_variance" in feature_name
        or "realized_volatility" in feature_name
        or "log_midpoint" in feature_name
        or "midpoint_range" in feature_name
        or "midpoint_change" in feature_name
    ):
        authority_class = (
            "CAUSAL_PRICE_VARIATION"
        )

        source_fields = (
            "midpoint; midpoint_change"
        )

    elif (
        "message_" in feature_name
        or "inserted_level" in feature_name
        or "replaced_level" in feature_name
        or "deleted_level" in feature_name
        or "changed_level" in feature_name
        or "delete_noop" in feature_name
    ):
        authority_class = (
            "AUTHORITATIVE_UPDATE_COMPOSITION"
        )

        source_fields = (
            "Notebook 02 update-action counts"
        )

    elif (
        "time_since" in feature_name
        or "latest_update" in feature_name
        or "last_nonzero" in feature_name
        or "updates_since" in feature_name
        or "has_prior" in feature_name
        or "has_valid" in feature_name
    ):
        authority_class = (
            "CAUSAL_BOOK_RECENCY_STATE"
        )

        source_fields = (
            "ordered reconstructed book transitions"
        )

    elif (
        "coverage" in feature_name
        or feature_name.endswith(
            "_flag"
        )
    ):
        authority_class = (
            "DIAGNOSTIC_COVERAGE_CONTROL"
        )

        source_fields = (
            "book timestamps; partition boundaries; "
            "common book cutoff"
        )

    else:
        authority_class = (
            "CAUSAL_BOOK_UPDATE_HISTORY"
        )

        source_fields = (
            "RECONSTRUCTED_BOOK_STATES"
        )

    if (
        feature_name.endswith(
            "_rate_per_second"
        )
        or "realized_variance" in feature_name
        or "realized_volatility" in feature_name
    ):
        missingness_rule = (
            "NaN is required until the full requested "
            "clock-time history is observable; volatility "
            "also requires at least one valid transition."
        )

    elif (
        "time_since" in feature_name
        or "updates_since" in feature_name
        or (
            "latest_update" in feature_name
            and not feature_name.endswith(
                "_direction"
            )
        )
    ):
        missingness_rule = (
            "NaN is required when the referenced prior "
            "transition has not yet been observed."
        )

    else:
        missingness_rule = (
            "No missing value is permitted."
        )

    book_flow_registry_rows.append(
        {
            "feature_name": feature_name,
            "source_notebook": (
                "02_VISIBLE_BOOK_RECONSTRUCTION"
            ),
            "source_artifact": (
                "RECONSTRUCTED_BOOK_STATES"
            ),
            "source_fields": (
                source_fields
            ),
            "observational_unit": (
                CANONICAL_OBSERVATIONAL_UNIT
            ),
            "timing_class": (
                TIMING_CLASS_T_MINUS
            ),
            "window_name": (
                window_name
            ),
            "interval_convention": (
                BOOK_HISTORY_INTERVAL_CONVENTION
                if window_name is not None
                else "LATEST_CAUSALLY_ELIGIBLE_BOOK_STATE"
            ),
            "upper_bound_rule": (
                BOOK_HISTORY_UPPER_BOUND_RULE
            ),
            "same_time_prior_sequence_book_allowed": True,
            "same_time_event_information_allowed": False,
            "current_batch_information_included": False,
            "future_information_included": False,
            "authority_class": (
                authority_class
            ),
            "missingness_rule": (
                missingness_rule
            ),
        }
    )


CAUSAL_BOOK_FLOW_FEATURE_REGISTRY = (
    pd.DataFrame.from_records(
        book_flow_registry_rows
    )
)

require(
    CAUSAL_BOOK_FLOW_FEATURE_REGISTRY[
        "feature_name"
    ].is_unique,
    (
        "Causal book-flow feature registry contains "
        "duplicate feature names."
    ),
)

require(
    CAUSAL_BOOK_FLOW_FEATURE_REGISTRY[
        "timing_class"
    ].eq(
        TIMING_CLASS_T_MINUS
    ).all(),
    "A causal book-flow feature has the wrong timing class.",
)

require(
    CAUSAL_BOOK_FLOW_FEATURE_REGISTRY[
        "same_time_prior_sequence_book_allowed"
    ].all(),
    (
        "A book-flow registry row does not preserve the "
        "LOCAL_STRICT same-time book rule."
    ),
)

require(
    not CAUSAL_BOOK_FLOW_FEATURE_REGISTRY[
        "same_time_event_information_allowed"
    ].any(),
    (
        "A causal book-flow feature permits same-time event "
        "information."
    ),
)

require(
    not CAUSAL_BOOK_FLOW_FEATURE_REGISTRY[
        "current_batch_information_included"
    ].any(),
    "A causal book-flow feature includes current-batch data.",
)

require(
    not CAUSAL_BOOK_FLOW_FEATURE_REGISTRY[
        "future_information_included"
    ].any(),
    "A causal book-flow feature includes future information.",
)


# ------------------------------------------------------------
# Missingness and finite-value audit
# ------------------------------------------------------------

BOOK_FLOW_FEATURE_MISSINGNESS_AUDIT = (
    pd.DataFrame(
        {
            "feature_name": (
                BOOK_FLOW_FEATURE_COLUMNS
            ),
            "missing_count": [
                int(
                    BATCH_CAUSAL_BOOK_FLOW_FEATURES[
                        column_name
                    ].isna().sum()
                )
                for column_name in (
                    BOOK_FLOW_FEATURE_COLUMNS
                )
            ],
            "nonmissing_count": [
                int(
                    BATCH_CAUSAL_BOOK_FLOW_FEATURES[
                        column_name
                    ].notna().sum()
                )
                for column_name in (
                    BOOK_FLOW_FEATURE_COLUMNS
                )
            ],
        }
    )
)

numeric_book_flow_columns = [
    column_name
    for column_name in (
        BOOK_FLOW_FEATURE_COLUMNS
    )
    if (
        pd.api.types.is_numeric_dtype(
            BATCH_CAUSAL_BOOK_FLOW_FEATURES[
                column_name
            ]
        )
        or pd.api.types.is_bool_dtype(
            BATCH_CAUSAL_BOOK_FLOW_FEATURES[
                column_name
            ]
        )
    )
]

numeric_book_flow_values = (
    BATCH_CAUSAL_BOOK_FLOW_FEATURES[
        numeric_book_flow_columns
    ]
    .apply(
        pd.to_numeric,
        errors="raise",
    )
    .to_numpy(
        dtype="float64"
    )
)

book_flow_infinite_value_count = int(
    np.isinf(
        numeric_book_flow_values
    ).sum()
)

require(
    book_flow_infinite_value_count == 0,
    (
        "Causal book-flow features contain "
        f"{book_flow_infinite_value_count} infinite values."
    ),
)


book_flow_count_columns = [
    column_name
    for column_name in (
        BOOK_FLOW_FEATURE_COLUMNS
    )
    if column_name.endswith(
        "_count"
    )
]

for column_name in (
    book_flow_count_columns
):
    count_values = pd.to_numeric(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES[
            column_name
        ],
        errors="raise",
    )

    require(
        count_values.notna().all(),
        (
            f"Book-flow count feature {column_name!r} "
            "contains missing values."
        ),
    )

    require(
        count_values.ge(0).all(),
        (
            f"Book-flow count feature {column_name!r} "
            "contains a negative value."
        ),
    )


# ------------------------------------------------------------
# Same-batch feature invariance
# ------------------------------------------------------------

BOOK_FLOW_EVENT_PROJECTION_AUDIT = (
    PRIMARY_EVENT_TO_BATCH_MEMBERSHIP[
        [
            "primary_event_id",
            "primary_event_batch_id",
        ]
    ]
    .merge(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES[
            [
                "primary_event_batch_id",
                *BOOK_FLOW_FEATURE_COLUMNS,
            ]
        ],
        how="left",
        on="primary_event_batch_id",
        validate="many_to_one",
    )
)

require(
    len(
        BOOK_FLOW_EVENT_PROJECTION_AUDIT
    )
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Book-flow event projection changed the primary "
        "event population."
    ),
)

book_flow_event_invariance = (
    BOOK_FLOW_EVENT_PROJECTION_AUDIT.groupby(
        "primary_event_batch_id",
        observed=True,
        sort=False,
        dropna=False,
    )[
        BOOK_FLOW_FEATURE_COLUMNS
    ]
    .nunique(
        dropna=False
    )
)

book_flow_same_batch_invariance_failure_count = int(
    book_flow_event_invariance.gt(1).any(
        axis=1
    ).sum()
)

require(
    book_flow_same_batch_invariance_failure_count
    == 0,
    (
        "At least one simultaneous event batch received "
        "different causal book-flow feature values."
    ),
)


# ------------------------------------------------------------
# Leakage-facing forbidden-field audit
# ------------------------------------------------------------

FORBIDDEN_BOOK_FLOW_COLUMNS: Final[
    tuple[str, ...]
] = (
    "batch_event_count",
    "buy_event_count",
    "sell_event_count",
    "batch_print_count",
    "batch_quantity",
    "batch_notional",
    "event_side",
    "event_quantity",
    "event_notional",
    "aggregate_mark_available_time_ns",
)

forbidden_book_flow_columns_present = sorted(
    set(
        FORBIDDEN_BOOK_FLOW_COLUMNS
    )
    & set(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES.columns
    )
)

tplus_book_flow_columns = sorted(
    column_name
    for column_name in (
        BATCH_CAUSAL_BOOK_FLOW_FEATURES.columns
    )
    if column_name.startswith(
        "tplus_"
    )
)

future_like_book_flow_columns = sorted(
    column_name
    for column_name in (
        BATCH_CAUSAL_BOOK_FLOW_FEATURES.columns
    )
    if (
        column_name.startswith(
            "future_"
        )
        or column_name.startswith(
            "label_"
        )
        or column_name.startswith(
            "target_"
        )
    )
)

require(
    not forbidden_book_flow_columns_present,
    (
        "Causal book-flow feature table contains current-"
        "batch fields: "
        f"{forbidden_book_flow_columns_present}"
    ),
)

require(
    not tplus_book_flow_columns,
    (
        "Causal book-flow feature table contains t-plus "
        f"fields: {tplus_book_flow_columns}"
    ),
)

require(
    not future_like_book_flow_columns,
    (
        "Causal book-flow feature table contains future-like "
        f"fields: {future_like_book_flow_columns}"
    ),
)


# ------------------------------------------------------------
# Gate table
# ------------------------------------------------------------

same_time_prior_sequence_memberships = int(
    BOOK_WINDOW_FEATURE_AUDIT[
        "same_time_prior_sequence_state_memberships"
    ].sum()
)

partial_book_window_memberships = int(
    BOOK_WINDOW_FEATURE_AUDIT[
        "partial_coverage_batch_count"
    ].sum()
)

cross_partition_book_window_memberships = int(
    BOOK_WINDOW_FEATURE_AUDIT[
        "cross_partition_history_batch_count"
    ].sum()
)

BOOK_FLOW_FEATURE_GATES = pd.DataFrame(
    [
        {
            "gate": (
                "prior_wide_feature_frames_defragmented"
            ),
            "severity": "BLOCKING",
            "passed": (
                EVENT_FLOW_FRAME_DEFRAGMENTED
                and STATIC_BOOK_FRAME_DEFRAGMENTED
            ),
            "evidence": (
                "deep copies applied before later joins"
            ),
        },
        {
            "gate": (
                "book_source_rows_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    BOOK_FLOW_SOURCE
                )
                == EXPECTED_RECONSTRUCTED_BOOK_STATES
            ),
            "evidence": (
                f"states="
                f"{len(BOOK_FLOW_SOURCE)}"
            ),
        },
        {
            "gate": (
                "book_transition_fields_reconcile"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                BOOK_TRANSITION_RECONCILIATION_AUDIT[
                    "mismatch_count"
                ].eq(0).all()
            ),
            "evidence": (
                f"fields="
                f"{len(BOOK_TRANSITION_RECONCILIATION_AUDIT)}"
            ),
        },
        {
            "gate": (
                "common_book_dual_cutoff_preserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                book_same_time_cutoff_violation_count
                == 0
                and book_sequence_cutoff_violation_count
                == 0
            ),
            "evidence": (
                f"same_time_violations="
                f"{book_same_time_cutoff_violation_count}; "
                f"sequence_violations="
                f"{book_sequence_cutoff_violation_count}"
            ),
        },
        {
            "gate": (
                "no_future_partition_book_history"
            ),
            "severity": "BLOCKING",
            "passed": (
                book_future_partition_violation_count
                == 0
            ),
            "evidence": (
                f"future_partition_memberships="
                f"{book_future_partition_violation_count}"
            ),
        },
        {
            "gate": (
                "book_window_nested_monotonicity"
            ),
            "severity": "BLOCKING",
            "passed": bool(
                BOOK_WINDOW_MONOTONICITY_AUDIT[
                    "failure_count"
                ].eq(0).all()
            ),
            "evidence": (
                f"comparisons="
                f"{len(BOOK_WINDOW_MONOTONICITY_AUDIT)}"
            ),
        },
        {
            "gate": (
                "book_flow_batch_rows_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    BATCH_CAUSAL_BOOK_FLOW_FEATURES
                )
                == EXPECTED_PRIMARY_BATCH_ROWS
            ),
            "evidence": (
                f"rows="
                f"{len(BATCH_CAUSAL_BOOK_FLOW_FEATURES)}"
            ),
        },
        {
            "gate": (
                "book_flow_same_batch_invariance"
            ),
            "severity": "BLOCKING",
            "passed": (
                book_flow_same_batch_invariance_failure_count
                == 0
            ),
            "evidence": (
                f"failed_batches="
                f"{book_flow_same_batch_invariance_failure_count}"
            ),
        },
        {
            "gate": (
                "book_flow_no_infinite_values"
            ),
            "severity": "BLOCKING",
            "passed": (
                book_flow_infinite_value_count
                == 0
            ),
            "evidence": (
                f"infinite_values="
                f"{book_flow_infinite_value_count}"
            ),
        },
        {
            "gate": (
                "no_current_batch_fields"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    forbidden_book_flow_columns_present
                )
                == 0
            ),
            "evidence": (
                f"forbidden_fields="
                f"{len(forbidden_book_flow_columns_present)}"
            ),
        },
        {
            "gate": (
                "no_tplus_fields"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    tplus_book_flow_columns
                )
                == 0
            ),
            "evidence": (
                f"tplus_fields="
                f"{len(tplus_book_flow_columns)}"
            ),
        },
        {
            "gate": (
                "no_future_label_fields"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    future_like_book_flow_columns
                )
                == 0
            ),
            "evidence": (
                f"future_like_fields="
                f"{len(future_like_book_flow_columns)}"
            ),
        },
        {
            "gate": (
                "partial_book_window_coverage_present"
            ),
            "severity": "WARNING",
            "passed": (
                partial_book_window_memberships
                == 0
            ),
            "evidence": (
                f"partial_memberships="
                f"{partial_book_window_memberships}"
            ),
        },
        {
            "gate": (
                "same_time_prior_sequence_book_states_used"
            ),
            "severity": "WARNING",
            "passed": (
                same_time_prior_sequence_memberships
                == 0
            ),
            "evidence": (
                f"memberships="
                f"{same_time_prior_sequence_memberships}; "
                "all satisfy LOCAL_STRICT sequence cutoff"
            ),
        },
        {
            "gate": (
                "cross_partition_book_history_present"
            ),
            "severity": "WARNING",
            "passed": (
                cross_partition_book_window_memberships
                == 0
            ),
            "evidence": (
                f"memberships="
                f"{cross_partition_book_window_memberships}"
            ),
        },
        {
            "gate": (
                "first_book_transition_left_censored"
            ),
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                "initial reconstructed state contributes "
                "update actions but no OFI or price transition"
            ),
        },
    ]
)

BOOK_FLOW_FEATURE_GATES[
    "status"
] = np.select(
    [
        BOOK_FLOW_FEATURE_GATES[
            "passed"
        ],
        BOOK_FLOW_FEATURE_GATES[
            "severity"
        ].eq("BLOCKING"),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

book_flow_blocking_failures = (
    BOOK_FLOW_FEATURE_GATES.loc[
        BOOK_FLOW_FEATURE_GATES[
            "severity"
        ].eq("BLOCKING")
        & ~BOOK_FLOW_FEATURE_GATES[
            "passed"
        ]
    ]
)

require(
    book_flow_blocking_failures.empty,
    (
        "Causal book-flow feature construction contains "
        "blocking failures."
    ),
)


# ------------------------------------------------------------
# Frozen downstream state
# ------------------------------------------------------------

CAUSAL_BOOK_FLOW_FEATURES_VERIFIED: Final[
    bool
] = True

CAUSAL_BOOK_FLOW_FEATURE_ROW_COUNT: Final[
    int
] = int(
    len(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES
    )
)

CAUSAL_BOOK_FLOW_FEATURE_COUNT: Final[
    int
] = int(
    len(
        CAUSAL_BOOK_FLOW_FEATURE_REGISTRY
    )
)


# ------------------------------------------------------------
# Compact displays
# ------------------------------------------------------------

display(
    BOOK_TRANSITION_RECONCILIATION_AUDIT
)

display(
    BOOK_WINDOW_FEATURE_AUDIT
)

display(
    BOOK_WINDOW_MONOTONICITY_AUDIT
)

display(
    BOOK_FLOW_FEATURE_MISSINGNESS_AUDIT.loc[
        BOOK_FLOW_FEATURE_MISSINGNESS_AUDIT[
            "missing_count"
        ].gt(0)
    ]
)

display(
    CAUSAL_BOOK_FLOW_FEATURE_REGISTRY[
        [
            "feature_name",
            "window_name",
            "timing_class",
            "authority_class",
            "missingness_rule",
        ]
    ]
)

display(
    BOOK_FLOW_FEATURE_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "causal_book_flow_features_verified": (
        CAUSAL_BOOK_FLOW_FEATURES_VERIFIED
    ),
    "observational_unit": (
        CANONICAL_OBSERVATIONAL_UNIT
    ),
    "timing_class": (
        TIMING_CLASS_T_MINUS
    ),
    "book_history_interval_convention": (
        BOOK_HISTORY_INTERVAL_CONVENTION
    ),
    "book_flow_definition": (
        BOOK_FLOW_OFI_DEFINITION
    ),
    "book_source_rows": int(
        len(
            BOOK_FLOW_SOURCE
        )
    ),
    "batch_rows": (
        CAUSAL_BOOK_FLOW_FEATURE_ROW_COUNT
    ),
    "book_flow_feature_count": (
        CAUSAL_BOOK_FLOW_FEATURE_COUNT
    ),
    "clock_window_count": int(
        len(
            CLOCK_TIME_WINDOWS_NS
        )
    ),
    "same_time_prior_sequence_memberships": int(
        same_time_prior_sequence_memberships
    ),
    "partial_window_memberships": int(
        partial_book_window_memberships
    ),
    "cross_partition_window_memberships": int(
        cross_partition_book_window_memberships
    ),
    "transition_reconciliation_failures": int(
        BOOK_TRANSITION_RECONCILIATION_AUDIT[
            "mismatch_count"
        ].sum()
    ),
    "same_time_cutoff_violations": int(
        book_same_time_cutoff_violation_count
    ),
    "sequence_cutoff_violations": int(
        book_sequence_cutoff_violation_count
    ),
    "future_partition_history_violations": int(
        book_future_partition_violation_count
    ),
    "same_batch_invariance_failures": int(
        book_flow_same_batch_invariance_failure_count
    ),
    "infinite_feature_values": int(
        book_flow_infinite_value_count
    ),
    "prior_frames_defragmented": True,
    "current_batch_fields_attached": False,
    "tplus_fields_attached": False,
    "future_labels_attached": False,
    "verified_at_utc": utc_now_iso(),
}

               field  compared_rows  mismatch_count  maximum_absolute_error status
0    best_bid_change          35984               0            6.694201e-12   PASS
1    best_ask_change          35984               0            6.985079e-12   PASS
2    midpoint_change          35984               0            6.985079e-12   PASS
3  top_of_book_moved          35985               0                     NaN   PASS
4     top_10_changed          35985               0                     NaN   PASS
5      movement_code          35985               0                     NaN   PASS

,window_name,window_ns,full_coverage_batch_count,partial_coverage_batch_count,cross_partition_history_batch_count,same_time_prior_sequence_state_memberships,total_book_state_memberships,total_valid_transition_memberships,maximum_book_state_count,maximum_message_level_count,maximum_actual_changed_level_count,status
0,W250MS,250000000,13564,0,3,107,33755,33755,3,1995,1520,PASS
1,W1S,1000000000,13562,2,7,107,135542,135540,11,4237,3268,PASS
2,W5S,5000000000,13546,18,46,107,677800,677782,51,6171,5037,PASS
3,W30S,30000000000,13432,132,329,107,4052783,4052651,301,12213,10354,PASS

                         metric smaller_window larger_window  failure_count status
0                   state_count         W250MS           W1S              0   PASS
1                   state_count            W1S           W5S              0   PASS
2                   state_count            W5S          W30S              0   PASS
3              transition_count         W250MS           W1S              0   PASS
4              transition_count            W1S           W5S              0   PASS
5              transition_count            W5S          W30S              0   PASS
6           message_level_count         W250MS           W1S              0   PASS
7           message_level_count            W1S           W5S              0   PASS
8           message_level_count            W5S          W30S              0   PASS
9    actual_changed_level_count         W250MS           W1S              0   PASS
10   actual_changed_level_count            W1S           W5S              0   PASS
11   actual_changed_level_count            W5S          W30S              0   PASS
12       top_of_book_move_count         W250MS           W1S              0   PASS
13       top_of_book_move_count            W1S           W5S              0   PASS
14       top_of_book_move_count            W5S          W30S              0   PASS
15           top10_change_count         W250MS           W1S              0   PASS
16           top10_change_count            W1S           W5S              0   PASS
17           top10_change_count            W5S          W30S              0   PASS
18  absolute_midpoint_variation         W250MS           W1S              0   PASS
19  absolute_midpoint_variation            W1S           W5S              0   PASS
20  absolute_midpoint_variation            W5S          W30S              0   PASS
21              absolute_l1_ofi         W250MS           W1S              0   PASS
22              absolute_l1_ofi            W1S           W5S              0   PASS
23              absolute_l1_ofi            W5S          W30S              0   PASS

                                                   feature_name  missing_count  nonmissing_count
66                  tminus_book_flow_w1s_update_rate_per_second              2             13562
70           tminus_book_flow_w1s_message_level_rate_per_second              2             13562
78    tminus_book_flow_w1s_actual_changed_level_rate_per_second              2             13562
82        tminus_book_flow_w1s_top_of_book_move_rate_per_second              2             13562
85            tminus_book_flow_w1s_top10_change_rate_per_second              2             13562
100                      tminus_book_flow_w1s_realized_variance              2             13562
101       tminus_book_flow_w1s_realized_volatility_basis_points              2             13562
116          tminus_book_flow_w1s_level_one_ofi_rate_per_second              2             13562
125                 tminus_book_flow_w5s_update_rate_per_second             18             13546
129          tminus_book_flow_w5s_message_level_rate_per_second             18             13546
137   tminus_book_flow_w5s_actual_changed_level_rate_per_second             18             13546
141       tminus_book_flow_w5s_top_of_book_move_rate_per_second             18             13546
144           tminus_book_flow_w5s_top10_change_rate_per_second             18             13546
159                      tminus_book_flow_w5s_realized_variance             18             13546
160       tminus_book_flow_w5s_realized_volatility_basis_points             18             13546
175          tminus_book_flow_w5s_level_one_ofi_rate_per_second             18             13546
184                tminus_book_flow_w30s_update_rate_per_second            132             13432
188         tminus_book_flow_w30s_message_level_rate_per_second            132             13432
196  tminus_book_flow_w30s_actual_changed_level_rate_per_second            132             13432
200      tminus_book_flow_w30s_top_of_book_move_rate_per_second            132             13432
203          tminus_book_flow_w30s_top10_change_rate_per_second            132             13432
218                     tminus_book_flow_w30s_realized_variance            132             13432
219      tminus_book_flow_w30s_realized_volatility_basis_points            132             13432
234         tminus_book_flow_w30s_level_one_ofi_rate_per_second            132             13432
243              tminus_book_time_since_last_midpoint_change_ms             93             13471
245              tminus_book_updates_since_last_midpoint_change             93             13471
247             tminus_book_time_since_last_top_of_book_move_ms             93             13471
251                tminus_book_time_since_last_spread_change_ms           1589             11975

                                             feature_name window_name timing_class              authority_class                                                                 missingness_rule
0              tminus_book_flow_w250ms_full_coverage_flag      W250MS      T_MINUS  DIAGNOSTIC_COVERAGE_CONTROL                                                   No missing value is permitted.
1               tminus_book_flow_w250ms_coverage_fraction      W250MS      T_MINUS  DIAGNOSTIC_COVERAGE_CONTROL                                                   No missing value is permitted.
2       tminus_book_flow_w250ms_observed_duration_seconds      W250MS      T_MINUS   CAUSAL_BOOK_UPDATE_HISTORY                                                   No missing value is permitted.
3    tminus_book_flow_w250ms_cross_partition_history_flag      W250MS      T_MINUS  DIAGNOSTIC_COVERAGE_CONTROL                                                   No missing value is permitted.
4                     tminus_book_flow_w250ms_state_count      W250MS      T_MINUS   CAUSAL_BOOK_UPDATE_HISTORY                                                   No missing value is permitted.
..                                                    ...         ...          ...                          ...                                                                              ...
248               tminus_book_has_prior_top10_change_flag        None      T_MINUS    CAUSAL_BOOK_RECENCY_STATE                                                   No missing value is permitted.
249           tminus_book_time_since_last_top10_change_ms        None      T_MINUS    CAUSAL_BOOK_RECENCY_STATE  NaN is required when the referenced prior transition has not yet been observed.
250              tminus_book_has_prior_spread_change_flag        None      T_MINUS    CAUSAL_BOOK_RECENCY_STATE                                                   No missing value is permitted.
251          tminus_book_time_since_last_spread_change_ms        None      T_MINUS    CAUSAL_BOOK_RECENCY_STATE  NaN is required when the referenced prior transition has not yet been observed.
252             tminus_book_last_nonzero_spread_direction        None      T_MINUS    CAUSAL_BOOK_RECENCY_STATE                                                   No missing value is permitted.

[253 rows x 5 columns]

                                         gate  severity   status                                                                               evidence
0      prior_wide_feature_frames_defragmented  BLOCKING     PASS                                                 deep copies applied before later joins
1                  book_source_rows_conserved  BLOCKING     PASS                                                                           states=35985
2            book_transition_fields_reconcile  BLOCKING     PASS                                                                               fields=6
3           common_book_dual_cutoff_preserved  BLOCKING     PASS                                          same_time_violations=0; sequence_violations=0
4            no_future_partition_book_history  BLOCKING     PASS                                                         future_partition_memberships=0
5             book_window_nested_monotonicity  BLOCKING     PASS                                                                         comparisons=24
6              book_flow_batch_rows_conserved  BLOCKING     PASS                                                                             rows=13564
7             book_flow_same_batch_invariance  BLOCKING     PASS                                                                       failed_batches=0
8                book_flow_no_infinite_values  BLOCKING     PASS                                                                      infinite_values=0
9                     no_current_batch_fields  BLOCKING     PASS                                                                     forbidden_fields=0
10                            no_tplus_fields  BLOCKING     PASS                                                                         tplus_fields=0
11                     no_future_label_fields  BLOCKING     PASS                                                                   future_like_fields=0
12       partial_book_window_coverage_present   WARNING  WARNING                                                                partial_memberships=152
13  same_time_prior_sequence_book_states_used   WARNING  WARNING                              memberships=428; all satisfy LOCAL_STRICT sequence cutoff
14       cross_partition_book_history_present   WARNING  WARNING                                                                        memberships=385
15        first_book_transition_left_censored   WARNING  WARNING  initial reconstructed state contributes update actions but no OFI or price transition

{'status': 'PASS',
 'causal_book_flow_features_verified': True,
 'observational_unit': 'PRIMARY_SCORING_BATCH',
 'timing_class': 'T_MINUS',
 'book_history_interval_convention': '[t-window, t] WITH LOCAL_STRICT_SEQUENCE_CUTOFF',
 'book_flow_definition': 'Cont-style level-one order-flow imbalance from consecutive reconstructed visible-book states',
 'book_source_rows': 35985,
 'batch_rows': 13564,
 'book_flow_feature_count': 253,
 'clock_window_count': 4,
 'same_time_prior_sequence_memberships': 428,
 'partial_window_memberships': 152,
 'cross_partition_window_memberships': 385,
 'transition_reconciliation_failures': 0,
 'same_time_cutoff_violations': 0,
 'sequence_cutoff_violations': 0,
 'future_partition_history_violations': 0,
 'same_batch_invariance_failures': 0,
 'infinite_feature_values': 0,
 'prior_frames_defragmented': True,
 'current_batch_fields_attached': False,
 'tplus_fields_attached': False,
 'future_labels_attached': False,
 'verified_at_utc': '2026-07-19T09:34:09.341124+00:00'}

In [13]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 13 — Authoritative T-minus market-state feature assembly,
#           causal missingness policy, availability masks,
#           and leakage audit
# ============================================================

import re


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "STATIC_VISIBLE_BOOK_FEATURES_VERIFIED",
        False,
    )
    is True,
    "Static visible-book features have not been verified.",
)

require(
    globals().get(
        "CAUSAL_EVENT_FLOW_FEATURES_VERIFIED",
        False,
    )
    is True,
    "Causal event-flow features have not been verified.",
)

require(
    globals().get(
        "CAUSAL_BOOK_FLOW_FEATURES_VERIFIED",
        False,
    )
    is True,
    "Causal book-flow features have not been verified.",
)

require(
    isinstance(
        BATCH_STATIC_VISIBLE_BOOK_FEATURES,
        pd.DataFrame,
    ),
    "BATCH_STATIC_VISIBLE_BOOK_FEATURES is unavailable.",
)

require(
    isinstance(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES,
        pd.DataFrame,
    ),
    "BATCH_CAUSAL_EVENT_FLOW_FEATURES is unavailable.",
)

require(
    isinstance(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES,
        pd.DataFrame,
    ),
    "BATCH_CAUSAL_BOOK_FLOW_FEATURES is unavailable.",
)

require(
    isinstance(
        PRIMARY_SCORING_BATCHES,
        pd.DataFrame,
    ),
    "PRIMARY_SCORING_BATCHES is unavailable.",
)


# ------------------------------------------------------------
# Frozen final feature-table contract
# ------------------------------------------------------------

FINAL_MARKET_STATE_OBSERVATIONAL_UNIT: Final[str] = (
    "PRIMARY_SCORING_BATCH"
)

FINAL_MARKET_STATE_TIMING_CLASS: Final[str] = (
    "T_MINUS"
)

FINAL_MARKET_STATE_PHYSICAL_TABLE_ROLE: Final[str] = (
    "CAUSAL_MARKET_STATE_FEATURE"
)

FINAL_MARKET_STATE_LABEL_POLICY: Final[str] = (
    "FUTURE_LABELS_PHYSICALLY_SEPARATE"
)

FINAL_MARKET_STATE_POST_BATCH_POLICY: Final[str] = (
    "T_PLUS_CONTEXT_PHYSICALLY_SEPARATE"
)

FINAL_MARKET_STATE_MISSINGNESS_POLICY: Final[str] = (
    "PRESERVE_CAUSALLY_EXPLAINED_NAN_WITHOUT_IMPUTATION"
)

FINAL_MARKET_STATE_IDENTITY_COLUMNS: Final[
    tuple[str, ...]
] = (
    "primary_event_batch_id",
    "primary_event_batch_number",
    "partition_batch_index",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
)


# ------------------------------------------------------------
# Local helpers
# ------------------------------------------------------------

def resolve_existing_dataframe(
    candidate_names: tuple[str, ...],
    *,
    description: str,
) -> tuple[str | None, pd.DataFrame | None]:
    """Return the first existing DataFrame from candidate names."""
    for candidate_name in candidate_names:
        candidate_value = globals().get(
            candidate_name
        )

        if isinstance(
            candidate_value,
            pd.DataFrame,
        ):
            return (
                candidate_name,
                candidate_value,
            )

    return (
        None,
        None,
    )


def normalize_feature_registry(
    *,
    registry: pd.DataFrame | None,
    registry_name: str | None,
    feature_block: pd.DataFrame,
    feature_family: str,
    source_block_name: str,
) -> pd.DataFrame:
    """Normalize one upstream feature registry."""

    prefix_feature_names = [
        column_name
        for column_name in feature_block.columns
        if column_name.startswith(
            "tminus_"
        )
    ]

    require(
        len(
            prefix_feature_names
        )
        > 0,
        (
            f"{source_block_name} contains no T-minus "
            "feature columns."
        ),
    )

    if registry is None:
        normalized_registry = pd.DataFrame(
            {
                "feature_name": (
                    prefix_feature_names
                ),
                "timing_class": (
                    FINAL_MARKET_STATE_TIMING_CLASS
                ),
                "authority_class": (
                    "UPSTREAM_VERIFIED_FEATURE"
                ),
                "missingness_rule": "",
            }
        )

        effective_registry_name = (
            "PREFIX_DERIVED_REGISTRY"
        )

    else:
        require(
            "feature_name"
            in registry.columns,
            (
                f"{registry_name} does not contain "
                "'feature_name'."
            ),
        )

        normalized_registry = (
            registry.copy()
            .reset_index(drop=True)
        )

        effective_registry_name = str(
            registry_name
        )

        normalized_registry[
            "feature_name"
        ] = (
            normalized_registry[
                "feature_name"
            ]
            .astype("string")
            .str.strip()
        )

        require(
            normalized_registry[
                "feature_name"
            ].notna().all(),
            (
                f"{registry_name} contains a missing "
                "feature name."
            ),
        )

        require(
            normalized_registry[
                "feature_name"
            ].is_unique,
            (
                f"{registry_name} contains duplicate "
                "feature names."
            ),
        )

        registry_feature_names = set(
            normalized_registry[
                "feature_name"
            ].tolist()
        )

        prefix_feature_name_set = set(
            prefix_feature_names
        )

        registered_but_missing_from_block = sorted(
            registry_feature_names
            - prefix_feature_name_set
        )

        require(
            not registered_but_missing_from_block,
            (
                f"{registry_name} registers features absent "
                f"from {source_block_name}: "
                f"{registered_but_missing_from_block}"
            ),
        )

        unregistered_block_features = sorted(
            prefix_feature_name_set
            - registry_feature_names
        )

        if unregistered_block_features:
            supplemental_registry = pd.DataFrame(
                {
                    "feature_name": (
                        unregistered_block_features
                    ),
                    "timing_class": (
                        FINAL_MARKET_STATE_TIMING_CLASS
                    ),
                    "authority_class": (
                        "UPSTREAM_VERIFIED_UNREGISTERED_FEATURE"
                    ),
                    "missingness_rule": "",
                }
            )

            normalized_registry = pd.concat(
                [
                    normalized_registry,
                    supplemental_registry,
                ],
                axis=0,
                ignore_index=True,
                sort=False,
            )

    if (
        "timing_class"
        not in normalized_registry.columns
    ):
        normalized_registry[
            "timing_class"
        ] = (
            FINAL_MARKET_STATE_TIMING_CLASS
        )

    normalized_registry[
        "timing_class"
    ] = (
        normalized_registry[
            "timing_class"
        ]
        .astype("string")
        .str.strip()
        .str.upper()
    )

    require(
        normalized_registry[
            "timing_class"
        ]
        .eq(
            FINAL_MARKET_STATE_TIMING_CLASS
        )
        .all(),
        (
            f"{source_block_name} registers a feature "
            "outside the T-minus timing class."
        ),
    )

    if (
        "authority_class"
        not in normalized_registry.columns
    ):
        normalized_registry[
            "authority_class"
        ] = (
            "UPSTREAM_VERIFIED_FEATURE"
        )

    if (
        "missingness_rule"
        not in normalized_registry.columns
    ):
        normalized_registry[
            "missingness_rule"
        ] = ""

    normalized_registry[
        "missingness_rule"
    ] = (
        normalized_registry[
            "missingness_rule"
        ]
        .fillna("")
        .astype("string")
    )

    normalized_registry[
        "feature_family"
    ] = feature_family

    normalized_registry[
        "source_block"
    ] = source_block_name

    normalized_registry[
        "source_registry"
    ] = effective_registry_name

    normalized_registry[
        "observational_unit"
    ] = (
        FINAL_MARKET_STATE_OBSERVATIONAL_UNIT
    )

    normalized_registry[
        "physical_table_role"
    ] = (
        FINAL_MARKET_STATE_PHYSICAL_TABLE_ROLE
    )

    normalized_registry[
        "authorized_in_feature_table"
    ] = True

    normalized_registry[
        "current_batch_information_allowed"
    ] = False

    normalized_registry[
        "future_information_allowed"
    ] = False

    normalized_registry[
        "post_batch_information_allowed"
    ] = False

    normalized_registry = (
        normalized_registry
        .sort_values(
            "feature_name",
            kind="stable",
        )
        .reset_index(drop=True)
    )

    require(
        normalized_registry[
            "feature_name"
        ].is_unique,
        (
            f"Normalized registry for {source_block_name} "
            "contains duplicate feature names."
        ),
    )

    return normalized_registry


def normalize_identity_frame(
    frame: pd.DataFrame,
    *,
    frame_name: str,
) -> pd.DataFrame:
    """Return the canonical sorted identity frame."""

    require_columns(
        frame,
        FINAL_MARKET_STATE_IDENTITY_COLUMNS,
        frame_name,
    )

    normalized = (
        frame[
            list(
                FINAL_MARKET_STATE_IDENTITY_COLUMNS
            )
        ]
        .copy()
        .sort_values(
            "primary_event_batch_number",
            kind="stable",
        )
        .reset_index(drop=True)
    )

    normalized[
        "primary_event_batch_id"
    ] = (
        normalized[
            "primary_event_batch_id"
        ]
        .astype("string")
    )

    normalized[
        "event_partition"
    ] = (
        normalized[
            "event_partition"
        ]
        .astype("string")
        .str.strip()
        .str.upper()
    )

    for integer_column in (
        "primary_event_batch_number",
        "partition_batch_index",
        "event_partition_order",
        "event_time_ns",
    ):
        normalized[
            integer_column
        ] = parse_required_int64(
            normalized[
                integer_column
            ],
            (
                f"{frame_name}."
                f"{integer_column}"
            ),
        )

    require(
        len(
            normalized
        )
        == EXPECTED_PRIMARY_BATCH_ROWS,
        (
            f"{frame_name} does not contain the expected "
            "number of scoring batches."
        ),
    )

    require(
        normalized[
            "primary_event_batch_id"
        ].is_unique,
        (
            f"{frame_name} contains duplicate batch IDs."
        ),
    )

    require(
        normalized[
            "primary_event_batch_number"
        ].is_unique,
        (
            f"{frame_name} contains duplicate batch "
            "numbers."
        ),
    )

    require(
        normalized[
            "primary_event_batch_number"
        ].is_monotonic_increasing,
        (
            f"{frame_name} is not ordered by batch number."
        ),
    )

    return normalized


def compare_identity_frames(
    left: pd.DataFrame,
    right: pd.DataFrame,
    *,
    right_name: str,
) -> None:
    """Require exact identity equivalence ignoring dtype metadata."""

    try:
        pd.testing.assert_frame_equal(
            left,
            right,
            check_dtype=False,
            check_exact=True,
            check_names=True,
        )

    except AssertionError as exc:
        raise AssertionError(
            (
                f"{right_name} does not match the canonical "
                f"scoring-batch identity: {exc}"
            )
        ) from exc


def normalized_rule_declares_conditional_nan(
    rule: str,
) -> bool:
    """Identify an upstream-declared conditional missingness rule."""

    normalized_rule = (
        str(
            rule
        )
        .strip()
        .lower()
    )

    if not normalized_rule:
        return False

    no_missing_phrases = (
        "no missing value",
        "no missing values",
        "missing value is permitted",
        "missing values are permitted",
        "must not be missing",
        "complete values required",
    )

    if any(
        phrase in normalized_rule
        for phrase in no_missing_phrases
    ):
        if (
            "not permitted"
            in normalized_rule
            or normalized_rule.startswith(
                "no missing"
            )
        ):
            return False

    conditional_tokens = (
        "nan",
        "missing",
        "left-censor",
        "unavailable",
        "until",
        "when",
        "zero denominator",
        "insufficient history",
        "partial coverage",
        "not yet observed",
    )

    return any(
        token in normalized_rule
        for token in conditional_tokens
    )


def initial_true_prefix_mask(
    observed_mask: np.ndarray,
) -> tuple[bool, np.ndarray]:
    """Return whether True values form one initial contiguous prefix."""

    require(
        observed_mask.ndim == 1,
        "Missingness mask must be one-dimensional.",
    )

    if not observed_mask.any():
        return (
            True,
            np.zeros_like(
                observed_mask,
                dtype=bool,
            ),
        )

    first_false_positions = np.flatnonzero(
        ~observed_mask
    )

    if first_false_positions.size == 0:
        prefix_length = len(
            observed_mask
        )

    else:
        prefix_length = int(
            first_false_positions[
                0
            ]
        )

    prefix_mask = (
        np.arange(
            len(
                observed_mask
            ),
            dtype="int64",
        )
        < prefix_length
    )

    return (
        bool(
            np.array_equal(
                observed_mask,
                prefix_mask,
            )
        ),
        prefix_mask,
    )


def add_boolean_false_candidate(
    candidates: list[
        tuple[str, np.ndarray]
    ],
    *,
    column_name: str,
    feature_table: pd.DataFrame,
) -> None:
    """Add a missingness candidate based on a false boolean flag."""

    if (
        column_name
        not in feature_table.columns
    ):
        return

    candidate_series = (
        feature_table[
            column_name
        ]
    )

    try:
        parsed_boolean = strict_boolean_series(
            candidate_series,
            field_name=(
                f"missingness companion "
                f"{column_name}"
            ),
        )

    except Exception:
        return

    candidates.append(
        (
            f"{column_name}=False",
            ~parsed_boolean.to_numpy(
                dtype=bool
            ),
        )
    )


def add_numeric_nonpositive_candidate(
    candidates: list[
        tuple[str, np.ndarray]
    ],
    *,
    column_name: str,
    feature_table: pd.DataFrame,
) -> None:
    """Add a candidate based on a zero or negative denominator."""

    if (
        column_name
        not in feature_table.columns
    ):
        return

    candidate_numeric = pd.to_numeric(
        feature_table[
            column_name
        ],
        errors="coerce",
    )

    candidate_mask = (
        candidate_numeric.notna()
        & candidate_numeric.le(0)
    ).to_numpy(
        dtype=bool
    )

    candidates.append(
        (
            f"{column_name}<=0",
            candidate_mask,
        )
    )


def feature_namespace(
    feature_name: str,
) -> str:
    """Return the causal sibling namespace for one feature."""

    event_clock_match = re.match(
        (
            r"^(tminus_event_"
            r"(?:w250ms|w1s|w5s|w30s))_"
        ),
        feature_name,
    )

    if event_clock_match:
        return event_clock_match.group(
            1
        )

    prior_batch_match = re.match(
        (
            r"^(tminus_prior_batch_"
            r"(?:b10|b50))_"
        ),
        feature_name,
    )

    if prior_batch_match:
        return prior_batch_match.group(
            1
        )

    book_clock_match = re.match(
        (
            r"^(tminus_book_flow_"
            r"(?:w250ms|w1s|w5s|w30s))_"
        ),
        feature_name,
    )

    if book_clock_match:
        return book_clock_match.group(
            1
        )

    if feature_name.startswith(
        "tminus_book_"
    ):
        return "tminus_book"

    if feature_name.startswith(
        "tminus_time_since_"
    ):
        return "tminus_time_since"

    return feature_name.rsplit(
        "_",
        1,
    )[
        0
    ]


def explicit_missingness_candidates(
    *,
    feature_name: str,
    feature_table: pd.DataFrame,
) -> list[
    tuple[str, np.ndarray]
]:
    """Construct deterministic causal missingness candidates."""

    candidates: list[
        tuple[str, np.ndarray]
    ] = []

    event_clock_match = re.match(
        (
            r"^(tminus_event_"
            r"(w250ms|w1s|w5s|w30s))_"
            r"(.+)$"
        ),
        feature_name,
    )

    if event_clock_match:
        prefix = event_clock_match.group(
            1
        )

        suffix = event_clock_match.group(
            3
        )

        if suffix.endswith(
            "_rate_per_second"
        ):
            add_boolean_false_candidate(
                candidates,
                column_name=(
                    f"{prefix}_full_coverage_flag"
                ),
                feature_table=feature_table,
            )

        if suffix in {
            "buy_event_fraction",
            "sell_event_fraction",
            "signed_event_fraction",
            "activated_mark_fraction",
        }:
            add_numeric_nonpositive_candidate(
                candidates,
                column_name=(
                    f"{prefix}_event_count"
                ),
                feature_table=feature_table,
            )

        if suffix in {
            "simultaneous_batch_fraction",
            "mixed_side_batch_fraction",
            "mean_events_per_batch",
        }:
            add_numeric_nonpositive_candidate(
                candidates,
                column_name=(
                    f"{prefix}_prior_batch_count"
                ),
                feature_table=feature_table,
            )

        if suffix == "activated_vwap":
            add_numeric_nonpositive_candidate(
                candidates,
                column_name=(
                    f"{prefix}_activated_quantity"
                ),
                feature_table=feature_table,
            )

    prior_batch_match = re.match(
        (
            r"^(tminus_prior_batch_"
            r"(b10|b50))_"
            r"(.+)$"
        ),
        feature_name,
    )

    if prior_batch_match:
        prefix = prior_batch_match.group(
            1
        )

        suffix = prior_batch_match.group(
            3
        )

        if suffix in {
            "buy_event_fraction",
            "sell_event_fraction",
            "signed_event_fraction",
        }:
            add_numeric_nonpositive_candidate(
                candidates,
                column_name=(
                    f"{prefix}_event_count"
                ),
                feature_table=feature_table,
            )

        if suffix in {
            "simultaneous_batch_fraction",
            "mixed_side_batch_fraction",
            "mean_events_per_batch",
        }:
            for possible_denominator in (
                f"{prefix}_prior_batch_count",
                f"{prefix}_batch_count",
            ):
                add_numeric_nonpositive_candidate(
                    candidates,
                    column_name=(
                        possible_denominator
                    ),
                    feature_table=feature_table,
                )

    book_clock_match = re.match(
        (
            r"^(tminus_book_flow_"
            r"(w250ms|w1s|w5s|w30s))_"
            r"(.+)$"
        ),
        feature_name,
    )

    if book_clock_match:
        prefix = book_clock_match.group(
            1
        )

        suffix = book_clock_match.group(
            3
        )

        if (
            suffix.endswith(
                "_rate_per_second"
            )
            or suffix
            in {
                "realized_variance",
                "realized_volatility_basis_points",
            }
        ):
            add_boolean_false_candidate(
                candidates,
                column_name=(
                    f"{prefix}_full_coverage_flag"
                ),
                feature_table=feature_table,
            )

        if suffix in {
            "realized_variance",
            "realized_volatility_basis_points",
        }:
            add_numeric_nonpositive_candidate(
                candidates,
                column_name=(
                    f"{prefix}_valid_transition_count"
                ),
                feature_table=feature_table,
            )

        if (
            suffix.endswith(
                "_fraction"
            )
            or suffix.endswith(
                "_per_update"
            )
        ):
            for possible_denominator in (
                f"{prefix}_state_count",
                f"{prefix}_valid_transition_count",
            ):
                add_numeric_nonpositive_candidate(
                    candidates,
                    column_name=(
                        possible_denominator
                    ),
                    feature_table=feature_table,
                )

    explicit_boolean_companions: dict[
        str,
        tuple[str, ...]
    ] = {
        (
            "tminus_book_latest_update_"
        ): (
            "tminus_book_has_valid_latest_transition_flag",
        ),
        (
            "tminus_book_time_since_last_midpoint_change_ms"
        ): (
            "tminus_book_has_prior_midpoint_change_flag",
        ),
        (
            "tminus_book_updates_since_last_midpoint_change"
        ): (
            "tminus_book_has_prior_midpoint_change_flag",
        ),
        (
            "tminus_book_time_since_last_top_of_book_move_ms"
        ): (
            "tminus_book_has_prior_top_of_book_move_flag",
        ),
        (
            "tminus_book_time_since_last_top10_change_ms"
        ): (
            "tminus_book_has_prior_top10_change_flag",
        ),
        (
            "tminus_book_time_since_last_spread_change_ms"
        ): (
            "tminus_book_has_prior_spread_change_flag",
        ),
        (
            "tminus_time_since_last_event_ms"
        ): (
            "tminus_has_prior_event_flag",
            "tminus_prior_event_available_flag",
        ),
        (
            "tminus_time_since_last_buy_event_ms"
        ): (
            "tminus_has_prior_buy_event_flag",
            "tminus_prior_buy_event_available_flag",
        ),
        (
            "tminus_time_since_last_sell_event_ms"
        ): (
            "tminus_has_prior_sell_event_flag",
            "tminus_prior_sell_event_available_flag",
        ),
        (
            "tminus_time_since_previous_batch_ms"
        ): (
            "tminus_has_previous_batch_flag",
            "tminus_previous_batch_available_flag",
        ),
    }

    for feature_prefix, companion_names in (
        explicit_boolean_companions.items()
    ):
        if feature_name.startswith(
            feature_prefix
        ):
            for companion_name in (
                companion_names
            ):
                add_boolean_false_candidate(
                    candidates,
                    column_name=(
                        companion_name
                    ),
                    feature_table=feature_table,
                )

    return candidates


def generic_sibling_candidates(
    *,
    feature_name: str,
    feature_table: pd.DataFrame,
) -> list[
    tuple[str, np.ndarray]
]:
    """Find conservative causal sibling conditions."""

    candidates: list[
        tuple[str, np.ndarray]
    ] = []

    namespace = feature_namespace(
        feature_name
    )

    boolean_tokens = (
        "full_coverage_flag",
        "has_prior",
        "has_valid",
        "available_flag",
        "history_available",
        "transition_available",
    )

    denominator_tokens = (
        "event_count",
        "prior_batch_count",
        "batch_count",
        "valid_transition_count",
        "state_count",
        "activated_quantity",
        "activated_notional",
        "total_quantity",
        "total_depth",
        "denominator",
    )

    for candidate_column in (
        feature_table.columns
    ):
        if candidate_column == feature_name:
            continue

        if not candidate_column.startswith(
            namespace
        ):
            continue

        lowered_name = (
            candidate_column.lower()
        )

        if any(
            token in lowered_name
            for token in boolean_tokens
        ):
            add_boolean_false_candidate(
                candidates,
                column_name=(
                    candidate_column
                ),
                feature_table=feature_table,
            )

        if any(
            token in lowered_name
            for token in denominator_tokens
        ):
            add_numeric_nonpositive_candidate(
                candidates,
                column_name=(
                    candidate_column
                ),
                feature_table=feature_table,
            )

    return candidates


def choose_causal_missingness_explanation(
    *,
    observed_missing_mask: np.ndarray,
    candidates: list[
        tuple[str, np.ndarray]
    ],
    upstream_rule: str,
) -> tuple[
    np.ndarray,
    tuple[str, ...],
    str,
]:
    """Choose a causal allowed-missing mask."""

    require(
        observed_missing_mask.ndim == 1,
        "Observed missingness mask must be one-dimensional.",
    )

    row_count = len(
        observed_missing_mask
    )

    if not observed_missing_mask.any():
        return (
            np.zeros(
                row_count,
                dtype=bool,
            ),
            tuple(),
            "NO_MISSING_VALUES",
        )

    valid_candidates: list[
        tuple[str, np.ndarray]
    ] = []

    seen_candidate_names: set[
        str
    ] = set()

    for candidate_name, candidate_mask in (
        candidates
    ):
        candidate_array = np.asarray(
            candidate_mask,
            dtype=bool,
        )

        if candidate_array.shape != (
            row_count,
        ):
            continue

        if candidate_name in (
            seen_candidate_names
        ):
            continue

        seen_candidate_names.add(
            candidate_name
        )

        if not (
            candidate_array
            & observed_missing_mask
        ).any():
            continue

        valid_candidates.append(
            (
                candidate_name,
                candidate_array,
            )
        )

    exact_candidates = [
        (
            candidate_name,
            candidate_mask,
        )
        for candidate_name, candidate_mask in (
            valid_candidates
        )
        if np.array_equal(
            candidate_mask,
            observed_missing_mask,
        )
    ]

    if exact_candidates:
        selected_name, selected_mask = (
            exact_candidates[
                0
            ]
        )

        return (
            selected_mask.copy(),
            (
                selected_name,
            ),
            "EXACT_CAUSAL_CONDITION",
        )

    allowed_mask = np.zeros(
        row_count,
        dtype=bool,
    )

    selected_conditions: list[
        str
    ] = []

    uncovered_missing = (
        observed_missing_mask.copy()
    )

    remaining_candidates = list(
        valid_candidates
    )

    while uncovered_missing.any():
        ranked_candidates: list[
            tuple[
                int,
                int,
                str,
                np.ndarray,
            ]
        ] = []

        for candidate_name, candidate_mask in (
            remaining_candidates
        ):
            newly_covered = int(
                (
                    candidate_mask
                    & uncovered_missing
                ).sum()
            )

            if newly_covered == 0:
                continue

            extra_allowed = int(
                (
                    candidate_mask
                    & ~observed_missing_mask
                ).sum()
            )

            ranked_candidates.append(
                (
                    extra_allowed,
                    -newly_covered,
                    candidate_name,
                    candidate_mask,
                )
            )

        if not ranked_candidates:
            break

        ranked_candidates.sort(
            key=lambda item: (
                item[
                    0
                ],
                item[
                    1
                ],
                item[
                    2
                ],
            )
        )

        (
            _,
            _,
            selected_name,
            selected_mask,
        ) = ranked_candidates[
            0
        ]

        allowed_mask |= selected_mask

        selected_conditions.append(
            selected_name
        )

        uncovered_missing = (
            observed_missing_mask
            & ~allowed_mask
        )

        remaining_candidates = [
            (
                candidate_name,
                candidate_mask,
            )
            for candidate_name, candidate_mask in (
                remaining_candidates
            )
            if candidate_name
            != selected_name
        ]

    if (
        uncovered_missing.any()
        and normalized_rule_declares_conditional_nan(
            upstream_rule
        )
    ):
        allowed_mask |= (
            observed_missing_mask
        )

        selected_conditions.append(
            "UPSTREAM_DECLARED_CONDITIONAL_NAN_MASK"
        )

        uncovered_missing = (
            observed_missing_mask
            & ~allowed_mask
        )

    if uncovered_missing.any():
        policy_class = (
            "UNEXPLAINED_MISSINGNESS"
        )

    elif selected_conditions:
        policy_class = (
            "UNION_OF_CAUSAL_CONDITIONS"
        )

    else:
        policy_class = (
            "UNEXPLAINED_MISSINGNESS"
        )

    return (
        allowed_mask,
        tuple(
            selected_conditions
        ),
        policy_class,
    )


# ------------------------------------------------------------
# Resolve upstream feature registries
# ------------------------------------------------------------

(
    STATIC_REGISTRY_NAME,
    STATIC_REGISTRY_SOURCE,
) = resolve_existing_dataframe(
    (
        "STATIC_VISIBLE_BOOK_FEATURE_REGISTRY",
        "CAUSAL_STATIC_VISIBLE_BOOK_FEATURE_REGISTRY",
        "VISIBLE_BOOK_FEATURE_REGISTRY",
        "BATCH_STATIC_VISIBLE_BOOK_FEATURE_REGISTRY",
    ),
    description=(
        "static visible-book feature registry"
    ),
)

(
    EVENT_FLOW_REGISTRY_NAME,
    EVENT_FLOW_REGISTRY_SOURCE,
) = resolve_existing_dataframe(
    (
        "CAUSAL_EVENT_FLOW_FEATURE_REGISTRY",
        "EVENT_FLOW_FEATURE_REGISTRY",
        "BATCH_CAUSAL_EVENT_FLOW_FEATURE_REGISTRY",
    ),
    description=(
        "causal event-flow feature registry"
    ),
)

(
    BOOK_FLOW_REGISTRY_NAME,
    BOOK_FLOW_REGISTRY_SOURCE,
) = resolve_existing_dataframe(
    (
        "CAUSAL_BOOK_FLOW_FEATURE_REGISTRY",
        "BOOK_FLOW_FEATURE_REGISTRY",
        "BATCH_CAUSAL_BOOK_FLOW_FEATURE_REGISTRY",
    ),
    description=(
        "causal book-flow feature registry"
    ),
)


STATIC_MARKET_STATE_FEATURE_REGISTRY = (
    normalize_feature_registry(
        registry=(
            STATIC_REGISTRY_SOURCE
        ),
        registry_name=(
            STATIC_REGISTRY_NAME
        ),
        feature_block=(
            BATCH_STATIC_VISIBLE_BOOK_FEATURES
        ),
        feature_family=(
            "STATIC_VISIBLE_BOOK_STATE"
        ),
        source_block_name=(
            "BATCH_STATIC_VISIBLE_BOOK_FEATURES"
        ),
    )
)

EVENT_FLOW_MARKET_STATE_FEATURE_REGISTRY = (
    normalize_feature_registry(
        registry=(
            EVENT_FLOW_REGISTRY_SOURCE
        ),
        registry_name=(
            EVENT_FLOW_REGISTRY_NAME
        ),
        feature_block=(
            BATCH_CAUSAL_EVENT_FLOW_FEATURES
        ),
        feature_family=(
            "CAUSAL_EVENT_FLOW_HISTORY"
        ),
        source_block_name=(
            "BATCH_CAUSAL_EVENT_FLOW_FEATURES"
        ),
    )
)

BOOK_FLOW_MARKET_STATE_FEATURE_REGISTRY = (
    normalize_feature_registry(
        registry=(
            BOOK_FLOW_REGISTRY_SOURCE
        ),
        registry_name=(
            BOOK_FLOW_REGISTRY_NAME
        ),
        feature_block=(
            BATCH_CAUSAL_BOOK_FLOW_FEATURES
        ),
        feature_family=(
            "CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY"
        ),
        source_block_name=(
            "BATCH_CAUSAL_BOOK_FLOW_FEATURES"
        ),
    )
)


# ------------------------------------------------------------
# Canonical identity validation
# ------------------------------------------------------------

CANONICAL_MARKET_STATE_IDENTITY = (
    normalize_identity_frame(
        PRIMARY_SCORING_BATCHES,
        frame_name=(
            "PRIMARY_SCORING_BATCHES"
        ),
    )
)

STATIC_MARKET_STATE_IDENTITY = (
    normalize_identity_frame(
        BATCH_STATIC_VISIBLE_BOOK_FEATURES,
        frame_name=(
            "BATCH_STATIC_VISIBLE_BOOK_FEATURES"
        ),
    )
)

EVENT_FLOW_MARKET_STATE_IDENTITY = (
    normalize_identity_frame(
        BATCH_CAUSAL_EVENT_FLOW_FEATURES,
        frame_name=(
            "BATCH_CAUSAL_EVENT_FLOW_FEATURES"
        ),
    )
)

BOOK_FLOW_MARKET_STATE_IDENTITY = (
    normalize_identity_frame(
        BATCH_CAUSAL_BOOK_FLOW_FEATURES,
        frame_name=(
            "BATCH_CAUSAL_BOOK_FLOW_FEATURES"
        ),
    )
)

compare_identity_frames(
    CANONICAL_MARKET_STATE_IDENTITY,
    STATIC_MARKET_STATE_IDENTITY,
    right_name=(
        "BATCH_STATIC_VISIBLE_BOOK_FEATURES"
    ),
)

compare_identity_frames(
    CANONICAL_MARKET_STATE_IDENTITY,
    EVENT_FLOW_MARKET_STATE_IDENTITY,
    right_name=(
        "BATCH_CAUSAL_EVENT_FLOW_FEATURES"
    ),
)

compare_identity_frames(
    CANONICAL_MARKET_STATE_IDENTITY,
    BOOK_FLOW_MARKET_STATE_IDENTITY,
    right_name=(
        "BATCH_CAUSAL_BOOK_FLOW_FEATURES"
    ),
)


# ------------------------------------------------------------
# Freeze feature columns and prevent overlap
# ------------------------------------------------------------

STATIC_MARKET_STATE_FEATURE_COLUMNS = (
    STATIC_MARKET_STATE_FEATURE_REGISTRY[
        "feature_name"
    ].tolist()
)

EVENT_FLOW_MARKET_STATE_FEATURE_COLUMNS = (
    EVENT_FLOW_MARKET_STATE_FEATURE_REGISTRY[
        "feature_name"
    ].tolist()
)

BOOK_FLOW_MARKET_STATE_FEATURE_COLUMNS = (
    BOOK_FLOW_MARKET_STATE_FEATURE_REGISTRY[
        "feature_name"
    ].tolist()
)

for feature_block, feature_columns, block_name in (
    (
        BATCH_STATIC_VISIBLE_BOOK_FEATURES,
        STATIC_MARKET_STATE_FEATURE_COLUMNS,
        "BATCH_STATIC_VISIBLE_BOOK_FEATURES",
    ),
    (
        BATCH_CAUSAL_EVENT_FLOW_FEATURES,
        EVENT_FLOW_MARKET_STATE_FEATURE_COLUMNS,
        "BATCH_CAUSAL_EVENT_FLOW_FEATURES",
    ),
    (
        BATCH_CAUSAL_BOOK_FLOW_FEATURES,
        BOOK_FLOW_MARKET_STATE_FEATURE_COLUMNS,
        "BATCH_CAUSAL_BOOK_FLOW_FEATURES",
    ),
):
    require_columns(
        feature_block,
        feature_columns,
        block_name,
    )


ALL_MARKET_STATE_FEATURE_COLUMNS = (
    STATIC_MARKET_STATE_FEATURE_COLUMNS
    + EVENT_FLOW_MARKET_STATE_FEATURE_COLUMNS
    + BOOK_FLOW_MARKET_STATE_FEATURE_COLUMNS
)

duplicate_market_state_features = (
    pd.Series(
        ALL_MARKET_STATE_FEATURE_COLUMNS,
        dtype="string",
    )
    .value_counts()
)

duplicate_market_state_features = (
    duplicate_market_state_features.loc[
        duplicate_market_state_features.gt(
            1
        )
    ]
)

require(
    duplicate_market_state_features.empty,
    (
        "Feature names overlap across upstream blocks: "
        f"{duplicate_market_state_features.to_dict()}"
    ),
)


# ------------------------------------------------------------
# Construct authoritative market-state feature table
# ------------------------------------------------------------

STATIC_FEATURE_BLOCK_SORTED = (
    BATCH_STATIC_VISIBLE_BOOK_FEATURES
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)[
        STATIC_MARKET_STATE_FEATURE_COLUMNS
    ]
    .copy()
)

EVENT_FLOW_FEATURE_BLOCK_SORTED = (
    BATCH_CAUSAL_EVENT_FLOW_FEATURES
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)[
        EVENT_FLOW_MARKET_STATE_FEATURE_COLUMNS
    ]
    .copy()
)

BOOK_FLOW_FEATURE_BLOCK_SORTED = (
    BATCH_CAUSAL_BOOK_FLOW_FEATURES
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)[
        BOOK_FLOW_MARKET_STATE_FEATURE_COLUMNS
    ]
    .copy()
)

PRIMARY_BATCH_MARKET_STATE_FEATURES = (
    pd.concat(
        [
            CANONICAL_MARKET_STATE_IDENTITY,
            STATIC_FEATURE_BLOCK_SORTED,
            EVENT_FLOW_FEATURE_BLOCK_SORTED,
            BOOK_FLOW_FEATURE_BLOCK_SORTED,
        ],
        axis=1,
    )
    .copy(
        deep=True
    )
)

require_unique_columns(
    PRIMARY_BATCH_MARKET_STATE_FEATURES,
    "PRIMARY_BATCH_MARKET_STATE_FEATURES",
)

require(
    len(
        PRIMARY_BATCH_MARKET_STATE_FEATURES
    )
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Final market-state feature table does not contain "
        "one row per scoring batch."
    ),
)

require(
    PRIMARY_BATCH_MARKET_STATE_FEATURES[
        "primary_event_batch_id"
    ].is_unique,
    (
        "Final market-state feature table contains duplicate "
        "batch IDs."
    ),
)

require(
    PRIMARY_BATCH_MARKET_STATE_FEATURES[
        "primary_event_batch_number"
    ].is_unique,
    (
        "Final market-state feature table contains duplicate "
        "batch numbers."
    ),
)

require(
    PRIMARY_BATCH_MARKET_STATE_FEATURES[
        "primary_event_batch_number"
    ].is_monotonic_increasing,
    (
        "Final market-state feature table is not ordered by "
        "batch number."
    ),
)

observed_final_feature_columns = [
    column_name
    for column_name in (
        PRIMARY_BATCH_MARKET_STATE_FEATURES.columns
    )
    if column_name
    not in FINAL_MARKET_STATE_IDENTITY_COLUMNS
]

require(
    observed_final_feature_columns
    == ALL_MARKET_STATE_FEATURE_COLUMNS,
    (
        "Final market-state feature order does not match the "
        "frozen upstream registry order."
    ),
)


# ------------------------------------------------------------
# Combined feature registry
# ------------------------------------------------------------

MARKET_STATE_FEATURE_REGISTRY = pd.concat(
    [
        STATIC_MARKET_STATE_FEATURE_REGISTRY,
        EVENT_FLOW_MARKET_STATE_FEATURE_REGISTRY,
        BOOK_FLOW_MARKET_STATE_FEATURE_REGISTRY,
    ],
    axis=0,
    ignore_index=True,
    sort=False,
)

MARKET_STATE_FEATURE_REGISTRY[
    "feature_order"
] = np.arange(
    1,
    len(
        MARKET_STATE_FEATURE_REGISTRY
    )
    + 1,
    dtype="int64",
)

require(
    MARKET_STATE_FEATURE_REGISTRY[
        "feature_name"
    ].is_unique,
    (
        "Combined market-state registry contains duplicate "
        "feature names."
    ),
)

require(
    MARKET_STATE_FEATURE_REGISTRY[
        "timing_class"
    ]
    .eq(
        FINAL_MARKET_STATE_TIMING_CLASS
    )
    .all(),
    (
        "Combined market-state registry contains a non-"
        "T-minus feature."
    ),
)

require(
    MARKET_STATE_FEATURE_REGISTRY[
        "authorized_in_feature_table"
    ].all(),
    (
        "Combined market-state registry contains an "
        "unauthorized feature."
    ),
)

require(
    not MARKET_STATE_FEATURE_REGISTRY[
        "current_batch_information_allowed"
    ].any(),
    (
        "Combined market-state registry permits current-"
        "batch information."
    ),
)

require(
    not MARKET_STATE_FEATURE_REGISTRY[
        "future_information_allowed"
    ].any(),
    (
        "Combined market-state registry permits future "
        "information."
    ),
)

require(
    MARKET_STATE_FEATURE_REGISTRY[
        "feature_name"
    ].tolist()
    == ALL_MARKET_STATE_FEATURE_COLUMNS,
    (
        "Combined market-state registry order does not match "
        "the final feature-table order."
    ),
)


# ------------------------------------------------------------
# Causal missingness policy
#
# No value is imputed here.
#
# A missing value is accepted only when at least one of the
# following is true:
#
# 1. an exact causal availability or denominator condition
#    explains it;
# 2. it belongs to a contiguous initial history-censoring
#    prefix;
# 3. the upstream verified feature registry explicitly
#    declares conditional NaN behavior.
# ------------------------------------------------------------

registry_rule_lookup = (
    MARKET_STATE_FEATURE_REGISTRY
    .set_index(
        "feature_name"
    )[
        "missingness_rule"
    ]
    .to_dict()
)

registry_family_lookup = (
    MARKET_STATE_FEATURE_REGISTRY
    .set_index(
        "feature_name"
    )[
        "feature_family"
    ]
    .to_dict()
)

missingness_policy_rows: list[
    dict[str, Any]
] = []

feature_allowed_missing_masks: dict[
    str,
    np.ndarray,
] = {}

feature_observed_missing_masks: dict[
    str,
    np.ndarray,
] = {}

feature_infinite_masks: dict[
    str,
    np.ndarray,
] = {}


for feature_name in (
    ALL_MARKET_STATE_FEATURE_COLUMNS
):
    feature_series = (
        PRIMARY_BATCH_MARKET_STATE_FEATURES[
            feature_name
        ]
    )

    observed_missing_mask = (
        feature_series.isna().to_numpy(
            dtype=bool
        )
    )

    upstream_rule = str(
        registry_rule_lookup.get(
            feature_name,
            "",
        )
    )

    candidates = (
        explicit_missingness_candidates(
            feature_name=(
                feature_name
            ),
            feature_table=(
                PRIMARY_BATCH_MARKET_STATE_FEATURES
            ),
        )
    )

    candidates.extend(
        generic_sibling_candidates(
            feature_name=(
                feature_name
            ),
            feature_table=(
                PRIMARY_BATCH_MARKET_STATE_FEATURES
            ),
        )
    )

    is_initial_prefix, prefix_mask = (
        initial_true_prefix_mask(
            observed_missing_mask
        )
    )

    if (
        observed_missing_mask.any()
        and is_initial_prefix
    ):
        candidates.append(
            (
                "INITIAL_CONTIGUOUS_HISTORY_LEFT_CENSORING",
                prefix_mask,
            )
        )

    (
        allowed_missing_mask,
        selected_conditions,
        policy_class,
    ) = choose_causal_missingness_explanation(
        observed_missing_mask=(
            observed_missing_mask
        ),
        candidates=candidates,
        upstream_rule=(
            upstream_rule
        ),
    )

    unexpected_missing_mask = (
        observed_missing_mask
        & ~allowed_missing_mask
    )

    feature_allowed_missing_masks[
        feature_name
    ] = allowed_missing_mask

    feature_observed_missing_masks[
        feature_name
    ] = observed_missing_mask

    if (
        pd.api.types.is_numeric_dtype(
            feature_series
        )
        or pd.api.types.is_bool_dtype(
            feature_series
        )
    ):
        numeric_values = pd.to_numeric(
            feature_series,
            errors="coerce",
        ).to_numpy(
            dtype="float64",
            na_value=np.nan,
        )

        infinite_mask = np.isinf(
            numeric_values
        )

    else:
        infinite_mask = np.zeros(
            len(
                feature_series
            ),
            dtype=bool,
        )

    feature_infinite_masks[
        feature_name
    ] = infinite_mask

    missingness_policy_rows.append(
        {
            "feature_name": feature_name,
            "feature_family": (
                registry_family_lookup[
                    feature_name
                ]
            ),
            "observed_missing_count": int(
                observed_missing_mask.sum()
            ),
            "allowed_missing_count": int(
                allowed_missing_mask.sum()
            ),
            "unexpected_missing_count": int(
                unexpected_missing_mask.sum()
            ),
            "infinite_count": int(
                infinite_mask.sum()
            ),
            "missingness_policy_class": (
                policy_class
            ),
            "selected_causal_conditions": (
                " | ".join(
                    selected_conditions
                )
                if selected_conditions
                else ""
            ),
            "upstream_missingness_rule": (
                upstream_rule
            ),
            "upstream_declares_conditional_nan": (
                normalized_rule_declares_conditional_nan(
                    upstream_rule
                )
            ),
            "initial_prefix_missingness_flag": (
                bool(
                    observed_missing_mask.any()
                    and is_initial_prefix
                )
            ),
            "status": (
                "PASS"
                if (
                    unexpected_missing_mask.sum()
                    == 0
                    and infinite_mask.sum()
                    == 0
                )
                else "FAIL"
            ),
        }
    )


MARKET_STATE_FEATURE_MISSINGNESS_POLICY = (
    pd.DataFrame.from_records(
        missingness_policy_rows
    )
)

require(
    len(
        MARKET_STATE_FEATURE_MISSINGNESS_POLICY
    )
    == len(
        ALL_MARKET_STATE_FEATURE_COLUMNS
    ),
    (
        "Missingness policy does not contain one row per "
        "market-state feature."
    ),
)

require(
    MARKET_STATE_FEATURE_MISSINGNESS_POLICY[
        "feature_name"
    ].is_unique,
    (
        "Missingness policy contains duplicate feature "
        "names."
    ),
)

feature_missingness_policy_violation_count = int(
    MARKET_STATE_FEATURE_MISSINGNESS_POLICY[
        "unexpected_missing_count"
    ].sum()
)

feature_infinite_value_count = int(
    MARKET_STATE_FEATURE_MISSINGNESS_POLICY[
        "infinite_count"
    ].sum()
)

require(
    feature_missingness_policy_violation_count
    == 0,
    (
        "At least one feature contains missing values that "
        "cannot be explained by a causal availability rule, "
        "an initial history-censoring prefix, or an upstream "
        "declared conditional-NaN contract."
    ),
)

require(
    feature_infinite_value_count
    == 0,
    (
        "At least one market-state feature contains an "
        "infinite value."
    ),
)


# ------------------------------------------------------------
# Merge missingness policy into final registry
# ------------------------------------------------------------

MARKET_STATE_FEATURE_REGISTRY = (
    MARKET_STATE_FEATURE_REGISTRY
    .merge(
        MARKET_STATE_FEATURE_MISSINGNESS_POLICY[
            [
                "feature_name",
                "observed_missing_count",
                "allowed_missing_count",
                "unexpected_missing_count",
                "infinite_count",
                "missingness_policy_class",
                "selected_causal_conditions",
                "upstream_declares_conditional_nan",
                "initial_prefix_missingness_flag",
            ]
        ],
        how="left",
        on="feature_name",
        validate="one_to_one",
    )
    .sort_values(
        "feature_order",
        kind="stable",
    )
    .reset_index(drop=True)
)

MARKET_STATE_FEATURE_REGISTRY[
    "nullable_flag"
] = (
    MARKET_STATE_FEATURE_REGISTRY[
        "observed_missing_count"
    ].gt(0)
)

MARKET_STATE_FEATURE_REGISTRY[
    "imputation_applied"
] = False

MARKET_STATE_FEATURE_REGISTRY[
    "future_label_attached"
] = False

MARKET_STATE_FEATURE_REGISTRY[
    "post_batch_context_attached"
] = False


# ------------------------------------------------------------
# Feature availability table
# ------------------------------------------------------------

FEATURE_AVAILABILITY_BLOCK = (
    PRIMARY_BATCH_MARKET_STATE_FEATURES[
        ALL_MARKET_STATE_FEATURE_COLUMNS
    ]
    .notna()
    .copy()
)

FEATURE_AVAILABILITY_BLOCK.columns = [
    f"available__{column_name}"
    for column_name in (
        FEATURE_AVAILABILITY_BLOCK.columns
    )
]

PRIMARY_BATCH_MARKET_STATE_FEATURE_AVAILABILITY = (
    pd.concat(
        [
            CANONICAL_MARKET_STATE_IDENTITY,
            FEATURE_AVAILABILITY_BLOCK,
        ],
        axis=1,
    )
    .copy(
        deep=True
    )
)

require_unique_columns(
    PRIMARY_BATCH_MARKET_STATE_FEATURE_AVAILABILITY,
    (
        "PRIMARY_BATCH_MARKET_STATE_FEATURE_"
        "AVAILABILITY"
    ),
)

require(
    len(
        PRIMARY_BATCH_MARKET_STATE_FEATURE_AVAILABILITY
    )
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Feature-availability table does not contain one row "
        "per scoring batch."
    ),
)


# ------------------------------------------------------------
# Row-level feature quality
# ------------------------------------------------------------

feature_family_columns: dict[
    str,
    list[str],
] = (
    MARKET_STATE_FEATURE_REGISTRY.groupby(
        "feature_family",
        sort=False,
        observed=True,
    )[
        "feature_name"
    ]
    .apply(
        list
    )
    .to_dict()
)

row_quality_payload: dict[
    str,
    Any,
] = {
    column_name: (
        CANONICAL_MARKET_STATE_IDENTITY[
            column_name
        ].copy()
    )
    for column_name in (
        FINAL_MARKET_STATE_IDENTITY_COLUMNS
    )
}

all_feature_missing_count = (
    PRIMARY_BATCH_MARKET_STATE_FEATURES[
        ALL_MARKET_STATE_FEATURE_COLUMNS
    ]
    .isna()
    .sum(
        axis=1
    )
    .astype("int64")
)

row_quality_payload[
    "available_feature_count"
] = (
    len(
        ALL_MARKET_STATE_FEATURE_COLUMNS
    )
    - all_feature_missing_count
)

row_quality_payload[
    "missing_feature_count"
] = (
    all_feature_missing_count
)

row_quality_payload[
    "complete_feature_row_flag"
] = (
    all_feature_missing_count.eq(
        0
    )
)

for (
    feature_family,
    family_feature_columns,
) in feature_family_columns.items():
    family_slug = (
        feature_family.lower()
    )

    family_missing_count = (
        PRIMARY_BATCH_MARKET_STATE_FEATURES[
            family_feature_columns
        ]
        .isna()
        .sum(
            axis=1
        )
        .astype("int64")
    )

    row_quality_payload[
        f"{family_slug}_missing_feature_count"
    ] = family_missing_count

    row_quality_payload[
        f"{family_slug}_complete_flag"
    ] = family_missing_count.eq(
        0
    )


PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY = (
    pd.DataFrame(
        row_quality_payload
    )
)

require_unique_columns(
    PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY,
    (
        "PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY"
    ),
)

require(
    len(
        PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY
    )
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Market-state row-quality table does not contain one "
        "row per scoring batch."
    ),
)


# ------------------------------------------------------------
# Leakage-facing column audit
# ------------------------------------------------------------

final_feature_name_set = set(
    ALL_MARKET_STATE_FEATURE_COLUMNS
)

tplus_feature_columns = sorted(
    feature_name
    for feature_name in (
        final_feature_name_set
    )
    if feature_name.startswith(
        "tplus_"
    )
)

future_feature_columns = sorted(
    feature_name
    for feature_name in (
        final_feature_name_set
    )
    if (
        feature_name.startswith(
            "future_"
        )
        or feature_name.startswith(
            "label_"
        )
        or feature_name.startswith(
            "target_"
        )
        or "_future_" in feature_name
        or "_label_" in feature_name
        or "_target_" in feature_name
    )
)

current_batch_raw_feature_columns = sorted(
    feature_name
    for feature_name in (
        final_feature_name_set
    )
    if (
        "current_batch" in feature_name
        or feature_name
        in {
            "batch_event_count",
            "batch_buy_event_count",
            "batch_sell_event_count",
            "batch_print_count",
            "batch_quantity",
            "batch_notional",
            "batch_vwap",
            "aggregate_mark_available_time_ns",
        }
    )
)

require(
    not tplus_feature_columns,
    (
        "Final market-state feature table contains T-plus "
        f"features: {tplus_feature_columns}"
    ),
)

require(
    not future_feature_columns,
    (
        "Final market-state feature table contains future "
        f"labels or targets: {future_feature_columns}"
    ),
)

require(
    not current_batch_raw_feature_columns,
    (
        "Final market-state feature table contains current-"
        "batch fields: "
        f"{current_batch_raw_feature_columns}"
    ),
)


# ------------------------------------------------------------
# Same-batch feature invariance by deterministic row hash
# ------------------------------------------------------------

MARKET_STATE_FEATURE_ROW_HASH = (
    pd.util.hash_pandas_object(
        PRIMARY_BATCH_MARKET_STATE_FEATURES[
            ALL_MARKET_STATE_FEATURE_COLUMNS
        ],
        index=False,
        categorize=True,
    )
    .astype("uint64")
)

MARKET_STATE_FEATURE_HASH_TABLE = (
    PRIMARY_BATCH_MARKET_STATE_FEATURES[
        [
            "primary_event_batch_id",
        ]
    ]
    .copy()
)

MARKET_STATE_FEATURE_HASH_TABLE[
    "market_state_feature_row_hash_uint64"
] = (
    MARKET_STATE_FEATURE_ROW_HASH.to_numpy(
        dtype="uint64"
    )
)

MARKET_STATE_EVENT_PROJECTION_AUDIT = (
    PRIMARY_EVENT_TO_BATCH_MEMBERSHIP[
        [
            "primary_event_id",
            "primary_event_batch_id",
        ]
    ]
    .merge(
        MARKET_STATE_FEATURE_HASH_TABLE,
        how="left",
        on="primary_event_batch_id",
        validate="many_to_one",
    )
)

require(
    len(
        MARKET_STATE_EVENT_PROJECTION_AUDIT
    )
    == EXPECTED_PRIMARY_EVENT_ROWS,
    (
        "Final market-state event projection changed the "
        "primary event population."
    ),
)

require(
    MARKET_STATE_EVENT_PROJECTION_AUDIT[
        "market_state_feature_row_hash_uint64"
    ].notna().all(),
    (
        "At least one primary event could not resolve its "
        "market-state feature row."
    ),
)

MARKET_STATE_SAME_BATCH_HASH_COUNTS = (
    MARKET_STATE_EVENT_PROJECTION_AUDIT.groupby(
        "primary_event_batch_id",
        observed=True,
        sort=False,
        dropna=False,
    )[
        "market_state_feature_row_hash_uint64"
    ]
    .nunique(
        dropna=False
    )
)

market_state_same_batch_invariance_failure_count = int(
    MARKET_STATE_SAME_BATCH_HASH_COUNTS.gt(
        1
    ).sum()
)

require(
    market_state_same_batch_invariance_failure_count
    == 0,
    (
        "At least one exact-time event batch resolves to more "
        "than one market-state feature row."
    ),
)


# ------------------------------------------------------------
# Partition-level feature completeness audit
# ------------------------------------------------------------

MARKET_STATE_PARTITION_COMPLETENESS_AUDIT = (
    PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY.groupby(
        [
            "event_partition_order",
            "event_partition",
        ],
        observed=True,
        sort=True,
        dropna=False,
    )
    .agg(
        batch_count=(
            "primary_event_batch_id",
            "size",
        ),
        complete_feature_row_count=(
            "complete_feature_row_flag",
            "sum",
        ),
        minimum_available_feature_count=(
            "available_feature_count",
            "min",
        ),
        median_available_feature_count=(
            "available_feature_count",
            "median",
        ),
        maximum_available_feature_count=(
            "available_feature_count",
            "max",
        ),
        maximum_missing_feature_count=(
            "missing_feature_count",
            "max",
        ),
    )
    .reset_index()
)

MARKET_STATE_PARTITION_COMPLETENESS_AUDIT[
    "complete_feature_row_fraction"
] = (
    MARKET_STATE_PARTITION_COMPLETENESS_AUDIT[
        "complete_feature_row_count"
    ]
    / MARKET_STATE_PARTITION_COMPLETENESS_AUDIT[
        "batch_count"
    ]
)

MARKET_STATE_PARTITION_COMPLETENESS_AUDIT[
    "status"
] = np.where(
    MARKET_STATE_PARTITION_COMPLETENESS_AUDIT[
        "minimum_available_feature_count"
    ].gt(
        0
    ),
    "PASS",
    "FAIL",
)

require(
    MARKET_STATE_PARTITION_COMPLETENESS_AUDIT[
        "status"
    ].eq(
        "PASS"
    ).all(),
    (
        "At least one partition contains a scoring batch "
        "with no available market-state features."
    ),
)


# ------------------------------------------------------------
# Feature-family summary
# ------------------------------------------------------------

MARKET_STATE_FEATURE_FAMILY_SUMMARY = (
    MARKET_STATE_FEATURE_REGISTRY.groupby(
        [
            "feature_family",
            "source_block",
            "source_registry",
        ],
        observed=True,
        sort=False,
        dropna=False,
    )
    .agg(
        feature_count=(
            "feature_name",
            "size",
        ),
        nullable_feature_count=(
            "nullable_flag",
            "sum",
        ),
        observed_missing_value_count=(
            "observed_missing_count",
            "sum",
        ),
        unexpected_missing_value_count=(
            "unexpected_missing_count",
            "sum",
        ),
        infinite_value_count=(
            "infinite_count",
            "sum",
        ),
    )
    .reset_index()
)

MARKET_STATE_FEATURE_FAMILY_SUMMARY[
    "status"
] = np.where(
    (
        MARKET_STATE_FEATURE_FAMILY_SUMMARY[
            "unexpected_missing_value_count"
        ].eq(
            0
        )
        & MARKET_STATE_FEATURE_FAMILY_SUMMARY[
            "infinite_value_count"
        ].eq(
            0
        )
    ),
    "PASS",
    "FAIL",
)


# ------------------------------------------------------------
# Final assembly gates
# ------------------------------------------------------------

declared_nullable_feature_count = int(
    MARKET_STATE_FEATURE_REGISTRY[
        "nullable_flag"
    ].sum()
)

observed_missing_value_count = int(
    MARKET_STATE_FEATURE_REGISTRY[
        "observed_missing_count"
    ].sum()
)

complete_market_state_row_count = int(
    PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY[
        "complete_feature_row_flag"
    ].sum()
)

incomplete_market_state_row_count = int(
    (
        ~PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY[
            "complete_feature_row_flag"
        ]
    ).sum()
)

minimum_available_feature_count = int(
    PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY[
        "available_feature_count"
    ].min()
)

maximum_missing_feature_count = int(
    PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY[
        "missing_feature_count"
    ].max()
)


MARKET_STATE_FEATURE_GATES = pd.DataFrame(
    [
        {
            "gate": (
                "upstream_feature_blocks_verified"
            ),
            "severity": "BLOCKING",
            "passed": (
                STATIC_VISIBLE_BOOK_FEATURES_VERIFIED
                and CAUSAL_EVENT_FLOW_FEATURES_VERIFIED
                and CAUSAL_BOOK_FLOW_FEATURES_VERIFIED
            ),
            "evidence": (
                "static=True; event_flow=True; "
                "book_flow=True"
            ),
        },
        {
            "gate": (
                "canonical_batch_identity_reconciles"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                f"batches="
                f"{EXPECTED_PRIMARY_BATCH_ROWS}"
            ),
        },
        {
            "gate": (
                "feature_names_unique_across_blocks"
            ),
            "severity": "BLOCKING",
            "passed": (
                duplicate_market_state_features.empty
            ),
            "evidence": (
                f"duplicates="
                f"{len(duplicate_market_state_features)}"
            ),
        },
        {
            "gate": (
                "final_feature_rows_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    PRIMARY_BATCH_MARKET_STATE_FEATURES
                )
                == EXPECTED_PRIMARY_BATCH_ROWS
            ),
            "evidence": (
                f"rows="
                f"{len(PRIMARY_BATCH_MARKET_STATE_FEATURES)}"
            ),
        },
        {
            "gate": (
                "registry_feature_set_matches_table"
            ),
            "severity": "BLOCKING",
            "passed": (
                MARKET_STATE_FEATURE_REGISTRY[
                    "feature_name"
                ].tolist()
                == ALL_MARKET_STATE_FEATURE_COLUMNS
            ),
            "evidence": (
                f"features="
                f"{len(ALL_MARKET_STATE_FEATURE_COLUMNS)}"
            ),
        },
        {
            "gate": (
                "all_features_are_tminus"
            ),
            "severity": "BLOCKING",
            "passed": (
                MARKET_STATE_FEATURE_REGISTRY[
                    "timing_class"
                ]
                .eq(
                    FINAL_MARKET_STATE_TIMING_CLASS
                )
                .all()
            ),
            "evidence": (
                f"timing_class="
                f"{FINAL_MARKET_STATE_TIMING_CLASS}"
            ),
        },
        {
            "gate": (
                "missingness_policy_verified"
            ),
            "severity": "BLOCKING",
            "passed": (
                feature_missingness_policy_violation_count
                == 0
            ),
            "evidence": (
                f"unexpected_missing_values="
                f"{feature_missingness_policy_violation_count}"
            ),
        },
        {
            "gate": (
                "no_infinite_feature_values"
            ),
            "severity": "BLOCKING",
            "passed": (
                feature_infinite_value_count
                == 0
            ),
            "evidence": (
                f"infinite_values="
                f"{feature_infinite_value_count}"
            ),
        },
        {
            "gate": (
                "feature_availability_rows_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    PRIMARY_BATCH_MARKET_STATE_FEATURE_AVAILABILITY
                )
                == EXPECTED_PRIMARY_BATCH_ROWS
            ),
            "evidence": (
                f"rows="
                f"{len(PRIMARY_BATCH_MARKET_STATE_FEATURE_AVAILABILITY)}"
            ),
        },
        {
            "gate": (
                "same_batch_feature_invariance"
            ),
            "severity": "BLOCKING",
            "passed": (
                market_state_same_batch_invariance_failure_count
                == 0
            ),
            "evidence": (
                f"failed_batches="
                f"{market_state_same_batch_invariance_failure_count}"
            ),
        },
        {
            "gate": (
                "no_tplus_feature_columns"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    tplus_feature_columns
                )
                == 0
            ),
            "evidence": (
                f"tplus_columns="
                f"{len(tplus_feature_columns)}"
            ),
        },
        {
            "gate": (
                "no_future_label_columns"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    future_feature_columns
                )
                == 0
            ),
            "evidence": (
                f"future_like_columns="
                f"{len(future_feature_columns)}"
            ),
        },
        {
            "gate": (
                "no_current_batch_raw_columns"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    current_batch_raw_feature_columns
                )
                == 0
            ),
            "evidence": (
                f"current_batch_columns="
                f"{len(current_batch_raw_feature_columns)}"
            ),
        },
        {
            "gate": (
                "every_batch_has_available_features"
            ),
            "severity": "BLOCKING",
            "passed": (
                minimum_available_feature_count
                > 0
            ),
            "evidence": (
                f"minimum_available_features="
                f"{minimum_available_feature_count}"
            ),
        },
        {
            "gate": (
                "conditional_feature_missingness_present"
            ),
            "severity": "WARNING",
            "passed": (
                declared_nullable_feature_count
                == 0
            ),
            "evidence": (
                f"nullable_features="
                f"{declared_nullable_feature_count}; "
                f"missing_values="
                f"{observed_missing_value_count}"
            ),
        },
        {
            "gate": (
                "incomplete_feature_rows_present"
            ),
            "severity": "WARNING",
            "passed": (
                incomplete_market_state_row_count
                == 0
            ),
            "evidence": (
                f"complete_rows="
                f"{complete_market_state_row_count}; "
                f"incomplete_rows="
                f"{incomplete_market_state_row_count}; "
                f"maximum_missing_features="
                f"{maximum_missing_feature_count}"
            ),
        },
        {
            "gate": (
                "no_feature_imputation_applied"
            ),
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                "causally explained NaN values are preserved "
                "and accompanied by availability masks"
            ),
        },
    ]
)

MARKET_STATE_FEATURE_GATES[
    "status"
] = np.select(
    [
        MARKET_STATE_FEATURE_GATES[
            "passed"
        ],
        MARKET_STATE_FEATURE_GATES[
            "severity"
        ].eq(
            "BLOCKING"
        ),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

market_state_blocking_failures = (
    MARKET_STATE_FEATURE_GATES.loc[
        MARKET_STATE_FEATURE_GATES[
            "severity"
        ].eq(
            "BLOCKING"
        )
        & ~MARKET_STATE_FEATURE_GATES[
            "passed"
        ]
    ]
)

require(
    market_state_blocking_failures.empty,
    (
        "Final market-state feature assembly contains "
        "blocking failures."
    ),
)


# ------------------------------------------------------------
# Frozen downstream aliases
# ------------------------------------------------------------

BATCH_MARKET_STATE_FEATURES = (
    PRIMARY_BATCH_MARKET_STATE_FEATURES
)

BATCH_TMINUS_MARKET_STATE_FEATURES = (
    PRIMARY_BATCH_MARKET_STATE_FEATURES
)

BATCH_MARKET_STATE_FEATURE_AVAILABILITY = (
    PRIMARY_BATCH_MARKET_STATE_FEATURE_AVAILABILITY
)

BATCH_MARKET_STATE_ROW_QUALITY = (
    PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY
)

MARKET_STATE_FEATURES_ASSEMBLED: Final[
    bool
] = True

MARKET_STATE_FEATURES_VERIFIED: Final[
    bool
] = True

MARKET_STATE_FEATURE_ROW_COUNT: Final[
    int
] = int(
    len(
        PRIMARY_BATCH_MARKET_STATE_FEATURES
    )
)

MARKET_STATE_FEATURE_COUNT: Final[
    int
] = int(
        len(
            ALL_MARKET_STATE_FEATURE_COLUMNS
        )
)

MARKET_STATE_FEATURE_FAMILY_COUNT: Final[
    int
] = int(
        MARKET_STATE_FEATURE_REGISTRY[
            "feature_family"
        ].nunique()
    )


# ------------------------------------------------------------
# Compact displays
# ------------------------------------------------------------

display(
    MARKET_STATE_FEATURE_FAMILY_SUMMARY
)

display(
    MARKET_STATE_PARTITION_COMPLETENESS_AUDIT
)

display(
    MARKET_STATE_FEATURE_MISSINGNESS_POLICY.loc[
        MARKET_STATE_FEATURE_MISSINGNESS_POLICY[
            "observed_missing_count"
        ].gt(
            0
        ),
        [
            "feature_name",
            "feature_family",
            "observed_missing_count",
            "allowed_missing_count",
            "unexpected_missing_count",
            "missingness_policy_class",
            "selected_causal_conditions",
            "status",
        ],
    ]
)

display(
    PRIMARY_BATCH_MARKET_STATE_ROW_QUALITY[
        [
            *FINAL_MARKET_STATE_IDENTITY_COLUMNS,
            "available_feature_count",
            "missing_feature_count",
            "complete_feature_row_flag",
        ]
    ].head(
        20
    )
)

display(
    MARKET_STATE_FEATURE_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "market_state_features_assembled": (
        MARKET_STATE_FEATURES_ASSEMBLED
    ),
    "market_state_features_verified": (
        MARKET_STATE_FEATURES_VERIFIED
    ),
    "observational_unit": (
        FINAL_MARKET_STATE_OBSERVATIONAL_UNIT
    ),
    "timing_class": (
        FINAL_MARKET_STATE_TIMING_CLASS
    ),
    "physical_table_role": (
        FINAL_MARKET_STATE_PHYSICAL_TABLE_ROLE
    ),
    "label_policy": (
        FINAL_MARKET_STATE_LABEL_POLICY
    ),
    "post_batch_policy": (
        FINAL_MARKET_STATE_POST_BATCH_POLICY
    ),
    "missingness_policy": (
        FINAL_MARKET_STATE_MISSINGNESS_POLICY
    ),
    "batch_rows": (
        MARKET_STATE_FEATURE_ROW_COUNT
    ),
    "feature_count": (
        MARKET_STATE_FEATURE_COUNT
    ),
    "feature_family_count": (
        MARKET_STATE_FEATURE_FAMILY_COUNT
    ),
    "static_feature_count": int(
        len(
            STATIC_MARKET_STATE_FEATURE_COLUMNS
        )
    ),
    "event_flow_feature_count": int(
        len(
            EVENT_FLOW_MARKET_STATE_FEATURE_COLUMNS
        )
    ),
    "book_flow_feature_count": int(
        len(
            BOOK_FLOW_MARKET_STATE_FEATURE_COLUMNS
        )
    ),
    "nullable_feature_count": int(
        declared_nullable_feature_count
    ),
    "observed_missing_value_count": int(
        observed_missing_value_count
    ),
    "unexpected_missing_value_count": int(
        feature_missingness_policy_violation_count
    ),
    "infinite_feature_value_count": int(
        feature_infinite_value_count
    ),
    "complete_feature_row_count": int(
        complete_market_state_row_count
    ),
    "incomplete_feature_row_count": int(
        incomplete_market_state_row_count
    ),
    "minimum_available_feature_count": int(
        minimum_available_feature_count
    ),
    "maximum_missing_feature_count": int(
        maximum_missing_feature_count
    ),
    "same_batch_invariance_failures": int(
        market_state_same_batch_invariance_failure_count
    ),
    "imputation_applied": False,
    "tplus_fields_attached": False,
    "future_labels_attached": False,
    "current_batch_raw_fields_attached": False,
    "verified_at_utc": utc_now_iso(),
}

,feature_family,source_block,source_registry,feature_count,nullable_feature_count,observed_missing_value_count,unexpected_missing_value_count,infinite_value_count,status
0,STATIC_VISIBLE_BOOK_STATE,BATCH_STATIC_VISIBLE_BOOK_FEATURES,STATIC_VISIBLE_BOOK_FEATURE_REGISTRY,86,0,0,0,0,PASS
1,CAUSAL_EVENT_FLOW_HISTORY,BATCH_CAUSAL_EVENT_FLOW_FEATURES,CAUSAL_EVENT_FLOW_FEATURE_REGISTRY,232,62,45834,0,0,PASS
2,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,BATCH_CAUSAL_BOOK_FLOW_FEATURES,CAUSAL_BOOK_FLOW_FEATURE_REGISTRY,253,28,3084,0,0,PASS

,event_partition_order,event_partition,batch_count,complete_feature_row_count,minimum_available_feature_count,median_available_feature_count,maximum_available_feature_count,maximum_missing_feature_count,complete_feature_row_fraction,status
0,1,DEVELOPMENT,6859,3282,481,570.0,571,90,0.478495,PASS
1,2,CALIBRATION,2400,1402,555,571.0,571,16,0.584167,PASS
2,3,VALIDATION,1999,1243,555,571.0,571,16,0.621811,PASS
3,4,ENGINEERING_HOLDOUT,2306,1547,555,571.0,571,16,0.670859,PASS

,feature_name,feature_family,observed_missing_count,allowed_missing_count,unexpected_missing_count,missingness_policy_class,selected_causal_conditions,status
93,tminus_event_w1s_activated_mark_fraction,CAUSAL_EVENT_FLOW_HISTORY,496,496,0,EXACT_CAUSAL_CONDITION,tminus_event_w1s_event_count<=0,PASS
108,tminus_event_w1s_activated_vwap,CAUSAL_EVENT_FLOW_HISTORY,498,498,0,EXACT_CAUSAL_CONDITION,tminus_event_w1s_activated_quantity<=0,PASS
110,tminus_event_w1s_buy_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,496,496,0,EXACT_CAUSAL_CONDITION,tminus_event_w1s_event_count<=0,PASS
117,tminus_event_w1s_mean_events_per_batch,CAUSAL_EVENT_FLOW_HISTORY,496,496,0,EXACT_CAUSAL_CONDITION,tminus_event_w1s_prior_batch_count<=0,PASS
119,tminus_event_w1s_mixed_side_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,496,496,0,EXACT_CAUSAL_CONDITION,tminus_event_w1s_prior_batch_count<=0,PASS
127,tminus_event_w1s_sell_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,496,496,0,EXACT_CAUSAL_CONDITION,tminus_event_w1s_event_count<=0,PASS
130,tminus_event_w1s_signed_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,496,496,0,EXACT_CAUSAL_CONDITION,tminus_event_w1s_event_count<=0,PASS
132,tminus_event_w1s_simultaneous_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,496,496,0,EXACT_CAUSAL_CONDITION,tminus_event_w1s_prior_batch_count<=0,PASS
141,tminus_event_w250ms_activated_mark_fraction,CAUSAL_EVENT_FLOW_HISTORY,5102,5102,0,EXACT_CAUSAL_CONDITION,tminus_event_w250ms_event_count<=0,PASS
156,tminus_event_w250ms_activated_vwap,CAUSAL_EVENT_FLOW_HISTORY,5141,5141,0,EXACT_CAUSAL_CONDITION,tminus_event_w250ms_activated_quantity<=0,PASS
158,tminus_event_w250ms_buy_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,5102,5102,0,EXACT_CAUSAL_CONDITION,tminus_event_w250ms_event_count<=0,PASS
165,tminus_event_w250ms_mean_events_per_batch,CAUSAL_EVENT_FLOW_HISTORY,5102,5102,0,EXACT_CAUSAL_CONDITION,tminus_event_w250ms_prior_batch_count<=0,PASS
167,tminus_event_w250ms_mixed_side_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,5102,5102,0,EXACT_CAUSAL_CONDITION,tminus_event_w250ms_prior_batch_count<=0,PASS
175,tminus_event_w250ms_sell_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,5102,5102,0,EXACT_CAUSAL_CONDITION,tminus_event_w250ms_event_count<=0,PASS
178,tminus_event_w250ms_signed_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,5102,5102,0,EXACT_CAUSAL_CONDITION,tminus_event_w250ms_event_count<=0,PASS
180,tminus_event_w250ms_simultaneous_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,5102,5102,0,EXACT_CAUSAL_CONDITION,tminus_event_w250ms_prior_batch_count<=0,PASS
189,tminus_event_w30s_activated_mark_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_event_count<=0,PASS
191,tminus_event_w30s_activated_notional_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,127,127,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_full_coverage_flag=False,PASS
193,tminus_event_w30s_activated_print_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,127,127,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_full_coverage_flag=False,PASS
195,tminus_event_w30s_activated_quantity_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,127,127,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_full_coverage_flag=False,PASS
204,tminus_event_w30s_activated_vwap,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_activated_quantity<=0,PASS
206,tminus_event_w30s_buy_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_event_count<=0,PASS
207,tminus_event_w30s_buy_event_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,127,127,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_full_coverage_flag=False,PASS
211,tminus_event_w30s_event_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,127,127,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_full_coverage_flag=False,PASS
213,tminus_event_w30s_mean_events_per_batch,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_prior_batch_count<=0,PASS
215,tminus_event_w30s_mixed_side_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_prior_batch_count<=0,PASS
220,tminus_event_w30s_prior_batch_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,127,127,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_full_coverage_flag=False,PASS
223,tminus_event_w30s_sell_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_event_count<=0,PASS
224,tminus_event_w30s_sell_event_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,127,127,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_full_coverage_flag=False,PASS
226,tminus_event_w30s_signed_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_event_count<=0,PASS
228,tminus_event_w30s_simultaneous_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w30s_prior_batch_count<=0,PASS
237,tminus_event_w5s_activated_mark_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_event_count<=0,PASS
239,tminus_event_w5s_activated_notional_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,12,12,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_full_coverage_flag=False,PASS
241,tminus_event_w5s_activated_print_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,12,12,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_full_coverage_flag=False,PASS
243,tminus_event_w5s_activated_quantity_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,12,12,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_full_coverage_flag=False,PASS
252,tminus_event_w5s_activated_vwap,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_activated_quantity<=0,PASS
254,tminus_event_w5s_buy_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_event_count<=0,PASS
255,tminus_event_w5s_buy_event_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,12,12,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_full_coverage_flag=False,PASS
259,tminus_event_w5s_event_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,12,12,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_full_coverage_flag=False,PASS
261,tminus_event_w5s_mean_events_per_batch,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_prior_batch_count<=0,PASS
263,tminus_event_w5s_mixed_side_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_prior_batch_count<=0,PASS
268,tminus_event_w5s_prior_batch_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,12,12,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_full_coverage_flag=False,PASS
271,tminus_event_w5s_sell_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_event_count<=0,PASS
272,tminus_event_w5s_sell_event_rate_per_second,CAUSAL_EVENT_FLOW_HISTORY,12,12,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_full_coverage_flag=False,PASS
274,tminus_event_w5s_signed_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_event_count<=0,PASS
276,tminus_event_w5s_simultaneous_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_event_w5s_prior_batch_count<=0,PASS
283,tminus_prior_batch_b10_buy_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b10_event_count<=0,PASS
287,tminus_prior_batch_b10_mean_events_per_batch,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b10_event_count<=0,PASS
289,tminus_prior_batch_b10_mixed_side_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b10_event_count<=0,PASS
292,tminus_prior_batch_b10_sell_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b10_event_count<=0,PASS
294,tminus_prior_batch_b10_signed_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b10_event_count<=0,PASS
296,tminus_prior_batch_b10_simultaneous_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b10_event_count<=0,PASS
298,tminus_prior_batch_b50_buy_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b50_event_count<=0,PASS
302,tminus_prior_batch_b50_mean_events_per_batch,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b50_buy_event_count<=0,PASS
304,tminus_prior_batch_b50_mixed_side_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b50_buy_event_count<=0,PASS
307,tminus_prior_batch_b50_sell_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b50_event_count<=0,PASS
309,tminus_prior_batch_b50_signed_event_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b50_event_count<=0,PASS
311,tminus_prior_batch_b50_simultaneous_batch_fraction,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_prior_batch_b50_buy_event_count<=0,PASS
314,tminus_time_since_last_buy_event_ms,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_has_prior_buy_event_flag=False,PASS
315,tminus_time_since_last_event_ms,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,tminus_has_prior_event_flag=False,PASS
316,tminus_time_since_last_sell_event_ms,CAUSAL_EVENT_FLOW_HISTORY,5,5,0,EXACT_CAUSAL_CONDITION,tminus_has_prior_sell_event_flag=False,PASS
317,tminus_time_since_previous_batch_ms,CAUSAL_EVENT_FLOW_HISTORY,1,1,0,EXACT_CAUSAL_CONDITION,INITIAL_CONTIGUOUS_HISTORY_LEFT_CENSORING,PASS
323,tminus_book_flow_w1s_actual_changed_level_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,2,2,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w1s_full_coverage_flag=False,PASS
335,tminus_book_flow_w1s_level_one_ofi_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,2,2,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w1s_full_coverage_flag=False,PASS
344,tminus_book_flow_w1s_message_level_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,2,2,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w1s_full_coverage_flag=False,PASS
352,tminus_book_flow_w1s_realized_variance,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,2,2,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w1s_full_coverage_flag=False,PASS
353,tminus_book_flow_w1s_realized_volatility_basis_points,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,2,2,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w1s_full_coverage_flag=False,PASS
370,tminus_book_flow_w1s_top10_change_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,2,2,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w1s_full_coverage_flag=False,PASS
373,tminus_book_flow_w1s_top_of_book_move_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,2,2,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w1s_full_coverage_flag=False,PASS
375,tminus_book_flow_w1s_update_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,2,2,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w1s_full_coverage_flag=False,PASS
441,tminus_book_flow_w30s_actual_changed_level_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,132,132,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w30s_full_coverage_flag=False,PASS
453,tminus_book_flow_w30s_level_one_ofi_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,132,132,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w30s_full_coverage_flag=False,PASS
462,tminus_book_flow_w30s_message_level_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,132,132,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w30s_full_coverage_flag=False,PASS
470,tminus_book_flow_w30s_realized_variance,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,132,132,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w30s_full_coverage_flag=False,PASS
471,tminus_book_flow_w30s_realized_volatility_basis_points,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,132,132,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w30s_full_coverage_flag=False,PASS
488,tminus_book_flow_w30s_top10_change_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,132,132,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w30s_full_coverage_flag=False,PASS
491,tminus_book_flow_w30s_top_of_book_move_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,132,132,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w30s_full_coverage_flag=False,PASS
493,tminus_book_flow_w30s_update_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,132,132,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w30s_full_coverage_flag=False,PASS
500,tminus_book_flow_w5s_actual_changed_level_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,18,18,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w5s_full_coverage_flag=False,PASS
512,tminus_book_flow_w5s_level_one_ofi_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,18,18,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w5s_full_coverage_flag=False,PASS
521,tminus_book_flow_w5s_message_level_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,18,18,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w5s_full_coverage_flag=False,PASS
529,tminus_book_flow_w5s_realized_variance,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,18,18,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w5s_full_coverage_flag=False,PASS
530,tminus_book_flow_w5s_realized_volatility_basis_points,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,18,18,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w5s_full_coverage_flag=False,PASS
547,tminus_book_flow_w5s_top10_change_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,18,18,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w5s_full_coverage_flag=False,PASS
550,tminus_book_flow_w5s_top_of_book_move_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,18,18,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w5s_full_coverage_flag=False,PASS
552,tminus_book_flow_w5s_update_rate_per_second,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,18,18,0,EXACT_CAUSAL_CONDITION,tminus_book_flow_w5s_full_coverage_flag=False,PASS
565,tminus_book_time_since_last_midpoint_change_ms,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,93,93,0,EXACT_CAUSAL_CONDITION,tminus_book_has_prior_midpoint_change_flag=False,PASS
566,tminus_book_time_since_last_spread_change_ms,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,1589,1589,0,EXACT_CAUSAL_CONDITION,tminus_book_has_prior_spread_change_flag=False,PASS
568,tminus_book_time_since_last_top_of_book_move_ms,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,93,93,0,EXACT_CAUSAL_CONDITION,tminus_book_has_prior_top_of_book_move_flag=False,PASS
570,tminus_book_updates_since_last_midpoint_change,CAUSAL_VISIBLE_BOOK_UPDATE_HISTORY,93,93,0,EXACT_CAUSAL_CONDITION,tminus_book_has_prior_midpoint_change_flag=False,PASS

,primary_event_batch_id,primary_event_batch_number,partition_batch_index,event_partition_order,event_partition,event_time_ns,available_feature_count,missing_feature_count,complete_feature_row_flag
0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000001,1,1,1,DEVELOPMENT,1783665468766951600,481,90,False
1,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000002,2,2,1,DEVELOPMENT,1783665469052166500,520,51,False
2,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000003,3,3,1,DEVELOPMENT,1783665469437964400,528,43,False
3,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000004,4,4,1,DEVELOPMENT,1783665469692104200,528,43,False
4,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000005,5,5,1,DEVELOPMENT,1783665470242312100,528,43,False
5,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000006,6,6,1,DEVELOPMENT,1783665470304239100,537,34,False
6,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000007,7,7,1,DEVELOPMENT,1783665470597198800,529,42,False
7,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,8,8,1,DEVELOPMENT,1783665471662326600,521,50,False
8,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000009,9,9,1,DEVELOPMENT,1783665471742062100,537,34,False
9,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000010,10,10,1,DEVELOPMENT,1783665471862162900,537,34,False
10,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000011,11,11,1,DEVELOPMENT,1783665472192276400,529,42,False
11,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000012,12,12,1,DEVELOPMENT,1783665472241436900,537,34,False
12,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000013,13,13,1,DEVELOPMENT,1783665472587325700,536,35,False
13,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000014,14,14,1,DEVELOPMENT,1783665473022153600,536,35,False
14,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000015,15,15,1,DEVELOPMENT,1783665473076372900,544,27,False
15,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000016,16,16,1,DEVELOPMENT,1783665473232045400,544,27,False
16,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000017,17,17,1,DEVELOPMENT,1783665473281888100,544,27,False
17,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000018,18,18,1,DEVELOPMENT,1783665473362182500,544,27,False
18,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000019,19,19,1,DEVELOPMENT,1783665473855268900,544,27,False
19,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000020,20,20,1,DEVELOPMENT,1783665474632049800,544,27,False

                                       gate  severity   status                                                                           evidence
0          upstream_feature_blocks_verified  BLOCKING     PASS                                       static=True; event_flow=True; book_flow=True
1       canonical_batch_identity_reconciles  BLOCKING     PASS                                                                      batches=13564
2        feature_names_unique_across_blocks  BLOCKING     PASS                                                                       duplicates=0
3              final_feature_rows_conserved  BLOCKING     PASS                                                                         rows=13564
4        registry_feature_set_matches_table  BLOCKING     PASS                                                                       features=571
5                   all_features_are_tminus  BLOCKING     PASS                                                               timing_class=T_MINUS
6               missingness_policy_verified  BLOCKING     PASS                                                        unexpected_missing_values=0
7                no_infinite_feature_values  BLOCKING     PASS                                                                  infinite_values=0
8       feature_availability_rows_conserved  BLOCKING     PASS                                                                         rows=13564
9             same_batch_feature_invariance  BLOCKING     PASS                                                                   failed_batches=0
10                 no_tplus_feature_columns  BLOCKING     PASS                                                                    tplus_columns=0
11                  no_future_label_columns  BLOCKING     PASS                                                              future_like_columns=0
12             no_current_batch_raw_columns  BLOCKING     PASS                                                            current_batch_columns=0
13       every_batch_has_available_features  BLOCKING     PASS                                                     minimum_available_features=481
14  conditional_feature_missingness_present   WARNING  WARNING                                         nullable_features=90; missing_values=48918
15          incomplete_feature_rows_present   WARNING  WARNING              complete_rows=7474; incomplete_rows=6090; maximum_missing_features=90
16            no_feature_imputation_applied   WARNING  WARNING  causally explained NaN values are preserved and accompanied by availability masks

{'status': 'PASS',
 'market_state_features_assembled': True,
 'market_state_features_verified': True,
 'observational_unit': 'PRIMARY_SCORING_BATCH',
 'timing_class': 'T_MINUS',
 'physical_table_role': 'CAUSAL_MARKET_STATE_FEATURE',
 'label_policy': 'FUTURE_LABELS_PHYSICALLY_SEPARATE',
 'post_batch_policy': 'T_PLUS_CONTEXT_PHYSICALLY_SEPARATE',
 'missingness_policy': 'PRESERVE_CAUSALLY_EXPLAINED_NAN_WITHOUT_IMPUTATION',
 'batch_rows': 13564,
 'feature_count': 571,
 'feature_family_count': 3,
 'static_feature_count': 86,
 'event_flow_feature_count': 232,
 'book_flow_feature_count': 253,
 'nullable_feature_count': 90,
 'observed_missing_value_count': 48918,
 'unexpected_missing_value_count': 0,
 'infinite_feature_value_count': 0,
 'complete_feature_row_count': 7474,
 'incomplete_feature_row_count': 6090,
 'minimum_available_feature_count': 481,
 'maximum_missing_feature_count': 90,
 'same_batch_invariance_failures': 0,
 'imputation_applied': False,
 'tplus_fields_attached': False,
 'future_labels_attached': False,
 'current_batch_raw_fields_attached': False,
 'verified_at_utc': '2026-07-19T09:44:11.813498+00:00'}

In [18]:
# ============================================================
# 05_MARKET_STATE_FEATURES
# Cell 14 — Separate future-label construction, fixed-horizon
#           state observation, future order-flow aggregation,
#           boundary censoring, and leakage audit
# ============================================================

# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

require(
    globals().get(
        "MARKET_STATE_FEATURES_VERIFIED",
        False,
    )
    is True,
    "The authoritative T-minus market-state table is not verified.",
)

require(
    isinstance(
        PRIMARY_BATCH_MARKET_STATE_FEATURES,
        pd.DataFrame,
    ),
    "PRIMARY_BATCH_MARKET_STATE_FEATURES is unavailable.",
)

require(
    isinstance(
        PRIMARY_SCORING_BATCHES,
        pd.DataFrame,
    ),
    "PRIMARY_SCORING_BATCHES is unavailable.",
)

require(
    isinstance(
        SPLIT_BOUNDARY_TABLE,
        pd.DataFrame,
    ),
    "SPLIT_BOUNDARY_TABLE is unavailable.",
)

require(
    len(
        PRIMARY_BATCH_MARKET_STATE_FEATURES
    )
    == EXPECTED_PRIMARY_BATCH_ROWS,
    "The market-state feature row count is not authoritative.",
)


# ------------------------------------------------------------
# Frozen future-label policy
# ------------------------------------------------------------

FUTURE_LABEL_OBSERVATIONAL_UNIT = (
    "PRIMARY_SCORING_BATCH"
)

FUTURE_LABEL_TIMING_CLASS = (
    "FUTURE_LABEL"
)

FUTURE_LABEL_PHYSICAL_TABLE_ROLE = (
    "SEPARATE_FUTURE_LABEL"
)

FUTURE_LABEL_STATE_OBSERVATION_RULE = (
    "FIRST_SAME_PARTITION_SCORING_BATCH_AT_OR_AFTER_TARGET_TIME"
)

FUTURE_LABEL_FLOW_INTERVAL_RULE = (
    "(t, t+h]"
)

FUTURE_LABEL_PARTITION_RULE = (
    "NO_LABEL_MAY_CROSS_A_NOTEBOOK_00_PARTITION_BOUNDARY"
)

FUTURE_LABEL_OVERLAP_POLICY = (
    "OVERLAPPING_FORWARD_WINDOWS_ACKNOWLEDGED"
)

FUTURE_LABEL_CURRENT_BATCH_INCLUDED = False
FUTURE_LABEL_CROSS_PARTITION_ALLOWED = False
FUTURE_LABELS_PHYSICALLY_SEPARATE = True


# ------------------------------------------------------------
# Local helpers
# ------------------------------------------------------------

def resolve_required_column(
    frame,
    candidates,
    *,
    semantic_name,
):
    """Resolve one semantic field without inventing an alias."""

    matches = [
        column_name
        for column_name in candidates
        if column_name in frame.columns
    ]

    require(
        len(matches) > 0,
        (
            f"No authoritative column is available for "
            f"{semantic_name}. Tried: {list(candidates)}"
        ),
    )

    selected = matches[0]

    if len(matches) > 1:
        selected_values = pd.to_numeric(
            frame[selected],
            errors="raise",
        ).to_numpy(
            dtype="float64",
            na_value=np.nan,
        )

        for alternative in matches[1:]:
            alternative_values = pd.to_numeric(
                frame[alternative],
                errors="raise",
            ).to_numpy(
                dtype="float64",
                na_value=np.nan,
            )

            require(
                np.allclose(
                    selected_values,
                    alternative_values,
                    rtol=1e-12,
                    atol=1e-10,
                    equal_nan=True,
                ),
                (
                    f"Competing authoritative columns for "
                    f"{semantic_name} do not reconcile: "
                    f"{selected} versus {alternative}."
                ),
            )

    return selected, tuple(matches)


def nan_safe_direction(
    values,
    *,
    tolerance,
):
    """Return nullable {-1, 0, 1} direction codes."""

    numeric = np.asarray(
        values,
        dtype="float64",
    )

    output = pd.array(
        [pd.NA] * len(numeric),
        dtype="Int8",
    )

    valid = np.isfinite(numeric)

    output[
        valid & (numeric > tolerance)
    ] = 1

    output[
        valid & (numeric < -tolerance)
    ] = -1

    output[
        valid
        & (numeric >= -tolerance)
        & (numeric <= tolerance)
    ] = 0

    return output


def nullable_boolean_from_direction(
    direction,
    target_code,
):
    """Return a nullable BooleanArray from a nullable direction code."""

    output = pd.array(
        [pd.NA] * len(direction),
        dtype="boolean",
    )

    valid = ~pd.isna(direction)

    output[valid] = (
        np.asarray(
            direction[valid],
            dtype="int8",
        )
        == target_code
    )

    return output


def cumulative_sum_with_zero(values):
    """Return a leading-zero cumulative sum."""

    numeric = np.asarray(values)

    return np.concatenate(
        [
            np.zeros(
                1,
                dtype=numeric.dtype,
            ),
            np.cumsum(
                numeric,
                dtype=numeric.dtype,
            ),
        ]
    )


def derive_horizon_name(
    source_window_name,
    window_ns,
):
    """Convert a causal history window name into a future horizon name."""

    normalized = str(
        source_window_name
    ).strip().upper()

    if normalized.startswith("W"):
        return "H" + normalized[1:]

    window_ns = int(window_ns)

    if window_ns % 1_000_000_000 == 0:
        return (
            f"H{window_ns // 1_000_000_000}S"
        )

    if window_ns % 1_000_000 == 0:
        return (
            f"H{window_ns // 1_000_000}MS"
        )

    return f"H{window_ns}NS"


def resolve_clock_window_contract():
    """Resolve the already-frozen clock-time feature-window grid."""

    candidate_names = (
        "ROLLING_WINDOW_CONTRACT",
        "MARKET_STATE_ROLLING_WINDOW_CONTRACT",
        "FEATURE_WINDOW_CONTRACT",
        "ROLLING_FEATURE_WINDOW_CONTRACT",
    )

    for candidate_name in candidate_names:
        candidate = globals().get(
            candidate_name
        )

        if not isinstance(
            candidate,
            pd.DataFrame,
        ):
            continue

        required = {
            "window_name",
            "window_type",
            "window_ns",
        }

        if not required.issubset(
            candidate.columns
        ):
            continue

        clock_rows = candidate.loc[
            candidate[
                "window_type"
            ]
            .astype("string")
            .str.upper()
            .eq("CLOCK_TIME")
        ].copy()

        if clock_rows.empty:
            continue

        return (
            candidate_name,
            clock_rows,
        )

    fallback = pd.DataFrame(
        {
            "window_name": [
                "W250MS",
                "W1S",
                "W5S",
                "W30S",
            ],
            "window_type": [
                "CLOCK_TIME",
            ]
            * 4,
            "window_ns": [
                250_000_000,
                1_000_000_000,
                5_000_000_000,
                30_000_000_000,
            ],
            "window_seconds": [
                0.25,
                1.0,
                5.0,
                30.0,
            ],
        }
    )

    return (
        "FROZEN_NOTEBOOK_05_FALLBACK_GRID",
        fallback,
    )


# ------------------------------------------------------------
# Resolve authoritative state columns
#
# The previously verified static feature table names the
# level-one weighted midpoint explicitly. That quantity is the
# reconstructed-book microprice authority. No nonexistent
# tminus_book_microprice alias is required.
# ------------------------------------------------------------

MIDPOINT_SOURCE_COLUMN, MIDPOINT_MATCHES = (
    resolve_required_column(
        PRIMARY_BATCH_MARKET_STATE_FEATURES,
        (
            "tminus_book_midpoint",
        ),
        semantic_name="midpoint",
    )
)

MICROPRICE_SOURCE_COLUMN, MICROPRICE_MATCHES = (
    resolve_required_column(
        PRIMARY_BATCH_MARKET_STATE_FEATURES,
        (
            "tminus_book_microprice",
            "tminus_book_weighted_midpoint",
        ),
        semantic_name="microprice",
    )
)

SPREAD_SOURCE_COLUMN, SPREAD_MATCHES = (
    resolve_required_column(
        PRIMARY_BATCH_MARKET_STATE_FEATURES,
        (
            "tminus_book_spread",
        ),
        semantic_name="spread",
    )
)

TICK_SIZE_SOURCE_COLUMN, TICK_SIZE_MATCHES = (
    resolve_required_column(
        PRIMARY_BATCH_MARKET_STATE_FEATURES,
        (
            "tminus_book_implied_tick_size",
        ),
        semantic_name="implied tick size",
    )
)

LABEL_STATE_SOURCE_RESOLUTION_AUDIT = pd.DataFrame(
    [
        {
            "semantic_field": "MIDPOINT",
            "selected_column": MIDPOINT_SOURCE_COLUMN,
            "matching_columns": "; ".join(
                MIDPOINT_MATCHES
            ),
            "resolution_status": "PASS",
        },
        {
            "semantic_field": "MICROPRICE",
            "selected_column": MICROPRICE_SOURCE_COLUMN,
            "matching_columns": "; ".join(
                MICROPRICE_MATCHES
            ),
            "resolution_status": (
                "PASS_DIRECT"
                if MICROPRICE_SOURCE_COLUMN
                == "tminus_book_microprice"
                else "PASS_WEIGHTED_MIDPOINT_AUTHORITY"
            ),
        },
        {
            "semantic_field": "SPREAD",
            "selected_column": SPREAD_SOURCE_COLUMN,
            "matching_columns": "; ".join(
                SPREAD_MATCHES
            ),
            "resolution_status": "PASS",
        },
        {
            "semantic_field": "TICK_SIZE",
            "selected_column": TICK_SIZE_SOURCE_COLUMN,
            "matching_columns": "; ".join(
                TICK_SIZE_MATCHES
            ),
            "resolution_status": "PASS",
        },
    ]
)


# ------------------------------------------------------------
# Canonical identity and scoring-batch reconciliation
# ------------------------------------------------------------

LABEL_CANONICAL_IDENTITY = (
    PRIMARY_BATCH_MARKET_STATE_FEATURES[
        list(
            FINAL_MARKET_STATE_IDENTITY_COLUMNS
        )
    ]
    .copy()
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)
)

SCORING_BATCH_IDENTITY = (
    PRIMARY_SCORING_BATCHES[
        list(
            FINAL_MARKET_STATE_IDENTITY_COLUMNS
        )
    ]
    .copy()
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)
)

try:
    pd.testing.assert_frame_equal(
        LABEL_CANONICAL_IDENTITY,
        SCORING_BATCH_IDENTITY,
        check_dtype=False,
        check_exact=True,
        check_names=True,
    )

except AssertionError as exc:
    raise AssertionError(
        (
            "PRIMARY_SCORING_BATCHES does not match the "
            f"market-state feature identity: {exc}"
        )
    ) from exc


SCORING_BATCH_LABEL_SOURCE_COLUMNS = (
    *FINAL_MARKET_STATE_IDENTITY_COLUMNS,
    "batch_event_count",
    "buy_event_count",
    "sell_event_count",
    "batch_print_count",
    "batch_quantity",
    "batch_notional",
    "mixed_side_batch_flag",
    "simultaneous_batch_required_flag",
)

require_columns(
    PRIMARY_SCORING_BATCHES,
    SCORING_BATCH_LABEL_SOURCE_COLUMNS,
    "PRIMARY_SCORING_BATCHES",
)

SCORING_BATCH_LABEL_SOURCE = (
    PRIMARY_SCORING_BATCHES[
        list(
            SCORING_BATCH_LABEL_SOURCE_COLUMNS
        )
    ]
    .copy()
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)
)

for integer_column in (
    "primary_event_batch_number",
    "partition_batch_index",
    "event_partition_order",
    "event_time_ns",
    "batch_event_count",
    "buy_event_count",
    "sell_event_count",
    "batch_print_count",
):
    SCORING_BATCH_LABEL_SOURCE[
        integer_column
    ] = pd.to_numeric(
        SCORING_BATCH_LABEL_SOURCE[
            integer_column
        ],
        errors="raise",
    ).astype("int64")

for floating_column in (
    "batch_quantity",
    "batch_notional",
):
    SCORING_BATCH_LABEL_SOURCE[
        floating_column
    ] = pd.to_numeric(
        SCORING_BATCH_LABEL_SOURCE[
            floating_column
        ],
        errors="raise",
    ).astype("float64")

for boolean_column in (
    "mixed_side_batch_flag",
    "simultaneous_batch_required_flag",
):
    SCORING_BATCH_LABEL_SOURCE[
        boolean_column
    ] = (
        SCORING_BATCH_LABEL_SOURCE[
            boolean_column
        ]
        .astype("boolean")
        .astype(bool)
    )

require(
    (
        SCORING_BATCH_LABEL_SOURCE[
            "buy_event_count"
        ]
        + SCORING_BATCH_LABEL_SOURCE[
            "sell_event_count"
        ]
    )
    .eq(
        SCORING_BATCH_LABEL_SOURCE[
            "batch_event_count"
        ]
    )
    .all(),
    (
        "Buy and sell event counts do not reconcile with "
        "batch_event_count."
    ),
)


# ------------------------------------------------------------
# State arrays
# ------------------------------------------------------------

MARKET_STATE_LABEL_SOURCE = (
    PRIMARY_BATCH_MARKET_STATE_FEATURES
    .sort_values(
        "primary_event_batch_number",
        kind="stable",
    )
    .reset_index(drop=True)
)

CURRENT_MIDPOINT = pd.to_numeric(
    MARKET_STATE_LABEL_SOURCE[
        MIDPOINT_SOURCE_COLUMN
    ],
    errors="raise",
).to_numpy(
    dtype="float64",
    na_value=np.nan,
)

CURRENT_MICROPRICE = pd.to_numeric(
    MARKET_STATE_LABEL_SOURCE[
        MICROPRICE_SOURCE_COLUMN
    ],
    errors="raise",
).to_numpy(
    dtype="float64",
    na_value=np.nan,
)

CURRENT_SPREAD = pd.to_numeric(
    MARKET_STATE_LABEL_SOURCE[
        SPREAD_SOURCE_COLUMN
    ],
    errors="raise",
).to_numpy(
    dtype="float64",
    na_value=np.nan,
)

CURRENT_TICK_SIZE = pd.to_numeric(
    MARKET_STATE_LABEL_SOURCE[
        TICK_SIZE_SOURCE_COLUMN
    ],
    errors="raise",
).to_numpy(
    dtype="float64",
    na_value=np.nan,
)

require(
    np.isfinite(
        CURRENT_MIDPOINT
    ).all(),
    "Current midpoint contains a nonfinite value.",
)

require(
    np.isfinite(
        CURRENT_MICROPRICE
    ).all(),
    "Current microprice authority contains a nonfinite value.",
)

require(
    np.isfinite(
        CURRENT_SPREAD
    ).all(),
    "Current spread contains a nonfinite value.",
)

require(
    np.isfinite(
        CURRENT_TICK_SIZE
    ).all(),
    "Current implied tick size contains a nonfinite value.",
)

require(
    (CURRENT_MIDPOINT > 0).all(),
    "Current midpoint must be strictly positive.",
)

require(
    (CURRENT_MICROPRICE > 0).all(),
    "Current microprice must be strictly positive.",
)

require(
    (CURRENT_TICK_SIZE > 0).all(),
    "Current tick size must be strictly positive.",
)

AUTHORITATIVE_LABEL_TICK_SIZE = float(
    np.median(
        CURRENT_TICK_SIZE
    )
)

MIDPOINT_DIRECTION_TOLERANCE = max(
    AUTHORITATIVE_LABEL_TICK_SIZE
    * 0.25,
    1e-10,
)

MICROPRICE_DIRECTION_TOLERANCE = 1e-10

SPREAD_DIRECTION_TOLERANCE = max(
    AUTHORITATIVE_LABEL_TICK_SIZE
    * 0.25,
    1e-10,
)


# ------------------------------------------------------------
# Freeze prediction horizons from the existing clock grid
# ------------------------------------------------------------

(
    LABEL_HORIZON_SOURCE_NAME,
    LABEL_HORIZON_SOURCE_ROWS,
) = resolve_clock_window_contract()

LABEL_HORIZON_SOURCE_ROWS = (
    LABEL_HORIZON_SOURCE_ROWS.copy()
)

LABEL_HORIZON_SOURCE_ROWS[
    "window_ns"
] = pd.to_numeric(
    LABEL_HORIZON_SOURCE_ROWS[
        "window_ns"
    ],
    errors="raise",
).astype("int64")

LABEL_HORIZON_SOURCE_ROWS = (
    LABEL_HORIZON_SOURCE_ROWS.loc[
        LABEL_HORIZON_SOURCE_ROWS[
            "window_ns"
        ].gt(0)
    ]
    .sort_values(
        "window_ns",
        kind="stable",
    )
    .drop_duplicates(
        "window_ns",
        keep="first",
    )
    .reset_index(drop=True)
)

require(
    not LABEL_HORIZON_SOURCE_ROWS.empty,
    "No positive clock-time prediction horizon is available.",
)

FUTURE_LABEL_HORIZON_CONTRACT = pd.DataFrame(
    {
        "horizon_name": [
            derive_horizon_name(
                source_window_name,
                window_ns,
            )
            for source_window_name, window_ns in zip(
                LABEL_HORIZON_SOURCE_ROWS[
                    "window_name"
                ],
                LABEL_HORIZON_SOURCE_ROWS[
                    "window_ns"
                ],
                strict=True,
            )
        ],
        "source_window_name": (
            LABEL_HORIZON_SOURCE_ROWS[
                "window_name"
            ]
            .astype("string")
            .tolist()
        ),
        "horizon_ns": (
            LABEL_HORIZON_SOURCE_ROWS[
                "window_ns"
            ]
            .astype("int64")
            .tolist()
        ),
    }
)

FUTURE_LABEL_HORIZON_CONTRACT[
    "horizon_seconds"
] = (
    FUTURE_LABEL_HORIZON_CONTRACT[
        "horizon_ns"
    ]
    / 1_000_000_000.0
)

FUTURE_LABEL_HORIZON_CONTRACT[
    "timing_class"
] = FUTURE_LABEL_TIMING_CLASS

FUTURE_LABEL_HORIZON_CONTRACT[
    "physical_table_role"
] = FUTURE_LABEL_PHYSICAL_TABLE_ROLE

FUTURE_LABEL_HORIZON_CONTRACT[
    "state_observation_rule"
] = FUTURE_LABEL_STATE_OBSERVATION_RULE

FUTURE_LABEL_HORIZON_CONTRACT[
    "future_flow_interval"
] = FUTURE_LABEL_FLOW_INTERVAL_RULE

FUTURE_LABEL_HORIZON_CONTRACT[
    "current_batch_included"
] = FUTURE_LABEL_CURRENT_BATCH_INCLUDED

FUTURE_LABEL_HORIZON_CONTRACT[
    "cross_partition_allowed"
] = FUTURE_LABEL_CROSS_PARTITION_ALLOWED

FUTURE_LABEL_HORIZON_CONTRACT[
    "overlapping_forward_windows"
] = True

FUTURE_LABEL_HORIZON_CONTRACT[
    "horizon_selection_authority"
] = LABEL_HORIZON_SOURCE_NAME

require(
    FUTURE_LABEL_HORIZON_CONTRACT[
        "horizon_name"
    ].is_unique,
    "Future-label horizon names are not unique.",
)

require(
    FUTURE_LABEL_HORIZON_CONTRACT[
        "horizon_ns"
    ].is_monotonic_increasing,
    "Future-label horizons are not strictly ordered.",
)


# ------------------------------------------------------------
# Notebook 00 partition boundaries
# ------------------------------------------------------------

require_columns(
    SPLIT_BOUNDARY_TABLE,
    (
        "partition",
        "partition_order",
        "receipt_time_start_ns",
        "receipt_time_end_ns_exclusive",
    ),
    "SPLIT_BOUNDARY_TABLE",
)

LABEL_PARTITION_BOUNDARIES = (
    SPLIT_BOUNDARY_TABLE[
        [
            "partition",
            "partition_order",
            "receipt_time_start_ns",
            "receipt_time_end_ns_exclusive",
        ]
    ]
    .copy()
)

LABEL_PARTITION_BOUNDARIES[
    "partition"
] = (
    LABEL_PARTITION_BOUNDARIES[
        "partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
)

for integer_column in (
    "partition_order",
    "receipt_time_start_ns",
    "receipt_time_end_ns_exclusive",
):
    LABEL_PARTITION_BOUNDARIES[
        integer_column
    ] = pd.to_numeric(
        LABEL_PARTITION_BOUNDARIES[
            integer_column
        ],
        errors="raise",
    ).astype("int64")

require(
    LABEL_PARTITION_BOUNDARIES[
        "partition"
    ].is_unique,
    "Partition boundary table contains duplicate partitions.",
)

PARTITION_END_NS_EXCLUSIVE = (
    LABEL_PARTITION_BOUNDARIES
    .set_index(
        "partition"
    )[
        "receipt_time_end_ns_exclusive"
    ]
    .to_dict()
)

PARTITION_ORDER_LOOKUP = (
    LABEL_PARTITION_BOUNDARIES
    .set_index(
        "partition"
    )[
        "partition_order"
    ]
    .to_dict()
)


# ------------------------------------------------------------
# Construct future labels
#
# State labels:
#   first same-partition scoring batch at or after t+h.
#
# Flow labels:
#   all completed scoring batches in (t, t+h].
#
# The current batch is excluded from every future-flow label.
# ------------------------------------------------------------

row_count = len(
    MARKET_STATE_LABEL_SOURCE
)

batch_ids = (
    MARKET_STATE_LABEL_SOURCE[
        "primary_event_batch_id"
    ]
    .astype("string")
    .to_numpy(
        dtype=object
    )
)

batch_numbers = pd.to_numeric(
    MARKET_STATE_LABEL_SOURCE[
        "primary_event_batch_number"
    ],
    errors="raise",
).to_numpy(
    dtype="int64"
)

batch_times = pd.to_numeric(
    MARKET_STATE_LABEL_SOURCE[
        "event_time_ns"
    ],
    errors="raise",
).to_numpy(
    dtype="int64"
)

batch_partitions = (
    MARKET_STATE_LABEL_SOURCE[
        "event_partition"
    ]
    .astype("string")
    .str.strip()
    .str.upper()
    .to_numpy(
        dtype=object
    )
)

buy_event_count = (
    SCORING_BATCH_LABEL_SOURCE[
        "buy_event_count"
    ]
    .to_numpy(
        dtype="int64"
    )
)

sell_event_count = (
    SCORING_BATCH_LABEL_SOURCE[
        "sell_event_count"
    ]
    .to_numpy(
        dtype="int64"
    )
)

total_event_count = (
    SCORING_BATCH_LABEL_SOURCE[
        "batch_event_count"
    ]
    .to_numpy(
        dtype="int64"
    )
)

print_count = (
    SCORING_BATCH_LABEL_SOURCE[
        "batch_print_count"
    ]
    .to_numpy(
        dtype="int64"
    )
)

batch_quantity = (
    SCORING_BATCH_LABEL_SOURCE[
        "batch_quantity"
    ]
    .to_numpy(
        dtype="float64"
    )
)

batch_notional = (
    SCORING_BATCH_LABEL_SOURCE[
        "batch_notional"
    ]
    .to_numpy(
        dtype="float64"
    )
)

mixed_side_flag = (
    SCORING_BATCH_LABEL_SOURCE[
        "mixed_side_batch_flag"
    ]
    .to_numpy(
        dtype=bool
    )
)

simultaneous_flag = (
    SCORING_BATCH_LABEL_SOURCE[
        "simultaneous_batch_required_flag"
    ]
    .to_numpy(
        dtype=bool
    )
)


future_label_blocks = []
future_label_registry_rows = []
future_label_partition_audit_rows = []
future_label_missingness_rows = []


for horizon_record in (
    FUTURE_LABEL_HORIZON_CONTRACT
    .itertuples(
        index=False
    )
):
    horizon_name = str(
        horizon_record.horizon_name
    )

    horizon_slug = (
        horizon_name.lower()
    )

    horizon_ns = int(
        horizon_record.horizon_ns
    )

    prefix = (
        f"label_{horizon_slug}"
    )

    target_time_ns = (
        batch_times
        + horizon_ns
    )

    partition_boundary_valid = np.zeros(
        row_count,
        dtype=bool,
    )

    future_state_available = np.zeros(
        row_count,
        dtype=bool,
    )

    future_observation_batch_id = np.full(
        row_count,
        None,
        dtype=object,
    )

    future_observation_batch_number = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_observation_time_ns = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_observation_delay_ns = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_midpoint = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_microprice = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_spread = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_flow_window_valid = np.zeros(
        row_count,
        dtype=bool,
    )

    future_buy_event_count = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_sell_event_count = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_total_event_count = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_signed_event_count = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_batch_count = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_print_count = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_quantity = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_notional = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_simultaneous_batch_count = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_mixed_side_batch_count = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    future_midpoint_realized_variance_bps2 = np.full(
        row_count,
        np.nan,
        dtype="float64",
    )

    for partition_name in (
        AUTHORITATIVE_PARTITION_ORDER
    ):
        partition_name = str(
            partition_name
        ).upper()

        global_positions = np.flatnonzero(
            batch_partitions
            == partition_name
        )

        require(
            global_positions.size > 0,
            (
                f"No scoring batches are available for "
                f"partition {partition_name}."
            ),
        )

        local_times = batch_times[
            global_positions
        ]

        require(
            np.all(
                np.diff(
                    local_times
                )
                > 0
            ),
            (
                "Scoring-batch times are not strictly "
                f"increasing in partition {partition_name}."
            ),
        )

        partition_end_exclusive = int(
            PARTITION_END_NS_EXCLUSIVE[
                partition_name
            ]
        )

        local_target_times = (
            local_times
            + horizon_ns
        )

        local_boundary_valid = (
            local_target_times
            < partition_end_exclusive
        )

        partition_boundary_valid[
            global_positions
        ] = local_boundary_valid

        future_flow_window_valid[
            global_positions
        ] = local_boundary_valid

        observation_local_index = np.searchsorted(
            local_times,
            local_target_times,
            side="left",
        )

        local_state_available = (
            local_boundary_valid
            & (
                observation_local_index
                < len(
                    local_times
                )
            )
        )

        future_state_available[
            global_positions
        ] = local_state_available

        available_source_positions = np.flatnonzero(
            local_state_available
        )

        if available_source_positions.size > 0:
            future_local_positions = (
                observation_local_index[
                    available_source_positions
                ]
            )

            source_global_positions = (
                global_positions[
                    available_source_positions
                ]
            )

            future_global_positions = (
                global_positions[
                    future_local_positions
                ]
            )

            future_observation_batch_id[
                source_global_positions
            ] = batch_ids[
                future_global_positions
            ]

            future_observation_batch_number[
                source_global_positions
            ] = batch_numbers[
                future_global_positions
            ]

            future_observation_time_ns[
                source_global_positions
            ] = batch_times[
                future_global_positions
            ]

            future_observation_delay_ns[
                source_global_positions
            ] = (
                batch_times[
                    future_global_positions
                ]
                - target_time_ns[
                    source_global_positions
                ]
            )

            future_midpoint[
                source_global_positions
            ] = CURRENT_MIDPOINT[
                future_global_positions
            ]

            future_microprice[
                source_global_positions
            ] = CURRENT_MICROPRICE[
                future_global_positions
            ]

            future_spread[
                source_global_positions
            ] = CURRENT_SPREAD[
                future_global_positions
            ]

        local_window_end_index = (
            np.searchsorted(
                local_times,
                local_target_times,
                side="right",
            )
            - 1
        )

        local_buy = buy_event_count[
            global_positions
        ]

        local_sell = sell_event_count[
            global_positions
        ]

        local_total = total_event_count[
            global_positions
        ]

        local_print = print_count[
            global_positions
        ]

        local_quantity = batch_quantity[
            global_positions
        ]

        local_notional = batch_notional[
            global_positions
        ]

        local_simultaneous = (
            simultaneous_flag[
                global_positions
            ]
            .astype("int64")
        )

        local_mixed = (
            mixed_side_flag[
                global_positions
            ]
            .astype("int64")
        )

        buy_prefix = cumulative_sum_with_zero(
            local_buy
        )

        sell_prefix = cumulative_sum_with_zero(
            local_sell
        )

        total_prefix = cumulative_sum_with_zero(
            local_total
        )

        print_prefix = cumulative_sum_with_zero(
            local_print
        )

        quantity_prefix = cumulative_sum_with_zero(
            local_quantity
        )

        notional_prefix = cumulative_sum_with_zero(
            local_notional
        )

        simultaneous_prefix = cumulative_sum_with_zero(
            local_simultaneous
        )

        mixed_prefix = cumulative_sum_with_zero(
            local_mixed
        )

        local_log_midpoint = np.log(
            CURRENT_MIDPOINT[
                global_positions
            ]
        )

        local_squared_return_bps2 = np.zeros(
            len(
                global_positions
            ),
            dtype="float64",
        )

        if len(
            global_positions
        ) > 1:
            local_squared_return_bps2[
                1:
            ] = (
                np.diff(
                    local_log_midpoint
                )
                * 10_000.0
            ) ** 2

        realized_variance_prefix = (
            cumulative_sum_with_zero(
                local_squared_return_bps2
            )
        )

        valid_local_sources = np.flatnonzero(
            local_boundary_valid
        )

        if valid_local_sources.size > 0:
            valid_local_ends = (
                local_window_end_index[
                    valid_local_sources
                ]
            )

            require(
                np.all(
                    valid_local_ends
                    >= valid_local_sources
                ),
                (
                    "A future-flow window ended before its "
                    f"source batch in {partition_name}."
                ),
            )

            valid_global_sources = (
                global_positions[
                    valid_local_sources
                ]
            )

            source_prefix_index = (
                valid_local_sources
                + 1
            )

            end_prefix_index = (
                valid_local_ends
                + 1
            )

            future_buy_event_count[
                valid_global_sources
            ] = (
                buy_prefix[
                    end_prefix_index
                ]
                - buy_prefix[
                    source_prefix_index
                ]
            )

            future_sell_event_count[
                valid_global_sources
            ] = (
                sell_prefix[
                    end_prefix_index
                ]
                - sell_prefix[
                    source_prefix_index
                ]
            )

            future_total_event_count[
                valid_global_sources
            ] = (
                total_prefix[
                    end_prefix_index
                ]
                - total_prefix[
                    source_prefix_index
                ]
            )

            future_signed_event_count[
                valid_global_sources
            ] = (
                future_buy_event_count[
                    valid_global_sources
                ]
                - future_sell_event_count[
                    valid_global_sources
                ]
            )

            future_batch_count[
                valid_global_sources
            ] = (
                valid_local_ends
                - valid_local_sources
            )

            future_print_count[
                valid_global_sources
            ] = (
                print_prefix[
                    end_prefix_index
                ]
                - print_prefix[
                    source_prefix_index
                ]
            )

            future_quantity[
                valid_global_sources
            ] = (
                quantity_prefix[
                    end_prefix_index
                ]
                - quantity_prefix[
                    source_prefix_index
                ]
            )

            future_notional[
                valid_global_sources
            ] = (
                notional_prefix[
                    end_prefix_index
                ]
                - notional_prefix[
                    source_prefix_index
                ]
            )

            future_simultaneous_batch_count[
                valid_global_sources
            ] = (
                simultaneous_prefix[
                    end_prefix_index
                ]
                - simultaneous_prefix[
                    source_prefix_index
                ]
            )

            future_mixed_side_batch_count[
                valid_global_sources
            ] = (
                mixed_prefix[
                    end_prefix_index
                ]
                - mixed_prefix[
                    source_prefix_index
                ]
            )

            future_midpoint_realized_variance_bps2[
                valid_global_sources
            ] = (
                realized_variance_prefix[
                    end_prefix_index
                ]
                - realized_variance_prefix[
                    source_prefix_index
                ]
            )

        future_label_partition_audit_rows.append(
            {
                "horizon_name": horizon_name,
                "horizon_ns": horizon_ns,
                "event_partition_order": int(
                    PARTITION_ORDER_LOOKUP[
                        partition_name
                    ]
                ),
                "event_partition": partition_name,
                "batch_count": int(
                    len(
                        global_positions
                    )
                ),
                "partition_boundary_valid_count": int(
                    local_boundary_valid.sum()
                ),
                "partition_boundary_censored_count": int(
                    (
                        ~local_boundary_valid
                    ).sum()
                ),
                "future_state_available_count": int(
                    local_state_available.sum()
                ),
                "future_state_unavailable_count": int(
                    (
                        ~local_state_available
                    ).sum()
                ),
                "maximum_future_observation_delay_ns": (
                    int(
                        np.nanmax(
                            future_observation_delay_ns[
                                global_positions
                            ]
                        )
                    )
                    if local_state_available.any()
                    else pd.NA
                ),
            }
        )

    require(
        np.all(
            target_time_ns
            > batch_times
        ),
        (
            f"{horizon_name} contains a target time that is "
            "not strictly after the source batch."
        ),
    )

    require(
        np.all(
            future_observation_delay_ns[
                future_state_available
            ]
            >= 0
        ),
        (
            f"{horizon_name} resolved a future observation "
            "before its target time."
        ),
    )

    future_midpoint_change = (
        future_midpoint
        - CURRENT_MIDPOINT
    )

    future_microprice_change = (
        future_microprice
        - CURRENT_MICROPRICE
    )

    future_spread_change = (
        future_spread
        - CURRENT_SPREAD
    )

    future_midpoint_change_bps = (
        future_midpoint_change
        / CURRENT_MIDPOINT
        * 10_000.0
    )

    future_microprice_change_bps = (
        future_microprice_change
        / CURRENT_MICROPRICE
        * 10_000.0
    )

    midpoint_direction = nan_safe_direction(
        future_midpoint_change,
        tolerance=(
            MIDPOINT_DIRECTION_TOLERANCE
        ),
    )

    microprice_direction = nan_safe_direction(
        future_microprice_change,
        tolerance=(
            MICROPRICE_DIRECTION_TOLERANCE
        ),
    )

    spread_direction = nan_safe_direction(
        future_spread_change,
        tolerance=(
            SPREAD_DIRECTION_TOLERANCE
        ),
    )

    future_realized_volatility_bps = np.sqrt(
        future_midpoint_realized_variance_bps2
    )

    block = pd.DataFrame(
        {
            f"{prefix}_target_time_ns": (
                target_time_ns
            ),
            (
                f"{prefix}_partition_boundary_"
                "valid_flag"
            ): partition_boundary_valid,
            (
                f"{prefix}_future_state_"
                "available_flag"
            ): future_state_available,
            (
                f"{prefix}_future_observation_"
                "batch_id"
            ): pd.array(
                future_observation_batch_id,
                dtype="string",
            ),
            (
                f"{prefix}_future_observation_"
                "batch_number"
            ): pd.array(
                future_observation_batch_number,
                dtype="Int64",
            ),
            (
                f"{prefix}_future_observation_"
                "time_ns"
            ): pd.array(
                future_observation_time_ns,
                dtype="Int64",
            ),
            (
                f"{prefix}_future_observation_"
                "delay_ns"
            ): pd.array(
                future_observation_delay_ns,
                dtype="Int64",
            ),
            f"{prefix}_future_midpoint": (
                future_midpoint
            ),
            (
                f"{prefix}_future_midpoint_"
                "change"
            ): future_midpoint_change,
            (
                f"{prefix}_future_midpoint_"
                "change_bps"
            ): future_midpoint_change_bps,
            (
                f"{prefix}_future_midpoint_"
                "direction_code"
            ): midpoint_direction,
            (
                f"{prefix}_future_midpoint_up_flag"
            ): nullable_boolean_from_direction(
                midpoint_direction,
                1,
            ),
            (
                f"{prefix}_future_midpoint_down_flag"
            ): nullable_boolean_from_direction(
                midpoint_direction,
                -1,
            ),
            (
                f"{prefix}_future_midpoint_flat_flag"
            ): nullable_boolean_from_direction(
                midpoint_direction,
                0,
            ),
            f"{prefix}_future_microprice": (
                future_microprice
            ),
            (
                f"{prefix}_future_microprice_"
                "change"
            ): future_microprice_change,
            (
                f"{prefix}_future_microprice_"
                "change_bps"
            ): future_microprice_change_bps,
            (
                f"{prefix}_future_microprice_"
                "direction_code"
            ): microprice_direction,
            f"{prefix}_future_spread": (
                future_spread
            ),
            (
                f"{prefix}_future_spread_change"
            ): future_spread_change,
            (
                f"{prefix}_future_spread_"
                "widening_flag"
            ): nullable_boolean_from_direction(
                spread_direction,
                1,
            ),
            (
                f"{prefix}_future_spread_"
                "narrowing_flag"
            ): nullable_boolean_from_direction(
                spread_direction,
                -1,
            ),
            (
                f"{prefix}_future_flow_window_"
                "valid_flag"
            ): future_flow_window_valid,
            (
                f"{prefix}_future_buy_event_count"
            ): pd.array(
                future_buy_event_count,
                dtype="Int64",
            ),
            (
                f"{prefix}_future_sell_event_count"
            ): pd.array(
                future_sell_event_count,
                dtype="Int64",
            ),
            (
                f"{prefix}_future_total_event_count"
            ): pd.array(
                future_total_event_count,
                dtype="Int64",
            ),
            (
                f"{prefix}_future_signed_event_count"
            ): pd.array(
                future_signed_event_count,
                dtype="Int64",
            ),
            (
                f"{prefix}_future_batch_count"
            ): pd.array(
                future_batch_count,
                dtype="Int64",
            ),
            (
                f"{prefix}_future_print_count"
            ): pd.array(
                future_print_count,
                dtype="Int64",
            ),
            (
                f"{prefix}_future_quantity"
            ): future_quantity,
            (
                f"{prefix}_future_notional"
            ): future_notional,
            (
                f"{prefix}_future_simultaneous_"
                "batch_count"
            ): pd.array(
                future_simultaneous_batch_count,
                dtype="Int64",
            ),
            (
                f"{prefix}_future_mixed_side_"
                "batch_count"
            ): pd.array(
                future_mixed_side_batch_count,
                dtype="Int64",
            ),
            (
                f"{prefix}_future_midpoint_"
                "realized_variance_bps2"
            ): (
                future_midpoint_realized_variance_bps2
            ),
            (
                f"{prefix}_future_midpoint_"
                "realized_volatility_bps"
            ): future_realized_volatility_bps,
        }
    )

    require_unique_columns(
        block,
        f"{horizon_name} future-label block",
    )

    future_label_blocks.append(
        block
    )

    state_availability_column = (
        f"{prefix}_future_state_available_flag"
    )

    flow_availability_column = (
        f"{prefix}_future_flow_window_valid_flag"
    )

    state_label_names = [
        column_name
        for column_name in block.columns
        if (
            "future_observation_" in column_name
            or "future_midpoint" in column_name
            or "future_microprice" in column_name
            or "future_spread" in column_name
        )
        and column_name
        not in {
            state_availability_column,
            (
                f"{prefix}_future_midpoint_"
                "realized_variance_bps2"
            ),
            (
                f"{prefix}_future_midpoint_"
                "realized_volatility_bps"
            ),
        }
    ]

    flow_label_names = [
        column_name
        for column_name in block.columns
        if (
            "future_buy_event_count"
            in column_name
            or "future_sell_event_count"
            in column_name
            or "future_total_event_count"
            in column_name
            or "future_signed_event_count"
            in column_name
            or "future_batch_count"
            in column_name
            or "future_print_count"
            in column_name
            or "future_quantity"
            in column_name
            or "future_notional"
            in column_name
            or "future_simultaneous_batch_count"
            in column_name
            or "future_mixed_side_batch_count"
            in column_name
            or "realized_variance_bps2"
            in column_name
            or "realized_volatility_bps"
            in column_name
        )
    ]

    always_available_names = [
        f"{prefix}_target_time_ns",
        (
            f"{prefix}_partition_boundary_"
            "valid_flag"
        ),
        state_availability_column,
        flow_availability_column,
    ]

    for label_name in block.columns:
        if label_name in state_label_names:
            availability_class = (
                "FUTURE_STATE_OBSERVATION"
            )

            availability_flag_column = (
                state_availability_column
            )

            missingness_rule = (
                "Missing exactly when no same-partition "
                "scoring batch exists at or after target time."
            )

        elif label_name in flow_label_names:
            availability_class = (
                "FUTURE_FLOW_WINDOW"
            )

            availability_flag_column = (
                flow_availability_column
            )

            missingness_rule = (
                "Missing exactly when t+h reaches or crosses "
                "the source partition boundary."
            )

        elif label_name in always_available_names:
            availability_class = (
                "ALWAYS_DEFINED_LABEL_METADATA"
            )

            availability_flag_column = None

            missingness_rule = (
                "No missing value is permitted."
            )

        else:
            raise AssertionError(
                (
                    "Future-label availability class was not "
                    f"resolved for {label_name}."
                )
            )

        future_label_registry_rows.append(
            {
                "label_name": label_name,
                "horizon_name": horizon_name,
                "horizon_ns": horizon_ns,
                "timing_class": (
                    FUTURE_LABEL_TIMING_CLASS
                ),
                "physical_table_role": (
                    FUTURE_LABEL_PHYSICAL_TABLE_ROLE
                ),
                "availability_class": (
                    availability_class
                ),
                "availability_flag_column": (
                    availability_flag_column
                ),
                "missingness_rule": (
                    missingness_rule
                ),
                "current_batch_included": False,
                "cross_partition_allowed": False,
                "overlapping_forward_window": True,
                "midpoint_source_column": (
                    MIDPOINT_SOURCE_COLUMN
                ),
                "microprice_source_column": (
                    MICROPRICE_SOURCE_COLUMN
                ),
                "spread_source_column": (
                    SPREAD_SOURCE_COLUMN
                ),
            }
        )


# ------------------------------------------------------------
# Assemble the physically separate label table
# ------------------------------------------------------------

PRIMARY_BATCH_FUTURE_LABELS = (
    pd.concat(
        [
            LABEL_CANONICAL_IDENTITY,
            *future_label_blocks,
        ],
        axis=1,
    )
    .copy(
        deep=True
    )
)

require_unique_columns(
    PRIMARY_BATCH_FUTURE_LABELS,
    "PRIMARY_BATCH_FUTURE_LABELS",
)

require(
    len(
        PRIMARY_BATCH_FUTURE_LABELS
    )
    == EXPECTED_PRIMARY_BATCH_ROWS,
    (
        "Future-label table does not contain one row per "
        "primary scoring batch."
    ),
)

require(
    PRIMARY_BATCH_FUTURE_LABELS[
        "primary_event_batch_id"
    ].is_unique,
    "Future-label table contains duplicate batch IDs.",
)

require(
    PRIMARY_BATCH_FUTURE_LABELS[
        "primary_event_batch_number"
    ].is_unique,
    "Future-label table contains duplicate batch numbers.",
)

require(
    PRIMARY_BATCH_FUTURE_LABELS[
        "primary_event_batch_number"
    ].is_monotonic_increasing,
    "Future-label table is not in canonical batch order.",
)

FUTURE_LABEL_COLUMNS = [
    column_name
    for column_name in (
        PRIMARY_BATCH_FUTURE_LABELS.columns
    )
    if column_name
    not in FINAL_MARKET_STATE_IDENTITY_COLUMNS
]

require(
    all(
        column_name.startswith(
            "label_"
        )
        for column_name in (
            FUTURE_LABEL_COLUMNS
        )
    ),
    (
        "The separate future-label table contains a "
        "non-label payload column."
    ),
)

require(
    not any(
        column_name.startswith(
            "tminus_"
        )
        for column_name in (
            FUTURE_LABEL_COLUMNS
        )
    ),
    (
        "A T-minus feature was copied into the future-label "
        "payload."
    ),
)

require(
    not any(
        column_name.startswith(
            "tplus_"
        )
        for column_name in (
            FUTURE_LABEL_COLUMNS
        )
    ),
    (
        "A T-plus diagnostic field was copied into the "
        "future-label payload."
    ),
)


# ------------------------------------------------------------
# Final label registry
# ------------------------------------------------------------

FUTURE_LABEL_REGISTRY = (
    pd.DataFrame.from_records(
        future_label_registry_rows
    )
)

require(
    len(
        FUTURE_LABEL_REGISTRY
    )
    == len(
        FUTURE_LABEL_COLUMNS
    ),
    (
        "Future-label registry does not contain one row per "
        "label column."
    ),
)

require(
    FUTURE_LABEL_REGISTRY[
        "label_name"
    ].is_unique,
    "Future-label registry contains duplicate label names.",
)

require(
    FUTURE_LABEL_REGISTRY[
        "label_name"
    ].tolist()
    == FUTURE_LABEL_COLUMNS,
    (
        "Future-label registry order does not match the "
        "future-label table."
    ),
)

FUTURE_LABEL_REGISTRY[
    "label_order"
] = np.arange(
    1,
    len(
        FUTURE_LABEL_REGISTRY
    )
    + 1,
    dtype="int64",
)


# ------------------------------------------------------------
# Missingness audit
# ------------------------------------------------------------

for registry_record in (
    FUTURE_LABEL_REGISTRY
    .itertuples(
        index=False
    )
):
    label_name = str(
        registry_record.label_name
    )

    availability_flag_column = (
        registry_record.availability_flag_column
    )

    observed_missing = (
        PRIMARY_BATCH_FUTURE_LABELS[
            label_name
        ]
        .isna()
        .to_numpy(
            dtype=bool
        )
    )

    if pd.isna(
        availability_flag_column
    ) or availability_flag_column is None:
        expected_missing = np.zeros(
            row_count,
            dtype=bool,
        )

    else:
        availability = (
            PRIMARY_BATCH_FUTURE_LABELS[
                str(
                    availability_flag_column
                )
            ]
            .astype("boolean")
            .fillna(False)
            .to_numpy(
                dtype=bool
            )
        )

        expected_missing = (
            ~availability
        )

    unexpected_missing = (
        observed_missing
        & ~expected_missing
    )

    unexpected_nonmissing = (
        ~observed_missing
        & expected_missing
    )

    series = (
        PRIMARY_BATCH_FUTURE_LABELS[
            label_name
        ]
    )

    if (
        pd.api.types.is_numeric_dtype(
            series.dtype
        )
        or pd.api.types.is_bool_dtype(
            series.dtype
        )
    ):
        numeric = pd.to_numeric(
            series,
            errors="coerce",
        ).to_numpy(
            dtype="float64",
            na_value=np.nan,
        )

        infinite_count = int(
            np.isinf(
                numeric
            ).sum()
        )

    else:
        infinite_count = 0

    future_label_missingness_rows.append(
        {
            "label_name": label_name,
            "horizon_name": (
                registry_record.horizon_name
            ),
            "availability_class": (
                registry_record.availability_class
            ),
            "observed_missing_count": int(
                observed_missing.sum()
            ),
            "expected_missing_count": int(
                expected_missing.sum()
            ),
            "unexpected_missing_count": int(
                unexpected_missing.sum()
            ),
            "unexpected_nonmissing_count": int(
                unexpected_nonmissing.sum()
            ),
            "infinite_count": infinite_count,
            "status": (
                "PASS"
                if (
                    unexpected_missing.sum()
                    == 0
                    and unexpected_nonmissing.sum()
                    == 0
                    and infinite_count
                    == 0
                )
                else "FAIL"
            ),
        }
    )


FUTURE_LABEL_MISSINGNESS_AUDIT = (
    pd.DataFrame.from_records(
        future_label_missingness_rows
    )
)

future_label_unexpected_missing_count = int(
    FUTURE_LABEL_MISSINGNESS_AUDIT[
        "unexpected_missing_count"
    ].sum()
)

future_label_unexpected_nonmissing_count = int(
    FUTURE_LABEL_MISSINGNESS_AUDIT[
        "unexpected_nonmissing_count"
    ].sum()
)

future_label_infinite_count = int(
    FUTURE_LABEL_MISSINGNESS_AUDIT[
        "infinite_count"
    ].sum()
)

require(
    future_label_unexpected_missing_count
    == 0,
    (
        "At least one future-label field contains an "
        "undeclared missing value."
    ),
)

require(
    future_label_unexpected_nonmissing_count
    == 0,
    (
        "At least one future-label field is populated beyond "
        "its declared availability boundary."
    ),
)

require(
    future_label_infinite_count
    == 0,
    "At least one future-label field contains infinity.",
)


# ------------------------------------------------------------
# Strict temporal and partition audit
# ------------------------------------------------------------

temporal_audit_rows = []

for horizon_record in (
    FUTURE_LABEL_HORIZON_CONTRACT
    .itertuples(
        index=False
    )
):
    horizon_name = str(
        horizon_record.horizon_name
    )

    prefix = (
        f"label_{horizon_name.lower()}"
    )

    target_column = (
        f"{prefix}_target_time_ns"
    )

    state_available_column = (
        f"{prefix}_future_state_available_flag"
    )

    observation_time_column = (
        f"{prefix}_future_observation_time_ns"
    )

    observation_batch_number_column = (
        f"{prefix}_future_observation_batch_number"
    )

    target_values = pd.to_numeric(
        PRIMARY_BATCH_FUTURE_LABELS[
            target_column
        ],
        errors="raise",
    ).to_numpy(
        dtype="int64"
    )

    state_available_values = (
        PRIMARY_BATCH_FUTURE_LABELS[
            state_available_column
        ]
        .astype("boolean")
        .to_numpy(
            dtype=bool
        )
    )

    observation_time_values = pd.to_numeric(
        PRIMARY_BATCH_FUTURE_LABELS[
            observation_time_column
        ],
        errors="coerce",
    ).to_numpy(
        dtype="float64"
    )

    observation_batch_numbers = pd.to_numeric(
        PRIMARY_BATCH_FUTURE_LABELS[
            observation_batch_number_column
        ],
        errors="coerce",
    ).to_numpy(
        dtype="float64"
    )

    target_not_future_count = int(
        (
            target_values
            <= batch_times
        ).sum()
    )

    observation_before_target_count = int(
        (
            state_available_values
            & (
                observation_time_values
                < target_values
            )
        ).sum()
    )

    observation_not_after_source_batch_count = int(
        (
            state_available_values
            & (
                observation_batch_numbers
                <= batch_numbers
            )
        ).sum()
    )

    future_partition_lookup = (
        PRIMARY_BATCH_FUTURE_LABELS[
            [
                "primary_event_batch_number",
                "event_partition",
            ]
        ]
        .rename(
            columns={
                "primary_event_batch_number": (
                    observation_batch_number_column
                ),
                "event_partition": (
                    "_future_event_partition"
                ),
            }
        )
    )

    partition_check = (
        PRIMARY_BATCH_FUTURE_LABELS[
            [
                "event_partition",
                observation_batch_number_column,
                state_available_column,
            ]
        ]
        .merge(
            future_partition_lookup,
            how="left",
            on=(
                observation_batch_number_column
            ),
            validate="many_to_one",
        )
    )

    cross_partition_state_count = int(
        (
            partition_check[
                state_available_column
            ]
            .astype("boolean")
            .fillna(False)
            & ~partition_check[
                "event_partition"
            ]
            .astype("string")
            .eq(
                partition_check[
                    "_future_event_partition"
                ]
                .astype("string")
            )
        ).sum()
    )

    temporal_audit_rows.append(
        {
            "horizon_name": horizon_name,
            "horizon_ns": int(
                horizon_record.horizon_ns
            ),
            "target_not_strictly_future_count": (
                target_not_future_count
            ),
            "observation_before_target_count": (
                observation_before_target_count
            ),
            (
                "observation_not_after_source_"
                "batch_count"
            ): (
                observation_not_after_source_batch_count
            ),
            "cross_partition_state_count": (
                cross_partition_state_count
            ),
            "status": (
                "PASS"
                if (
                    target_not_future_count
                    == 0
                    and observation_before_target_count
                    == 0
                    and observation_not_after_source_batch_count
                    == 0
                    and cross_partition_state_count
                    == 0
                )
                else "FAIL"
            ),
        }
    )


FUTURE_LABEL_TEMPORAL_AUDIT = (
    pd.DataFrame.from_records(
        temporal_audit_rows
    )
)

require(
    FUTURE_LABEL_TEMPORAL_AUDIT[
        "status"
    ]
    .eq("PASS")
    .all(),
    "A future-label temporal or partition gate failed.",
)


# ------------------------------------------------------------
# Nested-horizon flow audit
# ------------------------------------------------------------

nested_horizon_rows = []

ordered_horizons = (
    FUTURE_LABEL_HORIZON_CONTRACT[
        [
            "horizon_name",
            "horizon_ns",
        ]
    ]
    .sort_values(
        "horizon_ns",
        kind="stable",
    )
    .reset_index(drop=True)
)

monotone_flow_suffixes = (
    "future_buy_event_count",
    "future_sell_event_count",
    "future_total_event_count",
    "future_batch_count",
    "future_print_count",
    "future_quantity",
    "future_notional",
    "future_simultaneous_batch_count",
    "future_mixed_side_batch_count",
    "future_midpoint_realized_variance_bps2",
)

for smaller_index in range(
    len(
        ordered_horizons
    )
    - 1
):
    smaller_name = str(
        ordered_horizons.loc[
            smaller_index,
            "horizon_name",
        ]
    )

    larger_name = str(
        ordered_horizons.loc[
            smaller_index + 1,
            "horizon_name",
        ]
    )

    smaller_prefix = (
        f"label_{smaller_name.lower()}"
    )

    larger_prefix = (
        f"label_{larger_name.lower()}"
    )

    smaller_valid = (
        PRIMARY_BATCH_FUTURE_LABELS[
            (
                f"{smaller_prefix}_"
                "future_flow_window_valid_flag"
            )
        ]
        .astype("boolean")
        .to_numpy(
            dtype=bool
        )
    )

    larger_valid = (
        PRIMARY_BATCH_FUTURE_LABELS[
            (
                f"{larger_prefix}_"
                "future_flow_window_valid_flag"
            )
        ]
        .astype("boolean")
        .to_numpy(
            dtype=bool
        )
    )

    larger_valid_without_smaller_count = int(
        (
            larger_valid
            & ~smaller_valid
        ).sum()
    )

    require(
        larger_valid_without_smaller_count
        == 0,
        (
            "A larger forward horizon is valid where the "
            "adjacent smaller horizon is censored."
        ),
    )

    pair_valid = (
        smaller_valid
        & larger_valid
    )

    for suffix in monotone_flow_suffixes:
        smaller_column = (
            f"{smaller_prefix}_{suffix}"
        )

        larger_column = (
            f"{larger_prefix}_{suffix}"
        )

        smaller_values = pd.to_numeric(
            PRIMARY_BATCH_FUTURE_LABELS[
                smaller_column
            ],
            errors="coerce",
        ).to_numpy(
            dtype="float64"
        )

        larger_values = pd.to_numeric(
            PRIMARY_BATCH_FUTURE_LABELS[
                larger_column
            ],
            errors="coerce",
        ).to_numpy(
            dtype="float64"
        )

        failure_count = int(
            (
                pair_valid
                & (
                    smaller_values
                    > larger_values
                    + 1e-10
                )
            ).sum()
        )

        nested_horizon_rows.append(
            {
                "metric": suffix,
                "smaller_horizon": (
                    smaller_name
                ),
                "larger_horizon": (
                    larger_name
                ),
                "compared_rows": int(
                    pair_valid.sum()
                ),
                "failure_count": (
                    failure_count
                ),
                "status": (
                    "PASS"
                    if failure_count
                    == 0
                    else "FAIL"
                ),
            }
        )


FUTURE_LABEL_NESTED_HORIZON_AUDIT = (
    pd.DataFrame.from_records(
        nested_horizon_rows
    )
)

require(
    FUTURE_LABEL_NESTED_HORIZON_AUDIT[
        "status"
    ]
    .eq("PASS")
    .all(),
    (
        "At least one larger future-flow horizon contains "
        "less cumulative flow than a smaller horizon."
    ),
)


# ------------------------------------------------------------
# Physical-separation and leakage audit
# ------------------------------------------------------------

feature_payload_columns = set(
    PRIMARY_BATCH_MARKET_STATE_FEATURES.columns
) - set(
    FINAL_MARKET_STATE_IDENTITY_COLUMNS
)

label_payload_columns = set(
    PRIMARY_BATCH_FUTURE_LABELS.columns
) - set(
    FINAL_MARKET_STATE_IDENTITY_COLUMNS
)

feature_label_payload_overlap = sorted(
    feature_payload_columns
    & label_payload_columns
)

future_like_columns_in_feature_table = sorted(
    column_name
    for column_name in (
        PRIMARY_BATCH_MARKET_STATE_FEATURES.columns
    )
    if (
        column_name.startswith("label_")
        or column_name.startswith("future_")
        or "_future_" in column_name
        or column_name.startswith("target_")
    )
)

tminus_columns_in_label_payload = sorted(
    column_name
    for column_name in (
        label_payload_columns
    )
    if column_name.startswith(
        "tminus_"
    )
)

tplus_columns_in_label_payload = sorted(
    column_name
    for column_name in (
        label_payload_columns
    )
    if column_name.startswith(
        "tplus_"
    )
)

require(
    not feature_label_payload_overlap,
    (
        "Feature and future-label payloads overlap: "
        f"{feature_label_payload_overlap}"
    ),
)

require(
    not future_like_columns_in_feature_table,
    (
        "The T-minus feature table contains future-label "
        f"columns: {future_like_columns_in_feature_table}"
    ),
)

require(
    not tminus_columns_in_label_payload,
    (
        "The future-label payload contains T-minus columns: "
        f"{tminus_columns_in_label_payload}"
    ),
)

require(
    not tplus_columns_in_label_payload,
    (
        "The future-label payload contains T-plus columns: "
        f"{tplus_columns_in_label_payload}"
    ),
)


# ------------------------------------------------------------
# Partition and horizon summary
# ------------------------------------------------------------

FUTURE_LABEL_PARTITION_AUDIT = (
    pd.DataFrame.from_records(
        future_label_partition_audit_rows
    )
    .sort_values(
        [
            "horizon_ns",
            "event_partition_order",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

FUTURE_LABEL_HORIZON_SUMMARY = (
    FUTURE_LABEL_PARTITION_AUDIT.groupby(
        [
            "horizon_name",
            "horizon_ns",
        ],
        observed=True,
        sort=True,
        dropna=False,
    )
    .agg(
        batch_count=(
            "batch_count",
            "sum",
        ),
        partition_boundary_valid_count=(
            "partition_boundary_valid_count",
            "sum",
        ),
        partition_boundary_censored_count=(
            "partition_boundary_censored_count",
            "sum",
        ),
        future_state_available_count=(
            "future_state_available_count",
            "sum",
        ),
        future_state_unavailable_count=(
            "future_state_unavailable_count",
            "sum",
        ),
        maximum_future_observation_delay_ns=(
            "maximum_future_observation_delay_ns",
            "max",
        ),
    )
    .reset_index()
)

FUTURE_LABEL_HORIZON_SUMMARY[
    "future_state_available_fraction"
] = (
    FUTURE_LABEL_HORIZON_SUMMARY[
        "future_state_available_count"
    ]
    / FUTURE_LABEL_HORIZON_SUMMARY[
        "batch_count"
    ]
)

FUTURE_LABEL_HORIZON_SUMMARY[
    "status"
] = "PASS"


# ------------------------------------------------------------
# Final label gates
# ------------------------------------------------------------

partition_boundary_censored_count = int(
    FUTURE_LABEL_PARTITION_AUDIT[
        "partition_boundary_censored_count"
    ].sum()
)

future_state_unavailable_count = int(
    FUTURE_LABEL_PARTITION_AUDIT[
        "future_state_unavailable_count"
    ].sum()
)

microprice_weighted_midpoint_authority_used = (
    MICROPRICE_SOURCE_COLUMN
    == "tminus_book_weighted_midpoint"
)

FUTURE_LABEL_GATES = pd.DataFrame(
    [
        {
            "gate": (
                "market_state_feature_authority_verified"
            ),
            "severity": "BLOCKING",
            "passed": (
                MARKET_STATE_FEATURES_VERIFIED
            ),
            "evidence": (
                f"feature_rows="
                f"{len(PRIMARY_BATCH_MARKET_STATE_FEATURES)}"
            ),
        },
        {
            "gate": (
                "label_state_sources_resolved"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                f"midpoint={MIDPOINT_SOURCE_COLUMN}; "
                f"microprice={MICROPRICE_SOURCE_COLUMN}; "
                f"spread={SPREAD_SOURCE_COLUMN}"
            ),
        },
        {
            "gate": (
                "canonical_batch_identity_conserved"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    PRIMARY_BATCH_FUTURE_LABELS
                )
                == EXPECTED_PRIMARY_BATCH_ROWS
            ),
            "evidence": (
                f"rows="
                f"{len(PRIMARY_BATCH_FUTURE_LABELS)}"
            ),
        },
        {
            "gate": (
                "future_targets_strictly_after_source"
            ),
            "severity": "BLOCKING",
            "passed": (
                FUTURE_LABEL_TEMPORAL_AUDIT[
                    "target_not_strictly_future_count"
                ]
                .eq(0)
                .all()
            ),
            "evidence": (
                "all target times satisfy t+h > t"
            ),
        },
        {
            "gate": (
                "future_state_observation_not_before_target"
            ),
            "severity": "BLOCKING",
            "passed": (
                FUTURE_LABEL_TEMPORAL_AUDIT[
                    "observation_before_target_count"
                ]
                .eq(0)
                .all()
            ),
            "evidence": (
                FUTURE_LABEL_STATE_OBSERVATION_RULE
            ),
        },
        {
            "gate": (
                "future_observation_after_source_batch"
            ),
            "severity": "BLOCKING",
            "passed": (
                FUTURE_LABEL_TEMPORAL_AUDIT[
                    (
                        "observation_not_after_source_"
                        "batch_count"
                    )
                ]
                .eq(0)
                .all()
            ),
            "evidence": (
                "future batch number > source batch number"
            ),
        },
        {
            "gate": (
                "no_cross_partition_future_state"
            ),
            "severity": "BLOCKING",
            "passed": (
                FUTURE_LABEL_TEMPORAL_AUDIT[
                    "cross_partition_state_count"
                ]
                .eq(0)
                .all()
            ),
            "evidence": (
                FUTURE_LABEL_PARTITION_RULE
            ),
        },
        {
            "gate": (
                "current_batch_excluded_from_future_flow"
            ),
            "severity": "BLOCKING",
            "passed": True,
            "evidence": (
                FUTURE_LABEL_FLOW_INTERVAL_RULE
            ),
        },
        {
            "gate": (
                "nested_future_flow_horizons"
            ),
            "severity": "BLOCKING",
            "passed": (
                FUTURE_LABEL_NESTED_HORIZON_AUDIT[
                    "failure_count"
                ]
                .eq(0)
                .all()
            ),
            "evidence": (
                f"comparisons="
                f"{len(FUTURE_LABEL_NESTED_HORIZON_AUDIT)}"
            ),
        },
        {
            "gate": (
                "future_label_missingness_declared"
            ),
            "severity": "BLOCKING",
            "passed": (
                future_label_unexpected_missing_count
                == 0
                and future_label_unexpected_nonmissing_count
                == 0
            ),
            "evidence": (
                f"unexpected_missing="
                f"{future_label_unexpected_missing_count}; "
                f"unexpected_nonmissing="
                f"{future_label_unexpected_nonmissing_count}"
            ),
        },
        {
            "gate": (
                "future_label_values_finite"
            ),
            "severity": "BLOCKING",
            "passed": (
                future_label_infinite_count
                == 0
            ),
            "evidence": (
                f"infinite_values="
                f"{future_label_infinite_count}"
            ),
        },
        {
            "gate": (
                "future_labels_physically_separate"
            ),
            "severity": "BLOCKING",
            "passed": (
                len(
                    feature_label_payload_overlap
                )
                == 0
                and len(
                    future_like_columns_in_feature_table
                )
                == 0
            ),
            "evidence": (
                "feature and label tables share identity "
                "columns only"
            ),
        },
        {
            "gate": (
                "partition_boundary_censoring_present"
            ),
            "severity": "WARNING",
            "passed": (
                partition_boundary_censored_count
                == 0
            ),
            "evidence": (
                f"censored_label_windows="
                f"{partition_boundary_censored_count}"
            ),
        },
        {
            "gate": (
                "future_state_right_censoring_present"
            ),
            "severity": "WARNING",
            "passed": (
                future_state_unavailable_count
                == 0
            ),
            "evidence": (
                f"unavailable_state_observations="
                f"{future_state_unavailable_count}"
            ),
        },
        {
            "gate": (
                "overlapping_forward_windows_acknowledged"
            ),
            "severity": "WARNING",
            "passed": False,
            "evidence": (
                FUTURE_LABEL_OVERLAP_POLICY
            ),
        },
        {
            "gate": (
                "weighted_midpoint_microprice_authority"
            ),
            "severity": "WARNING",
            "passed": (
                not microprice_weighted_midpoint_authority_used
            ),
            "evidence": (
                (
                    "tminus_book_weighted_midpoint is the "
                    "verified microprice authority"
                )
                if microprice_weighted_midpoint_authority_used
                else (
                    "direct tminus_book_microprice column "
                    "available"
                )
            ),
        },
    ]
)

FUTURE_LABEL_GATES[
    "status"
] = np.select(
    [
        FUTURE_LABEL_GATES[
            "passed"
        ],
        FUTURE_LABEL_GATES[
            "severity"
        ].eq("BLOCKING"),
    ],
    [
        "PASS",
        "FAIL",
    ],
    default="WARNING",
)

future_label_blocking_failures = (
    FUTURE_LABEL_GATES.loc[
        FUTURE_LABEL_GATES[
            "severity"
        ].eq("BLOCKING")
        & ~FUTURE_LABEL_GATES[
            "passed"
        ]
    ]
)

require(
    future_label_blocking_failures.empty,
    "Future-label construction contains a blocking failure.",
)


# ------------------------------------------------------------
# Frozen downstream aliases
# ------------------------------------------------------------

BATCH_FUTURE_LABELS = (
    PRIMARY_BATCH_FUTURE_LABELS
)

MARKET_STATE_FUTURE_LABELS = (
    PRIMARY_BATCH_FUTURE_LABELS
)

FUTURE_LABELS_CONSTRUCTED = True
FUTURE_LABELS_VERIFIED = True

FUTURE_LABEL_ROW_COUNT = int(
    len(
        PRIMARY_BATCH_FUTURE_LABELS
    )
)

FUTURE_LABEL_COLUMN_COUNT = int(
    len(
        FUTURE_LABEL_COLUMNS
    )
)

FUTURE_LABEL_HORIZON_COUNT = int(
    len(
        FUTURE_LABEL_HORIZON_CONTRACT
    )
)


# ------------------------------------------------------------
# Compact displays
# ------------------------------------------------------------

display(
    LABEL_STATE_SOURCE_RESOLUTION_AUDIT
)

display(
    FUTURE_LABEL_HORIZON_CONTRACT
)

display(
    FUTURE_LABEL_HORIZON_SUMMARY
)

display(
    FUTURE_LABEL_TEMPORAL_AUDIT
)

display(
    FUTURE_LABEL_NESTED_HORIZON_AUDIT
)

display(
    FUTURE_LABEL_MISSINGNESS_AUDIT.loc[
        FUTURE_LABEL_MISSINGNESS_AUDIT[
            "observed_missing_count"
        ].gt(0)
    ].head(
        100
    )
)

display(
    PRIMARY_BATCH_FUTURE_LABELS.head(
        10
    )
)

display(
    FUTURE_LABEL_GATES[
        [
            "gate",
            "severity",
            "status",
            "evidence",
        ]
    ]
)

{
    "status": "PASS",
    "future_labels_constructed": (
        FUTURE_LABELS_CONSTRUCTED
    ),
    "future_labels_verified": (
        FUTURE_LABELS_VERIFIED
    ),
    "observational_unit": (
        FUTURE_LABEL_OBSERVATIONAL_UNIT
    ),
    "timing_class": (
        FUTURE_LABEL_TIMING_CLASS
    ),
    "physical_table_role": (
        FUTURE_LABEL_PHYSICAL_TABLE_ROLE
    ),
    "state_observation_rule": (
        FUTURE_LABEL_STATE_OBSERVATION_RULE
    ),
    "future_flow_interval": (
        FUTURE_LABEL_FLOW_INTERVAL_RULE
    ),
    "partition_rule": (
        FUTURE_LABEL_PARTITION_RULE
    ),
    "overlap_policy": (
        FUTURE_LABEL_OVERLAP_POLICY
    ),
    "batch_rows": (
        FUTURE_LABEL_ROW_COUNT
    ),
    "label_column_count": (
        FUTURE_LABEL_COLUMN_COUNT
    ),
    "horizon_count": (
        FUTURE_LABEL_HORIZON_COUNT
    ),
    "horizons_ns": (
        FUTURE_LABEL_HORIZON_CONTRACT
        .set_index(
            "horizon_name"
        )[
            "horizon_ns"
        ]
        .astype("int64")
        .to_dict()
    ),
    "midpoint_source_column": (
        MIDPOINT_SOURCE_COLUMN
    ),
    "microprice_source_column": (
        MICROPRICE_SOURCE_COLUMN
    ),
    "spread_source_column": (
        SPREAD_SOURCE_COLUMN
    ),
    "authoritative_tick_size": (
        AUTHORITATIVE_LABEL_TICK_SIZE
    ),
    "partition_boundary_censored_windows": (
        partition_boundary_censored_count
    ),
    "future_state_unavailable_observations": (
        future_state_unavailable_count
    ),
    "unexpected_missing_values": (
        future_label_unexpected_missing_count
    ),
    "unexpected_nonmissing_values": (
        future_label_unexpected_nonmissing_count
    ),
    "infinite_label_values": (
        future_label_infinite_count
    ),
    "current_batch_included": False,
    "cross_partition_labels_allowed": False,
    "labels_attached_to_feature_table": False,
    "verified_at_utc": utc_now_iso(),
}

  semantic_field                selected_column               matching_columns                 resolution_status
0       MIDPOINT           tminus_book_midpoint           tminus_book_midpoint                              PASS
1     MICROPRICE  tminus_book_weighted_midpoint  tminus_book_weighted_midpoint  PASS_WEIGHTED_MIDPOINT_AUTHORITY
2         SPREAD             tminus_book_spread             tminus_book_spread                              PASS
3      TICK_SIZE  tminus_book_implied_tick_size  tminus_book_implied_tick_size                              PASS

,horizon_name,source_window_name,horizon_ns,horizon_seconds,timing_class,physical_table_role,state_observation_rule,future_flow_interval,current_batch_included,cross_partition_allowed,overlapping_forward_windows,horizon_selection_authority
0,H250MS,W250MS,250000000,0.25,FUTURE_LABEL,SEPARATE_FUTURE_LABEL,FIRST_SAME_PARTITION_SCORING_BATCH_AT_OR_AFTER_TARGET_TIME,"(t, t+h]",False,False,True,ROLLING_WINDOW_CONTRACT
1,H1S,W1S,1000000000,1.00,FUTURE_LABEL,SEPARATE_FUTURE_LABEL,FIRST_SAME_PARTITION_SCORING_BATCH_AT_OR_AFTER_TARGET_TIME,"(t, t+h]",False,False,True,ROLLING_WINDOW_CONTRACT
2,H5S,W5S,5000000000,5.00,FUTURE_LABEL,SEPARATE_FUTURE_LABEL,FIRST_SAME_PARTITION_SCORING_BATCH_AT_OR_AFTER_TARGET_TIME,"(t, t+h]",False,False,True,ROLLING_WINDOW_CONTRACT
3,H30S,W30S,30000000000,30.00,FUTURE_LABEL,SEPARATE_FUTURE_LABEL,FIRST_SAME_PARTITION_SCORING_BATCH_AT_OR_AFTER_TARGET_TIME,"(t, t+h]",False,False,True,ROLLING_WINDOW_CONTRACT

,horizon_name,horizon_ns,batch_count,partition_boundary_valid_count,partition_boundary_censored_count,future_state_available_count,future_state_unavailable_count,maximum_future_observation_delay_ns,future_state_available_fraction,status
0,H1S,1000000000,13564,13548,16,13541,23,3028960100,0.998304,PASS
1,H250MS,250000000,13564,13560,4,13559,5,3103633900,0.999631,PASS
2,H30S,30000000000,13564,12967,597,12957,607,3046927500,0.955249,PASS
3,H5S,5000000000,13564,13497,67,13491,73,2662920100,0.994618,PASS

  horizon_name   horizon_ns  target_not_strictly_future_count  observation_before_target_count  observation_not_after_source_batch_count  cross_partition_state_count status
0       H250MS    250000000                                 0                                0                                         0                            0   PASS
1          H1S   1000000000                                 0                                0                                         0                            0   PASS
2          H5S   5000000000                                 0                                0                                         0                            0   PASS
3         H30S  30000000000                                 0                                0                                         0                            0   PASS

                                    metric smaller_horizon larger_horizon  compared_rows  failure_count status
0                   future_buy_event_count          H250MS            H1S          13548              0   PASS
1                  future_sell_event_count          H250MS            H1S          13548              0   PASS
2                 future_total_event_count          H250MS            H1S          13548              0   PASS
3                       future_batch_count          H250MS            H1S          13548              0   PASS
4                       future_print_count          H250MS            H1S          13548              0   PASS
5                          future_quantity          H250MS            H1S          13548              0   PASS
6                          future_notional          H250MS            H1S          13548              0   PASS
7          future_simultaneous_batch_count          H250MS            H1S          13548              0   PASS
8            future_mixed_side_batch_count          H250MS            H1S          13548              0   PASS
9   future_midpoint_realized_variance_bps2          H250MS            H1S          13548              0   PASS
10                  future_buy_event_count             H1S            H5S          13497              0   PASS
11                 future_sell_event_count             H1S            H5S          13497              0   PASS
12                future_total_event_count             H1S            H5S          13497              0   PASS
13                      future_batch_count             H1S            H5S          13497              0   PASS
14                      future_print_count             H1S            H5S          13497              0   PASS
15                         future_quantity             H1S            H5S          13497              0   PASS
16                         future_notional             H1S            H5S          13497              0   PASS
17         future_simultaneous_batch_count             H1S            H5S          13497              0   PASS
18           future_mixed_side_batch_count             H1S            H5S          13497              0   PASS
19  future_midpoint_realized_variance_bps2             H1S            H5S          13497              0   PASS
20                  future_buy_event_count             H5S           H30S          12967              0   PASS
21                 future_sell_event_count             H5S           H30S          12967              0   PASS
22                future_total_event_count             H5S           H30S          12967              0   PASS
23                      future_batch_count             H5S           H30S          12967              0   PASS
24                      future_print_count             H5S           H30S          12967              0   PASS
25                         future_quantity             H5S           H30S          12967              0   PASS
26                         future_notional             H5S           H30S          12967              0   PASS
27         future_simultaneous_batch_count             H5S           H30S          12967              0   PASS
28           future_mixed_side_batch_count             H5S           H30S          12967              0   PASS
29  future_midpoint_realized_variance_bps2             H5S           H30S          12967              0   PASS

                                               label_name horizon_name        availability_class  observed_missing_count  expected_missing_count  unexpected_missing_count  unexpected_nonmissing_count  infinite_count status
3                label_h250ms_future_observation_batch_id       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
4            label_h250ms_future_observation_batch_number       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
5                 label_h250ms_future_observation_time_ns       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
6                label_h250ms_future_observation_delay_ns       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
7                            label_h250ms_future_midpoint       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
8                     label_h250ms_future_midpoint_change       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
9                 label_h250ms_future_midpoint_change_bps       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
10            label_h250ms_future_midpoint_direction_code       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
11                   label_h250ms_future_midpoint_up_flag       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
12                 label_h250ms_future_midpoint_down_flag       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
13                 label_h250ms_future_midpoint_flat_flag       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
14                         label_h250ms_future_microprice       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
15                  label_h250ms_future_microprice_change       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
16              label_h250ms_future_microprice_change_bps       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
17          label_h250ms_future_microprice_direction_code       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
18                             label_h250ms_future_spread       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
19                      label_h250ms_future_spread_change       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
20               label_h250ms_future_spread_widening_flag       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
21              label_h250ms_future_spread_narrowing_flag       H250MS  FUTURE_STATE_OBSERVATION                       5                       5                         0                            0               0   PASS
23                    label_h250ms_future_buy_event_count       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
24                   label_h250ms_future_sell_event_count       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
25                  label_h250ms_future_total_event_count       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
26                 label_h250ms_future_signed_event_count       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
27                        label_h250ms_future_batch_count       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
28                        label_h250ms_future_print_count       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
29                           label_h250ms_future_quantity       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
30                           label_h250ms_future_notional       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
31           label_h250ms_future_simultaneous_batch_count       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
32             label_h250ms_future_mixed_side_batch_count       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
33    label_h250ms_future_midpoint_realized_variance_bps2       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
34   label_h250ms_future_midpoint_realized_volatility_bps       H250MS        FUTURE_FLOW_WINDOW                       4                       4                         0                            0               0   PASS
38                  label_h1s_future_observation_batch_id          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
39              label_h1s_future_observation_batch_number          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
40                   label_h1s_future_observation_time_ns          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
41                  label_h1s_future_observation_delay_ns          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
42                              label_h1s_future_midpoint          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
43                       label_h1s_future_midpoint_change          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
44                   label_h1s_future_midpoint_change_bps          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
45               label_h1s_future_midpoint_direction_code          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
46                      label_h1s_future_midpoint_up_flag          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
47                    label_h1s_future_midpoint_down_flag          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
48                    label_h1s_future_midpoint_flat_flag          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
49                            label_h1s_future_microprice          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
50                     label_h1s_future_microprice_change          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
51                 label_h1s_future_microprice_change_bps          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
52             label_h1s_future_microprice_direction_code          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
53                                label_h1s_future_spread          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
54                         label_h1s_future_spread_change          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
55                  label_h1s_future_spread_widening_flag          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
56                 label_h1s_future_spread_narrowing_flag          H1S  FUTURE_STATE_OBSERVATION                      23                      23                         0                            0               0   PASS
58                       label_h1s_future_buy_event_count          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
59                      label_h1s_future_sell_event_count          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
60                     label_h1s_future_total_event_count          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
61                    label_h1s_future_signed_event_count          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
62                           label_h1s_future_batch_count          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
63                           label_h1s_future_print_count          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
64                              label_h1s_future_quantity          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
65                              label_h1s_future_notional          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
66              label_h1s_future_simultaneous_batch_count          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
67                label_h1s_future_mixed_side_batch_count          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
68       label_h1s_future_midpoint_realized_variance_bps2          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
69      label_h1s_future_midpoint_realized_volatility_bps          H1S        FUTURE_FLOW_WINDOW                      16                      16                         0                            0               0   PASS
73                  label_h5s_future_observation_batch_id          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
74              label_h5s_future_observation_batch_number          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
75                   label_h5s_future_observation_time_ns          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
76                  label_h5s_future_observation_delay_ns          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
77                              label_h5s_future_midpoint          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
78                       label_h5s_future_midpoint_change          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
79                   label_h5s_future_midpoint_change_bps          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
80               label_h5s_future_midpoint_direction_code          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
81                      label_h5s_future_midpoint_up_flag          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
82                    label_h5s_future_midpoint_down_flag          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
83                    label_h5s_future_midpoint_flat_flag          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
84                            label_h5s_future_microprice          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
85                     label_h5s_future_microprice_change          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
86                 label_h5s_future_microprice_change_bps          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
87             label_h5s_future_microprice_direction_code          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
88                                label_h5s_future_spread          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
89                         label_h5s_future_spread_change          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
90                  label_h5s_future_spread_widening_flag          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
91                 label_h5s_future_spread_narrowing_flag          H5S  FUTURE_STATE_OBSERVATION                      73                      73                         0                            0               0   PASS
93                       label_h5s_future_buy_event_count          H5S        FUTURE_FLOW_WINDOW                      67                      67                         0                            0               0   PASS
94                      label_h5s_future_sell_event_count          H5S        FUTURE_FLOW_WINDOW                      67                      67                         0                            0               0   PASS
95                     label_h5s_future_total_event_count          H5S        FUTURE_FLOW_WINDOW                      67                      67                         0                            0               0   PASS
96                    label_h5s_future_signed_event_count          H5S        FUTURE_FLOW_WINDOW                      67                      67                         0                            0               0   PASS
97                           label_h5s_future_batch_count          H5S        FUTURE_FLOW_WINDOW                      67                      67                         0                            0               0   PASS
98                           label_h5s_future_print_count          H5S        FUTURE_FLOW_WINDOW                      67                      67                         0                            0               0   PASS
99                              label_h5s_future_quantity          H5S        FUTURE_FLOW_WINDOW                      67                      67                         0                            0               0   PASS

,primary_event_batch_id,primary_event_batch_number,partition_batch_index,event_partition_order,event_partition,event_time_ns,label_h250ms_target_time_ns,label_h250ms_partition_boundary_valid_flag,label_h250ms_future_state_available_flag,label_h250ms_future_observation_batch_id,label_h250ms_future_observation_batch_number,label_h250ms_future_observation_time_ns,label_h250ms_future_observation_delay_ns,label_h250ms_future_midpoint,label_h250ms_future_midpoint_change,label_h250ms_future_midpoint_change_bps,label_h250ms_future_midpoint_direction_code,label_h250ms_future_midpoint_up_flag,label_h250ms_future_midpoint_down_flag,label_h250ms_future_midpoint_flat_flag,label_h250ms_future_microprice,label_h250ms_future_microprice_change,label_h250ms_future_microprice_change_bps,label_h250ms_future_microprice_direction_code,label_h250ms_future_spread,label_h250ms_future_spread_change,label_h250ms_future_spread_widening_flag,label_h250ms_future_spread_narrowing_flag,label_h250ms_future_flow_window_valid_flag,label_h250ms_future_buy_event_count,label_h250ms_future_sell_event_count,label_h250ms_future_total_event_count,label_h250ms_future_signed_event_count,label_h250ms_future_batch_count,label_h250ms_future_print_count,label_h250ms_future_quantity,label_h250ms_future_notional,label_h250ms_future_simultaneous_batch_count,label_h250ms_future_mixed_side_batch_count,label_h250ms_future_midpoint_realized_variance_bps2,label_h250ms_future_midpoint_realized_volatility_bps,label_h1s_target_time_ns,label_h1s_partition_boundary_valid_flag,label_h1s_future_state_available_flag,label_h1s_future_observation_batch_id,label_h1s_future_observation_batch_number,label_h1s_future_observation_time_ns,label_h1s_future_observation_delay_ns,label_h1s_future_midpoint,label_h1s_future_midpoint_change,label_h1s_future_midpoint_change_bps,label_h1s_future_midpoint_direction_code,label_h1s_future_midpoint_up_flag,label_h1s_future_midpoint_down_flag,label_h1s_future_midpoint_flat_flag,label_h1s_future_microprice,label_h1s_future_microprice_change,label_h1s_future_microprice_change_bps,label_h1s_future_microprice_direction_code,label_h1s_future_spread,label_h1s_future_spread_change,label_h1s_future_spread_widening_flag,label_h1s_future_spread_narrowing_flag,label_h1s_future_flow_window_valid_flag,label_h1s_future_buy_event_count,label_h1s_future_sell_event_count,label_h1s_future_total_event_count,label_h1s_future_signed_event_count,label_h1s_future_batch_count,label_h1s_future_print_count,label_h1s_future_quantity,label_h1s_future_notional,label_h1s_future_simultaneous_batch_count,label_h1s_future_mixed_side_batch_count,label_h1s_future_midpoint_realized_variance_bps2,label_h1s_future_midpoint_realized_volatility_bps,label_h5s_target_time_ns,label_h5s_partition_boundary_valid_flag,label_h5s_future_state_available_flag,label_h5s_future_observation_batch_id,label_h5s_future_observation_batch_number,label_h5s_future_observation_time_ns,label_h5s_future_observation_delay_ns,label_h5s_future_midpoint,label_h5s_future_midpoint_change,label_h5s_future_midpoint_change_bps,label_h5s_future_midpoint_direction_code,label_h5s_future_midpoint_up_flag,label_h5s_future_midpoint_down_flag,label_h5s_future_midpoint_flat_flag,label_h5s_future_microprice,label_h5s_future_microprice_change,label_h5s_future_microprice_change_bps,label_h5s_future_microprice_direction_code,label_h5s_future_spread,label_h5s_future_spread_change,label_h5s_future_spread_widening_flag,label_h5s_future_spread_narrowing_flag,label_h5s_future_flow_window_valid_flag,label_h5s_future_buy_event_count,label_h5s_future_sell_event_count,label_h5s_future_total_event_count,label_h5s_future_signed_event_count,label_h5s_future_batch_count,label_h5s_future_print_count,label_h5s_future_quantity,label_h5s_future_notional,label_h5s_future_simultaneous_batch_count,label_h5s_future_mixed_side_batch_count,label_h5s_future_midpoint_realized_variance_bps2,label_h5s_future_midpoint_realized_volatility_bps,label_h30s_target_time_ns,label_h30s_partition_boundary_valid_flag,label_h30s_future_state_available_flag,label_h30s_future_observation_batch_id,label_h30s_future_observation_batch_number,label_h30s_future_observation_time_ns,label_h30s_future_observation_delay_ns,label_h30s_future_midpoint,label_h30s_future_midpoint_change,label_h30s_future_midpoint_change_bps,label_h30s_future_midpoint_direction_code,label_h30s_future_midpoint_up_flag,label_h30s_future_midpoint_down_flag,label_h30s_future_midpoint_flat_flag,label_h30s_future_microprice,label_h30s_future_microprice_change,label_h30s_future_microprice_change_bps,label_h30s_future_microprice_direction_code,label_h30s_future_spread,label_h30s_future_spread_change,label_h30s_future_spread_widening_flag,label_h30s_future_spread_narrowing_flag,label_h30s_future_flow_window_valid_flag,label_h30s_future_buy_event_count,label_h30s_future_sell_event_count,label_h30s_future_total_event_count,label_h30s_future_signed_event_count,label_h30s_future_batch_count,label_h30s_future_print_count,label_h30s_future_quantity,label_h30s_future_notional,label_h30s_future_simultaneous_batch_count,label_h30s_future_mixed_side_batch_count,label_h30s_future_midpoint_realized_variance_bps2,label_h30s_future_midpoint_realized_volatility_bps
0,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000001,1,1,1,DEVELOPMENT,1783665468766951600,1783665469016951600,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000002,2,1783665469052166400,35214900,63914.365,0.0,0.0,0,False,False,True,63914.365993,2.637535e-08,4.126669e-09,1,0.01,0.0,False,False,True,0,0,0,0,0,0,0.00000,0.000000,0,0,0.0,0.0,1783665469766951600,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000005,5,1783665470242312192,475360500,63914.365,0.0,0.0,0,False,False,True,63914.365992,-6.459959e-07,-1.010721e-07,-1,0.01,0.0,False,False,True,3,0,3,3,3,3,0.00119,76.058100,0,0,0.0,0.0,1783665473766951600,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000019,19,1783665473855268864,88317300,63914.365,0.0,0.0,0,False,False,True,63914.366191,0.000199,0.000031,1,0.01,0.0,False,False,True,8,9,17,-1,17,17,0.08679,5547.127349,0,0,0.0,0.0,1783665498766951600,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000134,134,1783665499443819520,676867900,63923.325,8.96,1.401876,1,True,False,False,63923.324511,8.958519,1.401644,1,0.01,0.0,False,False,True,76,62,138,14,132,401,3.04372,194541.206734,3,1,0.992396,0.996191
1,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000002,2,2,1,DEVELOPMENT,1783665469052166500,1783665469302166500,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000003,3,1783665469437964288,135797900,63914.365,0.0,0.0,0,False,False,True,63914.365993,7.912095e-07,1.237921e-07,1,0.01,0.0,False,False,True,0,0,0,0,0,0,0.00000,0.000000,0,0,0.0,0.0,1783665470052166500,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000005,5,1783665470242312192,190145600,63914.365,0.0,0.0,0,False,False,True,63914.365992,-6.723712e-07,-1.051988e-07,-1,0.01,0.0,False,False,True,2,0,2,2,2,2,0.00059,37.709478,0,0,0.0,0.0,1783665474052166500,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000020,20,1783665474632049920,579883300,63914.365,0.0,0.0,0,False,False,True,63914.366191,0.000199,0.000031,1,0.01,0.0,False,False,True,8,9,17,-1,17,17,0.08639,5521.561601,0,0,0.0,0.0,1783665499052166500,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000134,134,1783665499443819520,391653000,63923.325,8.96,1.401876,1,True,False,False,63923.324511,8.958519,1.401644,1,0.01,0.0,False,False,True,75,62,137,13,131,400,3.04312,194502.858112,3,1,0.992396,0.996191
2,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000003,3,3,1,DEVELOPMENT,1783665469437964400,1783665469687964400,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000004,4,1783665469692104192,4139800,63914.365,0.0,0.0,0,False,False,True,63914.365994,2.637898e-07,4.127239e-08,1,0.01,0.0,False,False,True,0,0,0,0,0,0,0.00000,0.000000,0,0,0.0,0.0,1783665470437964400,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000007,7,1783665470597198848,159234400,63914.365,0.0,0.0,0,False,False,True,63914.365993,-6.950359e-07,-1.087449e-07,-1,0.01,0.0,False,False,True,1,2,3,-1,3,3,0.00103,65.831795,0,0,0.0,0.0,1783665474437964400,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000020,20,1783665474632049920,194085400,63914.365,0.0,0.0,0,False,False,True,63914.366191,0.000198,0.000031,1,0.01,0.0,False,False,True,7,9,16,-2,16,16,0.08619,5508.778727,0,0,0.0,0.0,1783665499437964400,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000134,134,1783665499443819520,5855100,63923.325,8.96,1.401876,1,True,False,False,63923.324511,8.958518,1.401644,1,0.01,0.0,False,False,True,74,62,136,12,130,399,3.04292,194490.075238,3,1,0.992396,0.996191
3,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000004,4,4,1,DEVELOPMENT,1783665469692104200,1783665469942104200,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000005,5,1783665470242312192,300207900,63914.365,0.0,0.0,0,False,False,True,63914.365992,-1.727371e-06,-2.702633e-07,-1,0.01,0.0,False,False,True,0,0,0,0,0,0,0.00000,0.000000,0,0,0.0,0.0,1783665470692104200,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,8,1783665471662326528,970222400,63914.365,0.0,0.0,0,False,False,True,63914.365185,-8.091188e-04,-1.265942e-04,-1,0.01,0.0,False,False,True,0,3,3,-3,3,3,0.03559,2274.712072,0,0,0.0,0.0,1783665474692104200,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000021,21,1783665475023106816,331002700,63914.365,0.0,0.0,0,False,False,True,63914.366185,0.000191,0.000030,1,0.01,0.0,False,False,True,6,10,16,-4,16,16,0.09380,5995.167003,0,0,0.0,0.0,1783665499692104200,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000136,136,1783665500397790976,705686700,63923.325,8.96,1.401876,1,True,False,False,63923.324501,8.958507,1.401642,1,0.01,0.0,False,False,True,74,63,137,11,131,400,3.05581,195314.050327,3,1,0.992396,0.996191
4,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000005,5,5,1,DEVELOPMENT,1783665470242312100,1783665470492312100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000007,7,1783665470597198848,104886700,63914.365,0.0,0.0,0,False,False,True,63914.365993,7.685449e-07,1.202460e-07,1,0.01,0.0,False,False,True,0,1,1,-1,1,1,0.00018,11.504585,0,0,0.0,0.0,1783665471242312100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,8,1783665471662326528,420014500,63914.365,0.0,0.0,0,False,False,True,63914.365185,-8.073915e-04,-1.263239e-04,-1,0.01,0.0,False,False,True,0,2,2,-2,2,2,0.03513,2245.311467,0,0,0.0,0.0,1783665475242312100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000023,23,1783665475362078976,119766800,63914.365,0.0,0.0,0,False,False,True,63914.366518,0.000526,0.000082,1,0.01,0.0,False,False,True,8,9,17,-1,17,17,0.09395,6004.754163,0,0,0.0,0.0,1783665500242312100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000136,136,1783665500397790976,155478800,63923.325,8.96,1.401876,1,True,False,False,63923.324501,8.958509,1.401642,1,0.01,0.0,False,False,True,74,62,136,12,130,399,3.05535,195284.649721,3,1,0.992396,0.996191
5,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000006,6,6,1,DEVELOPMENT,1783665470304239100,1783665470554239100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000007,7,1783665470597198848,42959700,63914.365,0.0,0.0,0,False,False,True,63914.365993,7.685449e-07,1.202460e-07,1,0.01,0.0,False,False,True,0,0,0,0,0,0,0.00000,0.000000,0,0,0.0,0.0,1783665471304239100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,8,1783665471662326528,358087500,63914.365,0.0,0.0,0,False,False,True,63914.365185,-8.073915e-04,-1.263239e-04,-1,0.01,0.0,False,False,True,0,1,1,-1,1,1,0.03495,2233.806882,0,0,0.0,0.0,1783665475304239100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000023,23,1783665475362078976,57839800,63914.365,0.0,0.0,0,False,False,True,63914.366518,0.000526,0.000082,1,0.01,0.0,False,False,True,8,8,16,0,16,16,0.09377,5993.249578,0,0,0.0,0.0,1783665500304239100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000136,136,1783665500397790976,93551800,63923.325,8.96,1.401876,1,True,False,False,63923.324501,8.958509,1.401642,1,0.01,0.0,False,False,True,74,61,135,13,129,398,3.05517,195273.145136,3,1,0.992396,0.996191
6,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000007,7,7,1,DEVELOPMENT,1783665470597198800,1783665470847198800,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,8,1783665471662326528,815127800,63914.365,0.0,0.0,0,False,False,True,63914.365185,-8.081600e-04,-1.264442e-04,-1,0.01,0.0,False,False,True,0,0,0,0,0,0,0.00000,0.000000,0,0,0.0,0.0,1783665471597198800,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,8,1783665471662326528,65127800,63914.365,0.0,0.0,0,False,False,True,63914.365185,-8.081600e-04,-1.264442e-04,-1,0.01,0.0,False,False,True,0,0,0,0,0,0,0.00000,0.000000,0,0,0.0,0.0,1783665475597198800,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000024,24,1783665475951983872,354785000,63914.365,0.0,0.0,0,False,False,True,63914.366315,0.000322,0.000050,1,0.01,0.0,False,False,True,9,7,16,2,16,16,0.05927,3788.204163,0,0,0.0,0.0,1783665500597198800,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000137,137,1783665501753251328,1156052400,63923.325,8.96,1.401876,1,True,False,False,63923.322942,8.956949,1.401398,1,0.01,0.0,False,False,True,74,61,135,13,129,398,3.02042,193052.122918,3,1,0.992396,0.996191
7,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000008,8,8,1,DEVELOPMENT,1783665471662326600,1783665471912326600,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000011,11,1783665472192276480,279949800,63914.365,0.0,0.0,0,False,False,True,63914.365181,-3.292924e-06,-5.152087e-07,-1,0.01,0.0,False,False,True,1,1,2,0,2,2,0.00066,42.183482,0,0,0.0,0.0,1783665472662326600,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000014,14,1783665473022153728,359827000,63914.365,0.0,0.0,0,False,False,True,63914.365147,-3.766165e-05,-5.892518e-06,-1,0.01,0.0,False,False,True,3,2,5,1,5,5,0.04093,2616.014770,0,0,0.0,0.0,1783665476662326600,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000027,27,1783665476752040960,89714300,63914.365,0.0,0.0,0,False,False,True,63914.365934,0.000749,0.000117,1,0.01,0.0,False,False,True,10,8,18,2,18,18,0.13669,8736.453918,0,0,0.0,0.0,1783665501662326600,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000137,137,1783665501753251328,90924600,63923.325,8.96,1.401876,1,True,False,False,63923.322942,8.957757,1.401525,1,0.01,0.0,False,False,True,74,60,134,14,128,397,3.01986,193016.330877,3,1,0.992396,0.996191
8,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000009,9,9,1,DEVELOPMENT,1783665471742062100,1783665471992062100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000011,11,1783665472192276480,200214300,63914.365,0.0,0.0,0,False,False,True,63914.365181,-2.790890e-06,-4.366608e-07,-1,0.01,0.0,False,False,True,1,0,1,1,1,1,0.00046,29.400610,0,0,0.0,0.0,1783665472742062100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000014,14,1783665473022153728,280091500,63914.365,0.0,0.0,0,False,False,True,63914.365147,-3.715962e-05,-5.813970e-06,-1,0.01,0.0,False,False,True,3,1,4,2,4,4,0.04073,2603.231898,0,0,0.0,0.0,1783665476742062100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000027,27,1783665476752040960,9978800,63914.365,0.0,0.0,0,False,False,True,63914.365934,0.000750,0.000117,1,0.01,0.0,False,False,True,10,7,17,3,17,17,0.13649,8723.671046,0,0,0.0,0.0,1783665501742062100,True,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION__PRIMARY_BATCH__00000137,137,1783665501753251328,11189100,63923.325,8.96,1.401876,1,True,False,False,63923.322942,8.957758,1.401525,1,0.01,0.0,False,False,True,74,59,133,15,127,396,3.01966,193003.548005,3,1,0.992396,0.996191

                                          gate  severity   status                                                                                            evidence
0      market_state_feature_authority_verified  BLOCKING     PASS                                                                                  feature_rows=13564
1                 label_state_sources_resolved  BLOCKING     PASS  midpoint=tminus_book_midpoint; microprice=tminus_book_weighted_midpoint; spread=tminus_book_spread
2           canonical_batch_identity_conserved  BLOCKING     PASS                                                                                          rows=13564
3         future_targets_strictly_after_source  BLOCKING     PASS                                                                    all target times satisfy t+h > t
4   future_state_observation_not_before_target  BLOCKING     PASS                                          FIRST_SAME_PARTITION_SCORING_BATCH_AT_OR_AFTER_TARGET_TIME
5        future_observation_after_source_batch  BLOCKING     PASS                                                           future batch number > source batch number
6              no_cross_partition_future_state  BLOCKING     PASS                                                 NO_LABEL_MAY_CROSS_A_NOTEBOOK_00_PARTITION_BOUNDARY
7      current_batch_excluded_from_future_flow  BLOCKING     PASS                                                                                            (t, t+h]
8                  nested_future_flow_horizons  BLOCKING     PASS                                                                                      comparisons=30
9            future_label_missingness_declared  BLOCKING     PASS                                                       unexpected_missing=0; unexpected_nonmissing=0
10                  future_label_values_finite  BLOCKING     PASS                                                                                   infinite_values=0
11           future_labels_physically_separate  BLOCKING     PASS                                                feature and label tables share identity columns only
12        partition_boundary_censoring_present   WARNING  WARNING                                                                          censored_label_windows=684
13        future_state_right_censoring_present   WARNING  WARNING                                                                  unavailable_state_observations=708
14    overlapping_forward_windows_acknowledged   WARNING  WARNING                                                            OVERLAPPING_FORWARD_WINDOWS_ACKNOWLEDGED
15      weighted_midpoint_microprice_authority   WARNING  WARNING                                  tminus_book_weighted_midpoint is the verified microprice authority

{'status': 'PASS',
 'future_labels_constructed': True,
 'future_labels_verified': True,
 'observational_unit': 'PRIMARY_SCORING_BATCH',
 'timing_class': 'FUTURE_LABEL',
 'physical_table_role': 'SEPARATE_FUTURE_LABEL',
 'state_observation_rule': 'FIRST_SAME_PARTITION_SCORING_BATCH_AT_OR_AFTER_TARGET_TIME',
 'future_flow_interval': '(t, t+h]',
 'partition_rule': 'NO_LABEL_MAY_CROSS_A_NOTEBOOK_00_PARTITION_BOUNDARY',
 'overlap_policy': 'OVERLAPPING_FORWARD_WINDOWS_ACKNOWLEDGED',
 'batch_rows': 13564,
 'label_column_count': 140,
 'horizon_count': 4,
 'horizons_ns': {'H250MS': 250000000,
  'H1S': 1000000000,
  'H5S': 5000000000,
  'H30S': 30000000000},
 'midpoint_source_column': 'tminus_book_midpoint',
 'microprice_source_column': 'tminus_book_weighted_midpoint',
 'spread_source_column': 'tminus_book_spread',
 'authoritative_tick_size': 0.010000000002037268,
 'partition_boundary_censored_windows': 684,
 'future_state_unavailable_observations': 708,
 'unexpected_missing_values': 0,
 'unexpected_nonmissing_values': 0,
 'infinite_label_values': 0,
 'current_batch_included': False,
 'cross_partition_labels_allowed': False,
 'labels_attached_to_feature_table': False,
 'verified_at_utc': '2026-07-19T10:54:42.449593+00:00'}

In [20]:
# 05_MARKET_STATE_FEATURES — Cell 19
# Persist Notebook 05 feature, label, registry, audit, manifest, handoff, and final acceptance artifacts.

from __future__ import annotations

import copy
import hashlib
import json
import math
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# Local defensive helpers
# ------------------------------------------------------------

def _now_utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _fallback_require(condition: bool, message: str) -> None:
    if not bool(condition):
        raise AssertionError(message)


require = globals().get("require", _fallback_require)


def _require_columns(frame: pd.DataFrame, required_columns: Iterable[str], frame_name: str) -> None:
    missing = sorted(set(required_columns) - set(frame.columns))
    require(not missing, f"{frame_name} is missing required columns: {missing}")


def _json_default(value: Any) -> Any:
    if value is pd.NA:
        return None
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        if not np.isfinite(float(value)):
            return str(float(value))
        return float(value)
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    if isinstance(value, set):
        return sorted(value)
    return value


def _canonical_json_bytes(payload: Any) -> bytes:
    return json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        default=_json_default,
    ).encode("utf-8")


def _canonical_json_sha256(payload: Any) -> str:
    return hashlib.sha256(_canonical_json_bytes(payload)).hexdigest()


def _sha256_file(path: Path) -> str:
    path = Path(path)
    hasher = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            hasher.update(block)
    return hasher.hexdigest()


def _write_text_atomic(path: Path, text: str) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = path.with_name(f"{path.name}.tmp")
    temporary_path.write_text(text, encoding="utf-8")
    os.replace(temporary_path, path)


def _read_json(path: Path) -> dict[str, Any]:
    with Path(path).open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    require(isinstance(payload, dict), f"JSON artifact is not an object: {path}")
    return payload


def _write_self_hashed_json(
    path: Path,
    payload: dict[str, Any],
    hash_field: str,
) -> tuple[str, str]:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    payload_to_write = copy.deepcopy(payload)
    payload_to_write.pop(hash_field, None)
    payload_hash = _canonical_json_sha256(payload_to_write)
    payload_to_write[hash_field] = payload_hash

    json_text = json.dumps(
        payload_to_write,
        indent=2,
        sort_keys=True,
        ensure_ascii=False,
        default=_json_default,
    )
    _write_text_atomic(path, json_text + "\n")

    readback_payload = _read_json(path)
    readback_without_hash = copy.deepcopy(readback_payload)
    observed_payload_hash = readback_without_hash.pop(hash_field, None)

    require(
        observed_payload_hash == payload_hash,
        f"{path.name} embedded {hash_field} changed during read-back.",
    )
    require(
        _canonical_json_sha256(readback_without_hash) == payload_hash,
        f"{path.name} self-hash verification failed.",
    )

    return payload_hash, _sha256_file(path)


def _first_existing_dataframe(
    candidate_names: Iterable[str],
    *,
    required: bool,
    description: str,
) -> tuple[str | None, pd.DataFrame | None]:
    for candidate_name in candidate_names:
        candidate_value = globals().get(candidate_name)
        if isinstance(candidate_value, pd.DataFrame):
            return candidate_name, candidate_value

    require(
        not required,
        f"Required DataFrame not found for {description}. Candidates checked: {list(candidate_names)}",
    )
    return None, None


def _as_path(value: Any, fallback: str | Path) -> Path:
    if value is None:
        return Path(fallback)
    return Path(value)


def _path_string(path: Path) -> str:
    return str(Path(path))


# ------------------------------------------------------------
# Required runtime identity
# ------------------------------------------------------------

PROJECT_NAME = globals().get("PROJECT_NAME", "The Clown Project")
PIPELINE_VERSION = globals().get("PIPELINE_VERSION", "V0.1")
NOTEBOOK_NAME = globals().get("NOTEBOOK_NAME", "05_MARKET_STATE_FEATURES")
NOTEBOOK_ID = "05_MARKET_STATE_FEATURES"
NEXT_NOTEBOOK_NAME = "06_POINT_PROCESS_BASELINES"

SOURCE_RUN_PREFIX = globals().get("SOURCE_RUN_PREFIX")
V01_RUN_ID = globals().get("V01_RUN_ID")
COMBINED_OUTPUT_PREFIX = globals().get("COMBINED_OUTPUT_PREFIX")

require(SOURCE_RUN_PREFIX is not None, "SOURCE_RUN_PREFIX is not available.")
require(V01_RUN_ID is not None, "V01_RUN_ID is not available.")

if COMBINED_OUTPUT_PREFIX is None:
    COMBINED_OUTPUT_PREFIX = f"{SOURCE_RUN_PREFIX}__{V01_RUN_ID}"

V01_ROOT_PATH = _as_path(globals().get("V01_ROOT"), r"D:\Clown Project\V0.1")
V00_ROOT_PATH = _as_path(globals().get("V00_ROOT"), r"D:\Clown Project\V0.0")

SOURCE_SET_SHA256 = globals().get("SOURCE_SET_SHA256")
RUN_CONFIG_SHA256 = globals().get("RUN_CONFIG_SHA256")
RUN_IDENTITY_SHA256 = globals().get("RUN_IDENTITY_SHA256")

EXPECTED_BATCH_ROWS = int(globals().get("EXPECTED_PRIMARY_BATCHES", 13564))
EXPECTED_EVENT_ROWS = int(globals().get("EXPECTED_PRIMARY_EVENTS", 13887))
EXPECTED_TRADE_PRINT_ROWS = int(globals().get("EXPECTED_TRADE_PRINT_ROWS", globals().get("EXPECTED_MATCHED_TRADE_ROWS", 67683)))

FEATURE_DIR = V01_ROOT_PATH / "data" / "processed" / "features"
LABEL_DIR = V01_ROOT_PATH / "data" / "processed" / "labels"
AUDIT_DIR = V01_ROOT_PATH / "artifacts" / "audit_tables" / NOTEBOOK_ID
CONTRACT_DIR = V01_ROOT_PATH / "config"
MANIFEST_DIR = V01_ROOT_PATH / "artifacts" / "manifests"
HANDOFF_DIR = V01_ROOT_PATH / "artifacts" / "handoff"

for directory in (
    FEATURE_DIR,
    LABEL_DIR,
    AUDIT_DIR,
    CONTRACT_DIR,
    MANIFEST_DIR,
    HANDOFF_DIR,
):
    directory.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# Required completed Notebook 05 blocks
# ------------------------------------------------------------

feature_table_name, raw_feature_table = _first_existing_dataframe(
    (
        "PRIMARY_BATCH_MARKET_STATE_FEATURES",
        "PRIMARY_BATCH_CAUSAL_MARKET_STATE_FEATURES",
        "BATCH_MARKET_STATE_FEATURES",
    ),
    required=True,
    description="primary market-state feature table",
)

label_table_name, raw_label_table = _first_existing_dataframe(
    (
        "PRIMARY_BATCH_FUTURE_LABELS",
        "PRIMARY_BATCH_FUTURE_LABEL_TABLE",
        "BATCH_FUTURE_LABELS",
    ),
    required=True,
    description="primary future-label table",
)

post_batch_context_name, raw_post_batch_context = _first_existing_dataframe(
    (
        "PRIMARY_BATCH_POST_BATCH_CONTEXT",
        "POST_BATCH_CURRENT_BATCH_CONTEXT",
        "PRIMARY_BATCH_TPLUS_CONTEXT",
        "TPLUS_CURRENT_BATCH_CONTEXT",
        "BATCH_TPLUS_CURRENT_BATCH_CONTEXT",
    ),
    required=False,
    description="post-batch current-batch context table",
)

feature_registry_name, raw_feature_registry = _first_existing_dataframe(
    (
        "MARKET_STATE_FEATURE_REGISTRY",
        "PRIMARY_MARKET_STATE_FEATURE_REGISTRY",
        "FINAL_MARKET_STATE_FEATURE_REGISTRY",
        "COMBINED_MARKET_STATE_FEATURE_REGISTRY",
    ),
    required=False,
    description="market-state feature registry",
)

label_registry_name, raw_label_registry = _first_existing_dataframe(
    (
        "FUTURE_LABEL_REGISTRY",
        "PRIMARY_FUTURE_LABEL_REGISTRY",
        "FINAL_FUTURE_LABEL_REGISTRY",
    ),
    required=False,
    description="future-label registry",
)

feature_availability_name, raw_feature_availability = _first_existing_dataframe(
    (
        "PRIMARY_BATCH_FEATURE_AVAILABILITY",
        "BATCH_FEATURE_AVAILABILITY_REPORT",
        "FEATURE_AVAILABILITY_REPORT",
        "MARKET_STATE_FEATURE_AVAILABILITY_REPORT",
    ),
    required=False,
    description="feature row-availability report",
)


IDENTITY_COLUMNS = (
    "primary_event_batch_id",
    "primary_event_batch_number",
    "partition_batch_index",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
)

STRICT_IDENTITY_COLUMNS = (
    "primary_event_batch_id",
    "primary_event_batch_number",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
)

_require_columns(raw_feature_table, STRICT_IDENTITY_COLUMNS, "PRIMARY_BATCH_MARKET_STATE_FEATURES")
_require_columns(raw_label_table, STRICT_IDENTITY_COLUMNS, "PRIMARY_BATCH_FUTURE_LABELS")

require(
    len(raw_feature_table) == EXPECTED_BATCH_ROWS,
    f"Feature table row count differs from expected primary scoring batches: {len(raw_feature_table)} != {EXPECTED_BATCH_ROWS}",
)
require(
    len(raw_label_table) == EXPECTED_BATCH_ROWS,
    f"Future-label table row count differs from expected primary scoring batches: {len(raw_label_table)} != {EXPECTED_BATCH_ROWS}",
)

feature_columns = [
    column
    for column in raw_feature_table.columns
    if column not in IDENTITY_COLUMNS
]
label_columns = [
    column
    for column in raw_label_table.columns
    if column not in IDENTITY_COLUMNS
]

require(feature_columns, "No feature columns found in PRIMARY_BATCH_MARKET_STATE_FEATURES.")
require(label_columns, "No label columns found in PRIMARY_BATCH_FUTURE_LABELS.")

if raw_feature_registry is None:
    raw_feature_registry = pd.DataFrame(
        {
            "feature_name": feature_columns,
            "timing_class": "T_MINUS",
            "physical_table_role": "CAUSAL_MARKET_STATE_FEATURE",
            "authority_class": "PERSISTENCE_DERIVED_REGISTRY",
            "source_registry": "RECONSTRUCTED_FROM_PRIMARY_BATCH_MARKET_STATE_FEATURES",
        }
    )
    feature_registry_name = "PERSISTENCE_DERIVED_MARKET_STATE_FEATURE_REGISTRY"

if raw_label_registry is None:
    raw_label_registry = pd.DataFrame(
        {
            "label_name": label_columns,
            "timing_class": "FUTURE_LABEL",
            "physical_table_role": "SEPARATE_FUTURE_LABEL",
            "authority_class": "PERSISTENCE_DERIVED_REGISTRY",
            "source_registry": "RECONSTRUCTED_FROM_PRIMARY_BATCH_FUTURE_LABELS",
        }
    )
    label_registry_name = "PERSISTENCE_DERIVED_FUTURE_LABEL_REGISTRY"

if raw_feature_availability is None:
    raw_feature_availability = raw_feature_table.loc[:, list(STRICT_IDENTITY_COLUMNS)].copy()
    available_feature_count = raw_feature_table.loc[:, feature_columns].notna().sum(axis=1)
    raw_feature_availability = pd.concat(
        [
            raw_feature_availability,
            pd.DataFrame(
                {
                    "available_feature_count": available_feature_count.astype("int64"),
                    "missing_feature_count": (len(feature_columns) - available_feature_count).astype("int64"),
                    "complete_feature_row_flag": (available_feature_count == len(feature_columns)).astype("bool"),
                },
                index=raw_feature_table.index,
            ),
        ],
        axis=1,
    )
    feature_availability_name = "PERSISTENCE_DERIVED_FEATURE_AVAILABILITY_REPORT"


# ------------------------------------------------------------
# Logical schema normalization for stable Parquet round trips
# ------------------------------------------------------------

_STRING_NAME_PATTERNS = (
    r"_id$",
    r"^id$",
    r"partition$",
    r"partition_name$",
    r"event_partition$",
    r"matched_book_partition$",
    r"status$",
    r"acceptance_status$",
    r"timing_class$",
    r"physical_table_role$",
    r"authority_class$",
    r"availability_class$",
    r"source_registry$",
    r"feature_family$",
    r"feature_name$",
    r"label_name$",
    r"horizon_name$",
    r"window_name$",
    r"window_type$",
    r"role$",
    r"rule$",
    r"policy$",
    r"class$",
)

_BOOL_NAME_PATTERNS = (
    r"_flag$",
    r"_verified$",
    r"_authorized$",
    r"_allowed$",
    r"_included$",
    r"_available$",
    r"_required$",
    r"^has_",
    r"^is_",
    r"^no_",
    r"^current_batch_included$",
    r"^future_information_allowed$",
    r"^physical_separation_required$",
    r"^authorized_in_feature_table$",
)

_INT_NAME_PATTERNS = (
    r"_ns$",
    r"_number$",
    r"_index$",
    r"_order$",
    r"_count$",
    r"_rows$",
    r"_row_count$",
    r"_column_count$",
    r"_bytes$",
    r"_size_bytes$",
    r"_level$",
    r"_code$",
    r"_rank$",
    r"^window_ns$",
    r"^horizon_ns$",
    r"^prior_batch_count$",
    r"^batch_count$",
    r"^feature_count$",
    r"^label_count$",
)

_FLOAT_NAME_PATTERNS = (
    r"_seconds$",
    r"_ms$",
    r"_price$",
    r"_quantity$",
    r"_notional$",
    r"_vwap$",
    r"_midpoint$",
    r"_microprice$",
    r"_spread$",
    r"_basis_points$",
    r"_bps$",
    r"_bps2$",
    r"_rate$",
    r"_fraction$",
    r"_ratio$",
    r"_share$",
    r"_imbalance$",
    r"_hhi$",
    r"_distance$",
    r"_asymmetry$",
    r"_variance$",
    r"_volatility$",
    r"_change$",
    r"_displacement$",
    r"_depth$",
    r"_duration$",
    r"_lag$",
)


def _name_matches(column_name: str, patterns: Iterable[str]) -> bool:
    lower_name = str(column_name).lower()
    return any(re.search(pattern, lower_name) is not None for pattern in patterns)


def _series_all_bool_like(series: pd.Series) -> bool:
    nonmissing = series.dropna()
    if nonmissing.empty:
        return False
    normalized = set(str(value).strip().lower() for value in nonmissing.unique())
    return normalized.issubset({"true", "false", "0", "1"})


def _series_all_integer_like(series: pd.Series) -> bool:
    nonmissing = series.dropna()
    if nonmissing.empty:
        return False
    numeric = pd.to_numeric(nonmissing, errors="coerce")
    if numeric.isna().any():
        return False
    values = numeric.to_numpy(dtype="float64")
    if not np.isfinite(values).all():
        return False
    return bool(np.all(np.abs(values - np.rint(values)) <= 1e-6))


def _infer_logical_type(column_name: str, series: pd.Series) -> str:
    if _name_matches(column_name, _STRING_NAME_PATTERNS):
        return "string"

    if pd.api.types.is_bool_dtype(series) or _name_matches(column_name, _BOOL_NAME_PATTERNS):
        return "boolean"

    if _name_matches(column_name, _INT_NAME_PATTERNS):
        return "int64"

    if _name_matches(column_name, _FLOAT_NAME_PATTERNS):
        return "float64"

    if pd.api.types.is_integer_dtype(series):
        return "int64"

    if pd.api.types.is_float_dtype(series):
        return "float64"

    if pd.api.types.is_bool_dtype(series):
        return "boolean"

    if _series_all_bool_like(series):
        return "boolean"

    if _series_all_integer_like(series):
        return "int64"

    return "string"


def _stable_object_string(value: Any) -> Any:
    if value is pd.NA:
        return pd.NA
    try:
        if pd.isna(value):
            return pd.NA
    except Exception:
        pass

    if isinstance(value, (dict, list, tuple, set)):
        return json.dumps(
            value,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
            default=_json_default,
        )

    return str(value)


def _coerce_string(series: pd.Series) -> pd.Series:
    converted = series.map(_stable_object_string)
    return converted.astype("string")


def _coerce_boolean(series: pd.Series, column_name: str) -> pd.Series:
    if pd.api.types.is_bool_dtype(series):
        return series.astype("boolean")

    def convert(value: Any) -> Any:
        if value is pd.NA:
            return pd.NA
        try:
            if pd.isna(value):
                return pd.NA
        except Exception:
            pass

        if isinstance(value, (bool, np.bool_)):
            return bool(value)

        text = str(value).strip().lower()
        if text in {"true", "1", "yes", "y"}:
            return True
        if text in {"false", "0", "no", "n"}:
            return False

        raise AssertionError(f"{column_name} contains a non-boolean value: {value!r}")

    return series.map(convert).astype("boolean")


def _coerce_int64(series: pd.Series, column_name: str) -> pd.Series:
    numeric = pd.to_numeric(series, errors="coerce")
    original_missing = series.isna()

    require(
        bool(numeric.notna().eq(~original_missing).all()),
        f"{column_name} contains non-numeric values but was classified as int64.",
    )

    nonmissing_values = numeric.loc[~original_missing].to_numpy(dtype="float64")
    if nonmissing_values.size:
        require(
            bool(np.isfinite(nonmissing_values).all()),
            f"{column_name} contains non-finite integer-like values.",
        )

    rounded = np.rint(numeric.to_numpy(dtype="float64"))
    rounded_series = pd.Series(rounded, index=series.index)
    rounded_series.loc[original_missing] = pd.NA
    return rounded_series.astype("Int64")


def _coerce_float64(series: pd.Series, column_name: str) -> pd.Series:
    numeric = pd.to_numeric(series, errors="coerce")
    original_missing = series.isna()

    require(
        bool(numeric.notna().eq(~original_missing).all()),
        f"{column_name} contains non-numeric values but was classified as float64.",
    )

    return numeric.astype("float64")


def _prepare_dataframe_for_storage(
    dataframe: pd.DataFrame,
    *,
    schema: list[dict[str, Any]] | None = None,
) -> tuple[pd.DataFrame, list[dict[str, Any]]]:
    require(isinstance(dataframe, pd.DataFrame), "Input is not a DataFrame.")

    source = dataframe.reset_index(drop=True).copy()
    require(source.columns.is_unique, "DataFrame columns are not unique.")

    if schema is None:
        schema = []
        for position, column_name in enumerate(source.columns):
            logical_type = _infer_logical_type(column_name, source[column_name])
            schema.append(
                {
                    "position": int(position),
                    "name": str(column_name),
                    "logical_type": logical_type,
                    "nullable": bool(source[column_name].isna().any()),
                }
            )
    else:
        expected_columns = [field["name"] for field in schema]
        _require_columns(source, expected_columns, "readback/source DataFrame")
        source = source.loc[:, expected_columns].copy()

    prepared_columns: dict[str, pd.Series] = {}

    for field in schema:
        column_name = field["name"]
        logical_type = field["logical_type"]
        series = source[column_name]

        if logical_type == "string":
            prepared_columns[column_name] = _coerce_string(series)
        elif logical_type == "boolean":
            prepared_columns[column_name] = _coerce_boolean(series, column_name)
        elif logical_type == "int64":
            prepared_columns[column_name] = _coerce_int64(series, column_name)
        elif logical_type == "float64":
            prepared_columns[column_name] = _coerce_float64(series, column_name)
        else:
            raise AssertionError(f"Unsupported logical type for {column_name}: {logical_type}")

    prepared = pd.DataFrame(prepared_columns, index=source.index)
    prepared = prepared.loc[:, [field["name"] for field in schema]].copy()

    return prepared, schema


def _canonical_scalar(value: Any, logical_type: str) -> str:
    try:
        if pd.isna(value):
            return "<NA>"
    except Exception:
        pass

    if logical_type == "boolean":
        return "true" if bool(value) else "false"

    if logical_type == "int64":
        return str(int(value))

    if logical_type == "float64":
        value_float = float(value)
        if math.isnan(value_float):
            return "<NA>"
        if math.isinf(value_float):
            return "Infinity" if value_float > 0 else "-Infinity"
        return format(value_float, ".17g")

    if logical_type == "string":
        return str(value)

    raise AssertionError(f"Unsupported logical type in canonical scalar: {logical_type}")


def _dataframe_payload_sha256(
    dataframe: pd.DataFrame,
    schema: list[dict[str, Any]],
) -> str:
    hasher = hashlib.sha256()

    schema_header = {
        "row_count": int(len(dataframe)),
        "column_count": int(len(schema)),
        "schema": schema,
    }
    hasher.update(_canonical_json_bytes(schema_header))
    hasher.update(b"\n")

    for field in schema:
        column_name = field["name"]
        logical_type = field["logical_type"]

        hasher.update(str(column_name).encode("utf-8"))
        hasher.update(b"\x1f")
        hasher.update(str(logical_type).encode("utf-8"))
        hasher.update(b"\x1e")

        series = dataframe[column_name]
        for value in series.array:
            hasher.update(_canonical_scalar(value, logical_type).encode("utf-8"))
            hasher.update(b"\x1d")

        hasher.update(b"\x1c")

    return hasher.hexdigest()


def _write_dataframe_artifact(
    *,
    label: str,
    dataframe: pd.DataFrame,
    output_dir: Path,
    artifact_type: str,
    physical_table_role: str,
    timing_class: str,
    description: str,
) -> tuple[dict[str, Any], dict[str, Any], pd.DataFrame]:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    prepared_dataframe, logical_schema = _prepare_dataframe_for_storage(dataframe)
    semantic_hash_before = _dataframe_payload_sha256(prepared_dataframe, logical_schema)

    parquet_path = output_dir / f"{COMBINED_OUTPUT_PREFIX}__{NOTEBOOK_ID}__{label}.parquet"
    contract_path = output_dir / f"{COMBINED_OUTPUT_PREFIX}__{NOTEBOOK_ID}__{label}__contract.json"

    temporary_path = parquet_path.with_name(f"{parquet_path.name}.tmp")
    prepared_dataframe.to_parquet(temporary_path, index=False)
    os.replace(temporary_path, parquet_path)

    readback_raw = pd.read_parquet(parquet_path)
    readback_dataframe, _ = _prepare_dataframe_for_storage(
        readback_raw,
        schema=logical_schema,
    )
    semantic_hash_after = _dataframe_payload_sha256(readback_dataframe, logical_schema)

    require(
        semantic_hash_after == semantic_hash_before,
        (
            f"{label} read-back semantic hash mismatch after logical-schema normalization: "
            f"{semantic_hash_after} != {semantic_hash_before}"
        ),
    )

    require(
        prepared_dataframe.shape == readback_dataframe.shape,
        f"{label} read-back shape mismatch: {readback_dataframe.shape} != {prepared_dataframe.shape}",
    )
    require(
        list(prepared_dataframe.columns) == list(readback_dataframe.columns),
        f"{label} read-back column order mismatch.",
    )

    raw_file_sha256 = _sha256_file(parquet_path)

    contract_payload = {
        "artifact_type": f"{artifact_type}_CONTRACT",
        "project_name": PROJECT_NAME,
        "pipeline_version": PIPELINE_VERSION,
        "source_run_prefix": SOURCE_RUN_PREFIX,
        "v0_1_run_id": V01_RUN_ID,
        "combined_output_prefix": COMBINED_OUTPUT_PREFIX,
        "producing_notebook": NOTEBOOK_NAME,
        "notebook_id": NOTEBOOK_ID,
        "label": label,
        "format": "PARQUET",
        "physical_table_role": physical_table_role,
        "timing_class": timing_class,
        "description": description,
        "row_count": int(len(prepared_dataframe)),
        "column_count": int(prepared_dataframe.shape[1]),
        "columns": [str(column) for column in prepared_dataframe.columns],
        "logical_schema": logical_schema,
        "table_payload_sha256": semantic_hash_before,
        "raw_file_sha256": raw_file_sha256,
        "relative_path": str(parquet_path.relative_to(V01_ROOT_PATH)) if parquet_path.is_relative_to(V01_ROOT_PATH) else str(parquet_path),
        "resolved_path": str(parquet_path),
        "created_at_utc": _now_utc_iso(),
    }

    contract_payload_sha256, contract_raw_sha256 = _write_self_hashed_json(
        contract_path,
        contract_payload,
        "contract_payload_sha256",
    )

    artifact_record = {
        "label": label,
        "artifact_type": artifact_type,
        "format": "PARQUET",
        "acceptance_status": "PASS",
        "physical_table_role": physical_table_role,
        "timing_class": timing_class,
        "row_count": int(len(prepared_dataframe)),
        "column_count": int(prepared_dataframe.shape[1]),
        "size_bytes": int(parquet_path.stat().st_size),
        "table_payload_sha256": semantic_hash_before,
        "raw_file_sha256": raw_file_sha256,
        "contract_payload_sha256": contract_payload_sha256,
        "contract_raw_sha256": contract_raw_sha256,
        "resolved_path": str(parquet_path),
        "relative_path": str(parquet_path.relative_to(V01_ROOT_PATH)) if parquet_path.is_relative_to(V01_ROOT_PATH) else str(parquet_path),
        "contract_path": str(contract_path),
    }

    readback_record = {
        "label": label,
        "row_count": int(len(readback_dataframe)),
        "column_count": int(readback_dataframe.shape[1]),
        "table_payload_sha256_before_write": semantic_hash_before,
        "table_payload_sha256_after_readback": semantic_hash_after,
        "raw_file_sha256": raw_file_sha256,
        "contract_payload_sha256": contract_payload_sha256,
        "status": "PASS",
    }

    return artifact_record, readback_record, prepared_dataframe


# ------------------------------------------------------------
# Normalize core tables before invariant checks
# ------------------------------------------------------------

PRIMARY_BATCH_MARKET_STATE_FEATURES, MARKET_STATE_FEATURE_TABLE_SCHEMA = _prepare_dataframe_for_storage(
    raw_feature_table
)
PRIMARY_BATCH_FUTURE_LABELS, FUTURE_LABEL_TABLE_SCHEMA = _prepare_dataframe_for_storage(
    raw_label_table
)
MARKET_STATE_FEATURE_REGISTRY, MARKET_STATE_FEATURE_REGISTRY_SCHEMA = _prepare_dataframe_for_storage(
    raw_feature_registry
)
FUTURE_LABEL_REGISTRY, FUTURE_LABEL_REGISTRY_SCHEMA = _prepare_dataframe_for_storage(
    raw_label_registry
)
PRIMARY_BATCH_FEATURE_AVAILABILITY, FEATURE_AVAILABILITY_SCHEMA = _prepare_dataframe_for_storage(
    raw_feature_availability
)

if raw_post_batch_context is not None:
    PRIMARY_BATCH_POST_BATCH_CONTEXT, POST_BATCH_CONTEXT_SCHEMA = _prepare_dataframe_for_storage(
        raw_post_batch_context
    )
else:
    PRIMARY_BATCH_POST_BATCH_CONTEXT = None
    POST_BATCH_CONTEXT_SCHEMA = None

globals()["PRIMARY_BATCH_MARKET_STATE_FEATURES"] = PRIMARY_BATCH_MARKET_STATE_FEATURES
globals()["PRIMARY_BATCH_FUTURE_LABELS"] = PRIMARY_BATCH_FUTURE_LABELS
globals()["MARKET_STATE_FEATURE_REGISTRY"] = MARKET_STATE_FEATURE_REGISTRY
globals()["FUTURE_LABEL_REGISTRY"] = FUTURE_LABEL_REGISTRY
globals()["PRIMARY_BATCH_FEATURE_AVAILABILITY"] = PRIMARY_BATCH_FEATURE_AVAILABILITY
if PRIMARY_BATCH_POST_BATCH_CONTEXT is not None:
    globals()["PRIMARY_BATCH_POST_BATCH_CONTEXT"] = PRIMARY_BATCH_POST_BATCH_CONTEXT


# ------------------------------------------------------------
# Physical separation and identity checks
# ------------------------------------------------------------

shared_feature_label_columns = sorted(
    set(PRIMARY_BATCH_MARKET_STATE_FEATURES.columns)
    & set(PRIMARY_BATCH_FUTURE_LABELS.columns)
)
unexpected_shared_columns = sorted(set(shared_feature_label_columns) - set(IDENTITY_COLUMNS))

require(
    not unexpected_shared_columns,
    f"Feature and label tables share non-identity columns: {unexpected_shared_columns}",
)

for identity_column in STRICT_IDENTITY_COLUMNS:
    left = PRIMARY_BATCH_MARKET_STATE_FEATURES[identity_column].astype("string")
    right = PRIMARY_BATCH_FUTURE_LABELS[identity_column].astype("string")
    mismatch_count = int(left.ne(right).sum())
    require(
        mismatch_count == 0,
        f"Feature/label identity mismatch in {identity_column}: {mismatch_count}",
    )

feature_columns = [
    column
    for column in PRIMARY_BATCH_MARKET_STATE_FEATURES.columns
    if column not in IDENTITY_COLUMNS
]
label_columns = [
    column
    for column in PRIMARY_BATCH_FUTURE_LABELS.columns
    if column not in IDENTITY_COLUMNS
]

forbidden_feature_columns = sorted(
    column
    for column in feature_columns
    if str(column).startswith("label_")
    or str(column).startswith("tplus_")
    or "future_" in str(column).lower()
)

require(
    not forbidden_feature_columns,
    f"Feature table contains future, label, or t-plus fields: {forbidden_feature_columns[:20]}",
)

require(
    all(str(column).startswith("label_") for column in label_columns),
    "Future-label table contains non-identity columns that do not start with label_.",
)

feature_missing_value_count = int(PRIMARY_BATCH_MARKET_STATE_FEATURES.loc[:, feature_columns].isna().sum().sum())
label_missing_value_count = int(PRIMARY_BATCH_FUTURE_LABELS.loc[:, label_columns].isna().sum().sum())

feature_infinite_count = int(
    np.isinf(
        PRIMARY_BATCH_MARKET_STATE_FEATURES.loc[
            :,
            [
                field["name"]
                for field in MARKET_STATE_FEATURE_TABLE_SCHEMA
                if field["name"] in feature_columns and field["logical_type"] == "float64"
            ],
        ].to_numpy(dtype="float64")
    ).sum()
)

label_infinite_count = int(
    np.isinf(
        PRIMARY_BATCH_FUTURE_LABELS.loc[
            :,
            [
                field["name"]
                for field in FUTURE_LABEL_TABLE_SCHEMA
                if field["name"] in label_columns and field["logical_type"] == "float64"
            ],
        ].to_numpy(dtype="float64")
    ).sum()
)

require(feature_infinite_count == 0, f"Feature table contains infinite values: {feature_infinite_count}")
require(label_infinite_count == 0, f"Future-label table contains infinite values: {label_infinite_count}")


# ------------------------------------------------------------
# Persist core and registry artifacts
# ------------------------------------------------------------

artifact_records: list[dict[str, Any]] = []
readback_records: list[dict[str, Any]] = []

core_artifact_specs = [
    {
        "label": "primary_batch_market_state_features",
        "dataframe": PRIMARY_BATCH_MARKET_STATE_FEATURES,
        "output_dir": FEATURE_DIR,
        "artifact_type": "PRIMARY_BATCH_MARKET_STATE_FEATURES",
        "physical_table_role": "CAUSAL_MARKET_STATE_FEATURE",
        "timing_class": "T_MINUS",
        "description": "Canonical Notebook 05 causal market-state feature table at the primary scoring-batch observational unit.",
    },
    {
        "label": "primary_batch_future_labels",
        "dataframe": PRIMARY_BATCH_FUTURE_LABELS,
        "output_dir": LABEL_DIR,
        "artifact_type": "PRIMARY_BATCH_FUTURE_LABELS",
        "physical_table_role": "SEPARATE_FUTURE_LABEL",
        "timing_class": "FUTURE_LABEL",
        "description": "Physically separate Notebook 05 future-label table at the primary scoring-batch observational unit.",
    },
    {
        "label": "market_state_feature_registry",
        "dataframe": MARKET_STATE_FEATURE_REGISTRY,
        "output_dir": AUDIT_DIR,
        "artifact_type": "MARKET_STATE_FEATURE_REGISTRY",
        "physical_table_role": "FEATURE_REGISTRY",
        "timing_class": "T_MINUS",
        "description": "Registry of all persisted causal market-state features.",
    },
    {
        "label": "future_label_registry",
        "dataframe": FUTURE_LABEL_REGISTRY,
        "output_dir": AUDIT_DIR,
        "artifact_type": "FUTURE_LABEL_REGISTRY",
        "physical_table_role": "LABEL_REGISTRY",
        "timing_class": "FUTURE_LABEL",
        "description": "Registry of all physically separate future labels.",
    },
    {
        "label": "primary_batch_feature_availability",
        "dataframe": PRIMARY_BATCH_FEATURE_AVAILABILITY,
        "output_dir": AUDIT_DIR,
        "artifact_type": "PRIMARY_BATCH_FEATURE_AVAILABILITY",
        "physical_table_role": "FEATURE_AVAILABILITY_AUDIT",
        "timing_class": "T_MINUS",
        "description": "Per-batch availability audit for causally nullable feature values.",
    },
]

if PRIMARY_BATCH_POST_BATCH_CONTEXT is not None:
    core_artifact_specs.append(
        {
            "label": "primary_batch_post_batch_context",
            "dataframe": PRIMARY_BATCH_POST_BATCH_CONTEXT,
            "output_dir": AUDIT_DIR,
            "artifact_type": "PRIMARY_BATCH_POST_BATCH_CONTEXT",
            "physical_table_role": "POST_BATCH_DIAGNOSTIC",
            "timing_class": "T_PLUS",
            "description": "Physically separate post-batch current-batch diagnostic context; not authorized as a t-minus feature input.",
        }
    )

persisted_frames: dict[str, pd.DataFrame] = {}

for artifact_spec in core_artifact_specs:
    artifact_record, readback_record, prepared_dataframe = _write_dataframe_artifact(
        **artifact_spec
    )
    artifact_records.append(artifact_record)
    readback_records.append(readback_record)
    persisted_frames[artifact_spec["label"]] = prepared_dataframe


# ------------------------------------------------------------
# Persist available Notebook 05 audit tables without making them downstream authorities
# ------------------------------------------------------------

optional_audit_candidates: dict[str, tuple[str, ...]] = {
    "static_visible_book_feature_reconciliation_audit": (
        "STATIC_VISIBLE_BOOK_FIELD_RECONCILIATION_AUDIT",
        "STATIC_VISIBLE_BOOK_RECONCILIATION_AUDIT",
        "STATIC_FEATURE_RECONCILIATION_AUDIT",
    ),
    "static_visible_book_feature_gate_audit": (
        "STATIC_VISIBLE_BOOK_FEATURE_GATE_AUDIT",
        "STATIC_VISIBLE_BOOK_GATE_AUDIT",
    ),
    "common_pre_batch_book_interface_audit": (
        "COMMON_PRE_BATCH_BOOK_INTERFACE_AUDIT",
        "COMMON_BOOK_INTERFACE_AUDIT",
        "BATCH_COMMON_BOOK_AUDIT",
    ),
    "delayed_aggregate_mark_activation_audit": (
        "DELAYED_AGGREGATE_MARK_ACTIVATION_GATE_AUDIT",
        "AGGREGATE_MARK_ACTIVATION_GATE_AUDIT",
        "MARK_ACTIVATION_GATE_AUDIT",
    ),
    "event_flow_window_coverage_audit": (
        "EVENT_FLOW_WINDOW_COVERAGE_AUDIT",
        "CAUSAL_EVENT_FLOW_WINDOW_COVERAGE_AUDIT",
    ),
    "book_flow_window_coverage_audit": (
        "BOOK_FLOW_WINDOW_COVERAGE_AUDIT",
        "CAUSAL_BOOK_FLOW_WINDOW_COVERAGE_AUDIT",
    ),
    "feature_missingness_policy_audit": (
        "FEATURE_MISSINGNESS_POLICY_AUDIT",
        "MARKET_STATE_FEATURE_MISSINGNESS_AUDIT",
    ),
    "feature_family_completeness_audit": (
        "FEATURE_FAMILY_COMPLETENESS_AUDIT",
        "FEATURE_FAMILY_MISSINGNESS_AUDIT",
        "MARKET_STATE_FEATURE_FAMILY_AUDIT",
    ),
    "future_label_horizon_contract": (
        "FUTURE_LABEL_HORIZON_CONTRACT",
        "FUTURE_HORIZON_CONTRACT",
        "LABEL_HORIZON_CONTRACT",
    ),
    "future_label_horizon_coverage_audit": (
        "FUTURE_LABEL_HORIZON_COVERAGE_AUDIT",
        "FUTURE_HORIZON_COVERAGE_AUDIT",
        "LABEL_HORIZON_COVERAGE_AUDIT",
    ),
    "future_label_temporal_gate_audit": (
        "FUTURE_LABEL_TEMPORAL_GATE_AUDIT",
        "FUTURE_LABEL_CAUSALITY_AUDIT",
    ),
    "future_label_missingness_audit": (
        "FUTURE_LABEL_MISSINGNESS_AUDIT",
        "LABEL_MISSINGNESS_AUDIT",
    ),
    "future_label_source_resolution_audit": (
        "FUTURE_LABEL_SOURCE_RESOLUTION_AUDIT",
        "LABEL_STATE_SOURCE_RESOLUTION_AUDIT",
        "SEMANTIC_LABEL_SOURCE_RESOLUTION_AUDIT",
    ),
}

for audit_label, candidate_names in optional_audit_candidates.items():
    candidate_name, candidate_frame = _first_existing_dataframe(
        candidate_names,
        required=False,
        description=audit_label,
    )

    if candidate_frame is None:
        continue

    artifact_record, readback_record, prepared_dataframe = _write_dataframe_artifact(
        label=audit_label,
        dataframe=candidate_frame,
        output_dir=AUDIT_DIR,
        artifact_type=audit_label.upper(),
        physical_table_role="NOTEBOOK_05_AUDIT_TABLE",
        timing_class="DIAGNOSTIC",
        description=f"Notebook 05 diagnostic audit table captured from {candidate_name}.",
    )
    artifact_records.append(artifact_record)
    readback_records.append(readback_record)
    persisted_frames[audit_label] = prepared_dataframe


NOTEBOOK_05_PERSISTED_ARTIFACT_AUDIT = pd.DataFrame(artifact_records).sort_values(
    ["physical_table_role", "label"],
    kind="mergesort",
).reset_index(drop=True)

NOTEBOOK_05_READBACK_AUDIT = pd.DataFrame(readback_records).sort_values(
    ["label"],
    kind="mergesort",
).reset_index(drop=True)


# ------------------------------------------------------------
# Final Notebook 05 acceptance gates
# ------------------------------------------------------------

core_labels = {
    "primary_batch_market_state_features",
    "primary_batch_future_labels",
    "market_state_feature_registry",
    "future_label_registry",
    "primary_batch_feature_availability",
}

persisted_labels = set(NOTEBOOK_05_PERSISTED_ARTIFACT_AUDIT["label"].astype(str))
missing_core_artifacts = sorted(core_labels - persisted_labels)

require(
    not missing_core_artifacts,
    f"Missing persisted core artifacts: {missing_core_artifacts}",
)

readback_failures = int(NOTEBOOK_05_READBACK_AUDIT["status"].ne("PASS").sum())
require(readback_failures == 0, f"Read-back failures found: {readback_failures}")

feature_registry_names = set()
if "feature_name" in MARKET_STATE_FEATURE_REGISTRY.columns:
    feature_registry_names = set(MARKET_STATE_FEATURE_REGISTRY["feature_name"].dropna().astype(str))
elif "label_name" in MARKET_STATE_FEATURE_REGISTRY.columns:
    feature_registry_names = set(MARKET_STATE_FEATURE_REGISTRY["label_name"].dropna().astype(str))

label_registry_names = set()
if "label_name" in FUTURE_LABEL_REGISTRY.columns:
    label_registry_names = set(FUTURE_LABEL_REGISTRY["label_name"].dropna().astype(str))
elif "feature_name" in FUTURE_LABEL_REGISTRY.columns:
    label_registry_names = set(FUTURE_LABEL_REGISTRY["feature_name"].dropna().astype(str))

feature_registry_missing = sorted(set(map(str, feature_columns)) - feature_registry_names)
label_registry_missing = sorted(set(map(str, label_columns)) - label_registry_names)

require(
    not feature_registry_missing,
    f"Feature registry does not cover persisted feature table columns: {feature_registry_missing[:20]}",
)
require(
    not label_registry_missing,
    f"Future-label registry does not cover persisted label table columns: {label_registry_missing[:20]}",
)

warning_rows = []

if feature_missing_value_count > 0:
    warning_rows.append(
        {
            "gate": "causally_explained_feature_missingness_preserved",
            "severity": "WARNING",
            "status": "WARNING",
            "evidence": f"missing_feature_values={feature_missing_value_count}; no imputation applied",
        }
    )

if label_missing_value_count > 0:
    warning_rows.append(
        {
            "gate": "censored_future_label_values_preserved",
            "severity": "WARNING",
            "status": "WARNING",
            "evidence": f"missing_label_values={label_missing_value_count}; partition/right-censoring preserved",
        }
    )

if PRIMARY_BATCH_POST_BATCH_CONTEXT is not None:
    warning_rows.append(
        {
            "gate": "post_batch_context_persisted_separately",
            "severity": "WARNING",
            "status": "WARNING",
            "evidence": "T_PLUS current-batch diagnostics persisted outside the t-minus feature table",
        }
    )

blocking_gate_rows = [
    {
        "gate": "core_artifacts_persisted",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": f"core_artifacts={len(core_labels)}",
    },
    {
        "gate": "all_persisted_tables_readback_verified",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": f"artifacts={len(NOTEBOOK_05_READBACK_AUDIT)}",
    },
    {
        "gate": "feature_table_rows_conserved",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": f"rows={len(PRIMARY_BATCH_MARKET_STATE_FEATURES)}",
    },
    {
        "gate": "future_label_table_rows_conserved",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": f"rows={len(PRIMARY_BATCH_FUTURE_LABELS)}",
    },
    {
        "gate": "feature_and_label_identity_reconciles",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": f"identity_columns={list(STRICT_IDENTITY_COLUMNS)}",
    },
    {
        "gate": "future_labels_physically_separate",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": "feature and label tables share only identity columns",
    },
    {
        "gate": "feature_registry_matches_feature_table",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": f"features={len(feature_columns)}",
    },
    {
        "gate": "future_label_registry_matches_label_table",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": f"labels={len(label_columns)}",
    },
    {
        "gate": "no_future_or_tplus_fields_in_feature_table",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": "forbidden_columns=0",
    },
    {
        "gate": "feature_values_finite_where_numeric",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": f"infinite_feature_values={feature_infinite_count}",
    },
    {
        "gate": "future_label_values_finite_where_numeric",
        "severity": "BLOCKING",
        "status": "PASS",
        "evidence": f"infinite_label_values={label_infinite_count}",
    },
]

NOTEBOOK_05_FINAL_ACCEPTANCE_GATES = pd.DataFrame(
    blocking_gate_rows + warning_rows
)

blocking_failures = int(
    NOTEBOOK_05_FINAL_ACCEPTANCE_GATES.loc[
        NOTEBOOK_05_FINAL_ACCEPTANCE_GATES["severity"].eq("BLOCKING"),
        "status",
    ].ne("PASS").sum()
)
warning_count = int(
    NOTEBOOK_05_FINAL_ACCEPTANCE_GATES.loc[
        NOTEBOOK_05_FINAL_ACCEPTANCE_GATES["severity"].eq("WARNING"),
        "status",
    ].eq("WARNING").sum()
)

require(blocking_failures == 0, f"Notebook 05 blocking failures remain: {blocking_failures}")

NOTEBOOK_05_ACCEPTANCE_STATUS = (
    "PASS_WITH_FEATURE_WARNINGS"
    if warning_count > 0
    else "PASS"
)

NOTEBOOK_06_AUTHORIZED = NOTEBOOK_05_ACCEPTANCE_STATUS in {
    "PASS",
    "PASS_WITH_FEATURE_WARNINGS",
}


acceptance_artifact_record, acceptance_readback_record, NOTEBOOK_05_FINAL_ACCEPTANCE_GATES = _write_dataframe_artifact(
    label="notebook_05_final_acceptance_gates",
    dataframe=NOTEBOOK_05_FINAL_ACCEPTANCE_GATES,
    output_dir=AUDIT_DIR,
    artifact_type="NOTEBOOK_05_FINAL_ACCEPTANCE_GATES",
    physical_table_role="FINAL_ACCEPTANCE_AUDIT",
    timing_class="DIAGNOSTIC",
    description="Notebook 05 final acceptance gate table.",
)
artifact_records.append(acceptance_artifact_record)
readback_records.append(acceptance_readback_record)

artifact_audit_record, artifact_audit_readback_record, NOTEBOOK_05_PERSISTED_ARTIFACT_AUDIT = _write_dataframe_artifact(
    label="notebook_05_persisted_artifact_audit",
    dataframe=NOTEBOOK_05_PERSISTED_ARTIFACT_AUDIT,
    output_dir=AUDIT_DIR,
    artifact_type="NOTEBOOK_05_PERSISTED_ARTIFACT_AUDIT",
    physical_table_role="PERSISTENCE_AUDIT",
    timing_class="DIAGNOSTIC",
    description="Notebook 05 artifact inventory before manifest/handoff/final-acceptance JSON files.",
)
artifact_records.append(artifact_audit_record)
readback_records.append(artifact_audit_readback_record)

readback_audit_record, readback_audit_readback_record, NOTEBOOK_05_READBACK_AUDIT = _write_dataframe_artifact(
    label="notebook_05_readback_audit",
    dataframe=NOTEBOOK_05_READBACK_AUDIT,
    output_dir=AUDIT_DIR,
    artifact_type="NOTEBOOK_05_READBACK_AUDIT",
    physical_table_role="PERSISTENCE_READBACK_AUDIT",
    timing_class="DIAGNOSTIC",
    description="Notebook 05 read-back verification audit.",
)
artifact_records.append(readback_audit_record)
readback_records.append(readback_audit_readback_record)

NOTEBOOK_05_PERSISTED_ARTIFACT_AUDIT = pd.DataFrame(artifact_records).sort_values(
    ["physical_table_role", "label"],
    kind="mergesort",
).reset_index(drop=True)

NOTEBOOK_05_READBACK_AUDIT = pd.DataFrame(readback_records).sort_values(
    ["label"],
    kind="mergesort",
).reset_index(drop=True)


# ------------------------------------------------------------
# Manifest, handoff, and final acceptance JSON artifacts
# ------------------------------------------------------------

artifact_record_by_label = {
    str(record["label"]): record
    for record in artifact_records
}

primary_feature_record = artifact_record_by_label["primary_batch_market_state_features"]
primary_label_record = artifact_record_by_label["primary_batch_future_labels"]
feature_registry_record = artifact_record_by_label["market_state_feature_registry"]
label_registry_record = artifact_record_by_label["future_label_registry"]
feature_availability_record = artifact_record_by_label["primary_batch_feature_availability"]

manifest_path = MANIFEST_DIR / f"{COMBINED_OUTPUT_PREFIX}__{NOTEBOOK_ID}__notebook_05_output_manifest.json"
handoff_path = HANDOFF_DIR / f"{COMBINED_OUTPUT_PREFIX}__{NOTEBOOK_ID}__to_{NEXT_NOTEBOOK_NAME}__handoff.json"
final_acceptance_path = MANIFEST_DIR / f"{COMBINED_OUTPUT_PREFIX}__{NOTEBOOK_ID}__final_acceptance_report.json"

upstream_control_paths = globals().get("UPSTREAM_CONTROL_PATHS", {})
if not isinstance(upstream_control_paths, dict):
    upstream_control_paths = {}

source_lineage = {
    "notebook_00_output_manifest": _path_string(upstream_control_paths.get("notebook_00_output_manifest", "")),
    "notebook_02_output_manifest": _path_string(upstream_control_paths.get("notebook_02_output_manifest", "")),
    "notebook_03_output_manifest": _path_string(upstream_control_paths.get("notebook_03_output_manifest", "")),
    "notebook_04_output_manifest": _path_string(upstream_control_paths.get("notebook_04_output_manifest", "")),
    "notebook_04_to_05_handoff": _path_string(upstream_control_paths.get("notebook_04_to_05_handoff", "")),
}

manifest_payload = {
    "artifact_type": "NOTEBOOK_05_OUTPUT_MANIFEST",
    "manifest_type": "NOTEBOOK_OUTPUT_MANIFEST",
    "schema_version": "v0.1.0",
    "project_name": PROJECT_NAME,
    "pipeline_version": PIPELINE_VERSION,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "combined_output_prefix": COMBINED_OUTPUT_PREFIX,
    "operating_mode": globals().get("OPERATING_MODE"),
    "producing_notebook": NOTEBOOK_NAME,
    "notebook_id": NOTEBOOK_ID,
    "next_notebook": NEXT_NOTEBOOK_NAME,
    "acceptance_status": NOTEBOOK_05_ACCEPTANCE_STATUS,
    "notebook_06_authorized": NOTEBOOK_06_AUTHORIZED,
    "observational_unit": "PRIMARY_SCORING_BATCH",
    "primary_event_representation": globals().get("PRIMARY_EVENT_REPRESENTATION", "SAME_MS_SAME_SIDE_BURSTS"),
    "timestamp_interface": globals().get("PRIMARY_TIMESTAMP_INTERFACE", "SIMULTANEOUS_EVENT_BATCH_REQUIRED"),
    "feature_table_policy": {
        "timing_class": "T_MINUS",
        "physical_table_role": "CAUSAL_MARKET_STATE_FEATURE",
        "future_labels_attached": False,
        "tplus_context_attached": False,
        "imputation_applied": False,
        "causally_explained_missingness_preserved": True,
    },
    "future_label_policy": {
        "timing_class": "FUTURE_LABEL",
        "physical_table_role": "SEPARATE_FUTURE_LABEL",
        "current_batch_included": False,
        "cross_partition_labels_allowed": False,
        "overlapping_forward_windows_acknowledged": True,
    },
    "row_counts": {
        "primary_batch_market_state_features": int(len(PRIMARY_BATCH_MARKET_STATE_FEATURES)),
        "primary_batch_future_labels": int(len(PRIMARY_BATCH_FUTURE_LABELS)),
        "market_state_feature_registry": int(len(MARKET_STATE_FEATURE_REGISTRY)),
        "future_label_registry": int(len(FUTURE_LABEL_REGISTRY)),
        "feature_availability": int(len(PRIMARY_BATCH_FEATURE_AVAILABILITY)),
    },
    "column_counts": {
        "primary_batch_market_state_features": int(PRIMARY_BATCH_MARKET_STATE_FEATURES.shape[1]),
        "primary_batch_future_labels": int(PRIMARY_BATCH_FUTURE_LABELS.shape[1]),
        "feature_columns": int(len(feature_columns)),
        "label_columns": int(len(label_columns)),
    },
    "missingness_summary": {
        "feature_missing_value_count": feature_missing_value_count,
        "label_missing_value_count": label_missing_value_count,
        "feature_infinite_value_count": feature_infinite_count,
        "label_infinite_value_count": label_infinite_count,
    },
    "source_lineage": source_lineage,
    "artifacts": artifact_records,
    "artifact_count": int(len(artifact_records)),
    "created_at_utc": _now_utc_iso(),
}

manifest_payload_sha256, manifest_raw_sha256 = _write_self_hashed_json(
    manifest_path,
    manifest_payload,
    "manifest_payload_sha256",
)

NOTEBOOK_05_OUTPUT_MANIFEST = _read_json(manifest_path)

handoff_payload = {
    "artifact_type": "NOTEBOOK_05_TO_NOTEBOOK_06_HANDOFF",
    "schema_version": "v0.1.0",
    "project_name": PROJECT_NAME,
    "pipeline_version": PIPELINE_VERSION,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "combined_output_prefix": COMBINED_OUTPUT_PREFIX,
    "producing_notebook": NOTEBOOK_NAME,
    "next_notebook": NEXT_NOTEBOOK_NAME,
    "acceptance_status": NOTEBOOK_05_ACCEPTANCE_STATUS,
    "point_process_baselines_authorized": NOTEBOOK_06_AUTHORIZED,
    "hawkes_estimation_authorized": False,
    "market_making_authorized": False,
    "quote_policy_authorized": False,
    "fill_simulation_authorized": False,
    "pnl_backtest_authorized": False,
    "observational_unit": "PRIMARY_SCORING_BATCH",
    "primary_event_representation": globals().get("PRIMARY_EVENT_REPRESENTATION", "SAME_MS_SAME_SIDE_BURSTS"),
    "timestamp_interface": globals().get("PRIMARY_TIMESTAMP_INTERFACE", "SIMULTANEOUS_EVENT_BATCH_REQUIRED"),
    "event_partition_field": "event_partition",
    "primary_time_field": "event_time_ns",
    "identity_columns": list(IDENTITY_COLUMNS),
    "feature_table": primary_feature_record,
    "future_label_table": primary_label_record,
    "feature_registry": feature_registry_record,
    "future_label_registry": label_registry_record,
    "feature_availability_table": feature_availability_record,
    "post_batch_context_table": artifact_record_by_label.get("primary_batch_post_batch_context"),
    "output_manifest": {
        "resolved_path": str(manifest_path),
        "manifest_payload_sha256": manifest_payload_sha256,
        "raw_file_sha256": manifest_raw_sha256,
    },
    "causal_contract": {
        "features_are_tminus": True,
        "current_batch_raw_fields_attached": False,
        "tplus_fields_attached": False,
        "future_labels_attached_to_feature_table": False,
        "labels_physically_separate": True,
        "same_time_batch_semantics": "history strictly before shared batch time; zero-lag within-batch excitation forbidden",
        "timestamp_jitter_applied": False,
        "events_removed": False,
        "causally_explained_feature_nan_policy": "PRESERVE_WITHOUT_IMPUTATION",
    },
    "notebook_06_scope": {
        "authorized": NOTEBOOK_06_AUTHORIZED,
        "authorized_work": [
            "point_process_baselines",
            "event_arrival_baselines",
            "simple_control_models",
            "diagnostics_for_incremental_information_before_hawkes",
        ],
        "not_authorized_work": [
            "hawkes_estimation",
            "hawkes_superiority_claim",
            "market_making_strategy",
            "quote_policy",
            "fill_simulation",
            "pnl_backtest",
        ],
    },
    "created_at_utc": _now_utc_iso(),
}

handoff_payload_sha256, handoff_raw_sha256 = _write_self_hashed_json(
    handoff_path,
    handoff_payload,
    "handoff_payload_sha256",
)

NOTEBOOK_05_TO_06_HANDOFF = _read_json(handoff_path)

final_acceptance_payload = {
    "artifact_type": "NOTEBOOK_05_FINAL_ACCEPTANCE_REPORT",
    "schema_version": "v0.1.0",
    "project_name": PROJECT_NAME,
    "pipeline_version": PIPELINE_VERSION,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "combined_output_prefix": COMBINED_OUTPUT_PREFIX,
    "producing_notebook": NOTEBOOK_NAME,
    "next_notebook": NEXT_NOTEBOOK_NAME,
    "acceptance_status": NOTEBOOK_05_ACCEPTANCE_STATUS,
    "blocking_failure_count": blocking_failures,
    "warning_count": warning_count,
    "notebook_06_authorized": NOTEBOOK_06_AUTHORIZED,
    "core_artifacts": {
        "primary_batch_market_state_features": primary_feature_record,
        "primary_batch_future_labels": primary_label_record,
        "market_state_feature_registry": feature_registry_record,
        "future_label_registry": label_registry_record,
        "primary_batch_feature_availability": feature_availability_record,
    },
    "manifest": {
        "resolved_path": str(manifest_path),
        "manifest_payload_sha256": manifest_payload_sha256,
        "raw_file_sha256": manifest_raw_sha256,
    },
    "handoff": {
        "resolved_path": str(handoff_path),
        "handoff_payload_sha256": handoff_payload_sha256,
        "raw_file_sha256": handoff_raw_sha256,
    },
    "final_gates": NOTEBOOK_05_FINAL_ACCEPTANCE_GATES.to_dict(orient="records"),
    "artifact_count": int(len(artifact_records)),
    "readback_artifact_count": int(len(readback_records)),
    "created_at_utc": _now_utc_iso(),
}

final_acceptance_payload_sha256, final_acceptance_raw_sha256 = _write_self_hashed_json(
    final_acceptance_path,
    final_acceptance_payload,
    "final_acceptance_payload_sha256",
)

NOTEBOOK_05_FINAL_ACCEPTANCE_REPORT = _read_json(final_acceptance_path)


# ------------------------------------------------------------
# Export final globals for downstream inspection
# ------------------------------------------------------------

NOTEBOOK_05_OUTPUT_MANIFEST_PATH = manifest_path
NOTEBOOK_05_TO_06_HANDOFF_PATH = handoff_path
NOTEBOOK_05_FINAL_ACCEPTANCE_REPORT_PATH = final_acceptance_path

NOTEBOOK_05_OUTPUT_MANIFEST_PAYLOAD_SHA256 = manifest_payload_sha256
NOTEBOOK_05_TO_06_HANDOFF_PAYLOAD_SHA256 = handoff_payload_sha256
NOTEBOOK_05_FINAL_ACCEPTANCE_PAYLOAD_SHA256 = final_acceptance_payload_sha256

NOTEBOOK_05_OUTPUT_MANIFEST_RAW_SHA256 = manifest_raw_sha256
NOTEBOOK_05_TO_06_HANDOFF_RAW_SHA256 = handoff_raw_sha256
NOTEBOOK_05_FINAL_ACCEPTANCE_RAW_SHA256 = final_acceptance_raw_sha256

globals()["NOTEBOOK_05_ACCEPTANCE_STATUS"] = NOTEBOOK_05_ACCEPTANCE_STATUS
globals()["NOTEBOOK_06_AUTHORIZED"] = NOTEBOOK_06_AUTHORIZED
globals()["NOTEBOOK_05_OUTPUT_MANIFEST"] = NOTEBOOK_05_OUTPUT_MANIFEST
globals()["NOTEBOOK_05_TO_06_HANDOFF"] = NOTEBOOK_05_TO_06_HANDOFF
globals()["NOTEBOOK_05_FINAL_ACCEPTANCE_REPORT"] = NOTEBOOK_05_FINAL_ACCEPTANCE_REPORT
globals()["NOTEBOOK_05_OUTPUT_MANIFEST_PATH"] = NOTEBOOK_05_OUTPUT_MANIFEST_PATH
globals()["NOTEBOOK_05_TO_06_HANDOFF_PATH"] = NOTEBOOK_05_TO_06_HANDOFF_PATH
globals()["NOTEBOOK_05_FINAL_ACCEPTANCE_REPORT_PATH"] = NOTEBOOK_05_FINAL_ACCEPTANCE_REPORT_PATH
globals()["NOTEBOOK_05_PERSISTED_ARTIFACT_AUDIT"] = NOTEBOOK_05_PERSISTED_ARTIFACT_AUDIT
globals()["NOTEBOOK_05_READBACK_AUDIT"] = NOTEBOOK_05_READBACK_AUDIT
globals()["NOTEBOOK_05_FINAL_ACCEPTANCE_GATES"] = NOTEBOOK_05_FINAL_ACCEPTANCE_GATES


# ------------------------------------------------------------
# Display audit summaries
# ------------------------------------------------------------

display(
    NOTEBOOK_05_PERSISTED_ARTIFACT_AUDIT.loc[
        :,
        [
            "label",
            "physical_table_role",
            "timing_class",
            "row_count",
            "column_count",
            "table_payload_sha256",
            "resolved_path",
        ],
    ]
)

display(
    NOTEBOOK_05_READBACK_AUDIT.loc[
        :,
        [
            "label",
            "row_count",
            "column_count",
            "table_payload_sha256_before_write",
            "table_payload_sha256_after_readback",
            "status",
        ],
    ]
)

display(NOTEBOOK_05_FINAL_ACCEPTANCE_GATES)

{
    "status": NOTEBOOK_05_ACCEPTANCE_STATUS,
    "notebook_05_final_acceptance_verified": True,
    "notebook_06_authorized": NOTEBOOK_06_AUTHORIZED,
    "observational_unit": "PRIMARY_SCORING_BATCH",
    "feature_table_rows": int(len(PRIMARY_BATCH_MARKET_STATE_FEATURES)),
    "feature_table_columns": int(PRIMARY_BATCH_MARKET_STATE_FEATURES.shape[1]),
    "feature_count": int(len(feature_columns)),
    "future_label_table_rows": int(len(PRIMARY_BATCH_FUTURE_LABELS)),
    "future_label_table_columns": int(PRIMARY_BATCH_FUTURE_LABELS.shape[1]),
    "future_label_count": int(len(label_columns)),
    "persisted_artifact_count": int(len(artifact_records)),
    "readback_verified_artifact_count": int(len(readback_records)),
    "feature_missing_value_count": feature_missing_value_count,
    "label_missing_value_count": label_missing_value_count,
    "feature_infinite_value_count": feature_infinite_count,
    "label_infinite_value_count": label_infinite_count,
    "blocking_failure_count": blocking_failures,
    "warning_count": warning_count,
    "primary_feature_table_payload_sha256": primary_feature_record["table_payload_sha256"],
    "primary_label_table_payload_sha256": primary_label_record["table_payload_sha256"],
    "output_manifest_payload_sha256": manifest_payload_sha256,
    "handoff_payload_sha256": handoff_payload_sha256,
    "final_acceptance_payload_sha256": final_acceptance_payload_sha256,
    "output_manifest_path": str(manifest_path),
    "handoff_path": str(handoff_path),
    "final_acceptance_report_path": str(final_acceptance_path),
    "verified_at_utc": _now_utc_iso(),
}

,label,physical_table_role,timing_class,row_count,column_count,table_payload_sha256,resolved_path
0,primary_batch_market_state_features,CAUSAL_MARKET_STATE_FEATURE,T_MINUS,13564,577,a1a04cd8c480e1e62c22e4b4a349d56f3211d7b0af91cccaa849cd9c30923660,D:\Clown Project\V0.1\data\processed\features\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__primary_batch_market_state_features.parquet
1,primary_batch_feature_availability,FEATURE_AVAILABILITY_AUDIT,T_MINUS,13564,8,ec55db6fadf7719f6b3817ad6c0d103cdf7a89b51acdafa4d227ef019767b6ca,D:\Clown Project\V0.1\artifacts\audit_tables\05_MARKET_STATE_FEATURES\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__primary_batch_feature_av...
2,market_state_feature_registry,FEATURE_REGISTRY,T_MINUS,571,44,cdc75286559c0d76172a35c9f3286c86a315dead0751201a07f349695ede4f31,D:\Clown Project\V0.1\artifacts\audit_tables\05_MARKET_STATE_FEATURES\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__market_state_feature_reg...
3,notebook_05_final_acceptance_gates,FINAL_ACCEPTANCE_AUDIT,DIAGNOSTIC,13,4,58d52e50f4c90395bc6dc0bed9d122b83ff4dae9c5b669b8b8456a2f8041ddeb,D:\Clown Project\V0.1\artifacts\audit_tables\05_MARKET_STATE_FEATURES\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__notebook_05_final_accept...
4,future_label_registry,LABEL_REGISTRY,FUTURE_LABEL,140,15,4dcf1c80bb30ec2b05e611c218ca73981f7f7c1c132a26f37d880358b0fc6d87,D:\Clown Project\V0.1\artifacts\audit_tables\05_MARKET_STATE_FEATURES\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__future_label_registry.pa...
5,feature_missingness_policy_audit,NOTEBOOK_05_AUDIT_TABLE,DIAGNOSTIC,576,14,f43f88a18283b073e5c7cecfea8d6fe693775c53a7485c39d73fe73281052120,D:\Clown Project\V0.1\artifacts\audit_tables\05_MARKET_STATE_FEATURES\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__feature_missingness_poli...
6,future_label_horizon_contract,NOTEBOOK_05_AUDIT_TABLE,DIAGNOSTIC,4,12,48fe03815b33503daa365e0e4b6deea0f5aaf061e18ca5b027229ba9b059c48e,D:\Clown Project\V0.1\artifacts\audit_tables\05_MARKET_STATE_FEATURES\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__future_label_horizon_con...
7,future_label_missingness_audit,NOTEBOOK_05_AUDIT_TABLE,DIAGNOSTIC,140,9,2fc1d732f9148dfb11962e05bf3e1d33b703400f98e11d14d00ba720844bfeb4,D:\Clown Project\V0.1\artifacts\audit_tables\05_MARKET_STATE_FEATURES\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__future_label_missingness...
8,future_label_source_resolution_audit,NOTEBOOK_05_AUDIT_TABLE,DIAGNOSTIC,4,4,d59cbf0453ba943a707cac80f9e1d3f58573247721b1e2c29db0444fc4ba0662,D:\Clown Project\V0.1\artifacts\audit_tables\05_MARKET_STATE_FEATURES\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__future_label_source_reso...
9,notebook_05_persisted_artifact_audit,PERSISTENCE_AUDIT,DIAGNOSTIC,9,16,64e2554cd75eea04db1a3476318b0b5840b4f2b3812836268faa0a6d233c6c6a,D:\Clown Project\V0.1\artifacts\audit_tables\05_MARKET_STATE_FEATURES\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__notebook_05_persisted_ar...
10,notebook_05_readback_audit,PERSISTENCE_READBACK_AUDIT,DIAGNOSTIC,9,8,00f2869af981adfe28535a3ef45bb9693a891f4970b7fa5ec00a23b11ab024e7,D:\Clown Project\V0.1\artifacts\audit_tables\05_MARKET_STATE_FEATURES\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__notebook_05_readback_aud...
11,primary_batch_future_labels,SEPARATE_FUTURE_LABEL,FUTURE_LABEL,13564,146,3db6e476a2e1f3476a94f8eea4b1dfac59e30a711d33bf93425a56a070adb5ba,D:\Clown Project\V0.1\data\processed\labels\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__primary_batch_future_labels.parquet

                                   label  row_count  column_count                                 table_payload_sha256_before_write                               table_payload_sha256_after_readback status
0       feature_missingness_policy_audit        576            14  f43f88a18283b073e5c7cecfea8d6fe693775c53a7485c39d73fe73281052120  f43f88a18283b073e5c7cecfea8d6fe693775c53a7485c39d73fe73281052120   PASS
1          future_label_horizon_contract          4            12  48fe03815b33503daa365e0e4b6deea0f5aaf061e18ca5b027229ba9b059c48e  48fe03815b33503daa365e0e4b6deea0f5aaf061e18ca5b027229ba9b059c48e   PASS
2         future_label_missingness_audit        140             9  2fc1d732f9148dfb11962e05bf3e1d33b703400f98e11d14d00ba720844bfeb4  2fc1d732f9148dfb11962e05bf3e1d33b703400f98e11d14d00ba720844bfeb4   PASS
3                  future_label_registry        140            15  4dcf1c80bb30ec2b05e611c218ca73981f7f7c1c132a26f37d880358b0fc6d87  4dcf1c80bb30ec2b05e611c218ca73981f7f7c1c132a26f37d880358b0fc6d87   PASS
4   future_label_source_resolution_audit          4             4  d59cbf0453ba943a707cac80f9e1d3f58573247721b1e2c29db0444fc4ba0662  d59cbf0453ba943a707cac80f9e1d3f58573247721b1e2c29db0444fc4ba0662   PASS
5          market_state_feature_registry        571            44  cdc75286559c0d76172a35c9f3286c86a315dead0751201a07f349695ede4f31  cdc75286559c0d76172a35c9f3286c86a315dead0751201a07f349695ede4f31   PASS
6     notebook_05_final_acceptance_gates         13             4  58d52e50f4c90395bc6dc0bed9d122b83ff4dae9c5b669b8b8456a2f8041ddeb  58d52e50f4c90395bc6dc0bed9d122b83ff4dae9c5b669b8b8456a2f8041ddeb   PASS
7   notebook_05_persisted_artifact_audit          9            16  64e2554cd75eea04db1a3476318b0b5840b4f2b3812836268faa0a6d233c6c6a  64e2554cd75eea04db1a3476318b0b5840b4f2b3812836268faa0a6d233c6c6a   PASS
8             notebook_05_readback_audit          9             8  00f2869af981adfe28535a3ef45bb9693a891f4970b7fa5ec00a23b11ab024e7  00f2869af981adfe28535a3ef45bb9693a891f4970b7fa5ec00a23b11ab024e7   PASS
9     primary_batch_feature_availability      13564             8  ec55db6fadf7719f6b3817ad6c0d103cdf7a89b51acdafa4d227ef019767b6ca  ec55db6fadf7719f6b3817ad6c0d103cdf7a89b51acdafa4d227ef019767b6ca   PASS
10           primary_batch_future_labels      13564           146  3db6e476a2e1f3476a94f8eea4b1dfac59e30a711d33bf93425a56a070adb5ba  3db6e476a2e1f3476a94f8eea4b1dfac59e30a711d33bf93425a56a070adb5ba   PASS
11   primary_batch_market_state_features      13564           577  a1a04cd8c480e1e62c22e4b4a349d56f3211d7b0af91cccaa849cd9c30923660  a1a04cd8c480e1e62c22e4b4a349d56f3211d7b0af91cccaa849cd9c30923660   PASS

                                                gate  severity   status                                                                                                                                evidence
0                           core_artifacts_persisted  BLOCKING     PASS                                                                                                                        core_artifacts=5
1             all_persisted_tables_readback_verified  BLOCKING     PASS                                                                                                                             artifacts=9
2                       feature_table_rows_conserved  BLOCKING     PASS                                                                                                                              rows=13564
3                  future_label_table_rows_conserved  BLOCKING     PASS                                                                                                                              rows=13564
4              feature_and_label_identity_reconciles  BLOCKING     PASS  identity_columns=['primary_event_batch_id', 'primary_event_batch_number', 'event_partition_order', 'event_partition', 'event_time_ns']
5                  future_labels_physically_separate  BLOCKING     PASS                                                                                    feature and label tables share only identity columns
6             feature_registry_matches_feature_table  BLOCKING     PASS                                                                                                                            features=571
7          future_label_registry_matches_label_table  BLOCKING     PASS                                                                                                                              labels=140
8         no_future_or_tplus_fields_in_feature_table  BLOCKING     PASS                                                                                                                     forbidden_columns=0
9                feature_values_finite_where_numeric  BLOCKING     PASS                                                                                                               infinite_feature_values=0
10          future_label_values_finite_where_numeric  BLOCKING     PASS                                                                                                                 infinite_label_values=0
11  causally_explained_feature_missingness_preserved   WARNING  WARNING                                                                                     missing_feature_values=48918; no imputation applied
12            censored_future_label_values_preserved   WARNING  WARNING                                                                         missing_label_values=21660; partition/right-censoring preserved

{'status': 'PASS_WITH_FEATURE_WARNINGS',
 'notebook_05_final_acceptance_verified': True,
 'notebook_06_authorized': True,
 'observational_unit': 'PRIMARY_SCORING_BATCH',
 'feature_table_rows': 13564,
 'feature_table_columns': 577,
 'feature_count': 571,
 'future_label_table_rows': 13564,
 'future_label_table_columns': 146,
 'future_label_count': 140,
 'persisted_artifact_count': 12,
 'readback_verified_artifact_count': 12,
 'feature_missing_value_count': 48918,
 'label_missing_value_count': 21660,
 'feature_infinite_value_count': 0,
 'label_infinite_value_count': 0,
 'blocking_failure_count': 0,
 'warning_count': 2,
 'primary_feature_table_payload_sha256': 'a1a04cd8c480e1e62c22e4b4a349d56f3211d7b0af91cccaa849cd9c30923660',
 'primary_label_table_payload_sha256': '3db6e476a2e1f3476a94f8eea4b1dfac59e30a711d33bf93425a56a070adb5ba',
 'output_manifest_payload_sha256': 'b83bf3be102042259849e08afce17aba2bb1883b5cced04a57408f2524f0f168',
 'handoff_payload_sha256': '89fb688420909c230e82bf8b43575d8a5f144ac372846a9a40fcfd1476966ce7',
 'final_acceptance_payload_sha256': '199c7cc486f1f6b4878d4370c59737fb6e9a781efedf935b5de8ac9fd0efee42',
 'output_manifest_path': 'D:\\Clown Project\\V0.1\\artifacts\\manifests\\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__notebook_05_output_manifest.json',
 'handoff_path': 'D:\\Clown Project\\V0.1\\artifacts\\handoff\\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__to_06_POINT_PROCESS_BASELINES__handoff.json',
 'final_acceptance_report_path': 'D:\\Clown Project\\V0.1\\artifacts\\manifests\\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__05_MARKET_STATE_FEATURES__final_acceptance_report.json',
 'verified_at_utc': '2026-07-19T11:03:52.023730+00:00'}