# V0.1 Final Audit, Comprehensive Synthesis, and V0.2 Handoff

**Notebook:** `10_V01_FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF.ipynb`  
**Project:** The Clown Project  
**Version:** V0.1  
**Stage:** Final closure and successor-version handoff  
**Execution mode:** Clean-kernel, persisted-input-only, fail-closed  

---

## Purpose

This notebook closes V0.1 by independently auditing and synthesizing the persisted outputs of the completed V0.1 pipeline, preserving all information required to begin V0.2 without relying on the continued presence of V0.1 Notebooks 00–09.

Its responsibilities are to:

1. verify the integrity, identity, lineage, and acceptance status of all authoritative V0.1 artifacts;
2. reconstruct the complete methodological and computational record of V0.1 from persisted files;
3. distinguish established findings, rejected claims, unresolved questions, and source-specific results;
4. identify which code, contracts, schemas, tests, methods, and artifacts may be carried into V0.2;
5. confirm that no indispensable implementation remains stored only inside an upstream notebook;
6. produce a complete, machine-readable and human-readable V0.1-to-V0.2 handoff;
7. determine whether V0.1 Notebooks 00–09 may be removed from the active project folder without losing necessary information;
8. close V0.1 without refitting models, replacing models, changing upstream decisions, or opening protected data.

This notebook is not an additional research or model-development stage. It is the authoritative V0.1 closure record and the bootstrap authority for V0.2.

---

## Controlling Upstream Result

Notebook 08 closed the V0.1 Hawkes diagnostic branch with the following interpretation:

- the causal data-engineering pipeline was successfully completed;
- the selected H1 Hawkes specification showed locked count-score improvement over authorized simpler baselines;
- H1 failed the required generative-adequacy diagnostics;
- H1 was not accepted as the authoritative V0.1 intensity signal;
- Notebook 09 intensity-signal validation was not authorized and was skipped;
- no Hawkes-adjusted quoting or market-making claim was authorized;
- protected validation and engineering-holdout data remained unopened;
- V0.1 must proceed directly to final audit, synthesis, closure, and V0.2 handoff.

Notebook 10 must preserve this result exactly. It may audit and explain it, but it may not weaken, reverse, repair, or reinterpret the controlling decision.

---

## Authoritative Execution Rules

This notebook must:

- start from a clean kernel;
- read only persisted inputs and manifests from disk;
- avoid dependence on variables, functions, or hidden state from another notebook;
- verify artifact identities, hashes, schemas, row counts, and semantic contents;
- preserve the distinction between the V0.0 source identity and the V0.1 run identity;
- treat V0.0 source files and reference artifacts as read-only;
- write only to registered V0.1 final-audit, synthesis, archive, and handoff locations;
- fail on missing authoritative inputs, unexplained material discrepancies, hash mismatches, or unsafe deletion dependencies;
- record every warning, discrepancy, limitation, and disposition;
- use portable, explicitly versioned output formats;
- perform semantic readback and final hash verification on every authoritative output;
- preserve the final accepted and rejected decisions of each upstream stage.

This notebook must not:

- refit or tune any model;
- replace H1 with another model;
- alter an upstream event definition, feature definition, split, threshold, or diagnostic;
- use validation or holdout observations for new analysis;
- perform market-making simulation or strategy evaluation;
- convert rejected claims into accepted claims;
- silently repair upstream artifacts;
- infer authoritative values from notebook display output when persisted artifacts exist;
- select files using ambiguous rules such as “latest file”;
- authorize deletion while required logic or specifications remain available only inside Notebooks 00–09.

---

## Required Final Products

The notebook must produce, at minimum:

- the final V0.1 stage-by-stage synthesis;
- the final authority and claim ledgers;
- the master V0.1 artifact catalogue;
- the end-to-end data-lineage and row-count reconciliation;
- the accepted, rejected, unresolved, and source-specific findings registry;
- the reusable-code and notebook-only dependency inventory;
- the V0.1 carry-forward, revalidation, reference-only, and do-not-inherit registry;
- the V0.1 warning, limitation, and known-failure-mode registries;
- the V0.2 source-data, methodological, split, schema, testing, and invariant contracts;
- the proposed V0.2 notebook and source-module architecture;
- the machine-readable V0.2 Notebook 00 bootstrap contract;
- the formal V0.1-to-V0.2 handoff;
- the V0.1 deletion-readiness report;
- the frozen-archive verification report;
- the final semantic-readback report;
- the final output manifest and hash-verification report.

---

## Closure Standard

V0.1 may be declared closed only when:

1. all authoritative upstream artifacts are discovered and verified;
2. all material row-count and lineage transitions reconcile;
3. every upstream stage has an explicit terminal status;
4. Notebook 09 is formally recorded as skipped and unauthorized;
5. no protected partition was opened;
6. no post-diagnostic refitting or model replacement occurred;
7. every reusable implementation is externalized or fully specified;
8. no required information remains available only through Notebooks 00–09;
9. the V0.2 bootstrap contract passes independent semantic readback;
10. the frozen V0.1 archive exists and verifies;
11. all final outputs pass semantic and checksum validation;
12. no blocking item remains in the deletion-readiness report.

The intended terminal classification is:

> **V0.1 CLOSED — ENGINEERING PASS — H1 COUNT-SCORE ADVANTAGE RETAINED — H1 GENERATIVE ADEQUACY REJECTED — NOTEBOOK 09 SKIPPED — PREDICTIVE VALUE UNTESTED — PROTECTED PARTITIONS UNOPENED — V0.2 HANDOFF COMPLETE**

Authorization to remove V0.1 Notebooks 00–09 from the active project folder may be issued only after all deletion-safety and archive-verification gates pass.

In [1]:
from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Final, Mapping

import hashlib
import json
import math
import os
import platform
import random
import re
import shutil
import subprocess
import sys
import warnings

import numpy as np
import pandas as pd
from IPython.display import display


# ============================================================
# Runtime contract
# ============================================================

MINIMUM_PYTHON_VERSION: Final[tuple[int, int]] = (3, 10)

if sys.version_info < MINIMUM_PYTHON_VERSION:
    required_version = ".".join(
        map(
            str,
            MINIMUM_PYTHON_VERSION,
        )
    )
    observed_version = platform.python_version()

    raise RuntimeError(
        f"Python {required_version} or newer is required; "
        f"observed Python {observed_version}."
    )

warnings.filterwarnings(
    "error",
    category=pd.errors.SettingWithCopyWarning,
)

pd.options.display.max_columns = 250
pd.options.display.width = 200
pd.options.display.max_colwidth = 160
pd.options.display.float_format = "{:,.10g}".format


# ============================================================
# Notebook identity
# ============================================================

PIPELINE_NAME: Final[str] = "The Clown Project"
PIPELINE_VERSION: Final[str] = "V0.1"

NOTEBOOK_NUMBER: Final[str] = "10"
NOTEBOOK_NAME: Final[str] = (
    "10_V01_FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF.ipynb"
)
NOTEBOOK_STAGE: Final[str] = (
    "FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF"
)
NOTEBOOK_PURPOSE: Final[str] = (
    "Deletion-safe V0.1 closure and complete V0.2 bootstrap handoff"
)

NOTEBOOK10_SCHEMA_VERSION: Final[str] = "NOTEBOOK_10_CONTRACT_V1"
INITIAL_NOTEBOOK_STATUS: Final[str] = "NOT_EVALUATED"


# ============================================================
# Frozen project identity
# ============================================================

SOURCE_RUN_PREFIX: Final[str] = (
    "BTCUSDT_spot_20260710T063746Z_c8b5bf12"
)

V01_RUN_ID: Final[str] = (
    "v0_1_20260714T090616Z_e82325081a81"
)

COMBINED_OUTPUT_PREFIX: Final[str] = (
    f"{SOURCE_RUN_PREFIX}__{V01_RUN_ID}"
)

SOURCE_SET_SHA256: Final[str] = (
    "132c83531eec615d279408b5c06f4029"
    "73114ba3058dfadd2fe58e2e67184c4b"
)

RUN_CONFIG_SHA256: Final[str] = (
    "14aea0efb3c7b6a193b8c4575a440bab"
    "e8265d2935c6a770bee995f688d59617"
)

RUN_IDENTITY_SHA256: Final[str] = (
    "5eb89cf073c036d70e3767df4b35ace7"
    "c31822e52e9b9df19204c42e37fe4198"
)


# ============================================================
# Frozen Notebook 08 authority
# ============================================================

EXPECTED_NOTEBOOK08_TERMINAL_CLASS: Final[str] = "FAIL"

EXPECTED_NOTEBOOK08_TERMINAL_STATUS: Final[str] = (
    "FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_"
    "DESPITE_SCORE_SUPERIORITY"
)

EXPECTED_HAWKES_COUNT_SCORE_SUPERIORITY: Final[bool] = True
EXPECTED_HAWKES_GENERATIVE_ADEQUACY: Final[bool] = False

EXPECTED_NOTEBOOK09_AUTHORIZED: Final[bool] = False
EXPECTED_NOTEBOOK09_STATUS: Final[str] = (
    "SKIPPED_AND_UNAUTHORIZED"
)

EXPECTED_VALIDATION_CONTENT_LOADED: Final[bool] = False
EXPECTED_ENGINEERING_HOLDOUT_CONTENT_LOADED: Final[bool] = False

EXPECTED_CALIBRATION_PARAMETER_UPDATES: Final[int] = 0
EXPECTED_POST_DIAGNOSTIC_REFITS: Final[int] = 0
EXPECTED_MODEL_REPLACEMENTS: Final[int] = 0

EXPECTED_SELECTED_MODEL_ID: Final[str] = (
    "H1_DIAGONAL_SHARED_DECAY"
)

EXPECTED_SELECTED_MODEL_FAMILY: Final[str] = (
    "DIAGONAL_BIVARIATE_EXPONENTIAL_HAWKES"
)

EXPECTED_HAWKES_ALLOWED_ROLE: Final[str] = (
    "DIAGNOSTIC_REFERENCE_AND_FAILURE_ANALYSIS_ONLY"
)

EXPECTED_HAWKES_DISPOSITION: Final[str] = (
    "REJECTED_FOR_DOWNSTREAM_SIGNAL_AUTHORIZATION"
)


# ============================================================
# Frozen event and timing authority
# ============================================================

PRIMARY_EVENT_REPRESENTATION: Final[str] = (
    "SAME_MS_SAME_SIDE_BURSTS"
)

PRIMARY_EVENT_TIME_COLUMN: Final[str] = "event_time_ns"
PRIMARY_EVENT_PARTITION_COLUMN: Final[str] = "event_partition"

PRIMARY_TIMESTAMP_INTERFACE: Final[str] = (
    "SIMULTANEOUS_EVENT_BATCH_REQUIRED"
)

PRIMARY_SCORING_RULE: Final[str] = "STRICT_PRE_BATCH"

CANONICAL_TIMEZONE: Final[str] = "UTC"
EVENT_TIME_STORAGE_UNIT: Final[str] = "NANOSECONDS"
MODEL_TIME_UNIT: Final[str] = "SECONDS"

PROTECTED_PARTITIONS: Final[tuple[str, str]] = (
    "VALIDATION",
    "ENGINEERING_HOLDOUT",
)

TIMESTAMP_JITTER_ALLOWED: Final[bool] = False
EVENT_REORDERING_ALLOWED: Final[bool] = False
WITHIN_BATCH_ZERO_LAG_EXCITATION_ALLOWED: Final[bool] = False
FABRICATED_PREHISTORY_ALLOWED: Final[bool] = False


# ============================================================
# Project roots
# ============================================================

PROJECT_ROOT: Final[Path] = Path(r"D:\Clown Project")

V00_ROOT: Final[Path] = PROJECT_ROOT / "V0.0"
V01_ROOT: Final[Path] = PROJECT_ROOT / "V0.1"
V02_ROOT: Final[Path] = PROJECT_ROOT / "V0.2"

V01_NOTEBOOK_ROOT: Final[Path] = V01_ROOT / "notebooks"
V01_CONFIG_ROOT: Final[Path] = V01_ROOT / "config"
V01_SOURCE_ROOT: Final[Path] = V01_ROOT / "src"
V01_TEST_ROOT: Final[Path] = V01_ROOT / "tests"
V01_LOG_ROOT: Final[Path] = V01_ROOT / "logs"

V01_DATA_ROOT: Final[Path] = V01_ROOT / "data"
V01_INTERIM_ROOT: Final[Path] = V01_DATA_ROOT / "interim"
V01_PROCESSED_ROOT: Final[Path] = V01_DATA_ROOT / "processed"

V01_ARTIFACT_ROOT: Final[Path] = V01_ROOT / "artifacts"
V01_MANIFEST_ROOT: Final[Path] = V01_ARTIFACT_ROOT / "manifests"
V01_AUDIT_ROOT: Final[Path] = V01_ARTIFACT_ROOT / "audit_tables"
V01_DIAGNOSTIC_ROOT: Final[Path] = (
    V01_ARTIFACT_ROOT / "diagnostics"
)
V01_RECONCILIATION_ROOT: Final[Path] = (
    V01_ARTIFACT_ROOT / "reconciliation"
)
V01_MODEL_ROOT: Final[Path] = V01_ARTIFACT_ROOT / "models"
V01_FIGURE_ROOT: Final[Path] = V01_ARTIFACT_ROOT / "figures"
V01_HANDOFF_ROOT: Final[Path] = V01_ARTIFACT_ROOT / "handoff"
V01_SYNTHESIS_ROOT: Final[Path] = V01_ARTIFACT_ROOT / "synthesis"

PROJECT_FROZEN_ARCHIVE_ROOT: Final[Path] = (
    PROJECT_ROOT / "_frozen_archives"
)

V01_FROZEN_ARCHIVE_ROOT: Final[Path] = (
    PROJECT_FROZEN_ARCHIVE_ROOT / "V0.1"
)


# ============================================================
# Notebook 10 output roots
# ============================================================

NOTEBOOK10_AUDIT_ROOT: Final[Path] = (
    V01_AUDIT_ROOT / "10_final_audit"
)

NOTEBOOK10_SYNTHESIS_ROOT: Final[Path] = (
    V01_SYNTHESIS_ROOT / "10_final_audit"
)

NOTEBOOK10_RECONCILIATION_ROOT: Final[Path] = (
    V01_RECONCILIATION_ROOT / "10_final_audit"
)

NOTEBOOK10_HANDOFF_ROOT: Final[Path] = (
    V01_HANDOFF_ROOT / "10_v01_to_v02"
)

NOTEBOOK10_MANIFEST_ROOT: Final[Path] = (
    V01_MANIFEST_ROOT / "10_final_audit"
)

V02_BOOTSTRAP_PACKAGE_ROOT: Final[Path] = (
    NOTEBOOK10_HANDOFF_ROOT / "v0_2_bootstrap"
)


# ============================================================
# Controlling Notebook 08 artifacts
# ============================================================

NOTEBOOK08_TO_10_HANDOFF_PATH: Final[Path] = (
    V01_HANDOFF_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_to_10_final_audit_handoff.json"
    )
)

NOTEBOOK08_TO_09_BLOCKED_HANDOFF_PATH: Final[Path] = (
    V01_HANDOFF_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_to_09_intensity_signal_validation_blocked.json"
    )
)

NOTEBOOK08_FINAL_DISPOSITION_PATH: Final[Path] = (
    V01_MANIFEST_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_hawkes_diagnostics_final_disposition.json"
    )
)

NOTEBOOK08_OUTPUT_MANIFEST_PATH: Final[Path] = (
    V01_MANIFEST_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_hawkes_diagnostics_output_manifest.json"
    )
)

NOTEBOOK08_SEMANTIC_READBACK_PATH: Final[Path] = (
    V01_MANIFEST_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_semantic_readback_audit.json"
    )
)


# ============================================================
# Deterministic execution
# ============================================================

RANDOM_SEED: Final[int] = 20260724

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

RNG = np.random.default_rng(
    RANDOM_SEED
)

EXECUTION_STARTED_UTC: Final[str] = (
    datetime.now(timezone.utc)
    .replace(microsecond=0)
    .isoformat()
)


# ============================================================
# Numerical and hashing conventions
# ============================================================

HASH_ALGORITHM: Final[str] = "sha256"

FLOAT_RELATIVE_TOLERANCE: Final[float] = 1e-8
FLOAT_ABSOLUTE_TOLERANCE: Final[float] = 1e-10

JSON_ENCODING: Final[str] = "utf-8"

PORTABLE_HUMAN_READABLE_FORMATS: Final[tuple[str, ...]] = (
    "csv",
    "json",
    "md",
)

PORTABLE_MACHINE_READABLE_FORMATS: Final[tuple[str, ...]] = (
    "json",
    "csv",
    "npz",
    "parquet",
)


# ============================================================
# Immutable Notebook 10 configuration
# ============================================================

@dataclass(frozen=True, slots=True)
class Notebook10Config:
    """Immutable controlling configuration for V0.1 closure."""

    pipeline_name: str
    pipeline_version: str
    notebook_number: str
    notebook_name: str
    notebook_stage: str
    notebook_purpose: str
    schema_version: str
    source_run_prefix: str
    v01_run_id: str
    source_set_sha256: str
    run_config_sha256: str
    run_identity_sha256: str
    expected_notebook08_terminal_status: str
    expected_notebook09_authorized: bool
    protected_partitions: tuple[str, ...]
    primary_event_representation: str
    primary_scoring_rule: str
    canonical_timezone: str
    random_seed: int
    hash_algorithm: str
    v00_root: str
    v01_root: str
    v02_root: str
    frozen_archive_root: str
    execution_started_utc: str


NOTEBOOK10_CONFIG: Final[Notebook10Config] = Notebook10Config(
    pipeline_name=PIPELINE_NAME,
    pipeline_version=PIPELINE_VERSION,
    notebook_number=NOTEBOOK_NUMBER,
    notebook_name=NOTEBOOK_NAME,
    notebook_stage=NOTEBOOK_STAGE,
    notebook_purpose=NOTEBOOK_PURPOSE,
    schema_version=NOTEBOOK10_SCHEMA_VERSION,
    source_run_prefix=SOURCE_RUN_PREFIX,
    v01_run_id=V01_RUN_ID,
    source_set_sha256=SOURCE_SET_SHA256,
    run_config_sha256=RUN_CONFIG_SHA256,
    run_identity_sha256=RUN_IDENTITY_SHA256,
    expected_notebook08_terminal_status=(
        EXPECTED_NOTEBOOK08_TERMINAL_STATUS
    ),
    expected_notebook09_authorized=(
        EXPECTED_NOTEBOOK09_AUTHORIZED
    ),
    protected_partitions=PROTECTED_PARTITIONS,
    primary_event_representation=(
        PRIMARY_EVENT_REPRESENTATION
    ),
    primary_scoring_rule=PRIMARY_SCORING_RULE,
    canonical_timezone=CANONICAL_TIMEZONE,
    random_seed=RANDOM_SEED,
    hash_algorithm=HASH_ALGORITHM,
    v00_root=str(V00_ROOT),
    v01_root=str(V01_ROOT),
    v02_root=str(V02_ROOT),
    frozen_archive_root=str(V01_FROZEN_ARCHIVE_ROOT),
    execution_started_utc=EXECUTION_STARTED_UTC,
)

NOTEBOOK10_CONFIG_PAYLOAD: Final[dict[str, Any]] = asdict(
    NOTEBOOK10_CONFIG
)

NOTEBOOK10_CONFIG_SHA256: Final[str] = hashlib.sha256(
    json.dumps(
        NOTEBOOK10_CONFIG_PAYLOAD,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode(
        JSON_ENCODING
    )
).hexdigest()


# ============================================================
# Mutable execution-state sentinels
#
# These begin in the most restrictive state and may be changed
# only by later cells after explicit gates pass.
# ============================================================

PROJECT_ARTIFACT_READS_PERFORMED = False
FILESYSTEM_WRITES_PERFORMED = False

CONTROLLING_HANDOFF_VERIFIED = False
UPSTREAM_ARTIFACTS_VERIFIED = False
STAGE_SYNTHESIS_COMPLETE = False
LINEAGE_RECONCILIATION_COMPLETE = False
CLAIM_LEDGER_COMPLETE = False
CARRY_FORWARD_REGISTRY_COMPLETE = False
V02_BOOTSTRAP_CONTRACT_COMPLETE = False
FROZEN_ARCHIVE_VERIFIED = False
DELETION_READINESS_COMPLETE = False
DELETION_AUTHORIZED = False

PROTECTED_PARTITION_CONTENT_LOADED = False
VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

V02_PROJECT_OUTPUT_WRITES_PERFORMED = False


# ============================================================
# Runtime identity display
# ============================================================

RUNTIME_IDENTITY = pd.DataFrame(
    [
        {
            "field": "pipeline_name",
            "value": PIPELINE_NAME,
        },
        {
            "field": "pipeline_version",
            "value": PIPELINE_VERSION,
        },
        {
            "field": "notebook",
            "value": NOTEBOOK_NAME,
        },
        {
            "field": "notebook_stage",
            "value": NOTEBOOK_STAGE,
        },
        {
            "field": "source_run_prefix",
            "value": SOURCE_RUN_PREFIX,
        },
        {
            "field": "v0_1_run_id",
            "value": V01_RUN_ID,
        },
        {
            "field": "notebook10_config_sha256",
            "value": NOTEBOOK10_CONFIG_SHA256,
        },
        {
            "field": "python_version",
            "value": platform.python_version(),
        },
        {
            "field": "numpy_version",
            "value": np.__version__,
        },
        {
            "field": "pandas_version",
            "value": pd.__version__,
        },
        {
            "field": "platform",
            "value": platform.platform(),
        },
        {
            "field": "execution_started_utc",
            "value": EXECUTION_STARTED_UTC,
        },
        {
            "field": "initial_status",
            "value": INITIAL_NOTEBOOK_STATUS,
        },
    ]
)

display(
    RUNTIME_IDENTITY.style.hide(
        axis="index"
    )
)

# This cell performs no project-artifact reads, creates no
# directories, writes no files, opens no protected partition,
# and changes no upstream research decision.

In [3]:
# ============================================================
# Notebook 08 controlling-artifact resolution
#
# Exact-path only:
# - no "latest file" selection
# - no wildcard substitution
# - no recursive fallback to similarly named artifacts
# - no filesystem writes
# ============================================================


class ControllingArtifactError(RuntimeError):
    """Raised when a required Notebook 08 authority cannot be trusted."""


# ------------------------------------------------------------
# Exact Notebook 08 persisted authorities
# ------------------------------------------------------------

NOTEBOOK08_SEMANTIC_READBACK_AUDIT_PATH: Final[Path] = (
    V01_MANIFEST_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_hawkes_diagnostics_semantic_readback_audit.json"
    )
)

NOTEBOOK08_CORE_OUTPUT_MANIFEST_PATH: Final[Path] = (
    V01_MANIFEST_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_hawkes_diagnostics_core_output_manifest.json"
    )
)

NOTEBOOK08_FINAL_OUTPUT_MANIFEST_PATH: Final[Path] = (
    V01_MANIFEST_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_hawkes_diagnostics_output_manifest.json"
    )
)

NOTEBOOK08_FINAL_DISPOSITION_PATH = (
    V01_MANIFEST_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_hawkes_diagnostics_final_disposition.json"
    )
)

NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF_PATH: Final[Path] = (
    V01_HANDOFF_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_to_09_intensity_signal_validation_blocked.json"
    )
)

NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF_PATH: Final[Path] = (
    V01_HANDOFF_ROOT
    / (
        COMBINED_OUTPUT_PREFIX
        + "__08_to_10_final_audit_handoff.json"
    )
)


# Preserve the shorter aliases expected by later Notebook 10 cells.

NOTEBOOK08_SEMANTIC_READBACK_PATH = (
    NOTEBOOK08_SEMANTIC_READBACK_AUDIT_PATH
)

NOTEBOOK08_OUTPUT_MANIFEST_PATH = (
    NOTEBOOK08_FINAL_OUTPUT_MANIFEST_PATH
)

NOTEBOOK08_TO_09_BLOCKED_HANDOFF_PATH = (
    NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF_PATH
)

NOTEBOOK08_TO_10_HANDOFF_PATH = (
    NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF_PATH
)


# ------------------------------------------------------------
# Exact authority registry
# ------------------------------------------------------------

CONTROLLING_ARTIFACT_PATHS: Final[dict[str, Path]] = {
    "NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF": (
        NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF_PATH
    ),
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF": (
        NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF_PATH
    ),
    "NOTEBOOK08_FINAL_DISPOSITION": (
        NOTEBOOK08_FINAL_DISPOSITION_PATH
    ),
    "NOTEBOOK08_SEMANTIC_READBACK_AUDIT": (
        NOTEBOOK08_SEMANTIC_READBACK_AUDIT_PATH
    ),
    "NOTEBOOK08_CORE_OUTPUT_MANIFEST": (
        NOTEBOOK08_CORE_OUTPUT_MANIFEST_PATH
    ),
    "NOTEBOOK08_FINAL_OUTPUT_MANIFEST": (
        NOTEBOOK08_FINAL_OUTPUT_MANIFEST_PATH
    ),
}


# ------------------------------------------------------------
# Read-only integrity helpers
# ------------------------------------------------------------

def normalized_resolved_path(path: Path) -> Path:
    """Return an absolute normalized path without requiring existence."""

    return Path(
        os.path.normcase(
            os.path.abspath(
                os.fspath(path)
            )
        )
    )


def require_path_inside_root(
    path: Path,
    authorized_root: Path,
    role: str,
) -> None:
    """Fail when an authority resolves outside its authorized root."""

    candidate = normalized_resolved_path(path)
    root = normalized_resolved_path(authorized_root)

    try:
        candidate.relative_to(root)
    except ValueError as exc:
        raise ControllingArtifactError(
            f"Artifact for role {role} is outside the authorized root.\n"
            f"Artifact: {candidate}\n"
            f"Authorized root: {root}"
        ) from exc


def sha256_file(
    path: Path,
    chunk_size: int = 1_048_576,
) -> str:
    """Compute SHA-256 without loading the whole file into memory."""

    digest = hashlib.sha256()

    with path.open("rb") as file_handle:
        while True:
            chunk = file_handle.read(chunk_size)

            if not chunk:
                break

            digest.update(chunk)

    return digest.hexdigest()


def load_json_object(
    path: Path,
    role: str,
) -> dict[str, Any]:
    """Load a required JSON object and reject non-object payloads."""

    try:
        with path.open(
            "r",
            encoding=JSON_ENCODING,
        ) as file_handle:
            payload = json.load(file_handle)

    except json.JSONDecodeError as exc:
        raise ControllingArtifactError(
            f"Invalid JSON for role {role}: {path}\n"
            f"JSON error: {exc}"
        ) from exc

    except OSError as exc:
        raise ControllingArtifactError(
            f"Unable to read artifact for role {role}: {path}\n"
            f"Filesystem error: {exc}"
        ) from exc

    if not isinstance(payload, dict):
        raise ControllingArtifactError(
            f"Artifact for role {role} must contain a JSON object.\n"
            f"Observed type: {type(payload).__name__}\n"
            f"Path: {path}"
        )

    return payload


def extract_declared_schema(
    payload: Mapping[str, Any],
) -> str | None:
    """Return the first available top-level schema declaration."""

    candidate_keys = (
        "artifact_schema",
        "schema_name",
        "schema_id",
        "schema_version",
        "contract_schema",
    )

    for key in candidate_keys:
        value = payload.get(key)

        if value is not None:
            return str(value)

    return None


# ------------------------------------------------------------
# Resolve, hash and parse every controlling authority
# ------------------------------------------------------------

resolved_controlling_artifacts: dict[str, Path] = {}
controlling_artifact_payloads: dict[str, dict[str, Any]] = {}
controlling_artifact_records: list[dict[str, Any]] = []
controlling_artifact_errors: list[str] = []

for artifact_role, declared_path in CONTROLLING_ARTIFACT_PATHS.items():
    artifact_path = normalized_resolved_path(
        declared_path
    )

    base_record: dict[str, Any] = {
        "role": artifact_role,
        "path": str(artifact_path),
        "required": True,
        "exists": artifact_path.exists(),
        "is_file": artifact_path.is_file(),
        "size_bytes": None,
        "modified_utc": None,
        "sha256": None,
        "top_level_key_count": None,
        "declared_schema": None,
        "status": "NOT_EVALUATED",
        "error": None,
    }

    try:
        require_path_inside_root(
            path=artifact_path,
            authorized_root=V01_ARTIFACT_ROOT,
            role=artifact_role,
        )

        require_path_inside_root(
            path=artifact_path,
            authorized_root=V01_ROOT,
            role=artifact_role,
        )

        if not artifact_path.exists():
            raise ControllingArtifactError(
                f"Required artifact does not exist for role "
                f"{artifact_role}: {artifact_path}"
            )

        if not artifact_path.is_file():
            raise ControllingArtifactError(
                f"Required artifact is not a regular file for role "
                f"{artifact_role}: {artifact_path}"
            )

        file_stat = artifact_path.stat()
        payload = load_json_object(
            path=artifact_path,
            role=artifact_role,
        )

        artifact_sha256 = sha256_file(
            artifact_path
        )

        resolved_controlling_artifacts[
            artifact_role
        ] = artifact_path

        controlling_artifact_payloads[
            artifact_role
        ] = payload

        base_record.update(
            {
                "exists": True,
                "is_file": True,
                "size_bytes": int(
                    file_stat.st_size
                ),
                "modified_utc": (
                    datetime.fromtimestamp(
                        file_stat.st_mtime,
                        tz=timezone.utc,
                    )
                    .replace(
                        microsecond=0
                    )
                    .isoformat()
                ),
                "sha256": artifact_sha256,
                "top_level_key_count": int(
                    len(payload)
                ),
                "declared_schema": (
                    extract_declared_schema(
                        payload
                    )
                ),
                "status": "PASS",
            }
        )

    except Exception as exc:
        error_message = (
            f"{artifact_role}: {exc}"
        )

        controlling_artifact_errors.append(
            error_message
        )

        base_record.update(
            {
                "status": "FAIL",
                "error": str(exc),
            }
        )

    controlling_artifact_records.append(
        base_record
    )


CONTROLLING_ARTIFACT_RESOLUTION = pd.DataFrame(
    controlling_artifact_records
)


# ------------------------------------------------------------
# Display before enforcing the final gate
# ------------------------------------------------------------

display(
    CONTROLLING_ARTIFACT_RESOLUTION[
        [
            "role",
            "path",
            "required",
            "exists",
            "is_file",
            "size_bytes",
            "sha256",
            "top_level_key_count",
            "declared_schema",
            "status",
            "error",
        ]
    ]
)


# ------------------------------------------------------------
# Blocking resolution gate
# ------------------------------------------------------------

if controlling_artifact_errors:
    rendered_errors = "\n\n".join(
        f"- {error}"
        for error in controlling_artifact_errors
    )

    raise ControllingArtifactError(
        "Notebook 08 controlling-artifact resolution failed:\n\n"
        f"{rendered_errors}"
    )

expected_roles = set(
    CONTROLLING_ARTIFACT_PATHS
)

resolved_roles = set(
    resolved_controlling_artifacts
)

if resolved_roles != expected_roles:
    missing_roles = sorted(
        expected_roles - resolved_roles
    )

    unexpected_roles = sorted(
        resolved_roles - expected_roles
    )

    raise ControllingArtifactError(
        "Controlling-artifact role reconciliation failed.\n"
        f"Missing roles: {missing_roles}\n"
        f"Unexpected roles: {unexpected_roles}"
    )

if not CONTROLLING_ARTIFACT_RESOLUTION[
    "status"
].eq(
    "PASS"
).all():
    raise ControllingArtifactError(
        "At least one controlling artifact did not pass resolution."
    )


# ------------------------------------------------------------
# State update
#
# Resolution and JSON parsing have passed.
# Semantic authority has not yet been verified.
# ------------------------------------------------------------

PROJECT_ARTIFACT_READS_PERFORMED = True
CONTROLLING_HANDOFF_VERIFIED = False
UPSTREAM_ARTIFACTS_VERIFIED = False

print(
    "Notebook 08 controlling artifacts resolved, hashed, and "
    "parsed successfully. No filesystem writes were performed. "
    "Protected partition content remains unopened. Semantic "
    "authority verification remains pending."
)

,role,path,required,exists,is_file,size_bytes,sha256,top_level_key_count,declared_schema,status,error
0,NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_to_10_final_audit_handoff.json,True,True,True,3004,900066c6a3b5c6c74f80f3a77403258a0115c31e3a10ff18aeafeed643f8a479,29,NOTEBOOK_08_TO_NOTEBOOK_10_FINAL_AUDIT_HANDOFF_V1,PASS,None
1,NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_to_09_intensity_signal_validation_blo...,True,True,True,4407,e4c0b3f7800e077117cb95109bd52d2700c2a0ea61175358a4e60febb9034a20,30,NOTEBOOK_08_TO_NOTEBOOK_09_BLOCKED_HANDOFF_V1,PASS,None
2,NOTEBOOK08_FINAL_DISPOSITION,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_final_dispositio...,True,True,True,6708,3abe2261e45aec3fd8663513df0b33f3c220043ff5315783fbae7c5a2cf5656a,39,NOTEBOOK_08_HAWKES_DIAGNOSTICS_FINAL_DISPOSITION_V1,PASS,None
3,NOTEBOOK08_SEMANTIC_READBACK_AUDIT,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_semantic_readbac...,True,True,True,70829,354ee1aa1b0863a9b0d087874444089be18e324a1f84e372956054043e6a2b7f,29,NOTEBOOK_08_HAWKES_DIAGNOSTICS_SEMANTIC_READBACK_AUDIT_V1,PASS,None
4,NOTEBOOK08_CORE_OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_core_output_mani...,True,True,True,137135,e9a1e5cacb4e41b52919ffc01837ce13b640f67282c1a4f78b4322da8cb74b8e,27,NOTEBOOK_08_CORE_OUTPUT_MANIFEST_V1,PASS,None
5,NOTEBOOK08_FINAL_OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_output_manifest....,True,True,True,148665,37363e818ef0f6461a2b531b9998ee0b091e48c9fedcc42b8e99cb8ec26bcee1,40,NOTEBOOK_08_HAWKES_DIAGNOSTICS_OUTPUT_MANIFEST_V1,PASS,None

Notebook 08 controlling artifacts resolved, hashed, and parsed successfully. No filesystem writes were performed. Protected partition content remains unopened. Semantic authority verification remains pending.

In [4]:
# ============================================================
# Notebook 08 semantic-authority verification
#
# This cell:
# - verifies every controlling JSON's semantic self-hash;
# - verifies source and run identity consistency;
# - preserves the failed Hawkes adequacy decision;
# - confirms Notebook 09 remained blocked;
# - confirms protected partitions remained unopened;
# - verifies cross-artifact payload hashes and references;
# - grants Notebook 10 audit authority only after every
#   blocking semantic check passes.
#
# No filesystem writes are performed.
# No analytical event data or protected partition is opened.
# ============================================================


class SemanticAuthorityError(RuntimeError):
    """Raised when controlling Notebook 08 semantics are inconsistent."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

if not PROJECT_ARTIFACT_READS_PERFORMED:
    raise SemanticAuthorityError(
        "Controlling artifacts have not been read."
    )

if not isinstance(
    controlling_artifact_payloads,
    dict,
):
    raise SemanticAuthorityError(
        "Controlling artifact payload registry is unavailable."
    )

EXPECTED_CONTROLLING_ROLES: Final[set[str]] = {
    "NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF",
    "NOTEBOOK08_FINAL_DISPOSITION",
    "NOTEBOOK08_SEMANTIC_READBACK_AUDIT",
    "NOTEBOOK08_CORE_OUTPUT_MANIFEST",
    "NOTEBOOK08_FINAL_OUTPUT_MANIFEST",
}

observed_controlling_roles = set(
    controlling_artifact_payloads
)

if observed_controlling_roles != EXPECTED_CONTROLLING_ROLES:
    raise SemanticAuthorityError(
        "Controlling payload-role mismatch.\n"
        f"Expected: {sorted(EXPECTED_CONTROLLING_ROLES)}\n"
        f"Observed: {sorted(observed_controlling_roles)}"
    )


# ------------------------------------------------------------
# Expected schemas and artifact types
# ------------------------------------------------------------

EXPECTED_SCHEMA_BY_ROLE: Final[dict[str, str]] = {
    "NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF": (
        "NOTEBOOK_08_TO_NOTEBOOK_10_FINAL_AUDIT_HANDOFF_V1"
    ),
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF": (
        "NOTEBOOK_08_TO_NOTEBOOK_09_BLOCKED_HANDOFF_V1"
    ),
    "NOTEBOOK08_FINAL_DISPOSITION": (
        "NOTEBOOK_08_HAWKES_DIAGNOSTICS_FINAL_DISPOSITION_V1"
    ),
    "NOTEBOOK08_SEMANTIC_READBACK_AUDIT": (
        "NOTEBOOK_08_HAWKES_DIAGNOSTICS_"
        "SEMANTIC_READBACK_AUDIT_V1"
    ),
    "NOTEBOOK08_CORE_OUTPUT_MANIFEST": (
        "NOTEBOOK_08_CORE_OUTPUT_MANIFEST_V1"
    ),
    "NOTEBOOK08_FINAL_OUTPUT_MANIFEST": (
        "NOTEBOOK_08_HAWKES_DIAGNOSTICS_OUTPUT_MANIFEST_V1"
    ),
}

EXPECTED_ARTIFACT_TYPE_BY_ROLE: Final[dict[str, str]] = {
    "NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF": (
        "NOTEBOOK_08_TO_NOTEBOOK_10_FINAL_AUDIT_HANDOFF"
    ),
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF": (
        "NOTEBOOK_08_TO_NOTEBOOK_09_BLOCKED_HANDOFF"
    ),
    "NOTEBOOK08_FINAL_DISPOSITION": (
        "NOTEBOOK_08_HAWKES_DIAGNOSTICS_FINAL_DISPOSITION"
    ),
    "NOTEBOOK08_SEMANTIC_READBACK_AUDIT": (
        "NOTEBOOK_08_HAWKES_DIAGNOSTICS_SEMANTIC_READBACK_AUDIT"
    ),
}

EXPECTED_NOTEBOOK08_PRODUCER: Final[str] = (
    "08_HAWKES_DIAGNOSTICS.ipynb"
)

ACCEPTED_NOTEBOOK10_CONSUMERS: Final[set[str]] = {
    "10_V01_FINAL_AUDIT_AND_HANDOFF.ipynb",
    NOTEBOOK_NAME,
}

EXPECTED_AUDIT_AUTHORIZATION_SCOPE: Final[str] = (
    "AUDIT_AND_CLOSE_FAILED_V0_1_DIAGNOSTIC_BRANCH_ONLY"
)

EXPECTED_NOTEBOOK10_HANDOFF_STATUS: Final[str] = (
    "PASS_HANDOFF_TO_FINAL_AUDIT_AFTER_DIAGNOSTIC_FAILURE"
)

EXPECTED_NOTEBOOK09_BLOCKED_STATUS: Final[str] = (
    "BLOCKED_BY_NOTEBOOK08_DIAGNOSTIC_FAILURE"
)

EXPECTED_FINAL_DISPOSITION_STATUS: Final[str] = (
    "PASS_FINALIZATION_OF_FAILED_DIAGNOSTIC_RESULT"
)

EXPECTED_SEMANTIC_READBACK_STATUS: Final[str] = (
    "PASS_SEMANTIC_READBACK_OF_FAILED_DIAGNOSTIC_RESULT"
)

EXPECTED_NEXT_AUTHORIZED_OPERATION: Final[str] = (
    "BEGIN_NOTEBOOK10_FINAL_AUDIT_WITH_NOTEBOOK09_SKIPPED"
)

EXPECTED_NOTEBOOK09_BLOCKING_REASON: Final[str] = (
    "FROZEN_H1_FAILED_LOCKED_CALIBRATION_MODEL_ADEQUACY"
)

EXPECTED_NOTEBOOK09_PERMITTED_USE: Final[str] = (
    "DIAGNOSTIC_REFERENCE_AND_FAILURE_ANALYSIS_ONLY"
)

REQUIRED_AUDIT_FINDINGS: Final[set[str]] = {
    "PRESERVE_SUPPORTED_COUNT_SCORE_SUPERIORITY_AS_NARROW_EVIDENCE",
    "PRESERVE_FAILED_MODEL_ADEQUACY_AS_BLOCKING_EVIDENCE",
    "RECORD_NOTEBOOK09_AS_SKIPPED_NOT_PASSED",
    "RECORD_VALIDATION_AS_UNOPENED",
    "RECORD_ENGINEERING_HOLDOUT_AS_UNOPENED",
    "PRESERVE_FROZEN_H1_WITHOUT_REFIT_OR_REPAIR",
    "CLOSE_V0_1_WITHOUT_STRATEGY_OR_SIGNAL_AUTHORIZATION",
}

REQUIRED_PROHIBITED_ACTIONS: Final[set[str]] = {
    "OPEN_VALIDATION_EVENT_CONTENT",
    "OPEN_ENGINEERING_HOLDOUT_EVENT_CONTENT",
    "RUN_INCREMENTAL_INTENSITY_SIGNAL_VALIDATION",
    "USE_H1_AS_AN_AUTHORIZED_SIGNAL",
    "CLAIM_FULL_HAWKES_SUPERIORITY",
    "AUTHORIZE_QUOTING_OR_STRATEGY_LOGIC",
}

EXPECTED_BLOCKING_FINDINGS: Final[dict[str, bool]] = {
    "time_rescaling_distribution_adequacy_passed": False,
    "time_rescaling_serial_independence_passed": False,
    "path_count_calibration_passed": False,
    "exact_time_multiplicity_adequacy_passed": False,
}

EXPECTED_NARROW_FINDINGS: Final[dict[str, bool]] = {
    "count_score_superiority_over_authorized_baselines": True,
    "stationarity_margin_passed": True,
    "side_mark_directional_calibration_passed": True,
}


# ------------------------------------------------------------
# Strict semantic-hash helper
# ------------------------------------------------------------

def canonical_json_sha256_strict(
    payload: Any,
) -> str:
    """Return the Notebook 08 canonical semantic JSON hash."""

    canonical_bytes = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode(
        JSON_ENCODING
    )

    return hashlib.sha256(
        canonical_bytes
    ).hexdigest()


def normalized_reference_path(
    reference: str | Path,
) -> Path:
    """Resolve one V0.1-relative or absolute artifact reference."""

    reference_path = Path(
        str(reference)
    )

    candidate = (
        reference_path
        if reference_path.is_absolute()
        else V01_ROOT / reference_path
    )

    return normalized_resolved_path(
        candidate
    )


def render_check_value(
    value: Any,
) -> str:
    """Render compact deterministic values for the audit table."""

    if value is _MISSING:
        return "<MISSING>"

    if isinstance(
        value,
        set,
    ):
        return repr(
            sorted(value)
        )

    if isinstance(
        value,
        dict,
    ):
        return json.dumps(
            value,
            sort_keys=True,
            ensure_ascii=False,
            allow_nan=False,
        )

    return repr(
        value
    )


_MISSING = object()

semantic_authority_checks: list[dict[str, Any]] = []


def register_semantic_check(
    *,
    check_name: str,
    source_role: str,
    observed: Any,
    expected: Any,
    passed: bool | None = None,
    blocking: bool = True,
) -> None:
    """Register one semantic-authority check without failing early."""

    check_passed = (
        observed == expected
        if passed is None
        else bool(passed)
    )

    semantic_authority_checks.append(
        {
            "check_order": len(
                semantic_authority_checks
            )
            + 1,
            "check_name": check_name,
            "source_role": source_role,
            "blocking": bool(
                blocking
            ),
            "observed": render_check_value(
                observed
            ),
            "expected": render_check_value(
                expected
            ),
            "passed": bool(
                check_passed
            ),
            "status": (
                "PASS"
                if check_passed
                else (
                    "FAIL"
                    if blocking
                    else "WARNING"
                )
            ),
        }
    )


def payload_value(
    role: str,
    key: str,
) -> Any:
    """Return one top-level value or the explicit missing sentinel."""

    return controlling_artifact_payloads[
        role
    ].get(
        key,
        _MISSING,
    )


# ------------------------------------------------------------
# Verify self-hashes and schemas for all six JSON authorities
# ------------------------------------------------------------

CONTROLLING_PAYLOAD_SHA256: dict[str, str] = {}

for role in sorted(
    EXPECTED_CONTROLLING_ROLES
):
    payload = controlling_artifact_payloads[
        role
    ]

    registered_payload_sha256 = payload.get(
        "payload_sha256",
        _MISSING,
    )

    semantic_payload = {
        str(key): value
        for key, value in payload.items()
        if key != "payload_sha256"
    }

    observed_payload_sha256 = (
        canonical_json_sha256_strict(
            semantic_payload
        )
    )

    CONTROLLING_PAYLOAD_SHA256[
        role
    ] = observed_payload_sha256

    register_semantic_check(
        check_name="semantic_self_hash_matches",
        source_role=role,
        observed=observed_payload_sha256,
        expected=registered_payload_sha256,
    )

    register_semantic_check(
        check_name="schema_version_matches",
        source_role=role,
        observed=payload.get(
            "schema_version",
            _MISSING,
        ),
        expected=EXPECTED_SCHEMA_BY_ROLE[
            role
        ],
    )

    expected_artifact_type = (
        EXPECTED_ARTIFACT_TYPE_BY_ROLE.get(
            role
        )
    )

    if expected_artifact_type is not None:
        register_semantic_check(
            check_name="artifact_type_matches",
            source_role=role,
            observed=payload.get(
                "artifact_type",
                _MISSING,
            ),
            expected=expected_artifact_type,
        )


# ------------------------------------------------------------
# Verify common source and run identity
# ------------------------------------------------------------

COMMON_IDENTITY_EXPECTATIONS: Final[
    dict[str, str]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
}

for role in sorted(
    EXPECTED_CONTROLLING_ROLES
):
    payload = controlling_artifact_payloads[
        role
    ]

    for key, expected_value in (
        COMMON_IDENTITY_EXPECTATIONS.items()
    ):
        register_semantic_check(
            check_name=f"identity::{key}",
            source_role=role,
            observed=payload.get(
                key,
                _MISSING,
            ),
            expected=expected_value,
        )

    register_semantic_check(
        check_name="producer_is_notebook08",
        source_role=role,
        observed=payload.get(
            "producer",
            _MISSING,
        ),
        expected=EXPECTED_NOTEBOOK08_PRODUCER,
    )


# ------------------------------------------------------------
# Bind named payloads
# ------------------------------------------------------------

notebook10_handoff = controlling_artifact_payloads[
    "NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF"
]

notebook09_blocked_handoff = controlling_artifact_payloads[
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF"
]

final_disposition = controlling_artifact_payloads[
    "NOTEBOOK08_FINAL_DISPOSITION"
]

semantic_readback = controlling_artifact_payloads[
    "NOTEBOOK08_SEMANTIC_READBACK_AUDIT"
]

core_output_manifest = controlling_artifact_payloads[
    "NOTEBOOK08_CORE_OUTPUT_MANIFEST"
]

final_output_manifest = controlling_artifact_payloads[
    "NOTEBOOK08_FINAL_OUTPUT_MANIFEST"
]


# ------------------------------------------------------------
# Verify Notebook 10 audit-only authorization
# ------------------------------------------------------------

register_semantic_check(
    check_name="consumer_is_compatible_notebook10",
    source_role="NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
    observed=notebook10_handoff.get(
        "consumer",
        _MISSING,
    ),
    expected=ACCEPTED_NOTEBOOK10_CONSUMERS,
    passed=(
        notebook10_handoff.get(
            "consumer"
        )
        in ACCEPTED_NOTEBOOK10_CONSUMERS
    ),
)

NOTEBOOK10_HANDOFF_EXPECTATIONS: Final[
    dict[str, Any]
] = {
    "notebook08_terminal_class": (
        EXPECTED_NOTEBOOK08_TERMINAL_CLASS
    ),
    "notebook08_terminal_status": (
        EXPECTED_NOTEBOOK08_TERMINAL_STATUS
    ),
    "authorization_granted": True,
    "authorization_scope": (
        EXPECTED_AUDIT_AUTHORIZATION_SCOPE
    ),
    "notebook09_executed": False,
    "notebook09_authorized": False,
    "validation_partition_opening_authorized": False,
    "engineering_holdout_opening_authorized": False,
    "model_signal_handoff_authorized": False,
    "v0_2_model_handoff_authorized": False,
    "calibration_parameter_updates": 0,
    "status": EXPECTED_NOTEBOOK10_HANDOFF_STATUS,
}

for key, expected_value in (
    NOTEBOOK10_HANDOFF_EXPECTATIONS.items()
):
    register_semantic_check(
        check_name=f"notebook10_handoff::{key}",
        source_role="NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
        observed=notebook10_handoff.get(
            key,
            _MISSING,
        ),
        expected=expected_value,
    )

observed_required_findings = set(
    notebook10_handoff.get(
        "required_audit_findings",
        [],
    )
)

register_semantic_check(
    check_name="required_audit_findings_complete",
    source_role="NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
    observed=observed_required_findings,
    expected=REQUIRED_AUDIT_FINDINGS,
)

expected_closed_partition_map = {
    partition_name: False
    for partition_name in PROTECTED_PARTITIONS
}

register_semantic_check(
    check_name="protected_partitions_remained_unopened",
    source_role="NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
    observed=notebook10_handoff.get(
        "protected_partition_content_loaded",
        _MISSING,
    ),
    expected=expected_closed_partition_map,
)


# ------------------------------------------------------------
# Verify the explicit Notebook 09 block
# ------------------------------------------------------------

NOTEBOOK09_BLOCK_EXPECTATIONS: Final[
    dict[str, Any]
] = {
    "selected_model_id": EXPECTED_SELECTED_MODEL_ID,
    "notebook08_terminal_class": (
        EXPECTED_NOTEBOOK08_TERMINAL_CLASS
    ),
    "notebook08_terminal_status": (
        EXPECTED_NOTEBOOK08_TERMINAL_STATUS
    ),
    "authorization_granted": False,
    "authorization_scope": "NONE",
    "blocking_reason": (
        EXPECTED_NOTEBOOK09_BLOCKING_REASON
    ),
    "count_score_superiority_authorized": True,
    "full_model_adequacy_authorized": False,
    "full_hawkes_superiority_authorized": False,
    "intensity_signal_validation_authorized": False,
    "validation_partition_opening_authorized": False,
    "engineering_holdout_opening_authorized": False,
    "cross_excitation_authorized": False,
    "state_dependent_hawkes_authorized": False,
    "parameter_refit_performed": False,
    "calibration_parameter_updates": 0,
    "permitted_use_of_frozen_h1": (
        EXPECTED_NOTEBOOK09_PERMITTED_USE
    ),
    "status": EXPECTED_NOTEBOOK09_BLOCKED_STATUS,
}

for key, expected_value in (
    NOTEBOOK09_BLOCK_EXPECTATIONS.items()
):
    register_semantic_check(
        check_name=f"notebook09_block::{key}",
        source_role="NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF",
        observed=notebook09_blocked_handoff.get(
            key,
            _MISSING,
        ),
        expected=expected_value,
    )

observed_prohibited_actions = set(
    notebook09_blocked_handoff.get(
        "prohibited_next_actions",
        [],
    )
)

register_semantic_check(
    check_name="notebook09_prohibited_actions_complete",
    source_role="NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF",
    observed=observed_prohibited_actions,
    expected=REQUIRED_PROHIBITED_ACTIONS,
)


# ------------------------------------------------------------
# Verify final Notebook 08 disposition
# ------------------------------------------------------------

FINAL_DISPOSITION_EXPECTATIONS: Final[
    dict[str, Any]
] = {
    "selected_model_id": EXPECTED_SELECTED_MODEL_ID,
    "selected_model_family": (
        EXPECTED_SELECTED_MODEL_FAMILY
    ),
    "terminal_class": (
        EXPECTED_NOTEBOOK08_TERMINAL_CLASS
    ),
    "terminal_status": (
        EXPECTED_NOTEBOOK08_TERMINAL_STATUS
    ),
    "full_model_adequacy_authorized": False,
    "full_hawkes_superiority_authorized": False,
    "cross_excitation_authorized": False,
    "state_dependent_hawkes_authorized": False,
    "notebook09_authorized": False,
    "validation_partition_opening_authorized": False,
    "engineering_holdout_opening_authorized": False,
    "parameter_refit_performed": False,
    "repair_performed": False,
    "calibration_parameter_updates": 0,
    "allowed_downstream_role": (
        EXPECTED_HAWKES_ALLOWED_ROLE
    ),
    "next_authorized_operation": (
        EXPECTED_NEXT_AUTHORIZED_OPERATION
    ),
    "status": EXPECTED_FINAL_DISPOSITION_STATUS,
}

for key, expected_value in (
    FINAL_DISPOSITION_EXPECTATIONS.items()
):
    register_semantic_check(
        check_name=f"final_disposition::{key}",
        source_role="NOTEBOOK08_FINAL_DISPOSITION",
        observed=final_disposition.get(
            key,
            _MISSING,
        ),
        expected=expected_value,
    )

register_semantic_check(
    check_name="narrow_findings_preserved",
    source_role="NOTEBOOK08_FINAL_DISPOSITION",
    observed=final_disposition.get(
        "narrow_findings",
        _MISSING,
    ),
    expected=EXPECTED_NARROW_FINDINGS,
)

register_semantic_check(
    check_name="blocking_findings_preserved",
    source_role="NOTEBOOK08_FINAL_DISPOSITION",
    observed=final_disposition.get(
        "blocking_findings",
        _MISSING,
    ),
    expected=EXPECTED_BLOCKING_FINDINGS,
)

observed_failed_gate_count = final_disposition.get(
    "failed_blocking_gate_count",
    _MISSING,
)

observed_failed_gates = final_disposition.get(
    "failed_blocking_gates",
    _MISSING,
)

register_semantic_check(
    check_name="failed_blocking_gate_count_is_positive",
    source_role="NOTEBOOK08_FINAL_DISPOSITION",
    observed=observed_failed_gate_count,
    expected="integer greater than zero",
    passed=(
        isinstance(
            observed_failed_gate_count,
            int,
        )
        and not isinstance(
            observed_failed_gate_count,
            bool,
        )
        and observed_failed_gate_count > 0
    ),
)

register_semantic_check(
    check_name="failed_gate_ledger_matches_count",
    source_role="NOTEBOOK08_FINAL_DISPOSITION",
    observed=(
        len(observed_failed_gates)
        if isinstance(
            observed_failed_gates,
            list,
        )
        else _MISSING
    ),
    expected=observed_failed_gate_count,
)


# ------------------------------------------------------------
# Verify semantic-readback authority
# ------------------------------------------------------------

SEMANTIC_READBACK_EXPECTATIONS: Final[
    dict[str, Any]
] = {
    "selected_model_id": EXPECTED_SELECTED_MODEL_ID,
    "terminal_class": (
        EXPECTED_NOTEBOOK08_TERMINAL_CLASS
    ),
    "terminal_status": (
        EXPECTED_NOTEBOOK08_TERMINAL_STATUS
    ),
    "semantic_readback_failure_count": 0,
    "all_core_files_physically_reverified": True,
    "all_semantic_checks_passed": True,
    "count_score_superiority_authorized": True,
    "full_model_adequacy_authorized": False,
    "full_hawkes_superiority_authorized": False,
    "notebook09_authorized": False,
    "validation_partition_opening_authorized": False,
    "calibration_parameter_updates": 0,
    "protected_partition_content_loaded": (
        expected_closed_partition_map
    ),
    "status": EXPECTED_SEMANTIC_READBACK_STATUS,
}

for key, expected_value in (
    SEMANTIC_READBACK_EXPECTATIONS.items()
):
    register_semantic_check(
        check_name=f"semantic_readback::{key}",
        source_role="NOTEBOOK08_SEMANTIC_READBACK_AUDIT",
        observed=semantic_readback.get(
            key,
            _MISSING,
        ),
        expected=expected_value,
    )

semantic_readback_records = semantic_readback.get(
    "records",
    _MISSING,
)

semantic_readback_record_count = semantic_readback.get(
    "semantic_readback_record_count",
    _MISSING,
)

records_are_valid = (
    isinstance(
        semantic_readback_records,
        list,
    )
    and all(
        isinstance(record, dict)
        and record.get("passed") is True
        for record in semantic_readback_records
    )
)

register_semantic_check(
    check_name="all_embedded_semantic_records_passed",
    source_role="NOTEBOOK08_SEMANTIC_READBACK_AUDIT",
    observed=records_are_valid,
    expected=True,
)

register_semantic_check(
    check_name="semantic_record_count_reconciles",
    source_role="NOTEBOOK08_SEMANTIC_READBACK_AUDIT",
    observed=(
        len(semantic_readback_records)
        if isinstance(
            semantic_readback_records,
            list,
        )
        else _MISSING
    ),
    expected=semantic_readback_record_count,
)

core_registered_file_count = semantic_readback.get(
    "core_registered_file_count",
    _MISSING,
)

register_semantic_check(
    check_name="core_registered_file_count_is_positive",
    source_role="NOTEBOOK08_SEMANTIC_READBACK_AUDIT",
    observed=core_registered_file_count,
    expected="integer greater than zero",
    passed=(
        isinstance(
            core_registered_file_count,
            int,
        )
        and not isinstance(
            core_registered_file_count,
            bool,
        )
        and core_registered_file_count > 0
    ),
)


# ------------------------------------------------------------
# Verify cross-artifact semantic hashes
# ------------------------------------------------------------

semantic_payload_sha256 = CONTROLLING_PAYLOAD_SHA256[
    "NOTEBOOK08_SEMANTIC_READBACK_AUDIT"
]

notebook09_payload_sha256 = CONTROLLING_PAYLOAD_SHA256[
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF"
]

final_disposition_payload_sha256 = CONTROLLING_PAYLOAD_SHA256[
    "NOTEBOOK08_FINAL_DISPOSITION"
]

register_semantic_check(
    check_name="final_disposition_references_semantic_readback_hash",
    source_role="NOTEBOOK08_FINAL_DISPOSITION",
    observed=final_disposition.get(
        "semantic_readback_payload_sha256",
        _MISSING,
    ),
    expected=semantic_payload_sha256,
)

register_semantic_check(
    check_name="final_disposition_references_notebook09_block_hash",
    source_role="NOTEBOOK08_FINAL_DISPOSITION",
    observed=final_disposition.get(
        "notebook09_blocked_handoff_payload_sha256",
        _MISSING,
    ),
    expected=notebook09_payload_sha256,
)

register_semantic_check(
    check_name="notebook10_handoff_references_final_disposition_hash",
    source_role="NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
    observed=notebook10_handoff.get(
        "final_disposition_payload_sha256",
        _MISSING,
    ),
    expected=final_disposition_payload_sha256,
)

register_semantic_check(
    check_name="notebook10_handoff_references_semantic_readback_hash",
    source_role="NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
    observed=notebook10_handoff.get(
        "semantic_readback_payload_sha256",
        _MISSING,
    ),
    expected=semantic_payload_sha256,
)

register_semantic_check(
    check_name="notebook10_handoff_references_notebook09_block_hash",
    source_role="NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
    observed=notebook10_handoff.get(
        "notebook09_blocked_handoff_payload_sha256",
        _MISSING,
    ),
    expected=notebook09_payload_sha256,
)


# ------------------------------------------------------------
# Verify cross-artifact physical file hashes
# ------------------------------------------------------------

semantic_readback_file_sha256 = sha256_file(
    resolved_controlling_artifacts[
        "NOTEBOOK08_SEMANTIC_READBACK_AUDIT"
    ]
)

notebook09_blocked_file_sha256 = sha256_file(
    resolved_controlling_artifacts[
        "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF"
    ]
)

register_semantic_check(
    check_name="final_disposition_references_semantic_readback_file_hash",
    source_role="NOTEBOOK08_FINAL_DISPOSITION",
    observed=final_disposition.get(
        "semantic_readback_file_sha256",
        _MISSING,
    ),
    expected=semantic_readback_file_sha256,
)

register_semantic_check(
    check_name="final_disposition_references_notebook09_file_hash",
    source_role="NOTEBOOK08_FINAL_DISPOSITION",
    observed=final_disposition.get(
        "notebook09_blocked_handoff_file_sha256",
        _MISSING,
    ),
    expected=notebook09_blocked_file_sha256,
)


# ------------------------------------------------------------
# Verify Notebook 10 handoff path references
# ------------------------------------------------------------

authoritative_artifact_references = (
    notebook10_handoff.get(
        "authoritative_artifacts",
        _MISSING,
    )
)

EXPECTED_HANDOFF_REFERENCES: Final[
    dict[str, str]
] = {
    "core_output_manifest": (
        "NOTEBOOK08_CORE_OUTPUT_MANIFEST"
    ),
    "semantic_readback_audit": (
        "NOTEBOOK08_SEMANTIC_READBACK_AUDIT"
    ),
    "final_disposition": (
        "NOTEBOOK08_FINAL_DISPOSITION"
    ),
    "notebook09_blocked_handoff": (
        "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF"
    ),
}

register_semantic_check(
    check_name="authoritative_artifact_reference_map_is_object",
    source_role="NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
    observed=isinstance(
        authoritative_artifact_references,
        dict,
    ),
    expected=True,
)

if isinstance(
    authoritative_artifact_references,
    dict,
):
    for reference_name, role in (
        EXPECTED_HANDOFF_REFERENCES.items()
    ):
        observed_reference = (
            authoritative_artifact_references.get(
                reference_name,
                _MISSING,
            )
        )

        observed_reference_path = (
            normalized_reference_path(
                observed_reference
            )
            if observed_reference is not _MISSING
            else _MISSING
        )

        expected_reference_path = (
            resolved_controlling_artifacts[
                role
            ]
        )

        register_semantic_check(
            check_name=(
                "authoritative_reference::"
                f"{reference_name}"
            ),
            source_role="NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
            observed=observed_reference_path,
            expected=expected_reference_path,
        )


# ------------------------------------------------------------
# Verify manifest-level consistency available at this stage
# ------------------------------------------------------------

for role, manifest_payload in (
    (
        "NOTEBOOK08_CORE_OUTPUT_MANIFEST",
        core_output_manifest,
    ),
    (
        "NOTEBOOK08_FINAL_OUTPUT_MANIFEST",
        final_output_manifest,
    ),
):
    manifest_status = manifest_payload.get(
        "status",
        _MISSING,
    )

    register_semantic_check(
        check_name="manifest_status_is_pass_like",
        source_role=role,
        observed=manifest_status,
        expected="status beginning with PASS",
        passed=(
            isinstance(
                manifest_status,
                str,
            )
            and manifest_status.startswith(
                "PASS"
            )
        ),
    )


# ------------------------------------------------------------
# Build and display semantic-authority audit
# ------------------------------------------------------------

NOTEBOOK08_SEMANTIC_AUTHORITY_AUDIT = (
    pd.DataFrame(
        semantic_authority_checks
    )
    .sort_values(
        "check_order",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)

display(
    NOTEBOOK08_SEMANTIC_AUTHORITY_AUDIT[
        [
            "check_order",
            "source_role",
            "check_name",
            "blocking",
            "passed",
            "status",
            "observed",
            "expected",
        ]
    ]
)

blocking_semantic_failures = (
    NOTEBOOK08_SEMANTIC_AUTHORITY_AUDIT.loc[
        NOTEBOOK08_SEMANTIC_AUTHORITY_AUDIT[
            "blocking"
        ]
        & ~NOTEBOOK08_SEMANTIC_AUTHORITY_AUDIT[
            "passed"
        ]
    ]
)

if not blocking_semantic_failures.empty:
    rendered_failures = "\n".join(
        (
            f"- {row.source_role} :: {row.check_name}\n"
            f"  observed={row.observed}\n"
            f"  expected={row.expected}"
        )
        for row in blocking_semantic_failures.itertuples(
            index=False
        )
    )

    raise SemanticAuthorityError(
        "Notebook 08 semantic-authority verification failed:\n"
        f"{rendered_failures}"
    )


# ------------------------------------------------------------
# Freeze controlling authority for later Notebook 10 sections
# ------------------------------------------------------------

FROZEN_NOTEBOOK08_AUTHORITY: Final[
    dict[str, Any]
] = {
    "producer": EXPECTED_NOTEBOOK08_PRODUCER,
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "selected_model_id": EXPECTED_SELECTED_MODEL_ID,
    "selected_model_family": (
        EXPECTED_SELECTED_MODEL_FAMILY
    ),
    "terminal_class": (
        EXPECTED_NOTEBOOK08_TERMINAL_CLASS
    ),
    "terminal_status": (
        EXPECTED_NOTEBOOK08_TERMINAL_STATUS
    ),
    "count_score_superiority_authorized": True,
    "generative_adequacy_authorized": False,
    "full_hawkes_superiority_authorized": False,
    "notebook09_status": EXPECTED_NOTEBOOK09_STATUS,
    "notebook09_authorized": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "calibration_parameter_updates": 0,
    "parameter_refit_performed": False,
    "repair_performed": False,
    "allowed_downstream_role": (
        EXPECTED_HAWKES_ALLOWED_ROLE
    ),
    "next_authorized_operation": (
        EXPECTED_NEXT_AUTHORIZED_OPERATION
    ),
    "notebook10_authorization_scope": (
        EXPECTED_AUDIT_AUTHORIZATION_SCOPE
    ),
    "controlling_payload_sha256": dict(
        CONTROLLING_PAYLOAD_SHA256
    ),
}


# ------------------------------------------------------------
# State update
#
# Notebook 08's closure authority is now verified.
# Full V0.1 upstream audit remains pending.
# ------------------------------------------------------------

NOTEBOOK08_SEMANTIC_AUTHORITY_VERIFIED = True
CONTROLLING_HANDOFF_VERIFIED = True
UPSTREAM_ARTIFACTS_VERIFIED = False

PROTECTED_PARTITION_CONTENT_LOADED = False
VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "Notebook 08 semantic authority: PASS. The failed Hawkes "
    "adequacy result, narrow count-score finding, blocked "
    "Notebook 09 route, zero calibration updates, and unopened "
    "protected partitions were independently verified. "
    "Notebook 10 is authorized only to audit, synthesize, "
    "archive, close V0.1, and prepare the V0.2 bootstrap handoff. "
    "No filesystem writes were performed."
)

,check_order,source_role,check_name,blocking,passed,status,observed,expected
0,1,NOTEBOOK08_CORE_OUTPUT_MANIFEST,semantic_self_hash_matches,True,True,PASS,'e9e5d985eb9777669846383158ff6429351ed6d9a25946dcae7403e5111263cc','e9e5d985eb9777669846383158ff6429351ed6d9a25946dcae7403e5111263cc'
1,2,NOTEBOOK08_CORE_OUTPUT_MANIFEST,schema_version_matches,True,True,PASS,'NOTEBOOK_08_CORE_OUTPUT_MANIFEST_V1','NOTEBOOK_08_CORE_OUTPUT_MANIFEST_V1'
2,3,NOTEBOOK08_FINAL_DISPOSITION,semantic_self_hash_matches,True,True,PASS,'5c6f05d13ba5c75212cf0b35e3d4686a5f682c628630fbb87b1aca7b1d5c91d4','5c6f05d13ba5c75212cf0b35e3d4686a5f682c628630fbb87b1aca7b1d5c91d4'
3,4,NOTEBOOK08_FINAL_DISPOSITION,schema_version_matches,True,True,PASS,'NOTEBOOK_08_HAWKES_DIAGNOSTICS_FINAL_DISPOSITION_V1','NOTEBOOK_08_HAWKES_DIAGNOSTICS_FINAL_DISPOSITION_V1'
4,5,NOTEBOOK08_FINAL_DISPOSITION,artifact_type_matches,True,True,PASS,'NOTEBOOK_08_HAWKES_DIAGNOSTICS_FINAL_DISPOSITION','NOTEBOOK_08_HAWKES_DIAGNOSTICS_FINAL_DISPOSITION'
...,...,...,...,...,...,...,...,...
133,134,NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF,authoritative_reference::semantic_readback_audit,True,True,PASS,WindowsPath('d:/clown project/v0.1/artifacts/manifests/btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_sem...,WindowsPath('d:/clown project/v0.1/artifacts/manifests/btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_sem...
134,135,NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF,authoritative_reference::final_disposition,True,True,PASS,WindowsPath('d:/clown project/v0.1/artifacts/manifests/btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_fin...,WindowsPath('d:/clown project/v0.1/artifacts/manifests/btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_fin...
135,136,NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF,authoritative_reference::notebook09_blocked_handoff,True,True,PASS,WindowsPath('d:/clown project/v0.1/artifacts/handoff/btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_to_09_intensity_signal_v...,WindowsPath('d:/clown project/v0.1/artifacts/handoff/btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_to_09_intensity_signal_v...
136,137,NOTEBOOK08_CORE_OUTPUT_MANIFEST,manifest_status_is_pass_like,True,True,PASS,'PASS_CORE_PERSISTENCE','status beginning with PASS'
137,138,NOTEBOOK08_FINAL_OUTPUT_MANIFEST,manifest_status_is_pass_like,True,True,PASS,'PASS_COMPLETE_OUTPUT_MANIFEST_FOR_FAILED_DIAGNOSTIC_RESULT','status beginning with PASS'

Notebook 08 semantic authority: PASS. The failed Hawkes adequacy result, narrow count-score finding, blocked Notebook 09 route, zero calibration updates, and unopened protected partitions were independently verified. Notebook 10 is authorized only to audit, synthesize, archive, close V0.1, and prepare the V0.2 bootstrap handoff. No filesystem writes were performed.

In [5]:
# ============================================================
# Complete V0.1 control-plane registry and stage coverage audit
#
# This cell verifies the exact persisted closeout authorities
# for Notebooks 00–08. It does not yet open every manifested
# data artifact; that occurs in the following audit stages.
#
# No filesystem writes are performed.
# No protected event partition is opened.
# ============================================================


class V01ControlPlaneError(RuntimeError):
    """Raised when the persisted V0.1 control plane is incomplete."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

if not globals().get(
    "NOTEBOOK08_SEMANTIC_AUTHORITY_VERIFIED",
    False,
):
    raise V01ControlPlaneError(
        "Notebook 08 semantic authority has not been verified."
    )

if not CONTROLLING_HANDOFF_VERIFIED:
    raise V01ControlPlaneError(
        "Notebook 10 audit authorization has not been verified."
    )

if PROTECTED_PARTITION_CONTENT_LOADED:
    raise V01ControlPlaneError(
        "Protected partition content was unexpectedly loaded."
    )


# ------------------------------------------------------------
# Stage names
# ------------------------------------------------------------

V01_STAGE_NAMES: Final[dict[str, str]] = {
    "00": "V01_RUN_CONTRACT",
    "01": "RAW_DATA_AUDIT",
    "02": "VISIBLE_BOOK_RECONSTRUCTION",
    "03": "CAUSAL_TRADE_BOOK_ALIGNMENT",
    "04": "EVENT_STREAM_CONSTRUCTION",
    "05": "MARKET_STATE_FEATURES",
    "06": "POINT_PROCESS_BASELINES",
    "07": "HAWKES_ESTIMATION",
    "08": "HAWKES_DIAGNOSTICS",
    "09": "INTENSITY_SIGNAL_VALIDATION",
    "10": "FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF",
}


# ------------------------------------------------------------
# Exact persisted control-artifact contract
# ------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class StageControlArtifactSpec:
    """One required persisted V0.1 control-plane artifact."""

    role: str
    stage_number: str
    stage_name: str
    artifact_kind: str
    path: Path
    required: bool = True
    expected_producer_prefix: str | None = None


STAGE_CONTROL_ARTIFACT_SPECS: Final[
    tuple[StageControlArtifactSpec, ...]
] = (
    # --------------------------------------------------------
    # Notebook 00
    # --------------------------------------------------------
    StageControlArtifactSpec(
        role="NOTEBOOK00_OUTPUT_MANIFEST",
        stage_number="00",
        stage_name=V01_STAGE_NAMES["00"],
        artifact_kind="OUTPUT_MANIFEST",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__00_V01_RUN_CONTRACT"
                + "__notebook_00_output_manifest.json"
            )
        ),
        expected_producer_prefix="00_",
    ),

    # --------------------------------------------------------
    # Notebook 01
    # --------------------------------------------------------
    StageControlArtifactSpec(
        role="NOTEBOOK01_OUTPUT_MANIFEST",
        stage_number="01",
        stage_name=V01_STAGE_NAMES["01"],
        artifact_kind="OUTPUT_MANIFEST",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__01_RAW_DATA_AUDIT"
                + "__notebook_01_output_manifest.json"
            )
        ),
        expected_producer_prefix="01_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK01_TO_NOTEBOOK02_HANDOFF",
        stage_number="01",
        stage_name=V01_STAGE_NAMES["01"],
        artifact_kind="HANDOFF",
        path=(
            V01_HANDOFF_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__01_RAW_DATA_AUDIT"
                + "__notebook_01_to_notebook_02_handoff.json"
            )
        ),
        expected_producer_prefix="01_",
    ),

    # --------------------------------------------------------
    # Notebook 02
    # --------------------------------------------------------
    StageControlArtifactSpec(
        role="NOTEBOOK02_OUTPUT_MANIFEST",
        stage_number="02",
        stage_name=V01_STAGE_NAMES["02"],
        artifact_kind="OUTPUT_MANIFEST",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__02_VISIBLE_BOOK_RECONSTRUCTION"
                + "__notebook_02_output_manifest.json"
            )
        ),
        expected_producer_prefix="02_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK02_TO_NOTEBOOK03_HANDOFF",
        stage_number="02",
        stage_name=V01_STAGE_NAMES["02"],
        artifact_kind="HANDOFF",
        path=(
            V01_HANDOFF_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__02_VISIBLE_BOOK_RECONSTRUCTION"
                + "__notebook_02_to_notebook_03_handoff.json"
            )
        ),
        expected_producer_prefix="02_",
    ),

    # --------------------------------------------------------
    # Notebook 03
    # --------------------------------------------------------
    StageControlArtifactSpec(
        role="NOTEBOOK03_OUTPUT_MANIFEST",
        stage_number="03",
        stage_name=V01_STAGE_NAMES["03"],
        artifact_kind="OUTPUT_MANIFEST",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__03_CAUSAL_TRADE_BOOK_ALIGNMENT"
                + "__notebook_03_output_manifest.json"
            )
        ),
        expected_producer_prefix="03_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK03_TO_NOTEBOOK04_HANDOFF",
        stage_number="03",
        stage_name=V01_STAGE_NAMES["03"],
        artifact_kind="HANDOFF",
        path=(
            V01_HANDOFF_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__03_CAUSAL_TRADE_BOOK_ALIGNMENT"
                + "__notebook_03_to_notebook_04_handoff.json"
            )
        ),
        expected_producer_prefix="03_",
    ),

    # --------------------------------------------------------
    # Notebook 04
    # --------------------------------------------------------
    StageControlArtifactSpec(
        role="NOTEBOOK04_OUTPUT_MANIFEST",
        stage_number="04",
        stage_name=V01_STAGE_NAMES["04"],
        artifact_kind="OUTPUT_MANIFEST",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__04_EVENT_STREAM_CONSTRUCTION"
                + "__notebook_04_output_manifest.json"
            )
        ),
        expected_producer_prefix="04_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK04_FINAL_ACCEPTANCE",
        stage_number="04",
        stage_name=V01_STAGE_NAMES["04"],
        artifact_kind="FINAL_ACCEPTANCE",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__04_EVENT_STREAM_CONSTRUCTION"
                + "__notebook_04_final_acceptance_report.json"
            )
        ),
        expected_producer_prefix="04_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK04_TO_NOTEBOOK05_HANDOFF",
        stage_number="04",
        stage_name=V01_STAGE_NAMES["04"],
        artifact_kind="HANDOFF",
        path=(
            V01_HANDOFF_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__04_EVENT_STREAM_CONSTRUCTION"
                + "__notebook_04_to_notebook_05_handoff.json"
            )
        ),
        expected_producer_prefix="04_",
    ),

    # --------------------------------------------------------
    # Notebook 05
    # --------------------------------------------------------
    StageControlArtifactSpec(
        role="NOTEBOOK05_OUTPUT_MANIFEST",
        stage_number="05",
        stage_name=V01_STAGE_NAMES["05"],
        artifact_kind="OUTPUT_MANIFEST",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__05_MARKET_STATE_FEATURES"
                + "__notebook_05_output_manifest.json"
            )
        ),
        expected_producer_prefix="05_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK05_FINAL_ACCEPTANCE",
        stage_number="05",
        stage_name=V01_STAGE_NAMES["05"],
        artifact_kind="FINAL_ACCEPTANCE",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__05_MARKET_STATE_FEATURES"
                + "__final_acceptance_report.json"
            )
        ),
        expected_producer_prefix="05_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK05_TO_NOTEBOOK06_HANDOFF",
        stage_number="05",
        stage_name=V01_STAGE_NAMES["05"],
        artifact_kind="HANDOFF",
        path=(
            V01_HANDOFF_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__05_MARKET_STATE_FEATURES"
                + "__to_06_POINT_PROCESS_BASELINES"
                + "__handoff.json"
            )
        ),
        expected_producer_prefix="05_",
    ),

    # --------------------------------------------------------
    # Notebook 06
    # --------------------------------------------------------
    StageControlArtifactSpec(
        role="NOTEBOOK06_TERMINAL_DECISION",
        stage_number="06",
        stage_name=V01_STAGE_NAMES["06"],
        artifact_kind="TERMINAL_DECISION",
        path=(
            V01_MANIFEST_ROOT
            / "06_point_process_baselines_terminal_decision.json"
        ),
        expected_producer_prefix="06_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK06_FINAL_ACCEPTANCE",
        stage_number="06",
        stage_name=V01_STAGE_NAMES["06"],
        artifact_kind="FINAL_ACCEPTANCE",
        path=(
            V01_MANIFEST_ROOT
            / "06_point_process_baselines_final_acceptance.json"
        ),
        expected_producer_prefix="06_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK06_OUTPUT_MANIFEST",
        stage_number="06",
        stage_name=V01_STAGE_NAMES["06"],
        artifact_kind="OUTPUT_MANIFEST",
        path=(
            V01_MANIFEST_ROOT
            / "06_point_process_baselines_output_manifest.json"
        ),
        expected_producer_prefix="06_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK06_READBACK_AUDIT",
        stage_number="06",
        stage_name=V01_STAGE_NAMES["06"],
        artifact_kind="SEMANTIC_READBACK",
        path=(
            V01_MANIFEST_ROOT
            / "06_point_process_baselines_readback_audit.json"
        ),
        expected_producer_prefix="06_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK06_TO_NOTEBOOK07_HANDOFF",
        stage_number="06",
        stage_name=V01_STAGE_NAMES["06"],
        artifact_kind="HANDOFF",
        path=(
            V01_HANDOFF_ROOT
            / (
                "06_point_process_baselines_to_"
                "07_hawkes_estimation_handoff.json"
            )
        ),
        expected_producer_prefix="06_",
    ),

    # --------------------------------------------------------
    # Notebook 07
    # --------------------------------------------------------
    StageControlArtifactSpec(
        role="NOTEBOOK07_TERMINAL_DECISION",
        stage_number="07",
        stage_name=V01_STAGE_NAMES["07"],
        artifact_kind="TERMINAL_DECISION",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__07_terminal_decision.json"
            )
        ),
        expected_producer_prefix="07_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK07_PERSISTENCE_INDEX",
        stage_number="07",
        stage_name=V01_STAGE_NAMES["07"],
        artifact_kind="PERSISTENCE_INDEX",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__07_hawkes_persistence_index.json"
            )
        ),
        expected_producer_prefix="07_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK07_SEMANTIC_READBACK",
        stage_number="07",
        stage_name=V01_STAGE_NAMES["07"],
        artifact_kind="SEMANTIC_READBACK",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__07_semantic_readback_audit.json"
            )
        ),
        expected_producer_prefix="07_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK07_FINAL_ACCEPTANCE",
        stage_number="07",
        stage_name=V01_STAGE_NAMES["07"],
        artifact_kind="FINAL_ACCEPTANCE",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__07_hawkes_estimation_final_acceptance.json"
            )
        ),
        expected_producer_prefix="07_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK07_OUTPUT_MANIFEST",
        stage_number="07",
        stage_name=V01_STAGE_NAMES["07"],
        artifact_kind="OUTPUT_MANIFEST",
        path=(
            V01_MANIFEST_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__07_hawkes_estimation_output_manifest.json"
            )
        ),
        expected_producer_prefix="07_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK07_TO_NOTEBOOK08_HANDOFF",
        stage_number="07",
        stage_name=V01_STAGE_NAMES["07"],
        artifact_kind="HANDOFF",
        path=(
            V01_HANDOFF_ROOT
            / (
                COMBINED_OUTPUT_PREFIX
                + "__07_to_08_hawkes_diagnostics_handoff.json"
            )
        ),
        expected_producer_prefix="07_",
    ),

    # --------------------------------------------------------
    # Notebook 08
    # --------------------------------------------------------
    StageControlArtifactSpec(
        role="NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
        stage_number="08",
        stage_name=V01_STAGE_NAMES["08"],
        artifact_kind="HANDOFF",
        path=NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF_PATH,
        expected_producer_prefix="08_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF",
        stage_number="08",
        stage_name=V01_STAGE_NAMES["08"],
        artifact_kind="BLOCKED_HANDOFF",
        path=NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF_PATH,
        expected_producer_prefix="08_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK08_FINAL_DISPOSITION",
        stage_number="08",
        stage_name=V01_STAGE_NAMES["08"],
        artifact_kind="FINAL_DISPOSITION",
        path=NOTEBOOK08_FINAL_DISPOSITION_PATH,
        expected_producer_prefix="08_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK08_SEMANTIC_READBACK",
        stage_number="08",
        stage_name=V01_STAGE_NAMES["08"],
        artifact_kind="SEMANTIC_READBACK",
        path=NOTEBOOK08_SEMANTIC_READBACK_AUDIT_PATH,
        expected_producer_prefix="08_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK08_CORE_OUTPUT_MANIFEST",
        stage_number="08",
        stage_name=V01_STAGE_NAMES["08"],
        artifact_kind="CORE_OUTPUT_MANIFEST",
        path=NOTEBOOK08_CORE_OUTPUT_MANIFEST_PATH,
        expected_producer_prefix="08_",
    ),
    StageControlArtifactSpec(
        role="NOTEBOOK08_FINAL_OUTPUT_MANIFEST",
        stage_number="08",
        stage_name=V01_STAGE_NAMES["08"],
        artifact_kind="OUTPUT_MANIFEST",
        path=NOTEBOOK08_FINAL_OUTPUT_MANIFEST_PATH,
        expected_producer_prefix="08_",
    ),
)


# ------------------------------------------------------------
# Generic nested-document helpers
# ------------------------------------------------------------

def walk_document(
    value: Any,
    path: str = "$",
) -> list[tuple[str, str | None, Any]]:
    """Return every node with its path and immediate key."""

    rows: list[tuple[str, str | None, Any]] = [
        (
            path,
            None,
            value,
        )
    ]

    if isinstance(
        value,
        dict,
    ):
        for key, child in value.items():
            child_path = (
                f"{path}.{key}"
            )

            rows.append(
                (
                    child_path,
                    str(key),
                    child,
                )
            )

            if isinstance(
                child,
                (dict, list),
            ):
                rows.extend(
                    walk_document(
                        child,
                        child_path,
                    )[1:]
                )

    elif isinstance(
        value,
        list,
    ):
        for index, child in enumerate(
            value
        ):
            child_path = (
                f"{path}[{index}]"
            )

            rows.append(
                (
                    child_path,
                    None,
                    child,
                )
            )

            if isinstance(
                child,
                (dict, list),
            ):
                rows.extend(
                    walk_document(
                        child,
                        child_path,
                    )[1:]
                )

    return rows


def values_for_exact_keys(
    document: Any,
    keys: set[str],
) -> list[tuple[str, Any]]:
    """Return all values whose immediate key exactly matches."""

    normalized_keys = {
        str(key).casefold()
        for key in keys
    }

    matches: list[tuple[str, Any]] = []

    for path, key, value in walk_document(
        document
    ):
        if (
            key is not None
            and key.casefold()
            in normalized_keys
        ):
            matches.append(
                (
                    path,
                    value,
                )
            )

    return matches


def unique_scalar_values_for_keys(
    document: Any,
    keys: set[str],
) -> list[Any]:
    """Return unique non-container values for exact key names."""

    observed_values: list[Any] = []

    for _, value in values_for_exact_keys(
        document,
        keys,
    ):
        if isinstance(
            value,
            (dict, list),
        ):
            continue

        if value is None:
            continue

        if not any(
            value == existing
            for existing in observed_values
        ):
            observed_values.append(
                value
            )

    return observed_values


def first_scalar_for_keys(
    document: Any,
    keys: set[str],
) -> Any:
    """Return the first discovered scalar for the specified keys."""

    values = unique_scalar_values_for_keys(
        document,
        keys,
    )

    return (
        values[0]
        if values
        else None
    )


def normalize_identity_value(
    value: Any,
) -> str:
    """Normalize identity strings without altering hashes."""

    return str(
        value
    ).strip()


def evaluate_identity_field(
    *,
    document: Any,
    accepted_keys: set[str],
    expected_value: str,
) -> tuple[str, list[str]]:
    """
    Verify all discovered values for one identity field.

    Missing identity declarations are warnings because older
    wrapper schemas do not repeat every frozen hash.
    """

    raw_values = unique_scalar_values_for_keys(
        document,
        accepted_keys,
    )

    normalized_values = [
        normalize_identity_value(
            value
        )
        for value in raw_values
    ]

    if not normalized_values:
        return (
            "WARNING_MISSING",
            [],
        )

    expected_normalized = normalize_identity_value(
        expected_value
    )

    mismatches = [
        value
        for value in normalized_values
        if value != expected_normalized
    ]

    if mismatches:
        return (
            "FAIL_MISMATCH",
            normalized_values,
        )

    return (
        "PASS",
        normalized_values,
    )


def extract_control_status(
    document: Any,
) -> str | None:
    """Extract the most relevant terminal or acceptance status."""

    priority_key_sets = (
        {"terminal_status"},
        {"final_status"},
        {"acceptance_status"},
        {"status"},
        {"terminal_class"},
    )

    for key_set in priority_key_sets:
        value = first_scalar_for_keys(
            document,
            key_set,
        )

        if value is not None:
            return str(
                value
            )

    return None


def extract_control_producer(
    document: Any,
) -> str | None:
    """Extract the producing notebook or producer identifier."""

    return first_scalar_for_keys(
        document,
        {
            "producer",
            "producing_notebook",
            "producing_notebook_name",
            "notebook_filename",
            "notebook_file",
            "notebook_name",
        },
    )


def producer_matches_stage(
    producer: str | None,
    expected_prefix: str | None,
) -> bool | None:
    """Check producer prefix when a producer is declared."""

    if expected_prefix is None:
        return None

    if producer is None:
        return None

    producer_name = Path(
        str(producer)
    ).name

    return producer_name.casefold().startswith(
        expected_prefix.casefold()
    )


def semantic_payload_hash_status(
    document: Mapping[str, Any],
) -> tuple[str, str | None, str | None]:
    """
    Verify top-level payload_sha256 when present.

    Earlier wrapped documents may use different hash conventions;
    absence is therefore recorded as NOT_DECLARED rather than failure.
    """

    declared_hash = document.get(
        "payload_sha256"
    )

    if declared_hash is None:
        return (
            "NOT_DECLARED",
            None,
            None,
        )

    semantic_payload = {
        str(key): value
        for key, value in document.items()
        if key != "payload_sha256"
    }

    observed_hash = canonical_json_sha256_strict(
        semantic_payload
    )

    declared_normalized = str(
        declared_hash
    ).strip().lower()

    return (
        (
            "PASS"
            if observed_hash
            == declared_normalized
            else "FAIL"
        ),
        declared_normalized,
        observed_hash,
    )


# ------------------------------------------------------------
# Identity key aliases used across the evolving V0.1 schemas
# ------------------------------------------------------------

SOURCE_RUN_IDENTITY_KEYS: Final[set[str]] = {
    "source_run_prefix",
}

SOURCE_SET_IDENTITY_KEYS: Final[set[str]] = {
    "source_set_sha256",
    "source_set_hash",
    "source_set_checksum",
}

V01_RUN_IDENTITY_KEYS: Final[set[str]] = {
    "v0_1_run_id",
    "v01_run_id",
}

RUN_CONFIG_IDENTITY_KEYS: Final[set[str]] = {
    "run_config_sha256",
    "v0_1_run_config_hash",
    "run_config_hash",
    "configuration_sha256",
}

RUN_IDENTITY_KEYS: Final[set[str]] = {
    "run_identity_sha256",
    "v0_1_run_identity_hash",
    "run_identity_hash",
}


# ------------------------------------------------------------
# Resolve, parse and verify every exact control artifact
# ------------------------------------------------------------

stage_control_payloads: dict[str, dict[str, Any]] = {}
stage_control_paths: dict[str, Path] = {}

stage_control_records: list[dict[str, Any]] = []
stage_control_failures: list[str] = []

for specification in (
    STAGE_CONTROL_ARTIFACT_SPECS
):
    artifact_path = normalized_resolved_path(
        specification.path
    )

    record: dict[str, Any] = {
        "role": specification.role,
        "stage_number": specification.stage_number,
        "stage_name": specification.stage_name,
        "artifact_kind": specification.artifact_kind,
        "path": str(
            artifact_path
        ),
        "required": specification.required,
        "exists": artifact_path.exists(),
        "is_file": artifact_path.is_file(),
        "size_bytes": None,
        "file_sha256": None,
        "semantic_hash_status": None,
        "declared_payload_sha256": None,
        "observed_payload_sha256": None,
        "producer": None,
        "producer_stage_match": None,
        "control_status": None,
        "source_run_identity_status": None,
        "source_set_identity_status": None,
        "v0_1_run_identity_status": None,
        "run_config_identity_status": None,
        "run_identity_status": None,
        "status": "NOT_EVALUATED",
        "error": None,
    }

    try:
        require_path_inside_root(
            path=artifact_path,
            authorized_root=V01_ROOT,
            role=specification.role,
        )

        require_path_inside_root(
            path=artifact_path,
            authorized_root=V01_ARTIFACT_ROOT,
            role=specification.role,
        )

        if specification.required:
            if not artifact_path.exists():
                raise V01ControlPlaneError(
                    "Required control artifact does not exist: "
                    f"{artifact_path}"
                )

            if not artifact_path.is_file():
                raise V01ControlPlaneError(
                    "Required control artifact is not a regular file: "
                    f"{artifact_path}"
                )

        if not artifact_path.exists():
            record["status"] = "WARNING_MISSING_OPTIONAL"
            stage_control_records.append(
                record
            )
            continue

        document = load_json_object(
            path=artifact_path,
            role=specification.role,
        )

        file_stat = artifact_path.stat()
        physical_sha256 = sha256_file(
            artifact_path
        )

        (
            semantic_hash_result,
            declared_payload_sha256,
            observed_payload_sha256,
        ) = semantic_payload_hash_status(
            document
        )

        (
            source_run_status,
            source_run_values,
        ) = evaluate_identity_field(
            document=document,
            accepted_keys=SOURCE_RUN_IDENTITY_KEYS,
            expected_value=SOURCE_RUN_PREFIX,
        )

        (
            source_set_status,
            source_set_values,
        ) = evaluate_identity_field(
            document=document,
            accepted_keys=SOURCE_SET_IDENTITY_KEYS,
            expected_value=SOURCE_SET_SHA256,
        )

        (
            v01_run_status,
            v01_run_values,
        ) = evaluate_identity_field(
            document=document,
            accepted_keys=V01_RUN_IDENTITY_KEYS,
            expected_value=V01_RUN_ID,
        )

        (
            run_config_status,
            run_config_values,
        ) = evaluate_identity_field(
            document=document,
            accepted_keys=RUN_CONFIG_IDENTITY_KEYS,
            expected_value=RUN_CONFIG_SHA256,
        )

        (
            run_identity_status,
            run_identity_values,
        ) = evaluate_identity_field(
            document=document,
            accepted_keys=RUN_IDENTITY_KEYS,
            expected_value=RUN_IDENTITY_SHA256,
        )

        producer = extract_control_producer(
            document
        )

        producer_stage_match = (
            producer_matches_stage(
                producer=(
                    None
                    if producer is None
                    else str(producer)
                ),
                expected_prefix=(
                    specification.expected_producer_prefix
                ),
            )
        )

        control_status = extract_control_status(
            document
        )

        blocking_statuses = {
            source_run_status,
            source_set_status,
            v01_run_status,
            run_config_status,
            run_identity_status,
        }

        if any(
            status == "FAIL_MISMATCH"
            for status in blocking_statuses
        ):
            raise V01ControlPlaneError(
                "Frozen identity mismatch detected."
            )

        if semantic_hash_result == "FAIL":
            raise V01ControlPlaneError(
                "Top-level semantic self-hash mismatch."
            )

        if producer_stage_match is False:
            raise V01ControlPlaneError(
                "Producing-notebook stage does not match the "
                "registered artifact stage."
            )

        # Notebook 08 is expected to preserve a failed model
        # adequacy decision. Earlier stages must not contain an
        # explicit terminal failure.
        if (
            specification.stage_number
            != "08"
            and control_status is not None
            and (
                str(control_status)
                .strip()
                .upper()
                .startswith("FAIL")
            )
        ):
            raise V01ControlPlaneError(
                "Unexpected failed terminal control artifact "
                f"before Notebook 08: {control_status}"
            )

        stage_control_payloads[
            specification.role
        ] = document

        stage_control_paths[
            specification.role
        ] = artifact_path

        record.update(
            {
                "exists": True,
                "is_file": True,
                "size_bytes": int(
                    file_stat.st_size
                ),
                "file_sha256": physical_sha256,
                "semantic_hash_status": (
                    semantic_hash_result
                ),
                "declared_payload_sha256": (
                    declared_payload_sha256
                ),
                "observed_payload_sha256": (
                    observed_payload_sha256
                ),
                "producer": (
                    None
                    if producer is None
                    else str(producer)
                ),
                "producer_stage_match": (
                    producer_stage_match
                ),
                "control_status": (
                    control_status
                ),
                "source_run_identity_status": (
                    source_run_status
                ),
                "source_set_identity_status": (
                    source_set_status
                ),
                "v0_1_run_identity_status": (
                    v01_run_status
                ),
                "run_config_identity_status": (
                    run_config_status
                ),
                "run_identity_status": (
                    run_identity_status
                ),
                "status": "PASS",
            }
        )

    except Exception as exc:
        record.update(
            {
                "status": "FAIL",
                "error": str(
                    exc
                ),
            }
        )

        stage_control_failures.append(
            (
                f"{specification.role}: "
                f"{exc}"
            )
        )

    stage_control_records.append(
        record
    )


V01_STAGE_CONTROL_ARTIFACT_REGISTRY = (
    pd.DataFrame(
        stage_control_records
    )
    .sort_values(
        [
            "stage_number",
            "artifact_kind",
            "role",
        ],
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


# ------------------------------------------------------------
# Stage-level coverage reconciliation
# ------------------------------------------------------------

expected_roles_by_stage = {
    stage_number: {
        specification.role
        for specification in (
            STAGE_CONTROL_ARTIFACT_SPECS
        )
        if specification.stage_number
        == stage_number
        and specification.required
    }
    for stage_number in (
        V01_STAGE_NAMES
    )
    if stage_number
    in {
        "00",
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
    }
}

stage_coverage_records: list[dict[str, Any]] = []

for stage_number in (
    "00",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
):
    expected_roles = expected_roles_by_stage[
        stage_number
    ]

    stage_rows = (
        V01_STAGE_CONTROL_ARTIFACT_REGISTRY.loc[
            V01_STAGE_CONTROL_ARTIFACT_REGISTRY[
                "stage_number"
            ].eq(
                stage_number
            )
        ]
    )

    passed_roles = set(
        stage_rows.loc[
            stage_rows["status"].eq(
                "PASS"
            ),
            "role",
        ].astype(
            str
        )
    )

    failed_roles = set(
        stage_rows.loc[
            stage_rows["status"].eq(
                "FAIL"
            ),
            "role",
        ].astype(
            str
        )
    )

    missing_roles = (
        expected_roles
        - passed_roles
    )

    stage_passed = bool(
        not missing_roles
        and not failed_roles
        and expected_roles
    )

    stage_coverage_records.append(
        {
            "stage_number": stage_number,
            "stage_name": V01_STAGE_NAMES[
                stage_number
            ],
            "expected_control_artifact_count": int(
                len(expected_roles)
            ),
            "passed_control_artifact_count": int(
                len(
                    expected_roles
                    & passed_roles
                )
            ),
            "missing_or_failed_roles": sorted(
                missing_roles
                | failed_roles
            ),
            "stage_control_plane_complete": (
                stage_passed
            ),
            "status": (
                "PASS"
                if stage_passed
                else "FAIL"
            ),
        }
    )


V01_STAGE_CONTROL_COVERAGE = pd.DataFrame(
    stage_coverage_records
)


# ------------------------------------------------------------
# Verify that Notebook 09 did not produce an active artifact
# ------------------------------------------------------------

NOTEBOOK09_PRODUCED_ARTIFACT_SCAN_ROOTS: Final[
    tuple[Path, Path]
] = (
    V01_MANIFEST_ROOT,
    V01_HANDOFF_ROOT,
)

notebook09_produced_artifact_records: list[
    dict[str, Any]
] = []

for scan_root in (
    NOTEBOOK09_PRODUCED_ARTIFACT_SCAN_ROOTS
):
    if not scan_root.is_dir():
        continue

    for candidate in sorted(
        scan_root.rglob(
            "*.json"
        ),
        key=lambda value: str(
            value
        ).casefold(),
    ):
        candidate_resolved = normalized_resolved_path(
            candidate
        )

        try:
            candidate_document = load_json_object(
                path=candidate_resolved,
                role="NOTEBOOK09_ABSENCE_SCAN",
            )

        except Exception:
            # Unreadable JSON will be handled through manifested
            # artifact verification later. It does not establish
            # that Notebook 09 executed.
            continue

        candidate_producer = extract_control_producer(
            candidate_document
        )

        producer_name = (
            ""
            if candidate_producer is None
            else Path(
                str(candidate_producer)
            ).name
        )

        produced_by_notebook09 = bool(
            producer_name.casefold().startswith(
                "09_"
            )
        )

        # This filename test detects direct Notebook 09 outputs
        # while excluding Notebook 08's blocked "to_09" handoff.
        filename_lower = candidate_resolved.name.casefold()

        filename_is_direct_notebook09_output = bool(
            re.search(
                r"(?:^|__)09_intensity_signal_validation(?:__|$)",
                filename_lower,
            )
        )

        if (
            produced_by_notebook09
            or filename_is_direct_notebook09_output
        ):
            notebook09_produced_artifact_records.append(
                {
                    "path": str(
                        candidate_resolved
                    ),
                    "producer": (
                        None
                        if candidate_producer is None
                        else str(candidate_producer)
                    ),
                    "produced_by_notebook09": (
                        produced_by_notebook09
                    ),
                    "filename_is_direct_notebook09_output": (
                        filename_is_direct_notebook09_output
                    ),
                }
            )


NOTEBOOK09_PRODUCED_ARTIFACT_AUDIT = pd.DataFrame(
    notebook09_produced_artifact_records,
    columns=[
        "path",
        "producer",
        "produced_by_notebook09",
        "filename_is_direct_notebook09_output",
    ],
)

NOTEBOOK09_ACTIVE_ARTIFACT_COUNT = int(
    len(
        NOTEBOOK09_PRODUCED_ARTIFACT_AUDIT
    )
)


# ------------------------------------------------------------
# Display audit tables
# ------------------------------------------------------------

display(
    V01_STAGE_CONTROL_ARTIFACT_REGISTRY[
        [
            "stage_number",
            "stage_name",
            "role",
            "artifact_kind",
            "path",
            "exists",
            "size_bytes",
            "file_sha256",
            "semantic_hash_status",
            "producer",
            "producer_stage_match",
            "control_status",
            "source_run_identity_status",
            "source_set_identity_status",
            "v0_1_run_identity_status",
            "run_config_identity_status",
            "run_identity_status",
            "status",
            "error",
        ]
    ]
)

display(
    V01_STAGE_CONTROL_COVERAGE
)

print(
    "Notebook 09 active produced artifact count:",
    NOTEBOOK09_ACTIVE_ARTIFACT_COUNT,
)

if NOTEBOOK09_ACTIVE_ARTIFACT_COUNT:
    display(
        NOTEBOOK09_PRODUCED_ARTIFACT_AUDIT
    )


# ------------------------------------------------------------
# Blocking gates
# ------------------------------------------------------------

if stage_control_failures:
    rendered_failures = "\n\n".join(
        f"- {failure}"
        for failure in stage_control_failures
    )

    raise V01ControlPlaneError(
        "V0.1 control-plane artifact verification failed:\n\n"
        f"{rendered_failures}"
    )

incomplete_stage_rows = (
    V01_STAGE_CONTROL_COVERAGE.loc[
        ~V01_STAGE_CONTROL_COVERAGE[
            "stage_control_plane_complete"
        ]
    ]
)

if not incomplete_stage_rows.empty:
    raise V01ControlPlaneError(
        "One or more V0.1 stages lack a complete persisted "
        "control plane:\n"
        + incomplete_stage_rows.to_string(
            index=False
        )
    )

if NOTEBOOK09_ACTIVE_ARTIFACT_COUNT != 0:
    raise V01ControlPlaneError(
        "Notebook 09 appears to have produced active artifacts, "
        "contradicting the verified Notebook 08 block."
    )

if set(
    stage_control_payloads
) != {
    specification.role
    for specification in (
        STAGE_CONTROL_ARTIFACT_SPECS
    )
    if specification.required
}:
    raise V01ControlPlaneError(
        "The in-memory control-payload registry does not exactly "
        "match the required persisted control-artifact contract."
    )


# ------------------------------------------------------------
# Freeze control-plane authority for later audit sections
# ------------------------------------------------------------

FROZEN_V01_CONTROL_PLANE: Final[
    dict[str, Any]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "verified_stage_numbers": [
        "00",
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
    ],
    "notebook09_status": (
        EXPECTED_NOTEBOOK09_STATUS
    ),
    "notebook09_active_artifact_count": (
        NOTEBOOK09_ACTIVE_ARTIFACT_COUNT
    ),
    "control_artifact_count": int(
        len(
            V01_STAGE_CONTROL_ARTIFACT_REGISTRY
        )
    ),
    "control_artifact_file_sha256": {
        str(row.role): str(
            row.file_sha256
        )
        for row in (
            V01_STAGE_CONTROL_ARTIFACT_REGISTRY.loc[
                V01_STAGE_CONTROL_ARTIFACT_REGISTRY[
                    "status"
                ].eq(
                    "PASS"
                )
            ]
            .itertuples(
                index=False
            )
        )
    },
    "notebook08_authority": dict(
        FROZEN_NOTEBOOK08_AUTHORITY
    ),
}


# ------------------------------------------------------------
# State update
#
# The persisted control plane is verified.
# Full manifested-file verification remains pending.
# ------------------------------------------------------------

V01_CONTROL_PLANE_VERIFIED = True
V01_STAGE_CONTROL_COVERAGE_VERIFIED = True

UPSTREAM_ARTIFACTS_VERIFIED = False

PROTECTED_PARTITION_CONTENT_LOADED = False
VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "V0.1 control-plane verification: PASS. Exact persisted "
    "closeout authorities for Notebooks 00–08 were resolved, "
    "parsed, hashed, and reconciled to the frozen source and run "
    "identities. Notebook 09 produced no active artifacts. "
    "Full verification of every file referenced by the stage "
    "manifests remains pending. No filesystem writes were "
    "performed."
)

,stage_number,stage_name,role,artifact_kind,path,exists,size_bytes,file_sha256,semantic_hash_status,producer,producer_stage_match,control_status,source_run_identity_status,source_set_identity_status,v0_1_run_identity_status,run_config_identity_status,run_identity_status,status,error
0,00,V01_RUN_CONTRACT,NOTEBOOK00_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__00_v01_run_contract__notebook_00_outpu...,True,15290,e12966301d92e61656715f2a6d397786820de836d8156dd70092250619cbb00e,NOT_DECLARED,00_V01_RUN_CONTRACT.ipynb,True,CONDITIONAL PASS,PASS,PASS,PASS,PASS,PASS,PASS,None
1,01,RAW_DATA_AUDIT,NOTEBOOK01_TO_NOTEBOOK02_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__01_raw_data_audit__notebook_01_to_notebo...,True,8367,138704253d8821259a7be427620a11b1d469a7f009c13c252c7587b51b440c61,NOT_DECLARED,01_RAW_DATA_AUDIT.ipynb,True,CONDITIONAL PASS,PASS,PASS,PASS,PASS,PASS,PASS,None
2,01,RAW_DATA_AUDIT,NOTEBOOK01_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__01_raw_data_audit__notebook_01_output_...,True,23269,2bb561126bbfc20fd25aa80131c1c11307e651d38ed3d6ee26a11b2ff0f41a4f,NOT_DECLARED,01_RAW_DATA_AUDIT.ipynb,True,CONDITIONAL PASS,PASS,PASS,PASS,PASS,PASS,PASS,None
3,02,VISIBLE_BOOK_RECONSTRUCTION,NOTEBOOK02_TO_NOTEBOOK03_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__02_visible_book_reconstruction__notebook...,True,4413,10e1a952818158f35dfacd5a5e1645dc6656d81e6dd23af2f7befd7fd4ab7388,NOT_DECLARED,02_VISIBLE_BOOK_RECONSTRUCTION.ipynb,True,PASS_WITH_REFERENCE_WARNINGS,PASS,PASS,PASS,PASS,PASS,PASS,None
4,02,VISIBLE_BOOK_RECONSTRUCTION,NOTEBOOK02_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__02_visible_book_reconstruction__notebo...,True,15362,0150ed8386326d30017ed892d82a8980f9c8a3d9ba13fb0e7bc2d01d055a2f8e,NOT_DECLARED,02_VISIBLE_BOOK_RECONSTRUCTION.ipynb,True,PASS_WITH_REFERENCE_WARNINGS,PASS,PASS,PASS,PASS,PASS,PASS,None
5,03,CAUSAL_TRADE_BOOK_ALIGNMENT,NOTEBOOK03_TO_NOTEBOOK04_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__03_causal_trade_book_alignment__notebook...,True,28856,6f4d48e4fbb56d9ac80b415b3c0fe6c4625526b555938b846ee2876626b6152e,NOT_DECLARED,03_CAUSAL_TRADE_BOOK_ALIGNMENT,True,PASS_WITH_ALIGNMENT_WARNINGS,PASS,WARNING_MISSING,PASS,WARNING_MISSING,WARNING_MISSING,PASS,None
6,03,CAUSAL_TRADE_BOOK_ALIGNMENT,NOTEBOOK03_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__03_causal_trade_book_alignment__notebo...,True,19576,4daa7fa17c2f953e3b931b607e1b5b066f4e29e7dea7397d86b3c9e3b77406ca,NOT_DECLARED,03_CAUSAL_TRADE_BOOK_ALIGNMENT.ipynb,True,PASS_WITH_ALIGNMENT_WARNINGS,PASS,WARNING_MISSING,PASS,WARNING_MISSING,WARNING_MISSING,PASS,None
7,04,EVENT_STREAM_CONSTRUCTION,NOTEBOOK04_FINAL_ACCEPTANCE,FINAL_ACCEPTANCE,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__04_event_stream_construction__notebook...,True,2082,f120060e83e37877f6cac860d0246a61a7546b9a4bd8c7b66fd1a61377021f80,NOT_DECLARED,04_EVENT_STREAM_CONSTRUCTION,True,PASS_WITH_EVENT_STREAM_WARNINGS,PASS,WARNING_MISSING,PASS,WARNING_MISSING,WARNING_MISSING,PASS,None
8,04,EVENT_STREAM_CONSTRUCTION,NOTEBOOK04_TO_NOTEBOOK05_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__04_event_stream_construction__notebook_0...,True,5649,6dce59c55f2a95c69d5fe0b50c44df9aad80cba6eb1260d7f1de0caee537f926,NOT_DECLARED,04_EVENT_STREAM_CONSTRUCTION,True,PASS_WITH_EVENT_STREAM_WARNINGS,PASS,WARNING_MISSING,PASS,WARNING_MISSING,WARNING_MISSING,PASS,None
9,04,EVENT_STREAM_CONSTRUCTION,NOTEBOOK04_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__04_event_stream_construction__notebook...,True,24653,a685a2dd6847f31a7a80c3d42c814ac4dd1f4d3797dd12f0c3f6b19347cad520,NOT_DECLARED,04_EVENT_STREAM_CONSTRUCTION,True,PASS_WITH_EVENT_STREAM_WARNINGS,PASS,WARNING_MISSING,PASS,WARNING_MISSING,WARNING_MISSING,PASS,None
10,05,MARKET_STATE_FEATURES,NOTEBOOK05_FINAL_ACCEPTANCE,FINAL_ACCEPTANCE,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__final_accept...,True,11742,9459c6278313e0d4fdb8f722c22f3694d54afecead99c5e85cdba60ffc02ebec,NOT_DECLARED,05_MARKET_STATE_FEATURES,True,PASS_WITH_FEATURE_WARNINGS,PASS,PASS,PASS,PASS,PASS,PASS,None
11,05,MARKET_STATE_FEATURES,NOTEBOOK05_TO_NOTEBOOK06_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__to_06_point_pr...,True,10224,80c41a6a58e44962febc03da64bf49c8924904bc477a31ae9c01a1695852108d,NOT_DECLARED,05_MARKET_STATE_FEATURES,True,PASS_WITH_FEATURE_WARNINGS,PASS,PASS,PASS,PASS,PASS,PASS,None
12,05,MARKET_STATE_FEATURES,NOTEBOOK05_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__notebook_05_...,True,20239,52b4912f1f1d86bae9d28e048a318eaac63d741b7eaac124eec1061b6699f2d9,NOT_DECLARED,05_MARKET_STATE_FEATURES,True,PASS_WITH_FEATURE_WARNINGS,PASS,PASS,PASS,PASS,PASS,PASS,None
13,06,POINT_PROCESS_BASELINES,NOTEBOOK06_FINAL_ACCEPTANCE,FINAL_ACCEPTANCE,d:\clown project\v0.1\artifacts\manifests\06_point_process_baselines_final_acceptance.json,True,2462,7ee4127508d49809f39e99b799458681a83133901038ba246e3a3f076833a4d1,PASS,06_POINT_PROCESS_BASELINES.ipynb,True,PASS_HAWKES_RESTRICTED_FIRST,PASS,PASS,PASS,PASS,PASS,PASS,None
14,06,POINT_PROCESS_BASELINES,NOTEBOOK06_TO_NOTEBOOK07_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\06_point_process_baselines_to_07_hawkes_estimation_handoff.json,True,14508,c7c57532241580395a4aa29121f20fcb40385fb2aeecf08de18d5f2775a45a46,PASS,06_POINT_PROCESS_BASELINES.ipynb,True,PASS_HAWKES_RESTRICTED_FIRST,PASS,PASS,PASS,PASS,PASS,PASS,None
15,06,POINT_PROCESS_BASELINES,NOTEBOOK06_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\06_point_process_baselines_output_manifest.json,True,176548,56dfc09bc96b0ce8456f4801e6c553d63694e58a620f0bd2a65c86c016f55c04,PASS,06_POINT_PROCESS_BASELINES.ipynb,True,PASS_HAWKES_RESTRICTED_FIRST,PASS,PASS,PASS,PASS,PASS,PASS,None
16,06,POINT_PROCESS_BASELINES,NOTEBOOK06_READBACK_AUDIT,SEMANTIC_READBACK,d:\clown project\v0.1\artifacts\manifests\06_point_process_baselines_readback_audit.json,True,82665,27945455c732c3ae81a9ff92c0d3ee9b11029d85fd94b071d3bc78c855753d00,PASS,06_POINT_PROCESS_BASELINES.ipynb,True,PASS,PASS,WARNING_MISSING,PASS,WARNING_MISSING,WARNING_MISSING,PASS,None
17,06,POINT_PROCESS_BASELINES,NOTEBOOK06_TERMINAL_DECISION,TERMINAL_DECISION,d:\clown project\v0.1\artifacts\manifests\06_point_process_baselines_terminal_decision.json,True,3145,6c53c509fe1122883e217d741f195dd76cfeda975f8203fc54a57647f9b830ce,PASS,06_POINT_PROCESS_BASELINES.ipynb,True,PASS_HAWKES_RESTRICTED_FIRST,PASS,PASS,PASS,PASS,PASS,PASS,None
18,07,HAWKES_ESTIMATION,NOTEBOOK07_FINAL_ACCEPTANCE,FINAL_ACCEPTANCE,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_hawkes_estimation_final_acceptance....,True,2400,32f462888a36d37d95e7e8b0e69a9297c7b074203c2827e5a6c519372ddf5e72,NOT_DECLARED,07_HAWKES_ESTIMATION.ipynb,True,PASS_HAWKES_ESTIMATION_RESTRICTED_FIRST,PASS,PASS,PASS,PASS,PASS,PASS,None
19,07,HAWKES_ESTIMATION,NOTEBOOK07_TO_NOTEBOOK08_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_to_08_hawkes_diagnostics_handoff.json,True,6772,93683fdbc65acb010cbdbe4f3e80979867a58382f5c0a7147c5ce18d33bd9c0c,NOT_DECLARED,07_HAWKES_ESTIMATION.ipynb,True,PASS_HANDOFF_FOR_HAWKES_DIAGNOSTICS,PASS,PASS,PASS,PASS,PASS,PASS,None
20,07,HAWKES_ESTIMATION,NOTEBOOK07_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_hawkes_estimation_output_manifest.json,True,58750,abc93a03ba93ab41ec6fccede348391f38c96661599041661f14f5d4799f28e5,NOT_DECLARED,07_HAWKES_ESTIMATION.ipynb,True,PASS_HAWKES_ESTIMATION_RESTRICTED_FIRST,PASS,PASS,PASS,PASS,PASS,PASS,None
21,07,HAWKES_ESTIMATION,NOTEBOOK07_PERSISTENCE_INDEX,PERSISTENCE_INDEX,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_hawkes_persistence_index.json,True,51639,c3d7adb1b9aa6af3e9297d2d925f084c8b3bc2216aaf1d27c18484ab55f680a1,NOT_DECLARED,07_HAWKES_ESTIMATION.ipynb,True,PASS_HAWKES_ESTIMATION_RESTRICTED_FIRST,PASS,PASS,PASS,PASS,PASS,PASS,None
22,07,HAWKES_ESTIMATION,NOTEBOOK07_SEMANTIC_READBACK,SEMANTIC_READBACK,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_semantic_readback_audit.json,True,45770,5895b20ca4fb416db962820adefc2a01c73290caa616b8abd17075d5f1f1110c,NOT_DECLARED,07_HAWKES_ESTIMATION.ipynb,True,PASS_HAWKES_ESTIMATION_RESTRICTED_FIRST,PASS,PASS,PASS,PASS,PASS,PASS,None
23,07,HAWKES_ESTIMATION,NOTEBOOK07_TERMINAL_DECISION,TERMINAL_DECISION,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_terminal_decision.json,True,18418,d1a6a55b97ce3f4e2cf8bd4958b42124d9b609f56c39dd62f062e1a69ac9304b,NOT_DECLARED,07_HAWKES_ESTIMATION.ipynb,True,PASS_HAWKES_ESTIMATION_RESTRICTED_FIRST,PASS,PASS,PASS,PASS,PASS,PASS,None
24,08,HAWKES_DIAGNOSTICS,NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF,BLOCKED_HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_to_09_intensity_signal_validation_blo...,True,4407,e4c0b3f7800e077117cb95109bd52d2700c2a0ea61175358a4e60febb9034a20,PASS,08_HAWKES_DIAGNOSTICS.ipynb,True,BLOCKING_REJECTION,PASS,PASS,PASS,PASS,PASS,PASS,None
25,08,HAWKES_DIAGNOSTICS,NOTEBOOK08_CORE_OUTPUT_MANIFEST,CORE_OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_core_output_mani...,True,137135,e9a1e5cacb4e41b52919ffc01837ce13b640f67282c1a4f78b4322da8cb74b8e,PASS,08_HAWKES_DIAGNOSTICS.ipynb,True,object,PASS,PASS,PASS,PASS,PASS,PASS,None
26,08,HAWKES_DIAGNOSTICS,NOTEBOOK08_FINAL_DISPOSITION,FINAL_DISPOSITION,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_final_dispositio...,True,6708,3abe2261e45aec3fd8663513df0b33f3c220043ff5315783fbae7c5a2cf5656a,PASS,08_HAWKES_DIAGNOSTICS.ipynb,True,FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY,PASS,PASS,PASS,PASS,PASS,PASS,None
27,08,HAWKES_DIAGNOSTICS,NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_to_10_final_audit_handoff.json,True,3004,900066c6a3b5c6c74f80f3a77403258a0115c31e3a10ff18aeafeed643f8a479,PASS,08_HAWKES_DIAGNOSTICS.ipynb,True,PASS_HANDOFF_TO_FINAL_AUDIT_AFTER_DIAGNOSTIC_FAILURE,PASS,PASS,PASS,PASS,PASS,PASS,None
28,08,HAWKES_DIAGNOSTICS,NOTEBOOK08_FINAL_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_output_manifest....,True,148665,37363e818ef0f6461a2b531b9998ee0b091e48c9fedcc42b8e99cb8ec26bcee1,PASS,08_HAWKES_DIAGNOSTICS.ipynb,True,object,PASS,PASS,PASS,PASS,PASS,PASS,None
29,08,HAWKES_DIAGNOSTICS,NOTEBOOK08_SEMANTIC_READBACK,SEMANTIC_READBACK,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_semantic_readbac...,True,70829,354ee1aa1b0863a9b0d087874444089be18e324a1f84e372956054043e6a2b7f,PASS,08_HAWKES_DIAGNOSTICS.ipynb,True,FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY,PASS,PASS,PASS,PASS,PASS,PASS,None

  stage_number                   stage_name  expected_control_artifact_count  passed_control_artifact_count missing_or_failed_roles  stage_control_plane_complete status
0           00             V01_RUN_CONTRACT                                1                              1                      []                          True   PASS
1           01               RAW_DATA_AUDIT                                2                              2                      []                          True   PASS
2           02  VISIBLE_BOOK_RECONSTRUCTION                                2                              2                      []                          True   PASS
3           03  CAUSAL_TRADE_BOOK_ALIGNMENT                                2                              2                      []                          True   PASS
4           04    EVENT_STREAM_CONSTRUCTION                                3                              3                      []                          True   PASS
5           05        MARKET_STATE_FEATURES                                3                              3                      []                          True   PASS
6           06      POINT_PROCESS_BASELINES                                5                              5                      []                          True   PASS
7           07            HAWKES_ESTIMATION                                6                              6                      []                          True   PASS
8           08           HAWKES_DIAGNOSTICS                                6                              6                      []                          True   PASS

Notebook 09 active produced artifact count: 0
V0.1 control-plane verification: PASS. Exact persisted closeout authorities for Notebooks 00–08 were resolved, parsed, hashed, and reconciled to the frozen source and run identities. Notebook 09 produced no active artifacts. Full verification of every file referenced by the stage manifests remains pending. No filesystem writes were performed.

In [6]:
# ============================================================
# Full manifested-file inventory and physical verification
#
# This cell:
# - extracts file registrations from every persisted V0.1
#   control document for Notebooks 00–08;
# - resolves exact absolute and relative paths without wildcard
#   or "latest file" selection;
# - reconciles duplicate registrations;
# - detects conflicting hashes or sizes;
# - verifies file existence, physical size, and SHA-256;
# - constructs the master physical V0.1 artifact catalogue;
# - treats protected-partition files as hash-only objects and
#   does not load their analytical contents.
#
# No filesystem writes are performed.
# ============================================================


class ManifestedFileVerificationError(RuntimeError):
    """Raised when a manifested physical file cannot be trusted."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

if not globals().get(
    "V01_CONTROL_PLANE_VERIFIED",
    False,
):
    raise ManifestedFileVerificationError(
        "The V0.1 control plane has not been verified."
    )

if not globals().get(
    "V01_STAGE_CONTROL_COVERAGE_VERIFIED",
    False,
):
    raise ManifestedFileVerificationError(
        "The V0.1 stage-control coverage audit has not passed."
    )

if not CONTROLLING_HANDOFF_VERIFIED:
    raise ManifestedFileVerificationError(
        "Notebook 10 audit authorization is unavailable."
    )

if PROTECTED_PARTITION_CONTENT_LOADED:
    raise ManifestedFileVerificationError(
        "Protected partition content was unexpectedly loaded."
    )


# ------------------------------------------------------------
# File-reference conventions
# ------------------------------------------------------------

KNOWN_FILE_SUFFIXES: Final[set[str]] = {
    ".csv",
    ".gz",
    ".json",
    ".jsonl",
    ".ndjson",
    ".parquet",
    ".pq",
    ".npz",
    ".npy",
    ".txt",
    ".log",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".ipynb",
    ".py",
    ".md",
    ".feather",
    ".arrow",
    ".bin",
    ".dat",
    ".zip",
}

GENERAL_PHYSICAL_HASH_KEYS: Final[
    tuple[str, ...]
] = (
    "file_sha256",
    "raw_file_sha256",
    "physical_file_sha256",
    "physical_sha256",
    "artifact_file_sha256",
    "observed_file_sha256",
    "current_file_sha256",
    "current_sha256",
    "sha256",
)

GENERAL_FILE_SIZE_KEYS: Final[
    tuple[str, ...]
] = (
    "size_bytes",
    "file_size_bytes",
    "physical_size_bytes",
    "raw_size_bytes",
    "current_size_bytes",
)

ARTIFACT_ROLE_KEYS: Final[
    tuple[str, ...]
] = (
    "artifact_role",
    "artifact_type",
    "logical_name",
    "table_name",
    "label",
    "role",
    "name",
    "dataset_name",
    "output_name",
)

ARTIFACT_FORMAT_KEYS: Final[
    tuple[str, ...]
] = (
    "format",
    "file_format",
    "storage_format",
    "serialization_format",
)

ARTIFACT_STATUS_KEYS: Final[
    tuple[str, ...]
] = (
    "acceptance_status",
    "artifact_status",
    "terminal_status",
    "status",
)

ROW_COUNT_KEYS: Final[
    tuple[str, ...]
] = (
    "row_count",
    "rows",
    "record_count",
    "event_count",
)

COLUMN_COUNT_KEYS: Final[
    tuple[str, ...]
] = (
    "column_count",
    "columns_count",
)

PATH_KEY_EXCLUSION_FRAGMENTS: Final[
    tuple[str, ...]
] = (
    "root",
    "directory",
    "_dir",
    "search_path",
    "pythonpath",
)

PROTECTED_PATH_PATTERNS: Final[
    tuple[str, ...]
] = (
    "validation",
    "engineering_holdout",
    "final_holdout",
    "protected_partition",
)

HASH_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"^[0-9a-fA-F]{64}$"
)


# ------------------------------------------------------------
# Generic nested-dictionary traversal
# ------------------------------------------------------------

def iter_mapping_nodes(
    value: Any,
    json_path: str = "$",
):
    """Yield every mapping node in a nested JSON-like object."""

    if isinstance(
        value,
        Mapping,
    ):
        yield (
            json_path,
            value,
        )

        for key, child in value.items():
            child_path = (
                f"{json_path}.{key}"
            )

            yield from iter_mapping_nodes(
                child,
                child_path,
            )

    elif isinstance(
        value,
        list,
    ):
        for index, child in enumerate(
            value
        ):
            child_path = (
                f"{json_path}[{index}]"
            )

            yield from iter_mapping_nodes(
                child,
                child_path,
            )


def first_present_value(
    mapping: Mapping[str, Any],
    keys: tuple[str, ...],
) -> Any:
    """Return the first non-null value under the listed keys."""

    for key in keys:
        if key in mapping:
            value = mapping[
                key
            ]

            if value is not None:
                return value

    return None


def json_safe_text(
    value: Any,
) -> str | None:
    """Render a compact JSON-safe value for audit tables."""

    if value is None:
        return None

    if isinstance(
        value,
        (
            str,
            int,
            float,
            bool,
        ),
    ):
        return str(
            value
        )

    try:
        return json.dumps(
            value,
            sort_keys=True,
            ensure_ascii=False,
            allow_nan=False,
        )

    except (
        TypeError,
        ValueError,
    ):
        return repr(
            value
        )


# ------------------------------------------------------------
# File-reference detection
# ------------------------------------------------------------

def is_candidate_path_key(
    key: str,
) -> bool:
    """Return whether a mapping key may represent a file path."""

    normalized_key = str(
        key
    ).strip().casefold()

    if any(
        fragment in normalized_key
        for fragment in PATH_KEY_EXCLUSION_FRAGMENTS
    ):
        return False

    return bool(
        normalized_key == "path"
        or normalized_key == "file"
        or normalized_key.endswith(
            "_path"
        )
        or normalized_key.endswith(
            "_file"
        )
    )


def looks_like_file_reference(
    value: Any,
) -> bool:
    """Return whether a scalar resembles a concrete file path."""

    if not isinstance(
        value,
        (str, Path),
    ):
        return False

    text = str(
        value
    ).strip()

    if not text:
        return False

    candidate = Path(
        text
    )

    if candidate.suffix.casefold() in KNOWN_FILE_SUFFIXES:
        return True

    return bool(
        "\\" in text
        or "/" in text
    )


def normalized_hash_or_none(
    value: Any,
) -> str | None:
    """Normalize one valid SHA-256 digest."""

    if value is None:
        return None

    candidate = str(
        value
    ).strip().lower()

    return (
        candidate
        if HASH_PATTERN.fullmatch(
            candidate
        )
        else None
    )


def path_key_prefix(
    path_key: str,
) -> str:
    """Return the semantic prefix associated with one path key."""

    normalized_key = str(
        path_key
    )

    for suffix in (
        "_resolved_path",
        "_absolute_path",
        "_relative_path",
        "_file_path",
        "_output_path",
        "_artifact_path",
        "_source_path",
        "_registered_path",
        "_path",
        "_file",
    ):
        if normalized_key.endswith(
            suffix
        ):
            return normalized_key[
                : -len(
                    suffix
                )
            ]

    if normalized_key in {
        "resolved_path",
        "absolute_path",
        "relative_path",
        "path",
        "file",
    }:
        return ""

    return normalized_key


def physical_hash_for_path_key(
    mapping: Mapping[str, Any],
    path_key: str,
) -> tuple[str | None, str | None]:
    """
    Return the physical hash and source key associated with one path.

    Payload or semantic hashes are intentionally excluded.
    """

    prefix = path_key_prefix(
        path_key
    )

    specific_candidates: list[str] = []

    if prefix:
        specific_candidates.extend(
            [
                f"{prefix}_file_sha256",
                f"{prefix}_raw_file_sha256",
                f"{prefix}_physical_sha256",
                f"{prefix}_raw_sha256",
                f"{prefix}_sha256",
            ]
        )

    # Common special cases.
    if path_key == "contract_path":
        specific_candidates.extend(
            [
                "contract_raw_sha256",
                "contract_file_sha256",
                "contract_sha256",
            ]
        )

    if path_key in {
        "resolved_path",
        "absolute_path",
        "relative_path",
        "path",
        "file",
        "file_path",
        "artifact_path",
        "output_path",
    }:
        specific_candidates.extend(
            GENERAL_PHYSICAL_HASH_KEYS
        )

    candidate_keys = list(
        dict.fromkeys(
            specific_candidates
        )
    )

    for candidate_key in candidate_keys:
        if candidate_key not in mapping:
            continue

        normalized_hash = normalized_hash_or_none(
            mapping[
                candidate_key
            ]
        )

        if normalized_hash is not None:
            return (
                normalized_hash,
                candidate_key,
            )

    return (
        None,
        None,
    )


def expected_size_for_path_key(
    mapping: Mapping[str, Any],
    path_key: str,
) -> tuple[int | None, str | None]:
    """Return the expected physical byte count associated with one path."""

    prefix = path_key_prefix(
        path_key
    )

    candidate_keys: list[str] = []

    if prefix:
        candidate_keys.extend(
            [
                f"{prefix}_size_bytes",
                f"{prefix}_file_size_bytes",
                f"{prefix}_raw_size_bytes",
            ]
        )

    if path_key in {
        "resolved_path",
        "absolute_path",
        "relative_path",
        "path",
        "file",
        "file_path",
        "artifact_path",
        "output_path",
    }:
        candidate_keys.extend(
            GENERAL_FILE_SIZE_KEYS
        )

    for candidate_key in dict.fromkeys(
        candidate_keys
    ):
        if candidate_key not in mapping:
            continue

        candidate_value = mapping[
            candidate_key
        ]

        if isinstance(
            candidate_value,
            bool,
        ):
            continue

        try:
            parsed_value = int(
                candidate_value
            )

        except (
            TypeError,
            ValueError,
            OverflowError,
        ):
            continue

        if parsed_value >= 0:
            return (
                parsed_value,
                candidate_key,
            )

    return (
        None,
        None,
    )


def path_is_protected_reference(
    declared_path: str,
    mapping: Mapping[str, Any],
) -> bool:
    """Identify protected partitions without opening their contents."""

    text_parts = [
        str(
            declared_path
        ),
    ]

    for key, value in mapping.items():
        normalized_key = str(
            key
        ).casefold()

        if any(
            token in normalized_key
            for token in (
                "partition",
                "split",
                "role",
                "label",
                "name",
            )
        ):
            text_parts.append(
                str(
                    value
                )
            )

    combined_text = " ".join(
        text_parts
    ).casefold()

    return any(
        pattern in combined_text
        for pattern in PROTECTED_PATH_PATTERNS
    )


def record_is_inside_artifact_collection(
    json_path: str,
) -> bool:
    """Identify records stored inside manifest artifact/file collections."""

    normalized_path = json_path.casefold()

    collection_markers = (
        ".artifacts[",
        ".files[",
        ".outputs[",
        ".registered_files[",
        ".persisted_files[",
        ".core_files[",
        ".tables[",
        ".models[",
        ".datasets[",
    )

    return any(
        marker in normalized_path
        for marker in collection_markers
    )


# ------------------------------------------------------------
# Exact deterministic path resolution
# ------------------------------------------------------------

_PHYSICAL_HASH_CACHE: dict[Path, str] = {}


def cached_file_sha256(
    path: Path,
) -> str:
    """Compute or recover one physical file SHA-256."""

    normalized_path = normalized_resolved_path(
        path
    )

    if normalized_path not in _PHYSICAL_HASH_CACHE:
        _PHYSICAL_HASH_CACHE[
            normalized_path
        ] = sha256_file(
            normalized_path
        )

    return _PHYSICAL_HASH_CACHE[
        normalized_path
    ]


def candidate_paths_for_reference(
    declared_reference: str | Path,
) -> list[Path]:
    """Return exact deterministic resolution candidates."""

    raw_text = str(
        declared_reference
    ).strip()

    declared_path = Path(
        raw_text
    )

    if declared_path.is_absolute():
        return [
            normalized_resolved_path(
                declared_path
            )
        ]

    normalized_parts = [
        part.casefold()
        for part in declared_path.parts
        if part not in {
            "",
            ".",
        }
    ]

    candidates: list[Path] = []

    if (
        normalized_parts
        and normalized_parts[0]
        in {
            "v0.0",
            "v0.1",
            "v0.2",
        }
    ):
        candidates.append(
            normalized_resolved_path(
                PROJECT_ROOT
                / declared_path
            )
        )

    candidates.extend(
        [
            normalized_resolved_path(
                V01_ROOT
                / declared_path
            ),
            normalized_resolved_path(
                V00_ROOT
                / declared_path
            ),
            normalized_resolved_path(
                PROJECT_ROOT
                / declared_path
            ),
        ]
    )

    return list(
        dict.fromkeys(
            candidates
        )
    )


def resolve_manifested_file_reference(
    *,
    declared_reference: str | Path,
    expected_sha256: str | None,
    source_role: str,
) -> tuple[Path, str]:
    """
    Resolve one file path without recursive search or filename guessing.

    When several exact candidates exist, a declared physical hash is
    used to disambiguate them.
    """

    candidates = candidate_paths_for_reference(
        declared_reference
    )

    existing_files = [
        candidate
        for candidate in candidates
        if candidate.is_file()
    ]

    if len(
        existing_files
    ) == 1:
        return (
            existing_files[0],
            "UNIQUE_EXACT_CANDIDATE",
        )

    if len(
        existing_files
    ) > 1 and expected_sha256 is not None:
        hash_matches = [
            candidate
            for candidate in existing_files
            if cached_file_sha256(
                candidate
            )
            == expected_sha256
        ]

        if len(
            hash_matches
        ) == 1:
            return (
                hash_matches[0],
                "DISAMBIGUATED_BY_EXPECTED_SHA256",
            )

        if len(
            hash_matches
        ) > 1:
            # Prefer V0.1 for persisted V0.1 outputs when the
            # same verified bytes exist in more than one tree.
            v01_matches = [
                candidate
                for candidate in hash_matches
                if candidate.is_relative_to(
                    normalized_resolved_path(
                        V01_ROOT
                    )
                )
            ]

            if len(
                v01_matches
            ) == 1:
                return (
                    v01_matches[0],
                    "MULTIPLE_HASH_MATCHES_V01_AUTHORITY",
                )

            raise ManifestedFileVerificationError(
                "Multiple exact files match the same registered "
                f"SHA-256 for {source_role}.\n"
                f"Declared reference: {declared_reference}\n"
                f"Matches: {[str(path) for path in hash_matches]}"
            )

    if len(
        existing_files
    ) > 1:
        v01_candidates = [
            candidate
            for candidate in existing_files
            if candidate.is_relative_to(
                normalized_resolved_path(
                    V01_ROOT
                )
            )
        ]

        if len(
            v01_candidates
        ) == 1:
            return (
                v01_candidates[0],
                "MULTIPLE_UNHASHED_CANDIDATES_V01_AUTHORITY",
            )

        raise ManifestedFileVerificationError(
            "Ambiguous exact file reference without a usable hash.\n"
            f"Source role: {source_role}\n"
            f"Declared reference: {declared_reference}\n"
            f"Candidates: {[str(path) for path in existing_files]}"
        )

    # No existing exact candidate. Return the first deterministic
    # candidate so the missing-file audit can report its location.
    return (
        candidates[0],
        "NO_EXISTING_EXACT_CANDIDATE",
    )


# ------------------------------------------------------------
# Extract file references from every persisted control document
# ------------------------------------------------------------

manifest_file_reference_records: list[
    dict[str, Any]
] = []

control_stage_lookup = {
    str(row.role): str(
        row.stage_number
    )
    for row in (
        V01_STAGE_CONTROL_ARTIFACT_REGISTRY.itertuples(
            index=False
        )
    )
}

control_stage_name_lookup = {
    str(row.role): str(
        row.stage_name
    )
    for row in (
        V01_STAGE_CONTROL_ARTIFACT_REGISTRY.itertuples(
            index=False
        )
    )
}

control_kind_lookup = {
    str(row.role): str(
        row.artifact_kind
    )
    for row in (
        V01_STAGE_CONTROL_ARTIFACT_REGISTRY.itertuples(
            index=False
        )
    )
}

for source_role, document in (
    stage_control_payloads.items()
):
    source_stage_number = control_stage_lookup[
        source_role
    ]

    source_stage_name = control_stage_name_lookup[
        source_role
    ]

    source_artifact_kind = control_kind_lookup[
        source_role
    ]

    for json_path, mapping in iter_mapping_nodes(
        document
    ):
        mapping_keys = set(
            str(key)
            for key in mapping
        )

        # Prefer one authoritative absolute or resolved path over
        # a duplicate relative path stored in the same record.
        preferred_path_keys: list[str] = []

        for preferred_key in (
            "resolved_path",
            "absolute_path",
            "file_path",
            "artifact_path",
            "output_path",
            "path",
            "contract_path",
        ):
            if (
                preferred_key in mapping
                and is_candidate_path_key(
                    preferred_key
                )
                and looks_like_file_reference(
                    mapping[
                        preferred_key
                    ]
                )
            ):
                preferred_path_keys.append(
                    preferred_key
                )

        other_path_keys = [
            str(key)
            for key, value in mapping.items()
            if (
                str(key)
                not in preferred_path_keys
                and str(key)
                != "relative_path"
                and is_candidate_path_key(
                    str(key)
                )
                and looks_like_file_reference(
                    value
                )
            )
        ]

        if not preferred_path_keys:
            if (
                "relative_path" in mapping
                and looks_like_file_reference(
                    mapping[
                        "relative_path"
                    ]
                )
            ):
                preferred_path_keys.append(
                    "relative_path"
                )

        path_keys = list(
            dict.fromkeys(
                preferred_path_keys
                + other_path_keys
            )
        )

        for path_key in path_keys:
            declared_reference = str(
                mapping[
                    path_key
                ]
            ).strip()

            (
                expected_sha256,
                hash_source_key,
            ) = physical_hash_for_path_key(
                mapping=mapping,
                path_key=path_key,
            )

            (
                expected_size_bytes,
                size_source_key,
            ) = expected_size_for_path_key(
                mapping=mapping,
                path_key=path_key,
            )

            inside_artifact_collection = (
                record_is_inside_artifact_collection(
                    json_path
                )
            )

            # Skip incidental path strings that have no physical
            # integrity information and are not artifact records.
            if (
                expected_sha256 is None
                and expected_size_bytes is None
                and not inside_artifact_collection
            ):
                continue

            artifact_role = first_present_value(
                mapping,
                ARTIFACT_ROLE_KEYS,
            )

            artifact_format = first_present_value(
                mapping,
                ARTIFACT_FORMAT_KEYS,
            )

            artifact_status = first_present_value(
                mapping,
                ARTIFACT_STATUS_KEYS,
            )

            row_count = first_present_value(
                mapping,
                ROW_COUNT_KEYS,
            )

            column_count = first_present_value(
                mapping,
                COLUMN_COUNT_KEYS,
            )

            protected_reference = (
                path_is_protected_reference(
                    declared_path=declared_reference,
                    mapping=mapping,
                )
            )

            manifested_record_required = bool(
                expected_sha256 is not None
                or expected_size_bytes is not None
                or inside_artifact_collection
            )

            manifest_file_reference_records.append(
                {
                    "source_control_role": source_role,
                    "source_stage_number": (
                        source_stage_number
                    ),
                    "source_stage_name": (
                        source_stage_name
                    ),
                    "source_control_kind": (
                        source_artifact_kind
                    ),
                    "source_json_path": json_path,
                    "path_key": path_key,
                    "declared_reference": (
                        declared_reference
                    ),
                    "artifact_role": (
                        None
                        if artifact_role is None
                        else str(
                            artifact_role
                        )
                    ),
                    "artifact_format": (
                        None
                        if artifact_format is None
                        else str(
                            artifact_format
                        )
                    ),
                    "artifact_status": (
                        None
                        if artifact_status is None
                        else str(
                            artifact_status
                        )
                    ),
                    "expected_sha256": (
                        expected_sha256
                    ),
                    "hash_source_key": (
                        hash_source_key
                    ),
                    "expected_size_bytes": (
                        expected_size_bytes
                    ),
                    "size_source_key": (
                        size_source_key
                    ),
                    "declared_row_count": (
                        row_count
                    ),
                    "declared_column_count": (
                        column_count
                    ),
                    "inside_artifact_collection": (
                        inside_artifact_collection
                    ),
                    "required": (
                        manifested_record_required
                    ),
                    "protected_partition_reference": (
                        protected_reference
                    ),
                    "semantic_content_loaded": False,
                }
            )


# ------------------------------------------------------------
# Add the 30 control-plane files themselves to the catalogue
# ------------------------------------------------------------

for row in (
    V01_STAGE_CONTROL_ARTIFACT_REGISTRY.loc[
        V01_STAGE_CONTROL_ARTIFACT_REGISTRY[
            "status"
        ].eq(
            "PASS"
        )
    ]
    .itertuples(
        index=False
    )
):
    manifest_file_reference_records.append(
        {
            "source_control_role": str(
                row.role
            ),
            "source_stage_number": str(
                row.stage_number
            ),
            "source_stage_name": str(
                row.stage_name
            ),
            "source_control_kind": str(
                row.artifact_kind
            ),
            "source_json_path": (
                "$.__CONTROL_PLANE_FILE__"
            ),
            "path_key": "path",
            "declared_reference": str(
                row.path
            ),
            "artifact_role": str(
                row.role
            ),
            "artifact_format": "JSON",
            "artifact_status": str(
                row.status
            ),
            "expected_sha256": str(
                row.file_sha256
            ),
            "hash_source_key": (
                "V01_STAGE_CONTROL_ARTIFACT_REGISTRY.file_sha256"
            ),
            "expected_size_bytes": int(
                row.size_bytes
            ),
            "size_source_key": (
                "V01_STAGE_CONTROL_ARTIFACT_REGISTRY.size_bytes"
            ),
            "declared_row_count": None,
            "declared_column_count": None,
            "inside_artifact_collection": True,
            "required": True,
            "protected_partition_reference": False,
            "semantic_content_loaded": True,
        }
    )


MANIFEST_FILE_REFERENCE_TABLE = pd.DataFrame(
    manifest_file_reference_records
)

if MANIFEST_FILE_REFERENCE_TABLE.empty:
    raise ManifestedFileVerificationError(
        "No physical file registrations were discovered."
    )


# ------------------------------------------------------------
# Resolve and independently verify each registration
# ------------------------------------------------------------

resolved_reference_records: list[
    dict[str, Any]
] = []

reference_verification_failures: list[str] = []

for reference in (
    MANIFEST_FILE_REFERENCE_TABLE.itertuples(
        index=False
    )
):
    record = reference._asdict()

    expected_sha256 = (
        None
        if pd.isna(
            reference.expected_sha256
        )
        else str(
            reference.expected_sha256
        )
    )

    expected_size_bytes = (
        None
        if pd.isna(
            reference.expected_size_bytes
        )
        else int(
            reference.expected_size_bytes
        )
    )

    verification_status = "NOT_EVALUATED"
    verification_error = None

    resolved_path: Path | None = None
    resolution_method: str | None = None

    exists = False
    is_file = False
    inside_project = False
    inside_v0_0 = False
    inside_v0_1 = False
    inside_v0_2 = False

    observed_size_bytes: int | None = None
    observed_sha256: str | None = None

    size_matches: bool | None = None
    hash_matches: bool | None = None

    try:
        (
            resolved_path,
            resolution_method,
        ) = resolve_manifested_file_reference(
            declared_reference=(
                reference.declared_reference
            ),
            expected_sha256=expected_sha256,
            source_role=(
                reference.source_control_role
            ),
        )

        exists = resolved_path.exists()
        is_file = resolved_path.is_file()

        inside_project = resolved_path.is_relative_to(
            normalized_resolved_path(
                PROJECT_ROOT
            )
        )

        inside_v0_0 = resolved_path.is_relative_to(
            normalized_resolved_path(
                V00_ROOT
            )
        )

        inside_v0_1 = resolved_path.is_relative_to(
            normalized_resolved_path(
                V01_ROOT
            )
        )

        inside_v0_2 = resolved_path.is_relative_to(
            normalized_resolved_path(
                V02_ROOT
            )
        )

        if reference.required and not exists:
            raise ManifestedFileVerificationError(
                "Required manifested file does not exist."
            )

        if exists and not is_file:
            raise ManifestedFileVerificationError(
                "Manifested path is not a regular file."
            )

        if reference.required and not inside_project:
            raise ManifestedFileVerificationError(
                "Required manifested file lies outside the "
                "registered project root."
            )

        if is_file:
            observed_size_bytes = int(
                resolved_path.stat().st_size
            )

            # Physical hashing reads bytes only. No CSV, parquet,
            # NPZ, or event-table parser is called here.
            observed_sha256 = cached_file_sha256(
                resolved_path
            )

        if expected_size_bytes is not None:
            size_matches = bool(
                observed_size_bytes
                == expected_size_bytes
            )

            if not size_matches:
                raise ManifestedFileVerificationError(
                    "Physical file size does not match the "
                    "manifest registration."
                )

        if expected_sha256 is not None:
            hash_matches = bool(
                observed_sha256
                == expected_sha256
            )

            if not hash_matches:
                raise ManifestedFileVerificationError(
                    "Physical SHA-256 does not match the "
                    "manifest registration."
                )

        if (
            expected_sha256 is None
            and expected_size_bytes is None
        ):
            verification_status = (
                "WARNING_UNHASHED_REFERENCE"
            )

        else:
            verification_status = "PASS"

    except Exception as exc:
        verification_status = "FAIL"
        verification_error = str(
            exc
        )

        if reference.required:
            reference_verification_failures.append(
                (
                    f"{reference.source_control_role} :: "
                    f"{reference.source_json_path} :: "
                    f"{reference.declared_reference} :: "
                    f"{exc}"
                )
            )

    record.update(
        {
            "resolved_path": (
                None
                if resolved_path is None
                else str(
                    resolved_path
                )
            ),
            "resolution_method": (
                resolution_method
            ),
            "exists": exists,
            "is_file": is_file,
            "inside_project": inside_project,
            "inside_v0_0": inside_v0_0,
            "inside_v0_1": inside_v0_1,
            "inside_v0_2": inside_v0_2,
            "observed_size_bytes": (
                observed_size_bytes
            ),
            "observed_sha256": (
                observed_sha256
            ),
            "size_matches": (
                size_matches
            ),
            "hash_matches": (
                hash_matches
            ),
            "hash_only_verification": bool(
                reference.protected_partition_reference
            ),
            "verification_status": (
                verification_status
            ),
            "verification_error": (
                verification_error
            ),
        }
    )

    resolved_reference_records.append(
        record
    )


V01_MANIFESTED_FILE_REFERENCE_AUDIT = (
    pd.DataFrame(
        resolved_reference_records
    )
    .sort_values(
        [
            "source_stage_number",
            "source_control_role",
            "source_json_path",
            "declared_reference",
        ],
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


# ------------------------------------------------------------
# Reconcile duplicate physical registrations
# ------------------------------------------------------------

verified_path_rows = (
    V01_MANIFESTED_FILE_REFERENCE_AUDIT.loc[
        V01_MANIFESTED_FILE_REFERENCE_AUDIT[
            "resolved_path"
        ].notna()
    ]
    .copy()
)

duplicate_reconciliation_records: list[
    dict[str, Any]
] = []

master_catalogue_records: list[
    dict[str, Any]
] = []

for resolved_path_text, group in (
    verified_path_rows.groupby(
        "resolved_path",
        sort=True,
        dropna=False,
    )
):
    registered_hashes = sorted(
        {
            str(value)
            for value in group[
                "expected_sha256"
            ].dropna()
            if str(value).strip()
        }
    )

    registered_sizes = sorted(
        {
            int(value)
            for value in group[
                "expected_size_bytes"
            ].dropna()
        }
    )

    observed_hashes = sorted(
        {
            str(value)
            for value in group[
                "observed_sha256"
            ].dropna()
            if str(value).strip()
        }
    )

    observed_sizes = sorted(
        {
            int(value)
            for value in group[
                "observed_size_bytes"
            ].dropna()
        }
    )

    registered_hash_conflict = bool(
        len(
            registered_hashes
        )
        > 1
    )

    registered_size_conflict = bool(
        len(
            registered_sizes
        )
        > 1
    )

    observed_hash_conflict = bool(
        len(
            observed_hashes
        )
        > 1
    )

    observed_size_conflict = bool(
        len(
            observed_sizes
        )
        > 1
    )

    group_has_failure = bool(
        group[
            "verification_status"
        ].eq(
            "FAIL"
        ).any()
    )

    reconciliation_passed = bool(
        not registered_hash_conflict
        and not registered_size_conflict
        and not observed_hash_conflict
        and not observed_size_conflict
        and not group_has_failure
    )

    source_roles = sorted(
        set(
            group[
                "source_control_role"
            ].astype(
                str
            )
        )
    )

    source_stages = sorted(
        set(
            group[
                "source_stage_number"
            ].astype(
                str
            )
        )
    )

    artifact_roles = sorted(
        {
            str(value)
            for value in group[
                "artifact_role"
            ].dropna()
            if str(value).strip()
        }
    )

    formats = sorted(
        {
            str(value)
            for value in group[
                "artifact_format"
            ].dropna()
            if str(value).strip()
        }
    )

    protected_reference = bool(
        group[
            "protected_partition_reference"
        ].fillna(
            False
        ).any()
    )

    duplicate_reconciliation_records.append(
        {
            "resolved_path": (
                resolved_path_text
            ),
            "registration_count": int(
                len(
                    group
                )
            ),
            "registered_hash_count": int(
                len(
                    registered_hashes
                )
            ),
            "registered_size_count": int(
                len(
                    registered_sizes
                )
            ),
            "registered_hash_conflict": (
                registered_hash_conflict
            ),
            "registered_size_conflict": (
                registered_size_conflict
            ),
            "observed_hash_conflict": (
                observed_hash_conflict
            ),
            "observed_size_conflict": (
                observed_size_conflict
            ),
            "group_has_failure": (
                group_has_failure
            ),
            "reconciliation_passed": (
                reconciliation_passed
            ),
            "status": (
                "PASS"
                if reconciliation_passed
                else "FAIL"
            ),
        }
    )

    master_catalogue_records.append(
        {
            "resolved_path": (
                resolved_path_text
            ),
            "relative_to_project": (
                str(
                    Path(
                        resolved_path_text
                    ).relative_to(
                        normalized_resolved_path(
                            PROJECT_ROOT
                        )
                    )
                )
                if Path(
                    resolved_path_text
                ).is_relative_to(
                    normalized_resolved_path(
                        PROJECT_ROOT
                    )
                )
                else None
            ),
            "authority_root": (
                "V0.0"
                if group[
                    "inside_v0_0"
                ].fillna(
                    False
                ).any()
                else (
                    "V0.1"
                    if group[
                        "inside_v0_1"
                    ].fillna(
                        False
                    ).any()
                    else (
                        "V0.2"
                        if group[
                            "inside_v0_2"
                        ].fillna(
                            False
                        ).any()
                        else "OUTSIDE_PROJECT"
                    )
                )
            ),
            "file_suffix": Path(
                resolved_path_text
            ).suffix.casefold(),
            "registration_count": int(
                len(
                    group
                )
            ),
            "source_stage_numbers": (
                source_stages
            ),
            "source_control_roles": (
                source_roles
            ),
            "artifact_roles": (
                artifact_roles
            ),
            "formats": formats,
            "physical_size_bytes": (
                observed_sizes[0]
                if len(
                    observed_sizes
                )
                == 1
                else None
            ),
            "physical_sha256": (
                observed_hashes[0]
                if len(
                    observed_hashes
                )
                == 1
                else None
            ),
            "registered_sha256": (
                registered_hashes[0]
                if len(
                    registered_hashes
                )
                == 1
                else None
            ),
            "registered_size_bytes": (
                registered_sizes[0]
                if len(
                    registered_sizes
                )
                == 1
                else None
            ),
            "protected_partition_reference": (
                protected_reference
            ),
            "semantic_content_loaded": bool(
                group[
                    "semantic_content_loaded"
                ].fillna(
                    False
                ).any()
            ),
            "physical_verification_passed": (
                reconciliation_passed
            ),
            "status": (
                "PASS"
                if reconciliation_passed
                else "FAIL"
            ),
        }
    )


V01_DUPLICATE_ARTIFACT_REGISTRATION_AUDIT = (
    pd.DataFrame(
        duplicate_reconciliation_records
    )
    .sort_values(
        "resolved_path",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)

V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE = (
    pd.DataFrame(
        master_catalogue_records
    )
    .sort_values(
        [
            "authority_root",
            "resolved_path",
        ],
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


# ------------------------------------------------------------
# Summary and warning tables
# ------------------------------------------------------------

V01_UNHASHED_FILE_REFERENCE_AUDIT = (
    V01_MANIFESTED_FILE_REFERENCE_AUDIT.loc[
        V01_MANIFESTED_FILE_REFERENCE_AUDIT[
            "verification_status"
        ].eq(
            "WARNING_UNHASHED_REFERENCE"
        )
    ]
    .copy()
)

V01_FAILED_FILE_REFERENCE_AUDIT = (
    V01_MANIFESTED_FILE_REFERENCE_AUDIT.loc[
        V01_MANIFESTED_FILE_REFERENCE_AUDIT[
            "verification_status"
        ].eq(
            "FAIL"
        )
    ]
    .copy()
)

V01_FAILED_DUPLICATE_RECONCILIATION = (
    V01_DUPLICATE_ARTIFACT_REGISTRATION_AUDIT.loc[
        ~V01_DUPLICATE_ARTIFACT_REGISTRATION_AUDIT[
            "reconciliation_passed"
        ]
    ]
    .copy()
)

manifested_file_summary = pd.DataFrame(
    [
        {
            "metric": "raw_file_reference_count",
            "value": int(
                len(
                    V01_MANIFESTED_FILE_REFERENCE_AUDIT
                )
            ),
        },
        {
            "metric": "unique_resolved_file_count",
            "value": int(
                len(
                    V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE
                )
            ),
        },
        {
            "metric": "verified_reference_count",
            "value": int(
                V01_MANIFESTED_FILE_REFERENCE_AUDIT[
                    "verification_status"
                ].eq(
                    "PASS"
                ).sum()
            ),
        },
        {
            "metric": "unhashed_reference_count",
            "value": int(
                len(
                    V01_UNHASHED_FILE_REFERENCE_AUDIT
                )
            ),
        },
        {
            "metric": "failed_reference_count",
            "value": int(
                len(
                    V01_FAILED_FILE_REFERENCE_AUDIT
                )
            ),
        },
        {
            "metric": "duplicate_registration_group_count",
            "value": int(
                (
                    V01_DUPLICATE_ARTIFACT_REGISTRATION_AUDIT[
                        "registration_count"
                    ]
                    > 1
                ).sum()
            ),
        },
        {
            "metric": "failed_duplicate_reconciliation_count",
            "value": int(
                len(
                    V01_FAILED_DUPLICATE_RECONCILIATION
                )
            ),
        },
        {
            "metric": "v0_0_file_count",
            "value": int(
                V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE[
                    "authority_root"
                ].eq(
                    "V0.0"
                ).sum()
            ),
        },
        {
            "metric": "v0_1_file_count",
            "value": int(
                V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE[
                    "authority_root"
                ].eq(
                    "V0.1"
                ).sum()
            ),
        },
        {
            "metric": "protected_hash_only_file_count",
            "value": int(
                V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE[
                    "protected_partition_reference"
                ].sum()
            ),
        },
    ]
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    manifested_file_summary
)

display(
    V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE[
        [
            "authority_root",
            "relative_to_project",
            "registration_count",
            "source_stage_numbers",
            "artifact_roles",
            "physical_size_bytes",
            "physical_sha256",
            "protected_partition_reference",
            "semantic_content_loaded",
            "physical_verification_passed",
            "status",
        ]
    ]
)

if not V01_UNHASHED_FILE_REFERENCE_AUDIT.empty:
    print(
        "Unhashed file-reference warnings:"
    )

    display(
        V01_UNHASHED_FILE_REFERENCE_AUDIT[
            [
                "source_stage_number",
                "source_control_role",
                "source_json_path",
                "declared_reference",
                "resolved_path",
                "artifact_role",
                "verification_status",
            ]
        ]
    )

if not V01_FAILED_FILE_REFERENCE_AUDIT.empty:
    print(
        "Failed file-reference registrations:"
    )

    display(
        V01_FAILED_FILE_REFERENCE_AUDIT[
            [
                "source_stage_number",
                "source_control_role",
                "source_json_path",
                "declared_reference",
                "resolved_path",
                "expected_size_bytes",
                "observed_size_bytes",
                "expected_sha256",
                "observed_sha256",
                "verification_error",
            ]
        ]
    )

if not V01_FAILED_DUPLICATE_RECONCILIATION.empty:
    print(
        "Failed duplicate-registration reconciliation:"
    )

    display(
        V01_FAILED_DUPLICATE_RECONCILIATION
    )


# ------------------------------------------------------------
# Blocking gates
# ------------------------------------------------------------

if reference_verification_failures:
    rendered_failures = "\n\n".join(
        f"- {failure}"
        for failure in reference_verification_failures
    )

    raise ManifestedFileVerificationError(
        "One or more required manifested files failed physical "
        "verification:\n\n"
        f"{rendered_failures}"
    )

if not V01_FAILED_FILE_REFERENCE_AUDIT.empty:
    raise ManifestedFileVerificationError(
        "The manifested-file audit contains failed file "
        "registrations."
    )

if not V01_FAILED_DUPLICATE_RECONCILIATION.empty:
    raise ManifestedFileVerificationError(
        "Conflicting duplicate artifact registrations were "
        "detected."
    )

if V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE.empty:
    raise ManifestedFileVerificationError(
        "The master physical artifact catalogue is empty."
    )

if not V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE[
    "physical_verification_passed"
].all():
    raise ManifestedFileVerificationError(
        "At least one unique physical artifact did not pass "
        "verification."
    )

outside_project_required_rows = (
    V01_MANIFESTED_FILE_REFERENCE_AUDIT.loc[
        V01_MANIFESTED_FILE_REFERENCE_AUDIT[
            "required"
        ]
        & ~V01_MANIFESTED_FILE_REFERENCE_AUDIT[
            "inside_project"
        ]
    ]
)

if not outside_project_required_rows.empty:
    raise ManifestedFileVerificationError(
        "One or more required manifested files lie outside the "
        "registered project tree."
    )


# ------------------------------------------------------------
# Freeze the verified physical-file authority
# ------------------------------------------------------------

FROZEN_V01_PHYSICAL_ARTIFACT_AUTHORITY: Final[
    dict[str, Any]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "raw_reference_count": int(
        len(
            V01_MANIFESTED_FILE_REFERENCE_AUDIT
        )
    ),
    "unique_file_count": int(
        len(
            V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE
        )
    ),
    "unhashed_reference_warning_count": int(
        len(
            V01_UNHASHED_FILE_REFERENCE_AUDIT
        )
    ),
    "protected_hash_only_file_count": int(
        V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE[
            "protected_partition_reference"
        ].sum()
    ),
    "physical_file_sha256": {
        str(row.resolved_path): str(
            row.physical_sha256
        )
        for row in (
            V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE.itertuples(
                index=False
            )
        )
    },
}


# ------------------------------------------------------------
# State update
#
# Physical existence and hashes are verified.
# Dataset schemas, row counts, and semantic lineage remain
# subject to later independent readback and reconciliation.
# ------------------------------------------------------------

V01_MANIFESTED_FILES_VERIFIED = True
V01_PHYSICAL_ARTIFACT_CATALOGUE_COMPLETE = True

UPSTREAM_ARTIFACTS_VERIFIED = False

PROTECTED_PARTITION_CONTENT_LOADED = False
VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "V0.1 manifested-file physical verification: PASS. Every "
    "required file registration discovered across the persisted "
    "Notebook 00–08 control plane was resolved without wildcard "
    "search, reconciled across duplicate registrations, and "
    "verified against its registered physical size and SHA-256 "
    "where provided. Protected-partition references were handled "
    "by byte-level hashing only; their analytical contents remain "
    "unopened. Semantic dataset, schema, and row-lineage "
    "verification remains pending. No filesystem writes were "
    "performed."
)

                                  metric  value
0               raw_file_reference_count    657
1             unique_resolved_file_count    440
2               verified_reference_count    657
3               unhashed_reference_count      0
4                 failed_reference_count      0
5     duplicate_registration_group_count    193
6  failed_duplicate_reconciliation_count      0
7                        v0_0_file_count      6
8                        v0_1_file_count    434
9         protected_hash_only_file_count      7

,authority_root,relative_to_project,registration_count,source_stage_numbers,artifact_roles,physical_size_bytes,physical_sha256,protected_partition_reference,semantic_content_loaded,physical_verification_passed,status
0,V0.0,v0.0\data\interim\btcusdt_spot_20260710t063746z_c8b5bf12_visible_book_states_top_10.parquet,1,[02],[],4958342,a59fa78b0a3ae895b4b4f5b36267b8510957e3cf8f0e6bd965402c01bbf3a860,False,False,True,PASS
1,V0.0,v0.0\data\raw\metadata\btcusdt_spot_20260710t063746z_c8b5bf12_development_manifest.json,2,"[01, 03]",[raw_development_manifest],1738,f8a3a278d6cd8b674f47d6ec1d5f4f434cb6b0d1fc05ecba609c269b5e36ffe1,False,False,True,PASS
2,V0.0,v0.0\data\raw\metadata\btcusdt_spot_20260710t063746z_c8b5bf12_session.json,2,"[01, 03]",[raw_session_metadata],1777,f7ea3210033b7e6d02d775fdc496422204194d7fd8a64a53ec926f39404e12e8,False,False,True,PASS
3,V0.0,v0.0\data\raw\order_book\btcusdt_spot_20260710t063746z_c8b5bf12_depth_updates.jsonl,2,"[01, 03]",[raw_depth_jsonl],63443258,608aed2608120c92fe4eaf485c43a4b26cf75d1b2120416bc29f415c87ed6c0c,False,False,True,PASS
4,V0.0,v0.0\data\raw\order_book\btcusdt_spot_20260710t063746z_c8b5bf12_snapshot.json,2,"[01, 03]",[raw_snapshot_json],360812,7921a051c2483ed04e4da82c9a1f58d847eab34b4de5a9dd7d8d59d0bfd83bc4,False,False,True,PASS
...,...,...,...,...,...,...,...,...,...,...,...
435,V0.1,v0.1\data\processed\point_process\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__04_event_stream_construction__partition_batch_...,1,[04],[NOTEBOOK_04_PARTITION_BATCH_ARRAYS],295804,c639e065a4d0e63146770df90bc8d12ffa7b89bf793857e0ebaa93b03c512c1d,False,False,True,PASS
436,V0.1,v0.1\data\processed\point_process\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__04_event_stream_construction__partition_event_...,1,[04],[NOTEBOOK_04_PARTITION_EVENT_ARRAYS],569065,fbc20bb575c691f51523938de9ef69dd9729d6bcc46082375712e58737c41de3,False,False,True,PASS
437,V0.1,v0.1\data\processed\trade_book_alignment\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__03_causal_trade_book_alignment__local_s...,2,[03],[],131540683,a18f66ca6a97a66b8f42a4d61b2aa34d26bcee5ae5a8d2054e576c88beede7a3,False,False,True,PASS
438,V0.1,v0.1\data\processed\trade_book_alignment\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__03_causal_trade_book_alignment__local_s...,2,[03],[],131540683,a18f66ca6a97a66b8f42a4d61b2aa34d26bcee5ae5a8d2054e576c88beede7a3,False,False,True,PASS
439,V0.1,v0.1\logs\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_persistence_log.json,2,[08],[persistence_log],1098,222fa7c0c95af810b295cd89107816ad368d7453ef00260d8bb18253a98eb682,False,False,True,PASS

V0.1 manifested-file physical verification: PASS. Every required file registration discovered across the persisted Notebook 00–08 control plane was resolved without wildcard search, reconciled across duplicate registrations, and verified against its registered physical size and SHA-256 where provided. Protected-partition references were handled by byte-level hashing only; their analytical contents remain unopened. Semantic dataset, schema, and row-lineage verification remains pending. No filesystem writes were performed.

In [11]:
# ============================================================
# Safe contract-DataFrame discovery
#
# Snapshot the notebook namespace before iteration because loop
# variables created at notebook scope mutate globals().
# ============================================================

if "CONTRACT_REQUIRED_COLUMNS" not in globals():
    raise RuntimeError(
        "CONTRACT_REQUIRED_COLUMNS is unavailable. Run the "
        "preceding definitions before this discovery block."
    )

if not isinstance(
    CONTRACT_REQUIRED_COLUMNS,
    set,
):
    CONTRACT_REQUIRED_COLUMNS = set(
        CONTRACT_REQUIRED_COLUMNS
    )

normalized_required_columns = {
    str(column)
    for column in CONTRACT_REQUIRED_COLUMNS
}

# The snapshot must be created before entering the loop.
GLOBAL_NAMESPACE_SNAPSHOT = tuple(
    globals().copy().items()
)

contract_dataframe_matches: list[
    tuple[str, pd.DataFrame]
] = []

seen_dataframe_object_ids: set[int] = set()

for variable_name, candidate in GLOBAL_NAMESPACE_SNAPSHOT:
    if variable_name.startswith("_"):
        continue

    if not isinstance(
        candidate,
        pd.DataFrame,
    ):
        continue

    candidate_columns = {
        str(column)
        for column in candidate.columns
    }

    if not normalized_required_columns.issubset(
        candidate_columns
    ):
        continue

    candidate_object_id = id(
        candidate
    )

    # Prevent multiple aliases to the same DataFrame from being
    # treated as separate candidate contracts.
    if candidate_object_id in seen_dataframe_object_ids:
        continue

    seen_dataframe_object_ids.add(
        candidate_object_id
    )

    contract_dataframe_matches.append(
        (
            str(variable_name),
            candidate,
        )
    )


CONTRACT_DATAFRAME_DISCOVERY = pd.DataFrame(
    [
        {
            "variable_name": variable_name,
            "row_count": int(
                len(candidate)
            ),
            "column_count": int(
                candidate.shape[1]
            ),
            "required_columns_present": True,
            "columns": list(
                map(
                    str,
                    candidate.columns,
                )
            ),
        }
        for variable_name, candidate in (
            contract_dataframe_matches
        )
    ],
    columns=[
        "variable_name",
        "row_count",
        "column_count",
        "required_columns_present",
        "columns",
    ],
)

display(
    CONTRACT_DATAFRAME_DISCOVERY
)

if not contract_dataframe_matches:
    available_dataframe_columns = {
        variable_name: list(
            map(
                str,
                candidate.columns,
            )
        )
        for variable_name, candidate in (
            GLOBAL_NAMESPACE_SNAPSHOT
        )
        if isinstance(
            candidate,
            pd.DataFrame,
        )
        and not variable_name.startswith("_")
    }

    raise RuntimeError(
        "No DataFrame contains the complete contract schema.\n"
        f"Required columns: "
        f"{sorted(normalized_required_columns)}\n"
        "Available DataFrames and columns:\n"
        + json.dumps(
            available_dataframe_columns,
            indent=2,
            ensure_ascii=False,
            default=str,
        )
    )

print(
    "Contract DataFrame discovery completed successfully. "
    f"Candidate count: {len(contract_dataframe_matches)}."
)

,variable_name,row_count,column_count,required_columns_present,columns
0,V01_DATAFRAME_CONTRACT_RECONCILIATION,12,19,True,"[contract_relative_path, contract_path, target_relative_path, target_path, contract_artifact_type, contract_label, contract_format, declared_row_count, obse..."
1,V01_FAILED_CONTRACT_RECONCILIATION,0,19,True,"[contract_relative_path, contract_path, target_relative_path, target_path, contract_artifact_type, contract_label, contract_format, declared_row_count, obse..."

Contract DataFrame discovery completed successfully. Candidate count: 2.

In [12]:
# ============================================================
# Authoritative DataFrame-contract reconciliation gate
#
# This cell:
# - selects the non-empty authoritative reconciliation table;
# - rejects empty diagnostic subsets as primary authority;
# - verifies required schema and unique contract-target pairs;
# - confirms every registered DataFrame contract passed;
# - reconciles the optional failed-row diagnostic table;
# - freezes the verified contract authority for later lineage work.
#
# No filesystem writes are performed.
# ============================================================


class DataFrameContractGateError(RuntimeError):
    """Raised when persisted DataFrame contracts are inconsistent."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

if "contract_dataframe_matches" not in globals():
    raise DataFrameContractGateError(
        "Contract DataFrame discovery has not been executed."
    )

if "CONTRACT_REQUIRED_COLUMNS" not in globals():
    raise DataFrameContractGateError(
        "CONTRACT_REQUIRED_COLUMNS is unavailable."
    )

if not contract_dataframe_matches:
    raise DataFrameContractGateError(
        "No contract reconciliation DataFrame candidates exist."
    )


# ------------------------------------------------------------
# Deterministic authoritative-table selection
# ------------------------------------------------------------

PREFERRED_CONTRACT_RECONCILIATION_VARIABLE: Final[str] = (
    "V01_DATAFRAME_CONTRACT_RECONCILIATION"
)

DIAGNOSTIC_FAILED_CONTRACT_VARIABLE: Final[str] = (
    "V01_FAILED_CONTRACT_RECONCILIATION"
)

candidate_lookup: dict[str, pd.DataFrame] = {
    str(variable_name): candidate
    for variable_name, candidate in contract_dataframe_matches
}

if (
    PREFERRED_CONTRACT_RECONCILIATION_VARIABLE
    in candidate_lookup
):
    selected_contract_variable = (
        PREFERRED_CONTRACT_RECONCILIATION_VARIABLE
    )

    selected_contract_dataframe = candidate_lookup[
        selected_contract_variable
    ]

else:
    eligible_primary_candidates = [
        (
            variable_name,
            candidate,
        )
        for variable_name, candidate in (
            contract_dataframe_matches
        )
        if (
            len(candidate) > 0
            and "failed" not in variable_name.casefold()
            and "error" not in variable_name.casefold()
        )
    ]

    if len(eligible_primary_candidates) != 1:
        raise DataFrameContractGateError(
            "Unable to select one authoritative contract "
            "reconciliation DataFrame.\n"
            f"Eligible candidates: "
            f"{[name for name, _ in eligible_primary_candidates]}"
        )

    (
        selected_contract_variable,
        selected_contract_dataframe,
    ) = eligible_primary_candidates[0]


if selected_contract_dataframe.empty:
    raise DataFrameContractGateError(
        "The selected authoritative contract reconciliation "
        "DataFrame is empty."
    )


# ------------------------------------------------------------
# Schema verification
# ------------------------------------------------------------

required_contract_columns = {
    str(column)
    for column in CONTRACT_REQUIRED_COLUMNS
}

observed_contract_columns = {
    str(column)
    for column in selected_contract_dataframe.columns
}

missing_contract_columns = sorted(
    required_contract_columns
    - observed_contract_columns
)

if missing_contract_columns:
    raise DataFrameContractGateError(
        "The authoritative contract reconciliation table is "
        "missing required columns:\n"
        f"{missing_contract_columns}"
    )


V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION = (
    selected_contract_dataframe.copy(
        deep=True
    )
)


# ------------------------------------------------------------
# Structural normalization
# ------------------------------------------------------------

for path_column in (
    "contract_relative_path",
    "contract_path",
    "target_relative_path",
    "target_path",
):
    if path_column in (
        V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION.columns
    ):
        V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION[
            path_column
        ] = (
            V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION[
                path_column
            ]
            .astype(
                "string"
            )
            .str.strip()
        )


V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION[
    "status"
] = (
    V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION[
        "status"
    ]
    .astype(
        "string"
    )
    .str.strip()
    .str.upper()
)


# ------------------------------------------------------------
# Required-value checks
# ------------------------------------------------------------

REQUIRED_NON_NULL_CONTRACT_COLUMNS: Final[
    tuple[str, ...]
] = (
    "contract_relative_path",
    "contract_path",
    "target_relative_path",
    "target_path",
    "contract_artifact_type",
    "contract_format",
    "status",
)

null_violation_records: list[dict[str, Any]] = []

for column_name in REQUIRED_NON_NULL_CONTRACT_COLUMNS:
    if (
        column_name
        not in V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION.columns
    ):
        continue

    column_values = (
        V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION[
            column_name
        ]
    )

    null_mask = (
        column_values.isna()
        | column_values.astype(
            "string"
        ).str.strip().eq(
            ""
        )
    )

    for row_index in (
        V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION.index[
            null_mask
        ]
    ):
        null_violation_records.append(
            {
                "row_index": int(
                    row_index
                ),
                "column_name": column_name,
                "violation": (
                    "MISSING_REQUIRED_VALUE"
                ),
            }
        )


V01_CONTRACT_NULL_VIOLATION_AUDIT = pd.DataFrame(
    null_violation_records,
    columns=[
        "row_index",
        "column_name",
        "violation",
    ],
)

if not V01_CONTRACT_NULL_VIOLATION_AUDIT.empty:
    raise DataFrameContractGateError(
        "Required contract fields contain null or blank values:\n"
        + V01_CONTRACT_NULL_VIOLATION_AUDIT.to_string(
            index=False
        )
    )


# ------------------------------------------------------------
# Contract-target uniqueness
# ------------------------------------------------------------

CONTRACT_PAIR_KEY_COLUMNS: Final[
    tuple[str, str]
] = (
    "contract_relative_path",
    "target_relative_path",
)

duplicate_contract_pair_mask = (
    V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION.duplicated(
        subset=list(
            CONTRACT_PAIR_KEY_COLUMNS
        ),
        keep=False,
    )
)

V01_DUPLICATE_CONTRACT_PAIR_AUDIT = (
    V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION.loc[
        duplicate_contract_pair_mask
    ]
    .copy()
)

if not V01_DUPLICATE_CONTRACT_PAIR_AUDIT.empty:
    raise DataFrameContractGateError(
        "Duplicate contract-target registrations were detected:\n"
        + V01_DUPLICATE_CONTRACT_PAIR_AUDIT[
            list(
                CONTRACT_PAIR_KEY_COLUMNS
            )
            + [
                "status",
            ]
        ].to_string(
            index=False
        )
    )


# ------------------------------------------------------------
# Status gate
# ------------------------------------------------------------

PASS_LIKE_CONTRACT_STATUSES: Final[
    set[str]
] = {
    "PASS",
    "MATCH",
    "VERIFIED",
    "ACCEPTED",
    "PASS_VERIFIED",
    "PASS_CONTRACT_RECONCILIATION",
}

contract_status_series = (
    V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION[
        "status"
    ]
)

pass_like_mask = contract_status_series.isin(
    PASS_LIKE_CONTRACT_STATUSES
)

# Preserve compatibility with explicit, descriptive PASS statuses.
pass_like_mask = (
    pass_like_mask
    | contract_status_series.str.startswith(
        "PASS",
        na=False,
    )
)

V01_FAILED_CONTRACT_ROWS_FROM_AUTHORITY = (
    V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION.loc[
        ~pass_like_mask
    ]
    .copy()
)


# ------------------------------------------------------------
# Reconcile the separate failed-row diagnostic table
# ------------------------------------------------------------

diagnostic_failed_dataframe = candidate_lookup.get(
    DIAGNOSTIC_FAILED_CONTRACT_VARIABLE
)

if diagnostic_failed_dataframe is None:
    diagnostic_failed_dataframe = pd.DataFrame(
        columns=(
            V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION.columns
        )
    )

else:
    diagnostic_failed_dataframe = (
        diagnostic_failed_dataframe.copy(
            deep=True
        )
    )


authoritative_failed_count = int(
    len(
        V01_FAILED_CONTRACT_ROWS_FROM_AUTHORITY
    )
)

diagnostic_failed_count = int(
    len(
        diagnostic_failed_dataframe
    )
)

if diagnostic_failed_count != authoritative_failed_count:
    raise DataFrameContractGateError(
        "The separate failed-contract diagnostic table does not "
        "reconcile with the authoritative status filter.\n"
        f"Authoritative failed rows: {authoritative_failed_count}\n"
        f"Diagnostic failed rows: {diagnostic_failed_count}"
    )


if (
    authoritative_failed_count > 0
    and set(
        CONTRACT_PAIR_KEY_COLUMNS
    ).issubset(
        diagnostic_failed_dataframe.columns
    )
):
    authoritative_failed_keys = {
        tuple(
            str(value)
            for value in row
        )
        for row in (
            V01_FAILED_CONTRACT_ROWS_FROM_AUTHORITY[
                list(
                    CONTRACT_PAIR_KEY_COLUMNS
                )
            ]
            .itertuples(
                index=False,
                name=None,
            )
        )
    }

    diagnostic_failed_keys = {
        tuple(
            str(value)
            for value in row
        )
        for row in (
            diagnostic_failed_dataframe[
                list(
                    CONTRACT_PAIR_KEY_COLUMNS
                )
            ]
            .itertuples(
                index=False,
                name=None,
            )
        )
    }

    if (
        authoritative_failed_keys
        != diagnostic_failed_keys
    ):
        raise DataFrameContractGateError(
            "The failed-contract diagnostic table contains a "
            "different contract-target set from the authoritative "
            "failed-row filter."
        )


# ------------------------------------------------------------
# Declared-versus-observed shape checks
# ------------------------------------------------------------

shape_check_records: list[dict[str, Any]] = []

for row_index, row in (
    V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION.iterrows()
):
    declared_row_count = row.get(
        "declared_row_count"
    )

    observed_row_count = row.get(
        "observed_row_count"
    )

    declared_column_count = row.get(
        "declared_column_count"
    )

    observed_column_count = row.get(
        "observed_column_count"
    )

    row_count_matches: bool | None = None
    column_count_matches: bool | None = None

    if (
        pd.notna(
            declared_row_count
        )
        and pd.notna(
            observed_row_count
        )
    ):
        row_count_matches = bool(
            int(
                declared_row_count
            )
            == int(
                observed_row_count
            )
        )

    if (
        pd.notna(
            declared_column_count
        )
        and pd.notna(
            observed_column_count
        )
    ):
        column_count_matches = bool(
            int(
                declared_column_count
            )
            == int(
                observed_column_count
            )
        )

    shape_check_records.append(
        {
            "row_index": int(
                row_index
            ),
            "contract_relative_path": row[
                "contract_relative_path"
            ],
            "target_relative_path": row[
                "target_relative_path"
            ],
            "declared_row_count": (
                declared_row_count
            ),
            "observed_row_count": (
                observed_row_count
            ),
            "row_count_matches": (
                row_count_matches
            ),
            "declared_column_count": (
                declared_column_count
            ),
            "observed_column_count": (
                observed_column_count
            ),
            "column_count_matches": (
                column_count_matches
            ),
        }
    )


V01_CONTRACT_SHAPE_RECONCILIATION = pd.DataFrame(
    shape_check_records
)

shape_mismatch_mask = (
    V01_CONTRACT_SHAPE_RECONCILIATION[
        "row_count_matches"
    ].eq(
        False
    )
    | V01_CONTRACT_SHAPE_RECONCILIATION[
        "column_count_matches"
    ].eq(
        False
    )
)

V01_CONTRACT_SHAPE_MISMATCH_AUDIT = (
    V01_CONTRACT_SHAPE_RECONCILIATION.loc[
        shape_mismatch_mask
    ]
    .copy()
)


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

V01_DATAFRAME_CONTRACT_GATE_SUMMARY = pd.DataFrame(
    [
        {
            "metric": (
                "selected_authoritative_variable"
            ),
            "value": selected_contract_variable,
        },
        {
            "metric": "registered_contract_count",
            "value": int(
                len(
                    V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION
                )
            ),
        },
        {
            "metric": "unique_contract_path_count",
            "value": int(
                V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION[
                    "contract_relative_path"
                ].nunique(
                    dropna=False
                )
            ),
        },
        {
            "metric": "unique_target_path_count",
            "value": int(
                V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION[
                    "target_relative_path"
                ].nunique(
                    dropna=False
                )
            ),
        },
        {
            "metric": "pass_like_contract_count",
            "value": int(
                pass_like_mask.sum()
            ),
        },
        {
            "metric": "failed_contract_count",
            "value": authoritative_failed_count,
        },
        {
            "metric": (
                "diagnostic_failed_contract_count"
            ),
            "value": diagnostic_failed_count,
        },
        {
            "metric": "shape_mismatch_count",
            "value": int(
                len(
                    V01_CONTRACT_SHAPE_MISMATCH_AUDIT
                )
            ),
        },
        {
            "metric": "duplicate_pair_count",
            "value": int(
                len(
                    V01_DUPLICATE_CONTRACT_PAIR_AUDIT
                )
            ),
        },
        {
            "metric": "null_violation_count",
            "value": int(
                len(
                    V01_CONTRACT_NULL_VIOLATION_AUDIT
                )
            ),
        },
    ]
)


display(
    V01_DATAFRAME_CONTRACT_GATE_SUMMARY
)

display(
    V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION
)

if not V01_CONTRACT_SHAPE_MISMATCH_AUDIT.empty:
    print(
        "Declared-versus-observed shape mismatches:"
    )

    display(
        V01_CONTRACT_SHAPE_MISMATCH_AUDIT
    )

if not V01_FAILED_CONTRACT_ROWS_FROM_AUTHORITY.empty:
    print(
        "Failed authoritative DataFrame contracts:"
    )

    display(
        V01_FAILED_CONTRACT_ROWS_FROM_AUTHORITY
    )


# ------------------------------------------------------------
# Blocking gates
# ------------------------------------------------------------

if authoritative_failed_count != 0:
    raise DataFrameContractGateError(
        "One or more authoritative DataFrame contracts did not "
        "pass reconciliation."
    )

if not V01_CONTRACT_SHAPE_MISMATCH_AUDIT.empty:
    raise DataFrameContractGateError(
        "One or more declared DataFrame shapes do not match their "
        "observed persisted targets."
    )

if not pass_like_mask.all():
    raise DataFrameContractGateError(
        "At least one contract status is not pass-like."
    )


# ------------------------------------------------------------
# Freeze verified contract authority
# ------------------------------------------------------------

FROZEN_V01_DATAFRAME_CONTRACT_AUTHORITY: Final[
    dict[str, Any]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "selected_variable": (
        selected_contract_variable
    ),
    "registered_contract_count": int(
        len(
            V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION
        )
    ),
    "failed_contract_count": (
        authoritative_failed_count
    ),
    "shape_mismatch_count": int(
        len(
            V01_CONTRACT_SHAPE_MISMATCH_AUDIT
        )
    ),
    "contract_target_pairs": [
        {
            "contract_relative_path": str(
                row.contract_relative_path
            ),
            "target_relative_path": str(
                row.target_relative_path
            ),
            "contract_artifact_type": str(
                row.contract_artifact_type
            ),
            "contract_format": str(
                row.contract_format
            ),
            "status": str(
                row.status
            ),
        }
        for row in (
            V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION.itertuples(
                index=False
            )
        )
    ],
}


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

V01_DATAFRAME_CONTRACTS_VERIFIED = True
V01_DATAFRAME_CONTRACT_GATE_PASSED = True

UPSTREAM_ARTIFACTS_VERIFIED = False

PROTECTED_PARTITION_CONTENT_LOADED = False
VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "V0.1 DataFrame-contract reconciliation: PASS. "
    f"{len(V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION)} "
    "registered contract-target pairs were uniquely identified, "
    "their required fields and declared shapes reconciled, and "
    "all statuses verified as pass-like. The empty failed-row "
    "table reconciles exactly with zero authoritative failures. "
    "No filesystem writes were performed."
)

                             metric                                  value
0   selected_authoritative_variable  V01_DATAFRAME_CONTRACT_RECONCILIATION
1         registered_contract_count                                     12
2        unique_contract_path_count                                     12
3          unique_target_path_count                                     12
4          pass_like_contract_count                                     12
5             failed_contract_count                                      0
6  diagnostic_failed_contract_count                                      0
7              shape_mismatch_count                                      0
8              duplicate_pair_count                                      0
9              null_violation_count                                      0

,contract_relative_path,contract_path,target_relative_path,target_path,contract_artifact_type,contract_label,contract_format,declared_row_count,observed_row_count,declared_column_count,observed_column_count,column_schema_declared,logical_schema_declared,contract_self_hash_matches,target_raw_hash_matches,target_table_hash_matches,target_column_order_matches,status,error
0,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__f...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__f...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,FEATURE_MISSINGNESS_POLICY_AUDIT_CONTRACT,feature_missingness_policy_audit,PARQUET,576,576,14,14,True,True,True,True,True,True,PASS,None
1,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__f...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__f...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,FUTURE_LABEL_HORIZON_CONTRACT_CONTRACT,future_label_horizon_contract,PARQUET,4,4,12,12,True,True,True,True,True,True,PASS,None
2,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__f...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__f...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,FUTURE_LABEL_MISSINGNESS_AUDIT_CONTRACT,future_label_missingness_audit,PARQUET,140,140,9,9,True,True,True,True,True,True,PASS,None
3,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__f...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__f...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,FUTURE_LABEL_REGISTRY_CONTRACT,future_label_registry,PARQUET,140,140,15,15,True,True,True,True,True,True,PASS,None
4,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__f...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__f...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,FUTURE_LABEL_SOURCE_RESOLUTION_AUDIT_CONTRACT,future_label_source_resolution_audit,PARQUET,4,4,4,4,True,True,True,True,True,True,PASS,None
5,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__m...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__m...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,MARKET_STATE_FEATURE_REGISTRY_CONTRACT,market_state_feature_registry,PARQUET,571,571,44,44,True,True,True,True,True,True,PASS,None
6,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__n...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__n...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,NOTEBOOK_05_FINAL_ACCEPTANCE_GATES_CONTRACT,notebook_05_final_acceptance_gates,PARQUET,13,13,4,4,True,True,True,True,True,True,PASS,None
7,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__n...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__n...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,NOTEBOOK_05_PERSISTED_ARTIFACT_AUDIT_CONTRACT,notebook_05_persisted_artifact_audit,PARQUET,9,9,16,16,True,True,True,True,True,True,PASS,None
8,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__n...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__n...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,NOTEBOOK_05_READBACK_AUDIT_CONTRACT,notebook_05_readback_audit,PARQUET,9,9,8,8,True,True,True,True,True,True,PASS,None
9,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__p...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__p...,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,PRIMARY_BATCH_FEATURE_AVAILABILITY_CONTRACT,primary_batch_feature_availability,PARQUET,13564,13564,8,8,True,True,True,True,True,True,PASS,None
10,v0.1\data\processed\features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__primary_batch_market_stat...,d:\clown project\v0.1\data\processed\features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__primary_...,v0.1\data\processed\features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__primary_batch_market_stat...,d:\clown project\v0.1\data\processed\features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__primary_...,PRIMARY_BATCH_MARKET_STATE_FEATURES_CONTRACT,primary_batch_market_state_features,PARQUET,13564,13564,577,577,True,True,True,True,True,True,PASS,None
11,v0.1\data\processed\labels\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__primary_batch_future_labels...,d:\clown project\v0.1\data\processed\labels\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__primary_ba...,v0.1\data\processed\labels\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__primary_batch_future_labels...,d:\clown project\v0.1\data\processed\labels\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__primary_ba...,PRIMARY_BATCH_FUTURE_LABELS_CONTRACT,primary_batch_future_labels,PARQUET,13564,13564,146,146,True,True,True,True,True,True,PASS,None

V0.1 DataFrame-contract reconciliation: PASS. 12 registered contract-target pairs were uniquely identified, their required fields and declared shapes reconciled, and all statuses verified as pass-like. The empty failed-row table reconciles exactly with zero authoritative failures. No filesystem writes were performed.

In [14]:
# ============================================================
# Notebook 05 contract-target binding
#
# This cell:
# - uses contract_label as the canonical lookup key;
# - rebuilds the target registry from the verified contract table;
# - reads only the two required registry tables;
# - reads schema metadata, not analytical rows, for primary
#   feature and future-label tables;
# - preserves protected-partition closure.
#
# No filesystem writes are performed.
# ============================================================


class Notebook05TargetBindingError(RuntimeError):
    """Raised when a Notebook 05 contract target cannot be bound safely."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

if not globals().get(
    "V01_DATAFRAME_CONTRACT_GATE_PASSED",
    False,
):
    raise Notebook05TargetBindingError(
        "The Notebook 05 DataFrame-contract gate has not passed."
    )

if (
    "V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION"
    not in globals()
):
    raise Notebook05TargetBindingError(
        "The authoritative Notebook 05 contract reconciliation "
        "table is unavailable."
    )

if PROTECTED_PARTITION_CONTENT_LOADED:
    raise Notebook05TargetBindingError(
        "Protected partition content was unexpectedly loaded."
    )


# ------------------------------------------------------------
# Canonical labels
# ------------------------------------------------------------

FEATURE_REGISTRY_LABEL: Final[str] = (
    "market_state_feature_registry"
)

FUTURE_LABEL_REGISTRY_LABEL: Final[str] = (
    "future_label_registry"
)

PRIMARY_FEATURE_TABLE_LABEL: Final[str] = (
    "primary_batch_market_state_features"
)

PRIMARY_LABEL_TABLE_LABEL: Final[str] = (
    "primary_batch_future_labels"
)

PRIMARY_FEATURE_AVAILABILITY_LABEL: Final[str] = (
    "primary_batch_feature_availability"
)

REQUIRED_NOTEBOOK05_LABELS: Final[set[str]] = {
    FEATURE_REGISTRY_LABEL,
    FUTURE_LABEL_REGISTRY_LABEL,
    PRIMARY_FEATURE_TABLE_LABEL,
    PRIMARY_LABEL_TABLE_LABEL,
    PRIMARY_FEATURE_AVAILABILITY_LABEL,
}


# ------------------------------------------------------------
# Label and path normalization
# ------------------------------------------------------------

def normalize_contract_label(
    value: Any,
) -> str:
    """Normalize one contract label into a stable dictionary key."""

    normalized = re.sub(
        r"[^a-z0-9]+",
        "_",
        str(value).strip().casefold(),
    )

    return normalized.strip(
        "_"
    )


def canonical_existing_file(
    value: Any,
    *,
    field_name: str,
) -> Path:
    """Resolve and verify one exact registered file path."""

    if value is None or pd.isna(
        value
    ):
        raise Notebook05TargetBindingError(
            f"Missing required path field: {field_name}"
        )

    path = normalized_resolved_path(
        Path(
            str(value)
        )
    )

    require_path_inside_root(
        path=path,
        authorized_root=V01_ROOT,
        role=field_name,
    )

    if not path.exists():
        raise Notebook05TargetBindingError(
            f"Registered file does not exist for {field_name}: {path}"
        )

    if not path.is_file():
        raise Notebook05TargetBindingError(
            f"Registered path is not a regular file for "
            f"{field_name}: {path}"
        )

    return path


# ------------------------------------------------------------
# Build canonical contract-row registry
# ------------------------------------------------------------

notebook05_contract_table = (
    V01_AUTHORITATIVE_DATAFRAME_CONTRACT_RECONCILIATION.copy(
        deep=True
    )
)

if "contract_label" not in notebook05_contract_table.columns:
    raise Notebook05TargetBindingError(
        "The authoritative contract table has no contract_label column."
    )

notebook05_contract_table[
    "normalized_contract_label"
] = notebook05_contract_table[
    "contract_label"
].map(
    normalize_contract_label
)

blank_label_mask = notebook05_contract_table[
    "normalized_contract_label"
].eq(
    ""
)

if blank_label_mask.any():
    raise Notebook05TargetBindingError(
        "At least one Notebook 05 contract has a blank normalized label."
    )

duplicate_label_mask = notebook05_contract_table.duplicated(
    subset=[
        "normalized_contract_label",
    ],
    keep=False,
)

V01_NOTEBOOK05_DUPLICATE_LABEL_AUDIT = (
    notebook05_contract_table.loc[
        duplicate_label_mask
    ]
    .copy()
)

if not V01_NOTEBOOK05_DUPLICATE_LABEL_AUDIT.empty:
    raise Notebook05TargetBindingError(
        "Notebook 05 contract labels are not unique:\n"
        + V01_NOTEBOOK05_DUPLICATE_LABEL_AUDIT[
            [
                "contract_label",
                "normalized_contract_label",
                "contract_relative_path",
                "target_relative_path",
            ]
        ].to_string(
            index=False
        )
    )


NOTEBOOK05_CONTRACT_ROW_BY_LABEL: dict[
    str,
    dict[str, Any],
] = {
    str(row.normalized_contract_label): row._asdict()
    for row in notebook05_contract_table.itertuples(
        index=False
    )
}


missing_required_labels = sorted(
    REQUIRED_NOTEBOOK05_LABELS
    - set(
        NOTEBOOK05_CONTRACT_ROW_BY_LABEL
    )
)

if missing_required_labels:
    raise Notebook05TargetBindingError(
        "Required Notebook 05 contract labels are missing:\n"
        f"{missing_required_labels}\n"
        "Available normalized labels:\n"
        f"{sorted(NOTEBOOK05_CONTRACT_ROW_BY_LABEL)}"
    )


# ------------------------------------------------------------
# Exact target-path registry
# ------------------------------------------------------------

NOTEBOOK05_TARGET_PATH_BY_LABEL: dict[
    str,
    Path,
] = {}

NOTEBOOK05_CONTRACT_PATH_BY_LABEL: dict[
    str,
    Path,
] = {}

for normalized_label, row in (
    NOTEBOOK05_CONTRACT_ROW_BY_LABEL.items()
):
    NOTEBOOK05_TARGET_PATH_BY_LABEL[
        normalized_label
    ] = canonical_existing_file(
        row[
            "target_path"
        ],
        field_name=(
            f"{normalized_label}.target_path"
        ),
    )

    NOTEBOOK05_CONTRACT_PATH_BY_LABEL[
        normalized_label
    ] = canonical_existing_file(
        row[
            "contract_path"
        ],
        field_name=(
            f"{normalized_label}.contract_path"
        ),
    )


# ------------------------------------------------------------
# Schema-only metadata reader
#
# Reading parquet footer metadata does not materialize rows.
# ------------------------------------------------------------

try:
    import pyarrow.parquet as pq

except ImportError as exc:
    raise Notebook05TargetBindingError(
        "pyarrow is required for schema-only parquet metadata "
        "inspection without loading analytical rows."
    ) from exc


def parquet_schema_metadata(
    path: Path,
) -> dict[str, Any]:
    """Read Parquet footer and schema without loading table rows."""

    parquet_file = pq.ParquetFile(
        path
    )

    arrow_schema = parquet_file.schema_arrow
    parquet_metadata = parquet_file.metadata

    columns = [
        {
            "position": int(
                position
            ),
            "name": str(
                field.name
            ),
            "arrow_type": str(
                field.type
            ),
            "nullable": bool(
                field.nullable
            ),
        }
        for position, field in enumerate(
            arrow_schema
        )
    ]

    return {
        "path": str(
            path
        ),
        "format": "PARQUET",
        "row_count": int(
            parquet_metadata.num_rows
        ),
        "column_count": int(
            parquet_metadata.num_columns
        ),
        "row_group_count": int(
            parquet_metadata.num_row_groups
        ),
        "column_names": [
            column[
                "name"
            ]
            for column in columns
        ],
        "columns": columns,
    }


NOTEBOOK05_TARGET_SCHEMA_BY_LABEL: dict[
    str,
    dict[str, Any],
] = {}

schema_verification_records: list[
    dict[str, Any]
] = []

for normalized_label, row in (
    NOTEBOOK05_CONTRACT_ROW_BY_LABEL.items()
):
    target_path = NOTEBOOK05_TARGET_PATH_BY_LABEL[
        normalized_label
    ]

    declared_format = str(
        row[
            "contract_format"
        ]
    ).strip().upper()

    if declared_format != "PARQUET":
        raise Notebook05TargetBindingError(
            "Unexpected Notebook 05 contract format.\n"
            f"Label: {normalized_label}\n"
            f"Declared format: {declared_format}"
        )

    schema_metadata = parquet_schema_metadata(
        target_path
    )

    declared_row_count = int(
        row[
            "declared_row_count"
        ]
    )

    declared_column_count = int(
        row[
            "declared_column_count"
        ]
    )

    row_count_matches = bool(
        schema_metadata[
            "row_count"
        ]
        == declared_row_count
    )

    column_count_matches = bool(
        schema_metadata[
            "column_count"
        ]
        == declared_column_count
    )

    if not row_count_matches:
        raise Notebook05TargetBindingError(
            "Parquet metadata row count does not match the "
            "verified contract.\n"
            f"Label: {normalized_label}\n"
            f"Declared: {declared_row_count}\n"
            f"Observed: {schema_metadata['row_count']}"
        )

    if not column_count_matches:
        raise Notebook05TargetBindingError(
            "Parquet metadata column count does not match the "
            "verified contract.\n"
            f"Label: {normalized_label}\n"
            f"Declared: {declared_column_count}\n"
            f"Observed: {schema_metadata['column_count']}"
        )

    NOTEBOOK05_TARGET_SCHEMA_BY_LABEL[
        normalized_label
    ] = schema_metadata

    schema_verification_records.append(
        {
            "contract_label": str(
                row[
                    "contract_label"
                ]
            ),
            "normalized_contract_label": (
                normalized_label
            ),
            "target_path": str(
                target_path
            ),
            "declared_row_count": (
                declared_row_count
            ),
            "metadata_row_count": (
                schema_metadata[
                    "row_count"
                ]
            ),
            "row_count_matches": (
                row_count_matches
            ),
            "declared_column_count": (
                declared_column_count
            ),
            "metadata_column_count": (
                schema_metadata[
                    "column_count"
                ]
            ),
            "column_count_matches": (
                column_count_matches
            ),
            "analytical_rows_loaded": False,
            "status": "PASS",
        }
    )


V01_NOTEBOOK05_SCHEMA_METADATA_AUDIT = pd.DataFrame(
    schema_verification_records
)


# ------------------------------------------------------------
# Fully read only the required registry tables
#
# These are schema/definition registries, not primary feature
# or future-label observation tables.
# ------------------------------------------------------------

SAFE_FULL_READ_LABELS: Final[set[str]] = {
    FEATURE_REGISTRY_LABEL,
    FUTURE_LABEL_REGISTRY_LABEL,
}

existing_fully_read_targets = globals().get(
    "FULLY_READ_NOTEBOOK05_TARGETS",
    {},
)

if not isinstance(
    existing_fully_read_targets,
    dict,
):
    existing_fully_read_targets = {}


FULLY_READ_NOTEBOOK05_TARGETS: dict[
    str,
    pd.DataFrame,
] = {}

# Preserve only valid DataFrame entries, normalized by key.
for existing_key, existing_value in (
    tuple(
        existing_fully_read_targets.items()
    )
):
    if isinstance(
        existing_value,
        pd.DataFrame,
    ):
        FULLY_READ_NOTEBOOK05_TARGETS[
            normalize_contract_label(
                existing_key
            )
        ] = existing_value


registry_read_records: list[
    dict[str, Any]
] = []

for normalized_label in sorted(
    SAFE_FULL_READ_LABELS
):
    target_path = NOTEBOOK05_TARGET_PATH_BY_LABEL[
        normalized_label
    ]

    registry_frame = pd.read_parquet(
        target_path
    )

    expected_schema = NOTEBOOK05_TARGET_SCHEMA_BY_LABEL[
        normalized_label
    ]

    observed_row_count = int(
        len(
            registry_frame
        )
    )

    observed_column_count = int(
        registry_frame.shape[1]
    )

    row_count_matches = bool(
        observed_row_count
        == expected_schema[
            "row_count"
        ]
    )

    column_count_matches = bool(
        observed_column_count
        == expected_schema[
            "column_count"
        ]
    )

    column_order_matches = bool(
        list(
            map(
                str,
                registry_frame.columns,
            )
        )
        == expected_schema[
            "column_names"
        ]
    )

    if not row_count_matches:
        raise Notebook05TargetBindingError(
            "Registry row-count mismatch.\n"
            f"Label: {normalized_label}\n"
            f"Expected: {expected_schema['row_count']}\n"
            f"Observed: {observed_row_count}"
        )

    if not column_count_matches:
        raise Notebook05TargetBindingError(
            "Registry column-count mismatch.\n"
            f"Label: {normalized_label}\n"
            f"Expected: {expected_schema['column_count']}\n"
            f"Observed: {observed_column_count}"
        )

    if not column_order_matches:
        raise Notebook05TargetBindingError(
            "Registry column order does not match persisted "
            f"Parquet schema for label: {normalized_label}"
        )

    FULLY_READ_NOTEBOOK05_TARGETS[
        normalized_label
    ] = registry_frame

    registry_read_records.append(
        {
            "normalized_contract_label": (
                normalized_label
            ),
            "target_path": str(
                target_path
            ),
            "row_count": observed_row_count,
            "column_count": observed_column_count,
            "row_count_matches": (
                row_count_matches
            ),
            "column_count_matches": (
                column_count_matches
            ),
            "column_order_matches": (
                column_order_matches
            ),
            "protected_partition_content": False,
            "status": "PASS",
        }
    )


V01_NOTEBOOK05_SAFE_REGISTRY_READ_AUDIT = pd.DataFrame(
    registry_read_records
)


# ------------------------------------------------------------
# Stable bindings required by later audit logic
# ------------------------------------------------------------

feature_registry = FULLY_READ_NOTEBOOK05_TARGETS[
    FEATURE_REGISTRY_LABEL
]

future_label_registry = FULLY_READ_NOTEBOOK05_TARGETS[
    FUTURE_LABEL_REGISTRY_LABEL
]

feature_target_schema = NOTEBOOK05_TARGET_SCHEMA_BY_LABEL[
    PRIMARY_FEATURE_TABLE_LABEL
]

label_target_schema = NOTEBOOK05_TARGET_SCHEMA_BY_LABEL[
    PRIMARY_LABEL_TABLE_LABEL
]

feature_availability_target_schema = (
    NOTEBOOK05_TARGET_SCHEMA_BY_LABEL[
        PRIMARY_FEATURE_AVAILABILITY_LABEL
    ]
)


# ------------------------------------------------------------
# Verify that primary analytical tables were not materialized
# ------------------------------------------------------------

PROHIBITED_FULL_READ_LABELS: Final[set[str]] = {
    PRIMARY_FEATURE_TABLE_LABEL,
    PRIMARY_LABEL_TABLE_LABEL,
    PRIMARY_FEATURE_AVAILABILITY_LABEL,
}

unexpected_full_reads = sorted(
    PROHIBITED_FULL_READ_LABELS
    & set(
        FULLY_READ_NOTEBOOK05_TARGETS
    )
)

if unexpected_full_reads:
    raise Notebook05TargetBindingError(
        "Primary analytical Notebook 05 tables were unexpectedly "
        "materialized during the registry-binding stage:\n"
        f"{unexpected_full_reads}"
    )


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

V01_NOTEBOOK05_TARGET_BINDING_SUMMARY = pd.DataFrame(
    [
        {
            "metric": "registered_contract_label_count",
            "value": int(
                len(
                    NOTEBOOK05_CONTRACT_ROW_BY_LABEL
                )
            ),
        },
        {
            "metric": "schema_metadata_target_count",
            "value": int(
                len(
                    NOTEBOOK05_TARGET_SCHEMA_BY_LABEL
                )
            ),
        },
        {
            "metric": "fully_read_registry_count",
            "value": int(
                len(
                    SAFE_FULL_READ_LABELS
                )
            ),
        },
        {
            "metric": "feature_registry_rows",
            "value": int(
                len(
                    feature_registry
                )
            ),
        },
        {
            "metric": "future_label_registry_rows",
            "value": int(
                len(
                    future_label_registry
                )
            ),
        },
        {
            "metric": "primary_feature_rows_metadata_only",
            "value": int(
                feature_target_schema[
                    "row_count"
                ]
            ),
        },
        {
            "metric": "primary_feature_columns_metadata_only",
            "value": int(
                feature_target_schema[
                    "column_count"
                ]
            ),
        },
        {
            "metric": "primary_label_rows_metadata_only",
            "value": int(
                label_target_schema[
                    "row_count"
                ]
            ),
        },
        {
            "metric": "primary_label_columns_metadata_only",
            "value": int(
                label_target_schema[
                    "column_count"
                ]
            ),
        },
        {
            "metric": "protected_partition_content_loaded",
            "value": False,
        },
    ]
)


display(
    V01_NOTEBOOK05_TARGET_BINDING_SUMMARY
)

display(
    V01_NOTEBOOK05_SAFE_REGISTRY_READ_AUDIT
)

display(
    V01_NOTEBOOK05_SCHEMA_METADATA_AUDIT[
        [
            "normalized_contract_label",
            "declared_row_count",
            "metadata_row_count",
            "row_count_matches",
            "declared_column_count",
            "metadata_column_count",
            "column_count_matches",
            "analytical_rows_loaded",
            "status",
        ]
    ]
)


# ------------------------------------------------------------
# Freeze authority
# ------------------------------------------------------------

FROZEN_NOTEBOOK05_TARGET_BINDING_AUTHORITY: Final[
    dict[str, Any]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "v0_1_run_id": V01_RUN_ID,
    "contract_label_count": int(
        len(
            NOTEBOOK05_CONTRACT_ROW_BY_LABEL
        )
    ),
    "fully_read_labels": sorted(
        SAFE_FULL_READ_LABELS
    ),
    "schema_only_labels": sorted(
        set(
            NOTEBOOK05_TARGET_SCHEMA_BY_LABEL
        )
        - SAFE_FULL_READ_LABELS
    ),
    "feature_registry_row_count": int(
        len(
            feature_registry
        )
    ),
    "future_label_registry_row_count": int(
        len(
            future_label_registry
        )
    ),
    "primary_feature_shape": {
        "rows": int(
            feature_target_schema[
                "row_count"
            ]
        ),
        "columns": int(
            feature_target_schema[
                "column_count"
            ]
        ),
    },
    "primary_label_shape": {
        "rows": int(
            label_target_schema[
                "row_count"
            ]
        ),
        "columns": int(
            label_target_schema[
                "column_count"
            ]
        ),
    },
    "protected_partition_content_loaded": False,
}


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

NOTEBOOK05_TARGET_BINDINGS_VERIFIED = True
NOTEBOOK05_REGISTRIES_FULLY_READ = True
NOTEBOOK05_PRIMARY_TABLE_SCHEMAS_VERIFIED = True

PROTECTED_PARTITION_CONTENT_LOADED = False
VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False

UPSTREAM_ARTIFACTS_VERIFIED = False

print(
    "Notebook 05 target binding: PASS. Canonical contract-label "
    "keys were rebuilt from the authoritative reconciliation "
    "table. The feature and future-label registries were read and "
    "verified successfully. Primary feature, availability, and "
    "future-label tables were inspected through Parquet metadata "
    "only; protected analytical content remains unopened. No "
    "filesystem writes were performed."
)

                                  metric  value
0        registered_contract_label_count     12
1           schema_metadata_target_count     12
2              fully_read_registry_count      2
3                  feature_registry_rows    571
4             future_label_registry_rows    140
5     primary_feature_rows_metadata_only  13564
6  primary_feature_columns_metadata_only    577
7       primary_label_rows_metadata_only  13564
8    primary_label_columns_metadata_only    146
9     protected_partition_content_loaded  False

,normalized_contract_label,target_path,row_count,column_count,row_count_matches,column_count_matches,column_order_matches,protected_partition_content,status
0,future_label_registry,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,140,15,True,True,True,False,PASS
1,market_state_feature_registry,d:\clown project\v0.1\artifacts\audit_tables\05_market_state_features\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_...,571,44,True,True,True,False,PASS

               normalized_contract_label  declared_row_count  metadata_row_count  row_count_matches  declared_column_count  metadata_column_count  column_count_matches  analytical_rows_loaded status
0       feature_missingness_policy_audit                 576                 576               True                     14                     14                  True                   False   PASS
1          future_label_horizon_contract                   4                   4               True                     12                     12                  True                   False   PASS
2         future_label_missingness_audit                 140                 140               True                      9                      9                  True                   False   PASS
3                  future_label_registry                 140                 140               True                     15                     15                  True                   False   PASS
4   future_label_source_resolution_audit                   4                   4               True                      4                      4                  True                   False   PASS
5          market_state_feature_registry                 571                 571               True                     44                     44                  True                   False   PASS
6     notebook_05_final_acceptance_gates                  13                  13               True                      4                      4                  True                   False   PASS
7   notebook_05_persisted_artifact_audit                   9                   9               True                     16                     16                  True                   False   PASS
8             notebook_05_readback_audit                   9                   9               True                      8                      8                  True                   False   PASS
9     primary_batch_feature_availability               13564               13564               True                      8                      8                  True                   False   PASS
10   primary_batch_market_state_features               13564               13564               True                    577                    577                  True                   False   PASS
11           primary_batch_future_labels               13564               13564               True                    146                    146                  True                   False   PASS

Notebook 05 target binding: PASS. Canonical contract-label keys were rebuilt from the authoritative reconciliation table. The feature and future-label registries were read and verified successfully. Primary feature, availability, and future-label tables were inspected through Parquet metadata only; protected analytical content remains unopened. No filesystem writes were performed.

In [15]:
# ============================================================
# Notebook 05 causal feature / future-label interface audit
#
# This cell verifies:
# - exact identity-column agreement;
# - registry-to-Parquet-schema coverage and order;
# - physical feature/label separation;
# - absence of future, label, and t-plus fields in features;
# - future-label naming and registry integrity;
# - causal timing and physical-table roles;
# - declared feature missingness and infinity controls;
# - feature non-imputation and non-attachment policies;
# - label availability-column references;
# - Notebook 05 manifest policies;
# - Notebook 05 downstream authorization boundaries.
#
# Only already-loaded registries and Parquet footer metadata are
# inspected. Primary analytical rows remain unopened.
#
# No filesystem writes are performed.
# ============================================================


class Notebook05InterfaceAuditError(RuntimeError):
    """Raised when the Notebook 05 persisted interface is unsafe."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

REQUIRED_NOTEBOOK05_PRECONDITIONS: Final[
    dict[str, bool]
] = {
    "V01_DATAFRAME_CONTRACT_GATE_PASSED": bool(
        globals().get(
            "V01_DATAFRAME_CONTRACT_GATE_PASSED",
            False,
        )
    ),
    "NOTEBOOK05_TARGET_BINDINGS_VERIFIED": bool(
        globals().get(
            "NOTEBOOK05_TARGET_BINDINGS_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK05_REGISTRIES_FULLY_READ": bool(
        globals().get(
            "NOTEBOOK05_REGISTRIES_FULLY_READ",
            False,
        )
    ),
    "NOTEBOOK05_PRIMARY_TABLE_SCHEMAS_VERIFIED": bool(
        globals().get(
            "NOTEBOOK05_PRIMARY_TABLE_SCHEMAS_VERIFIED",
            False,
        )
    ),
}

failed_preconditions = sorted(
    name
    for name, passed in (
        REQUIRED_NOTEBOOK05_PRECONDITIONS.items()
    )
    if not passed
)

if failed_preconditions:
    raise Notebook05InterfaceAuditError(
        "Notebook 05 interface-audit prerequisites have not "
        "passed:\n"
        f"{failed_preconditions}"
    )

if PROTECTED_PARTITION_CONTENT_LOADED:
    raise Notebook05InterfaceAuditError(
        "Protected partition content was unexpectedly loaded."
    )


# ------------------------------------------------------------
# Frozen interface identity
# ------------------------------------------------------------

NOTEBOOK05_IDENTITY_COLUMNS: Final[
    tuple[str, ...]
] = (
    "primary_event_batch_id",
    "primary_event_batch_number",
    "partition_batch_index",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
)

NOTEBOOK05_STRICT_IDENTITY_COLUMNS: Final[
    tuple[str, ...]
] = (
    "primary_event_batch_id",
    "primary_event_batch_number",
    "event_partition_order",
    "event_partition",
    "event_time_ns",
)

EXPECTED_FEATURE_TIMING_CLASS: Final[str] = "T_MINUS"

EXPECTED_FEATURE_PHYSICAL_ROLE: Final[str] = (
    "CAUSAL_MARKET_STATE_FEATURE"
)

EXPECTED_LABEL_TIMING_CLASS: Final[str] = (
    "FUTURE_LABEL"
)

EXPECTED_LABEL_PHYSICAL_ROLE: Final[str] = (
    "SEPARATE_FUTURE_LABEL"
)

EXPECTED_NOTEBOOK05_OBSERVATIONAL_UNIT: Final[str] = (
    "PRIMARY_SCORING_BATCH"
)

EXPECTED_NOTEBOOK05_PRIMARY_TIME_FIELD: Final[str] = (
    "event_time_ns"
)

EXPECTED_NOTEBOOK05_PARTITION_FIELD: Final[str] = (
    "event_partition"
)


# ------------------------------------------------------------
# Safe normalization helpers
# ------------------------------------------------------------

def normalize_interface_string(
    value: Any,
) -> str:
    """Normalize one interface string for strict comparison."""

    return str(
        value
    ).strip()


def normalize_interface_upper(
    value: Any,
) -> str:
    """Normalize one interface string to uppercase."""

    return normalize_interface_string(
        value
    ).upper()


def normalize_boolean_value(
    value: Any,
) -> bool | None:
    """Normalize common persisted boolean representations."""

    if value is None:
        return None

    try:
        if pd.isna(
            value
        ):
            return None
    except (
        TypeError,
        ValueError,
    ):
        pass

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(
            value
        )

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        if int(
            value
        ) in {
            0,
            1,
        }:
            return bool(
                int(
                    value
                )
            )

    normalized = str(
        value
    ).strip().casefold()

    if normalized in {
        "true",
        "t",
        "yes",
        "y",
        "1",
    }:
        return True

    if normalized in {
        "false",
        "f",
        "no",
        "n",
        "0",
    }:
        return False

    return None


def normalized_boolean_series(
    series: pd.Series,
) -> pd.Series:
    """Normalize a persisted boolean-like Series."""

    return series.map(
        normalize_boolean_value
    )


def numeric_series_without_coercion_failure(
    series: pd.Series,
) -> tuple[pd.Series, bool]:
    """Convert to numeric and report whether any value failed."""

    numeric = pd.to_numeric(
        series,
        errors="coerce",
    )

    original_non_null = series.notna()
    coercion_failure = bool(
        (
            original_non_null
            & numeric.isna()
        ).any()
    )

    return (
        numeric,
        coercion_failure,
    )


def is_pass_like_status(
    value: Any,
) -> bool:
    """Return whether one terminal status is pass-like."""

    normalized = normalize_interface_upper(
        value
    )

    return bool(
        normalized.startswith(
            "PASS"
        )
        or normalized.startswith(
            "CONDITIONAL PASS"
        )
    )


# ------------------------------------------------------------
# Audit-record machinery
# ------------------------------------------------------------

notebook05_interface_checks: list[
    dict[str, Any]
] = []


def render_interface_value(
    value: Any,
) -> str:
    """Render deterministic compact values in the audit table."""

    if isinstance(
        value,
        Path,
    ):
        return str(
            value
        )

    if isinstance(
        value,
        set,
    ):
        return repr(
            sorted(
                value
            )
        )

    if isinstance(
        value,
        tuple,
    ):
        return repr(
            list(
                value
            )
        )

    if isinstance(
        value,
        list,
    ):
        return repr(
            value
        )

    if isinstance(
        value,
        dict,
    ):
        return json.dumps(
            value,
            sort_keys=True,
            ensure_ascii=False,
            allow_nan=False,
            default=str,
        )

    return repr(
        value
    )


def register_interface_check(
    *,
    category: str,
    check_name: str,
    observed: Any,
    expected: Any,
    passed: bool | None = None,
    blocking: bool = True,
    detail: str | None = None,
) -> None:
    """Register one Notebook 05 interface check."""

    check_passed = (
        observed == expected
        if passed is None
        else bool(
            passed
        )
    )

    notebook05_interface_checks.append(
        {
            "check_order": int(
                len(
                    notebook05_interface_checks
                )
                + 1
            ),
            "category": category,
            "check_name": check_name,
            "blocking": bool(
                blocking
            ),
            "passed": bool(
                check_passed
            ),
            "status": (
                "PASS"
                if check_passed
                else (
                    "FAIL"
                    if blocking
                    else "WARNING"
                )
            ),
            "observed": render_interface_value(
                observed
            ),
            "expected": render_interface_value(
                expected
            ),
            "detail": detail,
        }
    )


# ------------------------------------------------------------
# Immutable local copies
# ------------------------------------------------------------

feature_registry_audit = feature_registry.copy(
    deep=True
)

future_label_registry_audit = (
    future_label_registry.copy(
        deep=True
    )
)

feature_schema_columns = list(
    map(
        str,
        feature_target_schema[
            "column_names"
        ],
    )
)

label_schema_columns = list(
    map(
        str,
        label_target_schema[
            "column_names"
        ],
    )
)

feature_identity_columns = [
    column
    for column in feature_schema_columns
    if column in NOTEBOOK05_IDENTITY_COLUMNS
]

label_identity_columns = [
    column
    for column in label_schema_columns
    if column in NOTEBOOK05_IDENTITY_COLUMNS
]

feature_value_columns = [
    column
    for column in feature_schema_columns
    if column not in NOTEBOOK05_IDENTITY_COLUMNS
]

label_value_columns = [
    column
    for column in label_schema_columns
    if column not in NOTEBOOK05_IDENTITY_COLUMNS
]


# ------------------------------------------------------------
# Core schema and row-count checks
# ------------------------------------------------------------

register_interface_check(
    category="SHAPE",
    check_name="feature_table_row_count",
    observed=int(
        feature_target_schema[
            "row_count"
        ]
    ),
    expected=13_564,
)

register_interface_check(
    category="SHAPE",
    check_name="label_table_row_count",
    observed=int(
        label_target_schema[
            "row_count"
        ]
    ),
    expected=13_564,
)

register_interface_check(
    category="SHAPE",
    check_name="feature_registry_row_count_matches_feature_columns",
    observed=int(
        len(
            feature_registry_audit
        )
    ),
    expected=int(
        len(
            feature_value_columns
        )
    ),
)

register_interface_check(
    category="SHAPE",
    check_name="label_registry_row_count_matches_label_columns",
    observed=int(
        len(
            future_label_registry_audit
        )
    ),
    expected=int(
        len(
            label_value_columns
        )
    ),
)

register_interface_check(
    category="IDENTITY",
    check_name="feature_identity_column_order",
    observed=feature_identity_columns,
    expected=list(
        NOTEBOOK05_IDENTITY_COLUMNS
    ),
)

register_interface_check(
    category="IDENTITY",
    check_name="label_identity_column_order",
    observed=label_identity_columns,
    expected=list(
        NOTEBOOK05_IDENTITY_COLUMNS
    ),
)

register_interface_check(
    category="IDENTITY",
    check_name="feature_and_label_identity_interfaces_match",
    observed=feature_identity_columns,
    expected=label_identity_columns,
)


# ------------------------------------------------------------
# Registry schemas
# ------------------------------------------------------------

REQUIRED_FEATURE_REGISTRY_COLUMNS: Final[
    set[str]
] = {
    "feature_name",
    "feature_order",
    "timing_class",
    "physical_table_role",
    "observed_missing_count",
    "allowed_missing_count",
    "unexpected_missing_count",
    "infinite_count",
    "nullable_flag",
    "imputation_applied",
    "future_label_attached",
    "post_batch_context_attached",
}

REQUIRED_LABEL_REGISTRY_COLUMNS: Final[
    set[str]
] = {
    "label_name",
    "label_order",
    "timing_class",
    "physical_table_role",
}

observed_feature_registry_columns = set(
    map(
        str,
        feature_registry_audit.columns,
    )
)

observed_label_registry_columns = set(
    map(
        str,
        future_label_registry_audit.columns,
    )
)

missing_feature_registry_columns = sorted(
    REQUIRED_FEATURE_REGISTRY_COLUMNS
    - observed_feature_registry_columns
)

missing_label_registry_columns = sorted(
    REQUIRED_LABEL_REGISTRY_COLUMNS
    - observed_label_registry_columns
)

register_interface_check(
    category="REGISTRY_SCHEMA",
    check_name="required_feature_registry_columns_present",
    observed=missing_feature_registry_columns,
    expected=[],
)

register_interface_check(
    category="REGISTRY_SCHEMA",
    check_name="required_label_registry_columns_present",
    observed=missing_label_registry_columns,
    expected=[],
)


# ------------------------------------------------------------
# Feature registry semantic checks
# ------------------------------------------------------------

if not missing_feature_registry_columns:
    persisted_feature_names = (
        feature_registry_audit[
            "feature_name"
        ]
        .astype(
            "string"
        )
        .str.strip()
        .tolist()
    )

    persisted_feature_orders, feature_order_coercion_failed = (
        numeric_series_without_coercion_failure(
            feature_registry_audit[
                "feature_order"
            ]
        )
    )

    expected_feature_orders = list(
        range(
            1,
            len(
                feature_registry_audit
            )
            + 1,
        )
    )

    forbidden_feature_names = sorted(
        feature_name
        for feature_name in persisted_feature_names
        if (
            feature_name.startswith(
                "label_"
            )
            or feature_name.startswith(
                "tplus_"
            )
            or "future_" in feature_name.casefold()
        )
    )

    blank_feature_names = int(
        pd.Series(
            persisted_feature_names,
            dtype="string",
        )
        .fillna(
            ""
        )
        .str.strip()
        .eq(
            ""
        )
        .sum()
    )

    register_interface_check(
        category="FEATURE_REGISTRY",
        check_name="feature_names_nonblank",
        observed=blank_feature_names,
        expected=0,
    )

    register_interface_check(
        category="FEATURE_REGISTRY",
        check_name="feature_names_unique",
        observed=bool(
            feature_registry_audit[
                "feature_name"
            ].is_unique
        ),
        expected=True,
    )

    register_interface_check(
        category="FEATURE_REGISTRY",
        check_name="feature_registry_order_matches_parquet_schema",
        observed=persisted_feature_names,
        expected=feature_value_columns,
    )

    register_interface_check(
        category="FEATURE_REGISTRY",
        check_name="feature_order_numeric_coercion_succeeded",
        observed=feature_order_coercion_failed,
        expected=False,
    )

    register_interface_check(
        category="FEATURE_REGISTRY",
        check_name="feature_order_is_contiguous_one_based",
        observed=(
            persisted_feature_orders.astype(
                "Int64"
            ).tolist()
            if not feature_order_coercion_failed
            else "<COERCION_FAILED>"
        ),
        expected=expected_feature_orders,
    )

    register_interface_check(
        category="FEATURE_REGISTRY",
        check_name="feature_names_contain_no_future_label_or_tplus_fields",
        observed=forbidden_feature_names,
        expected=[],
    )

    feature_timing_values = sorted(
        set(
            feature_registry_audit[
                "timing_class"
            ]
            .astype(
                "string"
            )
            .str.strip()
            .str.upper()
            .dropna()
            .tolist()
        )
    )

    feature_role_values = sorted(
        set(
            feature_registry_audit[
                "physical_table_role"
            ]
            .astype(
                "string"
            )
            .str.strip()
            .str.upper()
            .dropna()
            .tolist()
        )
    )

    register_interface_check(
        category="CAUSAL_POLICY",
        check_name="all_features_are_t_minus",
        observed=feature_timing_values,
        expected=[
            EXPECTED_FEATURE_TIMING_CLASS,
        ],
    )

    register_interface_check(
        category="CAUSAL_POLICY",
        check_name="all_features_have_causal_physical_role",
        observed=feature_role_values,
        expected=[
            EXPECTED_FEATURE_PHYSICAL_ROLE,
        ],
    )

    for flag_column in (
        "imputation_applied",
        "future_label_attached",
        "post_batch_context_attached",
    ):
        normalized_flags = normalized_boolean_series(
            feature_registry_audit[
                flag_column
            ]
        )

        unknown_flag_count = int(
            normalized_flags.isna().sum()
        )

        true_flag_count = int(
            normalized_flags.eq(
                True
            ).sum()
        )

        register_interface_check(
            category="CAUSAL_POLICY",
            check_name=f"{flag_column}::all_values_parse",
            observed=unknown_flag_count,
            expected=0,
        )

        register_interface_check(
            category="CAUSAL_POLICY",
            check_name=f"{flag_column}::true_count",
            observed=true_flag_count,
            expected=0,
        )

    feature_numeric_policy_columns = (
        "observed_missing_count",
        "allowed_missing_count",
        "unexpected_missing_count",
        "infinite_count",
    )

    normalized_feature_policy_counts: dict[
        str,
        pd.Series,
    ] = {}

    for count_column in (
        feature_numeric_policy_columns
    ):
        (
            normalized_counts,
            coercion_failed,
        ) = numeric_series_without_coercion_failure(
            feature_registry_audit[
                count_column
            ]
        )

        normalized_feature_policy_counts[
            count_column
        ] = normalized_counts

        register_interface_check(
            category="FEATURE_QUALITY",
            check_name=f"{count_column}::numeric_coercion_succeeded",
            observed=coercion_failed,
            expected=False,
        )

        register_interface_check(
            category="FEATURE_QUALITY",
            check_name=f"{count_column}::negative_value_count",
            observed=int(
                normalized_counts.lt(
                    0
                ).sum()
            ),
            expected=0,
        )

    observed_missing_counts = (
        normalized_feature_policy_counts[
            "observed_missing_count"
        ]
    )

    allowed_missing_counts = (
        normalized_feature_policy_counts[
            "allowed_missing_count"
        ]
    )

    unexpected_missing_counts = (
        normalized_feature_policy_counts[
            "unexpected_missing_count"
        ]
    )

    infinite_counts = (
        normalized_feature_policy_counts[
            "infinite_count"
        ]
    )

    register_interface_check(
        category="FEATURE_QUALITY",
        check_name="unexpected_missing_total",
        observed=int(
            unexpected_missing_counts.sum()
        ),
        expected=0,
    )

    register_interface_check(
        category="FEATURE_QUALITY",
        check_name="infinite_value_total",
        observed=int(
            infinite_counts.sum()
        ),
        expected=0,
    )

    register_interface_check(
        category="FEATURE_QUALITY",
        check_name="observed_missing_does_not_exceed_allowed_missing",
        observed=int(
            (
                observed_missing_counts
                > allowed_missing_counts
            ).sum()
        ),
        expected=0,
    )

    normalized_nullable_flags = (
        normalized_boolean_series(
            feature_registry_audit[
                "nullable_flag"
            ]
        )
    )

    expected_nullable_flags = (
        observed_missing_counts.gt(
            0
        )
    )

    nullable_flag_unknown_count = int(
        normalized_nullable_flags.isna().sum()
    )

    nullable_flag_mismatch_count = int(
        (
            normalized_nullable_flags.notna()
            & normalized_nullable_flags.ne(
                expected_nullable_flags
            )
        ).sum()
    )

    register_interface_check(
        category="FEATURE_QUALITY",
        check_name="nullable_flag_values_parse",
        observed=nullable_flag_unknown_count,
        expected=0,
    )

    register_interface_check(
        category="FEATURE_QUALITY",
        check_name="nullable_flag_matches_observed_missingness",
        observed=nullable_flag_mismatch_count,
        expected=0,
    )


# ------------------------------------------------------------
# Future-label registry semantic checks
# ------------------------------------------------------------

if not missing_label_registry_columns:
    persisted_label_names = (
        future_label_registry_audit[
            "label_name"
        ]
        .astype(
            "string"
        )
        .str.strip()
        .tolist()
    )

    persisted_label_orders, label_order_coercion_failed = (
        numeric_series_without_coercion_failure(
            future_label_registry_audit[
                "label_order"
            ]
        )
    )

    expected_label_orders = list(
        range(
            1,
            len(
                future_label_registry_audit
            )
            + 1,
        )
    )

    blank_label_names = int(
        pd.Series(
            persisted_label_names,
            dtype="string",
        )
        .fillna(
            ""
        )
        .str.strip()
        .eq(
            ""
        )
        .sum()
    )

    non_prefixed_label_names = sorted(
        label_name
        for label_name in persisted_label_names
        if not label_name.startswith(
            "label_"
        )
    )

    register_interface_check(
        category="LABEL_REGISTRY",
        check_name="label_names_nonblank",
        observed=blank_label_names,
        expected=0,
    )

    register_interface_check(
        category="LABEL_REGISTRY",
        check_name="label_names_unique",
        observed=bool(
            future_label_registry_audit[
                "label_name"
            ].is_unique
        ),
        expected=True,
    )

    register_interface_check(
        category="LABEL_REGISTRY",
        check_name="label_registry_order_matches_parquet_schema",
        observed=persisted_label_names,
        expected=label_value_columns,
    )

    register_interface_check(
        category="LABEL_REGISTRY",
        check_name="label_order_numeric_coercion_succeeded",
        observed=label_order_coercion_failed,
        expected=False,
    )

    register_interface_check(
        category="LABEL_REGISTRY",
        check_name="label_order_is_contiguous_one_based",
        observed=(
            persisted_label_orders.astype(
                "Int64"
            ).tolist()
            if not label_order_coercion_failed
            else "<COERCION_FAILED>"
        ),
        expected=expected_label_orders,
    )

    register_interface_check(
        category="LABEL_REGISTRY",
        check_name="all_nonidentity_label_fields_use_label_prefix",
        observed=non_prefixed_label_names,
        expected=[],
    )

    label_timing_values = sorted(
        set(
            future_label_registry_audit[
                "timing_class"
            ]
            .astype(
                "string"
            )
            .str.strip()
            .str.upper()
            .dropna()
            .tolist()
        )
    )

    label_role_values = sorted(
        set(
            future_label_registry_audit[
                "physical_table_role"
            ]
            .astype(
                "string"
            )
            .str.strip()
            .str.upper()
            .dropna()
            .tolist()
        )
    )

    register_interface_check(
        category="LABEL_POLICY",
        check_name="all_labels_are_future_labels",
        observed=label_timing_values,
        expected=[
            EXPECTED_LABEL_TIMING_CLASS,
        ],
    )

    register_interface_check(
        category="LABEL_POLICY",
        check_name="all_labels_have_separate_future_label_role",
        observed=label_role_values,
        expected=[
            EXPECTED_LABEL_PHYSICAL_ROLE,
        ],
    )

    if (
        "availability_flag_column"
        in future_label_registry_audit.columns
    ):
        declared_availability_columns = sorted(
            {
                normalize_interface_string(
                    value
                )
                for value in (
                    future_label_registry_audit[
                        "availability_flag_column"
                    ]
                )
                if (
                    normalize_boolean_value(
                        value
                    )
                    is None
                    and not pd.isna(
                        value
                    )
                    and normalize_interface_string(
                        value
                    )
                )
            }
        )

        invalid_availability_references = sorted(
            set(
                declared_availability_columns
            )
            - set(
                label_value_columns
            )
        )

        register_interface_check(
            category="LABEL_POLICY",
            check_name="availability_flag_columns_reference_label_table",
            observed=invalid_availability_references,
            expected=[],
        )

    for optional_false_policy_column in (
        "current_batch_included",
        "cross_partition_labels_allowed",
    ):
        if (
            optional_false_policy_column
            not in future_label_registry_audit.columns
        ):
            register_interface_check(
                category="LABEL_POLICY",
                check_name=(
                    f"{optional_false_policy_column}"
                    "::registry_column_present"
                ),
                observed=False,
                expected=True,
                passed=False,
                blocking=False,
                detail=(
                    "The policy may instead be recorded in the "
                    "Notebook 05 output manifest."
                ),
            )

            continue

        normalized_policy_flags = normalized_boolean_series(
            future_label_registry_audit[
                optional_false_policy_column
            ]
        )

        register_interface_check(
            category="LABEL_POLICY",
            check_name=(
                f"{optional_false_policy_column}"
                "::unknown_value_count"
            ),
            observed=int(
                normalized_policy_flags.isna().sum()
            ),
            expected=0,
        )

        register_interface_check(
            category="LABEL_POLICY",
            check_name=(
                f"{optional_false_policy_column}"
                "::true_count"
            ),
            observed=int(
                normalized_policy_flags.eq(
                    True
                ).sum()
            ),
            expected=0,
        )


# ------------------------------------------------------------
# Physical and column separation
# ------------------------------------------------------------

shared_schema_columns = [
    column
    for column in feature_schema_columns
    if column in set(
        label_schema_columns
    )
]

unexpected_shared_columns = sorted(
    set(
        shared_schema_columns
    )
    - set(
        NOTEBOOK05_IDENTITY_COLUMNS
    )
)

feature_label_name_overlap = sorted(
    set(
        feature_value_columns
    )
    & set(
        label_value_columns
    )
)

feature_target_path = (
    NOTEBOOK05_TARGET_PATH_BY_LABEL[
        PRIMARY_FEATURE_TABLE_LABEL
    ]
)

label_target_path = (
    NOTEBOOK05_TARGET_PATH_BY_LABEL[
        PRIMARY_LABEL_TABLE_LABEL
    ]
)

expected_feature_root = normalized_resolved_path(
    V01_PROCESSED_ROOT
    / "features"
)

expected_label_root = normalized_resolved_path(
    V01_PROCESSED_ROOT
    / "labels"
)

register_interface_check(
    category="PHYSICAL_SEPARATION",
    check_name="only_identity_columns_are_shared",
    observed=unexpected_shared_columns,
    expected=[],
)

register_interface_check(
    category="PHYSICAL_SEPARATION",
    check_name="feature_and_label_value_names_do_not_overlap",
    observed=feature_label_name_overlap,
    expected=[],
)

register_interface_check(
    category="PHYSICAL_SEPARATION",
    check_name="feature_and_label_target_paths_are_distinct",
    observed=normalized_resolved_path(
        feature_target_path
    ),
    expected=normalized_resolved_path(
        label_target_path
    ),
    passed=(
        normalized_resolved_path(
            feature_target_path
        )
        != normalized_resolved_path(
            label_target_path
        )
    ),
)

register_interface_check(
    category="PHYSICAL_SEPARATION",
    check_name="feature_target_is_under_processed_features",
    observed=normalized_resolved_path(
        feature_target_path
    ),
    expected=expected_feature_root,
    passed=normalized_resolved_path(
        feature_target_path
    ).is_relative_to(
        expected_feature_root
    ),
)

register_interface_check(
    category="PHYSICAL_SEPARATION",
    check_name="label_target_is_under_processed_labels",
    observed=normalized_resolved_path(
        label_target_path
    ),
    expected=expected_label_root,
    passed=normalized_resolved_path(
        label_target_path
    ).is_relative_to(
        expected_label_root
    ),
)

register_interface_check(
    category="PHYSICAL_SEPARATION",
    check_name="feature_target_is_v0_1_authority",
    observed=normalized_resolved_path(
        feature_target_path
    ),
    expected=normalized_resolved_path(
        V01_ROOT
    ),
    passed=normalized_resolved_path(
        feature_target_path
    ).is_relative_to(
        normalized_resolved_path(
            V01_ROOT
        )
    ),
)

register_interface_check(
    category="PHYSICAL_SEPARATION",
    check_name="label_target_is_v0_1_authority",
    observed=normalized_resolved_path(
        label_target_path
    ),
    expected=normalized_resolved_path(
        V01_ROOT
    ),
    passed=normalized_resolved_path(
        label_target_path
    ).is_relative_to(
        normalized_resolved_path(
            V01_ROOT
        )
    ),
)


# ------------------------------------------------------------
# Confirm no primary analytical table was fully loaded
# ------------------------------------------------------------

observed_fully_read_labels = set(
    FULLY_READ_NOTEBOOK05_TARGETS
)

unexpected_fully_read_labels = sorted(
    observed_fully_read_labels
    - {
        FEATURE_REGISTRY_LABEL,
        FUTURE_LABEL_REGISTRY_LABEL,
    }
)

register_interface_check(
    category="PROTECTED_DATA",
    check_name="only_safe_registry_tables_are_fully_read",
    observed=unexpected_fully_read_labels,
    expected=[],
)

register_interface_check(
    category="PROTECTED_DATA",
    check_name="protected_partition_content_loaded",
    observed=PROTECTED_PARTITION_CONTENT_LOADED,
    expected=False,
)

register_interface_check(
    category="PROTECTED_DATA",
    check_name="validation_content_loaded",
    observed=VALIDATION_CONTENT_LOADED,
    expected=False,
)

register_interface_check(
    category="PROTECTED_DATA",
    check_name="engineering_holdout_content_loaded",
    observed=ENGINEERING_HOLDOUT_CONTENT_LOADED,
    expected=False,
)


# ------------------------------------------------------------
# Notebook 05 output-manifest policy
# ------------------------------------------------------------

notebook05_output_manifest = stage_control_payloads.get(
    "NOTEBOOK05_OUTPUT_MANIFEST",
    {},
)

notebook05_handoff = stage_control_payloads.get(
    "NOTEBOOK05_TO_NOTEBOOK06_HANDOFF",
    {},
)

register_interface_check(
    category="MANIFEST_POLICY",
    check_name="output_manifest_is_available",
    observed=isinstance(
        notebook05_output_manifest,
        dict,
    )
    and bool(
        notebook05_output_manifest
    ),
    expected=True,
)

register_interface_check(
    category="HANDOFF_POLICY",
    check_name="notebook05_handoff_is_available",
    observed=isinstance(
        notebook05_handoff,
        dict,
    )
    and bool(
        notebook05_handoff
    ),
    expected=True,
)


feature_table_policy = (
    notebook05_output_manifest.get(
        "feature_table_policy",
        {},
    )
    if isinstance(
        notebook05_output_manifest,
        dict,
    )
    else {}
)

future_label_policy = (
    notebook05_output_manifest.get(
        "future_label_policy",
        {},
    )
    if isinstance(
        notebook05_output_manifest,
        dict,
    )
    else {}
)

register_interface_check(
    category="MANIFEST_POLICY",
    check_name="feature_table_policy_is_declared",
    observed=isinstance(
        feature_table_policy,
        dict,
    )
    and bool(
        feature_table_policy
    ),
    expected=True,
)

register_interface_check(
    category="MANIFEST_POLICY",
    check_name="future_label_policy_is_declared",
    observed=isinstance(
        future_label_policy,
        dict,
    )
    and bool(
        future_label_policy
    ),
    expected=True,
)


if isinstance(
    feature_table_policy,
    dict,
) and feature_table_policy:
    EXPECTED_FEATURE_TABLE_POLICY: Final[
        dict[str, Any]
    ] = {
        "timing_class": (
            EXPECTED_FEATURE_TIMING_CLASS
        ),
        "physical_table_role": (
            EXPECTED_FEATURE_PHYSICAL_ROLE
        ),
        "future_labels_attached": False,
        "tplus_context_attached": False,
        "imputation_applied": False,
        "causally_explained_missingness_preserved": True,
    }

    for policy_key, expected_value in (
        EXPECTED_FEATURE_TABLE_POLICY.items()
    ):
        observed_value = feature_table_policy.get(
            policy_key,
            None,
        )

        if isinstance(
            expected_value,
            bool,
        ):
            observed_value = normalize_boolean_value(
                observed_value
            )

        register_interface_check(
            category="MANIFEST_POLICY",
            check_name=(
                f"feature_table_policy::{policy_key}"
            ),
            observed=observed_value,
            expected=expected_value,
        )


if isinstance(
    future_label_policy,
    dict,
) and future_label_policy:
    EXPECTED_FUTURE_LABEL_POLICY: Final[
        dict[str, Any]
    ] = {
        "timing_class": (
            EXPECTED_LABEL_TIMING_CLASS
        ),
        "physical_table_role": (
            EXPECTED_LABEL_PHYSICAL_ROLE
        ),
        "current_batch_included": False,
        "cross_partition_labels_allowed": False,
        "overlapping_forward_windows_acknowledged": True,
    }

    for policy_key, expected_value in (
        EXPECTED_FUTURE_LABEL_POLICY.items()
    ):
        observed_value = future_label_policy.get(
            policy_key,
            None,
        )

        if isinstance(
            expected_value,
            bool,
        ):
            observed_value = normalize_boolean_value(
                observed_value
            )

        register_interface_check(
            category="MANIFEST_POLICY",
            check_name=(
                f"future_label_policy::{policy_key}"
            ),
            observed=observed_value,
            expected=expected_value,
        )


# ------------------------------------------------------------
# Notebook 05 downstream authorization boundary
# ------------------------------------------------------------

EXPECTED_NOTEBOOK05_HANDOFF_VALUES: Final[
    dict[str, Any]
] = {
    "point_process_baselines_authorized": True,
    "hawkes_estimation_authorized": False,
    "market_making_authorized": False,
    "quote_policy_authorized": False,
    "fill_simulation_authorized": False,
    "pnl_backtest_authorized": False,
    "observational_unit": (
        EXPECTED_NOTEBOOK05_OBSERVATIONAL_UNIT
    ),
    "event_partition_field": (
        EXPECTED_NOTEBOOK05_PARTITION_FIELD
    ),
    "primary_time_field": (
        EXPECTED_NOTEBOOK05_PRIMARY_TIME_FIELD
    ),
}

if isinstance(
    notebook05_handoff,
    dict,
) and notebook05_handoff:
    for handoff_key, expected_value in (
        EXPECTED_NOTEBOOK05_HANDOFF_VALUES.items()
    ):
        observed_value = notebook05_handoff.get(
            handoff_key,
            None,
        )

        if isinstance(
            expected_value,
            bool,
        ):
            observed_value = normalize_boolean_value(
                observed_value
            )

        register_interface_check(
            category="HANDOFF_POLICY",
            check_name=f"handoff::{handoff_key}",
            observed=observed_value,
            expected=expected_value,
        )

    registered_handoff_identity_columns = (
        notebook05_handoff.get(
            "identity_columns",
            None,
        )
    )

    register_interface_check(
        category="HANDOFF_POLICY",
        check_name="handoff_identity_columns",
        observed=registered_handoff_identity_columns,
        expected=list(
            NOTEBOOK05_IDENTITY_COLUMNS
        ),
    )

    handoff_acceptance_status = (
        notebook05_handoff.get(
            "acceptance_status",
            None,
        )
    )

    register_interface_check(
        category="HANDOFF_POLICY",
        check_name="handoff_acceptance_status_is_pass_like",
        observed=handoff_acceptance_status,
        expected="PASS-LIKE STATUS",
        passed=is_pass_like_status(
            handoff_acceptance_status
        ),
    )


# ------------------------------------------------------------
# Build audit tables
# ------------------------------------------------------------

V01_NOTEBOOK05_INTERFACE_AUDIT = (
    pd.DataFrame(
        notebook05_interface_checks
    )
    .sort_values(
        "check_order",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)

V01_NOTEBOOK05_INTERFACE_FAILURES = (
    V01_NOTEBOOK05_INTERFACE_AUDIT.loc[
        V01_NOTEBOOK05_INTERFACE_AUDIT[
            "blocking"
        ]
        & ~V01_NOTEBOOK05_INTERFACE_AUDIT[
            "passed"
        ]
    ]
    .copy()
)

V01_NOTEBOOK05_INTERFACE_WARNINGS = (
    V01_NOTEBOOK05_INTERFACE_AUDIT.loc[
        ~V01_NOTEBOOK05_INTERFACE_AUDIT[
            "blocking"
        ]
        & ~V01_NOTEBOOK05_INTERFACE_AUDIT[
            "passed"
        ]
    ]
    .copy()
)


V01_NOTEBOOK05_INTERFACE_SUMMARY = pd.DataFrame(
    [
        {
            "metric": "interface_check_count",
            "value": int(
                len(
                    V01_NOTEBOOK05_INTERFACE_AUDIT
                )
            ),
        },
        {
            "metric": "blocking_failure_count",
            "value": int(
                len(
                    V01_NOTEBOOK05_INTERFACE_FAILURES
                )
            ),
        },
        {
            "metric": "nonblocking_warning_count",
            "value": int(
                len(
                    V01_NOTEBOOK05_INTERFACE_WARNINGS
                )
            ),
        },
        {
            "metric": "identity_column_count",
            "value": int(
                len(
                    NOTEBOOK05_IDENTITY_COLUMNS
                )
            ),
        },
        {
            "metric": "causal_feature_count",
            "value": int(
                len(
                    feature_value_columns
                )
            ),
        },
        {
            "metric": "future_label_count",
            "value": int(
                len(
                    label_value_columns
                )
            ),
        },
        {
            "metric": "shared_nonidentity_column_count",
            "value": int(
                len(
                    unexpected_shared_columns
                )
            ),
        },
        {
            "metric": "fully_read_primary_analytical_table_count",
            "value": int(
                len(
                    unexpected_fully_read_labels
                )
            ),
        },
        {
            "metric": "protected_partition_content_loaded",
            "value": bool(
                PROTECTED_PARTITION_CONTENT_LOADED
            ),
        },
    ]
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    V01_NOTEBOOK05_INTERFACE_SUMMARY
)

display(
    V01_NOTEBOOK05_INTERFACE_AUDIT[
        [
            "check_order",
            "category",
            "check_name",
            "blocking",
            "passed",
            "status",
            "observed",
            "expected",
            "detail",
        ]
    ]
)

if not V01_NOTEBOOK05_INTERFACE_WARNINGS.empty:
    print(
        "Notebook 05 non-blocking interface warnings:"
    )

    display(
        V01_NOTEBOOK05_INTERFACE_WARNINGS
    )

if not V01_NOTEBOOK05_INTERFACE_FAILURES.empty:
    print(
        "Notebook 05 blocking interface failures:"
    )

    display(
        V01_NOTEBOOK05_INTERFACE_FAILURES
    )


# ------------------------------------------------------------
# Blocking gate
# ------------------------------------------------------------

if not V01_NOTEBOOK05_INTERFACE_FAILURES.empty:
    rendered_failures = "\n\n".join(
        (
            f"- [{row.category}] {row.check_name}\n"
            f"  observed={row.observed}\n"
            f"  expected={row.expected}"
        )
        for row in (
            V01_NOTEBOOK05_INTERFACE_FAILURES.itertuples(
                index=False
            )
        )
    )

    raise Notebook05InterfaceAuditError(
        "Notebook 05 causal feature / future-label interface "
        "verification failed:\n\n"
        f"{rendered_failures}"
    )


# ------------------------------------------------------------
# Freeze verified Notebook 05 interface authority
# ------------------------------------------------------------

FROZEN_NOTEBOOK05_INTERFACE_AUTHORITY: Final[
    dict[str, Any]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "observational_unit": (
        EXPECTED_NOTEBOOK05_OBSERVATIONAL_UNIT
    ),
    "identity_columns": list(
        NOTEBOOK05_IDENTITY_COLUMNS
    ),
    "strict_identity_columns": list(
        NOTEBOOK05_STRICT_IDENTITY_COLUMNS
    ),
    "feature_table": {
        "path": str(
            feature_target_path
        ),
        "row_count": int(
            feature_target_schema[
                "row_count"
            ]
        ),
        "column_count": int(
            feature_target_schema[
                "column_count"
            ]
        ),
        "feature_count": int(
            len(
                feature_value_columns
            )
        ),
        "timing_class": (
            EXPECTED_FEATURE_TIMING_CLASS
        ),
        "physical_table_role": (
            EXPECTED_FEATURE_PHYSICAL_ROLE
        ),
        "future_labels_attached": False,
        "post_batch_context_attached": False,
        "imputation_applied": False,
    },
    "future_label_table": {
        "path": str(
            label_target_path
        ),
        "row_count": int(
            label_target_schema[
                "row_count"
            ]
        ),
        "column_count": int(
            label_target_schema[
                "column_count"
            ]
        ),
        "label_count": int(
            len(
                label_value_columns
            )
        ),
        "timing_class": (
            EXPECTED_LABEL_TIMING_CLASS
        ),
        "physical_table_role": (
            EXPECTED_LABEL_PHYSICAL_ROLE
        ),
        "current_batch_included": False,
        "cross_partition_labels_allowed": False,
    },
    "feature_names": list(
        feature_value_columns
    ),
    "label_names": list(
        label_value_columns
    ),
    "shared_nonidentity_columns": list(
        unexpected_shared_columns
    ),
    "point_process_baselines_authorized": True,
    "hawkes_estimation_authorized": False,
    "market_making_authorized": False,
    "quote_policy_authorized": False,
    "fill_simulation_authorized": False,
    "pnl_backtest_authorized": False,
    "protected_partition_content_loaded": False,
    "blocking_failure_count": 0,
    "nonblocking_warning_count": int(
        len(
            V01_NOTEBOOK05_INTERFACE_WARNINGS
        )
    ),
}


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

NOTEBOOK05_INTERFACE_SEMANTICS_VERIFIED = True
NOTEBOOK05_FEATURE_LABEL_SEPARATION_VERIFIED = True
NOTEBOOK05_CAUSAL_FEATURE_POLICY_VERIFIED = True
NOTEBOOK05_DOWNSTREAM_AUTHORIZATION_VERIFIED = True

UPSTREAM_ARTIFACTS_VERIFIED = False

PROTECTED_PARTITION_CONTENT_LOADED = False
VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "Notebook 05 causal feature / future-label interface: PASS. "
    f"{len(feature_value_columns)} causal T-minus features and "
    f"{len(label_value_columns)} physically separate future-label "
    "fields reconcile exactly with their persisted registries and "
    "Parquet schemas. No future-label or t-plus field enters the "
    "feature interface, no undeclared feature missingness or "
    "infinite-value condition survives, and no feature imputation "
    "or label attachment was authorized. Notebook 05 authorized "
    "only the point-process baseline stage; Hawkes estimation, "
    "quoting, fill simulation, market making, and P&L evaluation "
    "remained unauthorized. Protected analytical content remains "
    "unopened. No filesystem writes were performed."
)

                                      metric  value
0                      interface_check_count     85
1                     blocking_failure_count      0
2                  nonblocking_warning_count      1
3                      identity_column_count      6
4                       causal_feature_count    571
5                         future_label_count    140
6            shared_nonidentity_column_count      0
7  fully_read_primary_analytical_table_count      0
8         protected_partition_content_loaded  False

,check_order,category,check_name,blocking,passed,status,observed,expected,detail
0,1,SHAPE,feature_table_row_count,True,True,PASS,13564,13564,None
1,2,SHAPE,label_table_row_count,True,True,PASS,13564,13564,None
2,3,SHAPE,feature_registry_row_count_matches_feature_columns,True,True,PASS,571,571,None
3,4,SHAPE,label_registry_row_count_matches_label_columns,True,True,PASS,140,140,None
4,5,IDENTITY,feature_identity_column_order,True,True,PASS,"['primary_event_batch_id', 'primary_event_batch_number', 'partition_batch_index', 'event_partition_order', 'event_partition', 'event_time_ns']","['primary_event_batch_id', 'primary_event_batch_number', 'partition_batch_index', 'event_partition_order', 'event_partition', 'event_time_ns']",None
...,...,...,...,...,...,...,...,...,...
80,81,HANDOFF_POLICY,handoff::observational_unit,True,True,PASS,'PRIMARY_SCORING_BATCH','PRIMARY_SCORING_BATCH',None
81,82,HANDOFF_POLICY,handoff::event_partition_field,True,True,PASS,'event_partition','event_partition',None
82,83,HANDOFF_POLICY,handoff::primary_time_field,True,True,PASS,'event_time_ns','event_time_ns',None
83,84,HANDOFF_POLICY,handoff_identity_columns,True,True,PASS,"['primary_event_batch_id', 'primary_event_batch_number', 'partition_batch_index', 'event_partition_order', 'event_partition', 'event_time_ns']","['primary_event_batch_id', 'primary_event_batch_number', 'partition_batch_index', 'event_partition_order', 'event_partition', 'event_time_ns']",None
84,85,HANDOFF_POLICY,handoff_acceptance_status_is_pass_like,True,True,PASS,'PASS_WITH_FEATURE_WARNINGS','PASS-LIKE STATUS',None

Notebook 05 non-blocking interface warnings:

,check_order,category,check_name,blocking,passed,status,observed,expected,detail
47,48,LABEL_POLICY,cross_partition_labels_allowed::registry_column_present,False,False,WARNING,False,True,The policy may instead be recorded in the Notebook 05 output manifest.

Notebook 05 causal feature / future-label interface: PASS. 571 causal T-minus features and 140 physically separate future-label fields reconcile exactly with their persisted registries and Parquet schemas. No future-label or t-plus field enters the feature interface, no undeclared feature missingness or infinite-value condition survives, and no feature imputation or label attachment was authorized. Notebook 05 authorized only the point-process baseline stage; Hawkes estimation, quoting, fill simulation, market making, and P&L evaluation remained unauthorized. Protected analytical content remains unopened. No filesystem writes were performed.

In [17]:
# ============================================================
# Notebook 06 persisted baseline authority and deterministic
# reconstruction of the locked CALIBRATION ranking
#
# LOCKED_CALIBRATION_COUNT_BASELINE_RANKING was not persisted
# by Notebook 06's result-table discovery registry. It is
# reconstructed exactly from the verified persisted unified
# count-score table.
#
# No filesystem writes are performed.
# Protected partition analytical content remains unopened.
# ============================================================


class Notebook06BaselineAuthorityError(RuntimeError):
    """Raised when Notebook 06 baseline authority is inconsistent."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

REQUIRED_NOTEBOOK06_PRECONDITIONS: Final[
    dict[str, bool]
] = {
    "V01_CONTROL_PLANE_VERIFIED": bool(
        globals().get(
            "V01_CONTROL_PLANE_VERIFIED",
            False,
        )
    ),
    "V01_MANIFESTED_FILES_VERIFIED": bool(
        globals().get(
            "V01_MANIFESTED_FILES_VERIFIED",
            False,
        )
    ),
    "V01_PHYSICAL_ARTIFACT_CATALOGUE_COMPLETE": bool(
        globals().get(
            "V01_PHYSICAL_ARTIFACT_CATALOGUE_COMPLETE",
            False,
        )
    ),
}

failed_notebook06_preconditions = sorted(
    name
    for name, passed in (
        REQUIRED_NOTEBOOK06_PRECONDITIONS.items()
    )
    if not passed
)

if failed_notebook06_preconditions:
    raise Notebook06BaselineAuthorityError(
        "Notebook 06 baseline-authority prerequisites have not "
        "passed:\n"
        f"{failed_notebook06_preconditions}"
    )

if PROTECTED_PARTITION_CONTENT_LOADED:
    raise Notebook06BaselineAuthorityError(
        "Protected partition content was unexpectedly loaded."
    )

if (
    "NOTEBOOK06_OUTPUT_MANIFEST"
    not in stage_control_payloads
):
    raise Notebook06BaselineAuthorityError(
        "The verified Notebook 06 output manifest is unavailable."
    )

if (
    "NOTEBOOK06_TERMINAL_DECISION"
    not in stage_control_payloads
):
    raise Notebook06BaselineAuthorityError(
        "The verified Notebook 06 terminal decision is unavailable."
    )


# ------------------------------------------------------------
# Bind verified Notebook 06 control artifacts
# ------------------------------------------------------------

notebook06_output_manifest = stage_control_payloads[
    "NOTEBOOK06_OUTPUT_MANIFEST"
]

notebook06_terminal_decision = stage_control_payloads[
    "NOTEBOOK06_TERMINAL_DECISION"
]

if not isinstance(
    notebook06_output_manifest,
    dict,
):
    raise Notebook06BaselineAuthorityError(
        "Notebook 06 output manifest must be a JSON object."
    )

if not isinstance(
    notebook06_terminal_decision,
    dict,
):
    raise Notebook06BaselineAuthorityError(
        "Notebook 06 terminal decision must be a JSON object."
    )

if (
    notebook06_output_manifest.get(
        "artifact_type"
    )
    != "NOTEBOOK_06_OUTPUT_MANIFEST"
):
    raise Notebook06BaselineAuthorityError(
        "Unexpected Notebook 06 output-manifest artifact type."
    )

if (
    notebook06_output_manifest.get(
        "status"
    )
    != "PASS"
):
    raise Notebook06BaselineAuthorityError(
        "Notebook 06 output manifest did not pass."
    )


# ------------------------------------------------------------
# Verify frozen identities
# ------------------------------------------------------------

NOTEBOOK06_IDENTITY_EXPECTATIONS: Final[
    dict[str, str]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
}

for identity_key, expected_value in (
    NOTEBOOK06_IDENTITY_EXPECTATIONS.items()
):
    observed_value = notebook06_output_manifest.get(
        identity_key
    )

    if observed_value != expected_value:
        raise Notebook06BaselineAuthorityError(
            "Notebook 06 output-manifest identity mismatch.\n"
            f"Field: {identity_key}\n"
            f"Observed: {observed_value}\n"
            f"Expected: {expected_value}"
        )


# ------------------------------------------------------------
# Index only actually persisted Notebook 06 result tables
# ------------------------------------------------------------

notebook06_artifact_records = (
    notebook06_output_manifest.get(
        "artifacts"
    )
)

if not isinstance(
    notebook06_artifact_records,
    list,
):
    raise Notebook06BaselineAuthorityError(
        "Notebook 06 output manifest lacks an artifact list."
    )


notebook06_result_table_record_by_name: dict[
    str,
    dict[str, Any],
] = {}

for artifact_record in notebook06_artifact_records:
    if not isinstance(
        artifact_record,
        dict,
    ):
        continue

    if (
        artifact_record.get(
            "artifact_type"
        )
        != "NOTEBOOK_06_RESULT_TABLE"
    ):
        continue

    variable_name = str(
        artifact_record.get(
            "variable_name",
            "",
        )
    ).strip()

    if not variable_name:
        raise Notebook06BaselineAuthorityError(
            "A Notebook 06 result-table artifact lacks "
            "variable_name."
        )

    if (
        variable_name
        in notebook06_result_table_record_by_name
    ):
        raise Notebook06BaselineAuthorityError(
            "Notebook 06 output manifest contains duplicate "
            f"records for result table: {variable_name}"
        )

    notebook06_result_table_record_by_name[
        variable_name
    ] = artifact_record


# LOCKED_CALIBRATION_COUNT_BASELINE_RANKING is deliberately
# excluded: Notebook 06 did not persist it.

REQUIRED_PERSISTED_NOTEBOOK06_RESULT_TABLES: Final[
    tuple[str, ...]
] = (
    "COUNT_BASELINE_MODEL_REGISTRY",
    "UNIFIED_COUNT_BASELINE_SCORE_TABLE",
    "CALIBRATION_COUNT_SCORE_BLOCKS",
    "BOOTSTRAP_COVERAGE_AUDIT",
    "COUNT_BASELINE_BLOCK_BOOTSTRAP_COMPARISON",
    "COUNT_SCORE_RECONCILIATION",
)

missing_persisted_notebook06_tables = sorted(
    set(
        REQUIRED_PERSISTED_NOTEBOOK06_RESULT_TABLES
    )
    - set(
        notebook06_result_table_record_by_name
    )
)

if missing_persisted_notebook06_tables:
    raise Notebook06BaselineAuthorityError(
        "Notebook 06 output manifest lacks required persisted "
        "baseline tables:\n"
        f"{missing_persisted_notebook06_tables}\n"
        "Registered result tables:\n"
        f"{sorted(notebook06_result_table_record_by_name)}"
    )


# ------------------------------------------------------------
# Exact path and boolean helpers
# ------------------------------------------------------------

def resolve_notebook06_result_path(
    registered_path: Any,
) -> Path:
    """Resolve one exact Notebook 06 artifact path."""

    if registered_path is None:
        raise Notebook06BaselineAuthorityError(
            "A Notebook 06 result table lacks a registered path."
        )

    candidate = Path(
        str(
            registered_path
        )
    )

    if not candidate.is_absolute():
        candidate = (
            V01_ROOT
            / candidate
        )

    resolved = normalized_resolved_path(
        candidate
    )

    require_path_inside_root(
        path=resolved,
        authorized_root=V01_ROOT,
        role="NOTEBOOK06_RESULT_TABLE",
    )

    if not resolved.exists():
        raise Notebook06BaselineAuthorityError(
            f"Notebook 06 result table does not exist: {resolved}"
        )

    if not resolved.is_file():
        raise Notebook06BaselineAuthorityError(
            "Notebook 06 result-table path is not a regular file: "
            f"{resolved}"
        )

    return resolved


def normalize_notebook06_boolean_value(
    value: Any,
) -> bool | None:
    """Normalize one persisted boolean representation."""

    if value is None:
        return None

    try:
        if pd.isna(
            value
        ):
            return None
    except (
        TypeError,
        ValueError,
    ):
        pass

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(
            value
        )

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        if int(
            value
        ) in {
            0,
            1,
        }:
            return bool(
                int(
                    value
                )
            )

    normalized = str(
        value
    ).strip().casefold()

    if normalized in {
        "true",
        "t",
        "yes",
        "y",
        "1",
    }:
        return True

    if normalized in {
        "false",
        "f",
        "no",
        "n",
        "0",
    }:
        return False

    return None


def normalize_notebook06_boolean_column(
    frame: pd.DataFrame,
    column_name: str,
) -> None:
    """Normalize one required boolean column in place."""

    if column_name not in frame.columns:
        raise Notebook06BaselineAuthorityError(
            "Notebook 06 result table lacks required boolean "
            f"column: {column_name}"
        )

    normalized = frame[
        column_name
    ].map(
        normalize_notebook06_boolean_value
    )

    unresolved_count = int(
        normalized.isna().sum()
    )

    if unresolved_count:
        unresolved_values = sorted(
            {
                str(value)
                for value in frame.loc[
                    normalized.isna(),
                    column_name,
                ]
            }
        )

        raise Notebook06BaselineAuthorityError(
            "Notebook 06 boolean normalization failed.\n"
            f"Column: {column_name}\n"
            f"Unresolved count: {unresolved_count}\n"
            f"Values: {unresolved_values}"
        )

    frame[
        column_name
    ] = normalized.astype(
        bool
    )


# ------------------------------------------------------------
# Verified result-table readback
# ------------------------------------------------------------

def load_notebook06_persisted_result_table(
    variable_name: str,
) -> pd.DataFrame:
    """Read and independently verify one persisted Notebook 06 table."""

    if (
        variable_name
        not in notebook06_result_table_record_by_name
    ):
        raise Notebook06BaselineAuthorityError(
            "Notebook 06 persisted result table is unregistered: "
            f"{variable_name}"
        )

    record = notebook06_result_table_record_by_name[
        variable_name
    ]

    artifact_path = resolve_notebook06_result_path(
        record.get(
            "path"
        )
    )

    registered_format = str(
        record.get(
            "format",
            "",
        )
    ).strip().upper()

    if registered_format != "CSV_GZIP":
        raise Notebook06BaselineAuthorityError(
            "Notebook 06 result table has an unexpected format.\n"
            f"Table: {variable_name}\n"
            f"Observed: {registered_format}\n"
            "Expected: CSV_GZIP"
        )

    registered_sha256 = str(
        record.get(
            "sha256",
            "",
        )
    ).strip().lower()

    observed_sha256 = sha256_file(
        artifact_path
    )

    if observed_sha256 != registered_sha256:
        raise Notebook06BaselineAuthorityError(
            "Notebook 06 result-table file hash mismatch.\n"
            f"Table: {variable_name}\n"
            f"Observed: {observed_sha256}\n"
            f"Expected: {registered_sha256}"
        )

    registered_size_value = record.get(
        "byte_count",
        record.get(
            "size_bytes"
        ),
    )

    if registered_size_value is not None:
        registered_size = int(
            registered_size_value
        )

        observed_size = int(
            artifact_path.stat().st_size
        )

        if observed_size != registered_size:
            raise Notebook06BaselineAuthorityError(
                "Notebook 06 result-table byte-count mismatch.\n"
                f"Table: {variable_name}\n"
                f"Observed: {observed_size}\n"
                f"Expected: {registered_size}"
            )

    observed_frame = pd.read_csv(
        artifact_path,
        compression="gzip",
        low_memory=False,
    )

    expected_row_count = int(
        record[
            "row_count"
        ]
    )

    expected_column_count = int(
        record[
            "column_count"
        ]
    )

    expected_columns = [
        str(
            column_name
        )
        for column_name in record[
            "columns"
        ]
    ]

    if len(
        observed_frame
    ) != expected_row_count:
        raise Notebook06BaselineAuthorityError(
            "Notebook 06 result-table row count differs from "
            f"the manifest: {variable_name}"
        )

    if (
        observed_frame.shape[
            1
        ]
        != expected_column_count
    ):
        raise Notebook06BaselineAuthorityError(
            "Notebook 06 result-table column count differs from "
            f"the manifest: {variable_name}"
        )

    if (
        list(
            map(
                str,
                observed_frame.columns,
            )
        )
        != expected_columns
    ):
        raise Notebook06BaselineAuthorityError(
            "Notebook 06 result-table column order differs from "
            f"the manifest: {variable_name}"
        )

    return observed_frame


NOTEBOOK06_PERSISTED_RESULT_TABLES: dict[
    str,
    pd.DataFrame,
] = {
    variable_name: (
        load_notebook06_persisted_result_table(
            variable_name
        )
    )
    for variable_name in (
        REQUIRED_PERSISTED_NOTEBOOK06_RESULT_TABLES
    )
}


# ------------------------------------------------------------
# Stable table bindings
# ------------------------------------------------------------

COUNT_BASELINE_MODEL_REGISTRY = (
    NOTEBOOK06_PERSISTED_RESULT_TABLES[
        "COUNT_BASELINE_MODEL_REGISTRY"
    ].copy(
        deep=True
    )
)

UNIFIED_COUNT_BASELINE_SCORE_TABLE = (
    NOTEBOOK06_PERSISTED_RESULT_TABLES[
        "UNIFIED_COUNT_BASELINE_SCORE_TABLE"
    ].copy(
        deep=True
    )
)

CALIBRATION_COUNT_SCORE_BLOCKS = (
    NOTEBOOK06_PERSISTED_RESULT_TABLES[
        "CALIBRATION_COUNT_SCORE_BLOCKS"
    ].copy(
        deep=True
    )
)

BOOTSTRAP_COVERAGE_AUDIT = (
    NOTEBOOK06_PERSISTED_RESULT_TABLES[
        "BOOTSTRAP_COVERAGE_AUDIT"
    ].copy(
        deep=True
    )
)

COUNT_BASELINE_BLOCK_BOOTSTRAP_COMPARISON = (
    NOTEBOOK06_PERSISTED_RESULT_TABLES[
        "COUNT_BASELINE_BLOCK_BOOTSTRAP_COMPARISON"
    ].copy(
        deep=True
    )
)

COUNT_SCORE_RECONCILIATION = (
    NOTEBOOK06_PERSISTED_RESULT_TABLES[
        "COUNT_SCORE_RECONCILIATION"
    ].copy(
        deep=True
    )
)


# ------------------------------------------------------------
# Normalize persisted boolean columns
# ------------------------------------------------------------

for boolean_column in (
    "primary_simple_count_baseline_flag",
    "formal_count_comparator_flag",
    "calibration_used_for_selection",
):
    normalize_notebook06_boolean_column(
        COUNT_BASELINE_MODEL_REGISTRY,
        boolean_column,
    )

for boolean_column in (
    "primary_simple_count_baseline_flag",
    "formal_count_comparator_flag",
    "calibration_used_for_selection",
    "locked_before_calibration",
):
    normalize_notebook06_boolean_column(
        UNIFIED_COUNT_BASELINE_SCORE_TABLE,
        boolean_column,
    )

if (
    "complete_equal_exposure_block_flag"
    in CALIBRATION_COUNT_SCORE_BLOCKS.columns
):
    normalize_notebook06_boolean_column(
        CALIBRATION_COUNT_SCORE_BLOCKS,
        "complete_equal_exposure_block_flag",
    )

for boolean_column in (
    "equal_exposure_blocks_only",
    "partial_final_block_excluded_from_ci",
    "full_calibration_score_still_reported",
):
    if boolean_column in BOOTSTRAP_COVERAGE_AUDIT.columns:
        normalize_notebook06_boolean_column(
            BOOTSTRAP_COVERAGE_AUDIT,
            boolean_column,
        )


# ------------------------------------------------------------
# Resolve formal comparator and primary simple baseline
# ------------------------------------------------------------

formal_comparator_rows = (
    COUNT_BASELINE_MODEL_REGISTRY.loc[
        COUNT_BASELINE_MODEL_REGISTRY[
            "formal_count_comparator_flag"
        ]
    ]
)

primary_simple_rows = (
    COUNT_BASELINE_MODEL_REGISTRY.loc[
        COUNT_BASELINE_MODEL_REGISTRY[
            "primary_simple_count_baseline_flag"
        ]
    ]
)

if len(
    formal_comparator_rows
) != 1:
    raise Notebook06BaselineAuthorityError(
        "Notebook 06 must identify exactly one formal count "
        "comparator."
    )

if len(
    primary_simple_rows
) != 1:
    raise Notebook06BaselineAuthorityError(
        "Notebook 06 must identify exactly one primary simple "
        "count baseline."
    )


FORMAL_COUNT_COMPARATOR_MODEL_ID: Final[str] = str(
    formal_comparator_rows.iloc[
        0
    ][
        "model_id"
    ]
)

PRIMARY_SIMPLE_COUNT_BASELINE_MODEL_ID: Final[str] = str(
    primary_simple_rows.iloc[
        0
    ][
        "model_id"
    ]
)


terminal_formal_comparator = str(
    notebook06_terminal_decision.get(
        "formal_count_comparator",
        "",
    )
)

terminal_primary_simple_baseline = str(
    notebook06_terminal_decision.get(
        "primary_simple_count_baseline",
        "",
    )
)

if (
    FORMAL_COUNT_COMPARATOR_MODEL_ID
    != terminal_formal_comparator
):
    raise Notebook06BaselineAuthorityError(
        "Formal count-comparator identity differs between the "
        "persisted registry and terminal decision.\n"
        f"Registry: {FORMAL_COUNT_COMPARATOR_MODEL_ID}\n"
        f"Terminal decision: {terminal_formal_comparator}"
    )

if (
    PRIMARY_SIMPLE_COUNT_BASELINE_MODEL_ID
    != terminal_primary_simple_baseline
):
    raise Notebook06BaselineAuthorityError(
        "Primary simple-baseline identity differs between the "
        "persisted registry and terminal decision.\n"
        f"Registry: {PRIMARY_SIMPLE_COUNT_BASELINE_MODEL_ID}\n"
        f"Terminal decision: {terminal_primary_simple_baseline}"
    )


# ------------------------------------------------------------
# Reconstruct the non-persisted locked CALIBRATION ranking
# ------------------------------------------------------------

REQUIRED_UNIFIED_SCORE_COLUMNS: Final[
    set[str]
] = {
    "model_id",
    "model_family",
    "scored_partition",
    "observed_event_count",
    "predicted_event_count",
    "log_score_total",
    "log_score_per_second",
    "log_score_per_observed_event",
    "primary_simple_count_baseline_flag",
    "formal_count_comparator_flag",
    "calibration_used_for_selection",
    "locked_before_calibration",
    "status",
}

missing_unified_score_columns = sorted(
    REQUIRED_UNIFIED_SCORE_COLUMNS
    - set(
        map(
            str,
            UNIFIED_COUNT_BASELINE_SCORE_TABLE.columns,
        )
    )
)

if missing_unified_score_columns:
    raise Notebook06BaselineAuthorityError(
        "The persisted Notebook 06 unified score table lacks "
        "required columns:\n"
        f"{missing_unified_score_columns}"
    )


LOCKED_CALIBRATION_COUNT_BASELINE_RANKING = (
    UNIFIED_COUNT_BASELINE_SCORE_TABLE.loc[
        UNIFIED_COUNT_BASELINE_SCORE_TABLE[
            "scored_partition"
        ]
        .astype(
            "string"
        )
        .str.strip()
        .str.upper()
        .eq(
            "CALIBRATION"
        )
    ]
    .copy(
        deep=True
    )
    .sort_values(
        [
            "log_score_total",
            "model_id",
        ],
        ascending=[
            False,
            True,
        ],
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)

if LOCKED_CALIBRATION_COUNT_BASELINE_RANKING.empty:
    raise Notebook06BaselineAuthorityError(
        "The persisted Notebook 06 unified score table contains "
        "no CALIBRATION baseline rows."
    )

if not LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
    "locked_before_calibration"
].all():
    raise Notebook06BaselineAuthorityError(
        "At least one CALIBRATION-ranked baseline was not locked "
        "before CALIBRATION."
    )

if LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
    "calibration_used_for_selection"
].any():
    raise Notebook06BaselineAuthorityError(
        "At least one ranked baseline used CALIBRATION for model "
        "selection."
    )


registered_model_ids = set(
    COUNT_BASELINE_MODEL_REGISTRY[
        "model_id"
    ].astype(
        str
    )
)

ranked_model_ids = set(
    LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
        "model_id"
    ].astype(
        str
    )
)

if ranked_model_ids != registered_model_ids:
    raise Notebook06BaselineAuthorityError(
        "The reconstructed CALIBRATION ranking does not contain "
        "exactly the registered Notebook 06 model set.\n"
        f"Missing from ranking: "
        f"{sorted(registered_model_ids - ranked_model_ids)}\n"
        f"Unexpected in ranking: "
        f"{sorted(ranked_model_ids - registered_model_ids)}"
    )

if (
    LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
        "model_id"
    ].nunique()
    != len(
        LOCKED_CALIBRATION_COUNT_BASELINE_RANKING
    )
):
    raise Notebook06BaselineAuthorityError(
        "The reconstructed CALIBRATION ranking contains duplicate "
        "model identities."
    )


LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
    "calibration_score_rank"
] = np.arange(
    1,
    len(
        LOCKED_CALIBRATION_COUNT_BASELINE_RANKING
    )
    + 1,
    dtype=np.int64,
)


formal_comparator_score_rows = (
    LOCKED_CALIBRATION_COUNT_BASELINE_RANKING.loc[
        LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
            "model_id"
        ].eq(
            FORMAL_COUNT_COMPARATOR_MODEL_ID
        ),
        "log_score_total",
    ]
)

if len(
    formal_comparator_score_rows
) != 1:
    raise Notebook06BaselineAuthorityError(
        "The reconstructed ranking does not contain exactly one "
        "formal-comparator score."
    )


formal_comparator_calibration_score = float(
    formal_comparator_score_rows.iloc[
        0
    ]
)

LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
    "log_score_improvement_over_formal_comparator"
] = (
    pd.to_numeric(
        LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
            "log_score_total"
        ],
        errors="raise",
    )
    - formal_comparator_calibration_score
)

LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
    "ranking_role"
] = (
    "LOCKED_CALIBRATION_DIAGNOSTIC_ONLY"
)

LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
    "reconstruction_basis"
] = (
    "PERSISTED_UNIFIED_COUNT_BASELINE_SCORE_TABLE"
)

LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
    "persisted_as_standalone_table"
] = False


# ------------------------------------------------------------
# Verify reconstructed ranking semantics
# ------------------------------------------------------------

rank_values = (
    LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
        "calibration_score_rank"
    ].tolist()
)

expected_rank_values = list(
    range(
        1,
        len(
            LOCKED_CALIBRATION_COUNT_BASELINE_RANKING
        )
        + 1,
    )
)

if rank_values != expected_rank_values:
    raise Notebook06BaselineAuthorityError(
        "The reconstructed CALIBRATION rank sequence is invalid."
    )


ranked_scores = pd.to_numeric(
    LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
        "log_score_total"
    ],
    errors="raise",
).to_numpy(
    dtype=np.float64
)

if not np.isfinite(
    ranked_scores
).all():
    raise Notebook06BaselineAuthorityError(
        "The reconstructed CALIBRATION ranking contains "
        "non-finite log scores."
    )

if len(
    ranked_scores
) > 1:
    score_order_is_descending = bool(
        np.all(
            ranked_scores[
                :-1
            ]
            >= ranked_scores[
                1:
            ]
        )
    )

else:
    score_order_is_descending = True

if not score_order_is_descending:
    raise Notebook06BaselineAuthorityError(
        "The reconstructed CALIBRATION ranking is not ordered by "
        "descending log score."
    )


ranking_status_values = (
    LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
        "status"
    ]
    .astype(
        "string"
    )
    .str.strip()
    .str.upper()
)

if not ranking_status_values.str.startswith(
    "PASS",
    na=False,
).all():
    raise Notebook06BaselineAuthorityError(
        "At least one reconstructed ranking row is not pass-like."
    )


# ------------------------------------------------------------
# Persisted-table readback audit
# ------------------------------------------------------------

notebook06_result_table_readback_records: list[
    dict[str, Any]
] = []

for variable_name in (
    REQUIRED_PERSISTED_NOTEBOOK06_RESULT_TABLES
):
    record = notebook06_result_table_record_by_name[
        variable_name
    ]

    frame = NOTEBOOK06_PERSISTED_RESULT_TABLES[
        variable_name
    ]

    artifact_path = resolve_notebook06_result_path(
        record[
            "path"
        ]
    )

    notebook06_result_table_readback_records.append(
        {
            "table_name": variable_name,
            "persistence_role": (
                "PERSISTED_NOTEBOOK_06_RESULT_TABLE"
            ),
            "path": str(
                artifact_path
            ),
            "row_count": int(
                len(
                    frame
                )
            ),
            "column_count": int(
                frame.shape[
                    1
                ]
            ),
            "file_sha256": sha256_file(
                artifact_path
            ),
            "file_hash_matches": True,
            "row_count_matches": True,
            "column_count_matches": True,
            "column_order_matches": True,
            "status": "PASS",
        }
    )


notebook06_result_table_readback_records.append(
    {
        "table_name": (
            "LOCKED_CALIBRATION_COUNT_BASELINE_RANKING"
        ),
        "persistence_role": (
            "DETERMINISTICALLY_RECONSTRUCTED_RUNTIME_TABLE"
        ),
        "path": None,
        "row_count": int(
            len(
                LOCKED_CALIBRATION_COUNT_BASELINE_RANKING
            )
        ),
        "column_count": int(
            LOCKED_CALIBRATION_COUNT_BASELINE_RANKING.shape[
                1
            ]
        ),
        "file_sha256": None,
        "file_hash_matches": None,
        "row_count_matches": True,
        "column_count_matches": True,
        "column_order_matches": True,
        "status": "PASS_RECONSTRUCTED",
    }
)


V01_NOTEBOOK06_BASELINE_TABLE_READBACK_AUDIT = (
    pd.DataFrame(
        notebook06_result_table_readback_records
    )
    .sort_values(
        "table_name",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


V01_NOTEBOOK06_BASELINE_AUTHORITY_SUMMARY = pd.DataFrame(
    [
        {
            "metric": "persisted_result_table_count",
            "value": int(
                len(
                    REQUIRED_PERSISTED_NOTEBOOK06_RESULT_TABLES
                )
            ),
        },
        {
            "metric": (
                "reconstructed_runtime_table_count"
            ),
            "value": 1,
        },
        {
            "metric": (
                "registered_count_baseline_model_count"
            ),
            "value": int(
                len(
                    COUNT_BASELINE_MODEL_REGISTRY
                )
            ),
        },
        {
            "metric": (
                "locked_calibration_ranking_row_count"
            ),
            "value": int(
                len(
                    LOCKED_CALIBRATION_COUNT_BASELINE_RANKING
                )
            ),
        },
        {
            "metric": "formal_count_comparator",
            "value": FORMAL_COUNT_COMPARATOR_MODEL_ID,
        },
        {
            "metric": "primary_simple_count_baseline",
            "value": (
                PRIMARY_SIMPLE_COUNT_BASELINE_MODEL_ID
            ),
        },
        {
            "metric": (
                "calibration_used_for_selection_count"
            ),
            "value": int(
                LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
                    "calibration_used_for_selection"
                ].sum()
            ),
        },
        {
            "metric": (
                "not_locked_before_calibration_count"
            ),
            "value": int(
                (
                    ~LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
                        "locked_before_calibration"
                    ]
                ).sum()
            ),
        },
        {
            "metric": (
                "protected_partition_content_loaded"
            ),
            "value": False,
        },
    ]
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    V01_NOTEBOOK06_BASELINE_AUTHORITY_SUMMARY
)

display(
    V01_NOTEBOOK06_BASELINE_TABLE_READBACK_AUDIT
)

display(
    LOCKED_CALIBRATION_COUNT_BASELINE_RANKING[
        [
            "calibration_score_rank",
            "model_id",
            "model_family",
            "observed_event_count",
            "predicted_event_count",
            "log_score_total",
            "log_score_per_second",
            "log_score_improvement_over_formal_comparator",
            "primary_simple_count_baseline_flag",
            "formal_count_comparator_flag",
            "locked_before_calibration",
            "calibration_used_for_selection",
            "ranking_role",
            "reconstruction_basis",
            "status",
        ]
    ]
)


# ------------------------------------------------------------
# Freeze Notebook 06 baseline authority
# ------------------------------------------------------------

FROZEN_NOTEBOOK06_BASELINE_AUTHORITY: Final[
    dict[str, Any]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "terminal_status": (
        notebook06_terminal_decision.get(
            "terminal_status"
        )
    ),
    "authorization_state": (
        notebook06_terminal_decision.get(
            "authorization_state"
        )
    ),
    "formal_count_comparator_model_id": (
        FORMAL_COUNT_COMPARATOR_MODEL_ID
    ),
    "primary_simple_count_baseline_model_id": (
        PRIMARY_SIMPLE_COUNT_BASELINE_MODEL_ID
    ),
    "registered_model_count": int(
        len(
            COUNT_BASELINE_MODEL_REGISTRY
        )
    ),
    "persisted_result_tables": list(
        REQUIRED_PERSISTED_NOTEBOOK06_RESULT_TABLES
    ),
    "reconstructed_result_tables": [
        "LOCKED_CALIBRATION_COUNT_BASELINE_RANKING",
    ],
    "locked_calibration_ranking": [
        {
            "calibration_score_rank": int(
                row.calibration_score_rank
            ),
            "model_id": str(
                row.model_id
            ),
            "model_family": str(
                row.model_family
            ),
            "log_score_total": float(
                row.log_score_total
            ),
            "log_score_improvement_over_formal_comparator": float(
                row.log_score_improvement_over_formal_comparator
            ),
            "primary_simple_count_baseline_flag": bool(
                row.primary_simple_count_baseline_flag
            ),
            "formal_count_comparator_flag": bool(
                row.formal_count_comparator_flag
            ),
        }
        for row in (
            LOCKED_CALIBRATION_COUNT_BASELINE_RANKING.itertuples(
                index=False
            )
        )
    ],
    "calibration_parameter_updates": 0,
    "protected_partition_content_loaded": False,
}


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

NOTEBOOK06_BASELINE_AUTHORITY_VERIFIED = True
NOTEBOOK06_PERSISTED_RESULT_TABLES_VERIFIED = True
NOTEBOOK06_LOCKED_CALIBRATION_RANKING_RECONSTRUCTED = True

UPSTREAM_ARTIFACTS_VERIFIED = False

PROTECTED_PARTITION_CONTENT_LOADED = False
VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "Notebook 06 baseline authority: PASS. Six required "
    "result tables were loaded from the verified output manifest "
    "and independently reconciled to their physical hashes, row "
    "counts, and column order. "
    "LOCKED_CALIBRATION_COUNT_BASELINE_RANKING was correctly "
    "treated as a non-persisted runtime table and reconstructed "
    "deterministically from the persisted unified score table. "
    "All ranked models were locked before CALIBRATION, none used "
    "CALIBRATION for selection, and the formal comparator and "
    "primary simple baseline identities reconcile with the "
    "Notebook 06 terminal decision. No filesystem writes were "
    "performed."
)

                                  metric                      value
0           persisted_result_table_count                          6
1      reconstructed_runtime_table_count                          1
2  registered_count_baseline_model_count                          4
3   locked_calibration_ranking_row_count                          4
4                formal_count_comparator   D0_SIDE_CONSTANT_POISSON
5          primary_simple_count_baseline  E_SIDE_EWMA_250MS_POISSON
6   calibration_used_for_selection_count                          0
7    not_locked_before_calibration_count                          0
8     protected_partition_content_loaded                      False

,table_name,persistence_role,path,row_count,column_count,file_sha256,file_hash_matches,row_count_matches,column_count_matches,column_order_matches,status
0,BOOTSTRAP_COVERAGE_AUDIT,PERSISTED_NOTEBOOK_06_RESULT_TABLE,d:\clown project\v0.1\artifacts\audit_tables\06_point_process_baselines\bootstrap_coverage_audit.csv.gz,1,14,be3843375df89c97ab19121da1bd9402928d91b38396b2c870dade23220f8da8,True,True,True,True,PASS
1,CALIBRATION_COUNT_SCORE_BLOCKS,PERSISTED_NOTEBOOK_06_RESULT_TABLE,d:\clown project\v0.1\artifacts\audit_tables\06_point_process_baselines\calibration_count_score_blocks.csv.gz,288,11,749f18c9dd4132260aa963d510651dbdf64a5a6998df82128e9c90f0d0bd224c,True,True,True,True,PASS
2,COUNT_BASELINE_BLOCK_BOOTSTRAP_COMPARISON,PERSISTED_NOTEBOOK_06_RESULT_TABLE,d:\clown project\v0.1\artifacts\audit_tables\06_point_process_baselines\count_baseline_block_bootstrap_comparison.csv.gz,3,24,be7b64591ee202810bfe97c090f892c1c60c6826dc44291cfde7b82010ae1f5d,True,True,True,True,PASS
3,COUNT_BASELINE_MODEL_REGISTRY,PERSISTED_NOTEBOOK_06_RESULT_TABLE,d:\clown project\v0.1\artifacts\audit_tables\06_point_process_baselines\count_baseline_model_registry.csv.gz,4,11,e3bc5947109f0cca7d81fd46da51a2a94065d58bb71334ecdf60a0d272a983ba,True,True,True,True,PASS
4,COUNT_SCORE_RECONCILIATION,PERSISTED_NOTEBOOK_06_RESULT_TABLE,d:\clown project\v0.1\artifacts\audit_tables\06_point_process_baselines\count_score_reconciliation.csv.gz,8,8,1516b2cff4a24f9ea258217288ff0700147e77344bdd9d2ab994d6e758c9a5e0,True,True,True,True,PASS
5,LOCKED_CALIBRATION_COUNT_BASELINE_RANKING,DETERMINISTICALLY_RECONSTRUCTED_RUNTIME_TABLE,None,4,25,None,None,True,True,True,PASS_RECONSTRUCTED
6,UNIFIED_COUNT_BASELINE_SCORE_TABLE,PERSISTED_NOTEBOOK_06_RESULT_TABLE,d:\clown project\v0.1\artifacts\audit_tables\06_point_process_baselines\unified_count_baseline_score_table.csv.gz,8,20,8acd637aeb35435fdb09456a8288b3721af485ac8a86e623b04b4c5f79273ccd,True,True,True,True,PASS

,calibration_score_rank,model_id,model_family,observed_event_count,predicted_event_count,log_score_total,log_score_per_second,log_score_improvement_over_formal_comparator,primary_simple_count_baseline_flag,formal_count_comparator_flag,locked_before_calibration,calibration_used_for_selection,ranking_role,reconstruction_basis,status
0,1,E_SIDE_EWMA_250MS_POISSON,CAUSAL_EXPONENTIALLY_WEIGHTED_RATE,2493,"2,673.479105","-18,072.44329",-25.09019004,368.3327884,True,False,True,False,LOCKED_CALIBRATION_DIAGNOSTIC_ONLY,PERSISTED_UNIFIED_COUNT_BASELINE_SCORE_TABLE,PASS
1,2,R_SIDE_ROLLING_250MS_POISSON,CAUSAL_ROLLING_WINDOW_RATE,2493,"2,699.452555","-18,095.79606",-25.12261098,344.9800145,False,False,True,False,LOCKED_CALIBRATION_DIAGNOSTIC_ONLY,PERSISTED_UNIFIED_COUNT_BASELINE_SCORE_TABLE,PASS
2,3,B1_SIDE_SPECIFIC_HOMOGENEOUS_POISSON,INDEPENDENT_SIDE_SPECIFIC_HOMOGENEOUS_POISSON,2493,"2,799.871581","-18,440.77608",-25.60155087,0,False,False,True,False,LOCKED_CALIBRATION_DIAGNOSTIC_ONLY,PERSISTED_UNIFIED_COUNT_BASELINE_SCORE_TABLE,PASS
3,4,D0_SIDE_CONSTANT_POISSON,INDEPENDENT_SIDE_SPECIFIC_DETERMINISTIC_ELAPSED_TIME_POISSON,2493,"2,799.871581","-18,440.77608",-25.60155087,0,False,True,True,False,LOCKED_CALIBRATION_DIAGNOSTIC_ONLY,PERSISTED_UNIFIED_COUNT_BASELINE_SCORE_TABLE,PASS

Notebook 06 baseline authority: PASS. Six required result tables were loaded from the verified output manifest and independently reconciled to their physical hashes, row counts, and column order. LOCKED_CALIBRATION_COUNT_BASELINE_RANKING was correctly treated as a non-persisted runtime table and reconstructed deterministically from the persisted unified score table. All ranked models were locked before CALIBRATION, none used CALIBRATION for selection, and the formal comparator and primary simple baseline identities reconcile with the Notebook 06 terminal decision. No filesystem writes were performed.

In [26]:
# ============================================================
# Notebook 07 execution-contract final gate
#
# Correct persisted handoff schema:
#     selected_model.model_id
#
# This block replaces the incorrect top-level
# handoff["selected_model_id"] check and completes the freeze.
#
# No filesystem writes are performed.
# ============================================================


class Notebook07ExecutionContractError(RuntimeError):
    """Raised when Notebook 07 execution authority is inconsistent."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

if (
    "V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT"
    not in globals()
):
    raise Notebook07ExecutionContractError(
        "The Notebook 07 execution-contract audit table is unavailable."
    )

if not isinstance(
    V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT,
    pd.DataFrame,
):
    raise Notebook07ExecutionContractError(
        "V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT must be a DataFrame."
    )

REQUIRED_EXECUTION_AUDIT_COLUMNS = {
    "check_order",
    "source_artifact",
    "check_name",
    "blocking",
    "passed",
    "status",
    "observed",
    "expected",
}

missing_execution_audit_columns = sorted(
    REQUIRED_EXECUTION_AUDIT_COLUMNS
    - set(
        map(
            str,
            V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT.columns,
        )
    )
)

if missing_execution_audit_columns:
    raise Notebook07ExecutionContractError(
        "The Notebook 07 execution-contract audit lacks required "
        f"columns: {missing_execution_audit_columns}"
    )


# ------------------------------------------------------------
# Bind the persisted Notebook 07-to-08 handoff
# ------------------------------------------------------------

notebook07_execution_handoff = None
notebook07_execution_handoff_source = None

if isinstance(
    globals().get(
        "stage_control_payloads"
    ),
    dict,
):
    candidate = stage_control_payloads.get(
        "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF"
    )

    if isinstance(
        candidate,
        dict,
    ):
        notebook07_execution_handoff = candidate
        notebook07_execution_handoff_source = (
            "stage_control_payloads"
        )

if notebook07_execution_handoff is None:
    for candidate_name in (
        "notebook07_to_notebook08_handoff",
        "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF",
        "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF_PAYLOAD",
    ):
        candidate = globals().get(
            candidate_name
        )

        if isinstance(
            candidate,
            dict,
        ):
            notebook07_execution_handoff = candidate
            notebook07_execution_handoff_source = candidate_name
            break

if not isinstance(
    notebook07_execution_handoff,
    dict,
):
    raise Notebook07ExecutionContractError(
        "The persisted Notebook 07-to-Notebook 08 handoff "
        "could not be resolved."
    )


# ------------------------------------------------------------
# Read the selected model from its actual persisted location
# ------------------------------------------------------------

selected_model_section = (
    notebook07_execution_handoff.get(
        "selected_model"
    )
)

if not isinstance(
    selected_model_section,
    dict,
):
    raise Notebook07ExecutionContractError(
        "The Notebook 07 handoff lacks the required "
        "selected_model object."
    )

observed_handoff_selected_model_id = (
    selected_model_section.get(
        "model_id"
    )
)

if not isinstance(
    observed_handoff_selected_model_id,
    str,
) or not observed_handoff_selected_model_id.strip():
    raise Notebook07ExecutionContractError(
        "The Notebook 07 handoff lacks a valid "
        "selected_model.model_id value."
    )

observed_handoff_selected_model_id = (
    observed_handoff_selected_model_id.strip()
)


# ------------------------------------------------------------
# Locate the one erroneous audit row
# ------------------------------------------------------------

notebook07_execution_audit = (
    V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT.copy(
        deep=True
    )
)

selected_model_check_mask = (
    notebook07_execution_audit[
        "source_artifact"
    ]
    .astype(
        "string"
    )
    .eq(
        "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF"
    )
    & notebook07_execution_audit[
        "check_name"
    ]
    .astype(
        "string"
    )
    .isin(
        [
            "handoff::selected_model_id",
            "handoff::selected_model.model_id",
        ]
    )
)

selected_model_check_count = int(
    selected_model_check_mask.sum()
)

if selected_model_check_count != 1:
    raise Notebook07ExecutionContractError(
        "Expected exactly one Notebook 07 handoff selected-model "
        "audit row.\n"
        f"Observed count: {selected_model_check_count}"
    )


# ------------------------------------------------------------
# Recover the already-declared expected model identity
# ------------------------------------------------------------

import ast


registered_expected_value = (
    notebook07_execution_audit.loc[
        selected_model_check_mask,
        "expected",
    ]
    .iloc[
        0
    ]
)

expected_handoff_selected_model_id = None

if isinstance(
    registered_expected_value,
    str,
):
    try:
        parsed_expected_value = ast.literal_eval(
            registered_expected_value
        )

        if isinstance(
            parsed_expected_value,
            str,
        ):
            expected_handoff_selected_model_id = (
                parsed_expected_value.strip()
            )

    except (
        SyntaxError,
        ValueError,
    ):
        stripped_expected_value = (
            registered_expected_value.strip()
        )

        if stripped_expected_value:
            expected_handoff_selected_model_id = (
                stripped_expected_value.strip(
                    "'\""
                )
            )

if not expected_handoff_selected_model_id:
    expected_candidates: list[str] = []

    for candidate in (
        globals().get(
            "EXPECTED_SELECTED_MODEL_ID"
        ),
        globals().get(
            "SELECTED_HAWKES_MODEL_ID"
        ),
    ):
        if isinstance(
            candidate,
            str,
        ) and candidate.strip():
            expected_candidates.append(
                candidate.strip()
            )

    frozen_notebook08_authority = globals().get(
        "FROZEN_NOTEBOOK08_AUTHORITY"
    )

    if isinstance(
        frozen_notebook08_authority,
        dict,
    ):
        candidate = frozen_notebook08_authority.get(
            "selected_model_id"
        )

        if isinstance(
            candidate,
            str,
        ) and candidate.strip():
            expected_candidates.append(
                candidate.strip()
            )

    unique_expected_candidates = sorted(
        set(
            expected_candidates
        )
    )

    if len(
        unique_expected_candidates
    ) != 1:
        raise Notebook07ExecutionContractError(
            "Unable to resolve one expected Notebook 07 selected "
            "model identity.\n"
            f"Candidates: {unique_expected_candidates}"
        )

    expected_handoff_selected_model_id = (
        unique_expected_candidates[
            0
        ]
    )


# ------------------------------------------------------------
# Correct the audit row
# ------------------------------------------------------------

selected_model_id_matches = bool(
    observed_handoff_selected_model_id
    == expected_handoff_selected_model_id
)

notebook07_execution_audit.loc[
    selected_model_check_mask,
    "check_name",
] = "handoff::selected_model.model_id"

notebook07_execution_audit.loc[
    selected_model_check_mask,
    "observed",
] = repr(
    observed_handoff_selected_model_id
)

notebook07_execution_audit.loc[
    selected_model_check_mask,
    "expected",
] = repr(
    expected_handoff_selected_model_id
)

notebook07_execution_audit.loc[
    selected_model_check_mask,
    "passed",
] = selected_model_id_matches

notebook07_execution_audit.loc[
    selected_model_check_mask,
    "status",
] = (
    "PASS"
    if selected_model_id_matches
    else "FAIL"
)


# ------------------------------------------------------------
# Independent cross-artifact model-identity reconciliation
# ------------------------------------------------------------

model_identity_sources: dict[str, str] = {
    "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF.selected_model.model_id": (
        observed_handoff_selected_model_id
    ),
    "EXPECTED_SELECTED_MODEL_ID": (
        expected_handoff_selected_model_id
    ),
}

frozen_notebook08_authority = globals().get(
    "FROZEN_NOTEBOOK08_AUTHORITY"
)

if isinstance(
    frozen_notebook08_authority,
    dict,
):
    candidate = frozen_notebook08_authority.get(
        "selected_model_id"
    )

    if isinstance(
        candidate,
        str,
    ) and candidate.strip():
        model_identity_sources[
            "FROZEN_NOTEBOOK08_AUTHORITY.selected_model_id"
        ] = candidate.strip()

final_disposition_payload = None

if isinstance(
    globals().get(
        "controlling_artifact_payloads"
    ),
    dict,
):
    candidate = controlling_artifact_payloads.get(
        "NOTEBOOK08_FINAL_DISPOSITION"
    )

    if isinstance(
        candidate,
        dict,
    ):
        final_disposition_payload = candidate

if isinstance(
    final_disposition_payload,
    dict,
):
    candidate = final_disposition_payload.get(
        "selected_model_id"
    )

    if isinstance(
        candidate,
        str,
    ) and candidate.strip():
        model_identity_sources[
            "NOTEBOOK08_FINAL_DISPOSITION.selected_model_id"
        ] = candidate.strip()

unique_model_identity_values = sorted(
    set(
        model_identity_sources.values()
    )
)

if unique_model_identity_values != [
    expected_handoff_selected_model_id
]:
    raise Notebook07ExecutionContractError(
        "Notebook 07 selected-model identity does not reconcile "
        "across persisted authorities.\n"
        + json.dumps(
            model_identity_sources,
            indent=2,
            ensure_ascii=False,
        )
    )


# ------------------------------------------------------------
# Rebuild final failure and warning tables
# ------------------------------------------------------------

notebook07_execution_audit[
    "blocking"
] = notebook07_execution_audit[
    "blocking"
].fillna(
    False
).astype(
    bool
)

notebook07_execution_audit[
    "passed"
] = notebook07_execution_audit[
    "passed"
].fillna(
    False
).astype(
    bool
)

V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT = (
    notebook07_execution_audit.sort_values(
        "check_order",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)

V01_NOTEBOOK07_EXECUTION_CONTRACT_FAILURES = (
    V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT.loc[
        V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT[
            "blocking"
        ]
        & ~V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT[
            "passed"
        ]
    ]
    .copy()
)

V01_NOTEBOOK07_EXECUTION_CONTRACT_WARNINGS = (
    V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT.loc[
        ~V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT[
            "blocking"
        ]
        & ~V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT[
            "passed"
        ]
    ]
    .copy()
)


# ------------------------------------------------------------
# Summary helpers
# ------------------------------------------------------------

def prior_notebook07_summary_value(
    metric_name: str,
    default: Any = None,
) -> Any:
    """Recover one value from the previously built summary table."""

    summary_frame = globals().get(
        "V01_NOTEBOOK07_EXECUTION_CONTRACT_SUMMARY"
    )

    if not isinstance(
        summary_frame,
        pd.DataFrame,
    ):
        return default

    if not {
        "metric",
        "value",
    }.issubset(
        summary_frame.columns
    ):
        return default

    matching_rows = summary_frame.loc[
        summary_frame[
            "metric"
        ].astype(
            "string"
        ).eq(
            metric_name
        ),
        "value",
    ]

    if len(
        matching_rows
    ) != 1:
        return default

    return matching_rows.iloc[
        0
    ]


V01_NOTEBOOK07_EXECUTION_CONTRACT_SUMMARY = pd.DataFrame(
    [
        {
            "metric": "model_contract_package_path",
            "value": prior_notebook07_summary_value(
                "model_contract_package_path"
            ),
        },
        {
            "metric": "model_contract_file_sha256",
            "value": prior_notebook07_summary_value(
                "model_contract_file_sha256"
            ),
        },
        {
            "metric": "model_contract_semantic_sha256",
            "value": prior_notebook07_summary_value(
                "model_contract_semantic_sha256"
            ),
        },
        {
            "metric": "canonical_contract_leaf_count",
            "value": prior_notebook07_summary_value(
                "canonical_contract_leaf_count"
            ),
        },
        {
            "metric": "contract_check_count",
            "value": int(
                len(
                    V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT
                )
            ),
        },
        {
            "metric": "blocking_failure_count",
            "value": int(
                len(
                    V01_NOTEBOOK07_EXECUTION_CONTRACT_FAILURES
                )
            ),
        },
        {
            "metric": "nonblocking_warning_count",
            "value": int(
                len(
                    V01_NOTEBOOK07_EXECUTION_CONTRACT_WARNINGS
                )
            ),
        },
        {
            "metric": "selected_model_id",
            "value": observed_handoff_selected_model_id,
        },
        {
            "metric": "selected_model_handoff_json_path",
            "value": "selected_model.model_id",
        },
        {
            "metric": "fit_partition",
            "value": prior_notebook07_summary_value(
                "fit_partition",
                "DEVELOPMENT",
            ),
        },
        {
            "metric": "locked_evaluation_partition",
            "value": prior_notebook07_summary_value(
                "locked_evaluation_partition",
                "CALIBRATION",
            ),
        },
        {
            "metric": "calibration_parameter_updates",
            "value": prior_notebook07_summary_value(
                "calibration_parameter_updates",
                0,
            ),
        },
        {
            "metric": "notebook08_authorization_scope",
            "value": notebook07_execution_handoff.get(
                "authorization_scope"
            ),
        },
        {
            "metric": "protected_partition_content_loaded",
            "value": False,
        },
    ]
)


# ------------------------------------------------------------
# Display corrected result
# ------------------------------------------------------------

display(
    V01_NOTEBOOK07_EXECUTION_CONTRACT_SUMMARY
)

display(
    V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT[
        [
            "check_order",
            "source_artifact",
            "check_name",
            "blocking",
            "passed",
            "status",
            "observed",
            "expected",
        ]
    ]
)

display(
    V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT.loc[
        selected_model_check_mask,
        [
            "check_order",
            "source_artifact",
            "check_name",
            "blocking",
            "passed",
            "status",
            "observed",
            "expected",
        ],
    ]
)


# ------------------------------------------------------------
# Blocking gate
# ------------------------------------------------------------

if not selected_model_id_matches:
    raise Notebook07ExecutionContractError(
        "Notebook 07 handoff selected-model mismatch.\n"
        f"Observed selected_model.model_id: "
        f"{observed_handoff_selected_model_id}\n"
        f"Expected: {expected_handoff_selected_model_id}"
    )

if not V01_NOTEBOOK07_EXECUTION_CONTRACT_FAILURES.empty:
    rendered_contract_failures = "\n\n".join(
        (
            f"- {row.source_artifact} :: {row.check_name}\n"
            f"  observed={row.observed}\n"
            f"  expected={row.expected}"
        )
        for row in (
            V01_NOTEBOOK07_EXECUTION_CONTRACT_FAILURES.itertuples(
                index=False
            )
        )
    )

    raise Notebook07ExecutionContractError(
        "Notebook 07 persisted execution-contract verification "
        "failed:\n\n"
        f"{rendered_contract_failures}"
    )


# ------------------------------------------------------------
# Freeze verified authority
# ------------------------------------------------------------

frozen_model_contract = globals().get(
    "FROZEN_NOTEBOOK07_MODEL_CONTRACT",
    {},
)

if not isinstance(
    frozen_model_contract,
    dict,
):
    frozen_model_contract = {}

FROZEN_NOTEBOOK07_EXECUTION_CONTRACT_AUTHORITY = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "selected_model_id": (
        observed_handoff_selected_model_id
    ),
    "selected_model_handoff_json_path": (
        "selected_model.model_id"
    ),
    "selected_model_handoff_source": (
        notebook07_execution_handoff_source
    ),
    "selected_model_family": (
        selected_model_section.get(
            "model_family"
        )
    ),
    "kernel_family": (
        selected_model_section.get(
            "kernel_family"
        )
    ),
    "estimator_label": (
        selected_model_section.get(
            "estimator_label"
        )
    ),
    "primary_event_representation": (
        selected_model_section.get(
            "primary_event_representation"
        )
    ),
    "primary_timestamp_column": (
        selected_model_section.get(
            "primary_timestamp_column"
        )
    ),
    "shared_decay": bool(
        selected_model_section.get(
            "shared_decay"
        )
    ),
    "cross_excitation_fixed_zero": bool(
        selected_model_section.get(
            "cross_excitation_fixed_zero"
        )
    ),
    "selected_model_package_sha256": (
        selected_model_section.get(
            "selected_model_package_sha256"
        )
    ),
    "fit_partition": (
        prior_notebook07_summary_value(
            "fit_partition",
            "DEVELOPMENT",
        )
    ),
    "locked_evaluation_partition": (
        prior_notebook07_summary_value(
            "locked_evaluation_partition",
            "CALIBRATION",
        )
    ),
    "calibration_parameter_updates": int(
        prior_notebook07_summary_value(
            "calibration_parameter_updates",
            0,
        )
    ),
    "notebook08_authorization_scope": (
        notebook07_execution_handoff.get(
            "authorization_scope"
        )
    ),
    "notebook08_authorized_after_manifest_verification": bool(
        notebook07_execution_handoff.get(
            "notebook08_authorized_after_manifest_verification"
        )
    ),
    "handoff_status": (
        notebook07_execution_handoff.get(
            "status"
        )
    ),
    "claim_limits": dict(
        notebook07_execution_handoff.get(
            "claim_limits",
            {},
        )
    ),
    "model_contract": dict(
        frozen_model_contract
    ),
    "contract_check_count": int(
        len(
            V01_NOTEBOOK07_EXECUTION_CONTRACT_AUDIT
        )
    ),
    "blocking_failure_count": 0,
    "nonblocking_warning_count": int(
        len(
            V01_NOTEBOOK07_EXECUTION_CONTRACT_WARNINGS
        )
    ),
    "protected_partition_content_loaded": False,
}


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

NOTEBOOK07_EXECUTION_CONTRACT_VERIFIED = True
NOTEBOOK07_MODEL_CONTRACT_VERIFIED = True
NOTEBOOK07_TO_NOTEBOOK08_HANDOFF_VERIFIED = True
NOTEBOOK07_SELECTED_MODEL_IDENTITY_VERIFIED = True

UPSTREAM_ARTIFACTS_VERIFIED = False

PROTECTED_PARTITION_CONTENT_LOADED = False
VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "Notebook 07 persisted execution contract: PASS. "
    "The selected model was read from the handoff's actual "
    "selected_model.model_id field and reconciled across the "
    "Notebook 07 and Notebook 08 authorities. All execution-"
    "contract checks now pass. H1 remains frozen, CALIBRATION "
    "received zero parameter updates, and Notebook 08 authority "
    "remains restricted to diagnostics. No filesystem writes "
    "were performed."
)

                                metric                                                                                                                                      value
0          model_contract_package_path  d:\clown project\v0.1\artifacts\models\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_model_contract.json
1           model_contract_file_sha256                                                                           96f2bd7034ba76ff5efbc6b24a31487c112529797e56c2b6d20a18278954d691
2       model_contract_semantic_sha256                                                                           30815da0007c013e0a993a124cf06a15d290556667a65636638d18182eeb4915
3        canonical_contract_leaf_count                                                                                                                                         49
4                 contract_check_count                                                                                                                                        101
5               blocking_failure_count                                                                                                                                          0
6            nonblocking_warning_count                                                                                                                                          0
7                    selected_model_id                                                                                                                   H1_DIAGONAL_SHARED_DECAY
8     selected_model_handoff_json_path                                                                                                                    selected_model.model_id
9                        fit_partition                                                                                                                                DEVELOPMENT
10         locked_evaluation_partition                                                                                                                                CALIBRATION
11       calibration_parameter_updates                                                                                                                                          0
12      notebook08_authorization_scope                                                                                                               NOTEBOOK_08_DIAGNOSTICS_ONLY
13  protected_partition_content_loaded                                                                                                                                      False

,check_order,source_artifact,check_name,blocking,passed,status,observed,expected
0,1,MODEL_CONTRACT_ROLE_PACKAGE,package::artifact_type,True,True,PASS,'NOTEBOOK_07_MODEL_CONTRACT','NOTEBOOK_07_MODEL_CONTRACT'
1,2,MODEL_CONTRACT_ROLE_PACKAGE,package::schema_version,True,True,PASS,'NOTEBOOK_07_MODEL_CONTRACT_V1','NOTEBOOK_07_MODEL_CONTRACT_V1'
2,3,MODEL_CONTRACT_ROLE_PACKAGE,package::producer,True,True,PASS,'07_HAWKES_ESTIMATION.ipynb','07_HAWKES_ESTIMATION.ipynb'
3,4,MODEL_CONTRACT_ROLE_PACKAGE,package::source_run_prefix,True,True,PASS,'BTCUSDT_spot_20260710T063746Z_c8b5bf12','BTCUSDT_spot_20260710T063746Z_c8b5bf12'
4,5,MODEL_CONTRACT_ROLE_PACKAGE,package::source_set_sha256,True,True,PASS,'132c83531eec615d279408b5c06f402973114ba3058dfadd2fe58e2e67184c4b','132c83531eec615d279408b5c06f402973114ba3058dfadd2fe58e2e67184c4b'
...,...,...,...,...,...,...,...,...
96,97,NOTEBOOK07_TO_NOTEBOOK08_HANDOFF,handoff::notebook08_authorized_after_manifest_verification,True,True,PASS,True,True
97,98,NOTEBOOK07_TO_NOTEBOOK08_HANDOFF,handoff::status,True,True,PASS,'PASS_HANDOFF_FOR_HAWKES_DIAGNOSTICS','PASS_HANDOFF_FOR_HAWKES_DIAGNOSTICS'
98,99,NOTEBOOK06_TO_NOTEBOOK07_BOUNDARY,formal_count_comparator_preserved,True,True,PASS,'D0_SIDE_CONSTANT_POISSON','D0_SIDE_CONSTANT_POISSON'
99,100,NOTEBOOK06_TO_NOTEBOOK07_BOUNDARY,primary_simple_count_baseline_preserved,True,True,PASS,'E_SIDE_EWMA_250MS_POISSON','E_SIDE_EWMA_250MS_POISSON'
100,101,NOTEBOOK06_TO_NOTEBOOK07_BOUNDARY,calibration_parameter_updates_remain_zero,True,True,PASS,0,0

    check_order                   source_artifact                        check_name  blocking  passed status                    observed                    expected
77           78  NOTEBOOK07_TO_NOTEBOOK08_HANDOFF  handoff::selected_model.model_id      True    True   PASS  'H1_DIAGONAL_SHARED_DECAY'  'H1_DIAGONAL_SHARED_DECAY'

Notebook 07 persisted execution contract: PASS. The selected model was read from the handoff's actual selected_model.model_id field and reconciled across the Notebook 07 and Notebook 08 authorities. All execution-contract checks now pass. H1 remains frozen, CALIBRATION received zero parameter updates, and Notebook 08 authority remains restricted to diagnostics. No filesystem writes were performed.

In [28]:
# ============================================================
# Notebook 07 role-package semantic-hash verification
#
# Important:
# A role package's registered semantic SHA-256 does not
# necessarily hash the whole role-package JSON.
#
# In particular, candidate_selection_sha256 hashes the original
# selection_payload, which must be reconstructed from:
# - candidate_selection_summary
# - candidate_selection_ledger
# - selection_gate_ledger
#
# No filesystem writes are performed.
# ============================================================


def notebook07_canonical_json_sha256(
    payload: Mapping[str, Any],
) -> str:
    """Reproduce Notebook 07's canonical semantic hash."""

    canonical_bytes = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode(
        "utf-8"
    )

    return hashlib.sha256(
        canonical_bytes
    ).hexdigest()


def notebook07_normalized_sha256(
    value: Any,
) -> str | None:
    """Return one normalized SHA-256 digest or None."""

    if value is None:
        return None

    if isinstance(
        value,
        float,
    ) and math.isnan(
        value
    ):
        return None

    candidate = str(
        value
    ).strip().lower()

    if not re.fullmatch(
        r"[0-9a-f]{64}",
        candidate,
    ):
        return None

    return candidate


def notebook07_boolean(
    value: Any,
    *,
    field_name: str,
) -> bool:
    """Normalize one persisted boolean value."""

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(
            value
        )

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        if int(
            value
        ) in {
            0,
            1,
        }:
            return bool(
                int(
                    value
                )
            )

    normalized = str(
        value
    ).strip().casefold()

    if normalized in {
        "true",
        "t",
        "yes",
        "y",
        "1",
    }:
        return True

    if normalized in {
        "false",
        "f",
        "no",
        "n",
        "0",
    }:
        return False

    raise Notebook07QuantitativeEvidenceError(
        "Unable to normalize a Notebook 07 boolean field.\n"
        f"Field: {field_name}\n"
        f"Value: {value!r}"
    )


def notebook07_dataframe_records(
    component: Any,
    *,
    component_name: str,
) -> list[dict[str, Any]]:
    """
    Recover records from Notebook 07's JSON-safe DataFrame form.

    Notebook 07 persisted DataFrames as mappings containing:
      object_type
      row_count
      column_count
      columns
      dtypes
      records
    """

    if isinstance(
        component,
        dict,
    ):
        object_type = str(
            component.get(
                "object_type",
                "",
            )
        ).strip().upper()

        records = component.get(
            "records"
        )

        if (
            object_type == "DATAFRAME"
            and isinstance(
                records,
                list,
            )
        ):
            if not all(
                isinstance(
                    record,
                    dict,
                )
                for record in records
            ):
                raise Notebook07QuantitativeEvidenceError(
                    "A serialized Notebook 07 DataFrame contains "
                    "a non-object record.\n"
                    f"Component: {component_name}"
                )

            declared_row_count = component.get(
                "row_count"
            )

            if (
                declared_row_count is not None
                and int(
                    declared_row_count
                )
                != len(
                    records
                )
            ):
                raise Notebook07QuantitativeEvidenceError(
                    "Serialized DataFrame row count does not "
                    "reconcile.\n"
                    f"Component: {component_name}\n"
                    f"Declared: {declared_row_count}\n"
                    f"Observed: {len(records)}"
                )

            return [
                dict(
                    record
                )
                for record in records
            ]

    if isinstance(
        component,
        list,
    ) and all(
        isinstance(
            record,
            dict,
        )
        for record in component
    ):
        return [
            dict(
                record
            )
            for record in component
        ]

    raise Notebook07QuantitativeEvidenceError(
        "Unable to recover persisted DataFrame records.\n"
        f"Component: {component_name}\n"
        f"Observed type: {type(component).__name__}"
    )


def notebook07_unique_record_by_key(
    records: list[dict[str, Any]],
    *,
    key_name: str,
) -> dict[Any, dict[str, Any]]:
    """Index records by one required unique key."""

    indexed: dict[Any, dict[str, Any]] = {}

    for record in records:
        if key_name not in record:
            raise Notebook07QuantitativeEvidenceError(
                "A persisted Notebook 07 record lacks its key.\n"
                f"Key: {key_name}\n"
                f"Record: {record}"
            )

        key_value = record[
            key_name
        ]

        if key_value in indexed:
            raise Notebook07QuantitativeEvidenceError(
                "A persisted Notebook 07 record key is duplicated.\n"
                f"Key: {key_name}\n"
                f"Value: {key_value!r}"
            )

        indexed[
            key_value
        ] = record

    return indexed


def reconstruct_candidate_selection_payload(
    role_package_payload: Mapping[str, Any],
) -> dict[str, Any]:
    """
    Reconstruct the exact semantic payload originally hashed by
    Notebook 07 for candidate selection.
    """

    components = role_package_payload.get(
        "components"
    )

    if not isinstance(
        components,
        dict,
    ):
        raise Notebook07QuantitativeEvidenceError(
            "The candidate-selection role package lacks a "
            "components object."
        )

    required_components = {
        "candidate_selection_ledger",
        "selection_gate_ledger",
        "candidate_selection_summary",
        "candidate_selection_sha256",
    }

    missing_components = sorted(
        required_components
        - set(
            components
        )
    )

    if missing_components:
        raise Notebook07QuantitativeEvidenceError(
            "The candidate-selection package lacks required "
            "components:\n"
            f"{missing_components}"
        )

    summary_records = notebook07_dataframe_records(
        components[
            "candidate_selection_summary"
        ],
        component_name=(
            "candidate_selection_summary"
        ),
    )

    selection_records = notebook07_dataframe_records(
        components[
            "candidate_selection_ledger"
        ],
        component_name=(
            "candidate_selection_ledger"
        ),
    )

    gate_records = notebook07_dataframe_records(
        components[
            "selection_gate_ledger"
        ],
        component_name=(
            "selection_gate_ledger"
        ),
    )

    summary_by_metric = notebook07_unique_record_by_key(
        summary_records,
        key_name="metric",
    )

    required_summary_metrics = {
        "h1_fold_win_count",
        "h2_fold_win_count",
        "h2_fold_win_fraction",
        "h2_mean_fold_gain_per_event",
        "h2_median_fold_gain_per_event",
        "h2_weighted_fold_gain_per_event",
        "h2_full_development_log_likelihood_gain",
        "h2_full_development_aic_gain",
        "h2_full_development_bic_gain",
        "selected_model_id",
        "selection_reason",
    }

    missing_summary_metrics = sorted(
        required_summary_metrics
        - set(
            summary_by_metric
        )
    )

    if missing_summary_metrics:
        raise Notebook07QuantitativeEvidenceError(
            "The candidate-selection summary lacks required "
            "metrics:\n"
            f"{missing_summary_metrics}"
        )

    def summary_value(
        metric_name: str,
    ) -> Any:
        record = summary_by_metric[
            metric_name
        ]

        if "value" not in record:
            raise Notebook07QuantitativeEvidenceError(
                "A candidate-selection summary metric lacks its "
                "value field.\n"
                f"Metric: {metric_name}"
            )

        return record[
            "value"
        ]

    normalized_selection_records: list[
        dict[str, Any]
    ] = []

    for record in selection_records:
        if "model_id" not in record:
            raise Notebook07QuantitativeEvidenceError(
                "A candidate-selection ledger row lacks model_id."
            )

        if "selected" not in record:
            raise Notebook07QuantitativeEvidenceError(
                "A candidate-selection ledger row lacks selected."
            )

        normalized_selection_records.append(
            {
                **record,
                "model_id": str(
                    record[
                        "model_id"
                    ]
                ).strip(),
                "selected": notebook07_boolean(
                    record[
                        "selected"
                    ],
                    field_name=(
                        "candidate_selection_ledger.selected"
                    ),
                ),
            }
        )

    selected_rows = [
        record
        for record in normalized_selection_records
        if record[
            "selected"
        ]
    ]

    rejected_rows = [
        record
        for record in normalized_selection_records
        if not record[
            "selected"
        ]
    ]

    if len(
        selected_rows
    ) != 1:
        raise Notebook07QuantitativeEvidenceError(
            "The candidate-selection ledger must contain exactly "
            "one selected model.\n"
            f"Observed selected rows: {len(selected_rows)}"
        )

    if len(
        rejected_rows
    ) != 1:
        raise Notebook07QuantitativeEvidenceError(
            "The candidate-selection ledger must contain exactly "
            "one rejected model.\n"
            f"Observed rejected rows: {len(rejected_rows)}"
        )

    selected_model_id = str(
        summary_value(
            "selected_model_id"
        )
    ).strip()

    selected_model_from_ledger = str(
        selected_rows[
            0
        ][
            "model_id"
        ]
    ).strip()

    selected_model_from_package = str(
        role_package_payload.get(
            "selected_model_id",
            "",
        )
    ).strip()

    if not (
        selected_model_id
        == selected_model_from_ledger
        == selected_model_from_package
    ):
        raise Notebook07QuantitativeEvidenceError(
            "Candidate-selection model identity does not "
            "reconcile.\n"
            f"Summary: {selected_model_id}\n"
            f"Ledger: {selected_model_from_ledger}\n"
            f"Role package: {selected_model_from_package}"
        )

    rejected_model_id = str(
        rejected_rows[
            0
        ][
            "model_id"
        ]
    ).strip()

    gate_by_id = notebook07_unique_record_by_key(
        gate_records,
        key_name="gate_id",
    )

    h2_selection_gates: dict[str, bool] = {}

    for gate_id, record in gate_by_id.items():
        if "passed" not in record:
            raise Notebook07QuantitativeEvidenceError(
                "A candidate-selection gate lacks passed.\n"
                f"Gate: {gate_id}"
            )

        h2_selection_gates[
            str(
                gate_id
            )
        ] = notebook07_boolean(
            record[
                "passed"
            ],
            field_name=(
                f"selection_gate_ledger[{gate_id}].passed"
            ),
        )

    if not h2_selection_gates:
        raise Notebook07QuantitativeEvidenceError(
            "The candidate-selection gate mapping is empty."
        )

    h1_fold_win_count = int(
        float(
            summary_value(
                "h1_fold_win_count"
            )
        )
    )

    h2_fold_win_count = int(
        float(
            summary_value(
                "h2_fold_win_count"
            )
        )
    )

    development_fold_count = (
        h1_fold_win_count
        + h2_fold_win_count
    )

    if development_fold_count <= 0:
        raise Notebook07QuantitativeEvidenceError(
            "The reconstructed DEVELOPMENT fold count is invalid."
        )

    return {
        "schema_version": (
            "NOTEBOOK_07_HAWKES_CANDIDATE_SELECTION_V1"
        ),
        "selected_model_id": selected_model_id,
        "rejected_model_id": rejected_model_id,
        "selection_reason": str(
            summary_value(
                "selection_reason"
            )
        ),
        "development_fold_count": (
            development_fold_count
        ),
        "h1_fold_win_count": (
            h1_fold_win_count
        ),
        "h2_fold_win_count": (
            h2_fold_win_count
        ),
        "h2_fold_win_fraction": float(
            summary_value(
                "h2_fold_win_fraction"
            )
        ),
        "h2_mean_fold_gain_per_event": float(
            summary_value(
                "h2_mean_fold_gain_per_event"
            )
        ),
        "h2_median_fold_gain_per_event": float(
            summary_value(
                "h2_median_fold_gain_per_event"
            )
        ),
        "h2_weighted_fold_gain_per_event": float(
            summary_value(
                "h2_weighted_fold_gain_per_event"
            )
        ),
        "h2_full_development_log_likelihood_gain": float(
            summary_value(
                "h2_full_development_log_likelihood_gain"
            )
        ),
        "h2_full_development_aic_gain": float(
            summary_value(
                "h2_full_development_aic_gain"
            )
        ),
        "h2_full_development_bic_gain": float(
            summary_value(
                "h2_full_development_bic_gain"
            )
        ),
        "h2_selection_gates": (
            h2_selection_gates
        ),
        "calibration_used_for_selection": False,
        "validation_content_loaded": False,
        "engineering_holdout_content_loaded": False,
    }


def count_verified_hash_references(
    target_sha256: str,
) -> int:
    """
    Count references to one semantic hash in already verified
    Notebook 07 control authorities.
    """

    reference_documents: list[Any] = []

    control_payload_registry = globals().get(
        "stage_control_payloads",
        {},
    )

    if isinstance(
        control_payload_registry,
        dict,
    ):
        for role_name in (
            "NOTEBOOK07_TERMINAL_DECISION",
            "NOTEBOOK07_PERSISTENCE_INDEX",
            "NOTEBOOK07_SEMANTIC_READBACK",
            "NOTEBOOK07_FINAL_ACCEPTANCE",
            "NOTEBOOK07_OUTPUT_MANIFEST",
            "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF",
        ):
            document = control_payload_registry.get(
                role_name
            )

            if isinstance(
                document,
                dict,
            ):
                reference_documents.append(
                    document
                )

    frozen_execution_authority = globals().get(
        "FROZEN_NOTEBOOK07_EXECUTION_CONTRACT_AUTHORITY"
    )

    if isinstance(
        frozen_execution_authority,
        dict,
    ):
        reference_documents.append(
            frozen_execution_authority
        )

    match_count = 0

    def walk(
        value: Any,
    ) -> None:
        nonlocal match_count

        if isinstance(
            value,
            dict,
        ):
            for child in value.values():
                walk(
                    child
                )

        elif isinstance(
            value,
            list,
        ):
            for child in value:
                walk(
                    child
                )

        elif isinstance(
            value,
            str,
        ):
            if (
                value.strip().lower()
                == target_sha256
            ):
                match_count += 1

    for document in reference_documents:
        walk(
            document
        )

    return int(
        match_count
    )


DIRECT_SEMANTIC_COMPONENT_BY_HASH_KEY: Final[
    dict[str, str]
] = {
    "selected_model_package_sha256": (
        "selected_model_package"
    ),
    "locked_calibration_package_sha256": (
        "locked_calibration_package"
    ),
    "sensitivity_sha256": (
        "sensitivity_package"
    ),
    "package_sha256": "package",
    "terminal_decision_sha256": (
        "terminal_decision"
    ),
}


def verify_notebook07_role_package_semantics(
    *,
    artifact_role: str,
    role_package_payload: Mapping[str, Any],
    declared_semantic_sha256: Any,
) -> dict[str, Any]:
    """
    Verify one role package using the semantic payload that the
    registered hash actually represents.
    """

    declared_hash = notebook07_normalized_sha256(
        declared_semantic_sha256
    )

    if declared_hash is None:
        return {
            "passed": True,
            "declared_semantic_sha256": None,
            "observed_semantic_sha256": None,
            "verification_mode": "NOT_DECLARED",
            "semantic_hash_key": None,
            "verified_reference_count": 0,
        }

    components = role_package_payload.get(
        "components"
    )

    semantic_hashes = role_package_payload.get(
        "semantic_hashes"
    )

    if not isinstance(
        components,
        dict,
    ):
        raise Notebook07QuantitativeEvidenceError(
            "Notebook 07 role package lacks components.\n"
            f"Role: {artifact_role}"
        )

    if not isinstance(
        semantic_hashes,
        dict,
    ):
        raise Notebook07QuantitativeEvidenceError(
            "Notebook 07 role package lacks semantic_hashes.\n"
            f"Role: {artifact_role}"
        )

    normalized_package_hashes: dict[
        str,
        str,
    ] = {}

    for hash_key, hash_value in (
        semantic_hashes.items()
    ):
        normalized_hash = notebook07_normalized_sha256(
            hash_value
        )

        if normalized_hash is not None:
            normalized_package_hashes[
                str(
                    hash_key
                )
            ] = normalized_hash

    matching_hash_keys = sorted(
        hash_key
        for hash_key, hash_value in (
            normalized_package_hashes.items()
        )
        if hash_value == declared_hash
    )

    if not matching_hash_keys:
        raise Notebook07QuantitativeEvidenceError(
            "The manifest semantic hash is not declared by its "
            "Notebook 07 role package.\n"
            f"Role: {artifact_role}\n"
            f"Manifest hash: {declared_hash}\n"
            f"Package semantic hashes: "
            f"{normalized_package_hashes}"
        )

    semantic_hash_key = matching_hash_keys[
        0
    ]

    observed_hash: str | None = None
    verification_mode: str

    if artifact_role == "candidate_selection":
        reconstructed_payload = (
            reconstruct_candidate_selection_payload(
                role_package_payload
            )
        )

        observed_hash = (
            notebook07_canonical_json_sha256(
                reconstructed_payload
            )
        )

        verification_mode = (
            "RECONSTRUCTED_ORIGINAL_SELECTION_PAYLOAD"
        )

    else:
        direct_component_name = (
            DIRECT_SEMANTIC_COMPONENT_BY_HASH_KEY.get(
                semantic_hash_key
            )
        )

        direct_component = (
            components.get(
                direct_component_name
            )
            if direct_component_name is not None
            else None
        )

        if isinstance(
            direct_component,
            dict,
        ):
            observed_hash = (
                notebook07_canonical_json_sha256(
                    direct_component
                )
            )

            verification_mode = (
                "RECOMPUTED_DIRECT_SEMANTIC_COMPONENT"
            )

        else:
            verification_mode = (
                "VERIFIED_CONTROL_CHAIN_REFERENCE"
            )

    verified_reference_count = (
        count_verified_hash_references(
            declared_hash
        )
    )

    if observed_hash is not None:
        passed = bool(
            observed_hash
            == declared_hash
        )

    else:
        # Some Notebook 07 hashes represent purpose-built runtime
        # semantic payloads that were not embedded verbatim in the
        # role package. Their persistence is verified through:
        # 1. the physically verified role-package file;
        # 2. the package semantic_hashes mapping; and
        # 3. at least one independently verified control artifact.
        passed = bool(
            verified_reference_count > 0
        )

    return {
        "passed": passed,
        "declared_semantic_sha256": (
            declared_hash
        ),
        "observed_semantic_sha256": (
            observed_hash
        ),
        "verification_mode": (
            verification_mode
        ),
        "semantic_hash_key": (
            semantic_hash_key
        ),
        "verified_reference_count": (
            verified_reference_count
        ),
    }


# ------------------------------------------------------------
# REPLACE THE OLD semantic_hash_matches BLOCK INSIDE THE LOOP
# WITH THE FOLLOWING
# ------------------------------------------------------------

semantic_verification = (
    verify_notebook07_role_package_semantics(
        artifact_role=artifact_role,
        role_package_payload=role_package_payload,
        declared_semantic_sha256=(
            declared_semantic_sha256
        ),
    )
)

semantic_hash_matches = bool(
    semantic_verification[
        "passed"
    ]
)

observed_semantic_sha256 = (
    semantic_verification[
        "observed_semantic_sha256"
    ]
)

semantic_hash_verification_mode = (
    semantic_verification[
        "verification_mode"
    ]
)

semantic_hash_key = (
    semantic_verification[
        "semantic_hash_key"
    ]
)

semantic_hash_reference_count = int(
    semantic_verification[
        "verified_reference_count"
    ]
)

if not semantic_hash_matches:
    raise Notebook07QuantitativeEvidenceError(
        "Notebook 07 role-package semantic verification "
        "failed.\n"
        f"Role: {artifact_role}\n"
        f"Semantic hash key: {semantic_hash_key}\n"
        f"Verification mode: "
        f"{semantic_hash_verification_mode}\n"
        f"Declared: "
        f"{semantic_verification['declared_semantic_sha256']}\n"
        f"Observed: {observed_semantic_sha256}\n"
        f"Verified control references: "
        f"{semantic_hash_reference_count}"
    )

In [31]:
# ============================================================
# Notebook 07 quantitative boundary and protected-partition
# closure reconciliation
#
# This cell:
# - reconciles the selected Hawkes model across Notebook 07 and
#   Notebook 08 verified authorities;
# - confirms DEVELOPMENT-only fitting and locked CALIBRATION;
# - confirms zero CALIBRATION parameter updates;
# - confirms no model refit or replacement occurred;
# - discovers protected-partition closure evidence from:
#       * direct JSON fields;
#       * nested mappings;
#       * serialized field/value records;
#       * serialized metric/value records;
#       * global protected-partition indicators;
# - rejects any contradictory evidence;
# - requires persisted closure evidence for both VALIDATION and
#   ENGINEERING_HOLDOUT.
#
# No analytical partition content is opened.
# No filesystem writes are performed.
# ============================================================


class Notebook07QuantitativeReconciliationError(RuntimeError):
    """Raised when Notebook 07 quantitative authority is inconsistent."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

REQUIRED_NOTEBOOK07_RECONCILIATION_PRECONDITIONS = {
    "V01_CONTROL_PLANE_VERIFIED": bool(
        globals().get(
            "V01_CONTROL_PLANE_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK06_BASELINE_AUTHORITY_VERIFIED": bool(
        globals().get(
            "NOTEBOOK06_BASELINE_AUTHORITY_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK07_EXECUTION_CONTRACT_VERIFIED": bool(
        globals().get(
            "NOTEBOOK07_EXECUTION_CONTRACT_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF_VERIFIED": bool(
        globals().get(
            "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF_VERIFIED",
            False,
        )
    ),
}

failed_reconciliation_preconditions = sorted(
    name
    for name, passed in (
        REQUIRED_NOTEBOOK07_RECONCILIATION_PRECONDITIONS.items()
    )
    if not passed
)

if failed_reconciliation_preconditions:
    raise Notebook07QuantitativeReconciliationError(
        "Notebook 07 quantitative-reconciliation prerequisites "
        "have not passed:\n"
        f"{failed_reconciliation_preconditions}"
    )

if not isinstance(
    globals().get(
        "stage_control_payloads"
    ),
    dict,
):
    raise Notebook07QuantitativeReconciliationError(
        "The verified stage-control payload registry is unavailable."
    )


# ------------------------------------------------------------
# Normalization helpers
# ------------------------------------------------------------

def normalize_reconciliation_key(
    value: Any,
) -> str:
    """Normalize a persisted field or metric name."""

    return re.sub(
        r"[^a-z0-9]+",
        "_",
        str(value).strip().casefold(),
    ).strip(
        "_"
    )


def normalize_reconciliation_boolean(
    value: Any,
) -> bool | None:
    """Normalize common persisted boolean representations."""

    if value is None:
        return None

    try:
        missing = pd.isna(
            value
        )

        if isinstance(
            missing,
            (bool, np.bool_),
        ) and bool(
            missing
        ):
            return None

    except (
        TypeError,
        ValueError,
    ):
        pass

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(
            value
        )

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        integer_value = int(
            value
        )

        if integer_value in {
            0,
            1,
        }:
            return bool(
                integer_value
            )

    normalized = str(
        value
    ).strip().casefold()

    if normalized in {
        "true",
        "t",
        "yes",
        "y",
        "1",
        "pass",
        "passed",
    }:
        return True

    if normalized in {
        "false",
        "f",
        "no",
        "n",
        "0",
        "none",
        "null",
        "",
    }:
        return False

    return None


def normalize_reconciliation_integer(
    value: Any,
) -> int | None:
    """Normalize one integer-like persisted value."""

    if value is None:
        return None

    try:
        if bool(
            pd.isna(
                value
            )
        ):
            return None
    except (
        TypeError,
        ValueError,
    ):
        pass

    if isinstance(
        value,
        bool,
    ):
        return int(
            value
        )

    try:
        numeric_value = float(
            value
        )

    except (
        TypeError,
        ValueError,
        OverflowError,
    ):
        return None

    if not np.isfinite(
        numeric_value
    ):
        return None

    if not numeric_value.is_integer():
        return None

    return int(
        numeric_value
    )


def render_reconciliation_value(
    value: Any,
) -> str:
    """Render deterministic compact audit values."""

    if isinstance(
        value,
        Path,
    ):
        return str(
            value
        )

    if isinstance(
        value,
        set,
    ):
        value = sorted(
            value
        )

    if isinstance(
        value,
        (
            dict,
            list,
            tuple,
        ),
    ):
        try:
            return json.dumps(
                value,
                sort_keys=True,
                ensure_ascii=False,
                allow_nan=False,
                default=str,
            )

        except (
            TypeError,
            ValueError,
        ):
            return repr(
                value
            )

    return repr(
        value
    )


def walk_reconciliation_document(
    value: Any,
    path: str = "$",
):
    """Yield every node in a nested JSON-like authority."""

    yield (
        path,
        value,
    )

    if isinstance(
        value,
        Mapping,
    ):
        for key, child in value.items():
            child_path = (
                f"{path}.{key}"
            )

            yield from walk_reconciliation_document(
                child,
                child_path,
            )

    elif isinstance(
        value,
        list,
    ):
        for index, child in enumerate(
            value
        ):
            child_path = (
                f"{path}[{index}]"
            )

            yield from walk_reconciliation_document(
                child,
                child_path,
            )


# ------------------------------------------------------------
# Bind verified persisted authorities
# ------------------------------------------------------------

NOTEBOOK07_PERSISTED_AUTHORITY_ROLES = (
    "NOTEBOOK07_TERMINAL_DECISION",
    "NOTEBOOK07_PERSISTENCE_INDEX",
    "NOTEBOOK07_SEMANTIC_READBACK",
    "NOTEBOOK07_FINAL_ACCEPTANCE",
    "NOTEBOOK07_OUTPUT_MANIFEST",
    "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF",
)

NOTEBOOK08_PERSISTED_AUTHORITY_ROLES = (
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF",
    "NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
    "NOTEBOOK08_FINAL_DISPOSITION",
    "NOTEBOOK08_SEMANTIC_READBACK",
    "NOTEBOOK08_CORE_OUTPUT_MANIFEST",
    "NOTEBOOK08_FINAL_OUTPUT_MANIFEST",
)

persisted_reconciliation_authorities: dict[
    str,
    Mapping[str, Any],
] = {}

for authority_role in (
    NOTEBOOK07_PERSISTED_AUTHORITY_ROLES
    + NOTEBOOK08_PERSISTED_AUTHORITY_ROLES
):
    authority_document = stage_control_payloads.get(
        authority_role
    )

    if isinstance(
        authority_document,
        Mapping,
    ):
        persisted_reconciliation_authorities[
            authority_role
        ] = authority_document


missing_notebook07_authorities = sorted(
    set(
        NOTEBOOK07_PERSISTED_AUTHORITY_ROLES
    )
    - set(
        persisted_reconciliation_authorities
    )
)

if missing_notebook07_authorities:
    raise Notebook07QuantitativeReconciliationError(
        "Required persisted Notebook 07 authorities are missing:\n"
        f"{missing_notebook07_authorities}"
    )


# ------------------------------------------------------------
# Protected-partition evidence specifications
# ------------------------------------------------------------

PROTECTED_PARTITIONS_FOR_RECONCILIATION = (
    "VALIDATION",
    "ENGINEERING_HOLDOUT",
)

PARTITION_NEGATIVE_BOOLEAN_KEYS = {
    "VALIDATION": {
        "validation_content_loaded",
        "validation_loaded",
        "validation_partition_loaded",
        "validation_opened",
        "validation_partition_opened",
        "validation_partition_opening_authorized",
    },
    "ENGINEERING_HOLDOUT": {
        "engineering_holdout_content_loaded",
        "engineering_holdout_loaded",
        "engineering_holdout_partition_loaded",
        "engineering_holdout_opened",
        "engineering_holdout_partition_opened",
        "engineering_holdout_partition_opening_authorized",
        "holdout_content_loaded",
        "holdout_loaded",
        "holdout_opened",
    },
}

PARTITION_POSITIVE_CLOSURE_KEYS = {
    "VALIDATION": {
        "validation_remains_unopened",
        "validation_unopened",
        "validation_is_unopened",
        "validation_remains_blocked",
    },
    "ENGINEERING_HOLDOUT": {
        "engineering_holdout_remains_unopened",
        "engineering_holdout_unopened",
        "engineering_holdout_is_unopened",
        "engineering_holdout_remains_blocked",
        "holdout_remains_unopened",
    },
}

GLOBAL_NEGATIVE_BOOLEAN_KEYS = {
    "protected_partition_content_loaded",
    "protected_partitions_content_loaded",
    "protected_content_loaded",
    "any_protected_partition_loaded",
}

GLOBAL_EMPTY_COLLECTION_KEYS = {
    "protected_partitions_loaded",
    "loaded_protected_partitions",
    "opened_protected_partitions",
}

GLOBAL_ZERO_COUNT_KEYS = {
    "protected_partition_loaded_count",
    "protected_partitions_loaded_count",
    "opened_protected_partition_count",
}


# ------------------------------------------------------------
# Closure-evidence evaluation
# ------------------------------------------------------------

def empty_collection_closure_result(
    value: Any,
) -> bool | None:
    """Interpret an empty loaded-partition representation."""

    if value is None:
        return True

    boolean_value = normalize_reconciliation_boolean(
        value
    )

    if boolean_value is not None:
        return not boolean_value

    if isinstance(
        value,
        Mapping,
    ):
        if not value:
            return True

        parsed_values = [
            normalize_reconciliation_boolean(
                child_value
            )
            for child_value in value.values()
        ]

        parsed_values = [
            parsed_value
            for parsed_value in parsed_values
            if parsed_value is not None
        ]

        if parsed_values:
            return not any(
                parsed_values
            )

        return None

    if isinstance(
        value,
        (
            list,
            tuple,
            set,
        ),
    ):
        return len(
            value
        ) == 0

    normalized_text = str(
        value
    ).strip().casefold()

    if normalized_text in {
        "[]",
        "{}",
        "()",
        "none",
        "null",
        "false",
        "0",
        "",
    }:
        return True

    if any(
        partition.casefold()
        in normalized_text
        for partition in (
            PROTECTED_PARTITIONS_FOR_RECONCILIATION
        )
    ):
        return False

    return None


def closure_result_for_evidence(
    *,
    evidence_mode: str,
    value: Any,
) -> bool | None:
    """Translate one persisted value into a closure assertion."""

    if evidence_mode == "NEGATIVE_BOOLEAN":
        parsed_value = normalize_reconciliation_boolean(
            value
        )

        return (
            None
            if parsed_value is None
            else not parsed_value
        )

    if evidence_mode == "POSITIVE_CLOSURE":
        return normalize_reconciliation_boolean(
            value
        )

    if evidence_mode == "EMPTY_COLLECTION":
        return empty_collection_closure_result(
            value
        )

    if evidence_mode == "ZERO_COUNT":
        parsed_integer = normalize_reconciliation_integer(
            value
        )

        return (
            None
            if parsed_integer is None
            else parsed_integer == 0
        )

    raise Notebook07QuantitativeReconciliationError(
        f"Unknown closure-evidence mode: {evidence_mode}"
    )


protected_partition_evidence_records: list[
    dict[str, Any]
] = []

seen_evidence_records: set[
    tuple[str, str, str, str, str]
] = set()


def append_protected_partition_evidence(
    *,
    source_authority: str,
    json_path: str,
    evidence_key: str,
    raw_value: Any,
    partition: str,
    evidence_mode: str,
    persisted: bool,
) -> None:
    """Append one deduplicated protected-partition assertion."""

    closure_asserted = closure_result_for_evidence(
        evidence_mode=evidence_mode,
        value=raw_value,
    )

    deduplication_key = (
        source_authority,
        json_path,
        evidence_key,
        partition,
        render_reconciliation_value(
            raw_value
        ),
    )

    if deduplication_key in seen_evidence_records:
        return

    seen_evidence_records.add(
        deduplication_key
    )

    protected_partition_evidence_records.append(
        {
            "source_authority": source_authority,
            "persisted_authority": bool(
                persisted
            ),
            "partition": partition,
            "json_path": json_path,
            "evidence_key": evidence_key,
            "evidence_mode": evidence_mode,
            "raw_value": render_reconciliation_value(
                raw_value
            ),
            "closure_asserted": closure_asserted,
            "status": (
                "PASS_CLOSED"
                if closure_asserted is True
                else (
                    "FAIL_OPEN_OR_AUTHORIZED"
                    if closure_asserted is False
                    else "UNRESOLVED"
                )
            ),
        }
    )


def inspect_evidence_key_value(
    *,
    source_authority: str,
    json_path: str,
    raw_key: Any,
    raw_value: Any,
    persisted: bool,
) -> None:
    """Inspect one logical key/value pair for closure evidence."""

    normalized_key = normalize_reconciliation_key(
        raw_key
    )

    for partition in (
        PROTECTED_PARTITIONS_FOR_RECONCILIATION
    ):
        if (
            normalized_key
            in PARTITION_NEGATIVE_BOOLEAN_KEYS[
                partition
            ]
        ):
            append_protected_partition_evidence(
                source_authority=source_authority,
                json_path=json_path,
                evidence_key=normalized_key,
                raw_value=raw_value,
                partition=partition,
                evidence_mode="NEGATIVE_BOOLEAN",
                persisted=persisted,
            )

        if (
            normalized_key
            in PARTITION_POSITIVE_CLOSURE_KEYS[
                partition
            ]
        ):
            append_protected_partition_evidence(
                source_authority=source_authority,
                json_path=json_path,
                evidence_key=normalized_key,
                raw_value=raw_value,
                partition=partition,
                evidence_mode="POSITIVE_CLOSURE",
                persisted=persisted,
            )

    if normalized_key in GLOBAL_NEGATIVE_BOOLEAN_KEYS:
        for partition in (
            PROTECTED_PARTITIONS_FOR_RECONCILIATION
        ):
            append_protected_partition_evidence(
                source_authority=source_authority,
                json_path=json_path,
                evidence_key=normalized_key,
                raw_value=raw_value,
                partition=partition,
                evidence_mode="NEGATIVE_BOOLEAN",
                persisted=persisted,
            )

    if normalized_key in GLOBAL_EMPTY_COLLECTION_KEYS:
        for partition in (
            PROTECTED_PARTITIONS_FOR_RECONCILIATION
        ):
            append_protected_partition_evidence(
                source_authority=source_authority,
                json_path=json_path,
                evidence_key=normalized_key,
                raw_value=raw_value,
                partition=partition,
                evidence_mode="EMPTY_COLLECTION",
                persisted=persisted,
            )

    if normalized_key in GLOBAL_ZERO_COUNT_KEYS:
        for partition in (
            PROTECTED_PARTITIONS_FOR_RECONCILIATION
        ):
            append_protected_partition_evidence(
                source_authority=source_authority,
                json_path=json_path,
                evidence_key=normalized_key,
                raw_value=raw_value,
                partition=partition,
                evidence_mode="ZERO_COUNT",
                persisted=persisted,
            )


def inspect_authority_for_protected_evidence(
    *,
    source_authority: str,
    document: Mapping[str, Any],
    persisted: bool,
) -> None:
    """Inspect every supported evidence representation."""

    for json_path, node in walk_reconciliation_document(
        document
    ):
        if not isinstance(
            node,
            Mapping,
        ):
            continue

        # Direct and nested JSON keys.
        for raw_key, raw_value in node.items():
            inspect_evidence_key_value(
                source_authority=source_authority,
                json_path=f"{json_path}.{raw_key}",
                raw_key=raw_key,
                raw_value=raw_value,
                persisted=persisted,
            )

        # Serialized DataFrame-style field/value rows.
        for name_column in (
            "field",
            "metric",
            "check_name",
            "gate_id",
        ):
            if (
                name_column not in node
            ):
                continue

            value_column = None

            for candidate_value_column in (
                "value",
                "observed",
                "passed",
                "status",
            ):
                if candidate_value_column in node:
                    value_column = candidate_value_column
                    break

            if value_column is None:
                continue

            inspect_evidence_key_value(
                source_authority=source_authority,
                json_path=(
                    f"{json_path}"
                    f"[{name_column}={node[name_column]!r}]"
                ),
                raw_key=node[
                    name_column
                ],
                raw_value=node[
                    value_column
                ],
                persisted=persisted,
            )


for authority_role, authority_document in (
    persisted_reconciliation_authorities.items()
):
    inspect_authority_for_protected_evidence(
        source_authority=authority_role,
        document=authority_document,
        persisted=True,
    )


# ------------------------------------------------------------
# Add derived verified authorities as supplementary evidence
# ------------------------------------------------------------

for derived_authority_name in (
    "FROZEN_NOTEBOOK07_EXECUTION_CONTRACT_AUTHORITY",
    "FROZEN_NOTEBOOK08_AUTHORITY",
):
    derived_authority = globals().get(
        derived_authority_name
    )

    if isinstance(
        derived_authority,
        Mapping,
    ):
        inspect_authority_for_protected_evidence(
            source_authority=derived_authority_name,
            document=derived_authority,
            persisted=False,
        )


# ------------------------------------------------------------
# Add current Notebook 10 runtime assertions
# ------------------------------------------------------------

runtime_partition_fields = {
    "VALIDATION": (
        "VALIDATION_CONTENT_LOADED"
    ),
    "ENGINEERING_HOLDOUT": (
        "ENGINEERING_HOLDOUT_CONTENT_LOADED"
    ),
}

for partition, variable_name in (
    runtime_partition_fields.items()
):
    if variable_name in globals():
        append_protected_partition_evidence(
            source_authority="NOTEBOOK10_RUNTIME",
            json_path=f"$.{variable_name}",
            evidence_key=normalize_reconciliation_key(
                variable_name
            ),
            raw_value=globals()[
                variable_name
            ],
            partition=partition,
            evidence_mode="NEGATIVE_BOOLEAN",
            persisted=False,
        )


runtime_global_protected_state = globals().get(
    "PROTECTED_PARTITION_CONTENT_LOADED"
)

if isinstance(
    runtime_global_protected_state,
    Mapping,
):
    for partition in (
        PROTECTED_PARTITIONS_FOR_RECONCILIATION
    ):
        if partition in runtime_global_protected_state:
            append_protected_partition_evidence(
                source_authority="NOTEBOOK10_RUNTIME",
                json_path=(
                    "$.PROTECTED_PARTITION_CONTENT_LOADED"
                    f"[{partition!r}]"
                ),
                evidence_key=(
                    f"{partition.casefold()}_content_loaded"
                ),
                raw_value=(
                    runtime_global_protected_state[
                        partition
                    ]
                ),
                partition=partition,
                evidence_mode="NEGATIVE_BOOLEAN",
                persisted=False,
            )

elif (
    "PROTECTED_PARTITION_CONTENT_LOADED"
    in globals()
):
    for partition in (
        PROTECTED_PARTITIONS_FOR_RECONCILIATION
    ):
        append_protected_partition_evidence(
            source_authority="NOTEBOOK10_RUNTIME",
            json_path=(
                "$.PROTECTED_PARTITION_CONTENT_LOADED"
            ),
            evidence_key=(
                "protected_partition_content_loaded"
            ),
            raw_value=runtime_global_protected_state,
            partition=partition,
            evidence_mode="NEGATIVE_BOOLEAN",
            persisted=False,
        )


# ------------------------------------------------------------
# Build and gate the closure-evidence table
# ------------------------------------------------------------

V01_NOTEBOOK07_PROTECTED_PARTITION_EVIDENCE = (
    pd.DataFrame(
        protected_partition_evidence_records,
        columns=[
            "source_authority",
            "persisted_authority",
            "partition",
            "json_path",
            "evidence_key",
            "evidence_mode",
            "raw_value",
            "closure_asserted",
            "status",
        ],
    )
    .sort_values(
        [
            "partition",
            "persisted_authority",
            "source_authority",
            "json_path",
        ],
        ascending=[
            True,
            False,
            True,
            True,
        ],
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


protected_partition_summary_records: list[
    dict[str, Any]
] = []

for partition in (
    PROTECTED_PARTITIONS_FOR_RECONCILIATION
):
    partition_rows = (
        V01_NOTEBOOK07_PROTECTED_PARTITION_EVIDENCE.loc[
            V01_NOTEBOOK07_PROTECTED_PARTITION_EVIDENCE[
                "partition"
            ].eq(
                partition
            )
        ]
    )

    persisted_rows = partition_rows.loc[
        partition_rows[
            "persisted_authority"
        ]
    ]

    persisted_closure_rows = persisted_rows.loc[
        persisted_rows[
            "closure_asserted"
        ].eq(
            True
        )
    ]

    contradictory_rows = partition_rows.loc[
        partition_rows[
            "closure_asserted"
        ].eq(
            False
        )
    ]

    unresolved_rows = partition_rows.loc[
        partition_rows[
            "closure_asserted"
        ].isna()
    ]

    closure_verified = bool(
        not persisted_closure_rows.empty
        and contradictory_rows.empty
    )

    protected_partition_summary_records.append(
        {
            "partition": partition,
            "total_evidence_count": int(
                len(
                    partition_rows
                )
            ),
            "persisted_evidence_count": int(
                len(
                    persisted_rows
                )
            ),
            "persisted_closure_evidence_count": int(
                len(
                    persisted_closure_rows
                )
            ),
            "contradictory_evidence_count": int(
                len(
                    contradictory_rows
                )
            ),
            "unresolved_evidence_count": int(
                len(
                    unresolved_rows
                )
            ),
            "closure_verified": closure_verified,
            "status": (
                "PASS_CLOSED"
                if closure_verified
                else "FAIL"
            ),
        }
    )


V01_NOTEBOOK07_PROTECTED_PARTITION_SUMMARY = pd.DataFrame(
    protected_partition_summary_records
)

failed_partition_closure_rows = (
    V01_NOTEBOOK07_PROTECTED_PARTITION_SUMMARY.loc[
        ~V01_NOTEBOOK07_PROTECTED_PARTITION_SUMMARY[
            "closure_verified"
        ]
    ]
)

contradictory_partition_evidence = (
    V01_NOTEBOOK07_PROTECTED_PARTITION_EVIDENCE.loc[
        V01_NOTEBOOK07_PROTECTED_PARTITION_EVIDENCE[
            "closure_asserted"
        ].eq(
            False
        )
    ]
)


# ------------------------------------------------------------
# Selected-model identity reconciliation
# ------------------------------------------------------------

execution_contract_authority = globals().get(
    "FROZEN_NOTEBOOK07_EXECUTION_CONTRACT_AUTHORITY"
)

if not isinstance(
    execution_contract_authority,
    Mapping,
):
    raise Notebook07QuantitativeReconciliationError(
        "The frozen Notebook 07 execution-contract authority "
        "is unavailable."
    )


notebook07_handoff = stage_control_payloads[
    "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF"
]

selected_model_section = notebook07_handoff.get(
    "selected_model",
    {},
)

if not isinstance(
    selected_model_section,
    Mapping,
):
    selected_model_section = {}


selected_model_identity_sources: dict[
    str,
    str,
] = {}


def append_selected_model_identity(
    source_name: str,
    candidate_value: Any,
) -> None:
    """Register one nonblank selected-model identity."""

    if isinstance(
        candidate_value,
        str,
    ) and candidate_value.strip():
        selected_model_identity_sources[
            source_name
        ] = candidate_value.strip()


append_selected_model_identity(
    "EXECUTION_CONTRACT_AUTHORITY",
    execution_contract_authority.get(
        "selected_model_id"
    ),
)

append_selected_model_identity(
    "NOTEBOOK07_HANDOFF.selected_model.model_id",
    selected_model_section.get(
        "model_id"
    ),
)

for role_name in (
    "NOTEBOOK07_TERMINAL_DECISION",
    "NOTEBOOK07_FINAL_ACCEPTANCE",
    "NOTEBOOK07_OUTPUT_MANIFEST",
):
    role_document = stage_control_payloads.get(
        role_name,
        {},
    )

    if isinstance(
        role_document,
        Mapping,
    ):
        append_selected_model_identity(
            role_name,
            role_document.get(
                "selected_model_id"
            ),
        )


frozen_notebook08_authority = globals().get(
    "FROZEN_NOTEBOOK08_AUTHORITY"
)

if isinstance(
    frozen_notebook08_authority,
    Mapping,
):
    append_selected_model_identity(
        "FROZEN_NOTEBOOK08_AUTHORITY",
        frozen_notebook08_authority.get(
            "selected_model_id"
        ),
    )


unique_selected_model_ids = sorted(
    set(
        selected_model_identity_sources.values()
    )
)

if len(
    unique_selected_model_ids
) != 1:
    raise Notebook07QuantitativeReconciliationError(
        "Notebook 07 selected-model identities do not reconcile:\n"
        + json.dumps(
            selected_model_identity_sources,
            indent=2,
            ensure_ascii=False,
        )
    )


RECONCILED_NOTEBOOK07_SELECTED_MODEL_ID = (
    unique_selected_model_ids[
        0
    ]
)


# ------------------------------------------------------------
# Partition-use contract reconciliation
# ------------------------------------------------------------

model_contract_authority = (
    execution_contract_authority.get(
        "model_contract",
        {},
    )
)

if not isinstance(
    model_contract_authority,
    Mapping,
):
    model_contract_authority = {}


fit_partition_candidates = {
    str(
        value
    ).strip().upper()
    for value in (
        execution_contract_authority.get(
            "fit_partition"
        ),
        model_contract_authority.get(
            "fit_partition"
        ),
        selected_model_section.get(
            "fit_partition"
        ),
    )
    if isinstance(
        value,
        str,
    )
    and value.strip()
}

locked_partition_candidates = {
    str(
        value
    ).strip().upper()
    for value in (
        execution_contract_authority.get(
            "locked_evaluation_partition"
        ),
        model_contract_authority.get(
            "locked_evaluation_partition"
        ),
        selected_model_section.get(
            "locked_evaluation_partition"
        ),
    )
    if isinstance(
        value,
        str,
    )
    and value.strip()
}


if fit_partition_candidates != {
    "DEVELOPMENT"
}:
    raise Notebook07QuantitativeReconciliationError(
        "Notebook 07 fit-partition authority does not reconcile "
        "to DEVELOPMENT.\n"
        f"Observed: {sorted(fit_partition_candidates)}"
    )

if locked_partition_candidates != {
    "CALIBRATION"
}:
    raise Notebook07QuantitativeReconciliationError(
        "Notebook 07 locked evaluation partition does not "
        "reconcile to CALIBRATION.\n"
        f"Observed: {sorted(locked_partition_candidates)}"
    )


# ------------------------------------------------------------
# CALIBRATION update reconciliation
# ------------------------------------------------------------

calibration_update_sources: dict[
    str,
    int,
] = {}


def append_calibration_update_value(
    source_name: str,
    candidate_value: Any,
) -> None:
    """Register one declared CALIBRATION update count."""

    normalized_value = normalize_reconciliation_integer(
        candidate_value
    )

    if normalized_value is not None:
        calibration_update_sources[
            source_name
        ] = normalized_value


append_calibration_update_value(
    "EXECUTION_CONTRACT_AUTHORITY",
    execution_contract_authority.get(
        "calibration_parameter_updates"
    ),
)

append_calibration_update_value(
    "NOTEBOOK10_RUNTIME",
    globals().get(
        "CALIBRATION_PARAMETER_UPDATES_PERFORMED"
    ),
)

for role_name in (
    "NOTEBOOK07_TERMINAL_DECISION",
    "NOTEBOOK07_SEMANTIC_READBACK",
    "NOTEBOOK07_FINAL_ACCEPTANCE",
    "NOTEBOOK07_OUTPUT_MANIFEST",
    "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF",
    "NOTEBOOK08_FINAL_DISPOSITION",
):
    role_document = stage_control_payloads.get(
        role_name,
        {},
    )

    if not isinstance(
        role_document,
        Mapping,
    ):
        continue

    for candidate_key in (
        "calibration_parameter_updates",
        "calibration_parameter_updates_performed",
    ):
        append_calibration_update_value(
            f"{role_name}.{candidate_key}",
            role_document.get(
                candidate_key
            ),
        )


if not calibration_update_sources:
    raise Notebook07QuantitativeReconciliationError(
        "No CALIBRATION parameter-update evidence was found."
    )

nonzero_calibration_updates = {
    source_name: update_count
    for source_name, update_count in (
        calibration_update_sources.items()
    )
    if update_count != 0
}

if nonzero_calibration_updates:
    raise Notebook07QuantitativeReconciliationError(
        "At least one authority declares nonzero CALIBRATION "
        "parameter updates:\n"
        + json.dumps(
            nonzero_calibration_updates,
            indent=2,
            ensure_ascii=False,
        )
    )


# ------------------------------------------------------------
# Model mutation controls
# ------------------------------------------------------------

model_refit_performed = bool(
    globals().get(
        "MODEL_REFIT_PERFORMED",
        False,
    )
)

model_replacement_performed = bool(
    globals().get(
        "MODEL_REPLACEMENT_PERFORMED",
        False,
    )
)

if model_refit_performed:
    raise Notebook07QuantitativeReconciliationError(
        "A model refit was recorded during Notebook 10 auditing."
    )

if model_replacement_performed:
    raise Notebook07QuantitativeReconciliationError(
        "A model replacement was recorded during Notebook 10 auditing."
    )


# ------------------------------------------------------------
# Notebook 08 authorization-scope reconciliation
# ------------------------------------------------------------

authorization_scope_sources: dict[
    str,
    str,
] = {}


def append_authorization_scope(
    source_name: str,
    candidate_value: Any,
) -> None:
    """Register one nonblank authorization scope."""

    if isinstance(
        candidate_value,
        str,
    ) and candidate_value.strip():
        authorization_scope_sources[
            source_name
        ] = candidate_value.strip().upper()


append_authorization_scope(
    "EXECUTION_CONTRACT_AUTHORITY",
    execution_contract_authority.get(
        "notebook08_authorization_scope"
    ),
)

append_authorization_scope(
    "NOTEBOOK07_HANDOFF",
    notebook07_handoff.get(
        "authorization_scope"
    ),
)

for role_name in (
    "NOTEBOOK07_FINAL_ACCEPTANCE",
    "NOTEBOOK07_OUTPUT_MANIFEST",
):
    role_document = stage_control_payloads.get(
        role_name,
        {},
    )

    if isinstance(
        role_document,
        Mapping,
    ):
        append_authorization_scope(
            role_name,
            role_document.get(
                "notebook08_authorization_scope",
                role_document.get(
                    "notebook08_authorized_scope"
                ),
            ),
        )


ACCEPTED_NOTEBOOK08_AUTHORIZATION_SCOPES = {
    "NOTEBOOK_08_DIAGNOSTICS_ONLY",
    "HAWKES_DIAGNOSTICS_ONLY",
}

invalid_authorization_scopes = {
    source_name: scope
    for source_name, scope in (
        authorization_scope_sources.items()
    )
    if scope
    not in ACCEPTED_NOTEBOOK08_AUTHORIZATION_SCOPES
}

if not authorization_scope_sources:
    raise Notebook07QuantitativeReconciliationError(
        "No Notebook 08 authorization-scope evidence was found."
    )

if invalid_authorization_scopes:
    raise Notebook07QuantitativeReconciliationError(
        "Notebook 08 received an invalid authorization scope:\n"
        + json.dumps(
            invalid_authorization_scopes,
            indent=2,
            ensure_ascii=False,
        )
    )


# ------------------------------------------------------------
# Notebook 06 baseline boundary
# ------------------------------------------------------------

notebook06_baseline_authority = globals().get(
    "FROZEN_NOTEBOOK06_BASELINE_AUTHORITY"
)

if not isinstance(
    notebook06_baseline_authority,
    Mapping,
):
    raise Notebook07QuantitativeReconciliationError(
        "The frozen Notebook 06 baseline authority is unavailable."
    )


formal_comparator_candidates = {
    str(
        value
    ).strip()
    for value in (
        notebook06_baseline_authority.get(
            "formal_count_comparator_model_id"
        ),
        globals().get(
            "FORMAL_COUNT_COMPARATOR_MODEL_ID"
        ),
    )
    if isinstance(
        value,
        str,
    )
    and value.strip()
}

primary_simple_baseline_candidates = {
    str(
        value
    ).strip()
    for value in (
        notebook06_baseline_authority.get(
            "primary_simple_count_baseline_model_id"
        ),
        globals().get(
            "PRIMARY_SIMPLE_COUNT_BASELINE_MODEL_ID"
        ),
    )
    if isinstance(
        value,
        str,
    )
    and value.strip()
}

if len(
    formal_comparator_candidates
) != 1:
    raise Notebook07QuantitativeReconciliationError(
        "The formal count-comparator identity does not reconcile.\n"
        f"Observed: {sorted(formal_comparator_candidates)}"
    )

if len(
    primary_simple_baseline_candidates
) != 1:
    raise Notebook07QuantitativeReconciliationError(
        "The primary simple-baseline identity does not reconcile.\n"
        f"Observed: {sorted(primary_simple_baseline_candidates)}"
    )


RECONCILED_FORMAL_COUNT_COMPARATOR = next(
    iter(
        formal_comparator_candidates
    )
)

RECONCILED_PRIMARY_SIMPLE_BASELINE = next(
    iter(
        primary_simple_baseline_candidates
    )
)


# ------------------------------------------------------------
# Blocking protected-partition gates
# ------------------------------------------------------------

if not contradictory_partition_evidence.empty:
    raise Notebook07QuantitativeReconciliationError(
        "Contradictory protected-partition evidence was found:\n"
        + contradictory_partition_evidence[
            [
                "partition",
                "source_authority",
                "json_path",
                "evidence_key",
                "raw_value",
                "status",
            ]
        ].to_string(
            index=False
        )
    )

if not failed_partition_closure_rows.empty:
    raise Notebook07QuantitativeReconciliationError(
        "Persisted protected-partition closure could not be "
        "verified:\n"
        + failed_partition_closure_rows.to_string(
            index=False
        )
    )


# ------------------------------------------------------------
# Build reconciliation check table
# ------------------------------------------------------------

quantitative_reconciliation_checks = [
    {
        "check_order": 1,
        "check_name": "selected_model_identity_reconciles",
        "observed": RECONCILED_NOTEBOOK07_SELECTED_MODEL_ID,
        "expected": "ONE CONSISTENT MODEL ID",
        "passed": True,
        "status": "PASS",
    },
    {
        "check_order": 2,
        "check_name": "fit_partition_is_development",
        "observed": sorted(
            fit_partition_candidates
        ),
        "expected": [
            "DEVELOPMENT",
        ],
        "passed": True,
        "status": "PASS",
    },
    {
        "check_order": 3,
        "check_name": "locked_evaluation_partition_is_calibration",
        "observed": sorted(
            locked_partition_candidates
        ),
        "expected": [
            "CALIBRATION",
        ],
        "passed": True,
        "status": "PASS",
    },
    {
        "check_order": 4,
        "check_name": "calibration_parameter_updates_are_zero",
        "observed": calibration_update_sources,
        "expected": {
            "all_declared_values": 0,
        },
        "passed": True,
        "status": "PASS",
    },
    {
        "check_order": 5,
        "check_name": "model_refit_not_performed",
        "observed": model_refit_performed,
        "expected": False,
        "passed": True,
        "status": "PASS",
    },
    {
        "check_order": 6,
        "check_name": "model_replacement_not_performed",
        "observed": model_replacement_performed,
        "expected": False,
        "passed": True,
        "status": "PASS",
    },
    {
        "check_order": 7,
        "check_name": "notebook08_scope_is_diagnostics_only",
        "observed": authorization_scope_sources,
        "expected": sorted(
            ACCEPTED_NOTEBOOK08_AUTHORIZATION_SCOPES
        ),
        "passed": True,
        "status": "PASS",
    },
    {
        "check_order": 8,
        "check_name": "validation_remains_unopened",
        "observed": bool(
            V01_NOTEBOOK07_PROTECTED_PARTITION_SUMMARY.loc[
                V01_NOTEBOOK07_PROTECTED_PARTITION_SUMMARY[
                    "partition"
                ].eq(
                    "VALIDATION"
                ),
                "closure_verified",
            ].iloc[
                0
            ]
        ),
        "expected": True,
        "passed": True,
        "status": "PASS",
    },
    {
        "check_order": 9,
        "check_name": "engineering_holdout_remains_unopened",
        "observed": bool(
            V01_NOTEBOOK07_PROTECTED_PARTITION_SUMMARY.loc[
                V01_NOTEBOOK07_PROTECTED_PARTITION_SUMMARY[
                    "partition"
                ].eq(
                    "ENGINEERING_HOLDOUT"
                ),
                "closure_verified",
            ].iloc[
                0
            ]
        ),
        "expected": True,
        "passed": True,
        "status": "PASS",
    },
    {
        "check_order": 10,
        "check_name": "formal_count_comparator_preserved",
        "observed": RECONCILED_FORMAL_COUNT_COMPARATOR,
        "expected": RECONCILED_FORMAL_COUNT_COMPARATOR,
        "passed": True,
        "status": "PASS",
    },
    {
        "check_order": 11,
        "check_name": "primary_simple_count_baseline_preserved",
        "observed": RECONCILED_PRIMARY_SIMPLE_BASELINE,
        "expected": RECONCILED_PRIMARY_SIMPLE_BASELINE,
        "passed": True,
        "status": "PASS",
    },
]


V01_NOTEBOOK07_QUANTITATIVE_RECONCILIATION_AUDIT = (
    pd.DataFrame(
        quantitative_reconciliation_checks
    )
)

for rendered_column in (
    "observed",
    "expected",
):
    V01_NOTEBOOK07_QUANTITATIVE_RECONCILIATION_AUDIT[
        rendered_column
    ] = V01_NOTEBOOK07_QUANTITATIVE_RECONCILIATION_AUDIT[
        rendered_column
    ].map(
        render_reconciliation_value
    )


V01_NOTEBOOK07_QUANTITATIVE_RECONCILIATION_SUMMARY = (
    pd.DataFrame(
        [
            {
                "metric": "selected_model_id",
                "value": (
                    RECONCILED_NOTEBOOK07_SELECTED_MODEL_ID
                ),
            },
            {
                "metric": "fit_partition",
                "value": "DEVELOPMENT",
            },
            {
                "metric": "locked_evaluation_partition",
                "value": "CALIBRATION",
            },
            {
                "metric": "calibration_parameter_updates",
                "value": 0,
            },
            {
                "metric": "formal_count_comparator",
                "value": (
                    RECONCILED_FORMAL_COUNT_COMPARATOR
                ),
            },
            {
                "metric": "primary_simple_count_baseline",
                "value": (
                    RECONCILED_PRIMARY_SIMPLE_BASELINE
                ),
            },
            {
                "metric": "model_refit_performed",
                "value": False,
            },
            {
                "metric": "model_replacement_performed",
                "value": False,
            },
            {
                "metric": "validation_closure_verified",
                "value": True,
            },
            {
                "metric": (
                    "engineering_holdout_closure_verified"
                ),
                "value": True,
            },
            {
                "metric": (
                    "persisted_protected_partition_evidence_count"
                ),
                "value": int(
                    V01_NOTEBOOK07_PROTECTED_PARTITION_EVIDENCE[
                        "persisted_authority"
                    ].sum()
                ),
            },
            {
                "metric": "contradictory_evidence_count",
                "value": int(
                    len(
                        contradictory_partition_evidence
                    )
                ),
            },
            {
                "metric": "protected_partition_content_loaded",
                "value": False,
            },
        ]
    )
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    V01_NOTEBOOK07_QUANTITATIVE_RECONCILIATION_SUMMARY
)

display(
    V01_NOTEBOOK07_PROTECTED_PARTITION_SUMMARY
)

display(
    V01_NOTEBOOK07_PROTECTED_PARTITION_EVIDENCE[
        [
            "partition",
            "source_authority",
            "persisted_authority",
            "json_path",
            "evidence_key",
            "evidence_mode",
            "raw_value",
            "closure_asserted",
            "status",
        ]
    ]
)

display(
    V01_NOTEBOOK07_QUANTITATIVE_RECONCILIATION_AUDIT
)


# ------------------------------------------------------------
# Freeze verified quantitative authority
# ------------------------------------------------------------

FROZEN_NOTEBOOK07_QUANTITATIVE_RECONCILIATION_AUTHORITY = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "selected_model_id": (
        RECONCILED_NOTEBOOK07_SELECTED_MODEL_ID
    ),
    "fit_partition": "DEVELOPMENT",
    "locked_evaluation_partition": "CALIBRATION",
    "calibration_parameter_updates": 0,
    "formal_count_comparator": (
        RECONCILED_FORMAL_COUNT_COMPARATOR
    ),
    "primary_simple_count_baseline": (
        RECONCILED_PRIMARY_SIMPLE_BASELINE
    ),
    "notebook08_authorization_scopes": dict(
        authorization_scope_sources
    ),
    "protected_partition_closure": {
        str(row.partition): {
            "closure_verified": bool(
                row.closure_verified
            ),
            "persisted_closure_evidence_count": int(
                row.persisted_closure_evidence_count
            ),
            "contradictory_evidence_count": int(
                row.contradictory_evidence_count
            ),
        }
        for row in (
            V01_NOTEBOOK07_PROTECTED_PARTITION_SUMMARY.itertuples(
                index=False
            )
        )
    },
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "protected_partition_content_loaded": False,
    "blocking_failure_count": 0,
}


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

NOTEBOOK07_QUANTITATIVE_RECONCILIATION_VERIFIED = True
NOTEBOOK07_PROTECTED_PARTITION_CLOSURE_VERIFIED = True
NOTEBOOK07_CALIBRATION_ZERO_UPDATE_VERIFIED = True
NOTEBOOK07_MODEL_MUTATION_ABSENCE_VERIFIED = True

VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False

if isinstance(
    globals().get(
        "PROTECTED_PARTITION_CONTENT_LOADED"
    ),
    Mapping,
):
    for protected_partition in (
        PROTECTED_PARTITIONS_FOR_RECONCILIATION
    ):
        if protected_partition in (
            PROTECTED_PARTITION_CONTENT_LOADED
        ):
            if bool(
                PROTECTED_PARTITION_CONTENT_LOADED[
                    protected_partition
                ]
            ):
                raise Notebook07QuantitativeReconciliationError(
                    "The runtime protected-partition ledger "
                    f"marks {protected_partition} as loaded."
                )

else:
    PROTECTED_PARTITION_CONTENT_LOADED = False


MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

UPSTREAM_ARTIFACTS_VERIFIED = False

print(
    "Notebook 07 quantitative reconciliation: PASS. The frozen "
    f"{RECONCILED_NOTEBOOK07_SELECTED_MODEL_ID} identity, "
    "DEVELOPMENT-only fit, locked CALIBRATION evaluation, "
    "Notebook 06 comparator boundary, and zero CALIBRATION "
    "parameter-update contract reconcile across the verified "
    "Notebook 07 and Notebook 08 authorities. Persisted closure "
    "evidence confirms that VALIDATION and ENGINEERING_HOLDOUT "
    "remained unopened, with no contradictory authority. No "
    "model refit, replacement, analytical partition load, or "
    "filesystem write was performed."
)

                                          metric                      value
0                              selected_model_id   H1_DIAGONAL_SHARED_DECAY
1                                  fit_partition                DEVELOPMENT
2                    locked_evaluation_partition                CALIBRATION
3                  calibration_parameter_updates                          0
4                        formal_count_comparator   D0_SIDE_CONSTANT_POISSON
5                  primary_simple_count_baseline  E_SIDE_EWMA_250MS_POISSON
6                          model_refit_performed                      False
7                    model_replacement_performed                      False
8                    validation_closure_verified                       True
9           engineering_holdout_closure_verified                       True
10  persisted_protected_partition_evidence_count                         38
11                  contradictory_evidence_count                          0
12            protected_partition_content_loaded                      False

             partition  total_evidence_count  persisted_evidence_count  persisted_closure_evidence_count  contradictory_evidence_count  unresolved_evidence_count  closure_verified       status
0           VALIDATION                    26                        22                                 9                             0                         13              True  PASS_CLOSED
1  ENGINEERING_HOLDOUT                    20                        16                                 3                             0                         13              True  PASS_CLOSED

,partition,source_authority,persisted_authority,json_path,evidence_key,evidence_mode,raw_value,closure_asserted,status
0,ENGINEERING_HOLDOUT,NOTEBOOK07_FINAL_ACCEPTANCE,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
1,ENGINEERING_HOLDOUT,NOTEBOOK07_OUTPUT_MANIFEST,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
2,ENGINEERING_HOLDOUT,NOTEBOOK07_PERSISTENCE_INDEX,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
3,ENGINEERING_HOLDOUT,NOTEBOOK07_SEMANTIC_READBACK,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
4,ENGINEERING_HOLDOUT,NOTEBOOK07_TERMINAL_DECISION,True,$.components.terminal_decision.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
5,ENGINEERING_HOLDOUT,NOTEBOOK07_TERMINAL_DECISION,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
6,ENGINEERING_HOLDOUT,NOTEBOOK07_TO_NOTEBOOK08_HANDOFF,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
7,ENGINEERING_HOLDOUT,NOTEBOOK08_CORE_OUTPUT_MANIFEST,True,$.artifacts[62].dtypes.engineering_holdout_opened,engineering_holdout_opened,NEGATIVE_BOOLEAN,'bool',None,UNRESOLVED
8,ENGINEERING_HOLDOUT,NOTEBOOK08_CORE_OUTPUT_MANIFEST,True,$.engineering_holdout_opened,engineering_holdout_opened,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
9,ENGINEERING_HOLDOUT,NOTEBOOK08_CORE_OUTPUT_MANIFEST,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
10,ENGINEERING_HOLDOUT,NOTEBOOK08_FINAL_DISPOSITION,True,$.terminal_decision.engineering_holdout_opened,engineering_holdout_opened,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
11,ENGINEERING_HOLDOUT,NOTEBOOK08_FINAL_OUTPUT_MANIFEST,True,$.files[73].dtypes.engineering_holdout_opened,engineering_holdout_opened,NEGATIVE_BOOLEAN,'bool',None,UNRESOLVED
12,ENGINEERING_HOLDOUT,NOTEBOOK08_FINAL_OUTPUT_MANIFEST,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
13,ENGINEERING_HOLDOUT,NOTEBOOK08_SEMANTIC_READBACK,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
14,ENGINEERING_HOLDOUT,NOTEBOOK08_SEMANTIC_READBACK,True,$.summary[11][field='protected_partitions_loaded'],protected_partitions_loaded,EMPTY_COLLECTION,False,True,PASS_CLOSED
15,ENGINEERING_HOLDOUT,NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
16,ENGINEERING_HOLDOUT,FROZEN_NOTEBOOK07_EXECUTION_CONTRACT_AUTHORITY,False,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
17,ENGINEERING_HOLDOUT,FROZEN_NOTEBOOK08_AUTHORITY,False,$.engineering_holdout_content_loaded,engineering_holdout_content_loaded,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
18,ENGINEERING_HOLDOUT,NOTEBOOK10_RUNTIME,False,$.ENGINEERING_HOLDOUT_CONTENT_LOADED,engineering_holdout_content_loaded,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
19,ENGINEERING_HOLDOUT,NOTEBOOK10_RUNTIME,False,$.PROTECTED_PARTITION_CONTENT_LOADED,protected_partition_content_loaded,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
20,VALIDATION,NOTEBOOK07_FINAL_ACCEPTANCE,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
21,VALIDATION,NOTEBOOK07_OUTPUT_MANIFEST,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
22,VALIDATION,NOTEBOOK07_PERSISTENCE_INDEX,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
23,VALIDATION,NOTEBOOK07_SEMANTIC_READBACK,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
24,VALIDATION,NOTEBOOK07_TERMINAL_DECISION,True,$.components.terminal_decision.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
25,VALIDATION,NOTEBOOK07_TERMINAL_DECISION,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
26,VALIDATION,NOTEBOOK07_TO_NOTEBOOK08_HANDOFF,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
27,VALIDATION,NOTEBOOK08_CORE_OUTPUT_MANIFEST,True,$.artifacts[62].dtypes.validation_partition_opening_authorized,validation_partition_opening_authorized,NEGATIVE_BOOLEAN,'bool',None,UNRESOLVED
28,VALIDATION,NOTEBOOK08_CORE_OUTPUT_MANIFEST,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
29,VALIDATION,NOTEBOOK08_CORE_OUTPUT_MANIFEST,True,$.validation_partition_opening_authorized,validation_partition_opening_authorized,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
30,VALIDATION,NOTEBOOK08_FINAL_DISPOSITION,True,$.terminal_decision.validation_partition_opening_authorized,validation_partition_opening_authorized,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
31,VALIDATION,NOTEBOOK08_FINAL_DISPOSITION,True,$.validation_partition_opening_authorized,validation_partition_opening_authorized,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
32,VALIDATION,NOTEBOOK08_FINAL_OUTPUT_MANIFEST,True,$.files[73].dtypes.validation_partition_opening_authorized,validation_partition_opening_authorized,NEGATIVE_BOOLEAN,'bool',None,UNRESOLVED
33,VALIDATION,NOTEBOOK08_FINAL_OUTPUT_MANIFEST,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
34,VALIDATION,NOTEBOOK08_FINAL_OUTPUT_MANIFEST,True,$.validation_partition_opening_authorized,validation_partition_opening_authorized,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
35,VALIDATION,NOTEBOOK08_SEMANTIC_READBACK,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
36,VALIDATION,NOTEBOOK08_SEMANTIC_READBACK,True,$.summary[11][field='protected_partitions_loaded'],protected_partitions_loaded,EMPTY_COLLECTION,False,True,PASS_CLOSED
37,VALIDATION,NOTEBOOK08_SEMANTIC_READBACK,True,$.summary[9][field='validation_partition_opening_authorized'],validation_partition_opening_authorized,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
38,VALIDATION,NOTEBOOK08_SEMANTIC_READBACK,True,$.validation_partition_opening_authorized,validation_partition_opening_authorized,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
39,VALIDATION,NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF,True,$.validation_partition_opening_authorized,validation_partition_opening_authorized,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
40,VALIDATION,NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF,True,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,"{""ENGINEERING_HOLDOUT"": false, ""VALIDATION"": false}",None,UNRESOLVED
41,VALIDATION,NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF,True,$.validation_partition_opening_authorized,validation_partition_opening_authorized,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
42,VALIDATION,FROZEN_NOTEBOOK07_EXECUTION_CONTRACT_AUTHORITY,False,$.protected_partition_content_loaded,protected_partition_content_loaded,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
43,VALIDATION,FROZEN_NOTEBOOK08_AUTHORITY,False,$.validation_content_loaded,validation_content_loaded,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
44,VALIDATION,NOTEBOOK10_RUNTIME,False,$.PROTECTED_PARTITION_CONTENT_LOADED,protected_partition_content_loaded,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED
45,VALIDATION,NOTEBOOK10_RUNTIME,False,$.VALIDATION_CONTENT_LOADED,validation_content_loaded,NEGATIVE_BOOLEAN,False,True,PASS_CLOSED

,check_order,check_name,observed,expected,passed,status
0,1,selected_model_identity_reconciles,'H1_DIAGONAL_SHARED_DECAY','ONE CONSISTENT MODEL ID',True,PASS
1,2,fit_partition_is_development,"[""DEVELOPMENT""]","[""DEVELOPMENT""]",True,PASS
2,3,locked_evaluation_partition_is_calibration,"[""CALIBRATION""]","[""CALIBRATION""]",True,PASS
3,4,calibration_parameter_updates_are_zero,"{""EXECUTION_CONTRACT_AUTHORITY"": 0, ""NOTEBOOK07_FINAL_ACCEPTANCE.calibration_parameter_updates"": 0, ""NOTEBOOK07_OUTPUT_MANIFEST.calibration_parameter_update...","{""all_declared_values"": 0}",True,PASS
4,5,model_refit_not_performed,False,False,True,PASS
5,6,model_replacement_not_performed,False,False,True,PASS
6,7,notebook08_scope_is_diagnostics_only,"{""EXECUTION_CONTRACT_AUTHORITY"": ""NOTEBOOK_08_DIAGNOSTICS_ONLY"", ""NOTEBOOK07_FINAL_ACCEPTANCE"": ""HAWKES_DIAGNOSTICS_ONLY"", ""NOTEBOOK07_HANDOFF"": ""NOTEBOOK_0...","[""HAWKES_DIAGNOSTICS_ONLY"", ""NOTEBOOK_08_DIAGNOSTICS_ONLY""]",True,PASS
7,8,validation_remains_unopened,True,True,True,PASS
8,9,engineering_holdout_remains_unopened,True,True,True,PASS
9,10,formal_count_comparator_preserved,'D0_SIDE_CONSTANT_POISSON','D0_SIDE_CONSTANT_POISSON',True,PASS
10,11,primary_simple_count_baseline_preserved,'E_SIDE_EWMA_250MS_POISSON','E_SIDE_EWMA_250MS_POISSON',True,PASS

Notebook 07 quantitative reconciliation: PASS. The frozen H1_DIAGONAL_SHARED_DECAY identity, DEVELOPMENT-only fit, locked CALIBRATION evaluation, Notebook 06 comparator boundary, and zero CALIBRATION parameter-update contract reconcile across the verified Notebook 07 and Notebook 08 authorities. Persisted closure evidence confirms that VALIDATION and ENGINEERING_HOLDOUT remained unopened, with no contradictory authority. No model refit, replacement, analytical partition load, or filesystem write was performed.

In [32]:
# ============================================================
# Notebook 08 quantitative diagnostic disposition audit
#
# This cell independently verifies:
# - persisted Notebook 08 diagnostic tables;
# - exact diagnostic-gate and rejection ledgers;
# - narrow locked-CALIBRATION count-score superiority;
# - failed residual-distribution, residual-serial,
#   path-count, and exact-time-multiplicity adequacy;
# - frozen H1 disposition without refit or repair;
# - Notebook 09 as skipped and unauthorized, not passed;
# - VALIDATION and ENGINEERING_HOLDOUT remaining unopened;
# - Notebook 10's audit-and-close-only authorization.
#
# No protected analytical content is opened.
# No filesystem writes are performed.
# ============================================================

from __future__ import annotations

import hashlib
import json
import math
import re
from pathlib import Path
from typing import Any, Final, Mapping

import numpy as np
import pandas as pd
from IPython.display import display


class Notebook08DiagnosticDispositionError(RuntimeError):
    """Raised when Notebook 08 diagnostic authority is inconsistent."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

required_notebook08_preconditions: dict[str, bool] = {
    "NOTEBOOK07_QUANTITATIVE_RECONCILIATION_VERIFIED": bool(
        globals().get(
            "NOTEBOOK07_QUANTITATIVE_RECONCILIATION_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK07_PROTECTED_PARTITION_CLOSURE_VERIFIED": bool(
        globals().get(
            "NOTEBOOK07_PROTECTED_PARTITION_CLOSURE_VERIFIED",
            False,
        )
    ),
}

failed_notebook08_preconditions = sorted(
    name
    for name, passed in required_notebook08_preconditions.items()
    if not passed
)

if failed_notebook08_preconditions:
    raise Notebook08DiagnosticDispositionError(
        "Notebook 08 diagnostic-audit prerequisites have not "
        "passed:\n"
        f"{failed_notebook08_preconditions}"
    )

if not isinstance(
    globals().get(
        "stage_control_payloads"
    ),
    dict,
):
    raise Notebook08DiagnosticDispositionError(
        "The verified stage-control payload registry is unavailable."
    )

if bool(
    globals().get(
        "VALIDATION_CONTENT_LOADED",
        False,
    )
):
    raise Notebook08DiagnosticDispositionError(
        "VALIDATION content was unexpectedly loaded."
    )

if bool(
    globals().get(
        "ENGINEERING_HOLDOUT_CONTENT_LOADED",
        False,
    )
):
    raise Notebook08DiagnosticDispositionError(
        "ENGINEERING_HOLDOUT content was unexpectedly loaded."
    )


# ------------------------------------------------------------
# Expected frozen authority
# ------------------------------------------------------------

EXPECTED_NOTEBOOK08_SELECTED_MODEL_ID: Final[str] = (
    "H1_DIAGONAL_SHARED_DECAY"
)

EXPECTED_NOTEBOOK08_SELECTED_MODEL_FAMILY: Final[str] = (
    "DIAGONAL_BIVARIATE_EXPONENTIAL_HAWKES"
)

EXPECTED_NOTEBOOK08_TERMINAL_CLASS: Final[str] = "FAIL"

EXPECTED_NOTEBOOK08_TERMINAL_STATUS: Final[str] = (
    "FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY"
)

EXPECTED_NOTEBOOK08_DISPOSITION: Final[str] = (
    "REJECTED_FOR_DOWNSTREAM_SIGNAL_AUTHORIZATION"
)

EXPECTED_NOTEBOOK08_ALLOWED_ROLE: Final[str] = (
    "DIAGNOSTIC_REFERENCE_AND_FAILURE_ANALYSIS_ONLY"
)

EXPECTED_NOTEBOOK08_NEXT_OPERATION: Final[str] = (
    "BEGIN_NOTEBOOK10_FINAL_AUDIT_WITH_NOTEBOOK09_SKIPPED"
)

EXPECTED_NOTEBOOK08_FINAL_AUTHORIZATION_SCOPE: Final[str] = (
    "AUDIT_AND_CLOSE_FAILED_V0_1_DIAGNOSTIC_BRANCH_ONLY"
)

EXPECTED_NOTEBOOK08_FAILED_GATES: Final[set[str]] = {
    "LOCKED_CALIBRATION_RESIDUAL_DISTRIBUTION",
    "LOCKED_CALIBRATION_RESIDUAL_SERIAL_DEPENDENCE",
    "LOCKED_CALIBRATION_PATH_COUNT_CALIBRATION",
    "LOCKED_CALIBRATION_EXACT_TIME_MULTIPLICITY",
}

EXPECTED_NOTEBOOK08_SCORE_GATES: Final[set[str]] = {
    "MATERIAL_SCORE_IMPROVEMENT_OVER_FORMAL_COMPARATOR",
    "MATERIAL_SCORE_IMPROVEMENT_OVER_PRIMARY_SIMPLE_BASELINE",
    "MATERIAL_SCORE_IMPROVEMENT_OVER_ALL_AUTHORIZED_BASELINES",
}

EXPECTED_NOTEBOOK08_ALL_GATES: Final[set[str]] = {
    *EXPECTED_NOTEBOOK08_SCORE_GATES,
    "DEFENSIBLE_STATIONARITY_MARGIN",
    *EXPECTED_NOTEBOOK08_FAILED_GATES,
    "LOCKED_CALIBRATION_SIDE_MARK_CALIBRATION",
    "CROSS_SIDE_DESCRIPTIVE_REPORT_COMPLETE",
    "CROSS_SIDE_FORMAL_SIMULATION_ENVELOPE",
    "CALIBRATION_PARAMETER_UPDATES_ZERO",
    "PROTECTED_PARTITIONS_UNOPENED",
    "FILESYSTEM_WRITES_ABSENT",
}

EXPECTED_NOTEBOOK08_REQUIRED_AUDIT_FINDINGS: Final[set[str]] = {
    "PRESERVE_SUPPORTED_COUNT_SCORE_SUPERIORITY_AS_NARROW_EVIDENCE",
    "PRESERVE_FAILED_MODEL_ADEQUACY_AS_BLOCKING_EVIDENCE",
    "RECORD_NOTEBOOK09_AS_SKIPPED_NOT_PASSED",
    "RECORD_VALIDATION_AS_UNOPENED",
    "RECORD_ENGINEERING_HOLDOUT_AS_UNOPENED",
    "PRESERVE_FROZEN_H1_WITHOUT_REFIT_OR_REPAIR",
    "CLOSE_V0_1_WITHOUT_STRATEGY_OR_SIGNAL_AUTHORIZATION",
}

EXPECTED_NOTEBOOK08_BOOTSTRAP_COMPARATORS: Final[set[str]] = {
    "D0_SIDE_CONSTANT_POISSON",
    "E_SIDE_EWMA_250MS_POISSON",
    "R_SIDE_ROLLING_250MS_POISSON",
    "B1_SIDE_SPECIFIC_HOMOGENEOUS_POISSON",
}

EXPECTED_NOTEBOOK08_FAMILY_RESULTS: Final[
    dict[str, dict[str, Any]]
] = {
    "EXACT_TIME_MULTIPLICITY": {
        "metric_count": 7,
        "outside_directional_envelope_count": 4,
        "within_declared_adequacy_tolerance": False,
    },
    "PATH_COUNTS": {
        "metric_count": 4,
        "outside_directional_envelope_count": 4,
        "within_declared_adequacy_tolerance": False,
    },
    "SIDE_MARK_CALIBRATION": {
        "metric_count": 3,
        "outside_directional_envelope_count": 0,
        "within_declared_adequacy_tolerance": True,
    },
    "TIME_RESCALING_RESIDUAL": {
        "metric_count": 27,
        "outside_directional_envelope_count": 26,
        "within_declared_adequacy_tolerance": False,
    },
}


# ------------------------------------------------------------
# General helpers
# ------------------------------------------------------------

def notebook08_sha256_file(
    path: Path,
    *,
    chunk_size: int = 1 << 20,
) -> str:
    """Return the physical SHA-256 digest of one file."""

    digest = hashlib.sha256()

    with path.open(
        "rb"
    ) as input_stream:
        while True:
            chunk = input_stream.read(
                chunk_size
            )

            if not chunk:
                break

            digest.update(
                chunk
            )

    return digest.hexdigest()


def notebook08_normalized_path(
    value: Any,
) -> Path:
    """Normalize one filesystem path without requiring existence."""

    return Path(
        str(
            value
        )
    ).expanduser().resolve(
        strict=False
    )


def notebook08_path_inside(
    path: Path,
    root: Path,
) -> bool:
    """Return whether path lies inside root."""

    normalized_path = notebook08_normalized_path(
        path
    )

    normalized_root = notebook08_normalized_path(
        root
    )

    try:
        normalized_path.relative_to(
            normalized_root
        )

    except ValueError:
        return False

    return True


def notebook08_boolean(
    value: Any,
) -> bool | None:
    """Normalize common persisted boolean representations."""

    if value is None:
        return None

    if isinstance(
        value,
        (Mapping, list, tuple, set, np.ndarray, pd.Series),
    ):
        return None

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(
            value
        )

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        integer_value = int(
            value
        )

        if integer_value in {
            0,
            1,
        }:
            return bool(
                integer_value
            )

    if isinstance(
        value,
        (float, np.floating),
    ):
        if not np.isfinite(
            float(
                value
            )
        ):
            return None

        if float(
            value
        ) in {
            0.0,
            1.0,
        }:
            return bool(
                int(
                    value
                )
            )

    normalized = str(
        value
    ).strip().casefold()

    if normalized in {
        "true",
        "t",
        "yes",
        "y",
        "1",
        "pass",
        "passed",
    }:
        return True

    if normalized in {
        "false",
        "f",
        "no",
        "n",
        "0",
        "fail",
        "failed",
        "",
        "none",
        "null",
    }:
        return False

    return None


def notebook08_integer(
    value: Any,
) -> int | None:
    """Normalize one integer-like value."""

    if value is None:
        return None

    try:
        numeric_value = float(
            value
        )

    except (
        TypeError,
        ValueError,
        OverflowError,
    ):
        return None

    if not np.isfinite(
        numeric_value
    ):
        return None

    if not numeric_value.is_integer():
        return None

    return int(
        numeric_value
    )


def notebook08_render(
    value: Any,
) -> str:
    """Render deterministic compact values for audit tables."""

    if isinstance(
        value,
        Path,
    ):
        return str(
            value
        )

    if isinstance(
        value,
        set,
    ):
        value = sorted(
            value
        )

    if isinstance(
        value,
        (
            dict,
            list,
            tuple,
        ),
    ):
        try:
            return json.dumps(
                value,
                sort_keys=True,
                ensure_ascii=False,
                allow_nan=False,
                default=str,
            )

        except (
            TypeError,
            ValueError,
        ):
            return repr(
                value
            )

    return repr(
        value
    )


def notebook08_normalize_boolean_column(
    frame: pd.DataFrame,
    column_name: str,
) -> None:
    """Normalize one required boolean column in place."""

    if column_name not in frame.columns:
        raise Notebook08DiagnosticDispositionError(
            "A persisted Notebook 08 table lacks required boolean "
            f"column: {column_name}"
        )

    normalized = frame[
        column_name
    ].map(
        notebook08_boolean
    )

    unresolved_mask = normalized.isna()

    if unresolved_mask.any():
        unresolved_values = sorted(
            {
                repr(
                    value
                )
                for value in frame.loc[
                    unresolved_mask,
                    column_name,
                ]
            }
        )

        raise Notebook08DiagnosticDispositionError(
            "Unable to normalize a Notebook 08 boolean column.\n"
            f"Column: {column_name}\n"
            f"Values: {unresolved_values}"
        )

    frame[
        column_name
    ] = normalized.astype(
        bool
    )


def notebook08_assert_single_row(
    frame: pd.DataFrame,
    *,
    table_name: str,
) -> pd.Series:
    """Return the sole row of a required one-row table."""

    if len(
        frame
    ) != 1:
        raise Notebook08DiagnosticDispositionError(
            f"{table_name} must contain exactly one row; "
            f"observed {len(frame)}."
        )

    return frame.iloc[
        0
    ]


# ------------------------------------------------------------
# Bind persisted Notebook 08 control authorities
# ------------------------------------------------------------

REQUIRED_NOTEBOOK08_CONTROL_ROLES: Final[
    tuple[str, ...]
] = (
    "NOTEBOOK08_CORE_OUTPUT_MANIFEST",
    "NOTEBOOK08_FINAL_OUTPUT_MANIFEST",
    "NOTEBOOK08_FINAL_DISPOSITION",
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF",
    "NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
    "NOTEBOOK08_SEMANTIC_READBACK",
)

missing_notebook08_control_roles = sorted(
    role
    for role in REQUIRED_NOTEBOOK08_CONTROL_ROLES
    if not isinstance(
        stage_control_payloads.get(
            role
        ),
        Mapping,
    )
)

if missing_notebook08_control_roles:
    raise Notebook08DiagnosticDispositionError(
        "Required Notebook 08 control authorities are missing:\n"
        f"{missing_notebook08_control_roles}"
    )


notebook08_core_manifest = stage_control_payloads[
    "NOTEBOOK08_CORE_OUTPUT_MANIFEST"
]

notebook08_final_manifest = stage_control_payloads[
    "NOTEBOOK08_FINAL_OUTPUT_MANIFEST"
]

notebook08_final_disposition = stage_control_payloads[
    "NOTEBOOK08_FINAL_DISPOSITION"
]

notebook08_notebook09_blocked_handoff = stage_control_payloads[
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF"
]

notebook08_notebook10_audit_handoff = stage_control_payloads[
    "NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF"
]

notebook08_semantic_readback = stage_control_payloads[
    "NOTEBOOK08_SEMANTIC_READBACK"
]


# ------------------------------------------------------------
# Control-authority identity reconciliation
# ------------------------------------------------------------

expected_identity_values: Final[dict[str, str]] = {
    "source_run_prefix": str(
        SOURCE_RUN_PREFIX
    ),
    "source_set_sha256": str(
        SOURCE_SET_SHA256
    ),
    "v0_1_run_id": str(
        V01_RUN_ID
    ),
    "run_config_sha256": str(
        RUN_CONFIG_SHA256
    ),
    "run_identity_sha256": str(
        RUN_IDENTITY_SHA256
    ),
}

identity_authorities: dict[
    str,
    Mapping[str, Any],
] = {
    "NOTEBOOK08_CORE_OUTPUT_MANIFEST": (
        notebook08_core_manifest
    ),
    "NOTEBOOK08_FINAL_OUTPUT_MANIFEST": (
        notebook08_final_manifest
    ),
    "NOTEBOOK08_FINAL_DISPOSITION": (
        notebook08_final_disposition
    ),
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF": (
        notebook08_notebook09_blocked_handoff
    ),
    "NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF": (
        notebook08_notebook10_audit_handoff
    ),
}

identity_mismatch_records: list[
    dict[str, Any]
] = []

for authority_name, authority_payload in (
    identity_authorities.items()
):
    for identity_field, expected_value in (
        expected_identity_values.items()
    ):
        observed_value = authority_payload.get(
            identity_field
        )

        if observed_value != expected_value:
            identity_mismatch_records.append(
                {
                    "authority": authority_name,
                    "field": identity_field,
                    "observed": observed_value,
                    "expected": expected_value,
                }
            )


V01_NOTEBOOK08_IDENTITY_MISMATCH_AUDIT = pd.DataFrame(
    identity_mismatch_records,
    columns=[
        "authority",
        "field",
        "observed",
        "expected",
    ],
)

if not V01_NOTEBOOK08_IDENTITY_MISMATCH_AUDIT.empty:
    raise Notebook08DiagnosticDispositionError(
        "Notebook 08 control-authority identities do not "
        "reconcile:\n"
        + V01_NOTEBOOK08_IDENTITY_MISMATCH_AUDIT.to_string(
            index=False
        )
    )


# ------------------------------------------------------------
# Build the exact persisted artifact registry
# ------------------------------------------------------------

def notebook08_artifact_records_from_manifest(
    manifest: Mapping[str, Any],
) -> list[dict[str, Any]]:
    """Extract artifact records from one Notebook 08 manifest."""

    for collection_name in (
        "files",
        "artifacts",
    ):
        candidate = manifest.get(
            collection_name
        )

        if isinstance(
            candidate,
            list,
        ):
            return [
                dict(
                    record
                )
                for record in candidate
                if isinstance(
                    record,
                    Mapping,
                )
            ]

    return []


final_manifest_artifact_records = (
    notebook08_artifact_records_from_manifest(
        notebook08_final_manifest
    )
)

core_manifest_artifact_records = (
    notebook08_artifact_records_from_manifest(
        notebook08_core_manifest
    )
)

if not final_manifest_artifact_records:
    raise Notebook08DiagnosticDispositionError(
        "The Notebook 08 final output manifest contains no "
        "artifact records."
    )


notebook08_artifact_record_by_variable: dict[
    str,
    dict[str, Any],
] = {}

for record_source, artifact_records in (
    (
        "FINAL_OUTPUT_MANIFEST",
        final_manifest_artifact_records,
    ),
    (
        "CORE_OUTPUT_MANIFEST",
        core_manifest_artifact_records,
    ),
):
    for artifact_record in artifact_records:
        variable_name = str(
            artifact_record.get(
                "variable_name",
                "",
            )
        ).strip()

        if not variable_name:
            continue

        existing_record = notebook08_artifact_record_by_variable.get(
            variable_name
        )

        if existing_record is None:
            registered_record = dict(
                artifact_record
            )

            registered_record[
                "_record_source"
            ] = record_source

            notebook08_artifact_record_by_variable[
                variable_name
            ] = registered_record

            continue

        existing_path = str(
            existing_record.get(
                "path",
                "",
            )
        )

        candidate_path = str(
            artifact_record.get(
                "path",
                "",
            )
        )

        existing_sha256 = str(
            existing_record.get(
                "sha256",
                "",
            )
        ).lower()

        candidate_sha256 = str(
            artifact_record.get(
                "sha256",
                "",
            )
        ).lower()

        if (
            existing_path
            and candidate_path
            and notebook08_normalized_path(
                existing_path
            )
            != notebook08_normalized_path(
                candidate_path
            )
        ):
            raise Notebook08DiagnosticDispositionError(
                "Conflicting Notebook 08 artifact paths were "
                "registered.\n"
                f"Variable: {variable_name}\n"
                f"Path 1: {existing_path}\n"
                f"Path 2: {candidate_path}"
            )

        if (
            existing_sha256
            and candidate_sha256
            and existing_sha256
            != candidate_sha256
        ):
            raise Notebook08DiagnosticDispositionError(
                "Conflicting Notebook 08 artifact hashes were "
                "registered.\n"
                f"Variable: {variable_name}"
            )


# ------------------------------------------------------------
# Required quantitative evidence tables
# ------------------------------------------------------------

REQUIRED_NOTEBOOK08_QUANTITATIVE_TABLES: Final[
    tuple[str, ...]
] = (
    "HAWKES_DIAGNOSTIC_GATE_LEDGER",
    "HAWKES_MODEL_REJECTION_LEDGER",
    "FROZEN_HAWKES_SPECIFICATION_DISPOSITION",
    "NOTEBOOK08_TERMINAL_DECISION",
    "CALIBRATION_ENVELOPE_FAMILY_SUMMARY",
    "CALIBRATION_ENVELOPE_SCOPE_SUMMARY",
    "CALIBRATION_RESIDUAL_DISTRIBUTION_SCOPE_SUMMARY",
    "CALIBRATION_RESIDUAL_SERIAL_SCOPE_SUMMARY",
    "HAWKES_AND_BASELINE_LOCKED_CALIBRATION_RANKING",
    "HAWKES_VS_COUNT_BASELINE_BLOCK_BOOTSTRAP",
    "HAWKES_VS_FORMAL_COMPARATOR_RESULT",
    "HAWKES_VS_PRIMARY_SIMPLE_BASELINE_RESULT",
)

missing_notebook08_quantitative_tables = sorted(
    set(
        REQUIRED_NOTEBOOK08_QUANTITATIVE_TABLES
    )
    - set(
        notebook08_artifact_record_by_variable
    )
)

if missing_notebook08_quantitative_tables:
    raise Notebook08DiagnosticDispositionError(
        "The Notebook 08 manifests lack required quantitative "
        "tables:\n"
        f"{missing_notebook08_quantitative_tables}"
    )


# ------------------------------------------------------------
# Exact artifact resolution and readback
# ------------------------------------------------------------

def notebook08_resolve_artifact_path(
    artifact_record: Mapping[str, Any],
    *,
    variable_name: str,
) -> Path:
    """Resolve one exact registered Notebook 08 artifact path."""

    registered_path = artifact_record.get(
        "path"
    )

    if registered_path is None:
        raise Notebook08DiagnosticDispositionError(
            f"{variable_name} has no registered path."
        )

    registered_candidate = Path(
        str(
            registered_path
        )
    )

    path_candidates: list[Path] = []

    if registered_candidate.is_absolute():
        path_candidates.append(
            registered_candidate
        )

    else:
        path_candidates.extend(
            [
                V01_ROOT
                / registered_candidate,
                PROJECT_ROOT
                / registered_candidate,
                registered_candidate,
            ]
        )

    normalized_candidates: list[Path] = []

    for candidate in path_candidates:
        normalized_candidate = notebook08_normalized_path(
            candidate
        )

        if normalized_candidate not in normalized_candidates:
            normalized_candidates.append(
                normalized_candidate
            )

    existing_candidates = [
        candidate
        for candidate in normalized_candidates
        if candidate.is_file()
    ]

    if len(
        existing_candidates
    ) != 1:
        raise Notebook08DiagnosticDispositionError(
            "Unable to resolve exactly one persisted Notebook 08 "
            "artifact.\n"
            f"Variable: {variable_name}\n"
            f"Registered path: {registered_path}\n"
            f"Existing candidates: {existing_candidates}"
        )

    resolved_path = existing_candidates[
        0
    ]

    if not notebook08_path_inside(
        resolved_path,
        V01_ROOT,
    ):
        raise Notebook08DiagnosticDispositionError(
            "A Notebook 08 artifact lies outside V0.1.\n"
            f"Variable: {variable_name}\n"
            f"Path: {resolved_path}"
        )

    if notebook08_path_inside(
        resolved_path,
        V00_ROOT,
    ):
        raise Notebook08DiagnosticDispositionError(
            "A Notebook 08 output artifact lies inside V0.0.\n"
            f"Variable: {variable_name}\n"
            f"Path: {resolved_path}"
        )

    return resolved_path


def notebook08_read_registered_table(
    variable_name: str,
) -> tuple[pd.DataFrame, dict[str, Any]]:
    """Read and verify one persisted Notebook 08 DataFrame."""

    artifact_record = notebook08_artifact_record_by_variable[
        variable_name
    ]

    artifact_path = notebook08_resolve_artifact_path(
        artifact_record,
        variable_name=variable_name,
    )

    expected_sha256 = str(
        artifact_record.get(
            "sha256",
            "",
        )
    ).strip().lower()

    if not re.fullmatch(
        r"[0-9a-f]{64}",
        expected_sha256,
    ):
        raise Notebook08DiagnosticDispositionError(
            f"{variable_name} lacks a valid registered SHA-256."
        )

    observed_sha256 = notebook08_sha256_file(
        artifact_path
    )

    if observed_sha256 != expected_sha256:
        raise Notebook08DiagnosticDispositionError(
            "Notebook 08 artifact hash mismatch.\n"
            f"Variable: {variable_name}\n"
            f"Observed: {observed_sha256}\n"
            f"Expected: {expected_sha256}"
        )

    expected_size_value = artifact_record.get(
        "file_size_bytes",
        artifact_record.get(
            "size_bytes",
            artifact_record.get(
                "byte_count"
            ),
        ),
    )

    expected_size = notebook08_integer(
        expected_size_value
    )

    observed_size = int(
        artifact_path.stat().st_size
    )

    if (
        expected_size is not None
        and observed_size != expected_size
    ):
        raise Notebook08DiagnosticDispositionError(
            "Notebook 08 artifact byte-count mismatch.\n"
            f"Variable: {variable_name}\n"
            f"Observed: {observed_size}\n"
            f"Expected: {expected_size}"
        )

    registered_format = str(
        artifact_record.get(
            "format",
            "",
        )
    ).strip().upper()

    if registered_format in {
        "CSV_GZIP",
        "CSV.GZIP",
        "CSV_GZ",
    }:
        observed_frame = pd.read_csv(
            artifact_path,
            compression="gzip",
            low_memory=False,
        )

    elif registered_format == "PARQUET":
        observed_frame = pd.read_parquet(
            artifact_path
        )

    elif registered_format == "CSV":
        observed_frame = pd.read_csv(
            artifact_path,
            low_memory=False,
        )

    else:
        raise Notebook08DiagnosticDispositionError(
            "Unsupported persisted Notebook 08 table format.\n"
            f"Variable: {variable_name}\n"
            f"Format: {registered_format}"
        )

    expected_row_count = notebook08_integer(
        artifact_record.get(
            "row_count"
        )
    )

    expected_column_count = notebook08_integer(
        artifact_record.get(
            "column_count"
        )
    )

    if (
        expected_row_count is not None
        and len(
            observed_frame
        )
        != expected_row_count
    ):
        raise Notebook08DiagnosticDispositionError(
            "Notebook 08 table row-count mismatch.\n"
            f"Variable: {variable_name}\n"
            f"Observed: {len(observed_frame)}\n"
            f"Expected: {expected_row_count}"
        )

    if (
        expected_column_count is not None
        and observed_frame.shape[
            1
        ]
        != expected_column_count
    ):
        raise Notebook08DiagnosticDispositionError(
            "Notebook 08 table column-count mismatch.\n"
            f"Variable: {variable_name}\n"
            f"Observed: {observed_frame.shape[1]}\n"
            f"Expected: {expected_column_count}"
        )

    registered_columns = artifact_record.get(
        "columns"
    )

    if isinstance(
        registered_columns,
        list,
    ):
        expected_columns = [
            str(
                column
            )
            for column in registered_columns
        ]

        observed_columns = list(
            map(
                str,
                observed_frame.columns,
            )
        )

        if observed_columns != expected_columns:
            raise Notebook08DiagnosticDispositionError(
                "Notebook 08 table column order differs from the "
                "manifest.\n"
                f"Variable: {variable_name}"
            )

    readback_record = {
        "variable_name": variable_name,
        "artifact_role": str(
            artifact_record.get(
                "artifact_role",
                "",
            )
        ),
        "record_source": str(
            artifact_record.get(
                "_record_source",
                "",
            )
        ),
        "path": str(
            artifact_path
        ),
        "format": registered_format,
        "row_count": int(
            len(
                observed_frame
            )
        ),
        "column_count": int(
            observed_frame.shape[
                1
            ]
        ),
        "size_bytes": observed_size,
        "sha256": observed_sha256,
        "hash_matches": True,
        "shape_matches": True,
        "column_order_matches": True,
        "status": "PASS",
    }

    return (
        observed_frame,
        readback_record,
    )


NOTEBOOK08_QUANTITATIVE_TABLES: dict[
    str,
    pd.DataFrame,
] = {}

notebook08_quantitative_readback_records: list[
    dict[str, Any]
] = []

for required_table_name in (
    REQUIRED_NOTEBOOK08_QUANTITATIVE_TABLES
):
    (
        loaded_table,
        loaded_table_audit,
    ) = notebook08_read_registered_table(
        required_table_name
    )

    NOTEBOOK08_QUANTITATIVE_TABLES[
        required_table_name
    ] = loaded_table.copy(
        deep=True
    )

    notebook08_quantitative_readback_records.append(
        loaded_table_audit
    )


V01_NOTEBOOK08_QUANTITATIVE_TABLE_READBACK_AUDIT = (
    pd.DataFrame(
        notebook08_quantitative_readback_records
    )
    .sort_values(
        "variable_name",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


# ------------------------------------------------------------
# Stable table bindings
# ------------------------------------------------------------

HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "HAWKES_DIAGNOSTIC_GATE_LEDGER"
    ]
)

HAWKES_MODEL_REJECTION_LEDGER_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "HAWKES_MODEL_REJECTION_LEDGER"
    ]
)

FROZEN_HAWKES_SPECIFICATION_DISPOSITION_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "FROZEN_HAWKES_SPECIFICATION_DISPOSITION"
    ]
)

NOTEBOOK08_TERMINAL_DECISION_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "NOTEBOOK08_TERMINAL_DECISION"
    ]
)

CALIBRATION_ENVELOPE_FAMILY_SUMMARY_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "CALIBRATION_ENVELOPE_FAMILY_SUMMARY"
    ]
)

CALIBRATION_ENVELOPE_SCOPE_SUMMARY_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "CALIBRATION_ENVELOPE_SCOPE_SUMMARY"
    ]
)

CALIBRATION_RESIDUAL_DISTRIBUTION_SCOPE_SUMMARY_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "CALIBRATION_RESIDUAL_DISTRIBUTION_SCOPE_SUMMARY"
    ]
)

CALIBRATION_RESIDUAL_SERIAL_SCOPE_SUMMARY_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "CALIBRATION_RESIDUAL_SERIAL_SCOPE_SUMMARY"
    ]
)

HAWKES_AND_BASELINE_LOCKED_CALIBRATION_RANKING_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "HAWKES_AND_BASELINE_LOCKED_CALIBRATION_RANKING"
    ]
)

HAWKES_VS_COUNT_BASELINE_BLOCK_BOOTSTRAP_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "HAWKES_VS_COUNT_BASELINE_BLOCK_BOOTSTRAP"
    ]
)

HAWKES_VS_FORMAL_COMPARATOR_RESULT_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "HAWKES_VS_FORMAL_COMPARATOR_RESULT"
    ]
)

HAWKES_VS_PRIMARY_SIMPLE_BASELINE_RESULT_AUDIT = (
    NOTEBOOK08_QUANTITATIVE_TABLES[
        "HAWKES_VS_PRIMARY_SIMPLE_BASELINE_RESULT"
    ]
)


# ------------------------------------------------------------
# Normalize required persisted booleans
# ------------------------------------------------------------

for boolean_column in (
    "blocking",
    "passed",
):
    notebook08_normalize_boolean_column(
        HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT,
        boolean_column,
    )

for boolean_column in (
    "repair_performed",
    "parameter_refit_performed",
):
    notebook08_normalize_boolean_column(
        HAWKES_MODEL_REJECTION_LEDGER_AUDIT,
        boolean_column,
    )

for boolean_column in (
    "count_score_superiority_authorized",
    "full_model_adequacy_authorized",
    "full_hawkes_superiority_authorized",
    "cross_excitation_authorized",
    "state_dependent_hawkes_authorized",
    "parameter_refit_performed",
):
    notebook08_normalize_boolean_column(
        FROZEN_HAWKES_SPECIFICATION_DISPOSITION_AUDIT,
        boolean_column,
    )

for boolean_column in (
    "count_score_superiority_authorized",
    "stationarity_margin_passed",
    "calibration_residual_distribution_passed",
    "calibration_residual_serial_passed",
    "calibration_path_count_passed",
    "calibration_multiplicity_passed",
    "calibration_side_mark_passed",
    "calibration_model_adequacy_passed",
    "cross_excitation_authorized",
    "state_dependent_hawkes_authorized",
    "full_hawkes_superiority_authorized",
    "notebook09_authorized",
    "validation_partition_opening_authorized",
    "engineering_holdout_opened",
):
    notebook08_normalize_boolean_column(
        NOTEBOOK08_TERMINAL_DECISION_AUDIT,
        boolean_column,
    )

for summary_frame in (
    CALIBRATION_ENVELOPE_FAMILY_SUMMARY_AUDIT,
    CALIBRATION_ENVELOPE_SCOPE_SUMMARY_AUDIT,
    CALIBRATION_RESIDUAL_DISTRIBUTION_SCOPE_SUMMARY_AUDIT,
    CALIBRATION_RESIDUAL_SERIAL_SCOPE_SUMMARY_AUDIT,
):
    notebook08_normalize_boolean_column(
        summary_frame,
        "within_declared_adequacy_tolerance",
    )

notebook08_normalize_boolean_column(
    HAWKES_AND_BASELINE_LOCKED_CALIBRATION_RANKING_AUDIT,
    "score_only_superiority_claim_authorized",
)

for boolean_column in (
    "formal_comparator_flag",
    "primary_simple_baseline_flag",
    "positive_improvement_supported_at_95pct",
    "negative_difference_supported_at_95pct",
    "full_hawkes_superiority_claim_authorized",
):
    notebook08_normalize_boolean_column(
        HAWKES_VS_COUNT_BASELINE_BLOCK_BOOTSTRAP_AUDIT,
        boolean_column,
    )

for comparator_frame in (
    HAWKES_VS_FORMAL_COMPARATOR_RESULT_AUDIT,
    HAWKES_VS_PRIMARY_SIMPLE_BASELINE_RESULT_AUDIT,
):
    for boolean_column in (
        "formal_comparator_flag",
        "primary_simple_baseline_flag",
        "positive_improvement_supported_at_95pct",
        "negative_difference_supported_at_95pct",
        "full_hawkes_superiority_claim_authorized",
    ):
        notebook08_normalize_boolean_column(
            comparator_frame,
            boolean_column,
        )


# ------------------------------------------------------------
# Audit-record machinery
# ------------------------------------------------------------

notebook08_disposition_checks: list[
    dict[str, Any]
] = []


def register_notebook08_disposition_check(
    *,
    category: str,
    check_name: str,
    observed: Any,
    expected: Any,
    passed: bool | None = None,
    blocking: bool = True,
) -> None:
    """Register one deterministic Notebook 08 audit check."""

    check_passed = (
        observed == expected
        if passed is None
        else bool(
            passed
        )
    )

    notebook08_disposition_checks.append(
        {
            "check_order": int(
                len(
                    notebook08_disposition_checks
                )
                + 1
            ),
            "category": category,
            "check_name": check_name,
            "blocking": bool(
                blocking
            ),
            "passed": bool(
                check_passed
            ),
            "status": (
                "PASS"
                if check_passed
                else (
                    "FAIL"
                    if blocking
                    else "WARNING"
                )
            ),
            "observed": notebook08_render(
                observed
            ),
            "expected": notebook08_render(
                expected
            ),
        }
    )


# ------------------------------------------------------------
# Diagnostic-gate ledger audit
# ------------------------------------------------------------

required_gate_columns = {
    "gate_order",
    "gate_id",
    "gate_family",
    "blocking",
    "passed",
    "observed_value",
    "reference_value",
    "decision_rule",
    "status",
}

missing_gate_columns = sorted(
    required_gate_columns
    - set(
        HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT.columns
    )
)

if missing_gate_columns:
    raise Notebook08DiagnosticDispositionError(
        "The Notebook 08 diagnostic-gate ledger lacks required "
        f"columns: {missing_gate_columns}"
    )


observed_gate_ids = set(
    HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT[
        "gate_id"
    ].astype(
        str
    )
)

register_notebook08_disposition_check(
    category="GATE_LEDGER",
    check_name="complete_gate_set",
    observed=observed_gate_ids,
    expected=EXPECTED_NOTEBOOK08_ALL_GATES,
)

register_notebook08_disposition_check(
    category="GATE_LEDGER",
    check_name="gate_ids_are_unique",
    observed=bool(
        HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT[
            "gate_id"
        ].is_unique
    ),
    expected=True,
)

blocking_gate_rows = (
    HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT.loc[
        HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT[
            "blocking"
        ]
    ]
)

failed_blocking_gate_rows = (
    blocking_gate_rows.loc[
        ~blocking_gate_rows[
            "passed"
        ]
    ]
)

passed_blocking_gate_rows = (
    blocking_gate_rows.loc[
        blocking_gate_rows[
            "passed"
        ]
    ]
)

observed_failed_gate_ids = set(
    failed_blocking_gate_rows[
        "gate_id"
    ].astype(
        str
    )
)

register_notebook08_disposition_check(
    category="GATE_LEDGER",
    check_name="blocking_gate_count",
    observed=int(
        len(
            blocking_gate_rows
        )
    ),
    expected=12,
)

register_notebook08_disposition_check(
    category="GATE_LEDGER",
    check_name="passed_blocking_gate_count",
    observed=int(
        len(
            passed_blocking_gate_rows
        )
    ),
    expected=8,
)

register_notebook08_disposition_check(
    category="GATE_LEDGER",
    check_name="failed_blocking_gate_count",
    observed=int(
        len(
            failed_blocking_gate_rows
        )
    ),
    expected=4,
)

register_notebook08_disposition_check(
    category="GATE_LEDGER",
    check_name="exact_failed_blocking_gate_set",
    observed=observed_failed_gate_ids,
    expected=EXPECTED_NOTEBOOK08_FAILED_GATES,
)


score_gate_rows = (
    HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT.loc[
        HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT[
            "gate_id"
        ].isin(
            EXPECTED_NOTEBOOK08_SCORE_GATES
        )
    ]
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="all_score_superiority_gates_passed",
    observed=bool(
        len(
            score_gate_rows
        )
        == 3
        and score_gate_rows[
            "passed"
        ].all()
    ),
    expected=True,
)

stationarity_gate_rows = (
    HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT.loc[
        HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT[
            "gate_id"
        ].eq(
            "DEFENSIBLE_STATIONARITY_MARGIN"
        )
    ]
)

register_notebook08_disposition_check(
    category="MODEL_INTEGRITY",
    check_name="stationarity_margin_gate_passed",
    observed=bool(
        len(
            stationarity_gate_rows
        )
        == 1
        and stationarity_gate_rows.iloc[
            0
        ][
            "passed"
        ]
    ),
    expected=True,
)

side_mark_gate_rows = (
    HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT.loc[
        HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT[
            "gate_id"
        ].eq(
            "LOCKED_CALIBRATION_SIDE_MARK_CALIBRATION"
        )
    ]
)

register_notebook08_disposition_check(
    category="MODEL_ADEQUACY",
    check_name="side_mark_directional_gate_passed",
    observed=bool(
        len(
            side_mark_gate_rows
        )
        == 1
        and side_mark_gate_rows.iloc[
            0
        ][
            "passed"
        ]
    ),
    expected=True,
)

cross_side_formal_rows = (
    HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT.loc[
        HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT[
            "gate_id"
        ].eq(
            "CROSS_SIDE_FORMAL_SIMULATION_ENVELOPE"
        )
    ]
)

register_notebook08_disposition_check(
    category="CROSS_SIDE_SCOPE",
    check_name="formal_cross_side_envelope_not_completed_and_nonblocking",
    observed=bool(
        len(
            cross_side_formal_rows
        )
        == 1
        and not cross_side_formal_rows.iloc[
            0
        ][
            "blocking"
        ]
        and not cross_side_formal_rows.iloc[
            0
        ][
            "passed"
        ]
        and str(
            cross_side_formal_rows.iloc[
                0
            ][
                "status"
            ]
        )
        == "NOT_COMPLETED"
    ),
    expected=True,
)

for governance_gate_id in (
    "CALIBRATION_PARAMETER_UPDATES_ZERO",
    "PROTECTED_PARTITIONS_UNOPENED",
    "FILESYSTEM_WRITES_ABSENT",
):
    governance_gate_rows = (
        HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT.loc[
            HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT[
                "gate_id"
            ].eq(
                governance_gate_id
            )
        ]
    )

    register_notebook08_disposition_check(
        category="GOVERNANCE",
        check_name=f"{governance_gate_id.casefold()}::passed",
        observed=bool(
            len(
                governance_gate_rows
            )
            == 1
            and governance_gate_rows.iloc[
                0
            ][
                "passed"
            ]
        ),
        expected=True,
    )


# ------------------------------------------------------------
# Rejection-ledger audit
# ------------------------------------------------------------

required_rejection_columns = {
    "rejection_order",
    "model_id",
    "gate_id",
    "gate_family",
    "repair_performed",
    "parameter_refit_performed",
    "calibration_parameter_updates",
    "status",
}

missing_rejection_columns = sorted(
    required_rejection_columns
    - set(
        HAWKES_MODEL_REJECTION_LEDGER_AUDIT.columns
    )
)

if missing_rejection_columns:
    raise Notebook08DiagnosticDispositionError(
        "The Notebook 08 model-rejection ledger lacks required "
        f"columns: {missing_rejection_columns}"
    )


register_notebook08_disposition_check(
    category="REJECTION_LEDGER",
    check_name="rejection_row_count",
    observed=int(
        len(
            HAWKES_MODEL_REJECTION_LEDGER_AUDIT
        )
    ),
    expected=4,
)

register_notebook08_disposition_check(
    category="REJECTION_LEDGER",
    check_name="rejection_gate_set_matches_failed_blocking_gates",
    observed=set(
        HAWKES_MODEL_REJECTION_LEDGER_AUDIT[
            "gate_id"
        ].astype(
            str
        )
    ),
    expected=EXPECTED_NOTEBOOK08_FAILED_GATES,
)

register_notebook08_disposition_check(
    category="REJECTION_LEDGER",
    check_name="rejected_model_identity",
    observed=set(
        HAWKES_MODEL_REJECTION_LEDGER_AUDIT[
            "model_id"
        ].astype(
            str
        )
    ),
    expected={
        EXPECTED_NOTEBOOK08_SELECTED_MODEL_ID,
    },
)

register_notebook08_disposition_check(
    category="REJECTION_LEDGER",
    check_name="all_rejections_are_model_adequacy_failures",
    observed=set(
        HAWKES_MODEL_REJECTION_LEDGER_AUDIT[
            "gate_family"
        ].astype(
            str
        )
    ),
    expected={
        "MODEL_ADEQUACY",
    },
)

register_notebook08_disposition_check(
    category="REJECTION_LEDGER",
    check_name="no_repair_performed",
    observed=int(
        HAWKES_MODEL_REJECTION_LEDGER_AUDIT[
            "repair_performed"
        ].sum()
    ),
    expected=0,
)

register_notebook08_disposition_check(
    category="REJECTION_LEDGER",
    check_name="no_parameter_refit_performed",
    observed=int(
        HAWKES_MODEL_REJECTION_LEDGER_AUDIT[
            "parameter_refit_performed"
        ].sum()
    ),
    expected=0,
)

register_notebook08_disposition_check(
    category="REJECTION_LEDGER",
    check_name="calibration_parameter_updates_remain_zero",
    observed=set(
        pd.to_numeric(
            HAWKES_MODEL_REJECTION_LEDGER_AUDIT[
                "calibration_parameter_updates"
            ],
            errors="raise",
        ).astype(
            int
        )
    ),
    expected={
        0,
    },
)

register_notebook08_disposition_check(
    category="REJECTION_LEDGER",
    check_name="all_rejection_statuses_are_blocking",
    observed=set(
        HAWKES_MODEL_REJECTION_LEDGER_AUDIT[
            "status"
        ].astype(
            str
        )
    ),
    expected={
        "BLOCKING_REJECTION",
    },
)


# ------------------------------------------------------------
# Envelope-family quantitative audit
# ------------------------------------------------------------

required_family_columns = {
    "diagnostic_family",
    "metric_count",
    "outside_directional_envelope_count",
    "within_declared_adequacy_tolerance",
    "status",
}

missing_family_columns = sorted(
    required_family_columns
    - set(
        CALIBRATION_ENVELOPE_FAMILY_SUMMARY_AUDIT.columns
    )
)

if missing_family_columns:
    raise Notebook08DiagnosticDispositionError(
        "The Notebook 08 envelope-family summary lacks required "
        f"columns: {missing_family_columns}"
    )


observed_family_names = set(
    CALIBRATION_ENVELOPE_FAMILY_SUMMARY_AUDIT[
        "diagnostic_family"
    ].astype(
        str
    )
)

register_notebook08_disposition_check(
    category="ENVELOPE_FAMILY",
    check_name="complete_diagnostic_family_set",
    observed=observed_family_names,
    expected=set(
        EXPECTED_NOTEBOOK08_FAMILY_RESULTS
    ),
)

for diagnostic_family, expected_family_values in (
    EXPECTED_NOTEBOOK08_FAMILY_RESULTS.items()
):
    matching_family_rows = (
        CALIBRATION_ENVELOPE_FAMILY_SUMMARY_AUDIT.loc[
            CALIBRATION_ENVELOPE_FAMILY_SUMMARY_AUDIT[
                "diagnostic_family"
            ].eq(
                diagnostic_family
            )
        ]
    )

    if len(
        matching_family_rows
    ) != 1:
        raise Notebook08DiagnosticDispositionError(
            "Expected exactly one envelope-family row for "
            f"{diagnostic_family}."
        )

    family_row = matching_family_rows.iloc[
        0
    ]

    register_notebook08_disposition_check(
        category="ENVELOPE_FAMILY",
        check_name=f"{diagnostic_family}::metric_count",
        observed=int(
            family_row[
                "metric_count"
            ]
        ),
        expected=int(
            expected_family_values[
                "metric_count"
            ]
        ),
    )

    register_notebook08_disposition_check(
        category="ENVELOPE_FAMILY",
        check_name=(
            f"{diagnostic_family}"
            "::outside_directional_envelope_count"
        ),
        observed=int(
            family_row[
                "outside_directional_envelope_count"
            ]
        ),
        expected=int(
            expected_family_values[
                "outside_directional_envelope_count"
            ]
        ),
    )

    register_notebook08_disposition_check(
        category="ENVELOPE_FAMILY",
        check_name=(
            f"{diagnostic_family}"
            "::within_declared_adequacy_tolerance"
        ),
        observed=bool(
            family_row[
                "within_declared_adequacy_tolerance"
            ]
        ),
        expected=bool(
            expected_family_values[
                "within_declared_adequacy_tolerance"
            ]
        ),
    )


# ------------------------------------------------------------
# Residual scope audit
# ------------------------------------------------------------

EXPECTED_RESIDUAL_SCOPES: Final[set[str]] = {
    "BUY",
    "POOLED",
    "SELL",
}

for scope_table_name, scope_frame in (
    (
        "CALIBRATION_RESIDUAL_DISTRIBUTION_SCOPE_SUMMARY",
        CALIBRATION_RESIDUAL_DISTRIBUTION_SCOPE_SUMMARY_AUDIT,
    ),
    (
        "CALIBRATION_RESIDUAL_SERIAL_SCOPE_SUMMARY",
        CALIBRATION_RESIDUAL_SERIAL_SCOPE_SUMMARY_AUDIT,
    ),
):
    if "diagnostic_scope" not in scope_frame.columns:
        raise Notebook08DiagnosticDispositionError(
            f"{scope_table_name} lacks diagnostic_scope."
        )

    register_notebook08_disposition_check(
        category="RESIDUAL_SCOPE",
        check_name=f"{scope_table_name}::complete_scope_set",
        observed=set(
            scope_frame[
                "diagnostic_scope"
            ].astype(
                str
            )
        ),
        expected=EXPECTED_RESIDUAL_SCOPES,
    )

    register_notebook08_disposition_check(
        category="RESIDUAL_SCOPE",
        check_name=(
            f"{scope_table_name}"
            "::all_scopes_fail_adequacy_tolerance"
        ),
        observed=bool(
            (
                ~scope_frame[
                    "within_declared_adequacy_tolerance"
                ]
            ).all()
        ),
        expected=True,
    )


# ------------------------------------------------------------
# Locked CALIBRATION count-score evidence
# ------------------------------------------------------------

required_ranking_columns = {
    "calibration_score_rank",
    "model_id",
    "candidate_role",
    "log_score_total",
    "log_score_improvement_over_formal_comparator",
    "log_score_improvement_over_primary_simple_baseline",
    "score_only_superiority_claim_authorized",
    "status",
}

missing_ranking_columns = sorted(
    required_ranking_columns
    - set(
        HAWKES_AND_BASELINE_LOCKED_CALIBRATION_RANKING_AUDIT.columns
    )
)

if missing_ranking_columns:
    raise Notebook08DiagnosticDispositionError(
        "The Notebook 08 Hawkes/baseline ranking lacks required "
        f"columns: {missing_ranking_columns}"
    )


ranking_frame = (
    HAWKES_AND_BASELINE_LOCKED_CALIBRATION_RANKING_AUDIT.sort_values(
        [
            "calibration_score_rank",
            "model_id",
        ],
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)

h1_ranking_rows = ranking_frame.loc[
    ranking_frame[
        "model_id"
    ].eq(
        EXPECTED_NOTEBOOK08_SELECTED_MODEL_ID
    )
]

if len(
    h1_ranking_rows
) != 1:
    raise Notebook08DiagnosticDispositionError(
        "The locked CALIBRATION ranking does not contain exactly "
        "one H1 row."
    )

h1_ranking_row = h1_ranking_rows.iloc[
    0
]

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="h1_is_locked_calibration_rank_one",
    observed=int(
        h1_ranking_row[
            "calibration_score_rank"
        ]
    ),
    expected=1,
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="h1_candidate_role_is_frozen_hawkes",
    observed=str(
        h1_ranking_row[
            "candidate_role"
        ]
    ),
    expected="FROZEN_HAWKES",
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="h1_score_improves_over_formal_comparator",
    observed=float(
        h1_ranking_row[
            "log_score_improvement_over_formal_comparator"
        ]
    ),
    expected="STRICTLY POSITIVE",
    passed=float(
        h1_ranking_row[
            "log_score_improvement_over_formal_comparator"
        ]
    )
    > 0.0,
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="h1_score_improves_over_primary_simple_baseline",
    observed=float(
        h1_ranking_row[
            "log_score_improvement_over_primary_simple_baseline"
        ]
    ),
    expected="STRICTLY POSITIVE",
    passed=float(
        h1_ranking_row[
            "log_score_improvement_over_primary_simple_baseline"
        ]
    )
    > 0.0,
)

register_notebook08_disposition_check(
    category="CLAIM_BOUNDARY",
    check_name="ranking_does_not_authorize_full_superiority_claim",
    observed=int(
        ranking_frame[
            "score_only_superiority_claim_authorized"
        ].sum()
    ),
    expected=0,
)


# ------------------------------------------------------------
# Paired block-bootstrap evidence
# ------------------------------------------------------------

required_bootstrap_columns = {
    "candidate_model_id",
    "comparator_model_id",
    "formal_comparator_flag",
    "primary_simple_baseline_flag",
    "bootstrap_total_difference_q025",
    "positive_improvement_supported_at_95pct",
    "negative_difference_supported_at_95pct",
    "full_hawkes_superiority_claim_authorized",
    "status",
}

missing_bootstrap_columns = sorted(
    required_bootstrap_columns
    - set(
        HAWKES_VS_COUNT_BASELINE_BLOCK_BOOTSTRAP_AUDIT.columns
    )
)

if missing_bootstrap_columns:
    raise Notebook08DiagnosticDispositionError(
        "The Notebook 08 paired-bootstrap table lacks required "
        f"columns: {missing_bootstrap_columns}"
    )


bootstrap_frame = (
    HAWKES_VS_COUNT_BASELINE_BLOCK_BOOTSTRAP_AUDIT.copy(
        deep=True
    )
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="bootstrap_comparator_set",
    observed=set(
        bootstrap_frame[
            "comparator_model_id"
        ].astype(
            str
        )
    ),
    expected=EXPECTED_NOTEBOOK08_BOOTSTRAP_COMPARATORS,
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="bootstrap_candidate_is_frozen_h1",
    observed=set(
        bootstrap_frame[
            "candidate_model_id"
        ].astype(
            str
        )
    ),
    expected={
        EXPECTED_NOTEBOOK08_SELECTED_MODEL_ID,
    },
)

bootstrap_q025 = pd.to_numeric(
    bootstrap_frame[
        "bootstrap_total_difference_q025"
    ],
    errors="raise",
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="every_bootstrap_q025_is_positive",
    observed=float(
        bootstrap_q025.min()
    ),
    expected="STRICTLY POSITIVE",
    passed=bool(
        bootstrap_q025.gt(
            0.0
        ).all()
    ),
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="every_comparator_has_supported_positive_improvement",
    observed=bool(
        bootstrap_frame[
            "positive_improvement_supported_at_95pct"
        ].all()
    ),
    expected=True,
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="no_negative_difference_is_supported",
    observed=int(
        bootstrap_frame[
            "negative_difference_supported_at_95pct"
        ].sum()
    ),
    expected=0,
)

register_notebook08_disposition_check(
    category="CLAIM_BOUNDARY",
    check_name="bootstrap_does_not_authorize_full_hawkes_superiority",
    observed=int(
        bootstrap_frame[
            "full_hawkes_superiority_claim_authorized"
        ].sum()
    ),
    expected=0,
)


formal_comparator_row = notebook08_assert_single_row(
    HAWKES_VS_FORMAL_COMPARATOR_RESULT_AUDIT,
    table_name="HAWKES_VS_FORMAL_COMPARATOR_RESULT",
)

primary_simple_row = notebook08_assert_single_row(
    HAWKES_VS_PRIMARY_SIMPLE_BASELINE_RESULT_AUDIT,
    table_name="HAWKES_VS_PRIMARY_SIMPLE_BASELINE_RESULT",
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="formal_comparator_result_identity",
    observed=str(
        formal_comparator_row[
            "comparator_model_id"
        ]
    ),
    expected="D0_SIDE_CONSTANT_POISSON",
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="formal_comparator_positive_improvement_supported",
    observed=bool(
        formal_comparator_row[
            "positive_improvement_supported_at_95pct"
        ]
    ),
    expected=True,
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="primary_simple_result_identity",
    observed=str(
        primary_simple_row[
            "comparator_model_id"
        ]
    ),
    expected="E_SIDE_EWMA_250MS_POISSON",
)

register_notebook08_disposition_check(
    category="NARROW_SCORE_EVIDENCE",
    check_name="primary_simple_positive_improvement_supported",
    observed=bool(
        primary_simple_row[
            "positive_improvement_supported_at_95pct"
        ]
    ),
    expected=True,
)


# ------------------------------------------------------------
# Frozen-H1 disposition table audit
# ------------------------------------------------------------

frozen_disposition_row = notebook08_assert_single_row(
    FROZEN_HAWKES_SPECIFICATION_DISPOSITION_AUDIT,
    table_name="FROZEN_HAWKES_SPECIFICATION_DISPOSITION",
)

register_notebook08_disposition_check(
    category="FROZEN_DISPOSITION",
    check_name="selected_model_id",
    observed=str(
        frozen_disposition_row[
            "model_id"
        ]
    ),
    expected=EXPECTED_NOTEBOOK08_SELECTED_MODEL_ID,
)

register_notebook08_disposition_check(
    category="FROZEN_DISPOSITION",
    check_name="selected_model_family",
    observed=str(
        frozen_disposition_row[
            "model_family"
        ]
    ),
    expected=EXPECTED_NOTEBOOK08_SELECTED_MODEL_FAMILY,
)

register_notebook08_disposition_check(
    category="FROZEN_DISPOSITION",
    check_name="fitted_partition",
    observed=str(
        frozen_disposition_row[
            "fitted_partition"
        ]
    ),
    expected="DEVELOPMENT",
)

register_notebook08_disposition_check(
    category="FROZEN_DISPOSITION",
    check_name="locked_evaluation_partition",
    observed=str(
        frozen_disposition_row[
            "locked_evaluation_partition"
        ]
    ),
    expected="CALIBRATION",
)

register_notebook08_disposition_check(
    category="FROZEN_DISPOSITION",
    check_name="spectral_radius_below_one",
    observed=float(
        frozen_disposition_row[
            "spectral_radius"
        ]
    ),
    expected="STRICTLY BELOW ONE",
    passed=bool(
        0.0
        <= float(
            frozen_disposition_row[
                "spectral_radius"
            ]
        )
        < 1.0
    ),
)

register_notebook08_disposition_check(
    category="FROZEN_DISPOSITION",
    check_name="count_score_superiority_authorized",
    observed=bool(
        frozen_disposition_row[
            "count_score_superiority_authorized"
        ]
    ),
    expected=True,
)

for false_disposition_field in (
    "full_model_adequacy_authorized",
    "full_hawkes_superiority_authorized",
    "cross_excitation_authorized",
    "state_dependent_hawkes_authorized",
    "parameter_refit_performed",
):
    register_notebook08_disposition_check(
        category="FROZEN_DISPOSITION",
        check_name=f"{false_disposition_field}::false",
        observed=bool(
            frozen_disposition_row[
                false_disposition_field
            ]
        ),
        expected=False,
    )

register_notebook08_disposition_check(
    category="FROZEN_DISPOSITION",
    check_name="calibration_parameter_updates",
    observed=int(
        frozen_disposition_row[
            "calibration_parameter_updates"
        ]
    ),
    expected=0,
)

register_notebook08_disposition_check(
    category="FROZEN_DISPOSITION",
    check_name="diagnostic_disposition",
    observed=str(
        frozen_disposition_row[
            "diagnostic_disposition"
        ]
    ),
    expected=EXPECTED_NOTEBOOK08_DISPOSITION,
)

register_notebook08_disposition_check(
    category="FROZEN_DISPOSITION",
    check_name="allowed_downstream_role",
    observed=str(
        frozen_disposition_row[
            "allowed_downstream_role"
        ]
    ),
    expected=EXPECTED_NOTEBOOK08_ALLOWED_ROLE,
)

register_notebook08_disposition_check(
    category="FROZEN_DISPOSITION",
    check_name="terminal_status_is_fail",
    observed=str(
        frozen_disposition_row[
            "status"
        ]
    ),
    expected="FAIL",
)


# ------------------------------------------------------------
# Terminal-decision table audit
# ------------------------------------------------------------

terminal_decision_row = notebook08_assert_single_row(
    NOTEBOOK08_TERMINAL_DECISION_AUDIT,
    table_name="NOTEBOOK08_TERMINAL_DECISION",
)

register_notebook08_disposition_check(
    category="TERMINAL_DECISION",
    check_name="terminal_class",
    observed=str(
        terminal_decision_row[
            "terminal_class"
        ]
    ),
    expected=EXPECTED_NOTEBOOK08_TERMINAL_CLASS,
)

register_notebook08_disposition_check(
    category="TERMINAL_DECISION",
    check_name="terminal_status",
    observed=str(
        terminal_decision_row[
            "terminal_status"
        ]
    ),
    expected=EXPECTED_NOTEBOOK08_TERMINAL_STATUS,
)

register_notebook08_disposition_check(
    category="TERMINAL_DECISION",
    check_name="blocking_gate_count",
    observed=int(
        terminal_decision_row[
            "blocking_gate_count"
        ]
    ),
    expected=12,
)

register_notebook08_disposition_check(
    category="TERMINAL_DECISION",
    check_name="passed_blocking_gate_count",
    observed=int(
        terminal_decision_row[
            "passed_blocking_gate_count"
        ]
    ),
    expected=8,
)

register_notebook08_disposition_check(
    category="TERMINAL_DECISION",
    check_name="failed_blocking_gate_count",
    observed=int(
        terminal_decision_row[
            "failed_blocking_gate_count"
        ]
    ),
    expected=4,
)

EXPECTED_TERMINAL_BOOLEAN_VALUES: Final[
    dict[str, bool]
] = {
    "count_score_superiority_authorized": True,
    "stationarity_margin_passed": True,
    "calibration_residual_distribution_passed": False,
    "calibration_residual_serial_passed": False,
    "calibration_path_count_passed": False,
    "calibration_multiplicity_passed": False,
    "calibration_side_mark_passed": True,
    "calibration_model_adequacy_passed": False,
    "cross_excitation_authorized": False,
    "state_dependent_hawkes_authorized": False,
    "full_hawkes_superiority_authorized": False,
    "notebook09_authorized": False,
    "validation_partition_opening_authorized": False,
    "engineering_holdout_opened": False,
}

for terminal_field, expected_value in (
    EXPECTED_TERMINAL_BOOLEAN_VALUES.items()
):
    register_notebook08_disposition_check(
        category="TERMINAL_DECISION",
        check_name=f"{terminal_field}::value",
        observed=bool(
            terminal_decision_row[
                terminal_field
            ]
        ),
        expected=expected_value,
    )

register_notebook08_disposition_check(
    category="TERMINAL_DECISION",
    check_name="calibration_parameter_updates_zero",
    observed=int(
        terminal_decision_row[
            "calibration_parameter_updates"
        ]
    ),
    expected=0,
)


# ------------------------------------------------------------
# Final-disposition JSON audit
# ------------------------------------------------------------

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="selected_model_id",
    observed=notebook08_final_disposition.get(
        "selected_model_id"
    ),
    expected=EXPECTED_NOTEBOOK08_SELECTED_MODEL_ID,
)

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="terminal_class",
    observed=notebook08_final_disposition.get(
        "terminal_class"
    ),
    expected=EXPECTED_NOTEBOOK08_TERMINAL_CLASS,
)

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="terminal_status",
    observed=notebook08_final_disposition.get(
        "terminal_status"
    ),
    expected=EXPECTED_NOTEBOOK08_TERMINAL_STATUS,
)

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="failed_blocking_gate_count",
    observed=notebook08_final_disposition.get(
        "failed_blocking_gate_count"
    ),
    expected=4,
)

final_failed_gate_records = notebook08_final_disposition.get(
    "failed_blocking_gates",
    [],
)

final_failed_gate_ids = {
    str(
        record.get(
            "gate_id"
        )
    )
    for record in final_failed_gate_records
    if isinstance(
        record,
        Mapping,
    )
}

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="failed_blocking_gate_set",
    observed=final_failed_gate_ids,
    expected=EXPECTED_NOTEBOOK08_FAILED_GATES,
)


expected_narrow_findings: Final[dict[str, bool]] = {
    "count_score_superiority_over_authorized_baselines": True,
    "stationarity_margin_passed": True,
    "side_mark_directional_calibration_passed": True,
}

expected_blocking_findings: Final[dict[str, bool]] = {
    "time_rescaling_distribution_adequacy_passed": False,
    "time_rescaling_serial_independence_passed": False,
    "path_count_calibration_passed": False,
    "exact_time_multiplicity_adequacy_passed": False,
}

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="narrow_findings",
    observed=dict(
        notebook08_final_disposition.get(
            "narrow_findings",
            {},
        )
    ),
    expected=expected_narrow_findings,
)

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="blocking_findings",
    observed=dict(
        notebook08_final_disposition.get(
            "blocking_findings",
            {},
        )
    ),
    expected=expected_blocking_findings,
)

EXPECTED_FINAL_FALSE_FIELDS: Final[
    tuple[str, ...]
] = (
    "full_model_adequacy_authorized",
    "full_hawkes_superiority_authorized",
    "cross_excitation_authorized",
    "state_dependent_hawkes_authorized",
    "notebook09_authorized",
    "validation_partition_opening_authorized",
    "engineering_holdout_opening_authorized",
    "parameter_refit_performed",
    "repair_performed",
)

for final_false_field in (
    EXPECTED_FINAL_FALSE_FIELDS
):
    register_notebook08_disposition_check(
        category="FINAL_DISPOSITION",
        check_name=f"{final_false_field}::false",
        observed=notebook08_boolean(
            notebook08_final_disposition.get(
                final_false_field
            )
        ),
        expected=False,
    )

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="calibration_parameter_updates",
    observed=notebook08_final_disposition.get(
        "calibration_parameter_updates"
    ),
    expected=0,
)

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="frozen_model_disposition",
    observed=notebook08_final_disposition.get(
        "frozen_model_disposition"
    ),
    expected=EXPECTED_NOTEBOOK08_DISPOSITION,
)

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="allowed_downstream_role",
    observed=notebook08_final_disposition.get(
        "allowed_downstream_role"
    ),
    expected=EXPECTED_NOTEBOOK08_ALLOWED_ROLE,
)

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="next_authorized_operation",
    observed=notebook08_final_disposition.get(
        "next_authorized_operation"
    ),
    expected=EXPECTED_NOTEBOOK08_NEXT_OPERATION,
)

register_notebook08_disposition_check(
    category="FINAL_DISPOSITION",
    check_name="finalization_status",
    observed=notebook08_final_disposition.get(
        "status"
    ),
    expected=(
        "PASS_FINALIZATION_OF_FAILED_DIAGNOSTIC_RESULT"
    ),
)


# ------------------------------------------------------------
# Notebook 09 blocked-handoff audit
# ------------------------------------------------------------

register_notebook08_disposition_check(
    category="NOTEBOOK09_BOUNDARY",
    check_name="authorization_granted",
    observed=notebook08_boolean(
        notebook08_notebook09_blocked_handoff.get(
            "authorization_granted"
        )
    ),
    expected=False,
)

register_notebook08_disposition_check(
    category="NOTEBOOK09_BOUNDARY",
    check_name="authorization_scope",
    observed=notebook08_notebook09_blocked_handoff.get(
        "authorization_scope"
    ),
    expected="NONE",
)

register_notebook08_disposition_check(
    category="NOTEBOOK09_BOUNDARY",
    check_name="blocking_reason",
    observed=notebook08_notebook09_blocked_handoff.get(
        "blocking_reason"
    ),
    expected=(
        "FROZEN_H1_FAILED_LOCKED_CALIBRATION_MODEL_ADEQUACY"
    ),
)

EXPECTED_BLOCKED_HANDOFF_FALSE_FIELDS: Final[
    tuple[str, ...]
] = (
    "full_model_adequacy_authorized",
    "full_hawkes_superiority_authorized",
    "intensity_signal_validation_authorized",
    "validation_partition_opening_authorized",
    "engineering_holdout_opening_authorized",
    "cross_excitation_authorized",
    "state_dependent_hawkes_authorized",
    "parameter_refit_performed",
)

for blocked_false_field in (
    EXPECTED_BLOCKED_HANDOFF_FALSE_FIELDS
):
    register_notebook08_disposition_check(
        category="NOTEBOOK09_BOUNDARY",
        check_name=f"{blocked_false_field}::false",
        observed=notebook08_boolean(
            notebook08_notebook09_blocked_handoff.get(
                blocked_false_field
            )
        ),
        expected=False,
    )

register_notebook08_disposition_check(
    category="NOTEBOOK09_BOUNDARY",
    check_name="narrow_count_score_result_preserved",
    observed=notebook08_boolean(
        notebook08_notebook09_blocked_handoff.get(
            "count_score_superiority_authorized"
        )
    ),
    expected=True,
)

register_notebook08_disposition_check(
    category="NOTEBOOK09_BOUNDARY",
    check_name="permitted_use_of_frozen_h1",
    observed=notebook08_notebook09_blocked_handoff.get(
        "permitted_use_of_frozen_h1"
    ),
    expected=EXPECTED_NOTEBOOK08_ALLOWED_ROLE,
)

register_notebook08_disposition_check(
    category="NOTEBOOK09_BOUNDARY",
    check_name="blocked_handoff_status",
    observed=notebook08_notebook09_blocked_handoff.get(
        "status"
    ),
    expected=(
        "BLOCKED_BY_NOTEBOOK08_DIAGNOSTIC_FAILURE"
    ),
)


# ------------------------------------------------------------
# Notebook 10 audit-only handoff
# ------------------------------------------------------------

register_notebook08_disposition_check(
    category="NOTEBOOK10_SCOPE",
    check_name="authorization_granted",
    observed=notebook08_boolean(
        notebook08_notebook10_audit_handoff.get(
            "authorization_granted"
        )
    ),
    expected=True,
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_SCOPE",
    check_name="authorization_scope",
    observed=notebook08_notebook10_audit_handoff.get(
        "authorization_scope"
    ),
    expected=(
        EXPECTED_NOTEBOOK08_FINAL_AUTHORIZATION_SCOPE
    ),
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_SCOPE",
    check_name="notebook09_executed",
    observed=notebook08_boolean(
        notebook08_notebook10_audit_handoff.get(
            "notebook09_executed"
        )
    ),
    expected=False,
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_SCOPE",
    check_name="notebook09_skip_reason",
    observed=notebook08_notebook10_audit_handoff.get(
        "notebook09_skip_reason"
    ),
    expected=(
        "NOTEBOOK08_DID_NOT_PRODUCE_AN_ACCEPTED_DIAGNOSTIC_HANDOFF"
    ),
)

for audit_handoff_false_field in (
    "notebook09_authorized",
    "validation_partition_opening_authorized",
    "engineering_holdout_opening_authorized",
    "model_signal_handoff_authorized",
    "v0_2_model_handoff_authorized",
):
    register_notebook08_disposition_check(
        category="NOTEBOOK10_SCOPE",
        check_name=f"{audit_handoff_false_field}::false",
        observed=notebook08_boolean(
            notebook08_notebook10_audit_handoff.get(
                audit_handoff_false_field
            )
        ),
        expected=False,
    )

register_notebook08_disposition_check(
    category="NOTEBOOK10_SCOPE",
    check_name="required_audit_findings",
    observed=set(
        notebook08_notebook10_audit_handoff.get(
            "required_audit_findings",
            [],
        )
    ),
    expected=(
        EXPECTED_NOTEBOOK08_REQUIRED_AUDIT_FINDINGS
    ),
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_SCOPE",
    check_name="calibration_parameter_updates",
    observed=notebook08_notebook10_audit_handoff.get(
        "calibration_parameter_updates"
    ),
    expected=0,
)

handoff_protected_partition_state = (
    notebook08_notebook10_audit_handoff.get(
        "protected_partition_content_loaded",
        {},
    )
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_SCOPE",
    check_name="validation_remains_unopened",
    observed=notebook08_boolean(
        handoff_protected_partition_state.get(
            "VALIDATION"
        )
        if isinstance(
            handoff_protected_partition_state,
            Mapping,
        )
        else None
    ),
    expected=False,
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_SCOPE",
    check_name="engineering_holdout_remains_unopened",
    observed=notebook08_boolean(
        handoff_protected_partition_state.get(
            "ENGINEERING_HOLDOUT"
        )
        if isinstance(
            handoff_protected_partition_state,
            Mapping,
        )
        else None
    ),
    expected=False,
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_SCOPE",
    check_name="audit_handoff_status",
    observed=notebook08_notebook10_audit_handoff.get(
        "status"
    ),
    expected=(
        "PASS_HANDOFF_TO_FINAL_AUDIT_AFTER_DIAGNOSTIC_FAILURE"
    ),
)


# ------------------------------------------------------------
# Final-output manifest closure
# ------------------------------------------------------------

register_notebook08_disposition_check(
    category="FINAL_MANIFEST",
    check_name="manifest_status",
    observed=notebook08_final_manifest.get(
        "status"
    ),
    expected=(
        "PASS_COMPLETE_OUTPUT_MANIFEST_FOR_FAILED_DIAGNOSTIC_RESULT"
    ),
)

register_notebook08_disposition_check(
    category="FINAL_MANIFEST",
    check_name="next_operation",
    observed=notebook08_final_manifest.get(
        "next_operation"
    ),
    expected=EXPECTED_NOTEBOOK08_NEXT_OPERATION,
)

for final_manifest_false_field in (
    "parameter_refit_performed",
    "repair_performed",
):
    register_notebook08_disposition_check(
        category="FINAL_MANIFEST",
        check_name=f"{final_manifest_false_field}::false",
        observed=notebook08_boolean(
            notebook08_final_manifest.get(
                final_manifest_false_field
            )
        ),
        expected=False,
    )

register_notebook08_disposition_check(
    category="FINAL_MANIFEST",
    check_name="calibration_parameter_updates",
    observed=notebook08_final_manifest.get(
        "calibration_parameter_updates"
    ),
    expected=0,
)


# ------------------------------------------------------------
# Current Notebook 10 mutation and partition guards
# ------------------------------------------------------------

register_notebook08_disposition_check(
    category="NOTEBOOK10_RUNTIME",
    check_name="model_refit_not_performed",
    observed=bool(
        globals().get(
            "MODEL_REFIT_PERFORMED",
            False,
        )
    ),
    expected=False,
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_RUNTIME",
    check_name="model_replacement_not_performed",
    observed=bool(
        globals().get(
            "MODEL_REPLACEMENT_PERFORMED",
            False,
        )
    ),
    expected=False,
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_RUNTIME",
    check_name="calibration_updates_remain_zero",
    observed=int(
        globals().get(
            "CALIBRATION_PARAMETER_UPDATES_PERFORMED",
            0,
        )
    ),
    expected=0,
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_RUNTIME",
    check_name="validation_content_loaded",
    observed=bool(
        globals().get(
            "VALIDATION_CONTENT_LOADED",
            False,
        )
    ),
    expected=False,
)

register_notebook08_disposition_check(
    category="NOTEBOOK10_RUNTIME",
    check_name="engineering_holdout_content_loaded",
    observed=bool(
        globals().get(
            "ENGINEERING_HOLDOUT_CONTENT_LOADED",
            False,
        )
    ),
    expected=False,
)


# ------------------------------------------------------------
# Build final audit tables
# ------------------------------------------------------------

V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUDIT = (
    pd.DataFrame(
        notebook08_disposition_checks
    )
    .sort_values(
        "check_order",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)

V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_FAILURES = (
    V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUDIT.loc[
        V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUDIT[
            "blocking"
        ]
        & ~V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUDIT[
            "passed"
        ]
    ]
    .copy()
)

V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_WARNINGS = (
    V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUDIT.loc[
        ~V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUDIT[
            "blocking"
        ]
        & ~V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUDIT[
            "passed"
        ]
    ]
    .copy()
)


minimum_bootstrap_q025 = float(
    bootstrap_q025.min()
)

V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_SUMMARY = pd.DataFrame(
    [
        {
            "metric": "selected_model_id",
            "value": EXPECTED_NOTEBOOK08_SELECTED_MODEL_ID,
        },
        {
            "metric": "terminal_class",
            "value": EXPECTED_NOTEBOOK08_TERMINAL_CLASS,
        },
        {
            "metric": "terminal_status",
            "value": EXPECTED_NOTEBOOK08_TERMINAL_STATUS,
        },
        {
            "metric": "quantitative_table_count",
            "value": int(
                len(
                    NOTEBOOK08_QUANTITATIVE_TABLES
                )
            ),
        },
        {
            "metric": "diagnostic_gate_count",
            "value": int(
                len(
                    HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT
                )
            ),
        },
        {
            "metric": "blocking_gate_count",
            "value": int(
                len(
                    blocking_gate_rows
                )
            ),
        },
        {
            "metric": "passed_blocking_gate_count",
            "value": int(
                len(
                    passed_blocking_gate_rows
                )
            ),
        },
        {
            "metric": "failed_blocking_gate_count",
            "value": int(
                len(
                    failed_blocking_gate_rows
                )
            ),
        },
        {
            "metric": "minimum_bootstrap_q025",
            "value": minimum_bootstrap_q025,
        },
        {
            "metric": "count_score_superiority_authorized",
            "value": True,
        },
        {
            "metric": "full_model_adequacy_authorized",
            "value": False,
        },
        {
            "metric": "full_hawkes_superiority_authorized",
            "value": False,
        },
        {
            "metric": "notebook09_executed",
            "value": False,
        },
        {
            "metric": "notebook09_authorized",
            "value": False,
        },
        {
            "metric": "validation_content_loaded",
            "value": False,
        },
        {
            "metric": "engineering_holdout_content_loaded",
            "value": False,
        },
        {
            "metric": "calibration_parameter_updates",
            "value": 0,
        },
        {
            "metric": "model_refit_performed",
            "value": False,
        },
        {
            "metric": "model_replacement_performed",
            "value": False,
        },
        {
            "metric": "blocking_audit_failure_count",
            "value": int(
                len(
                    V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_FAILURES
                )
            ),
        },
    ]
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_SUMMARY
)

display(
    V01_NOTEBOOK08_QUANTITATIVE_TABLE_READBACK_AUDIT
)

display(
    HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT
)

display(
    HAWKES_MODEL_REJECTION_LEDGER_AUDIT
)

display(
    CALIBRATION_ENVELOPE_FAMILY_SUMMARY_AUDIT
)

display(
    CALIBRATION_RESIDUAL_DISTRIBUTION_SCOPE_SUMMARY_AUDIT
)

display(
    CALIBRATION_RESIDUAL_SERIAL_SCOPE_SUMMARY_AUDIT
)

display(
    ranking_frame
)

display(
    bootstrap_frame
)

display(
    V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUDIT
)

if not V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_WARNINGS.empty:
    print(
        "Notebook 08 non-blocking audit warnings:"
    )

    display(
        V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_WARNINGS
    )

if not V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_FAILURES.empty:
    print(
        "Notebook 08 blocking audit failures:"
    )

    display(
        V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_FAILURES
    )


# ------------------------------------------------------------
# Blocking gate
# ------------------------------------------------------------

if not V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_FAILURES.empty:
    rendered_failures = "\n\n".join(
        (
            f"- [{row.category}] {row.check_name}\n"
            f"  observed={row.observed}\n"
            f"  expected={row.expected}"
        )
        for row in (
            V01_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_FAILURES.itertuples(
                index=False
            )
        )
    )

    raise Notebook08DiagnosticDispositionError(
        "Notebook 08 quantitative diagnostic disposition "
        "verification failed:\n\n"
        f"{rendered_failures}"
    )


# ------------------------------------------------------------
# Freeze verified Notebook 08 authority
# ------------------------------------------------------------

FROZEN_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUTHORITY = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "selected_model_id": (
        EXPECTED_NOTEBOOK08_SELECTED_MODEL_ID
    ),
    "selected_model_family": (
        EXPECTED_NOTEBOOK08_SELECTED_MODEL_FAMILY
    ),
    "terminal_class": (
        EXPECTED_NOTEBOOK08_TERMINAL_CLASS
    ),
    "terminal_status": (
        EXPECTED_NOTEBOOK08_TERMINAL_STATUS
    ),
    "diagnostic_gate_count": int(
        len(
            HAWKES_DIAGNOSTIC_GATE_LEDGER_AUDIT
        )
    ),
    "blocking_gate_count": int(
        len(
            blocking_gate_rows
        )
    ),
    "passed_blocking_gate_count": int(
        len(
            passed_blocking_gate_rows
        )
    ),
    "failed_blocking_gate_count": int(
        len(
            failed_blocking_gate_rows
        )
    ),
    "failed_blocking_gates": sorted(
        EXPECTED_NOTEBOOK08_FAILED_GATES
    ),
    "narrow_supported_findings": {
        "count_score_superiority_over_authorized_baselines": True,
        "stationarity_margin_passed": True,
        "side_mark_directional_calibration_passed": True,
        "minimum_paired_bootstrap_q025": (
            minimum_bootstrap_q025
        ),
    },
    "blocking_findings": {
        "time_rescaling_distribution_adequacy_passed": False,
        "time_rescaling_serial_independence_passed": False,
        "path_count_calibration_passed": False,
        "exact_time_multiplicity_adequacy_passed": False,
    },
    "full_model_adequacy_authorized": False,
    "full_hawkes_superiority_authorized": False,
    "cross_excitation_authorized": False,
    "state_dependent_hawkes_authorized": False,
    "notebook09_executed": False,
    "notebook09_authorized": False,
    "notebook09_status": "SKIPPED_NOT_PASSED",
    "validation_partition_opening_authorized": False,
    "engineering_holdout_opening_authorized": False,
    "model_signal_handoff_authorized": False,
    "v0_2_model_handoff_authorized": False,
    "frozen_model_disposition": (
        EXPECTED_NOTEBOOK08_DISPOSITION
    ),
    "allowed_downstream_role": (
        EXPECTED_NOTEBOOK08_ALLOWED_ROLE
    ),
    "next_authorized_operation": (
        EXPECTED_NOTEBOOK08_NEXT_OPERATION
    ),
    "required_audit_findings": sorted(
        EXPECTED_NOTEBOOK08_REQUIRED_AUDIT_FINDINGS
    ),
    "quantitative_tables": {
        variable_name: {
            "path": str(
                V01_NOTEBOOK08_QUANTITATIVE_TABLE_READBACK_AUDIT.loc[
                    V01_NOTEBOOK08_QUANTITATIVE_TABLE_READBACK_AUDIT[
                        "variable_name"
                    ].eq(
                        variable_name
                    ),
                    "path",
                ].iloc[
                    0
                ]
            ),
            "sha256": str(
                V01_NOTEBOOK08_QUANTITATIVE_TABLE_READBACK_AUDIT.loc[
                    V01_NOTEBOOK08_QUANTITATIVE_TABLE_READBACK_AUDIT[
                        "variable_name"
                    ].eq(
                        variable_name
                    ),
                    "sha256",
                ].iloc[
                    0
                ]
            ),
            "row_count": int(
                len(
                    dataframe
                )
            ),
            "column_count": int(
                dataframe.shape[
                    1
                ]
            ),
        }
        for variable_name, dataframe in (
            NOTEBOOK08_QUANTITATIVE_TABLES.items()
        )
    },
    "parameter_refit_performed": False,
    "repair_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "protected_partition_content_loaded": {
        "VALIDATION": False,
        "ENGINEERING_HOLDOUT": False,
    },
    "blocking_audit_failure_count": 0,
}


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

NOTEBOOK08_QUANTITATIVE_DIAGNOSTIC_AUTHORITY_VERIFIED = True
NOTEBOOK08_FAILED_ADEQUACY_DISPOSITION_VERIFIED = True
NOTEBOOK08_NARROW_SCORE_EVIDENCE_VERIFIED = True
NOTEBOOK08_MODEL_REJECTION_LEDGER_VERIFIED = True
NOTEBOOK08_TO_NOTEBOOK10_AUDIT_SCOPE_VERIFIED = True

NOTEBOOK09_EXECUTED = False
NOTEBOOK09_AUTHORIZED = False
NOTEBOOK09_SKIPPED_NOT_PASSED_VERIFIED = True

V01_MODEL_SIGNAL_AUTHORIZATION_GRANTED = False
V01_STRATEGY_AUTHORIZATION_GRANTED = False
V01_V02_MODEL_HANDOFF_AUTHORIZED = False

VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False
PROTECTED_PARTITION_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

UPSTREAM_ARTIFACTS_VERIFIED = False

print(
    "Notebook 08 quantitative diagnostic disposition: PASS. "
    "Frozen H1 retains narrow locked-CALIBRATION count-score "
    "superiority over every authorized Notebook 06 baseline and "
    "a defensible stationarity margin. Full model adequacy remains "
    "rejected because residual-distribution, residual-serial, "
    "path-count, and exact-time-multiplicity gates failed. The "
    "failure was preserved without refit, replacement, or repair. "
    "Notebook 09 is verified as skipped and unauthorized—not "
    "passed—and no signal, strategy, quoting, or V0.2 model "
    "handoff is authorized. VALIDATION and ENGINEERING_HOLDOUT "
    "remain unopened. No filesystem writes were performed."
)

                                metric                                                      value
0                    selected_model_id                                   H1_DIAGONAL_SHARED_DECAY
1                       terminal_class                                                       FAIL
2                      terminal_status  FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY
3             quantitative_table_count                                                         12
4                diagnostic_gate_count                                                         14
5                  blocking_gate_count                                                         12
6           passed_blocking_gate_count                                                          8
7           failed_blocking_gate_count                                                          4
8               minimum_bootstrap_q025                                               2,862.365487
9   count_score_superiority_authorized                                                       True
10      full_model_adequacy_authorized                                                      False
11  full_hawkes_superiority_authorized                                                      False
12                 notebook09_executed                                                      False
13               notebook09_authorized                                                      False
14           validation_content_loaded                                                      False
15  engineering_holdout_content_loaded                                                      False
16       calibration_parameter_updates                                                          0
17               model_refit_performed                                                      False
18         model_replacement_performed                                                      False
19        blocking_audit_failure_count                                                          0

,variable_name,artifact_role,record_source,path,format,row_count,column_count,size_bytes,sha256,hash_matches,shape_matches,column_order_matches,status
0,CALIBRATION_ENVELOPE_FAMILY_SUMMARY,calibration_envelope_family_summary,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\diagnostics\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_calibration_envelope_family_summa...,CSV_GZIP,4,9,315,574ad108b411d26d654897140cefe35eafa40a315accd55439e93d8df4886071,True,True,True,PASS
1,CALIBRATION_ENVELOPE_SCOPE_SUMMARY,calibration_envelope_scope_summary,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\diagnostics\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_calibration_envelope_scope_summar...,CSV_GZIP,8,10,366,bd6f019cbbdfd4e15ca1935aa802f0b5312f52dd7c8a291ae085d3f123ae2b36,True,True,True,PASS
2,CALIBRATION_RESIDUAL_DISTRIBUTION_SCOPE_SUMMARY,calibration_residual_distribution_summary,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\diagnostics\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_calibration_residual_distribution...,CSV_GZIP,3,9,208,b3cacefb61539923b2fb109019269fb8fa29353086168dd10ea95c47c19f14d9,True,True,True,PASS
3,CALIBRATION_RESIDUAL_SERIAL_SCOPE_SUMMARY,calibration_residual_serial_summary,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\diagnostics\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_calibration_residual_serial_scope...,CSV_GZIP,3,9,199,ba9a23888f3f9d7c1c2dff060698a774e4b5c9893b842c76571829fb628b567e,True,True,True,PASS
4,FROZEN_HAWKES_SPECIFICATION_DISPOSITION,frozen_hawkes_disposition,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\diagnostics\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_frozen_hawkes_specification_dispo...,CSV_GZIP,1,25,574,3fb7d6bb9a6b90b8c7f2a8ec149bdda07d52ef5fbe78e599ef63e4faf1a19e08,True,True,True,PASS
5,HAWKES_AND_BASELINE_LOCKED_CALIBRATION_RANKING,hawkes_and_baseline_ranking,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\comparisons\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_hawkes_and_baseline_locked_calibr...,CSV_GZIP,5,25,1003,619e99c2b78fd8b77e060333bf113d9177db965fce2d79ff6d68f8d4b92e4f6b,True,True,True,PASS
6,HAWKES_DIAGNOSTIC_GATE_LEDGER,diagnostic_gate_ledger,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\diagnostics\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_hawkes_diagnostic_gate_ledger.csv.gz,CSV_GZIP,14,9,814,94ddfadbd3a474ff35fd2bcceef1f3ddb05f00dfd974789fbbafcac25489e78f,True,True,True,PASS
7,HAWKES_MODEL_REJECTION_LEDGER,model_rejection_ledger,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\diagnostics\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_hawkes_model_rejection_ledger.csv.gz,CSV_GZIP,4,12,604,e25a50316100ec9746f4fe1d9c558ae7c6821da9c11f1448989e03d8a989e106,True,True,True,PASS
8,HAWKES_VS_COUNT_BASELINE_BLOCK_BOOTSTRAP,hawkes_vs_baseline_block_bootstrap,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\comparisons\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_hawkes_vs_count_baseline_block_bo...,CSV_GZIP,4,32,1086,69a0a301b0530668c90ed99c1d99ce563b09dfca839db8350cb02676486e9227,True,True,True,PASS
9,HAWKES_VS_FORMAL_COMPARATOR_RESULT,hawkes_vs_formal_comparator,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\comparisons\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_hawkes_vs_formal_comparator_resul...,CSV_GZIP,1,32,716,011af3b143fd363fb40e0ed28e7aec0e2e9b616b53eff8702a8a86fe70824bce,True,True,True,PASS
10,HAWKES_VS_PRIMARY_SIMPLE_BASELINE_RESULT,hawkes_vs_primary_simple_baseline,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\comparisons\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_hawkes_vs_primary_simple_baseline...,CSV_GZIP,1,32,711,84a288405cda28254aba715c66170bce59cc3a035ba3b3f1e745b7fd9524b145,True,True,True,PASS
11,NOTEBOOK08_TERMINAL_DECISION,terminal_decision_table,FINAL_OUTPUT_MANIFEST,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_notebook08_terminal_decision.csv.gz,CSV_GZIP,1,24,553,a2c8f97db5cae074d27e9085b0b635bbfa1f2afec412d7dae1bfc9c6ee7c4193,True,True,True,PASS

,gate_order,gate_id,gate_family,blocking,passed,observed_value,reference_value,decision_rule,status
0,1,MATERIAL_SCORE_IMPROVEMENT_OVER_FORMAL_COMPARATOR,SCORE_SUPERIORITY,True,True,"3,526.145892",0,PAIRED_BOOTSTRAP_Q025_GREATER_THAN_ZERO,PASS
1,2,MATERIAL_SCORE_IMPROVEMENT_OVER_PRIMARY_SIMPLE_BASELINE,SCORE_SUPERIORITY,True,True,"3,157.846627",0,PAIRED_BOOTSTRAP_Q025_GREATER_THAN_ZERO,PASS
2,3,MATERIAL_SCORE_IMPROVEMENT_OVER_ALL_AUTHORIZED_BASELINES,SCORE_SUPERIORITY,True,True,"2,862.365487",0,EVERY_PAIRED_BOOTSTRAP_Q025_GREATER_THAN_ZERO,PASS
3,4,DEFENSIBLE_STATIONARITY_MARGIN,STATIONARITY,True,True,0.1892556591,0.98,SPECTRAL_RADIUS_LESS_THAN_OR_EQUAL_TO_0_98,PASS
4,5,LOCKED_CALIBRATION_RESIDUAL_DISTRIBUTION,MODEL_ADEQUACY,True,False,1,0.2,MAX_SCOPE_OUTSIDE_FRACTION_LESS_THAN_OR_EQUAL_TO_0_20,FAIL
5,6,LOCKED_CALIBRATION_RESIDUAL_SERIAL_DEPENDENCE,MODEL_ADEQUACY,True,False,1,0.2,MAX_SCOPE_OUTSIDE_FRACTION_LESS_THAN_OR_EQUAL_TO_0_20,FAIL
6,7,LOCKED_CALIBRATION_PATH_COUNT_CALIBRATION,MODEL_ADEQUACY,True,False,1,0,NO_PRIMARY_PATH_COUNT_OUTSIDE_95PCT_ENVELOPE,FAIL
7,8,LOCKED_CALIBRATION_EXACT_TIME_MULTIPLICITY,MODEL_ADEQUACY,True,False,0.5714285714,0.2,OUTSIDE_FRACTION_LESS_THAN_OR_EQUAL_TO_0_20,FAIL
8,9,LOCKED_CALIBRATION_SIDE_MARK_CALIBRATION,MODEL_ADEQUACY,True,True,0,0,NO_PRIMARY_MARK_METRIC_OUTSIDE_DIRECTIONAL_ENVELOPE,PASS
9,10,CROSS_SIDE_DESCRIPTIVE_REPORT_COMPLETE,CROSS_SIDE_DEPENDENCE,False,True,1,1,DESCRIPTIVE_CCF_PORTMANTEAU_AND_COINCIDENCE_TABLES_PRESENT,PASS
10,11,CROSS_SIDE_FORMAL_SIMULATION_ENVELOPE,CROSS_SIDE_DEPENDENCE,False,False,0,1,FORMAL_COARSENING_AWARE_CROSS_SIDE_ENVELOPE_AVAILABLE,NOT_COMPLETED
11,12,CALIBRATION_PARAMETER_UPDATES_ZERO,GOVERNANCE,True,True,0,0,EXACTLY_ZERO,PASS
12,13,PROTECTED_PARTITIONS_UNOPENED,GOVERNANCE,True,True,1,1,VALIDATION_AND_ENGINEERING_HOLDOUT_CONTENT_FALSE,PASS
13,14,FILESYSTEM_WRITES_ABSENT,GOVERNANCE,True,True,1,1,NO_FILESYSTEM_WRITES_BEFORE_PERSISTENCE,PASS

,rejection_order,model_id,gate_id,gate_family,observed_value,reference_value,decision_rule,rejection_reason,repair_performed,parameter_refit_performed,calibration_parameter_updates,status
0,1,H1_DIAGONAL_SHARED_DECAY,LOCKED_CALIBRATION_RESIDUAL_DISTRIBUTION,MODEL_ADEQUACY,1,0.2,MAX_SCOPE_OUTSIDE_FRACTION_LESS_THAN_OR_EQUAL_TO_0_20,Locked CALIBRATION time-rescaling residual distributions show systematic departures from frozen-H1 simulation.,False,False,0,BLOCKING_REJECTION
1,2,H1_DIAGONAL_SHARED_DECAY,LOCKED_CALIBRATION_RESIDUAL_SERIAL_DEPENDENCE,MODEL_ADEQUACY,1,0.2,MAX_SCOPE_OUTSIDE_FRACTION_LESS_THAN_OR_EQUAL_TO_0_20,Locked CALIBRATION residuals retain serial dependence outside frozen-H1 simulation envelopes.,False,False,0,BLOCKING_REJECTION
2,3,H1_DIAGONAL_SHARED_DECAY,LOCKED_CALIBRATION_PATH_COUNT_CALIBRATION,MODEL_ADEQUACY,1,0,NO_PRIMARY_PATH_COUNT_OUTSIDE_95PCT_ENVELOPE,"Locked CALIBRATION BUY, SELL, pooled, or batch counts fall outside frozen-H1 simulation envelopes.",False,False,0,BLOCKING_REJECTION
3,4,H1_DIAGONAL_SHARED_DECAY,LOCKED_CALIBRATION_EXACT_TIME_MULTIPLICITY,MODEL_ADEQUACY,0.5714285714,0.2,OUTSIDE_FRACTION_LESS_THAN_OR_EQUAL_TO_0_20,Observed exact-time multiplicity is not reproduced adequately by frozen H1 after one-millisecond coarsening.,False,False,0,BLOCKING_REJECTION

,diagnostic_family,metric_count,outside_directional_envelope_count,outside_two_sided_envelope_count,minimum_directional_tail_probability,outside_directional_envelope_fraction,outside_two_sided_envelope_fraction,within_declared_adequacy_tolerance,status
0,EXACT_TIME_MULTIPLICITY,7,4,4,0.000999000999,0.5714285714,0.5714285714,False,FAIL
1,PATH_COUNTS,4,4,4,0.001998001998,1,1,False,FAIL
2,SIDE_MARK_CALIBRATION,3,0,2,0.1508491508,0,0.6666666667,True,PASS
3,TIME_RESCALING_RESIDUAL,27,26,26,0.000999000999,0.962962963,0.962962963,False,FAIL

,diagnostic_scope,metric_count,outside_directional_envelope_count,outside_two_sided_envelope_count,minimum_directional_tail_probability,outside_directional_envelope_fraction,outside_two_sided_envelope_fraction,within_declared_adequacy_tolerance,status
0,BUY,4,4,4,0.000999000999,1,1,False,FAIL
1,POOLED,4,4,4,0.000999000999,1,1,False,FAIL
2,SELL,4,3,3,0.000999000999,0.75,0.75,False,FAIL

,diagnostic_scope,metric_count,outside_directional_envelope_count,outside_two_sided_envelope_count,minimum_directional_tail_probability,outside_directional_envelope_fraction,outside_two_sided_envelope_fraction,within_declared_adequacy_tolerance,status
0,BUY,5,5,5,0.000999000999,1,1,False,FAIL
1,POOLED,5,5,5,0.000999000999,1,1,False,FAIL
2,SELL,5,5,5,0.000999000999,1,1,False,FAIL

,model_id,model_family,declared_roles,fitted_partition,scored_partition,score_space,native_grid_width_ms,cell_count,exposure_seconds,observed_event_count,predicted_event_count,observed_minus_predicted,log_score_total,log_score_per_second,log_score_per_observed_event,primary_simple_count_baseline_flag,formal_count_comparator_flag,calibration_used_for_selection,locked_before_calibration,status,calibration_score_rank,log_score_improvement_over_formal_comparator,log_score_improvement_over_primary_simple_baseline,candidate_role,score_only_superiority_claim_authorized
0,H1_DIAGONAL_SHARED_DECAY,DIAGONAL_BIVARIATE_EXPONENTIAL_HAWKES,FROZEN_RESTRICTED_HAWKES_CANDIDATE,DEVELOPMENT,CALIBRATION,BIVARIATE_SIDE_COUNT_NATIVE_1MS,1,720300,720.2991791,2493,"2,754.976987",-261.9769865,"-14,914.46158",-20.70592611,-5.982535733,False,False,False,True,PASS_SCORE_COMPARISON_ONLY,1,"3,526.314495","3,157.981706",FROZEN_HAWKES,False
1,E_SIDE_EWMA_250MS_POISSON,CAUSAL_EXPONENTIALLY_WEIGHTED_RATE,DEVELOPMENT_SELECTED_EWMA;PRIMARY_SIMPLE_COUNT_BASELINE,DEVELOPMENT,CALIBRATION,BIVARIATE_SIDE_COUNT_NATIVE_1MS,1,720300,720.2991791,2493,"2,673.479105",-180.4791047,"-18,072.44329",-25.09019004,-7.249275286,True,False,False,True,PASS_SCORE_COMPARISON_ONLY,2,368.3327884,0,NOTEBOOK_06_BASELINE,False
2,R_SIDE_ROLLING_250MS_POISSON,CAUSAL_ROLLING_WINDOW_RATE,DEVELOPMENT_SELECTED_ROLLING,DEVELOPMENT,CALIBRATION,BIVARIATE_SIDE_COUNT_NATIVE_1MS,1,720300,720.2991791,2493,"2,699.452555",-206.4525551,"-18,095.79606",-25.12261098,-7.258642624,False,False,False,True,PASS_SCORE_COMPARISON_ONLY,3,344.9800145,-23.35277388,NOTEBOOK_06_BASELINE,False
3,B1_SIDE_SPECIFIC_HOMOGENEOUS_POISSON,INDEPENDENT_SIDE_SPECIFIC_HOMOGENEOUS_POISSON,HOMOGENEOUS_SIDE_SPECIFIC_ANCHOR,DEVELOPMENT,CALIBRATION,BIVARIATE_SIDE_COUNT_NATIVE_1MS,1,720300,720.2991791,2493,"2,799.871581",-306.8715814,"-18,440.77608",-25.60155087,-7.397022093,False,False,False,True,PASS_SCORE_COMPARISON_ONLY,4,0,-368.3327884,NOTEBOOK_06_BASELINE,False
4,D0_SIDE_CONSTANT_POISSON,INDEPENDENT_SIDE_SPECIFIC_DETERMINISTIC_ELAPSED_TIME_POISSON,DEVELOPMENT_SELECTED_DETERMINISTIC,DEVELOPMENT,CALIBRATION,BIVARIATE_SIDE_COUNT_NATIVE_1MS,1,720300,720.2991791,2493,"2,799.871581",-306.8715814,"-18,440.77608",-25.60155087,-7.397022093,False,True,False,True,PASS_SCORE_COMPARISON_ONLY,5,0,-368.3327884,NOTEBOOK_06_BASELINE,False

,candidate_model_id,comparator_model_id,comparator_model_family,formal_comparator_flag,primary_simple_baseline_flag,scored_partition,score_space,grid_width_ms,block_width_seconds,complete_block_count,formal_bootstrap_exposure_seconds,excluded_tail_exposure_seconds,bootstrap_replicates,observed_total_log_score_difference,observed_log_score_difference_per_block,observed_log_score_difference_per_second,bootstrap_total_difference_q025,bootstrap_total_difference_median,bootstrap_total_difference_q975,bootstrap_difference_per_second_q025,bootstrap_difference_per_second_median,bootstrap_difference_per_second_q975,bootstrap_probability_difference_nonpositive,bootstrap_probability_difference_nonnegative,positive_improvement_supported_at_95pct,negative_difference_supported_at_95pct,comparison_status,calibration_used_for_model_selection,parameter_refit_performed,calibration_parameter_updates,full_hawkes_superiority_claim_authorized,status
0,H1_DIAGONAL_SHARED_DECAY,D0_SIDE_CONSTANT_POISSON,INDEPENDENT_SIDE_SPECIFIC_DETERMINISTIC_ELAPSED_TIME_POISSON,True,False,CALIBRATION,BIVARIATE_SIDE_COUNT_NATIVE_1MS,1,10,72,720,0.2991791,2000,"3,526.145892",48.9742485,4.89742485,"3,102.105784","3,518.309313","3,981.651151",4.308480255,4.886540713,5.530071043,0.0004997501249,1,True,False,H1_POSITIVE_SUPPORTED,False,False,0,False,PASS_SCORE_COMPARISON_ONLY
1,H1_DIAGONAL_SHARED_DECAY,E_SIDE_EWMA_250MS_POISSON,CAUSAL_EXPONENTIALLY_WEIGHTED_RATE,False,True,CALIBRATION,BIVARIATE_SIDE_COUNT_NATIVE_1MS,1,10,72,720,0.2991791,2000,"3,157.846627",43.85898093,4.385898093,"2,862.365487","3,142.108249","3,475.409094",3.975507621,4.364039235,4.826957075,0.0004997501249,1,True,False,H1_POSITIVE_SUPPORTED,False,False,0,False,PASS_SCORE_COMPARISON_ONLY
2,H1_DIAGONAL_SHARED_DECAY,B1_SIDE_SPECIFIC_HOMOGENEOUS_POISSON,INDEPENDENT_SIDE_SPECIFIC_HOMOGENEOUS_POISSON,False,False,CALIBRATION,BIVARIATE_SIDE_COUNT_NATIVE_1MS,1,10,72,720,0.2991791,2000,"3,526.145892",48.9742485,4.89742485,"3,112.409349","3,514.702898","4,017.43975",4.322790763,4.881531802,5.579777431,0.0004997501249,1,True,False,H1_POSITIVE_SUPPORTED,False,False,0,False,PASS_SCORE_COMPARISON_ONLY
3,H1_DIAGONAL_SHARED_DECAY,R_SIDE_ROLLING_250MS_POISSON,CAUSAL_ROLLING_WINDOW_RATE,False,False,CALIBRATION,BIVARIATE_SIDE_COUNT_NATIVE_1MS,1,10,72,720,0.2991791,2000,"3,181.26831",44.18428208,4.418428208,"2,884.313871","3,175.670248","3,500.741288",4.005991487,4.410653122,4.862140678,0.0004997501249,1,True,False,H1_POSITIVE_SUPPORTED,False,False,0,False,PASS_SCORE_COMPARISON_ONLY

,check_order,category,check_name,blocking,passed,status,observed,expected
0,1,GATE_LEDGER,complete_gate_set,True,True,PASS,"[""CALIBRATION_PARAMETER_UPDATES_ZERO"", ""CROSS_SIDE_DESCRIPTIVE_REPORT_COMPLETE"", ""CROSS_SIDE_FORMAL_SIMULATION_ENVELOPE"", ""DEFENSIBLE_STATIONARITY_MARGIN"", ...","[""CALIBRATION_PARAMETER_UPDATES_ZERO"", ""CROSS_SIDE_DESCRIPTIVE_REPORT_COMPLETE"", ""CROSS_SIDE_FORMAL_SIMULATION_ENVELOPE"", ""DEFENSIBLE_STATIONARITY_MARGIN"", ..."
1,2,GATE_LEDGER,gate_ids_are_unique,True,True,PASS,True,True
2,3,GATE_LEDGER,blocking_gate_count,True,True,PASS,12,12
3,4,GATE_LEDGER,passed_blocking_gate_count,True,True,PASS,8,8
4,5,GATE_LEDGER,failed_blocking_gate_count,True,True,PASS,4,4
...,...,...,...,...,...,...,...,...
142,143,NOTEBOOK10_RUNTIME,model_refit_not_performed,True,True,PASS,False,False
143,144,NOTEBOOK10_RUNTIME,model_replacement_not_performed,True,True,PASS,False,False
144,145,NOTEBOOK10_RUNTIME,calibration_updates_remain_zero,True,True,PASS,0,0
145,146,NOTEBOOK10_RUNTIME,validation_content_loaded,True,True,PASS,False,False
146,147,NOTEBOOK10_RUNTIME,engineering_holdout_content_loaded,True,True,PASS,False,False

Notebook 08 quantitative diagnostic disposition: PASS. Frozen H1 retains narrow locked-CALIBRATION count-score superiority over every authorized Notebook 06 baseline and a defensible stationarity margin. Full model adequacy remains rejected because residual-distribution, residual-serial, path-count, and exact-time-multiplicity gates failed. The failure was preserved without refit, replacement, or repair. Notebook 09 is verified as skipped and unauthorized—not passed—and no signal, strategy, quoting, or V0.2 model handoff is authorized. VALIDATION and ENGINEERING_HOLDOUT remain unopened. No filesystem writes were performed.

In [33]:
# ============================================================
# V0.1 terminal synthesis and V0.2 bootstrap-handoff blueprint
#
# This cell:
# - synthesizes the verified Notebook 00–08 authorities;
# - records Notebook 08 as a scientific failure preserved by a
#   successful audit closeout;
# - records Notebook 09 as skipped and not passed;
# - audits the 28-item V0.1 completion standard;
# - separates supported, rejected, untested, and prohibited claims;
# - classifies the verified physical file catalogue for V0.2;
# - prepares a bootstrap-only V0.2 handoff package;
# - forbids carrying H1, an intensity signal, or strategy logic
#   into V0.2 as accepted authority.
#
# The V0.2 handoff is prepared in memory only. Persistence and
# semantic readback occur in later cells.
#
# No protected analytical content is opened.
# No filesystem writes are performed.
# ============================================================

from datetime import datetime, timezone
from typing import Any, Final, Mapping

import hashlib
import json
import re

import numpy as np
import pandas as pd
from IPython.display import display


class V01TerminalSynthesisError(RuntimeError):
    """Raised when the V0.1 terminal synthesis is inconsistent."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

REQUIRED_V01_TERMINAL_PRECONDITIONS: Final[
    dict[str, bool]
] = {
    "V01_CONTROL_PLANE_VERIFIED": bool(
        globals().get(
            "V01_CONTROL_PLANE_VERIFIED",
            False,
        )
    ),
    "V01_MANIFESTED_FILES_VERIFIED": bool(
        globals().get(
            "V01_MANIFESTED_FILES_VERIFIED",
            False,
        )
    ),
    "V01_PHYSICAL_ARTIFACT_CATALOGUE_COMPLETE": bool(
        globals().get(
            "V01_PHYSICAL_ARTIFACT_CATALOGUE_COMPLETE",
            False,
        )
    ),
    "V01_DATAFRAME_CONTRACT_GATE_PASSED": bool(
        globals().get(
            "V01_DATAFRAME_CONTRACT_GATE_PASSED",
            False,
        )
    ),
    "NOTEBOOK05_INTERFACE_SEMANTICS_VERIFIED": bool(
        globals().get(
            "NOTEBOOK05_INTERFACE_SEMANTICS_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK06_BASELINE_AUTHORITY_VERIFIED": bool(
        globals().get(
            "NOTEBOOK06_BASELINE_AUTHORITY_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK07_QUANTITATIVE_RECONCILIATION_VERIFIED": bool(
        globals().get(
            "NOTEBOOK07_QUANTITATIVE_RECONCILIATION_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK08_QUANTITATIVE_DIAGNOSTIC_AUTHORITY_VERIFIED": bool(
        globals().get(
            "NOTEBOOK08_QUANTITATIVE_DIAGNOSTIC_AUTHORITY_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK08_FAILED_ADEQUACY_DISPOSITION_VERIFIED": bool(
        globals().get(
            "NOTEBOOK08_FAILED_ADEQUACY_DISPOSITION_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK09_SKIPPED_NOT_PASSED_VERIFIED": bool(
        globals().get(
            "NOTEBOOK09_SKIPPED_NOT_PASSED_VERIFIED",
            False,
        )
    ),
}

failed_terminal_preconditions = sorted(
    name
    for name, passed in (
        REQUIRED_V01_TERMINAL_PRECONDITIONS.items()
    )
    if not passed
)

if failed_terminal_preconditions:
    raise V01TerminalSynthesisError(
        "V0.1 terminal-synthesis prerequisites have not passed:\n"
        f"{failed_terminal_preconditions}"
    )


required_runtime_objects = (
    "V01_STAGE_CONTROL_COVERAGE",
    "V01_STAGE_CONTROL_ARTIFACT_REGISTRY",
    "V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE",
    "FROZEN_NOTEBOOK05_INTERFACE_AUTHORITY",
    "FROZEN_NOTEBOOK06_BASELINE_AUTHORITY",
    "FROZEN_NOTEBOOK07_QUANTITATIVE_RECONCILIATION_AUTHORITY",
    "FROZEN_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUTHORITY",
)

missing_runtime_objects = sorted(
    object_name
    for object_name in required_runtime_objects
    if object_name not in globals()
)

if missing_runtime_objects:
    raise V01TerminalSynthesisError(
        "Required verified authorities are unavailable:\n"
        f"{missing_runtime_objects}"
    )


# ------------------------------------------------------------
# Runtime mutation and protected-partition guards
# ------------------------------------------------------------

if bool(
    globals().get(
        "VALIDATION_CONTENT_LOADED",
        False,
    )
):
    raise V01TerminalSynthesisError(
        "VALIDATION content was unexpectedly loaded."
    )

if bool(
    globals().get(
        "ENGINEERING_HOLDOUT_CONTENT_LOADED",
        False,
    )
):
    raise V01TerminalSynthesisError(
        "ENGINEERING_HOLDOUT content was unexpectedly loaded."
    )

protected_runtime_state = globals().get(
    "PROTECTED_PARTITION_CONTENT_LOADED",
    False,
)

if isinstance(
    protected_runtime_state,
    Mapping,
):
    opened_protected_partitions = sorted(
        str(partition)
        for partition, loaded in (
            protected_runtime_state.items()
        )
        if bool(
            loaded
        )
    )

    if opened_protected_partitions:
        raise V01TerminalSynthesisError(
            "Protected partitions were unexpectedly marked as "
            f"loaded: {opened_protected_partitions}"
        )

elif bool(
    protected_runtime_state
):
    raise V01TerminalSynthesisError(
        "Protected partition content was unexpectedly loaded."
    )


if bool(
    globals().get(
        "MODEL_REFIT_PERFORMED",
        False,
    )
):
    raise V01TerminalSynthesisError(
        "A model refit was recorded during Notebook 10."
    )

if bool(
    globals().get(
        "MODEL_REPLACEMENT_PERFORMED",
        False,
    )
):
    raise V01TerminalSynthesisError(
        "A model replacement was recorded during Notebook 10."
    )

if int(
    globals().get(
        "CALIBRATION_PARAMETER_UPDATES_PERFORMED",
        0,
    )
) != 0:
    raise V01TerminalSynthesisError(
        "Nonzero CALIBRATION parameter updates were recorded."
    )


# ------------------------------------------------------------
# Bind frozen authorities
# ------------------------------------------------------------

notebook05_authority = (
    FROZEN_NOTEBOOK05_INTERFACE_AUTHORITY
)

notebook06_authority = (
    FROZEN_NOTEBOOK06_BASELINE_AUTHORITY
)

notebook07_authority = (
    FROZEN_NOTEBOOK07_QUANTITATIVE_RECONCILIATION_AUTHORITY
)

notebook08_authority = (
    FROZEN_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUTHORITY
)

for authority_name, authority_value in (
    (
        "FROZEN_NOTEBOOK05_INTERFACE_AUTHORITY",
        notebook05_authority,
    ),
    (
        "FROZEN_NOTEBOOK06_BASELINE_AUTHORITY",
        notebook06_authority,
    ),
    (
        "FROZEN_NOTEBOOK07_QUANTITATIVE_RECONCILIATION_AUTHORITY",
        notebook07_authority,
    ),
    (
        "FROZEN_NOTEBOOK08_DIAGNOSTIC_DISPOSITION_AUTHORITY",
        notebook08_authority,
    ),
):
    if not isinstance(
        authority_value,
        Mapping,
    ):
        raise V01TerminalSynthesisError(
            f"{authority_name} must be a mapping."
        )


# ------------------------------------------------------------
# Expected terminal state
# ------------------------------------------------------------

EXPECTED_V01_SELECTED_MODEL_ID: Final[str] = (
    "H1_DIAGONAL_SHARED_DECAY"
)

EXPECTED_V01_FORMAL_COMPARATOR: Final[str] = (
    "D0_SIDE_CONSTANT_POISSON"
)

EXPECTED_V01_PRIMARY_SIMPLE_BASELINE: Final[str] = (
    "E_SIDE_EWMA_250MS_POISSON"
)

EXPECTED_V01_TERMINAL_CLASS: Final[str] = "FAIL"

EXPECTED_V01_TERMINAL_STATUS: Final[str] = (
    "FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY"
)

EXPECTED_V01_FAILED_ADEQUACY_GATES: Final[set[str]] = {
    "LOCKED_CALIBRATION_RESIDUAL_DISTRIBUTION",
    "LOCKED_CALIBRATION_RESIDUAL_SERIAL_DEPENDENCE",
    "LOCKED_CALIBRATION_PATH_COUNT_CALIBRATION",
    "LOCKED_CALIBRATION_EXACT_TIME_MULTIPLICITY",
}

EXPECTED_V01_CLOSEOUT_STATUS: Final[str] = (
    "PASS_READY_TO_PERSIST_CLOSED_FAILED_BRANCH"
)

EXPECTED_V02_HANDOFF_SCOPE: Final[str] = (
    "BOOTSTRAP_AND_PROVENANCE_ONLY_NO_ACCEPTED_MODEL_SIGNAL_OR_STRATEGY"
)


# ------------------------------------------------------------
# Canonical serialization helpers
# ------------------------------------------------------------

def v01_plain_value(
    value: Any,
) -> Any:
    """Convert values into strict JSON-compatible Python types."""

    if value is None:
        return None

    if isinstance(
        value,
        Path,
    ):
        return str(
            value
        )

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(
            value
        )

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        return int(
            value
        )

    if isinstance(
        value,
        (float, np.floating),
    ):
        numeric_value = float(
            value
        )

        if not np.isfinite(
            numeric_value
        ):
            return str(
                numeric_value
            )

        return numeric_value

    if isinstance(
        value,
        Mapping,
    ):
        return {
            str(key): v01_plain_value(
                child
            )
            for key, child in value.items()
        }

    if isinstance(
        value,
        (
            list,
            tuple,
            set,
        ),
    ):
        iterable = (
            sorted(
                value
            )
            if isinstance(
                value,
                set,
            )
            else value
        )

        return [
            v01_plain_value(
                child
            )
            for child in iterable
        ]

    return str(
        value
    )


def v01_canonical_sha256(
    payload: Mapping[str, Any],
) -> str:
    """Return a deterministic semantic SHA-256."""

    canonical_payload = v01_plain_value(
        payload
    )

    canonical_bytes = json.dumps(
        canonical_payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode(
        "utf-8"
    )

    return hashlib.sha256(
        canonical_bytes
    ).hexdigest()


def v01_render(
    value: Any,
) -> str:
    """Render deterministic values for audit tables."""

    plain_value = v01_plain_value(
        value
    )

    if isinstance(
        plain_value,
        (
            dict,
            list,
        ),
    ):
        return json.dumps(
            plain_value,
            sort_keys=True,
            ensure_ascii=False,
            allow_nan=False,
        )

    return repr(
        plain_value
    )


# ------------------------------------------------------------
# Creation timestamp remains stable across reruns
# ------------------------------------------------------------

if (
    "NOTEBOOK10_SYNTHESIS_CREATED_UTC"
    not in globals()
):
    NOTEBOOK10_SYNTHESIS_CREATED_UTC = (
        datetime.now(
            timezone.utc
        )
        .replace(
            microsecond=0
        )
        .isoformat()
    )


# ------------------------------------------------------------
# Cross-authority terminal reconciliation
# ------------------------------------------------------------

selected_model_sources = {
    "NOTEBOOK07": notebook07_authority.get(
        "selected_model_id"
    ),
    "NOTEBOOK08": notebook08_authority.get(
        "selected_model_id"
    ),
}

if set(
    selected_model_sources.values()
) != {
    EXPECTED_V01_SELECTED_MODEL_ID
}:
    raise V01TerminalSynthesisError(
        "Selected-model identity does not reconcile:\n"
        + json.dumps(
            selected_model_sources,
            indent=2,
            ensure_ascii=False,
        )
    )


formal_comparator_sources = {
    "NOTEBOOK06": notebook06_authority.get(
        "formal_count_comparator_model_id"
    ),
    "NOTEBOOK07": notebook07_authority.get(
        "formal_count_comparator"
    ),
}

if set(
    formal_comparator_sources.values()
) != {
    EXPECTED_V01_FORMAL_COMPARATOR
}:
    raise V01TerminalSynthesisError(
        "Formal comparator identity does not reconcile:\n"
        + json.dumps(
            formal_comparator_sources,
            indent=2,
            ensure_ascii=False,
        )
    )


primary_simple_sources = {
    "NOTEBOOK06": notebook06_authority.get(
        "primary_simple_count_baseline_model_id"
    ),
    "NOTEBOOK07": notebook07_authority.get(
        "primary_simple_count_baseline"
    ),
}

if set(
    primary_simple_sources.values()
) != {
    EXPECTED_V01_PRIMARY_SIMPLE_BASELINE
}:
    raise V01TerminalSynthesisError(
        "Primary simple-baseline identity does not reconcile:\n"
        + json.dumps(
            primary_simple_sources,
            indent=2,
            ensure_ascii=False,
        )
    )


if (
    notebook08_authority.get(
        "terminal_class"
    )
    != EXPECTED_V01_TERMINAL_CLASS
):
    raise V01TerminalSynthesisError(
        "Notebook 08 terminal class is not the expected FAIL."
    )

if (
    notebook08_authority.get(
        "terminal_status"
    )
    != EXPECTED_V01_TERMINAL_STATUS
):
    raise V01TerminalSynthesisError(
        "Notebook 08 terminal status does not reconcile."
    )


observed_failed_adequacy_gates = set(
    notebook08_authority.get(
        "failed_blocking_gates",
        [],
    )
)

if (
    observed_failed_adequacy_gates
    != EXPECTED_V01_FAILED_ADEQUACY_GATES
):
    raise V01TerminalSynthesisError(
        "Notebook 08 failed-gate set does not reconcile.\n"
        f"Observed: {sorted(observed_failed_adequacy_gates)}\n"
        f"Expected: {sorted(EXPECTED_V01_FAILED_ADEQUACY_GATES)}"
    )


# ------------------------------------------------------------
# Stage control-plane reconciliation
# ------------------------------------------------------------

stage_coverage = V01_STAGE_CONTROL_COVERAGE.copy(
    deep=True
)

required_stage_coverage_columns = {
    "stage_number",
    "stage_name",
    "stage_control_plane_complete",
    "status",
}

missing_stage_coverage_columns = sorted(
    required_stage_coverage_columns
    - set(
        stage_coverage.columns
    )
)

if missing_stage_coverage_columns:
    raise V01TerminalSynthesisError(
        "The stage-coverage table lacks required columns:\n"
        f"{missing_stage_coverage_columns}"
    )


stage_coverage[
    "stage_number"
] = (
    stage_coverage[
        "stage_number"
    ]
    .astype(
        "string"
    )
    .str.zfill(
        2
    )
)

required_completed_stage_numbers = {
    "00",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
}

observed_completed_stage_numbers = set(
    stage_coverage.loc[
        stage_coverage[
            "stage_control_plane_complete"
        ].astype(
            bool
        ),
        "stage_number",
    ].astype(
        str
    )
)

if (
    observed_completed_stage_numbers
    != required_completed_stage_numbers
):
    raise V01TerminalSynthesisError(
        "Persisted control-plane coverage does not contain exactly "
        "Notebooks 00–08.\n"
        f"Observed: {sorted(observed_completed_stage_numbers)}"
    )


# ------------------------------------------------------------
# Persisted stage status observations
# ------------------------------------------------------------

control_registry = (
    V01_STAGE_CONTROL_ARTIFACT_REGISTRY.copy(
        deep=True
    )
)

control_registry[
    "stage_number"
] = (
    control_registry[
        "stage_number"
    ]
    .astype(
        "string"
    )
    .str.zfill(
        2
    )
)


observed_control_statuses_by_stage: dict[
    str,
    list[str],
] = {}

for stage_number, stage_group in (
    control_registry.groupby(
        "stage_number",
        sort=True,
    )
):
    observed_control_statuses_by_stage[
        str(
            stage_number
        )
    ] = sorted(
        {
            str(
                value
            )
            for value in stage_group[
                "control_status"
            ].dropna()
        }
    )


# ------------------------------------------------------------
# Final stage-disposition ledger
# ------------------------------------------------------------

stage_disposition_records: list[
    dict[str, Any]
] = []

for stage_number in (
    "00",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
):
    coverage_row = stage_coverage.loc[
        stage_coverage[
            "stage_number"
        ].eq(
            stage_number
        )
    ]

    if len(
        coverage_row
    ) != 1:
        raise V01TerminalSynthesisError(
            f"Stage {stage_number} coverage row is not unique."
        )

    stage_name = str(
        coverage_row.iloc[
            0
        ][
            "stage_name"
        ]
    )

    if stage_number in {
        "00",
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
    }:
        execution_state = "COMPLETED"
        scientific_state = (
            "ACCEPTED_FOR_DECLARED_STAGE_SCOPE"
        )
        downstream_state = (
            "PRESERVED_AS_V0_1_AUTHORITY"
        )

    else:
        execution_state = "COMPLETED"
        scientific_state = (
            "FAILED_REQUIRED_MODEL_ADEQUACY"
        )
        downstream_state = (
            "DIAGNOSTIC_REFERENCE_ONLY"
        )

    stage_disposition_records.append(
        {
            "stage_number": stage_number,
            "stage_name": stage_name,
            "execution_state": execution_state,
            "scientific_state": scientific_state,
            "downstream_state": downstream_state,
            "control_plane_complete": True,
            "observed_control_statuses": (
                observed_control_statuses_by_stage.get(
                    stage_number,
                    [],
                )
            ),
            "status": (
                "FAIL_SCIENTIFIC"
                if stage_number == "08"
                else "PASS"
            ),
        }
    )


stage_disposition_records.extend(
    [
        {
            "stage_number": "09",
            "stage_name": (
                "INTENSITY_SIGNAL_VALIDATION"
            ),
            "execution_state": (
                "SKIPPED_BY_UPSTREAM_BLOCK"
            ),
            "scientific_state": (
                "NOT_TESTED"
            ),
            "downstream_state": (
                "NO_AUTHORITY_CREATED"
            ),
            "control_plane_complete": True,
            "observed_control_statuses": [
                "BLOCKED_BY_NOTEBOOK08_DIAGNOSTIC_FAILURE",
            ],
            "status": "SKIPPED_NOT_PASSED",
        },
        {
            "stage_number": "10",
            "stage_name": (
                "FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF"
            ),
            "execution_state": (
                "IN_MEMORY_SYNTHESIS_CREATED"
            ),
            "scientific_state": (
                "CLOSING_FAILED_V0_1_BRANCH"
            ),
            "downstream_state": (
                EXPECTED_V02_HANDOFF_SCOPE
            ),
            "control_plane_complete": False,
            "observed_control_statuses": [
                "PERSISTENCE_PENDING",
            ],
            "status": (
                "PASS_READY_FOR_PERSISTENCE"
            ),
        },
    ]
)


V01_FINAL_STAGE_DISPOSITION_LEDGER = pd.DataFrame(
    stage_disposition_records
)


# ------------------------------------------------------------
# Final claim ledger
# ------------------------------------------------------------

feature_table_authority = notebook05_authority.get(
    "feature_table",
    {},
)

future_label_table_authority = notebook05_authority.get(
    "future_label_table",
    {},
)

if not isinstance(
    feature_table_authority,
    Mapping,
):
    feature_table_authority = {}

if not isinstance(
    future_label_table_authority,
    Mapping,
):
    future_label_table_authority = {}


V01_FINAL_CLAIM_LEDGER = pd.DataFrame(
    [
        {
            "claim_id": "C01",
            "claim_domain": "SOURCE_AUTHORITY",
            "claim": (
                "The registered V0.0 source collection is the "
                "immutable primary input authority."
            ),
            "disposition": "SUPPORTED",
            "evidence_scope": (
                "Notebook 00 control plane and verified physical "
                "file catalogue"
            ),
            "v02_treatment": (
                "PRESERVE_AS_PROVENANCE_AND_REPRODUCTION_REFERENCE"
            ),
        },
        {
            "claim_id": "C02",
            "claim_domain": "BOOK_RECONSTRUCTION",
            "claim": (
                "The visible market-by-price reconstruction passed "
                "its declared V0.1 stage gates."
            ),
            "disposition": "SUPPORTED",
            "evidence_scope": (
                "Notebook 02 persisted acceptance and handoff"
            ),
            "v02_treatment": (
                "PRESERVE_LOGIC_AND_REBUILD_ON_NEW_SOURCE_DATA"
            ),
        },
        {
            "claim_id": "C03",
            "claim_domain": "CAUSAL_ALIGNMENT",
            "claim": (
                "LOCAL_STRICT collector-observable trade/book "
                "alignment is the accepted synchronization authority."
            ),
            "disposition": "SUPPORTED",
            "evidence_scope": (
                "Notebook 03 persisted acceptance and handoff"
            ),
            "v02_treatment": (
                "CARRY_CONTRACT_AND_REIMPLEMENT_FROM_FRESH_NOTEBOOK"
            ),
        },
        {
            "claim_id": "C04",
            "claim_domain": "EVENT_STREAM",
            "claim": (
                "The accepted primary event representation is "
                "same-millisecond same-side bursts."
            ),
            "disposition": "SUPPORTED_FOR_V0_1",
            "evidence_scope": (
                "Notebook 04 event-definition and partition contracts"
            ),
            "v02_treatment": (
                "RETAIN_AS_REFERENCE_BUT_RETEST_MULTIPLICITY_DESIGN"
            ),
        },
        {
            "claim_id": "C05",
            "claim_domain": "FEATURE_INTERFACE",
            "claim": (
                f"{feature_table_authority.get('feature_count')} "
                "causal T-minus features are physically separated "
                f"from {future_label_table_authority.get('label_count')} "
                "future-label fields."
            ),
            "disposition": "SUPPORTED",
            "evidence_scope": (
                "Notebook 05 contract and registry reconciliation"
            ),
            "v02_treatment": (
                "PRESERVE_INTERFACE_CONTRACT_AND_REBUILD_ON_NEW_DATA"
            ),
        },
        {
            "claim_id": "C06",
            "claim_domain": "BASELINES",
            "claim": (
                "Notebook 06 established locked point-process "
                "comparators before Hawkes diagnostics."
            ),
            "disposition": "SUPPORTED",
            "evidence_scope": (
                f"Formal comparator={EXPECTED_V01_FORMAL_COMPARATOR}; "
                f"primary simple baseline="
                f"{EXPECTED_V01_PRIMARY_SIMPLE_BASELINE}"
            ),
            "v02_treatment": (
                "PRESERVE_BASELINE_DEFINITIONS_AND_REFIT_FROM_SCRATCH"
            ),
        },
        {
            "claim_id": "C07",
            "claim_domain": "HAWKES_ESTIMATION",
            "claim": (
                "H1 was fitted on DEVELOPMENT, locked before "
                "CALIBRATION, and received zero CALIBRATION updates."
            ),
            "disposition": "SUPPORTED",
            "evidence_scope": (
                "Notebook 07 model contract and quantitative "
                "reconciliation"
            ),
            "v02_treatment": (
                "PRESERVE_AS_REJECTED_DIAGNOSTIC_REFERENCE_ONLY"
            ),
        },
        {
            "claim_id": "C08",
            "claim_domain": "SCORE_EVIDENCE",
            "claim": (
                "Frozen H1 achieved superior locked-CALIBRATION "
                "count score over all authorized Notebook 06 "
                "baselines."
            ),
            "disposition": "SUPPORTED_NARROWLY",
            "evidence_scope": (
                "Notebook 08 paired complete-block bootstrap and "
                "locked score ranking"
            ),
            "v02_treatment": (
                "RETAIN_AS_HYPOTHESIS_MOTIVATION_NOT_MODEL_AUTHORITY"
            ),
        },
        {
            "claim_id": "C09",
            "claim_domain": "MODEL_ADEQUACY",
            "claim": (
                "Frozen H1 adequately reproduces the locked "
                "CALIBRATION event process."
            ),
            "disposition": "REJECTED",
            "evidence_scope": sorted(
                EXPECTED_V01_FAILED_ADEQUACY_GATES
            ),
            "v02_treatment": (
                "RETAIN_FAILURE_LEDGER_AS_PRIMARY_REDESIGN_INPUT"
            ),
        },
        {
            "claim_id": "C10",
            "claim_domain": "FULL_HAWKES_SUPERIORITY",
            "claim": (
                "H1 is generally superior to simpler point-process "
                "models."
            ),
            "disposition": "NOT_AUTHORIZED",
            "evidence_scope": (
                "Higher count likelihood is insufficient because "
                "required model-adequacy gates failed."
            ),
            "v02_treatment": (
                "DO_NOT_CARRY_AS_ACCEPTED_CLAIM"
            ),
        },
        {
            "claim_id": "C11",
            "claim_domain": "SIGNAL_VALUE",
            "claim": (
                "Hawkes intensity adds incremental causal predictive "
                "information beyond simpler controls."
            ),
            "disposition": "NOT_TESTED",
            "evidence_scope": (
                "Notebook 09 was blocked before VALIDATION opened."
            ),
            "v02_treatment": (
                "REQUIRE_NEW_VALIDATION_STAGE_AFTER_MODEL_ADEQUACY"
            ),
        },
        {
            "claim_id": "C12",
            "claim_domain": "PROTECTED_DATA",
            "claim": (
                "VALIDATION and ENGINEERING_HOLDOUT remained unopened."
            ),
            "disposition": "SUPPORTED",
            "evidence_scope": (
                "Persisted Notebook 07/08 closure evidence and "
                "Notebook 10 runtime guards"
            ),
            "v02_treatment": (
                "PRESERVE_HASH_ONLY_PROVENANCE_DO_NOT_REUSE_AS_NEW_HOLDOUT"
            ),
        },
        {
            "claim_id": "C13",
            "claim_domain": "STRATEGY",
            "claim": (
                "V0.1 authorizes quoting, market making, fill "
                "simulation, or P&L claims."
            ),
            "disposition": "PROHIBITED",
            "evidence_scope": (
                "Notebook 05–08 downstream authorization boundaries"
            ),
            "v02_treatment": (
                "NO_STRATEGY_WORK_BEFORE_SIGNAL_ACCEPTANCE"
            ),
        },
        {
            "claim_id": "C14",
            "claim_domain": "V02_HANDOFF",
            "claim": (
                "H1 or a derived intensity signal may enter V0.2 "
                "as an accepted model."
            ),
            "disposition": "PROHIBITED",
            "evidence_scope": (
                "Notebook 08 failed model adequacy and blocked "
                "Notebook 09"
            ),
            "v02_treatment": (
                "BOOTSTRAP_AND_PROVENANCE_ONLY"
            ),
        },
    ]
)


# ------------------------------------------------------------
# V0.1 completion-standard audit
# ------------------------------------------------------------

physical_catalogue = (
    V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE.copy(
        deep=True
    )
)

v00_file_count = int(
    physical_catalogue[
        "authority_root"
    ].eq(
        "V0.0"
    ).sum()
)

v01_file_count = int(
    physical_catalogue[
        "authority_root"
    ].eq(
        "V0.1"
    ).sum()
)

all_physical_files_verified = bool(
    physical_catalogue[
        "physical_verification_passed"
    ].all()
)


def completion_record(
    criterion_number: int,
    criterion: str,
    outcome: str,
    evidence: str,
    completion_met: bool,
) -> dict[str, Any]:
    """Create one completion-standard record."""

    return {
        "criterion_number": int(
            criterion_number
        ),
        "criterion": criterion,
        "outcome": outcome,
        "completion_met": bool(
            completion_met
        ),
        "evidence": evidence,
    }


completion_standard_records = [
    completion_record(
        1,
        "V0.0 source paths are correctly registered.",
        "PASS",
        "Notebook 00 control plane verified.",
        True,
    ),
    completion_record(
        2,
        "The existing V0.0 raw collection is used as primary input.",
        "PASS",
        f"{v00_file_count} V0.0 files occur in the verified catalogue.",
        v00_file_count > 0,
    ),
    completion_record(
        3,
        "V0.1 does not require a copied raw-data directory.",
        "PASS",
        "Registered V0.0 source authority is preserved separately.",
        True,
    ),
    completion_record(
        4,
        "All V0.0 primary files have checksums.",
        "PASS",
        "Manifested-file physical verification passed.",
        all_physical_files_verified,
    ),
    completion_record(
        5,
        "The source run prefix remains preserved.",
        "PASS",
        str(
            SOURCE_RUN_PREFIX
        ),
        True,
    ),
    completion_record(
        6,
        "The pipeline runs from the registered V0.0 source set.",
        "PASS",
        "Notebooks 00–08 have complete persisted control planes.",
        True,
    ),
    completion_record(
        7,
        "Every completed phase has explicit saved outputs.",
        "PASS",
        f"{v01_file_count} V0.1 files were physically verified.",
        v01_file_count > 0,
    ),
    completion_record(
        8,
        "Every completed phase has an acceptance gate.",
        "PASS",
        "Stage-control coverage passed for Notebooks 00–08.",
        True,
    ),
    completion_record(
        9,
        "Differential-depth continuity is audited.",
        "PASS",
        "Notebook 01/02 control planes accepted.",
        True,
    ),
    completion_record(
        10,
        "The REST snapshot bridge is validated.",
        "PASS",
        "Notebook 01/02 control planes accepted.",
        True,
    ),
    completion_record(
        11,
        "Visible MBP reconstruction is reproducible.",
        "PASS",
        "Notebook 02 persisted output and handoff accepted.",
        True,
    ),
    completion_record(
        12,
        "LOCAL_STRICT causal alignment is audited.",
        "PASS",
        "Notebook 03 persisted output and handoff accepted.",
        True,
    ),
    completion_record(
        13,
        "Exact event-time ties have a defensible treatment.",
        "PASS",
        "Notebook 04 event and batch contracts accepted.",
        True,
    ),
    completion_record(
        14,
        "Event definitions are frozen before model comparison.",
        "PASS",
        "Notebook 04 precedes Notebook 06/07 and is persisted.",
        True,
    ),
    completion_record(
        15,
        "Poisson and simple baselines are established.",
        "PASS",
        (
            f"{EXPECTED_V01_FORMAL_COMPARATOR}; "
            f"{EXPECTED_V01_PRIMARY_SIMPLE_BASELINE}"
        ),
        True,
    ),
    completion_record(
        16,
        "The Hawkes estimator converges reliably.",
        "PASS_FOR_ESTIMATION_STAGE",
        "Notebook 07 accepted frozen H1 estimation.",
        True,
    ),
    completion_record(
        17,
        "The Hawkes parameterization convention is explicit.",
        "PASS",
        "Notebook 07 persisted execution and model contracts.",
        True,
    ),
    completion_record(
        18,
        "The model satisfies the stationarity safety margin.",
        "PASS",
        "Notebook 08 stationarity gate passed.",
        True,
    ),
    completion_record(
        19,
        "Split-boundary history is handled.",
        "PASS",
        "Notebook 07 boundary-history contract verified.",
        True,
    ),
    completion_record(
        20,
        "Residual diagnostics are acceptable.",
        "FAIL_BLOCKING",
        (
            "Residual distribution and residual serial-dependence "
            "gates failed on locked CALIBRATION."
        ),
        False,
    ),
    completion_record(
        21,
        "Validation likelihood improves over baselines.",
        "NOT_REACHED_BLOCKED",
        "Notebook 09 and VALIDATION were not authorized.",
        False,
    ),
    completion_record(
        22,
        "Parameter estimates are reasonably stable across windows.",
        "NOT_ESTABLISHED",
        (
            "No accepted multi-window validation authority was "
            "created after Notebook 08 failure."
        ),
        False,
    ),
    completion_record(
        23,
        "The intensity signal is tested against simpler controls.",
        "NOT_REACHED_BLOCKED",
        "Notebook 09 was skipped and not passed.",
        False,
    ),
    completion_record(
        24,
        "Latency decay is measured using local observability.",
        "NOT_REACHED_BLOCKED",
        "Signal validation was not authorized.",
        False,
    ),
    completion_record(
        25,
        "The final holdout remains untouched until Notebook 10.",
        "PASS_UNOPENED",
        (
            "ENGINEERING_HOLDOUT remained unopened throughout "
            "Notebooks 00–10."
        ),
        True,
    ),
    completion_record(
        26,
        "No tuning occurs after opening the holdout.",
        "PASS_HOLDOUT_NEVER_OPENED",
        "No holdout opening, refit, repair, or replacement occurred.",
        True,
    ),
    completion_record(
        27,
        "Important V0.0 results are reproduced or discrepancies explained.",
        "PASS_AS_RECORDED_BY_STAGE_AUTHORITIES",
        (
            "Control-plane and manifested-file reconciliation "
            "completed for Notebooks 00–08."
        ),
        True,
    ),
    completion_record(
        28,
        "The V0.2 handoff is complete.",
        "READY_FOR_PERSISTENCE",
        (
            "The bootstrap-only handoff is created in memory; "
            "persistence and semantic readback remain pending."
        ),
        False,
    ),
]


V01_COMPLETION_STANDARD_AUDIT = pd.DataFrame(
    completion_standard_records
)

if len(
    V01_COMPLETION_STANDARD_AUDIT
) != 28:
    raise V01TerminalSynthesisError(
        "The V0.1 completion-standard audit must contain 28 rows."
    )


completion_met_count = int(
    V01_COMPLETION_STANDARD_AUDIT[
        "completion_met"
    ].sum()
)

completion_unmet_count = int(
    (
        ~V01_COMPLETION_STANDARD_AUDIT[
            "completion_met"
        ]
    ).sum()
)


# ------------------------------------------------------------
# V0.2 carryover physical-file classification
# ------------------------------------------------------------

def normalized_stage_set(
    value: Any,
) -> set[str]:
    """Normalize the catalogue's source-stage representation."""

    if isinstance(
        value,
        (
            list,
            tuple,
            set,
        ),
    ):
        raw_values = value

    elif value is None:
        raw_values = []

    else:
        raw_values = re.findall(
            r"\d+",
            str(
                value
            ),
        )

    return {
        str(
            raw_value
        ).zfill(
            2
        )
        for raw_value in raw_values
    }


def classify_v02_carryover(
    row: pd.Series,
) -> tuple[str, str]:
    """Classify one verified physical file for V0.2."""

    relative_path = str(
        row.get(
            "relative_to_project",
            "",
        )
    ).casefold()

    authority_root = str(
        row.get(
            "authority_root",
            "",
        )
    )

    stages = normalized_stage_set(
        row.get(
            "source_stage_numbers"
        )
    )

    protected_reference = bool(
        row.get(
            "protected_partition_reference",
            False,
        )
    )

    if protected_reference:
        return (
            "PROTECTED_HASH_ONLY_REFERENCE",
            "HASH_ONLY_DO_NOT_OPEN_OR_REUSE_AS_V02_HOLDOUT",
        )

    if (
        "\\artifacts\\manifests\\" in relative_path
        or "/artifacts/manifests/" in relative_path
        or "\\artifacts\\handoff\\" in relative_path
        or "/artifacts/handoff/" in relative_path
    ):
        return (
            "CONTROL_PLANE_AUTHORITY",
            "AUDIT_AND_PROVENANCE_REFERENCE",
        )

    if authority_root == "V0.0":
        return (
            "IMMUTABLE_V00_SOURCE_OR_REFERENCE",
            "PROVENANCE_OR_REPRODUCTION_REFERENCE",
        )

    if "08" in stages:
        return (
            "FAILED_MODEL_DIAGNOSTIC_EVIDENCE",
            "DIAGNOSTIC_REFERENCE_ONLY",
        )

    if "07" in stages:
        return (
            "REJECTED_HAWKES_MODEL_REFERENCE",
            "DIAGNOSTIC_REFERENCE_ONLY_NOT_ACCEPTED_MODEL",
        )

    if "06" in stages:
        return (
            "POINT_PROCESS_BASELINE_AUTHORITY",
            "REPRODUCTION_TARGET_REFIT_ON_NEW_DATA",
        )

    if stages & {
        "00",
        "01",
        "02",
        "03",
        "04",
        "05",
    }:
        return (
            "CAUSAL_DATA_ENGINEERING_AUTHORITY",
            "REPRODUCTION_TARGET_REBUILD_ON_NEW_DATA",
        )

    return (
        "GENERAL_V01_PROVENANCE",
        "REFERENCE_ONLY",
    )


carryover_classifications = physical_catalogue.apply(
    classify_v02_carryover,
    axis=1,
    result_type="expand",
)

carryover_classifications.columns = [
    "v02_carryover_class",
    "v02_use_mode",
]

V01_V02_CARRYOVER_FILE_CATALOGUE = pd.concat(
    [
        physical_catalogue.reset_index(
            drop=True
        ),
        carryover_classifications.reset_index(
            drop=True
        ),
    ],
    axis=1,
)

V01_V02_CARRYOVER_FILE_CATALOGUE[
    "accepted_model_input_authorized"
] = False

V01_V02_CARRYOVER_FILE_CATALOGUE[
    "accepted_signal_input_authorized"
] = False

V01_V02_CARRYOVER_FILE_CATALOGUE[
    "strategy_input_authorized"
] = False


V01_V02_CARRYOVER_CLASS_SUMMARY = (
    V01_V02_CARRYOVER_FILE_CATALOGUE.groupby(
        [
            "v02_carryover_class",
            "v02_use_mode",
        ],
        dropna=False,
        sort=True,
    )
    .agg(
        file_count=(
            "resolved_path",
            "size",
        ),
        total_size_bytes=(
            "physical_size_bytes",
            "sum",
        ),
        protected_reference_count=(
            "protected_partition_reference",
            "sum",
        ),
    )
    .reset_index()
)


# ------------------------------------------------------------
# Explicit do-not-carry ledger
# ------------------------------------------------------------

V01_V02_DO_NOT_CARRY_LEDGER = pd.DataFrame(
    [
        {
            "item_id": "DNC01",
            "item": (
                "H1_DIAGONAL_SHARED_DECAY as an accepted V0.2 model"
            ),
            "reason": (
                "Failed locked-CALIBRATION model-adequacy gates."
            ),
            "permitted_use": (
                "Diagnostic reference and failure analysis only"
            ),
        },
        {
            "item_id": "DNC02",
            "item": (
                "Any H1-derived intensity signal as an accepted feature"
            ),
            "reason": (
                "Notebook 09 incremental-value testing was never run."
            ),
            "permitted_use": (
                "Hypothesis definition only"
            ),
        },
        {
            "item_id": "DNC03",
            "item": (
                "Notebook 09 as a completed or passed stage"
            ),
            "reason": (
                "Notebook 09 was explicitly blocked and skipped."
            ),
            "permitted_use": "None",
        },
        {
            "item_id": "DNC04",
            "item": (
                "VALIDATION or ENGINEERING_HOLDOUT results"
            ),
            "reason": (
                "Their analytical contents remained unopened."
            ),
            "permitted_use": (
                "Hash-only provenance"
            ),
        },
        {
            "item_id": "DNC05",
            "item": (
                "Full Hawkes superiority claim"
            ),
            "reason": (
                "Count-score superiority did not establish model adequacy."
            ),
            "permitted_use": (
                "Narrow score finding may be cited with limitations"
            ),
        },
        {
            "item_id": "DNC06",
            "item": (
                "Cross-excitation or state-dependent Hawkes authority"
            ),
            "reason": (
                "Neither extension was authorized as an accepted model."
            ),
            "permitted_use": (
                "Future predeclared candidate research only"
            ),
        },
        {
            "item_id": "DNC07",
            "item": (
                "Quoting, market-making, fill-simulation, or P&L logic"
            ),
            "reason": (
                "V0.1 ended before signal or strategy authorization."
            ),
            "permitted_use": "None",
        },
        {
            "item_id": "DNC08",
            "item": (
                "Interactive notebook state, repair variables, or "
                "temporary debugging logic"
            ),
            "reason": (
                "V0.2 must restart from persisted inputs and contracts."
            ),
            "permitted_use": "None",
        },
    ]
)


# ------------------------------------------------------------
# V0.2 bootstrap requirements
# ------------------------------------------------------------

V02_BOOTSTRAP_REQUIREMENTS = pd.DataFrame(
    [
        {
            "priority": 1,
            "requirement_id": "V02-R01",
            "requirement": (
                "Acquire and register a new, materially larger, "
                "multi-session source dataset."
            ),
            "reason": (
                "V0.1 used a short source run and could not complete "
                "credible validation and holdout stages."
            ),
            "blocking_before": "V0.2 NOTEBOOK 01",
        },
        {
            "priority": 2,
            "requirement_id": "V02-R02",
            "requirement": (
                "Create a new V0.2 run ID, source-set hash, split "
                "contract, and output tree."
            ),
            "reason": (
                "V0.2 must not continue hidden V0.1 notebook state."
            ),
            "blocking_before": "ANY V0.2 ANALYSIS",
        },
        {
            "priority": 3,
            "requirement_id": "V02-R03",
            "requirement": (
                "Rebuild raw audit, visible book, LOCAL_STRICT "
                "alignment, event stream, features, and labels from "
                "saved inputs."
            ),
            "reason": (
                "V0.1 artifacts are reproduction targets, not hidden "
                "runtime inputs."
            ),
            "blocking_before": "V0.2 MODELING",
        },
        {
            "priority": 4,
            "requirement_id": "V02-R04",
            "requirement": (
                "Predeclare and test event representations that address "
                "exact-time multiplicity and one-millisecond coarsening."
            ),
            "reason": (
                "Exact-time multiplicity was a blocking V0.1 failure."
            ),
            "blocking_before": "V0.2 HAWKES ESTIMATION",
        },
        {
            "priority": 5,
            "requirement_id": "V02-R05",
            "requirement": (
                "Re-establish Poisson, rolling, and EWMA baselines on "
                "the new dataset before Hawkes comparison."
            ),
            "reason": (
                "V0.2 needs dataset-specific locked comparators."
            ),
            "blocking_before": "V0.2 HAWKES SELECTION",
        },
        {
            "priority": 6,
            "requirement_id": "V02-R06",
            "requirement": (
                "Refit every Hawkes candidate from scratch; do not use "
                "V0.1 H1 parameters as initialization authority."
            ),
            "reason": (
                "V0.1 H1 is a rejected diagnostic reference."
            ),
            "blocking_before": "V0.2 CALIBRATION",
        },
        {
            "priority": 7,
            "requirement_id": "V02-R07",
            "requirement": (
                "Require residual-distribution, residual-serial, "
                "path-count, and multiplicity adequacy before opening "
                "VALIDATION."
            ),
            "reason": (
                "All four were blocking V0.1 diagnostic failures."
            ),
            "blocking_before": "V0.2 VALIDATION OPENING",
        },
        {
            "priority": 8,
            "requirement_id": "V02-R08",
            "requirement": (
                "Test cross-excitation or richer kernels only as "
                "predeclared candidates with explicit complexity gates."
            ),
            "reason": (
                "Extensions may not bypass ordinary-model adequacy."
            ),
            "blocking_before": "V0.2 CANDIDATE ACCEPTANCE",
        },
        {
            "priority": 9,
            "requirement_id": "V02-R09",
            "requirement": (
                "Authorize intensity-signal validation only after a "
                "frozen model passes calibration adequacy."
            ),
            "reason": (
                "Notebook 09 was correctly blocked in V0.1."
            ),
            "blocking_before": "V0.2 SIGNAL TESTING",
        },
        {
            "priority": 10,
            "requirement_id": "V02-R10",
            "requirement": (
                "Keep future labels physically separate and test "
                "incremental value against simpler causal controls."
            ),
            "reason": (
                "The Notebook 05 interface is valid and should be "
                "retained."
            ),
            "blocking_before": "V0.2 SIGNAL ACCEPTANCE",
        },
        {
            "priority": 11,
            "requirement_id": "V02-R11",
            "requirement": (
                "Measure latency decay using local observability before "
                "any signal handoff."
            ),
            "reason": (
                "Latency-decay testing was not reached in V0.1."
            ),
            "blocking_before": "V0.2 FINAL HOLDOUT",
        },
        {
            "priority": 12,
            "requirement_id": "V02-R12",
            "requirement": (
                "Open the final holdout once, only after model and "
                "signal definitions are frozen."
            ),
            "reason": (
                "No failed validation result may be repaired using the "
                "holdout."
            ),
            "blocking_before": "V0.2 FINAL DECISION",
        },
        {
            "priority": 13,
            "requirement_id": "V02-R13",
            "requirement": (
                "Do not begin quoting, fill simulation, or strategy "
                "evaluation until an intensity signal is accepted."
            ),
            "reason": (
                "V0.1 created no strategy authorization."
            ),
            "blocking_before": "ANY STRATEGY NOTEBOOK",
        },
    ]
)


# ------------------------------------------------------------
# Essential verified authority references
# ------------------------------------------------------------

ESSENTIAL_V01_CONTROL_ROLES_FOR_V02: Final[
    tuple[str, ...]
] = (
    "NOTEBOOK00_OUTPUT_MANIFEST",
    "NOTEBOOK01_OUTPUT_MANIFEST",
    "NOTEBOOK01_TO_NOTEBOOK02_HANDOFF",
    "NOTEBOOK02_OUTPUT_MANIFEST",
    "NOTEBOOK02_TO_NOTEBOOK03_HANDOFF",
    "NOTEBOOK03_OUTPUT_MANIFEST",
    "NOTEBOOK03_TO_NOTEBOOK04_HANDOFF",
    "NOTEBOOK04_OUTPUT_MANIFEST",
    "NOTEBOOK04_FINAL_ACCEPTANCE",
    "NOTEBOOK04_TO_NOTEBOOK05_HANDOFF",
    "NOTEBOOK05_OUTPUT_MANIFEST",
    "NOTEBOOK05_FINAL_ACCEPTANCE",
    "NOTEBOOK05_TO_NOTEBOOK06_HANDOFF",
    "NOTEBOOK06_OUTPUT_MANIFEST",
    "NOTEBOOK06_FINAL_ACCEPTANCE",
    "NOTEBOOK06_TERMINAL_DECISION",
    "NOTEBOOK06_TO_NOTEBOOK07_HANDOFF",
    "NOTEBOOK07_OUTPUT_MANIFEST",
    "NOTEBOOK07_FINAL_ACCEPTANCE",
    "NOTEBOOK07_TERMINAL_DECISION",
    "NOTEBOOK07_TO_NOTEBOOK08_HANDOFF",
    "NOTEBOOK08_FINAL_OUTPUT_MANIFEST",
    "NOTEBOOK08_FINAL_DISPOSITION",
    "NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF",
    "NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF",
)

control_role_rows = (
    control_registry.loc[
        control_registry[
            "role"
        ].isin(
            ESSENTIAL_V01_CONTROL_ROLES_FOR_V02
        )
    ]
    .copy()
)

observed_essential_control_roles = set(
    control_role_rows[
        "role"
    ].astype(
        str
    )
)

missing_essential_control_roles = sorted(
    set(
        ESSENTIAL_V01_CONTROL_ROLES_FOR_V02
    )
    - observed_essential_control_roles
)

if missing_essential_control_roles:
    raise V01TerminalSynthesisError(
        "Essential V0.1-to-V0.2 control authorities are missing:\n"
        f"{missing_essential_control_roles}"
    )


V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX = (
    control_role_rows[
        [
            "stage_number",
            "stage_name",
            "role",
            "artifact_kind",
            "path",
            "file_sha256",
            "control_status",
            "status",
        ]
    ]
    .sort_values(
        [
            "stage_number",
            "role",
        ],
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


essential_control_authorities_payload = [
    {
        "stage_number": str(
            row.stage_number
        ),
        "stage_name": str(
            row.stage_name
        ),
        "role": str(
            row.role
        ),
        "artifact_kind": str(
            row.artifact_kind
        ),
        "path": str(
            row.path
        ),
        "file_sha256": str(
            row.file_sha256
        ),
        "control_status": (
            None
            if pd.isna(
                row.control_status
            )
            else str(
                row.control_status
            )
        ),
    }
    for row in (
        V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX.itertuples(
            index=False
        )
    )
]


# ------------------------------------------------------------
# Final V0.1 decision
# ------------------------------------------------------------

V01_FINAL_DECISION = {
    "schema_version": (
        "V01_FINAL_AUDIT_SYNTHESIS_DECISION_V1"
    ),
    "created_utc": NOTEBOOK10_SYNTHESIS_CREATED_UTC,
    "producer": (
        "10_V01_FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF.ipynb"
    ),
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": (
        EXPECTED_V01_TERMINAL_CLASS
    ),
    "scientific_terminal_status": (
        EXPECTED_V01_TERMINAL_STATUS
    ),
    "pipeline_closeout_status": (
        EXPECTED_V01_CLOSEOUT_STATUS
    ),
    "selected_hawkes_model_id": (
        EXPECTED_V01_SELECTED_MODEL_ID
    ),
    "selected_model_disposition": (
        "REJECTED_FOR_DOWNSTREAM_SIGNAL_AUTHORIZATION"
    ),
    "count_score_superiority_supported": True,
    "full_model_adequacy_supported": False,
    "full_hawkes_superiority_supported": False,
    "failed_blocking_gates": sorted(
        EXPECTED_V01_FAILED_ADEQUACY_GATES
    ),
    "notebook09_execution_state": (
        "SKIPPED_NOT_PASSED"
    ),
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "model_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "accepted_model_handoff_to_v0_2_authorized": False,
    "v0_2_handoff_scope": EXPECTED_V02_HANDOFF_SCOPE,
    "completion_standard_met_count": (
        completion_met_count
    ),
    "completion_standard_unmet_count": (
        completion_unmet_count
    ),
    "completion_standard_fully_met": False,
    "next_authorized_operation": (
        "PERSIST_AND_READ_BACK_V0_1_CLOSEOUT_AND_V0_2_BOOTSTRAP_HANDOFF"
    ),
}


# ------------------------------------------------------------
# V0.2 bootstrap-handoff payload
# ------------------------------------------------------------

V02_BOOTSTRAP_HANDOFF = {
    "schema_version": (
        "V01_TO_V02_BOOTSTRAP_HANDOFF_V1"
    ),
    "created_utc": NOTEBOOK10_SYNTHESIS_CREATED_UTC,
    "producer": (
        "10_V01_FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF.ipynb"
    ),
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "v0_1_terminal_class": (
        EXPECTED_V01_TERMINAL_CLASS
    ),
    "v0_1_terminal_status": (
        EXPECTED_V01_TERMINAL_STATUS
    ),
    "handoff_scope": EXPECTED_V02_HANDOFF_SCOPE,
    "accepted_model_authorized": False,
    "accepted_signal_authorized": False,
    "strategy_authorized": False,
    "validation_result_available": False,
    "engineering_holdout_result_available": False,
    "v0_1_selected_model": {
        "model_id": (
            EXPECTED_V01_SELECTED_MODEL_ID
        ),
        "status": (
            "REJECTED_DIAGNOSTIC_REFERENCE_ONLY"
        ),
        "count_score_superiority_supported": True,
        "full_model_adequacy_supported": False,
        "failed_blocking_gates": sorted(
            EXPECTED_V01_FAILED_ADEQUACY_GATES
        ),
    },
    "baseline_authority": {
        "formal_comparator": (
            EXPECTED_V01_FORMAL_COMPARATOR
        ),
        "primary_simple_baseline": (
            EXPECTED_V01_PRIMARY_SIMPLE_BASELINE
        ),
        "v0_2_use": (
            "DEFINITION_AND_REPRODUCTION_REFERENCE_REFIT_ON_NEW_DATA"
        ),
    },
    "feature_interface_authority": {
        "identity_columns": list(
            notebook05_authority.get(
                "identity_columns",
                [],
            )
        ),
        "feature_count": (
            feature_table_authority.get(
                "feature_count"
            )
        ),
        "future_label_count": (
            future_label_table_authority.get(
                "label_count"
            )
        ),
        "feature_timing_class": (
            feature_table_authority.get(
                "timing_class"
            )
        ),
        "future_label_timing_class": (
            future_label_table_authority.get(
                "timing_class"
            )
        ),
        "v0_2_use": (
            "PRESERVE_CONTRACT_REBUILD_TABLES_ON_NEW_DATA"
        ),
    },
    "carryover_classes": [
        {
            "v02_carryover_class": str(
                row.v02_carryover_class
            ),
            "v02_use_mode": str(
                row.v02_use_mode
            ),
            "file_count": int(
                row.file_count
            ),
            "total_size_bytes": int(
                row.total_size_bytes
            ),
            "protected_reference_count": int(
                row.protected_reference_count
            ),
        }
        for row in (
            V01_V02_CARRYOVER_CLASS_SUMMARY.itertuples(
                index=False
            )
        )
    ],
    "essential_control_authorities": (
        essential_control_authorities_payload
    ),
    "do_not_carry": [
        {
            "item_id": str(
                row.item_id
            ),
            "item": str(
                row.item
            ),
            "reason": str(
                row.reason
            ),
            "permitted_use": str(
                row.permitted_use
            ),
        }
        for row in (
            V01_V02_DO_NOT_CARRY_LEDGER.itertuples(
                index=False
            )
        )
    ],
    "bootstrap_requirements": [
        {
            "priority": int(
                row.priority
            ),
            "requirement_id": str(
                row.requirement_id
            ),
            "requirement": str(
                row.requirement
            ),
            "reason": str(
                row.reason
            ),
            "blocking_before": str(
                row.blocking_before
            ),
        }
        for row in (
            V02_BOOTSTRAP_REQUIREMENTS.itertuples(
                index=False
            )
        )
    ],
    "protected_partition_policy": {
        "validation_content_loaded": False,
        "engineering_holdout_content_loaded": False,
        "old_protected_files_use": (
            "HASH_ONLY_PROVENANCE_NOT_V02_EVALUATION_DATA"
        ),
    },
    "v0_2_restart_contract": {
        "fresh_notebook_sequence_required": True,
        "new_source_set_required": True,
        "new_v0_2_run_id_required": True,
        "new_chronological_split_contract_required": True,
        "refit_models_from_scratch": True,
        "reuse_v0_1_h1_parameters_as_authority": False,
        "reuse_v0_1_validation_or_holdout_as_v0_2_holdout": False,
        "authorize_signal_before_model_adequacy": False,
        "authorize_strategy_before_signal_acceptance": False,
    },
    "status": (
        "READY_FOR_PERSISTENCE_BOOTSTRAP_ONLY"
    ),
}


# ------------------------------------------------------------
# Semantic hashes for the in-memory terminal authorities
# ------------------------------------------------------------

V01_FINAL_DECISION[
    "payload_sha256"
] = v01_canonical_sha256(
    V01_FINAL_DECISION
)

V02_BOOTSTRAP_HANDOFF[
    "payload_sha256"
] = v01_canonical_sha256(
    V02_BOOTSTRAP_HANDOFF
)


# ------------------------------------------------------------
# Final synthesis integrity checks
# ------------------------------------------------------------

if V01_FINAL_DECISION[
    "scientific_terminal_class"
] != "FAIL":
    raise V01TerminalSynthesisError(
        "The V0.1 scientific terminal class was not preserved."
    )

if V01_FINAL_DECISION[
    "model_signal_handoff_authorized"
]:
    raise V01TerminalSynthesisError(
        "A model-signal handoff was incorrectly authorized."
    )

if V01_FINAL_DECISION[
    "accepted_model_handoff_to_v0_2_authorized"
]:
    raise V01TerminalSynthesisError(
        "H1 was incorrectly authorized as a V0.2 accepted model."
    )

if V02_BOOTSTRAP_HANDOFF[
    "accepted_model_authorized"
]:
    raise V01TerminalSynthesisError(
        "The V0.2 bootstrap handoff incorrectly authorizes a model."
    )

if V02_BOOTSTRAP_HANDOFF[
    "accepted_signal_authorized"
]:
    raise V01TerminalSynthesisError(
        "The V0.2 bootstrap handoff incorrectly authorizes a signal."
    )

if V02_BOOTSTRAP_HANDOFF[
    "strategy_authorized"
]:
    raise V01TerminalSynthesisError(
        "The V0.2 bootstrap handoff incorrectly authorizes strategy work."
    )

if V01_COMPLETION_STANDARD_AUDIT.loc[
    V01_COMPLETION_STANDARD_AUDIT[
        "criterion_number"
    ].eq(
        20
    ),
    "outcome",
].iloc[
    0
] != "FAIL_BLOCKING":
    raise V01TerminalSynthesisError(
        "The failed residual-diagnostic completion criterion was "
        "not preserved."
    )

if not {
    "NOT_REACHED_BLOCKED",
}.issubset(
    set(
        V01_COMPLETION_STANDARD_AUDIT.loc[
            V01_COMPLETION_STANDARD_AUDIT[
                "criterion_number"
            ].isin(
                [
                    21,
                    23,
                    24,
                ]
            ),
            "outcome",
        ]
    )
):
    raise V01TerminalSynthesisError(
        "Blocked downstream completion criteria were not preserved."
    )


# ------------------------------------------------------------
# Summary tables
# ------------------------------------------------------------

V01_TERMINAL_SYNTHESIS_SUMMARY = pd.DataFrame(
    [
        {
            "metric": "scientific_terminal_class",
            "value": (
                V01_FINAL_DECISION[
                    "scientific_terminal_class"
                ]
            ),
        },
        {
            "metric": "scientific_terminal_status",
            "value": (
                V01_FINAL_DECISION[
                    "scientific_terminal_status"
                ]
            ),
        },
        {
            "metric": "pipeline_closeout_status",
            "value": (
                V01_FINAL_DECISION[
                    "pipeline_closeout_status"
                ]
            ),
        },
        {
            "metric": "selected_model_id",
            "value": EXPECTED_V01_SELECTED_MODEL_ID,
        },
        {
            "metric": "count_score_superiority_supported",
            "value": True,
        },
        {
            "metric": "full_model_adequacy_supported",
            "value": False,
        },
        {
            "metric": "notebook09_status",
            "value": "SKIPPED_NOT_PASSED",
        },
        {
            "metric": "completion_standard_met_count",
            "value": completion_met_count,
        },
        {
            "metric": "completion_standard_unmet_count",
            "value": completion_unmet_count,
        },
        {
            "metric": "verified_physical_file_count",
            "value": int(
                len(
                    physical_catalogue
                )
            ),
        },
        {
            "metric": "v02_handoff_scope",
            "value": EXPECTED_V02_HANDOFF_SCOPE,
        },
        {
            "metric": "accepted_model_handoff_authorized",
            "value": False,
        },
        {
            "metric": "accepted_signal_handoff_authorized",
            "value": False,
        },
        {
            "metric": "strategy_handoff_authorized",
            "value": False,
        },
        {
            "metric": "validation_content_loaded",
            "value": False,
        },
        {
            "metric": "engineering_holdout_content_loaded",
            "value": False,
        },
        {
            "metric": "v01_final_decision_payload_sha256",
            "value": (
                V01_FINAL_DECISION[
                    "payload_sha256"
                ]
            ),
        },
        {
            "metric": "v02_bootstrap_handoff_payload_sha256",
            "value": (
                V02_BOOTSTRAP_HANDOFF[
                    "payload_sha256"
                ]
            ),
        },
    ]
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    V01_TERMINAL_SYNTHESIS_SUMMARY
)

display(
    V01_FINAL_STAGE_DISPOSITION_LEDGER
)

display(
    V01_COMPLETION_STANDARD_AUDIT
)

display(
    V01_FINAL_CLAIM_LEDGER
)

display(
    V01_V02_CARRYOVER_CLASS_SUMMARY
)

display(
    V01_V02_DO_NOT_CARRY_LEDGER
)

display(
    V02_BOOTSTRAP_REQUIREMENTS
)

display(
    V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX
)


# ------------------------------------------------------------
# Freeze in-memory Notebook 10 synthesis authority
# ------------------------------------------------------------

FROZEN_V01_TERMINAL_SYNTHESIS_AUTHORITY = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "created_utc": NOTEBOOK10_SYNTHESIS_CREATED_UTC,
    "final_decision": dict(
        V01_FINAL_DECISION
    ),
    "v0_2_bootstrap_handoff": dict(
        V02_BOOTSTRAP_HANDOFF
    ),
    "stage_disposition_record_count": int(
        len(
            V01_FINAL_STAGE_DISPOSITION_LEDGER
        )
    ),
    "completion_standard_record_count": int(
        len(
            V01_COMPLETION_STANDARD_AUDIT
        )
    ),
    "claim_record_count": int(
        len(
            V01_FINAL_CLAIM_LEDGER
        )
    ),
    "carryover_file_count": int(
        len(
            V01_V02_CARRYOVER_FILE_CATALOGUE
        )
    ),
    "do_not_carry_record_count": int(
        len(
            V01_V02_DO_NOT_CARRY_LEDGER
        )
    ),
    "bootstrap_requirement_count": int(
        len(
            V02_BOOTSTRAP_REQUIREMENTS
        )
    ),
    "essential_control_authority_count": int(
        len(
            V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX
        )
    ),
    "scientific_terminal_class": "FAIL",
    "pipeline_closeout_status": (
        EXPECTED_V01_CLOSEOUT_STATUS
    ),
    "v0_2_handoff_scope": (
        EXPECTED_V02_HANDOFF_SCOPE
    ),
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "protected_partition_content_loaded": {
        "VALIDATION": False,
        "ENGINEERING_HOLDOUT": False,
    },
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
}


# ------------------------------------------------------------
# State update
#
# All upstream V0.1 authorities required for synthesis have now
# been verified. Persistence of Notebook 10 outputs remains
# pending and is the next authorized operation.
# ------------------------------------------------------------

UPSTREAM_ARTIFACTS_VERIFIED = True

V01_TERMINAL_SYNTHESIS_CREATED = True
V01_COMPLETION_STANDARD_AUDITED = True
V01_FINAL_CLAIM_LEDGER_CREATED = True
V01_V02_CARRYOVER_CATALOGUE_CREATED = True
V02_BOOTSTRAP_HANDOFF_CREATED = True

V01_TERMINAL_SYNTHESIS_PERSISTED = False
V01_TERMINAL_SYNTHESIS_READBACK_VERIFIED = False
V02_BOOTSTRAP_HANDOFF_PERSISTED = False
V02_BOOTSTRAP_HANDOFF_READBACK_VERIFIED = False

V01_MODEL_SIGNAL_AUTHORIZATION_GRANTED = False
V01_STRATEGY_AUTHORIZATION_GRANTED = False
V01_V02_MODEL_HANDOFF_AUTHORIZED = False

NOTEBOOK09_EXECUTED = False
NOTEBOOK09_AUTHORIZED = False

VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False
PROTECTED_PARTITION_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "V0.1 terminal synthesis: PASS. The pipeline is ready to "
    "persist a formally closed failed scientific branch. "
    "Notebooks 00–07 remain accepted within their declared stage "
    "scopes; Notebook 08 remains a blocking Hawkes-adequacy "
    "failure; Notebook 09 remains skipped and not passed. Frozen "
    "H1 retains only its narrow locked-CALIBRATION count-score "
    "finding and is not authorized as a V0.2 model or signal. "
    "The V0.2 handoff is bootstrap- and provenance-only and "
    "requires a new, materially better source dataset, a new run "
    "identity, fresh reconstruction, and model refitting from "
    "scratch. VALIDATION and ENGINEERING_HOLDOUT remain unopened. "
    "No filesystem writes were performed."
)

                                  metric                                                               value
0              scientific_terminal_class                                                                FAIL
1             scientific_terminal_status           FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY
2               pipeline_closeout_status                          PASS_READY_TO_PERSIST_CLOSED_FAILED_BRANCH
3                      selected_model_id                                            H1_DIAGONAL_SHARED_DECAY
4      count_score_superiority_supported                                                                True
5          full_model_adequacy_supported                                                               False
6                      notebook09_status                                                  SKIPPED_NOT_PASSED
7          completion_standard_met_count                                                                  22
8        completion_standard_unmet_count                                                                   6
9           verified_physical_file_count                                                                 440
10                     v02_handoff_scope  BOOTSTRAP_AND_PROVENANCE_ONLY_NO_ACCEPTED_MODEL_SIGNAL_OR_STRATEGY
11     accepted_model_handoff_authorized                                                               False
12    accepted_signal_handoff_authorized                                                               False
13           strategy_handoff_authorized                                                               False
14             validation_content_loaded                                                               False
15    engineering_holdout_content_loaded                                                               False
16     v01_final_decision_payload_sha256    68e3505b3c146df1ad5bb3055d518b8632cff5aac8d3660533af44d3dd5e3bbc
17  v02_bootstrap_handoff_payload_sha256    2c93e3b9c1dc377f826cde4f6991239bf0df265c785777b42425d56d9d6c7ee7

,stage_number,stage_name,execution_state,scientific_state,downstream_state,control_plane_complete,observed_control_statuses,status
0,00,V01_RUN_CONTRACT,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,[CONDITIONAL PASS],PASS
1,01,RAW_DATA_AUDIT,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,[CONDITIONAL PASS],PASS
2,02,VISIBLE_BOOK_RECONSTRUCTION,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,[PASS_WITH_REFERENCE_WARNINGS],PASS
3,03,CAUSAL_TRADE_BOOK_ALIGNMENT,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,[PASS_WITH_ALIGNMENT_WARNINGS],PASS
4,04,EVENT_STREAM_CONSTRUCTION,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,[PASS_WITH_EVENT_STREAM_WARNINGS],PASS
5,05,MARKET_STATE_FEATURES,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,[PASS_WITH_FEATURE_WARNINGS],PASS
6,06,POINT_PROCESS_BASELINES,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,"[PASS, PASS_HAWKES_RESTRICTED_FIRST]",PASS
7,07,HAWKES_ESTIMATION,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,"[PASS_HANDOFF_FOR_HAWKES_DIAGNOSTICS, PASS_HAWKES_ESTIMATION_RESTRICTED_FIRST]",PASS
8,08,HAWKES_DIAGNOSTICS,COMPLETED,FAILED_REQUIRED_MODEL_ADEQUACY,DIAGNOSTIC_REFERENCE_ONLY,True,"[BLOCKING_REJECTION, FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY, PASS_HANDOFF_TO_FINAL_AUDIT_AFTER_DIAGNOSTIC_FAILURE, object]",FAIL_SCIENTIFIC
9,09,INTENSITY_SIGNAL_VALIDATION,SKIPPED_BY_UPSTREAM_BLOCK,NOT_TESTED,NO_AUTHORITY_CREATED,True,[BLOCKED_BY_NOTEBOOK08_DIAGNOSTIC_FAILURE],SKIPPED_NOT_PASSED
10,10,FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF,IN_MEMORY_SYNTHESIS_CREATED,CLOSING_FAILED_V0_1_BRANCH,BOOTSTRAP_AND_PROVENANCE_ONLY_NO_ACCEPTED_MODEL_SIGNAL_OR_STRATEGY,False,[PERSISTENCE_PENDING],PASS_READY_FOR_PERSISTENCE

,criterion_number,criterion,outcome,completion_met,evidence
0,1,V0.0 source paths are correctly registered.,PASS,True,Notebook 00 control plane verified.
1,2,The existing V0.0 raw collection is used as primary input.,PASS,True,6 V0.0 files occur in the verified catalogue.
2,3,V0.1 does not require a copied raw-data directory.,PASS,True,Registered V0.0 source authority is preserved separately.
3,4,All V0.0 primary files have checksums.,PASS,True,Manifested-file physical verification passed.
4,5,The source run prefix remains preserved.,PASS,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12
5,6,The pipeline runs from the registered V0.0 source set.,PASS,True,Notebooks 00–08 have complete persisted control planes.
6,7,Every completed phase has explicit saved outputs.,PASS,True,434 V0.1 files were physically verified.
7,8,Every completed phase has an acceptance gate.,PASS,True,Stage-control coverage passed for Notebooks 00–08.
8,9,Differential-depth continuity is audited.,PASS,True,Notebook 01/02 control planes accepted.
9,10,The REST snapshot bridge is validated.,PASS,True,Notebook 01/02 control planes accepted.
10,11,Visible MBP reconstruction is reproducible.,PASS,True,Notebook 02 persisted output and handoff accepted.
11,12,LOCAL_STRICT causal alignment is audited.,PASS,True,Notebook 03 persisted output and handoff accepted.
12,13,Exact event-time ties have a defensible treatment.,PASS,True,Notebook 04 event and batch contracts accepted.
13,14,Event definitions are frozen before model comparison.,PASS,True,Notebook 04 precedes Notebook 06/07 and is persisted.
14,15,Poisson and simple baselines are established.,PASS,True,D0_SIDE_CONSTANT_POISSON; E_SIDE_EWMA_250MS_POISSON
15,16,The Hawkes estimator converges reliably.,PASS_FOR_ESTIMATION_STAGE,True,Notebook 07 accepted frozen H1 estimation.
16,17,The Hawkes parameterization convention is explicit.,PASS,True,Notebook 07 persisted execution and model contracts.
17,18,The model satisfies the stationarity safety margin.,PASS,True,Notebook 08 stationarity gate passed.
18,19,Split-boundary history is handled.,PASS,True,Notebook 07 boundary-history contract verified.
19,20,Residual diagnostics are acceptable.,FAIL_BLOCKING,False,Residual distribution and residual serial-dependence gates failed on locked CALIBRATION.
20,21,Validation likelihood improves over baselines.,NOT_REACHED_BLOCKED,False,Notebook 09 and VALIDATION were not authorized.
21,22,Parameter estimates are reasonably stable across windows.,NOT_ESTABLISHED,False,No accepted multi-window validation authority was created after Notebook 08 failure.
22,23,The intensity signal is tested against simpler controls.,NOT_REACHED_BLOCKED,False,Notebook 09 was skipped and not passed.
23,24,Latency decay is measured using local observability.,NOT_REACHED_BLOCKED,False,Signal validation was not authorized.
24,25,The final holdout remains untouched until Notebook 10.,PASS_UNOPENED,True,ENGINEERING_HOLDOUT remained unopened throughout Notebooks 00–10.
25,26,No tuning occurs after opening the holdout.,PASS_HOLDOUT_NEVER_OPENED,True,"No holdout opening, refit, repair, or replacement occurred."
26,27,Important V0.0 results are reproduced or discrepancies explained.,PASS_AS_RECORDED_BY_STAGE_AUTHORITIES,True,Control-plane and manifested-file reconciliation completed for Notebooks 00–08.
27,28,The V0.2 handoff is complete.,READY_FOR_PERSISTENCE,False,The bootstrap-only handoff is created in memory; persistence and semantic readback remain pending.

,claim_id,claim_domain,claim,disposition,evidence_scope,v02_treatment
0,C01,SOURCE_AUTHORITY,The registered V0.0 source collection is the immutable primary input authority.,SUPPORTED,Notebook 00 control plane and verified physical file catalogue,PRESERVE_AS_PROVENANCE_AND_REPRODUCTION_REFERENCE
1,C02,BOOK_RECONSTRUCTION,The visible market-by-price reconstruction passed its declared V0.1 stage gates.,SUPPORTED,Notebook 02 persisted acceptance and handoff,PRESERVE_LOGIC_AND_REBUILD_ON_NEW_SOURCE_DATA
2,C03,CAUSAL_ALIGNMENT,LOCAL_STRICT collector-observable trade/book alignment is the accepted synchronization authority.,SUPPORTED,Notebook 03 persisted acceptance and handoff,CARRY_CONTRACT_AND_REIMPLEMENT_FROM_FRESH_NOTEBOOK
3,C04,EVENT_STREAM,The accepted primary event representation is same-millisecond same-side bursts.,SUPPORTED_FOR_V0_1,Notebook 04 event-definition and partition contracts,RETAIN_AS_REFERENCE_BUT_RETEST_MULTIPLICITY_DESIGN
4,C05,FEATURE_INTERFACE,571 causal T-minus features are physically separated from 140 future-label fields.,SUPPORTED,Notebook 05 contract and registry reconciliation,PRESERVE_INTERFACE_CONTRACT_AND_REBUILD_ON_NEW_DATA
5,C06,BASELINES,Notebook 06 established locked point-process comparators before Hawkes diagnostics.,SUPPORTED,Formal comparator=D0_SIDE_CONSTANT_POISSON; primary simple baseline=E_SIDE_EWMA_250MS_POISSON,PRESERVE_BASELINE_DEFINITIONS_AND_REFIT_FROM_SCRATCH
6,C07,HAWKES_ESTIMATION,"H1 was fitted on DEVELOPMENT, locked before CALIBRATION, and received zero CALIBRATION updates.",SUPPORTED,Notebook 07 model contract and quantitative reconciliation,PRESERVE_AS_REJECTED_DIAGNOSTIC_REFERENCE_ONLY
7,C08,SCORE_EVIDENCE,Frozen H1 achieved superior locked-CALIBRATION count score over all authorized Notebook 06 baselines.,SUPPORTED_NARROWLY,Notebook 08 paired complete-block bootstrap and locked score ranking,RETAIN_AS_HYPOTHESIS_MOTIVATION_NOT_MODEL_AUTHORITY
8,C09,MODEL_ADEQUACY,Frozen H1 adequately reproduces the locked CALIBRATION event process.,REJECTED,"[LOCKED_CALIBRATION_EXACT_TIME_MULTIPLICITY, LOCKED_CALIBRATION_PATH_COUNT_CALIBRATION, LOCKED_CALIBRATION_RESIDUAL_DISTRIBUTION, LOCKED_CALIBRATION_RESIDUA...",RETAIN_FAILURE_LEDGER_AS_PRIMARY_REDESIGN_INPUT
9,C10,FULL_HAWKES_SUPERIORITY,H1 is generally superior to simpler point-process models.,NOT_AUTHORIZED,Higher count likelihood is insufficient because required model-adequacy gates failed.,DO_NOT_CARRY_AS_ACCEPTED_CLAIM
10,C11,SIGNAL_VALUE,Hawkes intensity adds incremental causal predictive information beyond simpler controls.,NOT_TESTED,Notebook 09 was blocked before VALIDATION opened.,REQUIRE_NEW_VALIDATION_STAGE_AFTER_MODEL_ADEQUACY
11,C12,PROTECTED_DATA,VALIDATION and ENGINEERING_HOLDOUT remained unopened.,SUPPORTED,Persisted Notebook 07/08 closure evidence and Notebook 10 runtime guards,PRESERVE_HASH_ONLY_PROVENANCE_DO_NOT_REUSE_AS_NEW_HOLDOUT
12,C13,STRATEGY,"V0.1 authorizes quoting, market making, fill simulation, or P&L claims.",PROHIBITED,Notebook 05–08 downstream authorization boundaries,NO_STRATEGY_WORK_BEFORE_SIGNAL_ACCEPTANCE
13,C14,V02_HANDOFF,H1 or a derived intensity signal may enter V0.2 as an accepted model.,PROHIBITED,Notebook 08 failed model adequacy and blocked Notebook 09,BOOTSTRAP_AND_PROVENANCE_ONLY

                 v02_carryover_class                                   v02_use_mode  file_count  total_size_bytes  protected_reference_count
0  CAUSAL_DATA_ENGINEERING_AUTHORITY        REPRODUCTION_TARGET_REBUILD_ON_NEW_DATA         123         639732702                          0
1            CONTROL_PLANE_AUTHORITY                 AUDIT_AND_PROVENANCE_REFERENCE          45           1253221                          0
2   FAILED_MODEL_DIAGNOSTIC_EVIDENCE                      DIAGNOSTIC_REFERENCE_ONLY          66           5672196                          0
3  IMMUTABLE_V00_SOURCE_OR_REFERENCE           PROVENANCE_OR_REPRODUCTION_REFERENCE           6         114848029                          0
4   POINT_PROCESS_BASELINE_AUTHORITY          REPRODUCTION_TARGET_REFIT_ON_NEW_DATA         137          36150421                          0
5      PROTECTED_HASH_ONLY_REFERENCE  HASH_ONLY_DO_NOT_OPEN_OR_REUSE_AS_V02_HOLDOUT           7             18515                          7
6    REJECTED_HAWKES_MODEL_REFERENCE   DIAGNOSTIC_REFERENCE_ONLY_NOT_ACCEPTED_MODEL          56           5998311                          0

  item_id                                                                        item                                                     reason                                       permitted_use
0   DNC01                          H1_DIAGONAL_SHARED_DECAY as an accepted V0.2 model            Failed locked-CALIBRATION model-adequacy gates.      Diagnostic reference and failure analysis only
1   DNC02                      Any H1-derived intensity signal as an accepted feature       Notebook 09 incremental-value testing was never run.                          Hypothesis definition only
2   DNC03                                  Notebook 09 as a completed or passed stage            Notebook 09 was explicitly blocked and skipped.                                                None
3   DNC04                                   VALIDATION or ENGINEERING_HOLDOUT results               Their analytical contents remained unopened.                                Hash-only provenance
4   DNC05                                               Full Hawkes superiority claim  Count-score superiority did not establish model adequacy.  Narrow score finding may be cited with limitations
5   DNC06                        Cross-excitation or state-dependent Hawkes authority     Neither extension was authorized as an accepted model.          Future predeclared candidate research only
6   DNC07                       Quoting, market-making, fill-simulation, or P&L logic        V0.1 ended before signal or strategy authorization.                                                None
7   DNC08  Interactive notebook state, repair variables, or temporary debugging logic     V0.2 must restart from persisted inputs and contracts.                                                None

,priority,requirement_id,requirement,reason,blocking_before
0,1,V02-R01,"Acquire and register a new, materially larger, multi-session source dataset.",V0.1 used a short source run and could not complete credible validation and holdout stages.,V0.2 NOTEBOOK 01
1,2,V02-R02,"Create a new V0.2 run ID, source-set hash, split contract, and output tree.",V0.2 must not continue hidden V0.1 notebook state.,ANY V0.2 ANALYSIS
2,3,V02-R03,"Rebuild raw audit, visible book, LOCAL_STRICT alignment, event stream, features, and labels from saved inputs.","V0.1 artifacts are reproduction targets, not hidden runtime inputs.",V0.2 MODELING
3,4,V02-R04,Predeclare and test event representations that address exact-time multiplicity and one-millisecond coarsening.,Exact-time multiplicity was a blocking V0.1 failure.,V0.2 HAWKES ESTIMATION
4,5,V02-R05,"Re-establish Poisson, rolling, and EWMA baselines on the new dataset before Hawkes comparison.",V0.2 needs dataset-specific locked comparators.,V0.2 HAWKES SELECTION
5,6,V02-R06,Refit every Hawkes candidate from scratch; do not use V0.1 H1 parameters as initialization authority.,V0.1 H1 is a rejected diagnostic reference.,V0.2 CALIBRATION
6,7,V02-R07,"Require residual-distribution, residual-serial, path-count, and multiplicity adequacy before opening VALIDATION.",All four were blocking V0.1 diagnostic failures.,V0.2 VALIDATION OPENING
7,8,V02-R08,Test cross-excitation or richer kernels only as predeclared candidates with explicit complexity gates.,Extensions may not bypass ordinary-model adequacy.,V0.2 CANDIDATE ACCEPTANCE
8,9,V02-R09,Authorize intensity-signal validation only after a frozen model passes calibration adequacy.,Notebook 09 was correctly blocked in V0.1.,V0.2 SIGNAL TESTING
9,10,V02-R10,Keep future labels physically separate and test incremental value against simpler causal controls.,The Notebook 05 interface is valid and should be retained.,V0.2 SIGNAL ACCEPTANCE
10,11,V02-R11,Measure latency decay using local observability before any signal handoff.,Latency-decay testing was not reached in V0.1.,V0.2 FINAL HOLDOUT
11,12,V02-R12,"Open the final holdout once, only after model and signal definitions are frozen.",No failed validation result may be repaired using the holdout.,V0.2 FINAL DECISION
12,13,V02-R13,"Do not begin quoting, fill simulation, or strategy evaluation until an intensity signal is accepted.",V0.1 created no strategy authorization.,ANY STRATEGY NOTEBOOK

,stage_number,stage_name,role,artifact_kind,path,file_sha256,control_status,status
0,00,V01_RUN_CONTRACT,NOTEBOOK00_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__00_v01_run_contract__notebook_00_outpu...,e12966301d92e61656715f2a6d397786820de836d8156dd70092250619cbb00e,CONDITIONAL PASS,PASS
1,01,RAW_DATA_AUDIT,NOTEBOOK01_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__01_raw_data_audit__notebook_01_output_...,2bb561126bbfc20fd25aa80131c1c11307e651d38ed3d6ee26a11b2ff0f41a4f,CONDITIONAL PASS,PASS
2,01,RAW_DATA_AUDIT,NOTEBOOK01_TO_NOTEBOOK02_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__01_raw_data_audit__notebook_01_to_notebo...,138704253d8821259a7be427620a11b1d469a7f009c13c252c7587b51b440c61,CONDITIONAL PASS,PASS
3,02,VISIBLE_BOOK_RECONSTRUCTION,NOTEBOOK02_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__02_visible_book_reconstruction__notebo...,0150ed8386326d30017ed892d82a8980f9c8a3d9ba13fb0e7bc2d01d055a2f8e,PASS_WITH_REFERENCE_WARNINGS,PASS
4,02,VISIBLE_BOOK_RECONSTRUCTION,NOTEBOOK02_TO_NOTEBOOK03_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__02_visible_book_reconstruction__notebook...,10e1a952818158f35dfacd5a5e1645dc6656d81e6dd23af2f7befd7fd4ab7388,PASS_WITH_REFERENCE_WARNINGS,PASS
5,03,CAUSAL_TRADE_BOOK_ALIGNMENT,NOTEBOOK03_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__03_causal_trade_book_alignment__notebo...,4daa7fa17c2f953e3b931b607e1b5b066f4e29e7dea7397d86b3c9e3b77406ca,PASS_WITH_ALIGNMENT_WARNINGS,PASS
6,03,CAUSAL_TRADE_BOOK_ALIGNMENT,NOTEBOOK03_TO_NOTEBOOK04_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__03_causal_trade_book_alignment__notebook...,6f4d48e4fbb56d9ac80b415b3c0fe6c4625526b555938b846ee2876626b6152e,PASS_WITH_ALIGNMENT_WARNINGS,PASS
7,04,EVENT_STREAM_CONSTRUCTION,NOTEBOOK04_FINAL_ACCEPTANCE,FINAL_ACCEPTANCE,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__04_event_stream_construction__notebook...,f120060e83e37877f6cac860d0246a61a7546b9a4bd8c7b66fd1a61377021f80,PASS_WITH_EVENT_STREAM_WARNINGS,PASS
8,04,EVENT_STREAM_CONSTRUCTION,NOTEBOOK04_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__04_event_stream_construction__notebook...,a685a2dd6847f31a7a80c3d42c814ac4dd1f4d3797dd12f0c3f6b19347cad520,PASS_WITH_EVENT_STREAM_WARNINGS,PASS
9,04,EVENT_STREAM_CONSTRUCTION,NOTEBOOK04_TO_NOTEBOOK05_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__04_event_stream_construction__notebook_0...,6dce59c55f2a95c69d5fe0b50c44df9aad80cba6eb1260d7f1de0caee537f926,PASS_WITH_EVENT_STREAM_WARNINGS,PASS
10,05,MARKET_STATE_FEATURES,NOTEBOOK05_FINAL_ACCEPTANCE,FINAL_ACCEPTANCE,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__final_accept...,9459c6278313e0d4fdb8f722c22f3694d54afecead99c5e85cdba60ffc02ebec,PASS_WITH_FEATURE_WARNINGS,PASS
11,05,MARKET_STATE_FEATURES,NOTEBOOK05_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__notebook_05_...,52b4912f1f1d86bae9d28e048a318eaac63d741b7eaac124eec1061b6699f2d9,PASS_WITH_FEATURE_WARNINGS,PASS
12,05,MARKET_STATE_FEATURES,NOTEBOOK05_TO_NOTEBOOK06_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__05_market_state_features__to_06_point_pr...,80c41a6a58e44962febc03da64bf49c8924904bc477a31ae9c01a1695852108d,PASS_WITH_FEATURE_WARNINGS,PASS
13,06,POINT_PROCESS_BASELINES,NOTEBOOK06_FINAL_ACCEPTANCE,FINAL_ACCEPTANCE,d:\clown project\v0.1\artifacts\manifests\06_point_process_baselines_final_acceptance.json,7ee4127508d49809f39e99b799458681a83133901038ba246e3a3f076833a4d1,PASS_HAWKES_RESTRICTED_FIRST,PASS
14,06,POINT_PROCESS_BASELINES,NOTEBOOK06_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\06_point_process_baselines_output_manifest.json,56dfc09bc96b0ce8456f4801e6c553d63694e58a620f0bd2a65c86c016f55c04,PASS_HAWKES_RESTRICTED_FIRST,PASS
15,06,POINT_PROCESS_BASELINES,NOTEBOOK06_TERMINAL_DECISION,TERMINAL_DECISION,d:\clown project\v0.1\artifacts\manifests\06_point_process_baselines_terminal_decision.json,6c53c509fe1122883e217d741f195dd76cfeda975f8203fc54a57647f9b830ce,PASS_HAWKES_RESTRICTED_FIRST,PASS
16,06,POINT_PROCESS_BASELINES,NOTEBOOK06_TO_NOTEBOOK07_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\06_point_process_baselines_to_07_hawkes_estimation_handoff.json,c7c57532241580395a4aa29121f20fcb40385fb2aeecf08de18d5f2775a45a46,PASS_HAWKES_RESTRICTED_FIRST,PASS
17,07,HAWKES_ESTIMATION,NOTEBOOK07_FINAL_ACCEPTANCE,FINAL_ACCEPTANCE,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_hawkes_estimation_final_acceptance....,32f462888a36d37d95e7e8b0e69a9297c7b074203c2827e5a6c519372ddf5e72,PASS_HAWKES_ESTIMATION_RESTRICTED_FIRST,PASS
18,07,HAWKES_ESTIMATION,NOTEBOOK07_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_hawkes_estimation_output_manifest.json,abc93a03ba93ab41ec6fccede348391f38c96661599041661f14f5d4799f28e5,PASS_HAWKES_ESTIMATION_RESTRICTED_FIRST,PASS
19,07,HAWKES_ESTIMATION,NOTEBOOK07_TERMINAL_DECISION,TERMINAL_DECISION,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_terminal_decision.json,d1a6a55b97ce3f4e2cf8bd4958b42124d9b609f56c39dd62f062e1a69ac9304b,PASS_HAWKES_ESTIMATION_RESTRICTED_FIRST,PASS
20,07,HAWKES_ESTIMATION,NOTEBOOK07_TO_NOTEBOOK08_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__07_to_08_hawkes_diagnostics_handoff.json,93683fdbc65acb010cbdbe4f3e80979867a58382f5c0a7147c5ce18d33bd9c0c,PASS_HANDOFF_FOR_HAWKES_DIAGNOSTICS,PASS
21,08,HAWKES_DIAGNOSTICS,NOTEBOOK08_FINAL_DISPOSITION,FINAL_DISPOSITION,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_final_dispositio...,3abe2261e45aec3fd8663513df0b33f3c220043ff5315783fbae7c5a2cf5656a,FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY,PASS
22,08,HAWKES_DIAGNOSTICS,NOTEBOOK08_FINAL_OUTPUT_MANIFEST,OUTPUT_MANIFEST,d:\clown project\v0.1\artifacts\manifests\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_hawkes_diagnostics_output_manifest....,37363e818ef0f6461a2b531b9998ee0b091e48c9fedcc42b8e99cb8ec26bcee1,object,PASS
23,08,HAWKES_DIAGNOSTICS,NOTEBOOK08_TO_NOTEBOOK09_BLOCKED_HANDOFF,BLOCKED_HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_to_09_intensity_signal_validation_blo...,e4c0b3f7800e077117cb95109bd52d2700c2a0ea61175358a4e60febb9034a20,BLOCKING_REJECTION,PASS
24,08,HAWKES_DIAGNOSTICS,NOTEBOOK08_TO_NOTEBOOK10_AUDIT_HANDOFF,HANDOFF,d:\clown project\v0.1\artifacts\handoff\btcusdt_spot_20260710t063746z_c8b5bf12__v0_1_20260714t090616z_e82325081a81__08_to_10_final_audit_handoff.json,900066c6a3b5c6c74f80f3a77403258a0115c31e3a10ff18aeafeed643f8a479,PASS_HANDOFF_TO_FINAL_AUDIT_AFTER_DIAGNOSTIC_FAILURE,PASS

V0.1 terminal synthesis: PASS. The pipeline is ready to persist a formally closed failed scientific branch. Notebooks 00–07 remain accepted within their declared stage scopes; Notebook 08 remains a blocking Hawkes-adequacy failure; Notebook 09 remains skipped and not passed. Frozen H1 retains only its narrow locked-CALIBRATION count-score finding and is not authorized as a V0.2 model or signal. The V0.2 handoff is bootstrap- and provenance-only and requires a new, materially better source dataset, a new run identity, fresh reconstruction, and model refitting from scratch. VALIDATION and ENGINEERING_HOLDOUT remain unopened. No filesystem writes were performed.

In [34]:
# ============================================================
# Notebook 10 persistence and output-manifest construction
#
# This cell persists the verified V0.1 terminal closeout and
# bootstrap-only V0.2 handoff.
#
# Persistence properties:
# - deterministic JSON serialization;
# - deterministic gzip output with mtime=0;
# - atomic same-directory writes;
# - idempotent reuse only when existing bytes are identical;
# - fail-closed refusal to overwrite differing artifacts;
# - exact physical SHA-256, shape, schema, and path registration;
# - Notebook 10 output manifest written last;
# - manifest SHA-256 sidecar written after the manifest.
#
# Semantic readback is intentionally deferred to the next cell.
# ============================================================

from __future__ import annotations

import gzip
import hashlib
import io
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any, Final, Mapping

import numpy as np
import pandas as pd
from IPython.display import display


class Notebook10PersistenceError(RuntimeError):
    """Raised when Notebook 10 persistence cannot complete safely."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

REQUIRED_NOTEBOOK10_PERSISTENCE_FLAGS: Final[
    dict[str, bool]
] = {
    "UPSTREAM_ARTIFACTS_VERIFIED": bool(
        globals().get(
            "UPSTREAM_ARTIFACTS_VERIFIED",
            False,
        )
    ),
    "V01_TERMINAL_SYNTHESIS_CREATED": bool(
        globals().get(
            "V01_TERMINAL_SYNTHESIS_CREATED",
            False,
        )
    ),
    "V01_COMPLETION_STANDARD_AUDITED": bool(
        globals().get(
            "V01_COMPLETION_STANDARD_AUDITED",
            False,
        )
    ),
    "V01_FINAL_CLAIM_LEDGER_CREATED": bool(
        globals().get(
            "V01_FINAL_CLAIM_LEDGER_CREATED",
            False,
        )
    ),
    "V01_V02_CARRYOVER_CATALOGUE_CREATED": bool(
        globals().get(
            "V01_V02_CARRYOVER_CATALOGUE_CREATED",
            False,
        )
    ),
    "V02_BOOTSTRAP_HANDOFF_CREATED": bool(
        globals().get(
            "V02_BOOTSTRAP_HANDOFF_CREATED",
            False,
        )
    ),
}

failed_persistence_flags = sorted(
    flag_name
    for flag_name, passed in (
        REQUIRED_NOTEBOOK10_PERSISTENCE_FLAGS.items()
    )
    if not passed
)

if failed_persistence_flags:
    raise Notebook10PersistenceError(
        "Notebook 10 persistence prerequisites have not passed:\n"
        f"{failed_persistence_flags}"
    )


REQUIRED_NOTEBOOK10_OBJECTS: Final[
    tuple[str, ...]
] = (
    "V01_FINAL_DECISION",
    "V02_BOOTSTRAP_HANDOFF",
    "V01_TERMINAL_SYNTHESIS_SUMMARY",
    "V01_FINAL_STAGE_DISPOSITION_LEDGER",
    "V01_COMPLETION_STANDARD_AUDIT",
    "V01_FINAL_CLAIM_LEDGER",
    "V01_V02_CARRYOVER_FILE_CATALOGUE",
    "V01_V02_CARRYOVER_CLASS_SUMMARY",
    "V01_V02_DO_NOT_CARRY_LEDGER",
    "V02_BOOTSTRAP_REQUIREMENTS",
    "V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX",
    "V01_ROOT",
    "V01_MANIFEST_ROOT",
    "V01_HANDOFF_ROOT",
    "COMBINED_OUTPUT_PREFIX",
)

missing_notebook10_objects = sorted(
    object_name
    for object_name in REQUIRED_NOTEBOOK10_OBJECTS
    if object_name not in globals()
)

if missing_notebook10_objects:
    raise Notebook10PersistenceError(
        "Required Notebook 10 objects are unavailable:\n"
        f"{missing_notebook10_objects}"
    )


if not isinstance(
    V01_FINAL_DECISION,
    Mapping,
):
    raise Notebook10PersistenceError(
        "V01_FINAL_DECISION must be a mapping."
    )

if not isinstance(
    V02_BOOTSTRAP_HANDOFF,
    Mapping,
):
    raise Notebook10PersistenceError(
        "V02_BOOTSTRAP_HANDOFF must be a mapping."
    )


# ------------------------------------------------------------
# Runtime safety guards
# ------------------------------------------------------------

if bool(
    globals().get(
        "VALIDATION_CONTENT_LOADED",
        False,
    )
):
    raise Notebook10PersistenceError(
        "VALIDATION content was unexpectedly loaded."
    )

if bool(
    globals().get(
        "ENGINEERING_HOLDOUT_CONTENT_LOADED",
        False,
    )
):
    raise Notebook10PersistenceError(
        "ENGINEERING_HOLDOUT content was unexpectedly loaded."
    )

protected_runtime_state = globals().get(
    "PROTECTED_PARTITION_CONTENT_LOADED",
    False,
)

if isinstance(
    protected_runtime_state,
    Mapping,
):
    opened_partitions = sorted(
        str(
            partition
        )
        for partition, loaded in (
            protected_runtime_state.items()
        )
        if bool(
            loaded
        )
    )

    if opened_partitions:
        raise Notebook10PersistenceError(
            "Protected partition content was unexpectedly marked "
            f"as loaded: {opened_partitions}"
        )

elif bool(
    protected_runtime_state
):
    raise Notebook10PersistenceError(
        "Protected partition content was unexpectedly loaded."
    )


if bool(
    globals().get(
        "MODEL_REFIT_PERFORMED",
        False,
    )
):
    raise Notebook10PersistenceError(
        "A model refit was recorded before persistence."
    )

if bool(
    globals().get(
        "MODEL_REPLACEMENT_PERFORMED",
        False,
    )
):
    raise Notebook10PersistenceError(
        "A model replacement was recorded before persistence."
    )

if int(
    globals().get(
        "CALIBRATION_PARAMETER_UPDATES_PERFORMED",
        0,
    )
) != 0:
    raise Notebook10PersistenceError(
        "Nonzero CALIBRATION parameter updates were recorded."
    )


# ------------------------------------------------------------
# Path and naming authority
# ------------------------------------------------------------

NOTEBOOK10_STAGE_SLUG: Final[str] = (
    "10_v01_final_audit_synthesis_and_v02_handoff"
)

combined_prefix_text = str(
    COMBINED_OUTPUT_PREFIX
).strip()

if not combined_prefix_text:
    raise Notebook10PersistenceError(
        "COMBINED_OUTPUT_PREFIX is blank."
    )

if (
    Path(
        combined_prefix_text
    ).name
    != combined_prefix_text
    or "/" in combined_prefix_text
    or "\\" in combined_prefix_text
):
    raise Notebook10PersistenceError(
        "COMBINED_OUTPUT_PREFIX contains a path separator."
    )


NOTEBOOK10_OUTPUT_PREFIX: Final[str] = (
    f"{combined_prefix_text}__{NOTEBOOK10_STAGE_SLUG}"
)

NOTEBOOK10_AUDIT_TABLE_ROOT: Final[Path] = (
    Path(
        V01_ROOT
    )
    / "artifacts"
    / "audit_tables"
    / NOTEBOOK10_STAGE_SLUG
)

NOTEBOOK10_FINAL_DECISION_PATH: Final[Path] = (
    Path(
        V01_MANIFEST_ROOT
    )
    / (
        f"{NOTEBOOK10_OUTPUT_PREFIX}"
        "__v01_final_decision.json"
    )
)

NOTEBOOK10_V02_HANDOFF_PATH: Final[Path] = (
    Path(
        V01_HANDOFF_ROOT
    )
    / (
        f"{NOTEBOOK10_OUTPUT_PREFIX}"
        "__v01_to_v02_bootstrap_handoff.json"
    )
)

NOTEBOOK10_OUTPUT_MANIFEST_PATH: Final[Path] = (
    Path(
        V01_MANIFEST_ROOT
    )
    / (
        f"{NOTEBOOK10_OUTPUT_PREFIX}"
        "__notebook10_output_manifest.json"
    )
)

NOTEBOOK10_OUTPUT_MANIFEST_SHA256_PATH: Final[Path] = (
    NOTEBOOK10_OUTPUT_MANIFEST_PATH.with_suffix(
        NOTEBOOK10_OUTPUT_MANIFEST_PATH.suffix
        + ".sha256"
    )
)


def notebook10_normalized_path(
    value: Any,
) -> Path:
    """Return an absolute normalized path."""

    return Path(
        str(
            value
        )
    ).expanduser().resolve(
        strict=False
    )


def notebook10_require_inside_v01(
    path: Path,
    *,
    role: str,
) -> Path:
    """Require one output path to remain inside V0.1."""

    normalized_path = notebook10_normalized_path(
        path
    )

    normalized_v01_root = notebook10_normalized_path(
        V01_ROOT
    )

    try:
        normalized_path.relative_to(
            normalized_v01_root
        )

    except ValueError as exc:
        raise Notebook10PersistenceError(
            "Notebook 10 output path lies outside V0.1.\n"
            f"Role: {role}\n"
            f"Path: {normalized_path}"
        ) from exc

    return normalized_path


for output_role, output_path in (
    (
        "NOTEBOOK10_AUDIT_TABLE_ROOT",
        NOTEBOOK10_AUDIT_TABLE_ROOT,
    ),
    (
        "NOTEBOOK10_FINAL_DECISION",
        NOTEBOOK10_FINAL_DECISION_PATH,
    ),
    (
        "NOTEBOOK10_V02_BOOTSTRAP_HANDOFF",
        NOTEBOOK10_V02_HANDOFF_PATH,
    ),
    (
        "NOTEBOOK10_OUTPUT_MANIFEST",
        NOTEBOOK10_OUTPUT_MANIFEST_PATH,
    ),
    (
        "NOTEBOOK10_OUTPUT_MANIFEST_SHA256",
        NOTEBOOK10_OUTPUT_MANIFEST_SHA256_PATH,
    ),
):
    notebook10_require_inside_v01(
        output_path,
        role=output_role,
    )


# ------------------------------------------------------------
# Canonical serialization helpers
# ------------------------------------------------------------

def notebook10_plain_value(
    value: Any,
) -> Any:
    """Convert values into strict JSON-compatible Python types."""

    if value is None:
        return None

    if isinstance(
        value,
        Path,
    ):
        return str(
            value
        )

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(
            value
        )

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        return int(
            value
        )

    if isinstance(
        value,
        (float, np.floating),
    ):
        numeric_value = float(
            value
        )

        if not np.isfinite(
            numeric_value
        ):
            return str(
                numeric_value
            )

        return numeric_value

    if isinstance(
        value,
        pd.Timestamp,
    ):
        return value.isoformat()

    if isinstance(
        value,
        Mapping,
    ):
        return {
            str(
                key
            ): notebook10_plain_value(
                child
            )
            for key, child in value.items()
        }

    if isinstance(
        value,
        (
            list,
            tuple,
            set,
        ),
    ):
        iterable = (
            sorted(
                value
            )
            if isinstance(
                value,
                set,
            )
            else value
        )

        return [
            notebook10_plain_value(
                child
            )
            for child in iterable
        ]

    try:
        missing_value = pd.isna(
            value
        )

        if isinstance(
            missing_value,
            (bool, np.bool_),
        ) and bool(
            missing_value
        ):
            return None

    except (
        TypeError,
        ValueError,
    ):
        pass

    return str(
        value
    )


def notebook10_canonical_sha256(
    payload: Mapping[str, Any],
) -> str:
    """Return the semantic SHA-256 of one mapping."""

    canonical_bytes = json.dumps(
        notebook10_plain_value(
            payload
        ),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode(
        "utf-8"
    )

    return hashlib.sha256(
        canonical_bytes
    ).hexdigest()


def notebook10_payload_with_semantic_hash(
    payload: Mapping[str, Any],
    *,
    hash_field: str = "payload_sha256",
) -> dict[str, Any]:
    """Return a copied payload with a non-self-referential hash."""

    copied_payload = dict(
        notebook10_plain_value(
            payload
        )
    )

    copied_payload.pop(
        hash_field,
        None,
    )

    copied_payload[
        hash_field
    ] = notebook10_canonical_sha256(
        copied_payload
    )

    return copied_payload


def notebook10_json_bytes(
    payload: Mapping[str, Any],
) -> bytes:
    """Serialize one JSON artifact deterministically."""

    serialized = json.dumps(
        notebook10_plain_value(
            payload
        ),
        sort_keys=True,
        indent=2,
        ensure_ascii=False,
        allow_nan=False,
    )

    return (
        serialized
        + "\n"
    ).encode(
        "utf-8"
    )


def notebook10_scalar_for_csv(
    value: Any,
) -> Any:
    """Convert one value into a stable CSV representation."""

    if isinstance(
        value,
        (
            Mapping,
            list,
            tuple,
            set,
        ),
    ):
        return json.dumps(
            notebook10_plain_value(
                value
            ),
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
            allow_nan=False,
        )

    if isinstance(
        value,
        Path,
    ):
        return str(
            value
        )

    if isinstance(
        value,
        pd.Timestamp,
    ):
        return value.isoformat()

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(
            value
        )

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        return int(
            value
        )

    if isinstance(
        value,
        (float, np.floating),
    ):
        numeric_value = float(
            value
        )

        if not np.isfinite(
            numeric_value
        ):
            return str(
                numeric_value
            )

        return numeric_value

    try:
        missing_value = pd.isna(
            value
        )

        if isinstance(
            missing_value,
            (bool, np.bool_),
        ) and bool(
            missing_value
        ):
            return None

    except (
        TypeError,
        ValueError,
    ):
        pass

    return value


def notebook10_dataframe_csv_bytes(
    dataframe: pd.DataFrame,
) -> tuple[bytes, str]:
    """
    Return deterministic gzip bytes and the uncompressed CSV hash.

    gzip mtime is fixed at zero so physical hashes remain stable
    across clean reruns.
    """

    export_frame = dataframe.copy(
        deep=True
    )

    for column_name in export_frame.columns:
        if (
            pd.api.types.is_object_dtype(
                export_frame[
                    column_name
                ].dtype
            )
            or pd.api.types.is_string_dtype(
                export_frame[
                    column_name
                ].dtype
            )
        ):
            export_frame[
                column_name
            ] = export_frame[
                column_name
            ].map(
                notebook10_scalar_for_csv
            )

    csv_text = export_frame.to_csv(
        index=False,
        lineterminator="\n",
        na_rep="",
        float_format="%.17g",
    )

    csv_bytes = csv_text.encode(
        "utf-8"
    )

    uncompressed_sha256 = hashlib.sha256(
        csv_bytes
    ).hexdigest()

    compressed_buffer = io.BytesIO()

    with gzip.GzipFile(
        filename="",
        mode="wb",
        fileobj=compressed_buffer,
        compresslevel=9,
        mtime=0,
    ) as gzip_stream:
        gzip_stream.write(
            csv_bytes
        )

    return (
        compressed_buffer.getvalue(),
        uncompressed_sha256,
    )


# ------------------------------------------------------------
# Physical hashing and atomic persistence
# ------------------------------------------------------------

def notebook10_sha256_bytes(
    payload_bytes: bytes,
) -> str:
    """Return the SHA-256 digest of bytes."""

    return hashlib.sha256(
        payload_bytes
    ).hexdigest()


def notebook10_sha256_file(
    path: Path,
    *,
    chunk_size: int = 1 << 20,
) -> str:
    """Return the physical SHA-256 digest of one file."""

    digest = hashlib.sha256()

    with path.open(
        "rb"
    ) as input_stream:
        while True:
            chunk = input_stream.read(
                chunk_size
            )

            if not chunk:
                break

            digest.update(
                chunk
            )

    return digest.hexdigest()


def notebook10_atomic_write_exact(
    path: Path,
    payload_bytes: bytes,
    *,
    role: str,
) -> dict[str, Any]:
    """
    Atomically create one exact artifact.

    Existing files are accepted only when their bytes are
    identical. Differing existing files are never overwritten.
    """

    normalized_path = notebook10_require_inside_v01(
        path,
        role=role,
    )

    normalized_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    intended_sha256 = notebook10_sha256_bytes(
        payload_bytes
    )

    if normalized_path.exists():
        if not normalized_path.is_file():
            raise Notebook10PersistenceError(
                "An intended output path already exists but is not "
                f"a regular file: {normalized_path}"
            )

        existing_sha256 = notebook10_sha256_file(
            normalized_path
        )

        if existing_sha256 != intended_sha256:
            raise Notebook10PersistenceError(
                "Refusing to overwrite a differing existing "
                "Notebook 10 artifact.\n"
                f"Role: {role}\n"
                f"Path: {normalized_path}\n"
                f"Existing SHA-256: {existing_sha256}\n"
                f"Intended SHA-256: {intended_sha256}"
            )

        return {
            "path": normalized_path,
            "sha256": existing_sha256,
            "size_bytes": int(
                normalized_path.stat().st_size
            ),
            "write_action": "REUSED_IDENTICAL",
        }

    temporary_path: Path | None = None

    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=normalized_path.parent,
            prefix=(
                normalized_path.name
                + "."
            ),
            suffix=".tmp",
            delete=False,
        ) as temporary_stream:
            temporary_path = Path(
                temporary_stream.name
            )

            notebook10_require_inside_v01(
                temporary_path,
                role=f"{role}_TEMPORARY_FILE",
            )

            temporary_stream.write(
                payload_bytes
            )

            temporary_stream.flush()
            os.fsync(
                temporary_stream.fileno()
            )

        temporary_sha256 = notebook10_sha256_file(
            temporary_path
        )

        if temporary_sha256 != intended_sha256:
            raise Notebook10PersistenceError(
                "Temporary artifact hash differs from intended "
                f"bytes for role: {role}"
            )

        if normalized_path.exists():
            existing_sha256 = notebook10_sha256_file(
                normalized_path
            )

            if existing_sha256 != intended_sha256:
                raise Notebook10PersistenceError(
                    "The target appeared during persistence with "
                    f"differing content: {normalized_path}"
                )

            temporary_path.unlink(
                missing_ok=True
            )

            temporary_path = None

            return {
                "path": normalized_path,
                "sha256": existing_sha256,
                "size_bytes": int(
                    normalized_path.stat().st_size
                ),
                "write_action": "REUSED_IDENTICAL_AFTER_RACE",
            }

        os.replace(
            temporary_path,
            normalized_path,
        )

        temporary_path = None

    finally:
        if (
            temporary_path is not None
            and temporary_path.exists()
        ):
            temporary_path.unlink(
                missing_ok=True
            )

    observed_sha256 = notebook10_sha256_file(
        normalized_path
    )

    if observed_sha256 != intended_sha256:
        raise Notebook10PersistenceError(
            "Persisted artifact hash differs from intended bytes.\n"
            f"Role: {role}\n"
            f"Path: {normalized_path}"
        )

    return {
        "path": normalized_path,
        "sha256": observed_sha256,
        "size_bytes": int(
            normalized_path.stat().st_size
        ),
        "write_action": "CREATED_ATOMICALLY",
    }


# ------------------------------------------------------------
# Create persistence-state copies
# ------------------------------------------------------------

persisted_stage_disposition = (
    V01_FINAL_STAGE_DISPOSITION_LEDGER.copy(
        deep=True
    )
)

stage10_mask = persisted_stage_disposition[
    "stage_number"
].astype(
    "string"
).str.zfill(
    2
).eq(
    "10"
)

if int(
    stage10_mask.sum()
) != 1:
    raise Notebook10PersistenceError(
        "The final stage-disposition ledger must contain exactly "
        "one Notebook 10 row."
    )

persisted_stage_disposition.loc[
    stage10_mask,
    "execution_state",
] = "PERSISTED_AWAITING_SEMANTIC_READBACK"

persisted_stage_disposition.loc[
    stage10_mask,
    "scientific_state",
] = "CLOSED_FAILED_V0_1_BRANCH"

persisted_stage_disposition.loc[
    stage10_mask,
    "control_plane_complete",
] = True

persisted_stage_disposition.loc[
    stage10_mask,
    "observed_control_statuses",
] = pd.Series(
    [
        [
            "PASS_PERSISTED_AWAITING_SEMANTIC_READBACK",
        ]
    ],
    index=persisted_stage_disposition.index[
        stage10_mask
    ],
    dtype="object",
)

persisted_stage_disposition.loc[
    stage10_mask,
    "status",
] = "PASS_PERSISTED_AWAITING_SEMANTIC_READBACK"


persisted_completion_standard = (
    V01_COMPLETION_STANDARD_AUDIT.copy(
        deep=True
    )
)

criterion28_mask = persisted_completion_standard[
    "criterion_number"
].eq(
    28
)

if int(
    criterion28_mask.sum()
) != 1:
    raise Notebook10PersistenceError(
        "The completion-standard audit must contain exactly one "
        "criterion 28 row."
    )

persisted_completion_standard.loc[
    criterion28_mask,
    "outcome",
] = "PERSISTED_AWAITING_SEMANTIC_READBACK"

persisted_completion_standard.loc[
    criterion28_mask,
    "completion_met",
] = False

persisted_completion_standard.loc[
    criterion28_mask,
    "evidence",
] = (
    "The bootstrap-only handoff and Notebook 10 closeout "
    "artifacts were persisted; semantic readback remains pending."
)


persisted_final_decision = dict(
    notebook10_plain_value(
        V01_FINAL_DECISION
    )
)

persisted_final_decision[
    "pipeline_closeout_status"
] = "PASS_PERSISTED_AWAITING_SEMANTIC_READBACK"

persisted_final_decision[
    "completion_standard_met_count"
] = int(
    persisted_completion_standard[
        "completion_met"
    ].sum()
)

persisted_final_decision[
    "completion_standard_unmet_count"
] = int(
    (
        ~persisted_completion_standard[
            "completion_met"
        ]
    ).sum()
)

persisted_final_decision[
    "next_authorized_operation"
] = (
    "VERIFY_NOTEBOOK10_SEMANTIC_READBACK_AND_FINALIZE_CLOSEOUT"
)

persisted_final_decision = (
    notebook10_payload_with_semantic_hash(
        persisted_final_decision
    )
)


persisted_v02_handoff = dict(
    notebook10_plain_value(
        V02_BOOTSTRAP_HANDOFF
    )
)

persisted_v02_handoff[
    "status"
] = "PERSISTED_AWAITING_SEMANTIC_READBACK"

persisted_v02_handoff[
    "next_authorized_operation"
] = (
    "VERIFY_NOTEBOOK10_SEMANTIC_READBACK_AND_BEGIN_NEW_V02_RUN_CONTRACT"
)

persisted_v02_handoff = (
    notebook10_payload_with_semantic_hash(
        persisted_v02_handoff
    )
)


persisted_terminal_summary = pd.DataFrame(
    [
        {
            "metric": "scientific_terminal_class",
            "value": persisted_final_decision[
                "scientific_terminal_class"
            ],
        },
        {
            "metric": "scientific_terminal_status",
            "value": persisted_final_decision[
                "scientific_terminal_status"
            ],
        },
        {
            "metric": "pipeline_closeout_status",
            "value": persisted_final_decision[
                "pipeline_closeout_status"
            ],
        },
        {
            "metric": "selected_model_id",
            "value": persisted_final_decision[
                "selected_hawkes_model_id"
            ],
        },
        {
            "metric": "count_score_superiority_supported",
            "value": True,
        },
        {
            "metric": "full_model_adequacy_supported",
            "value": False,
        },
        {
            "metric": "notebook09_status",
            "value": "SKIPPED_NOT_PASSED",
        },
        {
            "metric": "completion_standard_met_count",
            "value": persisted_final_decision[
                "completion_standard_met_count"
            ],
        },
        {
            "metric": "completion_standard_unmet_count",
            "value": persisted_final_decision[
                "completion_standard_unmet_count"
            ],
        },
        {
            "metric": "verified_physical_file_count_before_notebook10",
            "value": int(
                len(
                    V01_MASTER_PHYSICAL_ARTIFACT_CATALOGUE
                )
            ),
        },
        {
            "metric": "v02_handoff_scope",
            "value": persisted_final_decision[
                "v0_2_handoff_scope"
            ],
        },
        {
            "metric": "accepted_model_handoff_authorized",
            "value": False,
        },
        {
            "metric": "accepted_signal_handoff_authorized",
            "value": False,
        },
        {
            "metric": "strategy_handoff_authorized",
            "value": False,
        },
        {
            "metric": "validation_content_loaded",
            "value": False,
        },
        {
            "metric": "engineering_holdout_content_loaded",
            "value": False,
        },
        {
            "metric": "v01_final_decision_payload_sha256",
            "value": persisted_final_decision[
                "payload_sha256"
            ],
        },
        {
            "metric": "v02_bootstrap_handoff_payload_sha256",
            "value": persisted_v02_handoff[
                "payload_sha256"
            ],
        },
        {
            "metric": "semantic_readback_verified",
            "value": False,
        },
    ]
)


# ------------------------------------------------------------
# Tables to persist
# ------------------------------------------------------------

NOTEBOOK10_TABLES_TO_PERSIST: Final[
    dict[str, pd.DataFrame]
] = {
    "V01_TERMINAL_SYNTHESIS_SUMMARY": (
        persisted_terminal_summary
    ),
    "V01_FINAL_STAGE_DISPOSITION_LEDGER": (
        persisted_stage_disposition
    ),
    "V01_COMPLETION_STANDARD_AUDIT": (
        persisted_completion_standard
    ),
    "V01_FINAL_CLAIM_LEDGER": (
        V01_FINAL_CLAIM_LEDGER.copy(
            deep=True
        )
    ),
    "V01_V02_CARRYOVER_FILE_CATALOGUE": (
        V01_V02_CARRYOVER_FILE_CATALOGUE.copy(
            deep=True
        )
    ),
    "V01_V02_CARRYOVER_CLASS_SUMMARY": (
        V01_V02_CARRYOVER_CLASS_SUMMARY.copy(
            deep=True
        )
    ),
    "V01_V02_DO_NOT_CARRY_LEDGER": (
        V01_V02_DO_NOT_CARRY_LEDGER.copy(
            deep=True
        )
    ),
    "V02_BOOTSTRAP_REQUIREMENTS": (
        V02_BOOTSTRAP_REQUIREMENTS.copy(
            deep=True
        )
    ),
    "V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX": (
        V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX.copy(
            deep=True
        )
    ),
}


# ------------------------------------------------------------
# Persist deterministic tabular artifacts
# ------------------------------------------------------------

notebook10_artifact_records: list[
    dict[str, Any]
] = []

for variable_name, dataframe in (
    NOTEBOOK10_TABLES_TO_PERSIST.items()
):
    safe_variable_slug = re.sub(
        r"[^a-z0-9]+",
        "_",
        variable_name.casefold(),
    ).strip(
        "_"
    )

    table_path = (
        NOTEBOOK10_AUDIT_TABLE_ROOT
        / (
            f"{NOTEBOOK10_OUTPUT_PREFIX}"
            f"__{safe_variable_slug}.csv.gz"
        )
    )

    (
        compressed_table_bytes,
        uncompressed_csv_sha256,
    ) = notebook10_dataframe_csv_bytes(
        dataframe
    )

    write_result = notebook10_atomic_write_exact(
        table_path,
        compressed_table_bytes,
        role=variable_name,
    )

    notebook10_artifact_records.append(
        {
            "artifact_type": (
                "NOTEBOOK_10_AUDIT_TABLE"
            ),
            "artifact_role": (
                safe_variable_slug
            ),
            "variable_name": variable_name,
            "path": str(
                write_result[
                    "path"
                ]
            ),
            "relative_path": str(
                write_result[
                    "path"
                ].relative_to(
                    notebook10_normalized_path(
                        V01_ROOT
                    )
                )
            ),
            "format": "CSV_GZIP",
            "row_count": int(
                len(
                    dataframe
                )
            ),
            "column_count": int(
                dataframe.shape[
                    1
                ]
            ),
            "columns": list(
                map(
                    str,
                    dataframe.columns,
                )
            ),
            "dtypes": {
                str(
                    column
                ): str(
                    dtype
                )
                for column, dtype in (
                    dataframe.dtypes.items()
                )
            },
            "uncompressed_csv_sha256": (
                uncompressed_csv_sha256
            ),
            "sha256": write_result[
                "sha256"
            ],
            "size_bytes": int(
                write_result[
                    "size_bytes"
                ]
            ),
            "write_action": write_result[
                "write_action"
            ],
            "status": "PASS_PERSISTED",
        }
    )


# ------------------------------------------------------------
# Persist terminal decision and V0.2 bootstrap handoff
# ------------------------------------------------------------

for (
    variable_name,
    artifact_type,
    artifact_role,
    output_path,
    payload,
) in (
    (
        "V01_FINAL_DECISION",
        "NOTEBOOK_10_FINAL_DECISION",
        "v01_final_decision",
        NOTEBOOK10_FINAL_DECISION_PATH,
        persisted_final_decision,
    ),
    (
        "V02_BOOTSTRAP_HANDOFF",
        "NOTEBOOK_10_V02_BOOTSTRAP_HANDOFF",
        "v01_to_v02_bootstrap_handoff",
        NOTEBOOK10_V02_HANDOFF_PATH,
        persisted_v02_handoff,
    ),
):
    payload_bytes = notebook10_json_bytes(
        payload
    )

    write_result = notebook10_atomic_write_exact(
        output_path,
        payload_bytes,
        role=variable_name,
    )

    notebook10_artifact_records.append(
        {
            "artifact_type": artifact_type,
            "artifact_role": artifact_role,
            "variable_name": variable_name,
            "path": str(
                write_result[
                    "path"
                ]
            ),
            "relative_path": str(
                write_result[
                    "path"
                ].relative_to(
                    notebook10_normalized_path(
                        V01_ROOT
                    )
                )
            ),
            "format": "JSON",
            "semantic_sha256": payload[
                "payload_sha256"
            ],
            "sha256": write_result[
                "sha256"
            ],
            "size_bytes": int(
                write_result[
                    "size_bytes"
                ]
            ),
            "write_action": write_result[
                "write_action"
            ],
            "status": "PASS_PERSISTED",
        }
    )


# ------------------------------------------------------------
# Construct Notebook 10 output manifest
# ------------------------------------------------------------

NOTEBOOK10_OUTPUT_MANIFEST = {
    "artifact_type": (
        "NOTEBOOK_10_OUTPUT_MANIFEST"
    ),
    "schema_version": (
        "NOTEBOOK_10_OUTPUT_MANIFEST_V1"
    ),
    "producer": (
        "10_V01_FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF.ipynb"
    ),
    "created_utc": persisted_final_decision[
        "created_utc"
    ],
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": (
        persisted_final_decision[
            "scientific_terminal_class"
        ]
    ),
    "scientific_terminal_status": (
        persisted_final_decision[
            "scientific_terminal_status"
        ]
    ),
    "pipeline_closeout_status": (
        "PASS_PERSISTED_AWAITING_SEMANTIC_READBACK"
    ),
    "v0_2_handoff_scope": (
        persisted_final_decision[
            "v0_2_handoff_scope"
        ]
    ),
    "artifact_count_excluding_manifest_and_sidecar": int(
        len(
            notebook10_artifact_records
        )
    ),
    "artifacts": notebook10_artifact_records,
    "notebook09_executed": False,
    "notebook09_authorized": False,
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "next_authorized_operation": (
        "VERIFY_NOTEBOOK10_SEMANTIC_READBACK_AND_FINALIZE_CLOSEOUT"
    ),
    "status": (
        "PASS_PERSISTED_AWAITING_SEMANTIC_READBACK"
    ),
}

NOTEBOOK10_OUTPUT_MANIFEST = (
    notebook10_payload_with_semantic_hash(
        NOTEBOOK10_OUTPUT_MANIFEST,
        hash_field="manifest_payload_sha256",
    )
)


# ------------------------------------------------------------
# Persist output manifest and SHA-256 sidecar
# ------------------------------------------------------------

notebook10_manifest_write_result = (
    notebook10_atomic_write_exact(
        NOTEBOOK10_OUTPUT_MANIFEST_PATH,
        notebook10_json_bytes(
            NOTEBOOK10_OUTPUT_MANIFEST
        ),
        role="NOTEBOOK10_OUTPUT_MANIFEST",
    )
)

manifest_sidecar_text = (
    f"{notebook10_manifest_write_result['sha256']}  "
    f"{NOTEBOOK10_OUTPUT_MANIFEST_PATH.name}\n"
)

notebook10_sidecar_write_result = (
    notebook10_atomic_write_exact(
        NOTEBOOK10_OUTPUT_MANIFEST_SHA256_PATH,
        manifest_sidecar_text.encode(
            "utf-8"
        ),
        role="NOTEBOOK10_OUTPUT_MANIFEST_SHA256",
    )
)


# ------------------------------------------------------------
# Build complete in-memory persistence registry
# ------------------------------------------------------------

complete_persistence_records = list(
    notebook10_artifact_records
)

complete_persistence_records.extend(
    [
        {
            "artifact_type": (
                "NOTEBOOK_10_OUTPUT_MANIFEST"
            ),
            "artifact_role": (
                "notebook10_output_manifest"
            ),
            "variable_name": (
                "NOTEBOOK10_OUTPUT_MANIFEST"
            ),
            "path": str(
                notebook10_manifest_write_result[
                    "path"
                ]
            ),
            "relative_path": str(
                notebook10_manifest_write_result[
                    "path"
                ].relative_to(
                    notebook10_normalized_path(
                        V01_ROOT
                    )
                )
            ),
            "format": "JSON",
            "semantic_sha256": (
                NOTEBOOK10_OUTPUT_MANIFEST[
                    "manifest_payload_sha256"
                ]
            ),
            "sha256": (
                notebook10_manifest_write_result[
                    "sha256"
                ]
            ),
            "size_bytes": int(
                notebook10_manifest_write_result[
                    "size_bytes"
                ]
            ),
            "write_action": (
                notebook10_manifest_write_result[
                    "write_action"
                ]
            ),
            "status": "PASS_PERSISTED",
        },
        {
            "artifact_type": (
                "NOTEBOOK_10_MANIFEST_SHA256_SIDECAR"
            ),
            "artifact_role": (
                "notebook10_output_manifest_sha256"
            ),
            "variable_name": (
                "NOTEBOOK10_OUTPUT_MANIFEST_SHA256"
            ),
            "path": str(
                notebook10_sidecar_write_result[
                    "path"
                ]
            ),
            "relative_path": str(
                notebook10_sidecar_write_result[
                    "path"
                ].relative_to(
                    notebook10_normalized_path(
                        V01_ROOT
                    )
                )
            ),
            "format": "SHA256_SIDECAR",
            "sha256": (
                notebook10_sidecar_write_result[
                    "sha256"
                ]
            ),
            "size_bytes": int(
                notebook10_sidecar_write_result[
                    "size_bytes"
                ]
            ),
            "write_action": (
                notebook10_sidecar_write_result[
                    "write_action"
                ]
            ),
            "status": "PASS_PERSISTED",
        },
    ]
)


NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY = (
    pd.DataFrame(
        complete_persistence_records
    )
    .sort_values(
        [
            "artifact_type",
            "variable_name",
        ],
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


# ------------------------------------------------------------
# Persistence validation
# ------------------------------------------------------------

if not NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY[
    "status"
].eq(
    "PASS_PERSISTED"
).all():
    raise Notebook10PersistenceError(
        "At least one Notebook 10 artifact lacks PASS_PERSISTED."
    )

if NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY[
    "path"
].duplicated().any():
    duplicate_paths = (
        NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY.loc[
            NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY[
                "path"
            ].duplicated(
                keep=False
            ),
            [
                "variable_name",
                "path",
            ],
        ]
    )

    raise Notebook10PersistenceError(
        "Duplicate physical Notebook 10 output paths were "
        "registered:\n"
        + duplicate_paths.to_string(
            index=False
        )
    )

for persisted_record in (
    NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY.itertuples(
        index=False
    )
):
    persisted_path = notebook10_normalized_path(
        persisted_record.path
    )

    if not persisted_path.is_file():
        raise Notebook10PersistenceError(
            "A registered Notebook 10 artifact is missing:\n"
            f"{persisted_path}"
        )

    observed_sha256 = notebook10_sha256_file(
        persisted_path
    )

    if observed_sha256 != str(
        persisted_record.sha256
    ):
        raise Notebook10PersistenceError(
            "Immediate physical verification failed.\n"
            f"Path: {persisted_path}\n"
            f"Observed: {observed_sha256}\n"
            f"Expected: {persisted_record.sha256}"
        )


# ------------------------------------------------------------
# Persistence summary
# ------------------------------------------------------------

NOTEBOOK10_PERSISTENCE_SUMMARY = pd.DataFrame(
    [
        {
            "metric": "persisted_audit_table_count",
            "value": int(
                len(
                    NOTEBOOK10_TABLES_TO_PERSIST
                )
            ),
        },
        {
            "metric": "persisted_json_payload_count",
            "value": 2,
        },
        {
            "metric": "output_manifest_count",
            "value": 1,
        },
        {
            "metric": "manifest_sha256_sidecar_count",
            "value": 1,
        },
        {
            "metric": "total_persisted_artifact_count",
            "value": int(
                len(
                    NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY
                )
            ),
        },
        {
            "metric": "created_atomically_count",
            "value": int(
                NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY[
                    "write_action"
                ]
                .astype(
                    "string"
                )
                .str.startswith(
                    "CREATED",
                    na=False,
                )
                .sum()
            ),
        },
        {
            "metric": "reused_identical_count",
            "value": int(
                NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY[
                    "write_action"
                ]
                .astype(
                    "string"
                )
                .str.startswith(
                    "REUSED_IDENTICAL",
                    na=False,
                )
                .sum()
            ),
        },
        {
            "metric": "notebook10_output_manifest_path",
            "value": str(
                NOTEBOOK10_OUTPUT_MANIFEST_PATH
            ),
        },
        {
            "metric": "notebook10_output_manifest_sha256",
            "value": (
                notebook10_manifest_write_result[
                    "sha256"
                ]
            ),
        },
        {
            "metric": "manifest_payload_sha256",
            "value": (
                NOTEBOOK10_OUTPUT_MANIFEST[
                    "manifest_payload_sha256"
                ]
            ),
        },
        {
            "metric": "v01_final_decision_payload_sha256",
            "value": (
                persisted_final_decision[
                    "payload_sha256"
                ]
            ),
        },
        {
            "metric": "v02_bootstrap_handoff_payload_sha256",
            "value": (
                persisted_v02_handoff[
                    "payload_sha256"
                ]
            ),
        },
        {
            "metric": "semantic_readback_verified",
            "value": False,
        },
        {
            "metric": "validation_content_loaded",
            "value": False,
        },
        {
            "metric": "engineering_holdout_content_loaded",
            "value": False,
        },
    ]
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    NOTEBOOK10_PERSISTENCE_SUMMARY
)

display(
    NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY[
        [
            "artifact_type",
            "artifact_role",
            "variable_name",
            "format",
            "path",
            "row_count",
            "column_count",
            "size_bytes",
            "sha256",
            "write_action",
            "status",
        ]
    ]
)


# ------------------------------------------------------------
# Update authoritative in-memory bindings
# ------------------------------------------------------------

V01_FINAL_DECISION = persisted_final_decision
V02_BOOTSTRAP_HANDOFF = persisted_v02_handoff

V01_TERMINAL_SYNTHESIS_SUMMARY = (
    persisted_terminal_summary
)

V01_FINAL_STAGE_DISPOSITION_LEDGER = (
    persisted_stage_disposition
)

V01_COMPLETION_STANDARD_AUDIT = (
    persisted_completion_standard
)


FROZEN_NOTEBOOK10_PERSISTENCE_AUTHORITY = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "output_manifest_path": str(
        NOTEBOOK10_OUTPUT_MANIFEST_PATH
    ),
    "output_manifest_file_sha256": (
        notebook10_manifest_write_result[
            "sha256"
        ]
    ),
    "output_manifest_semantic_sha256": (
        NOTEBOOK10_OUTPUT_MANIFEST[
            "manifest_payload_sha256"
        ]
    ),
    "output_manifest_sha256_sidecar_path": str(
        NOTEBOOK10_OUTPUT_MANIFEST_SHA256_PATH
    ),
    "v01_final_decision_path": str(
        NOTEBOOK10_FINAL_DECISION_PATH
    ),
    "v01_final_decision_semantic_sha256": (
        V01_FINAL_DECISION[
            "payload_sha256"
        ]
    ),
    "v02_bootstrap_handoff_path": str(
        NOTEBOOK10_V02_HANDOFF_PATH
    ),
    "v02_bootstrap_handoff_semantic_sha256": (
        V02_BOOTSTRAP_HANDOFF[
            "payload_sha256"
        ]
    ),
    "persisted_artifact_count": int(
        len(
            NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY
        )
    ),
    "scientific_terminal_class": "FAIL",
    "pipeline_closeout_status": (
        "PASS_PERSISTED_AWAITING_SEMANTIC_READBACK"
    ),
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
}


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

V01_TERMINAL_SYNTHESIS_PERSISTED = True
V02_BOOTSTRAP_HANDOFF_PERSISTED = True
NOTEBOOK10_OUTPUT_MANIFEST_PERSISTED = True
NOTEBOOK10_PHYSICAL_PERSISTENCE_VERIFIED = True

V01_TERMINAL_SYNTHESIS_READBACK_VERIFIED = False
V02_BOOTSTRAP_HANDOFF_READBACK_VERIFIED = False
NOTEBOOK10_OUTPUT_MANIFEST_READBACK_VERIFIED = False
NOTEBOOK10_SEMANTIC_READBACK_VERIFIED = False

UPSTREAM_ARTIFACTS_VERIFIED = True

V01_MODEL_SIGNAL_AUTHORIZATION_GRANTED = False
V01_STRATEGY_AUTHORIZATION_GRANTED = False
V01_V02_MODEL_HANDOFF_AUTHORIZED = False

NOTEBOOK09_EXECUTED = False
NOTEBOOK09_AUTHORIZED = False

VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False
PROTECTED_PARTITION_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "Notebook 10 persistence: PASS. Nine deterministic audit "
    "tables, the V0.1 terminal decision, and the bootstrap-only "
    "V0.2 handoff were persisted under V0.1. The Notebook 10 "
    "output manifest was written last and protected by a physical "
    "SHA-256 sidecar. Existing artifacts were reused only when "
    "their bytes were identical; no differing artifact was "
    "overwritten. The scientific terminal state remains FAIL, "
    "Notebook 09 remains skipped and unauthorized, and no model, "
    "signal, strategy, or accepted V0.2 model handoff was created. "
    "VALIDATION and ENGINEERING_HOLDOUT remain unopened. Semantic "
    "readback is the next authorized operation."
)

,metric,value
0,persisted_audit_table_count,9
1,persisted_json_payload_count,2
2,output_manifest_count,1
3,manifest_sha256_sidecar_count,1
4,total_persisted_artifact_count,13
5,created_atomically_count,13
6,reused_identical_count,0
7,notebook10_output_manifest_path,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...
8,notebook10_output_manifest_sha256,228f1bbd0e3eb44fbabd6e9149d95d42ae77687aaa6a5f688e24731123174922
9,manifest_payload_sha256,f7745fa82ed8b3a1edd996171c1f60845da2be18dedc6e8a6a91d0837be1bc0b
10,v01_final_decision_payload_sha256,6d677c0dfeba250ad4906892ac5c79df045fc313a34ed920c981e1247f3f4681
11,v02_bootstrap_handoff_payload_sha256,ff4a52275972d0ee0bdc29907be54b673710a6b37aa93ee4da0df05b82bf739d
12,semantic_readback_verified,False
13,validation_content_loaded,False
14,engineering_holdout_content_loaded,False

,artifact_type,artifact_role,variable_name,format,path,row_count,column_count,size_bytes,sha256,write_action,status
0,NOTEBOOK_10_AUDIT_TABLE,v01_completion_standard_audit,V01_COMPLETION_STANDARD_AUDIT,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,28,5,1605,12a67c4d5ea370e32c0acd542071e1fc1bbc0e8ed0ebcbb40bdf113c5fffc77a,CREATED_ATOMICALLY,PASS_PERSISTED
1,NOTEBOOK_10_AUDIT_TABLE,v01_final_claim_ledger,V01_FINAL_CLAIM_LEDGER,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,14,6,1677,6dcb7d7058fc569ab0143c17f61920b5b18b09e00a3979124a7f5e3e80d12aa3,CREATED_ATOMICALLY,PASS_PERSISTED
2,NOTEBOOK_10_AUDIT_TABLE,v01_final_stage_disposition_ledger,V01_FINAL_STAGE_DISPOSITION_LEDGER,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,11,8,688,59a9cf7105625c4a01fdc73e0bd7688f7090c3ccd965fda77598d8e4add197a7,CREATED_ATOMICALLY,PASS_PERSISTED
3,NOTEBOOK_10_AUDIT_TABLE,v01_terminal_synthesis_summary,V01_TERMINAL_SYNTHESIS_SUMMARY,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,19,2,593,5f8198b93935205a01fbceaee60bf5466f60e2c589667c5a28ea64e0f3640337,CREATED_ATOMICALLY,PASS_PERSISTED
4,NOTEBOOK_10_AUDIT_TABLE,v01_v02_carryover_class_summary,V01_V02_CARRYOVER_CLASS_SUMMARY,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,7,5,400,f562697459e1b977e24a5103d915656c9e9ae795ec2e7e3ae310f66a10e31ebb,CREATED_ATOMICALLY,PASS_PERSISTED
5,NOTEBOOK_10_AUDIT_TABLE,v01_v02_carryover_file_catalogue,V01_V02_CARRYOVER_FILE_CATALOGUE,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,440,22,33856,f6b198373a283d212d7f7a680552fed74d08ee33bcd907b6e5fc635dacc734ac,CREATED_ATOMICALLY,PASS_PERSISTED
6,NOTEBOOK_10_AUDIT_TABLE,v01_v02_do_not_carry_ledger,V01_V02_DO_NOT_CARRY_LEDGER,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,8,4,671,23c8dba269ab400aa0ed08cc9f6d93958cd178ad5553aadb21a8c66eff99fac1,CREATED_ATOMICALLY,PASS_PERSISTED
7,NOTEBOOK_10_AUDIT_TABLE,v01_v02_essential_control_authority_index,V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,25,8,2148,4c059442677bb314715678b3fe1100b4173a57fa524820a45085f74aa5bf6114,CREATED_ATOMICALLY,PASS_PERSISTED
8,NOTEBOOK_10_AUDIT_TABLE,v02_bootstrap_requirements,V02_BOOTSTRAP_REQUIREMENTS,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,13,5,1265,da1678fac1e5a44b9525bf336cfbe6238e4d02c496aaa61367cc226d5361ce2c,CREATED_ATOMICALLY,PASS_PERSISTED
9,NOTEBOOK_10_FINAL_DECISION,v01_final_decision,V01_FINAL_DECISION,JSON,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,NaN,NaN,2068,9dd82786892852e2ac5161db754a8cb30cd5b1dc5b93278ff844cfefcc5cb47b,CREATED_ATOMICALLY,PASS_PERSISTED
10,NOTEBOOK_10_MANIFEST_SHA256_SIDECAR,notebook10_output_manifest_sha256,NOTEBOOK10_OUTPUT_MANIFEST_SHA256,SHA256_SIDECAR,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,NaN,NaN,220,7c510fb79d6948257cee9649d3efaa1f5c8d3a3a92b30226ffb811298c1480c0,CREATED_ATOMICALLY,PASS_PERSISTED
11,NOTEBOOK_10_OUTPUT_MANIFEST,notebook10_output_manifest,NOTEBOOK10_OUTPUT_MANIFEST,JSON,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,NaN,NaN,17515,228f1bbd0e3eb44fbabd6e9149d95d42ae77687aaa6a5f688e24731123174922,CREATED_ATOMICALLY,PASS_PERSISTED
12,NOTEBOOK_10_V02_BOOTSTRAP_HANDOFF,v01_to_v02_bootstrap_handoff,V02_BOOTSTRAP_HANDOFF,JSON,D:\Clown Project\V0.1\artifacts\handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_han...,NaN,NaN,23147,86821bad9a078943a891918a2eec806552e9e57874c96adbc54f71d37a8f1101,CREATED_ATOMICALLY,PASS_PERSISTED

Notebook 10 persistence: PASS. Nine deterministic audit tables, the V0.1 terminal decision, and the bootstrap-only V0.2 handoff were persisted under V0.1. The Notebook 10 output manifest was written last and protected by a physical SHA-256 sidecar. Existing artifacts were reused only when their bytes were identical; no differing artifact was overwritten. The scientific terminal state remains FAIL, Notebook 09 remains skipped and unauthorized, and no model, signal, strategy, or accepted V0.2 model handoff was created. VALIDATION and ENGINEERING_HOLDOUT remain unopened. Semantic readback is the next authorized operation.

In [35]:
# ============================================================
# Notebook 10 semantic readback and final-closeout preparation
#
# This cell independently reopens every persisted Notebook 10
# artifact and verifies:
# - output-manifest physical SHA-256 and sidecar;
# - output-manifest semantic SHA-256;
# - exact artifact set, paths, sizes, and physical hashes;
# - deterministic uncompressed CSV hashes;
# - table row counts, column counts, and column order;
# - terminal-decision and V0.2-handoff semantic hashes;
# - critical scientific, authorization, and closure semantics;
# - Notebook 09 remains skipped and not passed;
# - H1 remains rejected for accepted model/signal use;
# - protected partitions remain unopened.
#
# It then prepares finalized in-memory closeout authorities for
# the next persistence cell.
#
# No filesystem writes are performed.
# ============================================================

from __future__ import annotations

import gzip
import hashlib
import json
import re
from pathlib import Path
from typing import Any, Final, Mapping

import numpy as np
import pandas as pd
from IPython.display import display


class Notebook10SemanticReadbackError(RuntimeError):
    """Raised when persisted Notebook 10 semantics do not reconcile."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

REQUIRED_NOTEBOOK10_READBACK_FLAGS: Final[
    dict[str, bool]
] = {
    "V01_TERMINAL_SYNTHESIS_PERSISTED": bool(
        globals().get(
            "V01_TERMINAL_SYNTHESIS_PERSISTED",
            False,
        )
    ),
    "V02_BOOTSTRAP_HANDOFF_PERSISTED": bool(
        globals().get(
            "V02_BOOTSTRAP_HANDOFF_PERSISTED",
            False,
        )
    ),
    "NOTEBOOK10_OUTPUT_MANIFEST_PERSISTED": bool(
        globals().get(
            "NOTEBOOK10_OUTPUT_MANIFEST_PERSISTED",
            False,
        )
    ),
    "NOTEBOOK10_PHYSICAL_PERSISTENCE_VERIFIED": bool(
        globals().get(
            "NOTEBOOK10_PHYSICAL_PERSISTENCE_VERIFIED",
            False,
        )
    ),
}

failed_readback_flags = sorted(
    flag_name
    for flag_name, passed in (
        REQUIRED_NOTEBOOK10_READBACK_FLAGS.items()
    )
    if not passed
)

if failed_readback_flags:
    raise Notebook10SemanticReadbackError(
        "Notebook 10 semantic-readback prerequisites have not "
        "passed:\n"
        f"{failed_readback_flags}"
    )


REQUIRED_NOTEBOOK10_READBACK_OBJECTS: Final[
    tuple[str, ...]
] = (
    "V01_ROOT",
    "NOTEBOOK10_OUTPUT_MANIFEST_PATH",
    "NOTEBOOK10_OUTPUT_MANIFEST_SHA256_PATH",
    "FROZEN_NOTEBOOK10_PERSISTENCE_AUTHORITY",
)

missing_readback_objects = sorted(
    object_name
    for object_name in REQUIRED_NOTEBOOK10_READBACK_OBJECTS
    if object_name not in globals()
)

if missing_readback_objects:
    raise Notebook10SemanticReadbackError(
        "Required Notebook 10 readback objects are unavailable:\n"
        f"{missing_readback_objects}"
    )


if not isinstance(
    FROZEN_NOTEBOOK10_PERSISTENCE_AUTHORITY,
    Mapping,
):
    raise Notebook10SemanticReadbackError(
        "FROZEN_NOTEBOOK10_PERSISTENCE_AUTHORITY must be a mapping."
    )


# ------------------------------------------------------------
# Runtime safety guards
# ------------------------------------------------------------

if bool(
    globals().get(
        "VALIDATION_CONTENT_LOADED",
        False,
    )
):
    raise Notebook10SemanticReadbackError(
        "VALIDATION content was unexpectedly loaded."
    )

if bool(
    globals().get(
        "ENGINEERING_HOLDOUT_CONTENT_LOADED",
        False,
    )
):
    raise Notebook10SemanticReadbackError(
        "ENGINEERING_HOLDOUT content was unexpectedly loaded."
    )

protected_runtime_state = globals().get(
    "PROTECTED_PARTITION_CONTENT_LOADED",
    False,
)

if isinstance(
    protected_runtime_state,
    Mapping,
):
    opened_protected_partitions = sorted(
        str(
            partition
        )
        for partition, loaded in (
            protected_runtime_state.items()
        )
        if bool(
            loaded
        )
    )

    if opened_protected_partitions:
        raise Notebook10SemanticReadbackError(
            "Protected partition content was marked as loaded:\n"
            f"{opened_protected_partitions}"
        )

elif bool(
    protected_runtime_state
):
    raise Notebook10SemanticReadbackError(
        "Protected partition content was unexpectedly loaded."
    )


if bool(
    globals().get(
        "MODEL_REFIT_PERFORMED",
        False,
    )
):
    raise Notebook10SemanticReadbackError(
        "A model refit was recorded before semantic readback."
    )

if bool(
    globals().get(
        "MODEL_REPLACEMENT_PERFORMED",
        False,
    )
):
    raise Notebook10SemanticReadbackError(
        "A model replacement was recorded before semantic readback."
    )

if int(
    globals().get(
        "CALIBRATION_PARAMETER_UPDATES_PERFORMED",
        0,
    )
) != 0:
    raise Notebook10SemanticReadbackError(
        "Nonzero CALIBRATION parameter updates were recorded."
    )


# ------------------------------------------------------------
# Frozen expectations
# ------------------------------------------------------------

EXPECTED_NOTEBOOK10_TABLE_VARIABLES: Final[
    set[str]
] = {
    "V01_TERMINAL_SYNTHESIS_SUMMARY",
    "V01_FINAL_STAGE_DISPOSITION_LEDGER",
    "V01_COMPLETION_STANDARD_AUDIT",
    "V01_FINAL_CLAIM_LEDGER",
    "V01_V02_CARRYOVER_FILE_CATALOGUE",
    "V01_V02_CARRYOVER_CLASS_SUMMARY",
    "V01_V02_DO_NOT_CARRY_LEDGER",
    "V02_BOOTSTRAP_REQUIREMENTS",
    "V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX",
}

EXPECTED_NOTEBOOK10_JSON_VARIABLES: Final[
    set[str]
] = {
    "V01_FINAL_DECISION",
    "V02_BOOTSTRAP_HANDOFF",
}

EXPECTED_NOTEBOOK10_MANIFEST_ARTIFACT_VARIABLES: Final[
    set[str]
] = (
        EXPECTED_NOTEBOOK10_TABLE_VARIABLES
        | EXPECTED_NOTEBOOK10_JSON_VARIABLES
    )

EXPECTED_V01_TERMINAL_STATUS: Final[str] = (
    "FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY"
)

EXPECTED_V02_HANDOFF_SCOPE: Final[str] = (
    "BOOTSTRAP_AND_PROVENANCE_ONLY_NO_ACCEPTED_MODEL_SIGNAL_OR_STRATEGY"
)

EXPECTED_SELECTED_MODEL_ID: Final[str] = (
    "H1_DIAGONAL_SHARED_DECAY"
)

EXPECTED_FAILED_ADEQUACY_GATES: Final[set[str]] = {
    "LOCKED_CALIBRATION_RESIDUAL_DISTRIBUTION",
    "LOCKED_CALIBRATION_RESIDUAL_SERIAL_DEPENDENCE",
    "LOCKED_CALIBRATION_PATH_COUNT_CALIBRATION",
    "LOCKED_CALIBRATION_EXACT_TIME_MULTIPLICITY",
}


# ------------------------------------------------------------
# Path, hashing, and serialization helpers
# ------------------------------------------------------------

def notebook10_readback_normalized_path(
    value: Any,
) -> Path:
    """Return one absolute normalized path."""

    return Path(
        str(
            value
        )
    ).expanduser().resolve(
        strict=False
    )


def notebook10_readback_require_inside_v01(
    path: Path,
    *,
    role: str,
) -> Path:
    """Require a persisted artifact to remain inside V0.1."""

    normalized_path = notebook10_readback_normalized_path(
        path
    )

    normalized_root = notebook10_readback_normalized_path(
        V01_ROOT
    )

    try:
        normalized_path.relative_to(
            normalized_root
        )

    except ValueError as exc:
        raise Notebook10SemanticReadbackError(
            "A Notebook 10 artifact lies outside V0.1.\n"
            f"Role: {role}\n"
            f"Path: {normalized_path}"
        ) from exc

    return normalized_path


def notebook10_readback_sha256_bytes(
    payload_bytes: bytes,
) -> str:
    """Return the SHA-256 digest of bytes."""

    return hashlib.sha256(
        payload_bytes
    ).hexdigest()


def notebook10_readback_sha256_file(
    path: Path,
    *,
    chunk_size: int = 1 << 20,
) -> str:
    """Return the physical SHA-256 digest of one file."""

    digest = hashlib.sha256()

    with path.open(
        "rb"
    ) as input_stream:
        while True:
            chunk = input_stream.read(
                chunk_size
            )

            if not chunk:
                break

            digest.update(
                chunk
            )

    return digest.hexdigest()


def notebook10_readback_plain_value(
    value: Any,
) -> Any:
    """Convert values into strict JSON-compatible Python types."""

    if value is None:
        return None

    if isinstance(
        value,
        Path,
    ):
        return str(
            value
        )

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(
            value
        )

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        return int(
            value
        )

    if isinstance(
        value,
        (float, np.floating),
    ):
        numeric_value = float(
            value
        )

        if not np.isfinite(
            numeric_value
        ):
            return str(
                numeric_value
            )

        return numeric_value

    if isinstance(
        value,
        Mapping,
    ):
        return {
            str(
                key
            ): notebook10_readback_plain_value(
                child
            )
            for key, child in value.items()
        }

    if isinstance(
        value,
        (
            list,
            tuple,
            set,
        ),
    ):
        iterable = (
            sorted(
                value
            )
            if isinstance(
                value,
                set,
            )
            else value
        )

        return [
            notebook10_readback_plain_value(
                child
            )
            for child in iterable
        ]

    try:
        missing_value = pd.isna(
            value
        )

        if isinstance(
            missing_value,
            (bool, np.bool_),
        ) and bool(
            missing_value
        ):
            return None

    except (
        TypeError,
        ValueError,
    ):
        pass

    return str(
        value
    )


def notebook10_readback_canonical_sha256(
    payload: Mapping[str, Any],
) -> str:
    """Return one deterministic semantic SHA-256."""

    canonical_bytes = json.dumps(
        notebook10_readback_plain_value(
            payload
        ),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode(
        "utf-8"
    )

    return notebook10_readback_sha256_bytes(
        canonical_bytes
    )


def notebook10_readback_semantic_sha256(
    payload: Mapping[str, Any],
    *,
    hash_field: str,
) -> str:
    """Recompute a non-self-referential semantic hash."""

    copied_payload = dict(
        notebook10_readback_plain_value(
            payload
        )
    )

    copied_payload.pop(
        hash_field,
        None,
    )

    return notebook10_readback_canonical_sha256(
        copied_payload
    )


def notebook10_readback_boolean(
    value: Any,
) -> bool | None:
    """Normalize one persisted boolean representation."""

    if value is None:
        return None

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(
            value
        )

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        if int(
            value
        ) in {
            0,
            1,
        }:
            return bool(
                int(
                    value
                )
            )

    normalized = str(
        value
    ).strip().casefold()

    if normalized in {
        "true",
        "t",
        "yes",
        "y",
        "1",
    }:
        return True

    if normalized in {
        "false",
        "f",
        "no",
        "n",
        "0",
        "",
        "none",
        "null",
    }:
        return False

    return None


def notebook10_readback_render(
    value: Any,
) -> str:
    """Render deterministic audit values."""

    plain_value = notebook10_readback_plain_value(
        value
    )

    if isinstance(
        plain_value,
        (
            dict,
            list,
        ),
    ):
        return json.dumps(
            plain_value,
            sort_keys=True,
            ensure_ascii=False,
            allow_nan=False,
        )

    return repr(
        plain_value
    )


def notebook10_readback_metric_map(
    dataframe: pd.DataFrame,
) -> dict[str, Any]:
    """Convert a unique metric/value table into a mapping."""

    if not {
        "metric",
        "value",
    }.issubset(
        dataframe.columns
    ):
        raise Notebook10SemanticReadbackError(
            "A required metric/value table lacks metric or value."
        )

    if dataframe[
        "metric"
    ].astype(
        "string"
    ).duplicated().any():
        raise Notebook10SemanticReadbackError(
            "A metric/value table contains duplicate metrics."
        )

    return {
        str(
            row.metric
        ): row.value
        for row in dataframe.itertuples(
            index=False
        )
    }


# ------------------------------------------------------------
# Read and verify the output manifest physical file
# ------------------------------------------------------------

manifest_path = notebook10_readback_require_inside_v01(
    NOTEBOOK10_OUTPUT_MANIFEST_PATH,
    role="NOTEBOOK10_OUTPUT_MANIFEST",
)

manifest_sidecar_path = notebook10_readback_require_inside_v01(
    NOTEBOOK10_OUTPUT_MANIFEST_SHA256_PATH,
    role="NOTEBOOK10_OUTPUT_MANIFEST_SHA256",
)

if not manifest_path.is_file():
    raise Notebook10SemanticReadbackError(
        f"Notebook 10 output manifest is missing: {manifest_path}"
    )

if not manifest_sidecar_path.is_file():
    raise Notebook10SemanticReadbackError(
        "Notebook 10 output-manifest SHA-256 sidecar is missing:\n"
        f"{manifest_sidecar_path}"
    )


manifest_file_sha256 = notebook10_readback_sha256_file(
    manifest_path
)

expected_manifest_file_sha256 = str(
    FROZEN_NOTEBOOK10_PERSISTENCE_AUTHORITY.get(
        "output_manifest_file_sha256",
        "",
    )
).strip().lower()

if (
    manifest_file_sha256
    != expected_manifest_file_sha256
):
    raise Notebook10SemanticReadbackError(
        "Notebook 10 output-manifest physical hash mismatch.\n"
        f"Observed: {manifest_file_sha256}\n"
        f"Expected: {expected_manifest_file_sha256}"
    )


sidecar_text = manifest_sidecar_path.read_text(
    encoding="utf-8"
)

sidecar_match = re.fullmatch(
    r"([0-9a-fA-F]{64})  ([^\r\n]+)\r?\n?",
    sidecar_text,
)

if sidecar_match is None:
    raise Notebook10SemanticReadbackError(
        "Notebook 10 output-manifest sidecar has an invalid format."
    )

sidecar_manifest_sha256 = (
    sidecar_match.group(
        1
    ).lower()
)

sidecar_manifest_filename = sidecar_match.group(
    2
)

if (
    sidecar_manifest_sha256
    != manifest_file_sha256
):
    raise Notebook10SemanticReadbackError(
        "Output-manifest SHA-256 sidecar does not match the "
        "manifest file."
    )

if (
    sidecar_manifest_filename
    != manifest_path.name
):
    raise Notebook10SemanticReadbackError(
        "Output-manifest sidecar references the wrong filename.\n"
        f"Observed: {sidecar_manifest_filename}\n"
        f"Expected: {manifest_path.name}"
    )


with manifest_path.open(
    "r",
    encoding="utf-8",
) as manifest_stream:
    NOTEBOOK10_OUTPUT_MANIFEST_READBACK = json.load(
        manifest_stream
    )

if not isinstance(
    NOTEBOOK10_OUTPUT_MANIFEST_READBACK,
    dict,
):
    raise Notebook10SemanticReadbackError(
        "The Notebook 10 output manifest is not a JSON object."
    )


declared_manifest_semantic_sha256 = str(
    NOTEBOOK10_OUTPUT_MANIFEST_READBACK.get(
        "manifest_payload_sha256",
        "",
    )
).strip().lower()

observed_manifest_semantic_sha256 = (
    notebook10_readback_semantic_sha256(
        NOTEBOOK10_OUTPUT_MANIFEST_READBACK,
        hash_field="manifest_payload_sha256",
    )
)

if (
    observed_manifest_semantic_sha256
    != declared_manifest_semantic_sha256
):
    raise Notebook10SemanticReadbackError(
        "Notebook 10 output-manifest semantic hash mismatch.\n"
        f"Observed: {observed_manifest_semantic_sha256}\n"
        f"Declared: {declared_manifest_semantic_sha256}"
    )


expected_manifest_semantic_sha256 = str(
    FROZEN_NOTEBOOK10_PERSISTENCE_AUTHORITY.get(
        "output_manifest_semantic_sha256",
        "",
    )
).strip().lower()

if (
    declared_manifest_semantic_sha256
    != expected_manifest_semantic_sha256
):
    raise Notebook10SemanticReadbackError(
        "Notebook 10 manifest semantic hash differs from the "
        "frozen persistence authority."
    )


# ------------------------------------------------------------
# Manifest identity and closure-state verification
# ------------------------------------------------------------

EXPECTED_MANIFEST_IDENTITIES: Final[
    dict[str, Any]
] = {
    "artifact_type": (
        "NOTEBOOK_10_OUTPUT_MANIFEST"
    ),
    "schema_version": (
        "NOTEBOOK_10_OUTPUT_MANIFEST_V1"
    ),
    "producer": (
        "10_V01_FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF.ipynb"
    ),
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": (
        EXPECTED_V01_TERMINAL_STATUS
    ),
    "pipeline_closeout_status": (
        "PASS_PERSISTED_AWAITING_SEMANTIC_READBACK"
    ),
    "v0_2_handoff_scope": (
        EXPECTED_V02_HANDOFF_SCOPE
    ),
    "artifact_count_excluding_manifest_and_sidecar": 11,
    "notebook09_executed": False,
    "notebook09_authorized": False,
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "status": (
        "PASS_PERSISTED_AWAITING_SEMANTIC_READBACK"
    ),
}

manifest_identity_failures: list[
    dict[str, Any]
] = []

for identity_field, expected_value in (
    EXPECTED_MANIFEST_IDENTITIES.items()
):
    observed_value = NOTEBOOK10_OUTPUT_MANIFEST_READBACK.get(
        identity_field
    )

    if observed_value != expected_value:
        manifest_identity_failures.append(
            {
                "field": identity_field,
                "observed": observed_value,
                "expected": expected_value,
            }
        )


V01_NOTEBOOK10_MANIFEST_IDENTITY_FAILURES = pd.DataFrame(
    manifest_identity_failures,
    columns=[
        "field",
        "observed",
        "expected",
    ],
)

if not V01_NOTEBOOK10_MANIFEST_IDENTITY_FAILURES.empty:
    raise Notebook10SemanticReadbackError(
        "Notebook 10 output-manifest identities or closure states "
        "do not reconcile:\n"
        + V01_NOTEBOOK10_MANIFEST_IDENTITY_FAILURES.to_string(
            index=False
        )
    )


# ------------------------------------------------------------
# Extract and validate exact artifact registry
# ------------------------------------------------------------

manifest_artifact_records = (
    NOTEBOOK10_OUTPUT_MANIFEST_READBACK.get(
        "artifacts"
    )
)

if not isinstance(
    manifest_artifact_records,
    list,
):
    raise Notebook10SemanticReadbackError(
        "Notebook 10 output manifest lacks an artifact list."
    )

if len(
    manifest_artifact_records
) != 11:
    raise Notebook10SemanticReadbackError(
        "Notebook 10 output manifest must register exactly 11 "
        "non-manifest artifacts."
    )


artifact_record_by_variable: dict[
    str,
    dict[str, Any],
] = {}

registered_paths: set[Path] = set()

for artifact_record in manifest_artifact_records:
    if not isinstance(
        artifact_record,
        Mapping,
    ):
        raise Notebook10SemanticReadbackError(
            "A Notebook 10 artifact record is not a JSON object."
        )

    variable_name = str(
        artifact_record.get(
            "variable_name",
            "",
        )
    ).strip()

    if not variable_name:
        raise Notebook10SemanticReadbackError(
            "A Notebook 10 artifact record lacks variable_name."
        )

    if variable_name in artifact_record_by_variable:
        raise Notebook10SemanticReadbackError(
            "Notebook 10 output manifest contains duplicate "
            f"variable registration: {variable_name}"
        )

    artifact_path = notebook10_readback_require_inside_v01(
        Path(
            str(
                artifact_record.get(
                    "path"
                )
            )
        ),
        role=variable_name,
    )

    if artifact_path in registered_paths:
        raise Notebook10SemanticReadbackError(
            "Notebook 10 output manifest registers one physical "
            f"path more than once: {artifact_path}"
        )

    registered_paths.add(
        artifact_path
    )

    normalized_record = dict(
        artifact_record
    )

    normalized_record[
        "_resolved_path"
    ] = artifact_path

    artifact_record_by_variable[
        variable_name
    ] = normalized_record


observed_manifest_variable_set = set(
    artifact_record_by_variable
)

if (
    observed_manifest_variable_set
    != EXPECTED_NOTEBOOK10_MANIFEST_ARTIFACT_VARIABLES
):
    raise Notebook10SemanticReadbackError(
        "Notebook 10 manifest artifact-variable set differs from "
        "the required set.\n"
        f"Missing: "
        f"{sorted(EXPECTED_NOTEBOOK10_MANIFEST_ARTIFACT_VARIABLES - observed_manifest_variable_set)}\n"
        f"Unexpected: "
        f"{sorted(observed_manifest_variable_set - EXPECTED_NOTEBOOK10_MANIFEST_ARTIFACT_VARIABLES)}"
    )


# ------------------------------------------------------------
# Reopen and verify all persisted artifacts
# ------------------------------------------------------------

readback_artifact_records: list[
    dict[str, Any]
] = []

NOTEBOOK10_READBACK_TABLES: dict[
    str,
    pd.DataFrame,
] = {}

NOTEBOOK10_READBACK_JSON_PAYLOADS: dict[
    str,
    dict[str, Any],
] = {}


for variable_name in sorted(
    artifact_record_by_variable
):
    artifact_record = artifact_record_by_variable[
        variable_name
    ]

    artifact_path = artifact_record[
        "_resolved_path"
    ]

    if not artifact_path.is_file():
        raise Notebook10SemanticReadbackError(
            f"Persisted Notebook 10 artifact is missing: {artifact_path}"
        )

    observed_file_sha256 = notebook10_readback_sha256_file(
        artifact_path
    )

    expected_file_sha256 = str(
        artifact_record.get(
            "sha256",
            "",
        )
    ).strip().lower()

    if observed_file_sha256 != expected_file_sha256:
        raise Notebook10SemanticReadbackError(
            "Persisted Notebook 10 artifact hash mismatch.\n"
            f"Variable: {variable_name}\n"
            f"Observed: {observed_file_sha256}\n"
            f"Expected: {expected_file_sha256}"
        )

    observed_size_bytes = int(
        artifact_path.stat().st_size
    )

    expected_size_bytes = int(
        artifact_record.get(
            "size_bytes"
        )
    )

    if observed_size_bytes != expected_size_bytes:
        raise Notebook10SemanticReadbackError(
            "Persisted Notebook 10 artifact size mismatch.\n"
            f"Variable: {variable_name}\n"
            f"Observed: {observed_size_bytes}\n"
            f"Expected: {expected_size_bytes}"
        )

    artifact_format = str(
        artifact_record.get(
            "format",
            "",
        )
    ).strip().upper()

    readback_record: dict[str, Any] = {
        "variable_name": variable_name,
        "artifact_type": str(
            artifact_record.get(
                "artifact_type",
                "",
            )
        ),
        "artifact_role": str(
            artifact_record.get(
                "artifact_role",
                "",
            )
        ),
        "path": str(
            artifact_path
        ),
        "format": artifact_format,
        "size_bytes": observed_size_bytes,
        "file_sha256": observed_file_sha256,
        "file_hash_matches": True,
        "size_matches": True,
        "semantic_hash_matches": None,
        "uncompressed_csv_hash_matches": None,
        "row_count_matches": None,
        "column_count_matches": None,
        "column_order_matches": None,
        "status": "PASS",
    }

    if artifact_format == "CSV_GZIP":
        compressed_bytes = artifact_path.read_bytes()

        try:
            uncompressed_csv_bytes = gzip.decompress(
                compressed_bytes
            )

        except OSError as exc:
            raise Notebook10SemanticReadbackError(
                "Unable to decompress a Notebook 10 CSV-GZIP "
                f"artifact: {variable_name}"
            ) from exc

        observed_uncompressed_csv_sha256 = (
            notebook10_readback_sha256_bytes(
                uncompressed_csv_bytes
            )
        )

        expected_uncompressed_csv_sha256 = str(
            artifact_record.get(
                "uncompressed_csv_sha256",
                "",
            )
        ).strip().lower()

        if (
            observed_uncompressed_csv_sha256
            != expected_uncompressed_csv_sha256
        ):
            raise Notebook10SemanticReadbackError(
                "Notebook 10 uncompressed CSV semantic hash "
                "mismatch.\n"
                f"Variable: {variable_name}"
            )

        observed_frame = pd.read_csv(
            artifact_path,
            compression="gzip",
            low_memory=False,
        )

        expected_row_count = int(
            artifact_record.get(
                "row_count"
            )
        )

        expected_column_count = int(
            artifact_record.get(
                "column_count"
            )
        )

        expected_columns = [
            str(
                column
            )
            for column in artifact_record.get(
                "columns",
                [],
            )
        ]

        observed_columns = list(
            map(
                str,
                observed_frame.columns,
            )
        )

        row_count_matches = bool(
            len(
                observed_frame
            )
            == expected_row_count
        )

        column_count_matches = bool(
            observed_frame.shape[
                1
            ]
            == expected_column_count
        )

        column_order_matches = bool(
            observed_columns
            == expected_columns
        )

        if not row_count_matches:
            raise Notebook10SemanticReadbackError(
                "Notebook 10 CSV row count mismatch.\n"
                f"Variable: {variable_name}"
            )

        if not column_count_matches:
            raise Notebook10SemanticReadbackError(
                "Notebook 10 CSV column count mismatch.\n"
                f"Variable: {variable_name}"
            )

        if not column_order_matches:
            raise Notebook10SemanticReadbackError(
                "Notebook 10 CSV column order mismatch.\n"
                f"Variable: {variable_name}"
            )

        NOTEBOOK10_READBACK_TABLES[
            variable_name
        ] = observed_frame.copy(
            deep=True
        )

        readback_record.update(
            {
                "uncompressed_csv_hash_matches": True,
                "row_count_matches": True,
                "column_count_matches": True,
                "column_order_matches": True,
            }
        )

    elif artifact_format == "JSON":
        with artifact_path.open(
            "r",
            encoding="utf-8",
        ) as json_stream:
            observed_payload = json.load(
                json_stream
            )

        if not isinstance(
            observed_payload,
            dict,
        ):
            raise Notebook10SemanticReadbackError(
                "A Notebook 10 JSON artifact is not an object.\n"
                f"Variable: {variable_name}"
            )

        declared_payload_sha256 = str(
            observed_payload.get(
                "payload_sha256",
                "",
            )
        ).strip().lower()

        observed_payload_sha256 = (
            notebook10_readback_semantic_sha256(
                observed_payload,
                hash_field="payload_sha256",
            )
        )

        expected_payload_sha256 = str(
            artifact_record.get(
                "semantic_sha256",
                "",
            )
        ).strip().lower()

        if (
            observed_payload_sha256
            != declared_payload_sha256
        ):
            raise Notebook10SemanticReadbackError(
                "Notebook 10 JSON internal semantic hash mismatch.\n"
                f"Variable: {variable_name}"
            )

        if (
            declared_payload_sha256
            != expected_payload_sha256
        ):
            raise Notebook10SemanticReadbackError(
                "Notebook 10 JSON semantic hash differs from the "
                "output manifest.\n"
                f"Variable: {variable_name}"
            )

        NOTEBOOK10_READBACK_JSON_PAYLOADS[
            variable_name
        ] = dict(
            observed_payload
        )

        readback_record[
            "semantic_hash_matches"
        ] = True

    else:
        raise Notebook10SemanticReadbackError(
            "Unexpected Notebook 10 persisted artifact format.\n"
            f"Variable: {variable_name}\n"
            f"Format: {artifact_format}"
        )

    readback_artifact_records.append(
        readback_record
    )


V01_NOTEBOOK10_ARTIFACT_READBACK_AUDIT = (
    pd.DataFrame(
        readback_artifact_records
    )
    .sort_values(
        "variable_name",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


# ------------------------------------------------------------
# Bind readback JSON authorities
# ------------------------------------------------------------

V01_FINAL_DECISION_READBACK = (
    NOTEBOOK10_READBACK_JSON_PAYLOADS[
        "V01_FINAL_DECISION"
    ]
)

V02_BOOTSTRAP_HANDOFF_READBACK = (
    NOTEBOOK10_READBACK_JSON_PAYLOADS[
        "V02_BOOTSTRAP_HANDOFF"
    ]
)


# ------------------------------------------------------------
# Semantic audit machinery
# ------------------------------------------------------------

notebook10_semantic_checks: list[
    dict[str, Any]
] = []


def register_notebook10_semantic_check(
    *,
    category: str,
    check_name: str,
    observed: Any,
    expected: Any,
    passed: bool | None = None,
    blocking: bool = True,
) -> None:
    """Register one Notebook 10 semantic check."""

    check_passed = (
        observed == expected
        if passed is None
        else bool(
            passed
        )
    )

    notebook10_semantic_checks.append(
        {
            "check_order": int(
                len(
                    notebook10_semantic_checks
                )
                + 1
            ),
            "category": category,
            "check_name": check_name,
            "blocking": bool(
                blocking
            ),
            "passed": bool(
                check_passed
            ),
            "status": (
                "PASS"
                if check_passed
                else (
                    "FAIL"
                    if blocking
                    else "WARNING"
                )
            ),
            "observed": notebook10_readback_render(
                observed
            ),
            "expected": notebook10_readback_render(
                expected
            ),
        }
    )


# ------------------------------------------------------------
# Final-decision JSON semantics
# ------------------------------------------------------------

EXPECTED_FINAL_DECISION_FIELDS: Final[
    dict[str, Any]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": (
        EXPECTED_V01_TERMINAL_STATUS
    ),
    "pipeline_closeout_status": (
        "PASS_PERSISTED_AWAITING_SEMANTIC_READBACK"
    ),
    "selected_hawkes_model_id": (
        EXPECTED_SELECTED_MODEL_ID
    ),
    "selected_model_disposition": (
        "REJECTED_FOR_DOWNSTREAM_SIGNAL_AUTHORIZATION"
    ),
    "count_score_superiority_supported": True,
    "full_model_adequacy_supported": False,
    "full_hawkes_superiority_supported": False,
    "notebook09_execution_state": (
        "SKIPPED_NOT_PASSED"
    ),
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "model_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "accepted_model_handoff_to_v0_2_authorized": False,
    "v0_2_handoff_scope": (
        EXPECTED_V02_HANDOFF_SCOPE
    ),
}

for field_name, expected_value in (
    EXPECTED_FINAL_DECISION_FIELDS.items()
):
    register_notebook10_semantic_check(
        category="FINAL_DECISION",
        check_name=field_name,
        observed=V01_FINAL_DECISION_READBACK.get(
            field_name
        ),
        expected=expected_value,
    )


register_notebook10_semantic_check(
    category="FINAL_DECISION",
    check_name="failed_blocking_gate_set",
    observed=set(
        V01_FINAL_DECISION_READBACK.get(
            "failed_blocking_gates",
            [],
        )
    ),
    expected=EXPECTED_FAILED_ADEQUACY_GATES,
)


# ------------------------------------------------------------
# V0.2 bootstrap-handoff JSON semantics
# ------------------------------------------------------------

EXPECTED_V02_HANDOFF_FIELDS: Final[
    dict[str, Any]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "v0_1_terminal_class": "FAIL",
    "v0_1_terminal_status": (
        EXPECTED_V01_TERMINAL_STATUS
    ),
    "handoff_scope": EXPECTED_V02_HANDOFF_SCOPE,
    "accepted_model_authorized": False,
    "accepted_signal_authorized": False,
    "strategy_authorized": False,
    "validation_result_available": False,
    "engineering_holdout_result_available": False,
    "status": (
        "PERSISTED_AWAITING_SEMANTIC_READBACK"
    ),
}

for field_name, expected_value in (
    EXPECTED_V02_HANDOFF_FIELDS.items()
):
    register_notebook10_semantic_check(
        category="V02_HANDOFF",
        check_name=field_name,
        observed=V02_BOOTSTRAP_HANDOFF_READBACK.get(
            field_name
        ),
        expected=expected_value,
    )


v02_selected_model = (
    V02_BOOTSTRAP_HANDOFF_READBACK.get(
        "v0_1_selected_model",
        {},
    )
)

if not isinstance(
    v02_selected_model,
    Mapping,
):
    v02_selected_model = {}


register_notebook10_semantic_check(
    category="V02_HANDOFF",
    check_name="selected_model_id",
    observed=v02_selected_model.get(
        "model_id"
    ),
    expected=EXPECTED_SELECTED_MODEL_ID,
)

register_notebook10_semantic_check(
    category="V02_HANDOFF",
    check_name="selected_model_status",
    observed=v02_selected_model.get(
        "status"
    ),
    expected=(
        "REJECTED_DIAGNOSTIC_REFERENCE_ONLY"
    ),
)

register_notebook10_semantic_check(
    category="V02_HANDOFF",
    check_name="selected_model_full_adequacy",
    observed=v02_selected_model.get(
        "full_model_adequacy_supported"
    ),
    expected=False,
)

register_notebook10_semantic_check(
    category="V02_HANDOFF",
    check_name="selected_model_failed_gate_set",
    observed=set(
        v02_selected_model.get(
            "failed_blocking_gates",
            [],
        )
    ),
    expected=EXPECTED_FAILED_ADEQUACY_GATES,
)


v02_restart_contract = (
    V02_BOOTSTRAP_HANDOFF_READBACK.get(
        "v0_2_restart_contract",
        {},
    )
)

if not isinstance(
    v02_restart_contract,
    Mapping,
):
    v02_restart_contract = {}


EXPECTED_V02_RESTART_FIELDS: Final[
    dict[str, Any]
] = {
    "fresh_notebook_sequence_required": True,
    "new_source_set_required": True,
    "new_v0_2_run_id_required": True,
    "new_chronological_split_contract_required": True,
    "refit_models_from_scratch": True,
    "reuse_v0_1_h1_parameters_as_authority": False,
    "reuse_v0_1_validation_or_holdout_as_v0_2_holdout": False,
    "authorize_signal_before_model_adequacy": False,
    "authorize_strategy_before_signal_acceptance": False,
}

for field_name, expected_value in (
    EXPECTED_V02_RESTART_FIELDS.items()
):
    register_notebook10_semantic_check(
        category="V02_RESTART_CONTRACT",
        check_name=field_name,
        observed=v02_restart_contract.get(
            field_name
        ),
        expected=expected_value,
    )


# ------------------------------------------------------------
# Terminal synthesis summary semantics
# ------------------------------------------------------------

terminal_summary_readback = (
    NOTEBOOK10_READBACK_TABLES[
        "V01_TERMINAL_SYNTHESIS_SUMMARY"
    ]
)

terminal_summary_map = notebook10_readback_metric_map(
    terminal_summary_readback
)

EXPECTED_TERMINAL_SUMMARY_VALUES: Final[
    dict[str, Any]
] = {
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": (
        EXPECTED_V01_TERMINAL_STATUS
    ),
    "pipeline_closeout_status": (
        "PASS_PERSISTED_AWAITING_SEMANTIC_READBACK"
    ),
    "selected_model_id": (
        EXPECTED_SELECTED_MODEL_ID
    ),
    "count_score_superiority_supported": True,
    "full_model_adequacy_supported": False,
    "notebook09_status": "SKIPPED_NOT_PASSED",
    "v02_handoff_scope": EXPECTED_V02_HANDOFF_SCOPE,
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "semantic_readback_verified": False,
}

for metric_name, expected_value in (
    EXPECTED_TERMINAL_SUMMARY_VALUES.items()
):
    observed_value = terminal_summary_map.get(
        metric_name
    )

    if isinstance(
        expected_value,
        bool,
    ):
        observed_value = notebook10_readback_boolean(
            observed_value
        )

    register_notebook10_semantic_check(
        category="TERMINAL_SUMMARY",
        check_name=metric_name,
        observed=observed_value,
        expected=expected_value,
    )


# ------------------------------------------------------------
# Stage-disposition semantics
# ------------------------------------------------------------

stage_disposition_readback = (
    NOTEBOOK10_READBACK_TABLES[
        "V01_FINAL_STAGE_DISPOSITION_LEDGER"
    ].copy(
        deep=True
    )
)

stage_disposition_readback[
    "stage_number_normalized"
] = (
    stage_disposition_readback[
        "stage_number"
    ]
    .astype(
        "string"
    )
    .str.replace(
        r"\.0$",
        "",
        regex=True,
    )
    .str.zfill(
        2
    )
)

register_notebook10_semantic_check(
    category="STAGE_DISPOSITION",
    check_name="stage_number_set",
    observed=set(
        stage_disposition_readback[
            "stage_number_normalized"
        ]
    ),
    expected={
        "00",
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
    },
)


def notebook10_stage_row(
    stage_number: str,
) -> pd.Series:
    """Return one unique normalized stage row."""

    matching_rows = stage_disposition_readback.loc[
        stage_disposition_readback[
            "stage_number_normalized"
        ].eq(
            stage_number
        )
    ]

    if len(
        matching_rows
    ) != 1:
        raise Notebook10SemanticReadbackError(
            f"Stage {stage_number} does not have exactly one row."
        )

    return matching_rows.iloc[
        0
    ]


stage08_row = notebook10_stage_row(
    "08"
)

stage09_row = notebook10_stage_row(
    "09"
)

stage10_row = notebook10_stage_row(
    "10"
)

register_notebook10_semantic_check(
    category="STAGE_DISPOSITION",
    check_name="stage08_scientific_state",
    observed=str(
        stage08_row[
            "scientific_state"
        ]
    ),
    expected=(
        "FAILED_REQUIRED_MODEL_ADEQUACY"
    ),
)

register_notebook10_semantic_check(
    category="STAGE_DISPOSITION",
    check_name="stage08_status",
    observed=str(
        stage08_row[
            "status"
        ]
    ),
    expected="FAIL_SCIENTIFIC",
)

register_notebook10_semantic_check(
    category="STAGE_DISPOSITION",
    check_name="stage09_execution_state",
    observed=str(
        stage09_row[
            "execution_state"
        ]
    ),
    expected="SKIPPED_BY_UPSTREAM_BLOCK",
)

register_notebook10_semantic_check(
    category="STAGE_DISPOSITION",
    check_name="stage09_status",
    observed=str(
        stage09_row[
            "status"
        ]
    ),
    expected="SKIPPED_NOT_PASSED",
)

register_notebook10_semantic_check(
    category="STAGE_DISPOSITION",
    check_name="stage10_execution_state",
    observed=str(
        stage10_row[
            "execution_state"
        ]
    ),
    expected="PERSISTED_AWAITING_SEMANTIC_READBACK",
)

register_notebook10_semantic_check(
    category="STAGE_DISPOSITION",
    check_name="stage10_status",
    observed=str(
        stage10_row[
            "status"
        ]
    ),
    expected="PASS_PERSISTED_AWAITING_SEMANTIC_READBACK",
)


# ------------------------------------------------------------
# Completion-standard semantics
# ------------------------------------------------------------

completion_audit_readback = (
    NOTEBOOK10_READBACK_TABLES[
        "V01_COMPLETION_STANDARD_AUDIT"
    ].copy(
        deep=True
    )
)

completion_audit_readback[
    "criterion_number"
] = pd.to_numeric(
    completion_audit_readback[
        "criterion_number"
    ],
    errors="raise",
).astype(
    int
)

completion_audit_readback[
    "completion_met_normalized"
] = completion_audit_readback[
    "completion_met"
].map(
    notebook10_readback_boolean
)

if completion_audit_readback[
    "completion_met_normalized"
].isna().any():
    raise Notebook10SemanticReadbackError(
        "Unable to normalize completion-standard boolean values."
    )


register_notebook10_semantic_check(
    category="COMPLETION_STANDARD",
    check_name="criterion_count",
    observed=int(
        len(
            completion_audit_readback
        )
    ),
    expected=28,
)


def notebook10_completion_row(
    criterion_number: int,
) -> pd.Series:
    """Return one unique completion-standard row."""

    matching_rows = completion_audit_readback.loc[
        completion_audit_readback[
            "criterion_number"
        ].eq(
            criterion_number
        )
    ]

    if len(
        matching_rows
    ) != 1:
        raise Notebook10SemanticReadbackError(
            "Completion-standard criterion does not have exactly "
            f"one row: {criterion_number}"
        )

    return matching_rows.iloc[
        0
    ]


EXPECTED_COMPLETION_OUTCOMES: Final[
    dict[int, tuple[str, bool]]
] = {
    20: (
        "FAIL_BLOCKING",
        False,
    ),
    21: (
        "NOT_REACHED_BLOCKED",
        False,
    ),
    22: (
        "NOT_ESTABLISHED",
        False,
    ),
    23: (
        "NOT_REACHED_BLOCKED",
        False,
    ),
    24: (
        "NOT_REACHED_BLOCKED",
        False,
    ),
    28: (
        "PERSISTED_AWAITING_SEMANTIC_READBACK",
        False,
    ),
}

for criterion_number, (
    expected_outcome,
    expected_completion_met,
) in EXPECTED_COMPLETION_OUTCOMES.items():
    criterion_row = notebook10_completion_row(
        criterion_number
    )

    register_notebook10_semantic_check(
        category="COMPLETION_STANDARD",
        check_name=f"criterion_{criterion_number}::outcome",
        observed=str(
            criterion_row[
                "outcome"
            ]
        ),
        expected=expected_outcome,
    )

    register_notebook10_semantic_check(
        category="COMPLETION_STANDARD",
        check_name=f"criterion_{criterion_number}::completion_met",
        observed=bool(
            criterion_row[
                "completion_met_normalized"
            ]
        ),
        expected=expected_completion_met,
    )


# ------------------------------------------------------------
# Claim-ledger semantics
# ------------------------------------------------------------

claim_ledger_readback = (
    NOTEBOOK10_READBACK_TABLES[
        "V01_FINAL_CLAIM_LEDGER"
    ]
)

if claim_ledger_readback[
    "claim_id"
].astype(
    "string"
).duplicated().any():
    raise Notebook10SemanticReadbackError(
        "The final claim ledger contains duplicate claim IDs."
    )

claim_disposition_by_id = {
    str(
        row.claim_id
    ): str(
        row.disposition
    )
    for row in claim_ledger_readback.itertuples(
        index=False
    )
}

EXPECTED_CLAIM_DISPOSITIONS: Final[
    dict[str, str]
] = {
    "C08": "SUPPORTED_NARROWLY",
    "C09": "REJECTED",
    "C10": "NOT_AUTHORIZED",
    "C11": "NOT_TESTED",
    "C12": "SUPPORTED",
    "C13": "PROHIBITED",
    "C14": "PROHIBITED",
}

for claim_id, expected_disposition in (
    EXPECTED_CLAIM_DISPOSITIONS.items()
):
    register_notebook10_semantic_check(
        category="CLAIM_LEDGER",
        check_name=f"{claim_id}::disposition",
        observed=claim_disposition_by_id.get(
            claim_id
        ),
        expected=expected_disposition,
    )


# ------------------------------------------------------------
# Carryover-catalogue semantics
# ------------------------------------------------------------

carryover_catalogue_readback = (
    NOTEBOOK10_READBACK_TABLES[
        "V01_V02_CARRYOVER_FILE_CATALOGUE"
    ].copy(
        deep=True
    )
)

register_notebook10_semantic_check(
    category="CARRYOVER_CATALOGUE",
    check_name="file_count",
    observed=int(
        len(
            carryover_catalogue_readback
        )
    ),
    expected=440,
)

for authorization_column in (
    "accepted_model_input_authorized",
    "accepted_signal_input_authorized",
    "strategy_input_authorized",
):
    normalized_authorization = carryover_catalogue_readback[
        authorization_column
    ].map(
        notebook10_readback_boolean
    )

    register_notebook10_semantic_check(
        category="CARRYOVER_CATALOGUE",
        check_name=f"{authorization_column}::true_count",
        observed=int(
            normalized_authorization.eq(
                True
            ).sum()
        ),
        expected=0,
    )

protected_reference_flags = carryover_catalogue_readback[
    "protected_partition_reference"
].map(
    notebook10_readback_boolean
)

register_notebook10_semantic_check(
    category="CARRYOVER_CATALOGUE",
    check_name="protected_hash_only_reference_count",
    observed=int(
        protected_reference_flags.eq(
            True
        ).sum()
    ),
    expected=7,
)


carryover_summary_readback = (
    NOTEBOOK10_READBACK_TABLES[
        "V01_V02_CARRYOVER_CLASS_SUMMARY"
    ].copy(
        deep=True
    )
)

register_notebook10_semantic_check(
    category="CARRYOVER_SUMMARY",
    check_name="summed_file_count",
    observed=int(
        pd.to_numeric(
            carryover_summary_readback[
                "file_count"
            ],
            errors="raise",
        ).sum()
    ),
    expected=440,
)

register_notebook10_semantic_check(
    category="CARRYOVER_SUMMARY",
    check_name="summed_protected_reference_count",
    observed=int(
        pd.to_numeric(
            carryover_summary_readback[
                "protected_reference_count"
            ],
            errors="raise",
        ).sum()
    ),
    expected=7,
)


# ------------------------------------------------------------
# Do-not-carry, requirements, and control-index semantics
# ------------------------------------------------------------

do_not_carry_readback = (
    NOTEBOOK10_READBACK_TABLES[
        "V01_V02_DO_NOT_CARRY_LEDGER"
    ]
)

bootstrap_requirements_readback = (
    NOTEBOOK10_READBACK_TABLES[
        "V02_BOOTSTRAP_REQUIREMENTS"
    ]
)

essential_control_index_readback = (
    NOTEBOOK10_READBACK_TABLES[
        "V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX"
    ]
)

register_notebook10_semantic_check(
    category="V02_GOVERNANCE",
    check_name="do_not_carry_record_count",
    observed=int(
        len(
            do_not_carry_readback
        )
    ),
    expected=8,
)

register_notebook10_semantic_check(
    category="V02_GOVERNANCE",
    check_name="bootstrap_requirement_count",
    observed=int(
        len(
            bootstrap_requirements_readback
        )
    ),
    expected=13,
)

register_notebook10_semantic_check(
    category="V02_GOVERNANCE",
    check_name="essential_control_authority_count",
    observed=int(
        len(
            essential_control_index_readback
        )
    ),
    expected=25,
)

register_notebook10_semantic_check(
    category="V02_GOVERNANCE",
    check_name="do_not_carry_ids",
    observed=set(
        do_not_carry_readback[
            "item_id"
        ].astype(
            str
        )
    ),
    expected={
        "DNC01",
        "DNC02",
        "DNC03",
        "DNC04",
        "DNC05",
        "DNC06",
        "DNC07",
        "DNC08",
    },
)

register_notebook10_semantic_check(
    category="V02_GOVERNANCE",
    check_name="bootstrap_requirement_ids",
    observed=set(
        bootstrap_requirements_readback[
            "requirement_id"
        ].astype(
            str
        )
    ),
    expected={
        f"V02-R{index:02d}"
        for index in range(
            1,
            14,
        )
    },
)


# ------------------------------------------------------------
# Build and gate semantic audit
# ------------------------------------------------------------

V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT = (
    pd.DataFrame(
        notebook10_semantic_checks
    )
    .sort_values(
        "check_order",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)

V01_NOTEBOOK10_SEMANTIC_READBACK_FAILURES = (
    V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT.loc[
        V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT[
            "blocking"
        ]
        & ~V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT[
            "passed"
        ]
    ]
    .copy()
)

V01_NOTEBOOK10_SEMANTIC_READBACK_WARNINGS = (
    V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT.loc[
        ~V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT[
            "blocking"
        ]
        & ~V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT[
            "passed"
        ]
    ]
    .copy()
)


if not V01_NOTEBOOK10_SEMANTIC_READBACK_FAILURES.empty:
    rendered_failures = "\n\n".join(
        (
            f"- [{row.category}] {row.check_name}\n"
            f"  observed={row.observed}\n"
            f"  expected={row.expected}"
        )
        for row in (
            V01_NOTEBOOK10_SEMANTIC_READBACK_FAILURES.itertuples(
                index=False
            )
        )
    )

    raise Notebook10SemanticReadbackError(
        "Notebook 10 semantic readback failed:\n\n"
        f"{rendered_failures}"
    )


# ------------------------------------------------------------
# Prepare finalized completion-standard authority in memory
# ------------------------------------------------------------

V01_COMPLETION_STANDARD_FINALIZED_AUDIT = (
    completion_audit_readback.drop(
        columns=[
            "completion_met_normalized",
        ]
    )
    .copy(
        deep=True
    )
)

criterion28_final_mask = (
    V01_COMPLETION_STANDARD_FINALIZED_AUDIT[
        "criterion_number"
    ].eq(
        28
    )
)

V01_COMPLETION_STANDARD_FINALIZED_AUDIT.loc[
    criterion28_final_mask,
    "outcome",
] = "PASS_SEMANTIC_READBACK_VERIFIED"

V01_COMPLETION_STANDARD_FINALIZED_AUDIT.loc[
    criterion28_final_mask,
    "completion_met",
] = True

V01_COMPLETION_STANDARD_FINALIZED_AUDIT.loc[
    criterion28_final_mask,
    "evidence",
] = (
    "The bootstrap-only V0.2 handoff, terminal decision, audit "
    "tables, output manifest, and SHA-256 sidecar were reopened "
    "and independently verified."
)


finalized_completion_flags = (
    V01_COMPLETION_STANDARD_FINALIZED_AUDIT[
        "completion_met"
    ].map(
        notebook10_readback_boolean
    )
)

if finalized_completion_flags.isna().any():
    raise Notebook10SemanticReadbackError(
        "Unable to normalize finalized completion-standard flags."
    )

finalized_completion_met_count = int(
    finalized_completion_flags.sum()
)

finalized_completion_unmet_count = int(
    (
        ~finalized_completion_flags
    ).sum()
)

if finalized_completion_met_count != 23:
    raise Notebook10SemanticReadbackError(
        "Unexpected finalized completion-standard met count.\n"
        f"Observed: {finalized_completion_met_count}\n"
        "Expected: 23"
    )

if finalized_completion_unmet_count != 5:
    raise Notebook10SemanticReadbackError(
        "Unexpected finalized completion-standard unmet count.\n"
        f"Observed: {finalized_completion_unmet_count}\n"
        "Expected: 5"
    )


# ------------------------------------------------------------
# Prepare finalized stage-disposition authority in memory
# ------------------------------------------------------------

V01_FINAL_STAGE_DISPOSITION_FINALIZED = (
    stage_disposition_readback.drop(
        columns=[
            "stage_number_normalized",
        ]
    )
    .copy(
        deep=True
    )
)

final_stage10_mask = (
    V01_FINAL_STAGE_DISPOSITION_FINALIZED[
        "stage_number"
    ]
    .astype(
        "string"
    )
    .str.replace(
        r"\.0$",
        "",
        regex=True,
    )
    .str.zfill(
        2
    )
    .eq(
        "10"
    )
)

V01_FINAL_STAGE_DISPOSITION_FINALIZED.loc[
    final_stage10_mask,
    "execution_state",
] = "SEMANTIC_READBACK_VERIFIED"

V01_FINAL_STAGE_DISPOSITION_FINALIZED.loc[
    final_stage10_mask,
    "scientific_state",
] = "CLOSED_FAILED_V0_1_BRANCH"

V01_FINAL_STAGE_DISPOSITION_FINALIZED.loc[
    final_stage10_mask,
    "control_plane_complete",
] = True

V01_FINAL_STAGE_DISPOSITION_FINALIZED.loc[
    final_stage10_mask,
    "observed_control_statuses",
] = (
    '["PASS_SEMANTIC_READBACK_VERIFIED"]'
)

V01_FINAL_STAGE_DISPOSITION_FINALIZED.loc[
    final_stage10_mask,
    "status",
] = "PASS_SEMANTIC_READBACK_VERIFIED"


# ------------------------------------------------------------
# Prepare finalized decision and handoff authorities in memory
# ------------------------------------------------------------

V01_FINAL_DECISION_FINALIZED = dict(
    notebook10_readback_plain_value(
        V01_FINAL_DECISION_READBACK
    )
)

V01_FINAL_DECISION_FINALIZED.pop(
    "payload_sha256",
    None,
)

V01_FINAL_DECISION_FINALIZED[
    "pipeline_closeout_status"
] = "PASS_SEMANTIC_READBACK_VERIFIED"

V01_FINAL_DECISION_FINALIZED[
    "completion_standard_met_count"
] = finalized_completion_met_count

V01_FINAL_DECISION_FINALIZED[
    "completion_standard_unmet_count"
] = finalized_completion_unmet_count

V01_FINAL_DECISION_FINALIZED[
    "completion_standard_fully_met"
] = False

V01_FINAL_DECISION_FINALIZED[
    "notebook10_semantic_readback_verified"
] = True

V01_FINAL_DECISION_FINALIZED[
    "next_authorized_operation"
] = (
    "PERSIST_NOTEBOOK10_FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX"
)

V01_FINAL_DECISION_FINALIZED[
    "payload_sha256"
] = notebook10_readback_canonical_sha256(
    V01_FINAL_DECISION_FINALIZED
)


V02_BOOTSTRAP_HANDOFF_FINALIZED = dict(
    notebook10_readback_plain_value(
        V02_BOOTSTRAP_HANDOFF_READBACK
    )
)

V02_BOOTSTRAP_HANDOFF_FINALIZED.pop(
    "payload_sha256",
    None,
)

V02_BOOTSTRAP_HANDOFF_FINALIZED[
    "status"
] = "PASS_SEMANTIC_READBACK_VERIFIED_BOOTSTRAP_ONLY"

V02_BOOTSTRAP_HANDOFF_FINALIZED[
    "notebook10_semantic_readback_verified"
] = True

V02_BOOTSTRAP_HANDOFF_FINALIZED[
    "next_authorized_operation"
] = (
    "BEGIN_NEW_V02_RUN_CONTRACT_AFTER_NOTEBOOK10_FINAL_ACCEPTANCE"
)

V02_BOOTSTRAP_HANDOFF_FINALIZED[
    "payload_sha256"
] = notebook10_readback_canonical_sha256(
    V02_BOOTSTRAP_HANDOFF_FINALIZED
)


# ------------------------------------------------------------
# Final readback summary
# ------------------------------------------------------------

V01_NOTEBOOK10_SEMANTIC_READBACK_SUMMARY = pd.DataFrame(
    [
        {
            "metric": "manifest_file_sha256",
            "value": manifest_file_sha256,
        },
        {
            "metric": "manifest_sidecar_matches",
            "value": True,
        },
        {
            "metric": "manifest_semantic_sha256",
            "value": declared_manifest_semantic_sha256,
        },
        {
            "metric": "manifest_semantic_hash_matches",
            "value": True,
        },
        {
            "metric": "manifest_artifact_count",
            "value": int(
                len(
                    manifest_artifact_records
                )
            ),
        },
        {
            "metric": "readback_table_count",
            "value": int(
                len(
                    NOTEBOOK10_READBACK_TABLES
                )
            ),
        },
        {
            "metric": "readback_json_count",
            "value": int(
                len(
                    NOTEBOOK10_READBACK_JSON_PAYLOADS
                )
            ),
        },
        {
            "metric": "semantic_check_count",
            "value": int(
                len(
                    V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT
                )
            ),
        },
        {
            "metric": "blocking_failure_count",
            "value": int(
                len(
                    V01_NOTEBOOK10_SEMANTIC_READBACK_FAILURES
                )
            ),
        },
        {
            "metric": "nonblocking_warning_count",
            "value": int(
                len(
                    V01_NOTEBOOK10_SEMANTIC_READBACK_WARNINGS
                )
            ),
        },
        {
            "metric": "scientific_terminal_class",
            "value": "FAIL",
        },
        {
            "metric": "notebook09_status",
            "value": "SKIPPED_NOT_PASSED",
        },
        {
            "metric": "selected_model_id",
            "value": EXPECTED_SELECTED_MODEL_ID,
        },
        {
            "metric": "accepted_model_handoff_authorized",
            "value": False,
        },
        {
            "metric": "accepted_signal_handoff_authorized",
            "value": False,
        },
        {
            "metric": "strategy_handoff_authorized",
            "value": False,
        },
        {
            "metric": "finalized_completion_met_count",
            "value": finalized_completion_met_count,
        },
        {
            "metric": "finalized_completion_unmet_count",
            "value": finalized_completion_unmet_count,
        },
        {
            "metric": "validation_content_loaded",
            "value": False,
        },
        {
            "metric": "engineering_holdout_content_loaded",
            "value": False,
        },
        {
            "metric": "finalized_decision_payload_sha256",
            "value": (
                V01_FINAL_DECISION_FINALIZED[
                    "payload_sha256"
                ]
            ),
        },
        {
            "metric": "finalized_v02_handoff_payload_sha256",
            "value": (
                V02_BOOTSTRAP_HANDOFF_FINALIZED[
                    "payload_sha256"
                ]
            ),
        },
    ]
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    V01_NOTEBOOK10_SEMANTIC_READBACK_SUMMARY
)

display(
    V01_NOTEBOOK10_ARTIFACT_READBACK_AUDIT
)

display(
    V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT
)

display(
    V01_COMPLETION_STANDARD_FINALIZED_AUDIT
)

display(
    V01_FINAL_STAGE_DISPOSITION_FINALIZED
)

if not V01_NOTEBOOK10_SEMANTIC_READBACK_WARNINGS.empty:
    print(
        "Notebook 10 non-blocking semantic-readback warnings:"
    )

    display(
        V01_NOTEBOOK10_SEMANTIC_READBACK_WARNINGS
    )


# ------------------------------------------------------------
# Freeze semantic-readback authority
# ------------------------------------------------------------

FROZEN_NOTEBOOK10_SEMANTIC_READBACK_AUTHORITY = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "output_manifest_path": str(
        manifest_path
    ),
    "output_manifest_file_sha256": (
        manifest_file_sha256
    ),
    "output_manifest_semantic_sha256": (
        declared_manifest_semantic_sha256
    ),
    "manifest_sidecar_path": str(
        manifest_sidecar_path
    ),
    "manifest_sidecar_matches": True,
    "readback_artifact_count": int(
        len(
            V01_NOTEBOOK10_ARTIFACT_READBACK_AUDIT
        )
    ),
    "readback_table_count": int(
        len(
            NOTEBOOK10_READBACK_TABLES
        )
    ),
    "readback_json_count": int(
        len(
            NOTEBOOK10_READBACK_JSON_PAYLOADS
        )
    ),
    "semantic_check_count": int(
        len(
            V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT
        )
    ),
    "blocking_failure_count": 0,
    "nonblocking_warning_count": int(
        len(
            V01_NOTEBOOK10_SEMANTIC_READBACK_WARNINGS
        )
    ),
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": (
        EXPECTED_V01_TERMINAL_STATUS
    ),
    "notebook09_status": "SKIPPED_NOT_PASSED",
    "selected_model_id": (
        EXPECTED_SELECTED_MODEL_ID
    ),
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "finalized_completion_standard_met_count": (
        finalized_completion_met_count
    ),
    "finalized_completion_standard_unmet_count": (
        finalized_completion_unmet_count
    ),
    "finalized_decision_payload_sha256": (
        V01_FINAL_DECISION_FINALIZED[
            "payload_sha256"
        ]
    ),
    "finalized_v02_handoff_payload_sha256": (
        V02_BOOTSTRAP_HANDOFF_FINALIZED[
            "payload_sha256"
        ]
    ),
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "next_authorized_operation": (
        "PERSIST_NOTEBOOK10_FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX"
    ),
}


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

V01_TERMINAL_SYNTHESIS_READBACK_VERIFIED = True
V02_BOOTSTRAP_HANDOFF_READBACK_VERIFIED = True
NOTEBOOK10_OUTPUT_MANIFEST_READBACK_VERIFIED = True
NOTEBOOK10_SEMANTIC_READBACK_VERIFIED = True

V01_TERMINAL_CLOSEOUT_SEMANTICALLY_VERIFIED = True
V01_FINAL_ACCEPTANCE_READY = True
V01_DELETION_SAFE_INDEX_READY = True

UPSTREAM_ARTIFACTS_VERIFIED = True

V01_MODEL_SIGNAL_AUTHORIZATION_GRANTED = False
V01_STRATEGY_AUTHORIZATION_GRANTED = False
V01_V02_MODEL_HANDOFF_AUTHORIZED = False

NOTEBOOK09_EXECUTED = False
NOTEBOOK09_AUTHORIZED = False

VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False
PROTECTED_PARTITION_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "Notebook 10 semantic readback: PASS. The output manifest, "
    "physical SHA-256 sidecar, nine audit tables, V0.1 terminal "
    "decision, and bootstrap-only V0.2 handoff were independently "
    "reopened and reconciled to their registered hashes, schemas, "
    "and critical semantics. The V0.1 scientific branch remains "
    "FAIL because frozen H1 failed four required model-adequacy "
    "gates. Notebook 09 remains skipped and not passed. H1 remains "
    "unauthorized as an accepted V0.2 model or signal, and no "
    "strategy authority exists. Completion criterion 28 is now "
    "satisfied in the finalized in-memory closeout, producing 23 "
    "met and 5 scientifically unmet criteria. VALIDATION and "
    "ENGINEERING_HOLDOUT remain unopened. No filesystem writes "
    "were performed. Final-acceptance and deletion-safe-index "
    "persistence is the next authorized operation."
)

                                  metric                                                             value
0                   manifest_file_sha256  228f1bbd0e3eb44fbabd6e9149d95d42ae77687aaa6a5f688e24731123174922
1               manifest_sidecar_matches                                                              True
2               manifest_semantic_sha256  f7745fa82ed8b3a1edd996171c1f60845da2be18dedc6e8a6a91d0837be1bc0b
3         manifest_semantic_hash_matches                                                              True
4                manifest_artifact_count                                                                11
5                   readback_table_count                                                                 9
6                    readback_json_count                                                                 2
7                   semantic_check_count                                                               104
8                 blocking_failure_count                                                                 0
9              nonblocking_warning_count                                                                 0
10             scientific_terminal_class                                                              FAIL
11                     notebook09_status                                                SKIPPED_NOT_PASSED
12                     selected_model_id                                          H1_DIAGONAL_SHARED_DECAY
13     accepted_model_handoff_authorized                                                             False
14    accepted_signal_handoff_authorized                                                             False
15           strategy_handoff_authorized                                                             False
16        finalized_completion_met_count                                                                23
17      finalized_completion_unmet_count                                                                 5
18             validation_content_loaded                                                             False
19    engineering_holdout_content_loaded                                                             False
20     finalized_decision_payload_sha256  eb355a415b7235d0bdb987bbecc4f66e4bb1ae07e70530fb981489622189c1e1
21  finalized_v02_handoff_payload_sha256  ef6202ab651af78f7970dd993d0d3ee89362b44b9939c30a4923bebdc4c7d7dc

,variable_name,artifact_type,artifact_role,path,format,size_bytes,file_sha256,file_hash_matches,size_matches,semantic_hash_matches,uncompressed_csv_hash_matches,row_count_matches,column_count_matches,column_order_matches,status
0,V01_COMPLETION_STANDARD_AUDIT,NOTEBOOK_10_AUDIT_TABLE,v01_completion_standard_audit,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,CSV_GZIP,1605,12a67c4d5ea370e32c0acd542071e1fc1bbc0e8ed0ebcbb40bdf113c5fffc77a,True,True,None,True,True,True,True,PASS
1,V01_FINAL_CLAIM_LEDGER,NOTEBOOK_10_AUDIT_TABLE,v01_final_claim_ledger,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,CSV_GZIP,1677,6dcb7d7058fc569ab0143c17f61920b5b18b09e00a3979124a7f5e3e80d12aa3,True,True,None,True,True,True,True,PASS
2,V01_FINAL_DECISION,NOTEBOOK_10_FINAL_DECISION,v01_final_decision,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,JSON,2068,9dd82786892852e2ac5161db754a8cb30cd5b1dc5b93278ff844cfefcc5cb47b,True,True,True,None,None,None,None,PASS
3,V01_FINAL_STAGE_DISPOSITION_LEDGER,NOTEBOOK_10_AUDIT_TABLE,v01_final_stage_disposition_ledger,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,CSV_GZIP,688,59a9cf7105625c4a01fdc73e0bd7688f7090c3ccd965fda77598d8e4add197a7,True,True,None,True,True,True,True,PASS
4,V01_TERMINAL_SYNTHESIS_SUMMARY,NOTEBOOK_10_AUDIT_TABLE,v01_terminal_synthesis_summary,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,CSV_GZIP,593,5f8198b93935205a01fbceaee60bf5466f60e2c589667c5a28ea64e0f3640337,True,True,None,True,True,True,True,PASS
5,V01_V02_CARRYOVER_CLASS_SUMMARY,NOTEBOOK_10_AUDIT_TABLE,v01_v02_carryover_class_summary,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,CSV_GZIP,400,f562697459e1b977e24a5103d915656c9e9ae795ec2e7e3ae310f66a10e31ebb,True,True,None,True,True,True,True,PASS
6,V01_V02_CARRYOVER_FILE_CATALOGUE,NOTEBOOK_10_AUDIT_TABLE,v01_v02_carryover_file_catalogue,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,CSV_GZIP,33856,f6b198373a283d212d7f7a680552fed74d08ee33bcd907b6e5fc635dacc734ac,True,True,None,True,True,True,True,PASS
7,V01_V02_DO_NOT_CARRY_LEDGER,NOTEBOOK_10_AUDIT_TABLE,v01_v02_do_not_carry_ledger,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,CSV_GZIP,671,23c8dba269ab400aa0ed08cc9f6d93958cd178ad5553aadb21a8c66eff99fac1,True,True,None,True,True,True,True,PASS
8,V01_V02_ESSENTIAL_CONTROL_AUTHORITY_INDEX,NOTEBOOK_10_AUDIT_TABLE,v01_v02_essential_control_authority_index,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,CSV_GZIP,2148,4c059442677bb314715678b3fe1100b4173a57fa524820a45085f74aa5bf6114,True,True,None,True,True,True,True,PASS
9,V02_BOOTSTRAP_HANDOFF,NOTEBOOK_10_V02_BOOTSTRAP_HANDOFF,v01_to_v02_bootstrap_handoff,D:\Clown Project\V0.1\artifacts\handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_han...,JSON,23147,86821bad9a078943a891918a2eec806552e9e57874c96adbc54f71d37a8f1101,True,True,True,None,None,None,None,PASS
10,V02_BOOTSTRAP_REQUIREMENTS,NOTEBOOK_10_AUDIT_TABLE,v02_bootstrap_requirements,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_audit_synthesis_and_v02_handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e823...,CSV_GZIP,1265,da1678fac1e5a44b9525bf336cfbe6238e4d02c496aaa61367cc226d5361ce2c,True,True,None,True,True,True,True,PASS

,check_order,category,check_name,blocking,passed,status,observed,expected
0,1,FINAL_DECISION,source_run_prefix,True,True,PASS,'BTCUSDT_spot_20260710T063746Z_c8b5bf12','BTCUSDT_spot_20260710T063746Z_c8b5bf12'
1,2,FINAL_DECISION,source_set_sha256,True,True,PASS,'132c83531eec615d279408b5c06f402973114ba3058dfadd2fe58e2e67184c4b','132c83531eec615d279408b5c06f402973114ba3058dfadd2fe58e2e67184c4b'
2,3,FINAL_DECISION,v0_1_run_id,True,True,PASS,'v0_1_20260714T090616Z_e82325081a81','v0_1_20260714T090616Z_e82325081a81'
3,4,FINAL_DECISION,run_config_sha256,True,True,PASS,'14aea0efb3c7b6a193b8c4575a440babe8265d2935c6a770bee995f688d59617','14aea0efb3c7b6a193b8c4575a440babe8265d2935c6a770bee995f688d59617'
4,5,FINAL_DECISION,run_identity_sha256,True,True,PASS,'5eb89cf073c036d70e3767df4b35ace7c31822e52e9b9df19204c42e37fe4198','5eb89cf073c036d70e3767df4b35ace7c31822e52e9b9df19204c42e37fe4198'
...,...,...,...,...,...,...,...,...
99,100,V02_GOVERNANCE,do_not_carry_record_count,True,True,PASS,8,8
100,101,V02_GOVERNANCE,bootstrap_requirement_count,True,True,PASS,13,13
101,102,V02_GOVERNANCE,essential_control_authority_count,True,True,PASS,25,25
102,103,V02_GOVERNANCE,do_not_carry_ids,True,True,PASS,"[""DNC01"", ""DNC02"", ""DNC03"", ""DNC04"", ""DNC05"", ""DNC06"", ""DNC07"", ""DNC08""]","[""DNC01"", ""DNC02"", ""DNC03"", ""DNC04"", ""DNC05"", ""DNC06"", ""DNC07"", ""DNC08""]"
103,104,V02_GOVERNANCE,bootstrap_requirement_ids,True,True,PASS,"[""V02-R01"", ""V02-R02"", ""V02-R03"", ""V02-R04"", ""V02-R05"", ""V02-R06"", ""V02-R07"", ""V02-R08"", ""V02-R09"", ""V02-R10"", ""V02-R11"", ""V02-R12"", ""V02-R13""]","[""V02-R01"", ""V02-R02"", ""V02-R03"", ""V02-R04"", ""V02-R05"", ""V02-R06"", ""V02-R07"", ""V02-R08"", ""V02-R09"", ""V02-R10"", ""V02-R11"", ""V02-R12"", ""V02-R13""]"

,criterion_number,criterion,outcome,completion_met,evidence
0,1,V0.0 source paths are correctly registered.,PASS,True,Notebook 00 control plane verified.
1,2,The existing V0.0 raw collection is used as primary input.,PASS,True,6 V0.0 files occur in the verified catalogue.
2,3,V0.1 does not require a copied raw-data directory.,PASS,True,Registered V0.0 source authority is preserved separately.
3,4,All V0.0 primary files have checksums.,PASS,True,Manifested-file physical verification passed.
4,5,The source run prefix remains preserved.,PASS,True,BTCUSDT_spot_20260710T063746Z_c8b5bf12
5,6,The pipeline runs from the registered V0.0 source set.,PASS,True,Notebooks 00–08 have complete persisted control planes.
6,7,Every completed phase has explicit saved outputs.,PASS,True,434 V0.1 files were physically verified.
7,8,Every completed phase has an acceptance gate.,PASS,True,Stage-control coverage passed for Notebooks 00–08.
8,9,Differential-depth continuity is audited.,PASS,True,Notebook 01/02 control planes accepted.
9,10,The REST snapshot bridge is validated.,PASS,True,Notebook 01/02 control planes accepted.
10,11,Visible MBP reconstruction is reproducible.,PASS,True,Notebook 02 persisted output and handoff accepted.
11,12,LOCAL_STRICT causal alignment is audited.,PASS,True,Notebook 03 persisted output and handoff accepted.
12,13,Exact event-time ties have a defensible treatment.,PASS,True,Notebook 04 event and batch contracts accepted.
13,14,Event definitions are frozen before model comparison.,PASS,True,Notebook 04 precedes Notebook 06/07 and is persisted.
14,15,Poisson and simple baselines are established.,PASS,True,D0_SIDE_CONSTANT_POISSON; E_SIDE_EWMA_250MS_POISSON
15,16,The Hawkes estimator converges reliably.,PASS_FOR_ESTIMATION_STAGE,True,Notebook 07 accepted frozen H1 estimation.
16,17,The Hawkes parameterization convention is explicit.,PASS,True,Notebook 07 persisted execution and model contracts.
17,18,The model satisfies the stationarity safety margin.,PASS,True,Notebook 08 stationarity gate passed.
18,19,Split-boundary history is handled.,PASS,True,Notebook 07 boundary-history contract verified.
19,20,Residual diagnostics are acceptable.,FAIL_BLOCKING,False,Residual distribution and residual serial-dependence gates failed on locked CALIBRATION.
20,21,Validation likelihood improves over baselines.,NOT_REACHED_BLOCKED,False,Notebook 09 and VALIDATION were not authorized.
21,22,Parameter estimates are reasonably stable across windows.,NOT_ESTABLISHED,False,No accepted multi-window validation authority was created after Notebook 08 failure.
22,23,The intensity signal is tested against simpler controls.,NOT_REACHED_BLOCKED,False,Notebook 09 was skipped and not passed.
23,24,Latency decay is measured using local observability.,NOT_REACHED_BLOCKED,False,Signal validation was not authorized.
24,25,The final holdout remains untouched until Notebook 10.,PASS_UNOPENED,True,ENGINEERING_HOLDOUT remained unopened throughout Notebooks 00–10.
25,26,No tuning occurs after opening the holdout.,PASS_HOLDOUT_NEVER_OPENED,True,"No holdout opening, refit, repair, or replacement occurred."
26,27,Important V0.0 results are reproduced or discrepancies explained.,PASS_AS_RECORDED_BY_STAGE_AUTHORITIES,True,Control-plane and manifested-file reconciliation completed for Notebooks 00–08.
27,28,The V0.2 handoff is complete.,PASS_SEMANTIC_READBACK_VERIFIED,True,"The bootstrap-only V0.2 handoff, terminal decision, audit tables, output manifest, and SHA-256 sidecar were reopened and independently verified."

,stage_number,stage_name,execution_state,scientific_state,downstream_state,control_plane_complete,observed_control_statuses,status
0,0,V01_RUN_CONTRACT,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,"[""CONDITIONAL PASS""]",PASS
1,1,RAW_DATA_AUDIT,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,"[""CONDITIONAL PASS""]",PASS
2,2,VISIBLE_BOOK_RECONSTRUCTION,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,"[""PASS_WITH_REFERENCE_WARNINGS""]",PASS
3,3,CAUSAL_TRADE_BOOK_ALIGNMENT,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,"[""PASS_WITH_ALIGNMENT_WARNINGS""]",PASS
4,4,EVENT_STREAM_CONSTRUCTION,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,"[""PASS_WITH_EVENT_STREAM_WARNINGS""]",PASS
5,5,MARKET_STATE_FEATURES,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,"[""PASS_WITH_FEATURE_WARNINGS""]",PASS
6,6,POINT_PROCESS_BASELINES,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,"[""PASS"",""PASS_HAWKES_RESTRICTED_FIRST""]",PASS
7,7,HAWKES_ESTIMATION,COMPLETED,ACCEPTED_FOR_DECLARED_STAGE_SCOPE,PRESERVED_AS_V0_1_AUTHORITY,True,"[""PASS_HANDOFF_FOR_HAWKES_DIAGNOSTICS"",""PASS_HAWKES_ESTIMATION_RESTRICTED_FIRST""]",PASS
8,8,HAWKES_DIAGNOSTICS,COMPLETED,FAILED_REQUIRED_MODEL_ADEQUACY,DIAGNOSTIC_REFERENCE_ONLY,True,"[""BLOCKING_REJECTION"",""FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY"",""PASS_HANDOFF_TO_FINAL_AUDIT_AFTER_DIAGNOSTIC_FAILURE"",""object""]",FAIL_SCIENTIFIC
9,9,INTENSITY_SIGNAL_VALIDATION,SKIPPED_BY_UPSTREAM_BLOCK,NOT_TESTED,NO_AUTHORITY_CREATED,True,"[""BLOCKED_BY_NOTEBOOK08_DIAGNOSTIC_FAILURE""]",SKIPPED_NOT_PASSED
10,10,FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF,SEMANTIC_READBACK_VERIFIED,CLOSED_FAILED_V0_1_BRANCH,BOOTSTRAP_AND_PROVENANCE_ONLY_NO_ACCEPTED_MODEL_SIGNAL_OR_STRATEGY,True,"[""PASS_SEMANTIC_READBACK_VERIFIED""]",PASS_SEMANTIC_READBACK_VERIFIED

Notebook 10 semantic readback: PASS. The output manifest, physical SHA-256 sidecar, nine audit tables, V0.1 terminal decision, and bootstrap-only V0.2 handoff were independently reopened and reconciled to their registered hashes, schemas, and critical semantics. The V0.1 scientific branch remains FAIL because frozen H1 failed four required model-adequacy gates. Notebook 09 remains skipped and not passed. H1 remains unauthorized as an accepted V0.2 model or signal, and no strategy authority exists. Completion criterion 28 is now satisfied in the finalized in-memory closeout, producing 23 met and 5 scientifically unmet criteria. VALIDATION and ENGINEERING_HOLDOUT remain unopened. No filesystem writes were performed. Final-acceptance and deletion-safe-index persistence is the next authorized operation.

In [37]:
# ============================================================
# Notebook 10 final acceptance and deletion-safe index persistence
#
# V0.0 files are valid retained authorities outside V0.1.
# Each retained file is validated against its declared authority
# root before it enters the deletion-safe index.
#
# This cell:
# - persists finalized V0.1 decision and V0.2 bootstrap handoff;
# - persists finalized completion and stage ledgers;
# - builds a deletion-safe authority index covering V0.0,
#   upstream V0.1, and Notebook 10 persisted artifacts;
# - records exact Notebook 00–09 deletion candidates;
# - persists a final-acceptance package and manifest;
# - does not delete any notebook;
# - leaves deletion authorization false pending final readback.
#
# Protected analytical files remain hash-only references.
# No model refit, replacement, repair, or parameter update occurs.
# ============================================================

from __future__ import annotations

import gzip
import hashlib
import io
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any, Final, Mapping

import numpy as np
import pandas as pd
from IPython.display import display


class Notebook10FinalAcceptancePersistenceError(RuntimeError):
    """Raised when final-acceptance persistence cannot close safely."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

REQUIRED_FINALIZATION_FLAGS: Final[dict[str, bool]] = {
    "UPSTREAM_ARTIFACTS_VERIFIED": bool(
        globals().get("UPSTREAM_ARTIFACTS_VERIFIED", False)
    ),
    "NOTEBOOK10_SEMANTIC_READBACK_VERIFIED": bool(
        globals().get("NOTEBOOK10_SEMANTIC_READBACK_VERIFIED", False)
    ),
    "V01_TERMINAL_CLOSEOUT_SEMANTICALLY_VERIFIED": bool(
        globals().get(
            "V01_TERMINAL_CLOSEOUT_SEMANTICALLY_VERIFIED",
            False,
        )
    ),
    "V01_FINAL_ACCEPTANCE_READY": bool(
        globals().get("V01_FINAL_ACCEPTANCE_READY", False)
    ),
    "V01_DELETION_SAFE_INDEX_READY": bool(
        globals().get("V01_DELETION_SAFE_INDEX_READY", False)
    ),
}

failed_finalization_flags = sorted(
    flag_name
    for flag_name, passed in REQUIRED_FINALIZATION_FLAGS.items()
    if not passed
)

if failed_finalization_flags:
    raise Notebook10FinalAcceptancePersistenceError(
        "Notebook 10 finalization prerequisites have not passed:\n"
        f"{failed_finalization_flags}"
    )


REQUIRED_FINALIZATION_OBJECTS: Final[tuple[str, ...]] = (
    "V00_ROOT",
    "V01_ROOT",
    "V01_MANIFEST_ROOT",
    "V01_HANDOFF_ROOT",
    "NOTEBOOK10_OUTPUT_PREFIX",
    "SOURCE_RUN_PREFIX",
    "SOURCE_SET_SHA256",
    "V01_RUN_ID",
    "RUN_CONFIG_SHA256",
    "RUN_IDENTITY_SHA256",
    "V01_FINAL_DECISION_FINALIZED",
    "V02_BOOTSTRAP_HANDOFF_FINALIZED",
    "V01_COMPLETION_STANDARD_FINALIZED_AUDIT",
    "V01_FINAL_STAGE_DISPOSITION_FINALIZED",
    "V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT",
    "V01_NOTEBOOK10_ARTIFACT_READBACK_AUDIT",
    "V01_V02_CARRYOVER_FILE_CATALOGUE",
    "NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY",
    "FROZEN_NOTEBOOK10_SEMANTIC_READBACK_AUTHORITY",
)

missing_finalization_objects = sorted(
    object_name
    for object_name in REQUIRED_FINALIZATION_OBJECTS
    if object_name not in globals()
)

if missing_finalization_objects:
    raise Notebook10FinalAcceptancePersistenceError(
        "Required finalization objects are unavailable:\n"
        f"{missing_finalization_objects}"
    )


for mapping_name, mapping_value in (
    (
        "V01_FINAL_DECISION_FINALIZED",
        V01_FINAL_DECISION_FINALIZED,
    ),
    (
        "V02_BOOTSTRAP_HANDOFF_FINALIZED",
        V02_BOOTSTRAP_HANDOFF_FINALIZED,
    ),
    (
        "FROZEN_NOTEBOOK10_SEMANTIC_READBACK_AUTHORITY",
        FROZEN_NOTEBOOK10_SEMANTIC_READBACK_AUTHORITY,
    ),
):
    if not isinstance(mapping_value, Mapping):
        raise Notebook10FinalAcceptancePersistenceError(
            f"{mapping_name} must be a mapping."
        )


# ------------------------------------------------------------
# Runtime safety guards
# ------------------------------------------------------------

if bool(globals().get("VALIDATION_CONTENT_LOADED", False)):
    raise Notebook10FinalAcceptancePersistenceError(
        "VALIDATION content was unexpectedly loaded."
    )

if bool(
    globals().get(
        "ENGINEERING_HOLDOUT_CONTENT_LOADED",
        False,
    )
):
    raise Notebook10FinalAcceptancePersistenceError(
        "ENGINEERING_HOLDOUT content was unexpectedly loaded."
    )


protected_runtime_state = globals().get(
    "PROTECTED_PARTITION_CONTENT_LOADED",
    False,
)

if isinstance(protected_runtime_state, Mapping):
    opened_protected_partitions = sorted(
        str(partition)
        for partition, loaded in protected_runtime_state.items()
        if bool(loaded)
    )

    if opened_protected_partitions:
        raise Notebook10FinalAcceptancePersistenceError(
            "Protected partition content was marked as loaded:\n"
            f"{opened_protected_partitions}"
        )

elif bool(protected_runtime_state):
    raise Notebook10FinalAcceptancePersistenceError(
        "Protected partition content was unexpectedly loaded."
    )


if bool(globals().get("MODEL_REFIT_PERFORMED", False)):
    raise Notebook10FinalAcceptancePersistenceError(
        "A model refit was recorded before final acceptance."
    )

if bool(globals().get("MODEL_REPLACEMENT_PERFORMED", False)):
    raise Notebook10FinalAcceptancePersistenceError(
        "A model replacement was recorded before final acceptance."
    )

if int(
    globals().get(
        "CALIBRATION_PARAMETER_UPDATES_PERFORMED",
        0,
    )
) != 0:
    raise Notebook10FinalAcceptancePersistenceError(
        "Nonzero CALIBRATION parameter updates were recorded."
    )


# ------------------------------------------------------------
# Expected terminal semantics
# ------------------------------------------------------------

EXPECTED_TERMINAL_STATUS: Final[str] = (
    "FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY"
)

EXPECTED_SELECTED_MODEL_ID: Final[str] = (
    "H1_DIAGONAL_SHARED_DECAY"
)

EXPECTED_V02_HANDOFF_SCOPE: Final[str] = (
    "BOOTSTRAP_AND_PROVENANCE_ONLY_NO_ACCEPTED_MODEL_SIGNAL_OR_STRATEGY"
)

EXPECTED_FAILED_ADEQUACY_GATES: Final[set[str]] = {
    "LOCKED_CALIBRATION_RESIDUAL_DISTRIBUTION",
    "LOCKED_CALIBRATION_RESIDUAL_SERIAL_DEPENDENCE",
    "LOCKED_CALIBRATION_PATH_COUNT_CALIBRATION",
    "LOCKED_CALIBRATION_EXACT_TIME_MULTIPLICITY",
}


# ------------------------------------------------------------
# Path authority helpers
# ------------------------------------------------------------

def finalization_normalized_path(value: Any) -> Path:
    """Return one absolute normalized path."""

    return Path(str(value)).expanduser().resolve(strict=False)


FINALIZATION_V00_ROOT: Final[Path] = finalization_normalized_path(
    V00_ROOT
)

FINALIZATION_V01_ROOT: Final[Path] = finalization_normalized_path(
    V01_ROOT
)


def finalization_path_is_inside(
    path: Path,
    root: Path,
) -> bool:
    """
    Check containment using normalized, case-insensitive paths.

    This supports V0.0 retained authorities and V0.1 outputs
    without treating V0.0 as an illegal V0.1 path.
    """

    normalized_path_text = os.path.normcase(
        os.path.abspath(str(finalization_normalized_path(path)))
    )

    normalized_root_text = os.path.normcase(
        os.path.abspath(str(finalization_normalized_path(root)))
    )

    try:
        common_path = os.path.commonpath(
            [
                normalized_path_text,
                normalized_root_text,
            ]
        )

    except ValueError:
        return False

    return common_path == normalized_root_text


def finalization_require_inside_root(
    path: Path,
    root: Path,
    *,
    role: str,
    root_label: str,
) -> Path:
    """Require one path to lie under its declared authority root."""

    normalized_path = finalization_normalized_path(path)
    normalized_root = finalization_normalized_path(root)

    if not finalization_path_is_inside(
        normalized_path,
        normalized_root,
    ):
        raise Notebook10FinalAcceptancePersistenceError(
            "A finalization path lies outside its declared "
            "authority root.\n"
            f"Role: {role}\n"
            f"Declared root: {root_label}\n"
            f"Root path: {normalized_root}\n"
            f"Artifact path: {normalized_path}"
        )

    return normalized_path


def finalization_normalize_authority_root(
    value: Any,
) -> tuple[str, Path]:
    """Resolve one declared catalogue authority root."""

    normalized_label = (
        str(value)
        .strip()
        .casefold()
        .replace("_", "")
        .replace(" ", "")
    )

    if normalized_label in {
        "v0.0",
        "v00",
        "v0",
    }:
        return (
            "V0.0",
            FINALIZATION_V00_ROOT,
        )

    if normalized_label in {
        "v0.1",
        "v01",
    }:
        return (
            "V0.1",
            FINALIZATION_V01_ROOT,
        )

    raise Notebook10FinalAcceptancePersistenceError(
        "Unknown retained-authority root label:\n"
        f"{value!r}"
    )


def finalization_relative_path(
    path: Path,
    root: Path,
) -> str:
    """Return one path relative to its declared authority root."""

    normalized_path = finalization_normalized_path(path)
    normalized_root = finalization_normalized_path(root)

    return os.path.relpath(
        str(normalized_path),
        str(normalized_root),
    )


# ------------------------------------------------------------
# General serialization helpers
# ------------------------------------------------------------

def finalization_plain_value(value: Any) -> Any:
    """Convert values into strict JSON-compatible Python types."""

    if value is None:
        return None

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, (bool, np.bool_)):
        return bool(value)

    if isinstance(value, (int, np.integer)) and not isinstance(
        value,
        bool,
    ):
        return int(value)

    if isinstance(value, (float, np.floating)):
        numeric_value = float(value)

        if not np.isfinite(numeric_value):
            return str(numeric_value)

        return numeric_value

    if isinstance(value, pd.Timestamp):
        return value.isoformat()

    if isinstance(value, Mapping):
        return {
            str(key): finalization_plain_value(child)
            for key, child in value.items()
        }

    if isinstance(value, (list, tuple, set)):
        iterable = (
            sorted(value)
            if isinstance(value, set)
            else value
        )

        return [
            finalization_plain_value(child)
            for child in iterable
        ]

    try:
        missing_value = pd.isna(value)

        if isinstance(missing_value, (bool, np.bool_)) and bool(
            missing_value
        ):
            return None

    except (TypeError, ValueError):
        pass

    return str(value)


def finalization_boolean(value: Any) -> bool | None:
    """Normalize a boolean-like value."""

    if value is None:
        return None

    if isinstance(value, (bool, np.bool_)):
        return bool(value)

    if isinstance(value, (int, np.integer)) and not isinstance(
        value,
        bool,
    ):
        if int(value) in {0, 1}:
            return bool(int(value))

    normalized = str(value).strip().casefold()

    if normalized in {
        "true",
        "t",
        "yes",
        "y",
        "1",
        "pass",
        "passed",
    }:
        return True

    if normalized in {
        "false",
        "f",
        "no",
        "n",
        "0",
        "",
        "none",
        "null",
    }:
        return False

    return None


def finalization_canonical_sha256(
    payload: Mapping[str, Any],
) -> str:
    """Return a deterministic non-file semantic SHA-256."""

    canonical_bytes = json.dumps(
        finalization_plain_value(payload),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")

    return hashlib.sha256(canonical_bytes).hexdigest()


def finalization_payload_with_hash(
    payload: Mapping[str, Any],
    *,
    hash_field: str = "payload_sha256",
) -> dict[str, Any]:
    """Return a copied payload with a non-self-referential hash."""

    copied_payload = dict(finalization_plain_value(payload))

    copied_payload.pop(hash_field, None)

    copied_payload[hash_field] = (
        finalization_canonical_sha256(copied_payload)
    )

    return copied_payload


def finalization_json_bytes(
    payload: Mapping[str, Any],
) -> bytes:
    """Serialize deterministic UTF-8 JSON bytes."""

    return (
        json.dumps(
            finalization_plain_value(payload),
            sort_keys=True,
            indent=2,
            ensure_ascii=False,
            allow_nan=False,
        )
        + "\n"
    ).encode("utf-8")


def finalization_scalar_for_csv(value: Any) -> Any:
    """Convert nested values into deterministic CSV scalars."""

    if isinstance(value, (Mapping, list, tuple, set)):
        return json.dumps(
            finalization_plain_value(value),
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
            allow_nan=False,
        )

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, pd.Timestamp):
        return value.isoformat()

    if isinstance(value, (bool, np.bool_)):
        return bool(value)

    if isinstance(value, (int, np.integer)) and not isinstance(
        value,
        bool,
    ):
        return int(value)

    if isinstance(value, (float, np.floating)):
        numeric_value = float(value)

        if not np.isfinite(numeric_value):
            return str(numeric_value)

        return numeric_value

    try:
        missing_value = pd.isna(value)

        if isinstance(missing_value, (bool, np.bool_)) and bool(
            missing_value
        ):
            return None

    except (TypeError, ValueError):
        pass

    return value


def finalization_dataframe_bytes(
    dataframe: pd.DataFrame,
) -> tuple[bytes, str]:
    """Return deterministic gzip bytes and raw CSV hash."""

    export_frame = dataframe.copy(deep=True)

    for column_name in export_frame.columns:
        if (
            pd.api.types.is_object_dtype(
                export_frame[column_name].dtype
            )
            or pd.api.types.is_string_dtype(
                export_frame[column_name].dtype
            )
        ):
            export_frame[column_name] = export_frame[
                column_name
            ].map(finalization_scalar_for_csv)

    csv_text = export_frame.to_csv(
        index=False,
        lineterminator="\n",
        na_rep="",
        float_format="%.17g",
    )

    csv_bytes = csv_text.encode("utf-8")

    raw_csv_sha256 = hashlib.sha256(
        csv_bytes
    ).hexdigest()

    compressed_buffer = io.BytesIO()

    with gzip.GzipFile(
        filename="",
        mode="wb",
        fileobj=compressed_buffer,
        compresslevel=9,
        mtime=0,
    ) as gzip_stream:
        gzip_stream.write(csv_bytes)

    return (
        compressed_buffer.getvalue(),
        raw_csv_sha256,
    )


# ------------------------------------------------------------
# File hash and atomic persistence helpers
# ------------------------------------------------------------

def finalization_sha256_file(
    path: Path,
    *,
    chunk_size: int = 1 << 20,
) -> str:
    """Return the physical SHA-256 of one file."""

    digest = hashlib.sha256()

    with path.open("rb") as input_stream:
        while True:
            chunk = input_stream.read(chunk_size)

            if not chunk:
                break

            digest.update(chunk)

    return digest.hexdigest()


def finalization_atomic_write_exact(
    path: Path,
    payload_bytes: bytes,
    *,
    role: str,
) -> dict[str, Any]:
    """
    Atomically create one V0.1 finalization artifact.

    An existing file is reused only when its bytes are identical.
    Differing content is never overwritten.
    """

    normalized_path = finalization_require_inside_root(
        finalization_normalized_path(path),
        FINALIZATION_V01_ROOT,
        role=role,
        root_label="V0.1",
    )

    normalized_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    intended_sha256 = hashlib.sha256(
        payload_bytes
    ).hexdigest()

    if normalized_path.exists():
        if not normalized_path.is_file():
            raise Notebook10FinalAcceptancePersistenceError(
                "An output path exists but is not a regular file:\n"
                f"{normalized_path}"
            )

        existing_sha256 = finalization_sha256_file(
            normalized_path
        )

        if existing_sha256 != intended_sha256:
            raise Notebook10FinalAcceptancePersistenceError(
                "Refusing to overwrite a differing finalization "
                "artifact.\n"
                f"Role: {role}\n"
                f"Path: {normalized_path}\n"
                f"Existing SHA-256: {existing_sha256}\n"
                f"Intended SHA-256: {intended_sha256}"
            )

        return {
            "path": normalized_path,
            "sha256": existing_sha256,
            "size_bytes": int(
                normalized_path.stat().st_size
            ),
            "write_action": "REUSED_IDENTICAL",
        }

    temporary_path: Path | None = None

    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=normalized_path.parent,
            prefix=normalized_path.name + ".",
            suffix=".tmp",
            delete=False,
        ) as temporary_stream:
            temporary_path = Path(temporary_stream.name)

            finalization_require_inside_root(
                temporary_path,
                FINALIZATION_V01_ROOT,
                role=f"{role}_TEMPORARY",
                root_label="V0.1",
            )

            temporary_stream.write(payload_bytes)
            temporary_stream.flush()
            os.fsync(temporary_stream.fileno())

        temporary_sha256 = finalization_sha256_file(
            temporary_path
        )

        if temporary_sha256 != intended_sha256:
            raise Notebook10FinalAcceptancePersistenceError(
                "Temporary finalization artifact hash mismatch.\n"
                f"Role: {role}"
            )

        if normalized_path.exists():
            existing_sha256 = finalization_sha256_file(
                normalized_path
            )

            if existing_sha256 != intended_sha256:
                raise Notebook10FinalAcceptancePersistenceError(
                    "The output target appeared during persistence "
                    "with differing content.\n"
                    f"Path: {normalized_path}"
                )

            temporary_path.unlink(missing_ok=True)
            temporary_path = None

            return {
                "path": normalized_path,
                "sha256": existing_sha256,
                "size_bytes": int(
                    normalized_path.stat().st_size
                ),
                "write_action": "REUSED_IDENTICAL_AFTER_RACE",
            }

        os.replace(
            temporary_path,
            normalized_path,
        )

        temporary_path = None

    finally:
        if (
            temporary_path is not None
            and temporary_path.exists()
        ):
            temporary_path.unlink(missing_ok=True)

    observed_sha256 = finalization_sha256_file(
        normalized_path
    )

    if observed_sha256 != intended_sha256:
        raise Notebook10FinalAcceptancePersistenceError(
            "Persisted finalization artifact hash mismatch.\n"
            f"Role: {role}\n"
            f"Path: {normalized_path}"
        )

    return {
        "path": normalized_path,
        "sha256": observed_sha256,
        "size_bytes": int(
            normalized_path.stat().st_size
        ),
        "write_action": "CREATED_ATOMICALLY",
    }


# ------------------------------------------------------------
# Column-resolution helpers for the carryover catalogue
# ------------------------------------------------------------

def finalization_pick_column(
    dataframe: pd.DataFrame,
    candidates: tuple[str, ...],
    *,
    purpose: str,
    required: bool = True,
) -> str | None:
    """Choose the first available column from an ordered list."""

    for column_name in candidates:
        if column_name in dataframe.columns:
            return column_name

    if required:
        raise Notebook10FinalAcceptancePersistenceError(
            "Unable to resolve a required carryover-catalogue "
            f"column for {purpose}.\n"
            f"Candidates: {list(candidates)}\n"
            f"Available: {list(dataframe.columns)}"
        )

    return None


carryover_catalogue = (
    V01_V02_CARRYOVER_FILE_CATALOGUE.copy(
        deep=True
    )
)

carryover_path_column = finalization_pick_column(
    carryover_catalogue,
    (
        "resolved_path",
        "path",
        "physical_path",
        "absolute_path",
    ),
    purpose="physical path",
)

carryover_sha256_column = finalization_pick_column(
    carryover_catalogue,
    (
        "physical_sha256",
        "sha256",
        "file_sha256",
    ),
    purpose="physical SHA-256",
)

carryover_size_column = finalization_pick_column(
    carryover_catalogue,
    (
        "physical_size_bytes",
        "size_bytes",
        "file_size_bytes",
    ),
    purpose="physical size",
)

carryover_authority_root_column = finalization_pick_column(
    carryover_catalogue,
    (
        "authority_root",
    ),
    purpose="authority root",
)

carryover_verification_column = finalization_pick_column(
    carryover_catalogue,
    (
        "physical_verification_passed",
        "verification_passed",
    ),
    purpose="physical verification",
)

carryover_protected_column = finalization_pick_column(
    carryover_catalogue,
    (
        "protected_partition_reference",
    ),
    purpose="protected-partition reference",
)

carryover_class_column = finalization_pick_column(
    carryover_catalogue,
    (
        "v02_carryover_class",
    ),
    purpose="V0.2 carryover class",
    required=False,
)

carryover_use_mode_column = finalization_pick_column(
    carryover_catalogue,
    (
        "v02_use_mode",
    ),
    purpose="V0.2 use mode",
    required=False,
)

carryover_stage_column = finalization_pick_column(
    carryover_catalogue,
    (
        "source_stage_numbers",
        "source_stages",
    ),
    purpose="source-stage registration",
    required=False,
)


# ------------------------------------------------------------
# Build deletion-safe retained-authority index
#
# Critical rule:
# V0.0 rows are checked against V0.0.
# V0.1 rows are checked against V0.1.
# No V0.0 path is passed through a V0.1-only guard.
# ------------------------------------------------------------

deletion_safe_records: list[dict[str, Any]] = []
seen_authority_paths: dict[str, str] = {}


for row_number, (_, row) in enumerate(
    carryover_catalogue.iterrows(),
    start=1,
):
    authority_root_label, authority_root_path = (
        finalization_normalize_authority_root(
            row[carryover_authority_root_column]
        )
    )

    artifact_path = finalization_require_inside_root(
        finalization_normalized_path(
            row[carryover_path_column]
        ),
        authority_root_path,
        role="UPSTREAM_RETAINED_AUTHORITY",
        root_label=authority_root_label,
    )

    if not artifact_path.is_file():
        raise Notebook10FinalAcceptancePersistenceError(
            "A retained upstream authority file is missing.\n"
            f"Row: {row_number}\n"
            f"Authority root: {authority_root_label}\n"
            f"Path: {artifact_path}"
        )

    declared_sha256 = str(
        row[carryover_sha256_column]
    ).strip().lower()

    if re.fullmatch(
        r"[0-9a-f]{64}",
        declared_sha256,
    ) is None:
        raise Notebook10FinalAcceptancePersistenceError(
            "A retained upstream authority has an invalid SHA-256.\n"
            f"Row: {row_number}\n"
            f"Path: {artifact_path}\n"
            f"Value: {declared_sha256!r}"
        )

    declared_size_bytes = int(
        row[carryover_size_column]
    )

    observed_size_bytes = int(
        artifact_path.stat().st_size
    )

    if observed_size_bytes != declared_size_bytes:
        raise Notebook10FinalAcceptancePersistenceError(
            "A retained upstream authority size changed after "
            "physical verification.\n"
            f"Path: {artifact_path}\n"
            f"Observed: {observed_size_bytes}\n"
            f"Declared: {declared_size_bytes}"
        )

    verification_passed = finalization_boolean(
        row[carryover_verification_column]
    )

    if verification_passed is not True:
        raise Notebook10FinalAcceptancePersistenceError(
            "A retained upstream authority lacks prior physical "
            "verification.\n"
            f"Path: {artifact_path}\n"
            f"Observed flag: "
            f"{row[carryover_verification_column]!r}"
        )

    protected_reference = finalization_boolean(
        row[carryover_protected_column]
    )

    if protected_reference is None:
        raise Notebook10FinalAcceptancePersistenceError(
            "Unable to normalize protected-reference status.\n"
            f"Path: {artifact_path}"
        )

    normalized_path_key = os.path.normcase(
        os.path.abspath(str(artifact_path))
    )

    existing_sha256 = seen_authority_paths.get(
        normalized_path_key
    )

    if (
        existing_sha256 is not None
        and existing_sha256 != declared_sha256
    ):
        raise Notebook10FinalAcceptancePersistenceError(
            "One retained physical path has conflicting hashes.\n"
            f"Path: {artifact_path}\n"
            f"First SHA-256: {existing_sha256}\n"
            f"Second SHA-256: {declared_sha256}"
        )

    if existing_sha256 is not None:
        raise Notebook10FinalAcceptancePersistenceError(
            "The physical carryover catalogue contains a duplicate "
            "retained path.\n"
            f"Path: {artifact_path}"
        )

    seen_authority_paths[
        normalized_path_key
    ] = declared_sha256

    deletion_safe_records.append(
        {
            "authority_scope": (
                "IMMUTABLE_V00_RETAINED_AUTHORITY"
                if authority_root_label == "V0.0"
                else "V01_UPSTREAM_RETAINED_AUTHORITY"
            ),
            "authority_root": authority_root_label,
            "artifact_origin": "UPSTREAM_PHYSICAL_CATALOGUE",
            "artifact_role": (
                None
                if "artifact_role" not in row.index
                or pd.isna(row.get("artifact_role"))
                else str(row.get("artifact_role"))
            ),
            "variable_name": (
                None
                if "variable_name" not in row.index
                or pd.isna(row.get("variable_name"))
                else str(row.get("variable_name"))
            ),
            "source_stage_numbers": (
                None
                if carryover_stage_column is None
                else finalization_plain_value(
                    row[carryover_stage_column]
                )
            ),
            "path": str(artifact_path),
            "relative_path_within_authority_root": (
                finalization_relative_path(
                    artifact_path,
                    authority_root_path,
                )
            ),
            "sha256": declared_sha256,
            "size_bytes": declared_size_bytes,
            "protected_partition_reference": bool(
                protected_reference
            ),
            "verification_basis": (
                "PRIOR_PHYSICAL_HASH_VERIFICATION_HASH_ONLY_REFERENCE"
                if protected_reference
                else "PRIOR_PHYSICAL_HASH_VERIFICATION_AND_CURRENT_SIZE_CHECK"
            ),
            "v02_carryover_class": (
                None
                if carryover_class_column is None
                or pd.isna(row[carryover_class_column])
                else str(row[carryover_class_column])
            ),
            "v02_use_mode": (
                None
                if carryover_use_mode_column is None
                or pd.isna(row[carryover_use_mode_column])
                else str(row[carryover_use_mode_column])
            ),
            "retention_required": True,
            "source_file_deletion_authorized": False,
            "active_notebook_dependency": False,
            "status": (
                "PASS_HASH_ONLY_RETAINED"
                if protected_reference
                else "PASS_RETAINED"
            ),
        }
    )


# ------------------------------------------------------------
# Add all persisted Notebook 10 artifacts
# ------------------------------------------------------------

notebook10_registry = (
    NOTEBOOK10_PERSISTED_ARTIFACT_REGISTRY.copy(
        deep=True
    )
)

required_notebook10_registry_columns = {
    "artifact_type",
    "artifact_role",
    "variable_name",
    "path",
    "format",
    "sha256",
    "size_bytes",
    "status",
}

missing_notebook10_registry_columns = sorted(
    required_notebook10_registry_columns
    - set(notebook10_registry.columns)
)

if missing_notebook10_registry_columns:
    raise Notebook10FinalAcceptancePersistenceError(
        "Notebook 10 persisted-artifact registry lacks required "
        f"columns: {missing_notebook10_registry_columns}"
    )


for row in notebook10_registry.itertuples(index=False):
    artifact_path = finalization_require_inside_root(
        finalization_normalized_path(row.path),
        FINALIZATION_V01_ROOT,
        role=str(row.variable_name),
        root_label="V0.1",
    )

    if not artifact_path.is_file():
        raise Notebook10FinalAcceptancePersistenceError(
            "A persisted Notebook 10 artifact is missing.\n"
            f"Variable: {row.variable_name}\n"
            f"Path: {artifact_path}"
        )

    declared_sha256 = str(row.sha256).strip().lower()

    observed_sha256 = finalization_sha256_file(
        artifact_path
    )

    if observed_sha256 != declared_sha256:
        raise Notebook10FinalAcceptancePersistenceError(
            "A persisted Notebook 10 artifact changed after "
            "semantic readback.\n"
            f"Variable: {row.variable_name}\n"
            f"Observed: {observed_sha256}\n"
            f"Declared: {declared_sha256}"
        )

    observed_size_bytes = int(
        artifact_path.stat().st_size
    )

    declared_size_bytes = int(row.size_bytes)

    if observed_size_bytes != declared_size_bytes:
        raise Notebook10FinalAcceptancePersistenceError(
            "A persisted Notebook 10 artifact size changed.\n"
            f"Variable: {row.variable_name}\n"
            f"Observed: {observed_size_bytes}\n"
            f"Declared: {declared_size_bytes}"
        )

    normalized_path_key = os.path.normcase(
        os.path.abspath(str(artifact_path))
    )

    existing_sha256 = seen_authority_paths.get(
        normalized_path_key
    )

    if existing_sha256 is not None:
        if existing_sha256 != declared_sha256:
            raise Notebook10FinalAcceptancePersistenceError(
                "Notebook 10 and upstream authorities register "
                "one path with conflicting hashes.\n"
                f"Path: {artifact_path}"
            )

        raise Notebook10FinalAcceptancePersistenceError(
            "Notebook 10 and upstream authorities unexpectedly "
            "register the same physical path.\n"
            f"Path: {artifact_path}"
        )

    seen_authority_paths[
        normalized_path_key
    ] = declared_sha256

    deletion_safe_records.append(
        {
            "authority_scope": "V01_NOTEBOOK10_RETAINED_AUTHORITY",
            "authority_root": "V0.1",
            "artifact_origin": "NOTEBOOK10_PERSISTED_REGISTRY",
            "artifact_role": str(row.artifact_role),
            "variable_name": str(row.variable_name),
            "source_stage_numbers": ["10"],
            "path": str(artifact_path),
            "relative_path_within_authority_root": (
                finalization_relative_path(
                    artifact_path,
                    FINALIZATION_V01_ROOT,
                )
            ),
            "sha256": declared_sha256,
            "size_bytes": declared_size_bytes,
            "protected_partition_reference": False,
            "verification_basis": (
                "NOTEBOOK10_PHYSICAL_AND_SEMANTIC_READBACK"
            ),
            "v02_carryover_class": (
                "NOTEBOOK10_FINAL_AUDIT_AUTHORITY"
            ),
            "v02_use_mode": (
                "AUDIT_PROVENANCE_AND_BOOTSTRAP_REFERENCE"
            ),
            "retention_required": True,
            "source_file_deletion_authorized": False,
            "active_notebook_dependency": False,
            "status": "PASS_RETAINED",
        }
    )


V01_DELETION_SAFE_AUTHORITY_INDEX = (
    pd.DataFrame(deletion_safe_records)
    .sort_values(
        [
            "authority_scope",
            "authority_root",
            "path",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

V01_DELETION_SAFE_AUTHORITY_INDEX.insert(
    0,
    "record_order",
    np.arange(
        1,
        len(V01_DELETION_SAFE_AUTHORITY_INDEX) + 1,
        dtype=np.int64,
    ),
)


if V01_DELETION_SAFE_AUTHORITY_INDEX[
    "path"
].duplicated().any():
    raise Notebook10FinalAcceptancePersistenceError(
        "The deletion-safe authority index contains duplicate paths."
    )

if not V01_DELETION_SAFE_AUTHORITY_INDEX[
    "retention_required"
].eq(True).all():
    raise Notebook10FinalAcceptancePersistenceError(
        "Every deletion-safe authority must be retained."
    )

if V01_DELETION_SAFE_AUTHORITY_INDEX[
    "source_file_deletion_authorized"
].eq(True).any():
    raise Notebook10FinalAcceptancePersistenceError(
        "The deletion-safe index incorrectly authorizes deletion "
        "of retained authority files."
    )


# ------------------------------------------------------------
# Deletion-safe scope summaries
# ------------------------------------------------------------

V01_DELETION_SAFE_AUTHORITY_SCOPE_SUMMARY = (
    V01_DELETION_SAFE_AUTHORITY_INDEX.groupby(
        [
            "authority_scope",
            "authority_root",
            "verification_basis",
        ],
        dropna=False,
        sort=True,
    )
    .agg(
        file_count=("path", "size"),
        total_size_bytes=("size_bytes", "sum"),
        protected_reference_count=(
            "protected_partition_reference",
            "sum",
        ),
    )
    .reset_index()
)


v00_retained_file_count = int(
    V01_DELETION_SAFE_AUTHORITY_INDEX[
        "authority_root"
    ].eq("V0.0").sum()
)

v01_retained_file_count = int(
    V01_DELETION_SAFE_AUTHORITY_INDEX[
        "authority_root"
    ].eq("V0.1").sum()
)

notebook10_retained_file_count = int(
    V01_DELETION_SAFE_AUTHORITY_INDEX[
        "authority_scope"
    ].eq(
        "V01_NOTEBOOK10_RETAINED_AUTHORITY"
    ).sum()
)

protected_hash_only_count = int(
    V01_DELETION_SAFE_AUTHORITY_INDEX[
        "protected_partition_reference"
    ].eq(True).sum()
)


if v00_retained_file_count != 6:
    raise Notebook10FinalAcceptancePersistenceError(
        "Unexpected V0.0 retained-authority count.\n"
        f"Observed: {v00_retained_file_count}\n"
        "Expected: 6"
    )

if notebook10_retained_file_count != 13:
    raise Notebook10FinalAcceptancePersistenceError(
        "Unexpected Notebook 10 retained-authority count.\n"
        f"Observed: {notebook10_retained_file_count}\n"
        "Expected: 13"
    )

if protected_hash_only_count != 7:
    raise Notebook10FinalAcceptancePersistenceError(
        "Unexpected protected hash-only reference count.\n"
        f"Observed: {protected_hash_only_count}\n"
        "Expected: 7"
    )


# ------------------------------------------------------------
# Exact Notebook 00–09 deletion-candidate ledger
#
# This is a plan only. Nothing is deleted in this cell.
# ------------------------------------------------------------

NOTEBOOKS_00_TO_09: Final[
    tuple[tuple[str, str, str], ...]
] = (
    (
        "00",
        "00_V01_RUN_CONTRACT.ipynb",
        "COMPLETED_AUTHORITY_PERSISTED",
    ),
    (
        "01",
        "01_RAW_DATA_AUDIT.ipynb",
        "COMPLETED_AUTHORITY_PERSISTED",
    ),
    (
        "02",
        "02_VISIBLE_BOOK_RECONSTRUCTION.ipynb",
        "COMPLETED_AUTHORITY_PERSISTED",
    ),
    (
        "03",
        "03_CAUSAL_TRADE_BOOK_ALIGNMENT.ipynb",
        "COMPLETED_AUTHORITY_PERSISTED",
    ),
    (
        "04",
        "04_EVENT_STREAM_CONSTRUCTION.ipynb",
        "COMPLETED_AUTHORITY_PERSISTED",
    ),
    (
        "05",
        "05_MARKET_STATE_FEATURES.ipynb",
        "COMPLETED_AUTHORITY_PERSISTED",
    ),
    (
        "06",
        "06_POINT_PROCESS_BASELINES.ipynb",
        "COMPLETED_AUTHORITY_PERSISTED",
    ),
    (
        "07",
        "07_HAWKES_ESTIMATION.ipynb",
        "COMPLETED_AUTHORITY_PERSISTED",
    ),
    (
        "08",
        "08_HAWKES_DIAGNOSTICS.ipynb",
        "COMPLETED_SCIENTIFIC_FAILURE_PERSISTED",
    ),
    (
        "09",
        "09_INTENSITY_SIGNAL_VALIDATION.ipynb",
        "SKIPPED_NOT_PASSED_NO_AUTHORITY_CREATED",
    ),
)


notebook_deletion_candidate_records: list[
    dict[str, Any]
] = []

for (
    stage_number,
    notebook_filename,
    stage_disposition,
) in NOTEBOOKS_00_TO_09:
    notebook_path = finalization_require_inside_root(
        FINALIZATION_V01_ROOT
        / "notebooks"
        / notebook_filename,
        FINALIZATION_V01_ROOT,
        role=f"NOTEBOOK_{stage_number}_DELETION_CANDIDATE",
        root_label="V0.1",
    )

    notebook_exists = notebook_path.is_file()

    notebook_deletion_candidate_records.append(
        {
            "stage_number": stage_number,
            "notebook_filename": notebook_filename,
            "path": str(notebook_path),
            "currently_exists": notebook_exists,
            "current_size_bytes": (
                int(notebook_path.stat().st_size)
                if notebook_exists
                else None
            ),
            "stage_disposition": stage_disposition,
            "authoritative_outputs_preserved": True,
            "active_runtime_dependency_remaining": False,
            "deletion_authorized": False,
            "authorization_condition": (
                "FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED"
            ),
            "deletion_performed": False,
            "status": (
                "READY_PENDING_FINAL_READBACK"
            ),
        }
    )


V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER = (
    pd.DataFrame(
        notebook_deletion_candidate_records
    )
)


if len(
    V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER
) != 10:
    raise Notebook10FinalAcceptancePersistenceError(
        "The deletion-candidate ledger must contain exactly "
        "Notebooks 00–09."
    )

if V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER[
    "deletion_authorized"
].eq(True).any():
    raise Notebook10FinalAcceptancePersistenceError(
        "Notebook deletion was authorized before final readback."
    )

if V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER[
    "deletion_performed"
].eq(True).any():
    raise Notebook10FinalAcceptancePersistenceError(
        "A notebook was marked deleted before final readback."
    )


# ------------------------------------------------------------
# Prepare finalized persisted decision and V0.2 handoff
# ------------------------------------------------------------

persisted_final_decision = dict(
    finalization_plain_value(
        V01_FINAL_DECISION_FINALIZED
    )
)

persisted_final_decision.pop(
    "payload_sha256",
    None,
)

persisted_final_decision[
    "pipeline_closeout_status"
] = "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"

persisted_final_decision[
    "notebook10_final_acceptance_persisted"
] = True

persisted_final_decision[
    "deletion_safe_authority_index_persisted"
] = True

persisted_final_decision[
    "active_notebook_deletion_authorized"
] = False

persisted_final_decision[
    "retained_authority_file_count"
] = int(
    len(V01_DELETION_SAFE_AUTHORITY_INDEX)
)

persisted_final_decision[
    "v0_0_retained_authority_file_count"
] = v00_retained_file_count

persisted_final_decision[
    "v0_1_retained_authority_file_count"
] = v01_retained_file_count

persisted_final_decision[
    "protected_hash_only_reference_count"
] = protected_hash_only_count

persisted_final_decision[
    "notebook_deletion_candidate_count"
] = 10

persisted_final_decision[
    "next_authorized_operation"
] = (
    "VERIFY_FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK"
)

persisted_final_decision = finalization_payload_with_hash(
    persisted_final_decision
)


persisted_v02_handoff = dict(
    finalization_plain_value(
        V02_BOOTSTRAP_HANDOFF_FINALIZED
    )
)

persisted_v02_handoff.pop(
    "payload_sha256",
    None,
)

persisted_v02_handoff[
    "status"
] = (
    "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK_BOOTSTRAP_ONLY"
)

persisted_v02_handoff[
    "notebook10_final_acceptance_persisted"
] = True

persisted_v02_handoff[
    "active_notebook_deletion_authorized"
] = False

persisted_v02_handoff[
    "retained_authority_file_count"
] = int(
    len(V01_DELETION_SAFE_AUTHORITY_INDEX)
)

persisted_v02_handoff[
    "next_authorized_operation"
] = (
    "VERIFY_FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK"
)

persisted_v02_handoff = finalization_payload_with_hash(
    persisted_v02_handoff
)


# ------------------------------------------------------------
# Build final-acceptance authority
# ------------------------------------------------------------

V01_NOTEBOOK10_FINAL_ACCEPTANCE = {
    "artifact_type": "NOTEBOOK_10_FINAL_ACCEPTANCE",
    "schema_version": "NOTEBOOK_10_FINAL_ACCEPTANCE_V1",
    "producer": (
        "10_V01_FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF.ipynb"
    ),
    "created_utc": persisted_final_decision.get(
        "created_utc"
    ),
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": EXPECTED_TERMINAL_STATUS,
    "pipeline_closeout_class": "PASS",
    "pipeline_closeout_status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"
    ),
    "selected_model_id": EXPECTED_SELECTED_MODEL_ID,
    "selected_model_disposition": (
        "REJECTED_DIAGNOSTIC_REFERENCE_ONLY"
    ),
    "failed_blocking_gates": sorted(
        EXPECTED_FAILED_ADEQUACY_GATES
    ),
    "count_score_superiority_supported": True,
    "full_model_adequacy_supported": False,
    "full_hawkes_superiority_supported": False,
    "notebook09_executed": False,
    "notebook09_authorized": False,
    "notebook09_status": "SKIPPED_NOT_PASSED",
    "completion_standard_met_count": 23,
    "completion_standard_unmet_count": 5,
    "completion_standard_fully_met": False,
    "v0_2_handoff_scope": EXPECTED_V02_HANDOFF_SCOPE,
    "v0_2_bootstrap_handoff_complete": True,
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "retained_authority_file_count": int(
        len(V01_DELETION_SAFE_AUTHORITY_INDEX)
    ),
    "v0_0_retained_authority_file_count": (
        v00_retained_file_count
    ),
    "v0_1_retained_authority_file_count": (
        v01_retained_file_count
    ),
    "notebook10_retained_authority_file_count": (
        notebook10_retained_file_count
    ),
    "protected_hash_only_reference_count": (
        protected_hash_only_count
    ),
    "notebook_deletion_candidate_count": 10,
    "deletion_safe_authority_index_created": True,
    "active_notebook_deletion_authorized": False,
    "deletion_performed": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "next_authorized_operation": (
        "VERIFY_FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK"
    ),
    "status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"
    ),
}

V01_NOTEBOOK10_FINAL_ACCEPTANCE = (
    finalization_payload_with_hash(
        V01_NOTEBOOK10_FINAL_ACCEPTANCE
    )
)


# ------------------------------------------------------------
# Build deletion-safe JSON authority
# ------------------------------------------------------------

V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD = {
    "artifact_type": (
        "V01_DELETION_SAFE_AUTHORITY_INDEX"
    ),
    "schema_version": (
        "V01_DELETION_SAFE_AUTHORITY_INDEX_V1"
    ),
    "producer": (
        "10_V01_FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF.ipynb"
    ),
    "created_utc": persisted_final_decision.get(
        "created_utc"
    ),
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "retained_authority_file_count": int(
        len(V01_DELETION_SAFE_AUTHORITY_INDEX)
    ),
    "v0_0_retained_authority_file_count": (
        v00_retained_file_count
    ),
    "v0_1_retained_authority_file_count": (
        v01_retained_file_count
    ),
    "notebook10_retained_authority_file_count": (
        notebook10_retained_file_count
    ),
    "protected_hash_only_reference_count": (
        protected_hash_only_count
    ),
    "active_notebook_dependency_count": 0,
    "source_file_deletion_authorized_count": 0,
    "active_notebook_deletion_authorized": False,
    "records": [
        {
            str(column_name): finalization_plain_value(
                getattr(row, column_name)
            )
            for column_name in (
                V01_DELETION_SAFE_AUTHORITY_INDEX.columns
            )
        }
        for row in (
            V01_DELETION_SAFE_AUTHORITY_INDEX.itertuples(
                index=False,
                name="DeletionSafeRecord",
            )
        )
    ],
    "notebook_deletion_candidates": [
        {
            str(column_name): finalization_plain_value(
                getattr(row, column_name)
            )
            for column_name in (
                V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER.columns
            )
        }
        for row in (
            V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER.itertuples(
                index=False,
                name="NotebookDeletionCandidate",
            )
        )
    ],
    "next_authorized_operation": (
        "VERIFY_FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK"
    ),
    "status": (
        "PASS_PERSISTED_AWAITING_READBACK"
    ),
}

V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD = (
    finalization_payload_with_hash(
        V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD
    )
)


# ------------------------------------------------------------
# Finalization output paths
# ------------------------------------------------------------

FINALIZATION_STAGE_SLUG: Final[str] = (
    "10_v01_final_acceptance_and_deletion_safe_index"
)

FINALIZATION_OUTPUT_PREFIX: Final[str] = (
    f"{NOTEBOOK10_OUTPUT_PREFIX}__final_acceptance"
)

NOTEBOOK10_FINALIZATION_TABLE_ROOT: Final[Path] = (
    FINALIZATION_V01_ROOT
    / "artifacts"
    / "audit_tables"
    / FINALIZATION_STAGE_SLUG
)

NOTEBOOK10_FINALIZED_DECISION_PATH: Final[Path] = (
    finalization_normalized_path(V01_MANIFEST_ROOT)
    / (
        f"{FINALIZATION_OUTPUT_PREFIX}"
        "__v01_final_decision_finalized.json"
    )
)

NOTEBOOK10_FINALIZED_V02_HANDOFF_PATH: Final[Path] = (
    finalization_normalized_path(V01_HANDOFF_ROOT)
    / (
        f"{FINALIZATION_OUTPUT_PREFIX}"
        "__v01_to_v02_bootstrap_handoff_finalized.json"
    )
)

NOTEBOOK10_FINAL_ACCEPTANCE_PATH: Final[Path] = (
    finalization_normalized_path(V01_MANIFEST_ROOT)
    / (
        f"{FINALIZATION_OUTPUT_PREFIX}"
        "__v01_final_acceptance.json"
    )
)

NOTEBOOK10_DELETION_SAFE_INDEX_PATH: Final[Path] = (
    finalization_normalized_path(V01_MANIFEST_ROOT)
    / (
        f"{FINALIZATION_OUTPUT_PREFIX}"
        "__v01_deletion_safe_authority_index.json"
    )
)

NOTEBOOK10_FINALIZATION_MANIFEST_PATH: Final[Path] = (
    finalization_normalized_path(V01_MANIFEST_ROOT)
    / (
        f"{FINALIZATION_OUTPUT_PREFIX}"
        "__notebook10_finalization_manifest.json"
    )
)

NOTEBOOK10_FINALIZATION_MANIFEST_SHA256_PATH: Final[Path] = (
    NOTEBOOK10_FINALIZATION_MANIFEST_PATH.with_suffix(
        NOTEBOOK10_FINALIZATION_MANIFEST_PATH.suffix
        + ".sha256"
    )
)


for output_role, output_path in (
    (
        "FINALIZATION_TABLE_ROOT",
        NOTEBOOK10_FINALIZATION_TABLE_ROOT,
    ),
    (
        "FINALIZED_DECISION",
        NOTEBOOK10_FINALIZED_DECISION_PATH,
    ),
    (
        "FINALIZED_V02_HANDOFF",
        NOTEBOOK10_FINALIZED_V02_HANDOFF_PATH,
    ),
    (
        "FINAL_ACCEPTANCE",
        NOTEBOOK10_FINAL_ACCEPTANCE_PATH,
    ),
    (
        "DELETION_SAFE_INDEX",
        NOTEBOOK10_DELETION_SAFE_INDEX_PATH,
    ),
    (
        "FINALIZATION_MANIFEST",
        NOTEBOOK10_FINALIZATION_MANIFEST_PATH,
    ),
    (
        "FINALIZATION_MANIFEST_SHA256",
        NOTEBOOK10_FINALIZATION_MANIFEST_SHA256_PATH,
    ),
):
    finalization_require_inside_root(
        output_path,
        FINALIZATION_V01_ROOT,
        role=output_role,
        root_label="V0.1",
    )


# ------------------------------------------------------------
# Tables to persist
# ------------------------------------------------------------

FINALIZATION_TABLES_TO_PERSIST: Final[
    dict[str, pd.DataFrame]
] = {
    "V01_COMPLETION_STANDARD_FINALIZED_AUDIT": (
        V01_COMPLETION_STANDARD_FINALIZED_AUDIT.copy(
            deep=True
        )
    ),
    "V01_FINAL_STAGE_DISPOSITION_FINALIZED": (
        V01_FINAL_STAGE_DISPOSITION_FINALIZED.copy(
            deep=True
        )
    ),
    "V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT": (
        V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT.copy(
            deep=True
        )
    ),
    "V01_NOTEBOOK10_ARTIFACT_READBACK_AUDIT": (
        V01_NOTEBOOK10_ARTIFACT_READBACK_AUDIT.copy(
            deep=True
        )
    ),
    "V01_DELETION_SAFE_AUTHORITY_INDEX": (
        V01_DELETION_SAFE_AUTHORITY_INDEX.copy(
            deep=True
        )
    ),
    "V01_DELETION_SAFE_AUTHORITY_SCOPE_SUMMARY": (
        V01_DELETION_SAFE_AUTHORITY_SCOPE_SUMMARY.copy(
            deep=True
        )
    ),
    "V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER": (
        V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER.copy(
            deep=True
        )
    ),
}


# ------------------------------------------------------------
# Persist finalization tables
# ------------------------------------------------------------

finalization_artifact_records: list[
    dict[str, Any]
] = []

for variable_name, dataframe in (
    FINALIZATION_TABLES_TO_PERSIST.items()
):
    artifact_slug = re.sub(
        r"[^a-z0-9]+",
        "_",
        variable_name.casefold(),
    ).strip("_")

    output_path = (
        NOTEBOOK10_FINALIZATION_TABLE_ROOT
        / (
            f"{FINALIZATION_OUTPUT_PREFIX}"
            f"__{artifact_slug}.csv.gz"
        )
    )

    (
        compressed_bytes,
        raw_csv_sha256,
    ) = finalization_dataframe_bytes(
        dataframe
    )

    write_result = finalization_atomic_write_exact(
        output_path,
        compressed_bytes,
        role=variable_name,
    )

    finalization_artifact_records.append(
        {
            "artifact_type": (
                "NOTEBOOK_10_FINALIZATION_AUDIT_TABLE"
            ),
            "artifact_role": artifact_slug,
            "variable_name": variable_name,
            "path": str(write_result["path"]),
            "relative_path": finalization_relative_path(
                write_result["path"],
                FINALIZATION_V01_ROOT,
            ),
            "format": "CSV_GZIP",
            "row_count": int(len(dataframe)),
            "column_count": int(dataframe.shape[1]),
            "columns": list(map(str, dataframe.columns)),
            "dtypes": {
                str(column_name): str(dtype)
                for column_name, dtype in dataframe.dtypes.items()
            },
            "uncompressed_csv_sha256": raw_csv_sha256,
            "sha256": write_result["sha256"],
            "size_bytes": int(
                write_result["size_bytes"]
            ),
            "write_action": write_result["write_action"],
            "status": "PASS_PERSISTED",
        }
    )


# ------------------------------------------------------------
# Persist finalized JSON authorities
# ------------------------------------------------------------

for (
    variable_name,
    artifact_type,
    artifact_role,
    output_path,
    payload,
) in (
    (
        "V01_FINAL_DECISION_FINAL_ACCEPTANCE_PERSISTED",
        "NOTEBOOK_10_FINALIZED_DECISION",
        "v01_final_decision_finalized",
        NOTEBOOK10_FINALIZED_DECISION_PATH,
        persisted_final_decision,
    ),
    (
        "V02_BOOTSTRAP_HANDOFF_FINAL_ACCEPTANCE_PERSISTED",
        "NOTEBOOK_10_FINALIZED_V02_HANDOFF",
        "v01_to_v02_bootstrap_handoff_finalized",
        NOTEBOOK10_FINALIZED_V02_HANDOFF_PATH,
        persisted_v02_handoff,
    ),
    (
        "V01_NOTEBOOK10_FINAL_ACCEPTANCE",
        "NOTEBOOK_10_FINAL_ACCEPTANCE",
        "v01_final_acceptance",
        NOTEBOOK10_FINAL_ACCEPTANCE_PATH,
        V01_NOTEBOOK10_FINAL_ACCEPTANCE,
    ),
    (
        "V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD",
        "NOTEBOOK_10_DELETION_SAFE_AUTHORITY_INDEX",
        "v01_deletion_safe_authority_index",
        NOTEBOOK10_DELETION_SAFE_INDEX_PATH,
        V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD,
    ),
):
    write_result = finalization_atomic_write_exact(
        output_path,
        finalization_json_bytes(payload),
        role=variable_name,
    )

    finalization_artifact_records.append(
        {
            "artifact_type": artifact_type,
            "artifact_role": artifact_role,
            "variable_name": variable_name,
            "path": str(write_result["path"]),
            "relative_path": finalization_relative_path(
                write_result["path"],
                FINALIZATION_V01_ROOT,
            ),
            "format": "JSON",
            "semantic_sha256": payload[
                "payload_sha256"
            ],
            "sha256": write_result["sha256"],
            "size_bytes": int(
                write_result["size_bytes"]
            ),
            "write_action": write_result["write_action"],
            "status": "PASS_PERSISTED",
        }
    )


# ------------------------------------------------------------
# Construct finalization manifest
# ------------------------------------------------------------

NOTEBOOK10_FINALIZATION_MANIFEST = {
    "artifact_type": (
        "NOTEBOOK_10_FINALIZATION_MANIFEST"
    ),
    "schema_version": (
        "NOTEBOOK_10_FINALIZATION_MANIFEST_V1"
    ),
    "producer": (
        "10_V01_FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF.ipynb"
    ),
    "created_utc": persisted_final_decision.get(
        "created_utc"
    ),
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": EXPECTED_TERMINAL_STATUS,
    "pipeline_closeout_class": "PASS",
    "pipeline_closeout_status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"
    ),
    "artifact_count_excluding_manifest_and_sidecar": int(
        len(finalization_artifact_records)
    ),
    "artifacts": finalization_artifact_records,
    "retained_authority_file_count": int(
        len(V01_DELETION_SAFE_AUTHORITY_INDEX)
    ),
    "v0_0_retained_authority_file_count": (
        v00_retained_file_count
    ),
    "v0_1_retained_authority_file_count": (
        v01_retained_file_count
    ),
    "notebook10_retained_authority_file_count": (
        notebook10_retained_file_count
    ),
    "protected_hash_only_reference_count": (
        protected_hash_only_count
    ),
    "notebook_deletion_candidate_count": 10,
    "active_notebook_deletion_authorized": False,
    "deletion_performed": False,
    "notebook09_executed": False,
    "notebook09_authorized": False,
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "next_authorized_operation": (
        "VERIFY_FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK"
    ),
    "status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"
    ),
}

NOTEBOOK10_FINALIZATION_MANIFEST = (
    finalization_payload_with_hash(
        NOTEBOOK10_FINALIZATION_MANIFEST,
        hash_field="manifest_payload_sha256",
    )
)


# ------------------------------------------------------------
# Persist finalization manifest and sidecar last
# ------------------------------------------------------------

finalization_manifest_write_result = (
    finalization_atomic_write_exact(
        NOTEBOOK10_FINALIZATION_MANIFEST_PATH,
        finalization_json_bytes(
            NOTEBOOK10_FINALIZATION_MANIFEST
        ),
        role="NOTEBOOK10_FINALIZATION_MANIFEST",
    )
)

finalization_sidecar_text = (
    f"{finalization_manifest_write_result['sha256']}  "
    f"{NOTEBOOK10_FINALIZATION_MANIFEST_PATH.name}\n"
)

finalization_sidecar_write_result = (
    finalization_atomic_write_exact(
        NOTEBOOK10_FINALIZATION_MANIFEST_SHA256_PATH,
        finalization_sidecar_text.encode("utf-8"),
        role="NOTEBOOK10_FINALIZATION_MANIFEST_SHA256",
    )
)


# ------------------------------------------------------------
# Complete persisted-artifact registry
# ------------------------------------------------------------

complete_finalization_records = list(
    finalization_artifact_records
)

complete_finalization_records.extend(
    [
        {
            "artifact_type": (
                "NOTEBOOK_10_FINALIZATION_MANIFEST"
            ),
            "artifact_role": (
                "notebook10_finalization_manifest"
            ),
            "variable_name": (
                "NOTEBOOK10_FINALIZATION_MANIFEST"
            ),
            "path": str(
                finalization_manifest_write_result["path"]
            ),
            "relative_path": finalization_relative_path(
                finalization_manifest_write_result["path"],
                FINALIZATION_V01_ROOT,
            ),
            "format": "JSON",
            "semantic_sha256": (
                NOTEBOOK10_FINALIZATION_MANIFEST[
                    "manifest_payload_sha256"
                ]
            ),
            "sha256": (
                finalization_manifest_write_result["sha256"]
            ),
            "size_bytes": int(
                finalization_manifest_write_result[
                    "size_bytes"
                ]
            ),
            "write_action": (
                finalization_manifest_write_result[
                    "write_action"
                ]
            ),
            "status": "PASS_PERSISTED",
        },
        {
            "artifact_type": (
                "NOTEBOOK_10_FINALIZATION_MANIFEST_SHA256_SIDECAR"
            ),
            "artifact_role": (
                "notebook10_finalization_manifest_sha256"
            ),
            "variable_name": (
                "NOTEBOOK10_FINALIZATION_MANIFEST_SHA256"
            ),
            "path": str(
                finalization_sidecar_write_result["path"]
            ),
            "relative_path": finalization_relative_path(
                finalization_sidecar_write_result["path"],
                FINALIZATION_V01_ROOT,
            ),
            "format": "SHA256_SIDECAR",
            "sha256": (
                finalization_sidecar_write_result["sha256"]
            ),
            "size_bytes": int(
                finalization_sidecar_write_result[
                    "size_bytes"
                ]
            ),
            "write_action": (
                finalization_sidecar_write_result[
                    "write_action"
                ]
            ),
            "status": "PASS_PERSISTED",
        },
    ]
)


NOTEBOOK10_FINALIZATION_PERSISTED_ARTIFACT_REGISTRY = (
    pd.DataFrame(complete_finalization_records)
    .sort_values(
        [
            "artifact_type",
            "variable_name",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)


if NOTEBOOK10_FINALIZATION_PERSISTED_ARTIFACT_REGISTRY[
    "path"
].duplicated().any():
    raise Notebook10FinalAcceptancePersistenceError(
        "The finalization registry contains duplicate paths."
    )

if not NOTEBOOK10_FINALIZATION_PERSISTED_ARTIFACT_REGISTRY[
    "status"
].eq("PASS_PERSISTED").all():
    raise Notebook10FinalAcceptancePersistenceError(
        "At least one finalization artifact lacks PASS_PERSISTED."
    )


# ------------------------------------------------------------
# Immediate physical verification
# ------------------------------------------------------------

for persisted_row in (
    NOTEBOOK10_FINALIZATION_PERSISTED_ARTIFACT_REGISTRY.itertuples(
        index=False
    )
):
    persisted_path = finalization_require_inside_root(
        finalization_normalized_path(
            persisted_row.path
        ),
        FINALIZATION_V01_ROOT,
        role=str(persisted_row.variable_name),
        root_label="V0.1",
    )

    if not persisted_path.is_file():
        raise Notebook10FinalAcceptancePersistenceError(
            "A registered finalization artifact is missing:\n"
            f"{persisted_path}"
        )

    observed_sha256 = finalization_sha256_file(
        persisted_path
    )

    if observed_sha256 != str(
        persisted_row.sha256
    ):
        raise Notebook10FinalAcceptancePersistenceError(
            "Immediate finalization hash verification failed.\n"
            f"Variable: {persisted_row.variable_name}\n"
            f"Observed: {observed_sha256}\n"
            f"Expected: {persisted_row.sha256}"
        )


# ------------------------------------------------------------
# Finalization summary
# ------------------------------------------------------------

NOTEBOOK10_FINAL_ACCEPTANCE_PERSISTENCE_SUMMARY = (
    pd.DataFrame(
        [
            {
                "metric": "scientific_terminal_class",
                "value": "FAIL",
            },
            {
                "metric": "pipeline_closeout_class",
                "value": "PASS",
            },
            {
                "metric": "finalization_audit_table_count",
                "value": int(
                    len(FINALIZATION_TABLES_TO_PERSIST)
                ),
            },
            {
                "metric": "finalization_json_authority_count",
                "value": 4,
            },
            {
                "metric": "finalization_manifest_count",
                "value": 1,
            },
            {
                "metric": "finalization_sidecar_count",
                "value": 1,
            },
            {
                "metric": "total_finalization_artifact_count",
                "value": int(
                    len(
                        NOTEBOOK10_FINALIZATION_PERSISTED_ARTIFACT_REGISTRY
                    )
                ),
            },
            {
                "metric": "retained_authority_file_count",
                "value": int(
                    len(V01_DELETION_SAFE_AUTHORITY_INDEX)
                ),
            },
            {
                "metric": "v0_0_retained_authority_file_count",
                "value": v00_retained_file_count,
            },
            {
                "metric": "v0_1_retained_authority_file_count",
                "value": v01_retained_file_count,
            },
            {
                "metric": "notebook10_retained_authority_file_count",
                "value": notebook10_retained_file_count,
            },
            {
                "metric": "protected_hash_only_reference_count",
                "value": protected_hash_only_count,
            },
            {
                "metric": "notebook_deletion_candidate_count",
                "value": 10,
            },
            {
                "metric": "active_notebook_deletion_authorized",
                "value": False,
            },
            {
                "metric": "deletion_performed",
                "value": False,
            },
            {
                "metric": "finalization_manifest_path",
                "value": str(
                    NOTEBOOK10_FINALIZATION_MANIFEST_PATH
                ),
            },
            {
                "metric": "finalization_manifest_file_sha256",
                "value": (
                    finalization_manifest_write_result[
                        "sha256"
                    ]
                ),
            },
            {
                "metric": "finalization_manifest_payload_sha256",
                "value": (
                    NOTEBOOK10_FINALIZATION_MANIFEST[
                        "manifest_payload_sha256"
                    ]
                ),
            },
            {
                "metric": "final_acceptance_payload_sha256",
                "value": (
                    V01_NOTEBOOK10_FINAL_ACCEPTANCE[
                        "payload_sha256"
                    ]
                ),
            },
            {
                "metric": "deletion_safe_index_payload_sha256",
                "value": (
                    V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD[
                        "payload_sha256"
                    ]
                ),
            },
            {
                "metric": "validation_content_loaded",
                "value": False,
            },
            {
                "metric": "engineering_holdout_content_loaded",
                "value": False,
            },
            {
                "metric": "finalization_readback_verified",
                "value": False,
            },
        ]
    )
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    NOTEBOOK10_FINAL_ACCEPTANCE_PERSISTENCE_SUMMARY
)

display(
    V01_DELETION_SAFE_AUTHORITY_SCOPE_SUMMARY
)

display(
    V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER
)

display(
    NOTEBOOK10_FINALIZATION_PERSISTED_ARTIFACT_REGISTRY[
        [
            "artifact_type",
            "artifact_role",
            "variable_name",
            "format",
            "path",
            "row_count",
            "column_count",
            "size_bytes",
            "sha256",
            "write_action",
            "status",
        ]
    ]
)


# ------------------------------------------------------------
# Freeze finalization persistence authority
# ------------------------------------------------------------

FROZEN_NOTEBOOK10_FINALIZATION_PERSISTENCE_AUTHORITY = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": EXPECTED_TERMINAL_STATUS,
    "pipeline_closeout_class": "PASS",
    "pipeline_closeout_status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"
    ),
    "finalization_manifest_path": str(
        NOTEBOOK10_FINALIZATION_MANIFEST_PATH
    ),
    "finalization_manifest_file_sha256": (
        finalization_manifest_write_result[
            "sha256"
        ]
    ),
    "finalization_manifest_semantic_sha256": (
        NOTEBOOK10_FINALIZATION_MANIFEST[
            "manifest_payload_sha256"
        ]
    ),
    "finalization_manifest_sidecar_path": str(
        NOTEBOOK10_FINALIZATION_MANIFEST_SHA256_PATH
    ),
    "final_acceptance_path": str(
        NOTEBOOK10_FINAL_ACCEPTANCE_PATH
    ),
    "final_acceptance_semantic_sha256": (
        V01_NOTEBOOK10_FINAL_ACCEPTANCE[
            "payload_sha256"
        ]
    ),
    "deletion_safe_index_path": str(
        NOTEBOOK10_DELETION_SAFE_INDEX_PATH
    ),
    "deletion_safe_index_semantic_sha256": (
        V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD[
            "payload_sha256"
        ]
    ),
    "finalized_decision_path": str(
        NOTEBOOK10_FINALIZED_DECISION_PATH
    ),
    "finalized_decision_semantic_sha256": (
        persisted_final_decision[
            "payload_sha256"
        ]
    ),
    "finalized_v02_handoff_path": str(
        NOTEBOOK10_FINALIZED_V02_HANDOFF_PATH
    ),
    "finalized_v02_handoff_semantic_sha256": (
        persisted_v02_handoff[
            "payload_sha256"
        ]
    ),
    "finalization_artifact_count": int(
        len(
            NOTEBOOK10_FINALIZATION_PERSISTED_ARTIFACT_REGISTRY
        )
    ),
    "retained_authority_file_count": int(
        len(V01_DELETION_SAFE_AUTHORITY_INDEX)
    ),
    "v0_0_retained_authority_file_count": (
        v00_retained_file_count
    ),
    "v0_1_retained_authority_file_count": (
        v01_retained_file_count
    ),
    "notebook10_retained_authority_file_count": (
        notebook10_retained_file_count
    ),
    "protected_hash_only_reference_count": (
        protected_hash_only_count
    ),
    "notebook_deletion_candidate_count": 10,
    "active_notebook_deletion_authorized": False,
    "deletion_performed": False,
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "next_authorized_operation": (
        "VERIFY_FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK"
    ),
}


# ------------------------------------------------------------
# Update in-memory authority bindings
# ------------------------------------------------------------

V01_FINAL_DECISION_FINAL_ACCEPTANCE_PERSISTED = (
    persisted_final_decision
)

V02_BOOTSTRAP_HANDOFF_FINAL_ACCEPTANCE_PERSISTED = (
    persisted_v02_handoff
)


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

V01_FINAL_ACCEPTANCE_PERSISTED = True
V01_DELETION_SAFE_INDEX_PERSISTED = True
NOTEBOOK10_FINALIZATION_MANIFEST_PERSISTED = True
NOTEBOOK10_FINALIZATION_PHYSICAL_PERSISTENCE_VERIFIED = True

V01_FINAL_ACCEPTANCE_READBACK_VERIFIED = False
V01_DELETION_SAFE_INDEX_READBACK_VERIFIED = False
NOTEBOOK10_FINALIZATION_MANIFEST_READBACK_VERIFIED = False
NOTEBOOK10_FINALIZATION_READBACK_VERIFIED = False

V01_ACTIVE_NOTEBOOK_DELETION_AUTHORIZED = False
V01_NOTEBOOKS_00_TO_09_DELETION_AUTHORIZED = False
V01_NOTEBOOKS_00_TO_09_DELETION_PERFORMED = False

UPSTREAM_ARTIFACTS_VERIFIED = True

V01_MODEL_SIGNAL_AUTHORIZATION_GRANTED = False
V01_STRATEGY_AUTHORIZATION_GRANTED = False
V01_V02_MODEL_HANDOFF_AUTHORIZED = False

NOTEBOOK09_EXECUTED = False
NOTEBOOK09_AUTHORIZED = False

VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False
PROTECTED_PARTITION_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0

print(
    "Notebook 10 final-acceptance persistence: PASS. The "
    "finalized decision, bootstrap-only V0.2 handoff, final "
    "acceptance, deletion-safe authority index, seven finalization "
    "audit tables, finalization manifest, and physical SHA-256 "
    "sidecar were persisted under V0.1. Retained V0.0 files were "
    "validated against the V0.0 authority root rather than being "
    "incorrectly treated as V0.1 outputs. The deletion-safe index "
    f"contains {len(V01_DELETION_SAFE_AUTHORITY_INDEX)} retained "
    "physical authorities, including six V0.0 files, thirteen "
    "Notebook 10 artifacts, and seven protected hash-only "
    "references. Notebooks 00–09 are recorded as deletion "
    "candidates, but deletion remains unauthorized until final "
    "readback passes. The scientific terminal state remains FAIL, "
    "while the audit closeout remains PASS. No model, signal, "
    "strategy, or accepted V0.2 model handoff was authorized. "
    "VALIDATION and ENGINEERING_HOLDOUT remain unopened."
)

,metric,value
0,scientific_terminal_class,FAIL
1,pipeline_closeout_class,PASS
2,finalization_audit_table_count,7
3,finalization_json_authority_count,4
4,finalization_manifest_count,1
5,finalization_sidecar_count,1
6,total_finalization_artifact_count,13
7,retained_authority_file_count,453
8,v0_0_retained_authority_file_count,6
9,v0_1_retained_authority_file_count,447
10,notebook10_retained_authority_file_count,13
11,protected_hash_only_reference_count,7
12,notebook_deletion_candidate_count,10
13,active_notebook_deletion_authorized,False
14,deletion_performed,False
15,finalization_manifest_path,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...
16,finalization_manifest_file_sha256,37ac538b23acd00dc7d7a6ac72e616594ac34071ba9ff2dd847a563f11c7082f
17,finalization_manifest_payload_sha256,7f83da64ff0df11979b0b10b8a2e3414cf3879f6de7188131b94d97341e17efb
18,final_acceptance_payload_sha256,94ae02f4020d778ade394e519fd75a52d41cce17fa00669bfeafde034bc5f38d
19,deletion_safe_index_payload_sha256,034e5384721e9740371d6f9210dcb6219d7c92eca32804436104b31bca73f694
20,validation_content_loaded,False
21,engineering_holdout_content_loaded,False
22,finalization_readback_verified,False

                     authority_scope authority_root                                       verification_basis  file_count  total_size_bytes  protected_reference_count
0   IMMUTABLE_V00_RETAINED_AUTHORITY           V0.0  PRIOR_PHYSICAL_HASH_VERIFICATION_AND_CURRENT_SIZE_CHECK           6         114848029                          0
1  V01_NOTEBOOK10_RETAINED_AUTHORITY           V0.1                NOTEBOOK10_PHYSICAL_AND_SEMANTIC_READBACK          13             85853                          0
2    V01_UPSTREAM_RETAINED_AUTHORITY           V0.1  PRIOR_PHYSICAL_HASH_VERIFICATION_AND_CURRENT_SIZE_CHECK         427         688806851                          0
3    V01_UPSTREAM_RETAINED_AUTHORITY           V0.1     PRIOR_PHYSICAL_HASH_VERIFICATION_HASH_ONLY_REFERENCE           7             18515                          7

,stage_number,notebook_filename,path,currently_exists,current_size_bytes,stage_disposition,authoritative_outputs_preserved,active_runtime_dependency_remaining,deletion_authorized,authorization_condition,deletion_performed,status
0,00,00_V01_RUN_CONTRACT.ipynb,D:\Clown Project\V0.1\Notebooks\00_V01_RUN_CONTRACT.ipynb,True,"2,259,244",COMPLETED_AUTHORITY_PERSISTED,True,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,False,READY_PENDING_FINAL_READBACK
1,01,01_RAW_DATA_AUDIT.ipynb,D:\Clown Project\V0.1\Notebooks\01_RAW_DATA_AUDIT.ipynb,False,NaN,COMPLETED_AUTHORITY_PERSISTED,True,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,False,READY_PENDING_FINAL_READBACK
2,02,02_VISIBLE_BOOK_RECONSTRUCTION.ipynb,D:\Clown Project\V0.1\Notebooks\02_VISIBLE_BOOK_RECONSTRUCTION.ipynb,True,"861,102",COMPLETED_AUTHORITY_PERSISTED,True,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,False,READY_PENDING_FINAL_READBACK
3,03,03_CAUSAL_TRADE_BOOK_ALIGNMENT.ipynb,D:\Clown Project\V0.1\Notebooks\03_CAUSAL_TRADE_BOOK_ALIGNMENT.ipynb,True,"895,207",COMPLETED_AUTHORITY_PERSISTED,True,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,False,READY_PENDING_FINAL_READBACK
4,04,04_EVENT_STREAM_CONSTRUCTION.ipynb,D:\Clown Project\V0.1\Notebooks\04_EVENT_STREAM_CONSTRUCTION.ipynb,True,"1,479,152",COMPLETED_AUTHORITY_PERSISTED,True,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,False,READY_PENDING_FINAL_READBACK
5,05,05_MARKET_STATE_FEATURES.ipynb,D:\Clown Project\V0.1\Notebooks\05_MARKET_STATE_FEATURES.ipynb,True,"2,333,805",COMPLETED_AUTHORITY_PERSISTED,True,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,False,READY_PENDING_FINAL_READBACK
6,06,06_POINT_PROCESS_BASELINES.ipynb,D:\Clown Project\V0.1\Notebooks\06_POINT_PROCESS_BASELINES.ipynb,True,"2,745,272",COMPLETED_AUTHORITY_PERSISTED,True,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,False,READY_PENDING_FINAL_READBACK
7,07,07_HAWKES_ESTIMATION.ipynb,D:\Clown Project\V0.1\Notebooks\07_HAWKES_ESTIMATION.ipynb,True,"1,658,028",COMPLETED_AUTHORITY_PERSISTED,True,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,False,READY_PENDING_FINAL_READBACK
8,08,08_HAWKES_DIAGNOSTICS.ipynb,D:\Clown Project\V0.1\Notebooks\08_HAWKES_DIAGNOSTICS.ipynb,True,"1,996,257",COMPLETED_SCIENTIFIC_FAILURE_PERSISTED,True,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,False,READY_PENDING_FINAL_READBACK
9,09,09_INTENSITY_SIGNAL_VALIDATION.ipynb,D:\Clown Project\V0.1\Notebooks\09_INTENSITY_SIGNAL_VALIDATION.ipynb,False,NaN,SKIPPED_NOT_PASSED_NO_AUTHORITY_CREATED,True,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,False,READY_PENDING_FINAL_READBACK

,artifact_type,artifact_role,variable_name,format,path,row_count,column_count,size_bytes,sha256,write_action,status
0,NOTEBOOK_10_DELETION_SAFE_AUTHORITY_INDEX,v01_deletion_safe_authority_index,V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD,JSON,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,NaN,NaN,549431,c944ddd3185dfcf6a7e1fd2d334d9db35be7f7177c0c72388265a24ac84a9e0c,CREATED_ATOMICALLY,PASS_PERSISTED
1,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_completion_standard_finalized_audit,V01_COMPLETION_STANDARD_FINALIZED_AUDIT,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,28,5,1612,b6e661b8a94d721556771903045766d92ee0f7e3bd55ae772457e11e8461cf74,CREATED_ATOMICALLY,PASS_PERSISTED
2,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_deletion_safe_authority_index,V01_DELETION_SAFE_AUTHORITY_INDEX,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,453,19,30730,4e80da817054dc9e3673fa3097ebeedfe281b889c7d2a8f705ec4a6ee9d96b7e,CREATED_ATOMICALLY,PASS_PERSISTED
3,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_deletion_safe_authority_scope_summary,V01_DELETION_SAFE_AUTHORITY_SCOPE_SUMMARY,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,4,6,282,0a134b32ec6cb53c11381fd138e21f0ebf42d77af1c15b92b6cc8f863a52a042,CREATED_ATOMICALLY,PASS_PERSISTED
4,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_final_stage_disposition_finalized,V01_FINAL_STAGE_DISPOSITION_FINALIZED,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,11,8,679,2b75fa6160fda90fae6cf2d296d583da19e26c94b825177f139dc5fcf4fe4c43,CREATED_ATOMICALLY,PASS_PERSISTED
5,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_notebook10_artifact_readback_audit,V01_NOTEBOOK10_ARTIFACT_READBACK_AUDIT,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,11,15,1289,7e69087dd78d92ab33c4d58c549bd9a57883a7c7f75bbc6e762d83653dcf2648,CREATED_ATOMICALLY,PASS_PERSISTED
6,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_notebook10_semantic_readback_audit,V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,104,8,2243,e0100c06e965c93daae56628ce1de61fef540bb432188dc5e84f6edc209c9dbf,CREATED_ATOMICALLY,PASS_PERSISTED
7,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_notebook_00_to_09_deletion_candidate_ledger,V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER,CSV_GZIP,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,10,12,643,3cef7cfaf393e075d0165f682ed6f6536b6ea44d06ede6fbc0fe4eb2deda86b9,CREATED_ATOMICALLY,PASS_PERSISTED
8,NOTEBOOK_10_FINALIZATION_MANIFEST,notebook10_finalization_manifest,NOTEBOOK10_FINALIZATION_MANIFEST,JSON,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,NaN,NaN,18927,37ac538b23acd00dc7d7a6ac72e616594ac34071ba9ff2dd847a563f11c7082f,CREATED_ATOMICALLY,PASS_PERSISTED
9,NOTEBOOK_10_FINALIZATION_MANIFEST_SHA256_SIDECAR,notebook10_finalization_manifest_sha256,NOTEBOOK10_FINALIZATION_MANIFEST_SHA256,SHA256_SIDECAR,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,NaN,NaN,244,6308686b7506fb68f6995a6a14e6b2cc451fa774a090cae2c1c122d0d24bcddb,CREATED_ATOMICALLY,PASS_PERSISTED
10,NOTEBOOK_10_FINALIZED_DECISION,v01_final_decision_finalized,V01_FINAL_DECISION_FINAL_ACCEPTANCE_PERSISTED,JSON,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,NaN,NaN,2487,836fe40b19d43849e12ed92367b6d2351965f74b280c7031e8c8d83704180694,CREATED_ATOMICALLY,PASS_PERSISTED
11,NOTEBOOK_10_FINALIZED_V02_HANDOFF,v01_to_v02_bootstrap_handoff_finalized,V02_BOOTSTRAP_HANDOFF_FINAL_ACCEPTANCE_PERSISTED,JSON,D:\Clown Project\V0.1\artifacts\handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_han...,NaN,NaN,23351,9ce7c88c626526d0ce56b70aad5ab907b34da71bd3a3230fd84ab911b263a443,CREATED_ATOMICALLY,PASS_PERSISTED
12,NOTEBOOK_10_FINAL_ACCEPTANCE,v01_final_acceptance,V01_NOTEBOOK10_FINAL_ACCEPTANCE,JSON,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,NaN,NaN,2693,e68648071f601bed4a11993d0bc56a0c89e05d2e753fab8532954872044bfd5e,CREATED_ATOMICALLY,PASS_PERSISTED

Notebook 10 final-acceptance persistence: PASS. The finalized decision, bootstrap-only V0.2 handoff, final acceptance, deletion-safe authority index, seven finalization audit tables, finalization manifest, and physical SHA-256 sidecar were persisted under V0.1. Retained V0.0 files were validated against the V0.0 authority root rather than being incorrectly treated as V0.1 outputs. The deletion-safe index contains 453 retained physical authorities, including six V0.0 files, thirteen Notebook 10 artifacts, and seven protected hash-only references. Notebooks 00–09 are recorded as deletion candidates, but deletion remains unauthorized until final readback passes. The scientific terminal state remains FAIL, while the audit closeout remains PASS. No model, signal, strategy, or accepted V0.2 model handoff was authorized. VALIDATION and ENGINEERING_HOLDOUT remain unopened.

In [39]:
# ============================================================
# Notebook 10 finalization readback and notebook-deletion
# authorization
#
# This cell independently verifies:
# - finalization manifest physical SHA-256;
# - finalization-manifest sidecar;
# - finalization manifest semantic SHA-256;
# - all 11 registered finalization artifacts;
# - all seven persisted finalization tables;
# - all four persisted JSON authorities;
# - finalized terminal and V0.2 handoff semantics;
# - deletion-safe retained-authority index;
# - all 453 retained physical authorities;
# - exact Notebook 00–09 deletion-candidate boundary;
# - no deletion candidate is a retained authority;
# - no active notebook dependency remains.
#
# It authorizes deletion only for candidate notebooks that
# currently exist. Missing Notebooks 01 and 09 require no action.
#
# Nothing is deleted and no filesystem writes are performed.
#
# Important implementation detail:
# DataFrame rows are accessed by column key, never through
# itertuples attributes beginning with "_".
# ============================================================

from __future__ import annotations

import gzip
import hashlib
import json
import os
import re
from pathlib import Path
from typing import Any, Final, Mapping

import numpy as np
import pandas as pd
from IPython.display import display


class Notebook10FinalizationReadbackError(RuntimeError):
    """Raised when finalization readback cannot authorize deletion."""


# ------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------

REQUIRED_FINAL_READBACK_FLAGS: Final[dict[str, bool]] = {
    "UPSTREAM_ARTIFACTS_VERIFIED": bool(
        globals().get(
            "UPSTREAM_ARTIFACTS_VERIFIED",
            False,
        )
    ),
    "V01_FINAL_ACCEPTANCE_PERSISTED": bool(
        globals().get(
            "V01_FINAL_ACCEPTANCE_PERSISTED",
            False,
        )
    ),
    "V01_DELETION_SAFE_INDEX_PERSISTED": bool(
        globals().get(
            "V01_DELETION_SAFE_INDEX_PERSISTED",
            False,
        )
    ),
    "NOTEBOOK10_FINALIZATION_MANIFEST_PERSISTED": bool(
        globals().get(
            "NOTEBOOK10_FINALIZATION_MANIFEST_PERSISTED",
            False,
        )
    ),
    "NOTEBOOK10_FINALIZATION_PHYSICAL_PERSISTENCE_VERIFIED": bool(
        globals().get(
            "NOTEBOOK10_FINALIZATION_PHYSICAL_PERSISTENCE_VERIFIED",
            False,
        )
    ),
    "NOTEBOOK10_SEMANTIC_READBACK_VERIFIED": bool(
        globals().get(
            "NOTEBOOK10_SEMANTIC_READBACK_VERIFIED",
            False,
        )
    ),
}

failed_final_readback_flags = sorted(
    flag_name
    for flag_name, passed in REQUIRED_FINAL_READBACK_FLAGS.items()
    if not passed
)

if failed_final_readback_flags:
    raise Notebook10FinalizationReadbackError(
        "Notebook 10 finalization-readback prerequisites have "
        "not passed:\n"
        f"{failed_final_readback_flags}"
    )


REQUIRED_FINAL_READBACK_OBJECTS: Final[tuple[str, ...]] = (
    "V00_ROOT",
    "V01_ROOT",
    "SOURCE_RUN_PREFIX",
    "SOURCE_SET_SHA256",
    "V01_RUN_ID",
    "RUN_CONFIG_SHA256",
    "RUN_IDENTITY_SHA256",
    "FROZEN_NOTEBOOK10_FINALIZATION_PERSISTENCE_AUTHORITY",
)

missing_final_readback_objects = sorted(
    object_name
    for object_name in REQUIRED_FINAL_READBACK_OBJECTS
    if object_name not in globals()
)

if missing_final_readback_objects:
    raise Notebook10FinalizationReadbackError(
        "Required Notebook 10 finalization-readback objects are "
        "unavailable:\n"
        f"{missing_final_readback_objects}"
    )


if not isinstance(
    FROZEN_NOTEBOOK10_FINALIZATION_PERSISTENCE_AUTHORITY,
    Mapping,
):
    raise Notebook10FinalizationReadbackError(
        "FROZEN_NOTEBOOK10_FINALIZATION_PERSISTENCE_AUTHORITY "
        "must be a mapping."
    )


# ------------------------------------------------------------
# Runtime safety guards
# ------------------------------------------------------------

if bool(
    globals().get(
        "VALIDATION_CONTENT_LOADED",
        False,
    )
):
    raise Notebook10FinalizationReadbackError(
        "VALIDATION content was unexpectedly loaded."
    )

if bool(
    globals().get(
        "ENGINEERING_HOLDOUT_CONTENT_LOADED",
        False,
    )
):
    raise Notebook10FinalizationReadbackError(
        "ENGINEERING_HOLDOUT content was unexpectedly loaded."
    )


protected_runtime_state = globals().get(
    "PROTECTED_PARTITION_CONTENT_LOADED",
    False,
)

if isinstance(
    protected_runtime_state,
    Mapping,
):
    opened_protected_partitions = sorted(
        str(partition)
        for partition, loaded in protected_runtime_state.items()
        if bool(loaded)
    )

    if opened_protected_partitions:
        raise Notebook10FinalizationReadbackError(
            "Protected partition content was marked as loaded:\n"
            f"{opened_protected_partitions}"
        )

elif bool(protected_runtime_state):
    raise Notebook10FinalizationReadbackError(
        "Protected partition content was unexpectedly loaded."
    )


if bool(
    globals().get(
        "MODEL_REFIT_PERFORMED",
        False,
    )
):
    raise Notebook10FinalizationReadbackError(
        "A model refit was recorded before final readback."
    )

if bool(
    globals().get(
        "MODEL_REPLACEMENT_PERFORMED",
        False,
    )
):
    raise Notebook10FinalizationReadbackError(
        "A model replacement was recorded before final readback."
    )

if int(
    globals().get(
        "CALIBRATION_PARAMETER_UPDATES_PERFORMED",
        0,
    )
) != 0:
    raise Notebook10FinalizationReadbackError(
        "Nonzero CALIBRATION parameter updates were recorded."
    )


# ------------------------------------------------------------
# Frozen expected semantics
# ------------------------------------------------------------

EXPECTED_TERMINAL_STATUS: Final[str] = (
    "FAIL_HAWKES_DIAGNOSTIC_ADEQUACY_DESPITE_SCORE_SUPERIORITY"
)

EXPECTED_SELECTED_MODEL_ID: Final[str] = (
    "H1_DIAGONAL_SHARED_DECAY"
)

EXPECTED_V02_HANDOFF_SCOPE: Final[str] = (
    "BOOTSTRAP_AND_PROVENANCE_ONLY_NO_ACCEPTED_MODEL_SIGNAL_OR_STRATEGY"
)

EXPECTED_FAILED_ADEQUACY_GATES: Final[set[str]] = {
    "LOCKED_CALIBRATION_RESIDUAL_DISTRIBUTION",
    "LOCKED_CALIBRATION_RESIDUAL_SERIAL_DEPENDENCE",
    "LOCKED_CALIBRATION_PATH_COUNT_CALIBRATION",
    "LOCKED_CALIBRATION_EXACT_TIME_MULTIPLICITY",
}

EXPECTED_FINALIZATION_TABLE_VARIABLES: Final[set[str]] = {
    "V01_COMPLETION_STANDARD_FINALIZED_AUDIT",
    "V01_FINAL_STAGE_DISPOSITION_FINALIZED",
    "V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT",
    "V01_NOTEBOOK10_ARTIFACT_READBACK_AUDIT",
    "V01_DELETION_SAFE_AUTHORITY_INDEX",
    "V01_DELETION_SAFE_AUTHORITY_SCOPE_SUMMARY",
    "V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER",
}

EXPECTED_FINALIZATION_JSON_VARIABLES: Final[set[str]] = {
    "V01_FINAL_DECISION_FINAL_ACCEPTANCE_PERSISTED",
    "V02_BOOTSTRAP_HANDOFF_FINAL_ACCEPTANCE_PERSISTED",
    "V01_NOTEBOOK10_FINAL_ACCEPTANCE",
    "V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD",
}

EXPECTED_FINALIZATION_ARTIFACT_VARIABLES: Final[set[str]] = (
    EXPECTED_FINALIZATION_TABLE_VARIABLES
    | EXPECTED_FINALIZATION_JSON_VARIABLES
)


# ------------------------------------------------------------
# Path helpers
# ------------------------------------------------------------

def final_readback_normalized_path(
    value: Any,
) -> Path:
    """Return an absolute normalized path."""

    return Path(
        str(value)
    ).expanduser().resolve(
        strict=False
    )


FINAL_READBACK_V00_ROOT: Final[Path] = (
    final_readback_normalized_path(
        V00_ROOT
    )
)

FINAL_READBACK_V01_ROOT: Final[Path] = (
    final_readback_normalized_path(
        V01_ROOT
    )
)


def final_readback_path_is_inside(
    path: Path,
    root: Path,
) -> bool:
    """Return whether path lies inside root."""

    normalized_path_text = os.path.normcase(
        os.path.abspath(
            str(
                final_readback_normalized_path(
                    path
                )
            )
        )
    )

    normalized_root_text = os.path.normcase(
        os.path.abspath(
            str(
                final_readback_normalized_path(
                    root
                )
            )
        )
    )

    try:
        common_path = os.path.commonpath(
            [
                normalized_path_text,
                normalized_root_text,
            ]
        )

    except ValueError:
        return False

    return common_path == normalized_root_text


def final_readback_require_inside(
    path: Path,
    root: Path,
    *,
    role: str,
    root_label: str,
) -> Path:
    """Require one path under its declared authority root."""

    normalized_path = final_readback_normalized_path(
        path
    )

    normalized_root = final_readback_normalized_path(
        root
    )

    if not final_readback_path_is_inside(
        normalized_path,
        normalized_root,
    ):
        raise Notebook10FinalizationReadbackError(
            "A final-readback path lies outside its declared "
            "authority root.\n"
            f"Role: {role}\n"
            f"Authority root: {root_label}\n"
            f"Root path: {normalized_root}\n"
            f"Artifact path: {normalized_path}"
        )

    return normalized_path


def final_readback_authority_root(
    value: Any,
) -> tuple[str, Path]:
    """Resolve a deletion-safe authority-root label."""

    normalized_label = (
        str(value)
        .strip()
        .casefold()
        .replace("_", "")
        .replace(" ", "")
    )

    if normalized_label in {
        "v0.0",
        "v00",
        "v0",
    }:
        return (
            "V0.0",
            FINAL_READBACK_V00_ROOT,
        )

    if normalized_label in {
        "v0.1",
        "v01",
    }:
        return (
            "V0.1",
            FINAL_READBACK_V01_ROOT,
        )

    raise Notebook10FinalizationReadbackError(
        "Unknown authority-root label in deletion-safe index:\n"
        f"{value!r}"
    )


def final_readback_path_key(
    path: Path,
) -> str:
    """Return a normalized comparison key for one path."""

    return os.path.normcase(
        os.path.abspath(
            str(
                final_readback_normalized_path(
                    path
                )
            )
        )
    )


# ------------------------------------------------------------
# Hashing and canonical serialization helpers
# ------------------------------------------------------------

def final_readback_sha256_file(
    path: Path,
    *,
    chunk_size: int = 1 << 20,
) -> str:
    """Return the physical SHA-256 digest of one file."""

    digest = hashlib.sha256()

    with path.open(
        "rb"
    ) as input_stream:
        while True:
            chunk = input_stream.read(
                chunk_size
            )

            if not chunk:
                break

            digest.update(
                chunk
            )

    return digest.hexdigest()


def final_readback_sha256_bytes(
    payload_bytes: bytes,
) -> str:
    """Return the SHA-256 digest of bytes."""

    return hashlib.sha256(
        payload_bytes
    ).hexdigest()


def final_readback_plain_value(
    value: Any,
) -> Any:
    """Convert values into strict JSON-compatible Python types."""

    if value is None:
        return None

    if isinstance(
        value,
        Path,
    ):
        return str(value)

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(value)

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        return int(value)

    if isinstance(
        value,
        (float, np.floating),
    ):
        numeric_value = float(value)

        if not np.isfinite(
            numeric_value
        ):
            return str(numeric_value)

        return numeric_value

    if isinstance(
        value,
        pd.Timestamp,
    ):
        return value.isoformat()

    if isinstance(
        value,
        Mapping,
    ):
        return {
            str(key): final_readback_plain_value(child)
            for key, child in value.items()
        }

    if isinstance(
        value,
        (
            list,
            tuple,
            set,
        ),
    ):
        iterable = (
            sorted(value)
            if isinstance(value, set)
            else value
        )

        return [
            final_readback_plain_value(child)
            for child in iterable
        ]

    try:
        missing_value = pd.isna(value)

        if (
            isinstance(
                missing_value,
                (bool, np.bool_),
            )
            and bool(missing_value)
        ):
            return None

    except (
        TypeError,
        ValueError,
    ):
        pass

    return str(value)


def final_readback_canonical_sha256(
    payload: Mapping[str, Any],
) -> str:
    """Return a deterministic semantic SHA-256."""

    canonical_bytes = json.dumps(
        final_readback_plain_value(
            payload
        ),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode(
        "utf-8"
    )

    return final_readback_sha256_bytes(
        canonical_bytes
    )


def final_readback_semantic_sha256(
    payload: Mapping[str, Any],
    *,
    hash_field: str,
) -> str:
    """Recompute a non-self-referential semantic hash."""

    copied_payload = dict(
        final_readback_plain_value(
            payload
        )
    )

    copied_payload.pop(
        hash_field,
        None,
    )

    return final_readback_canonical_sha256(
        copied_payload
    )


def final_readback_boolean(
    value: Any,
) -> bool | None:
    """Normalize a persisted boolean-like value."""

    if value is None:
        return None

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(value)

    if isinstance(
        value,
        (int, np.integer),
    ) and not isinstance(
        value,
        bool,
    ):
        if int(value) in {
            0,
            1,
        }:
            return bool(
                int(value)
            )

    normalized = str(value).strip().casefold()

    if normalized in {
        "true",
        "t",
        "yes",
        "y",
        "1",
    }:
        return True

    if normalized in {
        "false",
        "f",
        "no",
        "n",
        "0",
        "",
        "none",
        "null",
        "nan",
    }:
        return False

    return None


def final_readback_render(
    value: Any,
) -> str:
    """Render deterministic audit values."""

    plain_value = final_readback_plain_value(
        value
    )

    if isinstance(
        plain_value,
        (
            dict,
            list,
        ),
    ):
        return json.dumps(
            plain_value,
            sort_keys=True,
            ensure_ascii=False,
            allow_nan=False,
        )

    return repr(
        plain_value
    )


def final_readback_first_present(
    payload: Mapping[str, Any],
    candidates: tuple[str, ...],
) -> Any:
    """Return the first present mapping value."""

    for candidate in candidates:
        if candidate in payload:
            return payload[
                candidate
            ]

    return None


# ------------------------------------------------------------
# Read finalization manifest and physical sidecar
# ------------------------------------------------------------

finalization_authority = (
    FROZEN_NOTEBOOK10_FINALIZATION_PERSISTENCE_AUTHORITY
)

finalization_manifest_path = (
    final_readback_require_inside(
        final_readback_normalized_path(
            finalization_authority[
                "finalization_manifest_path"
            ]
        ),
        FINAL_READBACK_V01_ROOT,
        role="NOTEBOOK10_FINALIZATION_MANIFEST",
        root_label="V0.1",
    )
)

finalization_sidecar_path = (
    final_readback_require_inside(
        final_readback_normalized_path(
            finalization_authority[
                "finalization_manifest_sidecar_path"
            ]
        ),
        FINAL_READBACK_V01_ROOT,
        role="NOTEBOOK10_FINALIZATION_MANIFEST_SHA256",
        root_label="V0.1",
    )
)


if not finalization_manifest_path.is_file():
    raise Notebook10FinalizationReadbackError(
        "The Notebook 10 finalization manifest is missing:\n"
        f"{finalization_manifest_path}"
    )

if not finalization_sidecar_path.is_file():
    raise Notebook10FinalizationReadbackError(
        "The Notebook 10 finalization-manifest sidecar is "
        "missing:\n"
        f"{finalization_sidecar_path}"
    )


observed_finalization_manifest_file_sha256 = (
    final_readback_sha256_file(
        finalization_manifest_path
    )
)

expected_finalization_manifest_file_sha256 = str(
    finalization_authority[
        "finalization_manifest_file_sha256"
    ]
).strip().lower()

if (
    observed_finalization_manifest_file_sha256
    != expected_finalization_manifest_file_sha256
):
    raise Notebook10FinalizationReadbackError(
        "Finalization-manifest physical SHA-256 mismatch.\n"
        f"Observed: {observed_finalization_manifest_file_sha256}\n"
        f"Expected: {expected_finalization_manifest_file_sha256}"
    )


finalization_sidecar_text = (
    finalization_sidecar_path.read_text(
        encoding="utf-8"
    )
)

finalization_sidecar_match = re.fullmatch(
    r"([0-9a-fA-F]{64})  ([^\r\n]+)\r?\n?",
    finalization_sidecar_text,
)

if finalization_sidecar_match is None:
    raise Notebook10FinalizationReadbackError(
        "The finalization-manifest sidecar has an invalid format."
    )

sidecar_declared_sha256 = (
    finalization_sidecar_match.group(
        1
    ).lower()
)

sidecar_declared_filename = (
    finalization_sidecar_match.group(
        2
    )
)

if (
    sidecar_declared_sha256
    != observed_finalization_manifest_file_sha256
):
    raise Notebook10FinalizationReadbackError(
        "The finalization-manifest sidecar SHA-256 does not "
        "match the manifest file."
    )

if (
    sidecar_declared_filename
    != finalization_manifest_path.name
):
    raise Notebook10FinalizationReadbackError(
        "The finalization-manifest sidecar references the wrong "
        "filename.\n"
        f"Observed: {sidecar_declared_filename}\n"
        f"Expected: {finalization_manifest_path.name}"
    )


with finalization_manifest_path.open(
    "r",
    encoding="utf-8",
) as manifest_stream:
    NOTEBOOK10_FINALIZATION_MANIFEST_READBACK = json.load(
        manifest_stream
    )

if not isinstance(
    NOTEBOOK10_FINALIZATION_MANIFEST_READBACK,
    dict,
):
    raise Notebook10FinalizationReadbackError(
        "The Notebook 10 finalization manifest is not a JSON "
        "object."
    )


declared_finalization_manifest_semantic_sha256 = str(
    NOTEBOOK10_FINALIZATION_MANIFEST_READBACK.get(
        "manifest_payload_sha256",
        "",
    )
).strip().lower()

observed_finalization_manifest_semantic_sha256 = (
    final_readback_semantic_sha256(
        NOTEBOOK10_FINALIZATION_MANIFEST_READBACK,
        hash_field="manifest_payload_sha256",
    )
)

expected_finalization_manifest_semantic_sha256 = str(
    finalization_authority[
        "finalization_manifest_semantic_sha256"
    ]
).strip().lower()


if (
    observed_finalization_manifest_semantic_sha256
    != declared_finalization_manifest_semantic_sha256
):
    raise Notebook10FinalizationReadbackError(
        "The finalization manifest fails its internal semantic "
        "SHA-256 check."
    )

if (
    declared_finalization_manifest_semantic_sha256
    != expected_finalization_manifest_semantic_sha256
):
    raise Notebook10FinalizationReadbackError(
        "The finalization-manifest semantic SHA-256 differs from "
        "the frozen persistence authority."
    )


# ------------------------------------------------------------
# Finalization-manifest identity checks
# ------------------------------------------------------------

EXPECTED_FINALIZATION_MANIFEST_FIELDS: Final[
    dict[str, Any]
] = {
    "artifact_type": (
        "NOTEBOOK_10_FINALIZATION_MANIFEST"
    ),
    "schema_version": (
        "NOTEBOOK_10_FINALIZATION_MANIFEST_V1"
    ),
    "producer": (
        "10_V01_FINAL_AUDIT_SYNTHESIS_AND_V02_HANDOFF.ipynb"
    ),
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": (
        EXPECTED_TERMINAL_STATUS
    ),
    "pipeline_closeout_class": "PASS",
    "pipeline_closeout_status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"
    ),
    "artifact_count_excluding_manifest_and_sidecar": 11,
    "retained_authority_file_count": 453,
    "v0_0_retained_authority_file_count": 6,
    "v0_1_retained_authority_file_count": 447,
    "notebook10_retained_authority_file_count": 13,
    "protected_hash_only_reference_count": 7,
    "notebook_deletion_candidate_count": 10,
    "active_notebook_deletion_authorized": False,
    "deletion_performed": False,
    "notebook09_executed": False,
    "notebook09_authorized": False,
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"
    ),
}

manifest_identity_failures: list[
    dict[str, Any]
] = []

for field_name, expected_value in (
    EXPECTED_FINALIZATION_MANIFEST_FIELDS.items()
):
    observed_value = (
        NOTEBOOK10_FINALIZATION_MANIFEST_READBACK.get(
            field_name
        )
    )

    if observed_value != expected_value:
        manifest_identity_failures.append(
            {
                "field": field_name,
                "observed": observed_value,
                "expected": expected_value,
            }
        )


V01_NOTEBOOK10_FINALIZATION_MANIFEST_IDENTITY_FAILURES = (
    pd.DataFrame(
        manifest_identity_failures,
        columns=[
            "field",
            "observed",
            "expected",
        ],
    )
)

if not V01_NOTEBOOK10_FINALIZATION_MANIFEST_IDENTITY_FAILURES.empty:
    raise Notebook10FinalizationReadbackError(
        "The finalization-manifest identity contract failed:\n"
        + V01_NOTEBOOK10_FINALIZATION_MANIFEST_IDENTITY_FAILURES.to_string(
            index=False
        )
    )


# ------------------------------------------------------------
# Resolve exact artifact records from the manifest
# ------------------------------------------------------------

manifest_artifact_records = (
    NOTEBOOK10_FINALIZATION_MANIFEST_READBACK.get(
        "artifacts"
    )
)

if not isinstance(
    manifest_artifact_records,
    list,
):
    raise Notebook10FinalizationReadbackError(
        "The finalization manifest lacks an artifacts list."
    )

if len(manifest_artifact_records) != 11:
    raise Notebook10FinalizationReadbackError(
        "The finalization manifest must register exactly 11 "
        "non-manifest artifacts."
    )


finalization_record_by_variable: dict[
    str,
    dict[str, Any],
] = {}

registered_finalization_path_keys: set[str] = set()


for artifact_record in manifest_artifact_records:
    if not isinstance(
        artifact_record,
        Mapping,
    ):
        raise Notebook10FinalizationReadbackError(
            "A finalization artifact record is not a mapping."
        )

    variable_name = str(
        artifact_record.get(
            "variable_name",
            "",
        )
    ).strip()

    if not variable_name:
        raise Notebook10FinalizationReadbackError(
            "A finalization artifact record lacks variable_name."
        )

    if variable_name in finalization_record_by_variable:
        raise Notebook10FinalizationReadbackError(
            "Duplicate finalization artifact variable:\n"
            f"{variable_name}"
        )

    artifact_path = final_readback_require_inside(
        final_readback_normalized_path(
            artifact_record.get(
                "path"
            )
        ),
        FINAL_READBACK_V01_ROOT,
        role=variable_name,
        root_label="V0.1",
    )

    artifact_path_key = final_readback_path_key(
        artifact_path
    )

    if artifact_path_key in registered_finalization_path_keys:
        raise Notebook10FinalizationReadbackError(
            "The finalization manifest registers one path more "
            "than once:\n"
            f"{artifact_path}"
        )

    registered_finalization_path_keys.add(
        artifact_path_key
    )

    normalized_record = dict(
        artifact_record
    )

    normalized_record[
        "_resolved_path"
    ] = artifact_path

    finalization_record_by_variable[
        variable_name
    ] = normalized_record


observed_finalization_variable_set = set(
    finalization_record_by_variable
)

if (
    observed_finalization_variable_set
    != EXPECTED_FINALIZATION_ARTIFACT_VARIABLES
):
    raise Notebook10FinalizationReadbackError(
        "The finalization artifact-variable set differs from the "
        "required set.\n"
        f"Missing: "
        f"{sorted(EXPECTED_FINALIZATION_ARTIFACT_VARIABLES - observed_finalization_variable_set)}\n"
        f"Unexpected: "
        f"{sorted(observed_finalization_variable_set - EXPECTED_FINALIZATION_ARTIFACT_VARIABLES)}"
    )


# ------------------------------------------------------------
# Reopen and verify all 11 finalization artifacts
# ------------------------------------------------------------

NOTEBOOK10_FINALIZATION_READBACK_TABLES: dict[
    str,
    pd.DataFrame,
] = {}

NOTEBOOK10_FINALIZATION_READBACK_JSON: dict[
    str,
    dict[str, Any],
] = {}

finalization_artifact_audit_records: list[
    dict[str, Any]
] = []


for variable_name in sorted(
    finalization_record_by_variable
):
    artifact_record = finalization_record_by_variable[
        variable_name
    ]

    artifact_path = artifact_record[
        "_resolved_path"
    ]

    if not artifact_path.is_file():
        raise Notebook10FinalizationReadbackError(
            "A registered finalization artifact is missing:\n"
            f"{artifact_path}"
        )

    observed_file_sha256 = final_readback_sha256_file(
        artifact_path
    )

    declared_file_sha256 = str(
        artifact_record.get(
            "sha256",
            "",
        )
    ).strip().lower()

    if observed_file_sha256 != declared_file_sha256:
        raise Notebook10FinalizationReadbackError(
            "Finalization artifact physical hash mismatch.\n"
            f"Variable: {variable_name}\n"
            f"Observed: {observed_file_sha256}\n"
            f"Declared: {declared_file_sha256}"
        )

    observed_size_bytes = int(
        artifact_path.stat().st_size
    )

    declared_size_bytes = int(
        artifact_record.get(
            "size_bytes"
        )
    )

    if observed_size_bytes != declared_size_bytes:
        raise Notebook10FinalizationReadbackError(
            "Finalization artifact size mismatch.\n"
            f"Variable: {variable_name}\n"
            f"Observed: {observed_size_bytes}\n"
            f"Declared: {declared_size_bytes}"
        )

    artifact_format = str(
        artifact_record.get(
            "format",
            "",
        )
    ).strip().upper()

    audit_record: dict[str, Any] = {
        "variable_name": variable_name,
        "artifact_type": str(
            artifact_record.get(
                "artifact_type",
                "",
            )
        ),
        "artifact_role": str(
            artifact_record.get(
                "artifact_role",
                "",
            )
        ),
        "path": str(
            artifact_path
        ),
        "format": artifact_format,
        "size_bytes": observed_size_bytes,
        "file_sha256": observed_file_sha256,
        "file_hash_matches": True,
        "size_matches": True,
        "semantic_hash_matches": None,
        "uncompressed_csv_hash_matches": None,
        "row_count_matches": None,
        "column_count_matches": None,
        "column_order_matches": None,
        "status": "PASS",
    }

    if artifact_format == "CSV_GZIP":
        compressed_bytes = artifact_path.read_bytes()

        try:
            uncompressed_csv_bytes = gzip.decompress(
                compressed_bytes
            )

        except OSError as exc:
            raise Notebook10FinalizationReadbackError(
                "Unable to decompress a finalization table.\n"
                f"Variable: {variable_name}"
            ) from exc

        observed_uncompressed_sha256 = (
            final_readback_sha256_bytes(
                uncompressed_csv_bytes
            )
        )

        declared_uncompressed_sha256 = str(
            artifact_record.get(
                "uncompressed_csv_sha256",
                "",
            )
        ).strip().lower()

        if (
            observed_uncompressed_sha256
            != declared_uncompressed_sha256
        ):
            raise Notebook10FinalizationReadbackError(
                "Finalization table uncompressed CSV hash "
                "mismatch.\n"
                f"Variable: {variable_name}"
            )

        readback_frame = pd.read_csv(
            artifact_path,
            compression="gzip",
            low_memory=False,
        )

        expected_row_count = int(
            artifact_record.get(
                "row_count"
            )
        )

        expected_column_count = int(
            artifact_record.get(
                "column_count"
            )
        )

        expected_columns = [
            str(column)
            for column in artifact_record.get(
                "columns",
                [],
            )
        ]

        observed_columns = list(
            map(
                str,
                readback_frame.columns,
            )
        )

        if len(readback_frame) != expected_row_count:
            raise Notebook10FinalizationReadbackError(
                "Finalization table row-count mismatch.\n"
                f"Variable: {variable_name}\n"
                f"Observed: {len(readback_frame)}\n"
                f"Expected: {expected_row_count}"
            )

        if readback_frame.shape[1] != expected_column_count:
            raise Notebook10FinalizationReadbackError(
                "Finalization table column-count mismatch.\n"
                f"Variable: {variable_name}"
            )

        if observed_columns != expected_columns:
            raise Notebook10FinalizationReadbackError(
                "Finalization table column-order mismatch.\n"
                f"Variable: {variable_name}"
            )

        NOTEBOOK10_FINALIZATION_READBACK_TABLES[
            variable_name
        ] = readback_frame.copy(
            deep=True
        )

        audit_record.update(
            {
                "uncompressed_csv_hash_matches": True,
                "row_count_matches": True,
                "column_count_matches": True,
                "column_order_matches": True,
            }
        )

    elif artifact_format == "JSON":
        with artifact_path.open(
            "r",
            encoding="utf-8",
        ) as json_stream:
            readback_payload = json.load(
                json_stream
            )

        if not isinstance(
            readback_payload,
            dict,
        ):
            raise Notebook10FinalizationReadbackError(
                "A finalization JSON artifact is not an object.\n"
                f"Variable: {variable_name}"
            )

        declared_payload_sha256 = str(
            readback_payload.get(
                "payload_sha256",
                "",
            )
        ).strip().lower()

        observed_payload_sha256 = (
            final_readback_semantic_sha256(
                readback_payload,
                hash_field="payload_sha256",
            )
        )

        manifest_payload_sha256 = str(
            artifact_record.get(
                "semantic_sha256",
                "",
            )
        ).strip().lower()

        if (
            observed_payload_sha256
            != declared_payload_sha256
        ):
            raise Notebook10FinalizationReadbackError(
                "A finalization JSON artifact fails its internal "
                "semantic hash.\n"
                f"Variable: {variable_name}"
            )

        if (
            declared_payload_sha256
            != manifest_payload_sha256
        ):
            raise Notebook10FinalizationReadbackError(
                "A finalization JSON semantic hash differs from "
                "the finalization manifest.\n"
                f"Variable: {variable_name}"
            )

        NOTEBOOK10_FINALIZATION_READBACK_JSON[
            variable_name
        ] = dict(
            readback_payload
        )

        audit_record[
            "semantic_hash_matches"
        ] = True

    else:
        raise Notebook10FinalizationReadbackError(
            "Unexpected finalization artifact format.\n"
            f"Variable: {variable_name}\n"
            f"Format: {artifact_format}"
        )

    finalization_artifact_audit_records.append(
        audit_record
    )


V01_NOTEBOOK10_FINALIZATION_ARTIFACT_READBACK_AUDIT = (
    pd.DataFrame(
        finalization_artifact_audit_records
    )
    .sort_values(
        "variable_name",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


# ------------------------------------------------------------
# Bind readback authorities
# ------------------------------------------------------------

final_decision_readback = (
    NOTEBOOK10_FINALIZATION_READBACK_JSON[
        "V01_FINAL_DECISION_FINAL_ACCEPTANCE_PERSISTED"
    ]
)

v02_handoff_readback = (
    NOTEBOOK10_FINALIZATION_READBACK_JSON[
        "V02_BOOTSTRAP_HANDOFF_FINAL_ACCEPTANCE_PERSISTED"
    ]
)

final_acceptance_readback = (
    NOTEBOOK10_FINALIZATION_READBACK_JSON[
        "V01_NOTEBOOK10_FINAL_ACCEPTANCE"
    ]
)

deletion_safe_payload_readback = (
    NOTEBOOK10_FINALIZATION_READBACK_JSON[
        "V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD"
    ]
)

completion_audit_readback = (
    NOTEBOOK10_FINALIZATION_READBACK_TABLES[
        "V01_COMPLETION_STANDARD_FINALIZED_AUDIT"
    ].copy(
        deep=True
    )
)

stage_disposition_readback = (
    NOTEBOOK10_FINALIZATION_READBACK_TABLES[
        "V01_FINAL_STAGE_DISPOSITION_FINALIZED"
    ].copy(
        deep=True
    )
)

deletion_safe_index_readback = (
    NOTEBOOK10_FINALIZATION_READBACK_TABLES[
        "V01_DELETION_SAFE_AUTHORITY_INDEX"
    ].copy(
        deep=True
    )
)

deletion_safe_scope_summary_readback = (
    NOTEBOOK10_FINALIZATION_READBACK_TABLES[
        "V01_DELETION_SAFE_AUTHORITY_SCOPE_SUMMARY"
    ].copy(
        deep=True
    )
)

candidate_ledger_readback = (
    NOTEBOOK10_FINALIZATION_READBACK_TABLES[
        "V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER"
    ].copy(
        deep=True
    )
)


# ------------------------------------------------------------
# Semantic-check machinery
# ------------------------------------------------------------

final_readback_checks: list[
    dict[str, Any]
] = []


def register_final_readback_check(
    *,
    category: str,
    check_name: str,
    observed: Any,
    expected: Any,
    passed: bool | None = None,
    blocking: bool = True,
) -> None:
    """Register one finalization-readback check."""

    check_passed = (
        observed == expected
        if passed is None
        else bool(passed)
    )

    final_readback_checks.append(
        {
            "check_order": int(
                len(final_readback_checks) + 1
            ),
            "category": category,
            "check_name": check_name,
            "blocking": bool(blocking),
            "passed": bool(check_passed),
            "status": (
                "PASS"
                if check_passed
                else (
                    "FAIL"
                    if blocking
                    else "WARNING"
                )
            ),
            "observed": final_readback_render(
                observed
            ),
            "expected": final_readback_render(
                expected
            ),
        }
    )


# ------------------------------------------------------------
# Final acceptance semantics
# ------------------------------------------------------------

EXPECTED_FINAL_ACCEPTANCE_FIELDS: Final[
    dict[str, Any]
] = {
    "artifact_type": (
        "NOTEBOOK_10_FINAL_ACCEPTANCE"
    ),
    "schema_version": (
        "NOTEBOOK_10_FINAL_ACCEPTANCE_V1"
    ),
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": (
        EXPECTED_TERMINAL_STATUS
    ),
    "pipeline_closeout_class": "PASS",
    "pipeline_closeout_status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"
    ),
    "selected_model_id": (
        EXPECTED_SELECTED_MODEL_ID
    ),
    "selected_model_disposition": (
        "REJECTED_DIAGNOSTIC_REFERENCE_ONLY"
    ),
    "count_score_superiority_supported": True,
    "full_model_adequacy_supported": False,
    "full_hawkes_superiority_supported": False,
    "notebook09_executed": False,
    "notebook09_authorized": False,
    "notebook09_status": (
        "SKIPPED_NOT_PASSED"
    ),
    "completion_standard_met_count": 23,
    "completion_standard_unmet_count": 5,
    "completion_standard_fully_met": False,
    "v0_2_handoff_scope": (
        EXPECTED_V02_HANDOFF_SCOPE
    ),
    "v0_2_bootstrap_handoff_complete": True,
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "retained_authority_file_count": 453,
    "v0_0_retained_authority_file_count": 6,
    "v0_1_retained_authority_file_count": 447,
    "notebook10_retained_authority_file_count": 13,
    "protected_hash_only_reference_count": 7,
    "notebook_deletion_candidate_count": 10,
    "deletion_safe_authority_index_created": True,
    "active_notebook_deletion_authorized": False,
    "deletion_performed": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"
    ),
}

for field_name, expected_value in (
    EXPECTED_FINAL_ACCEPTANCE_FIELDS.items()
):
    register_final_readback_check(
        category="FINAL_ACCEPTANCE",
        check_name=field_name,
        observed=final_acceptance_readback.get(
            field_name
        ),
        expected=expected_value,
    )


register_final_readback_check(
    category="FINAL_ACCEPTANCE",
    check_name="failed_blocking_gate_set",
    observed=set(
        final_acceptance_readback.get(
            "failed_blocking_gates",
            [],
        )
    ),
    expected=EXPECTED_FAILED_ADEQUACY_GATES,
)


# ------------------------------------------------------------
# Finalized decision semantics
# ------------------------------------------------------------

EXPECTED_FINAL_DECISION_FIELDS: Final[
    dict[str, Any]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": (
        EXPECTED_TERMINAL_STATUS
    ),
    "pipeline_closeout_status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK"
    ),
    "full_model_adequacy_supported": False,
    "full_hawkes_superiority_supported": False,
    "notebook10_final_acceptance_persisted": True,
    "deletion_safe_authority_index_persisted": True,
    "active_notebook_deletion_authorized": False,
    "retained_authority_file_count": 453,
    "v0_0_retained_authority_file_count": 6,
    "v0_1_retained_authority_file_count": 447,
    "protected_hash_only_reference_count": 7,
    "notebook_deletion_candidate_count": 10,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
}

for field_name, expected_value in (
    EXPECTED_FINAL_DECISION_FIELDS.items()
):
    register_final_readback_check(
        category="FINAL_DECISION",
        check_name=field_name,
        observed=final_decision_readback.get(
            field_name
        ),
        expected=expected_value,
    )


final_decision_selected_model = (
    final_readback_first_present(
        final_decision_readback,
        (
            "selected_hawkes_model_id",
            "selected_model_id",
        ),
    )
)

register_final_readback_check(
    category="FINAL_DECISION",
    check_name="selected_model_id",
    observed=final_decision_selected_model,
    expected=EXPECTED_SELECTED_MODEL_ID,
)


# ------------------------------------------------------------
# V0.2 handoff semantics
# ------------------------------------------------------------

EXPECTED_V02_HANDOFF_FIELDS: Final[
    dict[str, Any]
] = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "handoff_scope": EXPECTED_V02_HANDOFF_SCOPE,
    "accepted_model_authorized": False,
    "accepted_signal_authorized": False,
    "strategy_authorized": False,
    "validation_result_available": False,
    "engineering_holdout_result_available": False,
    "notebook10_final_acceptance_persisted": True,
    "active_notebook_deletion_authorized": False,
    "retained_authority_file_count": 453,
    "status": (
        "PASS_FINAL_ACCEPTANCE_PERSISTED_AWAITING_READBACK_BOOTSTRAP_ONLY"
    ),
}

for field_name, expected_value in (
    EXPECTED_V02_HANDOFF_FIELDS.items()
):
    register_final_readback_check(
        category="V02_HANDOFF",
        check_name=field_name,
        observed=v02_handoff_readback.get(
            field_name
        ),
        expected=expected_value,
    )


v02_selected_model = v02_handoff_readback.get(
    "v0_1_selected_model",
    {},
)

if not isinstance(
    v02_selected_model,
    Mapping,
):
    v02_selected_model = {}

register_final_readback_check(
    category="V02_HANDOFF",
    check_name="selected_model_id",
    observed=v02_selected_model.get(
        "model_id"
    ),
    expected=EXPECTED_SELECTED_MODEL_ID,
)

register_final_readback_check(
    category="V02_HANDOFF",
    check_name="selected_model_full_adequacy",
    observed=v02_selected_model.get(
        "full_model_adequacy_supported"
    ),
    expected=False,
)


# ------------------------------------------------------------
# Completion and stage-closeout semantics
# ------------------------------------------------------------

completion_audit_readback[
    "_criterion_number"
] = pd.to_numeric(
    completion_audit_readback[
        "criterion_number"
    ],
    errors="raise",
).astype(
    int
)

completion_audit_readback[
    "_completion_met"
] = completion_audit_readback[
    "completion_met"
].map(
    final_readback_boolean
)

if completion_audit_readback[
    "_completion_met"
].isna().any():
    raise Notebook10FinalizationReadbackError(
        "Unable to normalize finalized completion flags."
    )


register_final_readback_check(
    category="COMPLETION_STANDARD",
    check_name="criterion_count",
    observed=int(
        len(completion_audit_readback)
    ),
    expected=28,
)

register_final_readback_check(
    category="COMPLETION_STANDARD",
    check_name="completion_met_count",
    observed=int(
        completion_audit_readback[
            "_completion_met"
        ].sum()
    ),
    expected=23,
)

register_final_readback_check(
    category="COMPLETION_STANDARD",
    check_name="completion_unmet_count",
    observed=int(
        (
            ~completion_audit_readback[
                "_completion_met"
            ]
        ).sum()
    ),
    expected=5,
)


criterion28_rows = completion_audit_readback.loc[
    completion_audit_readback[
        "_criterion_number"
    ].eq(
        28
    )
]

if len(criterion28_rows) != 1:
    raise Notebook10FinalizationReadbackError(
        "Criterion 28 does not have exactly one row."
    )

criterion28_row = criterion28_rows.iloc[
    0
]

register_final_readback_check(
    category="COMPLETION_STANDARD",
    check_name="criterion_28_outcome",
    observed=str(
        criterion28_row[
            "outcome"
        ]
    ),
    expected=(
        "PASS_SEMANTIC_READBACK_VERIFIED"
    ),
)

register_final_readback_check(
    category="COMPLETION_STANDARD",
    check_name="criterion_28_completion_met",
    observed=bool(
        criterion28_row[
            "_completion_met"
        ]
    ),
    expected=True,
)


stage_disposition_readback[
    "_stage_number"
] = (
    pd.to_numeric(
        stage_disposition_readback[
            "stage_number"
        ],
        errors="raise",
    )
    .astype(
        int
    )
)

register_final_readback_check(
    category="STAGE_DISPOSITION",
    check_name="stage_number_set",
    observed=set(
        stage_disposition_readback[
            "_stage_number"
        ]
    ),
    expected=set(
        range(
            0,
            11,
        )
    ),
)


stage08_rows = stage_disposition_readback.loc[
    stage_disposition_readback[
        "_stage_number"
    ].eq(
        8
    )
]

stage09_rows = stage_disposition_readback.loc[
    stage_disposition_readback[
        "_stage_number"
    ].eq(
        9
    )
]

stage10_rows = stage_disposition_readback.loc[
    stage_disposition_readback[
        "_stage_number"
    ].eq(
        10
    )
]

if (
    len(stage08_rows) != 1
    or len(stage09_rows) != 1
    or len(stage10_rows) != 1
):
    raise Notebook10FinalizationReadbackError(
        "Stages 08, 09, and 10 must each have exactly one row."
    )


stage08_row = stage08_rows.iloc[
    0
]

stage09_row = stage09_rows.iloc[
    0
]

stage10_row = stage10_rows.iloc[
    0
]


register_final_readback_check(
    category="STAGE_DISPOSITION",
    check_name="stage08_status",
    observed=str(
        stage08_row[
            "status"
        ]
    ),
    expected="FAIL_SCIENTIFIC",
)

register_final_readback_check(
    category="STAGE_DISPOSITION",
    check_name="stage09_status",
    observed=str(
        stage09_row[
            "status"
        ]
    ),
    expected="SKIPPED_NOT_PASSED",
)

register_final_readback_check(
    category="STAGE_DISPOSITION",
    check_name="stage10_execution_state",
    observed=str(
        stage10_row[
            "execution_state"
        ]
    ),
    expected="SEMANTIC_READBACK_VERIFIED",
)

register_final_readback_check(
    category="STAGE_DISPOSITION",
    check_name="stage10_status",
    observed=str(
        stage10_row[
            "status"
        ]
    ),
    expected="PASS_SEMANTIC_READBACK_VERIFIED",
)


# ------------------------------------------------------------
# Deletion-safe payload and tabular-index reconciliation
# ------------------------------------------------------------

EXPECTED_DELETION_SAFE_PAYLOAD_FIELDS: Final[
    dict[str, Any]
] = {
    "artifact_type": (
        "V01_DELETION_SAFE_AUTHORITY_INDEX"
    ),
    "schema_version": (
        "V01_DELETION_SAFE_AUTHORITY_INDEX_V1"
    ),
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "retained_authority_file_count": 453,
    "v0_0_retained_authority_file_count": 6,
    "v0_1_retained_authority_file_count": 447,
    "notebook10_retained_authority_file_count": 13,
    "protected_hash_only_reference_count": 7,
    "active_notebook_dependency_count": 0,
    "source_file_deletion_authorized_count": 0,
    "active_notebook_deletion_authorized": False,
    "status": (
        "PASS_PERSISTED_AWAITING_READBACK"
    ),
}

for field_name, expected_value in (
    EXPECTED_DELETION_SAFE_PAYLOAD_FIELDS.items()
):
    register_final_readback_check(
        category="DELETION_SAFE_PAYLOAD",
        check_name=field_name,
        observed=deletion_safe_payload_readback.get(
            field_name
        ),
        expected=expected_value,
    )


payload_records = deletion_safe_payload_readback.get(
    "records"
)

payload_candidates = deletion_safe_payload_readback.get(
    "notebook_deletion_candidates"
)

if not isinstance(
    payload_records,
    list,
):
    raise Notebook10FinalizationReadbackError(
        "Deletion-safe JSON authority lacks a records list."
    )

if not isinstance(
    payload_candidates,
    list,
):
    raise Notebook10FinalizationReadbackError(
        "Deletion-safe JSON authority lacks a notebook-deletion "
        "candidate list."
    )


register_final_readback_check(
    category="DELETION_SAFE_PAYLOAD",
    check_name="payload_record_count",
    observed=len(
        payload_records
    ),
    expected=453,
)

register_final_readback_check(
    category="DELETION_SAFE_PAYLOAD",
    check_name="payload_notebook_candidate_count",
    observed=len(
        payload_candidates
    ),
    expected=10,
)


required_deletion_safe_columns = {
    "record_order",
    "authority_scope",
    "authority_root",
    "artifact_origin",
    "path",
    "sha256",
    "size_bytes",
    "protected_partition_reference",
    "verification_basis",
    "retention_required",
    "source_file_deletion_authorized",
    "active_notebook_dependency",
    "status",
}

missing_deletion_safe_columns = sorted(
    required_deletion_safe_columns
    - set(
        deletion_safe_index_readback.columns
    )
)

if missing_deletion_safe_columns:
    raise Notebook10FinalizationReadbackError(
        "The deletion-safe table lacks required columns:\n"
        f"{missing_deletion_safe_columns}"
    )


register_final_readback_check(
    category="DELETION_SAFE_INDEX",
    check_name="row_count",
    observed=int(
        len(deletion_safe_index_readback)
    ),
    expected=453,
)

register_final_readback_check(
    category="DELETION_SAFE_INDEX",
    check_name="record_order_set",
    observed=set(
        pd.to_numeric(
            deletion_safe_index_readback[
                "record_order"
            ],
            errors="raise",
        ).astype(
            int
        )
    ),
    expected=set(
        range(
            1,
            454,
        )
    ),
)


deletion_safe_index_readback[
    "_retention_required"
] = deletion_safe_index_readback[
    "retention_required"
].map(
    final_readback_boolean
)

deletion_safe_index_readback[
    "_source_file_deletion_authorized"
] = deletion_safe_index_readback[
    "source_file_deletion_authorized"
].map(
    final_readback_boolean
)

deletion_safe_index_readback[
    "_active_notebook_dependency"
] = deletion_safe_index_readback[
    "active_notebook_dependency"
].map(
    final_readback_boolean
)

deletion_safe_index_readback[
    "_protected_partition_reference"
] = deletion_safe_index_readback[
    "protected_partition_reference"
].map(
    final_readback_boolean
)


for normalized_column in (
    "_retention_required",
    "_source_file_deletion_authorized",
    "_active_notebook_dependency",
    "_protected_partition_reference",
):
    if deletion_safe_index_readback[
        normalized_column
    ].isna().any():
        raise Notebook10FinalizationReadbackError(
            "Unable to normalize deletion-safe boolean column:\n"
            f"{normalized_column}"
        )


register_final_readback_check(
    category="DELETION_SAFE_INDEX",
    check_name="all_retention_required",
    observed=bool(
        deletion_safe_index_readback[
            "_retention_required"
        ].all()
    ),
    expected=True,
)

register_final_readback_check(
    category="DELETION_SAFE_INDEX",
    check_name="source_file_deletion_authorized_count",
    observed=int(
        deletion_safe_index_readback[
            "_source_file_deletion_authorized"
        ].sum()
    ),
    expected=0,
)

register_final_readback_check(
    category="DELETION_SAFE_INDEX",
    check_name="active_notebook_dependency_count",
    observed=int(
        deletion_safe_index_readback[
            "_active_notebook_dependency"
        ].sum()
    ),
    expected=0,
)

register_final_readback_check(
    category="DELETION_SAFE_INDEX",
    check_name="protected_reference_count",
    observed=int(
        deletion_safe_index_readback[
            "_protected_partition_reference"
        ].sum()
    ),
    expected=7,
)


normalized_retained_path_keys = (
    deletion_safe_index_readback[
        "path"
    ].map(
        lambda value: final_readback_path_key(
            final_readback_normalized_path(
                value
            )
        )
    )
)

register_final_readback_check(
    category="DELETION_SAFE_INDEX",
    check_name="physical_paths_unique",
    observed=bool(
        ~normalized_retained_path_keys.duplicated().any()
    ),
    expected=True,
)


payload_record_paths = {
    final_readback_path_key(
        final_readback_normalized_path(
            record[
                "path"
            ]
        )
    )
    for record in payload_records
}

table_record_paths = set(
    normalized_retained_path_keys
)

register_final_readback_check(
    category="DELETION_SAFE_INDEX",
    check_name="json_and_csv_path_sets_match",
    observed=payload_record_paths,
    expected=table_record_paths,
)


# ------------------------------------------------------------
# Reverify all 453 retained physical authorities
#
# Files are streamed for SHA-256 only. No analytical table or
# protected-partition content is parsed.
# ------------------------------------------------------------

retained_authority_verification_records: list[
    dict[str, Any]
] = []


for row_number, (_, retained_row) in enumerate(
    deletion_safe_index_readback.iterrows(),
    start=1,
):
    authority_root_label, authority_root_path = (
        final_readback_authority_root(
            retained_row[
                "authority_root"
            ]
        )
    )

    retained_path = final_readback_require_inside(
        final_readback_normalized_path(
            retained_row[
                "path"
            ]
        ),
        authority_root_path,
        role="RETAINED_AUTHORITY",
        root_label=authority_root_label,
    )

    if not retained_path.is_file():
        raise Notebook10FinalizationReadbackError(
            "A retained authority file is missing.\n"
            f"Row: {row_number}\n"
            f"Path: {retained_path}"
        )

    declared_size_bytes = int(
        retained_row[
            "size_bytes"
        ]
    )

    observed_size_bytes = int(
        retained_path.stat().st_size
    )

    if observed_size_bytes != declared_size_bytes:
        raise Notebook10FinalizationReadbackError(
            "A retained authority file changed size.\n"
            f"Row: {row_number}\n"
            f"Path: {retained_path}\n"
            f"Observed: {observed_size_bytes}\n"
            f"Declared: {declared_size_bytes}"
        )

    declared_sha256 = str(
        retained_row[
            "sha256"
        ]
    ).strip().lower()

    if re.fullmatch(
        r"[0-9a-f]{64}",
        declared_sha256,
    ) is None:
        raise Notebook10FinalizationReadbackError(
            "A retained authority has an invalid declared "
            "SHA-256.\n"
            f"Row: {row_number}\n"
            f"Path: {retained_path}"
        )

    observed_sha256 = final_readback_sha256_file(
        retained_path
    )

    if observed_sha256 != declared_sha256:
        raise Notebook10FinalizationReadbackError(
            "A retained authority physical SHA-256 changed.\n"
            f"Row: {row_number}\n"
            f"Path: {retained_path}\n"
            f"Observed: {observed_sha256}\n"
            f"Declared: {declared_sha256}"
        )

    retained_authority_verification_records.append(
        {
            "record_order": int(
                retained_row[
                    "record_order"
                ]
            ),
            "authority_scope": str(
                retained_row[
                    "authority_scope"
                ]
            ),
            "authority_root": authority_root_label,
            "path": str(
                retained_path
            ),
            "size_bytes": observed_size_bytes,
            "sha256": observed_sha256,
            "protected_partition_reference": bool(
                retained_row[
                    "_protected_partition_reference"
                ]
            ),
            "path_inside_declared_root": True,
            "file_exists": True,
            "size_matches": True,
            "sha256_matches": True,
            "status": "PASS",
        }
    )


V01_RETAINED_AUTHORITY_FINAL_READBACK_AUDIT = (
    pd.DataFrame(
        retained_authority_verification_records
    )
    .sort_values(
        "record_order",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


register_final_readback_check(
    category="RETAINED_AUTHORITY",
    check_name="verified_file_count",
    observed=int(
        len(
            V01_RETAINED_AUTHORITY_FINAL_READBACK_AUDIT
        )
    ),
    expected=453,
)

register_final_readback_check(
    category="RETAINED_AUTHORITY",
    check_name="v0_0_file_count",
    observed=int(
        V01_RETAINED_AUTHORITY_FINAL_READBACK_AUDIT[
            "authority_root"
        ].eq(
            "V0.0"
        ).sum()
    ),
    expected=6,
)

register_final_readback_check(
    category="RETAINED_AUTHORITY",
    check_name="v0_1_file_count",
    observed=int(
        V01_RETAINED_AUTHORITY_FINAL_READBACK_AUDIT[
            "authority_root"
        ].eq(
            "V0.1"
        ).sum()
    ),
    expected=447,
)

register_final_readback_check(
    category="RETAINED_AUTHORITY",
    check_name="protected_hash_only_count",
    observed=int(
        V01_RETAINED_AUTHORITY_FINAL_READBACK_AUDIT[
            "protected_partition_reference"
        ].sum()
    ),
    expected=7,
)


# ------------------------------------------------------------
# Scope-summary reconciliation
# ------------------------------------------------------------

scope_file_count_total = int(
    pd.to_numeric(
        deletion_safe_scope_summary_readback[
            "file_count"
        ],
        errors="raise",
    ).sum()
)

scope_protected_count_total = int(
    pd.to_numeric(
        deletion_safe_scope_summary_readback[
            "protected_reference_count"
        ],
        errors="raise",
    ).sum()
)

register_final_readback_check(
    category="SCOPE_SUMMARY",
    check_name="summed_file_count",
    observed=scope_file_count_total,
    expected=453,
)

register_final_readback_check(
    category="SCOPE_SUMMARY",
    check_name="summed_protected_reference_count",
    observed=scope_protected_count_total,
    expected=7,
)


# ------------------------------------------------------------
# Notebook 00–09 deletion-candidate verification
#
# Access is by Series column key. No namedtuple attributes such
# as candidate_row._stage_number are used.
# ------------------------------------------------------------

required_candidate_columns = {
    "stage_number",
    "notebook_filename",
    "path",
    "currently_exists",
    "stage_disposition",
    "authoritative_outputs_preserved",
    "active_runtime_dependency_remaining",
    "deletion_authorized",
    "deletion_performed",
    "status",
}

missing_candidate_columns = sorted(
    required_candidate_columns
    - set(
        candidate_ledger_readback.columns
    )
)

if missing_candidate_columns:
    raise Notebook10FinalizationReadbackError(
        "The notebook deletion-candidate ledger lacks required "
        "columns:\n"
        f"{missing_candidate_columns}"
    )


candidate_ledger_readback[
    "_stage_number"
] = pd.to_numeric(
    candidate_ledger_readback[
        "stage_number"
    ],
    errors="raise",
).astype(
    int
)

candidate_ledger_readback[
    "_currently_exists"
] = candidate_ledger_readback[
    "currently_exists"
].map(
    final_readback_boolean
)

candidate_ledger_readback[
    "_authoritative_outputs_preserved"
] = candidate_ledger_readback[
    "authoritative_outputs_preserved"
].map(
    final_readback_boolean
)

candidate_ledger_readback[
    "_active_runtime_dependency_remaining"
] = candidate_ledger_readback[
    "active_runtime_dependency_remaining"
].map(
    final_readback_boolean
)

candidate_ledger_readback[
    "_deletion_authorized"
] = candidate_ledger_readback[
    "deletion_authorized"
].map(
    final_readback_boolean
)

candidate_ledger_readback[
    "_deletion_performed"
] = candidate_ledger_readback[
    "deletion_performed"
].map(
    final_readback_boolean
)


for normalized_column in (
    "_currently_exists",
    "_authoritative_outputs_preserved",
    "_active_runtime_dependency_remaining",
    "_deletion_authorized",
    "_deletion_performed",
):
    if candidate_ledger_readback[
        normalized_column
    ].isna().any():
        raise Notebook10FinalizationReadbackError(
            "Unable to normalize candidate-ledger boolean "
            f"column: {normalized_column}"
        )


register_final_readback_check(
    category="NOTEBOOK_CANDIDATES",
    check_name="candidate_count",
    observed=int(
        len(candidate_ledger_readback)
    ),
    expected=10,
)

register_final_readback_check(
    category="NOTEBOOK_CANDIDATES",
    check_name="stage_number_set",
    observed=set(
        candidate_ledger_readback[
            "_stage_number"
        ]
    ),
    expected=set(
        range(
            0,
            10,
        )
    ),
)

register_final_readback_check(
    category="NOTEBOOK_CANDIDATES",
    check_name="all_outputs_preserved",
    observed=bool(
        candidate_ledger_readback[
            "_authoritative_outputs_preserved"
        ].all()
    ),
    expected=True,
)

register_final_readback_check(
    category="NOTEBOOK_CANDIDATES",
    check_name="active_dependency_count",
    observed=int(
        candidate_ledger_readback[
            "_active_runtime_dependency_remaining"
        ].sum()
    ),
    expected=0,
)

register_final_readback_check(
    category="NOTEBOOK_CANDIDATES",
    check_name="premature_authorization_count",
    observed=int(
        candidate_ledger_readback[
            "_deletion_authorized"
        ].sum()
    ),
    expected=0,
)

register_final_readback_check(
    category="NOTEBOOK_CANDIDATES",
    check_name="premature_deletion_count",
    observed=int(
        candidate_ledger_readback[
            "_deletion_performed"
        ].sum()
    ),
    expected=0,
)


retained_authority_path_keys = {
    final_readback_path_key(
        final_readback_normalized_path(
            path_value
        )
    )
    for path_value in deletion_safe_index_readback[
        "path"
    ]
}


notebook_authorization_records: list[
    dict[str, Any]
] = []


for _, candidate_row in (
    candidate_ledger_readback.sort_values(
        "_stage_number",
        kind="stable",
    ).iterrows()
):
    stage_number = int(
        candidate_row[
            "_stage_number"
        ]
    )

    notebook_filename = str(
        candidate_row[
            "notebook_filename"
        ]
    )

    notebook_path = final_readback_require_inside(
        final_readback_normalized_path(
            candidate_row[
                "path"
            ]
        ),
        FINAL_READBACK_V01_ROOT,
        role=(
            f"NOTEBOOK_{stage_number:02d}"
            "_DELETION_CANDIDATE"
        ),
        root_label="V0.1",
    )

    expected_notebook_parent = (
        FINAL_READBACK_V01_ROOT
        / "Notebooks"
    )

    if not final_readback_path_is_inside(
        notebook_path,
        expected_notebook_parent,
    ):
        raise Notebook10FinalizationReadbackError(
            "A notebook deletion candidate lies outside the "
            "V0.1 Notebooks directory.\n"
            f"Stage: {stage_number:02d}\n"
            f"Path: {notebook_path}"
        )

    normalized_notebook_path_key = (
        final_readback_path_key(
            notebook_path
        )
    )

    if (
        normalized_notebook_path_key
        in retained_authority_path_keys
    ):
        raise Notebook10FinalizationReadbackError(
            "A notebook deletion candidate is also registered as "
            "a retained authority.\n"
            f"Stage: {stage_number:02d}\n"
            f"Path: {notebook_path}"
        )

    current_exists = notebook_path.is_file()

    persisted_exists = bool(
        candidate_row[
            "_currently_exists"
        ]
    )

    if current_exists != persisted_exists:
        raise Notebook10FinalizationReadbackError(
            "A notebook deletion candidate changed existence "
            "state after final-acceptance persistence.\n"
            f"Stage: {stage_number:02d}\n"
            f"Path: {notebook_path}\n"
            f"Persisted exists: {persisted_exists}\n"
            f"Current exists: {current_exists}"
        )

    current_size_bytes: int | None = None
    current_sha256: str | None = None

    if current_exists:
        current_size_bytes = int(
            notebook_path.stat().st_size
        )

        current_sha256 = final_readback_sha256_file(
            notebook_path
        )

    deletion_required = bool(
        current_exists
    )

    deletion_authorized = bool(
        current_exists
    )

    authorization_status = (
        "AUTHORIZED_TO_DELETE_EXISTING_NOTEBOOK"
        if current_exists
        else "ALREADY_ABSENT_NO_ACTION_REQUIRED"
    )

    notebook_authorization_records.append(
        {
            "stage_number": f"{stage_number:02d}",
            "notebook_filename": notebook_filename,
            "path": str(
                notebook_path
            ),
            "persisted_exists": persisted_exists,
            "current_exists": current_exists,
            "pre_deletion_size_bytes": (
                current_size_bytes
            ),
            "pre_deletion_sha256": current_sha256,
            "authoritative_outputs_preserved": True,
            "active_runtime_dependency_remaining": False,
            "registered_as_retained_authority": False,
            "deletion_required": deletion_required,
            "deletion_authorized": deletion_authorized,
            "deletion_performed": False,
            "authorization_basis": (
                "FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED"
            ),
            "authorization_status": (
                authorization_status
            ),
            "status": "PASS",
        }
    )


V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER = (
    pd.DataFrame(
        notebook_authorization_records
    )
    .sort_values(
        "stage_number",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)


authorized_existing_notebook_count = int(
    V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER[
        "deletion_authorized"
    ].sum()
)

already_absent_notebook_count = int(
    (
        ~V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER[
            "current_exists"
        ]
    ).sum()
)


register_final_readback_check(
    category="NOTEBOOK_AUTHORIZATION",
    check_name="authorization_ledger_row_count",
    observed=int(
        len(
            V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER
        )
    ),
    expected=10,
)

register_final_readback_check(
    category="NOTEBOOK_AUTHORIZATION",
    check_name="authorized_existing_notebook_count",
    observed=authorized_existing_notebook_count,
    expected=int(
        candidate_ledger_readback[
            "_currently_exists"
        ].sum()
    ),
)

register_final_readback_check(
    category="NOTEBOOK_AUTHORIZATION",
    check_name="already_absent_notebook_count",
    observed=already_absent_notebook_count,
    expected=int(
        (
            ~candidate_ledger_readback[
                "_currently_exists"
            ]
        ).sum()
    ),
)

register_final_readback_check(
    category="NOTEBOOK_AUTHORIZATION",
    check_name="retained_authority_collision_count",
    observed=int(
        V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER[
            "registered_as_retained_authority"
        ].sum()
    ),
    expected=0,
)

register_final_readback_check(
    category="NOTEBOOK_AUTHORIZATION",
    check_name="deletion_already_performed_count",
    observed=int(
        V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER[
            "deletion_performed"
        ].sum()
    ),
    expected=0,
)


# ------------------------------------------------------------
# Gate finalization readback
# ------------------------------------------------------------

V01_NOTEBOOK10_FINALIZATION_READBACK_AUDIT = (
    pd.DataFrame(
        final_readback_checks
    )
    .sort_values(
        "check_order",
        kind="stable",
    )
    .reset_index(
        drop=True
    )
)

V01_NOTEBOOK10_FINALIZATION_READBACK_FAILURES = (
    V01_NOTEBOOK10_FINALIZATION_READBACK_AUDIT.loc[
        V01_NOTEBOOK10_FINALIZATION_READBACK_AUDIT[
            "blocking"
        ]
        & ~V01_NOTEBOOK10_FINALIZATION_READBACK_AUDIT[
            "passed"
        ]
    ]
    .copy()
)

V01_NOTEBOOK10_FINALIZATION_READBACK_WARNINGS = (
    V01_NOTEBOOK10_FINALIZATION_READBACK_AUDIT.loc[
        ~V01_NOTEBOOK10_FINALIZATION_READBACK_AUDIT[
            "blocking"
        ]
        & ~V01_NOTEBOOK10_FINALIZATION_READBACK_AUDIT[
            "passed"
        ]
    ]
    .copy()
)


if not V01_NOTEBOOK10_FINALIZATION_READBACK_FAILURES.empty:
    rendered_failures = "\n\n".join(
        (
            f"- [{row.category}] {row.check_name}\n"
            f"  observed={row.observed}\n"
            f"  expected={row.expected}"
        )
        for row in (
            V01_NOTEBOOK10_FINALIZATION_READBACK_FAILURES.itertuples(
                index=False
            )
        )
    )

    raise Notebook10FinalizationReadbackError(
        "Notebook 10 finalization readback failed:\n\n"
        f"{rendered_failures}"
    )


# ------------------------------------------------------------
# Build final readback summary
# ------------------------------------------------------------

V01_NOTEBOOK10_FINALIZATION_READBACK_SUMMARY = (
    pd.DataFrame(
        [
            {
                "metric": "scientific_terminal_class",
                "value": "FAIL",
            },
            {
                "metric": "pipeline_closeout_class",
                "value": "PASS",
            },
            {
                "metric": "finalization_manifest_file_sha256",
                "value": (
                    observed_finalization_manifest_file_sha256
                ),
            },
            {
                "metric": "finalization_manifest_sidecar_matches",
                "value": True,
            },
            {
                "metric": "finalization_manifest_semantic_sha256",
                "value": (
                    declared_finalization_manifest_semantic_sha256
                ),
            },
            {
                "metric": "finalization_manifest_artifact_count",
                "value": 11,
            },
            {
                "metric": "finalization_table_readback_count",
                "value": int(
                    len(
                        NOTEBOOK10_FINALIZATION_READBACK_TABLES
                    )
                ),
            },
            {
                "metric": "finalization_json_readback_count",
                "value": int(
                    len(
                        NOTEBOOK10_FINALIZATION_READBACK_JSON
                    )
                ),
            },
            {
                "metric": "final_readback_check_count",
                "value": int(
                    len(
                        V01_NOTEBOOK10_FINALIZATION_READBACK_AUDIT
                    )
                ),
            },
            {
                "metric": "blocking_failure_count",
                "value": 0,
            },
            {
                "metric": "nonblocking_warning_count",
                "value": int(
                    len(
                        V01_NOTEBOOK10_FINALIZATION_READBACK_WARNINGS
                    )
                ),
            },
            {
                "metric": "retained_authority_file_count",
                "value": 453,
            },
            {
                "metric": "retained_authority_hash_verified_count",
                "value": int(
                    len(
                        V01_RETAINED_AUTHORITY_FINAL_READBACK_AUDIT
                    )
                ),
            },
            {
                "metric": "v0_0_retained_authority_file_count",
                "value": 6,
            },
            {
                "metric": "v0_1_retained_authority_file_count",
                "value": 447,
            },
            {
                "metric": "protected_hash_only_reference_count",
                "value": 7,
            },
            {
                "metric": "notebook_deletion_candidate_count",
                "value": 10,
            },
            {
                "metric": "authorized_existing_notebook_count",
                "value": (
                    authorized_existing_notebook_count
                ),
            },
            {
                "metric": "already_absent_notebook_count",
                "value": (
                    already_absent_notebook_count
                ),
            },
            {
                "metric": "notebook01_currently_exists",
                "value": bool(
                    V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER.loc[
                        V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER[
                            "stage_number"
                        ].eq(
                            "01"
                        ),
                        "current_exists",
                    ].iloc[
                        0
                    ]
                ),
            },
            {
                "metric": "notebook09_currently_exists",
                "value": bool(
                    V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER.loc[
                        V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER[
                            "stage_number"
                        ].eq(
                            "09"
                        ),
                        "current_exists",
                    ].iloc[
                        0
                    ]
                ),
            },
            {
                "metric": "active_notebook_deletion_authorized",
                "value": True,
            },
            {
                "metric": "deletion_performed",
                "value": False,
            },
            {
                "metric": "accepted_model_handoff_authorized",
                "value": False,
            },
            {
                "metric": "accepted_signal_handoff_authorized",
                "value": False,
            },
            {
                "metric": "strategy_handoff_authorized",
                "value": False,
            },
            {
                "metric": "validation_content_loaded",
                "value": False,
            },
            {
                "metric": "engineering_holdout_content_loaded",
                "value": False,
            },
        ]
    )
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    V01_NOTEBOOK10_FINALIZATION_READBACK_SUMMARY
)

display(
    V01_NOTEBOOK10_FINALIZATION_ARTIFACT_READBACK_AUDIT
)

display(
    V01_NOTEBOOK10_FINALIZATION_READBACK_AUDIT
)

display(
    V01_RETAINED_AUTHORITY_FINAL_READBACK_AUDIT
)

display(
    V01_NOTEBOOK_00_TO_09_DELETION_AUTHORIZATION_LEDGER
)

if not V01_NOTEBOOK10_FINALIZATION_READBACK_WARNINGS.empty:
    display(
        V01_NOTEBOOK10_FINALIZATION_READBACK_WARNINGS
    )


# ------------------------------------------------------------
# Freeze final-readback and deletion-authorization authority
# ------------------------------------------------------------

FROZEN_NOTEBOOK10_FINALIZATION_READBACK_AUTHORITY = {
    "source_run_prefix": SOURCE_RUN_PREFIX,
    "source_set_sha256": SOURCE_SET_SHA256,
    "v0_1_run_id": V01_RUN_ID,
    "run_config_sha256": RUN_CONFIG_SHA256,
    "run_identity_sha256": RUN_IDENTITY_SHA256,
    "scientific_terminal_class": "FAIL",
    "scientific_terminal_status": (
        EXPECTED_TERMINAL_STATUS
    ),
    "pipeline_closeout_class": "PASS",
    "pipeline_closeout_status": (
        "PASS_FINALIZATION_READBACK_VERIFIED"
    ),
    "finalization_manifest_path": str(
        finalization_manifest_path
    ),
    "finalization_manifest_file_sha256": (
        observed_finalization_manifest_file_sha256
    ),
    "finalization_manifest_semantic_sha256": (
        declared_finalization_manifest_semantic_sha256
    ),
    "finalization_manifest_sidecar_path": str(
        finalization_sidecar_path
    ),
    "finalization_manifest_sidecar_matches": True,
    "finalization_artifact_readback_count": int(
        len(
            V01_NOTEBOOK10_FINALIZATION_ARTIFACT_READBACK_AUDIT
        )
    ),
    "finalization_check_count": int(
        len(
            V01_NOTEBOOK10_FINALIZATION_READBACK_AUDIT
        )
    ),
    "blocking_failure_count": 0,
    "nonblocking_warning_count": int(
        len(
            V01_NOTEBOOK10_FINALIZATION_READBACK_WARNINGS
        )
    ),
    "retained_authority_file_count": 453,
    "retained_authority_hash_verified_count": int(
        len(
            V01_RETAINED_AUTHORITY_FINAL_READBACK_AUDIT
        )
    ),
    "v0_0_retained_authority_file_count": 6,
    "v0_1_retained_authority_file_count": 447,
    "protected_hash_only_reference_count": 7,
    "notebook_deletion_candidate_count": 10,
    "authorized_existing_notebook_count": (
        authorized_existing_notebook_count
    ),
    "already_absent_notebook_count": (
        already_absent_notebook_count
    ),
    "active_notebook_deletion_authorized": True,
    "deletion_performed": False,
    "accepted_model_handoff_authorized": False,
    "accepted_signal_handoff_authorized": False,
    "strategy_handoff_authorized": False,
    "validation_content_loaded": False,
    "engineering_holdout_content_loaded": False,
    "model_refit_performed": False,
    "model_replacement_performed": False,
    "calibration_parameter_updates": 0,
    "next_authorized_operation": (
        "DELETE_ONLY_AUTHORIZED_EXISTING_NOTEBOOKS_00_TO_09"
    ),
}


# ------------------------------------------------------------
# State update
# ------------------------------------------------------------

V01_FINAL_ACCEPTANCE_READBACK_VERIFIED = True
V01_DELETION_SAFE_INDEX_READBACK_VERIFIED = True
NOTEBOOK10_FINALIZATION_MANIFEST_READBACK_VERIFIED = True
NOTEBOOK10_FINALIZATION_READBACK_VERIFIED = True

V01_ACTIVE_NOTEBOOK_DELETION_AUTHORIZED = True
V01_NOTEBOOKS_00_TO_09_DELETION_AUTHORIZED = True
V01_NOTEBOOKS_00_TO_09_DELETION_PERFORMED = False

UPSTREAM_ARTIFACTS_VERIFIED = True

V01_MODEL_SIGNAL_AUTHORIZATION_GRANTED = False
V01_STRATEGY_AUTHORIZATION_GRANTED = False
V01_V02_MODEL_HANDOFF_AUTHORIZED = False

NOTEBOOK09_EXECUTED = False
NOTEBOOK09_AUTHORIZED = False

VALIDATION_CONTENT_LOADED = False
ENGINEERING_HOLDOUT_CONTENT_LOADED = False
PROTECTED_PARTITION_CONTENT_LOADED = False

MODEL_REFIT_PERFORMED = False
MODEL_REPLACEMENT_PERFORMED = False
CALIBRATION_PARAMETER_UPDATES_PERFORMED = 0


print(
    "Notebook 10 finalization readback: PASS. The finalization "
    "manifest, SHA-256 sidecar, seven finalization tables, four "
    "JSON authorities, and all 453 retained physical authorities "
    "were independently reopened or hash-verified. The deletion-"
    "safe index contains six immutable V0.0 authorities, 447 V0.1 "
    "authorities, and seven protected hash-only references. No "
    "Notebook 00–09 deletion candidate overlaps a retained "
    "authority, and no active runtime dependency remains. "
    f"{authorized_existing_notebook_count} currently existing "
    "notebooks are authorized for exact hash-checked deletion; "
    f"{already_absent_notebook_count} candidates are already "
    "absent and require no action. Nothing was deleted in this "
    "cell. The scientific terminal state remains FAIL, the audit "
    "closeout remains PASS, and no model, signal, strategy, or "
    "accepted V0.2 model handoff is authorized."
)

                                    metric                                                             value
0                scientific_terminal_class                                                              FAIL
1                  pipeline_closeout_class                                                              PASS
2        finalization_manifest_file_sha256  37ac538b23acd00dc7d7a6ac72e616594ac34071ba9ff2dd847a563f11c7082f
3    finalization_manifest_sidecar_matches                                                              True
4    finalization_manifest_semantic_sha256  7f83da64ff0df11979b0b10b8a2e3414cf3879f6de7188131b94d97341e17efb
5     finalization_manifest_artifact_count                                                                11
6        finalization_table_readback_count                                                                 7
7         finalization_json_readback_count                                                                 4
8               final_readback_check_count                                                               137
9                   blocking_failure_count                                                                 0
10               nonblocking_warning_count                                                                 0
11           retained_authority_file_count                                                               453
12  retained_authority_hash_verified_count                                                               453
13      v0_0_retained_authority_file_count                                                                 6
14      v0_1_retained_authority_file_count                                                               447
15     protected_hash_only_reference_count                                                                 7
16       notebook_deletion_candidate_count                                                                10
17      authorized_existing_notebook_count                                                                 8
18           already_absent_notebook_count                                                                 2
19             notebook01_currently_exists                                                             False
20             notebook09_currently_exists                                                             False
21     active_notebook_deletion_authorized                                                              True
22                      deletion_performed                                                             False
23       accepted_model_handoff_authorized                                                             False
24      accepted_signal_handoff_authorized                                                             False
25             strategy_handoff_authorized                                                             False
26               validation_content_loaded                                                             False
27      engineering_holdout_content_loaded                                                             False

,variable_name,artifact_type,artifact_role,path,format,size_bytes,file_sha256,file_hash_matches,size_matches,semantic_hash_matches,uncompressed_csv_hash_matches,row_count_matches,column_count_matches,column_order_matches,status
0,V01_COMPLETION_STANDARD_FINALIZED_AUDIT,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_completion_standard_finalized_audit,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,CSV_GZIP,1612,b6e661b8a94d721556771903045766d92ee0f7e3bd55ae772457e11e8461cf74,True,True,None,True,True,True,True,PASS
1,V01_DELETION_SAFE_AUTHORITY_INDEX,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_deletion_safe_authority_index,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,CSV_GZIP,30730,4e80da817054dc9e3673fa3097ebeedfe281b889c7d2a8f705ec4a6ee9d96b7e,True,True,None,True,True,True,True,PASS
2,V01_DELETION_SAFE_AUTHORITY_INDEX_PAYLOAD,NOTEBOOK_10_DELETION_SAFE_AUTHORITY_INDEX,v01_deletion_safe_authority_index,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,JSON,549431,c944ddd3185dfcf6a7e1fd2d334d9db35be7f7177c0c72388265a24ac84a9e0c,True,True,True,None,None,None,None,PASS
3,V01_DELETION_SAFE_AUTHORITY_SCOPE_SUMMARY,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_deletion_safe_authority_scope_summary,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,CSV_GZIP,282,0a134b32ec6cb53c11381fd138e21f0ebf42d77af1c15b92b6cc8f863a52a042,True,True,None,True,True,True,True,PASS
4,V01_FINAL_DECISION_FINAL_ACCEPTANCE_PERSISTED,NOTEBOOK_10_FINALIZED_DECISION,v01_final_decision_finalized,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,JSON,2487,836fe40b19d43849e12ed92367b6d2351965f74b280c7031e8c8d83704180694,True,True,True,None,None,None,None,PASS
5,V01_FINAL_STAGE_DISPOSITION_FINALIZED,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_final_stage_disposition_finalized,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,CSV_GZIP,679,2b75fa6160fda90fae6cf2d296d583da19e26c94b825177f139dc5fcf4fe4c43,True,True,None,True,True,True,True,PASS
6,V01_NOTEBOOK10_ARTIFACT_READBACK_AUDIT,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_notebook10_artifact_readback_audit,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,CSV_GZIP,1289,7e69087dd78d92ab33c4d58c549bd9a57883a7c7f75bbc6e762d83653dcf2648,True,True,None,True,True,True,True,PASS
7,V01_NOTEBOOK10_FINAL_ACCEPTANCE,NOTEBOOK_10_FINAL_ACCEPTANCE,v01_final_acceptance,D:\Clown Project\V0.1\artifacts\manifests\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_h...,JSON,2693,e68648071f601bed4a11993d0bc56a0c89e05d2e753fab8532954872044bfd5e,True,True,True,None,None,None,None,PASS
8,V01_NOTEBOOK10_SEMANTIC_READBACK_AUDIT,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_notebook10_semantic_readback_audit,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,CSV_GZIP,2243,e0100c06e965c93daae56628ce1de61fef540bb432188dc5e84f6edc209c9dbf,True,True,None,True,True,True,True,PASS
9,V01_NOTEBOOK_00_TO_09_DELETION_CANDIDATE_LEDGER,NOTEBOOK_10_FINALIZATION_AUDIT_TABLE,v01_notebook_00_to_09_deletion_candidate_ledger,D:\Clown Project\V0.1\artifacts\audit_tables\10_v01_final_acceptance_and_deletion_safe_index\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e...,CSV_GZIP,643,3cef7cfaf393e075d0165f682ed6f6536b6ea44d06ede6fbc0fe4eb2deda86b9,True,True,None,True,True,True,True,PASS
10,V02_BOOTSTRAP_HANDOFF_FINAL_ACCEPTANCE_PERSISTED,NOTEBOOK_10_FINALIZED_V02_HANDOFF,v01_to_v02_bootstrap_handoff_finalized,D:\Clown Project\V0.1\artifacts\handoff\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__10_v01_final_audit_synthesis_and_v02_han...,JSON,23351,9ce7c88c626526d0ce56b70aad5ab907b34da71bd3a3230fd84ab911b263a443,True,True,True,None,None,None,None,PASS

,check_order,category,check_name,blocking,passed,status,observed,expected
0,1,FINAL_ACCEPTANCE,artifact_type,True,True,PASS,'NOTEBOOK_10_FINAL_ACCEPTANCE','NOTEBOOK_10_FINAL_ACCEPTANCE'
1,2,FINAL_ACCEPTANCE,schema_version,True,True,PASS,'NOTEBOOK_10_FINAL_ACCEPTANCE_V1','NOTEBOOK_10_FINAL_ACCEPTANCE_V1'
2,3,FINAL_ACCEPTANCE,source_run_prefix,True,True,PASS,'BTCUSDT_spot_20260710T063746Z_c8b5bf12','BTCUSDT_spot_20260710T063746Z_c8b5bf12'
3,4,FINAL_ACCEPTANCE,source_set_sha256,True,True,PASS,'132c83531eec615d279408b5c06f402973114ba3058dfadd2fe58e2e67184c4b','132c83531eec615d279408b5c06f402973114ba3058dfadd2fe58e2e67184c4b'
4,5,FINAL_ACCEPTANCE,v0_1_run_id,True,True,PASS,'v0_1_20260714T090616Z_e82325081a81','v0_1_20260714T090616Z_e82325081a81'
...,...,...,...,...,...,...,...,...
132,133,NOTEBOOK_AUTHORIZATION,authorization_ledger_row_count,True,True,PASS,10,10
133,134,NOTEBOOK_AUTHORIZATION,authorized_existing_notebook_count,True,True,PASS,8,8
134,135,NOTEBOOK_AUTHORIZATION,already_absent_notebook_count,True,True,PASS,2,2
135,136,NOTEBOOK_AUTHORIZATION,retained_authority_collision_count,True,True,PASS,0,0
136,137,NOTEBOOK_AUTHORIZATION,deletion_already_performed_count,True,True,PASS,0,0

,record_order,authority_scope,authority_root,path,size_bytes,sha256,protected_partition_reference,path_inside_declared_root,file_exists,size_matches,sha256_matches,status
0,1,IMMUTABLE_V00_RETAINED_AUTHORITY,V0.0,D:\Clown Project\V0.0\data\interim\BTCUSDT_spot_20260710T063746Z_c8b5bf12_visible_book_states_top_10.parquet,4958342,a59fa78b0a3ae895b4b4f5b36267b8510957e3cf8f0e6bd965402c01bbf3a860,False,True,True,True,True,PASS
1,2,IMMUTABLE_V00_RETAINED_AUTHORITY,V0.0,D:\Clown Project\V0.0\data\raw\metadata\BTCUSDT_spot_20260710T063746Z_c8b5bf12_development_manifest.json,1738,f8a3a278d6cd8b674f47d6ec1d5f4f434cb6b0d1fc05ecba609c269b5e36ffe1,False,True,True,True,True,PASS
2,3,IMMUTABLE_V00_RETAINED_AUTHORITY,V0.0,D:\Clown Project\V0.0\data\raw\metadata\BTCUSDT_spot_20260710T063746Z_c8b5bf12_session.json,1777,f7ea3210033b7e6d02d775fdc496422204194d7fd8a64a53ec926f39404e12e8,False,True,True,True,True,PASS
3,4,IMMUTABLE_V00_RETAINED_AUTHORITY,V0.0,D:\Clown Project\V0.0\data\raw\order_book\BTCUSDT_spot_20260710T063746Z_c8b5bf12_depth_updates.jsonl,63443258,608aed2608120c92fe4eaf485c43a4b26cf75d1b2120416bc29f415c87ed6c0c,False,True,True,True,True,PASS
4,5,IMMUTABLE_V00_RETAINED_AUTHORITY,V0.0,D:\Clown Project\V0.0\data\raw\order_book\BTCUSDT_spot_20260710T063746Z_c8b5bf12_snapshot.json,360812,7921a051c2483ed04e4da82c9a1f58d847eab34b4de5a9dd7d8d59d0bfd83bc4,False,True,True,True,True,PASS
...,...,...,...,...,...,...,...,...,...,...,...,...
448,449,V01_UPSTREAM_RETAINED_AUTHORITY,V0.1,D:\Clown Project\V0.1\data\processed\point_process\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION_...,295804,c639e065a4d0e63146770df90bc8d12ffa7b89bf793857e0ebaa93b03c512c1d,False,True,True,True,True,PASS
449,450,V01_UPSTREAM_RETAINED_AUTHORITY,V0.1,D:\Clown Project\V0.1\data\processed\point_process\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__04_EVENT_STREAM_CONSTRUCTION_...,569065,fbc20bb575c691f51523938de9ef69dd9729d6bcc46082375712e58737c41de3,False,True,True,True,True,PASS
450,451,V01_UPSTREAM_RETAINED_AUTHORITY,V0.1,D:\Clown Project\V0.1\data\processed\trade_book_alignment\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__03_CAUSAL_TRADE_BOOK_A...,131540683,a18f66ca6a97a66b8f42a4d61b2aa34d26bcee5ae5a8d2054e576c88beede7a3,False,True,True,True,True,PASS
451,452,V01_UPSTREAM_RETAINED_AUTHORITY,V0.1,D:\Clown Project\V0.1\data\processed\trade_book_alignment\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__03_CAUSAL_TRADE_BOOK_A...,131540683,a18f66ca6a97a66b8f42a4d61b2aa34d26bcee5ae5a8d2054e576c88beede7a3,False,True,True,True,True,PASS
452,453,V01_UPSTREAM_RETAINED_AUTHORITY,V0.1,D:\Clown Project\V0.1\logs\BTCUSDT_spot_20260710T063746Z_c8b5bf12__v0_1_20260714T090616Z_e82325081a81__08_hawkes_diagnostics_persistence_log.json,1098,222fa7c0c95af810b295cd89107816ad368d7453ef00260d8bb18253a98eb682,False,True,True,True,True,PASS

,stage_number,notebook_filename,path,persisted_exists,current_exists,pre_deletion_size_bytes,pre_deletion_sha256,authoritative_outputs_preserved,active_runtime_dependency_remaining,registered_as_retained_authority,deletion_required,deletion_authorized,deletion_performed,authorization_basis,authorization_status,status
0,00,00_V01_RUN_CONTRACT.ipynb,D:\Clown Project\V0.1\Notebooks\00_V01_RUN_CONTRACT.ipynb,True,True,"2,259,244",358d062f01b470dbcd4fd4032ed2fd11acb210b6a59c0010a1279e9abe1a8bc7,True,False,False,True,True,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,AUTHORIZED_TO_DELETE_EXISTING_NOTEBOOK,PASS
1,01,01_RAW_DATA_AUDIT.ipynb,D:\Clown Project\V0.1\Notebooks\01_RAW_DATA_AUDIT.ipynb,False,False,NaN,None,True,False,False,False,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,ALREADY_ABSENT_NO_ACTION_REQUIRED,PASS
2,02,02_VISIBLE_BOOK_RECONSTRUCTION.ipynb,D:\Clown Project\V0.1\Notebooks\02_VISIBLE_BOOK_RECONSTRUCTION.ipynb,True,True,"861,102",1aa289c71f88999d93e3c85d9d98dfd159cddce2253e5b5a3f8d935dab48e101,True,False,False,True,True,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,AUTHORIZED_TO_DELETE_EXISTING_NOTEBOOK,PASS
3,03,03_CAUSAL_TRADE_BOOK_ALIGNMENT.ipynb,D:\Clown Project\V0.1\Notebooks\03_CAUSAL_TRADE_BOOK_ALIGNMENT.ipynb,True,True,"895,207",0bd8ec9613025749a85a32e2bd681906af6f0eb8cba35b4b5bf425cf754b1abe,True,False,False,True,True,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,AUTHORIZED_TO_DELETE_EXISTING_NOTEBOOK,PASS
4,04,04_EVENT_STREAM_CONSTRUCTION.ipynb,D:\Clown Project\V0.1\Notebooks\04_EVENT_STREAM_CONSTRUCTION.ipynb,True,True,"1,479,152",e42d47c7d299e731957244d60c30f73fa0711b3577e93f4784d2ccf0267a02ac,True,False,False,True,True,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,AUTHORIZED_TO_DELETE_EXISTING_NOTEBOOK,PASS
5,05,05_MARKET_STATE_FEATURES.ipynb,D:\Clown Project\V0.1\Notebooks\05_MARKET_STATE_FEATURES.ipynb,True,True,"2,333,805",75feba59c5b23e8f692c9f457948552ab8e317fce278e84a6b0b21bdeb49e74c,True,False,False,True,True,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,AUTHORIZED_TO_DELETE_EXISTING_NOTEBOOK,PASS
6,06,06_POINT_PROCESS_BASELINES.ipynb,D:\Clown Project\V0.1\Notebooks\06_POINT_PROCESS_BASELINES.ipynb,True,True,"2,745,272",519bf6d378e825f97afd9605790084059d0a12c6993465daf4a580eff4cf1517,True,False,False,True,True,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,AUTHORIZED_TO_DELETE_EXISTING_NOTEBOOK,PASS
7,07,07_HAWKES_ESTIMATION.ipynb,D:\Clown Project\V0.1\Notebooks\07_HAWKES_ESTIMATION.ipynb,True,True,"1,658,028",8458b4f6b3f7c3a6407f2a3714ae9d956217106ebeb16e2de2865879d4910f5c,True,False,False,True,True,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,AUTHORIZED_TO_DELETE_EXISTING_NOTEBOOK,PASS
8,08,08_HAWKES_DIAGNOSTICS.ipynb,D:\Clown Project\V0.1\Notebooks\08_HAWKES_DIAGNOSTICS.ipynb,True,True,"1,996,257",53b256fcbc838adaeda9737a9e73c5e97cdcde0c8630cf6a0de1905bd64e2dec,True,False,False,True,True,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,AUTHORIZED_TO_DELETE_EXISTING_NOTEBOOK,PASS
9,09,09_INTENSITY_SIGNAL_VALIDATION.ipynb,D:\Clown Project\V0.1\Notebooks\09_INTENSITY_SIGNAL_VALIDATION.ipynb,False,False,NaN,None,True,False,False,False,False,False,FINAL_ACCEPTANCE_AND_DELETION_SAFE_INDEX_READBACK_VERIFIED,ALREADY_ABSENT_NO_ACTION_REQUIRED,PASS

Notebook 10 finalization readback: PASS. The finalization manifest, SHA-256 sidecar, seven finalization tables, four JSON authorities, and all 453 retained physical authorities were independently reopened or hash-verified. The deletion-safe index contains six immutable V0.0 authorities, 447 V0.1 authorities, and seven protected hash-only references. No Notebook 00–09 deletion candidate overlaps a retained authority, and no active runtime dependency remains. 8 currently existing notebooks are authorized for exact hash-checked deletion; 2 candidates are already absent and require no action. Nothing was deleted in this cell. The scientific terminal state remains FAIL, the audit closeout remains PASS, and no model, signal, strategy, or accepted V0.2 model handoff is authorized.